### ISSUE TITLE
Spatialite issue

### ISSUE THREAD

**Issue by hugoC1** [3liz/lizmap-web-client#1000]
Hi,

I'm using Lizmap to create an editable online map but I have issues using Spatialite layers.
Those data are not loaded with the map (they work fine in QGIS Desktop 2.18.23)

The server administrator found that in the log :
`ERROR: Too many connections: max 64
ERROR unable to initialize the SpatiaLite extension: NULL cache !!!
php-apache2handler-lizmap.XXXXX.org[25693]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":190.31000137329,"CACHE_STATUS":"off"}
php-apache2handler-lizmap.XXXX.org[25687]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":188.13705444336,"CACHE_STATUS":"off"}`

We have the issue even with the demo project 'Montpellier - Transport' that's why I think the issue has nothing to do with the creation of the database made with QGIS.

Thanks for helping,

Hugo

**Comment by josemvm** [comment]
hi @hugoC1 

take a look at https://github.com/3liz/lizmap-web-client/issues/740

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
