### ISSUE TITLE
Can't editing layers in projects (Windows)

### ISSUE THREAD

**Issue by Zargith** [3liz/lizmap-web-client#1002]
Hello!

I'm trying to setup Lizmap in a Windows server (Windows Server 2012 R2). I followed the doc about how to install Lizmap in a Windows server but actually I can access to my project but I can't edit layers on it.

I opened the consol panel in firefox to find out what was happening when I clicked on the editing layer and I got this :
`jquery-1.12.4.min.js:4 GET http://91.206.199.123/index.php/lizmap/edition/createFeature?repository=test&project=demogeopoppy&layerId=points20181026145249565&featureId= 500 (Internal Jelix Error)`

Also, in logs I got that :

> 2018-11-05 11:12:04	91.206.199.123	error	Spatialite is not available
2018-11-05 11:12:06	91.206.199.123	error	Erreur dans la requête (ERREUR:  Input geometry has unknown (0) SRID(
        WITH source AS (
         SELECT "id", "geom" AS "geosource" FROM "test"."points" WHERE True
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            'points',
            '.',
            "id") AS id,
                        ST_AsGeoJSON(ST_Transform(ST_Envelope(lg.geosource::geometry), 4326))::json As geometry,
            
                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "id"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))

> 2018-11-05 11:12:46	91.206.199.123	warning	2018-11-05 11:12:46	[2]	openlog() expects parameter 3 to be integer, string given	C:\webserver\lizmap\lib\jelix\core\log\jSyslogLogger.class.php	34
2018-11-05 11:12:48	91.206.199.123	error	2018-11-05 11:12:48	[403]	Erreur dans la requête (ERREUR:  la colonne pg_class.relhaspkey n'existe pas
LINE 1: SELECT pg_class.oid, pg_class.relhaspkey, pg_class.relhasind...
                             ^(SELECT pg_class.oid, pg_class.relhaspkey, pg_class.relhasindex FROM pg_class JOIN pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace WHERE relname = 'points' AND n.nspname = 'test'))	C:\webserver\lizmap\lib\jelix\plugins\db\pgsql\pgsql.dbconnection.php	174

I tried to found some solutions but I found nothing unfortunaly...

If some of you got any, thank a lot!

**Comment by nboisteault** [comment]
@Zargith 
Does issue still occur ?
