### ISSUE TITLE
urlengine https add a :80 on getmedia URL

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#1003]
Hi,
When I add
```
[urlengine]
checkHttpsOnParsing = off
forceProxyProtocol = https
```

on my  localconfig.ini.php all getMedia requests  have a :80 added...
Without the urlengine no modification of the url
Here are the examples:
with urlengine:
https://lizmap.sig.inra.fr:80/websig/lizmap/www/index.php/view/media/getMedia?repository=public&project=atlas_2&path=media%2Fupload%2Fentete_popup.png
without urlengine:
https://lizmap.sig.inra.fr/websig/lizmap/www/index.php/view/media/getMedia?repository=public&project=atlas_2&path=media%2Fupload%2Fentete_popup.png

**Comment by laurentj** [comment]
@jancelin did you set `forceHTTPPort = true` and `forceHTTPSPort = true`?

https://docs.lizmap.com/current/fr/install/advanced_install.html#lizmap-behind-a-proxy-reverse-proxy

**Comment by jancelin** [comment]
@laurentj 
Works with 
```
[urlengine]
checkHttpsOnParsing = off
forceProxyProtocol = https
```
and

``` forceHTTPSPort = 443```
