### ISSUE TITLE
Lizmap Print - set a minimum height for the text box

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1005]
If a user want to add a long text (for example a long description), the input in the Lizmap web client is too small. Would it be interested to have an option to change the default input to a a textarea ?

**Comment by josemvm** [comment]
hi @arno974 

you can see here about it https://github.com/3liz/lizmap-web-client/issues/426

**Comment by arno974** [comment]
Oops sorry ! Thanks @josemvm. Didn't use well the github search box...
