### ISSUE TITLE
modify the popup layer informazioni

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#1006]
How is possible modify the pop layer "informazioni"?

![info](https://user-images.githubusercontent.com/28442671/48430990-e3436b80-e770-11e8-96a0-d03dec84a30b.JPG)

thanks
Roberto

**Comment by rldhont** [comment]
If you mean updating the localization, you can do it on Transifex.

**Comment by robibrazze** [comment]
Hi, i would modify the text in bold, for example "zoom all'estensione del layer" whit
" visualizza il percorso".-
thanks 
Roberto

**Comment by danzig666** [comment]
> If you mean updating the localization, you can do it on Transifex.

I applied for hungarian translation a while ago on Transifex. I got no answer.

**Comment by rldhont** [comment]
Hi @danzig666 
Hungarian has been updated and will be available in 3_2 branch.

**Comment by nboisteault** [comment]
@robibrazze is it ok now ? Close issue if fixed.
