### ISSUE TITLE
Composer layouts not recognized at all when using QGIS3

### ISSUE THREAD

**Issue by danzig666** [3liz/lizmap-web-client#1007]
Composer layouts not recognized at all when using QGIS3.
A print button doesn't even show up in LizMap.

**Comment by Gustry** [comment]
@danzig666 Which version of Lizmap are you using?

3liz, do you confirm that only the master branch of LWC (aka 3.3) will be fully compatible with QGIS 3?

Do you have a know list of issues with QGIS 3 and Lizmap 3.2?

**Comment by danzig666** [comment]
> @danzig666 Which version of Lizmap are you using?
3.2.0
3.1.16 did not work either.

**Comment by rldhont** [comment]
@danzig666 and @Gustry the next release 3.3.0 will be designed to be fully compatible with QGIS 3. Layouts are the main point to fix in 3.3.0

**Comment by nboisteault** [comment]
Here are two prints with montpellier project made in QGIS 2.18. Only server versions differ.

[montpellier_Landscape_A4_QGIS_2.18_QGIS-Server_2.18.pdf](https://github.com/3liz/lizmap-web-client/files/2935780/montpellier_Landscape_A4_QGIS_2.18_QGIS-Server_2.18.pdf)
[montpellier_Landscape_A4_QGIS_2.18_QGIS-Server_3.4.5.pdf](https://github.com/3liz/lizmap-web-client/files/2935781/montpellier_Landscape_A4_QGIS_2.18_QGIS-Server_3.4.5.pdf)

**Comment by rldhont** [comment]
@nboisteault the PR  [Bugfix] Print with QGIS Server 3.0 and Project 2.18 #1115 fixing your example.

**Comment by nboisteault** [comment]
@rldhont : I have tested your PR. I changed QGIS version in admin to ≥ 3.0. The print is the same than it was.

**Comment by rldhont** [comment]
After changing the QGIS Server version you have to clean the vartmp to remove the cache

**Comment by nboisteault** [comment]
@rldhont : it is way better ! The only difference I see is the red rectangle above the map in the bottom right corner.
[montpellier_Landscape_A4_QGIS-Server_3.4.5-with-bugfix.pdf](https://github.com/3liz/lizmap-web-client/files/2987288/montpellier_Landscape_A4_QGIS-Server_3.4.5-with-bugfix.pdf)

**Comment by rldhont** [comment]
Yes, QGIS Server 3 does not recognize 2.18 overview definition

So it works!

**Comment by rldhont** [comment]
Fixed by [Bugfix] Parsing QGS file build with QGIS 3 for printing #1137
