### ISSUE TITLE
Please share a roadmap

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1008]
It would be good to have a public roadmap for the upcoming releases, and if possible also for the longer term development. This would make things more predictable for users and sponsors.

**Comment by rldhont** [comment]
We will use the Milestones to share a roadmap: https://github.com/3liz/lizmap-web-client/milestones
* Version 3.3.0 is already defined
* Version 4.0.0 has to be defined

**Comment by pcav** [comment]
Thanks, very useful!
