### ISSUE TITLE
Edition: uploaded picture link and https proxy

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#1009]
Hi,

My Lizmap installation (3.1.4) is on : 192.168.0.3 (80)
Lizmap is accessible from the net via an https proxy.

Links to pictures uploaded are wrong: it generates https://192.168.0.3:80... url instead of http:192.168.0.3.
Also when accessed via the https proxy.

1. How to make sure that the locally generated address is http and no https?
2. And how to make sure that when using the https proxy, the address is the same as the proxy?

Thanks in advance ;-)

**Comment by laurentj** [comment]
Hi, please configure Lizmap as indicated in the [documentation of proxy configuration](https://docs.lizmap.com/current/en/install/advanced_install.html#lizmap-behind-a-proxy-reverse-proxy). Then tell us if it's ok.

**Comment by loic74** [comment]
Thanks for your help. forceHTTPSPort  and domainName solved the problem ;-)
