### ISSUE TITLE
Touch screen sensitivity issue

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#1012]
### What is the bug?
I have a problem with touch screen and Samsung S7 or S9 terminals (not with samsung A6 for example): It is almost impossible to click on an entity to open popups, because the terminal interprets a move and not a click. Changing the sensitivity of the screen does not change anything. This problem only occurs with Chrome and Samsung Internet (not with Firefox), with glass protection or not.

### Steps to reproduce the issue
1. Use a Samsung S7 or S9
2. Open Lizmap with Google Chrome or Samsung Internet
3. Try to click on an entity

### Expected behavior
Open the popup ;-)

### Environment
 - Lizmap version: 3.1.4
 - QGis version: 2.14
 - OS: android
 - Browser: Chrome & Samsung Internet
 - Database: Postgresql

**Comment by rldhont** [comment]
Is it the same as #999 ?

**Comment by loic74** [comment]
> Is it the same as #999 ?

Yes. Sorry, I didn't find this post. But I can't check if the problem also appears with Nougat.

**Comment by nboisteault** [comment]
I let #1596 open and close this one.
