### ISSUE TITLE
Edit legend in print composer to not showing unselected layers

### ISSUE THREAD

**Issue by FIPRODEFO** [3liz/lizmap-web-client#1014]
Hi everyone,

I'm trying to make the legend in the print composer not shown the layer labels i have unselected in the project.

Have any of you had the same problem or know how to solve it?

I attach 2 images to show what i'm talking about.

Justo want to do it for a better clean looking. 

I hope i was clear. :)

![liz1](https://user-images.githubusercontent.com/45242824/48864893-9f192200-ed93-11e8-9b03-ebf1022a34c2.PNG)
![liz2](https://user-images.githubusercontent.com/45242824/48864895-9f192200-ed93-11e8-8f7c-73f2b2231c8c.PNG)

**Comment by mdouchin** [comment]
Have you tried to activate the filter icon (green funnel) in the options of the composer legend item ?

**Comment by FIPRODEFO** [comment]
Hello, thanks for answering

You mean this funnel...

![simbologia qgis](https://user-images.githubusercontent.com/45242824/48911804-6cc20000-ee39-11e8-82be-3d864ee0f46a.PNG)

Yes i did but everything stays the same, the .pdf keeps showing legen items even if they are not selected.

**Comment by FIPRODEFO** [comment]
Well, after it seems was a cache problem, using the funnel button worked.

Thanks and here is my app if you want to check it. 

http://mapsfiprodefo.net/3liz/index.php/view/map/?repository=5&project=POFMET
