### ISSUE TITLE
QGIS server 3

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#1018]
Hi! 

Thanks for a great software! I followed the instructions on installing QGIS server ltr and Lizmap and everything works well. I even tried to install QGIS server 3 using the same documentation and  din't work at all. Is there some changes I should consider when installimng QGIS srever version 3 using the documentation from: https://docs.lizmap.com/current/en/install/windows.html  ?

Thank you for your time!
BR
Abel

**Comment by danzig666** [comment]
Lizmap version 3.2.0 is mostly working on Linux (Ubuntu 18.04 LTS + QGIS server 3.4.1). Printing is not available at all, but everything else seems just fine.

**Comment by Abelon38** [comment]
Thanks for answering! 
We work with Windows server and it seems like QGIS server 3 needs more polish in order to be installed on Windows environments. We continue with QGIS server 2.18 instead. 
Have a great weekend!
Abel

**Comment by pcav** [comment]
IMHO this should be closed.

**Comment by rldhont** [comment]
@Abelon38 do you test with QGIS Server 3.4.5 ?

**Comment by Abelon38** [comment]
Hi!

I have not tested with Latest QGIS server. Last time I try it didn't work
with QGIS 3.1. Should I give it a tray with latest?
Br/ Abel

Den tis 26 feb. 2019 10:36rldhont <notifications@github.com> skrev:

**Comment by nboisteault** [comment]
@Abelon38 Did you try to install QGIS Server with [QGIS doc](https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/getting_started.html#installation-on-windows) ? Are you able to request QGIS Server without Lizmap first ?

**Comment by Abelon38** [comment]
Hi! I just tried again installing QGIS server 3.1, following the documentation from https://docs.lizmap.com/current/en/install/windows.html ?I have no idea what it may be wrong.  and I am getting error:

mod_fcgid: get overlap result error........End of script output before headers: qgis_mapserv.fcgi.exe

Any help is appreciated!

BR/Abel

**Comment by nboisteault** [comment]
@Abelon38 QGIS Server 3.1 not 3.4.5 ?

**Comment by Abelon38** [comment]
Hi!

Thanks for your time! I have tried with QGIS server 3.6.0 but nothing happend. the problem I have is not related to Lizmap, Apache is working well but I dont get respons from QGIS server when requesting http://localhost/qgis/qgis_mapserv.fcgi.exe. Should I try with QGIS doc instead? I guess it may be something wrong with php file in Apache. Mine looks like this: 

FcgidInitialEnv PHPRC "C:\\php"

FcgidInitialEnv PATH "E:\QGISserver3\OSGeo4W64\bin;E:\QGISserver3\OSGeo4W64\apps\qgis\bin;E:\QGISserver3\OSGeo4W64\apps\grass\grass-7.6.0\lib;E:\QGISserver3\OSGeo4W64\apps\grass\grass-7.6.0\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\WBem"
 FcgidInitialEnv QT_PLUGIN_PATH "E:\QGISserver3\OSGeo4W64\apps\qgis\qtplugins;E:\QGISserver3\OSGeo4W64\apps\Qt4\plugins"
 FcgidInitialEnv PYTHONHOME "E:\QGISserver3\OSGeo4W64\apps\Python37"
 FcgidInitialEnv PYTHONPATH "E:\QGISserver3\OSGeo4W64\apps\qgis\.\python;E:\QGISserver3\OSGeo4W64\apps\qgis\.\python\plugins;E:\QGISserver3\OSGeo4W64\apps\Python37\DLLs;E:\QGISserver3\OSGeo4W64\apps\Python37\lib;E:\QGISserver3\OSGeo4W64\bin;E:\QGISserver3\OSGeo4W64\apps\Python37;E:\QGISserver3\OSGeo4W64\apps\Python37\lib\site-packages"

FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0
FcgidInitialEnv QGIS_SERVER_LOG_FILE "C:\\QGISserver\\Apache24\\logs\\qgis_server.log"

FcgidIOTimeout 120
      FcgidInitialEnv LC_ALL "en_US.UTF-8"
      FcgidInitialEnv PYTHONIOENCODING UTF-8
      FcgidInitialEnv LANG "en_US.UTF-8"
      FcgidInitialEnv QGIS_DEBUG 1
      FcgidInitialEnv QGIS_SERVER_LOG_FILE "E:\\QGISserver3\Apache24\logs\\qgis_server.log"
      FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0
      FcgidInitialEnv QGIS_PLUGINPATH "E:\QGISserver3\OSGeo4W64\apps\qgis\python\plugins"

SetEnvIf Request_URI ^/qgis QGIS_PREFIX_PATH "E:\QGISserver3\OSGeo4W64\apps\qgis"
SetEnvIf Request_URI ^/qgis TEMP "E:\QGISserver3\Temp"

SetEnvIf Request_URI ^/qgis GDAL_DATA "E:\QGISserver3\OSGeo4W64\share\gdal"
SetEnvIf Request_URI ^/qgis GDAL_DRIVER_PATH "E:\QGISserver3\OSGeo4W64\bin"
SetEnvIf Request_URI ^/qgis PDAL_DRIVER_PATH "E:\QGISserver3\OSGeo4W64\bin"
SetEnvIf Request_URI ^/qgis GDAL_SKIP "JP2ECW"
SetEnvIf Request_URI ^/qgis PROJ_LIB "E:\QGISserver3\OSGeo4W64\share\proj"

 <FilesMatch \.php$>
  AddHandler fcgid-script .php
  FcgidWrapper "C:/php/php-cgi.exe" .php
 </FilesMatch>

**Comment by nboisteault** [comment]
@Abelon38 Yes try with QGIS doc.

**Comment by Abelon38** [comment]
Hi! I tryed with XAMPP according to the QGIS doc and QGIS server does work! Anyway when it comes to Lizmap I am getting som errors. No layers are been desplayed  the Lizmap map and the  Lizmap error-Logs is saying: 

::1	error	 error key E:\qgisprojekt\lindingo/lidingo.qgs, use only alphanumeric characters and the character '_' and maximum length 255

and 

::1	warning	2019-03-19 14:38:28	[2]	strpos(): Empty needle	E:\QGISserver3\lizmap32\lizmap\modules\lizmap\classes\lizmapProject.class.php	354

Any Idea?
BR/Abel

**Comment by nboisteault** [comment]
I close, please reopen if issue still occurs.
