### ISSUE TITLE
Demo in Lizmap 3.2.0

### ISSUE THREAD

**Issue by adelchia** [3liz/lizmap-web-client#1019]
In lizmap 3.2.0 web client I do not see the Montpellier Demo. 
I use QGis server 2.18.26, browse firefox, SO Ubuntu 16.04.

**Comment by rldhont** [comment]
Can you provide some logs and more information about your lizmap configuration and the way you install it ?

**Comment by rldhont** [comment]
Do you have some logs file in `lizmap/var/log`, just after installation ?

**Comment by adelchia** [comment]
Hi,
in lizmap/var/log there is nothing

root@arpab:/var/www/lizmap-web-client-3.2.0/lizmap/var/log# ls -l
totale 0

**Comment by nboisteault** [comment]
@adelchia Please test with last version and reopen issue if it sill occurs.
