### ISSUE TITLE
Unable to load the demonstration map of Montpellier after installation of LizMap Web Client

### ISSUE THREAD

**Issue by Nikeou** [3liz/lizmap-web-client#1021]
Hi,
After the installation of Lizmap Web Client, I can see the Lizmap application home page with the demo project Montpellier - Transport.
But If I want to see the map, the screen stays frozen on the loading of the data without succeeding.

Here is the contents of the lizmap-error.log file :

_[Wed Nov 28 13:57:44.261544 2018] [php7:warn] [pid 6980:tid 1992] [client ::1:53831] PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search in C:\\xampp\\lizmap\\prod_3.2.0\\lib\\jelix\\plugins\\db\\sqlite3\\sqlite3.dbconnection.php on line 112, referer: http://localhost/index.php/view/map/?repository=montpellier&project=montpellier
[Wed Nov 28 13:57:44.266530 2018] [php7:warn] [pid 6980:tid 1992] [client ::1:53831] PHP Warning:  file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found\r\n in C:\\xampp\\lizmap\\prod_3.2.0\\lizmap\\modules\\lizmap\\classes\\lizmapProxy.class.php on line 237, referer: http://localhost/index.php/view/map/?repository=montpellier&project=montpellier_

Thank's in advance if you have any idee.

**Comment by Nikeou** [comment]
Details about the installation environment ::

    Windows 10
    XAMPP installation of Apache 2.4.37
    PHP 7.2.12
    Lizmap Web Client 3.2.0

**Comment by nboisteault** [comment]
@Nikeou Do you still have this issue ?

**Comment by Nikeou** [comment]
Certainly yes.
I never found the solution so I finally stopped trying to install Lizmap, but thank you anyway.

**Comment by rldhont** [comment]
@Nikeou a point not verified, is your QGIS Server installation and configuration.
