### ISSUE TITLE
My new project doesn't appear in the repository page

### ISSUE THREAD

**Issue by Nikeou** [3liz/lizmap-web-client#1023]
Hi everyone,

As my Montpellier demo project map doesn't work (#1021), I created a new very simple project (only one shp layer) that I published in qgis via the Lizmap module.
In the administration of Lizmap I created a new repository where I stored my project.
When I ask to see this repository, no project appears in the repository page.

I tried to put my project files in the demo directory. Same thing, I only can see the project of Montpellier and not my new one...

I checked the rights on the files and everything seems ok.

I do not understand where I made a mistake. Please help to finally discover Lizmap.

Installation environment ::
Windows 10
XAMPP installation of Apache 2.4.37
PHP 7.2.12
Lizmap Web Client 3.2.0

**Comment by Nikeou** [comment]
Strange Lizmap's logs that continues to talk about the demo project (Montpellier) while it has nothing to do with what I'm trying to display...

_2018-11-30 10:32:13	::1	error	 erreur clé C:\xampp\lizmap\prod_3.2.0\lizmap\install\qgis/montpellier.qgs , limité à 255 caractères et seuls les caractères alphanumeric et le caractère '_' sont autorisés
2018-11-30 10:32:13	::1	error	Spatialite is not available_

**Comment by pcav** [comment]
Have you copied both .qgs and .qgs.cfg?

**Comment by Nikeou** [comment]
Yes I did but my project doesn't appear...
An idea ?

**Comment by pcav** [comment]
Have you given appropriate permissions to admin and anonymous?

**Comment by Nikeou** [comment]
Thank you pcav for your help and your time.

I have progressed : now I can see my project. The problem came from saving my project in qgz format instead of qgs (default extension in QGIS Madeira) !

So an other problem now : If I want to see the map, the screen stays frozen on the loading of the data without succeeding.
Here is the contents of the lizmap-error.log file (my project's name is "rando"):

_[Fri Jan 04 09:57:22.256730 2019] [php7:warn] [pid 6364:tid 1964] [client ::1:53267] PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search in C:\\xampp\\lizmap\\prod_3.2.0\\lib\\jelix\\plugins\\db\\sqlite3\\sqlite3.dbconnection.php on line 112, referer: http://localhost/index.php/view/map/?repository=rep1&project=rando_

It looks like a connection problem to sqlite, whereas my source data is in a shp file and not in a sqlite database...

**Comment by rufuscorp** [comment]
I can see the same error with:
`no such table: lizmap_search`
 lizmap 3.2.2 on debian stretch freshly install, with qgis server 3.4. 

Only base layer with Montpellier appear, and no layer with another qgis project . I can't see the data too.
I've install the 3.1.12 on the same server, and it works: i can see layer and data.

It seem there's a problem with the 3.2.2 version.

**Comment by nboisteault** [comment]
@rufuscorp `lizmap_search` is not important. Can try again with 3.2.4 ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
