### ISSUE TITLE
child objets in popup with QGIS server 3

### ISSUE THREAD

**Issue by ddespres** [3liz/lizmap-web-client#1024]
### What is the bug?
with QGIS Server 3, childs elements are not displayed in the popup  of the lizmap client.
The response of the second GetFeatureInfo request (for the childs) is empty.

### Environment

 - Lizmap version: 3.2rc6
 - QGis version: 3.2
 - QGIS Server version: docker => 3liz/qgis-map-server:1.1
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...):
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?

**Comment by nboisteault** [comment]
I can confirm that. I found that GetFeatureInfo request for child objects doesn't have the CRS parameter which is mandatory with QGIS 3. Fix coming.
