### ISSUE TITLE
 How to retrieve a field value after the entity has been saved

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#1025]
How to retrieve the value of a field after the entity has been saved?

I need to execute a script if a box is checked in a form (or maybe if the value saved in the field is equal to "t", or "TRUE"...), and after the entity has been saved.

Here is my code:
```
var formPrefix = 'jforms_view_edition';
var champSIG = 'integration_sig';
   
lizMap.events.on({
	'lizmapeditionfeaturecreated': function(e){
		var sig = $('#' + formPrefix + '_' + champSIG );
		if (sig.is(':checked')) {
                   $.get("http://192.168.0.6/wekan.php");
		}
	}
});
```

The conditionnal statement does not work...

**Comment by nboisteault** [comment]
@loic74 Can you provide a public link showing your issue ?

**Comment by loic74** [comment]
I think I found the problem. lizmapeditionfeaturecreated does not allow to retrieve the values of the form because it is closed. It would require a beforelizmapeditionfeaturecreated event.

Am I right?
