### ISSUE TITLE
Error when editing PostGIS layer (LM 3.2)

### ISSUE THREAD

**Issue by hoge6b01** [3liz/lizmap-web-client#1026]
Hello.
I've got a freshly Lizmap 3.2 installation. I can display PG-Layers but I cannot edit them. My setting is:

Ubuntu Server 18.04.1
PostgreSQL 10.6
Apache2
Lizmap 3.2
PHP 7.2

I followed this documentation [https://docs.lizmap.com/current/en/index.html](https://docs.lizmap.com/current/en/index.html) with all extension mentioned installed. 

I can see the PG layer but when editing I get the following error log in Chrome's developer tools:

_Failed to load resource: the server responded with a status of 500 (Internal Jelix Error)
Error 500. A technical error has occured. Sorry for this trouble.
jquery-1.12.4.min.js:4_ 

Looking into Lizmap's error logs I get:

_2018-12-10 11:38:08	80.149.89.58	error	2018-12-10 11:38:08	[402]	Fehler während der Verbindung '<here's my servers ip>'	/var/www/lizmap-web-client-3.2.0/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	153_

(Fehler während der Verbindung = German for 'Error during Connection')

I have nothing added to profiles.ini or localconfig.ini

Any hints how to attack this issue?
Thanks!!

**Comment by hoge6b01** [comment]
By the way, the connection string in the .qgs file is:

      _<datasource>dbname='postgis' host='<here's my servers ip>' port=5678 user='<user>' password='<password>' sslmode=disable key='id' srid=3857 type=Polygon 'key='id' table="bike"."iso_vrs_db_edit" (geom) sql=</datasource>_

It's not in the public schema. Does this cause any unexpected behavior?

**Comment by hoge6b01** [comment]
I found this in the .cfg file. Maybe something is missing?
Do I have to change mit profiles.ini file?

`    "editionLayers": {
        "iso_vrs_db_edit": {
            "layerId": "iso_vrs_db_edit_f8a99ef9_2e50_40da_8b8a_036a8f9aefa3",
            "geometryType": "polygon",
            "capabilities": {
                "createFeature": "True",
                "modifyAttribute": "True",
                "modifyGeometry": "True",
                "deleteFeature": "True"
            },
            "acl": "",
            "order": 0
        }
    }`

**Comment by hoge6b01** [comment]
Updated to 3.2.1 - nothing changes. Does anyone has a example of profiles.ini to get a postgis connection?

**Comment by hoge6b01** [comment]
Could someone please give a hint how to debug this problem? Thanks

**Comment by rldhont** [comment]
QGIS needs a key as an integer to identify feature.

If the key is not an integer, each QGIS Server build it's own integer key so each QGIS Server can identify a feature with a different key.

**Comment by hoge6b01** [comment]
thanks. I'll close this now.
