### ISSUE TITLE
Edition does not work with PostgreSQL 11

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#1028]
It is impossible to edit or add a new feature in a layer with the Editing tool if the PostgreSQL version is >= 11. PostgreSQL returns the following error (visible in `lizmap/var/log/error.log` )

```bash
RROR:  column pg_class.relhaspkey does not exist
LINE 1: SELECT pg_class.oid, pg_class.relhaspkey, pg_class.relhasind...
                             ^(SELECT pg_class.oid, pg_class.relhaspkey, pg_class.relhasindex FROM pg_class JOIN pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace WHERE relname = 'DLOG_NETTOYAGE_LOCAUX' AND n.nspname = 'patrimoine'))	/srv/lizmap-web-client/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174
```

It appears PostgreSQL 11 has changed the system tables. See:
https://github.com/bucardo/bucardo/commit/2358ada04637c57ca39163f2053614e140c0504b

We need to either
* add a try catch to handle both cases
* get the PostgreSQL version via `SELECT version();` and then use the correct SQL

@rldhont @dmarteau @nboisteault

**Comment by mdouchin** [comment]
@laurentj je pense que ceci suffirait. A tester sur PostgreSQL v9.5 à v11

```diff
diff --git a/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php b/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php
index 1142d213..7aece038 100644
--- a/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php
+++ b/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php
@@ -226,11 +226,12 @@ class pgsqlDbTools extends jDbTools {
         $tableName = $this->_conn->prefixTable($tableName);
 
         // get table informations
-        $sql ='SELECT pg_class.oid, pg_class.relhaspkey, pg_class.relhasindex';
+        $sql ='SELECT pg_class.oid, coalesce(i.indisprimary, false) as relhaspkey, pg_class.relhasindex';
         $sql.=' FROM pg_class';
         if(!empty($schemaName)){
             $sql.= ' JOIN pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace';
         }
+        $sql.=' LEFT JOIN pg_index i ON (indrelid = pg_class.oid AND indisprimary)';
         $sql.=' WHERE relname = \''.$tableName.'\'';
         if(!empty($schemaName)){
             $sql.= ' AND n.nspname = \''.$schemaName.'\'';

```

**Comment by mdouchin** [comment]
@laurentj @rldhont I just push a quickfix in branch release_3_2, tested against PostgreSQL 9.6, 10 and 11 . We would need to use jDbSchema in future

**Comment by rldhont** [comment]
Commit 75108dba3ee73959fe7e13a3a694fd8cb98db131
close if it fix the issue

**Comment by laurentj** [comment]
Tested with Postgresql 9.4: it's ok. I confirm also it's ok with 9.6. Your patch has been backported to Jelix 1.6. Thank you :)
