### ISSUE TITLE
DELETE BOTTOM "REPOSITORIES" ONLY IN REPO X

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#1037]
Hi, how is possible delete or disable the botton "repositories"  only in one repo ?
Thanks

rb

**Comment by laurentj** [comment]
Hi,

which button do you talk about? Where is it?

**Comment by robibrazze** [comment]
Hi,
below insert screenshot
![repositories](https://user-images.githubusercontent.com/28442671/50835641-8ec70180-1357-11e9-8d3f-36533f0adacc.PNG)

**Comment by laurentj** [comment]
In the configuration of Lizmap, if you set "Only maps" to "on", the "home" button does nothing when a map is displayed.

**Comment by nboisteault** [comment]
Hi, you can [disable with CSS](https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#creating-simple-themes).

**Comment by nboisteault** [comment]
@robibrazze did you try CSS ?

**Comment by robibrazze** [comment]
Hi, sorry for the late, i try whit the js and it work:
lizMap.events.on({
  uicreated: function(e) {
    console.log("lizmap.on");
    var element = document.getElementById("button-home");
    console.log(element);
    element.parentNode.removeChild(element);
  }
});

**Comment by nboisteault** [comment]
@robibrazze thanks for your feedback.
