### ISSUE TITLE
Search location with Nominatim does not work

### ISSUE THREAD

**Issue by cimbach** [3liz/lizmap-web-client#1039]
Ubuntu desktop 18.04
QGIS Server 3.4.2
QGIS 3.4.2
Lizmap plugin 3.0.0
Lizmap Web Client 3.2.0

Since Google is no more a free option, I would like to switch to the OSM Nominatim location search.
From what I see, all I have to do is select 'Nominatim' in the Address search drop down menu of the Lizmap plugin. Right?

When doing so all the result I get after a query is a blank black area with a Search title on top and a close button that does not work.

The Chromium DevTools shows the following URL:
_http://127.0.0.1/lm/index.php/lizmap/osm/nominatim?query=lausanne%2C+gare&bbox=6.421448%2C46.42268%2C6.87698%2C46.681958_

The GET method has a 200 OK status for getting a nominatim.json file of 0 length.

Copying the above URL as a Curl one, I get:
_curl 'http://127.0.0.1/lm/index.php/lizmap/osm/nominatim?query=lausanne%2C+gare&bbox=6.421448%2C46.42268%2C6.87698%2C46.681958' -H 'Cookie: PHPSESSID=lujh7i5ujpfiodn17vu18bu30v' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.80 Chrome/71.0.3578.80 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://127.0.0.1/lm/index.php/view/map/?repository=surf&project=20180901_surface_liz' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --compressed_

Pasting it into a terminal does not trigger anything.

Looking at the Lizmap errors.log, this is showing up at the web client startup:
_127.0.0.1	warning	2018-12-21 14:43:11	[2]	SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search	/var/www/lizmap-web-client/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	112_

sqlite3.dbconnection.php is there though with a size of 4.9KB

Then when launching a location search, the following error appears in the log:
 _127.0.0.1	warning	2018-12-21 14:52:01	[2]	file_get_contents(https://nominatim.openstreetmap.org/search.php?q=lausanne%2C+gare&amp;format=json&amp;viewbox=6.421448%2C46.42268%2C6.87698%2C46.681958): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
	/var/www/lizmap-web-client/lizmap/modules/lizmap/classes/lizmapProxy.class.php	237_

Any idea what I did wrong?

Let me know if you need more info.

**Comment by rldhont** [comment]
Has been fixed in 3.2.1 https://github.com/3liz/lizmap-web-client/releases/tag/3.2.1
by the commit 13c06462a7ed8a8b72801a343c5c5f725c3b9afe

Can you update your version, test it and provide feedbacks ?

**Comment by cimbach** [comment]
Wow that was fast, thanx a lot!
No problem to update to 3.2.1 and test it, but I am afraid that will be in two weeks only.

**Comment by pcav** [comment]
Confirmed: upgraded to 3.2.1, Nominatim works
