### ISSUE TITLE
Error BaseLayer Bing - ImagerySet not supported

### ISSUE THREAD

**Issue by Cesaaar** [3liz/lizmap-web-client#1042]
### What is the bug?
Is not possible to use the Bing basemap.

### Steps to reproduce the issue
1. Add BaseMap Bing with Valid Key
2. Open the map
4. Lizmap doesn't show Bing base map
5. See the error on Javascript console: **"imagerySet: This parameter value has an invalid format."**

### Environment
 - Lizmap version: 3.2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): Ubuntu 18.04
 - Browser (Firefox, Chrome...): Chrome
 
Andrea

**Comment by Cesaaar** [comment]
For example now ImagerySet = **bhybrid**, but correct ImagerSet are reported in https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata, for example: **Aerial**.

- As Is: https://dev.virtualearth.net/REST/v1/Imagery/Metadata/bhybrid?key=[API_KEY]&jsonp=_callback_OpenLayers_Layer_Bing_22&include=ImageryProviders

- To Be: https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?key=[API_KEY]&jsonp=_callback_OpenLayers_Layer_Bing_22&include=ImageryProviders

**Comment by Cesaaar** [comment]
I used GDAL as a workaround

https://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/OpenStreetMap-Tiles-in-QGIS

**Comment by rldhont** [comment]
We need to update lizmap.

**Comment by igeofr** [comment]
I have a problem with Bing that I think is related to the changes (only hybrid and road) .

`Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://ak.dynamic.t3.tiles.virtualearth.net`

`Raison : échec de la requête CORS.`

### Environment
* Lizmap version: 3.2.2
* QGIS version: 2.18

**Comment by robibrazze** [comment]
> I used GDAL as a workaround
> 
> https://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/OpenStreetMap-Tiles-in-QGIS

Hi Cesaaar,
do yuo can show your tms whit work fine using bing map?

thanks
Roberto
