### ISSUE TITLE
Cannot create local user on system with LDAP integration

### ISSUE THREAD

**Issue by signedav** [3liz/lizmap-web-client#1049]
### What is the bug?
When I have installed LDAP Authentification I cannot create a local user anymore.

### Steps to reproduce the issue
Installed LDAP like this https://github.com/3liz/lizmap-web-client/issues/1001#issuecomment-453025806
1. Login with admin/admin (local admin user)
2. Activate the right to create user (click on "admin" -> "My account", then on the left to "Rights of users" and select the "rights" button of _admin_
![image](https://user-images.githubusercontent.com/28384354/50958827-db2e5080-14c1-11e9-9dcf-d0754f5ad3fe.png)
Here I set the options to "yes" instead of "no"
And I press "save"
3. Select on the left "Users"
And I find the button "Create a new user" (that was not visible before) - I choose it and I enter the user data like this:
![image](https://user-images.githubusercontent.com/28384354/50959191-ae2e6d80-14c2-11e9-83ad-1e9c9f4629c6.png)
And I press "Save"
**Error 500 appears. Page could not be displayed.**
![image](https://user-images.githubusercontent.com/28384354/50959132-86d7a080-14c2-11e9-85ec-07755bad9aee.png)

### Expected behavior
Local user "testuser" will be created.

### Environment
Lizmap: 3.1.12
On:
```
root@test_lizmap:/# lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie
```

**Comment by laurentj** [comment]
We don't support creation of ldap users, this is why the right "Activate the right to create user" is off.

**Comment by signedav** [comment]
I don't want to create a user on the AD, but a local Lizmap user. Is it not possible to use both kind of authentication simultaneously?

**Comment by signedav** [comment]
Okay. Thanks for the information. When is it planned to be improved? Are you looking for sponsors?

**Comment by laurentj** [comment]
I just finished to develop a module, [multiauth](https://github.com/jelix/multiauth-module), that will replace ldapdao and which allow to have both, ldap users and database users.

It will replace ldapdao into Lizmap 3.3 ;-). It will be possible to use it into Lizmap 3.2 when #1066 will be accepted, but it will be an experimental feature.

**Comment by rmarzocchi84** [comment]
> I just finished to develop a module, [multiauth](https://github.com/jelix/multiauth-module), that will replace ldapdao and which allow to have both, ldap users and database users.
> 
> It will replace ldapdao into Lizmap 3.3 ;-). It will be possible to use it into Lizmap 3.2 when #1066 will be accepted, but consider this as an experimental feature into Lizmap 3.2.

what about LWC 3.4?  I try to install ldapdao but it doesn't work. See https://github.com/3liz/lizmap-web-client/issues/2276

**Comment by josemvm** [comment]
> what about LWC 3.4? I try to install ldapdao but it doesn't work

with multiauth module and as admin user i can create users without problems
