### ISSUE TITLE
Bad display of top menu bar on mobile

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1051]
### What is the bug?

With low width screen, the top menu bar display icons and item text, except in the map view mode.

### Steps to reproduce the issue

1. With Firefox > Developpement web > vue adpatative, select a little width for the page
2. go the project page or an administration page
3. see that item text are still shown, and overflow the menu bar.

![lizmap_mobile_menu_overflow](https://user-images.githubusercontent.com/336034/50962107-cd7cc900-14c9-11e9-856d-a2b639d34659.png)

### Expected behavior

We should see only icons, so it doesn't overflow the menu bar.

![lizmap_mobile_menu_ok](https://user-images.githubusercontent.com/336034/50962458-9529ba80-14ca-11e9-90ab-6adbfa563eaa.png)

### Environment

 - Lizmap version:  3.2
 - OS : kubuntu 
 - Browser : Firefox

**Comment by nboisteault** [comment]
@laurentj do you think logged name should also be hidden ?

**Comment by laurentj** [comment]
@nboisteault yes

**Comment by laurentj** [comment]
we could open a new issue, to hide the search field on tiny screen. We could have instead a button in the menu, that open a dialog box showing the search field.

**Comment by rldhont** [comment]
@laurentj agree with you.

**Comment by nboisteault** [comment]
Working on search bar.
