### ISSUE TITLE
Eternal loading after successful login

### ISSUE THREAD

**Issue by signedav** [3liz/lizmap-web-client#1053]
### What is the bug?
Sometimes it hangs on login with the admin account. It's loading eternal. After reentering the address it's successfully logged in.

### Steps to reproduce the issue
Installed LDAP like this https://github.com/3liz/lizmap-web-client/issues/1001#issuecomment-453025806
1. Login with admin/admin (local admin user) and it's loading eternal (sometimes, not always)
2. I refresh the page and I get an error **_ERR_TO_MANY_REDIRECTS_**
3. I enter http://localhost (domain of lizmap) and I'm successfully logged in

I did not delete my cookies and cannot reproduce the error again anyway. But as soon as I can, I will check for more log messages. Anyway I guess the issue with **_ERR_TO_MANY_REDIRECTS_** is because of the refresh of the login mask and not the problem here. The problem here is that it hangs there and should go on...

### Expected behavior
Coming to the map repositories.

### Screenshots and logs
After refresh:
![login_error_02](https://user-images.githubusercontent.com/28384354/51187032-3eade900-18db-11e9-9ffd-367565a70c86.png)

### Environment
Lizmap: 3.1.12
On:
```
root@test_lizmap:/# lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie
```

**Comment by Gustry** [comment]
@laurentj Is-it a issue in Jelix exclusively? Should we transfer the ticket on Jelix repository? 
Or is-it a bug in Lizmap?

**Comment by signedav** [comment]
There have been several updates on this customer system meanwhile, and I haven't noticed the issue anymore. But I cannot say what changed it. Thanks anyway and keep on the good work.
