### ISSUE TITLE
LDAP authentification with empty password possible

### ISSUE THREAD

**Issue by signedav** [3liz/lizmap-web-client#1057]
I'm still on the LDAP authentification I actually everything seems to work fine beside this issue #1053 and that it's possible to login without a password:

- correct username / correct password -> accepted (expected)
- correct username / incorrect password -> rejected (expected)
- correct username / empty password -> accepted (wrong behavior)

So this solution is unusable, since you can login as anyone you want. Anyway I'm not sure if it's a problem on the Lizmap implementation, on the configuration on the Active Directory or in my own Lizmap setup.

I installed LDAP like this https://github.com/3liz/lizmap-web-client/issues/1001#issuecomment-453025806 and with the profile settings of the test AD system everything works fine but with the settings of the real AD system the mentioned behavior occurs.

### Working tests settings in `/var/www/websig/lizmap/var/config/profiles.ini.php`:
```
[ldap:myldap]
hostname = ldap.forumsys.com
port = 389
adminUserDn = "cn=read-only-admin,dc=example,dc=com"
adminPassword = "password"
searchUserBaseDN = "dc=example,dc=com"
searchUserFilter = "(&(objectClass=*)(uid=%%LOGIN%%))"
bindUserDN = "uid=%?%,dc=example,dc=com"
searchAttributes="uid:login,firstname,sn:lastname,mail:email,dn:"
```

### Not working productive settings in `/var/www/websig/lizmap/var/config/profiles.ini.php`:
(I had to "anonymize" the values)
```
[ldap:myldap]
hostname = company.network
port = 389
adminUserDn="cn=adminaccount,ou=admins,ou=users,dc=company,dc=network"
adminPassword="password"
searchUserBaseDN = "dc=company,dc=network"
searchUserFilter = "(&(objectClass=*)(sAMAccountName=%%LOGIN%%))"
bindUserDN="$distinguishedName"
searchAttributes="sAMAccountName:login,givenName:firstname,sn:lastname,mail:email,distinguishedName:"
```

According to the RFC for LDAP https://tools.ietf.org/html/rfc4513#section-5.1.2 it's written: 
>    The distinguished name value provided by the client is intended to be
   used for trace (e.g., logging) purposes only.  The value is not to be
   authenticated or otherwise validated (including verification that the
   DN refers to an existing directory object).  The value is not to be
   used (directly or indirectly) for authorization purposes.
   Unauthenticated Bind operations can have significant security issues
   (see Section 6.3.1).  In particular, users intending to perform
   Name/Password Authentication may inadvertently provide an empty
   password and thus cause poorly implemented clients to request
   Unauthenticated access.  Clients SHOULD be implemented to require
   user selection of the Unauthenticated Authentication Mechanism by
   means other than user input of an empty password.  Clients SHOULD
   disallow an empty password input to a Name/Password Authentication
   user interface.  Additionally, Servers SHOULD by default fail
   Unauthenticated Bind requests with a resultCode of
   unwillingToPerform.

Thanks for your help!

**Comment by signedav** [comment]
Good morning @laurentj I wonder if there is kind of a `AllowEmptyPassword` setting on the ldapdao module implementation? Because this would avoid the problem. Or is that more the general GUI part in Lizmap?

According to the RFC the distinguished name should not be used as authentication, what I do at the customers system. But this is AFAIK the only way it works there. And btw. when I would use `bindUserDN="sAMAccountName=%?%,dc=company,dc=network"` it's not possible with the correct password but still with an empty password.

**Comment by signedav** [comment]
Regarding my question above. A "dirty" hack would be to add here https://github.com/jelix/ldapdao-module/blob/master/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php#L175 something like this:
```
if( $this->_params['dontAllowEmptyPassword'] && !$password ) {
     return false;
}
```
and then here `vim /var/www/websig/lizmap/var/config/profiles.ini.php`:
```
[ldap:myldap]
dontAllowEmptyPassword=1
```
But since I'm neither a lizmap nor a ldapdao developer I don't arrogate the right to tell you what has to be done in the code.

**Comment by laurentj** [comment]
Fixed. Thank you :-)
