### ISSUE TITLE
Adding link to a popup points to the same project

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1058]
When adding a popup of this type:
```
<b>[% "name" %]</b><br>
[% "notes" %] <a href="[% "link" %]" target="_blank">Info</a>

```
the result is whet expected if the field "link" is correctly filled up. If empty, however, it points to he same lizmap project.
See an example:
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=sail&layers=B00TTTTT&bbox=895381.792358%2C4988921.335403%2C932797.717698%2C5020719.139166&crs=EPSG%3A3857

**Comment by blaisegeo** [comment]
Hi pcav;
Can you elaborate a bit more your solution please, as I'm facing the same problem.
Thanks

**Comment by pcav** [comment]
I have used `CASE WHEN fiieldname IS NOT NULL` to display the field.

**Comment by rldhont** [comment]
@pcav lizmap can't really fix your explain issue. If the popup contains a link without explicit link the browser automatically points to the page, like when the link is an anchor.

I think it's a documentation issue.

**Comment by pcav** [comment]
ot it, thanks.
