### ISSUE TITLE
QGIS Server 3.4.4 does not show the map anymore

### ISSUE THREAD

**Issue by hoge6b01** [3liz/lizmap-web-client#1059]
### What is the bug?
Since update to QGIS Server 3.4.4 the map layers aren't displayed any longer.
Data is there because popups show content of features but no geometries are shown.

URL to map image returns:
OperationNotSupported">Please check the value of the REQUEST parameter

### Screenshots and logs
![image](https://user-images.githubusercontent.com/5871910/51474066-6ccd7600-1d7e-11e9-8ba6-6f3019f8067a.png)

### Environment

 - Lizmap version: 3.2.1
 - QGis version: 3.4.4
 - OS: Ubuntu Server 18.04
 - Browser: any
 - Lizmap data stored into Postgresql

**Comment by laurentj** [comment]
Lizmap 3.2 is not compatible with Qgis 3. Lizmap 3.3 will be compatible (but the actual lizmap 3.3pre is not ready yet).

**Comment by mbernasocchi** [comment]
@laurentj this is an issue in QGIS server, 3.4.5 solves it

**Comment by pcav** [comment]
Confirmed, it works also in QGIS 3.6

**Comment by rldhont** [comment]
thanks to @elpaso for the multiple QGIS Server bufixing

**Comment by jhcardoso** [comment]
@pcav when you say qgis 3.6 you mean desktop or server?

**Comment by pcav** [comment]
Desktop. Sorry for the missing detail.

**Comment by cxc61cxc** [comment]
Hi, i still have this issue on QGIS LTR 3.4.13 postgresql do not show any layer 
All is working on 3.10.0-A Coruña
Thanks

**Comment by paolomartinis** [comment]
same problem, ubuntu 18.04 lizmap 3.3.2 and qgis server 3.10.9. data is there, if you click on it it is selected and queried but it is not rendered...
it was working with qgis server 3.4

**Comment by nboisteault** [comment]
@paolomartinis Please update Lizmap to last version.

**Comment by paolomartinis** [comment]
> @paolomartinis Please update Lizmap to last version.

it is working now, really thanks
