### ISSUE TITLE
pg_close(): supplied resource is not a valid PostgreSQL link resource

### ISSUE THREAD

**Issue by hoge6b01** [3liz/lizmap-web-client#1060]
### What is the bug?
Although Lizmap and PG is working fine I constantly get the following error in the Lizmap log:
[2]	pg_close(): supplied resource is not a valid PostgreSQL link resource	/var/www/lizmap-web-client-3.2.1/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	166

### Environment

 - Lizmap version: 3.2.1
 - QGis version: 2.18
 - OS): Ubuntu Server 18.04
 - Lizmap data stored into Postgresql?

**Comment by laurentj** [comment]
It should be fixed by the upgrade of Jelix made into c0ee8f6df0e1d0a9165f60045913d153e7893fd2
