### ISSUE TITLE
Minidock popup with wrong dimensions

### ISSUE THREAD

**Issue by tethysgeco** [3liz/lizmap-web-client#1065]
@pcav 

### What is the bug?
Sometimes (apparently with no logic) the popup (minidock type) has wrong size with respect to the content of compiled fields (both using Chrome and Mozilla Firefox - see pictures for examples). Do you have ever experienced something similar and have any idea of the reasons?  
![1](https://user-images.githubusercontent.com/23027624/51912961-cca6cb00-23d5-11e9-90cc-9773021c7def.JPG)
![2](https://user-images.githubusercontent.com/23027624/51912962-cd3f6180-23d5-11e9-86b9-1494fef6fcb9.JPG)
![immagine](https://user-images.githubusercontent.com/23027624/51969490-d3d0e600-2474-11e9-9d0b-5d69c5052187.png)

### Environment

 - Debian 6.3.0
 - Lizmap version: 3.2
 - QGis version: 2.18.25
 - Postgresql 9.6.10

**Comment by rldhont** [comment]
@tethysgeco can you test PR #1117 ? thanks

**Comment by rldhont** [comment]
@nboisteault ok, can you create a pull request ?

**Comment by tethysgeco** [comment]
Sorry for the late reply.
We have just had time to test the improvement and we can confirm that minidock popup works properly.
Thank you very much for your work.
