### ISSUE TITLE
jelix upgrade

### ISSUE THREAD

**Issue by manasa-maddi** [3liz/lizmap-web-client#1067]
Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown.

**Comment by rldhont** [comment]
Can you be more precise about the lizmap versions ?

**Comment by laurentj** [comment]
@manasa-maddi which version of Lizmap please?

**Comment by laurentj** [comment]
@manasa-maddi and how did you do the upgrade ? which steps have you done?
