### ISSUE TITLE
popup - used once, allways remains activated 

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1068]
when you do a click on the map the popup displays the contents of features and highlights them like you can see as below:

![imagem](https://user-images.githubusercontent.com/10053874/52183769-43dbc500-2803-11e9-8583-ff02aff4049d.png)

after you close the popup window and select some features using any selection method/tool (case selection tool, by circle):

![imagem](https://user-images.githubusercontent.com/10053874/52184135-58ba5780-2807-11e9-851b-3c7931353aa3.png)

the last/previous highlighted geometries by popup come back to the map:

![imagem](https://user-images.githubusercontent.com/10053874/52184181-d4b49f80-2807-11e9-9e3f-772afe5f347f.png)

lizmap master and previous
qgis server 2.14 e 2.18

thanks

**Comment by rldhont** [comment]
I am working one.

**Comment by josemvm** [comment]
thanks @rldhont :-)

**Comment by rldhont** [comment]
@josemvm can you test and review #1117 ? thanks
