### ISSUE TITLE
0 is like null

### ISSUE THREAD

**Issue by gcalibris** [3liz/lizmap-web-client#1069]
In postgresql table I have the field temperatura with type integer and with NOT NULL.
In this field from QGIS program I can write the temperature value equal to 0, but from lizmap I can't write the value 0.

The log is: An error has been raised when saving form data edition to db : invalid query (ERROR:  null value in column "temperatura" violates not-null constraint.

software
qgi project from 2.18 qgis
lizmap web client 3.2.1
qgis-server 2.18.27+24xenial

Somebody can help for this issue?

**Comment by rldhont** [comment]
@gcalibris can you test https://github.com/3liz/lizmap-web-client/pull/1111 or actual release_3_2 branch ?

**Comment by rmarzocchi84** [comment]
I have the same problem using
- QGIS server 3.4.8 
- dev lizmap release (git pull from repository today) 

In my case I have a value map on QGIS for a not boolean field which cannot be a boolean.
The QGIS project seem OK
```


          <editWidget type="ValueMap">
            <config>
              <Option type="Map">
                <Option name="map" type="List">
                  <Option type="Map">
                    <Option value="0" name="No" type="QString"/>
                  </Option>
                  <Option type="Map">
                    <Option value="1" name="Si" type="QString"/>
                  </Option>
                </Option>
              </Option>
            </config>
          </editWidget>


 
```

**Comment by nboisteault** [comment]
I can confirm bug on release_3_2.

**Comment by nboisteault** [comment]
@rmarzocchi84 please open an issue if you have a similar behavior with lizmap 3.3rc2 and QGIS 3.4.x. Thanks.
