### ISSUE TITLE
Editor Form - Do not show atributes like define in QGIS

### ISSUE THREAD

**Issue by PFerro** [3liz/lizmap-web-client#107]
Hi,

When the Lizmap call the Default form it will show the attributes as they are defined in the database, if the layer also has permissions update the form will show the attributes as defined in the Qgis |Edit Widget project (which I think is what should happen also in the query editor).

Some images to ilustrate
![image](https://cloud.githubusercontent.com/assets/9886773/5146610/55fa1308-71a6-11e4-91e6-ce085d5ad42c.png)

![lizmap editores](https://cloud.githubusercontent.com/assets/9886773/5146658/ca91c0c6-71a6-11e4-8dc4-036176f13b32.png)

Pedro

**Comment by mdouchin** [comment]
You are right this should be coherent with QGIS way of handling thos hidden attributes. The solution for now in Lizmap:
* In the "popup" (identify feature), you can hide some columns by unchecking the WMS checkbox for each field to hide, in the Field tab as visible in the screenshot above
* In the Lizmap edition form, you should be able to hide some field by choosing the "Hidden" (Occulto) edit type, or you should also be able to do so by unchecking the checbox "Visible" in the configuration dialog (the one where you can choose the edit type)

**Comment by rldhont** [comment]
I'll close this issue, because it's du to QGIS configuration
