### ISSUE TITLE
Remove the hardcoded "Projects" from the title

### ISSUE THREAD

**Issue by signedav** [3liz/lizmap-web-client#1073]
Customers think it's confusing to have the projects in title, because in their working context projects are something completely different.
![image](https://user-images.githubusercontent.com/28384354/52646993-db02e580-2eb1-11e9-9429-a6aec2e5cad9.png)
They would like to see only "Visualisierung (experimental)".

So what do you think about the possibility to have an option to remove the `jLocale::get("view~default.repository.list.title").' - '.` here?

https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/view/controllers/default.classic.php#L73

Or is this problematic?

Another approach would be, that customers can influence it by deleting the string from the translation file `lizmap/modules/admin/locales/de_DE/admin.UTF-8.properties` but then there is still a lost hyphen. So I would suggest to do something like:
```
if(  jLocale::get("view~default.repository.list.title") ) {
    $title = jLocale::get("view~default.repository.list.title").' - '.$services->appName;
} else {
    $title = $services->appName;
}
```

What does the community think about?

**Comment by laurentj** [comment]
> by deleting the string from the translation file

Lizmap sources files MUST NOT be modified, as it adds difficulties to upgrade Lizmap.

However, I'm in favor of removing completely this "Projects" work. @mdouchin  @rldhont What do you think about it?

**Comment by rldhont** [comment]
I think the pages' title have to be enhanced.

For the projects page, "Projects" can be removed.

For the map pages, what do you think about the title ?
