### ISSUE TITLE
displaying a window for user information

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-web-client#1079]
Hi all,
I would like to open a popup / window when people access my lizmap project to telle them how to access files associated to a poi and download it.
Is there sucha feature in lizmap?

Thank you for your help!!
Gérald

**Comment by Gustry** [comment]
Yes you can add some custom javascript:
https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#adding-your-own-javascript

One example:
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/qgis/media/js/montpellier/displayMessageAtStartup.js.example

**Comment by gerald2545** [comment]
thank you for the links, I will try that

**Comment by gerald2545** [comment]
Too easy ;) thank you for your quick reply ! !
Our  project (french) : https://velomax.2p2r.org
