### ISSUE TITLE
Can't insert&update data in PostGis Views 

### ISSUE THREAD

**Issue by PFerro** [3liz/lizmap-web-client#108]
Hi, 

When I try to update or insert data which are in Postgis Views it's not possible (they all have write permissions and if I do the some action at QGIS works). 

![image](https://cloud.githubusercontent.com/assets/9886773/5181155/8f34fa6a-748b-11e4-887e-337c2f097a82.png)

When I do the same action on Postgis Tables it works as expected.

Tested at Lizmap 2.10 and 2.11 

Regards,
Pedro

**Comment by rldhont** [comment]
I can't reproduce the issue.

I created a vue base on a table with a trigger and I was able to update through the view.

**Comment by jancelin** [comment]
No problems for me on Lizmap 2.10 or 11beta. All my  views working . insert update delete with triggers  working also.We need more information on the view

**Comment by jancelin** [comment]
Have you registered your login password postgis in qgis, so in your .qgis file?

**Comment by rldhont** [comment]
Has been fixed and validated by @jancelin

**Comment by slarosa** [comment]
I have a similar error in 3.0b4 (e45489d),

```Failed to load resource: the server responded with a status of 500 (Internal Jelix Error)```

on edit/add/delete geometry in a postgis (point) table.

This is happening on a localhost server, Chrome and OSX.

**Comment by slarosa** [comment]
I created a simple project for testing: http://lrssvt.ns0.it/h2o/lizmap/www/index.php/view/

**Comment by josemvm** [comment]
hi,

i think that I had a similar case because the GID field wasn't published  through WFS

**Comment by josemvm** [comment]
hi,

i think that I had a similar case... because the GID field wasn't published through WFS

**Comment by slarosa** [comment]
@josemvm Did you manage to figure out a way to solve the problem?

**Comment by josemvm** [comment]
in my case, it was a simple project configuration trouble, in layer properties/fields

![wfs](https://cloud.githubusercontent.com/assets/10053874/15245141/c93b1976-18fc-11e6-9f94-f7add1167ab0.jpg)

**Comment by slarosa** [comment]
unfortunately it does not work for me, all fields have the check in my case.
