### ISSUE TITLE
Constraints on fields defined on QGIS aren't included in Lizmap

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#1080]
### What is the bug?
For example, to avoid mistakes when updating an IP field, I used a regular expression  

It works well on QGIS, but Lizmap ignore it.
I can put any value on the field without error.

### Expected behavior
On QGIS, field appaers with red backround when value doesn't respect the constraint, it would be fine to have the same thing with Lizmap.

### Screenshots and logs

![image](https://user-images.githubusercontent.com/32867483/53158465-f06bc400-35c3-11e9-88a7-684ff802a297.png)

### Environment

 - Lizmap version: 3.2.2
 - QGis version: 2.18.18
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Postgresql.

**Comment by rldhont** [comment]
Expressions are not evaluated by QGIS Server or Lizmap, so we need to build a plugin to evaluate expression.

This plugin will be usefull for:
* default values
* constraints
* filtering form groups

**Comment by rldhont** [comment]
Constraint has been implmented in version 3.4.0 with lizmap plugin server side started at version 3.3.0
* PR https://github.com/3liz/lizmap-plugin/pull/196
