### ISSUE TITLE
Unexpected results of dataviz aggregation parameters

### ISSUE THREAD

**Issue by bsaglio2001** [3liz/lizmap-web-client#1081]
### What is the bug?

Unexpected results of dataviz aggregation parameters. 
The aggregate function displayed on my web map is not the one I choose with QGIS Lizmap plugin !
(#743)
Is there a limitation about the type of attributes in use ?

### Steps to reproduce the issue

I try with different layers of my project to create an histogram.
X-axis is for a simple category of values (1,23,4 or 0,1,2) based on one attribute
Y-axis must be a sum of another attribute values (area, population... for instance)
I specify "sum" as a group function in QGIS lizmap Plugin...
I upload my project to Lizmap.

### Screenshots and logs

Parameters in QGIS Lizmap plugin
![capture01](https://user-images.githubusercontent.com/47885683/53235875-2b88f880-3693-11e9-8eda-fdbb35e7f354.PNG)

parameters in the cfg file
![capture02](https://user-images.githubusercontent.com/47885683/53235877-2c218f00-3693-11e9-8b47-3ef0600772c9.PNG)

results on my webmap :
- The first graph displays the number of entities in each categroy (as if it was a "count" aggergate function)
- The second graph displays population of the first entitie of each category only.
![capture03](https://user-images.githubusercontent.com/47885683/53235878-2c218f00-3693-11e9-9c39-a6b5a4f77f6f.PNG)
![capture04](https://user-images.githubusercontent.com/47885683/53235880-2c218f00-3693-11e9-9a0f-82144b7987fc.PNG)

### Environment

 - Lizmap version: 3.2.2
 - QGis version: 2.18.20
 - OS: Windows 10
 - Browser: Firefox 65 / Microsoft Edge 17.17134
 - Lizmap data stored into Postgresql or Shapefile

**Comment by rldhont** [comment]
This is a lizmap-plugin issue. It has been fixed in the plugin:
* master (qgis3) https://github.com/3liz/lizmap-plugin/commit/5e4ed761fb9cb89a2a06f27044079a7ac75c44c9
* qgis2 https://github.com/3liz/lizmap-plugin/commit/e6713ecdd803dced1be513dadde013d6641c3fb2

The fix will be available in next lizmap-plugin versions:
* 3.0.2 
* 2.4.3
