### ISSUE TITLE
Transparency of polygon layer isn't taken into map printing

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#1082]
### What is the bug?
The transparency is defined on layer's properties in QGIS project.
The review in Lizmap is well-done, but in editing preview, the layer isn't transparent at all.

### Expected behavior
To see the same things in both Lizmap and edition.

### Screenshots and logs
In lizmap :

![image](https://user-images.githubusercontent.com/32867483/53350515-82a2fd80-391f-11e9-8bb8-7d1fd19024a4.png)

In pdf :
![image](https://user-images.githubusercontent.com/32867483/53350559-9d757200-391f-11e9-920f-9ce85524e185.png)

### Environment

 - Lizmap version: 3.2.2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Postgresql

**Comment by rldhont** [comment]
I have tested printing transparency on your instance and it works.

I think the background is not printable in your example.

**Comment by mfangain** [comment]
Hi,

In my example, the background is printable as you can see here :
![image](https://user-images.githubusercontent.com/32867483/55239034-24c34780-5236-11e9-850c-bc3d27bdfb05.png)

But if I change opacity in Lizmap, there's no problem with some layers :
![image](https://user-images.githubusercontent.com/32867483/55239160-60f6a800-5236-11e9-8780-cb0d3328e2a5.png)

Even setting opacity in Lizmap to other layers, there's no transparency in editing preview :
![image](https://user-images.githubusercontent.com/32867483/55240232-baf86d00-5238-11e9-9b4b-611889d6292d.png)

I don't see anything that can explain this difference...

MFANGAIN

**Comment by rldhont** [comment]
In the last examples, is it a point layer ?

**Comment by mfangain** [comment]
No, it's also a polygon layer (buffer around point layer)

**Comment by nboisteault** [comment]
@mfangain what do you call "editing preview" ?

**Comment by mfangain** [comment]
Hi,

I call "editing preview" the new tab that's open after clicking on "print" button.
This happens with pdf files, but not with jpg.

Thanks.

MFANGAIN

**Comment by rldhont** [comment]
QGIS config and QGIS Server issues.
