### ISSUE TITLE
attribute table - problem with bbox on getfeature request

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1084]
hi

> it seems there is an issue when BBOX is added to the GetFeature Request https://github.com/3liz/lizmap-web-client/issues/1075

qgis server 3.4.5

thanks

**Comment by josemvm** [comment]
@rldhont the problem happens when `"limitDataToBbox": "True"` is set in the plugin

**Comment by nboisteault** [comment]
@josemvm  I have tested with original "Montpellier - Transports" project just adding `"limitDataToBbox": "True"`  with QGIS Server 2.18 and 3.4.5. Lizmap is last version of the 3.2 branch. I can't reproduce the issue. @josemvm is your project made in QGIS desktop 3.4.5 ?

**Comment by nboisteault** [comment]
I can reproduce the issue with a minimal QGIS 2.18 project.

**Comment by josemvm** [comment]
@nboisteault i can provide a link if you want to inspect

**Comment by nboisteault** [comment]
@josemvm I have found the bug. Thank you.

**Comment by josemvm** [comment]
now i'm talking about children tables, it´s not working with `"limitDataToBbox": "True"`
thanks @nboisteault

**Comment by josemvm** [comment]
like "Quatiers" and "Sous-Quatiers"

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/pull/1101

great!!! :-)
thanks @nboisteault

**Comment by rldhont** [comment]
Fixed
