### ISSUE TITLE
Release of Lizmap 3.3 with qgis 3.4.X support TODAY

### ISSUE THREAD

**Issue by Xpirix** [3liz/lizmap-web-client#1086]
Today is the day.
https://www.3liz.com/blog/rldhont/index.php?post/2019/01/21/Lizmap-Web-Client-3.2-and-futur
![screenshot from 2019-02-28 13-55-15](https://user-images.githubusercontent.com/43842786/53561653-84a7cf00-3b60-11e9-9b02-27a909e35174.png)

**Comment by pcav** [comment]
Sorry, I'm confused: has version 3.2.2 or 3.3 (with QGIS 3.4 support) been released today?

**Comment by Xpirix** [comment]
The version 3.2.2 has been just released but the post on the blog said that the are planing to release the version 3.3 at the end of February. Maybe the version 3.3 is for today too.
![screenshot from 2019-02-28 14-04-06](https://user-images.githubusercontent.com/43842786/53562268-02b8a580-3b62-11e9-847c-3d6cf546cf8a.png)

**Comment by pcav** [comment]
Wow, that's great news, thanks!

**Comment by Xpirix** [comment]
You're welcome.

**Comment by josemvm** [comment]
very good news!!! :-)
thanks

**Comment by rldhont** [comment]
version 3.3 should have been released this week but QGIS Server 3.4 should also be fixed

**Comment by pcav** [comment]
Thanks. Could you please point out which tickets should be closed on QGIS to be ready?

**Comment by pcav** [comment]
If you could publish an RC version I can start early testing.

**Comment by Gustry** [comment]
> version 3.3 should have been released this week but QGIS Server 3.4 should also be fixed

Do you mean that QGIS 3.4.5 is not enough and Lizmap 3.3 needs to wait 3.4.6?

**Comment by rldhont** [comment]
Probable issue in QGIS Server:
* #1084 attribute table - problem with bbox on getfeature request 
* #1024  child objets in popup with QGIS server 3

**Comment by pcav** [comment]
Thanks

**Comment by nboisteault** [comment]
#Please go on #1075 for any comments.
