### ISSUE TITLE
Live tracking multiple trace

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#1087]
### Is your feature request related to a problem? Please describe
I need to track multiple objects. This should be gpsd clients

### Describe the solution you'd like
GPSD client that send data to gpsd server. QGIS/Lizmap has a layer with live update of the tracks. Doas that means a js script that update data? a refresh function?

### Describe alternatives you've considered
* updated positions are send directly to a postgis table, js refresh the layer each 5 seconds
* Use GPS info (plugin) in qgis?

**Comment by josemvm** [comment]
hi @jlstanus 
see here https://github.com/3liz/lizmap-web-client/issues/1011

**Comment by jlstanus** [comment]
ok thank you
