### ISSUE TITLE
Unable to see shp and geoTiff on LWC

### ISSUE THREAD

**Issue by GiuliaRonchetti** [3liz/lizmap-web-client#1088]
Hello, 
we are trying to use Lizmap 3.2 on OSGeoLive 12. This is our configuration: OSGeoLive 12, QGIS server, Apache 2, Lizmap 3.2, QGIS desktop 2.18 (with lizmap plugin). 
We have no problems with the Montpellier Demo project (everything works), but when we create our new project we have problems with layer visualization. We are able to correctly see only GeoJson layers. It seems that there is an issue with shp and GeoTiff. On the Desktop everything works, we have configurated WMS, WFS and WCS capabilities, but on the web shp and GeoTiff layers disappear and only GeoJson remain.

What can we do? do you have any suggestions?
Thank you

**Comment by pcav** [comment]
Have you checked files and directories permissions?

**Comment by GiuliaRonchetti** [comment]
Thank you! We solved!

**Comment by Gustry** [comment]
@GiuliaRonchetti Please close your issue if it's solved. Thanks
