### ISSUE TITLE
Better sort order and default for base layers

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#109]
I think there is a problem in the sorting of baselayers:
* in QGIS desktop layers are sorted from top to bottom, and the last one is the selected one
* same in LizMap plugin
* in LMWC, the order is reversed, and the selection is maintained
* if we add an empty baselayer, its order in the list is ok, but it is not active (the penultimate is selected instead)
* if we add public layers (OSM, Google etc.), they are placed in the first places of the list.
IMHO:
* the order should be consistent
* the user should be able to explicitly select the default layer

**Comment by pcav** [comment]
In addition, if an empty baselayer is added as first, another baselayer is displayed. To show the empty one one must select that one, then switch back to the empty baselayer,

**Comment by pcav** [comment]
@umbiz

**Comment by rldhont** [comment]
Hi @pcav, does the commit 5a2a41ad8726a9a82bbc0cbca3dc0dfaf1cfd058 helps for empty baselayer ?

**Comment by umbiz** [comment]
Hi, i added the line and it's ok: when the empty baselayer is actived into plugin at any time order, in lmwc appear selected as first. Thanks!
