### ISSUE TITLE
Atlas for several layers

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#1090]
### Is your feature request related to a problem? Please describe

In Lizmap plugin (2.4.2), only one layer can be defined for the atlas feature.
Would it be possible to manage several composers with different coverage layer?

### Describe the solution you'd like
It would be called from popup, or selected in atlas windows.

### Describe alternatives you've considered
Today, we must duplicate a project for this.

Thanks.

MFANGAIN

**Comment by nboisteault** [comment]
It is possible now thanks to [this script](https://github.com/3liz/lizmap-javascript-scripts/tree/master/multipleatlas).

**Comment by rldhont** [comment]
It has to be integrated in next release, with plugin configuration.
