### ISSUE TITLE
qgis server lizmap dataviz

### ISSUE THREAD

**Issue by kino94** [3liz/lizmap-web-client#1093]
Hi, we have a problem to create charts with dataviz.
In particular we have problem to create scatterplot, the other types of charts seem work except when we try to create one of them with more data (about 5000).

The result that show at the display is the following

![image](https://user-images.githubusercontent.com/48024513/53796043-91973a80-3f33-11e9-8103-5e1bfb8a9970.png)

The steps to reproduce the issue are the following:

- Create the charts on the project in Qgis using Lizmap
- Save the project
- Refresh the page in Firefox
- Click on Dataviz icon

Configuration

 - Lizmap version: Lizmap-web-client-release_3_2
 - QGis version: 2.18
 - OS: Ubuntu
 - Browser: Firefox

**Comment by nboisteault** [comment]
@kino94 Could you provide a project with portable data which reproduce the issue ?

**Comment by rldhont** [comment]
Can be closed ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
