### ISSUE TITLE
external WFS

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#1094]
Is it possible to add an external WFS layer in Lizmap (lizmap 3.2) ?

I have an external WFS layer in my Qgis project (it works fine), but this one doesn't show up in Lizmap...

**Comment by rldhont** [comment]
If the layer is deifnied in the QGIS project, it has to be available in lizmap as all other vector layer but you probably have a proxy configuration to add to your QGIS Server configuration.

**Comment by loic74** [comment]
No proxy needed. I have no server-side access restrictions.
- Get capabilities from server (command line) works fine: `curl --location --request GET "http://geoservices.brgm.fr/geologie?service=wfs&request=getcapabilities&version=2.0.0"`
- I have no error in logfiles.
- The layer is published in OWS capacities...
- CRS are the same (2154)

**Comment by rldhont** [comment]
Nothing in the qgis server log ?

**Comment by loic74** [comment]
Sorry. Indeed, I double-checked, and I found this error message: 
`DescribeFeatureType failed for url...`
Maybe a problem with 2.14 version of my Qgis Server... Would version 2.18 solve the problem?

**Comment by nboisteault** [comment]
@loic74 you definitly should update to 2.18. Also is your WFS using https ?

**Comment by loic74** [comment]
Yes, it use https. But I think I found the problem. (a noob problem !). 

I use QGIS desktop 2.18 (until then I had no problems!) with the 2.14 server (due to stability problems with version 2.14 on my PC). Version 2.14 does not seem to support WFS versions above 1.0.0. The WFS server does not provide CRS 2154 in this version, so the layer is only available in WGS84.
All that remains is to upgrade the server (to avoid making a reprojection on the fly).

Thank you for your help, and sorry for the time lost ;-)

**Comment by nboisteault** [comment]
Don't forget to add this part to your configuration : https://issues.qgis.org/issues/16462#note-25

**Comment by loic74** [comment]
> Don't forget to add this part to your configuration : https://issues.qgis.org/issues/16462#note-25

Thank you for the information. Thanks to this, in addition to installing an X server, everything works fine with version 2.18 ;-)

**Comment by Cww7** [comment]
I have the same problem with a WFS HTTPS (with password). I use qgis server 3.4 and lizmap 3.3.

What change must we make to make it work ?
