### ISSUE TITLE
Layer werden in Lizmap- Web Client nicht angezeigt und die Schaltfläche zum Drucken ist auch nicht da

### ISSUE THREAD

**Issue by zollilein** [3liz/lizmap-web-client#1096]
Hallo zusammen,

ich verzweifele so langsam.
Ich habe nach Anleitung den Qgis Server 2.18 und den Lizmap Web Client unter Windows 7 installiert.
Lief erst alles prima. Ich konnte Layer aus einem fertigen Projekt auswählen, abspeichern und später im Web Client war alles zu sehen.
Jetzt zeigt er mir einfach keine Layer mehr an. Ich weiß einfach nicht woran es liegen kann. Habe schon alles durchsucht, finde aber keinen Hinweis auf Veränderung.
Von Anfang war auch keine Schaltfläche zum Drucken da. Auch hier weiß ich nicht, wie ich die herstellen kann.

Es wäre super, wenn jemand eine Lösung für mich hätte.

Liebe Grüße

**Comment by rldhont** [comment]
Sorry, we do not speak German, can you update your issue in English.

**Comment by zollilein** [comment]
Hello everybody,

I despair so slowly.
I installed the Qgis Server 2.18 and the Lizmap Web Client under Windows 7 after instructions.
Everything went great first. I was able to select from a finished project, save it and later everything was visible in the web client.
Now he just shows me no more shift. I just do not know why it can be. Have all the best, but find no evidence of change.
Was also no button for printing there. Again, I do not know how I can make that.

It would be great if someone had a solution for me.

best regards

**Comment by zollilein** [comment]
Hello everybody,

I despair so slowly.
I installed the Qgis Server 2.18 and the Lizmap Web Client under Windows 7 after instructions.
Everything went great first. I was able to select from a finished project, save it and later everything was visible in the web client.
Now he just shows me no more shift. I just do not know why it can be. Have all the best, but find no evidence of change.
Was also no button for printing there. Again, I do not know how I can make that.

It would be great if someone had a solution for me.

best regards

**Comment by nboisteault** [comment]
@zollilein did you update QGIS Server to 3.4 ?

**Comment by zollilein** [comment]
no  i didn`t.because I was afraid that then nothing works.
I was so glad that I got it installed at all

**Comment by nboisteault** [comment]
@zollilein Do you have errors in your browser console ?

**Comment by zollilein** [comment]
During the test run in the server:
Some layer encodings are not set:

Then there was also times that he grass 7.4.2 can not find and in the Python protocol was something like this: FcgidInitialEnv PATH "C: Qgis ...

**Comment by zollilein** [comment]
I would like to create a working Qgis Server with Web Client. This should be my project work for the oral exam. I'm very nervous because I'm afraid I can not make it on time

**Comment by nboisteault** [comment]
@zollilein Lizmap and QGIS Server work best with Linux. If you're not comfortable with Linux, you can try the vagrant way : https://github.com/3liz/lizmap-web-client/tree/release_3_2/vagrant

**Comment by zollilein** [comment]
ok .... thanks for the effort.
I think I'll try again
