### ISSUE TITLE
Some Vagranfile parameters should be put in custom .yml ?

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1097]
I have multiple Lizmap installed with Vagrant. I had to modify in Vagranfile `vb.name` and host port to not collide between instances. Now `git` see this modification but I don't want to commit it. Should those parameters be moved to custom.yml ?

**Comment by laurentj** [comment]
these parameters are parameters for vagrant. Vagrant does not know to read its parameters from an Ansible file or any yaml files. Except if you know Ruby (Vagranfile is a Ruby program), and you program the reading of an external file to retrieve parameters to set to `vb.name` etc..
