### ISSUE TITLE
The print icon disappears in QGIS 3

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#1100]
### What is the bug?
I tested the latest version and verified a different behavior if I use QGIS 2.18.x and QGIS 3.6.x. In QGIS 2 creating the Lizmap file via the plugin with the print option, the icon is clearly visible on the left. If I use QGIS 3 instead, creating the Lizmap file with the print option, the icon disappears and then it is impossible to print. Maybe the bug is present in Lizmap plugin 3.x.

### Steps to reproduce the issue

1. QGIS 2.18.x - Lizmap plugin - Print option selected
2. In Lizmap webclient the print icon is present and it works
3. QGIS 3.6.x - Lizmap plugin - Print option selected 
4. In Lizmap webclient the print icon disappears

### Expected behavior
Same behaviour in QGIS 2 and QGIS 3

### Environment

 - Lizmap version: QGis version 2.18.x with Lizmap plugin 2.4.2 and QGIS 3.6.x with Lizmap plugin 3.0.1. Lizmap webclient 3.3pre:
 - OS :  Ubuntu, Mac OS
 - Browser : all
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? Sqlite

**Comment by rldhont** [comment]
Duplicates Composer layouts not recognized at all when using QGIS3 #1007 ?

**Comment by news24lor** [comment]
Yes, the problem is compatibility with QGIS 3.
I would also insert in QGIS 3 the problem with Relationships with no longer work and the data linked in Lizmap are no longer visible.

**Comment by josemvm** [comment]
the print icon disappears again in qgis 3.4.6
lwc master - montpellier project

**Comment by rldhont** [comment]
@josemvm If the print icon disappears it means that lizmap does not correctly parsed the qgis poject.

**Comment by josemvm** [comment]
it seems to me that the last merge 3.2 into master is not yet available in master zip file...

**Comment by josemvm** [comment]
e.g.:
 ```"abstract": "Districts of Montpellier <b>bold</b>" ```

**Comment by rldhont** [comment]
@josemvm it is in the master https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/qgis/montpellier.qgs.cfg#L68
I have merged release_3_2 yesterday.

**Comment by josemvm** [comment]
@rldhont  can you download master version and inspect the master.zip file?...

**Comment by nboisteault** [comment]
@rldhont here is the issue : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/map.js#L3927
In 2.18 `pTemplate` does **not** have `'atlas'` property.
In 3.4 `pTemplate` does have `'atlas'` property with `enabled: "0"` in it.

To fix this, should we avoid `'atlas'` property in `pTemplate` when it is not an atlas or should we just test `enabled` value ?

**Comment by rldhont** [comment]
@nboisteault 'atlas' property is added y the PHP:
* with 2.18 Project https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/lizmapProject.class.php#L1081
* with 3.* Project https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/lizmapProject.class.php#L1081

If with a 3.* Project, Atals element is always here we have to also test enabled:
```
if ( ('atlas' in pTemplate) && pTemplate.atlas.enabled == 1 )
```

**Comment by josemvm** [comment]
i'm trying with a master version fresh install, but the print icon not appears at all...

**Comment by josemvm** [comment]
it's ok with 3.2

**Comment by nboisteault** [comment]
@josemvm with master do you use QGIS Server 3.4 ?

**Comment by josemvm** [comment]
3.4.6

**Comment by nboisteault** [comment]
Did you refresh your cache ?

**Comment by josemvm** [comment]
yes @nboisteault

**Comment by josemvm** [comment]
@rmarzocchi84

do you have a fresh install with master version on qgis server 3.4.6? and can you see the print icon on montpellier project?

**Comment by rmarzocchi84** [comment]
yes @josemvm  I see the icon and I can print correctly. I have problem with project saved with QGIS 3 (layer style and print)  
The WMS gives me this error:


> <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
> <ServiceException code="StyleNotDefined">
> Style "default" does not exist for layer "palazzi_rolli"
> </ServiceException>
> </ServiceExceptionReport>
> 

It is probably related to this bug #1119

**Comment by josemvm** [comment]
@rldhont and @nboisteault sorry for the noise...
i have tried with qgis server 3.4 and 3.6 but the print icon doen't appears, and always with master fresh install
how can i debug this situation?

thanks again

**Comment by nboisteault** [comment]
@josemvm anything in the console ?

**Comment by rldhont** [comment]
@josemvm can't reproduce, any example url ?

**Comment by josemvm** [comment]
@nboisteault nothing in console
@rldhont please check your mailbox

**Comment by rldhont** [comment]
@josemvm In master, the projects are 3.4 and the config specified that the QGIS Server 2.18.

**Comment by josemvm** [comment]
@rldhont does this mean it is expected that the icon does not appear with qgis server 3 and projects 3?

**Comment by rldhont** [comment]
No it means QGIS Server 2.* cannot print with project 3.*

**Comment by josemvm** [comment]
@rldhont sorry for the noise...
thanks @rldhont and @nboisteault (with https://github.com/3liz/lizmap-web-client/pull/1186)
