### ISSUE TITLE
CRS problem with selection tools

### ISSUE THREAD

**Issue by christophemm** [3liz/lizmap-web-client#1102]
### What is the bug?

Hello,
I have a problem with the selection tool. my data is in wgs84, reprojected in 3857 with OSM in base layer. When I use one of the selection tools, I send coordinates in 3857.
`SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=Commerce&OUTPUTFORMAT=GeoJSON&EXP_FILTER=intersects(%24geometry%2C+geom_from_gml('%3Cgml%3APolygon+xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%22%3E%3Cgml%3Aexterior%3E%3Cgml%3ALinearRing%3E%3Cgml%3AposList%3E535221.7220868528+5734806.303789528+535189.4752155495+5734846.910960799+535280.2441866255+5734922.153660507+535305.3250865281+5734881.546489236+535221.7220868528+5734806.303789528%3C%2Fgml%3AposList%3E%3C%2Fgml%3ALinearRing%3E%3C%2Fgml%3Aexterior%3E%3C%2Fgml%3APolygon%3E'))&BBOX=535189.475216%2C5734806.30379%2C535305.325087%2C5734922.153661`
The db receives in 3857 and the selection gives nothing in return.
Why is there no reprojection of the coordinates of the selection tool?

I have 2 more errors:
/lm/Proj4js/defs/.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spatialreference.org/ref///proj4js/:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)

 - Lizmap version: 3.2.1
 - QGis version: 3.6.0-Noosa
 - OS : linux, Ubuntu 
 - Browser : Chrome
 - data stored : MSSQL

**Comment by christophemm** [comment]
additional info: in the demo project on montpellier, only the layer "public bulding" is selectable. It's a spatial layer but not the only one. "Points of interest" is a spatial layer but can not be selected

**Comment by christophemm** [comment]
Response from the selection of Tram Stop : 
`
{"type": "FeatureCollection",
 "bbox": [ 0, 0, 0, 0],
 "features": [
 ]
}
`
Response from the selection of Public Bulding : 
`
{"type": "FeatureCollection",
 "bbox": [ 3.87424453, 43.59681014, 3.89867796, 43.61450247],
 "features": [
  {
   "type":"Feature",
   "id":"publicbuildings.5",
   "geometry":
   {"type": "Point", "coordinates": [3.880303, 43.604219]},
   "properties":{
      "b_id":5,
      "b_name":"Railway station",
      "b_description":" "
   }
}
 ]
}
`

**Comment by nboisteault** [comment]
@christophemm Can you update to Lizmap on branch release_3_2 or at least apply this patch : https://github.com/3liz/lizmap-web-client/commit/6d9903425ec8bbccc6d58dc5f629f96e3990c852
I am almost sure it will fix your bug.

**Comment by christophemm** [comment]
Oh yes  ! 
I had seen your way out but I was not sure it was the same thing. 
Thank you ! it works

**Comment by nboisteault** [comment]
Glad it solved your issue :)
