### ISSUE TITLE
attribute table - non spatial children tables (display info panel)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1103]
hi

the display info panel doesn´t work for non spatial children tables

see the behaviour,e.g., between "Quartiers" & "Sous-quartiers" and "public buildings" & "Pivot tramstops / Buildings"

please fix it asap
thanks

qgis server: 2.14 e 2.18
lwc: all

**Comment by nboisteault** [comment]
I can confirm with 2.18. No requests are send when clicking on "Pivot tramstops / Buildings".

**Comment by nboisteault** [comment]
Fixed with https://github.com/3liz/lizmap-web-client/commit/22d302e486bf075de5aa115d51f6eb9a680caecd

**Comment by nboisteault** [comment]
@josemvm thank you for your bug report.

**Comment by josemvm** [comment]
@nboisteault so many thanks for your effort!!! :-)

**Comment by rldhont** [comment]
@nboisteault this CRS issue is only with QGIS 2.* ? Or also with QGIS Server 3.* ?

**Comment by josemvm** [comment]
@rldhont and @nboisteault we have a regression here...

**Comment by josemvm** [comment]
unknown particularities of the project 2.18...
