### ISSUE TITLE
Setting rights on layers

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1112]
We should be able to set rights on layers, not only on maps : rights for specific users/groups to view or edit a layer.

The ACL system of Jelix should be enhanced, to support hierarchical rights. So we should be able to set rights on a "resource path", like `/<repository>/<project>/<layer>/`

Roles (or subject in the jAcl2 terminology), could be "view a map", "modify a map", "delete a map".

To check if the user has the right to modify a layer, Lizmap will check the right on the resource `/<repository>/<project>/<layer>/`. Internally, if there is not right set on this layer, jAcl2 will check on the resource `/<repository>/<project>/`, or `/<repository>/` and so on...

Probably we should modify the interface to set rights on maps, to add specific users or groups on a layer..

**Comment by rldhont** [comment]
Has been implemented in version 3.4.0 with lizmap plugin server side first version 3.3.0
* PR https://github.com/3liz/lizmap-plugin/pull/267
