### ISSUE TITLE
Hide layers in legend

### ISSUE THREAD

**Issue by tobola123** [3liz/lizmap-web-client#1118]
Hello,
is it possiblle to hide layers by default in lizmap settings?
**When I start my project it looks like this ->**
![pic1](https://user-images.githubusercontent.com/17334448/54673906-95ae8500-4afb-11e9-8e53-b5c8cef67475.PNG)

**but I want to, that layers will hide like this ->**
![pic2](https://user-images.githubusercontent.com/17334448/54673909-96dfb200-4afb-11e9-97ab-1defa35fd488.PNG)

IS it possiblle?
Thanks for answers.

**Comment by NvBgm** [comment]
Yes this is.
Read the documentation 'Publisher guide' > ''Adding your own JavaScript'
There is also an example.

**Comment by rldhont** [comment]
@tobola123 it's possible with a script added in `media/js/your_project_name/`. 

Documentation: https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#examples

Examples: https://github.com/3liz/lizmap-web-client/tree/master/lizmap/install/qgis/media/js/montpellier

And the solution is this script: https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/qgis/media/js/montpellier/toggleGroups.js.example
