### ISSUE TITLE
Search does not work for integer fields(?)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#112]
It seems to me that the search does not work on integer fields (tested shapes and postgis). Not sure I'm doing something wrong or is a bug. Tested on LM 2.10.1

**Comment by mdouchin** [comment]
You mean the "Locate by layer" tool, which lies above the legend and allow to zoom to one feature by selecting it with the combox box or via typing the first letters in the input ?

**Comment by gioman** [comment]
yes, tested again now with  LM 2.10.2 and qgis master (desktop and server).

**Comment by rldhont** [comment]
Fixed by commit 99fc1ca
