### ISSUE TITLE
selection tool - geometry type with Z dimension

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1124]
hi

selection tool doesn´t work with geometries type `MultiPointZ`, `MultiLineStringZ`, `MultiPolygonZ`
we need to force type with `USING ST_Force_2D(the_geom)`

thanks

**Comment by rldhont** [comment]
Which version ? 3.1 or 3.2 ?

**Comment by josemvm** [comment]
3.2

**Comment by nboisteault** [comment]
@josemvm I can use the selection tool with lizmap 3.2, QGIS Server 2.18 and 3.4.
Here my SQL : 

```sql
CREATE TABLE public.edition_multipoint
(
    id SERIAL
    geom geometry(MultiPointZ,3857)
);
INSERT INTO public.edition_multipoint(
	geom)
	VALUES (ST_GeomFromText('MULTIPOINT Z (432476.820493413 5407620.23578794 1, 433476.820493413 5418620.23578794 2)',3857));
```

**Comment by josemvm** [comment]
@nboisteault yes it works, maybe a crs problem... (?)

**Comment by josemvm** [comment]
i think that there is a problem here with crs other than 3857
i have tried with several layers with crs 3763 and it doesn't work

**Comment by nboisteault** [comment]
@josemvm I can't reproduce your issue with `MultiPointZ` and CRS 2154 and CRS 3763. Please give us a reproductible case.
