### ISSUE TITLE
selection tool - special (accentuated) characters

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1125]
hi

selection tool not taking layers from qgis whose name contains special characters

thanks

**Comment by josemvm** [comment]
can you fix it asap?...

thank you so much :-)

**Comment by rldhont** [comment]
@josemvm it's version 3.1 or 3.2 ?

**Comment by josemvm** [comment]
3.2

**Comment by nboisteault** [comment]
@rldhont what the prupose of cleaning the name  [here](https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/www/js/attributeTable.js#L3214). If I remove that, it works but there might be some side effects I guess.

**Comment by rldhont** [comment]
@nboisteault the problem is that the FeatureType Name is not the same as WMS Layer Name and the cleanname is not equal to.

**Comment by rldhont** [comment]
@josemvm what is the QGIS Layer Name, the WMS Layer Name and the WFS FeatureType Name ?

**Comment by josemvm** [comment]
all the same: `Bocas de Incêndio`
but no problems if `Bocas de Incendio`

**Comment by nboisteault** [comment]
@rldhont : all the same for me too with QGIS Server 2.18 and 3.4. Maybe QGIS Server know return accented names for every case ?

**Comment by josemvm** [comment]
@nboisteault `loading map data` forever...

**Comment by nboisteault** [comment]
@josemvm any errors in console ?

**Comment by josemvm** [comment]
``TypeError: config.attributeLayers[lname] is undefined``
``addSelectionToolControl http://x.x.x.x/js/attributeTable.js:3150``
``each2jQuery``
``addSelectionToolControl http://x.x.x.x/js/attributeTable.js:3142``
``uicreated http://1x.x.x.x/js/attributeTable.js:224``
``triggerEvent http://x.x.x.x/OpenLayers-2.13/OpenLayers.js:138``
``init http://x.x.x.x/js/map.js:6594``
``i4jQuery``

**Comment by rldhont** [comment]
I confirm the bug, layers published in WFS are not all displayed in attribute table tool.

**Comment by nboisteault** [comment]
@josemvm Could you replace if block line 3146 code above and tell me if it is ok ?

```javascript
        if( lname in config.layers
            && lname in config.attributeLayers
            && config.layers[lname]['geometryType'] != 'none'
            && config.layers[lname]['geometryType'] != 'unknown') {
            var lConfig = config.layers[lname];
            selectionLayersSorted[config.attributeLayers[lname].order] = '<option value="'+lname+'">'+lConfig.title+'</option>';
        }
```

**Comment by josemvm** [comment]
yes @nboisteault 
everything is ok now! :-)

thank you so much

**Comment by nboisteault** [comment]
@josemvm not totally ok I think. Layers not set for attribute layers are not visible.

**Comment by josemvm** [comment]
layers are set for selection tool and for attribute table, and both work...

**Comment by rldhont** [comment]
@nboisteault thanks for the PR, but the selection can't be yet performed without attribute table configuration.

**Comment by rldhont** [comment]
Fixed
