### ISSUE TITLE
Rotation of symbols lost in Lizmap

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1128]
A rotated symbol in qgis desktop
![3_4](https://user-images.githubusercontent.com/691842/54770017-b4e40a00-4c02-11e9-98ce-dce7ce3b5932.png)
is not shown correctly in lizmap:
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=Test
See attached project.
[test.zip](https://github.com/3liz/lizmap-web-client/files/2993120/test.zip)

**Comment by gioman** [comment]
Not a Lizmap issue, if you put this 

https://lizmap.faunalia.eu/index.php/lizmap/service/?repository=faunalia&project=Test&VERSION=1.3.0

in QGIS WMS client you gets the same, so is a QGIS Server issue.

**Comment by pcav** [comment]
Thanks for checking. Then it will be interesting to check whether it has been solved in QGIS 3.4.

Il 21 marzo 2019 21:26:00 CET, Giovanni Manghi <notifications@github.com> ha scritto:
>Not a Lizmap issue, if you put this 
>
>https://lizmap.faunalia.eu/index.php/lizmap/service/?repository=faunalia&project=Test&VERSION=1.3.0
>
>in QGIS WMS client you gets the same, so is a QGIS Server issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1128#issuecomment-475388953

-- 
Sorry for being short

**Comment by pcav** [comment]
Fixed in QGIS 3. One more reason to migrate soon ;)
