### ISSUE TITLE
Add a tool to move features (lines, polygons)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#113]
It would be very handy among the editing tools.

**Comment by mdouchin** [comment]
+1 for this tool

**Comment by jaitor1** [comment]
+1

**Comment by jlstanus** [comment]
What do you mean by move feature, drag and drop one feature drom a table to an other?
So wps4server plugin would be useful ?

**Comment by rldhont** [comment]
Implemented in PR #693 reviews are welcomed ?
