### ISSUE TITLE
lizmap master - stop printing

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1144]
hi

when i try to print the montpellier project i get this error in the next browser tab:

`
<ServiceExceptionReport version="1.3.0">`
`<ServiceException code="Error">Composer template not found</ServiceException>`
`</ServiceExceptionReport>
`

thanks

**Comment by rldhont** [comment]
Hi @josemvm which QGIS Server version and QGIS Project version ? thanks

**Comment by josemvm** [comment]
qgis server 2.18 and montpellier project 3

**Comment by rldhont** [comment]
The QGIS 3 project description of layout is not compatible with QGIS server 2.18 which use composition. So the print tool has not to be available in this case. i have to update the code for this case.

**Comment by josemvm** [comment]
yes, it works with projects 2.18

**Comment by josemvm** [comment]
@rldhont  please give us feedback about this issue https://github.com/3liz/lizmap-web-client/issues/464
