### ISSUE TITLE
Probleme avec la liste de recherche

### ISSUE THREAD

**Issue by kali06** [3liz/lizmap-web-client#115]
Bonjour à tous,

j'ai installé limzpa sur un serveur linux debian + Lizmap 2.10 + Qgis server (et non qgis map-server) avec la version 2.6.0 de qgis sur le serveur,

j'ai un problème lors de l'affichage des cartes puisque mon champ de recherche s'affiche mais la liste déroulante est vide, pour info dans le plugin lizmap, j'ai mis en nombre de caractère pour autocomplétion 0. De ce fait, la liste déroulante s'affiche avec un rectangle blanc sans la liste avec les individus. 

Seriez-vous d'ou vient le problème et si vous aviez une solution,

en vous remerciant par avance,

**Comment by rldhont** [comment]
Bonjour,

Il y a un bug dans la version 2.6.* de QGIS-Server. Nous avons corriger ce bug  pour la prochaine version de QGIS https://github.com/qgis/QGIS/commit/2f75c3c88483bfb06a6878dfeda79347a67431cd mais aussi sur la branche 2.6 https://github.com/qgis/QGIS/commit/102cfedcba5a092f64e7bd076f6e86cceb21a774 seulement celle-ci n'est pas disponible dans les paquets.

Si vous savez le faire vous pouvez compiler la version 2.6 de QGIS:
https://raw.githubusercontent.com/qgis/QGIS/master/INSTALL

**Comment by kali06** [comment]
Merci pour votre réponse,

cependant ce bug était présent dans des versions antérieures de qgis server : ce problème existait même lorsque j'installais qgis-mapserver.
j'ai mis en pièce jointe la capture du problème.
Ce problème est d'autant plus frustrant que parfois la liste est disponible dans le menu déroulant et parfois elle ne l'ai pas. C'est aléatoire.

![lizmap](https://cloud.githubusercontent.com/assets/10414855/5628572/7af559d4-95a9-11e4-89a5-7e23f8ba7797.png)

en tout cas merci pour avoir pris le temps de répondre.

**Comment by pcav** [comment]
Wouldn't it be better to ask releasing a fixed 2.6.2?
Merci.

**Comment by kali06** [comment]
yes...if the problem come from qgis server,
but it's not sure, because even on lizmap demo, this problem exist

**Comment by mdouchin** [comment]
The issue is related to QGIS Server, as @rldhont mentionned. The demo online in http://demo.lizmap.3liz.com does not always reflect the last Lizmap and/or QGIS server version

**Comment by rldhont** [comment]
Does this issue is fixed by qgis 2.8.* ?

**Comment by kali06** [comment]
J'ai la version 2.6,

je pense que le problème est résolu, j'avais le nomd es couches en majuscules,

j'ai renommer mes couches avec un nom en minuscule,

par renommer, j'entends renommer le nom des fichiers shape,

ensuite dans le plugin lizmap sous qgis j'ai laissé le même nom que le nom de ma couche,

du coup cela fonctionne parfaitement,
