### ISSUE TITLE
GML 2 or 3 export. 00 value for month in date field

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1152]
### What is the bug?
GML 2 or 3 export changes month value to 00 in date field.

### Steps to reproduce the issue

1. Go to Montpellier project
2. Click on Layers => Points of interest
3. Select GML 2 or 3 and clic export
4. Open export

### Expected behavior
For example first value is  `<qgs:date>2012-00-17</qgs:date>` and not `<qgs:date>2012-01-17</qgs:date>`

### Screenshots and logs
![Capture du 2019-03-29 16-50-24](https://user-images.githubusercontent.com/2145040/55245104-cf416780-5242-11e9-8a79-11ce38f00d70.png)

### Environment

 - Lizmap version: master
 - QGIS Server version: 3.4.6
 - QGIS Project version: 3.4.5

**Comment by rldhont** [comment]
@nboisteault what is the date field edition configuration ?

**Comment by nboisteault** [comment]
![Capture du 2019-03-29 18-18-50](https://user-images.githubusercontent.com/2145040/55250713-20575880-524f-11e9-82b8-7f2a102f0ac0.png)

**Comment by rldhont** [comment]
The error is in the field format mm is not MM.

QGIS Server used the format of the date to provide the date value.

It is not an error or a bug just a malformed field format.
