### ISSUE TITLE
add selection in GetPrint request

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1153]
hi

the lwc can´t use this capability provided by the qgis server 3

thanks

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/464
https://github.com/3liz/lizmap-web-client/issues/748

**Comment by rldhont** [comment]
It's a QGIS Server regression not a lizmap one.

I don't know if the GetPrint test has been deactivated to loose this capability.

**Comment by rldhont** [comment]
It's a regression in the PDF output, not in the image one!

**Comment by josemvm** [comment]
are you talking about qgis server 3.4.6 ?

**Comment by rldhont** [comment]
I am talking about qgis server 3.*

If you do a GetPrint in PNG output format, you'll have the selection displayed. If you do the same in PDF, the selection is not displayed.

PNG output is automaticly tested, not the other output.

**Comment by josemvm** [comment]
it seems to me that we are not using the same versions...

- i'm testing with master version and the icon print doesn´t appears
- i'm testing with last 3.2 and the selection is not displayed at all formats

qgis server 3.4.6

**Comment by rldhont** [comment]
@josemvm QGIS PR done https://github.com/qgis/QGIS/pull/9654

**Comment by rldhont** [comment]
@josemvm new PR for 3.4 https://github.com/qgis/QGIS/pull/9692
A fix in 3.6 has not been backported to 3.4

**Comment by josemvm** [comment]
thank you very much for your work @rldhont 
it will be avaiable soon, at 2019-04-19 on 3.4.7

**Comment by rldhont** [comment]
@josemvm the fix seems to need more discussion https://github.com/qgis/QGIS/pull/9692#discussion_r272405690
@pcav do you have an opinion on https://github.com/qgis/QGIS/pull/9692 and the full backport of https://github.com/qgis/QGIS/pull/9016 to fix https://issues.qgis.org/issues/19500 ?

**Comment by josemvm** [comment]
> If you do a GetPrint in PNG output format, you'll have the selection displayed. If you do the same in PDF, the selection is not displayed.

now i can see the print icon and i have tried but selection is not displayed in any of the formats...
if you can inspect, you can use my last url

thanks

**Comment by josemvm** [comment]
@rldhont can you take a look here?

**Comment by rldhont** [comment]
@josemvm tested
I have selected a `Quartiers` and I have printed in ONG and the selection is displayed.

**Comment by josemvm** [comment]
ok, but i'm talking about selection with locate tool!

**Comment by rldhont** [comment]
The locate tool has never been printable

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/288

**Comment by rldhont** [comment]
The PR QGIS Server has been merged in QGIS 3.6.2 and NOT in QGIS 3.4.7.

**Comment by nboisteault** [comment]
Issue should be fixed now with QGIS 3.4.9 if I'm correct. @josemvm  did you test ?

**Comment by nboisteault** [comment]
I have tested, it works !
