### ISSUE TITLE
[UI] print parameters hidden with some window width

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1154]
### What is the bug?
With some window width, print paramters to the right are hidden

### Steps to reproduce the issue

1. Select print tool
2. Change window width

### Expected behavior
All parameters should be accessible

### Screenshots and logs
![print_select_parameters_hidden](https://user-images.githubusercontent.com/2145040/55247973-2ea27600-5249-11e9-98ca-cdc2cd2fe01f.jpeg)

### Environment
 - Lizmap version: 3.2.2
 - Browser (Firefox, Chrome...): Opera, Firefox

**Comment by rldhont** [comment]
Duplicate #1151 ?

**Comment by nboisteault** [comment]
What are the odds ? :) Yes, duplicate.
