### ISSUE TITLE
service non disponible de lizmap

### ISSUE THREAD

**Issue by saidoul** [3liz/lizmap-web-client#1155]
- Lizmap version: 3,1
 - QGIS Server version:3,4
 - QGIS Project version:
 - OS (windows, linux, macOS, android..): windows 10
 - Browser (Firefox, Chrome...):Chrome
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?.
![tempsnip](https://user-images.githubusercontent.com/48227484/55277908-a46c1780-5305-11e9-83f9-d9dd7819977d.png)
![tempsnip](https://user-images.githubusercontent.com/48227484/55277911-afbf4300-5305-11e9-9fc6-659c77901b5f.png)

 Postgresql

**Comment by rldhont** [comment]
Lizmap 3.1 is not compatible with QGIS Server and QGIS Project 3.*

You can update to 3.2 in which we fix some issues and support QGIS Server 3.* with QGIS Project 2.18

Version 3.3 will support QGIS Server and QGIS Project 3.*

**Comment by saidoul** [comment]
Thanks for your help
