### ISSUE TITLE
Change layer style

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1159]
### What is the bug?
I observed the same problem as bug  #552 

### Environment

- Lizmap version: **3.2.2**
- QGIS Server version: 2.18
- QGIS Project version: 2.18.28
- OS (windows, linux, macOS, android..): MacOS
- Browser (Firefox, Chrome...): Firefox, Safari

**Comment by rldhont** [comment]
Can't reproduce, can you provide an example ?

**Comment by igeofr** [comment]
Yes, [here is an example of a project.](https://map.data-wax.com/websig/lizmap/www/index.php/view/map/?repository=rep008&project=Projet_limite_UP)

Note: I use a number and a dash in the style name

**Comment by rldhont** [comment]
The issue, is that the layer dock does not respect the applied style.

**Comment by igeofr** [comment]
Ok. Thank you.

**Comment by rldhont** [comment]
Fixed by #1177
