### ISSUE TITLE
Problème avec l'infobulle

### ISSUE THREAD

**Issue by kali06** [3liz/lizmap-web-client#116]
Bonjour,

J'ai installé lizmap sur un serveur linux debian + Lizmap 2.10 + Qgis server (et non qgis map-server) avec la version 2.6.0 de qgis sur le serveur,

J'ai paramétré les infobulles via le plugin lizmap,

cependant, lorsque je clique sur la carte, celles-ci n'apparaissent pas, hors elles existent bien,

d'ailleurs elles apparaissent bien mais quelques minutes d'attente (5 min environ), passé ces 5 minutes, les infobulles sont disponibles et lorsque je clique sur la carte, elles apparaissent, ce que je souhaiterais savoir si il existe un moyen de faire que les infobulles fonctionnent dés le départ ( c'est-à-dire  dés que j'arrive sur la carte sans attendre ces 5 minutes)

en vous remerciant par avance,

**Comment by rldhont** [comment]
Le problème et la solution sont les mêmes que pour le #115

**Comment by kali06** [comment]
Merci de votre réponse,

bien reçu, je vais voir ce que je peux faire,

mais est-ce que le problème ne viendrais pas des configurations du serveur ou de jelix directement ?

en vous remerciant d'avoir prêté attention a mon message,

**Comment by nboisteault** [comment]
This issue can be closed ?
