### ISSUE TITLE
 Bing - Error hybrid and road

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1160]
### What is the bug?
I have a problem with Bing that I think is related to the changes #1042 (only hybrid and road).

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://ak.dynamic.t3.tiles.virtualearth.net

Raison : échec de la requête CORS.

### Environment

Lizmap version: 3.2.2
QGIS version: 2.18

**Comment by rldhont** [comment]
Can you update and test map.js by replacing `RoadOnDemand` by `Road` https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/www/js/map.js#L6956  and `AerialWithLabelsOnDemand` by `AerialWithLabels` https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/www/js/map.js#L7016

If it's ok, I can fix it.

**Comment by igeofr** [comment]
After testing your proposal, I confirm that it's ok.
Thank you.
