### ISSUE TITLE
Scale - Safari browser

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1161]
### What is the bug?
There is a problem with the map scale window and the Safari browser.

### Screenshots and logs
<img width="245" alt="Capture d’écran 2019-04-02 à 08 22 09" src="https://user-images.githubusercontent.com/7761073/55387526-1c625980-5521-11e9-9514-5f78d8f4d90b.png">

### Environment
- Lizmap version: 3.2.2
- QGIS Server version: 2.18
- QGIS Project version: 2.18.28
- OS (windows, linux, macOS, android..): MacOS
- Browser (Firefox, Chrome...): Safari (Tested on firefox and chrome)

**Comment by nboisteault** [comment]
No more an issue since at least Lizmap 3.6.
