### ISSUE TITLE
Information window - URL WMS - http/https

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1162]
### What is the bug?
When we copy the WMS/WMTS url from the information window then it is given to us in http and not in https.

### Steps to reproduce the issue
1. Go to information window
2. Copy the WMS URL
3. Add the URL in QGIS

> Échec du téléchargement des possibilités:
> Purge des possibilités : Unknown error

### Screenshots and logs
<img width="256" alt="Capture d’écran 2019-04-02 à 08 47 40" src="https://user-images.githubusercontent.com/7761073/55389082-15891600-5524-11e9-81d7-af8f669218ae.png">

### Environment
- Lizmap version: 3.2.2
- QGIS Server version: 2.18
- QGIS Project version: 2.18.28
- OS (windows, linux, macOS, android..): MacOS
- Browser (Firefox, Chrome...): Firefox, Safari

**Comment by rldhont** [comment]
You can force lizmap to provide HTTPS: https://docs.lizmap.com/current/fr/install/advanced_install.html

**Comment by igeofr** [comment]
Thank you for your answer. It led me to solve several configuration problems.
