### ISSUE TITLE
Issue with selection tools

### ISSUE THREAD

**Issue by bgisb** [3liz/lizmap-web-client#1163]
Hi!

I have an issue with selection by rectangle etc. It's not working.
Lizmap 3.2.1
Lizmap Plugin 3.0.2
QGIS 3.4.5
Project EPSG:4326
Layer EPSG:4326

I have WFS enabled and layer have been added to the attribute table in Lizmap plugin.
![selection1](https://user-images.githubusercontent.com/48524622/55402213-3157e080-5553-11e9-8ae4-dd91d28fd9f0.png)
![selection2](https://user-images.githubusercontent.com/48524622/55402253-4f254580-5553-11e9-9c89-a11d48f8fb05.png)
![selection3](https://user-images.githubusercontent.com/48524622/55402325-7bd95d00-5553-11e9-898d-890f7bdb0d0c.png)

Is there sth wrong with my projection? Thanks in advance.

**Comment by rldhont** [comment]
A similar issue has been fixed #1102 with https://github.com/3liz/lizmap-web-client/commit/6d9903425ec8bbccc6d58dc5f629f96e3990c852 and will be available in lizmap-web-client 3.2.3

**Comment by bgisb** [comment]
Thank you! I will try and let you know.

**Comment by bgisb** [comment]
Unfortunately, the patch did not help.  Do you have any other idea why I still have a problem with selection by a polygon?

**Comment by bgisb** [comment]
EDIT. It has emerged that issue was related to bug with QGIS Server.
https://issues.qgis.org/issues/20927 It's up and running. Thank you!
