### ISSUE TITLE
Theme/project - Safari

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1166]
### What is the bug?
When we assign a theme to a project, it is only taken into account on Safari after clearing the browser cache.

### Environment
 - Lizmap version: 3.2.2
- QGIS Server version: 2.18
- QGIS Project version: 2.18.28
- OS (windows, linux, macOS, android..): MacOS
- Browser (Firefox, Chrome...): Safari (Tested on firefox and chrome)

**Comment by nboisteault** [comment]
@igeofr 
Does issue still occur ? Did you upgrade to 3.2.3 ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
