### ISSUE TITLE
popups au format HTML impossible avec une vue

### ISSUE THREAD

**Issue by gmenguy** [3liz/lizmap-web-client#117]
Bonjour,

La configuration HTML d'un popup sur une couche basée sur une vue de Postresql ne fonctionne pas. Par contre, l'affichage simple sans configuration HTML fonctionne très bien.

A suivre

gwen

**Comment by jancelin** [comment]
la même.

**Comment by rldhont** [comment]
Pouvez-vous confirmer que ce bug existe toujours dans la version 2.11 Beta 2 ?
https://github.com/3liz/lizmap-web-client/releases/tag/2.11beta2

**Comment by jancelin** [comment]
bug présent dans la béta3

**Comment by rldhont** [comment]
Quelle version de QGIS-Server ?

**Comment by jancelin** [comment]
Toujours le même bug,
+ un nouveau : perte de l'affichage de l'alias des boites à cocher
 qgis 2.8.1 mapserver 2.8.1 lizmap2.11beta3.

**Comment by rldhont** [comment]
Merci d'ouvrir ou de ré-ouvrir un nouveau bug pour l'alias

**Comment by rldhont** [comment]
Pouvez-vous nous donner plus d'information sur la structure de votre vue et de votre Popup HTML ?

Dans mon cas j'ai la popup suivante :
```
<h1>{$gid}</h1>
<h2>{$maille22}</h2>
```

**Comment by jancelin** [comment]
salut, voici ce que j'utilise:

<table CELLPADDING="5" CELLSPACING="5">
<tr><td align= "right"><b>Date :</b> </td><td>{$limi_date}</td></tr>
<tr><td align= "right"><b>Type d'oiseau :</b> </td><td>{$type_oiso}</td></tr>
<tr><td  align= "right"><b>Catégorie : </b></td><td>{$categorie}</td></tr>
<tr><td  align= "right"><b>Quantité : </b></td><td>{$limi_qte}</td></tr>
<tr><td  align= "right"><b>Genre: </b></td><td>{$genre}</td></tr>
<tr><td  align= "right"><b>Espèce : </b></td><td>{$espece}</td></tr>
<tr><td  align= "right"><b>Sexe : </b></td><td>{$sexe}</td></tr>
<tr><td  align= "right"><b>Comportement:</b> </td><td>{$comportement}</td></tr>
<tr><td  align= "right"><b>Nid : </b></td><td>{$limi_nid}</td></tr>
<tr><td  align= "right"><b>Jeune : </b></td><td>{$limi_jeun}</td></tr>
<tr><td  align= "right"><b>Animaux: </b></td><td>{$limi_anx}</td></tr>
<tr><td  align= "right"><b>Commentaire : </b></td><td>{$limi_com}</td></tr>
</table>

**Comment by rldhont** [comment]
As-tu essayé l'URL GetFeatureInfo directement ?
As-tu essayé l'URL GetFeatureInfo avec le format XML ?
As-tu des erreurs dans les logs du serveur ?

**Comment by jancelin** [comment]
apache error log lors de l'ouverture de la popup:

[Mon Mar 09 10:14:24.557663 2015] [:error] [pid 14] [client xxx.xxx.xx.xx:60276] 2015-03-09 11:14:24\t147.100.92.6\twarning\t2015-03-09 11:14:24\t[2]\tpreg_replace(): Compilation failed: missing ) at offset 48\t/var/www/websig/lizmap/$

**Comment by jancelin** [comment]
/var/www/lizmap/.../messages.log:

2015-03-09 11:14:24     147.100.92.6    default --> CURL: {"url":"http:\/\/127.0.0.1\/cgi-bin\/qgis_mapserv.fcgi?bbox=-116421.676362%2C5776329.661996%2C-108887.851763%2C5779081.395013&crs=EPSG%3A3857&exceptions=application%2Fvnd.ogc.$

**Comment by jancelin** [comment]
fonctionne avec GetFeatureInfo avec le format XML

**Comment by rldhont** [comment]
Oui, je n'en doute pas le problème se trouve dans la transformation du XML en HTML. Par contre j'ai besoin de vérifier que tous les champs renvoyés ont bien le **name** attendu dans la **template** de popup html

**Comment by jancelin** [comment]
doc 3liz: 
http://docs.3liz.com/fr/publisher_guide/advanced_lizmap_config.html#configurer-les-popups-dans-lizmap

"Note
Si vous avez configuré un alias pour un champ, il faut utiliser l’alias au lieu du nom entre accolade".

**Comment by Spitfiire** [comment]
Bonjour,

Est ce que quelqu'un peut donner un exemple de syntaxe lors de l'utilisation d'un alias, la doc n'étant pas clair la dessus.

> Si vous avez choisi un alias pour un champ, vous devez utiliser l’alias plutôt que le nom, entre crochets.

>If you have configured an alias for a field, you have to use the alias instead of the name, between the brackets.


Merci

**Comment by Gustry** [comment]
La popup HTML lizmap est dépréciée. Il faut désormais utiliser l'infobulle QGIS, beaucoup plus performante.
