### ISSUE TITLE
Location by layer creates spikes

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#118]
LM 2.10.2 on a fresh Debian testing
![bug_lm](https://cloud.githubusercontent.com/assets/691842/5959510/3558e494-a7cf-11e4-9e4c-0f0c4dc94406.png)
. See attached.

**Comment by rldhont** [comment]
Hi @pcav, does this issue still exist in 2.11 ?

**Comment by pcav** [comment]
Cannot reproduce it now. Will reopen if necessary. Thanks for following this up.
