### ISSUE TITLE
lizmap 3.2.2 / qgisserver 2.18 : Error on editing a PotGIS viewEditing 

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#1185]
### What is the bug?
I my project I have a view with polygon geometries and gid. I set it to be upadatable.

But when i want to edit a feature, I get this message :

> Lizmap ne peut pas récupérer cet objet via le WFS

And those ones into the logs : 

> 2019-04-08 17:43:03	90.80.141.17	warning	2019-04-08 17:43:03	[2]	fopen(/tmp/1554738183cfgn4u94a035si3lisovv3igi7_wfs.csv): failed to open stream: Permission denied	/var/www/websig/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php	359
> 
> 2019-04-08 17:43:03	90.80.141.17	warning	2019-04-08 17:43:03	[2]	fwrite() expects parameter 1 to be resource, boolean given	/var/www/websig/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php	364
> 
> 2019-04-08 17:43:03	90.80.141.17	warning	2019-04-08 17:43:03	[2]	fwrite() expects parameter 1 to be resource, boolean given	/var/www/websig/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php	367
> 
> 2019-04-08 17:43:03	90.80.141.17	warning	2019-04-08 17:43:03	[2]	fwrite() expects parameter 1 to be resource, boolean given	/var/www/websig/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php	373
> 
> 2019-04-08 17:43:03	90.80.141.17	warning	2019-04-08 17:43:03	[2]	fclose() expects parameter 1 to be resource, boolean given	/var/www/websig/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php	374

### Environment

 - Lizmap version: 3.2.2
 - QGIS Server version: both 2.18 and 2.14
 - QGIS Project version: 2.18
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): FF
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? 

I tried to create a table instead of a view and I have the same problem.

**Comment by mathieubossaert** [comment]
I downgraded to lizmap 3.1.11 / qgiserver 2.14 as it was next year.
I'll retry later when moving to qgisserver 3.x version.

**Comment by rldhont** [comment]
When the WFS data comes from PostgreSQL, Lizmap creates files to store the result of the request and retrieve it without memory limits. But the files are not destroyed.

@laurentj do you know when in the PHP we can unlink the file ?

The file is created here: https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php#L392
The file is used here: https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/modules/lizmap/controllers/service.classic.php#L1288

**Comment by laurentj** [comment]
I tried a solution, where the file is deleted after sending, (in jResponseBinary). It seems to work. It should be tested with heavy files. Patch is coming.

**Comment by laurentj** [comment]
@mathieubossaert is your /tmp directory on the server is writable by anyone? 

You should have `drwxrwxrwt` when you launch the command `ls -al /`
```
...
drwxrwxrwt  28 root root  4096 avril 16 16:14 tmp
...
```

If this is not the case, execute this command and retry.
```
sudo chmod ugo+w /tmp
```

**Comment by laurentj** [comment]
@rldhont the filename is the same for any feature asked during the same second: `sys_get_temp_dir().'/'.time().session_id().'_wfs'.'.csv'`. If there are many feature requests at the same time, each requests try to overwrite the same file, and it probably causes the problem of @mathieubossaert . Is the Javascript can ask many feature requests at the same time ?

**Comment by rldhont** [comment]
@laurentj yes the Javascript can do many request in the same time.
