### ISSUE TITLE
search bar - not present for some projects

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1191]
hi

search bar is not present for some projects

when lizmap loads a project:
![imagem](https://user-images.githubusercontent.com/10053874/55873267-16a2ee80-5b87-11e9-97a9-6a567edb8e2e.png)

and after it desappears...
you can see montpellier - intranet map example

lwc 3.2 and master

thanks

**Comment by rldhont** [comment]
@josemvm search bar has to be activated for each project where you want to use it.

**Comment by josemvm** [comment]
of course @rldhont :-)
i will update the documentation by myself

**Comment by josemvm** [comment]
documentation has been updated https://github.com/3liz/lizmap-documentation/pull/111

**Comment by rldhont** [comment]
thanks! for the documentation.
