### ISSUE TITLE
Is it possible to remove the project button ?

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#1192]
Hello,

I want to remove project button on some maps to use them like independent maps.

Apparently, this functionnality will be avaible on Lizmap 3.3 (see [here](https://github.com/3liz/lizmap-web-client/pull/1139)).

Meanwhile, is there a way to do it with Lizmap 3.2.2 ? I'm a new user of Lizmap, so any advice will be welcome.

Thank you in advance for your assistance.

Mavialle

**Comment by rldhont** [comment]
You can use a javascript file as described in documentation https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#adding-your-own-javascript

You can find an example here : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/qgis/media/js/montpellier/changeHomeIconUrl.js.example

**Comment by rldhont** [comment]
You can also use the integrated URL provided by the tool permalink.

**Comment by igeofr** [comment]
You can try this code: 

```
lizMap.events.on({
     'uicreated':function(evt){
        $('.nav-list .home').css({
           'display':'none'
        });
        }
   });
```

**Comment by Mavialle** [comment]
Great, it works perfectly with javasrcipt code, thank you !

However, I did not understand how is it possible to create integrated URL ? You have to click on permalink button, select integrate tab, choose a size, but what is the next step ? There is a text frame but is empty. Maybe there is something to do before using the tool?

**Comment by Mavialle** [comment]
And an other question : is it possible to remove other buttons, for exemple the information button ? I tried to adapt javasrcipt code, but it doesn't work (sorry, I don't know javascript). For exemple : 

```
lizMap.events.on({
     'uicreated':function(evt){
        $('.nav-list .metadata.nav-dock').css({
           'display':'none'
        });
        }
   });
```

or

```
lizMap.events.on({
     'uicreated':function(evt){
        $('#mapmenu > div > ul > li.metadata.nav-dock').css({
           'display':'none'
        });
        }
   });
```


Sorry if I ask too many questions, but I'm really curious to know the right way to do it.

Have a good day.

Mavialle
