### ISSUE TITLE
Unique values indicate wrong column values

### ISSUE THREAD

**Issue by remigods** [3liz/lizmap-web-client#1193]
When setting the field as Unique values, Lizmap in edition mode indicate, or not, the values from the right field. Within the same project, one table may display values from the same unique field for all the fields set as Unique values too.

Ex : table A, field 1 (values a, b, c), field 2 (values d, e), field 3 (f), all set as Unique values in QGIS (2.18.18). In Lizmap, field 1 should display values a, b, c, field 2 values d, e, and field 3 value f.
Here, whatever the field to be filled, only d and e values are suggested...
table B (from the same QGIS project) : Unique values set for different fields work perfectly under Lizmap.

- Lizmap version: release_3_2
 - QGIS Server version: 2.18.28
 - QGIS Project version: 2.18.18
 - OS : Windows
 - Browser : Firefox
 - tables stored into PostgreSQL

Thanks in advance,
Rémi

**Comment by rldhont** [comment]
What is the primary key type in table A and table B ?

**Comment by remigods** [comment]
Thanks from contributing to this issue.
table A and table B have both a gid primary key (nextval)

**Comment by nboisteault** [comment]
@rldhont https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/www/js/edition.js#L1011
When there are multiple autocomplete, `selectAutocomplete` has the last value set in it for every autocomplete.

**Comment by rldhont** [comment]
@nboisteault thanks for the review. I know how to fix it.

**Comment by nboisteault** [comment]
@rldhont Good. I was testing [this answer](https://stackoverflow.com/a/35259319), it is good to initiate the good values but autocomplete doesn't show filtered values.

**Comment by remigods** [comment]
Thanks for your help. Should I understand it will be fixed in the next Lizmap version?
Meanwhile, I limited the Unique values to one field per layer, so that the field suggests the proper values.
I am a newcomer in GitHub. Should I close this issue?

**Comment by nboisteault** [comment]
@remigods No we'll close the issue when it will be fixed (soon I think). Thanks for your issue report !

**Comment by rldhont** [comment]
Fixed needs to be tested
