### ISSUE TITLE
Printing issue with CRS

### ISSUE THREAD

**Issue by dobignies** [3liz/lizmap-web-client#1196]
### What is the bug?
Hi,
I use EPSG:4674 (SIRGAS 2000) in my project and layers, but the red rectangle in printing function disappears. When I use UTM projection everything is fine (EPSG:31982). Is there any incompatibility? 
best regards

### Environment

 - Lizmap version: Master
 - QGIS Server version: >3.0
 - QGIS Project version: 3.6.1
 - OS (Windows, Linux, MacOS, Android…): Windows 10
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PostgreSQL

**Comment by nboisteault** [comment]
@rldhont I can reproduce the issue. First catch if I replace `var extent = dragCtrl.layer.features[0].geometry.getBounds();` by `var extent = map.getExtent()` [here](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/map.js#L4172) it prints correctly.

**Comment by rldhont** [comment]
The build of the feature representing the printing surface failed.

**Comment by nboisteault** [comment]
@rldhont [here](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/map.js#L3912) `map.getUnits()` return null. There is no '+units=' for EPSG:4674 in proj4 definition, how do you handle this ?

**Comment by rldhont** [comment]
add the right defs here https://github.com/3liz/lizmap-web-client/tree/master/lizmap/www/Proj4js/defs

**Comment by nboisteault** [comment]
@rldhont the def is good so it doesn't change anything when I put the def in the directory you gave. EPSG:4326 also doesn't have its unit defined but openlayers handle it correctly. Maybe we could assume unit is degree when it is not in proj4 def ?

**Comment by nboisteault** [comment]
@rldhont [here](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Map-js.html#OpenLayers.Map.units) the end of the sentence is interesting.

**Comment by nboisteault** [comment]
@rldhont [here](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/map.js#L1456) is it ok if I replace the line with `,units:projection.proj.units !== null ? projection.proj.units : "degrees"` ?

**Comment by nboisteault** [comment]
@dobignies can you test branch release_3_2 please ?
