### ISSUE TITLE
Make LM "skinnable"

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#12]
Add an option to replace the default logo and colour scheme with one of the choice of users. Probably better implemented in the plugin.

**Comment by rldhont** [comment]
@pcav: @mdouchin has implement a way to change the default LWC theme af10c30c4b36238968f0f23e927d8fe1f5fcd824
Do you think we can close this issue ?

**Comment by pcav** [comment]
You are welcome to close it; however, I think having 2-3 sample themes, and possibly a way to change the main logo through a GUI, are still much requested, if minor, features.

**Comment by rldhont** [comment]
@pcav thanks for your reviews. After testing the feature, you can create specific requests.
