### ISSUE TITLE
2.11beta1 : attribute tables for vector layers, first visit...

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#120]
Je passe en mode français

* Le nom de colonne ne prends pas l'alias mais le nom du champ.
* Pourquoi seulement 5 couches. Frustration...
* Pas de boutton export, mais ça passe en surlignant et copie colle.

qgis-mapserver: 2.4.0-0trusty3
qgis: 2.4.0-Chugiak
docker-lizmap: 2.11beta1

**Comment by jancelin** [comment]
Sinon, merci beaucoup, ça va me changer la vie.

**Comment by jancelin** [comment]
le boutton masquer dans l'interface ne fonctionne pas sur certains mes anciens projets mis à jour

**Comment by rldhont** [comment]
Issue linked to #94
