### ISSUE TITLE
DISABLE POPUP "INFORMAZIONI" AND ZOOM INSTANTLY

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#1201]
Hi,
i would disable the action  - pupup "informazioni" when i click on the layer name

![popuo](https://user-images.githubusercontent.com/28442671/56138713-b1d90100-5f97-11e9-85bc-f231ef3cdd49.JPG)

and when i click the checkbox for viex a layer on a map i would like enable instantly 
the action "zoom at layer".

any suggestions and welcome ..tanks

Roberto

**Comment by rldhont** [comment]
You probably need a script to do so.

**Comment by igeofr** [comment]
@robibrazze, here is the code to hide the information panel

```
lizMap.events.on({
    'lizmapswitcheritemselected': function(e) {
      $('#sub-dock').css({
            'display':'none'
      });
      }
});
```
