### ISSUE TITLE
XYZ Tiles layers slows down Lizmap?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1204]
AFAICT now base layers are replaced by direct usage of native XYZ layers. According to my preliminary tests, however, this slows down rendering very considerably, especially if reprjected to the project main projection (e.g. 4326).
Is this a known limitation, or a bug? Any way to avoid it?
Thanks.

**Comment by rldhont** [comment]
The native XYZ layer is faster  than the old GDAL way of use.
The limitation is probably QGIS Server side ?

**Comment by pcav** [comment]
See a sample here:
https://github.com/3liz/lizmap-web-client/files/3084048/test.zip
How do I check for server side limitations?
Thanks.
