### ISSUE TITLE
tooltip does not work

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1205]
I have tooltips not working in current lizmap master, QGIS 3.4.
Just the sample world vector, field SOVEREIGNT activated as tooltip, causes the tooltip widget to show the gif rotating for ages, and no tooltip is displayed.

**Comment by mdouchin** [comment]
Could you please have a look at the wfs request used when activating the tooltip? It should return data with no errors.

**Comment by pcav** [comment]
How do I best check?

**Comment by pcav** [comment]
BTW, the table is correctly displayed

**Comment by rldhont** [comment]
@pcav can you provide an example ?

**Comment by pcav** [comment]
[test.zip](https://github.com/3liz/lizmap-web-client/files/3084048/test.zip)
here is a sample project with data.
QGIS 3.4.6, Lizmap master from a few days ago.
Thanks!

**Comment by nboisteault** [comment]
Tooltip was crashing when it did not find geometries in data (e.g. Malta in your project).
Fixed with https://github.com/3liz/lizmap-web-client/commit/c4e1d05122fb36ba60621fac48c47468cc0ca2fe
