### ISSUE TITLE
Change project's image doesn't work

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#1214]
Hy!
I have a little problem to change the default project's image. 
I created an image in png format, I renamed her like the qgis project's name (example natureforcity.qgis.png) and putt it in the project's directory. 
But the image does't appear et the result is always the default image.

Is there a specific size to use?

Thanks for your help !!

**Comment by nboisteault** [comment]
@Maverick83000 
Can you provide a public link showing your issue ? Or at least the content of the browser console ?

**Comment by andremano** [comment]
I am having the same issue here, but I am working on a local machine using windows, no link I can share I'm afraid.
However if I inspect the element this is what the source of the image is:

`<div class="liz-project" style="cursor: pointer;">
        <img src="/lizmap/lizmap/www/index.php/view/media/illustration?repository=sigap&amp;project=investigadores" alt="project image" class="liz-project-img">
[...]`

It points to the right repository but the `investigadores.qgs.png` image is being ignored.

**Comment by Marcuzzo77** [comment]
Hi,
I have the same problem.
I tried different versions of QGIS 3.10, 3.14 and export of the qgs project with the lizmap plugin in 3.3.0 and 3.3.1 but nothing positive.
Once the project has been loaded eg. "project_name.ggs" and inserted the thumbnail "project_name.ggs.png" everything works correctly, but if I decide to replace it with a different one while keeping the same name, then it no longer works and the previous one always remains in memory.
The pc on which the package is installed is a debian 10.6.
Any idea?
Marco

**Comment by Marcuzzo77** [comment]
> Hi,
> I have the same problem.
> I tried different versions of QGIS 3.10, 3.14 and export of the qgs project with the lizmap plugin in 3.3.0 and 3.3.1 but nothing positive.
> Once the project has been loaded eg. "project_name.ggs" and inserted the thumbnail "project_name.ggs.png" everything works correctly, but if I decide to replace it with a different one while keeping the same name, then it no longer works and the previous one always remains in memory.
> The pc on which the package is installed is a debian 10.6.
> Any idea?
> Marco


ok I solved it simply with a clear cache and hard reload from the browser.
Marco

**Comment by Gustry** [comment]
I added it in the doc.

**Comment by andremano** [comment]
Hello, I am repoking this issue. This feature does not appear to be working. My ecosystem:
_Ubuntu 20.04, QGIS Server 3.24.1 Lizmap client 3.5.2_. Here is my data structure

```
investigadores.qgs
investigadores.cfg
investigadores.qgs.png
```

Already cleared the cache, refreshed the web browser and even tried to restart Apache but to no avail - the default project image remains. Is anyone else having the same problem? Any solution?

**Comment by nboisteault** [comment]
Hi,
Could you open the browser console, go in Network tab and look for a query with `illustration?repository=YOUR-REPOSITORY-NAME&project=investigadores` click on it and copy here what is the `Headers` tab.

**Comment by andremano** [comment]
Sure, (and thanks for giving it a look)

```
Request URL: http://mydomain/lizmap/index.php/view/media/illustration?repository=got&project=got
Request Method: GET
Status Code: 200 OK (from memory cache)
Remote Address: -----------
Referrer Policy: strict-origin-when-cross-origin
Cache-Control
Content-Disposition: inline; filename="lizmap_mappemonde.jpg"
Content-Length: 14302
Content-Type: image/jpeg
Date: Wed, 06 Apr 2022 16:56:43 GMT
Expires: Thu, 07 Apr 2022 16:56:43 GMT
Pragma
Server: Apache/2.4.41 (Ubuntu)
Provisional headers are shown. Disable cache to see full headers.
Learn more
DNT: 1
Referer: http://mydomain/lizmap/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
```

**Comment by nboisteault** [comment]
Do you have the same header when doing ctrl + F5 (forced refresh) ?

**Comment by andremano** [comment]
Yes, the same.
