### ISSUE TITLE
Select/Filter problems

### ISSUE THREAD

**Issue by andrerjesus** [3liz/lizmap-web-client#1216]
### What is the bug?
Select/Filter return mixed SRID when used layer is not in EPSG4326

May layers are in EPSG29191 stored in a PostgreSQL database and I don't use external sources (OSM/Google). 
When using Select tool i get the error below:

> with source as (
> select
> 	"matricula_c_digito",
> 	"ocorrencias",
> 	"leituras_sem_consumo",
> 	"fiscalizacoes",
> 	"nao_ativa_com_consumo",
> 	"mudancas_hd",
> 	"hd_posicao",
> 	"grupo",
> 	"ligacao_agua",
> 	"ligacao_esgoto",
> 	"geometry" as "geosource"
> from
> 	"comercial"."mvw_fiscalizacao"
> where
> 	true
> 	and ("leituras_sem_consumo" >= 3
> 	and "leituras_sem_consumo" < 6)
> 	and "fiscalizacoes" is null
> 	and "ligacao_agua" = 'Ativa'
> 	and ST_Intersects("geometry",
> 	st_makeenvelope(601077.00024,8278387.023296,603775.755638,8280768.278058,29191))
> 	and ST_Intersects("geometry",
> 	st_geomfromgml('<gml:Polygon xmlns:gml="http://www.opengis.net/gml"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates decimal="." cs="," ts=" ">601077.0002403446,8278387.0232955525 601077.0002403446,8280768.278058062 603775.7556378553,8280768.278058062 603775.7556378553,8278387.0232955525 601077.0002403446,8278387.0232955525</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon>')) )
> --SELECT row_to_json(fc, True) AS geojson
> --FROM (
> --    SELECT
> --        'FeatureCollection' As type,
> --        array_to_json(array_agg(f)) As features
>  select
> 	row_to_json(f, true) as geojson
> from
> 	(
> 	select
> 		'Feature' as type,
> 		concat( 'semconsumo3_5_ativa', '.', "matricula_c_digito") as id,
> 		st_asgeojson(st_transform(lg.geosource::geometry,
> 		4326))::json as geometry,
> 		row_to_json( ( select l from ( select "matricula_c_digito", "ocorrencias", "leituras_sem_consumo", "fiscalizacoes", "nao_ativa_com_consumo", "mudancas_hd", "hd_posicao", "grupo", "ligacao_agua", "ligacao_esgoto" ) as l ) ) as properties
> 	from
> 		source as lg ) as f
> 	--) As fc))

The number count of select features is correct, but the filter doesn't work. My guess the problem lies on this intersect: 

> 	and ST_Intersects("geometry",
> 	st_geomfromgml('<gml:Polygon xmlns:gml="http://www.opengis.net/gml"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates decimal="." cs="," ts=" ">601077.0002403446,8278387.0232955525 601077.0002403446,8280768.278058062 603775.7556378553,8280768.278058062 603775.7556378553,8278387.0232955525 601077.0002403446,8278387.0232955525</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon>'))

### Steps to reproduce the issue

1. qgis project and layers in EPSG29191
2. use lizmap select tool 

### Expected behavior
features able to be selected and filtered

### Environment

 - Lizmap version: 3.2.2
 - QGIS Server version: 3.4.1
 - QGIS Project version: 3.6.2
 - OS (Windows, Linux, MacOS, Android…): Ubunto Server
 - Browser (Firefox, Chrome…): 75.0.3766.2 
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL

**Comment by nboisteault** [comment]
@andrerjesus Please test with Lizmap 3.2.3 and tell us if issue still occurs ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
