### ISSUE TITLE
Requested unknown parameter warnings in attribute table tool

### ISSUE THREAD

**Issue by dobignies** [3liz/lizmap-web-client#1217]
### What is the bug?

Hi,
I have an odd issue with the related tables in attribute table tool. The main parent layer (X) in my project demands 11 spacial and 5 non-spacial 1:M children tables (sensible data). The biggest related spacial layer has about 18000 rows (Y). I'm using the option to limit fetched data to map extent and visibility. The issue happens in one of the rows from X table that requests 5500 rows from Y table. After a few seconds of lag the client returnes many "DataTables warning: Requested unknown parameter..." messages (https://datatables.net/manual/tech-notes/4) referencing the next children tables that seem shuffled or corrupted.
I revised the tables including the relations in PgAdmin/Qgis and I didn't find any problem. The related fields are integer. So, I tested the layer X only with layer Y related and it worked fine. Layers X, Y with non-spacial tables worked well too, but when I add any spacial related table the issue happens again. Anyway, I reduced the amount of data in table Y about to 8000 rows and everything worked well. Perhaps the server (or client) has a limit for the amount of data requested for children tables display. Is there any custom setup in server or client sides? Some workaround?
I appreciate any help.
best regards

### Environment

 - Lizmap version:  Master
 - QGIS Server version:  >3.0
 - QGIS Project version:  3.6.1
 - OS (Windows, Linux, MacOS, Android…):  Windows 7 (localhost)
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into:  PostgreSQL 11

**Comment by nboisteault** [comment]
@dobignies We need an access to your project to identify the issue. Do you have a public link or a private one you can share by email ?

**Comment by dobignies** [comment]
@nboisteault Thanks for the feedback. It's a big intranet project, but I'll try reproduce something at home for share.

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
