### ISSUE TITLE
media content - domain name vs domain ip

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1220]
hi

e.g. : if i request the lizmap projects by ip, the media contents are displayed correctly. next time, if i request the lizmap projects by name, media contents are not displayed.

attribute table
![imagem](https://user-images.githubusercontent.com/10053874/56891539-ba8c0580-6a74-11e9-9abd-6208660bc8cd.png)

popup
![imagem](https://user-images.githubusercontent.com/10053874/56891582-d8596a80-6a74-11e9-8df1-34774f3c55b2.png)

and when i click on the link the browser displays this error:
`{"error":"403 forbidden (you're not allowed to access to this media)"`

to solve it between ip and name (or name and ip) it is necessary to run the command `clean_vartmp.sh`

lwc all
qgis server all

thanks

**Comment by josemvm** [comment]
the same if you have a `ServerAlias` in your virtual host configuration

**Comment by rldhont** [comment]
@josemvm when you update from ip to serverName, do you remove from the server config, the ip config ?

**Comment by josemvm** [comment]
@rldhont no, i keep the configuration, like this:

`WMS server URL` `http://myHostName.myDomainName.pt/cgi-bin/qgis_mapserv.fcgi
`

**Comment by rldhont** [comment]
@josemvm the media is manage by lizmap, the alias and ip is for lizmap.

**Comment by josemvm** [comment]
> to solve it between ip and name (or name and ip) it is necessary to run the command clean_vartmp.sh

**Comment by rldhont** [comment]
@josemvm I know it.

@laurentj has identified the code where the problem comes from

**Comment by josemvm** [comment]
ok, thanks

**Comment by laurentj** [comment]
Fixed

**Comment by laurentj** [comment]
thanks for your report
