### ISSUE TITLE
WFS additional output formats on QGIS Server 3+

### ISSUE THREAD

**Issue by dobignies** [3liz/lizmap-web-client#1224]
### What is the bug?
I tried to install wfsOutputExtension plugin but no success. It returns missing classfactory (iface) instruction. I added the iface codes like other qgis server 3+ plugins and the installation is ok now [wfsOutputExtension.zip](https://github.com/3liz/lizmap-web-client/files/3136285/wfsOutputExtension.zip), but I can't get no additional formats in GetCapabilities of the WFS service. Using wfsfilter from 1.0.1 branch the export dialog in LWC returns all formats, but it exports html .zip files (0 bytes). Is there any extra setup to work on Windows?

Qgis server log:
Python path:
['C:\\OSGeo4W64\\apps\\qgis\\python', 'C:\\OSGeo4W64\\apps\\Python37', 'C:\\OSGeo4W64\\apps\\Python37\\DLLs', 'C:\\OSGeo4W64\\apps\\Python37\\lib', 'C:\\OSGe', 'C:\\OSGeo4W64\\bin\\python37.zip', 'C:\\OSGeo4W64\\apps\\qgis\\bin', 'C:\\OSGeo4W64\\apps\\Python37\\lib\\site-packages', 'C:\\OSGeo4W64\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\OSGeo4W64\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\OSGeo4W64\\apps\\Python37\\lib\\site-packages\\Pythonwin']
19:30:28 INFO wfsOutputExtension[8020]: WFSFilter.init
19:30:28 INFO wfsOutputExtension[8020]: WFSFilter.tempdir: C:\WINDOWS\Temp\qgis_wfs
19:30:28 INFO Server[8020]: Server plugin wfsOutputExtension loaded!
19:30:28 INFO Server[8020]: Server python plugins loaded
19:30:28 INFO Server[8020]: ******************** New request ***************
19:30:28 INFO Server[8020]: SERVER_NAME: localhost
19:30:28 INFO Server[8020]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?SERVICE=WFS&REQUEST=GetCapabilities&MAP=/webserver/data/prod/rep1/Teste.qgs
19:30:28 INFO Server[8020]: REMOTE_ADDR: ::1
19:30:28 INFO Server[8020]: HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
19:30:28 INFO wfsOutputExtension[8020]: WFSFilter.requestReady
19:30:28 INFO Server[8020]: MAP:/webserver/data/prod/rep1/Teste.qgs
19:30:28 INFO Server[8020]: REQUEST:GetCapabilities
19:30:28 INFO Server[8020]: SERVICE:WFS
19:30:29 INFO wfsOutputExtension[8020]: WFSFilter.responseComplete
19:30:29 INFO Server[8020]: Request finished in 1146 ms
### Environment

 - Lizmap version: master
 - QGIS Server version: 3+
 - QGIS Project version: 3.6.2
 - OS (Windows, Linux, MacOS, Android…): Windows 10
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite

**Comment by dobignies** [comment]
Le plugin fonctionne pleinement maintenant. Merci beaucoup pour la mise à jour.
I'd suggest the insertion of the classfactory (iface) to avoid error messages during the installation. I verified too that new profile plugin path is mandatory in php7x.conf setup for Windows.
regards

**Comment by nboisteault** [comment]
@rldhont it is related to wfsOutputExtension plugin. I let you see if suggestion above has to be added to plugin.

**Comment by dobignies** [comment]
Check the file. It works fine.
[wfsOutputExtension.zip](https://github.com/3liz/lizmap-web-client/files/3433610/wfsOutputExtension.zip)

**Comment by rldhont** [comment]
@dobignies the `classfactory (iface)` should not be necessary for server plugin. This instruction is for Desktop plugin.

**Comment by rldhont** [comment]
I have reopen wfsOutputExtenion issue https://github.com/3liz/qgis-wfsOutputExtension/issues/2
