### ISSUE TITLE
Server cache not working on Lizmap QGIS 3.X

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#1227]
Hi there!

I hope you guys are doing great! 

I am getting problems with showing upp layers with configuration Server cache. 
I am using Xampp/Apache, QGIS server 3.6, Lizmap 3.2 on Windows server 2012. 

<img width="530" alt="qserver" src="https://user-images.githubusercontent.com/12575941/57079080-e6ff8600-6cef-11e9-81cd-ad76d6efe2e0.PNG">

Does anyone has the same problem? any idea what it may be wrong ?
B.Regards!
Abel

**Comment by nboisteault** [comment]
You should use Lizmap 3.3.x with QGIS Server 3.6. I close issue, please reopen if issue remains with correct setup.

**Comment by lmwu** [comment]
This also happens to me.
![image](https://user-images.githubusercontent.com/12655592/80171109-1bb0cf80-861c-11ea-9888-0d6dcb1b9c3c.png)

Lizmap web client Ver. 3.3.5
QGIS Server Ver. 3.12
