### ISSUE TITLE
Different layout in the embedded map

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#1228]
### What is the bug?
There's a strange problem with the embedded map. Creating a map in QGIS with a selected layer and a background map, for example OSM, in the standard layout everything works well, if instead I insert this same map in a web page, the embedded map, the layout is different i.e. another layer is selected at random and not the real one and also if there are for example two background maps, OSM and Stamen, and I selected OSM, in the embedded map there is the map Stamen. I cleared the cache and tried again several times but nothing to do. Really strange.

### Steps to reproduce the issue

The problem is only in the embedded map

### Expected behavior

The same layout in normal and embedded map

### Environment

 - Lizmap version: 3.4pre
 - QGIS Server version: 2.18.17
 - QGIS Project version: 3.6.1
 - OS (Windows, Linux, MacOS, Android…): Linux, Ubuntu
 - Browser (Firefox, Chrome…): Firefox, Safari, Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

**Comment by nboisteault** [comment]
You have to use QGIS Server >= 3.4 with lizmap >= 3.3.x. I close please reopen if issue still occurs with correct setup.
