### ISSUE TITLE
Allow editing of a non geometrical table

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1230]
It is currently possible to display a table even if it does not have a geometry, e.g. `table_operation` in:
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=lrs_project
But apparently it is not possible to add records or edit existing ones, even though this is enabled both in the plugin and in the Project Properties.

**Comment by tethysgeco** [comment]
Which Lizmap/Qgis version are you using?
With Lizmap 3.2.1 and Qgis server 2.18 editing of a non geometrical table seems to work fine.

**Comment by pcav** [comment]
Lizmap 3.3pre1 and QGIS server 3.4.7
Thanbks for the feedback.

**Comment by pcav** [comment]
Sorry, it works indeed.

**Comment by ludovico85** [comment]
Hi, I'm facing the same issue. I've a table in postresql/postgis without geometry (Biotopi umidi dati variabili). In Lizmap plugin I've activated the necessary options and also in the project properties.
When I try to add a row in the table I receive the following message: "Activated line needed" 

How to solve?
Thanks.

Lizmap 3.4.0
Qgis server 3.16


![error](https://user-images.githubusercontent.com/24815399/128038214-497b68a0-d182-4cae-9245-8f5a9f80ea00.PNG)

![plugin](https://user-images.githubusercontent.com/24815399/128039296-15a2dcf0-d69d-40e1-89a7-ed5ffbb743d9.PNG)

![server](https://user-images.githubusercontent.com/24815399/128039419-8527dd86-d3c2-42a8-81d2-2d0897c85689.PNG)
