### ISSUE TITLE
Search by coordinates with OpenStreetMap

### ISSUE THREAD

**Issue by elvovo** [3liz/lizmap-web-client#1232]
Hi everyone,

is it possible to set the search by address with the "internal" service of OpenStreetMap and not Nominatim?
I need to set the search by coordinates.

Thank you all.
Giorgio

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/268

**Comment by josemvm** [comment]
it's an essential function in cartography/GIS
please develop this functionality

thanks on more time

**Comment by josemvm** [comment]
maybe resusing part of this code https://github.com/rldhont/lizmap-web-client/commit/32e7de9e2242b0e72349e8157fa95d016fb61be8 :-)

**Comment by josemvm** [comment]
i think this is a basic function on GIS, locate by coordinates!

and we have the basic work here:
![imagem](https://user-images.githubusercontent.com/10053874/81539915-d3f2ad80-9368-11ea-8dda-681904da9ba9.png)

the user chooses theCRS and reaches the map at that point (center, zoom and highlights the point)

this was my first issue here on LWC https://github.com/3liz/lizmap-web-client/issues/268

thanks

**Comment by Gustry** [comment]
> is it possible to set the search by address with the "internal" service of OpenStreetMap and not Nominatim?

@elvovo I don't understand what do you mean by "internal" service instead of Nominatim. OSM.org is using only Nominatim, no?

> Search by coordinates with OpenStreetMap

Do you mean searching OSM objects around coordinates? Can you show us example strings you would to use?
