### ISSUE TITLE
Issue with with hierarchization when rule-base style

### ISSUE THREAD

**Issue by bgisb** [3liz/lizmap-web-client#1233]
Hi!

Is it expected that when I have a style based on a rule, I do not see the hierarchy style in the application, such as in QGIS? With grouping layer everything is ok, but when it comes to a rule-based style, there are problems...I do not see "steps/hierarchy".

1.Lizmap
![Zrzut ekranu 2019-04-29 o 11 21 00](https://user-images.githubusercontent.com/48524622/57291076-09621c80-70bf-11e9-8d27-aaca6909b651.png)
2. Layer panel
![Zrzut ekranu 2019-04-29 o 11 21 07](https://user-images.githubusercontent.com/48524622/57291089-0ebf6700-70bf-11e9-8434-d8ccd592e41f.png)
3.Style (rule-based)
![stylerulebased](https://user-images.githubusercontent.com/48524622/57291107-1848cf00-70bf-11e9-9b8b-885910a4803f.png)

Any advice?

**Comment by igeofr** [comment]
Unless I'm mistaken, identical request : [#422](https://github.com/3liz/lizmap-web-client/issues/422)

**Comment by bgisb** [comment]
You're right. Thanks!
