### ISSUE TITLE
Zoom to coordinates

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1241]
Add the possibility to zoom on the coordinates entered by the user (Like the QGIS 2.18 plugin - ZoomToCoordinates).

<img width="341" alt="image" src="https://user-images.githubusercontent.com/7761073/57583771-701e7600-74c3-11e9-87f3-933d016e818f.png">

**Comment by josemvm** [comment]
hi @igeofr 

or something like this:

![imagem](https://user-images.githubusercontent.com/10053874/57633624-b6df9f00-759b-11e9-94f6-ce4808fb1437.png)

https://github.com/3liz/lizmap-web-client/issues/1232
https://github.com/3liz/lizmap-web-client/issues/268

**Comment by igeofr** [comment]
Exactly!

**Comment by josemvm** [comment]
@rldhont @mdouchin what do you think about this issue?

**Comment by gioman** [comment]
@rldhont @mdouchin was this feature request ever implemented? if not please contact me I'm interested in having it developed. Thanks in advance.

**Comment by Gustry** [comment]
It seems a duplicated feature request to #268 
Let's close this one.

@gioman It has not been implemented
