### ISSUE TITLE
value relation widget - drive down lists (filter expression)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1242]
hi

i noticed that the old "value relation form" plugin was implement  into the core parts of QGIS 3
https://www.northrivergeographic.com/archives/qgis-3-2-drive-down-lists-aka-value-relation-widget

i think this feature is very important for edition operations in lizmap!

![imagem](https://user-images.githubusercontent.com/10053874/57637576-ac290800-75a3-11e9-8dca-b0f2b7ceb8c0.png)

but lizmap does´t recognize **filter expression** as above

![imagem](https://user-images.githubusercontent.com/10053874/57637024-4720e280-75a2-11e9-97ef-43031aec8a01.png)

thanks

**Comment by josemvm** [comment]
the value relation widget without filter expression is like a value map widget...

**Comment by josemvm** [comment]
@nboisteault what can you tell me about this issue?

**Comment by josemvm** [comment]
@rldhont @mdouchin what do you think about this issue?

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/636

**Comment by josemvm** [comment]
@Gustry and all developpers i'am talking about this feature and https://github.com/3liz/lizmap-web-client/issues/636 instead of this https://github.com/3liz/lizmap-web-client/issues/350

> how long can we wait for this essential feature for edition on lizmap?
this enhancement would be greatly appreciated if it could be integrated in upcoming 3.4

thanks

**Comment by rldhont** [comment]
Work in progress in lizmap-plugin for server side to evaluate QGIS expression. https://github.com/3liz/lizmap-plugin/pull/196 funded by Conseil Departemental des Pyrénées-Atlantiques.

**Comment by josemvm** [comment]
good news!!! thanks to Conseil Departemental des Pyrénées-Atlantiques and thanks to you :-)

**Comment by josemvm** [comment]
hi @rldhont can you tell us if this work is already completed?
thanks

**Comment by rldhont** [comment]
Not yet...

**Comment by nboisteault** [comment]
@josemvm did you test the new feature? If it is ok can you close this issue?

**Comment by josemvm** [comment]
@nboisteault not yet. i think it needs a documentation...

**Comment by nboisteault** [comment]
@josemvm Good idea! Please make a PR [here](https://github.com/3liz/lizmap-documentation#contributing-to-the-english-documentation).

**Comment by nboisteault** [comment]
I close. @josemvm open a ticket for documentation please.
