### ISSUE TITLE
date/time widget - field format/date time

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1244]
postgresql - defalt value `now()`
field format: **data**

![imagem](https://user-images.githubusercontent.com/10053874/57792928-0d81e000-7738-11e9-8543-ab3e0cf67396.png)

field format: **date time**
postgresql - defalt value `now()`

![imagem](https://user-images.githubusercontent.com/10053874/57793017-399d6100-7738-11e9-90c3-eb1b67459c9d.png)

in this case the lizmap doesn't show the current date/time value

thanks

**Comment by mdouchin** [comment]
I think depending on postgresql, now() returns also microseconds. Could you try `SELECT now();` in your database and give the reponse here ?

We should probably truncate the microseconds part in Lizmap before setting the Calendar widget. @laurentj any idea ?

We should probably use instead
`SELECT now()::timestamp(0);`

**Comment by josemvm** [comment]
hi @mdouchin 

`SELECT now();`
"2019-05-15 21:50:24.962766+01"

`SELECT now()::timestamp(0);`
"2019-05-15 21:51:56"

i'm using
`timestamp(0) without time zone DEFAULT now(),`
"2019-05-15 21:51:56"

i think we should probably truncate the **seconds** part before setting the calendar widget

thanks

**Comment by rldhont** [comment]
linked to #957 ?

**Comment by josemvm** [comment]
yes, i think so

**Comment by laurentj** [comment]
Fixed widget generators from Jelix
