### ISSUE TITLE
Having in the url bar, the url corresponding to the context of the map

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1245]
### Is your feature request related to a problem? Please describe

If we refresh the map by clicking on the "reload" button of the browser, we loose the context of the map : selected layers, position in the map, zoom etc..

it's a bad user experience.

### Describe the solution you'd like

When we change the zoom or the position in the map and when we change the selected layers, the url into the URL bar of the browser should be updated so it correspond to what it is displayed. It seems we should set the same url as proposed in the permalink feature.

We could use the history API in javascript to change the url.

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/502

**Comment by nboisteault** [comment]
Done
