### ISSUE TITLE
Error showing label to prevent overlap

### ISSUE THREAD

**Issue by dmiolo** [3liz/lizmap-web-client#1251]
I set the option on labels "Discourage other labels from covering features in this layer" in qGIS on some linear layers, and in qGIS the labels are displayed correctly not overlapping the linear layers as shown in the attached image.

![1](https://user-images.githubusercontent.com/43961850/58318196-96270d00-7e17-11e9-8f6a-d8fee03c1419.PNG)

However, in Lizmap the same project does not maintain these settings, and the labels overlap with the lines, as shown in the attached image.

![2](https://user-images.githubusercontent.com/43961850/58318273-b9ea5300-7e17-11e9-9315-9baa3a5c90f3.PNG)

Am I wrong with some settings or does Lizmap load these settings?
Thank you

 - Lizmap version: 3.15
 - QGIS Server version: 2.18
 - QGIS Project version: 2.18
 - OS (Windows, Linux, MacOS, Android…):  Ubuntu 14
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgres

**Comment by gioman** [comment]
@dmiolo very unlikely to be a LMWC problem, is much more likely to be a QGIS Server one. But QGIS (Server) 2.* is discontinued, you should try to publish your project with QGIS Server 3 and check if the WMS layers show the same issue.

**Comment by nboisteault** [comment]
@dmiolo please follow @gioman advice and give us a feedback.

**Comment by dmiolo** [comment]
Sorry I was very busy lately.
However I have updated qGIS Server to the latest version but the display error is the same.

**Comment by nboisteault** [comment]
@dmiolo probably a QGIS Server bug. Please open an issue [here](https://github.com/qgis/QGIS/issues).
