### ISSUE TITLE
Error Editing Layer ( PostgreSQL )

### ISSUE THREAD

**Issue by FPaulsen** [3liz/lizmap-web-client#1253]
QGIS 3.4.8 
Lizmap 3.3 / 3.4pre.190426
Postgres 10 
Ubuntu 18.04

Creating an new Point is working in QGIS.
On Lizmap the Popup open when I click on the Point.
Clicking on "Edit" - nothing happens

Delete is working, Create new point is not possible

Log: 
Edit: 
Nothing in the Log.
Editing Menu on the left side doesn't open

on another testing system - QGIS 3.4.7, same lizmap - Version ist works
Postgresql Server Version 9.6

Creating Point: 
2019-05-25 18:10:28     31.16.173.23    error   2019-05-25 18:10:28     31.16.173.23    [403]   unzulässige Anfrage(ERROR:  invalid input syntax for integer: ""
LINE 3: ...M "KFVUSERGIS"."KFV_USER_HYDRANTEN" WHERE True AND "id" = ''
                                                                     ^(
        WITH source AS (
         SELECT "id" FROM "KFVUSERGIS"."KFV_USER_HYDRANTEN" WHERE True AND "id" = ''
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            'Löschwasserentnahmestellen',
            '.',
            "id") AS id,
                        Null As geometry,
            
                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "id"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))     /var/www/lizmap-web-client-master/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php     174
        /lizmap/index.php/lizmap/edition/editFeature?project=kfv&repository=100&layerId=KFV_USER_HYDRANTEN20180827075703574&status=0
array (   'project' => 'kfv',   'repository' => '100',   'layerId' => 'KFV_USER_HYDRANTEN20180827075703574',   'status' => '0',   'module' => 'lizmap',   'action' => 'edition:editFeature', )

        0       pgsqlDbConnection->_doQuery()   /var/www/lizmap-web-client-master/lib/jelix/db/jDbConnection.class.php : 123
        1       jDbConnection->query()  /var/www/lizmap-web-client-master/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 382
        2       lizmapWFSRequest->getfeaturePostgres()  /var/www/lizmap-web-client-master/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 137
        3       lizmapWFSRequest->getfeature()  /var/www/lizmap-web-client-master/lizmap/modules/lizmap/controllers/edition.classic.php : 242
        4       editionCtrl->getWfsFeature()    /var/www/lizmap-web-client-master/lizmap/modules/lizmap/controllers/edition.classic.php : 386
        5       editionCtrl->editFeature()      /var/www/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php : 225
        6       jCoordinator->process() /var/www/lizmap-web-client-master/lizmap/www/index.php : 23

**Comment by FPaulsen** [comment]
Additionale Information:

The Projektfile from QGIS 3.4.7 works with Editing, Deleting an New Points
on qgis - server 3.4.8, Lizmap3.3pre , PostgreSQL10.

After saving the project in QGIS 3.4.8 it dosn´t work

**Comment by FPaulsen** [comment]
I have Setup an new system 
Ubuntu 18.04 - QGIS Server 2.18 , Lizmap 3.3rc1

QGIS Project saved in QGIS 2.18

The error, that it is not possible to edit a point in Lizmap exists ohne on Safari 12.1.1 
Firefox 67 / Chrome is working.

**Comment by Hessamj** [comment]
@FPaulsen could you help me here https://github.com/3liz/lizmap-web-client/issues/1256 and https://github.com/3liz/lizmap-web-client/issues/1258

**Comment by lore423** [comment]
I've tested Lizmap with the following parameters and it works (for edition tool):

Ubuntu 18.04.2 LTS
QGIS 3.4.8
QGIS-server 3.4.8
Lizmap 3.3rc2 
Postgres 9.6.5 + PostGIS 2.1

**Comment by rmarzocchi84** [comment]
I have a similar problem. Edition do not works:

Ubuntu 16.04
QGIS Server 3.4.9
Lizmap Latest
Postgresl 10.9 + PostGIS 2.4.4

This is the error log: 

error	2019-06-27 12:31:37	[0]	dbtools, pgsql: unknown table	/var/www/lizmap-3.3-git/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php	242

**Comment by nboisteault** [comment]
Does issue still occur in Lizmap 3.3.4 ?

**Comment by Kirag-hue** [comment]
Hi! I have the Same problem
Ubuntu 18.04
QGIS 2.18
Lizmap 3.2.9
Postgres 10.12

The problem occurred when creating a layer with a filter based on the "Sety" attribute
If you make a layer without a filter, the error does not appear

2020-03-17 18:37:04	176.59.102.107	error	2020-03-17 18:37:04	176.59.102.107	[403]	 неверный запрос (ERROR:  syntax error at or near ")"
LINE 4:         )
                ^(
        WITH source AS (
         SELECT "id" FROM "NetW"."SS" WHERE True AND "Sety"= 3 AND 
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            'ПС_Сет._район_3',
            '.',
            "id") AS id,
                        Null As geometry,
            
                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "id"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))	/var/www/lizmap-web-client-3.2.0/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174
	/lm/index.php/lizmap/edition/modifyFeature?repository=4&project=u10&layerId=SubStation_b5d6c24a_9d64_435d_8f6b_ce8fc642c78f&featureId=1210
array (   'repository' => '4',   'project' => 'u10',   'layerId' => 'SubStation_b5d6c24a_9d64_435d_8f6b_ce8fc642c78f',   'featureId' => '1210',   'module' => 'lizmap',   'action' => 'edition:modifyFeature', )

	0	pgsqlDbConnection->_doQuery()	/var/www/lizmap-web-client-3.2.0/lib/jelix/db/jDbConnection.class.php : 127
	1	jDbConnection->query()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 419
	2	lizmapWFSRequest->getfeaturePostgres()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 160
	3	lizmapWFSRequest->getfeature()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/controllers/edition.classic.php : 242
	4	editionCtrl->getWfsFeature()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/controllers/edition.classic.php : 320
	5	editionCtrl->modifyFeature()	/var/www/lizmap-web-client-3.2.0/lib/jelix/core/jCoordinator.class.php : 225
	6	jCoordinator->process()	/var/www/lizmap-web-client-3.2.0/lizmap/www/index.php : 23

**Comment by kirag-ozyaz** [comment]
Hi! I have the Same problem
Ubuntu 18.04
QGIS 2.18
Lizmap 3.2.9
Postgres 10.12

The problem occurred when creating a layer with a filter based on the "Sety" attribute
If you make a layer without a filter, the error does not appear

2020-03-17 18:37:04	176.59.102.107	error	2020-03-17 18:37:04	176.59.102.107	[403]	 неверный запрос (ERROR:  syntax error at or near ")"
LINE 4:         )
                ^(
        WITH source AS (
         SELECT "id" FROM "NetW"."SS" WHERE True AND "Sety"= 3 AND 
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            'ПС_Сет._район_3',
            '.',
            "id") AS id,
                        Null As geometry,
            
                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "id"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))	/var/www/lizmap-web-client-3.2.0/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174
	/lm/index.php/lizmap/edition/modifyFeature?repository=4&project=u10&layerId=SubStation_b5d6c24a_9d64_435d_8f6b_ce8fc642c78f&featureId=1210
array (   'repository' => '4',   'project' => 'u10',   'layerId' => 'SubStation_b5d6c24a_9d64_435d_8f6b_ce8fc642c78f',   'featureId' => '1210',   'module' => 'lizmap',   'action' => 'edition:modifyFeature', )

	0	pgsqlDbConnection->_doQuery()	/var/www/lizmap-web-client-3.2.0/lib/jelix/db/jDbConnection.class.php : 127
	1	jDbConnection->query()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 419
	2	lizmapWFSRequest->getfeaturePostgres()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 160
	3	lizmapWFSRequest->getfeature()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/controllers/edition.classic.php : 242
	4	editionCtrl->getWfsFeature()	/var/www/lizmap-web-client-3.2.0/lizmap/modules/lizmap/controllers/edition.classic.php : 320
	5	editionCtrl->modifyFeature()	/var/www/lizmap-web-client-3.2.0/lib/jelix/core/jCoordinator.class.php : 225
	6	jCoordinator->process()	/var/www/lizmap-web-client-3.2.0/lizmap/www/index.php : 23

**Comment by mdouchin** [comment]
there is a missing space in the SQL query here `"Sety"= 3` I will propose a bug fix soon

**Comment by nboisteault** [comment]
@mdouchin gentle ping :)

**Comment by gcalibris** [comment]
Same issue like to @FPaulsen for a long time (lizmap 3.4pre.190808).

**Comment by mdouchin** [comment]
To tackle this issue, please reporters give more information:

* copy/paste the definition of the layer in the QGIS project **WITHOUT PASSWORD** or better add it here as an attachment (after complete removal of sensitive data !)
* tell if you use a FILTER in the `Source` tab of the QGIS layer properties
* check if you have not unchecked the checkbox "WFS" for the primary key field in the tabe `Source fields` of the layer properties

**Comment by kirag-ozyaz** [comment]
Закрывайте, все исправлено! Почему то все стало нормально. :(
Close it, everything is fixed! For some reason, everything became normal. :(
