### ISSUE TITLE
Attribute tables not shown, cursor wheel spinning; search not working

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1255]
In several projects, e.g. [0] (all based on PotsgreSQL layers, BTW) attribute tables are not shown, and the cursor is spinning forever. I cannot find a reason for this. The same project works when based on shapefile.
In the same project, the search widget is shown, but it is not working.
Thanks for any hint. 

[0]http://webgis.provincia.belluno.it/index.php/view/map/?repository=mappe&project=test4

**Comment by pcav** [comment]
.qgs and .cfg available on request. QGIS 3.4 + Lizmap 3.3rc1

**Comment by mdouchin** [comment]
Please write here the <datasource> content of one of the layers, obviously with no sensitive information.

**Comment by pcav** [comment]
[test4.zip](https://github.com/3liz/lizmap-web-client/files/3234071/test4.zip)
here you go

**Comment by pcav** [comment]
error log is also available

**Comment by mdouchin** [comment]
@pcav could test the last release_3_2 or release_3_3 branch. I think I debugged your issue with this commit, related to a new QGIS 3 property `checkPrimaryKeyUnicity` in the PostGIS datasource.

https://github.com/3liz/lizmap-web-client/commit/1c4b67e6b5b8234d734fa47946055530e2686330
or
https://github.com/3liz/lizmap-web-client/commit/1c4b67e6b5b8234d734fa47946055530e2686330

**Comment by pcav** [comment]
Thanks @mdouchin , will try

**Comment by mdouchin** [comment]
Ok, please close this issue if the commits fix this issue. 

In the future, we plan to use a QGIS Server python plugin (lizmap) to read the project data, such as PostGIS layers information. This will make Lizmap Web Client less prone to have bugs when new QGIS project properties are created between versions

**Comment by pcav** [comment]
Confirmed, it works. Thanks a lot. Wouldn't this deserve a `rc2` release?
