### ISSUE TITLE
Qgis server and Lizmap latest version

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#1257]
Hello,
Maby this is not the place to ask but i am a newby .

Where can i download always the last version of Lizmap ??

Thanks

**Comment by Hessamj** [comment]
Hi
I think you'll find it here https://github.com/3liz/lizmap-web-client/tags

**Comment by nboisteault** [comment]
The last master is [here](https://github.com/3liz/lizmap-web-client/archive/master.zip). Master means that it might be unstable.
If you want stable versions link given by @Hessamj is good. You need 3.2.x if you use QGIS Server 2.18 or 3.3.x (today there is only 3.3rc1) if you use QGIS Server 3.4.

**Comment by NvBgm** [comment]
Thank you,
Found Lizmap 3.3rc1,   AGIS server 3.4. 

First continuously get it not running ( server not found error) but after a wile i discover that apache 2.4 can not handle the old command "allow from all" witch is in the .htaccess file.
I change it to "Require all granted" and it is running very good.
Thank you for the info...

**Comment by nboisteault** [comment]
Thank you for your feedback.

**Comment by pieri70** [comment]
Hello
we are maintaining our servers with lizmap wc.
Based on this post If I want to use Qgis server 3.4.x I need to use Lizmap WC 3.3.x.
3.2.x don't work with qgis server 3.4.x?
Is 3.3.x stable?

Thanks
Pietro
