### ISSUE TITLE
Using PostgreSQL database in lizmap

### ISSUE THREAD

**Issue by Hessamj** [3liz/lizmap-web-client#1258]
Under windows 10, QGIS server 2.18 and lizmap master
I tried to configure the `profiles.ini.php` lizmap to use the pgsql but without resutat.
could you help me find a solution to load data (layers) from a PostgreSQL database ?

**Comment by nboisteault** [comment]
@Hessamj did you try [vagrant](https://github.com/3liz/lizmap-web-client/tree/master/vagrant) ?

**Comment by Gustry** [comment]
> could you help me find a solution to load data (layers) from a PostgreSQL database ?

@Hessamj Do you want to use Postgresql for storing vector layers and/or lizmap config
If it's only vector layers (like it seems to be according to your message), you have nothing to do. Just be sure that the database is accessible from your QGIS Server with the same credentials.

**Comment by Hessamj** [comment]
@Gustry Thanks for your answer, how can I check that PostgreSQL is accessible from QGIS Server?

**Comment by Gustry** [comment]
The documentation was updated with the different use cases of PG for Lizmap Web Client : https://docs.lizmap.com/current/fr/install/pre_requirements.html#postgresql

> how can I check that PostgreSQL is accessible from QGIS Server?

With `pgsql` by making a request from the QGIS host server or by loading a project with Postgresql layer (checking QGIS server logs if the layer is not displayed)
