### ISSUE TITLE
Server configuration problem

### ISSUE THREAD

**Issue by CassperB** [3liz/lizmap-web-client#1259]
Hello,

I have a problem configuring Qgis server. I followed the instructions listed on this site (https://docs.lizmap.com/current/en/install/windows.html#qgis-server-installation) and after seemingly successful installation I can not open any projects that I uploaded to the server. When I try to open any project, the web site freezes on loading screen and reports the Service non disponible. Lizmap-error.og reports error AH01630: client denied by server configuration: C:/OSGeo4W64/apps/qgis-ltr/binqgis_mapserv.fcgi.exe. I am running Lizmap web client 3.1.20 and qgis server 3.6.3.1.  Also w when I try to run the qgis_mapserv.fcgi.exe i got an error that a lot of dll (libfcgi, QT5core, Qt5xml.dll) are missing.  I am new at this so any help will be much appreciated

**Comment by gioman** [comment]
@CassperB you must first test if QGIS server works itself (as a WMS/WFS server), if it doesn't then LM has nothing to do with your issue.

Try do a GetCapabilities request in a browser, pointing QGIS Server to one of your projects.

**Comment by nboisteault** [comment]
@CassperB With Windows you should use [vagrant](https://github.com/3liz/lizmap-web-client/tree/master/vagrant). Also you should use lizmap [3.3rc1](https://github.com/3liz/lizmap-web-client/releases/tag/3.3rc1) with QGIS Server 3.4.
