### ISSUE TITLE
Permalink functionalaity broken

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#126]
It seems that in the lastest LM releases the permalink functionality is broken. Try for example

http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep1&project=plan_parc

and leave selected just one layer: by clicking on the permalink the new map has all layers selected instead of the only one of the original map, and anyway no layers are shown in the canvas.

**Comment by rldhont** [comment]
Hi @gioman 
I can't reproduce the bug:
* http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep1&project=plan_parc&zoom=3&lat=2350998.78035&lon=937822.38698&layers=BTTTTTTTTTTTTTF
* http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep1&project=plan_parc&zoom=3&lat=2350998.78035&lon=937822.38698&layers=BTFFFTTTTFTFTTF

Re-open if needed

**Comment by gioman** [comment]
Hi @rldhont see this screencast

https://www.dropbox.com/s/iuj0jkj6rwslti7/permalink.mp4?dl=0

**Comment by rldhont** [comment]
Hi @gioman,

I have tested permalink after zooming and it's work.

You pointing that only deactivated layers did not changed permalink.

**Comment by gioman** [comment]
Hi @rldhont 
yes I just realized that the difference was the zoom. I didn't realized at the time I filed the ticket. Cheers!

**Comment by rldhont** [comment]
Hi @gioman, I just realized the same thing
