### ISSUE TITLE
Checkbox always unticked when updating data

### ISSUE THREAD

**Issue by remigods** [3liz/lizmap-web-client#1261]
Hi,
I set a boolean field in a table. When the users tick the checkbox, it is shown as True in the data tool (so far so good).
But when a user wants to edit the data with True value, the checkbox from the form is not checked anymore, and stays as False when the edited row is saved.
I though it was because of the default value set in Postgresql and QGIS (set as False), but I observed the same behaviour when I dropped this default constraint (in both Postgres and QGIS).
I would like the value of this boolean field (true for instance) stays as true when editing that row.
Any idea please?
Thanks

**Comment by rldhont** [comment]
Which lizmap, QGIS Server and QGIS Project version ?

**Comment by rmarzocchi84** [comment]
I have the opposite problem. 

In postgresql not null field with false option. When I try to edit filed the checkbox is always checked

QGIS Project 3.4.9
QGIS Server 3.4.9 
Lizmap 3.3.rc2

**Comment by rmarzocchi84** [comment]
Tested also with QGIS 3.9.10 (both server and desktop)

I do not understand the .qgs file sintax:

        ```
<field name="restituito">
          <editWidget type="CheckBox">
            <config>
              <Option type="Map">
                <Option value="" type="QString" name="CheckedState"/>
                <Option value="" type="QString" name="UncheckedState"/>
              </Option>
            </config>
          </editWidget>
        </field>
```

Perhaps a QGIS bug? or it is related to https://github.com/3liz/lizmap-web-client/issues/958 ?

**Comment by rmarzocchi84** [comment]
similar to this bug https://github.com/3liz/lizmap-web-client/issues/1069#issuecomment-514535427

**Comment by nboisteault** [comment]
I can confirm issue with release_3_2.

**Comment by nboisteault** [comment]
@laurentj If I insert a `var_dump($record);` [here](https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L429) I get a `'t'` value instead of a boolean `true`.

`object(stdClass)#132 (9) {
...
  ["boolean_field"]=>
  string(1) "t"
...
}`

If I force to `true` for my checkbox field its representation in the form is correct. Do you have any idea why the value is `'t'` ?

**Comment by nboisteault** [comment]
@Hi remigods
Did you put other values than 't' and 'f' for your checkbox ?

**Comment by rmarzocchi84** [comment]
I think, but I could be wrong,  't' is the value returned from postgresql DB for boolean.

**Comment by nboisteault** [comment]
@rmarzocchi84 yes you are right the issue is somewhere else. I'm close to fix it.

**Comment by remigods** [comment]
> 
> 
> @hi remigods
> Did you put other values than 't' and 'f' for your checkbox ?

Nope. I assume Postgresql to return True or False accordingly. I just set the checkbox "status" under QGIS (true when checked), but I doubt it affects Postgres values.

**Comment by rmarzocchi84** [comment]
I have updated to lizmap 3.3.0 and the problem is still present

**Comment by rmarzocchi84** [comment]
Data visualization:
![view_data](https://user-images.githubusercontent.com/4061154/64238986-ab740300-ceff-11e9-880e-3ff76e99eccd.png)

Data editing:
![edit_data](https://user-images.githubusercontent.com/4061154/64239015-b890f200-ceff-11e9-9ea6-16ce52afa04b.png)

**Comment by nboisteault** [comment]
@rmarzocchi84 Are you using QGIS Server 3.4 ?

**Comment by rmarzocchi84** [comment]
Yes 3.4.11

**Comment by nboisteault** [comment]
Confirmed. Fix coming.

**Comment by rldhont** [comment]
@rmarzocchi84 has been fixed, can you test the actual release_3_3 branch ?
