### ISSUE TITLE
proj4js - console errors

### ISSUE THREAD

**Issue by infoble** [3liz/lizmap-web-client#1262]
Hello,
(my config: debian 10, nginx, php7.2, lizmap 3.3rc1, qgisserver3.4 + multiwatch). No major problem apparent but many errors are present in the console when opening a card. They are of the type:
  - VM9302 .js: 1 Uncaught SyntaxError: Unexpected token <
    (the incriminated .js files are actually html files)
or
  - Uncaught TypeError: Can not read property 'dependsOn' of undefined
     at a.loadProjCodeSuccess (proj4js.min.js: 45)
     at HTMLScriptElement. <anonymous> (proj4js.min.js: 39)
I do not understand by their origin. 
Thank you

**Comment by infoble** [comment]
Hello, no one would have a track ?

**Comment by rldhont** [comment]
Do you have an issue ? Is lizmap usable ?

**Comment by infoble** [comment]
Hello,
I have lizmap-web-client 3.3rc1 and qgis-server 3.6. For now lizmap works except the server cache that does not seem to want to register. I do not know if these errors have a role in this problem. 
I would still like to find the origin of these multiple mistakes

**Comment by nboisteault** [comment]
@infoble Please give us a way to reproduce your issue.

**Comment by infoble** [comment]
Hello, unfortunately I see no way to reproduce these problems (which would already be a beginning of solution). However here is the link to see them (any map): 
[site](https://carto.clermontmetropole.org/)

**Comment by rldhont** [comment]
@infoble Did you update your lizmap web client version to 3.3.0 ?
Which QGIS Desktop version did you use to build the project ?
Can you downgrade your QGIS server to 3.4 ?

@nboisteault It seems that Lizmap does not well identify some EPSG code in the project.
Lizmap (Javascript) produces this link for EPSG code:
* Proj4js/projCode/null.js
* Proj4js/projCode/.js

**Comment by nboisteault** [comment]
@infoble Please make changes @rldhont suggested and tell us, I'll debug from there.

**Comment by infoble** [comment]
Thank you for your answers, so I updated lizmap-webclient to 3.3.0 and qgis-server to 3.4 after having purged the previous versions. But now I have a 500 error on the display of all slabs. I must have a config error ...

**Comment by NvBgm** [comment]
Check the file ". htacces" in lizmap www map.
Het have to "Require all granted".
I had the same error after update.

⁣Met vriendelijke groeten
NvBgm

BlueMail voor Android downloaden ​

Op 1 okt. 2019 16:54, om 16:54, infoble <notifications@github.com> schreef:

**Comment by infoble** [comment]
Thank you for the answer. My server is Nginx (no htaccess) but the track is interesting. I look at Thursday.

**Comment by infoble** [comment]
@NvBgm @rldhont So I reviewed everything, there are rights and permissions on the file lizmap/www. I do not understand, I still have a 500 error in displaying tiles. The problem does not come from the project because it exists with the examples projects.

**Comment by infoble** [comment]
a new component update has finally solved all the problems. A bug had to be corrected in the meantime ... Thank you
