### ISSUE TITLE
Request too long when exporting features

### ISSUE THREAD

**Issue by faibistes** [3liz/lizmap-web-client#1263]
Whenever I try to export a fairly large number of selected features, it fails with this error:

```
Bad Request - Request Too Long

HTTP Error 400. The size of the request headers is too long.

```
Why is it trying to use GET, not POST, for this request?
Here's an example request, for 452 selected features:

`https://geomarketing.tesa/mapas/index.php/lizmap/service/?repository=pruebasliz&project=falsosnegativos&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=Fincas_despliegue&OUTPUTFORMAT=XLSX&FEATUREID=Fincas_despliegue.1296956%2CFincas_despliegue.2740741%2CFincas_despliegue.4824755%2CFincas_despliegue.6665455%2CFincas_despliegue.8995476%2CFincas_despliegue.9398705%2CFincas_despliegue.11827251%2CFincas_despliegue.12334230%2CFincas_despliegue.12402848%2CFincas_despliegue.13265475%2CFincas_despliegue.13581692%2CFincas_despliegue.16251208%2CFincas_despliegue.16375376%2CFincas_despliegue.16416443%2CFincas_despliegue.2048105%2CFincas_despliegue.8548775%2CFincas_despliegue.9339899%2CFincas_despliegue.10929099%2CFincas_despliegue.12367687%2CFincas_despliegue.13400040%2CFincas_despliegue.13709265%2CFincas_despliegue.17213553%2CFincas_despliegue.1685992%2CFincas_despliegue.4900989%2CFincas_despliegue.5735272%2CFincas_despliegue.6159346%2CFincas_despliegue.10156923%2CFincas_despliegue.10960074%2CFincas_despliegue.17144986%2CFincas_despliegue.17560054%2CFincas_despliegue.7879088%2CFincas_despliegue.375552%2CFincas_despliegue.3353138%2CFincas_despliegue.9128337%2CFincas_despliegue.11268531%2CFincas_despliegue.16629196%2CFincas_despliegue.17648324%2CFincas_despliegue.981671%2CFincas_despliegue.1053222%2CFincas_despliegue.1837404%2CFincas_despliegue.2650711%2CFincas_despliegue.6319832%2CFincas_despliegue.15820429%2CFincas_despliegue.16280724%2CFincas_despliegue.1009169%2CFincas_despliegue.1126927%2CFincas_despliegue.1161614%2CFincas_despliegue.1922458%2CFincas_despliegue.2751980%2CFincas_despliegue.3719173%2CFincas_despliegue.3744066%2CFincas_despliegue.4086537%2CFincas_despliegue.4628663%2CFincas_despliegue.4885208%2CFincas_despliegue.4890537%2CFincas_despliegue.6451722%2CFincas_despliegue.6762260%2CFincas_despliegue.6994524%2CFincas_despliegue.7190927%2CFincas_despliegue.8181794%2CFincas_despliegue.8618576%2CFincas_despliegue.10958826%2CFincas_despliegue.11026065%2CFincas_despliegue.12465604%2CFincas_despliegue.12830962%2CFincas_despliegue.17667873%2CFincas_despliegue.524992%2CFincas_despliegue.531727%2CFincas_despliegue.8924659%2CFincas_despliegue.9164716%2CFincas_despliegue.11794002%2CFincas_despliegue.1859688%2CFincas_despliegue.2453522%2CFincas_despliegue.3126253%2CFincas_despliegue.10814012%2CFincas_despliegue.15133872%2CFincas_despliegue.13536854%2CFincas_despliegue.11091106%2CFincas_despliegue.12925102%2CFincas_despliegue.14084207%2CFincas_despliegue.13369398%2CFincas_despliegue.1631555%2CFincas_despliegue.3354362%2CFincas_despliegue.9510578%2CFincas_despliegue.199141%2CFincas_despliegue.5633754%2CFincas_despliegue.16063313%2CFincas_despliegue.10127191%2CFincas_despliegue.1106223%2CFincas_despliegue.11954814%2CFincas_despliegue.11955011%2CFincas_despliegue.12078966%2CFincas_despliegue.13269361%2CFincas_despliegue.17717737%2CFincas_despliegue.8876171%2CFincas_despliegue.8993726%2CFincas_despliegue.8184985%2CFincas_despliegue.16425752%2CFincas_despliegue.1035491%2CFincas_despliegue.8148871%2CFincas_despliegue.15724341%2CFincas_despliegue.2292959%2CFincas_despliegue.6596709%2CFincas_despliegue.14283395%2CFincas_despliegue.58981%2CFincas_despliegue.14124567%2CFincas_despliegue.13442486%2CFincas_despliegue.13937064%2CFincas_despliegue.14566096%2CFincas_despliegue.7079729%2CFincas_despliegue.15288388%2CFincas_despliegue.5358760%2CFincas_despliegue.5827988%2CFincas_despliegue.459590%2CFincas_despliegue.14491311%2CFincas_despliegue.14229366%2CFincas_despliegue.3594919%2CFincas_despliegue.17536979%2CFincas_despliegue.4974895%2CFincas_despliegue.1756930%2CFincas_despliegue.6788714%2CFincas_despliegue.908619%2CFincas_despliegue.2128159%2CFincas_despliegue.2109542%2CFincas_despliegue.15232628%2CFincas_despliegue.8994255%2CFincas_despliegue.14854810%2CFincas_despliegue.9744187%2CFincas_despliegue.9044885%2CFincas_despliegue.10363192%2CFincas_despliegue.13091538%2CFincas_despliegue.1001741%2CFincas_despliegue.9604419%2CFincas_despliegue.9567453%2CFincas_despliegue.9864062%2CFincas_despliegue.3217291%2CFincas_despliegue.9495064%2CFincas_despliegue.10432331%2CFincas_despliegue.10701190%2CFincas_despliegue.12356997%2CFincas_despliegue.14576875%2CFincas_despliegue.14669251%2CFincas_despliegue.6399306%2CFincas_despliegue.10753802%2CFincas_despliegue.1366277%2CFincas_despliegue.3599039%2CFincas_despliegue.5642111%2CFincas_despliegue.8112592%2CFincas_despliegue.8240607%2CFincas_despliegue.9185094%2CFincas_despliegue.14814336%2CFincas_despliegue.17878440%2CFincas_despliegue.1413817%2CFincas_despliegue.5986342%2CFincas_despliegue.7002229%2CFincas_despliegue.8106689%2CFincas_despliegue.10445155%2CFincas_despliegue.10587411%2CFincas_despliegue.10893566%2CFincas_despliegue.11791153%2CFincas_despliegue.12270974%2CFincas_despliegue.16281908%2CFincas_despliegue.11273703%2CFincas_despliegue.12376994%2CFincas_despliegue.14841542%2CFincas_despliegue.16946754%2CFincas_despliegue.17261135%2CFincas_despliegue.6642158%2CFincas_despliegue.10640549%2CFincas_despliegue.2589417%2CFincas_despliegue.4563310%2CFincas_despliegue.6211904%2CFincas_despliegue.9671135%2CFincas_despliegue.10843653%2CFincas_despliegue.17688256%2CFincas_despliegue.544321%2CFincas_despliegue.2289142%2CFincas_despliegue.3237290%2CFincas_despliegue.4322051%2CFincas_despliegue.5653615%2CFincas_despliegue.9483232%2CFincas_despliegue.11322340%2CFincas_despliegue.17187571%2CFincas_despliegue.5898907%2CFincas_despliegue.8903338%2CFincas_despliegue.12187869%2CFincas_despliegue.408802%2CFincas_despliegue.5241079%2CFincas_despliegue.11712980%2CFincas_despliegue.12713298%2CFincas_despliegue.2784543%2CFincas_despliegue.9603642%2CFincas_despliegue.17233054%2CFincas_despliegue.10410881%2CFincas_despliegue.971741%2CFincas_despliegue.5378312%2CFincas_despliegue.9337078%2CFincas_despliegue.14390975%2CFincas_despliegue.16870571%2CFincas_despliegue.9039584%2CFincas_despliegue.17025140%2CFincas_despliegue.8718095%2CFincas_despliegue.9335729%2CFincas_despliegue.16439535%2CFincas_despliegue.635580%2CFincas_despliegue.2424781%2CFincas_despliegue.6649851%2CFincas_despliegue.16403610%2CFincas_despliegue.5230906%2CFincas_despliegue.7180519%2CFincas_despliegue.7596538%2CFincas_despliegue.11183294%2CFincas_despliegue.13709419%2CFincas_despliegue.17542098%2CFincas_despliegue.1016089%2CFincas_despliegue.3000311%2CFincas_despliegue.7352758%2CFincas_despliegue.7777793%2CFincas_despliegue.8219335%2CFincas_despliegue.9879826%2CFincas_despliegue.10701003%2CFincas_despliegue.12694557%2CFincas_despliegue.16460373%2CFincas_despliegue.17183060%2CFincas_despliegue.3536684%2CFincas_despliegue.8352772%2CFincas_despliegue.10605915%2CFincas_despliegue.13667743%2CFincas_despliegue.17777979%2CFincas_despliegue.189180%2CFincas_despliegue.1053375%2CFincas_despliegue.1673373%2CFincas_despliegue.3951652%2CFincas_despliegue.4909930%2CFincas_despliegue.5603684%2CFincas_despliegue.6267131%2CFincas_despliegue.8424605%2CFincas_despliegue.8548801%2CFincas_despliegue.10019397%2CFincas_despliegue.11473597%2CFincas_despliegue.13484086%2CFincas_despliegue.13648047%2CFincas_despliegue.15491834%2CFincas_despliegue.16549574%2CFincas_despliegue.17327309%2CFincas_despliegue.3429687%2CFincas_despliegue.16774147%2CFincas_despliegue.1066146%2CFincas_despliegue.14546547%2CFincas_despliegue.4667475%2CFincas_despliegue.1200919%2CFincas_despliegue.5213413%2CFincas_despliegue.6489372%2CFincas_despliegue.7326907%2CFincas_despliegue.9618464%2CFincas_despliegue.1285844%2CFincas_despliegue.5176316%2CFincas_despliegue.6593599%2CFincas_despliegue.2608027%2CFincas_despliegue.14070514%2CFincas_despliegue.8340931%2CFincas_despliegue.4569942%2CFincas_despliegue.11903758%2CFincas_despliegue.16250970%2CFincas_despliegue.3733230%2CFincas_despliegue.5802336%2CFincas_despliegue.5368072%2CFincas_despliegue.14225053%2CFincas_despliegue.2841983%2CFincas_despliegue.872160%2CFincas_despliegue.4863745%2CFincas_despliegue.8746757%2CFincas_despliegue.11641299%2CFincas_despliegue.2303529%2CFincas_despliegue.9597811%2CFincas_despliegue.11089914%2CFincas_despliegue.13789042%2CFincas_despliegue.14992106%2CFincas_despliegue.4952034%2CFincas_despliegue.17094903%2CFincas_despliegue.6521941%2CFincas_despliegue.11111120%2CFincas_despliegue.978877%2CFincas_despliegue.8005562%2CFincas_despliegue.14030345%2CFincas_despliegue.2753090%2CFincas_despliegue.5068078%2CFincas_despliegue.8866838%2CFincas_despliegue.10415294%2CFincas_despliegue.11228716%2CFincas_despliegue.11263135%2CFincas_despliegue.12561768%2CFincas_despliegue.12571986%2CFincas_despliegue.13928238%2CFincas_despliegue.14820613%2CFincas_despliegue.15789781%2CFincas_despliegue.16429884%2CFincas_despliegue.8552224%2CFincas_despliegue.10038984%2CFincas_despliegue.10463533%2CFincas_despliegue.10726351%2CFincas_despliegue.2726151%2CFincas_despliegue.5297344%2CFincas_despliegue.13037405%2CFincas_despliegue.1721597%2CFincas_despliegue.2056628%2CFincas_despliegue.2867033%2CFincas_despliegue.3306340%2CFincas_despliegue.3356838%2CFincas_despliegue.3561454%2CFincas_despliegue.3805671%2CFincas_despliegue.5295053%2CFincas_despliegue.6076492%2CFincas_despliegue.10534996%2CFincas_despliegue.16570953%2CFincas_despliegue.16965046%2CFincas_despliegue.682186%2CFincas_despliegue.7030657%2CFincas_despliegue.10935822%2CFincas_despliegue.14270281%2CFincas_despliegue.15826925%2CFincas_despliegue.12859291%2CFincas_despliegue.12999906%2CFincas_despliegue.15331039%2CFincas_despliegue.16984607%2CFincas_despliegue.2788111%2CFincas_despliegue.13852790%2CFincas_despliegue.12414%2CFincas_despliegue.4194250%2CFincas_despliegue.2699850%2CFincas_despliegue.14116519%2CFincas_despliegue.6257428%2CFincas_despliegue.6570425%2CFincas_despliegue.9394053%2CFincas_despliegue.1812674%2CFincas_despliegue.5210267%2CFincas_despliegue.7858824%2CFincas_despliegue.8658106%2CFincas_despliegue.9206304%2CFincas_despliegue.9618939%2CFincas_despliegue.10067957%2CFincas_despliegue.10685119%2CFincas_despliegue.13079144%2CFincas_despliegue.13343006%2CFincas_despliegue.13915243%2CFincas_despliegue.16938745%2CFincas_despliegue.17169433%2CFincas_despliegue.467895%2CFincas_despliegue.755205%2CFincas_despliegue.912211%2CFincas_despliegue.1729423%2CFincas_despliegue.1786412%2CFincas_despliegue.2697862%2CFincas_despliegue.4882623%2CFincas_despliegue.8339804%2CFincas_despliegue.10242507%2CFincas_despliegue.12989225%2CFincas_despliegue.14152160%2CFincas_despliegue.14233100%2CFincas_despliegue.16155019%2CFincas_despliegue.17660354%2CFincas_despliegue.17671799%2CFincas_despliegue.341404%2CFincas_despliegue.1306130%2CFincas_despliegue.1966328%2CFincas_despliegue.2958061%2CFincas_despliegue.3102109%2CFincas_despliegue.5336003%2CFincas_despliegue.9499533%2CFincas_despliegue.9513276%2CFincas_despliegue.13530817%2CFincas_despliegue.15130540%2CFincas_despliegue.16259327%2CFincas_despliegue.16868924%2CFincas_despliegue.586352%2CFincas_despliegue.2891082%2CFincas_despliegue.6696977%2CFincas_despliegue.7431683%2CFincas_despliegue.8229319%2CFincas_despliegue.8375698%2CFincas_despliegue.9006542%2CFincas_despliegue.9802620%2CFincas_despliegue.12717323%2CFincas_despliegue.13408554%2CFincas_despliegue.13747912%2CFincas_despliegue.15526479%2CFincas_despliegue.16064310%2CFincas_despliegue.6112897%2CFincas_despliegue.9462540%2CFincas_despliegue.11855444%2CFincas_despliegue.13920079%2CFincas_despliegue.14162611%2CFincas_despliegue.16641785%2CFincas_despliegue.302202%2CFincas_despliegue.589621%2CFincas_despliegue.1476787%2CFincas_despliegue.3952850%2CFincas_despliegue.5373707%2CFincas_despliegue.8765410%2CFincas_despliegue.10326618%2CFincas_despliegue.12141366%2CFincas_despliegue.13460805%2CFincas_despliegue.15601567%2CFincas_despliegue.16729184%2CFincas_despliegue.5325258%2CFincas_despliegue.12560814%2CFincas_despliegue.13151809%2CFincas_despliegue.16571587%2CFincas_despliegue.8399442%2CFincas_despliegue.16129794%2CFincas_despliegue.3437013%2CFincas_despliegue.3999312%2CFincas_despliegue.4547227%2CFincas_despliegue.4754229%2CFincas_despliegue.7121157%2CFincas_despliegue.8256775%2CFincas_despliegue.15149756%2CFincas_despliegue.16300873%2CFincas_despliegue.2074082%2CFincas_despliegue.3217600%2CFincas_despliegue.4157645%2CFincas_despliegue.4300646%2CFincas_despliegue.5416513%2CFincas_despliegue.5531724%2CFincas_despliegue.5941011%2CFincas_despliegue.6938965%2CFincas_despliegue.6998841%2CFincas_despliegue.7062697%2CFincas_despliegue.7346626%2CFincas_despliegue.15167081%2CFincas_despliegue.16952419%2CFincas_despliegue.17308355%2CFincas_despliegue.6003670%2CFincas_despliegue.12417890%2CFincas_despliegue.3227219%2CFincas_despliegue.11759920%2CFincas_despliegue.13477790%2CFincas_despliegue.17763012%2CFincas_despliegue.17864185%2CFincas_despliegue.77456%2CFincas_despliegue.4243824%2CFincas_despliegue.11909457%2CFincas_despliegue.16030323%2CFincas_despliegue.6241245%2CFincas_despliegue.8736635%2CFincas_despliegue.9396928%2CFincas_despliegue.1960451%2CFincas_despliegue.2100560%2CFincas_despliegue.5437582%2CFincas_despliegue.7431981%2CFincas_despliegue.14142861%2CFincas_despliegue.17088896&dl=1`

**Comment by rldhont** [comment]
Can you provide these informations :
- Lizmap version: 
- QGIS Server version:
- QGIS Project version:

**Comment by faibistes** [comment]
It's Lizmap 3.2.3, QGIS server 2.18 QGIS project 2.18

**Comment by buoncri** [comment]
same problem with LZ 3.3rc2, QGIS server 3.4.9, project 3.8
