### ISSUE TITLE
SVG printing in the legend

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1266]
### What is the bug?
When I print a map with an SVG file, it appears on the map but not in the legend.
[Example](https://map.data-wax.com/index.php/view/map/?repository=rep008&project=Projet2)

### Screenshots and logs
<img width="109" alt="image" src="https://user-images.githubusercontent.com/7761073/59609252-96f54b00-9106-11e9-85e7-da070c8e84d1.png">

### Environment
 - Lizmap version: 3.3rc2
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4.8
 - Browser (Firefox, Chrome…): Firefox, Safari

**Comment by igeofr** [comment]
Finally I used the option : Embed File

**Comment by rldhont** [comment]
Hi @igeofr if you think it will be usefull for other user, please update the documentation. Thanks
