### ISSUE TITLE
Installing LizMap on Windows 10 - 500 internal server error

### ISSUE THREAD

**Issue by caduguedess** [3liz/lizmap-web-client#1267]
Hi, thanks for developing such a great tool.
I'm following the tutorial available at https://docs.lizmap.com/current/en/install/windows.html to install Lizmap on Windows 10.
After QGIS Server installing, changing the files httpd-vhosts.conf and php73.conf and restarting Apache I'm getting errors in the browsers that were working in the previous steps.
localhost gives 403 Forbidden error
http://localhost/index.php gives Not Found error
http://localhost/qgis/qgis_mapserv.fcgi.exe gives 500 Internal Server Error

I uploaded my files httpd.conf, httpd-vhosts.conf and php73.conf if someone want to check.

[error.zip](https://github.com/3liz/lizmap-web-client/files/3299302/error.zip)

I'm installing in a notebook with Windows 10 64 bits and the versions of the softwares are the following:
Apache 2.4.39 VC15 win64
mod fcgid 2.3.9 win64
PHP 7.3.6 nts x64
OSGEO4W64
QGIS 2.18.28 installed manually
QGIS Server LTR installed through OSGEO4W64

I also have installed QGIS 3.4.2 installed manually, so I'm scared that having two versions of QGIS and manually installing them would make it not work.

**Comment by caduguedess** [comment]
[error.log](https://github.com/3liz/lizmap-web-client/files/3303605/error.log)
[install.log](https://github.com/3liz/lizmap-web-client/files/3303606/install.log)
[lizmap-access.log](https://github.com/3liz/lizmap-web-client/files/3303607/lizmap-access.log)
[access.log](https://github.com/3liz/lizmap-web-client/files/3303609/access.log)

[lizmap-error.log](https://github.com/3liz/lizmap-web-client/files/3303608/lizmap-error.log)

I'm also uploading the log files

**Comment by nboisteault** [comment]
You should try an [install with Vagrant](https://github.com/3liz/lizmap-web-client/tree/master/vagrant).

**Comment by PQK0108** [comment]
I follow tutorial at : https://opengislab.com/blog/2018/7/7/updated-installing-apache-qgis-server-and-lizmap-on-windows-os
But have same problem at
http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities get 500 error.

**Comment by dobignies** [comment]
Assuming you're installing lizmap master, QGIS 3.8.x or LTR (you don't need two versions):
- in php73 modify phyton27 to phyton37 and qgis paths according installed version (qgis-ltr/ or qgis/)
- httpd-vhosts is missing some instructions. Try again following the tutorial and setup lizmap www document root.
- in httpd active access_compat_module (it works for 500 Internal Server error)

**Comment by Gustry** [comment]
If you are still using Windows, I think you should have a look to https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by Gustry** [comment]
The documentation about Windows has been droppped : https://github.com/3liz/lizmap-web-client/issues/1267
We redirect to NaturalGIS or to docker-compose.
