### ISSUE TITLE
Print tool not showing

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-web-client#1268]
Hi,

The print button on Lizmap map menue is not appearing.

On the QGIS project i've created a composer with a map to try the feature. Then in lizmap plugin i've enable de print option in the map option.

The problem is once i go to see my map in Lizmap web client, the print button is not on the panel.

I used the dockerfile and the docker-compose file from your repositories 
https://github.com/3liz/lizmap-docker-compose/blob/master/docker-compose.yml

**Comment by buoncri** [comment]
I don't know about the docker imager of lizmap, but i had a similar problem that was solved by upgrading lizmap from 3.2.someothernumber to 3.3.rcothernumber

**Comment by rldhont** [comment]
Hi @Ailurupoda if your projet has been build with QGIS 3.* you need to upgrade Lizmap-Web-Client to 3.3*

**Comment by rldhont** [comment]
Please close this issue if the upgrade solve it.

**Comment by Ailurupoda** [comment]
Thanks ! I took the 3.3-rc docker image and it works.
