### ISSUE TITLE
Strange warning in the log 

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#1274]
In the lizmap log i see these strange warning:

```
2019-06-27 17:37:51	XXX.XXX.XXXX.XXX	warning	2019-06-27 17:37:51	[2]	file_get_contents(http://www.webgislepini.it/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fvar%2Fwww%2Fnextcloud%2Fdata%2Fcontributor%2Ffiles%2Fwebgis%2FPartecipazioneAttiva%2Fprova%5F2%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
	/var/www/lizmap-3.3-git/lizmap/modules/lizmap/classes/lizmapProxy.class.php	236
```

I think the problem can be due to the **amp;** string in the url of getcapabilities request

### Environment

 - Lizmap version: latest (clone of github)
 - QGIS Server version: 3.4.9
 - QGIS Project version: 3.4.9

**Comment by miszokienka** [comment]
No, **&amp** is ok. I think that this is because of QGIS yveraion 3.4.9. I'm experiencing problems with loading my WMS tiles after upgrading to QGIS Server 3.4.9.

**Comment by rldhont** [comment]
Wuth QGIS Server 3.4.9, if one layer could not be loaded by QGIS Server , all the requests failed!

**Comment by rldhont** [comment]
can you check the QGIS Server log.

**Comment by rmarzocchi84** [comment]
In the qgis server erro log this is the corresponding lines:

```
16:08:15 WARNING [25448]: mapSettings.destinationCrs(): EPSG:3857
16:08:15 WARNING [25448]: mapSettings.extent(): 863605.9598779999651015,5799687.5910459998995066 : 983612.0942689999938011,5851817.6443290002644062
16:08:15 WARNING [25448]: mapSettings width = 1570 height = 682
16:08:15 WARNING [25448]: mapSettings.mapUnitsPerPixel() = 76.437
16:08:17 WARNING Server[25448]: Found WMS capabilities document in cache
16:08:17 WARNING [25448]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
16:08:17 WARNING [25448]: formatString is: image/png
16:08:18 WARNING [25448]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
16:08:18 WARNING [25448]: formatString is: image/png
16:08:19 WARNING [25448]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
16:08:19 WARNING [25448]: formatString is: image/png
16:08:19 WARNING [25448]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
16:08:19 WARNING [25448]: formatString is: image/png
```

**Comment by rmarzocchi84** [comment]
Moreover when I call WFS (editing or table visualization) I encountered the following error: 

`2019-06-28 16:13:41	93.149.193.29	error	2019-06-28 16:13:41	[0]	dbtools, pgsql: unknown table	/home/gter/lizmap-web-client-3.3git/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php	242`

**Comment by mdouchin** [comment]
Could you give the exact content of the <datasource> of the layer in the QGIS project ? Please remove the password before !

**Comment by rmarzocchi84** [comment]
> Could you give the exact content of the of the layer in the QGIS project ? Please remove the password before !

Sorry, where I have to remove the password? I do not understand :-(

**Comment by rmarzocchi84** [comment]
> No, **&amp** is ok. I think that this is because of QGIS version 3.4.9. I'm experiencing problems with loading my WMS tiles after upgrading to QGIS Server 3.4.9. I did a rollback to 3.4.8.

Sorry @miszokienka, but how can i do the rollback? I use a ubuntu server and when I do apt-cache showpkg I see only the 3.4.9 version and the 2.18.17 available.

**Comment by miszokienka** [comment]
I have Timeshift backups and that's how I did it.
I had the same problem with 3.4.9 on another computer and i upgraded to 3.8.0 and it's working fine. To make a rollback to 3.4.8 without any backup you'll need probably to compile from sources...

**Comment by rmarzocchi84** [comment]
It seems the problem related to WFS not depend on qgis server, but on qgis desktop or lizmap plugin 

I try with a previous saved project and editing works correctly, after I open the project save it with qgis 3.4.9  run lizmap to add attribute data visualization and now the project is corrupted (editing do not works).

I try to rollback qgis desktop version 3.4.8 create a new test project and I have the same problem. 

Unfortunately I do not know which version of qgis works correctly because I do not create a copy of the *previous saved version*

I will do more tests

**Comment by mdouchin** [comment]
Please open the qgs file with a text editor (I recommand notepad++ on Windows ), and find the `<datasource` of your layer. Lizmap reads this property to gather needed information on PostgreSQL connexion

**Comment by rmarzocchi84** [comment]
Same project saved with qgis desktop 3.4.6 works fine, saved with 3.4.8 or 3.4.9 do not works

DATASOURCE 3.4.6 
      <datasource>dbname='workshop' host=gishosting.gter.it port=5432 user='workshop' password='padova2019' sslmode=disable key='id' srid=3003 type=Polygon table="data"."palazzi_rolli" (geom) sql=</datasource>

DATASOURCE 3.4.8
      <datasource>dbname='workshop' host=gishosting.gter.it port=5432 user='workshop' password='padova2019' sslmode=disable srid=3003 type=Polygon checkPrimaryKeyUnicity='1' table="data"."palazzi_rolli" (geom) sql=</datasource>


It seems the problem for lizmap is the checkPrimaryKeyUnicity='1' ? It is possible.. I hope to be useful

**Comment by rmarzocchi84** [comment]
I confirm that checkPrimaryKeyUnicity='1' is a problem for lizmap
If I remove from a project which do not works (using notepad++) it works without error.


The warning seems to persist

**Comment by mdouchin** [comment]
it is strange. I corrected this bug in release_3_2. @rldhont we need to merge release_3_3 into master more often.
See #1255 and https://github.com/3liz/lizmap-web-client/commit/1c4b67e6b5b8234d734fa47946055530e2686330

**Comment by rmarzocchi84** [comment]
Have you merge the release 3_3 into master?

I do not see any update in the code.

**Comment by nboisteault** [comment]
@rmarzocchi84 it has been merged lately. Can you test and close issue if it is ok ? Thanks.

**Comment by rmarzocchi84** [comment]
It works! Thanks for all your work!
