### ISSUE TITLE
3 forms in one (1:N relations)

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#1276]
With Lizmap, I know it's possible to display a child form in a parent form, as described in issue [#1238](https://github.com/3liz/lizmap-web-client/issues/1238).

But is it possible to display a third form whose the second one is the parent ?

I managed to get this functionality with QGIS (see picture above), but I don't know if it's possible with Lizmap ?
![image](https://user-images.githubusercontent.com/46535425/60677089-d949b680-9e80-11e9-8812-425400774661.png)

Thank you for your help and advices.

**Comment by nboisteault** [comment]
@Mavialle Did you try in lizmap ?

**Comment by Mavialle** [comment]
Yes, but the 3rd level doesn't display

**Comment by Gustry** [comment]
Did you get some progress on that @Mavialle ?
I don't think this is possible in Lizmap. This would need some development I think.
