### ISSUE TITLE
links/URLs unrelated to layer

### ISSUE THREAD

**Issue by frank11000** [3liz/lizmap-web-client#1278]
### Is your feature request related to a problem? Please describe
Most of my documents are related to layers and I linked them with the popups but some of them are unrelated because they are too general.

### Describe the solution you'd like
I would like to know if there's a way to display some links, without having to select a layer, in a window somewhere in the map.

### Additional context
I'm new to Lizmap and I want to thank all the community for the hard work and support, thanks by advance

**Comment by nboisteault** [comment]
You can put your links in the description part in 'information' tab (big I the left in tha bar).

**Comment by Gustry** [comment]
There is also a javascript API where you can add custom buttons.
https://docs.lizmap.com/next/en/publish/customization/javascript.html

Like this demo : https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=qgis_info

Closing for lack of feedback, feel free to reopen.
