### ISSUE TITLE
HTML getfeatureinfo return XML

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#128]
I've upgraded QGIS server to 2.8.1 and lizmap to master on ubuntu 12.04.
Now when Lizmap sends getfeatureinfo with HTML info_format it returns XML.
I've also tried with QGIS server 2.9.0 and lizmap 2.10.1 and the issue is the same.

You can try this URL : http://92.243.19.0/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=adpag&project=adpag&LAYERS=Belette%20Saison%202013%20-%202014&QUERY_LAYERS=Belette%20Saison%202013%20-%202014&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&BBOX=-168045.707951%2C5473621.385302%2C103764.364593%2C5731978.54087&FEATURE_COUNT=10&HEIGHT=845&WIDTH=889&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&CRS=EPSG%3A3857&I=338&J=264

I didn't find a way to downgrade qgis-server to 2.6.1. Any suggestions? Thanks.

**Comment by rldhont** [comment]
To downgrade you have to compile qgis-server with the branch release-2_6.

Because QGIS 2.8.* is not yet downloadable on qgis.org, we didn't yet test it with lizmap.

Now for your issue, I think it's some changes in the QGIS-Server GetFeatureInfo mime-type. I'll take a look.

**Comment by rldhont** [comment]
I can't reproduce this issue with QGIS 2.8.*

Do you have this issue with other layers ?

**Comment by rldhont** [comment]
I can't reproduce it in my environment but I understand why you have this issue.

The mime-type of the xml request is not *text/xml* but *text/xml; charset=utf-8*
