### ISSUE TITLE
project on another server

### ISSUE THREAD

**Issue by frank11000** [3liz/lizmap-web-client#1282]
Hello,

I would like to know if I can place my project (.qlr, datas ans documents) on another server and how can I link them to my repertory path.

Thank you,

Frank

**Comment by nboisteault** [comment]
It is not related to Lizmap but here is an idea. You can make an external directory looks like it was local via [NFS](https://doc.ubuntu-fr.org/nfs) for example. Some network protocols suit better some OS than others. Do some search on internet.
