### ISSUE TITLE
lizmap button

### ISSUE THREAD

**Issue by maximgulko** [3liz/lizmap-web-client#1288]
Hi! Please help me.
How to add a button to lizmap via code?
 Where to find the script responsible for this function?

which folder to look for the code?

**Comment by igeofr** [comment]
What exactly do you want to do? 
Here is an example of code to add a button to open a link : [add_link_documentation.js](https://github.com/3liz/lizmap-javascript-scripts/blob/master/add_documentation/add_link_documentation.js)

**Comment by nboisteault** [comment]
Other example https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/atlas.js#L186

**Comment by maximgulko** [comment]
> Что именно вы хотите сделать? 
> Вот пример кода для добавления кнопки для открытия ссылки: [add_link_documentation.js](https://github.com/3liz/lizmap-javascript-scripts/blob/master/add_documentation/add_link_documentation.js)


thanks for the answer

I want to add a button in the menu or in the header near the "search" to create my address list or link a table.
