### ISSUE TITLE
NULL value written in HTML popup

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#129]
If we have a NULL value in a HTML popup "NULL" is written. No string should be displayed.

For example : http://92.243.19.0/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=adpag&project=adpag&LAYERS=Belette%20Saison%202013%20-%202014&QUERY_LAYERS=Belette%20Saison%202013%20-%202014&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&BBOX=-168045.707951%2C5473621.385302%2C103764.364593%2C5731978.54087&FEATURE_COUNT=10&HEIGHT=845&WIDTH=889&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&CRS=EPSG%3A3857&I=363&J=219

**Comment by rldhont** [comment]
Can you specify the QGIS Server version ?

**Comment by nboisteault** [comment]
QGIS Server 2.8.1.
