### ISSUE TITLE
Unable to find driver "ldapdao" for authentication

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#1290]
Hi,
I've correctly installed/configured Lizmap Web Client 3.1.20 in an Ubuntu server 16.04 and condigured for ldapdao authentication adding the ldapdao-module-2.0.6, so the users authenticate by an Active Directory domain controller.
I replicate the same step by step procedure on an Ubuntu server 18.04, but when I try login, also as admin user, in the browser appear the following error:
`Error 500. A technical error has occured. Sorry for this trouble.`
and in the error.log I have the following error:
`2019-07-22 08:38:25     192.168.23.171  error   2019-07-22 08:38:25     [602]   Unable to find driver "ldapdao" for authentication    /var/www/lizmap-web-client-3.1.20/lib/jelix/auth/jAuth.class.php     149`
Can anyone help me?
Thanks.

Below some details.
I've done the following steps:
```
apt install php-ldap
systemctl restart apache2.service
cd /var/www/
MYAPP=ldapdao-module
VERSION=2.0.6
wget https://github.com/jelix/$MYAPP/archive/v$VERSION.tar.gz
tar xvzf v$VERSION.tar.gz
rm v$VERSION.tar.gz
cd $MYAPP-$VERSION
cp -r ./ldapdao/ /var/www/lizmap-web-client-3.1.20/lizmap/lizmap-modules/
cd ..
cp ldapdao-module-2.0.6/ldapdao/install/authldap.coord.ini.php lizmap-web-client-3.1.20/lizmap/var/config/
```
I declared the ldapdao module in the file `lizmap/var/config/localconfig.ini.php`
```
[modules]
ldapdao.access=1
```
and redefined the state of the following parameters in the same file:
```
jacl2.access=1
jauth.access=2
jauthdb.access=1
```
I redefined the path to the authentication file in the following files:
```
lizmap/var/config/localconfig.ini.php
lizmap/var/config/admin/config.ini.php
lizmap/var/config/index/config.ini.php
```
as follow
```
[coordplugins]
auth="authldap.coord.ini.php"
```
I created a profile in `lizmap/var/config/profiles.ini.php` as follow
```
[ldap:pgldap]
hostname=my.domain.com
port=389
adminUserDn="cn=administrator,ou=adminstrators,dc=my,dc=domain,dc=com"
adminPassword="*************"
```
and configured the file `lizmap/var/config/authldap.coord.ini.php ` as follow
```
[LDAPDAO]
...
ldapprofile = "pgldap"
...
searchUserBaseDN="OU=Comune di Spoleto,DC=my,DC=domain,DC=com"
...
searchUserFilter="(sAMAccountName=%%LOGIN%%)"
...
bindUserDN="%%LOGIN%%@my.domain.com"
...
searchAttributes="sAMAccountName:login,givenName:firstname,sn:lastname,mail:email,distinguishedName,name,dn:dn"
...
searchGroupFilter="(&(objectClass=group)(CN=GeoPortale*)(member:1.2.840.113556.1.4.1941:=%%distinguishedName%%))"
...
searchGroupBaseDN="CN=Users,DC=my,DC=domain,DC=com"
```
and finally
```
php lizmap/install/installer.php
lizmap/install/set_rights.sh www-data www-data
```

**Comment by quelo1972** [comment]
Some details, I've done the following steps:
```
cd /var/www/
MYAPP=ldapdao-module
VERSION=2.0.6
wget https://github.com/jelix/$MYAPP/archive/v$VERSION.tar.gz
tar xvzf v$VERSION.tar.gz
rm v$VERSION.tar.gz
cd $MYAPP-$VERSION
cp -r ./ldapdao/ /var/www/lizmap-web-client-3.1.20/lizmap/lizmap-modules/
cd ..
cp ldapdao-module-2.0.6/ldapdao/install/authldap.coord.ini.php lizmap-web-client-3.1.20/lizmap/var/config/
```
I declared the ldapdao module in the file `lizmap/var/config/localconfig.ini.php`
```
[modules]
ldapdao.access=1
```
and redefined the state of the following parameters in the same file:
```
jacl2.access=1
jauth.access=2
jauthdb.access=1
```
I redefined the path to the authentication file in the following files:
```
lizmap/var/config/localconfig.ini.php
lizmap/var/config/admin/config.ini.php
lizmap/var/config/index/config.ini.php
```
as follow
```
[coordplugins]
auth="authldap.coord.ini.php"
```
I created a profile in `lizmap/var/config/profiles.ini.php` as follow
```
[ldap:pgldap]
hostname=my.domain.com
port=389
adminUserDn="cn=administrator,ou=adminstrators,dc=my,dc=domain,dc=com"
adminPassword="*************"
```
and configured the file `lizmap/var/config/authldap.coord.ini.php ` as follow
```
[LDAPDAO]
...
ldapprofile = "pgldap"
...
searchUserBaseDN="OU=Comune di Spoleto,DC=my,DC=domain,DC=com"
...
searchUserFilter="(sAMAccountName=%%LOGIN%%)"
...
bindUserDN="%%LOGIN%%@my.domain.com"
...
searchAttributes="sAMAccountName:login,givenName:firstname,sn:lastname,mail:email,distinguishedName,name,dn:dn"
...
searchGroupFilter="(&(objectClass=group)(CN=GeoPortale*)(member:1.2.840.113556.1.4.1941:=%%distinguishedName%%))"
...
searchGroupBaseDN="CN=Users,DC=my,DC=domain,DC=com"
```

**Comment by pcav** [comment]
Is this still valid?

**Comment by laurentj** [comment]
I'm in favor to close this issue. Lizmap 3.1 is not maintained anymore. It's better for @quelo1972 to migrate to Lizmap 3.2 or 3.3 (it's better), as ldapdao is preconfigured into these versions, and so it is easier to enable ldap into them.
