### ISSUE TITLE
Latest stable release

### ISSUE THREAD

**Issue by bgisb** [3liz/lizmap-web-client#1291]
Hi! Could you please advice if version 3.2.3 is the latest stable release? As far as I know, it should be, but, also I can see _Latest release_ tag with 3.1.20.
![release](https://user-images.githubusercontent.com/48524622/61636300-9ddb2480-ac95-11e9-883e-78c45fa9354d.png)

Maybe it's obvious, but I'd rather ask.

**Comment by rldhont** [comment]
The latest published release is the 3.1.20 but the latest advanced version released is the 3.2.3.

It's the github way to manage version.

**Comment by bgisb** [comment]
Thank you!
