### ISSUE TITLE
edition bolean: perte de l'affichage de l'alias

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#130]
perte de l'affichage de l'alias des boites à cocher 

![limicole edition](https://cloud.githubusercontent.com/assets/6421175/6552811/4bc27396-c64a-11e4-9bca-459f83439535.jpeg)

qgis 2.8.1 mapserver 2.8.1 lizmap2.11beta3

**Comment by jancelin** [comment]
salut,
ça remarche mais pas du bon côté...
![limicole edition](https://cloud.githubusercontent.com/assets/6421175/6570838/3946be2c-c701-11e4-8358-8bb612afadd4.jpeg)

bonne journée

**Comment by rldhont** [comment]
Bonjour, cette implémentation est voulue afin de pouvoir cliquer sur le libellé.

Bonne journée
