### ISSUE TITLE
qgisForm class: undefined $v variable during widget option reading

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1300]
### What is the bug?

At the [line 153](https://github.com/3liz/lizmap-web-client/blob/56db5bdb1ce895865fafc3c8617e1aac0aac248c/lizmap/modules/lizmap/classes/qgisForm.class.php#L153), `$v` is undefined.

If I could find an XML schema of Qgis XML format, I could fix it but I don't know from which element we should retrieve the value attribute.

Probably from the `<option>` element itself? SO it could be fixed as: 

`$values[] = (string) $l->attributes()->value;`

@rldhont an idea?

**Comment by rldhont** [comment]
It seems `$v` has to be changed to `$l`.
