### ISSUE TITLE
Execute custom PHP Scripts stored inside media

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1305]
In a custom javascript file I would like to be able to execute a php script (example to request a database and display the results in a mini dock). One solution could be to simply put all my php files in a directory readeable by apache and specify it inside my JS Script. But a cleaner approach could be to add them like custom JS or CSS inside a media directory related to a project.

Is there a way to get the path and execute a php script stored inside my media directory ?

**Comment by rldhont** [comment]
To use PHP, you need a Jelix Module https://docs.jelix.org

**Comment by arno974** [comment]
Do you mean I must develop a module for a simple php script ? It's a bit overkill isnt't ?

**Comment by laurentj** [comment]
>Is there a way to get the path and execute a php script stored inside my media directory ?

In most installation, the media directory, or the data directory, is accessible to any user that have a ftp/ssh account. So a user may store any PHP script that could be bad things, like access to the internal configuration of lizmap (credentials to a database for example), access to some sensitive files of the server etc.

And allowing to execute PHP scripts from these directory, with a call from JS, means also:

- configuring the web server to access to the media directory from the web, so if it is bad configured, we can access directly to some sensitive files like qgis files etc
- or it means that a service (like a kind of proxy) should be created into lizmap allowing to execute this script, but the code into the script could be causes conflicts.

So I'm not in favor to allow this. The medias or data directory is not the "cleaner approach" ;-)

Only the administrator of the server should be allowed to add modules or additional PHP scripts. And if he is agree to add custom scripts, the better place is the lizmap/www directory (or lizmap/lizmap-modules/ for custom modules).
