### ISSUE TITLE
Manually migrating SQLite users passwords from lizmap 2 to lizmap 3

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#1312]
I want to manually migrate the jauth users passwords from lizmap 2.12 (my current server) to lizmap 3 master (new server I am preparing).

I tried this guide https://docs.lizmap.com/3.1/en/install/upgrade.html but encountered a lot of problems so I opted to do the migration manually.

I have everything now migrated and working like a charm but the only issue I find is in the migration on users' passswords. On `jlx_user` table the passwords are not hashed the same in both lizmaps. 

In lizmap 2,12 the `usr_password` for `usr_login='admin'` is `'d033e22ae348aeb5660fc2140aec35850c4da997'`. This stands for "admin" password and looks like hashed using SHA1 algo.

In lizmap master  the `usr_password` for `usr_login='admin'` is `'$2y$10$WqGfNV5Ce5mPCH4f77Qt1.g3SuqwjItxjB3ciY5AcEsND51OwMWVu'`.  This stands for "admin" password too but looks like is hashed using BCRYPT algo. I don't know if there is a salt or if it is using several rounds but I can't reproduce de output from "admin" input using bcrypt on online websites.

Which is the exact new hashing function?

I have the non-hashed passwords of all users too, so if I had a way to call the function that hashes the password that would be it. I don't mind if it is an external web, there are 150 users and I can do it 1 by 1 if there is not another alternative...

**Comment by jaitor1** [comment]
I only had to update users table and set status=1. All passwords worked after that although they where hashed in SHA1. Once login is ok it automatically rehashes to BCRYPT and updates the password.

**Comment by nboisteault** [comment]
@jaitor1 thank you for your feedback !
