### ISSUE TITLE
Lizmap WC and QGIS server 3.x

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1315]
Hello
we are maintaining our servers with lizmap wc.
Based on some post here on github  If I want to use Qgis server 3.4.x I need to use Lizmap WC 3.3.x.
3.2.x don't work with qgis server 3.4.x?
Is 3.3.x stable enough for production??

Thanks
Pietro

**Comment by nboisteault** [comment]
Lizmap 3.3.x should be stable enough for production. Tests are welcome.

**Comment by pcav** [comment]
I confirm, we are using it in production.

**Comment by pieri70** [comment]
Thanks!
We will move to that client version.
pietro
