### ISSUE TITLE
Problem with a WMS repository - QGIS Server

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#1316]
I encountered today a problem with the following wms repository of Genoa Municipality 

https://mappe.comune.genova.it/geoserver/wms?service=wms&version=1.3.0&request=GetCapabilities

I tested various layers and but qgis server say me that the layers are not valid.

It not seem to be a problem of lizmap with WMS because I tested several other WMS service and they work without problems. 

Anyone can test it?

Probably it is a problem f the WMS service, but I have no idea about the reason so it is difficult to contact the technician of Genoa municipality to ask to fix it.

**Comment by josemvm** [comment]
hi @rmarzocchi84 

i tested some layers and evething works fine

not if you set

> Third-party WMS layers/Get images directly from WMS Server

AND

> Single Tile

**Comment by rmarzocchi84** [comment]
I try (e.g with "BACINI IDROGRAFICI" layer)  using the following options:

![image](https://user-images.githubusercontent.com/4061154/63608689-e14aea80-c5d5-11e9-91b3-87e239684137.png)

but it do not works

**Comment by josemvm** [comment]
yes, no problems:
![imagem](https://user-images.githubusercontent.com/10053874/63640651-9a72f880-c69a-11e9-8a79-5a7131ce305b.png)
i'am using lwc 3.3rc4 and qgis server 2.18

**Comment by rmarzocchi84** [comment]
I use qgis 3.4.11 and lwc 3.3rc2

Eng. Roberto Marzocchi, PhD
GIS Project Coordinator
Gter srl (Unige spin-off)
Piazza De Marini 3/61 - 16123 Genova
P.IVA/CF 01998770992
ph: 010-8694830 - mob: 349-8786575
E-mail: roberto.marzocchi@gter.it
www.gter.it

--
Gter social
www.twitter.com/Gteronline - www.facebook.com/Gteronline
www.linkedin.com/company/gter-srl-innovazione-in-geomatica-gnss-e-gis

-----------------------------------------------------------------
Please consider the environment before printing this email! 




---- On sab, 24 ago 2019 19:12:07 +0200 notifications@github.com wrote ----



yes, no problems:

i'am using lwc 3.3rc4 and qgis server 2.18

**Comment by rmarzocchi84** [comment]
It seems a qgis server bug? Anyone can confirm it?

**Comment by rmarzocchi84** [comment]
QGIS SERVER LOG: 

```
10:36:38 WARNING WMS[31162]: Download of capabilities failed: SSL handshake failed
10:36:38 CRITICAL Server[31162]: Layer(s) BACINI_IDROGRAFICI_a99b6847_544c_44f2_8d46_4f51fb97b650 not valid
```
