### ISSUE TITLE
Lizmap 3.2.3 symbol color

### ISSUE THREAD

**Issue by matteoconte** [3liz/lizmap-web-client#1317]
Hy all,
I've created a new server (ubuntu 16.04) with lizmap 3.2.3. When I tranfert a project from an old server (ubuntu 16.04) with lizmap 3.1.11 all work fine but the color of symbols are change from red to black.
Why? 

LINK OLD SERVER=>https://www.abitatsit.it/lm/index.php/view/map/?repository=3&project=Sanuto_IllasiSoaveColognaLonigo
LINK NEW SERVER=>https://lizmap.abitat.it/lm/index.php/view/map/?repository=1&project=Sanuto_IllasiSoaveColognaLonigo

Anyone can help me?
Kind regards,
Matteo

**Comment by nboisteault** [comment]
@matteoconte which QGIS Server version are you using ?

**Comment by matteoconte** [comment]
@nboisteault On new server I have QGIS Server 2.18. On the old server QGIS version is <=2.14.
I find these values in Lizmap Admin pannel.
Kind Regards
Matteo

**Comment by nboisteault** [comment]
@matteoconte please tell me QGIS Server version installed on your server. Also which OS is it, Linux Windows ? That's why it is better to fill the issue template.

**Comment by matteoconte** [comment]
@nboisteault  my os is Ubuntu 16.04.6 LTS and QGIS server version (finded with apt-cache policy qgis-server) is 2.8.6+dfsg-1ubuntu1.

**Comment by nboisteault** [comment]
@matteoconte 2.8.6 is too old. Please test at least 2.18.x. Or 3.4.x if you want the last supported version.

**Comment by matteoconte** [comment]
@nboisteault If I remove qgis-server (with "apt-get autoremove --purge qgis-server python-qgis command") and execute the command "apt-cache policy qgis-server" in "candidate" i find 2.8.6+dfsg-1ubuntu1.
In /etc/sources.list I added these line
deb     https://qgis.org/debian xenial main
deb-src https://qgis.org/debian xenial main
Why I don't see 2.18.x version?
Thks

**Comment by matteoconte** [comment]
I solved it. The problem was https protocol. I replaced https with http and I found the 2.18.16+24 version.
Thks

**Comment by nboisteault** [comment]
@matteoconte You can also try [this procedure](https://scriptndebug.wordpress.com/2018/02/27/installing-qgis-3-on-ubuntu-16-04/) if you want 3.4 version.

**Comment by nboisteault** [comment]
@matteoconte does it work now ?

**Comment by matteoconte** [comment]
Hi @nboisteault yes now work fine. Tnks
