### ISSUE TITLE
Is it possible to keep layer dock fixed (not hide when popup dock appears)?

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#1318]
When I click on an element the layers dock is closed and the popup dock is shown. 
It makes my users angry to have to open the layers dock again and again after they click the info of an element...is it possible to make it fixed so that the popup dock is shown at the right of the layers dock and it is never hidden unless you do it manually?

**Comment by rldhont** [comment]
Popup cannot be configured to be displayed in the right dock.

@jaitor1 is teh min-dock too small ?

**Comment by jaitor1** [comment]
@rldhont is a bit annoying that layers dock is closed every time popup dock appears. That's the feedback I got from my users at least. 
I was asking if maybe layers dock could be somehow fixed (doesnt disappear and popup dock stays next to layers dock, not on the right on the screen as you understood).

**Comment by jaitor1** [comment]
Maybe I could make a JS to reopen the layers dock when popup dock is closed? Is this possible?

**Comment by jaitor1** [comment]
I noticed that there is an option in Lizmap QGIS plugin to place the popup in different places.
