### ISSUE TITLE
[feature] - add document preview with zoom controls for pdf docs in data/display info

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1321]
![imagem](https://user-images.githubusercontent.com/10053874/64076078-fc91b600-ccb7-11e9-91ab-14974c492544.png)

**Comment by josemvm** [comment]
just remember LizmapTeam ;-)

**Comment by Gustry** [comment]
I think you can already do it with the "QGIS HTML maptip" popup if you generate the correct HTML : 
https://www.w3docs.com/snippets/html/how-to-embed-pdf-in-html.html

**Comment by josemvm** [comment]
hi @Gustry after several experiments, i can conclude that this can be done very easily:

popup source: QGIS HTML maptip:
`<iframe src="[%"pdf_field_name"%]" width="100%" height="500px"></iframe>`

popup source: Lizmap HTML:
`<iframe src="{$pdf_field_name_OR_alias_pdf_field_name_if_exists}" width="100%" height="500px"></iframe>`
