### ISSUE TITLE
public base layers - missing transparency

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1325]
is it a bug or an impossibility?
thanks

**Comment by nboisteault** [comment]
Is it what you are missing ? The UI has to be improved.

![image](https://user-images.githubusercontent.com/2145040/64440424-3ace1180-d0cc-11e9-9f92-d17cc249dfb0.png)

**Comment by josemvm** [comment]
it is present but it doesn´t work for google maps

**Comment by josemvm** [comment]
it works for openstreetmaps, ign and other base layers, but not for google maps base layers...

**Comment by nboisteault** [comment]
[It is a limitation](http://osgeo-org.1560.x6.nabble.com/Openlayers-2-13-1-Google-maps-not-showing-recently-Sep-2015-td5222280.html).

**Comment by josemvm** [comment]
@nboisteault thanks for your answer
