### ISSUE TITLE
If layer name (as defined in QGIS) has spaces in it, then Filtering data in function of users does not work

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#1328]
QGIS Server 3.4
LMWC 3.3

Description: see subject. On map the filter is ok, but for attributes table, locate by layer the whole list of records is shown.

**Comment by gioman** [comment]
Oddly enough accented letters seems to be ok, problem is just spaces.

**Comment by nboisteault** [comment]
@rldhont findLayerByTypeName() found it !
