### ISSUE TITLE
Numeric fields missing CSS class

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#1329]
Minor bug, in the editing form the fields that are numbers (tested integer) seems to miss a CSS class when compared to string fields:

![Screenshot_20190910_154155](https://user-images.githubusercontent.com/1951107/64624139-1c288d00-d3e2-11e9-8718-21d1fa447c8d.png)

LMWC 3.3

**Comment by nboisteault** [comment]
I can't reproduce this issue with LWC 3.3.4-pre. Can you give us the HTML of wrong display input or better a small project ?

**Comment by nboisteault** [comment]
@gioman gentle ping :)

**Comment by gioman** [comment]
@nboisteault sorry I missed the ping. I'll check.

**Comment by gioman** [comment]
Can't replicate anymore, thanks.
