### ISSUE TITLE
wfsOutputExtension

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1331]
**What is the bug?**

I Installed the QGIS Server plugin wfsOutputExtension but I do not get the additional formats
<GML2/>
<GML3/>
<GeoJSON/>

**Steps to reproduce the issue**

I installed the plugin here :
/opt/qgis-server/plugins

I added these lines in my conf file in sites-enabled
 ```
        FcgidIOTimeout 120
        FcgidInitialEnv LC_ALL "en_US.UTF-8"
        FcgidInitialEnv PYTHONIOENCODING UTF-8
        FcgidInitialEnv LANG "en_US.UTF-8"
        FcgidInitialEnv QGIS_DEBUG 1
        FcgidInitialEnv QGIS_SERVER_LOG_FILE ${APACHE_LOG_DIR}/qgis-000.log
        FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0
        FcgidInitialEnv QGIS_PLUGINPATH "/opt/qgis-server/plugins"
        FcgidInitialEnv HOME "/srv/qgis"

        <IfModule mod_fcgid.c>
            RewriteEngine on
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
        </IfModule>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
            AllowOverride All
            Options +ExecCGI -MultiViews +FollowSymLinks
            Require all granted
            #Allow from all
        </Directory>
```
restart Apache

**Expected behavior**

No additional format...
I have a doubt on the variable HOME. I have nothing in this directory...
Do I need to install qgis server AND qgis on my server ?

**Environment**

    Lizmap version: 3.3.0
    QGis server version: 3.4
    OS (windows, linux, macOS, android..): Debian 10
    Browser (Firefox, Chrome...): all
    Lizmap data stored into Postgresql

**Comment by gioman** [comment]
In Lizmap web control panel, the URL for QGIS Server must point to the actual domain (not 127.0.0.1 or localhost) otherwise the plugin won’t work.

**Comment by Cww7** [comment]
I modified the URL but it still does not work, nothing happened...

**Comment by Gustry** [comment]
@Cww7 Can you check your QGIS logs? You will find if the plugin has been detected and loaded.

> I have a doubt on the variable HOME. I have nothing in this directory...

Yes, correct. QGIS-Server will use this directory to write some temporary outputs.

> Do I need to install qgis server AND qgis on my server ?

No, no need for QGIS Desktop to be on the server.

**Comment by Cww7** [comment]
I can't find my QGIS logs in the log directory... 
The documentation of qgis indicates : 

> QGIS_SERVER_LOG_FILE is deprecated since QGIS 3.4. File logging support will be removed in QGIS 4.0.
