### ISSUE TITLE
[LWC][3.3.0] Fresh install can't enter with default admin credentials

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#1333]
### What is the bug?
After a clean install of lizmap https://github.com/3liz/lizmap-web-client/releases/tag/3.3.0 can't enter with default admin account 
Username: admin
Password: admin

The result is opening of the same login dialog

### Steps to reproduce the issue

1. Go to http://localhost/teste/admin.php/auth/login/
2. Add admin in username and password fields.
3. Clique enter.
4. The values are erase and stays in the same page.

### Expected behavior
Insert **admin** word in username and password field and open the Admin dashboard.

### Screenshots and logs

![login](https://user-images.githubusercontent.com/4480601/65036745-08ca7400-d944-11e9-9396-a99490b50b71.PNG)

### Environment
 - Lizmap version: 3.3.0
 - QGIS Server version: 3.4.12
 - QGIS Project version: Demo Lizmap projects
 - OS (Windows, Linux, MacOS, Android…): Windows 64-bits
 - php version: 7.3.9
 - Apache version: 2.4
 - Browser (Firefox, Chrome…): Firefox, Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

**Comment by jonnyforestGIS** [comment]
My lizmap log say this when I try to atempt to login with admin admin:

```log
::1 - - [17/Sep/2019:12:16:22 +0100] "POST /teste/admin.php/auth/login/in HTTP/1.1" 303 -
::1 - - [17/Sep/2019:12:16:22 +0100] "GET /teste/admin.php/auth/login/ HTTP/1.1" 200 1530
```

**Comment by jonnyforestGIS** [comment]
Found the problem. in lizmap error.log in jelix i don't define a correct folder to the sessions.

I will close this.
Solved.

**Comment by Gustry** [comment]
@jonnyforestGIS What should be added in the documentation?

**Comment by jonnyforestGIS** [comment]
@Gustry in my case was the wrong path of php sessions in the php.ini file. The path that I had didn't exist.
