### ISSUE TITLE
[Form] Display values from Array field in lizmap edit form

### ISSUE THREAD

**Issue by drillinP** [3liz/lizmap-web-client#1340]
### What is the bug?

When I want edit layer in Lizmap I have a problem with array type fields. In form this fields are represented by checkboxes. When I  am on edit form, the fields values are not checked.

### Steps to reproduce the issue

1. Need an array field in database: integer[]
2. In QGIS put the field in relational value which references another layer in properties ->attribute form
3. make the layer editable on Lizmap
4. In Lizmap select a feature and click edit layer
5. see none of the checkboxes are checked

### Expected behavior

The value get from database is {102,104,107,108}, jelix does not recognized it as a list of value.

### Screenshots and logs

Select feature
![select](https://user-images.githubusercontent.com/16720972/65977499-5251ad80-e472-11e9-9602-04ad02ec207f.png)

Field with relationnal value not empty
![field](https://user-images.githubusercontent.com/16720972/65977617-8af18700-e472-11e9-960a-57c1151f8579.png)

Edit feature: none are checked
![check](https://user-images.githubusercontent.com/16720972/65977727-bf654300-e472-11e9-95dc-aea132f884a4.png)

### Environment

 - Lizmap version: 3.3
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome and Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by nboisteault** [comment]
Working on it.

**Comment by rldhont** [comment]
@nboisteault thanks
