### ISSUE TITLE
QGIS Server version visible in admin panel

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1346]
### Is your feature request related to a problem? Please describe
QGIS Server is not visible in administration panel. When you don't have access to server, you can't know QGIS Server version.

### Describe the solution you'd like
If would be handy to have QGIS Server version visible in admin panel **at least for admins**.

**Comment by Gustry** [comment]
With Lizmap 4.0, we will have a lizmap plugin on the server side, it will be easy to get the version from there.

**Comment by Gustry** [comment]
FYI, QGIS Server is giving its version number in the HTTP header:
`http://qgis.server/ltr?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`

```
HTTP/1.1 500 Internal Server Error
Date: Wed, 30 Oct 2019 09:50:30 GMT
Content-Type: text/xml; charset=utf-8
Content-Length: 54
Connection: keep-alive
Server: Qgis FCGI server - QGis version 3.4.13-Madeira
```

![Screenshot from 2019-10-30 14-12-39](https://user-images.githubusercontent.com/1609292/67860931-73fc8e00-fb1f-11e9-830c-7931f37758e2.png)

**Comment by Gustry** [comment]
Related to this ticket and until we don't have a way to have the precise QGIS Server version (with @rldhont in #1597 and using Lizmap Server plugin)

Can we add a warning, when the project **is displayed**, for admins **only** about : 
* If the Lizmap server is not installed
  * Read the QGIS version in the QGS file and compare it with Lizmap Server configuration. Not  doesn't very precise, but it would save time for debugging already CF https://github.com/3liz/lizmap-web-client/issues/1638#issuecomment-723948112 and many other tickets. It's *enough* for QGIS 2 versus QGIS 3.
* If the Lizmap server is installed
  * Use the JSON CF https://github.com/3liz/lizmap-web-client/issues/1908#issuecomment-723577105

@nboisteault @rldhont Is-it possible to have a message bar for admins ?
It would save us time.

CF, the message bar can be used as well for #1560

**Comment by rldhont** [comment]
Some works has been done https://github.com/3liz/lizmap-web-client/pull/1597

**Comment by Gustry** [comment]
Visible since LWC 3.5
