### ISSUE TITLE
Custom HTML content at top of projects page

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1347]
### Is your feature request related to a problem? Please describe
We need a way to let admin create some HTML content at top of projects page.

### Describe the solution you'd like
- [x] A link in the admin menu to a configuration page (Contenu de la page d'accueil / Landing page content)
- [x] The configuration page has a wysiwyg widget to let the user build the HTML content.
- [x] HTML content is saved in `lizmapConfig.ini.php` in the `[landing_page_content]` section

- [x] HTML content is shown at top of projects page

**Comment by nboisteault** [comment]
@mdouchin @laurentj le contenu du wysiwyg, c'est stockable dans un fichier ini ou ça devrait plutôt aller en base sqlite ou postgres ?

**Comment by mdouchin** [comment]
IMHO, ini file is better

**Comment by laurentj** [comment]
No, ini file is bad to store HTML content. You should store it else where, in a file for example. Or in a template ? 
The problem of the database is we don't have any existing table to store this html part, and we won't create a table just for this item.

**Comment by nboisteault** [comment]
@laurentj If I store HTML in a file, is it ok to put it in `lizmap/var/config/` ?
