### ISSUE TITLE
QGIS projects tags display and search in LWC projects page

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1348]
### Describe the solution you'd like

- [x] Display QGIS projects tags in LWC projects page for each project item
- [x] Let user filter projects based on comma separated tags. Tags will be defined as a comma separated list in QGIS projects.
- [ ] Let user filter projects based on slash separated tags. Tags will be defined as a slash separated list in QGIS projects for hierarchical trees or unidirectional graphs, in this case LWC will handle search with hierarchical filters.

- [ ] Have a new admin menu which shows the list of tags (nodes) and relations between tags (edges), and lists all the published QGIS projects -> the UI could be quite the same as the project page, but could in the future allow the admin user to set up rights or other properties on projects

**Comment by nboisteault** [comment]
@mdouchin is it ok to use ES6 functionalities not working in IE 11 ?

**Comment by mdouchin** [comment]
I would prefer to keep it compatible, since it would land in 3.4 and not in 4.0

**Comment by nboisteault** [comment]
Last point has to be handled in #1856
