### ISSUE TITLE
seeding script : level

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1354]
How can we know what are the useful values for ​​'TileMatrixMin' and 'TileMatrixMax' ?
When i run the script `/script.php lizmap~wmts:capabilities`, it always returns :
`For "layer" and "EPSG:3857" from TileMatrix 0 to 19` 
But I only use scales between 50000 and 1000 and I don't want to generate too much tiles.

**Comment by Gustry** [comment]
I'm not sure, is-it `lizMap.map.getZoom()` in your webbrowser?

**Comment by Cww7** [comment]
I don't find this expression in the html page.

**Comment by Gustry** [comment]
@Cww7 Is it fine on your side?
Can we move this issue to the documentation?

Related ticket https://github.com/3liz/lizmap-plugin/issues/161

**Comment by Cww7** [comment]
Yes, @Gustry, it's ok for me !
