### ISSUE TITLE
Can not select all layers in Lizmap3.4pre that i can in Qgis3.8.3

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#1355]
I am searching why i can not doe all selections in Lizmap that i can doe in Qgis.

Or is this not possibly at this moment ??

![image](https://user-images.githubusercontent.com/8125819/66926464-611d9000-f02e-11e9-92e2-d36b3096598c.png)

 - Lizmap version:  3.4pre
 - QGIS Server version: 3.4.12-1
 - QGIS Project version: 3.8.3
 - OS (Windows, Linux, MacOS, Android…): Windows 10
 - Browser (Firefox, Chrome…): Chrome

**Comment by rldhont** [comment]
you probably disable group checkbox in lizmap plugin.

**Comment by NvBgm** [comment]
That is not the case. I try with group checkbox enable and disable. Same result.
Let me gif a beter example.

In QGIS i can select also the selection witch are in the yelow 

![image](https://user-images.githubusercontent.com/8125819/66990505-a097bb00-f0c6-11e9-99cb-fcf2a486a47a.png)


![image](https://user-images.githubusercontent.com/8125819/66990274-2f580800-f0c6-11e9-9960-a9f18bc1b02c.png)

But in Lizmap i can not .....

![image](https://user-images.githubusercontent.com/8125819/66990401-67f7e180-f0c6-11e9-9db1-3948db7942a4.png)

Sorry for my poor English. I hope you can give a answer. I am looking for day's now to find out if it is possible.

**Comment by Gustry** [comment]
This is not possible in Lizmap for now. It would require some development.
