### ISSUE TITLE
Mise à jour automatique des données de la table attributaire

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#136]
Bonjour,

L'affichage des données via la table attributaire n'est pas synchronisé avec les mouvements de la carte.

Il pourrait être intéressant d'ajouter cette fonctionnalité (peut être une case à cocher dans la fenêtre de la table) afin que la liste de la table se mette à jour automatiquement en fonction des zooms et déplacements de l'utilisateur.

**Comment by mdouchin** [comment]
Je viens d'ajouter une option dans le plugin Lizmap (version de développement) et dans le client Web. Cela 
* ne permet pas d'afficher les données de la table si la couche n'est pas visible
* ajouter un bouton "rafraîchir" qui permet de raffraîchir les données de la table.

Je ne souhaite pas implémenter un rafraîchissement automatique pour des soucis de performances (nombre de requête à chaque fois qu'on zoome ou se déplace dans la carte)

**Comment by rldhont** [comment]
I close it because it has been done
