### ISSUE TITLE
Seeding script path

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1360]
The tiles are generated by default in the /tmp directory with the seeding script but that seems to be a problem when the server is restarted (Debian).
Is it possible to change the path of the cache ?
The automatic cache seems to be generated at another location (/var/www/lizmap-web-client-3.3.0/temp/lizmap) no ?

**Comment by mdouchin** [comment]
The cache provider (files, redis) and directory (for files) can be configured in Lizmap admin panel, with the Service form:
https://docs.lizmap.com/current/en/admin/lizmap-configuration.html#services

**Comment by nboisteault** [comment]
@mdouchin So seeding script can read cache provider set in Lizmap admin panel ?

**Comment by Cww7** [comment]
Wonderful !
Thx @mdouchin !
