### ISSUE TITLE
"filter layer on zoom" does not work anymore in "locate by layer"

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#1361]
QGIS Server 3.14.12 and LMWC 3.3

The datasource is GPKG, PostGIS. The  "locate by layer" functionality works (it zooms to the selected feature) but the layer is not filtered if the "filter layer on zoom" is active.

**Comment by josemvm** [comment]
more tests: if you try with Montpellier project and the Tram lines layer, the locate by layer tool only zooms to the first feature you chosen...

**Comment by geomoes** [comment]
Same behavior. QGIS 3.14-1 on macos, QServer LM 3.3
Datasource is PostGIS-View. I can filter, in "Filter data by form" but the "Zoom to filtered features" does not work.

**Comment by nboisteault** [comment]
In release_3_3 I can't reproduce the issue. Please reopen if issue still occurs.
