### ISSUE TITLE
Themes: logo not replaced

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1362]
When adding a custom logo from
http://10.50.10.93/lm/admin.php/admin/theme/
the first image added cannot apparently be replaced with a new one afterwards.

**Comment by Gustry** [comment]
Which LWC version?
I tried it works.
Did you empty you cache?

**Comment by pcav** [comment]
Old issue, I also did not see it resurfacing recently.
Thanks for checking, and sorry for the noise.
