### ISSUE TITLE
Error rendering grouped layers

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#1363]
### What is the bug?
Grouped layers seems not to be rendered. Image is broken in the legend and nothing is rendered in PNG. In JPEG, white tiles are rendered

This issue came from an installation from 
https://github.com/3liz/lizmap-docker-compose
However I don't know if the issue is in Qgis-Server or Lizmap-Client

### Steps to reproduce the issue

Create a Qgis project with a group of sqlite layers
In Lizmap-plugin enable the option "group as a layer"

### Expected behavior
Same project is rendered properly with an other installation 
(this one : https://github.com/3liz/lizmap-docker)

### Screenshots and logs
![image](https://user-images.githubusercontent.com/49779177/67500091-79228e80-f682-11e9-84fa-3dafa4cb2236.png)

Proper rendering (same qgis project with an other Lizmap installation)
![image](https://user-images.githubusercontent.com/49779177/67500287-bd159380-f682-11e9-9116-130feb019cd7.png)

### Environment

Docker installation
https://github.com/3liz/lizmap-docker-compose

**Comment by vlebert** [comment]
For your information, I solved this issue changing the version of the lizmap client in the docker-compose.yml (I used 3.3)

**Comment by nboisteault** [comment]
@vlebert did you upgrade or downgrade lizmap version ? If the bug is not in last version, please close issue.

**Comment by vlebert** [comment]
Yes inupgraded from 3.2 to 3.3 and i think the docker-compose repository have been corrected by the team.
