### ISSUE TITLE
wrong print scale

### ISSUE THREAD

**Issue by buoncri** [3liz/lizmap-web-client#1368]
### What is the bug?
Print tool make a pdf in wrong scale or better not in the same selected scale in printing tool.  

### Steps to reproduce the issue
1. Go to 'map'
2. Click on 'print'
3. Scroll down to 'select the layout and the scale'
4. The pdf [which is well made in qgis layout, export pdf] is in wrong scale for me

### Environment
 - Lizmap version: 3.3 pre2
 - QGIS Server version: 3.4.10
 - QGIS Project version: 3.10
 - OS (Windows for client and qgis map editing, Linux for html publishing): 
 - Browser (Firefox ):
 - Lizmap admin information (admin user) stored into PostgreSQL

PS: The layout is in right scale in printing from Qgis layout.

**Comment by gioman** [comment]
any public url? what is your project CRS?

**Comment by Gustry** [comment]
Can you copy/paste the URL which is send to Lizmap when you press print? From the web developer console.
You can remove the public part if you don't want to share the server.

**Comment by buoncri** [comment]
Project SR 3004 

It's a intranet and the url is
http://192.168.63.104/intragis/index.php/view/map/?repository=intragis&project=Irrigazione#print

The url for the print button
<button id="print-launch" class="btn-print-launch btn btn-small btn-primary btn-block"><span class="icon"></span>&nbsp;Stampa</button>

The script for the print button call printing seems to call another SR and is
http:// ... intragis/js/map.js:4167

**Comment by Gustry** [comment]
I meant to have the HTTP request which is made to lizmap server when you press the "print" button. You should find it the "network" tab.
Open the developper tools, network tab, and then press "print". You wil lsee the full URL with like "REQUEST=GetPrint&....".

**Comment by buoncri** [comment]
Thk for the patience :-D 

repository=intragis
project=Irrigazione
LAYERS=impianti_irrigazione
STYLES=predefinito
VERSION=1.3.0
EXCEPTIONS=application%2Fvnd.ogc.se_inimage
FORMAT=image%2Fpng
DPI=96
TRANSPARENT=TRUE
SERVICE=WMS
REQUEST=GetMap
CRS=EPSG%3A3857
BBOX=1347406.985515301,5263134.944333963,1487898.2434838987,5337661.046901636
WIDTH=1838
HEIGHT=975

**Comment by Gustry** [comment]
@buoncri This is a `REQUEST=GetMap` request. As mentioned in my previous comment, it should be a `REQUEST=GetPrint` which is fired by LWC for a PDF print.

**Comment by buoncri** [comment]
'''
https://mercatore.bonificaumbra.local/intragis/index.php/lizmap/service/?repository=intragis&project=Irrigazione&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:3857&DPI=100&TEMPLATE=A3%20Orizzontale&map0:extent=1408973.685059,5302574.694245,1409787.704633,5303146.708&map0:scale=2000&map0:LAYERS=catasto_terreni,CATASTO_fogli,CATASTO_comuni,impianti_irrigazione&map0:STYLES=predefinito,predefinito,predefinito,predefinito&LAYERS=catasto_terreni,CATASTO_fogli,CATASTO_comuni,impianti_irrigazione&STYLES=predefinito,predefinito,predefinito,predefinito&OPACITIES=255,255,255,255
'''

**Comment by gioman** [comment]
> SRS=EPSG:3857&

you have baselayers active from OSM, Google, etc. so LMWC switches automatically the CRS to 3857 and prints (and shows the map) at the scales those map are available (because are not available at arbitrary scales).

**Comment by buoncri** [comment]
Yes, now i can see the light :-D I will try to switch project to 3857 to have right printing scale

**Comment by Gustry** [comment]
> > SRS=EPSG:3857&
> 
> you have baselayers active from OSM, Google, etc. so LMWC switches automatically the CRS to 3857 and prints (and shows the map) at the scales those map are available (because are not available at arbitrary scales).

I'm planning to improve the UI in Lizmap QGIS plugin about that: https://github.com/3liz/lizmap-plugin/issues/161

**Comment by buoncri** [comment]
PS:
Switching project default CRS to 3857 the problem remain, the scale is the same as first post on this tread

**Comment by gioman** [comment]
>  Switching project default CRS to 3857 the problem remain, the scale is the same as first post on this tread

@buoncri I think I may have explained myself poorly: it is not about if your project is in EPSG 3857, is about if you have baselayers from OSM, Google, etc.: If you have such baselayers the project must be in 3857 (as they are not reprojectable) and the scales used are no more the one you defined in the LM plugin, as those layers are not available at arbitrary scales, but only at fixed ones > https://gis.stackexchange.com/a/7443
