### ISSUE TITLE
Mutually exclusive groups are not honoured in case of subgroups

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1369]
If a mutually exclusive group has a non-exclusive subgroup, this works as expected in the desktop, but not in LM: activating the subgroup does not deactivate the other layers.

**Comment by itsakifa** [comment]
Is there any news about this issue?

**Comment by Gustry** [comment]
Please follow ticket template for bugs with required information : LWC version, QGIS version etc. Thanks

**Comment by pcav** [comment]
LWC 3.3.6
QGIS 3.10

**Comment by pcav** [comment]
Server on Debian Sid, Clients both on Chrome and FireFox.
Thanks.

**Comment by pcav** [comment]
Has this been fixed?

**Comment by nboisteault** [comment]
It now works in Lizmap 3.7!
