### ISSUE TITLE
Grouper les champs lors de l'édition des données attributaires

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#137]
Bonjour,

Dans le paramétrage des champs d'une couche QGIS, il est possible de grouper les champs en fonction de catégories préalablement définies [1].

Il pourrait être intéressant dans l'interface web de LizMap  de reproduire cette même logique en utilisant le composant tab [2] de Bootstrap.

Qu'en pensez-vous ?

Arnaud

[1] http://docs.qgis.org/2.2/en/docs/user_manual/working_with_vector/vector_properties.html#figure-fields-2
[2] http://getbootstrap.com/javascript/#tabs

**Comment by rldhont** [comment]
C'est une idée que nous n'avons pas encore eu le temps d'implémenter.

**Comment by rldhont** [comment]
It's done! You can test it in 3.0Beta4 https://github.com/3liz/lizmap-web-client/releases/tag/3.0beta4
