### ISSUE TITLE
GetCapabilitiesAtlas strange request

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#1376]
In the log file I see the following lines:  

```

warning	2019-11-06 12:01:40	[2]	file_get_contents(http://XXXXXXXX/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=path_to_project/xxx.qgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
	/home/gter/lizmap-web-client-3.3git/lizmap/modules/lizmap/classes/lizmapProxy.class.php	236
```

I do not know exactly what it is mean the message, but the **GetCapabilitiesAtlas** is allowed in qgis server?

**Comment by rldhont** [comment]
It is added by https://github.com/3liz/qgis-atlasprint QGIS Server Atlas Print plugin.

This request is done by Lizmap-Web6client to request QGIS Server if the plugin is installed.

**Comment by nboisteault** [comment]
We have deprecated the QGIS Server Atlas plugin with coming Lizmap 3.7. We now use the [ATLAS_PK](https://docs.qgis.org/3.22/en/docs/server_manual/services/wms.html#wms-atlaspk) parameter.
