### ISSUE TITLE
Add option to hide Base layer switch

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#1377]
Hello.
If is possible add an option to hide base layer switch from left menu bar.
Thanks

**Comment by nboisteault** [comment]
You can hide it with some CSS.

**Comment by ygorigor** [comment]
Unfortunately I don't know how to do it

**Comment by mdouchin** [comment]
I do not understand why you would like to hide it. It is hidden by default when there is only one baselayer. If you have more than one, how would the user change the active baselayer with no selector ? Or you would like to propose another selector ?

We have a JS script which adds a new way to choose the baselayer, with images "a la Google Maps"
https://github.com/3liz/lizmap-javascript-scripts/tree/master/background_selector
Example in action here:

**Comment by ygorigor** [comment]
I'm using this JS script, this is the reason why I want to hide base layer switch.
Maybe in this script is possible to to add something to hide base layer, but I don't know how.

**Comment by nboisteault** [comment]
Follow the [doc](https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#creating-simple-themes) to create a `map.css` file for your project or directory in which you put :

```css
#switcher-baselayer{
    display:none
}
```

**Comment by ygorigor** [comment]
@nboisteault thanks. It works

**Comment by mdouchin** [comment]
nb: do not forget the semi-colon after the `display:none;`

**Comment by nboisteault** [comment]
@mdouchin Maybe we can add a README.md in the background_selector directory to tell how to hide the switcher-baselayer. We could point to the method of simple theme or add the CSS part to `background_selector.css` and tell how to comment ?

**Comment by ygorigor** [comment]
> nb: do not forget the semi-colon after the `display:none;`

thanks

**Comment by Gustry** [comment]
@nboisteault In the JS file as comment?

**Comment by nboisteault** [comment]
@Gustry I'm not sure every users will read it.

**Comment by ygorigor** [comment]
@nboisteault I moved 

#switcher-baselayer{
    display:none;
}

to background_selector.css

**Comment by Gustry** [comment]
@nboisteault Ah yes, indeed,  I read too quick. It's indeed a directory, so a readme.md would help.

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-javascript-scripts/pull/16
