### ISSUE TITLE
problème affichage couche

### ISSUE THREAD

**Issue by kali06** [3liz/lizmap-web-client#138]
Bonjour,

je travaille actuellement sur 4 projets qgis que je souhaite convertir en autant d'applications sous lizmap, ces projets ont les mêmes couches communes, seules les droits d'édition varient en fonction des applications

le problème lorsque je publie ces projets est que la première application à toutes les couches qui s'affichent,

la seconde application à des couches en moins,

la troisième application à encore moins de couches qui s'affichent et la dernière application n'a quasiment plus de couches,

Le problème ne vient pas des applications mais de l'ordre d'ouverture de ces projets, quelques soient la première application que j'ouvre sur le navigateur, elle aura toutes les couches, quelques soit la dernière application, elle aura trés peu de couche, et ce jusqu'a que je redemarre le serveur,

je souhaiterais savoir si vous aviez des éléments de réponses pour résoudre ce problème,
 en vous remerciant,

**Comment by rldhont** [comment]
Bonjour,

Il se pourrait que le problème provienne des identifiants des couches.

Avez-vous recréé chacune des couches pour chaque projets ?
SI vous ouvrez les projets dans un éditeurs de texte, pouvez-vous vérifier les identifiant des couches et vérifier que ceux-ci sont tous différents ?

**Comment by kali06** [comment]
Bonjour,

merci de votre réponse,

non je n'avais pas recréé les couches,

j'avais un projet global sous qgis que j'ai duppliqué 4 fois (enregistré sous de qgis),

par contre quand j'ai recréé un projet de 0 pour chaque application, quand bien même il y avait des couches communes,

les applications n'ont eu aucun problème et fonctionnaient trés bien,

**Comment by rldhont** [comment]
Le problème venait donc des identifiants commun entre projets QGIS. Votre problème provient de la gestion des couches dans QGIS-Server.

Ayant solutionné votre problème, je me permet de fermer cette discussion.
