### ISSUE TITLE
How to format the data viewed with the relations

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#1381]
When I see the data linked to an object I can choose which fields to see and how to view them with a code to be inserted in the Lizmap plugin in Layers > Activate popup > source Lizmap.

My problem is when I want to see related data by selecting "Display related children under each object (use relations)". I see all data field by field without formatting.

I would like to know how to format also this data viewed with relations in order to select how and which fields to view.

Thanks in advance

**Comment by Gustry** [comment]
@news24lor Did you solve your question? I'm indeed not sure about the behavior.

**Comment by nboisteault** [comment]
@news24lor Did you try to create those popups with QGIS HTML Map Tip ? Those are more powerful than Lizmap ones.

**Comment by news24lor** [comment]
Hi @nboisteault 
I tried to use HTML QGIS but couldn't get an interesting result. I made the page in HTML with the codes of the fields but since the related data are a lot I can't show them in a LOOP. I tried to insert the HTML in the table of the related data but it doesn't work. Maybe with javascript but I don't know. Do you have some tips to use this internal QGIS function in a complete way?

**Comment by nboisteault** [comment]
I said that QGIS HTML Map Tip are powerful because you can use QGIS Expressions (the little epslion at bottom). I'm sure you'll find what you need in [documentation](https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/expression.html). `relation_aggregate` function might help you for example.

**Comment by Gustry** [comment]
> I made the page in HTML with the codes of the fields but since the related data are a lot I can't show them in a LOOP

Do you mean you where using the auto popup before because you got too many fields to build the HTML manually?

**Comment by news24lor** [comment]
Hi @Gustry 
Yes I have many fields but with the advice of @nboisteault  I will use `relation_aggregate`.

It’s closed for me.
Thanks
