### ISSUE TITLE
Information panel cannot be closed

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1386]
### Screenshots and logs
<img width="1139" alt="Capture d’écran 2019-11-13 à 12 48 47" src="https://user-images.githubusercontent.com/7761073/68765204-25b5b780-0614-11ea-91b9-e006b20395c9.png">

### Environment

 - Lizmap version: 3.3.2
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4.13
 - OS (Windows, Linux, MacOS, Android…):  MacOS
 - Browser (Firefox, Chrome…): Safari,Firefox

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/pull/1426
