### ISSUE TITLE
"localisation par couche" limitation aux couches de moins de 6290 objets

### ISSUE THREAD

**Issue by antoine373** [3liz/lizmap-web-client#139]
Bonjour,
Je viens de faire la MAJ vers la dernière version de lizmap : 2.11.0
Cette dernière est encore plus performante (merci pour votre super travail), mais je rencontre un problème avec l'outil de localisation. Il fonctionne très bien avec certaines couches, mais avec d'autres rien ne se passe. C'est notamment le cas pour les deux couches que j'utilise le plus pour la localisation : le cadastre et les adresses. Est-ce que le fait d'avoir énormément d'objets (plusieurs milliers) peut poser problème ?
A savoir qu'avec ces mêmes couches la localisation fonctionnait très bien sous lizmap 2.10.0....

Ma configuration : 
Lizmap 2.11.0
Qgis server 2.8.1

EDIT------
Je pense qu'il s'agit bien d'une limitation du nombre d'objets, j'ai fait le test avec une couche de cadastre : la localisation fonctionne parfaitement avec 6289 objets et par contre avec 6290 plus rien ne marche.

**Comment by doducdung** [comment]
Hello  there, I am new in LizMap. I try to use LizMap plugin to publish map to the web. It work well in the localhost but when I upload it to the server it could not. Do you know how to solve this problem? Could you please help me?Thank you very much in advance. -------------------------------------------------- --------------------------- 
Do Duc Dung 
Deputy Director 
Southern Institute for Water Resources Planning (SIWRP) 
An Duong Vuong 271/3 Str., Dist. 5, Ho Chi Minh City 
Mobile: 0932 881 369 Phone: 84-8-3 8354456 Fax: 84-8-38351 721 
Email: doducdung@yahoo.com
      From: antoine373 <notifications@github.com> To: 3liz / lizmap-web-client <lizmap-web-client@noreply.github.com> Sent: Thursday, April 9, 2015 9:29 PM Subject: [lizmap-web -client] "localization layer" unstable Version 2.11.0 (# 139)
 
 
 
   
Hello, 
I just made ​​the shift to the latest version of lizmap: 2.11.0 
The latter is even better (thank you for your great work), but I have a problem with localization tool. It works very well with some layers, but with other nothing happens. This is particularly the case for the two layers that I use the most for the location: the land registry and addresses. Does having lot of objects (several thousand) can be a problem? 
Namely that with these same layers location worked well in lizmap 2.10.0 ....My setup: 
Lizmap 2.11.0 
Qgis server 2.8.1- 
Reply to this email Directly or view it on GitHub .

**Comment by rldhont** [comment]
Bonjour,

La requête est trop longue ou trop grosse par rapport aux configurations serveurs. Pour remédier à cela, il faudrait ne pas charger l'intégralité des données vectorielles dans le Client. La fonction de localisation n'a pas été conçu pour manipuler autant d'objet. Elle a été conçu pour faciliter la navigation dans la carte en créant des raccourcis simples :
* zoom sur une commune
* zoom sur un quartier
Il faudrait donc améliorer Lizmap en ajoutant une nouvelle fonctionnalité ou en faisant évoluer la fonction de localisation par couche.

**Comment by antoine373** [comment]
Bonjour,
J'entends bien le problème posé par le nombre d'objets contenus dans la couche et de la lourdeur de la requête.
Après ce qui semble étonnant, c'est qu'avec la version 2.10.0 de lizmap je n'avais aucun problème pour faire fonctionner la fonction de localisation, et ce même avec une couche cadastre de 20 000 objets ou bien avec un référentiel adresse utilisant une liste hiérarchique (sélection d'une rue puis d'un numéro dans la rue).
Le test que j'ai réalisé (entre 6289 et 6290 objets) fait penser à une limitation voulue.

**Comment by rldhont** [comment]
Bonjour,

Il n'y a pas de limitation voulue du côté de Lizmap. SI il y a une limitation, celle-ci est involontaire.

Utilisez-vous la même version de QGIS-Server ?

**Comment by antoine373** [comment]
Oui j'utilise bien la même version de QGIS (la 2.8).
Par contre en regardant du côté de la lourdeur de la requête, j'ai décidé d'alléger la géométrie de la couche concernée. En utilisant la fonction "ST_simplify(geom)" dans ma base postgis ça me permet de faire fonctionner la localisation comme précédemment.

C'est un moyen de contourner le problème, mais ça n'explique pas la différence de comportement entre la version 2.10 et la 2.11...

**Comment by veroniqueC** [comment]
Dans ce cas, y'a t-il moyen de détourner le problème? Comment permettre a l'utilisateur de zoomer sur une parcelle cadastrale même via une requête SQL?

PS: dslée pour mon dernier post, je n'avais pas vu cette discussion

**Comment by rldhont** [comment]
Bonjour, La futur version 2.12 et 3 de Lizmap Web Client devrait corriger ce problème grâce à la modification 9d04d8f27985f8ac42714c9627d2d3a77705a082

**Comment by antoine373** [comment]
Autre moyen de contourner le problème : utiliser une couche de points plutôt que des polygones (plus lourd). Pour le cadastre, générer une couche de centroid des parcelles par exemple.
De plus dans QGIS le parametre "précision de la géométrie" (dans propreites du projet et serveur oWS) semble jouer

**Comment by geoek** [comment]
Bonjour,
Je rencontre moi aussi ce problème de limitation.
Je suis sur QgisServer 2.8 (Ubuntu server) et Lizmap 2.12 et 3 (meme comportement).
L'outil LocateByLayer ne fonctionne pas (pas de chargement de la liste) et il est impossible d'afficher la table attributaire pour des couches ayant plus de 300 lignes environ.

C'est particulièrement génant pour les tables attributaires. J'ai essayé avec différentes géométries (centroid des polygones pour alléger les requetes) mais avec toujours le même résultat.

Cela peut il venir d'une configuration hardware trop limitante, ou d'une mauvaise configuration de Qgis Server ? et dans ce cas, existe t il une requette qui permettrait d'être sûr que le problème vient bien de Qgis server.

Merci d'avance pour vos réponses. (Je vais essayer de passer sur une version plus récente de Qgis server pour voir si les performances s'améliorent).

**Comment by rldhont** [comment]
Quelle méthode d'envois de requête à QGIS Server est configuée ? curl ou php ?

**Comment by geoek** [comment]
J'utilise curl. Je vais tester dès que possible avec php pour voir ce que ca donne.

**Comment by rldhont** [comment]
C'est probablement le même problème que là #231

**Comment by geoek** [comment]
C'est bon, j'ai pu réaliser des tests !
Alors le problème venait de ma couche qui avait une entité avec une géométry nulle. Et cela bloque l'affichage de la table attributaire ou la liste de localisation. => bug ?

Sinon, concernant les limitations, sur une couche de parcelles cadastrale, la table fonctionne jusqu'à environ 55000 lignes.
Si je travaille avec les centroides des polygones pour alléger la géométrie, la limite passe à 75000 lignes.
Dans les deux cas, il faut environ 20 secondes pour afficher la table. A ce propos, il serait intéressant d'avoir une barre de progression du chargement (ou un message d'erreur dans le cas du chargement impossible de la table (trop d'entités ou erreur dans les données)).

Concernant la méthode d'envoi de requète à Qgis Server, j'ai testé les deux solutions et j'obtiens les mêmes performances.

**Comment by rldhont** [comment]
A new feature in 3.1, will give you the ability to filter the table by map 5e736a01c2cbf739c737b8e8c1d54c41d23d4f0f

**Comment by nboisteault** [comment]
Il semble que la limitation puisse venir de la configuration du serveur web. En diminuant le volume de donnée vous arrivez à obtenir plus d'objets.
Concernant la création d'une barre de progression, vous pouvez ouvrir un autre ticket.
