### ISSUE TITLE
How to refresh the attribute table after adding a field?

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1391]
I added a field on several PostgreSQL layers and when I display the attribute table in Lizmap this field does not appear for all layers. How can I refresh the table?

I would like to point out that I did not hide the field in the plugin and that the field appears well for popups.

**Environment**

Lizmap version: 3.3.2
QGIS Server version: 3.4
QGIS Project version: 3.4.13
OS (Windows, Linux, MacOS, Android…): MacOS
Browser (Firefox, Chrome…): Safari,Firefox

**Comment by tethysgeco** [comment]
Have you tried opening the Qgis project, opening the Lizmap plugin, applying it (even without any changes) and saving the refreshed files on your server?

**Comment by igeofr** [comment]
Yes, but the field added on several layers only appears for some of them.

**Comment by Gustry** [comment]
I guess your fields should be in the QGS file, no?
Did you use "change datasource plugin" ?

**Comment by igeofr** [comment]
1. Yes, the fields appeared well in the QGS.
2. No I didn't use the plugin, I just added columns in PG.

I just checked the project on which I had the problem and the columns all appear. It's possible that an update has fixed the bug I encountered.
