### ISSUE TITLE
Album slideshow in Popup

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#1403]
This question is not directly related to the actual features of lizmap, although it can be a feature in the future, maybe as a javascript addon.

At popups I'm using media links, and works fine. Now I would like to link whole galleries (hosted eg. in google photos) and display in dock when clicked as a slideshow or carousel. Well I don't have a solution, every css or javascript slideshow which I've tested need direct links to each photo. I would like something like [here](https://www.publicalbum.org/blog/embedding-google-photos-albums), but the image link generation should be done directly on my site, so I can put my album link for each point into the script.

Do any of you had this need, and how did you solve it?

**Comment by aeduard** [comment]
A friend of mine have helped to solve this issue. I will post the solution/codes here, someone may need it. It is also welcome to have any observations regarding the solution.

It uses links from shared google photos albums. The size of the parsed photos can also be changed. For compatibility issues (javascript version of lizmap) it uses fotorama album, but other albums can also be used.

First step: the following php file should be created: api_google_photos_to_json.php Than the file was copied in the main root www folder where lizmap is installed, basically it is near the index.php
The php has the following content:
`<?php

function parse_photos($contents)
{
    $m = NULL;
    preg_match_all('~\"(http[^"]+)"\,[0-9^,]+\,[0-9^,]+~i', $contents, $m);

    $photos = array_unique($m[1]);
    $photos = array_filter($photos, function($url){
        return (!preg_match('/(widget\/app|en\/about)/', $url)) ? true : false;
    });

    return $photos;
}

$URL = $_REQUEST['url_google'];

if (empty($URL)) die("Invalid");

$ch = curl_init();
curl_setopt($ch,CURLOPT_URL, $URL);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER ,false);
curl_setopt($ch,CURLOPT_FOLLOWLOCATION  ,true);
curl_setopt($ch,CURLOPT_HEADER   ,false);
curl_setopt($ch,CURLOPT_USERAGENT    ,"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36");

$content = curl_exec($ch);

curl_close($ch);


header('Content-Type: application/json');
echo json_encode(parse_photos($content));`

Second step: In lizmap pop-up, the following lines should be added in the head seaction:
` <link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>`

Third step: in lizmap pop-up body sections the following lines:
`<div id="google_photo_album_viewer" data-allowfullscreen="true"></div>
<script type="text/javascript">
   var ALBUM_URL = '{**_$postgresql column with google photo album link_**}';
    var url = '_**the full url here**_/api_google_photos_to_json.php?url_google='+ALBUM_URL;
    $.get(url, function(response){
        var _html = "";
        $.each(response, function(idx, item){
            _html += '<a href="'+item+'=w1920" ><img src="'+item+'" alt="" title=""/></a>';
        });

        $('#google_photo_album_viewer').html(_html);
		$('#google_photo_album_viewer').fotorama();
    }, "json");
</script>
   </div>`

**Comment by Gustry** [comment]
Thanks for reporting your solution. 
I'm closing as this not a question anymore.

**Comment by pcav** [comment]
I think this is worth adding to documentation, as an `Advanced` section, as it can be useful to many.
