### ISSUE TITLE
Can't edit Spatialite layer

### ISSUE THREAD

**Issue by Warkorentin** [3liz/lizmap-web-client#1404]
Hello, 
I followed the documentation in order to create an editable SpatiaLite layer. I did everything from adding an auto-increment column, editing the layer properties and enabling the layer in the projet properties tab, to adding the layer in the lizmap configuration plugin. 
At this point, the layer is showing up on the web client but not the editing tab. I have no clue as to what I should do next. I would like to avoid using postGis if possible.

I'm using qgis v.2.18, lizmap web client in a docker (v.3.1.11) and qgis server v.2.18ltr
Do you have any idea on what I could be doing wrong ?
Thanks in advance

**Comment by capu81** [comment]
I've the same problem!

**Comment by pcav** [comment]
In my understanding the issue is still valid, and SL layer cannot be edited.
