### ISSUE TITLE
repository does not appear

### ISSUE THREAD

**Issue by texasred08** [3liz/lizmap-web-client#1405]
I have succesfully installed lizmap on Windows 10 and inserted a QGIS project to a local path called "webserver project". However, it is not appearing on the project page. It see Here is the error log:

2019-11-26 19:56:11	::1	error	2019-11-26 19:56:11	::1	[0]	The QGIS project C:\webserver\lizmap\lizmap\install\new/webserver.qgs does not exist!	C:\webserver\lizmap\lizmap\modules\lizmap\classes\lizmapProject.class.php	148
	/index.php/view/
array (   'module' => 'view',   'action' => 'default:index', )

	0	lizmapProject->__construct()	C:\webserver\lizmap\lizmap\modules\lizmap\classes\lizmap.class.php : 298
	1	lizmap::getProject()	C:\webserver\lizmap\lizmap\modules\lizmap\classes\lizmapRepository.class.php : 150
	2	lizmapRepository->getProjects()	C:\webserver\lizmap\lizmap\modules\view\zones\main_view.zone.php : 47
	3	main_viewZone->_prepareTpl()	C:\webserver\lizmap\lib\jelix\utils\jZone.class.php : 239
	4	jZone->_createContent()	C:\webserver\lizmap\lib\jelix\utils\jZone.class.php : 206
	5	jZone->getContent()	C:\webserver\lizmap\lib\jelix\utils\jZone.class.php : 294
	6	jZone::_callZone()	C:\webserver\lizmap\lib\jelix\utils\jZone.class.php : 95
	7	jZone::get()	C:\webserver\lizmap\lib\jelix\tpl\jTpl.class.php : 125
	8	jTpl->assignZone()	C:\webserver\lizmap\lizmap\modules\view\controllers\default.classic.php : 101
	9	defaultCtrl->index()	C:\webserver\lizmap\lib\jelix\core\jCoordinator.class.php : 225
	10	jCoordinator->process()	C:\webserver\lizmap\lizmap\www\index.php : 23

**Comment by pcav** [comment]
IMHO this is a broken installation, nothing to do with Lizmap. Please reinstall everything from scratch and test again.
Thanks.

**Comment by nboisteault** [comment]
@texasred08 did you solve issue ?
