### ISSUE TITLE
Possibility of changing the theme

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#1406]
I think the default theme of Lizmap is very good but sometimes you would like to adjust your own colors and things here and there. Now this is partially present. The best thing would be that you could change the entire theme. Now there is only a default theme in \www\themes\

It would be great if you could add your own theme and choose the theme that you want to use in the configuration.

**Comment by mdouchin** [comment]
You can modify the colors of the interface in the admin Panel, in Lizmap submenu / Theme. We should improve documentation to help user discover and use this feature

**Comment by nboisteault** [comment]
@NvBgm Lizmap is based on Jelix. You can [create your own theme](https://docs.jelix.org/en/manual/application/themes).

**Comment by NvBgm** [comment]
@nboisteault  Thanks for the link we going to try make a theme.

**Comment by laurentj** [comment]
@NvBgm the version of Jelix used by Lizmap is 1.6, and this documentation is for 1.7. You should [read this](https://docs.jelix.org/en/manual-1.6/themes) instead.

**Comment by NvBgm** [comment]
@laurentj Oke thanks ..
