### ISSUE TITLE
Issue with vagrant

### ISSUE THREAD

**Issue by gmolinu** [3liz/lizmap-web-client#1407]
Hi, I followed the steps shown here without changing any options: https://github.com/3liz/lizmap-web-client/tree/master/vagrant

The result is that going to http: // localhost: 8130 / the result is this:

![Annotation 2019-11-27 124059](https://user-images.githubusercontent.com/12598401/69720555-30437700-1113-11ea-8f86-5a662e8b83bb.jpg)

something wrong?

**Comment by gmolinu** [comment]
I found this error:

ASK [qgis : Add QGIS repository] **********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: W:GPG error: http://qgis.org/debian-ltr-2.18 stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51F523511C7028C3, E:The repository 'http://qgis.org/debian-ltr-2.18 stretch InRelease' is not signed.
fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_QbVVhi/ansible_module_apt_repository.py\", line 538, in <module>\n    main()\n  File \"/tmp/ansible_QbVVhi/ansible_module_apt_repository.py\", line 527, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 464, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:GPG error: http://qgis.org/debian-ltr-2.18 stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51F523511C7028C3, E:The repository 'http://qgis.org/debian-ltr-2.18 stretch InRelease' is not signed.\n", "module_stdout": "", "msg": "MODULE FAILURE"}

**Comment by laurentj** [comment]
This is a bug in the ansible scripts. We should update so they install the key correctly.

**Comment by laurentj** [comment]
And in the lizmap_3_3 and master branch, we should install Qgis 3.4

**Comment by laurentj** [comment]
It is fixed.
