### ISSUE TITLE
Error with Lizmap on windows 10

### ISSUE THREAD

**Issue by gmolinu** [3liz/lizmap-web-client#1408]
Hello,
I tried installing lizmap on windows 10 following this guide https://docs.lizmap.com/current/it/install/windows.html#apache-2-x-x-server-configuration

With this configuration:

- php 7.3.12
- lizmap-web-client-master
- QGis 3.4.13-2
- QGis server 3.4.13-2

Gives me this error with the Montpellier project:
2019-11-27 14:44:33 :: 1 error Spatialite is not available
2019-11-27 14:44:33 :: 1 error 2019-11-27 14:44:33 :: 1 [901] error key C: server server lizmap product master lizmap install ggis / montpellier .qgs, use only alphanumeric characters and the character '_ and maximum length 255 C: server server lizmap product master lib julia utils jCache.class.php 444
/index.php/view/
array ('module' => 'view', 'action' => 'default: index',)_

I also attach the configuration files:
[httpd.txt](https://github.com/3liz/lizmap-web-client/files/3897133/httpd.txt)
[httpd-vhosts.txt](https://github.com/3liz/lizmap-web-client/files/3897138/httpd-vhosts.txt)
[php-7.3.12.txt](https://github.com/3liz/lizmap-web-client/files/3897139/php-7.3.12.txt)

**Comment by ygorigor** [comment]
@gmolinu try in this way http://qgisusers.co/es/blog/instalacion-de-lizmap-y-qgis-server-en-windows-10/

**Comment by gioman** [comment]
> @gmolinu try in this way http://qgisusers.co/es/blog/instalacion-de-lizmap-y-qgis-server-en-windows-10/

@gmolinu or this way: https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by gmolinu** [comment]
thank you @ygorigor ! it works

**Comment by rldhont** [comment]
@ygorigor @gioman @gmolinu Does the documentation need to be updated?

Does the PR https://github.com/3liz/lizmap-documentation/pull/115 not enough?

**Comment by gioman** [comment]
@rldhont 

> Does the documentation need to be updated?
> 
> Does the PR [3liz/lizmap-documentation#115](https://github.com/3liz/lizmap-documentation/pull/115) not enough?

I have not checked the link posted by @ygorigor but regarding the link I posted it is based on @jonnyforestGIS PR, what I just did in that repo is to provide ready to use PHP and Apache binaries and config files.

**Comment by jonnyforestGIS** [comment]
@rldhont the link of @ygorigor point to lizmap documentation as well. Correct me if I'm wrong but the only thing that is different is a ready to use installation similiar to the @gioman approach 


Cheers

**Comment by jonnyforestGIS** [comment]
This can be close? There isn't more feedback. I tested and work for me. @rldhont ?

**Comment by nboisteault** [comment]
@jonnyforestGIS thanks for feedback.
