### ISSUE TITLE
Editing of PostGIS layers - coordinates ever in EPSG 4326

### ISSUE THREAD

**Issue by paolomartinis** [3liz/lizmap-web-client#1409]
### What is the bug?
While editing of PostGIS layers the coordinates of new points are ever expressed in EPSG 4326 instead of the native layers projection or the selected one
When adding a new point Lizmap stores the geometric field in 4326 instead of the native layers projection or the selected one
(see screenshot below)

### Expected behavior
Default coordinates values and storage same as default EPSG of the layer or of the project 
Selecting different EPSGs from dropdown changes coordinates values but the storage of geometry field has to be in the projection defined in the QGIS project

### Screenshots and logs
![image](https://user-images.githubusercontent.com/40235048/69912485-61c98480-142a-11ea-8797-606cb9a5a590.png)

### Environment

 - Lizmap version: 3.3.2
 - QGIS Server version: 3.4.13
 - QGIS Project version: 3.4.13
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 18.04.3
 - Browser (Firefox, Chrome…): Chrome

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
