### ISSUE TITLE
Install curl 

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1412]
### Is your feature request related to a problem? Please describe
LWC allows to use PHP or Curl to send request to QGIS Server.

### Describe the solution you'd like
Curl should be installed in Vagrant machine.

**Comment by nboisteault** [comment]
@laurentj is PHP-curl enough ? Don't we need curl too ?

**Comment by laurentj** [comment]
@nboisteault no. From what I know, lizmap is only using the curl API of the php extension.
