### ISSUE TITLE
Plotly updates

### ISSUE THREAD

**Issue by ghtmtt** [3liz/lizmap-web-client#1413]
### What is the bug?
Some plotly facilities are not available "live" like x any y axis renaming, plot title and the custom plotly toolbar buttons.

Also tried to replace the current `https://github.com/3liz/lizmap-web-client/tree/master/lizmap/www/js/dataviz` with the latest plotly dev version (`https://cdn.plot.ly/plotly-latest.min.js`)
 but nothing changed.

### Expected behavior
It is not possible to change the axis name and other small but important stuff.

Might be related to the ploly.js version (very old in lizmap). 

### Screenshots and logs

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2884884/69972594-2dd18a80-1522-11ea-9c13-206b70dba36f.gif)

### Environment

 - Lizmap version: 3.3.2
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4
 - OS (Windows, Linux, MacOS, Android…): all
 - Browser (Firefox, Chrome…): all

**Comment by nboisteault** [comment]
Plotly.js has v1.52.1 version in Lizmap. The last version is v1.52.2. So the issue is not related to version.

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
