### ISSUE TITLE
Upgrade causes `jauth.db` missing `Display projects WMS links` and other options

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1416]
Until 3.3.0 the admin could choose to display the URL of the WMS service.
In 3.3.3 this option has disappeared.
See attached screenshots.
![image](https://user-images.githubusercontent.com/691842/70141291-0a7c1c00-1697-11ea-8e1d-63f6b49bb676.png)
![image](https://user-images.githubusercontent.com/691842/70141348-27185400-1697-11ea-948f-2e801474393d.png)

**Comment by pcav** [comment]
You can check WMS links are not present e.g. in https://lizmap.faunalia.eu (they were before the update to 3.3.3)
Thanks for checking

**Comment by Gustry** [comment]
I can't reproduce too on 3.3.4-pre

**Comment by pcav** [comment]
Thanks @Gustry for checking. Have you also a 3.3.3 installation to check? Have you seen my example? Could this be a side effect of the upgrade rather than a fresh install?

**Comment by pcav** [comment]
Tried a fresh install of 3.3.3, the option is there. Then upgrading, still there. So it's a local issue, probably due to some upgrade issue (I noticed it in an installation that has undergone many upgrades, since version 2). I can close this. I would appreciate a suggestion on how to clean it up, as this is a production instance and I cannot just drop all users and groups.
Thanks.

**Comment by pcav** [comment]
The other strange thing is that group rights are not displayed correctly, see attached
![Schermata del 2019-12-17 11-58-52](https://user-images.githubusercontent.com/691842/70989823-985afc80-20c4-11ea-9651-7407cf8a9b66.png)

**Comment by pcav** [comment]
Further investigation: row `lizmap.tools.displayGetCapabilitiesLinks` is missing from old `jauth.db`

**Comment by pcav** [comment]
Adding the record back makes the option available.
Remaining issues:
* the option is not available to admin, it has to be added by hand in the Rights of groups page
* the order in that page is wrong (Display projects WMS links is the first row)
* some rights are displayed with the wrong name (acl.grp.group.management and acl.grp.user.management)

**Comment by pcav** [comment]
Any hint on how I can clean up the second and third point? I tried running again 
`php lizmap/install/installer.php`
and
`php lizmap/install/upgrade-to-3.php`
to no avail.
Thanks.

**Comment by rldhont** [comment]
@pcav I don't think that jelix as a command line to check and upgarde jauth-db.

**Comment by pcav** [comment]
/s/as/has?

**Comment by pcav** [comment]
/s/jauth-db/jauth.db?

**Comment by pcav** [comment]
More info: in correct db,
`acl.group.create	jelix~acl2db.acl.group.create	acl.grp.group.management`
is replaced by
`acl.group.create	jacl2db~acl2db.acl.group.create	acl.grp.group.management`
this fixes the names of rights (e.g. Create a group) but not those of headings (e.g. `acl.grp.group.management`)

**Comment by pcav** [comment]
Same for `jacl2db~acl2db.acl.grp.group.management` and `jacl2db~acl2db.acl.grp.user.management`

**Comment by pcav** [comment]
Issue solved for me, I leave it open for reference (I believe other can have the same issue during upgrades), feel free to close it @rldhont
