### ISSUE TITLE
Export rights

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1418]
Hello,

Is it possible to modify the export rights for each layer ? I would activate  export features only for a table  and not for all the tables :

![image](https://user-images.githubusercontent.com/19794922/70240840-3f0ed700-176e-11ea-887f-c48f5e40267c.png)

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/499

**Comment by Cww7** [comment]
Does it means that it is not possible actually ?

**Comment by gioman** [comment]
> Does it means that it is not possible actually ?

it means that it has already been requested as a feature, if the feature request is not closed it means that it has not been implemented yet and so this ticket it a duplicate.

**Comment by Cww7** [comment]
Thank you for your clarification @gioman

**Comment by laurentj** [comment]
duplicate of #499
