### ISSUE TITLE
Update proj4php and install it with composer

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1422]

**Comment by laurentj** [comment]
depends of #1056

**Comment by laurentj** [comment]
@nboisteault please, do a pull request on the upstream project, against their proj4php5.2 branch, with fixes you made in commit 6ae3098bc046e70ce0c6ca8d0b8a7bb3b10e030f

As we still support php 5.6 for Lizmap 3.4, we should install the proj4php5.2 branch.

**Comment by nboisteault** [comment]
@laurentj https://github.com/proj4php/proj4php/pull/95

**Comment by julien2512** [comment]
merged

**Comment by laurentj** [comment]
Thank you @nboisteault and @julien2512 .

There is still a difference with our version : our version has a defs EPSG3857 that is not into the proj4php5.2 branch. @rldhont  added probably it when it added sources into lizmap for the first time. I will propose a patch.

**Comment by laurentj** [comment]
proj4php/proj4php#97
