### ISSUE TITLE
Form filter with date, got some Nan with Firefox

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1424]
### What is the bug?

I have some NAN values in my Lizmap when I'm trying to use form filtering with a date field

![Capture d’écran de 2019-12-11 22-54-19](https://user-images.githubusercontent.com/1609292/70663725-3a17bf00-1c69-11ea-843e-8c4e0ae2d46f.png)

### Steps to reproduce the issue

1. Create a table with 

```sql
CREATE TABLE gestion_obs.observation (
	id SERIAL PRIMARY KEY,
	espece_id INTEGER NOT NULL,
	observateur_id INTEGER REFERENCES gestion_obs.observateur NOT NULL,
	date_observation TIMESTAMPTZ NOT NULL,
	genre VARCHAR(10),
	photo TEXT,
	geom geometry(Point,2154) NOT NULL
);
```

Populate some data in it using QGIS. The calendar is working well.

![Capture d’écran de 2019-12-11 22-58-31](https://user-images.githubusercontent.com/1609292/70664651-1e151d00-1c6b-11ea-9717-c83dcc520e77.png)

In Lizmap plugin, do a filter with 

![Capture d’écran de 2019-12-11 22-59-10](https://user-images.githubusercontent.com/1609292/70664740-469d1700-1c6b-11ea-81f2-6106c80c5568.png)

Then in Lizmap, I have the result above. I can't choose a value in the LWC calendars. SLiders is not moving.

I can see the request is good from LWC :
```json
[{"min":"2000-01-01 00:00:00+01","max":"2019-12-12 00:00:00+01"}]
```

THis is in Firefox. It's working in Chromium.

### Expected behavior

It should work with Firefox, not only with Chromium.

### Environment

 - Lizmap version: Branch 3.3
 - QGIS Server version: 3.4.13
 - QGIS Project version: 3.4.13
 - OS (Windows, Linux, MacOS, Android…): Ubuntu
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgresql

**Comment by nboisteault** [comment]
Confirmed.

**Comment by nboisteault** [comment]
Firefox wants minutes in offset : 
```javascript
new Date('2019-12-30 00:00:00+01')
Invalid Date

new Date('2019-12-30 00:00:00+01:00')
Date Mon Dec 30 2019 00:00:00 GMT+0100 (heure normale d’Europe centrale)
```
