### ISSUE TITLE
Toggle of group change expanding state of its layers in treeview

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1425]
### What is the bug?
Lizmap does not keep expanding state for layers when group expanding state is toggled.

### Steps to reproduce the issue

QGIS (ok) :
1. 
![image](https://user-images.githubusercontent.com/2145040/70744885-f84b4f00-1d22-11ea-9d70-8e8608263d16.png)
2.
![image](https://user-images.githubusercontent.com/2145040/70744923-0bf6b580-1d23-11ea-9c95-c6eba1b82fc4.png)
3.
![image](https://user-images.githubusercontent.com/2145040/70744944-17e27780-1d23-11ea-938b-2a22727e3319.png)

Lizmap (nok) : 

1.
![image](https://user-images.githubusercontent.com/2145040/70745191-95a68300-1d23-11ea-98d0-a66fa42259ae.png)
2.
![image](https://user-images.githubusercontent.com/2145040/70745223-a1924500-1d23-11ea-988e-e023d190be13.png)
3.
![image](https://user-images.githubusercontent.com/2145040/70745246-afe06100-1d23-11ea-96e3-281cef254e9f.png)

### Environment

 - Lizmap version: master
 - QGIS Server version: 3.4.13

**Comment by Gustry** [comment]
There are quite a few updates on the layer tree view in LWC 3.7, thanks to you, see #3656
