### ISSUE TITLE
No image in IE11

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1429]
### What is the bug?

It seems that no images are loaded on IE 11.864.
AFAIK, Lizmap is compatible with this version, right?

https://demo.lizmap.com/lizmap/ No thumbnails on the home page were loaded and no pictures too when we clicked on a project.

### Expected behavior

Side note, should we keep a table, in the documentation, with which software lizmap is compatible?
(Which chrome, which firefox, which QGIS Server etc for each Lizmap WC versions?)

### Environment

* URL : demo.lizmap.com so lizmap 3.3 I think
* Internet browser : IE 11.864

**Comment by laurentj** [comment]
I don't think we target IE 11. If we target it, we should forget it. This is a very old browser. [Even Microsoft says to stop to use it](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732)

**Comment by Gustry** [comment]
Ok. I got no idea, it has been a long time I didn't follow Microsoft and web development.

I did a research before writing this issue and I found https://github.com/3liz/lizmap-web-client/issues/1348#issuecomment-549440853 @mdouchin was saying to keep it compatible for IE 11.

I still think the table would be good to have somewhere in the documentation.

Feel free to close if it's not worth it to fix.

**Comment by Gustry** [comment]
It seems we decided to not support IE11 according to a discussion in the team. I will make a table to keep track of these decisions.
