### ISSUE TITLE
Problème d'affichage du style des lignes et des contours de polygone

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#143]
Bonjour à tous,
avec QGIS 2.6 et Lizmap 2.10, les contours des polygones ainsi que les lignes sont tout le temps affiché avec un trait noir. Changer la couleur, le style de trait ou l'épaisseur ne fonctionne pas...

Est ce un bug  connu ou un problème de configuration ?

Merci !

**Comment by rldhont** [comment]
Bonjour,

Avez-vous vérifié la version de QGIS-Server ?
Avez-vous supprimé le cache après modification du style ?

**Comment by geoek** [comment]
Pour le cache, oui, j'ai bien supprimé le cache. A noter que cela se produit avec tous mes projets...

Concernant QGis-server, c'est la version présente dans les dépots officiels d'Ubuntu server (v14.10). (Je n'arrive pas à trouver la commande pour connaitre la version...)

**Comment by geoek** [comment]
J'ai mis à jour lizmap (2.11.0) et j'ai toujours le même comportement...

**Comment by rldhont** [comment]
Le problème ne provient pas de Lizmap mais du différentiel de version entre QGIS-Server et QGIS-Desktop.

**Comment by geoek** [comment]
Ok ! merci pour cette information ! Je vais voir pour mettre à jour mon serveur où utiliser une ancienne version de Qgis pour exporter mes projets.
