### ISSUE TITLE
Remove support of minify

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1439]
Although there is some minify parameters configured into the mainconfig.ini.php, minify is disabled by default.

I propose to remove the support of Minify, as 

- it is no used
- to provide compact JS or CSS files, it is better nowadays to use build processor like webpack

@rldhont @mdouchin : ok to remove it?

**Comment by nboisteault** [comment]
@laurentj We disabled JS minification years ago because it was breaking one of my project. I agree to remove support.
