### ISSUE TITLE
Amélioration de la vitesse d'affichage des couches

### ISSUE THREAD

**Issue by kali06** [3liz/lizmap-web-client#144]
Bonjour,

j'utilise lizmap web-client 2.10.2 + qgis server 2.6 + OS linux debian

je souhaiterais savoir comment améliorer la vitesse d'affichage de mes couches sachant que toutes mes couches sont non tuilées + durée cache client au max + serveur 8 Go RAM + Intel xeon

Cependant, je trouve que les applications prennent du temps à se charger, de même que quand je zoome, les couches prennent du temps à se recharger,

je ne tuile pas mes couches car le temps de chargement est vraiment trop long

je souhaiterais savoir si il y a moyen de configurer le serveur de façon optimale pour améliorer le temps de chargement des couches,

je pense principalement aux paramètrages du mpm-worker et du mod_fcgid, 

actuellement, ces deux fichiers ont une configuration standart comme indiqué sur votre site
http://docs.3liz.com/fr/admin_guide/installation/server_configuration.html#configuration-du-mpm-worker

Est-ce qu'il est possible de modifier ces configurations afin d'améliorer la vitesse de chargement des cartes,

en vous remerciant par avance,

Cordialement,

**Comment by rldhont** [comment]
Bonjour,

La version 2.11 de Lizmap-Web-Client apporte certaines amélioration dans la vitesse d'affichage de la carte. Sinon je vous invite à poser votre question sur ForumSIG http://www.forumsig.org/forumdisplay.php/54-Assistance-et-Programmation, vous y trouverez plus de personne susceptible de répondre à ce genre de question.

**Comment by kali06** [comment]
Bien reçu,

Merci beaucoup,

j'irais voir,

mais si vous avez des billes,

je suis preneur ;)

**Comment by nboisteault** [comment]
Pour plus d'info voir la partie sur l'optimisation de la [doc](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#optimizing-lizmap).
