### ISSUE TITLE
Edition - Layer order

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1442]
### What is the bug?
In editing, the layer order is not respected between the plugin and Lizmap

### Screenshots and logs
<img width="130" alt="Capture d’écran 2019-12-15 à 19 16 30" src="https://user-images.githubusercontent.com/7761073/71250966-51b60e00-2321-11ea-8db7-4513b982a4a2.png"> - <img width="108" alt="Capture d’écran 2019-12-15 à 19 23 12" src="https://user-images.githubusercontent.com/7761073/71250965-51b60e00-2321-11ea-93c4-d2944843d43d.png">
### Environment

 - Lizmap version: 3.3.3
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4.14
 - OS (Windows, Linux, MacOS, Android…): MacOS
 - Browser (Firefox, Chrome…): Safari

**Comment by nboisteault** [comment]
It will be fixed in next 3.2 release thanks to https://github.com/3liz/lizmap-web-client/commit/8e585f3a507474b5e4dcda197c5e947b75248907
Same issue described here https://github.com/3liz/lizmap-web-client/issues/491#issuecomment-534106153
Thanks for reporting.
