### ISSUE TITLE
Added new layers on QGIS project, Lizmap Web Client  doesn't show them unless I add as a new project

### ISSUE THREAD

**Issue by carekapt** [3liz/lizmap-web-client#1445]
Hi there.

First time here, I'm trying to understand what cache should I remove to get the latest update on my QGIS project.

I'm using Qgis Desktop 3.4, I started with 2 groups of 3 layers each, and then added a 3rd group with 3 layers also, saved the project, restarted all services (Nginx + php7.2-fpm) and the new group does not appear.

I then copied the project to a different folder (called it v2) and added the project to Lizmap, where everything appears OK.

On the first project, I deleted all files from the following locations:

/tmp/<projectID>
/srv/lizmap-web-client/temp/lizmap/www/cache/myapp
/srv/lizmap-web-client/temp/lizmap/www/cache/qgisprojects/jelix_cache

Using a docker container running a customized Ubuntu Bionic + qgis-server 3.4 + nginx +  Lizmap 3,3,3 (after a few hours debugging the email issue for registering new users, it's working)

Any hints would be appreciated,
Kind regards,
NMS

**Comment by gioman** [comment]
> I'm using Qgis Desktop 3.4, I started with 2 groups of 3 layers each, and then added a 3rd group with 3 layers also, saved the project, restarted all services (Nginx + php7.2-fpm) and the new group does not appear.

@carekapt maybe you just forgot to update the lizmap configuration file?

**Comment by carekapt** [comment]
> > I'm using Qgis Desktop 3.4, I started with 2 groups of 3 layers each, and then added a 3rd group with 3 layers also, saved the project, restarted all services (Nginx + php7.2-fpm) and the new group does not appear.
> 
> @carekapt maybe you just forgot to update the lizmap configuration file?

Thanks for the reply!
**What file is that?** Besides the docker container running, I have a virtual machine with the same specs as the container, and when I added the same project, it showed the last group that I created with the 3 additional layers without a problem.

I'm trying to debug issues with the new lizmap version, trying to add database layers, GeoServer layers, external layers etc...one at the time, so I can detect bottlenecks or misconfigurations and it slows down things when I have to delete the project from lizmap and add it again with a different name.

**Comment by gioman** [comment]
> What file is that?

the one you must generate with the Lizmap QGIS plugin, and that you need to re-generate/update each time you do some type of changes in your QGIS project (i.e. adding layers/groups).

**Comment by carekapt** [comment]
Are you talking about this file?
/srv/lizmap-web-client/temp/lizmap/www/cache/qgisprojects/jelix_cache/project.qgs.cache

When I open this file, it has the layers that I added on QGIS Desktop, I repeated the whole process of Lizmap plugin, and I still have the missing layers using Lizmap Web Client like if it were some cache in the middle. :(

**Comment by gioman** [comment]
> Are you talking about this file?
> /srv/lizmap-web-client/temp/lizmap/www/cache/qgisprojects/jelix_cache/project.qgs.cache

no, I'm speaking about the .cfg file that the Lizmap plugin generates and that you have to upload to the server/container/vm along with the qgis project file.

**Comment by carekapt** [comment]
Actually, I have the files located on a DFS server and I've mounted this shared folder on the container...so the files are always accessible to the Lizmap (project.qgs + project.qgs.cfg) ...i'm conducting tests and when I'm using apache instead of Nginx, a service apache2 restart is sufficient to refresh the cache plus a CTRL+F5 on the browser...i'm feeling lost. :/

**Comment by gioman** [comment]
@carekapt feel free to contact me if you want to speak about it in Portuguese.

**Comment by carekapt** [comment]
> @carekapt feel free to contact me if you want to speak about it in Portuguese.

I'm feeling kinda dumb, I can't find the private message button :P

**Comment by gioman** [comment]
> I'm feeling kinda dumb, I can't find the private message button :P

@carecapt there is no private messages in GH, I think. Have a look at my profile for my contact.

**Comment by carekapt** [comment]
Hi there.
After further analysis, I think this only happens when running Lizmap on a docker container with Nginx...I have a virtual server with Ubuntu Bionic + Apache + Lizmap 3.3.3 and the trick is to restart the apache2 service to see the updated project...on the container, I restart Nginx and php7.2-fpm services and nothing happens

**Comment by rldhont** [comment]
@carkapt, if you use QGIS Server in a docker image you need this QGIS Serrver plugin https://github.com/3liz/qgis-logging-plugin to flush the QGIS Server project cache each time a project has changed.

**Comment by carekapt** [comment]
> @carkapt, if you use QGIS Server in a docker image you need this QGIS Serrver plugin https://github.com/3liz/qgis-logging-plugin to flush the QGIS Server project cache each time a project has changed.

Thank you very much for the tip, but only now i picked up this subject again...and i'm having a bit of dificulty understanding how this plugin works, all the documentation is apache oriented and i'm using nginx to publish lizmap web interface.

I'm trying to figure what triggers the cache flush, is it the timer on flush interval? Like i said, i was running inside a container and the only way that I can to refresh the project layers is killing the container and restart it again...among other stuff like 

1) Cleaning the cache folders and files  (@ /tmp), 
2) Cleaning the Lizmap cache folders  (@/srv/lizmap-web-client/temp/lizmap/www/cache/myapp )
    a) *WMTS_tilematrixsetlist.cache
    b) *WMTS_layers.cache
    c) /WMTS_hashe.cache
3) Cleaning the Jelix Cache (@ /srv/lizmap-web-client/temp/lizmap/www/cache/qgisprojects/jelix_cache)

Still trying stuff...

**Comment by carekapt** [comment]
Updated!
I have a workaround so I don't have to terminate de container to force QGIS Server to refresh de project properties:

1) First I remove the socket file: **rm /tmp/qgis-server.sock** 
2) Restart the QGIS Server manually (since it doesn't run as a service) **spawn-fcgi -s /tmp/qgis-server.sock -U www-data -G www-data -n /usr/lib/cgi-bin/qgis_mapserv.fcgi &**

Hope this workaround helps someone with the same problem.

**Comment by rldhont** [comment]
@carekapt you need this QGIS Server plugin https://github.com/3liz/qgis-logging-plugin to correctly flush project in QGIS Server Cache.

**Comment by carekapt** [comment]
Greetings all!
Two years later, here I am again !

Since this plugin is deprecated and I'm using qgis-plugin-manager to manage the plugins, was this flusher embedded on another server plugin that I can install via the plugin manager?

Kind regards

**Comment by Gustry** [comment]
No, there isn't any other plugin. We switched to Py-QGIS-Server https://docs.3liz.org/py-qgis-server/
