### ISSUE TITLE
Filter header section shows incorrect number of object when qgis layer has a filter.

### ISSUE THREAD

**Issue by groschialeux** [3liz/lizmap-web-client#1446]
I have a postgres table called "poi", it contains 328 records and there is a column called "source" which tells me where the poi comes from.

The current record count by source is:
S1: 23
S2: 223
S3:82

I show these POI's in separate layers in qgis by filtering on the "source" column.   

I have added those 3 layers in the filters section of lizmap.  When I open the filter window in the lizmap web client, the number in the header section shows 328 objects.

The database table has 328 rows but the layers don't, these should show 23 and 82 objects respectively. 

![Filter1](https://user-images.githubusercontent.com/50236986/71415662-cdb69b80-262a-11ea-964e-f2c6c450322f.png)

![Filter 2](https://user-images.githubusercontent.com/50236986/71415665-d1e2b900-262a-11ea-8621-d8f219a93ae5.png)

I understand that Lizmap only "talks" to qgis server and not directly to the database so I am not sure if it is a qgis server bug or a Lizmap bug.

**Comment by nboisteault** [comment]
Lizmap often talks to qgis server but sometimes directly to postgres.
We need a link to your project or a copy without any sensitive information to debug.

**Comment by groschialeux** [comment]
My map is not online yet.  I'm developing on a Linux desktop.

I am planning on publishing sometime in January

**Comment by rmarzocchi84** [comment]
I have encountered the same problem. 

In QGIS I add a filter on layer data, but when I use the filter I see the count of data without filter

**Comment by rmarzocchi84** [comment]
here an example as requested by @nboisteault :
https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/view/map/?repository=workshop&project=test_filter

Here the geopackage with data: 
[test_filter_ok.zip](https://github.com/3liz/lizmap-web-client/files/4576059/test_filter_ok.zip)



There are three problems: 
1) the data contained in a geopackage file.  if filtered on a QGIS project are not correctly shown 

Here the data not filtered:
![image](https://user-images.githubusercontent.com/4061154/80991568-83df8c80-8e38-11ea-914d-9afa354f6b40.png)

Here the data filtered:
![image](https://user-images.githubusercontent.com/4061154/80991632-9bb71080-8e38-11ea-87f5-dc001bc0e1e5.png)


2) the filter count do not works
Data not filtered count:
![image](https://user-images.githubusercontent.com/4061154/80991745-c3a67400-8e38-11ea-9974-3907db266fa5.png)

Data filtered count:
![image](https://user-images.githubusercontent.com/4061154/80991816-e6388d00-8e38-11ea-8b65-1eb09651ff41.png)

While on QGIS:
![image](https://user-images.githubusercontent.com/4061154/80991923-0c5e2d00-8e39-11ea-97ea-98a7b7856200.png)


3) Also data table do not works for filtered layer




Finally field "Map value" definitions are lost in data table and also in filter (unique value) and this is not nice expecially for filter where decoding is often very useful. 

![image](https://user-images.githubusercontent.com/4061154/80992721-3c5a0000-8e3a-11ea-86d5-6ea68b73a97f.png)

**Comment by rmarzocchi84** [comment]
QGIS server 3.10.6
LWC 3.3.5

**Comment by tethysgeco** [comment]
Hi, we have a similar issue.. Qgis server 3.4, LWC 3.3.3, Postgis layers. If we add a filter in Qgis desktop project the counter in Lizmap filter returns the total number of records of Postgis table (image 1) ignoring Qgis desktop filter.
The layer is correctly shown in Lizmap map and the data table in Lizmap (image 2) is the same of Qgis desktop (image3).
Image 1 - Lizmap filter counter:
 
![immagine](https://user-images.githubusercontent.com/23027624/81046211-2723b680-8eb8-11ea-8230-af03f8358d55.png)

Image 2 - Lizmap data table counter:
 
![immagine](https://user-images.githubusercontent.com/23027624/81046219-2e4ac480-8eb8-11ea-8116-c17f3f3bad8f.png)

Image 3 - Qgis attribute table counter:
 ![immagine](https://user-images.githubusercontent.com/23027624/81046243-399df000-8eb8-11ea-9a41-c14f2553d6ba.png)

**Comment by rmarzocchi84** [comment]
@nboisteault i do not know if my data can be useful for debug. Let me know.

**Comment by rmarzocchi84** [comment]
@nboisteault It is solved?

**Comment by nboisteault** [comment]
@rmarzocchi84 I reopen and I'll take a look when I'll find time.

**Comment by rmarzocchi84** [comment]
Thanks @nboisteault . if you have a suggestion to the file to check I can try a PR. Just yesterday we have encountered another issue related to filter https://github.com/3liz/lizmap-web-client/issues/1417 and it is nice if we can help your team

**Comment by nboisteault** [comment]
I confirm that LWC count all lines in the queried table => https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/filter/classes/filterDatasource.class.php#L125
@mdouchin To get correct count, do you know if we should query QGIS Server or if we could get and translate QGIS expression to SQL ?

**Comment by mdouchin** [comment]
I will propose a PR for this issue

**Comment by mdouchin** [comment]
PR #1708 will fix it . Please try and report sucess or failure

**Comment by nboisteault** [comment]
@mdouchin Ok for me !

**Comment by mdouchin** [comment]
PR merged. The related commit is now in release_3_3 and will land in master soon

**Comment by nboisteault** [comment]
Fixed in https://github.com/3liz/lizmap-web-client/commit/16e1da7af2d6e58952ff0d1faa4473d057634889
Thank you all for your reports.

**Comment by RobiFag** [comment]
@nboisteault @mdouchin we made some tests and I confirm that this problem is solved in LWC 3.3.8
QGIS SIDE
![image](https://user-images.githubusercontent.com/25825472/86483678-d663f900-bd54-11ea-8fe4-aa10fa77d109.png)
LIZMAP SIDE
![image](https://user-images.githubusercontent.com/25825472/86483721-f1366d80-bd54-11ea-946b-1dfa37406142.png)
