### ISSUE TITLE
Problème de stabilité des couches

### ISSUE THREAD

**Issue by kali06** [3liz/lizmap-web-client#145]
Bonjour,

j'ai un problème au niveau de l'affichage des couches de certaines applications 
j'ai une application avec un certain nombre de couches,
mais à chaque fois que j'ouvre cette application, je contaste que des couches n'apparaissent plus ni à l'affichage ni dans la légende,
et plus je me connecte à cette application et plus le nombre de couches qui disparaissent augmente,

le seule moyen que j'ai pour rétablir l'affichage est de redemarer le serveur apache,

je tiens à préciser que ces couches sont propres uniquement à cette application et ne sont pas utilisées par d'autres applications,

en vous remerciant par avance,

ps : config lizmap 2.10.2 + qgis server 2.6

**Comment by rldhont** [comment]
What's your OS ?
Did you use CGI or FCGI ?
Which apache version did you use ?

**Comment by kali06** [comment]
OS : Linux Debian 7
Apache 2
Ensuite j'ai suivi le guide d'installation donc normalement FCGI

**Comment by kali06** [comment]
Pour détailler ce problème récurent,

la disparition des couches se passent au bout d'un certain nombre de connexions successives sur la même application,
le nom de mes couches utilisées par les applications sont toutes en majuscules et propre à l'application,
Pour configurer mon serveur, j'ai suivit le guide d'installation linux dispoible sur votre site,
est-ce que ce problème provientd es configurations du serveur ?
Ou du nom des couches ?
En vous remerciant par avance

**Comment by rldhont** [comment]
Bonjour,

Ce bug a peut-être été corrigé dans QGIS-Server. Vous pouvez dès à présent le tester avec QGIS 2.12. Sinon ce bugfix a été backporté sur la branche 2.8 et 2.10.

Merci de nous indiqué si ce problème existe toujours.

**Comment by nboisteault** [comment]
Reopen issue if needed.
