### ISSUE TITLE
lizmap postgres layer edit error in CRS 5514

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-web-client#1452]
### Environment

 - Lizmap version: 
 - QGIS Server version:
 - QGIS Project version:
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by gisgogo** [comment]
lizmap v. 3.3.3
after edit point at crs 5514, point is lost. coordinate is changed. point at wgs84 is editable ok.

**Comment by nboisteault** [comment]
Hi,
Add 5514 projection in https://github.com/3liz/lizmap-web-client/tree/master/lizmap/www/Proj4js/defs and tell us if it fixes the issue.

**Comment by gisgogo** [comment]
Hi. I add projection 5514 to this directory, but no efekt. 

Proj4js.defs["EPSG:5514"] = "+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs ";

**Comment by nboisteault** [comment]
Please fill the issue template completely and give a small project illustrating the issue.
