### ISSUE TITLE
Edit layer : can't access to the edit form (loading progress bar)

### ISSUE THREAD

**Issue by julienh1** [3liz/lizmap-web-client#1453]
### What is the bug?
I try to edit a layer stored in PostGis. But when I select the layer in the Edition menu nothing happens but a loading progress bar. 
The form seems to be ok in Qgis and the cfg configuration file has no error.

### Steps to reproduce the issue

1. Go to Lizmap Web Client
2. Click on 'Edition'
3. Select layer to edit

![edition_bug](https://user-images.githubusercontent.com/58294367/71891776-99250280-3147-11ea-857a-df180221e610.PNG)

### Screenshots and logs
In Google Chrome Inspector I have the following error : 
```
Failed to load resource: the server responded with a status of 500 (Internal Jelix Error)
http://IP/websig/lizmap/www/index.php/lizmap/edition/modifyFeature?repository=demo&project=Test_Projet_QGIS_218&layerId=epci_1720200107114840283&featureId=13
```

In Lizmap web client logs I have:
```
2020-01-07 11:56:37	192.168.17.31	warning	2020-01-07 11:56:37	[2]	SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search	/var/www/websig/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	112

2020-01-07 11:56:53	192.168.17.31	error	2020-01-07 11:56:53	[403]	Erreur dans la requête (ERROR:  column d.adsrc does not exist
LINE 2:         a.atthasdef, d.adsrc
                             ^(SELECT t.typname, a.attname, a.attnotnull, a.attnum, a.attlen, a.atttypmod,
        a.atthasdef, d.adsrc
        FROM pg_type t, pg_attribute a LEFT JOIN pg_attrdef d ON (d.adrelid=a.attrelid AND d.adnum=a.attnum)
        WHERE
          a.attnum > 0 AND a.attrelid = 18299 AND a.atttypid = t.oid
        ORDER BY a.attnum))	/var/www/websig/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174
```

### Environment

 - Lizmap version: use of image 'jancelin/docker-lizmap:3.2.1'
 - QGIS Server version: use of image 'jancelin/qgis-server:2.18LTR'
 - QGIS Project version: tested with both 3.4 and 2.18
 - OS (Windows, Linux, MacOS, Android…): Ubuntu Server 18
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?  no changes, admin infos are stored in SQlite.

Any help would be very appreciated, thanks !

**Comment by rldhont** [comment]
It seems that the definition of your layer in the project is not up to date. The field `adsrc` is defined in the project not in the database.

**Comment by rldhont** [comment]
If you use image `jancelin/qgis-server:2.18LTR` for QGIS Server, you cannot use QGIS project version 3.4

**Comment by julienh1** [comment]
Thanks.
Indeed, I should not use the 3.4 QGIS project version, I just wanted to test. But right now I go with the 2.18.
Ok, but if the cause is the definition of the layer, whar should I correct to make it work ?

**Comment by ocelot73** [comment]
I have exactly the same issue with latest releases of all components:
Lizmap: 3.4.0-pre
QGIS server: 3.10.1+28bionic
QGIS project: 3.10.1
Server: Ubuntu 18.04.3 LTS
PostgreSQL: 12.1
PostGIS: 3.0.0
Tables set up with autoincremental primary key as stated in Lizmap documentation.

Lizmap correctly shows postgis layers and qgis projects but when I click on edit layer, when i press the Add button, it appears the loading bar and nothing else happens.
Here is the error log in lizmap administration panel: 

`2020-01-08 23:47:38	84.223.140.170	warning	2020-01-08 23:47:38	[2]	SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search	/var/www/lizmap-web-client-master/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	112

2020-01-08 23:47:38	84.223.140.170	warning	2020-01-08 23:47:38	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fhome%2Fqgis%2Fprojects%2Fsit%2Fprova%5Fedit%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
	/var/www/lizmap-web-client-master/lizmap/modules/lizmap/classes/lizmapProxy.class.php	240

2020-01-08 23:47:44	84.223.140.170	error	2020-01-08 23:47:44	[403]	query non valida (ERRORE:  la colonna d.adsrc non esiste
LINE 2:         a.atthasdef, d.adsrc
                             ^(SELECT t.typname, a.attname, a.attnotnull, a.attnum, a.attlen, a.atttypmod,
        a.atthasdef, d.adsrc
        FROM pg_type t, pg_attribute a LEFT JOIN pg_attrdef d ON (d.adrelid=a.attrelid AND d.adnum=a.attnum)
        WHERE
          a.attnum > 0 AND a.attrelid = 17880 AND a.atttypid = t.oid
        ORDER BY a.attnum))	/var/www/lizmap-web-client-master/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174`

I don't know what is d,adssrc column that doesn't exists.....
Any hint to solve this error in editing postgis layers ?
Thanks in advance

**Comment by ygorigor** [comment]
It's a QGIS server issue. You need to wait for an update. This issue happened because of Postgresql 12

**Comment by julienh1** [comment]
@ygorigor Thanks ! I tried with the version 11 of Postgresql (I'm still on the 2.3 QGIS Server version) and it works ! I can edit every object I want.

**Comment by paolo73an** [comment]
I confirm with postgresql 11 everything works fine but it would be a pity if lizmap developers won't try to fix this...

**Comment by laurentj** [comment]
@paolo73an it is not an issue into Lizmap, but into the framework on which lizmap is built.

**Comment by ygorigor** [comment]
@laurentj I solved this issue by changing `d.adsrc` to `pg_get_expr(d.adbin,d.adrelid) AS adsrc` in lib/jelix/plugins/db/pgsql/pgsql.dbschema.php and lib/jelix/plugins/db/pgsql/pgsql.dbtools.php

**Comment by rldhont** [comment]
@ygorigor can you provide a pull request to https://github.com/jelix/jelix to branch https://github.com/jelix/jelix/tree/jelix-1.6.x ?

**Comment by laurentj** [comment]
@ygorigor thanks, but I just [fixed the issue](https://github.com/jelix/jelix/commit/b353e311865537c6ca965a2480593a54dec439ac) ;-)

And your change may not be compatible with Postgresql <12. The compatibility with previous version must be kept.

**Comment by ocelot73** [comment]
@laurentj I've tried to edit the 3 php files according to your commits, run the installer and set rights for lizmap but I'm not still able to edit layers with Lizmap 3.4.0 pre (edited), latest QGIS server and Postgresql12 with postgis 3, if I press the add button the loading bar gets stuck.

**Comment by ygorigor** [comment]
@ocelot73 @laurentj I also tried to change `adsrc` to `adbin` before I found solution to change `d.adsrc` to `pg_get_expr(d.adbin,d.adrelid) AS adsrc`, and I'm mostly sure that my version should work with postgresql 9.5+

**Comment by ocelot73** [comment]
@ygorigor your solution works, I will use it until next lizmap update, thanks

**Comment by laurentj** [comment]
@ygorigor sorry, you're right. `pg_get_expr` should be used. I search into the postgresql documentation and it is the good way to read admin. I'm going to fix that.

**Comment by laurentj** [comment]
Fixed. Thanks for your help.
