### ISSUE TITLE
Layers not showing any geometries

### ISSUE THREAD

**Issue by groschialeux** [3liz/lizmap-web-client#1455]
Configuration is lizmap 3.3.3, qgis-server 3.4.14, apache2, postgresql 10 on ubuntu 18.04.3 LTS server
I created the project on my linux mint desktop.  Lizmap, qgis-server, apache and postgresql are the same versions as the server.

Everything works just fine on the desktop but on the server nothing shows up in any layers.  I can see my data in the attribute tables, the popups and tooltips work, I can create geometries and they show up when I check with qgis desktop.

qgis-server is working, I tested it with these url's, [WMS](https://maps.expedimaps.com/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&REQUEST=GetCapabilities), [WMTS](https://maps.expedimaps.com/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&REQUEST=GetCapabilities), [WFS](https://maps.expedimaps.com/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities)

Everything works except I don't see any geometries in the browser.

I don't see any error(s) in any of the logs (apache, qgis, lizmap).    I am lost with this, I can't figure out what the problem is.

**Comment by nboisteault** [comment]
Nothing in the console ?

**Comment by groschialeux** [comment]
Nothing.

**Comment by groschialeux** [comment]
So this morning I changed my cache setting in lizmap to use Sqlite.  I enabled all the layers in my map and spent some time zooming in and out and dragging the map around.   I expected the cache files to grow but they did not.

Every one of them if 3072 bytes, I think that should not be the case.

**Comment by groschialeux** [comment]
I think I got something interesting here.  I am hosting this on a VPS droplet at Digital Ocean.

I tested on a laptop following the same procedure I did on the VPS and everything works just fine.  The difference is the laptop is hardware and has display unlike Digital ocean's VPS and I used a downloaded image if Ubuntu as opposed to digital ocean who may be using an image that was modified for compatibility with the virtualization environment.

Does Lizmap need a display ?  Do I have to install a fake x-server on the VPS ?   I know I had to when I was playing with QWC2 so I'm thinking maybe it's the same here.

**Comment by groschialeux** [comment]
Problem solved.

In my lizmap configuration I had put the FQDN of my site, it looks like the server somehow could not resolve this internally, I changed the wms URL to http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi and voilà, problem solved.
