### ISSUE TITLE
BAN controller: property of non-object

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1456]
### What is the bug?
```
Trying to get property of non-object	/srv/lizmap_web_client/lizmap/modules/lizmap/controllers/ban.classic.php	53
```

### Expected behavior
Cleanly check the object

### Environment

 - Lizmap version: 3.3
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4
 - OS (Windows, Linux, MacOS, Android…):  Linux
 - Browser (Firefox, Chrome…): Any

**Comment by laurentj** [comment]
Fixed in caba78ed0dc79e555a07496ca36ace6fd0155aac
