### ISSUE TITLE
PG_PCONNECT: FATAL error with persistent connection on terminated connection

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1457]
### What is the bug?
```
2020-01-08 14:56:48	127.0.0.1	error	2020-01-08 14:56:48	[403]	Erreur dans la requête (FATAL:  terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.(SET search_path TO "cadastre",public))	/srv/lizmap/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	159

2020-01-08 14:56:48	127.0.0.1	notice	2020-01-08 14:56:48	[8]	Unknown: Cannot set connection to blocking mode	Unknown	0
```

### Steps to reproduce the issue

1. Create a QGIS project with PostgreSQL/PostGIS layer
2. Publish this layer as WFS
3. Configure this layer in attribute layer
4. Open the project in lizmap web client
5. Restart the PostgreSQL/PostGIS
6. Open the attribute table
7. The table never comes and the log has the FATAL Error

Restart the php-fpm to partially solve the issue.

### Expected behavior

Restart the connection in this case.

### Environment

 - Lizmap version: 3.3
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4
 - OS (Windows, Linux, MacOS, Android…):  Linux

**Comment by rldhont** [comment]
@mdouchin do you have more information ?

**Comment by mdouchin** [comment]
Jelix uses a virtual database profile to get the data from PostgreSQL. This profile is set with `persistent = on`.

We could perhaps enhance `lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php` to test the `pg_last_error` and try to reconnect when the error corresponds to `FATAL:  terminating connection due to administrator command server closed the connection unexpectedly`. Perhaps use the method `pg_connection_reset` . See [php documentation](https://www.php.net/manual/en/function.pg-connection-reset.php)

**Comment by laurentj** [comment]
the `persistent = on` has been added **months ago**. If this is related, the problem would appear months ago. So I don't understand.

Do you have made some tests WITHOUT this  `persistent = on` ? And what are the results ?

And what is the PHP version?

**Comment by rldhont** [comment]
The issue appear after the migration to lizmap-web-client 3.3 because of the migration to QGIS Server 3.4.

I have test without  `persistent = on` because it is not in lizmap-web-client 3.2 and I never have ths problem.

PHP 7.0

**Comment by laurentj** [comment]
I removed the `persistant` parameter. In some real case, it seems it fixes the issue.
