### ISSUE TITLE
Possibilité de masquer une catégorie pour une couche catégorisé (ou gradué) via la légende.

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#146]
Bonjour,
QGIS 2.6 a introduit la possibilité de masquer ou non dans la légende une catégorie d'une couche catégorisé (via une case à cocher). (https://www.qgis.org/fr/site/forusers/visualchangelog260/index.html#feature-classes-within-graduated-and-categorised-renderers-can-be-toggled)

J'utilise Lizmap 2.11 avec QGis serveur 2.8 sur un serveur Ubuntu et j'aurais aimé utilisé cette fonctionnalité. Est elle disponible et si oui, comment l'activer ?

Merci d'avance.

**Comment by igeofr** [comment]
Identical request : #422

**Comment by nboisteault** [comment]
Duplicate of #422
