### ISSUE TITLE
print icon does not display

### ISSUE THREAD

**Issue by saeri-ims** [3liz/lizmap-web-client#1460]
Hello,
this is my working environment
    Lizmap version: 3.3
    QGIS Server version: >= 3.0
    QGIS Project version: 3.4 LTR
    OS (Windows, Linux, MacOS, Android…): Linux Ubuntu 18

I have noticed that lizmap webclient does not display anymore the "print" icon, despite when preparing the QGIS project i tick the print function in the lizmap form (plugin).

Has anybody else encountered the same problem?
Before moving to lizmap version 3.3 the print icon and print functionalities have always worked fine.

Many thanks

**Comment by Gustry** [comment]
Are you sure you didn't enable the atlas feature in your layout?

**Comment by saeri-ims** [comment]
@Gustry, the only thing i enable when preparing the project in QGIS is under map option (this is in the lizmap plugin) and in map tools i tick simply print. In all previous occasions (when the print icon worked well and displayed e.g. QGIS 2.18LTR and Lizmapwebclient prior 3.3) i never set up the atlas.

**Comment by saeri-ims** [comment]
@Gustry, i found where i was making a mistake and i never realised before "why" the print function worked. So, as in the documentation of lizmap, apart from ticking the print option in the lizmap plugin i need to have a print layout set up with at least one map. I have done it now and the print icon has appeared.
