### ISSUE TITLE
Dataviz in popup

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#1462]
Can someone direct me how to create plots (dataviz?) in pop-up, I would prefer lizmap source configuration instead of qgis.
I would like to get something similar as in #818.

**Comment by aeduard** [comment]
Well, being a basic user for html/css and a beginner for javascript it took me some days to figure it out. Probably it's obvious for most of the community here, but if there are beginners like me it might help to start.

In the pop-up code for lizmap source you can put html code, as in lizmap [documentation](https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html?highlight=dataviz#lizmap-popup). For plotly just simply copy plotly chart javascript code (eg. from [official documentation](https://plot.ly/javascript/line-charts/)) and paste in the html file between <script></script> tags in the <body></body> section.

Of course the above linked plotly code is static, but it can take lizmap/qgis database attribute fields having the classic format {$myfield}.

**Comment by Gustry** [comment]
In the cats project, it's using relation. No need to code, using the relation and the checkbox : 
![Sélection_002](https://user-images.githubusercontent.com/1609292/74613511-5c1d3a00-510f-11ea-9ab3-e41983f8ff01.png)

**Comment by aeduard** [comment]
Thank you for your input. For this special case I needed a bit of code, as I made a pie chart for the distribution of chemical components at some monitoring station. I needed to use 8 columns.
