### ISSUE TITLE
are now users setting their password?

### ISSUE THREAD

**Issue by saeri-ims** [3liz/lizmap-web-client#1463]
Hello,

this is my working Environment

    Lizmap version: 3.3
    QGIS Server version: >= 3.0
    QGIS Project version: 3.4 LTR
    OS (Windows, Linux, MacOS, Android…): Linux Ubuntu 18
    Browser (Firefox, Chrome…): Firefox

I have recently had to set a new user for a repository and to my surprise i have noticed that I, as administrator, cannot set anymore the password of the user. Rather an email is sent to the user and he/she set the password. At the bottom in fact it is written:
An email will be send to the user, so the user could activate the account by giving a new password.¨ 
See screenshot below
![new_user_lizmap](https://user-images.githubusercontent.com/42073830/72390597-e2f28780-3709-11ea-9484-3902eabe2c3a.png)

This is not fully clear to me. OK that the user can change password but after it has been given by the administrator. I cannot understand if this is a bug (it did not happened before as admin i set the password of the users) or i am missing something.
Thanks for your help!

**Comment by ygorigor** [comment]
@saeri-ims https://github.com/3liz/lizmap-web-client/issues/1402

**Comment by saeri-ims** [comment]
@ygorigor thanks for pointing to the issue #1402. I confirm that i solved the problem by editing the local config file as suggested by @laurentj

**Comment by rldhont** [comment]
It is a lack of documentation ?

**Comment by Gustry** [comment]
@rldhont, yes. The ticket mentioned #1402 has the label `doc-needed`
