### ISSUE TITLE
IGN basemap no display

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-web-client#1465]
### What is the bug?
Problèm using IGN basemap with key on Lizmap 3.3.3 and Qgis-server 3.10/3.8/3.4

### Steps to reproduce the issue

1. QGIS Lizmap plugin
2."FOND"
3. ign-photo, ign-scan (with valid key)
4. Launch Lizmap app
5. No basemap 

### Expected behavior
Lizmap should display the IGN photo map but it doesn't find it.
It seems that it uses the wrong URL.
I have a lower lizmap 3.0 and qgis-server 2.18 runing and it works perfectly, but not on the lizmap 3.3.3 + docker >3.0.

### Screenshots and logs
When i check the F12 network management i get : 
  -  Lizmap 3.0 - QgisServer 2.18 : 
      - https://gpp3-wxs.ign.fr
  - Lizmap 3.3.3 - QgisServer 3.10
      - https://wxs.ign.fr
If i add the "gpp3" to the url it actually work fine.

Where could i change that path ? Or is there a ways that i can have this working well ?

### Environment

 - Lizmap version: 3.3.3
 - QGIS Server version: 3.4,3.8, 3.10 using docker-qgis-server from 3Liz docker hub
 - QGIS Project version: 3.8.3
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

Thanks

**Comment by rldhont** [comment]
The URL https://gpp3-wxs.ign.fr is deprecated and will be deactivated https://geoservices.ign.fr/blog/2019/05/03/redirection-auto-oshimae.html

So if your key works fine with https://gpp3-wxs.ign.fr and not with https://wxs.ign.fr, it means that your key has not been updated to be available with the new web service URL.

The Geoportail service manager is currently in maintenance, you will have to wait to update your key.

**Comment by Ailurupoda** [comment]
Great thanks, 
I also had a DNS problem.
