### ISSUE TITLE
WMTS:seeding with small bounding box generates a huge quantity of tiles

### ISSUE THREAD

**Issue by cfsgarcia** [3liz/lizmap-web-client#1469]
Hi, I'm trying to compute a cache generation for a very small bounding box using wmts command line script.
E.g.: 5 meters * 5 meters bounding box between two googlemaps level of details (1:18,056 -> 1:9,028)

**php lizmap/scripts/script.php lizmap~wmts:seeding -v -f -bbox "-83120,6800140,-83115,6800145" my_repo my_app "my_layer" EPSG:3857 16 17**

When running the above it says it shall generate over 6 millions tiles although it seems to understand the bounding box passed on: 

**The TileMatrixSet 'EPSG:3857'!
1400111 tiles to generate for "my_layer" "EPSG:3857" "16" "-83120,6800143,-83115,6800148"
5588635 tiles to generate for "my_layer" "EPSG:3857" "17" "-83120,6800143,-83115,6800148"
6988746 tiles to generate for "my_layer" "EPSG:3857" between "16" and "17"
Start generation**

Here are those two levels of details analysed in the initial capabilities:
**lizmap/scripts/script.php lizmap~wmts:capabilities -v my_repo my_app "my_layer" EPSG:3857**
The above returns:
**For "my_layer" and "EPSG:3857" the TileMatrix 16 has 4916280 tiles
For "my_layer" and "EPSG:3857" the TileMatrix 17 has 19647368 tiles**

Any ideas what I could be doing wrong or if ever there was a problem whether a fix exists?

Merci et bravo pour le travail!

**Comment by cfsgarcia** [comment]
Just taken a look at modules/lizmap/controllers/wmts.cmdline.php and I'm not sure why in seeding function we take the minimum of bounding box tiles location and service tile limits:

```
$tileMatrix = (object) array(
	id => $tileMatrixLimit->id,
	minRow => min($minRow, $tileMatrixLimit->minRow),
	minCol => min($minCol, $tileMatrixLimit->minCol),
	maxRow => min($maxRow, $tileMatrixLimit->maxRow),
	maxCol => min($maxCol, $tileMatrixLimit->maxCol),
);
```

Looks like to restrict to the bounding box we should have:
```
$tileMatrix = (object) array(
	id => $tileMatrixLimit->id,
	minRow => $minRow, 
	minCol => $minCol,
	maxRow => $maxRow,
	maxCol => $maxCol,
);
```

**Comment by johnzet39** [comment]
Have you solved this issue? I have a problem with count of tiles too. If I take the same size of the bbox in different areas of the map extent, then the count of tiles differs significantly for each bbox.

**Comment by johnzet39** [comment]
Well, I made changes to wmts.cmdline.php as cfsgarcia noticed and the script worked as I needed.

**Comment by nboisteault** [comment]
@rldhont there might be something to fix.

**Comment by johnzet39** [comment]
Any thoughts? :) On 3.5.2 still have to do code substitution.

**Comment by rldhont** [comment]
@cfsgarcia @johnzet39 The right code should be:
```php
                        $tileMatrix = (object) array(
                            'id' => $tileMatrixLimit->id,
                            'minRow' => max($minRow, $tileMatrixLimit->minRow),
                            'minCol' => max($minCol, $tileMatrixLimit->minCol),
                            'maxRow' => min($maxRow, $tileMatrixLimit->maxRow),
                            'maxCol' => min($maxCol, $tileMatrixLimit->maxCol),
                        );
```
