### ISSUE TITLE
Error when editing layers stored in Postgis if field is in capital letters

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#147]
In Postgis, when executing SQL querys if the field is in capital letters the field in the query MUST be between double quotes ("). Example.

INSERT INTO "public"."portales" ("GEOMETRY", cod_calle, portal_num ) 
VALUES (ST_GeomFromText('POINT(499117.09083286155 4799669.372050852)', 23030), '333', '33');

note that "GEOMETRY" field is between double quotes.

In lizmap, when editing a layer that is stored in postgis, the insert query generated when adding a new feature to the layer, has no double quotes NEVER. This raises an error and the feature is not inserted.

In apache\htdocs\lizmap\lizmap-web-client-master\lizmap\var\log\messages.log I can see that the query being executed was:

INSERT INTO "public"."portales" (GEOMETRY, cod_calle, portal_num ) 
VALUES (ST_GeomFromText('POINT(499117.09083286155 4799669.372050852)', 23030), '333', '33');

note that GEOMETRY is without double quotes so postgis after that will convert that field to lower case and the query will crash telling that the field geometry (in lowercase) does not exist.

The easiest solution to this issue should be, for layers stored in postgis, all the fields must be between double quotes in all the querys (SELECT, INSERT, UPDATE, DELETE). Example:

INSERT INTO "public"."portales" ("GEOMETRY", "cod_calle", "portal_num" ) 
VALUES (ST_GeomFromText('POINT(499117.09083286155 4799669.372050852)', 23030), '333', '33');

I don't know if this behaviour can be parametrized in PostGIS but should be fixed in Lizmap to avoid problems.

**Comment by rldhont** [comment]
It is not a problem of capital field, it's a problem of reserved name. GEOMETRY is the name of a PostGIS class.

But it's a bug and it has to be fixed.
