### ISSUE TITLE
geolocation doesn't work with postgis

### ISSUE THREAD

**Issue by paolo73an** [3liz/lizmap-web-client#1474]
I got a Let's encrypt certificate so my website is under https now and I"ve started using geolocation that works perfectly if i use layers linked to shapefiles (copied in data subdirectory) but it doesn't work if I use in Lizmap project a layer linked to a Postgis database in same server. I suppose the problem is in configuring the correct settings for postgis database connection or in some other ssl issues but i haven't been able to solve this so far..
In lizmap documentation there are no explanations about it so I kindly ask the support of this community, thanks.

(P.S: lizmap 3.4.0 pre, latest qgis and qgis server, postgresql 11 with postgis 2.5, QGIS Project version: 3.10.1,linux ubuntu 18.04.3, Browser (Firefox, Chrome…)

**Comment by paolo73an** [comment]
I've tried the 3.3.4-pre version of lizmap (3.3.3 branch) and geolocation always works (with shapefiles, spatialite and postgresql/postgis layers).
With master version downloaded today geolocation doesn't work at all...

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#building-javascript

**Comment by josemvm** [comment]
@nboisteault does it mean that the geolocation component is no longer part of the lizmap core?!

**Comment by nboisteault** [comment]
We are making Lizmap JavaScript more modular and we are using more modern tools. Geolocation is the first component to be now in is own module. End users won't see no changes but developers using source code will have to build JavaScript with npm.

**Comment by Gustry** [comment]
@paolo73an @josemvm 
As @nboisteault mentionned in the link, starting from Lizmap 3.4 (the master branch), you can't use the code from GitHub directly. PHP Composer and Javascript NPM are required to build.

Either build using these tools or use the zip files provided in release.

@paolo73an Can you confirm it's working if you do one of these steps?

**Comment by paolo73an** [comment]
@Gustry I"ve quickly read the docs and started to build (latest master version) but serveral errors came out so I suddenly recovered a snaphot of the vps and reverted to lizmap 3.3.4-pre because I needed it to work. I'll soon try again maybe reporting the warning/error messages so you will be able to help a newbie :--) see you soon

**Comment by paolo73an** [comment]
I'd like to specify that I'm experimenting the issue of geolocation not working with lizmap 3.4 master branch by downloading and installing lizmap from zip file

**Comment by nboisteault** [comment]
@paolo73an can you give us the link you used ?

**Comment by paolo73an** [comment]
@nboisteault the one from git repository
https://github.com/3liz/lizmap-web-client/archive/master.zip

Do I have to build as suggested anyway ?

**Comment by nboisteault** [comment]
Github archive is just source code with no build in it. Different built LWC can be downloaded [here](https://packages.3liz.org/pub/lizmap/). Last build of master is [here](https://packages.3liz.org/pub/lizmap/unstable/3.4/lizmap-web-client-3.4.0-pre.zip).
Please close issue if everything works. Thanks.

**Comment by Gustry** [comment]
> @nboisteault the one from git repository
> https://github.com/3liz/lizmap-web-client/archive/master.zip
> 
> Do I have to build as suggested anyway ?

Yes, as we said. It's not possible anymore to use the code from git directly. You must use NPM and PHP composer.

**Comment by ocelot73** [comment]
I've tried with the pre-built zip file from 3liz website but geolocation doesn't work either.
I've just seen there's a similar [issue #1447](https://github.com/3liz/lizmap-web-client/issues/1447) already open, maybe they can be merged.

**Comment by nboisteault** [comment]
@laurentj In pre-built master I cannot see `lizmap.js` in `lizmap/www/js/`. Could you investigate ?
@ocelot73 #1447 was a different issue.

**Comment by paolo73an** [comment]
Detective needed :-)

**Comment by laurentj** [comment]
@nboisteault the issue in the package have been fixed a month ago . 69c21b1730bdab22e967eb15bcc4e60f4b5eb055

@paolo73an please retry with the latest package https://packages.3liz.org/pub/lizmap/unstable/3.4/

**Comment by nboisteault** [comment]
@paolo73an 
Please reopen if issue still occurs.
