### ISSUE TITLE
export files - wrong file name

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1475]
hi

lizmap exports the files with wrong file name encoding (e.g.: `export_Bocas_de_IncÃªndio.xxx` in case of `Bocas de Incêndio`/layer name in lizmap).
https://github.com/3liz/lizmap-web-client/issues/500#issuecomment-559717086

thanks for your attention

**Comment by josemvm** [comment]
the same problem when the user downloads the PDF file print output

**Comment by josemvm** [comment]
@rldhont here i'm talking about with wrong file name (PDF output) related to printer tool

**Comment by josemvm** [comment]
it's a very annoying situation for the users...

please, can you try to fix it?

**Comment by rldhont** [comment]
@josemvm I think this issue a lizmap issue not wfsOutputExtension one.

**Comment by josemvm** [comment]
@rldhont yes, i think so too, that's why i keep it here
and that is why i ask you to try to fix it

**Comment by josemvm** [comment]
@rldhont this issue is about the `composer title` into the qgis desktop

when the user downloads the printer output (PDF, JPG, PNG or SVG), lizmap doesn't assume the special characters

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/blob/720b5a0edebe9941c6220a5e824b76876c6fb844/lizmap/modules/lizmap/classes/lizmapProject.class.php#L1084

???

**Comment by rldhont** [comment]
> https://github.com/3liz/lizmap-web-client/blob/720b5a0edebe9941c6220a5e824b76876c6fb844/lizmap/modules/lizmap/classes/lizmapProject.class.php#L1084
> 
> ???

This code is about excluding the restricted composers to the available composers.

**Comment by josemvm** [comment]
somewhere in the code the name of the printer output file is formed based on the concatenation of the `project name`/qgis file name with string `_` and with the name of the print layout/`composer title` ...

**Comment by nboisteault** [comment]
`typename` is used to compose the file name. This one should **never** contain special characters. You can test that as shown in screenshot above (Launch button) : 
![image](https://user-images.githubusercontent.com/2145040/95186998-eadbe580-07ca-11eb-9ddd-9e529d930641.png)
