### ISSUE TITLE
Change default .htaccess content on src files for Windows

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#1478]
I've been struggling around to make a new fresh installation of Lizmap working under Apache 2.4 in Windows Server 2016.

I followed this guide: https://docs.lizmap.com/current/en/install/windows.html

I finally found the solution to my problem:

In lizmap/www/.htaccess file in Lizmap 3.3 fresh download I have the content "Allow from all" but apache 3.4 does not understand this words so I couldn't access my lizmap installation via web (localhost/lizmap3/index.php gave Internal Server Error continuosly). Once changed the content of .htaccess file to "Require all granted", which Apache 2.4 does understand, it worked properly.

I suggest changing the .htaccess file content in the src files for windows because the default installation from now on should be Apache 2.4.

Maybe there is something I am missing and I am wrong. Your choice.

**Comment by laurentj** [comment]
We should fix the .htaccess file with conditionnal instruction for apache, which will execute `Allow from all` or `Require all granted`, depending of the existence of some module specific to 2.4 (I don't remember which one, I'll take a look).

**Comment by laurentj** [comment]
Thanks for the report
