### ISSUE TITLE
loading.gif and logo_footer.gif paths are absolute

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#148]
If I load lizmap from a diferent server where lizmap is running, the loading.gif and logo_footer.gif are not displayed. In the firebug console I see:

"NetworkError: 404 Not Found - http://localhost/lizmap/lizmap-web-client-master/lizmap/www/themes/default/css/img/logo_footer.png"
logo_footer.png
"NetworkError: 404 Not Found - http://localhost/lizmap/lizmap-web-client-master/lizmap/www/themes/default/css/img/loading.gif"

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7680018/9e8f6986-fd62-11e4-81f4-fb0f8bcabce1.png)

Note that is looking for the gif files in locahost. As I am in another machine it doesn't find anything.

**Comment by rldhont** [comment]
Lizmap is based on jelix http://jelix.org/en/

If you change the domain of lizmap, you have to clear the lizmap www temp directory. You'll find it in the lizmap has temp/lizmap/www

**Comment by jaitor1** [comment]
Solved. Thanks.
