### ISSUE TITLE
Cannot save features with PG serial ids

### ISSUE THREAD

**Issue by signedav** [3liz/lizmap-web-client#1480]
### What is the bug?
On having serial ids on the postgres database I'm not able to create or edit features in Lizmap.

### Steps to reproduce the issue

1. Go to 'Edit'
2. Select Layer
3. Enter Values in Form and select geometry
4. Click on 'Speichern' (save)
5. Message appears 'Zeichen Sie auf Karte um Objekt zu erstellen'. (draw on map to create object)
6. On the Form it says thet 'id' field is requested

### Expected behavior
That it stores the feature and the id is handled on postgres.

### Screenshots and logs
![image](https://user-images.githubusercontent.com/28384354/73434082-5d481c00-4346-11ea-8708-9689cfbb986f.png)

### Environment
 - Lizmap version: 3.3.3
 - OS (Windows, Linux, MacOS, Android…): Windows/Linux
 - Browser (Firefox, Chrome…): Chrome / IE

#### PG field definition
```
CREATE TABLE infra_visu.baustelle (
  id SERIAL PRIMARY KEY,
  [...]
  geom geometry(POINT, 2056)
);

CREATE OR REPLACE VIEW infra_visu.baustelle_aktuell AS SELECT
  *
FROM
  infra_visu.baustelle
WHERE
  enddatum >= now()::DATE;

ALTER VIEW IF EXISTS infra_visu.baustelle_aktuell ALTER id SET DEFAULT nextval('infra_visu.baustelle_id_seq');
```
#### QGIS widget config 
![image](https://user-images.githubusercontent.com/28384354/73435317-aef1a600-4348-11ea-97ad-515e1884e631.png)
```
        <field name="id">
          <editWidget type="TextEdit">
            <config>
              <Option/>
            </config>
          </editWidget>
        </field>
```

Since the field is not selected in the QGIS form layout it's not visible in Lizmap.
If it would be, it would be displayed red (constraint) and empty.

**Comment by rldhont** [comment]
Can you provide ?
* the PG field definition
* the QGIS editing widget configuration (the choosen widget and the required part)
* the XML of the QGIS editing widget configuration
* the field displayed in lizmap editing form

Thanks

**Comment by signedav** [comment]
Okay @rldhont Updated additional info in the description.

**Comment by rldhont** [comment]
@signedav how the field is displayed in the QGIS Form ?

As it is configured the user has to defined to a value to get a valid form ?

**Comment by signedav** [comment]
It's not displayed because it's not selected by the drag and drop configuration. But if I would display it it would look like this:
![image](https://user-images.githubusercontent.com/28384354/73468121-9901d680-4384-11ea-8cc5-e7aac80b72fb.png)

**Comment by rldhont** [comment]
And the check is green ?

**Comment by signedav** [comment]
Yes

**Comment by rldhont** [comment]
fixed regression found
