### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#1486]
Hi there!

I am getting permission error after installning according the Liz3 manual: https://docs.lizmap.com/current/en/install/windows.html

![image](https://user-images.githubusercontent.com/12575941/73541045-c193da00-4431-11ea-9e05-8afe3c0ae7ab.png)

I am using QGIS 3.10
Windows 10
QGIS server 3.10
PHP 7.4.2

I wonder what may be wrong or missing ? any help will be appreciated!!

/Abel

**Comment by Gustry** [comment]
Your URL is showing the use of QGIS Server, not Lizmap.
You first need to check that QGIS Server is working (without Lizmap).

Which webserver are you using? (to call qgis server)

Did you follow this documentation ? https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/server/getting_started.html

Personally, I don't have experience on windows.

**Comment by Abelon38** [comment]
Hi! Thanks för answering!

I am using the installation process described in 3Liz website (https://docs.lizmap.com/current/en/install/windows.html) because installation from qgis.org has performance issues. 

My QGIS server is not working well as I can see in http://localhost:60/qgis/qgis_mapserv.fcgi.exe? 
Apache is on. My virtualHosts looks like this:
<VirtualHost *:60>
  Include conf/extra/php-qgis.conf
  ServerName localhost

  DocumentRoot "C:/webserver/lizmap/"
  <Directory "C:/webserver/lizmap">
      Options -Indexes +FollowSymLinks +ExecCGI
      AllowOverride All
      Require all granted
  </Directory>

  Alias /qgis/ "C:/webserver/OSGeo4W64/apps/qgis/bin/"
  <Directory "C:/webserver/OSGeo4W64/apps/qgis/bin/">
      SetHandler fcgid-script
      Options +ExecCGI
      AllowOverride All
      Require all granted
  </Directory>

  CustomLog "logs/lizmap-access.log" common
  ErrorLog "logs/lizmap-error.log"

  <IfModule mod_fcgid.c>
                RewriteEngine on
                RewriteCond %{HTTP:Authorization} .
                RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  </IfModule>

        <IfModule fcgid_module>
    FcgidMaxRequestLen 51200000
    FcgidConnectTimeout 60
  </IfModule>

</VirtualHost>

**Comment by Gustry** [comment]
We can only give you this link about Windows : https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows
Not a lot of users are using Windows. Or you should have a look to Docker which works on Windows as well https://github.com/3liz/lizmap-docker-compose#run-lizmap-stack-with-docker-compose
