### ISSUE TITLE
TASK [lizmap : Set rights on dirs]

### ISSUE THREAD

**Issue by FlatEric88** [3liz/lizmap-web-client#1490]
### What is the bug?
Hallo, I'm tryling to install Lizmap via Vagrant. Everytime I'm using the vagrant provision command i get an error with the ansible task [lizmap : Set rights on dirs]

It seems like the file set_rights.sh can't be found on server, but it is where it should be.

### Steps to reproduce the issue
I was following these steps.

https://github.com/3liz/lizmap-web-client/blob/master/vagrant/README.md

After the Installation I can reache Nginx server under http://localhost:8130/ but http://localhost:8131/ and http://localhost:8132/ cause errors.

### Screenshots and logs

TASK [lizmap : Set rights on dirs] *********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "cd /lizmap_web_client && lizmap/install/set_rights.sh vagrant vagrant", "delta": "0:00:00.003712", "end": "2020-02-02 14:33:14.014149", "msg": "non-zero return code", "rc": 2, "start": "2020-02-02 14:33:14.010437", "stderr": "lizmap/install/set_rights.sh: 1: lizmap/install/set_rights.sh: !/bin/sh\r: not found\nlizmap/install/set_rights.sh: 3: lizmap/install/set_rights.sh: \r: not found\nlizmap/install/set_rights.sh: 6: lizmap/install/set_rights.sh: \r: not found\nlizmap/install/set_rights.sh: 20: lizmap/install/set_rights.sh: Syntax error: end of file unexpected (expecting \"then\")", "stderr_lines": ["lizmap/install/set_rights.sh: 1: lizmap/install/set_rights.sh: !/bin/sh", ": not found", "lizmap/install/set_rights.sh: 3: lizmap/install/set_rights.sh: ", ": not found", "lizmap/install/set_rights.sh: 6: lizmap/install/set_rights.sh: ", ": not found", "lizmap/install/set_rights.sh: 20: lizmap/install/set_rights.sh: Syntax error: end of file unexpected (expecting \"then\")"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=80   changed=11   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Environment

 - Lizmap version: 3.3.3
 - Vagrant Installation

**Comment by nboisteault** [comment]
What is your host system ?

**Comment by FlatEric88** [comment]
> What is your host system ?

Windows 10 Pro

**Comment by nboisteault** [comment]
SSH into your VM with `vagrant ssh` then try to execute `/lizmap_web_client/lizmap/install/set_rights.sh`.
