### ISSUE TITLE
The vector object is no longer highlighted

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#1493]
### What is the bug?
The vector object is no longer highlighted.
"Add geometry to feature response" option in project properties does not work anymore and the zoom lens on the object doesn't work.

### Steps to reproduce the issue

This bug is only in the last master code. In previous release, 3.3.x, it worked.

### Expected behavior
When I select a vectorial object, the yellow outline must be visible

### Environment

 - Lizmap version: 
 - QGIS 3.4, 3.10:
 - QGIS 3.4, 3.10:
 - OS (Linux, MacOS, Windows): 
 - Browser (Firefox, Safari, Chrome, Edge, ...):
 - Lizmap admin information (users, logs…) stored into Sqlite

**Comment by news24lor** [comment]
This very useful function was always present until version 3.3 several months ago, but unfortunately it has now disappeared in the master code. Are there incompatibilities with the JELIX framework or the new Javascript?

**Comment by nboisteault** [comment]
@news24lor Where do you perform those actions ?

**Comment by news24lor** [comment]
Always. This feature is only for vector layer. It's useful because when I select the object, this one is highlighted and there is a lens to zoom to the object. Now all is disappeared. This feature is linked to the "Add geometry to feature response" option in Project properties > QGIS Server. Last master code that worked was in November.

**Comment by nboisteault** [comment]
Thanks for your report @news24lor :)
