### ISSUE TITLE
Lizmap and qGIS Server version

### ISSUE THREAD

**Issue by sylvain258** [3liz/lizmap-web-client#1495]
Hello,

I have this problem. AlwaysData.net, where my website is located, indicate me yesterday, that only qGIS Server 2.4 is available on their servers. I seems me it's a version which doesn't exist any more. 

I install Lizmap on my website, I hadn't difficulties to install it. But after the installation and upload the qGis Project, Lizmap indicates me this message "Service non disponible". Do you think it's because qGis Server version is too old, or the problem isn't here and I have to search somewhere else ?

I have to be sure, because it's for the needs of a placement, and I would have finished this placement when the update by AlwaysData will be ok.

Thank you very much for your help

Sylvain

**Comment by nboisteault** [comment]
Hello,
It is impossible to say where the issue is.
You really should use at least QGIS server 2.18 with LWC 3.2.x or better QGIS server > 3.4 with LWC 3.3.x.

**Comment by sylvain258** [comment]
Except this problem about qgis version, what could be the issue ?

**Comment by Gustry** [comment]
Before opening Lizmap Web Client, check that QGIS Server is up and running correctly by querying with HTTP requests to QGIS Server directly.

QGIS Server 2.4 is definitely too old.

**Comment by rldhont** [comment]
We cannot give guarantees that QGIS Server 2.4 is supported by Lizmap Web Client 3.2.x and upper.

**Comment by laurentj** [comment]
I didn't know that AlwaysData could provide Qgis (it is not indicated into their web site). 

Anyway, installing Qgis Server is not enough. The web server should be configured also, in order to have an endpoint to qgis server, else Lizmap cannot make WMS requests. Did AlwaysData configured the webserver of your container ? 

And of course Lizmap should be well configured : the URL to the WMS endpoint must be indicated.

**Comment by sylvain258** [comment]
I don’t know if alwaysdata has configured their servers like that.
After I create a symbolic link to qgis_mapserv.fcgi as if work with mapserver.
I don’t know if another configuration is necessary.

**Comment by nboisteault** [comment]
Did you compare alwaysdata with https://www.lizmap.com/plans.html ?
