### ISSUE TITLE
When inserting a new point in a layer first time data form is not displayed

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#150]
The first time I insert a new point in a layer, the form to insert the alfanumeric data is not displayed. I have to click on return button and add the point again. Second time and all the next times the form is displayed correctly.

**Comment by rldhont** [comment]
Which version is concerned ?
Does the form is complex or not ?
Did you observe this for one layer or multiple layers ?
Does this issue concern only point ?

**Comment by jaitor1** [comment]
The bug was found in Lizmap Web Application 2.11beta5 running on Windows Server 2012 R2. With a point layer. The form is not very complex: 5 text inputs a calendar and a dropdown selection. 

Let me make some more tests to answer all of your questions, I'll write back soon.

**Comment by jaitor1** [comment]
I made some more tests and I'll answer your questions:

Which version is concerned ? 2.11 Beta 5
Does the form is complex or not ? Not complex.
Did you observe this for one layer or multiple layers? In multiple layers.
Does this issue concern only point ? Teste with a linestring layer and happened too.

The layers are postgis layers. 
I tried with maps in other repos and happens the same. 
I am using Windows Server 2012 R2.

**Comment by rldhont** [comment]
Can you test with the stable version 2.11.0 ? Thanks

**Comment by jaitor1** [comment]
Tested in 2.11.0 Stable right now, with same results.

**Comment by rldhont** [comment]
Fixes in 2.11.3
af8d5fbcbe72faaea4fc110cf2cc3b67f376ddb3
Backported to 2.12 and 3
