### ISSUE TITLE
Printing scale bar using various scales

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1503]
# Problem

When setting up a map template scale bar should always be set to the following
![fixed-scale-w](https://user-images.githubusercontent.com/2510900/74082174-2a95d600-4a60-11ea-9f7b-555822568db5.png)

This will allow a user to be able to use the different scale ranges defined in lizmap for printing without distorting the scale

**Comment by Gustry** [comment]
QGIS Server doesn't respect the minimum/maximum width length?
Is-it a Lizmap issue? Lizmap forward the request to QGIS Server.

**Comment by NyakudyaA** [comment]
@Gustry It's just maybe a tip you could add to the documentation to let users know. But basically it's a configuration issue in the qgis project

**Comment by Gustry** [comment]
It's in the documentation
