### ISSUE TITLE
Filter with form: numeric type not working

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1505]
Apparently it works only with PostgreSQL, not with GPKG.
See also:
https://github.com/3liz/lizmap-web-client/pull/1494#issuecomment-582788719

**Comment by mdouchin** [comment]
Have you tried to give write permission to the folder containing the gpkg file for apache/nginx ?

**Comment by pcav** [comment]
Yes, no change. Thanks for the hint anyway.

**Comment by nboisteault** [comment]
@mdouchin there are errors in console : 
`Invalid Query: Erreur dans la requête (misuse of aggregate function Min() ( SELECT  Min(Min("capacity_m")) AS min, Max(Max("capacity_m")) AS max FROM power WHERE 2>1))
Invalid Query: Erreur dans la requête (misuse of aggregate function Min() ( SELECT  Min(Min("year_of_ca")) AS min, Max(Max("year_of_ca")) AS max FROM power WHERE 2>1))`

**Comment by rldhont** [comment]
@nboisteault do you know why the request contains `Min(Min())` and `Max(Max())` ?

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/filter/classes/filterDatasource.class.php#L278

**Comment by rldhont** [comment]
@nboisteault to fix it, I think I Have found how to fix it:
```
if (count($fields) == 1) {
            $sql.= ' Min("' . $fields[0] . '") AS min,';
            $sql.= ' Max("' . $fields[0] . '") AS max';
} else {
            $sql.= ' Min(Min("' . implode('","', $fields) . '")) AS min,';
            $sql.= ' Max(Max("' . implode('","', $fields) . '")) AS max';
}
```

**Comment by pcav** [comment]
Great, thanks. Any hope of a new point release fixing this?
Cheers.

**Comment by nboisteault** [comment]
Fixed : https://github.com/3liz/lizmap-web-client/commit/d2bb715c8c694b15d187778e14468d497be9a59b
