### ISSUE TITLE
Selectively publish layouts

### ISSUE THREAD

**Issue by gubuntu** [3liz/lizmap-web-client#1506]
### Is your feature request related to a problem? Please describe
It would be really useful at QGIS server properties level or LizMap configuration level to choose which layouts to include or exclude from availability in the web client. 

For example, when a layout is being developed collaboratively we want to withhold it while in draft status, or if a problem appears. 

### Describe the solution you'd like
At the moment the default is to make all layouts public. So the easiest might be to choose which ones to withhold.

**Comment by gioman** [comment]
@gubuntu 

![Screenshot_20200209_114432](https://user-images.githubusercontent.com/1951107/74101426-91cf8b00-4b31-11ea-90d2-cca16ad27dae.png)

?

**Comment by pcav** [comment]
The current option,to choose which ones to exclude from Project Properties, seems functional for me. Of course integrating PP with LM options would be nice, but that's a bigger project

**Comment by gubuntu** [comment]
ah, sorry I missed that in the WMS properties, that'll do the trick thanks

**Comment by Gustry** [comment]
@gubuntu FYI It was mentioned in the documentation in the blue section and I added some screenshots this morning https://docs.lizmap.com/next/en/publish/configuration/print.html
