### ISSUE TITLE
Editing with Postgresql 12

### ISSUE THREAD

**Issue by geographit** [3liz/lizmap-web-client#1507]
### What is the bug?

Editing a layer in a Postgresql 12 database doesn't work.
The following error appears:

> ERROR: column d.adsrc does not exist at character...

The error seems to be related to a change in PostgreSQL 12 described here
[https://github.com/docker-library/postgres/issues/616](url)

### Steps to reproduce the issue

1. Save a layer in PostgreSQL 12/Postgis 3
2. Create a Lizmap project with editing capabilities
3. Try to edit the layer living in PostgreSQL 12

### Expected behavior

The edition hangs.
In browser developer mode,  profiling the request related to the edition function below shows it failing
`GET /index.php/lizmap/edition/createFeature?repository=...` 

PostgreSQL logs show the following:
` ERROR: column d.adsrc does not exist at character...`

### Environment

 - Lizmap version: 3.3.3
 - QGIS Server version: 3.14
 - QGIS Project version: 3
 - OS (Windows, Linux, MacOS, Android…): Debian
 - Browser (Firefox, Chrome…): All
 - PostgreSQL version: 12

**Comment by ygorigor** [comment]
https://github.com/3liz/lizmap-web-client/issues/1453

**Comment by Gustry** [comment]
Duplicated of #1453 and already fixed

**Comment by geographit** [comment]
Thanks awesome!
