### ISSUE TITLE
Possibility to use media files not stored in the media folder

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#151]
I would like to display in lizmap several images and PDFs stored in the local network without having to copy them into the media folder. The files are mantained by third users in their local network location.

By the way, I don't know how to mark the issue as enhancement.

**Comment by rldhont** [comment]
You already can do it, if your medias are available through an URL

You can stored the link in your data or construct it in the popup or QGIS maptooltip.

Take a look at the documentation: http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#how-to-configure-popups

**Comment by jaitor1** [comment]
I created a field with the following URL: file://Z:/022 TURIsmo/1_1.jpg
Then I configured the field as "Image". 
In lizmap I am seeing the text (file://Z:/022 TURIsmo/1_1.jpg) instead of the image. What should the format be?
I checked the documentation and I didn't see a sample "file URL" that works. I will update de documentation with a sample if I make it work.

**Comment by rldhont** [comment]
Hi @jaitor1, *file* protocol is not a **web** protocol. For your "file URL", you have to use a **web** protocol like *http* or *https*.

**Comment by rldhont** [comment]
Hi @jaitor1 did you make it work ?

**Comment by jaitor1** [comment]
Yes, I have to copy each file to another location so it can be accessed via URL though....
I forgot to close the issue.

**Comment by rldhont** [comment]
Thanks @jaitor1 for your time. Can you take a look at the others issues ?

**Comment by jaitor1** [comment]
Sure. I'll give them a look soon. Thanks to you!
