### ISSUE TITLE
Please upgrade jQuery version

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1511]
The jQuery version used by Lizmap is obsolete, unsupported, and may represent a non negligible security risk. Standard penetration tests reports this as a grave vulnerability.
A guide is available for the migration:
https://jquery.com/upgrade-guide/3.0/
together with plugins that should help smooth it out.
I suggest upgrading it ASAP. I'm available for support.
Thanks a lot.

**Comment by laurentj** [comment]
>Standard penetration tests reports this as a grave vulnerability.

Which vulnerabilities ?

**Comment by laurentj** [comment]
We are using many libraries relying on jQuery (jQuery UI, datatables, some plugins etc..). There are also our own code, some plugins for Lizmap. 

So upgrading jQuery is a huge task.

**Comment by pcav** [comment]
I can imagine. Any known vulnerabilities for the old version?

**Comment by nboisteault** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html

There is nothing critical.

**Comment by pcav** [comment]
Thanks a lot.
