### ISSUE TITLE
Failure to render layers  when using geopackage layers

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1512]
# Problem

I have a project with data coming from geopackage and when I try to render the layers I get the following error.

If I login to the qgis server container and execute the following 

```
curl "http://localhost:8080/ows/?map=maceira/Maceira.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities" >out.txt
```

I get the following output.

`Invalid layers for project 'maceira/Maceira.qgs' - strict mode on`

I tried to set up the path to the data source to be relative to the qgis project or to be relative but both methods do not work.

On a standalone QGIS Server the layers render fine without an issues.

**Comment by Gustry** [comment]
> curl "http://localhost:8080/ows/?map=maceira/Maceira.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities" >out.txt

According to your ticket and URL above, this is an issue with QGIS Server with Docker as it works on a standalone QGIS Server and it's not related to Lizmap.

It seems you are using py-qgis-server. When using geopackage, you need to write access in the directory or the layer is invalid.

**Comment by NyakudyaA** [comment]
> > curl "http://localhost:8080/ows/?map=maceira/Maceira.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities" >out.txt
> 
> According to your ticket and URL above, this is an issue with QGIS Server with Docker as it works on a standalone QGIS Server and it's not related to Lizmap.
> 
> It seems you are using py-qgis-server. When using geopackage, you need to write access in the directory or the layer is invalid.

Thanks @Gustry , Will check it upstream with qgis server

**Comment by dmarteau** [comment]
@NyakudyaA FYI geopackage play really badely with multiprocessing and should be avoided on server side.
