### ISSUE TITLE
Missing labels in published maps

### ISSUE THREAD

**Issue by Naturtecnica** [3liz/lizmap-web-client#1513]
Hi, got a problem with text labels.
After setting labels of a point shpfile in Qgis, they are missing in Lizmap map.
I tried to change layer format, I tried to force labels but no goal.
Any suggest?

Thanx.

Lorenzo

Context
QGIS version: 3.4.15
Lizmap version: 3.2.4
OS: windows 10

**Comment by Gustry** [comment]
Are you sure that if you updates your point shapefile (like color or position), it works?

**Comment by Gustry** [comment]
QGIS Server version?

Is-it a QGIS Server 2.18 ?

**Comment by Naturtecnica** [comment]
When I change colors, it works but no labels...
Qgis server version:
![Cattura](https://user-images.githubusercontent.com/16917466/74261074-e83bf580-4cfa-11ea-8c1c-1120afcd177f.JPG)

**Comment by Naturtecnica** [comment]
QGis server:

  Installed: 2.18.17+dfsg-1
  Candidate: 2.18.17+dfsg-1

**Comment by Gustry** [comment]
Your screenshot says : `QGIS Server >= 3.0`
You say : `Installed: 2.18.17+dfsg-1`

There is a mismatch. You will have troubles using Lizmap Web Client.

> QGIS Desktop version: 3.4.15

And using QGIS Desktop version 3.X, you are loosing labels with a QGIS Server 2.X. It's better to use the same QGIS version on both Desktop and Server.

**Comment by Naturtecnica** [comment]
You're right.
My mate updated to 3.4 e now everything works well.
Thanx for your fast support!!!

Lorenzo
