### ISSUE TITLE
Missing editing tool button in the map page with sqlite layers

### ISSUE THREAD

**Issue by Naturtecnica** [3liz/lizmap-web-client#1516]
Hi, got this question.
I creata a qgis project with spatialite db. In DB I put two layers. Then I set layers in project properties as WFS:
![Cattura](https://user-images.githubusercontent.com/16917466/74596807-82ca6a80-5054-11ea-9c9c-5b7d907c7ac5.JPG)

Then i set Lizmap Plugin:
![Cattura2](https://user-images.githubusercontent.com/16917466/74596812-907ff000-5054-11ea-9523-413b2e9c023a.JPG)

Saved project and uploded in FTP, I set all USERS permissions "ON" but there's no "editing tool" activated on the map:
![Cattura3](https://user-images.githubusercontent.com/16917466/74596836-ef456980-5054-11ea-96bd-9b279db75f84.JPG)

Where's my mistake? Any idea?

QGis 3.4.15
Gisserver 3.4.15
windows 10

**Comment by nboisteault** [comment]
Please give us logs in Lizmap administration.

Le dim. 16 févr. 2020 à 00:48, Naturtecnica <notifications@github.com> a
écrit :

**Comment by Gustry** [comment]
> I creata a qgis project with spatialite db.

Is your folder writable? I guess to edit the file. Check permissions.

I tried with a Postgis layer, it's working well.

**Comment by Naturtecnica** [comment]
Folder and files in are writeble.
This is the log:

2020-02-16 11:02:43	93.42.44.60	warning	2020-02-16 11:02:43	[2]	SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search	/var/www/naturmap/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	112

2020-02-16 11:02:43	93.42.44.60	warning	2020-02-16 11:02:43	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fhome%2Fung%2Fftp%2Fdati%2Ftrofie%2Fsalvo%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
	/var/www/naturmap/lizmap/modules/lizmap/classes/lizmapProxy.class.php	240

Thanx for your so fast support!!!

**Comment by shiftybloke** [comment]
Hello, I'm also having the same issue with the edition tool not appearing, the exactly the same logs as @Naturtecnica

**Comment by Naturtecnica** [comment]
Online editing tool does not work with spatialite db.
My tech mate tested any way to fix it but no goal.
We can not use postgis layers just spatialite db.
Please, help us.

**Comment by CpuigGIS** [comment]
Hi everyone,

I got the same issue in my Lizmap project.
Did you finally get a solution to this problem?
Or is this definitely not possible to edit spatialite file in Lizmap?

Thanks a lot for your answers and happy new year to everyone
