### ISSUE TITLE
form filtering - fields with values containning the + character

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1517]
the form filter does not show geometries for fields that contain `+` values, like `REN+RAN`
only the counter works in these cases

thanks for this very useful tool!

**Comment by nboisteault** [comment]
Any message in the console ?

**Comment by josemvm** [comment]
no, no errors in the console...

**Comment by rldhont** [comment]
Encoding/Decoding values error

**Comment by josemvm** [comment]
hi

just to remind you, please can you fix this bug (asap)?

i have a project in which i'm using some arithmetic formulas and this is quite annoying...

thanks again

**Comment by mdouchin** [comment]
Could you provide a simple QGIS project with one layer and the filter configured ? It will help a lot to have a reproductible use case.

**Comment by josemvm** [comment]
@mdouchin please check your mailbox
thanks

**Comment by mdouchin** [comment]
Please try  #1777 if possible in a test environment.
Hum... I should have proposed a PR against release_3_3 and not master...

**Comment by josemvm** [comment]
hi @laurentj the problem remains...

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/pull/1777

**Comment by josemvm** [comment]
@mdouchin gentle ping...

**Comment by nboisteault** [comment]
@josemvm I can't reproduce in Lizmap 3.7. Please reopen issue if needed.
