### ISSUE TITLE
Posiibility to edit the projects thumbnail

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#153]
I would like to edit the thumbnails of the published projects. All of them show this image:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7748045/37907840-ffc1-11e4-8c7a-103fc4347bb6.png)

It would be a good idea to be able to change this image, or, by default, to show an overview of the map instead of that image.

**Comment by pcav** [comment]
Just add an image with the same name as the project, extension .png
And of course RTFM ;)

**Comment by rldhont** [comment]
I'd like to point the documentation but I didn't find this information.
http://docs.3liz.com/en

You can contribute to the doc here: https://github.com/3liz/lizmap-documentation

**Comment by jaitor1** [comment]
I read the entire manual, I didn't find that info so I thought just this couldn't be done. Thanks!

**Comment by jaitor1** [comment]
By the way, where do I have to put the .png image? I tried int he same folder where the project is located and in /media folder relative to the project. Neither of them worked...

**Comment by pcav** [comment]
Same folder, call it project.qgs.png (I know, not so obvious)

**Comment by rldhont** [comment]
Thanks paolo!

@jaitor1 if you want you can update the documentation, we'll merge and publish it.

**Comment by jaitor1** [comment]
@rldhont I'll add it to the documentantion. Thanks for the help!

**Comment by jaitor1** [comment]
added at the end of  en/source/publisher_guide/advanced_lizmap_config.rst. Sorry if I made something wrong, I am new at github.
