### ISSUE TITLE
Print variable in popup lwc whit html+php

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#1531]
hi,
in my project i have a table whit value variable 
in the column tags :
![image](https://user-images.githubusercontent.com/28442671/74756452-d61b0380-5274-11ea-9013-82c6a1dab0d6.png)

In the popup whit LWC i would like print only variable "phone", i tried whit php
but i can't: for example i tried whit the code <?php echo "phone"; ?> 

any help is welcome, thanks

Roberto

**Comment by robibrazze** [comment]
Sorry, the code...	<?php echo "phone"; ?>

**Comment by robibrazze** [comment]
![image](https://user-images.githubusercontent.com/28442671/74846190-5fdbd700-5330-11ea-8a83-2cfcad178e59.png)

**Comment by Gustry** [comment]
You can only write HTML in these popups. It would be a big security issue if some PHP could be executed from a popup.

Your `tags` column is a HStore string. Either you want to use HStore functions in PostgreSQL https://www.postgresql.org/docs/10/hstore.html if your layer is in PostgreSQL or use HStore functions in QGIS : https://gis.stackexchange.com/a/308381/24505

You can make a virtual field if needed.
