### ISSUE TITLE
dataviz - graphic colors not taken by lizmap

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1532]
hi,

the color fields into the lizmap plugin (`color`, `color2` and `colorfield2`) are not taken by lizmap...

according to my experiences, only the field `color` works on `type` `bar`

thanks

**Comment by josemvm** [comment]
customizing collors (`color` and `color2`)

- [x] - scatter
- [ ] - box
- [x] - bar
- [x] - histogram
- [ ] - histogram2d
- [x] - pie (random)
- [x] - polar (**ERROR**):

![imagem](https://user-images.githubusercontent.com/10053874/81167519-3de80d00-8f8d-11ea-8c35-3a5c8d423480.png)


![imagem](https://user-images.githubusercontent.com/10053874/81165565-1479b200-8f8a-11ea-9aa7-1b7ba97085a7.png)

**Comment by Gustry** [comment]
@josemvm Please follow the bug report template so we know your Lizmap QGIS plugin version, your LWC version etc.

**Comment by josemvm** [comment]
@Gustry sorry
lwc 3.3.6
qgis server 2.18

thanks
