### ISSUE TITLE
Layer not visible in Chrome/Chromium

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1533]
### What is the bug?

Someone told me the Lac Léman project on https://demo.lizmap.com/ is not working on Chrome/Chromium.

https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=leman

The attraction layer is not visible.

Firefox on the left, Chromium on the right:

![Capture d’écran de 2020-02-19 11-15-14](https://user-images.githubusercontent.com/1609292/74824966-5e4ae880-5309-11ea-8bf6-7227a63dc0b7.png)

### Expected behavior

Chrome is quite used. It would be nice to have this project working on this browser.

I'm not sure if it's a version problem, Lizmap web client problem.

### Environment

 - Lizmap version: demo.lizmap.com
 - QGIS Server version: demo.lizmap.com
 - QGIS Project version: demo.lizmap.com
 - OS (Windows, Linux, MacOS, Android…): Windows/Ubuntu
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by nboisteault** [comment]
Note to myself : 
"Attractions" layer (4 index) is behind "Fond de carte" (0 index). It is odd because : 
```javascript
lizMap.map.layers[0].getZIndex()
"325"
lizMap.map.layers[4].getZIndex()
"345"
```
If I set an index >= 356 for "Attractions" it is ok : 
```javascript
lizMap.map.layers[4].setZIndex(356)
```

**Comment by rldhont** [comment]
It seems to be a regression, we already have to fix something like that in Chrome!

**Comment by Gustry** [comment]
It works fine on chromium.
@nboisteault Can we close ?
