### ISSUE TITLE
SERVICE NON DISPONIBLE!

### ISSUE THREAD

**Issue by claudiogeop** [3liz/lizmap-web-client#1535]
Hello again, I have this constant error in my project, it appears on the screen but when I click the message SERVICE NON DISPONIBLE always appears!

lizmap/var/log/errors.log:

[errors.log](https://github.com/3liz/lizmap-web-client/files/4226757/errors.log)

![01](https://user-images.githubusercontent.com/61161982/74865238-98c77c00-532f-11ea-9546-73f6ac9f943b.PNG)
![02](https://user-images.githubusercontent.com/61161982/74865247-9a913f80-532f-11ea-83c8-e5674235bc94.PNG)

**Comment by nboisteault** [comment]
Please first check that QGIS Server is correctly working.

**Comment by claudiogeop** [comment]
Can you solve this?

![qgis server](https://user-images.githubusercontent.com/61161982/74870844-2e1b3e00-5339-11ea-975c-398142d444f9.PNG)

**Comment by gioman** [comment]
> Can you solve this?

@claudiogeop there isn't anything to solve. That error message means that QGIS Server is working fine (the request via URL is incomplete, so the error).

**Comment by claudiogeop** [comment]
I'm sorry, I miscalculated, how to solve the problem YOU ARE NOT AVAILABLE!
Is the problem with the qgs file configuration?

**Comment by Gustry** [comment]
QGIS Server is working in your case.

You need to check your layers, one of your layer is invalid in QGIS Server context. Where your layers come from?

**Comment by claudiogeop** [comment]
I also thought about this situation, I used a base in the GeoPackage format and then I changed it to shapefile ...
And it still didn't work!
Not to mention that I can't activate the demos.
Did anyone have difficulties too?

**Comment by Gustry** [comment]
Project properties -> QGIS Server, any warning from the "Test configuration"?

**Comment by rldhont** [comment]
Can you take a look at the qgis-server log ?

**Comment by claudiogeop** [comment]
I'm sorry for the delay, where can I access the qgiserver error log?
