### ISSUE TITLE
Do not take care of layer's key ""

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1538]
### What is the bug?
For some PostgreSQL/PostGIS layer, the datasource contains `key='""'`.

In this case no primary key is defined. Lizmap has to avoid it like `key=''`

### Expected behavior
Lizmap has to consider `key='""'` has no primary key defined.

### Environment

 - Lizmap version: 3.3.3
 - QGIS Server version: 3.4.13
 - QGIS Project version: 3.4.9
 - OS (Windows, Linux, MacOS, Android…):  Windows for desktop, Debian for server

**Comment by nboisteault** [comment]
@rldhont how to reproduce this issue?

**Comment by rldhont** [comment]
@nboisteault with a view.

**Comment by nboisteault** [comment]
Note : https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L160

**Comment by rldhont** [comment]
add after https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L252
```php
if ( $ds['key'] === '""' ) $ds['key'] = '';
```

**Comment by nboisteault** [comment]
@rldhont if I add a view as a layer in DB manager I get `_uid_` as an id. If I add a view with other methods I also have an id.
How do you do to have an empty id ?

**Comment by rldhont** [comment]
@nboisteault QGIS probably fix it but can you add this check in php ?

**Comment by rldhont** [comment]
@nboisteault have you use DB Manager to add a request ? I think you can create a request with no primary key defined.

**Comment by nboisteault** [comment]
> @nboisteault have you use DB Manager to add a request ? I think you can create a request with no primary key defined.

It automatically adds `_uid_` as said in previous comment.

**Comment by nboisteault** [comment]
> @nboisteault QGIS probably fix it but can you add this check in php ?

I can but we might add some checks elsewhere as we should never be in this situation.

**Comment by rldhont** [comment]
The other checks already exist.
