### ISSUE TITLE
Locate by layer, dropdown list is empty

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#154]
I active the locate by layer option. 

![sin titulo2](https://cloud.githubusercontent.com/assets/12136796/7771498/16715c6a-0098-11e5-9e26-60dd3e2f193d.png)

As explained in the documentantion, I checked that WFS is activated for the layer. In fact it is, because I can edit the layer.

But in the dropdown list I am not seeing anything. I tried with other fields (both numeric and text fields) and with other layers too and always happens the same to me. Dropdown list is empty.

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7771506/203b4594-0098-11e5-8b09-80839111bc53.png)

My lizmap is running on Windows Server 2012 R2. We think that this will be a very useful feature for us.

**Comment by rldhont** [comment]
Lizmap does not use WFS for edition. Check in the Project Properties that the layer is publushed in WFS.

**Comment by jaitor1** [comment]
Yes it is published in WFS:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7930332/c4888c84-0907-11e5-9bb1-1c390cd7aee5.png)

**Comment by rldhont** [comment]
Can you test the WFS GetCapabilities in QGIS ?

**Comment by jaitor1** [comment]
I suppose this is the result of the WFS getcapabilities. If you need any other test, please, let me know:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7931288/b73d2e56-090f-11e5-9922-fdfb4fcaa7c5.png)

If I insert http://localhost/qgis/qgis_mapserv.fcgi.exe?&SERVICE=WFS&REQUEST=GetCapabilities in a browser I get a XML with the same layers.

**Comment by rldhont** [comment]
QGIS-Server get an extra parameter which is map. This parameter has to be a path to a QGIS project. Can you test the URL with a map parameter ?

But I think that Locate by Layer does not work because the name of your layers has parenthesis. I suggest to you to set name without parenthesis, space and accent. Use the title properties for complex name.

**Comment by jaitor1** [comment]
With the map parameter I get the exact same result.

I simplified the names of the layers and used Title property in lizmap plugin for complex naming but the result is the same, nothing is shown in my combobox

**Comment by geoek** [comment]
I identified the same behaviour and i have observe this : 
- if you rename your layer in qgis, it may cause this problem (even without space or special character... strange...).
- to change the name of the layer, use the field 'Title' of Metadata area (in Lizmap plugin, or in Server OWS).

That's all and sorry for my english ;)

**Comment by jaitor1** [comment]
You are right geoek.

**Comment by geoek** [comment]
Thanks !
So, I think it is a bug that appears when the "rename Layer" fonction of Qgis is used. Perhaps it will be corriged in a next version of Lizmap.

**Comment by rldhont** [comment]
Hi @geoek and @jaitor1,

If I well understand your comments, it's probably a 3liz/lizmap-plugin issue. Can you open an issue in this project ?

**Comment by rldhont** [comment]
Reopen the issue if needed
