### ISSUE TITLE
Atlas - The popup does not appear

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1541]
I have two projects that use the atlas but on one of them the popup is not displayed (see picture below)
I only have the message "SUP".

### Screenshots and logs
<img width="746" alt="Capture d’écran 2020-02-22 à 12 14 36" src="https://user-images.githubusercontent.com/7761073/75092192-660ac700-556d-11ea-8b28-568c965a4c79.png">

### Environment

 - Lizmap version: 3.3.4
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4.15
 - OS (Windows, Linux, MacOS, Android…): MacOS
 - Browser (Firefox, Chrome…): Safari, Firefox

**Comment by mdouchin** [comment]
Do you have a maptip configured for this layer in QGIS vector layer properties ? What is the option for the popup: auto, lizmap or qgis ?

**Comment by igeofr** [comment]
Hi @mdouchin,
I don't have a maptip configured for this layer and the popup is based on QGIS.

**Comment by mdouchin** [comment]
"QGIS" popup mode is based on the layer Maptip, so you either need to write the popup template in the QGIS map tip, or change mode
https://docs.lizmap.com/current/fr/publish/advanced_lizmap_config.html#qgis-popup

**Comment by igeofr** [comment]
Thank you, the problem comes indeed from the configuration of the QGIS Maptip.
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/7761073/75095338-97928b00-558b-11ea-889c-2314fa6a1258.png">

But what's surprising is that I don't have a problem with the main popup... only in the atlas.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/7761073/75095306-57cba380-558b-11ea-8f19-010f99761c66.png">
