### ISSUE TITLE
Form filter, max date is compulsory

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1542]
## Description

@mdouchin Can you confirm that Max date is compulsory in Filter by form? (even if it's the same field, but both are compulsory)

## Context
* QGIS version: 3.4.15
* Lizmap version: Master
* OS: Ubuntu

**Comment by nboisteault** [comment]
@Gustry @mdouchin Is it compulsory?

**Comment by mdouchin** [comment]
It is

**Comment by nboisteault** [comment]
@Gustry @mdouchin does this mean we should force user to select the 'max date' field or it should be written in config?
![image](https://user-images.githubusercontent.com/2145040/95847939-a8c41e00-0d4d-11eb-819b-61c80b3e560f.png)
