### ISSUE TITLE
Multiple popup report incorrect info

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1543]
When displaying popups for >1 element, when clicking on a tab for one element the second one is updated with the info from the first element.
See attached screenshots.
To reproduce it:
* click to show two popups
* click on the second tab of the first plugin (in the example, UBICAZIONE)
* click on the same tab for the second popup
Result: data from the first tab are displayed.
Expected: data from the second tab should be displayed.
Forms are generated using the `Copy from attribute form` function of the plugin.
Lizmap 3.3.4, QGIS 3.4 and 3.10.

**Comment by pcav** [comment]
![Schermata del 2020-02-24 12-26-17](https://user-images.githubusercontent.com/691842/75149046-5c19cd00-5701-11ea-81f7-9acfcc92d6bd.png)
![Schermata del 2020-02-24 12-25-37](https://user-images.githubusercontent.com/691842/75149049-5d4afa00-5701-11ea-954c-6eb2a3267dbe.png)

**Comment by rldhont** [comment]
@pcav can you provide the QGIS tooltip content ? Which will be translated to popup.

**Comment by pcav** [comment]
<style>
    div.popup_lizmap_dd {
        margin: 2px;
    }
    div.popup_lizmap_dd div {
        padding: 5px;
    }
    div.popup_lizmap_dd div.tab-content{
        border: 1px solid rgba(150,150,150,0.5);
    }
    div.popup_lizmap_dd ul.nav.nav-tabs li a {
        border: 1px solid rgba(150,150,150,0.5);
        border-bottom: none;
        color: grey;
    }
    div.popup_lizmap_dd ul.nav.nav-tabs li.active a {
        color: #333333;
    }
    div.popup_lizmap_dd div.tab-content div.tab-pane div {
        border: 1px solid rgba(150,150,150,0.5);
        border-radius: 5px;
        background-color: rgba(150,150,150,0.5);
    }
    div.popup_lizmap_dd div.tab-content div.tab-pane div.field,
    div.popup_lizmap_dd div.field,
    div.popup_lizmap_dd div.tab-content div.field {
        background-color: white;
        border: 1px solid white;
    }
    div.popup_lizmap_dd div.tab-content legend {
        font-weight: bold;
        font-size: 1em !important;
        color: #333333;
        border-bottom: none;
        margin-top: 15px !important;
    }

</style>

<div class="container popup_lizmap_dd" style="width:100%;">
<ul class="nav nav-tabs">

    <li class="active"><a href="#popup_dd_NODO_ACQUEDOTTO" data-toggle="tab">NODO ACQUEDOTTO</a></li>

    <li class=""><a href="#popup_dd_UBICAZIONE" data-toggle="tab">UBICAZIONE</a></li>

    <li class=""><a href="#popup_dd_QUOTE" data-toggle="tab">QUOTE</a></li>

    <li class=""><a href="#popup_dd_DATI_ACCESSORI" data-toggle="tab">DATI ACCESSORI</a></li>

    <li class=""><a href="#popup_dd_ALLEGATI" data-toggle="tab">ALLEGATI</a></li>
</ul>
<div class="tab-content">
  <div id="popup_dd_NODO_ACQUEDOTTO" class="tab-pane active">
    
            [% CASE
                WHEN "elemento" IS NOT NULL OR trim("elemento") != ''
                THEN concat(
                    '<p>', '<b>ELEMENTO</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('Ra_Alimentatore=>Alimentatore, Ra_Alimentatore_Tele=>Alimentatore Telecontrollato, Ra_Anodo_Magnesio=>Anodo al Magnesio, Ra_Cartello_Segnalatore=>Cartello Segnalatore, Ra_Casa_Acqua=>Casa sell’Acqua, Ra_Cont_Elettrom=>Contatore Elettromagnetico, Ra_Cont_Elettrom_Coni=>Contatore Elettromagnetico con Coni, Ra_Cont_Woltman=>Contatore Woltman, Ra_Dispersore_P=>Dispersore di Profondità, Ra_Dispersore_S=>Dispersore in Superficie, Ra_Flangia=>Flangia, Ra_Fontanella=>Fontanella, Ra_Giunto_Transizione=>Giunto di Transizione, Ra_Giunto_Dielettr=>Giunto Dielettrico, Ra_Idra_Sopra=>Idrante Soprasuolo, Ra_Idra_Sotto=>Idrante Sottosuolo, Ra_Impianto_Rilancio=>Impianto di Rilancio, ’Ra_Impianto_Sollevamento=>Impianto di Sollevamento, Ra_Manicotto=>Manicotto, Ra_Pal_Conc_Ricerca_Tubo=>Palina Conchiglia Ricerca Tubo, Ra_Impianto_Potabilizzazione=>Potabilizzatore, Ra_Pozzetto=>Pozzetto, Ra_Pozzo=>Pozzo, Ra_Pozzo_Piezo=>Pozzo Piezometrico, Ra_P_Misura=>Punto Misura, Ra_Riduttore=>Riduttore, Ra_Riduzione=>Riduzione, Ra_Saracinesca=>Saracinesca, Ra_Scarico=>Scarico, Ra_Scarico_Automatico=>Scarico Automatico, Ra_Serbatoio_Pensile=>Serbatoio Pensile, Ra_Sfiato=>Sfiato, Ra_Strettoio=>Strettoio, Ra_Tappo=>Tappo, Ra_Valvola_Non_Ritorno=>Valvola di Non Ritorno, Ra_Vasca_Terra=>Vasca a Terra, Ra_Vasca_Reflue=>Vasca Acque Reflue'),
                        "elemento"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "tipo" IS NOT NULL OR trim("tipo") != ''
                THEN concat(
                    '<p>', '<b>TIPO</b>',
                    '<div class="field">', "tipo", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "diametro" IS NOT NULL OR trim("diametro") != ''
                THEN concat(
                    '<p>', '<b>DIAMETRO INTERNO</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('32=>32, 40=>40, 50=>50, 60=>60, 63=>63, 65=>65, 75=>75, 80=>80, 90=>90, 100=>100, 110=>110, 125=>125, 150=>150, 160=>160, 200=>200, 250=>250, 300=>300, 350=>350, 400=>400, 500=>500, 600=>600, DE50=>DE50, DE63=>DE63, DN20=>DN20, DN25=>DN25, DN30=>DN30, DN40=>DN40, DN50=>DN50, DN60=>DN60, DN65=>DN65, DN75=>DN75, DN80=>DN80, DN100=>DN100, DN150=>DN150, DN200=>DN200, ALTRO=>ALTRO'),
                        "diametro"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "materiale" IS NOT NULL OR trim("materiale") != ''
                THEN concat(
                    '<p>', '<b>MATERIALE</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('ACCIAO=>ACCIAIO, GHISA=>GHISA, GHISA GRIGIA=>GHISA GRIGIA, GHISA SFEROIDALE=>GHISA SFEROIDALE, PEAD=>PEAD, PVC=>PVC'),
                        "materiale"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "nome_rete" IS NOT NULL OR trim("nome_rete") != ''
                THEN concat(
                    '<p>', '<b>RETE DI</b>',
                    '<div class="field">', "nome_rete", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "cod_rete" IS NOT NULL OR trim("cod_rete") != ''
                THEN concat(
                    '<p>', '<b>CODICE RETE</b>',
                    '<div class="field">', "cod_rete", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "note" IS NOT NULL OR trim("note") != ''
                THEN concat(
                    '<p>', '<b>NOTE</b>',
                    '<div class="field">', "note", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
  </div>

  <div id="popup_dd_UBICAZIONE" class="tab-pane ">
    
            [% CASE
                WHEN "comune" IS NOT NULL OR trim("comune") != ''
                THEN concat(
                    '<p>', '<b>COMUNE</b>',
                    '<div class="field">', "comune", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "zona" IS NOT NULL OR trim("zona") != ''
                THEN concat(
                    '<p>', '<b>ZONA</b>',
                    '<div class="field">', "zona", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "toponimo" IS NOT NULL OR trim("toponimo") != ''
                THEN concat(
                    '<p>', '<b>VIA</b>',
                    '<div class="field">', "toponimo", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "pos_stra" IS NOT NULL OR trim("pos_stra") != ''
                THEN concat(
                    '<p>', '<b>POSIZIONE CONDOTTA RISPETTO ALLA STRADA</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('ASSE STRADA=>ASSE STRADA, ATTRAVERSAMENTO=>ATTRAVERSAMENTO, BANCHINA=>BANCHINA, CARREGGIATA CENTRALE=>CARREGGIATA CENTRALE, CARREGGIATA DISPARI=>CARREGGIATA DISPARI, CARREGGIATA PARI=>CARREGGIATA PARI, CARREGGIATA E MARCIAPIEDE DISPARI=>CARREGGIATA E MARCIAPIEDE DISPARI, CARREGGIATA E MARCIAPIEDE PARI=>CARREGGIATA E MARCIAPIEDE PARI, MARCIAPIEDE DISPARI=>MARCIAPIEDE DISPARI, MARCIAPIEDE PARI=>MARCIAPIEDE PARI, PARCHEGGI=>PARCHEGGI, PARTERRE=>PARTERRE, PARTERRE E MARCIAPIEDI=>PARTERRE E MARCIAPIEDI, TERRENO=>TERRENO, ALTRO=>ALTRO'),
                        "pos_stra"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
  </div>

  <div id="popup_dd_QUOTE" class="tab-pane ">
    
            [% CASE
                WHEN "quota_alti" IS NOT NULL OR trim("quota_alti") != ''
                THEN concat(
                    '<p>', '<b>QUOTA TERRENO ASSOLUTA (mt. s.l.m.)</b>',
                    '<div class="field">', "quota_alti", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
  </div>

  <div id="popup_dd_DATI_ACCESSORI" class="tab-pane ">
    
            [% CASE
                WHEN "nome" IS NOT NULL OR trim("nome") != ''
                THEN concat(
                    '<p>', '<b>NOME</b>',
                    '<div class="field">', "nome", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "utenza" IS NOT NULL OR trim("utenza") != ''
                THEN concat(
                    '<p>', '<b>TIPOLOGIA DI UTRENZA ALLACCIATA</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('DOMESTICA=>DOMESTICA, INDUSTRIALE=>INDUSTRIALE, AGRICOLA=>AGRICOLA, MISTA=>MISTA, ALTRO=>ALTRO'),
                        "utenza"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "stato" IS NOT NULL OR trim("stato") != ''
                THEN concat(
                    '<p>', '<b>STATO DI ESERCIZIO</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('IN ESERCIZIO=>IN ESERCIZIO, NON IN EASERCIZIO=>NON IN EASERCIZIO, IN DISUSO=>IN DISUSO, DEMOLITO - NON PIU’ ESISTENTE=>DEMOLITO - NON PIU’ ESISTENTE, IN PROGETTO=>IN PROGETTO, IN COSTRUZIONE=>IN COSTRUZIONE, ALTRO=>ALTRO'),
                        "stato"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "condizioni" IS NOT NULL OR trim("condizioni") != ''
                THEN concat(
                    '<p>', '<b>CONDIZIONI DI USURA</b>',
                    '<div class="field">', 
                    map_get(
                        hstore_to_map('BUONE=>BUONE, SUFFICIENTI=>SUFFICIENTI, SCARSE=>SCARSE, PESSIME=>PESSIME'),
                        "condizioni"
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "potenza" IS NOT NULL OR trim("potenza") != ''
                THEN concat(
                    '<p>', '<b>POTENZA Kw (solo per impianti di sollevamento)</b>',
                    '<div class="field">', "potenza", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "gestione" IS NOT NULL OR trim("gestione") != ''
                THEN concat(
                    '<p>', '<b>ENTE GESTORE</b>',
                    '<div class="field">', "gestione", '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
  </div>

  <div id="popup_dd_ALLEGATI" class="tab-pane ">
    
            [% CASE
                WHEN "a_foto" IS NOT NULL OR trim("a_foto") != ''
                THEN concat(
                    '<p>', '<b>FOTO</b>',
                    '<div class="field">', 
                        concat(
                            '<a href="','media/ra/',
                            "a_foto",
                            '" target="_blank">',
                            '
                            <img src="',
                            "a_foto",
                            '" width="100%" title="FOTO">',
                            '
                            </a>'
                        )
                    , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "a_raster" IS NOT NULL OR trim("a_raster") != ''
                THEN concat(
                    '<p>', '<b>PLANIMETRIA</b>',
                    '<div class="field">', 
                    concat(
                        '<a href="','media/ra/',
                        "a_raster",
                        '" target="_blank">PLANIMETRIA</a>'
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "a_particol" IS NOT NULL OR trim("a_particol") != ''
                THEN concat(
                    '<p>', '<b>PARTICOLARI</b>',
                    '<div class="field">', 
                    concat(
                        '<a href="','media/ra/',
                        "a_particol",
                        '" target="_blank">PARTICOLARI</a>'
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "a_slide" IS NOT NULL OR trim("a_slide") != ''
                THEN concat(
                    '<p>', '<b>SLIDE</b>',
                    '<div class="field">', 
                    concat(
                        '<a href="','media/ra/',
                        "a_slide",
                        '" target="_blank">SLIDE</a>'
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
    
            [% CASE
                WHEN "a_scheda" IS NOT NULL OR trim("a_scheda") != ''
                THEN concat(
                    '<p>', '<b>SCHEDA TECNICA</b>',
                    '<div class="field">', 
                    concat(
                        '<a href="','media/ra/',
                        "a_scheda",
                        '" target="_blank">SCHEDA TECNICA</a>'
                    )
                , '</div>',
                    '</p>'
                )
                ELSE ''
            END %]
            
  </div>
</div>
</div>

**Comment by pcav** [comment]
merci
