### ISSUE TITLE
How to use Lizmap variables in other contexts

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1547]
e.g. if one wants to add to a print layout the name of the Lizmap user who did the printing, in analogy to what it is possible for desktop printing, where we have the variables @user_full_name etc.

**Comment by rldhont** [comment]
This has to be done with a plugin server.

**Comment by pcav** [comment]
Thanks for the clarification; I believe it is a useful feature

**Comment by Gustry** [comment]
Very late answer @pcav it's possible to print current user in a PDF.
https://docs.lizmap.com/current/en/publish/configuration/expression.html#project-level
