### ISSUE TITLE
lizmapProject.class.php

### ISSUE THREAD

**Issue by t0xycus** [3liz/lizmap-web-client#1554]
Bonjour à tous, 

lorsque je mets à jour le client via la BranchMaster (3.4)
le chargement d'une carte avec un calque éditable, ça mouline sans cesse sur le logo chargement lizmap.

Après de nombreux tests, le coupable est désigné lizmapProject.class.php (/lizmap/modules/lizmap/classes).

Lorsque je le remplace par celui de la 3.3, plus de soucis tout fonctionne comme avant. 

Une idée ? 

config : 
- postgresql 12
- ubuntu 18.04
- qgis 3.4)

**Comment by Gustry** [comment]
Est-ce que vous avez lu https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#get-the-source ?

Les fichiers sources de lizmap 3.4 ne sont plus utilisables directement.

**Comment by t0xycus** [comment]
Non, je n'avais pas vu ce changement, ça pourrai venir de là ?

**Comment by Gustry** [comment]
D'après le lien  https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#get-the-source 

> Since Lizmap 3.4, the sources in the repository are not usable directly.

Donc si tu utilises GIT en passant sur la branche 3.4, oui, cela ne marche pas.

Il y a des packages de la 3.4 : https://packages.3liz.org/pub/lizmap/unstable/3.4/

je vais installer la 3.4 également à partir de git

**Comment by t0xycus** [comment]
Ah merci j'avais pas vu le lien vers la version déjà build ... :/

**Comment by t0xycus** [comment]
Avant que je casse tout, j'ai essayé de remplacer seulement le fichier incriminé "lizmapProject.class.php", 
ce qui me donne toujours la même erreur le logo de chargement qui mouline sans rien. 

Bien sûr quand je remet la version précédente du fichier, tout fonctionne parfaitement. 

Je n'ai pas relancé une install et je n'ai pas encore remplacé tous les fichiers.

**Comment by t0xycus** [comment]
AHHHHHHH yes, c'est bon quand ça fonctionne !!!!

Donc effectivement, avec ce zip aucuns problèmes, quel plaisir de voir toutes les petites amélioration de cette version. enfin la possibilité de modifier la page d'acceuil via un éditeur (manque juste le bouton code source dans l'éditeur html).

Merci pour lizmap logiciel au top !!!! 👯‍♂

**Comment by nboisteault** [comment]
Bonjour et merci pour votre retour.
Concernant l'éditeur HTML, nous utilisons ckeditor 5 qui n'intègre pas cette fonction.
