### ISSUE TITLE
Qgis server 3.10.3 issues

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#1555]
Since Ubuntu 16.04 -> 18.04 upgrade and Qgis server 3.4 -> 3.10 upgrade, I have stange issues with Lizmap and Qgis Server.

- With a 3.4.3 project on 3.10.3 server:  When any group as layer is checked or when no layer is checked, layers printed are always default visible (checked) layers of the Qgis project ! When layers checked aren't a "group as layer", the print export is correct.

- Project saved with Qgis 3.10 are not showned correctly (endless loading) : 
Qgis server returns `<ServiceException code="Error"> Server Error ! </ServiceException>`
Lizmap logs show: `failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/var/www/lizmap_3.3.4/lizmap/modules/lizmap/classes/lizmapProxy.class.php	240`
Qgis server logs show: `mod_fcgid: error reading data, FastCGI server closed connection` and `
End of script output before headers: qgis_mapserv.fcgi`

Thanks for your help ;-)

 - Lizmap version: 3.3.4 (or 3.3.2)
 - QGIS Server version: 3.10.3
 - QGIS Project version: 3.10.3
 - OS :  Ubuntu 18.04

**Comment by gisgogo** [comment]
Hi, the same problem.

**Comment by nboisteault** [comment]
@loic74 : For the first point about print, does it work as expected when you update the 3.4 project to 3.10 ?

**Comment by loic74** [comment]
@nboisteault Don't know. 3.10 projects just don't work (2d point)

**Comment by rldhont** [comment]
@loic74 can you find the QGIS Server log and provide the log for only 1 WMS GetCapabilities request?

**Comment by gisgogo** [comment]
Hi, the same problem. After update qgis server 3.4. to 3.10. version, Layer at group + normal layer not print group layer. Only normal layer. When I off normal layer, group layer is printable.
Lizmap version: 3.3.4 (or 3.4.0.pre)
QGIS Server version: 3.10.3
QGIS Project version: 3.4. and 3.10.3
OS : Ubuntu 18.04
You can test it on my project
https://gisland.eu/mapserver/index.php/view/map/?repository=chudenice&project=pasport_komunikaci
Thanks, Michal

**Comment by loic74** [comment]
> @loic74 can you find the QGIS Server log and provide the log for only 1 WMS GetCapabilities request?

Sorry, but I had to restore a backup because it was a production server. Since then, I was able to get a test server. So I installed Qgis Server 3.10.3, with Nginx this time, and the latest version of Lizmap. I saved the project with the latest version of the plugin, and I still have the same problem: the printed layers are not correct (as in my previous post).

**Comment by rldhont** [comment]
It is QGIS Server issue. 

Can you open an issue in https://github.com/qgis/QGIS/ then referenced it here ?
I will assigned it to me.

Thanks

**Comment by loic74** [comment]
@rldhont 

Of course: https://github.com/qgis/QGIS/issues/35107

Thanks

**Comment by rldhont** [comment]
Fix by https://github.com/qgis/QGIS/pull/37425 in QGIS Server version 3.10.8. This version will be available the July 17th 2020
