### ISSUE TITLE
build lizmap from github - not clear

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1556]
> If you get the source code directly from git, you have to build Lizmap

with `git clone https://github.com/3liz/lizmap-web-client.git` i get a folder named `lizmap-web-client`

- [X] - install `Composer`, `Make `and `zip`
- [ ] -     run `make package`  **??? package ???**
- [ ] -     you'll have a package `build/lizmap-web-client-X.Y.zip`

thanks in advanced for your help

**Comment by Gustry** [comment]
@josemvm Can you explain what is the problem?
Indeed, when you are in `lizmap-web-client`, you type in a terminal `make package`.

**Comment by josemvm** [comment]
@Gustry thanks

- [X] - install `Composer`, `Make `and `zip`
- [X] - run `make package`
- [ ] -     you'll have a package `build/lizmap-web-client-X.Y.zip`

i have a packages:

lizmapdemo-module-X.Y.zip
lizmap-web-client-X.Y.Z-pre.zip
lizmap_web_client.zip

and i have a folders:
lizmapdemo
lizmap_web_client

@Gustry can you clarify the differences between zip files?

thanks

**Comment by Gustry** [comment]
@josemvm Please update your lizmap master branch. The readme has been improved and the Makefile has been fixed for `make package` command.

**Comment by josemvm** [comment]
@Gustry thanks for clarifying and thanks for all your improvements in the lizmap documentation!

**Comment by josemvm** [comment]
hi @Gustry 

i'm trying to build a new package from https://github.com/3liz/lizmap-web-client.git
this is the result when i run the `make packape` command:

```rm -rf build
rm -f docker/factory.manifest docker/lizmap_web_client.zip
LIZMAP_VERSION=3.4.0-pre
LTR=
MAJOR_VERSION=3
MINOR_VERSION=4
PATCH_VERSION=0
STABLE_VERSION=3.4.0
SHORT_VERSION=3.4
SHORT_VERSION_NAME=3_4
DOCKER_MANIFEST_VERSION=3.4-dev
SAAS_LZMPACK_VERSION=
PACKAGE_NAME=lizmap-web-client-3.4.0-pre
SAAS_PACKAGE=lizmap_web_client_3_4
GENERIC_PACKAGE_PATH=build/lizmap_web_client.zip
BRANCH=master
BUILDID=202003260925
COMMITID=75de4a38
composer update --working-dir=lizmap/ --prefer-dist --no-ansi --no-interaction --ignore-platform-reqs --no-dev --no-suggest --no-prog                                                                ress
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Writing lock file
Generating autoload files
cd assets/ && npm install
/bin/sh: 1: npm: not found
Makefile:107: recipe for target 'build' failed
make: *** [build] Error 127
```

**Comment by Gustry** [comment]
```
/bin/sh: 1: npm: not found
```
So install `npm`. It's written in the readme https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#building-a-zip-with-javascript-and-php

**Comment by josemvm** [comment]
@Gustry of course!
thanks
