### ISSUE TITLE
Search box is overlapping landing HTML

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1558]
### What is the bug?

* Setup some content on the landing page, **on** the first line (without a blank line)
* Go back to the landing page

![Capture d’écran de 2020-03-09 17-20-43](https://user-images.githubusercontent.com/1609292/76234950-af743b00-622a-11ea-9321-1b8d97a9b057.png)

To avoid this bug, the user need to put
```html
<!-- Empty line -->
<p>Hello</p>
```

### Environment

 - Lizmap version: 3.4 Master
 - QGIS Server version: 3.13
 - QGIS Project version: Any
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 19.10
 - Browser (Firefox, Chrome…): Firefox

**Comment by nboisteault** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/commit/4e623274243c11093a1242536f0aea6c777fd609
