### ISSUE TITLE
Missing qgis/edition and qgis/media directories on a new install

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1561]
On a new install (git clone https://github.com/3liz/lizmap-web-client.git), when using the command line 
`lizmap/install/set_rights.sh`
I have an error message related to missing directories :
`chown: impossible d'accéder à 'lizmap/install/../install/qgis/edition': Aucun fichier ou dossier de ce type
chown: impossible d'accéder à 'lizmap/install/../install/qgis/media/upload': Aucun fichier ou dossier de ce type
chmod: impossible d'accéder à 'lizmap/install/../install/qgis/edition': Aucun fichier ou dossier de ce type
chmod: impossible d'accéder à 'lizmap/install/../install/qgis/media/upload': Aucun fichier ou dossier de ce type
`
Are these directories been removed ?

**Comment by Gustry** [comment]
In which directory are you?
Which branch are you using? If you are using master, did you read https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#get-the-source

**Comment by nboisteault** [comment]
Those directories have been moved. We have to fix the script.

**Comment by laurentj** [comment]
I fix the issue in the script : f894b7e774bda7740980f09908bb4eb71151e8f7
