### ISSUE TITLE
How to integrate the split feature in lizmap 3.3?

### ISSUE THREAD

**Issue by geographit** [3liz/lizmap-web-client#1562]
Hi,

Sorry if I am duplicating this. I was unsure if commenting on a closed issue would be noticed, so I thought I would ask the question here.

I have tried integrating the files from #1336 and #1351 in Lizmap 3.3 .
I can see the Split functionality when editing, however when I split a feature, one part gets deleted.

For example if I split a polygon into 2 pieces I can see in Postgresql log that the biggest part of the split feature gets updated while the other one is an INSERT statement with the same ID which gets rejected. Hence the smallest piece become "deleted".

```
LOG:  statement:  INSERT INTO "webapp"."00_test_polygon" ("id", "geom" ) VALUES (1, ST_GeomFromText('POLYGON((12942892.827410802 -3766037.86237783,12943128.0256651 -3767249.13338755,12942577.357415842 -3767435.3888248047,12942498.842978436 -3765921.8049481474,12942892.827410802 -3766037.86237783))', 3857) )  RETURNING "id";
ERROR:  duplicate key value violates unique constraint "00_test_polygon_pkey"
DETAIL:  Key (id)=(1) already exists.
STATEMENT:   INSERT INTO "webapp"."00_test_polygon" ("id", "geom" ) VALUES (1, ST_GeomFromText('POLYGON((12942892.827410802 -3766037.86237783,12943128.0256651 -3767249.13338755,12942577.357415842 -3767435.3888248047,12942498.842978436 -3765921.8049481474,12942892.827410802 -3766037.86237783))', 3857) )  RETURNING "id";
```

Is there anything I might have missed?

Thanks, this is a great feature!

**Comment by laurentj** [comment]
Don't try to backport patchs. It is difficult to answer to you if the issue is because you didn't apply all needed patches, or if there is a real issue.

Please, try Lizmap 3.4-pre. And tell us if your issue still exists.

**Comment by geographit** [comment]
Thank you @laurentj for your reply.

I have tried the current 3.4-pre with postgresql 9.6. 

Here is what I observe when splitting the following features with the split tool:

- Polygon: the polygon is divided. When saving one part of the polygon disappear
- Line: the line is divided. When saving one part of the line disappear
- Multiline: the line is divided. When saving one part of the line disappear
-Multipolygon: the polygon is not divided. The split feature doesn't seem to work

postgresql log indicate an error and one part of the split feature is not saved:
`ERROR:  duplicate key value violates unique constraint "00_test_polygon_pkey"
`

I will see if upgrading postgresql works better.

**Comment by geographit** [comment]
I have also tried with postgresql 12 and have the same result.

Also the reshape tool does the thing, where the feature divided gets deleted.
The error is different though: 
`ERROR:  zero-length delimited identifier at or near """" at character 49`

**Comment by geographit** [comment]
It works fine in lizmap 3.3.9 :)

**Comment by DominikVisca** [comment]
I've got the same problem in Lizmap 3.4.1 and 3.4.3 with a SpatiaLite-Database. The problem seems to be the unique_constraint of the primary key which is necessary for the editing tool to work.
