### ISSUE TITLE
which QGIS version (desktop and server) for Lizmap 3.3.4

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#1563]
Hi there,

I have some Lizmap projects running successfully and stably under Lizmap 3.1.x and QGIS-Server 2.18.x.

Now I want to go to Lizmap 3.3.x and QGIS 3.? to update.

Which QGIS version (desktop and server) is recommended?

Here on Github [1] under "Versions" for Lizmap 3.3.x the QGIS server 3.4 is mentioned.
I can not install it (so easy) under Ubuntu 18.04.

Is the LTR version (3.10) or the current 3.12 recommended for the QGIS server?
And if 3.4, how can I install it on Ubuntu 18.04?

A test project [2] with QGIS server 3.12 is going well. With QGIS projects from QGIS-Desktop (3.4 and 3.10).
Editing also works well (login with users FOSSGIS and PW fossgis)
(the test project will be deleted soon)

Under QGIS-Desktop 3.12 there is a small problem with the display of the Lizmap plugin window [3]. The window size is probably not saved either.

And on the Internet the window size is sometimes a bit too small (Lizmap 3.3.4 under QGIS server 3.12) [4].

Thanks and Regards

Günter

(Sorry for the English, is Google Translate)

[1] https://github.com/3liz/lizmap-web-client
[2] https://fossgis.webgis.biz
[3] https://wagner-it.de/download/lizmap/Lizmap_Plugin_QGIS3_12.jpg
[4] https://wagner-it.de/download/lizmap/Lizmap_Fenster_QGIS_3_12.jpg

**Comment by nboisteault** [comment]
Please use Lizmap 3.3.4 with QGIS Desktop and Server 3.10.
@Gustry Can you watch [3] please ?

**Comment by Gustry** [comment]
About the screen [3], it's fixed. Wait for the next point release.

**Comment by guenterw** [comment]
thank you for the fast feedback.

But I can't find a repository for Ubuntu 2.18 to install QIS-Server 3.4 (does anyone have a tip?)

Then I just have to wait. Is the problem fixed with an update from QGIS Server 3.10.3 or later?

**Comment by gioman** [comment]
>  Ubuntu 2.18

@guenterw do you mean Ubuntu 18.04?

**Comment by guenterw** [comment]
@gioman sorry, yes of course Ubuntu 18.04. LTS

**Comment by ygorigor** [comment]
@guenterw I use Lizmap 3.4.pre with QGIS server 3.12 and is working well, so it's not mandatory to use qgis server 3.4

**Comment by rldhont** [comment]
An issue has been found in QGIS 3.10 https://github.com/3liz/lizmap-web-client/issues/1555

**Comment by guenterw** [comment]
@rldhont Thanks for the hint. I had seen the post and will add the print function to my test project in the next few days. And test with an extensive project.
My installation is based on Ubuntu 18.04 on the Apache web server
QGIS-Server 3.4 can probably no longer be installed on Ubuntu 18.04 (that simple)

**Comment by gisgogo** [comment]
At qgis-server version 3.12 same problem with print as 3.10.
