### ISSUE TITLE
[DataViz] Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1564]
https://github.com/3liz/lizmap-web-client/blob/7e85c9c3bdbba59f57f40c63e944f159aded517b/lizmap/www/assets/js/dataviz/dataviz.js#L154

**Comment by mdouchin** [comment]
yep, already fixed in my local repo. I will push asap

**Comment by nboisteault** [comment]
Fixed by da31bbe4da9d1049c39a3620929e9a339f24cd9d
