### ISSUE TITLE
Upgrade acorn to version 6.4.1 or later.

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1565]
### What is the bug?
For security reason, upgrade acorn to version 6.4.1 or later.
https://github.com/3liz/lizmap-web-client/network/alert/assets/package-lock.json/acorn/open

### Environment

 - Lizmap version: 3.4.0-pre

**Comment by nboisteault** [comment]
I've updated in https://github.com/3liz/lizmap-web-client/pull/1552

**Comment by rldhont** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/pull/1570
