### ISSUE TITLE
Problem editing 3D geometry in PostGIS 3

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#1567]
Using PostGIS 3 I encountered the following 

ERROR:  function st_force_3dz(geometry) does not exist 

It is due to the change of name of function st_force_3dz(geometry) to *st_force3dz* 

I solved defining a new function in the PostgreSQL DB using root user, but I think it is a problem for future editing. 

```
-- FUNCTION: public.st_force_3dz(geometry) as copy of the st_force3dz

CREATE OR REPLACE FUNCTION public.st_force_3dz(
	geometry)
    RETURNS geometry
    LANGUAGE 'c'

    COST 1
    IMMUTABLE STRICT PARALLEL SAFE
AS '$libdir/postgis-3', 'LWGEOM_force_3dz'
;

ALTER FUNCTION public.st_force_3dz(geometry)
    OWNER TO postgres;

COMMENT ON FUNCTION public.st_force_3dz(geometry)
    IS 'args: geomA - Force the geometries into XYZ mode.';

```

 - Lizmap version: 3.3.5
 - QGIS Server version: 3.10.3
 - OS: Ubuntu server 18.04 
 - PostGIS 3.0

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/902#issuecomment-399934661

**Comment by rldhont** [comment]
@rmarzocchi84 does st_force3dz exist in Postgis 2 ?
If it already exists, it is better to update lizmap to use this function, isn't it ?

**Comment by rmarzocchi84** [comment]
Yes. It seem to exists so on PostGIS 2.X

**Comment by rmarzocchi84** [comment]
https://postgis.net/docs/ST_Force_3DZ.html

**Comment by nboisteault** [comment]
@rmarzocchi84 Many thanks for reporting.
