### ISSUE TITLE
WFS edition

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1569]
I created a project and groups with different rights for editing according to the layers.

But if I use a WFS link `https: // myserver / service /? Repository = myrepository & project = myprojetct & SERVICE = WFS & REQUEST = GetCapabilities` in Qgis, the user can edit all the layers without restriction.

Is it possible to restrict this access via the WFS service?

**Comment by rldhont** [comment]
This feature required a QGIS Server plugin to manage accescontrol over WFS request.

**Comment by Cww7** [comment]
Ok, thanks.
But if I limit all layers on read only access with the plugin, there will be an impact on LM ?

**Comment by rldhont** [comment]
You can limit all layers on read only access in the QGIS Project WFS configuration, there will be no impact on LWC edition capabilities, because LWC does not use WFS Transactionnal.

**Comment by Cww7** [comment]
I just need to check 'publié' in the OWS Server tab in order to limit all layers on read only and, in the same time allow edition capabilities on LWC :

![image](https://user-images.githubusercontent.com/19794922/78154742-e827be80-743c-11ea-8ce7-49c121fc9783.png)

**Comment by Gustry** [comment]
Yes, no need to enable Update, Insert and Delete. Lizmap is not using these settings.
https://docs.lizmap.com/next/en/publish/lizmap_plugin/edition.html#prerequisites 4th bullet point on the next version of the documentation.

**Comment by Cww7** [comment]
Thank you, I hadn't seen that.

Everything is well explained  👍

**Comment by Gustry** [comment]
> Everything is well explained +1

Thanks. It's a heavy on going work about refactoring the documentation.

**Comment by franyam2006** [comment]
Hello, I created a spatial database, I made the configurations of the layers to be edited, I activated the WFS and other parameters but lizmap does not display the edit panel. lizmap 3.3.6

**Comment by nboisteault** [comment]
@franyam2006 What kind of spatial database ?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
