### ISSUE TITLE
lizmap/vendor/autoload.php n'existe pas

### ISSUE THREAD

**Issue by majorxtrem** [3liz/lizmap-web-client#1575]
Bonjour, 

Après la mise à jour de lizmap-web-client (version gitt branche master en date du 30-03-2020)

Il y a un soucis avec la modification ci-dessous

https://github.com/3liz/lizmap-web-client/commit/bbc5a696d6ed64bb35ac975e4ab413bf206a6952#diff-08287acab92fb1b65eb888ffa255f9f9

voici l'erreur lors de l’installation de la mise à jour

```
php lizmap/install/installer.php
PHP Warning:  require(/var/www/lizmap-web-client/lizmap/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/lizmap-web-client/lizmap/application.init.php on line 12
PHP Fatal error:  require(): Failed opening required '/var/www/lizmap-web-client/lizmap/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/lizmap-web-client/lizmap/application.init.php on line 12
```

Le fichier lizmap/vendor/autoload.php n'existe pas 

J'ai commenté la ligne pour que l'application fonctionne

Bonne journée

Johann

**Comment by majorxtrem** [comment]
@laurentj pour info :)

merci

**Comment by laurentj** [comment]
Il ne faut pas commenter la ligne.

Si le fichier vendor/autoload.php n'existe pas, c'est que tu n'as pas suivi les instructions de build de lizmap.

Lizmap n'est plus utilisable tel quel sur la branche master. 

Soit tu veux l'utiliser pour contribuer sur lizmap, auquel cas il faut suivre les instructions d'installation dans CONTRIBUTING.md, afin d'installer les dépendances PHP et JS, et générer les scripts JS de lizmap.

Soit tu veux simplement avoir la dernière version master pour tester, dans ce cas il faut télécharger le paquet sur https://packages.3liz.org/pub/lizmap/unstable/. Il ne faut plus utiliser git.
