### ISSUE TITLE
mobile - scale does not follow zoom level

### ISSUE THREAD

**Issue by geoemka** [3liz/lizmap-web-client#1576]
Identified on Android mobile, with Chrome, when zooming in/out with fingers, the scale indication panel on the down-right side of the map does not follow the effective zoom level. 
Might observe the same phenomenon on tablet since it's seems to be linked with the touch-sensitive zoom function.

1. for instance, go to the Léman Lake project on demo.lizmap.com
2. Load the map
3. Zoom/unzoom with fingers (does not apper on adaptative viewing for debug on pc)
4. Check the scale whether it is correct or not
5. the scale seems to adjust itself when rolling over the map after a few but didn't get the exact steps to make it right

The scale should follow the predefined zoom level on every zoom in/out action.

Some screenshots (ordered) : 
![InkedScreenshot_20200330-111346_Chrome_LI](https://user-images.githubusercontent.com/56970645/77897979-b6ff9080-727a-11ea-835d-03fc1e895a01.jpg)
![InkedScreenshot_20200330-111356_Chrome_LI](https://user-images.githubusercontent.com/56970645/77897996-ba931780-727a-11ea-8ad3-924fbe8bfe68.jpg)
![InkedScreenshot_20200330-111406_Chrome_LI](https://user-images.githubusercontent.com/56970645/77898009-c088f880-727a-11ea-8a48-a314b6bd55ae.jpg)
![InkedScreenshot_20200330-111410_Chrome_LI](https://user-images.githubusercontent.com/56970645/77898022-c41c7f80-727a-11ea-9456-1236bfc43528.jpg)

### Environment
 - **Lizmap version** : the one on demo version, but also noticed on Lizmap 3.3 webclient
 - **QGIS Server version** : the one on demo version
 - **QGIS Project version** : the one on demo version, but also noticed on QGIS 3.10 (LTR)
 - **OS**(Windows, Linux, MacOS, Android…): Android
 - **Browser** (Firefox, Chrome…) : Chrome

**Comment by Gustry** [comment]
I could indeed replicate on Samsung Internet browser.
Not on Firefox Android, it's working fine.

**Comment by geoemka** [comment]
Tried on Google Chrome for Android
Did not try on Firefox Android

**Comment by nboisteault** [comment]
@geoemka Which android and chrome version ? I can't confirm on Android 9 and Chrome 80.

**Comment by geoemka** [comment]
@nboisteault 
Bug confirmed on both an Android 8 and Chrome 80.0.3987 (screenshots).149, and an Android 8 and Chrome 80

**Comment by nboisteault** [comment]
I can confirm on Android 7 and Chrome 80 but the bug appears randomly.
@mdouchin @rldhont I think scale and scaleline are good candidates for a migration the Lizmap 4 way.

**Comment by rldhont** [comment]
It seems to be an issue in the old OpenLayers

**Comment by rldhont** [comment]
@nboisteault yes they are good candidates for a migration the Lizmap 4 way.
