### ISSUE TITLE
Create a default favicon

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1579]
### Is your feature request related to a problem? Please describe
Lizmap web client doesn't have any favicon.

### Describe the solution you'd like
A 3Liz favicon or a Lizmap one.

**Comment by nboisteault** [comment]
@rldhont @mdouchin https://www.3liz.com/images/flavicon.png would be ok ?

**Comment by Gustry** [comment]
I don't think this one will be readable https://www.3liz.com/images/logo-lizmap.png
So yes +1 for your proposition @nboisteault 

Side note: https://www.3liz.com/ does not have one too.

**Comment by igeofr** [comment]
I'd like to take this opportunity to remind you : https://github.com/3liz/lizmap-web-client/issues/1324

**Comment by nboisteault** [comment]
> I'd like to take this opportunity to remind you : #1324

It would be a nice feature but it needs to be funded.

**Comment by rldhont** [comment]
Closed?
