### ISSUE TITLE
On try to expand the group all the groups with similar names are expanded too

### ISSUE THREAD

**Issue by acdmail** [3liz/lizmap-web-client#158]
hi,
If there are some groups on the map with similar names they are all expanded in case one of the groups is expanded.
Example:
let say we have the following struncture:
xyz
xxx
  -xyz  
yyy

If I will try to expand the group xyz, the group xxx->xyz will be expanded too because of similar name

Thanks in advance

**Comment by rldhont** [comment]
With QGIS Server version 2.14, you can defined short name to avoid this issue. 2 groups can have the same name or title but have different short name. The short names are used to identify each group.

Feel free to reopen if you can't use short names.
