### ISSUE TITLE
Form filtering working on more layer at the same time?

### ISSUE THREAD

**Issue by tethysgeco** [3liz/lizmap-web-client#1580]
### Describe the solution you'd like
Hi, currently form filter can work only on one layer at a time and it’s been a great improvement.  
Do you think it's feasible to add the option of filtering two or more layers at the same time? Would it be easy or it's a high time-consuming activity?  

### Additional context
We are also testing a change in the user interface. We have modified the UI  as shown in the image below; if you are interested, we could share the js code with you. We think it’s better for users to see the TOC and filter at the same time. 
![immagine](https://user-images.githubusercontent.com/23027624/78115708-7d0dc600-7403-11ea-87e5-ad13d4eb449c.png)

**Comment by ygorigor** [comment]
Hi @tethysgeco . Can you share the js code here with your modifications?

**Comment by tethysgeco** [comment]
hi @ygorigor, we're trying adding these lines in media/js:

// add some custom style
var style = "<style>"
style += "#dock {max-width:100%; padding: 0px; background: transparent!important;}"
style += "#dock-tabs { background: rgba(00,00,00,0.7)}";
style += "#dock-content{ display: flex; }"
style += "#dock .tab-pane{ padding: 0px 10px; background: rgba(00,00,00,0.7); height: 100%; max-width:350px; min-width:270px;}"
style += "#dock .tab-pane#filter{ height: max-content; margin-left:2px; min-width:200px;}"
style += "#mapmenu .filter.nav-dock{ display: none!important;}"
style += "#switcher-layers-actions{ min-height: 40px;}"
style += ".btn-custom:hover{opacity: 0.9 }"
style += '#metadata.tab-pane { background-color: #EFEFEF!important; }'
style += '#bottom-dock{ max-width: calc( 100% - 40px)}'
style += '#switcher-baselayer { min-height: 100px}'
style += '.modebar-btn.plotlyjsicon.modebar-btn--logo{ display:none; important!;}'
style += "</style>"
$( style ).appendTo( "head" )

lizMap.events.on({
    'uicreated': function(e) {
        setTimeout(() => {

            // add filter panel title
            $("#filter #filter-container").before('<h3 style="margin-bottom: 40px; border-bottom: 1px solid rgba(255,255,255,0.5);"><span class="title"><span class="icon" style="background-image: url(/css/filter-icon-white.png); background-position: center; width: 20px; background-size: contain; height: width: 20px; height: 20px; display: inline-block;"></span>&nbsp;<span class="text">Filter</span></span></h3>')

            // add filter button on layers panel
            $('#switcher-layers-actions').append('<button class="btn-custom" id="custom-filter-switcher" style="outline: none;background: rgba(255,255,255,0.9); border-radius: 3px;color: black; margin: 8px; margin-right: 0px;">Filtra dati</button>');

            // open filter panel on click
            $("#custom-filter-switcher").click(function(e) {
                e.preventDefault();
                setTimeout( function() {
                    $("#filter").toggleClass("active");
                }, 200);
            })

        }, 800);   
    }
});


it definitely can be improved..

**Comment by ygorigor** [comment]
Thank you

**Comment by rmarzocchi84** [comment]
You can add your javascript here https://github.com/3liz/lizmap-javascript-scripts

**Comment by nboisteault** [comment]
@mdouchin is it a bug or a feature request ?

**Comment by nboisteault** [comment]
[This line](https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/www/js/filter.js#L1183) can be commented out to get desired behavior but I've not tested for undesirable side effects.

**Comment by mdouchin** [comment]
It requires a big refactoring of the code responsible for applying filtering. At the time present, it is not possible to apply a filter on more than one layer.

Keep in mind that triggering a filter applies also the filter to the child layers by following QGIS relations defined in the project, so it is not an easy stuff to change, and changing only the UI won't be enough

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
