### ISSUE TITLE
JS : selected feature

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1584]
Hi,
Which variable should I call to retrieve the current selection from the map ?

**Comment by nboisteault** [comment]
Hi,
`lizMap.config.layers['targetFeatureType'].selectedFeatures`
where `'targetFeatureType'` is the feature type you're looking for.

**Comment by Cww7** [comment]
Thanks @nboisteault  !
Is it possible to know where are these functions and their parameters defined ?

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/assets/js/map.js

**Comment by Cww7** [comment]
thanks again
