### ISSUE TITLE
QGIS 2.18 Value map widget edit type no longer supported

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1589]
### What is the bug?
The QGIS 2.18 value map widget edit type is no longer supported since PR https://github.com/3liz/lizmap-web-client/pull/1582 **Fix support of boolean values in qgis form properties with Qgis 3**
 has been merged

### Steps to reproduce the issue

1. Go to QGIS Desktop 2.18
2. Create a project with a PostGIS Layer
3. In the PostGIS Layer configure a field with checkbox widget edit type
4. In Lizmap plugin, add the PostGIS Layer as editable
5. In Lizmap Web Client, open the edit form
6. See error

### Expected behavior
Display the checkbox as defined in QGIS 2.18 Project

### Screenshots and logs
@josemvm can you provide screenshots ?

### Environment

 - Lizmap version: 3.3.6-pre
 - QGIS Server version: 2.18
 - QGIS Project version: 2.18

**Comment by josemvm** [comment]
before fix:
![imagem](https://user-images.githubusercontent.com/10053874/78898459-bf6e7d00-7a6b-11ea-8782-27c47fbc259e.png)


after fix:
![imagem](https://user-images.githubusercontent.com/10053874/78898375-96e68300-7a6b-11ea-8f93-8aad36261bea.png)

**Comment by rldhont** [comment]
@josemvm it's not checbox ? What is the QGIS edit type ?

**Comment by josemvm** [comment]
@rldhont value map
check box is ok

**Comment by josemvm** [comment]
@rldhont sorry

> check box is ok

it's false, the check box no longer supported too

**Comment by josemvm** [comment]
and all other wiget edit types...

**Comment by laurentj** [comment]
Thanks for your report. I tried to fix some things, even I'm not sure this is related to your issue. 

Tell me if it fix your issue. [package](https://packages.3liz.org/pub/lizmap/unstable/3.3/lizmap-web-client-3.3.6-pre.zip)

**Comment by josemvm** [comment]
@laurentj no, the problem remains...

**Comment by josemvm** [comment]
all the edit widgets have stopped working!

**Comment by rldhont** [comment]
@josemvm do you have some logs ?

**Comment by josemvm** [comment]
@rldhont the application is in production right now. later i will look for logs

**Comment by josemvm** [comment]
@rldhont unfortunately, i have no logs...

**Comment by laurentj** [comment]
@josemvm what are you calling "edit widget" ? Give us the exact name of type of widget that don't work anymore and you set into your qgis project.

Before you upgraded lizmap, what was the previous version you installed ? or what is the date of this previous version ? Because, I don't see how my patch could break the behavior, and since there were some other changes on the editor before submitting my patch....

**Comment by josemvm** [comment]
hi @laurentj 
i'm using lwc 3.3.6-pre (on qgis server 2.18) with all commits made up to this point https://github.com/3liz/lizmap-web-client/commit/e99ca8687ba8e2264fafd90efef12e0ce84e9c1b

when i update the the `qgisFormControl.class.php` with yout patch https://github.com/3liz/lizmap-web-client/pull/1582/commits/411ec54510c302509c7e4271b5b140da3e356789 all edit widget (from qgis desktop) becomes a text edit widget (text box)

> what are you calling "edit widget" ?

![imagem](https://user-images.githubusercontent.com/10053874/79324000-da773c00-7f06-11ea-8e62-0674b5cd0e78.png)

**Comment by nboisteault** [comment]
I can confirm the issue with a Postgis layer (no problem with sqlite in Montpellier project) with checkbox and Value map widget in release_3_3. No issue in 3.3.5. I keep investigating.

**Comment by nboisteault** [comment]
@josemvm thank you for reporting this issue.

**Comment by josemvm** [comment]
thanks to all :smile:
