### ISSUE TITLE
Deleting a feature not working

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#159]
I select a feature and once it is selected I can edit the geometry of the feature, but I can't delete a feature...

Reading the user guide I read the sentence "If you want to remove the object you selected, you must click Del." I thought i had to press "Del" key in my keyboard as I had no Deletion button in my screen. Later, I discovered that in Spanish, the left menu buttons' text are quite long and the buttons don't fit in the left menu (too wide) and the last button "Borrar" (delete) isn't even being displayed, although it is there...

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7958741/73c5516a-09f2-11e5-863b-0583098686c5.png)

**Comment by rldhont** [comment]
Hi @jaitor1, some strings are too long and break the UI. e have to update the UI.
