### ISSUE TITLE
Why Trigger filter on the atlas does not hide data?

### ISSUE THREAD

**Issue by remigods** [3liz/lizmap-web-client#1593]
Hi,

I am trying to use the atlas function on Lizmap. 
I activated the "trigger filter" atlas function on LWC, which should hide other data than the selected one in the atlas list.
It does not work. All data are still displayed. 

Some info from my project:
I used multipoint geometry (ST_Union) for generating the data. Could it be because of that?
I realized that the atlas function was not working neither with virtual layers, view generated from the database management, nor the view saved in PostgreSQL. Only using a table from PostgreSQL seems to work to feed the atlas list. 

Lizmap version: release 3.2
QGIS Server version: 2.18

Thank you for your advices,
Rémi

**Comment by remigods** [comment]
I am not able to produce the issue again. Probably a wrong config from my side. Sorry....
Now it works well.

**Comment by josemvm** [comment]
i have the same issue

**Comment by josemvm** [comment]
maybe a cache problem... now everything is ok
