### ISSUE TITLE
Utilisation de relations (sous-formulaires dans un formulaire) et édition d'objets dans lizmap

### ISSUE THREAD

**Issue by Anne432** [3liz/lizmap-web-client#1594]
Hello,

I need your help because I cannot find a solution having gone through all the documentation, having read the different topics of the forums ...

Here is the configuration I use:

     -  Qgis bureautique 3.4

      - QGIS server 3.4

     -  Lizmap web client 3.3.5

   -  Database  PostgreSQL 11

I have a QGIS project including a layer with geometry which is linked to several tables without geometry (all from my PostgreSQL DB)
I have created the appropriate relationships in the properties of my QGIS project.
I created the appropriate form for each table.
Then, I created for my layer with geometry, a form calling thanks to the relations defined previously in the subforms.
Everything works well on QGIS: when I click on a punctual, the form including the subforms opens well.

In the lizmap pluggin, I have:

    - Checked that all of my layers / tables are published in WFS in the OWS properties of the project (including child tables) to make them editable
   -  Added all editing tables (including girls) in the attribute table tab of the plugin

I would like to be able to obtain the same thing via lizmap, that is to say on my carto interface, when I click on an existing punctual and that I go into edit mode, to be able to see my "subforms" in order to be able to put the data from tables, also up to date.
-> it doesn't work, I can't see my subform.

Furthermore, I have no problem adding a new object, the form opens very well (even if I don't have access to my subform). However, when I want to modify an existing object via the pop-up and clicking on the pencil "editing tool", nothing happens, nothing opens. It seems blocked.

So, I obviously have 2 problems:

   - subforms

   - modification of existing objects.

Thank you in advance for the help you can give me.

Anne

**Comment by Anne432** [comment]
Hello,

I will need your help because I cannot find a solution having gone through all the documentation, having read the different topics of the forums ...

Here is the configuration I use:
-        Qgis bureautique 3.4
-        QGIS server 3.4
-        Lizmap web client 3.3.5
-      l’ensemble des données utilisées sont dans une base de données PostgreSQL 11

I have a QGIS project including a layer with geometry which is linked to several tables without geometry (all from my PostgreSQL DB)
I have created the appropriate relationships in the properties of my QGIS project.
I created the appropriate form for each table.
Then, I created for my layer with geometry, a form calling thanks to the relations defined previously in the subforms.
Everything works well on QGIS: when I click on a punctual, the form including the subforms opens well.

In the lizmap pluggin, I have:

-  Checked that all of my layers / tables are published in WFS in the OWS properties of the project (including child tables) to make them editable
-  Added all editing tables (including girls) in the attribute table tab of the plugin

I would like to be able to obtain the same thing via lizmap, that is to say on my carto interface, when I click on an existing punctual and that I go into edit mode, to be able to see my "subforms" in order to be able to put the data from tables, also up to date.
-> it doesn't work, I can't see my subform.

Furthermore, I have no problem adding a new object, the form opens very well (even if I don't have access to my subform). However, when I want to modify an existing object via the pop-up and clicking on the pencil "editing tool", nothing happens, nothing opens. It seems blocked.

So, I obviously have 2 problems:
-     subforms
-     modification of existing objects.

Thank you in advance for the help you can give me.

Anne

**Comment by paolo73an** [comment]
I have the same issue with PG11 tables.
I've tried also with child tables with geometry (thinking that maybe lizmap interfacae doesn't manage non-geometry tables), but after setting parent-child relation, the only way to insert a new child record is to draw a new point and manually set the foreign key to relate it to parent. When I click to a parent point layer in lizmap, a popup appears with child records' attributes below: if I click the button to add a new child record, ad input form appears but the foreign key field is empty and not editable and when I try to save, a warning message appears saying that that field is mandatory.
