### ISSUE TITLE
Composer template not found

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#1599]
Bonjour,
Pourquoi ce message "Composer template not found" quand je lance le module d'impression depuis mon navigateur ?

dans les logs Lizmap, il est reporté ceci : (même ligne deux fois)
2020-04-19 21:35:47	192.168.35.200	warning	2020-04-19 21:35:47	[2]	SQLite3::exec(): attempt to write a readonly database	/var/www/lizmap-web-client-3.0.4/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	120
2020-04-19 21:35:47	192.168.35.200	warning	2020-04-19 21:35:47	[2]	SQLite3::exec(): attempt to write a readonly database	/var/www/lizmap-web-client-3.0.4/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	120

Les données du projets sont toutes dans une base postgis
Il y a bien un composeur dans le projet Qgis. 
Je demande bien à ne pas exclure de mise en page dans Propriété/QGis server" mais inexorablement, la coche revient à 'vert'. J'ai généré une 2e mise en page exclue de qgis server mais pas plus de chance.
Est-ce là la cause ? Si Oui comment la résoudre ?

Mon contexte de travail : 
    Lizmap version: 3.3.5
    QGIS Server version: 3.4.15
    QGIS Project version: 3.4.15
    (plugin 3.2.12)
    OS (Windows, Linux, MacOS, Android…): Windows
    Browser (Firefox, Chrome…): Firefox, Chrome
Merci pour votre retour
Cordialement

**Comment by Gustry** [comment]
> Je demande bien à ne pas exclure de mise en page dans Propriété/QGis server" mais inexorablement, la coche revient à 'vert'.

Que voulez-vous dire par "vert"? Dans les propriétés du projet, il suffit de ne rien ajouter dans la liste d'exclusion.

**Comment by cocro** [comment]
Bonjour, 
![image](https://user-images.githubusercontent.com/46560615/79835083-662d1480-83ae-11ea-9a2b-3bb91350319d.png)

Aucune mep filtrée, coche "verte" toujours active ; mais c'est peut-êre la configuration std de qgis. Juste une piste pour comprendre pourquoi mon composeur ne bascule pas coté Lizmap web. 
Faut-il créer un modèle carto basé sur le composeur et le basculer ftp ?
ou le problème est-il autre coté configuration qgis server ?

Merci

**Comment by rldhont** [comment]
Est-ce que le composer à une fonction atlas ?

**Comment by cocro** [comment]
Bonjour,
Désolée pour ce silence mais nous cherchions aussi à comprendre les dysfonctionnements sur ce serveur. Nous avons pris la décision d'utiliser le serveur de production "perceval" comme serveur test et voir comment il réagit. Sidérant, nous ne reproduisons pas le souci d'impression. Impossible de savoir ce qui diffère entre les deux configurations ; nous abandonnons cette machine "merlin" trop instable. 
Nous allons générer un nouveau serveur test sur la base de perceval.
Je vais pouvoir continuer à déployer des projets ... prochaine étape pour moi, trouver comment emboiter des filtres (choix 1 epci, ne donne que les communes concernées dans le filtre 2)

Je clos ce poste et vous remercie pour vos appuis
Cordialement
