### ISSUE TITLE
Add a panel for edition tools.

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#160]
I really think that adding a panel for editing elements (insert new elements, delete, move, edit..) should be the next big move on lizmap. Something like:

![sin titulo](https://cloud.githubusercontent.com/assets/12136796/7958088/6dbd1b78-09ec-11e5-9336-5781fcad826c.png)

buttons taken from :
https://www.scribblemaps.com/create/#lat=43.34480718693234&lng=-3.010179339599631&z=18&t=hybrid

Another map with tools panel: http://www.gmapgis.com/

this enhancement has something to do with it too: https://github.com/3liz/lizmap-web-client/issues/113

**Comment by josemvm** [comment]
the snapping option is essential too!

**Comment by Abelon38** [comment]
I agree! it would be a big step for Lizmap!
Cheers Abel

**Comment by rldhont** [comment]
Implementing Drag, Rotate and Reshape for 3.2

**Comment by josemvm** [comment]
@rldhont, how can we finish the reshape feature?

thanks

**Comment by josemvm** [comment]
probably, it needs double click to finish the reshape instead of a right click (as it happens in qgis desktop)...

**Comment by rldhont** [comment]
I'll close this issue, because an edition toolbar has been introduced in 3.2.0. You can open enhancement to get specific tool.
