### ISSUE TITLE
Lizmap 3.3.5 installation error

### ISSUE THREAD

**Issue by claudiogeop** [3liz/lizmap-web-client#1603]
Hello friends, I have been trying to install Lizmap web Client 3.3.5, I have also installed PostgreSQL + Postgis but I am stuck in this situation. I can install to prod / release_3_3 with the following error message:

PHP Warning: pg_close (): supplied resource is not a valid PostgreSQL link resource in C: \ webserver \ lizmap \ prod \ release_3_3 \ lib \ jelix \ plugins \ db \ pgsql \ pgsql.dbconnection.php on line 166.

When I proceed to install in preprod \ master the message always appears:
C: \ webserver \ lizmap \ preprod \ master> php lizmap \ install \ installer.php
PHP Warning: require (C: \ webserver \ lizmap \ preprod \ master \ lizmap / vendor / autoload.php): failed to open stream: No such file or directory in C: \ webserver \ lizmap \ preprod \ master \ lizmap \ application .init.php on line 12
PHP Fatal error: require (): Failed opening required 'C: \ webserver \ lizmap \ preprod \ master \ lizmap / vendor / autoload.php' (include_path = '.; C: \ php \ pear') in C: \ webserver \ lizmap \ preprod \ master \ lizmap \ application.init.php on line 12
![error](https://user-images.githubusercontent.com/61161982/79813090-0f452200-8351-11ea-9de2-d2b13c333f46.PNG)

I appreciate if anyone can help and I hope you are well ...

**Comment by cfsgarcia** [comment]
using linux command, install composer (find equivalent in windows...):
`apt install composer`
then deploy composer into lizmap:
`cd /path_to_lizmap/lizmap-web-client-x.x/lizmap`
`composer install`
You should then be able to run `installer.php`

**Comment by claudiogeop** [comment]
cfsgarcia thank you very much, an installation went perfectly.

**Comment by news24lor** [comment]
Please insert these instructions in your INSTALL file

> using linux command, install composer (find equivalent in windows...):
apt install composer
then deploy composer into lizmap:
cd /path_to_lizmap/lizmap-web-client-x.x/lizmap
composer install
You should then be able to run installer.php

Thanks

**Comment by baradgeo** [comment]
> using linux command, install composer (find equivalent in windows...):
> `apt install composer`
> then deploy composer into lizmap:
> `cd /path_to_lizmap/lizmap-web-client-x.x/lizmap`
> `composer install`
> You should then be able to run `installer.php`

how to do for windows.. its not working

**Comment by claudiogeop** [comment]
I have some tips for windows:
The composer.exe installation can create an environment variable
C: \ ProgramData \ ComposerSetup \ bin, this way you run the composer in any other folder / environment
COMPOSER in the environment:
C: \ server \ lizmap \ preprod \ master \ lizmap
Download the COMPOSER.phar file
https://getcomposer.org/download/
Place in the same folder where the composer.json file exists
Extension = php_openssl.dll removing it; in the php.ini file
It is important that the **vendor** folder is created in C: \ server \ lizmap \ preprod \ master \ lizmap

Try to run the php composer.phar installer

If successful please return with a tutorial

**Comment by baradgeo** [comment]
I got help from this. Its already working for windows and in 4-5 steps you will be up and running. Please take note form all the setting. Its working for me. I have all the recent versions. Please follow the below link.
 https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by claudiogeop** [comment]
It's very good!

**Comment by laurentj** [comment]
>When I proceed to install in preprod \ master the message always appears:
C: \ webserver \ lizmap \ preprod \ master> php lizmap \ install \ installer.php
PHP Warning: require (C: \ webserver \ lizmap \ preprod \ master \ lizmap / vendor / autoload.php): 


This is normal. This is NOT an issue. Except if you want to develop Lizmap, you SHOULD download lizmap from https://packages.3liz.org/pub/lizmap/unstable/ or from https://github.com/3liz/lizmap-web-client/releases.

Sources from the master branch are not usable directly, as we started to have some build step for Javscript code and PHP Code.

Please read the README.md file on the master branch.

For the issue about postgresql error, access parameters into var/config/profiles.ini.php are bad.
