### ISSUE TITLE
Permettre l'utilisation de @import dans la personalisation CSS

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#1608]
Bonjour,

Dans l'interface d'administration il est possible de personnaliser l'apparence en ajoutant des propriétés CSS.
Par contre je n'ai pas réussi à ajouter des styles en utilisant un
```css
@import url("blablaba");
```
Est-ce possible d'une manière ou d'une autre? Sinon ce serait une bonne amélioration à développer.

Valérian

**Comment by nboisteault** [comment]
@vlebert pouvez-vous essayer `@import url('blablaba');` avec des guillemets simples et pas doubles ?

**Comment by vlebert** [comment]
Je viens d'essayer, ça passe effectivement mieux avec les simple-quote
Le code est proprement généré mais le résultat le style est cassé en affichage.

![image](https://user-images.githubusercontent.com/49779177/79986300-1d5b8580-84ac-11ea-8a1e-4bb2f5f31d8c.png)


En revanche si je l'intègre dans la popup cela fonctionne :
![image](https://user-images.githubusercontent.com/49779177/79986519-74f9f100-84ac-11ea-98c4-219e57ac1a15.png)

**Comment by nboisteault** [comment]
Que voulez-vous dire par le style est cassé en affichage ? Avez-vous un screenshot ? Il y a-t-il un message d'erreur dans la console ?

**Comment by vlebert** [comment]
Bonjour,

J'utilise fontsawesome pour ces icones :
![image](https://user-images.githubusercontent.com/49779177/80184846-9f15f500-860b-11ea-964d-3cf5a085bf9f.png)

Si je passe le CSS en @import au niveau administration les icones ne s'affichent pas.

Si j'appelle le CSS dans les popum avec une balise <link rel="stylesheet"> les icones s'affichent correctement.
Il me semble que l'appel à la balise <link> est plus propre, mais ce qui me dérange un peu est qu'elle est appelé plusieurs fois (pour chaque feature dans les popup)

**Comment by mdouchin** [comment]
Il faudrait simplement regarder comment votre CSS est appelé par la page lorsque vous l'ajouter au niveau de l'administration. Ouvrir les sources de la page, et cherchez `@import` pour comprendre la différence entre cette source, et ce que vous voyiez dans la popup.

Pouvez-vous poser ici le code source lié à cet import
* via l'admin
* via la popup (sélectionner la popup et clic-droit "Code source de la sélection" dans Firefox (ou bien utiliser les outils de développement / inspecteur)

**Comment by vlebert** [comment]
Voici l'option via l'administration : 
![image](https://user-images.githubusercontent.com/49779177/80186008-9f16f480-860d-11ea-88da-e9066e87a43e.png)

Qui se traduit par : 
![image](https://user-images.githubusercontent.com/49779177/80186057-af2ed400-860d-11ea-85b3-ff9ebd11bf58.png)

Au niveau des popup : 
![image](https://user-images.githubusercontent.com/49779177/80186105-c7065800-860d-11ea-9dcd-5e27a1b87b45.png)

Traduit par : 
![image](https://user-images.githubusercontent.com/49779177/80186194-e56c5380-860d-11ea-8f54-4b125df742ef.png)

Au final je ne sais pas si le problème est lié à Lizmap puisque le code est bien intégré à la page. J'ai essayer de faire le @import via les themes mais je n'ai pas non plus réussi de cette manière. Et j'ai lu que l'utilisation de @import n’était pas la meilleure pratique.
Il manque dont peut-être un endroit où pouvoir mettre du HTML (balises [link rel]) au niveau de la page principale et non au niveau des popup.

Sinon j'ai constaté que les  propriétés CSS des > ne passent pas (traduit en &gt; dans le code)

**Comment by nboisteault** [comment]
@vlebert il y a un bug pour le `>` qui ne passe pas. Je vais publier un patch rapidement.

**Comment by nboisteault** [comment]
> @vlebert il y a un bug pour le `>` qui ne passe pas. Je vais publier un patch rapidement.

Le bug est corrigé : https://github.com/3liz/lizmap-web-client/commit/fb78f6babac2d8eb74105ee43ffb9b5c252f31b3

**Comment by josemvm** [comment]
bonjour @vlebert 


Additional CSS properties:
`@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')`


![image](https://user-images.githubusercontent.com/49779177/80184846-9f15f500-860b-11ea-964d-3cf5a085bf9f.png)

où ces icones devraient-ils apparaître en utilisant ce code?

merci

**Comment by vlebert** [comment]
Bonjour @josemvm 

Ces icones apparaissent dans les popups dans lesquelles j'utilise des balises font-awesome

Est-ce que cela répond à la question?

**Comment by josemvm** [comment]
j'ai essayé d'insérer simplement ce code dans "les Additional CSS properties" et il ne s'est passé rien...  

je crois bien que vous avez fait le mêmme seulement pour voir comment le code a été traduit dans le fichier de thème, en le comparant à l'insertion du même code dans la configuration des popup - c'est comme ça?

merci

**Comment by vlebert** [comment]
Bonjour,

Voici le code que j'utilise dans la configuration des popup (type lizmap/html)

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

`	
[...]	
`
<a href="{$liens}" target="_blank" class="alert-link"><b>Page du projet sur Do4A</b></a>
<br />

<a class="fa fa-linkedin" style="font-size:16px" href="{$linkedin}" target="_blank"></a>
&nbsp;
<a class="fa fa-facebook-square" style="font-size:16px" href="{$fundproj_facebook}" target="_blank"></a>
&nbsp;
<a class="fa fa-youtube-play" style="font-size:16px;color:red" href="{$fundproj_video}" target="_blank"></a>
&nbsp;
<a class="fa fa-twitter" style="font-size:16px" href="{$fundproj_twitter}" target="_blank"></a>
 `

Ce code fonctionne mais le link rel est fait à chaque popup. Mon but était de le faire une seul fois pour la page avec un @import. mais cela n'a pas fonctionné

**Comment by josemvm** [comment]
@vlebert merci beaucoup pour avoir partagé! :-)
