### ISSUE TITLE
Personnalisation CSS par projet QGIS

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#1609]
Bonjour,

Dans la page d'administration on peut ajouter des propriété CSS
Ce serait intéressant de pouvoir faire cela également carte par carte. En l'état il faut utiliser plusieurs instances de lizmap si on veut publier des cartes avec des styles différents

Qu'en pensez-vous?

Valérian

**Comment by Gustry** [comment]
C'est déjà possible par l'utilisation des thèmes par projet : https://docs.lizmap.com/next/fr/publish/customization/themes.html

**Comment by vlebert** [comment]
Merci je vais essayer ça

**Comment by vlebert** [comment]
Après quelques j'arrive à appeler un theme en ajoutant
&theme=blabla dans l'URL
En revanche je n'arrive pas à mettre un theme par défaut à un projet donné (j'ai essayé avec le nom du projet et le nom du repository)

Suis-je passé à coté de quelque chose?

**Comment by Gustry** [comment]
Quelle est l'arborescence des dossiers/fichiers?

**Comment by vlebert** [comment]
J'ai une installation docker-compose : https://github.com/3liz/lizmap-docker-compose
J'ai juste modifié les versions (lizmap 3.3.5 et QGIS SERVER 3.10)

J'ai donc un repository xxx avec un projet yyy.qgs
xxx/yyy.qgs

Ensuite au niveau des thèmes j'ai l'arborescence suivante. J'ai essayé plusieurs nommage pour le theme personnalisé mais sans succès (sauf en ajoutant &theme=zzz)
![image](https://user-images.githubusercontent.com/49779177/80006029-9f57a880-84c4-11ea-873c-fb14090b85f8.png)

**Comment by Gustry** [comment]
La documentation parle de l'utilisation du dossier `media` et de mettre le thème pour un projet spécifique à l'intérieur.

**Comment by vlebert** [comment]
Je me demande si la documentation est à jour à ce sujet. Sauf erreur il n'y a pas de dossier media.
Le dossier "themes" est d'origine directement dans www

**Comment by vlebert** [comment]
Ok je crois que j'ai compris la subtilité après une meilleur lecture.
Notamment cette page
https://docs.lizmap.com/next/fr/publish/configuration/media.html#media
Merci

**Comment by Gustry** [comment]
I have just added a "prerequisites" section to make it more visible:
https://github.com/3liz/lizmap-documentation/commit/a259441346a22bf7a13789d31195d0df9ef00ec1
