### ISSUE TITLE
Default Repositories don't load data montepelier project

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#161]
Description of the issue:
When open the montepelier repositories the webpage stays with loading data splash and the background shows the panels and in the map view "SHOW SERVICE NON DISPONIBLE".

Error Log from Apache Server in paste.org:
http://goo.gl/fXORFn

Point to nonexistent .js files of jquery-ui-1.10.3.custom.min.js, the lizmap/www/js  have the jquery-ui-1.11.2.custom.min.js

Regards
João

**Comment by jonnyforestGIS** [comment]
UPDATE:
Problem solve.
I change the dir of fcgi.exe to qgis path in php file \lizmap\var\config\lizmapConfig.ini.php and works

**Comment by rldhont** [comment]
You can do it in the admin interface.
