### ISSUE TITLE
Draw features on the map and save them

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1610]
It would be great to be able to draw on the map and save the drawings. 
As an option:
* filter the drawings by user
* the possibility to define the feature's color (background/contour)
* the possibility to modify the geometry of existing drawings

**Comment by nboisteault** [comment]
Parts of this enhancement have been made in https://github.com/3liz/lizmap-web-client/pull/1703 for upcoming LWC 3.4.

**Comment by nboisteault** [comment]
@arno974 I close as most points have been made. Please open another ticket for remaining ideas.
