### ISSUE TITLE
selection tool - the drawings remain on the map

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1613]
hi

using the new selection tool, you can see that the drawings (point, line or polygon) remain on the map after making selection

![imagem](https://user-images.githubusercontent.com/10053874/80354916-4a72b400-886f-11ea-8efd-8ddc39af95be.png)

thanks

**Comment by nboisteault** [comment]
There is a new button to toggle the selection layer.

![image](https://user-images.githubusercontent.com/2145040/80368278-c0394880-888c-11ea-9948-d9338e7be376.png)

**Comment by josemvm** [comment]
@nboisteault thanks
