### ISSUE TITLE
Media and HTTPS

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#1616]
Hi

I have a Lizmap instance (3.3.5) on port 443 on a server with HTTPS.

The projects is a map with popups set to auto, and with pictures in the media directory.

The picture preview OK but when I click on a picture it opens a link without HTTPS
http://{URL}/index.php/view/media/getMedia?repository=XXX&project=YYY&path=media%2FDCIM%2F20200427111436712.jpg

I had to open connections on port 80 to solve this issue and make the pictures full size visible.

Is it an issue on the client or is there a parameter somewhere to fix it?

Valérian

**Comment by nboisteault** [comment]
Hi,
Do you have a public link to share ?

**Comment by mdouchin** [comment]
You should not  need to open your 80 port and enable plain HTTP connexion. Perhaps your app was at first configured without HTTPS, and then you enabled HTTPS ?
If so, try to purge Lizmap cache. No the tile cache, but the app cache

Go to your installation directory, then clean the temp:

```bash
cd /your/lizmap/directory/
lizmap/install/clean_vartmp.sh
```

**Comment by vlebert** [comment]
Hi,

Actually Lizmap is on server_1 on port 1000. 
I don't have port 443 or port 80 on this server.

To embed maps in websites without https security alerts from browsers, I set a proxy on server_1 which runs apache2 and routs traffic on a subdomain dedicated to Lizmap on server_2.
server_2 has port 80, port 443 and https certificate.

I can send you a public url on private mail as it contains some private datas.

**Comment by Gustry** [comment]
Is this issue still valid ?
