### ISSUE TITLE
Mark the active element in the query window

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#1617]
In lizmap-client 3.2.x you could mark the corresponding element in the query window (with the check mark). To do this, the attribute table had to be available
![grafik](https://user-images.githubusercontent.com/8373176/80872103-30423700-8cb0-11ea-9d97-57f07d4476a1.png)

In the m lizmap-client 3.3.x (here 3.3.6) this is only possible via the attribute table.
Is that what is wanted or is it a mistake?
![grafik](https://user-images.githubusercontent.com/8373176/80872140-7bf4e080-8cb0-11ea-8c95-19c92d27e184.png)

It would be nice if the function was always available in the query window, even without an attribute table

**Comment by Gustry** [comment]
It works for me.
https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=cats I can click on a cat.

**Comment by guenterw** [comment]
Thank you for the feedback.

after a new test for me it also works in other projects.
Affected probably only a one-time project / data.
