### ISSUE TITLE
mouse wheel issue in Chrome when lizmap is in an iframe

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1619]
### What is the bug?

In Chrome and in some version of Firefox, when using the mouse wheel or the trackpad to zoom in/out on the map, the whole page scroll at the same time.

- Chrome MacOS : bug
- Chrome win10 : bug
- Chrome linux + trackpad : bug
- Chrome linux + molette souris : bug
- Firefox linux + trackpad : OK
- Firefox linux + molette souris : OK
- Firefox Mac + trackpad : bug
- Firefox Mac + molette souris : OK
- Firefox win10 : OK
- Safari MacOS : OK
- Edge win10 : OK

### Steps to reproduce the issue

1. use an iframe into a web page, using the `/index.php/view/embed/` url to display lizmap
2. put the mouse over the map, and use the mouse wheel or the trackpad to zoom
3. the map zoom in or zoom out, but the page also scrolls.

### Expected behavior

The page should not scroll.

### Environment

 - Lizmap version: 3.3
 - OS : Windows, Linux, MacOS 
 - Browser : Chrome

**Comment by nboisteault** [comment]
This bug might be linked to this error in Chrome console :

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

The bug is in Openlayers 2. It is more and more time to upgrade :-)

**Comment by nboisteault** [comment]
@rldhont @laurentj maybe a solution ? https://developers.google.com/web/updates/2017/01/scrolling-intervention

**Comment by rldhont** [comment]
The files to update are :
* OpenLayers/Events.js
* OpenLayers/Handler.js
* OpenLayers/Handler/Click.js
* OpenLayers/Handler/MouseWheel.js

**Comment by nboisteault** [comment]
FYI this issue has been fixed in OL 6 [here](https://github.com/openlayers/openlayers/pull/10286/files).

**Comment by nboisteault** [comment]
@rldhont @laurentj I found how to fix the issue. I'll patch soon.
