### ISSUE TITLE
Easier popup in mobile

### ISSUE THREAD

**Issue by GitMorin** [3liz/lizmap-web-client#162]
I am looking for an imporovement to get up the pop-up when you use lizmap in smartphones. It is hard to get up the pop-up for points and lines, it would be great if there was some kind of buffer around points and lines so ones dont need to be so precise where to press on the screen.

**Comment by jaitor1** [comment]
+1. 

Not only in mobile phones, in computers sometimes it gets hard to select one item too...

**Comment by rldhont** [comment]
Fixed with popup search radius
