### ISSUE TITLE
Child table in compact way - hidden fields are shown - No merged view

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1620]
Hello
I'm trying to display a child table in Lizmap 3.2.6-pre

Child table is a view

CREATE OR REPLACE VIEW myview AS 
 ```
SELECT id,
  id_impianto,
    date(data) AS data,
    n_accettazione,
    anno,
    zona_prelievo,
    motivo_prelievo,
    prova,
   risultato,
    umis
   FROM Mytable;
```
It is related to a layer by id_impianto  field

In Qgis 2.18.28 relation works fine
In Lizmap the same

I set lizmap as for advanced config and I'll like ho hide some field in child table
So I followed what is written here
https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#display-children-in-a-compact-way

This is the code

```
<table class="lizmap_merged">
 <tr class="lizmapPopupHeader">
	 <th class="lizmapPopupHidden"><center> id </center></th>	
     <th class="lizmapPopupHidden"><center> id_impianto </center></th>
     <th> <center> Data </center> </th>
     <th> <center> Accettazione</center> </th>
	 <th class="lizmapPopupHidden"><center> anno </center></th>
	 <th> <center> Prelievo</center> </th>
	 <th class="lizmapPopupHidden"><center> motivo_prelievo </center></th>
	 <th> <center> Prova</center> </th>
	 <th> <center> Risultato</center> </th>
	 <th> <center> U.M.</center> </th>
  </tr>
  <tr>
	 <td class="lizmapPopupHidden"><center>{$id}</center></td>
     <td class="lizmapPopupHidden"><center>{$id_impianto}</center></td>
     <td><center>{$data}</center></td>
     <td><center>{$n_accettazione}</center></td>
	 <td class="lizmapPopupHidden"><center>{$anno}</center></td>
	 <td><center>{$zona_prelievo}</center></td>
	 <td class="lizmapPopupHidden"><center>{$motivo_prelievo}</center></td>
	 <td><center>{$prova}</center></td>
	 <td><center>{$risultato}</center></td>
	 <td><center>{$umis}</center></td>
  </tr>
</table>

```

Child table is shown as table but hidden fields (id, id_impianto ecc..) appear
What is my problem?

Thanks
Pietro

**Comment by nboisteault** [comment]
Hi,

Do you have a public link to your Lizmap ?

FYI in upcoming Lizmap 3.4 there will be a button to toggle between 
expanded/compact view by default.

Le 05/05/2020 à 18:14, Pietro Rossin a écrit :

**Comment by pieri70** [comment]
Hello 
yes go to https://lizmap.arpa.fvg.it
login with esterno/esterno

If you click on a plant (impianto) like Udine via Gonars

https://lizmap.arpa.fvg.it/index.php/view/map/?repository=testesterni&project=arpa_reperibilita&layers=00B0TFFFFFFTFFFFFFFFFFFFFFTTT&bbox=1463472.950048%2C5779653.35334%2C1481149.012836%2C5787908.552393&crs=EPSG%3A3857&layerStyles=Limiti_amministrativi%3Adefault%3BImpianti%3Adefault%3Bimpianti_analisi%3Adefault

you can see data in popup.

Here is another problem..
I asked for it here
https://github.com/3liz/lizmap-web-client/issues/1577

Udine via Gonars has around 1500 records in child table..
Lizmap shows only 10 records (I see there is an option in lizmap plugin to change this number)

If you open impianti data table lizmap hangs...
Child table has a total of 40.000 records for all plants

Thanks
Pietro

**Comment by nboisteault** [comment]
@pieri70 You need to create a QGIS popup and not a Lizmap one if you want the compact table to work.

**Comment by nboisteault** [comment]
Concerning records limit, did you try this option ?
![image](https://user-images.githubusercontent.com/2145040/81163481-201ba780-8f8f-11ea-901f-0f74ade3fdcd.png)

**Comment by nboisteault** [comment]
> If you open impianti data table lizmap hangs...
Child table has a total of 40.000 records for all plants

Please open another ticket for this issue. I looked at your project, data is loading but there is an error in console. It is at line 1379 of attributeTable.js @mdouchin do you understand what's happening ?

**Comment by tethysgeco** [comment]
@ pieri70, maybe this is not the case, but we saw a similar behavior in a project where a user typed by mistake special characters in a field of text type in the attribute table (pressing enter or TAB on computer keyboard). Lizmap was no more able to show data table.

**Comment by pieri70** [comment]
> @pieri70 You need to create a QGIS popup and not a Lizmap one if you want the compact table to work.

@nboisteault I tried to set Qgis source in popup style
The popup style is not shown as a table with headers and rows
The same as auto style
Here are two pictures
![qgispopup](https://user-images.githubusercontent.com/11612625/83002806-c3e7f880-a00d-11ea-9ee9-70368e157bf6.JPG)

If I set Lizmap style in popup with the code below I get a well ordered table but it isn't merged, so double child table layout

![lizmappopup](https://user-images.githubusercontent.com/11612625/83004649-378b0500-a010-11ea-911e-501668f7fa35.JPG)

`<table class="lizmap_merged">
 <tr class="lizmapPopupHeader">
     <th> <center> Specie </center> </th>
     <th> <center> Anno </center> </th>
	 <th> <center> Quantità </center> </th>
  </tr>
  <tr>
     <td><center>{$specie}</center></td>
     <td><center>{$anno}</center></td>
     <td><center>{$numero}</center></td>
  </tr>
</table>`

You can see it in 
https://lizmap.arpa.fvg.it
usr=lizdevelopers
pw=lizdevelopers

Thanks

**Comment by brulien** [comment]
Hello all,

I have exactly the same problem. I followed the insctructions from the documentation, edit the HTML code. I just had to replace [% "attribute" %] by {$attribute} cause the first syntax doest work and the child entities are not merged.

**Comment by brulien** [comment]
I suggest to add the tag bug

**Comment by brulien** [comment]
On version 3.4.10, I think the bug comes from the following block in js/map.js (class LizMap)  :
`                //Manage if the user choose to create a table for children
                if( rConfigLayer.popupSource == 'qgis' &&
                    childPopup.find('.lizmap_merged').length != 0 )
                {...}
`
rConfigLayer.popupSource cant be == 'qgis'

**Comment by nboisteault** [comment]
Compact tables will be automatic with a button to toggle mode in next Lizmap version 3.4.

**Comment by aeduard** [comment]
The icon ([doc](https://docs.lizmap.com/current/en/publish/configuration/popup.html#one-to-many-relations)) for the compact child table view is not appearing for me in lizmap 3.4.0. Any hints?

**Comment by Alain-LG** [comment]
> 
> 
> The icon ([doc](https://docs.lizmap.com/current/en/publish/configuration/popup.html#one-to-many-relations)) for the compact child table view is not appearing for me in lizmap 3.4.0. Any hints?

Do you find how to do ?

**Comment by aeduard** [comment]
No, I didn't, I can't find the button neither in version 3.4.1.

**Comment by aeduard** [comment]
Actually it is working if Pop-up source is set to _auto_. Button does not appear if source is set to _qgis_ or _lizmap_. But in this case, having a primary key and a foreign key column which shows on the child pop-up table, it is a waste of table space. I couldn't manage to hide these two columns if Pop-up source is set to _auto_.

**Comment by ygorigor** [comment]
> Actually it is working if Pop-up source is set to _auto_. Button does not appear if source is set to _qgis_ or _lizmap_. But in this case, having a primary key and a foreign key column which shows on the child pop-up table, it is a waste of table space. I couldn't manage to hide these two columns if Pop-up source is set to _auto_.

@aeduard you can hide columns in layer properties -> Fields -> Configuration -> Do not expose via WMS

**Comment by Gustry** [comment]
Is this question still relevant ?
I used the compact way with hidden fields recently, without issues
