### ISSUE TITLE
page showing only projects for a given repository - ?repository=yourRepo

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1621]
> @nboisteault there is no page showing only projects for a given repository

if you try an url with `lizmap-web-client/lizmap/www/index.php/view/map/?repository=yourRepo`

you get:
![imagem](https://user-images.githubusercontent.com/10053874/81163156-383af900-8f86-11ea-847f-252b9ce0f1f3.png)

https://github.com/3liz/lizmap-web-client/issues/549

thanks

**Comment by Gustry** [comment]
This seems to be fixed : 

https://demo.lizmap.com/lizmap/index.php
https://demo.lizmap.com/lizmap/index.php?repository=miscellaneous

It would be nice to have an anchor when clicking on a title.
This link is available for admins in the map managment interface.
