### ISSUE TITLE
export non-spatial data table

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1623]
### What is the bug?
it's not possible to export non-spatial data table

### Screenshots and logs
lizmap log:

```
2020-05-06 16:01:12 xxx.xxx.xxx.xxx warning 2020-05-06 17:01:12 [2] file_get_contents(http://xxx.xxx.xxx.xxx/cgi-bin/qgis_mapserv.fcgi): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server
Error /var/www/html/lizmap-web-client-release_3_3/lizmap/modules/lizmap/classes/lizmapProxy.class.php 240
```
postgresSql log:
```
2020-05-06 15:56:12 WEST [11813-1] myName@databaseName LOG:  unexpected EOF on client connection with an open transaction
```

### Environment

 - Lizmap version: 3.3.6
 - QGIS Server version: 2.18
 - QGIS Project version: 2.18
 - OS (Windows, Linux, MacOS, Android…): linux
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? postgreSql

thanks

**Comment by Gustry** [comment]
Which format did you choose?

**Comment by josemvm** [comment]
XLSX, ODT or CSV

**Comment by Gustry** [comment]
I can't confirm, it's working for me if I choose formats supporting non spatial data : GPKG, CSV, XLSX ...
I'm using QGIS 3.

The only bug would be to hide formats not compatible such as SHP and others

**Comment by josemvm** [comment]
probably it's a bug on qgis server 2.18 or a lizmap one, in the way that lizmap deals with qgis server 2.18

i can confirm on qgis, evething works as expected!

**Comment by josemvm** [comment]
please can someone confirm this bug on qgis server 2.18 ?

thanks in advance

**Comment by pcav** [comment]
2.18 is end of life, better stop using it.
Cheers.

**Comment by josemvm** [comment]
:-) that's not the answer to my question...
the qgis server 2.18 is the qgis server minimum for lizmap 3.3

**Comment by josemvm** [comment]
unfortunately, this is a issue related to the qgis server 2.18

directly  when i request to qgis server, i get the following error from apache:
`mod_fcgid: error reading data, FastCGI server closed connection`

and from web browser:
`Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.`

**Comment by Gustry** [comment]
@josemvm Should we close this issue? QGIS 2 is not maintained since end 2018.

Related to my UX issue,  I think it should go WFS Output extension repository

**Comment by josemvm** [comment]
@Gustry 

> Should we close this issue?

yes, of course


> Related to my UX issue, I think it should go WFS Output extension repository

yes, i think it could be a good improvement!

thanks

**Comment by Abdelghafour1** [comment]
> s'il vous plaît quelqu'un peut-il confirmer ce bogue sur le serveur qgis 2.18?
> 
> Merci d'avance

je confirme ça , j'ai aussi le même problème avec qgis server 2.18, lors de l'export des table non spatiales vers XLS ou CSV.

y a t'il une solution pour ça ou non ?

**Comment by josemvm** [comment]
@Abdelghafour1 non, je pense qu'il n'y a plus de solution :-(

**Comment by Abdelghafour1** [comment]
Donc, je dois migrer vers qgis server 3

**Comment by Gustry** [comment]
Cela marche avec QGIS 3 apparemment. De notre côté, nous ne ferons pas de fix pour QGIS 2. Il est temps de migrer ;-)

**Comment by josemvm** [comment]
dans un cas particulier, pour contourner le problème, vous pouvez transformer la table non spatiale en table spatiale, en ajoutant une géométrie (par exemple un point) commune à toutes les lignes du tableau.

mais le mieux, sans aucun doute, comme le dit @Gustry, sera de migrer vers le serveur qgis 3

**Comment by Abdelghafour1** [comment]
j'ai déjà essayer de migrer vers qgis 3.x mais j'ai eu un problème de version de qgis server adéquate pour le desktop 3.4 (j'ai pas pu télécharger la version 3.4 de qgis server à partir de OSGEO4W ). comment régler ça? et merci pour votre aide.

**Comment by josemvm** [comment]
je ne peux pas vous aider car j'ai très peu d'expérience sur le serveur qgis fonctionnant avec windows

https://docs.lizmap.com/current/en/install/windows.html

**Comment by Gustry** [comment]
Sous Windows, je connais très peu aussi. Mais je suggère fortement de suivre le lien de @gioman https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by Abdelghafour1** [comment]
Merci beaucoup @josemvm et @Industrie
