### ISSUE TITLE
Lizmap issues 

### ISSUE THREAD

**Issue by jiptwo** [3liz/lizmap-web-client#1626]
Hello
I haven't really had conclusive answers on geoRezo
Here are the following points in order of importance that we have problems in lizmap that we miss on the web-client
1. The drop-down lists in the fields are not displayed in edition
2. Labels do not appear on vectors
3. The writing obligations in the fields are not displayed in edition
4. The printing tool does not appear even if it is checked in the lizmap plugin
5. The miniature map next to the scale is not displayed

I tried with chrome and microsoft edge ... same problem ...
Is qgis 3.6.0 the problem and do I need to install an earlier version?

Windows 10 pro
qgis 3.6.0
plugin lizmap 3.2 in qgis 3.6.0

Linux
pgadmin4/postgis2.5.1/postgres1.0
jancelin/docker-lizmap:3.2rc6 (RC for release candidate)
jancelin/docker-qgis-server:2.18LTR (LTR = Long time release)

Sorry for my english ... i speak french

JP

**Comment by Gustry** [comment]
> plugin lizmap 3.2 in qgis 3.6.0
> jancelin/docker-qgis-server:2.18LTR (LTR = Long time release)

Don't use QGIS Project made with QGIS 3 with a QGIS Server 2.X
It will solve issue 2 and maybe others too.

Il ne faut pas utiliser des projets fait avec QGIS 3 avec un QGIS Serveur 2.
il faut utiliser les mêmes versions. Cela va résoudre le problème 2 et aussi peut-être les autres.

**Comment by jiptwo** [comment]
Hello
with 2.18.14 qgis its works ... :)

Except on the following points
3.The writing obligations in the fields are not displayed in edition
5.The miniature map next to the scale is not displayed

jp

**Comment by Gustry** [comment]
> 3.The writing obligations in the fields are not displayed in edition

Is your layer stored in postgresql? Are fields setup correctly in the DB?


>  5.The miniature map next to the scale is not displayed
Did you follow https://docs.lizmap.com/next/en/publish/configuration/legend.html#create-an-overview-map ?

**Comment by jiptwo** [comment]
Super thank you ... the miniature map is functional!
For field bonds I thought it was qgis in the project file qgis the episode was managing…. But yes I am on postgresql…. This is my main database!
If I have to put a condition on the fields in the postgresql? ... how should I put take? If you have an info
Thank you!

Windows 10 Pro
QGIS 2.18.14
Plugin Lizmap 3.2 dans QGIS 2.18.14
Linux
pgadmin4 / postgis2.5.1 / postgres1.0
jancelin / docker-lizmap: 3.2rc6 (RC pour la version candidate)
jancelin / docker-qgis-server: 2.18LTR (LTR = Long time release)

Super merci … la carte miniature est fonctionnelle !
Pour les obligations de champs je croyais que c’était qgis dans le fichier projet qgis qu’il le gérait …. Mais oui je suis sur postgresql …. C’est ma base de données principale!
Si je dois mettre une condition obligation sur des champs dans postgresql ? ... Comment je devrais mis prendre? Si vous avez une info

Merci!

**Comment by Gustry** [comment]
> If I have to put a condition on the fields in the postgresql? ... how should I put take? 

What kind of condition?

**Comment by jiptwo** [comment]
The field should not be null on must fill ... or select the information in the drop-down list if it exists ... which I created from qgis 2.18.14
Le champs ne devrait pas être null on doit remplir… ou sélectionner l’info dans la liste déroulante si celle-ci existe …que j’ai créer a partir de qgis 2.18.14

**Comment by Gustry** [comment]
@jiptwo https://docs.lizmap.com/next/en/publish/configuration/layer.html#customize-the-edition-form

**Comment by jiptwo** [comment]
thanks :)
