### ISSUE TITLE
"filter data with form": wrong ordering of attributes where the first letter has an accent

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#1627]
LMWC 3.3.6 on QGIS Server 3.10

![Screenshot_20200507_115325](https://user-images.githubusercontent.com/1951107/81286927-cc29c500-9059-11ea-9c50-0e1174812f38.png)

**Comment by nboisteault** [comment]
Fixed with https://github.com/3liz/lizmap-web-client/commit/61d67f384a69bcc1bf074f157c5a7adfeeadd1e0
Thanks @gioman

**Comment by josemvm** [comment]
hi @nboisteault 
have you a fix for https://github.com/3liz/lizmap-web-client/issues/1517

thanks

**Comment by gioman** [comment]
@nboisteault @rldhont  thank to you guys!
