### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by c0debum** [3liz/lizmap-web-client#163]
Hi,

I successfully install the web client and decided to change the Admin account password, right after I attempted to log back in and I was not able to do so... So my question is, where can I change the password in the background? or, is there a way of escalating lizadmin account so it can become the new Admin?

**Comment by virtusmankind** [comment]
Is there any chance to allow user to auto-recover a lost password?

**Comment by Verticalsrl** [comment]
How did you solve it?
Tnx
andrea

**Comment by rldhont** [comment]
Enhancement has been merged. For those who make tests, installer.php has to be launch.
