### ISSUE TITLE
Hide NULL fields in lizmap popup

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1632]
### What is the bug?
When the attribute field is empty then the field does not appear (#174) but when the value is considered NULL then the field is displayed in Lizmap.

### Screenshots and logs
**Lizmap** 
<img width="865" alt="Capture d’écran 2020-05-09 à 17 07 55" src="https://user-images.githubusercontent.com/7761073/81477379-d5609080-9217-11ea-8856-e84c591879f3.png">

**QGIS**
<img width="407" alt="Capture d’écran 2020-05-09 à 17 06 45" src="https://user-images.githubusercontent.com/7761073/81477380-d72a5400-9217-11ea-8906-8d961c60033d.png">

### Environment
 - Lizmap version: 3.3.0
 - QGIS Server version: 3.4
 - QGIS Project version: 3.4.15
 - Browser (Firefox, Chrome…): Firefox

**Comment by mdouchin** [comment]
We should add a new checkbox in lizmap plugin popup configuration to let the map publisher if the auto popup should show or hide the fields with a Null or empty value, default to Yes.

**Comment by Gustry** [comment]
According to #3763 it seems the popup is no more showing NULL values.
