### ISSUE TITLE
PHP 7.4 instead of 7.3

### ISSUE THREAD

**Issue by catalinmiraute** [3liz/lizmap-web-client#1634]
Hello, I configured Lizmap web client and Qgis Server on a Windows Server using PHP 7.4 instead of 7.3 and now I have the following problem when I am trying to seed a cache for a layer I am getting 2 errors: 
1. Array and string offset access syntax with curly braces is deprecated....
2.  Too many parameters
Both of them are pointing to lines from jCmdUtils.class.php
I found an answer for the first: https://wiki.php.net/rfc/deprecate_curly_braces_array_access
But I have no ideea what to do.

**Comment by nboisteault** [comment]
@catalinmiraute why did you close ?

**Comment by catalinmiraute** [comment]
For the problem no 2 I found the problem: the name of the layer contained 2 words and I put it between qutation marks (""), like this: php lizmap/scripts/script.php lizmap~wmts:seeding -v -f montpellier "Layer Name" bus EPSG:3857 12 14

For the problem no 1, I replaced the content of the PHP74 directory with PHP73 files and worked just fine.

**Comment by catalinmiraute** [comment]
Does anyone know how to set the project to avoid duplicating the labels on each tile?

**Comment by catalinmiraute** [comment]
Regarding the duplicating the labels on each tile, I undestand that QGIS Server doesn't support metatiles natively, like Geoserver. What are the options in this case?

**Comment by rldhont** [comment]
@catalinmiraute lizmap can do it for you. You have to activate cache with metatile https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#in-detail-how-to-activate-the-caches
You also have to set label position in a way it is fixed.

**Comment by catalinmiraute** [comment]
> @catalinmiraute lizmap can do it for you. You have to activate cache with metatile https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#in-detail-how-to-activate-the-caches
> You also have to set label position in a way it is fixed.

Tks man, I missed that info while reading the documentation.

**Comment by catalinmiraute** [comment]
Does any one have any ideea how to obtain a permalink or a hyperlink in order that an object in the map to apear central positioned and selected?

**Comment by Gustry** [comment]
> Does any one have any ideea how to obtain a permalink or a hyperlink in order that an object in the map to apear central positioned

Generating the permalink doesn't work for that?

> selected?

This is not supported AFAIK
