### ISSUE TITLE
attribute table - order by column 

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1635]
hi

when n user loads a table in qgis desktop, the qgis desktop respects the order given by postgresql but lizmap not...

is this the desired environment in lwc?

thanks

**Comment by josemvm** [comment]
lizmap always sort by primary key

**Comment by aeduard** [comment]
I also have an issue, which partially connects here. I have a master-child table relation (1:N), where in the pop-up it would be important to order the child table rows by a specific column. Right now the order is mostly by save time, I mean the last edited row will appear first. It does not use primary key or any other column to order.

System> Ubuntu 16, PostgreSQL 9.5, Qgis Server 2.18 and Lizmap 3.2.

This would be a nice new feature to be able to set an order by column for child table. Should I open a new issue?
