### ISSUE TITLE
Lizmap dataviz HTML customizable

### ISSUE THREAD

**Issue by jiptwo** [3liz/lizmap-web-client#1636]
Bonjour
Dans la section dataviz du plugin Lizmap… est-ce que nous pouvons créer notre propre graphique avec l’aide du modèle de conteneur html dans le plugin lizmap
Présentement j’ai 4 graphiques … sauf que le 4ème est un nuage de points mais il ne représente pas bien ce que je veux produire
Présentement j’ai mis ce code pour produire 4 graphiques
Ma première problématique c'est que je ne suis pas en mesure d'identifier le nom de mon point par rapport a mes données X et Y dans mon graphique nuage
Et
[Permettre](url) d'avoir un axe X de 0 à 100 et un axe Y de 0 à 100

Hello
In the dataviz section of the Lizmap plugin… can we create our own graphic using the html container model in the lizmap plugin
Currently I have 4 graphics ... except that the 4th is a point cloud but it does not represent well what I want to produce
Currently I have put this code to produce 4 graphics
My first problem is that I am not able to identify the name of my point in relation to my X and Y data in my cloud graph
And
Allow to have an X axis from 0 to 100 and a Y axis from 0 to 100

```html
div class="container-fluid">
    div class="row-fluid">
        div class="span6">$0</div>
        div class="span6">$1</div>
    /div>
    div class="row-fluid">
        div class="span6">$2</div>
		div class="span6">$3</div>
    /div>
/div>
```

Windows 10 pro
qgis 2.18.14
plugin lizmap 3.2 in qgis 2.18.14
Linux
pgadmin4/postgis2.5.1/postgres1.0
jancelin/docker-lizmap:3.2rc6 (RC for release candidate)
jancelin/docker-qgis-server:2.18LTR (LTR = Long time release)

**Comment by Gustry** [comment]
Do you mean you have your own plotly code?
Or do you have an image?

We added some new features in LWC 3.4:
* Custom settings for plots : https://github.com/3liz/lizmap-plugin/pull/261
* New HTML plot : https://github.com/3liz/lizmap-plugin/pull/237

**Comment by jiptwo** [comment]
J’ai déjà un type de graphique avec image … mais au besoin je ferai développer un code 
Si on a l’option de créer notre propre graphique en 3.4 c’est super
Sauf que…
Je vois bien que dans 3.4 …que c’est la prochaine version qui s’en vient ... Mais est-ce que nous allons pouvoir migrer … car de notre côté nous utilisons linux docker avec postgresql/postgis… et nous pouvons juste être en version 2.18 serverqgis et 3.2 lizmap

I already have a type of graphic with image ... but if necessary, I will have a code developed
If we have the option to create our own graph in 3.4 it's great
Except that…
I can see that in 3.4 ... that it is the next version coming ... But will we be able to migrate ... in version 2.18 serverqgis and 3.2 lizmap
I leave you the versions of our products

Windows 10 Pro
QGIS 2.18.14
Plugin Lizmap 3.2 dans QGIS 2.18.14
Linux ubuntu1804
Docker 19.03.6 / postgis10.0-2.4
pgadmin4 / postgis2.5.1 / postgresql10.0
jancelin / docker-lizmap: 3.2rc6 (RC pour la version candidate)
jancelin / docker-qgis-server: 2.18LTR (LTR = Long time release)

**Comment by nboisteault** [comment]
You should and can update to last versions with docker images from [here](https://hub.docker.com/u/3liz).
