### ISSUE TITLE
Lizmap limit view goupe

### ISSUE THREAD

**Issue by jiptwo** [3liz/lizmap-web-client#1637]
Hello
Would there be a possibility in lizmap to limit the viewing of one or more layers for a group of users?

bonjour
Est-ce qu'il aurait une possibilité dans lizmap pour limiter la visualisation d'une ou plusieurs couches pour un groupe d'utilisateur?

Windows 10 pro
qgis 2.18.14
plugin lizmap 3.2 in qgis 2.18.14
Linux
pgadmin4/postgis2.5.1/postgres1.0
jancelin/docker-lizmap:3.2rc6 (RC for release candidate)
jancelin/docker-qgis-server:2.18LTR (LTR = Long time release)

**Comment by Gustry** [comment]
You maybe looking for this new feature in LWC 3.4 https://github.com/3liz/lizmap-plugin/pull/249 ?
In the meantime, did you try https://docs.lizmap.com/next/en/publish/lizmap_plugin/filtered_layers_login.html ? You can use the same user or group for all features.

**Comment by jiptwo** [comment]
ok thanks
