### ISSUE TITLE
QGIS project with a PostgreSQL layer

### ISSUE THREAD

**Issue by Nokram** [3liz/lizmap-web-client#1638]
Hello,

Setup : 
Windows 10 / Windows Server 2019
PostgreSQL 12 + PostGis 3
QGis 3.10.5 (last LTR) + QGis Server (last LTR)

I've already installed Lizmap several times since a month (first version 3.3.5, then today version 3.3.6) and I still have the same problem : 

I get a "Service Non Disponible" when I want to view a QGis project with only one layer stored in PostgreSQL. The loading is infinite. 

I specify that an identical project but with the .shp layer in the project folder works correctly. 

I suspect a problem with Lizmap's access to PostgreSQL but I don't know how to fix it.

______________________________________________

Bonjour,

Configuration : 
Windows 10 / Windows Server 2019
PostgreSQL 12 + PostGis 3
QGis 3.10.5 (dernière LTR) + QGis Server (dernière LTR)

J'ai installé déjà plusieurs fois depuis un mois Lizmap (d'abord la version 3.3.5, puis aujourd'hui la version 3.3.6) et j'ai toujours le même problème : 

J'obtiens une "Service Non Disponible" lorsque je veux visualiser un projet QGis comportant une seule couche stockée dans PostgreSQL. Le chargement est infini. 

Je précise qu'un projet identique mais avec la couche .shp dans le dossier du projet fonctionne correctement. 

Je suspecte un problème d'accès de Lizmap à PostgreSQL mais je ne sais pas comment résoudre le problème.

**Comment by Gustry** [comment]
How did you save your credentials (user/password) ? In the QGS file?
Do you have QGIS logs?

**Comment by Nokram** [comment]
Hi @Gustry , thanks for taking the time for me. 
_Bonjour Gustry, merci pour le temps que tu prends pour moi._ 

In QGis I connect to my database "Postgis_12" through the interface provided for this purpose and I save the connection information (see the image below).
_Dans QGis je me connecte à ma base de donnée "Postgis_12" par l'interface prévue à cet effet et j'enregistre les information de connexion (voir l'image ci-dessous)._ 

[https://prnt.sc/sfuuir](url)

The .qgs file, when I open it with notepad++ doesn't mention "user" and "password" but I find the authentication key visible in the image above.
_Le fichier .qgs, quand je l'ouvre avec notepad++ ne fait mention à aucun moment de "user" et "password" mais je retrouve la clé d’authentification visible dans l'image plus haut._ 

`    <layer-tree-layer legend_exp="" expanded="1" id="Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86" source="dbname='postgis_12' host=51.210.5.238 port=5432 sslmode=disable authcfg=15q4k51 key='id_0' srid=4326 type=MultiPolygonZ checkPrimaryKeyUnicity='1' table=&quot;public&quot;.&quot;Vaucluse&quot; (geom) sql=" providerKey="postgres" name="Vaucluse" checked="Qt::Checked">
      <customproperties/>`

My log of the QGis server when I try to load the project is just there :
_Mon log du QGis server quand je tente de charger le projet est juste là :_  

> 10:07:39 INFO Server[5848]: ******************** New request ***************
10:07:39 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?service=WMS&request=GetCapabilitiesAtlas&map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs
10:07:39 INFO Server[5848]: Environment:
10:07:39 INFO Server[5848]: ------------------------------------------------
10:07:39 INFO Server[5848]: SERVER_NAME: localhost
10:07:39 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?service=WMS&request=GetCapabilitiesAtlas&map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs
10:07:39 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:39 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:39 INFO Server[5848]: SERVER_PORT: 1991
10:07:39 INFO Server[5848]: QUERY_STRING: service=WMS&request=GetCapabilitiesAtlas&map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs
10:07:39 INFO Server[5848]: REQUEST_METHOD: GET
10:07:39 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:39 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:39 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:39 INFO Server[5848]: REQUEST:GetCapabilitiesAtlas
10:07:39 INFO Server[5848]: SERVICE:WMS
10:07:39 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:39 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:39 INFO Server[5848]: Request finished in 62 ms
10:07:41 INFO Server[5848]: ******************** New request ***************
10:07:41 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WMS&version=1.3.0
10:07:41 INFO Server[5848]: Environment:
10:07:41 INFO Server[5848]: ------------------------------------------------
10:07:41 INFO Server[5848]: SERVER_NAME: localhost
10:07:41 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0
10:07:41 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:41 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:41 INFO Server[5848]: SERVER_PORT: 1991
10:07:41 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0
10:07:41 INFO Server[5848]: REQUEST_METHOD: GET
10:07:41 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:41 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:41 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:41 INFO Server[5848]: REQUEST:GetCapabilities
10:07:41 INFO Server[5848]: SERVICE:WMS
10:07:41 INFO Server[5848]: VERSION:1.3.0
10:07:41 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:41 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:41 INFO Server[5848]: Request finished in 78 ms
10:07:41 INFO Server[5848]: ******************** New request ***************
10:07:41 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WMS&version=1.3.0
10:07:41 INFO Server[5848]: Environment:
10:07:41 INFO Server[5848]: ------------------------------------------------
10:07:41 INFO Server[5848]: SERVER_NAME: localhost
10:07:41 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0
10:07:41 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:41 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:41 INFO Server[5848]: SERVER_PORT: 1991
10:07:41 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0
10:07:41 INFO Server[5848]: REQUEST_METHOD: GET
10:07:41 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:41 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:41 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:41 INFO Server[5848]: REQUEST:GetCapabilities
10:07:41 INFO Server[5848]: SERVICE:WMS
10:07:41 INFO Server[5848]: VERSION:1.3.0
10:07:41 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:41 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:41 INFO Server[5848]: Request finished in 48 ms
10:07:42 INFO Server[5848]: ******************** New request ***************
10:07:42 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: Environment:
10:07:42 INFO Server[5848]: ------------------------------------------------
10:07:42 INFO Server[5848]: SERVER_NAME: localhost
10:07:42 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:42 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:42 INFO Server[5848]: SERVER_PORT: 1991
10:07:42 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: REQUEST_METHOD: GET
10:07:42 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:42 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:42 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:42 INFO Server[5848]: REQUEST:GetCapabilities
10:07:42 INFO Server[5848]: SERVICE:WMS
10:07:42 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:42 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:42 INFO Server[5848]: Request finished in 47 ms
10:07:42 INFO Server[5848]: ******************** New request ***************
10:07:42 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: Environment:
10:07:42 INFO Server[5848]: ------------------------------------------------
10:07:42 INFO Server[5848]: SERVER_NAME: localhost
10:07:42 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:42 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:42 INFO Server[5848]: SERVER_PORT: 1991
10:07:42 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WMS
10:07:42 INFO Server[5848]: REQUEST_METHOD: GET
10:07:42 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:42 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:42 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:42 INFO Server[5848]: REQUEST:GetCapabilities
10:07:42 INFO Server[5848]: SERVICE:WMS
10:07:42 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:42 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:42 INFO Server[5848]: Request finished in 47 ms
10:07:43 INFO Server[5848]: ******************** New request ***************
10:07:43 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WFS&version=1.0.0
10:07:43 INFO Server[5848]: Environment:
10:07:43 INFO Server[5848]: ------------------------------------------------
10:07:43 INFO Server[5848]: SERVER_NAME: localhost
10:07:43 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WFS&version=1%2E0%2E0
10:07:43 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:43 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:43 INFO Server[5848]: SERVER_PORT: 1991
10:07:43 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WFS&version=1%2E0%2E0
10:07:43 INFO Server[5848]: REQUEST_METHOD: GET
10:07:43 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:43 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:43 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:43 INFO Server[5848]: REQUEST:GetCapabilities
10:07:43 INFO Server[5848]: SERVICE:WFS
10:07:43 INFO Server[5848]: VERSION:1.0.0
10:07:43 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:43 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:43 INFO Server[5848]: Request finished in 63 ms
10:07:43 INFO Server[5848]: ******************** New request ***************
10:07:43 INFO Server[5848]: Request URL: http://localhost:1991/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ.qgs&request=GetCapabilities&service=WFS&version=1.0.0
10:07:43 INFO Server[5848]: Environment:
10:07:43 INFO Server[5848]: ------------------------------------------------
10:07:43 INFO Server[5848]: SERVER_NAME: localhost
10:07:43 INFO Server[5848]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WFS&version=1%2E0%2E0
10:07:43 INFO Server[5848]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
10:07:43 INFO Server[5848]: REMOTE_ADDR: ::1
10:07:43 INFO Server[5848]: SERVER_PORT: 1991
10:07:43 INFO Server[5848]: QUERY_STRING: map=C%3A%5CS%5CL%5Cdata%5Cprod%5Crep1%2FLIZ%2Eqgs&request=GetCapabilities&service=WFS&version=1%2E0%2E0
10:07:43 INFO Server[5848]: REQUEST_METHOD: GET
10:07:43 INFO Server[5848]: HTTP_ACCEPT: */*
10:07:43 INFO Server[5848]: HTTP_USER_AGENT: Lizmap
10:07:43 INFO Server[5848]: MAP:C:\S\L\data\prod\rep1/LIZ.qgs
10:07:43 INFO Server[5848]: REQUEST:GetCapabilities
10:07:43 INFO Server[5848]: SERVICE:WFS
10:07:43 INFO Server[5848]: VERSION:1.0.0
10:07:43 CRITICAL Server[5848]: Error, Layer(s) Vaucluse_29251077_9ea7_4f27_a6db_288ccbb38d86 not valid in project C:\S\L\data\prod\rep1/LIZ.qgs
10:07:44 WARNING Server[5848]: <ServerException>Layer(s) not valid</ServerException>

> 10:07:44 INFO Server[5848]: Request finished in 62 ms

**Comment by Gustry** [comment]
As you are using the authentication DB from QGIS, you need to setup the password in QGIS Server too : https://docs.qgis.org/3.4/en/docs/user_manual/auth_system/auth_workflows.html#qgis-server-support

But I think you will hit other issues with Lizmap if you enable more tools, like edition. With edition, and other tools, Lizmap will need access to the database using user/password. Lizmap is doing some queries straight to Postgresql (without using QGIS Server) and gets the credentials in the QGIS projects. @rldhont might confirm this? 

If you are using a plain text/password, it will work.

**Comment by Gustry** [comment]
If you don't want to add credentials in your QGIS Project, using PostgreSQL service file works well.
https://www.postgresql.org/docs/9.1/libpq-pgservice.html

Like:
```ini
[qgistest]
host=localhost
port=5432
user=etienne
dbname=qgistest
password=******
```

**Comment by Nokram** [comment]
I must admit that the first part of your answer takes me to the limit of my knowledge. 
However, I changed my method to use plain text/password and it finally worked.

I'll look at your suggestion about the PostgreSQL service next time, when I'll have a better understanding of all those tools needed to run a webgis. 

Many thanks to you. I will certainly come back to this topic if I have difficulties with the other solutions proposed.

______________

Je dois admettre que la première partie de votre réponse me pousse dans la limite de mes connaissances. 
Ceci-dit, j'ai changé de méthode pour utiliser le plain text/password et ça a enfin fonctionné.

Je me pencherai sur ta remarque concernant le service PostgreSQL une prochaine fois, quand j'aurai mieux en mains l'ensemble de ces outils qui servent à faire tourner un websig 

Un grand merci à vous. Je reviendrai certainement vers ce topic si jamais j'éprouve des difficultés avec les autres solutions proposées.

**Comment by virtusmankind** [comment]
Hello everybody, i'm still in trouble with db authentication and postgresql layer. I set up my project with all postgresql layers on qgis 3.10 and create the repository in lizmap 3.3 (running on qgis server 2.18). I'm still not able to show layers in my map and edit a table layer. In qgis log I obtain the following: "_ERROR: Master password: FAILED to access database_"
Any help?

**Comment by Gustry** [comment]
> ERROR: Master password: FAILED to access database

You used the master password authentication.
Everything is written above https://github.com/3liz/lizmap-web-client/issues/1638#issuecomment-627872662

**Comment by virtusmankind** [comment]
> > ERROR: Master password: FAILED to access database
> 
> You used the master password authentication.
> Everything is written above [#1638 (comment)](https://github.com/3liz/lizmap-web-client/issues/1638#issuecomment-627872662)

The strange behaviour is that some layers in PG are rendered in maps, but most of them in the same projects are not rendered. 
I cannot understand why. In this moment using plain text/password could be a good solution, later I will try to set "master password authentication" (I think I should set something in my server configuration to make master password working).

Thanks

**Comment by Gustry** [comment]
> The strange behaviour is that some layers in PG are rendered in maps, but most of them in the same projects are not rendered.

Check in the QGS file if some layers are using service OR user/pass OR master password. They may don't have all the same configuration.
Changing the configuration in the datasource manager will **only** affect newly added layers.

> In this moment using plain text/password could be a good solution, later I will try to set "master password authentication" (I think I should set something in my server configuration to make master password working).

Yes, but as mentionned, you won't be able to do edition for instance in LWC. Because Lizmap won't be able to connect to the database. Only the display will work.

**Comment by virtusmankind** [comment]
Working on the project I just found the issue is in the "Scale dependent visibility" option. If toggled, Lizmap don't display the layer on the map. 
I need to display layers based on scale!!!
Is it a known issue of QGis/Lizmap/QGis server version?

**Configuration:**
_Debian 8.7 (jessie) server
PostgreSQL 9.6.2 + PostGis 2.32 
QGis 3.10.11 (LTR) + QGis Server 2.18_

**Comment by Gustry** [comment]
> QGis 3.10.11 (LTR) + QGis Server 2.18

You will just hit a lot of issues if you are running a so different QGIS Server version.
QGIS Server 2.18 is not designed to read Project written in the future with Desktop 3.10 !

**Comment by Gustry** [comment]
I think I can close this ticket, because of the latest feature in the plugin to allows you or not to use the QGIS authentication DB, allows you to use PG service or not. This is a first step, this new panel will be improved later.
