### ISSUE TITLE
Selection tool - no data export

### ISSUE THREAD

**Issue by Polytrauma83** [3liz/lizmap-web-client#1639]
Hi,

in the selection pane in 3.4.0-pre, there is no reaction when I do export -> file format. A download of the selected features in "layers" or "data" (attribute table) works perfectly. I use the plugin wfsOutputExtension for extended file formats. No error in log, just nothing happens as far as i can tell.

Specs:
Lizmap 3.4.0-pre
Postgres 12
QGIS 3.12.0 + Server
Ubuntu 18.04

**Comment by nboisteault** [comment]
@Polytrauma83 Thank you for your report. I can reproduce the issue. I'll fix it soon.

@rldhont @mdouchin If a selection is made on multiple layers should we disable the export button or allow as much export as there are layers selected.

**Comment by nboisteault** [comment]
@rldhont @mdouchin If a selection is made on multiple layers should we disable the export button or allow as much export as there are layers selected.

**Comment by mdouchin** [comment]
I would allow export for only one layer.
If the combo is on "all layers" we should warn thé user with adequate message such as "please select one of the layers " or similar...
