### ISSUE TITLE
Where has "Landing page" section gone in LWC 3.3.6 ?

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#1642]
Hi, I've done a fresh install of latest stable build 3.3.6 but no "Landing page" section appears inside Dashboard.
I've just copied jauth.db and logs.db from previous installed release but I don't think that could be the problem...
Is it just me not able to write a welcome message and some instructions for the visitors?
Do I have to enable/configure something else?
Thanks

**Comment by nboisteault** [comment]
Landing page configuration is in master and will be in future 3.4.

**Comment by paolo73an** [comment]
Ok. you can close this question, thanks (i had master version before and thought to have missed something :-)) thanks
