### ISSUE TITLE
Geolocation doesn't work in LWC master

### ISSUE THREAD

**Issue by paolo73an** [3liz/lizmap-web-client#1643]
### What is the bug?
Geolocation is not correct in LWC master (alpha2 - may 13th 2020)

### Steps to reproduce the issue

1. Go to project
2. Click on geolocation button
3. After starting geolocation, gps point is not set correctly on map

### Expected behavior
I'd expect gps point to be set correctly on map (as it is with LWC 3.3.6 for istance)

### Environment

 - Lizmap version 3.4.0 pre alpha2 may 13th 2020: 
 - QGIS Server version: 3.12
 - QGIS Project version: 3.12.2
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 18.04 LTS
 - Browser (Firefox, Chrome…): Mozilla Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite

**Comment by nboisteault** [comment]
Do you have an error in your browser console ?

**Comment by ocelot73** [comment]
Yes, after pressing "Start" button in geolocation panel, the map is zoomed in a wrong area and inside the console the following error appears:

TypeError: t is nulltransforms.js:57:7
    kt transforms.js:57
    qt proj.js:410
    Bt proj.js:427
    get position Geolocation.js:96
    t lizmap.js:96
    n Geolocation.js:27
    connectedCallback Geolocation.js:36
    dispatch EventDispatcher.js:141
    forEach self-hosted:225
    dispatch EventDispatcher.js:129
    Ue Geolocation.js:52
    dispatchEvent Target.js:115
    notify Object.js:154
    set Object.js:173
    positionChange_ Geolocation.js:186
    <anonima> self-hosted:844

**Comment by nboisteault** [comment]
I can't reproduce your issue with master branch. Do you have a public link to share to watch your issue?

**Comment by ocelot73** [comment]
I've tries to reproduce my issue with LWC master branch using a test website where I've published 2 projects: each with one OSM tile layer as basemp and with one Postgresql/Postgis vector layer.
Link is [www.qgis-server.cloud](https://www.qgis-server.cloud)
One project and its layers are all in EPSG:3857 and the other project and its layers are all in EPSG:3004.
With LWC master geolocation only works properly with EPSG:3857, in the project with EPSG:3004 after starting geolocation no point mark appears, but since in the other "main" website I use to publish projects the preferred CRS is 3004 I wrote this post to ask for help.
With Lizmap 3.3.6 geolocation works properly with both CRSs

**Comment by paolo73an** [comment]
@nboisteault I've tries to reproduce my issue with LWC master branch (may, 13th 2020 version) using a test website where I've published 2 projects: each with one OSM tile layer as basemp and with one Postgresql/Postgis vector layer.
Link is [www.qgis-server.cloud](https://www.qgis-server.cloud)
One project and its layers are all in EPSG:3857 and the other project and its layers are all in EPSG:3004.
I've noticed the with LWC master geolocation only works properly with EPSG:3857, in the project with EPSG:3004 after starting geolocation no point mark appears and map is zoomed in a wrong location, but since in the other "main" website I'm using to publish projects the preferred CRS is EPSG:3004 I wrote this post to ask for help.
With Lizmap 3.3.6 geolocation works properly with both CRSs

**Comment by nboisteault** [comment]
Thank you for your link, it helps a lot. I'm investigating.

**Comment by nboisteault** [comment]
@rldhont @mdouchin I have to deal with reprojection in OL6. Should we load mostly used projection code and let users add some more if needed (as we do now). Or should we load projection code with epsg.io like in [this example](https://openlayers.org/en/latest/examples/reprojection-by-code.html) ?

**Comment by nboisteault** [comment]
@paolo73an I have commited a0d8f4aa804b97ea7e329b59f9a90994116e5350. Can you test master branch and close issue if issue is fixed please ?

**Comment by paolo73an** [comment]
YEEEEESSSS. Issue fixed. Thank you very much @nboisteault !!!!
