### ISSUE TITLE
Problem with diacritics in labels

### ISSUE THREAD

**Issue by catalinmiraute** [3liz/lizmap-web-client#1644]
Hello, I have problems with Romanian diacritics in **labels**. In popup there are no problems.
Also in the qgs map document when is loaded in QGIS.
To be more precise, there are problems with the letters "ă" and "ţ".
I have tryied with Romanian Standard and Romanian Legacy keyboard.
Tks!

**Comment by nboisteault** [comment]
Please provide a screenshot.

**Comment by catalinmiraute** [comment]
> Please provide a screenshot.

![QGIS](https://user-images.githubusercontent.com/48051678/81919652-c8a9b700-95e0-11ea-91f9-a73e190ce4f3.png)
![LWC](https://user-images.githubusercontent.com/48051678/81919676-d19a8880-95e0-11ea-8b58-a6d6fcb554b9.png)

**Comment by Gustry** [comment]
> Hello, I have problems with Romanian diacritics in labels.

If it's in labels, then the issue is coming from QGIS Server, no?
Please follow the ticket template provided, so we could know which QGIS Desktop/Server version you are using too.

**Comment by Gustry** [comment]
According to your screenshots, the rendering is the same between QGIS Desktop and Lizmap, right?
Do you mean you have an encoding problem in QGIS Desktop? Is the issue with the field name or with its value?

**Comment by catalinmiraute** [comment]
I am using QGIS Desktop 3.12.2.
The problem apears only in LWC, on labels, with letters "ă" and "ţ".
The data are stored in MS SQl DB.

**Comment by Gustry** [comment]
It's not an issue with LWC. You would have the same issue if you load the WMS in QGIS Desktop.
Your popup is fine. The issue is with QGIS Server, providing the tiles.

Did you look your font on the server?

**Comment by ygorigor** [comment]
@catalinmiraute it's an encoding issue. Change the font of the labels in QGIS Desktop

**Comment by catalinmiraute** [comment]
> @catalinmiraute it's an encoding issue. Change the font of the labels in QGIS Desktop

I used Arial, than Calibri and nothing happened.
Can you give precise info what to change/check?

**Comment by catalinmiraute** [comment]
> It's not an issue with LWC. You would have the same issue if you load the WMS in QGIS Desktop.
> Your popup is fine. The issue is with QGIS Server, providing the tiles.
> 
> Did you look your font on the server?

I am new in using QGIS Server and I have no idee where to look.
Can you help me ?

**Comment by ygorigor** [comment]
@catalinmiraute first provide the info on which OS is running your applications.

**Comment by catalinmiraute** [comment]
> @catalinmiraute first provide the info on which OS is running your applications.

Windows Server 2019 Standard

**Comment by ygorigor** [comment]
all of them?

**Comment by catalinmiraute** [comment]
> all of them?

Yes, I am testing and I put QGIS Desktop, Server and DB here

**Comment by ygorigor** [comment]
I had some similar issues. My QGIS Deskop is on Windows, LWC and QGIS Server are on linux. After font change all was OK. In your case I'm not sure then.

**Comment by catalinmiraute** [comment]
I solved the problem like this:
in the file php73.conf from location 
..\Apache24\conf\extra
I insert the following line that points to Windows Fonts:
DefaultInitEnv QT_QPA_FONTDIR "C:\Windows\Fonts"

**Comment by nboisteault** [comment]
Thank you for your feedback.
