### ISSUE TITLE
column not null bug

### ISSUE THREAD

**Issue by jiptwo** [3liz/lizmap-web-client#1645]
hi
I was mentioned in a question asked on this forum ... to add the not null constraint from postgis / postgresql
I checked the not null constraint button in column property in pgadmin… from where I put an info… I refreshed on my table… it puts a star on my web client but even if I have put an info in my box ... the polygon is not displayed during registration!
Even all of my polygons in my table are gone
In my table ... create a polygon geometry and the info in my box is there! Even my old polygons
I even tried to add in qgis 2.18.14 to check the not null in the box ... but the display of the polygon and all my polygons in my table still does not appear
Even if I put everything as before in my table and qgis ... nothing is displayed ...
I even did a refresh on my table
I have a problem there…. It’s like lizmap no longer recognizes geometry

lizmap 3.2
qgis 2.18.14

On m’a mentionné dans une question posée sur ce forum... de rajouter la contrainte not null à partir de postgis/postgresql
J’ai cocher le bouton de la contrainte not null dans propriété de la column dans pgadmin …d’où je mets une info …j’ai fait refresh sur ma table … il se met une étoile sur mon webclient mais même si j’ai mis une info dans ma case ... le polygone ne s’affiche pas lors de l’enregistrement!
Même tous mes polygones dans ma table ont disparu
Dans ma table ... il créer une géométrie polygone et l’info mis dans ma case est là! Même mes anciens polygones
J’ai même essayé de rajouter dans qgis 2.18.14 de cocher le not null dans la case... mais l’affichage du polygone et de tous mes polygones de ma table ne s’affiche toujours pas 
Même si je remets tout comme avant dans ma table et qgis… rien ne s’affiche … 
J’ai même fait un refresh sur ma table
J’ai un problème là…. C’est comme si lizmap ne reconnait plus les géométries

lizmap 3.2
qgis 2.18.14

**Comment by nboisteault** [comment]
Please provide a clear step by step way to reproduce your issue with a bullet list.

**Comment by jiptwo** [comment]
I want to put a constraint (not null) on fields in lizmap .. I was told to directly pass the non null in postgis / postgres ..
when I put the not null on my existing table column in postgis / postgres ... I have the constraint in lizmap which is displayed with a star .. but the polygons do not appear in my lizmap .. mes la column geometry in my table has a value ...

**Comment by Gustry** [comment]
You mean your polygon is not displayed after pressing the "save" button?
but in the DB, the geom field is not empty, right?
and when you open enable/disable the layer, everything is back to normal?

**Comment by jiptwo** [comment]
bug in postgresql .. it's correct ... sorry for my return
