### ISSUE TITLE
Cache management not working

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#1646]
I've set a Redis server working in localhost:6379 for cache management of layers served with Lizmap web client.
In the "cache directory field" inside Lizmap dashboard, do I have to set a whatsoever folder with write permission or do I have to put the directory where redis server stores its database (/var/lib/redis) ?.
I've tried in both cases and just for a test I've also done cache seeding of some Postgis layers used as base map that ended successfully with tiles saved, but when I open a lizmap project in a web browser, the map is showing up very slowly with tiles appearing progressively very slowly and not all at once (more or less) as I expected.
I'm experiencing that server side cache management with tiles pre-generated and served in a Redis database is slower than "single image" option and it sounds strange.
I've tried various optimizations suggested in lizmap documentation (using jpeg format for basemaps, using png with lower depth, simplifying PG layers according to zoom level, etc...) but the map shows slower than if I use cache with files and just single image (no server cache tiles).
Can you please explain to me the best way to setup lizmap with redis server ?
Thanks

**Comment by ygorigor** [comment]
@ocelot73 did you set cache for layers in lizmap plugin?

**Comment by ocelot73** [comment]
Yes I did, infact I've manage to successfully do cache seeding.

**Comment by ygorigor** [comment]
You can type in terminal `redis-cli`, and then `monitor`, and when you will browse your map you will see if cache are working.

**Comment by ocelot73** [comment]
If I type redis-cli monitor it appears an "OK" message but if I open and zoome the map no further messages appear so I've realized redis-server is not correctly setup (but if I type 
But apart from setting address and port configuration inside lizmap administration dashboard what else do I have to set up? I haven't found useful documentation about it....
If I type redis-cli INFO it appears following information (the db size's number equals the total number of tiles pre generated with seeding):

# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9435c3c2879311f3
redis_mode:standalone
os:Linux 4.15.0-99-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.4.0
process_id:5154
run_id:00207afaff81d1d561d5879bdd372253fd6fd85c
tcp_port:6379
uptime_in_seconds:287
uptime_in_days:0
hz:10
lru_clock:12462455
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:108853128
used_memory_human:103.81M
used_memory_rss:112812032
used_memory_rss_human:107.59M
used_memory_peak:108853128
used_memory_peak_human:103.81M
used_memory_peak_perc:100.00%
used_memory_overhead:1576678
used_memory_startup:782504
used_memory_dataset:107276450
used_memory_dataset_perc:99.27%
total_system_memory:8364208128
total_system_memory_human:7.79G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:402653184
maxmemory_human:384.00M
maxmemory_policy:allkeys-lru
mem_fragmentation_ratio:1.04
mem_allocator:jemalloc-3.6.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1589520472
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:2
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:31
total_net_output_bytes:5
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:cb41cd2ce7b95ba5243a4366e3344af82a6633af
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.42
used_cpu_user:0.53
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db1:keys=15336,expires=0,avg_ttl=0

What can you suggest me to correctly configure Redis server to work with Lizmap web client ??
Thanks

**Comment by ygorigor** [comment]
How did you set it in lizmap?

**Comment by ocelot73** [comment]
I've just set the following values inside Lizmap administration dashboard (Italian language):

Tipo di archiviazione per la cache sul Server	**Redis**
Cartella per la cache	**/home/qgis/cache/** (but I've tried with **/var/lib/redis** , too)
Server Redis	**localhost**
Porta Redis		**6379**
Indice del database Redis	**1**
Prefisso della chiave Redis	**c**

**Comment by ygorigor** [comment]
in my case the cache root dir is set to `/tmp/`

**Comment by ocelot73** [comment]
EPSG:3857

**Comment by ygorigor** [comment]
@ocelot73 I use cache only for layers with allot of data, and which data will not changing in time.
Yes, with cache enabled, layers are loading more quickly.

**Comment by ocelot73** [comment]
But can anyone suggest me how to make Redis work properly with Lizmap ?

**Comment by ocelot73** [comment]
I've tried also with a fresh install of LWC master branch but Lizmap seems not able to work with/connect to Redis server only with setting up redis server info inside lizmap administration dashboard..

**Comment by ocelot73** [comment]
I've found that server caching is not working (at least with postgis layers) not only with Redis but neither with "Sqlite" nor "Files".
databases of file folders are created but no files are written and db files' size doesn't increase and, most of all, map tiles are loaded very slowly.

**Comment by ygorigor** [comment]
@ocelot73 did you run this command after all setup?
`lizmap/install/set_rights.sh www-data www-data`

**Comment by paolo73an** [comment]
Yes I did. But cache doesn't work either.

**Comment by paolo73an** [comment]
Yes I did. But cache doesn't work either.

**Comment by ocelot73** [comment]
@ygorigor yes I did but cache doesn't work either.
