### ISSUE TITLE
[Warning] session_set_cookie_params(): Unrecognized key 'expires' found in the options array	/lizmap_web_client/lib/jelix/core/jSession.class.php	55

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1648]
### What is the bug?
I found in Lizmap logs : 

`2020-05-19 15:38:30	10.0.2.2	warning	2020-05-19 15:38:30	[2]	session_set_cookie_params(): Unrecognized key 'expires' found in the options array	/lizmap_web_client/lib/jelix/core/jSession.class.php	55`

This might be linked to **PHP 7.4**

### Steps to reproduce the issue

1. Go on whatever the page

### Environment

 - Lizmap version: 3.3.7-pre
 - QGIS Server version: 3.10
 - QGIS Project version: 3.10
 - OS (Windows, Linux, MacOS, Android…):  Linux
 - Browser (Firefox, Chrome…): Chrome
- **PHP 7.4**

**Comment by aeduard** [comment]
I can confirm this error also on lizmap 3.3.6

**Environment**
    Lizmap version: 3.3.6
    QGIS Server version: 3.10
    QGIS Project version: 3.10
    OS (Windows, Linux, MacOS, Android…): Linux
    Browser (Firefox, Chrome…): Firefox
    PHP 7.4

**Comment by laurentj** [comment]
It was fixed with 253f3d73c9d546142ac7873ad5371722592fc74c
