### ISSUE TITLE
support virtual layers

### ISSUE THREAD

**Issue by gubuntu** [3liz/lizmap-web-client#1649]
### Is your feature request related to a problem? Please describe
a virtual layer in the QGIS project breaks LizMap (3.3)

not sure if this should be a bug or a feature request - to support virtual layers.

**Comment by Gustry** [comment]
Any example of a breaking virtual layer?
Virtual layers are supported already.

**Comment by dmarteau** [comment]
Cc @dmarteau

**Comment by Gustry** [comment]
@gubuntu Tell us also which QGIS Server you are using?
@dmarteau Maybe some rights writing the sqlite in pyqgis server? I think @gubuntu is using it.
