### ISSUE TITLE
Make Lizmap cope with recent GetPrint legend fix in QGIS server

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#165]
Hi there guys,
thanks for the fix

https://github.com/qgis/QGIS/commit/7c735213ca54371f10881856ebac767dbcc878c4

in qgis server, that was hurting a lot.

There is one thing that anyway should be fixed in Lizmap: right now in Lizmap (2.11 at least) when printing the GetPrint parameters

&map0:LAYERS=

and 

&LAYERS=

are passed the *same* list of layers, the ones are active in the table of contents and the legend is built accordingly.

Now with your fix is possible to successfully use the legend configuration "map=none" in QGIS print composer to achieve "static" legends, regardless of what layers are active in the toc.

So the

&LAYERS=

parameter must always be completed with the complete list of layers that are in the legend as defined in the qgis project.

Moreover I spotted this

https://github.com/qgis/QGIS/commit/7c735213ca54371f10881856ebac767dbcc878c4#commitcomment-11781046

so at this moment if a user (using qgis server master) will set the legend as "map=none" printing will work in Lizmap only by chance, just in the cases the layers in the legend are also active in the toc, otherwise printing will hang.

Cheers!

**Comment by gioman** [comment]
Example: say you have a project with 3 layers A,B,C,D,E... and the legend has only A and B, is set to map=none, auto update OFF and filter OFF. If you try to print and by chance you have A and B active, then it will work, if you don't have A and B active, then printing will hang. This because &LAYERS= must be "&LAYERS=A,B ", where of course "&map0:LAYERS=" can have any list of layers in the project, the one you actually want to print as part of the map.

**Comment by rldhont** [comment]
I'm not sure to understand your request.

The LAYERS parameter has to list all the layers will be used in the mapComposerss. For exemple if you have to maps map0 and map1 (the overview), the layers parameter will be the concatenation of map0:layers  and map1:layers.

Before my fix, legendComposers was linked to LAYERS because they reused the ones in maps. legendComposers with map=none are free of LAYERS parameter.

**Comment by gioman** [comment]
Hi again @rldhont let me check it, I may have overlooked something. Cheers!

**Comment by gioman** [comment]
Hi @rldhont forget about "&map0:LAYERS=" in my description, I had got it wrong and that lead me to not understanding correctly the issue. Regardless of that  I still see a problem when using a "map=none" in the legend of a print layout together with qgis server master (or 2.10 now). See this two services

http://193.136.216.94/lm211_tests/lizmap/www/index.php/view/

http://193.136.217.85/lm211_tests_master/lizmap/www/index.php/view/

the first uses qgis server 2.8.2 the second master. Both contain two copies of the same project, one has a layout with a legend set to map=map0 and the other set to map=none. On qgis server master when printing the project that has the layout with the legend set to map=none the pdf creation hangs if you don't have all the layers active (so if you don't pass in the url LAYER parameter the complete list of layers that are in the composer legend).

**Comment by rldhont** [comment]
Did you test the request directly in QGIS-Server ?

In my environment, I don't have this issue. I think it can be a timeout issue.

**Comment by gioman** [comment]
@rldhont yes, it hangs also when requesting directly, see

http://193.136.217.85/cgi-bin/qgis_mapserv.fcgi?map=/var/www/html/lm211_tests_master/lizmap/install/qgis/prj290.qgs&service=WMS&VERSION=1.3&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:3763&DPI=300&TEMPLATE=test_layout_legend_map_none&map0:extent=-239795.308000505,-389632.89329657354,132713.64979690503,-9623.755140826455&map0:scale=2500000&map0:grid_interval_x=50000&map0:grid_interval_y=50000&map0:LAYERS=layer1,layer2&LAYERS=layer1

what timeout should I check, apache? is already set to 300 seconds.

**Comment by gioman** [comment]
This should be closed, is not a LM problem it should be a qgis server one ( @rldhont I see the hang problem on getprint and map=none on any qgis server master/2.10 I have tested so far)  , see also https://github.com/qgis/QGIS/commit/7c735213ca54371f10881856ebac767dbcc878c4#commitcomment-11781046

**Comment by rldhont** [comment]
I don't have this issue with my own QGIS-Server.

**Comment by gioman** [comment]
@rldhont desperate to troubleshoot I have tested on qgis server on Windows (yikes) and as a matter of fact it works (but the request has to be done twice because the first time it crashes, only happens when map=none). Now I just need to understand why on Ubuntu server does not. Ideas?
