### ISSUE TITLE
popup.tpl XML Error Using default template (popupDefaultContent)

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1650]
### What is the bug?
In firefox and Chrome, if I use the QGIS Popup option my browser (firefox) returns the XML error (that causes a Javascript error) below :

```
Erreur d’analyse XML : données incompréhensibles après l’élément de document
Emplacement : http://localhost/lizmap/index.php/view/map/?repository=my_repo&project=my_project
Numéro de ligne 2, Colonne 5 : map:2:5
TypeError: layer.addFeatures is not a function
```

By looking at the template (popup.tpl) it looks like to be valid the dom section should be integrated inside a node (ex:<div>/div>) : 

```
<div>
    <h4>{$layerTitle}</h4>
    <div class="lizmapPopupDiv">
    {$popupContent}
    </div>
</div>
```

### Steps to reproduce the issue

1. In firefox or chrome open a Lizmap project with a layer with a QGIS popup 
2. Click on a feature
3. XML and Javascript error are displayed

### Environment

 - Lizmap version: tested on 3.3.0 and 3.4.0-pre
 - QGIS Server version: ≥ 3.0
 - QGIS Project version: ≥ 3.0
 - OS : Ubuntu 
 - Browser (Firefox, Chrome…): Firefox & Chrome

**Comment by Gustry** [comment]
Is this still valid ?

If I remember correctly, you are adding a QGIS server plugin at that time updating the GetFeatureInfo ?
