### ISSUE TITLE
Loading map data screen and then it freezes

### ISSUE THREAD

**Issue by baradgeo** [3liz/lizmap-web-client#1654]
Upto the index.php page it loads nicely. 
![main](https://user-images.githubusercontent.com/47609439/82981034-8fbe0900-a008-11ea-9251-755492cc10e1.PNG)
After that when I click on "Load the map", then this appears and the page stage there.
![main2](https://user-images.githubusercontent.com/47609439/82981113-cb58d300-a008-11ea-92ae-c70e98dba117.PNG)

Please help..

Here is a error log:

2020-05-27 07:41:15	::1	warning	2020-05-27 07:41:15	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=C%3A%5Cwebserver%5Cwww%5Clizmap%5Clizmap%5Cinstall%5Cqgis%2Fmontpellier%2Eqgs&amp;request=GetCapabilities&amp;service=WFS&amp;version=1%2E0%2E0): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
	C:\webserver\www\lizmap\lizmap\modules\lizmap\classes\lizmapProxy.class.php	240

2020-05-27 07:41:15	::1	error	GetCapabilities empty data
2020-05-27 07:41:19	::1	warning	2020-05-27 07:41:19	[2]	session_set_cookie_params(): Unrecognized key 'expires' found in the options array	C:\webserver\www\lizmap\lib\jelix\core\jSession.class.php	55

**Comment by ygorigor** [comment]
@baradgeo did you setup qgis server?

**Comment by baradgeo** [comment]
> @baradgeo did you setup qgis server?

when i run "http://localhost/qgis/qgis_mapserv.fcgi.exe", I am getting this..

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
<ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>
</ServiceExceptionReport>

That means it is working. Right??

**Comment by Gustry** [comment]
Are you sure about the QGIS-Server URL in your lizmap settings?

> when i run "http://localhost/qgis/qgis_mapserv.fcgi.exe", I am getting this..

versus

> 2020-05-27 07:41:15 ::1 warning 2020-05-27 07:41:15 [2] file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=C%3A%5Cwebserver%5Cwww%5Clizmap%5Clizmap%5Cinstall%5Cqgis%2Fmontpellier%2Eqgs&amp;request=GetCapabilities&amp;service=WFS&amp;version=1%2E0%2E0): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

It's different

**Comment by ygorigor** [comment]
@baradgeo you can try this `http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`
to know for sure

**Comment by baradgeo** [comment]
I tried this "http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities", getting 
![main3](https://user-images.githubusercontent.com/47609439/82986634-d402d680-a013-11ea-8c41-55a1f2ab118a.PNG)

I am new to this. Please help. I just followed  this link. https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows 
I don't know what i am doing wrong.

**Comment by ygorigor** [comment]
@baradgeo in lizmap you have to change `http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?` to `http://localhost/qgis/qgis_mapserv.fcgi.exe?`

**Comment by baradgeo** [comment]
Yes, It worked finally. Thanks guys. Really appreciate it.

**Comment by Gustry** [comment]
Nice.
Maybe the default setting should be changed in the configuration @gioman ?
