### ISSUE TITLE
upload de fichier 

### ISSUE THREAD

**Issue by remichairat** [3liz/lizmap-web-client#1655]
Bonjour, 

je rencontre un problème sur mes projets Lizmap, en effet lors de mes uploads de photo dès que le photo dépasse les 100 Ko et que je veux sauvegarder le projet ce met a charger indéfiniment, je tiens a préciser que mon php.ini a bien était configuré : 

`; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; http://php.net/post-max-size
post_max_size = 10M`

`; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 20M
`
je ne comprend pas ce chargement infini pour des petit fichier comme ceux-la.

merci pour vos réponses

**Comment by nboisteault** [comment]
Bonjour,
Qu'y a-t-il dans vos logs ?

**Comment by remichairat** [comment]
Bonjour, 
je viens de regarder dans mes log et malheureusement il n'y a rien car ça ne bug pas juste ça charge indéfiniment.

**Comment by nboisteault** [comment]
Et dans la console du navigateur ?

**Comment by remichairat** [comment]
URL de la requête :http://lizmap.crige-paca.org/lm/index.php/lizmap/edition/saveFeature
Méthode de la requête :POST
Adresse distante :91.206.199.181:80
Code d’état :
500
Version :HTTP/1.1
Politique de référent :no-referrer-when-downgrade
dans la console le seul endroit ou je trouve une erreur quand je veux enregistrer c'est ici mais je suis pas sur de bien comprendre le message d'erreur

**Comment by remichairat** [comment]
alors dans le log de apache2 j'ai trouver ça : 
`[Wed May 27 09:39:49.964156 2020] [fcgid:warn] [pid 14390:tid 140622914561792] [client 193.252.0.24:1389] mod_fcgid: HTTP request length 134606 (so far) exceeds MaxRequestLen (131072), referer: http://lizmap.crige-paca.org/lm/index.php/view/map/?repository=sarf05&project=sarf05`

**Comment by nboisteault** [comment]
Voilà la restriction de taille de fichier doit être modifiée pour Apache2.

**Comment by remichairat** [comment]
ok par contre c'est dans le fichier mod_fcgid que je trouve cette restriction ?

**Comment by remichairat** [comment]
ok pour moi je viens de finir par comprendre il fallais ajouter la clause MaxRequestLen 15728640 dans mod_fcgid qui limite la taille des fichiers maintenant cela fonctionne merci pour ton aide nboisteault
