### ISSUE TITLE
Attribute table functionality stopped to work (using qgis server master)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#166]
If using Lizmap 2.11 and QGIS server master the "attribute table" functionality stopped to work. You can test easily with the Lizmap demo projects. I filed the ticket here but I'm unsure if is a QGIS server or something that need to be updated in Lizmap. If is a QGIS server issue please close this. Cheers!

**Comment by JogicPogic** [comment]
It's similar to my case #186

**Comment by rldhont** [comment]
Did you use curl for sending request to QGIS Server ?
Can you test Send request to QGIS Server with php ?

**Comment by gioman** [comment]
Just tested again with the latest master and LM 2.11.1 and is ok.
