### ISSUE TITLE
Labels display on QGIS but not on Lizmap

### ISSUE THREAD

**Issue by remigods** [3liz/lizmap-web-client#1660]
Hello,

Using QGIS 2.18, I could see the labels on QGIS but not on Lizmap.
Initially, labels were produced using an expression, but even using a simple text field from the table, it does not appear once on Lizmap.
There is no special option activated on QGIS, except "Display all label [...]" and "Avoid overlapping [...]".

Do you have any idea where the problem comes from?

**Comment by Gustry** [comment]
Could you follow the issue template provided? So we can have all information.
Are you using QGIS Desktop *and* Server 2.18?

**Comment by remigods** [comment]
Sorry the delay... and the lack of template!

### What is the bug? Steps to reproduce the issue. Expected behavior
See my previous post

### Environment
 - Lizmap version: release_3_2
 - QGIS Server version: 2.18.28
 - QGIS Project version: 2.18.22
 - OS: Windows/Android
 - Browser: Firefox
 - Lizmap admin information : based on PostgreSQL layers

**Comment by Gustry** [comment]
Sorry, I don't know what can be the problem. I think there is a low probability to have an answer on QGIS 2. It's not supported anymore by QGIS. You should think to update to QGIS 3.
