### ISSUE TITLE
How to show Postgres views/materialized views with Lizmap?

### ISSUE THREAD

**Issue by paolo73an** [3liz/lizmap-web-client#1661]
I haven't managed to show as attribute table in Lizmap neither a PG V or MV (table with no geometry) imported in Qgis from DB Manager nor a virtual layer (no geometry) filled with aggregate sums of value of main vector layer.
I'd like to show a sort of data summary with total values always updated as soon as I edit vector attributes.
Is there any way or trick I can use to do that?
Thanks

**Comment by Gustry** [comment]
Do you have any issue @paolo73an ? What is not working?

**Comment by paolo73an** [comment]
in lizmap attribute table I can see table column labels but no data are displayed; if I open a MV table or virtual layer table (without geometry), data are correctly displayed.
I'd like to show data (resulting from different queries with aggregate values from another PG layer) with LWC attribute table, too.
