### ISSUE TITLE
Editing: now it is allowed to add a record without geom

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1665]
* add a PostGIS layer to a project
* make it editable
* Lizmap llows to add a record without a geometry, without warning.
AFAIR previous versions issued a warning in this case, asking the user to add a geometry.
I think the current behaviour is less desirable, as it leads to useless entries.
LM 3.3.6, QGIS 3.10, pg 11.

**Comment by nboisteault** [comment]
In my case I can't add a geometry, I have an error message. I'm looking why there is no warning.

![image](https://user-images.githubusercontent.com/2145040/84403585-28a67400-ac06-11ea-94c4-8974b7d252b0.png)

**Comment by nboisteault** [comment]
@pcav : Do you have this checked ?
![image](https://user-images.githubusercontent.com/2145040/84407339-0105da80-ac0b-11ea-8218-0914dd3f38ef.png)

**Comment by nboisteault** [comment]
@rldhont @laurentj [this modification](https://github.com/3liz/lizmap-web-client/commit/bcddea64fd38ebda7534239a712f2b7bc15e1588#diff-c7de2f3dea765a639a0e12f783e722fdR1313) disable the popup message saying user has to draw the geom on the map. I don't fully understand what was its purpose.

**Comment by pcav** [comment]
Thanks @nboisteault , clicking on it displays the correct behaviour. I find however confusing that the `Create` permission was not enough. I do not want the user to *edit* geometries, just to create them.
So it's probably more of a semantic issue with the plugin @Gustry . Feel free to close this ticket.

**Comment by nboisteault** [comment]
@pcav I think it is a bug. I am asking my team how to fix this.

**Comment by pcav** [comment]
OK, thanks.

**Comment by mdouchin** [comment]
I think we should not change this type of behaviour without a deep understanding of the consequences. Editing is a key lizmap feature, as it concerns data.

As a map editor, for 99% of the use cases, I do not want the users to create a new item without geometry.

Though since the recent change in Lizmap which allows the user to create an object without geometry, the default behaviour is not the correct one IMHO.

The only way to force the user to create a geometry since this modification is to set the geom field as NOT NULL in the table, which is never done in most tables, and is undocumented.

We should add a new option in the plugin "Allow the user to create a feature with no geometry", False by default.

**Comment by pcav** [comment]
@mdouchin fully agreed. Thanks.

**Comment by nboisteault** [comment]
I've added a test to illustrate issue which fails currently => https://github.com/3liz/lizmap-web-client/commit/bd770f2cc6709a2db2e07e2db34b9b19767db3d0

**Comment by rmarzocchi84** [comment]
I agree with @mdouchin. 

For example in various qgis project we use edition without geometry. 

Perhaps it is not clear the option "Edit the geometry" of the plugin and it is better to change the name of "Allow the user to create a feature with no geometry" but I think it is a good option.

Perhaps this issue can be migrated to plugin?

**Comment by nboisteault** [comment]
After discussion with @mdouchin we think that few users might want to save a feature without geometry.
So we need to add a confirm dialog when someone save a feature without geometry as most of the time he does that accidentally.
This has to be made in next 3.3.x and 3.4 versions.
@rldhont @Gustry  thoughts ?

**Comment by tethysgeco** [comment]
just a general consideration.. in our projects it is often necessary to add or edit data in tables without geometry

**Comment by nboisteault** [comment]
@tethysgeco but your table has no geometry column isn't it?

**Comment by tethysgeco** [comment]
@nboisteault no, it hasn't. We often use tables withou geometry column as child tables to store data. Geometry column is in father table.

**Comment by rmarzocchi84** [comment]
@nboisteault normally we use this option in tables with geometry column when we have a PostgreSQL  trigger which create the geometry from inserted attribute data (e.g start poin and end poin on a line). 

I'm agree with we need to add a confirm dialog, but perhaps it is more useful on the plugin.. 

So the "admin" choose the behaviour on the lizmap plugin and for editing user there is not a need to confirm this option.

**Comment by nboisteault** [comment]
I propose that we add in the plugin a checkbox, unchecked by default, in the list above with label 'Allow creation without geometry' or 'Allow creation without drawn geometry'. This checkbox + label will be only visible for spatial layers.

Then in JS I will change [this line](https://github.com/3liz/lizmap-web-client/commit/bcddea64fd38ebda7534239a712f2b7bc15e1588#diff-4c07e19f3b7ab2f105b286b0564be51333f7d8ae4f98602921f8f1d49aa3a497R1313) to : 
```javascript
if( editionLayer['spatial'] && editionLayer['config'].capabilities.createFeatureWithoutGeometry == 'False'){
```
cc @mdouchin @rldhont @laurentj @Gustry 

![image](https://user-images.githubusercontent.com/2145040/97709398-902c6580-1aba-11eb-9977-45c3a9e61983.png)

**Comment by Gustry** [comment]
Yes, we can add this checkbox, to make the choice explicit. It affects 3.3, correct?

**Comment by nboisteault** [comment]
@Gustry Yes it does. Thanks.

**Comment by Gustry** [comment]
Check https://github.com/3liz/lizmap-plugin/pull/302 for the QGIS Desktop side
