### ISSUE TITLE
Locate by layer stopped to work on point layers, using Lizmap 2.11 and qgis master

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#167]
Does not happen if using qgis server 2.8.2, but it does when using the latest master. It also works ok if using polygons (lines not tested).

For what it can matter the GetFeature request with filter seems to work.

**Comment by JogicPogic** [comment]
This is a problem with a large amount of data.
It is necessary to make dynamic data loading from the server.

**Comment by rldhont** [comment]
Did you use curl for sending request to QGIS Server ?
Can you test Send request to QGIS Server with php ?

**Comment by gioman** [comment]
Just tested again with the latest master and LM 2.11.1 and is ok.
