### ISSUE TITLE
Value Map description not used in "Filter data with form"

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#1674]
**Related Problem:**
When a filter (type=uniquevalues) is applied to a column with a configured ValueMap/ ValueRelation widget, Lizmap does not show the descriptions of the configured widget but the original values (see. image below)

![widget](https://user-images.githubusercontent.com/25825472/84058590-bd686200-a9b9-11ea-8410-4c125cb8c848.png)

**Possible Solution:**
I proposed a possible solution in this similar open issue #747
At the moment I partially solved the problem adding a js script to the media folder but there is still something that does not work perfectly. For instance, as reported in the issue, I'm not able to identify the proper event (es. dockopened,  layerFilterParamChanged, ecc.) to trigger my js function. 

Any suggestion about the proposed solution?

**Comment by rmarzocchi84** [comment]
perhaps related to this issue? https://github.com/3liz/lizmap-web-client/issues/1517

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/pull/2722
