### ISSUE TITLE
Locate by layer go wrong when Server tile cache is on

### ISSUE THREAD

**Issue by capu81** [3liz/lizmap-web-client#1676]
Hi, i have some projects that works very well with lizmap. Now i have decided to activate Server tile cache for speed reason. If i activate Server tile cache (on any layer), the function "locate by layer" stop working. I can search my text but the point on map are wrong (about 6 or 7 Km). If i toggle the layer without search I can see the points on the right position. If i disable Server tile cache all go well and locate work.
The source of layer for "locate by layer" is in a postgress table.

### Environment
 - Lizmap version: 3.3.6
 - QGIS Server version: 3.10.6
 - QGIS Project version: 3.10.6
 - OS (Windows, Linux, MacOS, Android…): Server Ubuntu bionic
 - Browser (Firefox, Chrome…): Chrome last version and Firefox ESR

**Comment by nboisteault** [comment]
I can't reproduce the issue. Do you have any public link or small project to upload here, logs in browser console?

**Comment by capu81** [comment]
I don't have a public access to the layer at the base of "locate by layer". I'have a link of another public WMS that have problem with the Map Scale only if i activate cache. Layer is "BASE CARTOGRAFICA"
http://servermap.comune.calenzano.fi.it:8080/geoserver/CALENZANO_WMS/wms?version=1.3.0&layers=CALENZANO_WMS
I don't know if the two problem are related

**Comment by nboisteault** [comment]
Nothing in browser console or server logs ?

**Comment by capu81** [comment]
I've two error in the browser console but i think it's not related to this problem

`GET http://qgisserver.calenzano.priv/lm/Proj4js/defs/EPSG3857.js net::ERR_ABORTED 404 (Not Found)`
`GET https://spatialreference.org/ref/epsg/3857/proj4js/ net::ERR_ABORTED 404 (NOT FOUND)`

Lizmap log
`2020-06-11 17:12:15     172.16.20.47    warning 2020-06-11 17:12:15     [2]     SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search  /var/www/lizmap-web-client/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php   112

2020-06-11 17:12:15     172.16.20.47    warning 2020-06-11 17:12:15     [2]     file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fgeodata%2Frepo%2FUrbanistica%2FRegolamentoUrbanisticoEsterno%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
        /var/www/lizmap-web-client/lizmap/modules/lizmap/classes/lizmapProxy.class.php  240

2020-06-11 17:12:15     172.16.20.47    error   2020-06-11 17:12:15     172.16.20.47    [403]   query non valida (ERROR:  Input geometry has unknown (0) SRID(
        WITH source AS (
         SELECT "gid", "indirizzo", "the_geom" AS "geosource" FROM "public"."civici_sit" WHERE True
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            'civici_sit',
            '.',
            "gid") AS id,
                        ST_AsGeoJSON(ST_Transform(ST_Envelope(lg.geosource::geometry), 4326))::json As geometry,

                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "gid", "indirizzo"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))     /var/www/lizmap-web-client/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php    174
        /lm/index.php/lizmap/service/?repository=urbanistica&project=RegolamentoUrbanisticoEsterno
array (   'repository' => 'urbanistica',   'project' => 'RegolamentoUrbanisticoEsterno',   'module' => 'lizmap',   'action' => 'service:index',   'SERVICE' => 'WFS',   'VERSION' => '1.0.0',   'REQUEST' => 'GetFeature',   'TYPENAME' => 'civici_sit',   'OUTPUTFORMAT' => 'GeoJSON',   'GEOMETRYNAME' => 'extent',   'PROPERTYNAME' => 'geometry,indirizzo', )

        0       pgsqlDbConnection->_doQuery()   /var/www/lizmap-web-client/lib/jelix/db/jDbConnection.class.php : 129
        1       jDbConnection->query()  /var/www/lizmap-web-client/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 422
        2       lizmapWFSRequest->getfeaturePostgres()  /var/www/lizmap-web-client/lizmap/modules/lizmap/classes/lizmapWFSRequest.class.php : 160
        3       lizmapWFSRequest->getfeature()  /var/www/lizmap-web-client/lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php : 71
        4       lizmapOGCRequest->process()     /var/www/lizmap-web-client/lizmap/modules/lizmap/controllers/service.classic.php : 1320
        5       serviceCtrl->GetFeature()       /var/www/lizmap-web-client/lizmap/modules/lizmap/controllers/service.classic.php : 99
        6       serviceCtrl->index()    /var/www/lizmap-web-client/lib/jelix/core/jCoordinator.class.php : 225
        7       jCoordinator->process() /var/www/lizmap-web-client/lizmap/www/index.php : 23
`

No error on qgiserver log or httpd log.

Layer "BASE CARTOGRAFICA" is a WMS layer from geoserver. Layer "civici" (for "locate by layer") is from a postresql table.

**Comment by virtusmankind** [comment]
I'm facing same issue with LWC 3.3.6-pre and QGis desktop/server 2.18.
Any help?
