### ISSUE TITLE
Disable file based layer for edition capabilities

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1680]
# Problem

I have followed the documentation in setting up editing but when I log in my front end I do not see any editing icon.

![editing-grp](https://user-images.githubusercontent.com/2510900/84366736-8c637980-abd3-11ea-9a40-7c503825f7ae.png)

Repo permissions

![repo-perm](https://user-images.githubusercontent.com/2510900/84366862-b4eb7380-abd3-11ea-9a84-1fb20528a28e.png)

Group permisions
![grp-perms](https://user-images.githubusercontent.com/2510900/84366943-d9475000-abd3-11ea-981e-823e52cca665.png)

My front end looks like
![no-edit-icon](https://user-images.githubusercontent.com/2510900/84367042-f845e200-abd3-11ea-8f78-d73f34f70e40.png)

**Comment by Gustry** [comment]
Did you check file permission on your spatialite file? Write permission.

**Comment by NyakudyaA** [comment]
> Did you check file permission on your spatialite file? Write permission.

![perms](https://user-images.githubusercontent.com/2510900/84374689-a8b8e380-abde-11ea-9a71-f67f6955dc79.png)

I have tried using Postgres and editing works.

**Comment by Gustry** [comment]
We are currently dropping Spatialite support for editing capabilities.
3liz/lizmap-plugin#364

Only postgresql is supported.
