### ISSUE TITLE
Issues with wfsOutputExtension on master branch

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#1681]
### What is the bug?

After the commit [Update jQuery to 3.5.1, add jquery-migrate 3.3.0](https://github.com/3liz/lizmap-web-client/commit/4699401119070910b881519f9aedc7d9c8e9eedc)
the [wfsOutputExtension](https://github.com/3liz/qgis-wfsOutputExtension) is not working anymore. 

Before this commit export to csv, kml, etc formats was working

### Environment

 - Lizmap version: 3.4.0-alpha.2
 - QGIS Server FULL version: 3.12
 - QGIS Desktop FULL version: 3.12
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome

**Comment by nboisteault** [comment]
@ygorigor Could you test https://github.com/3liz/lizmap-web-client/pull/1686 please ?

**Comment by ygorigor** [comment]
@nboisteault it works. Thanks

**Comment by ygorigor** [comment]
I will leave it open until fix will be merged
