### ISSUE TITLE
impressions fond de carte issu d'un projet parent

### ISSUE THREAD

**Issue by antoine373** [3liz/lizmap-web-client#169]
Bonjour,

Pour centraliser le cache, le fond de carte que j'utilise est issu d'un seul projet. Tous les autres projets sont donc des projets fils en ce qui concerne le fond de carte. Le problème c'est que lors de l'utilisation du module impression dans ces projets fils, le fond de carte n'est pas exporté.

Est-ce "normal", ou bien y a-t-il un volet de la configuration qui m'échappe ?....

**Comment by rldhont** [comment]
Bonjour,

Tout d'abord, sous QGIS les couches parentes sont-elles imprimées ?

**Comment by antoine373** [comment]
Bonjour,

Tout d'abord merci pour la réponse.
Oui les couches parentes sont bien imprimées sous qgis.

Bon j'ai refait plein de test ce matin, et il finalement il s'avère que l'impression de données issues d'un projet parent fonctionne mais de façon TRES aléatoire :
- J'ai un projet parent qui centralise de nombreuses couches, et aucune d'entres elles ne sont imprimables via les projets fils.
- En faisant le test avec un autre projet "lambda", toutes les couches que celui-ci possède peuvent être réutilisées par un projet fils et sont imprimables.

Il s'avère que ces deux projets ont exactement les mêmes propriétés sous qgis. Leur seule différence est leur répertoire lizmap, mais là encore le compte utilisateur utilisé pour l'impression a exactement les mêmes droits sur chacun des 2 répertoires....

Je n'ai, pour le moment, aucune explication quant au comportement de ce projet parent que j'utilise pour centraliser le cache !

**Comment by rldhont** [comment]
Bonjour,

Ceci est un Bug QGIS-Server, celui-ci a été corrigé et backporté sur différentes branches. Cette correction sera ccessible sur 2.12.1 et 2.8.4 sinon vous pouvez compiler.
