### ISSUE TITLE
Simplify print format option

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1699]
From my own experiences I've seen a lot of people confuse about the different print format option (PDF, JPEG, PNG, SVG). Would it be relevant to have something simpler like : pdf, image.

For users who want to have all the format, we could probably integrate in the QGIS Lizmap Extension  an option like : 
- Print with limited format options (PDF, PNG)
- Print with all the format (PDF, JPEG, PNG, SVG)

**Comment by rldhont** [comment]
Some code https://github.com/arno974/lizmap-javascript-scripts/blob/master/ui/simplify-print-options/simplify-print-options.js

**Comment by nboisteault** [comment]
It will be possible in coming Lizmap 3.7 : https://github.com/3liz/lizmap-web-client/pull/3411
You can now test and give us back.
