### ISSUE TITLE
Centraliser le cache via l’intégration de groupes et couches d’un projet parent

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#170]
Bonjour à tous,
J'essaie d'utiliser cette fonction pour mettre dans un projet parents toutes les couches "lourdes" que j'utilise et centraliser ainsi les tuiles. J'ai respecté les consignes de la doc (même emprise, même paramètres de cache...), mais mes couches n'apparaissent pas dans mon projet fils.

Une idée ? Si certains ont réussi à utiliser cette fonction, je veux bien leur retour.

Merci d'avance.

**Comment by veroniqueC** [comment]
Bonjour,

Avez-vous bien charger les couches du projet parent dans qgis via Couche/Integrer des couches et des groupes?

**Comment by rldhont** [comment]
Bonjour,

La documentation est-elle trop peu précise ?
http://docs.3liz.com/fr/publisher_guide/advanced_lizmap_config.html#centralizing-the-cache-with-the-integration-of-groups-and-layers-from-a-master-project
Y-a-t-il des points à préciser ?

**Comment by RaphaelChochon** [comment]
Bonjour,
Oui effectivement @rldhont on se fait avoir par habitude (je n'avais jamais utilisé cette fonction de QGIS) ou alors on ne comprend pas vraiment...
Il faudrait peut être ajouter une capture d'écran de la fonction sur QGIS avec un petit texte un petit peu plus explicite.

On peut vous faire une pull request sur la doc en français ? En Anglais j'ai bien trouvé (https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#centralizing-the-cache-with-the-integration-of-groups-and-layers-from-a-master-project), 
mais mon Anglais n'étant pas merveilleux ...

**Comment by nboisteault** [comment]
@RaphaelChochon : Le pull request se fait sur la documentation en anglais, ensuite il est possible de faire la traduction avec transifex.
