### ISSUE TITLE
Configuring WPS in lizmap client

### ISSUE THREAD

**Issue by mazimweal** [3liz/lizmap-web-client#1701]
### Description
I have copied wps module to lizmap-modules upon installation..says that wps is installed
Added to docker limap image configuration the LIZMAP_WPS_URL= http://localhost:8080
after creating container this becomes http://localhost:8081

Added this to localConfig.ini.php

wps.access=2

[wps]
wps_url="http://127.0.0.1:8080/"
wps_rootDirectories="/srv/projects"
redis_host=redis
redis_port=6379
redis_key_prefix=wpslizmap
ows_url="http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi"
[coordplugin_auth]

However, am not seeing the WPS button on the WebClient. under what circumstances does this button come on the client ???because i don't seem to see its provision in QGIS lizmap plugin 
Please find my docker settings attached. Note that the containers generated fro make run command are "up"

version: '3'
services:
lizmap:
image: 3liz/lizmap-web-client:3.3.6
environment:
LIZMAP_CACHEREDISDB: '1'
LIZMAP_DEBUGMODE: DEBUG
LIZMAP_CACHEREDISHOST: redis
LIZMAP_CACHESTORAGETYPE: redis
LIZMAP_HOME: /srv/lizmap
LIZMAP_USER: '1000'
LIZMAP_WMSSERVERURL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi
LIZMAP_WPS_URL: http://127.0.0.1:8080/
expose:

  - 9000
volumes:
  - /home/qgis/www/webgis/ugandaVulnerability:/srv/projects
  - /home/qgis/www/webgis/lizmap/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
  - /home/qgis/www/webgis/lizmap/var/config:/www/lizmap/var/config
  - /home/qgis/www/webgis/lizmap/var/db:/www/lizmap/var/db
  - /home/qgis/www/webgis/lizmap/www:/www/lizmap/www
  - /home/qgis/www/webgis/lizmap/var/log:/www/lizmap/var/log
  - /home/qgis/www/webgis/lizmap/etc:/srv/etc:ro
  - /home/qgis/www/webgis/lizmap/lizmap-modules/wps:/www/lizmap/lizmap-modules/wps
  - /home/qgis/www/webgis/lizmap:/srv/lizmap
command:
  - php-fpm
restart: unless-stopped
entrypoint: >

  sh -c " chown -R  1010:1010 /tmp && /bin/lizmap-entrypoint.sh php-fpm"    
map:
image: 3liz/qgis-map-server:3.4
environment:
QGSRV_CACHE_ROOTDIR: /srv/projects
QGSRV_CACHE_SIZE: '20'
QGSRV_LOGGING_LEVEL: DEBUG
QGSRV_USER: 1000:1000
QGSRV_SERVER_WORKERS: 4
QGSRV_SERVER_PLUGINPATH: /srv/plugins
QGSRV_WPS_RESULTS_PROTOCOL: /srv/data
PGSERVICEFILE: /srv/etc/pg_service.conf
PGSPASSFILE: /srv/etc/pgpass.conf
volumes:
- /home/qgis/www/webgis/ugandaVulnerability:/srv/projects
- /home/qgis/www/webgis/lizmap/etc:/srv/etc:ro
- /home/qgis/www/webgis/lizmap/wps-data:/srv/data
ports:
- 443:80
restart: unless-stopped
wps:
image: 3liz/qgis-wps:3.4
volumes:
- /home/qgis/www/webgis/lizmap/processing:/srv/processing/:ro
- /home/qgis/www/webgis/ugandaVulnerability:/srv/projects'
- /home/qgis/www/webgis/lizmap/etc:/srv/etc:ro
- /home/qgis/www/webgis/lizmap/wps-data:/srv/data
environment:
QYWPS_SERVER_PARALLELPROCESSES: '2'
QYWPS_PROCESSING_PROVIDERS_MODULE_PATH: /srv/processing
QYWPS_CACHE_ROOTDIR: /srv/projects
QYWPS_SERVER_WORKDIR: /srv/data
QYWPS_OUTPUTPATH: /srv/data
QYWPS_REDIS_HOST: redis
QYWPS_USER: 1000:1000
QYWPS_SERVER_WMS_SERVICE_URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi
QYWPS_SERVER_RESPONSE_TIMEOUT: 1800
QYWPS_SERVER_RESPONSE_EXPIRATION: 86400
QYWPS_LOGLEVEL: DEBUG
QGSRV_LIZMAP_POLICY: /srv/processing/policy.yml
PGSERVICEFILE: /srv/etc/pg_service.conf
ports:
- 8081:8080
redis:
image: redis:5

### Environment

 - Lizmap version: 3.3.6
 - QGIS Server FULL version: 3.4
-WPS version 3.4
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…):  linux
 - Browser (Firefox, Chrome…): firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)?

**Comment by ygorigor** [comment]
@mazimweal did you run this `php lizmap/install/installer.php` after you add module?

**Comment by mazimweal** [comment]
Yes i did.... message WPS module installed appeared.

**Comment by ygorigor** [comment]
@mazimweal try to clean cache of your browser

**Comment by dmarteau** [comment]
Please have a look to the https://github.com/3liz/lizmap-docker-compose configuration.

Also you do not need to configure the localConfig.ini.php yourself since is is configured at the lizmap container startup.

In all cases the LIZMAP_WPS_URL host cannot be 127.0.0.1 since it must be reachable from inside the container, with docker compose the host is the name of the service as docker run its own subnet.

**Comment by mazimweal** [comment]
you are the best...Merci beaucoup!  this link did it for me  https://github.com/3liz/lizmap-docker-compose
however, there was an exception that Processing error... saga not installed.. I guess this means all the tools I develop shouldn't use saga

**Comment by dmarteau** [comment]
> saga not installed

Yes, by default, we do not install SAGA nor R in the WPS image.  If SAGA or R is required in your algorithms, we use to build a derived Docker image and install the appropriate packages (it is a debian buster-slim based).

**Comment by mazimweal** [comment]
Hi ..the wps plugin has an error of undefined result. is it possible that you could update qgis_WPS IMAGE on docker hub 
![Screenshot from 2020-07-04 01-07-21](https://user-images.githubusercontent.com/18460294/86453183-0ba52280-bd26-11ea-9c5c-7d88151e40e9.png)
