### ISSUE TITLE
Error when trying to search from lizmap using lizmap_search

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#1702]
### What is the bug?
`Uncaught TypeError: Cannot read property 'replace' of null
    at initialize.read (OpenLayers.js:1565)
    at Function.OpenLayers.Geometry.fromWKT (OpenLayers.js:617)
    at Object.success (search.js:125)
    at c (jquery-3.5.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2)
    at l (jquery-3.5.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2)`

### Environment

 - Lizmap version: 3.4.0-alpha.2
 - QGIS Server FULL version: 3.12
 - QGIS Desktop FULL version: 3.12
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into PostgreSQL

**Comment by ygorigor** [comment]
@nboisteault can you look into it?

**Comment by nboisteault** [comment]
@ygorigor It seems your request does not return any geometry. Can you paste the response of your searchFts request ? Request looks like : `http://localhost:8330/index.php/lizmap/searchFts/get?repository=localprojects&project=lizmap_search&query=label&bbox=-29.325917%2C26.986121%2C56.981925%2C60.164834
`

**Comment by ygorigor** [comment]
@nboisteault this is the response: `http://192.168.2.12:8081/index.php/lizmap/searchFts/get?repository=rep2&project=drm&query=Chisinau&bbox=16.985781%2C42.350536%2C41.23418%2C51.148744`

It's strange because this error occurs only in one project. I tried the same search in another project and it is ok.

**Comment by ygorigor** [comment]
@nboisteault I will close this issue, it seems that lizmap has nothing to do wit tis error
