### ISSUE TITLE
change title on page projet

### ISSUE THREAD

**Issue by jiptwo** [3liz/lizmap-web-client#1705]
Hello
I'm on 3.2lizmap and qgis 2.18.14

I would like to know how to change the title of the project page (from where its all projects)
currently in the header ... I have my logo ... and '' Project - Lizmap ''
I would like to remove Lizmap to put a title on this page

bonjour
je suis sur 3.2lizmap et qgis 2.18.14

j'aimerais savoir comment changé le titre de la page projet (d'où son tout les projets)
présentement dans l'entête... j'ai mon logo ... et ''Projet - Lizmap''
j'aimerais enlever Lizmap pour mettre un titre  a cette page

**Comment by Gustry** [comment]
In the admin panel, in your `Configuration`, `Interface`, you can change the `Application name` setting.
