### ISSUE TITLE
Minify of JS makes master not working

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#171]
I had trouble to make master working.
I found no documentation for the new way to install lizmap but maybe it is because it is master...

First I launched /lizmap/install/installer.php a got an error message.
I renamed lizmapConfig.ini.php.dist  => lizmapConfig.ini.php
and profiles.ini.php.dist => profiles.ini.php
Then I add a javascript error : "Uncaught ReferenceError: Invalid left-hand side expression in postfix operation"
I found that jquery-ui doesn't like JS minification so I disabled it in lizmap/var/config/mainconfig.ini.php :
minifyJS=0

Now it works!

**Comment by mdouchin** [comment]
Lizmap 3 is in heavy development right now, and we have not completed the documentation.
Concerning minify, you should not have this problem, since jquery-ui is in the list of minifyExcludeJS = JS files which must not be minified.
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/var/config/mainconfig.ini.php#L41

**Comment by mdouchin** [comment]
Do you have a ~ in the complete web url to your lizmap instance ?

**Comment by nboisteault** [comment]
Here it is : http://www.observatoire-environnement.org/lizmap-web-client-master/lizmap/www/
I put minifyJS=1 so you can look the error.

**Comment by mdouchin** [comment]
Thanks
Problem is the basepath, see http://docs.jelix.org/fr/manuel-1.6/vues/vue-html#compression-des-fichiers-css-et-javascript
In the mainConfig, could you test if you delete all the / before the minifyExcludeJS , like this:


```
minifyExcludeJS="index.php/view/translate/,OpenLayers-2.13/OpenLayers.js,js/jquery-1.11.1.min.js,js/jquery-ui-1.11.2.custom.min.js"
```

**Comment by nboisteault** [comment]
Perfect it works now! Thanks.

**Comment by nboisteault** [comment]
Is it a good idea to test master now or is it too soon?

**Comment by rldhont** [comment]
It's a good idea to test now.

**Comment by nboisteault** [comment]
I've tested master on an old project working with lizmap 2.11.
Minify.php is not working with css neither javascript. I have to disable it to make the viewer work.
I can enable it and show you the bug if you want.

**Comment by pcav** [comment]
confirmed here, setting
  minifyJS=0
  minifyCSS=0
in
  lizmap/var/config/mainconfig.ini.php
and
  rm -rf temp/lizmap/*
solves the issue temporarily.
Thanks René

**Comment by jancelin** [comment]
+1

**Comment by jancelin** [comment]
Only need to apply the change on debian jessie (raspberry pi).
No malfunction with Debian wheezy (raspberry pi) and ubuntu 14.04 lts.
