### ISSUE TITLE
undefined result  after running WPS process in lizmap web client

### ISSUE THREAD

**Issue by mazimweal** [3liz/lizmap-web-client#1711]
I used this configuration to create full-stack of li map client,  https://github.com/3liz/lizmap-docker-compose

When i run the WPS process it returns undefined result which is not mapped on the web client but files are created in the WPS result folder with unexpected file names. see picture below
![Capture](https://user-images.githubusercontent.com/18460294/86404056-2be5ca80-bcaf-11ea-8530-7f48df06c9f3.PNG)

see error log

  2020-07-02 19:57:22,829	[22]	INFO	Starting task 3e875b74:lzmtest:qgisbuffer
2020-07-02 19:57:23,041	[22]	INFO	lzmtest:qgisbuffer:3e875b74 Results: {'OUTPUT': './OUTPUT.gpkg'}
2020-07-02 19:57:23,042	[22]	INFO	lzmtest:qgisbuffer:3e875b74 Results: {'OUTPUT': './OUTPUT.gpkg'}
2020-07-02 19:57:23,204	[22]	INFO	Task finished lzmtest:qgisbuffer:3e875b74-bc9e-11ea-8f5b-0242ac120004
2020-07-02 19:57:23,278	[22]	INFO	lzmtest:qgisbuffer:3e875b74 memory: start=163.992Mb end=168.031Mb delta=4.039Mb

 - Lizmap version: 3.3
 - QGIS Server FULL version: 3.12
 -QGIS-WPS Version: 3.12
 - QGIS Desktop FULL version:
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…): firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)?

**Comment by mazimweal** [comment]
When i try Lizmap 3.3 QGISserver 3.4, qgis_wps 3.4  now.. the legend names appear but with no layer.

![Screenshot from 2020-07-05 20-33-56](https://user-images.githubusercontent.com/18460294/86538888-870efb80-bf01-11ea-8b5d-b71d450ab52a.png)


below is the error log in the terminal
map_1     | 2020-07-05 17:38:58,114	ERROR	[33]	Project 'wps-results:80d940ac-bee5-11ea-afed-0242ac120002/qgisbuffer.qgs' not found (404)

**Comment by dmarteau** [comment]
> map_1 | 2020-07-05 17:51:19,979 ERROR [34] File protocol handler: File not found: /srv/1fc96c08-bee8-11ea-a336-0242ac120004/qgisbuffer.qgs

The path is not correct, it should be 'srv/data/1fc96c08-bee8-11ea-a336-0242ac120004/qgisbuffer.qgs'

Looks like there is an error in the docker compose file try the following:
```
QGSRV_PROJECTS_SCHEMES_WPS_RESULTS: /srv/data/
```

With a `/` at the end.

**Comment by mazimweal** [comment]
Thank you very much .. it has worked out. Cheers!
