### ISSUE TITLE
Lizmap PostGis Layer Rendering Process Slow

### ISSUE THREAD

**Issue by indeOWS** [3liz/lizmap-web-client#1721]
### Description

I am running Lizmap@3.3.8 and I have noticed that Lizmap instance is taking a long time for rendering PostGis vector layers. The images in attached show the layer rendering  looping in the canvas until it finishes the rendering process (rendering_time_1.png, rendering_time_2.png and rendering_time_3.png)

I have tried to speed up the layer rendering process through httpd (apache) visrtualhost configuration as shown bellow, but I have not seen any improvement: the layer rendering process still slow. I wonder If someone could give me an insight to make PoostGIS layer rendering process faster.

```
<IfModule mod_fcgid.c>
         FcgidMaxRequestLen 26214400
         FcgidConnectTimeout 60
         # FcgidMaxRequestsPerProcess 1
         FcgidIdleTimeout 10
 </IfModule>
```

### Environment

 - Lizmap version: 
 - QGIS Server FULL version: qgis-server-3.14.0-1.fc32.x86_64
 - QGIS Desktop FULL version: 3.12.0-București
 - OS (Windows, Linux, MacOS, Android…): Fedora32
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite
![rendering_time_1](https://user-images.githubusercontent.com/14243472/87694153-377fc980-c764-11ea-8d40-b582470a5703.png)
![rendering_time_2](https://user-images.githubusercontent.com/14243472/87694158-38b0f680-c764-11ea-8d80-ad7f14024e35.png)
![rendering_time_3](https://user-images.githubusercontent.com/14243472/87694162-39498d00-c764-11ea-839f-bf93463c038d.png)

**Comment by nboisteault** [comment]
Did you read this [part of the documentation](https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#optimizing-lizmap) ?
Is your PostGIS query fast without Lizmap ?

**Comment by juliermegeotube** [comment]
@nboisteault I will take a look on the documentation you mentioned and check PostGIS query.
