### ISSUE TITLE
Tile cache and custom CRS

### ISSUE THREAD

**Issue by shermp** [3liz/lizmap-web-client#1725]
### What is the bug?

First, I'm not sure if this should be considered a bug or a documentation issue.

The tile cache (or more specifically, the tile generator I think) produces empty tiles if the project/layer CRS is not a "standard" web Mercator or WGS84 projection. The tiles are transparent/white. Monitoring Redis while lizmap is "generating" tiles, tiles appear to appear in the cache, but looking at the hex content displayed (a lot of `\x00`), they're empty.

### Steps to reproduce the issue

1. Create a project that uses a custom CRS, and add a layer with that CRS. (In my case, EPSG:2193 NZTM)
2. Set the QGIS server properties etc.
3. In the lizmap plugin, untick `single tile` and tick `Server tile cache`, with desired expiration/metatile settings.
4. Load project onto the lizmap web client server, set up repository etc.
5. View the map. Toggle layer if required. The layer will either show nothing, or white squares depending on image format.
6. There are no errors in the log regarding tile generation.

### Expected behavior

When toggling the layer on the map, appropriate tiles should appear.

Note, unticking both `single tile` and `Server tile cache` correctly generates tiles. I assume this uses a different tile generation process?

### Screenshots and logs

N/A

### Environment

 - Lizmap version: Docker 3.3.x (with Redis cache)
 - QGIS Server FULL version: 3.4, 3.10
 - QGIS Desktop FULL version: 3.4, 3.10
 - OS (Windows, Linux, MacOS, Android…): N/A 
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into PostgreSQL

### Test project
I've created two very simple test projects to demonstrate this issue. They are both as similar as possible, other than the layer and project CRS. The test projects are self contained, and should be able to be loaded into any lizmap-web-client setup. One project is setup for EPSG:3857, the other is in EPSG:2193.

The layers within these test files have the attribution `CC BY 4.0 Land Information New Zealand`
[TileTest.zip](https://github.com/3liz/lizmap-web-client/files/4940921/TileTest.zip)

**Comment by Gustry** [comment]
Custom CRS is not supported in Lizmap Web Client.
There is now a warning in the administration project page when the project has a custom CRS.
