### ISSUE TITLE
Relational values and multiple selections

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#173]
In QGIS I've an attribute which is a relational value permitting mutiple values.
But in the master web client the resulting form widget is a combobox that permits a single value not multiple ones.

**Comment by nboisteault** [comment]
I'm trying to develop this functionality and I'll commit it.
Is it ok if I replace jFormsControlMenulist by jFormsControlListbox. I can't see a way to have one or the other based on 'allowMulti' parameter.

**Comment by nboisteault** [comment]
I thought about it and I now think that listbox which results in a select multiple control is not a good choice because users have to ctrl + click to check/uncheck items which is really not intuitive.
So I see two solutions : 
* to make listbox selectable with one click with http://silviomoreto.github.io/bootstrap-select/
* to use jelix checkboxes

Thoughts?

**Comment by mdouchin** [comment]
Hi
Thanks for looking at this. 
I would prefer to use Jelix checkboxes and not rely on a bootstrap plugin, to keep things lightweight

**Comment by rldhont** [comment]
Hi @nboisteault, I have merged your code. Can you close this issue ?

**Comment by nboisteault** [comment]
Great, thank you!
