### ISSUE TITLE
search bar - clear button stop working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1732]
### What is the bug?

the the clear button in search bar stop working

### Screenshots and logs
![imagem](https://user-images.githubusercontent.com/10053874/81541633-4fedf500-936b-11ea-8fd5-f8d8a337c86c.png)

### Environment
 - Lizmap version: 3.3.9
 - QGIS Server version: 2.18
 - QGIS Project version: 2.18
 - OS (Windows, Linux, MacOS, Android…): linux
 - Browser (Firefox, Chrome…): all
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

thanks

**Comment by nboisteault** [comment]
@josemvm Can you tell us more on what happened?

**Comment by josemvm** [comment]
@nboisteault everything works fine, it was my mistake
thanks
