### ISSUE TITLE
Filter button should be hidden if there isn't a filter in the config

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1734]
### What is the bug?

The filter is button is visible even if there isn't a filter config.

![Screenshot from 2020-07-27 10-24-49](https://user-images.githubusercontent.com/1609292/88520249-9a3e5400-cff3-11ea-9272-f173f05e13c7.png)

In the JSON config, it's empty:

```json
    "formFilterLayers": {}
```

### Expected behavior

If there isn't a form filter config, the button should not be there. Like for other tools : attribute table, time manager etc

### Environment

 - Lizmap version: 3.4 master
 - QGIS Server FULL version: Master 3.15
 - QGIS Desktop FULL version: Master 3.15
 - OS (Windows, Linux, MacOS, Android…):  ubuntu 20.04
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PG

**Comment by nboisteault** [comment]
@mdouchin there is something to do in `/lizmap/modules/filter/classes/filterDockable.listener.php` but I'm not sure what because of this comment line 51 `lizmap/modules/filter/classes/filterConfig.class.php`

**Comment by mdouchin** [comment]
I take this one
