### ISSUE TITLE
relationship between layers with 2 or more variables

### ISSUE THREAD

**Issue by seb933** [3liz/lizmap-web-client#1736]
In qgis 3.14.1 there is the possibility of having a relationship between layers with 2 or more variables. I tried a project with a 2 variable relationship and on qgis 3.14.1 it works perfectly but transported on lizmap only displays the relationship with the first variable.

is it a compatibility issue with lizmap?

 - Lizmap version: 3.3.9

 - QGIS Desktop 3.14.1
 - OS server ununtu

**Comment by rldhont** [comment]
yes it is a compatibility issue.

**Comment by Gustry** [comment]
We usually stick to LTR version, so 3.10.
New features in QGIS takes time to have it in Lizmap.
