### ISSUE TITLE
Get repository/project name inside controllers

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#1737]
For a custom module I need to know the repository and project name.

While I can easily get them inside the listener (jEventListener) Class  (thanks to the $event variable  $project = $event->getParam('project'); ) I don't know how to do it in the controllers (jController).

Is there a way to get the repository and project name inside a controller ?

Thanks

**Comment by laurentj** [comment]
In a controller, you call `$this->param('name of the parameter')`.

**Comment by arno974** [comment]
But in this case the variable this->param('project') refers to a value passed by a post or a get request ?
Can I get the repository and project name directly inside my PHP code (jController) without having to expose them first as a javascript value / HTML params ?
