### ISSUE TITLE
Configure a default admin password when Lizmap start for the first time

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#1739]
### Description

When running Lizmap for the first time the default administrative login/password is `admin/amin` and one has to connect to the Lizmap interface for chongin the password.

This is not a secure behavior and a default password should be easily configured at first startup .

This configuration should also be available when runnig from the the docker configuration.

**Comment by erosfaus** [comment]
I have a new installation, and do not work admin/amin. It is posible restart the password?*

**Comment by nworr** [comment]
You can use the console command
`
php console.php jcommunity:password:change admin <NewPassword> --force
`
