### ISSUE TITLE
Make Lizmap changes to take effects without restarting hhtpd

### ISSUE THREAD

**Issue by juliermegeotube** [3liz/lizmap-web-client#1743]
### Description

I have made changes to *.qgs files, and the changes take effect only after restarting httpd. Could anyone give me an insight on how to make the changes to take effect by just refreshing the website and without running httpd?

### Environment

Lizmap version: 3.8
QGIS Server FULL version: qgis-server-3.14.0-1.fc32.x86_64
QGIS Desktop FULL version: 3.12.0-București
OS (Windows, Linux, MacOS, Android…): Fedora32
Browser (Firefox, Chrome…): Chrome
Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

**Comment by nboisteault** [comment]
@juliermegeotube how did you solve your issue ?
