### ISSUE TITLE
WMS layer with authentication required

### ISSUE THREAD

**Issue by geographit** [3liz/lizmap-web-client#1744]
### WMS service with login/password fail
A bug apparently previously solved seems to be back.
The symptoms are similar to this issue: [https://github.com/3liz/lizmap-web-client/issues/617](url)

With a WMS service that requires login/password, the project doesn't load (service unavailable).
The log displays the following error:
`Download of capabilities failed: Host requires authentication`

### Environment

 - Lizmap version: 3.3.9
 - QGIS Server FULL version: 3.14

**Comment by rldhont** [comment]
How did you connect to the service ?

**Comment by gioman** [comment]
@rldhont confirmed here too: remote WMS layer was added in QGIS using basic auth (username and password stored in the QGIS project).

In logs I'm seeing this error, that does not show if the WMS layer is removed from the project. Unsure how this is related, but it says "service=WFS" and in this particular project there are no configured layers to be served as WFS.
```

2020-08-03 09:50:48	193.136.216.94	warning	2020-08-03 09:50:48	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2Fdata%ng%2Ffiles%2Flizmap%5Frepos%2Fdemo1%2Eqgs&amp;request=GetCapabilities&amp;service=WFS&amp;version=1%2E0%2E0): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/var/www/html/webgis/lizmap/modules/lizmap/classes/lizmapProxy.class.php	240

2020-08-03 09:50:48	193.136.216.94	error	GetCapabilities empty data
```

**Comment by geographit** [comment]
@rldhont , I connect to the service as per @gioman described using QGIS basic auth. The same project work on a previous version of lizmap (3.3 with qgis server 3.4).

Interesting I get the same behaviour as you describe @gioman. I have no WFS layers setup but get a GetCapabilities error.

In the qgis server logs:
```
INFO Server[253]: SERVICE:WFS
INFO Server[253]: VERSION:1.0.0
WARNING WMS[253]: Download of capabilities failed: Host requires authentication
...
INFO Server[253]: SERVICE:WFS
INFO Server[253]: VERSION:1.0.0
WARNING WMS[253]: Download of capabilities failed: Host requires authentication
```

Looking at my web browser dev-tool I can see a succession of Get capabilities (WMS, WMTS,WFS):
The WMS get capabilities fails:

- `...&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0`

Response:

- ```<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
  <ServiceException code="Error">
        Server Error !
      </ServiceException>
</ServiceExceptionReport>
```

WFS request;

- `&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.0.0`

Response:

- ```<ServiceExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
  <ServiceException code="Error">
        Server Error !
      </ServiceException>
</ServiceExceptionReport>```

WMTS request:

- `...&SERVICE=WMTS&REQUEST=GetCapabilities&VERSION=1.0.0`

Response:

- ```<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" 
	version="1.0.0" xml:lang="en">
	<ows:Exception exceptionCode="ServiceError">
    		<ows:ExceptionText>The WMTS Service can't be initialized!</ows:ExceptionText>
    
	</ows:Exception></ows:ExceptionReport>```
