### ISSUE TITLE
lwc master - missing lizmap/vendor folder

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1751]
hi

i'm trying to install the lwc master version but when i run the `php lizmap/install/installer.php` command i get this error:

`PHP Warning:  require(/var/www/html/lizmap-web-client-master/lizmap/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/lizmap-web-client-master/lizmap/application.init.php on line 12`

https://github.com/3liz/lizmap-web-client/blob/master/lizmap/application.init.php#L12

`vendor` folder does not exist then `autoload.php` file does not exist too

`PHP Fatal error:  require(): Failed opening required '/var/www/html/lizmap-web-client-master/lizmap/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/lizmap-web-client-master/lizmap/application.init.php on line 12`

thanks

**Comment by Gustry** [comment]
Did you do 'make build'? Or use https://packages.3liz.org

**Comment by josemvm** [comment]
sorry @Gustry directly from github, i did not make build
thanks

**Comment by Kratos42** [comment]
> Did you do 'make build'? Or use https://packages.3liz.org

I spent the afternoon trying to find this vendor folder !
Thank you
