### ISSUE TITLE
Theme files of common media directory are not loaded 

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1756]
### What is the bug?

CSS media are not loaded from `media/themes/default/css/` but are loaded from `<repo>/media/themes/default/css`

### Steps to reproduce the issue

1. put some css files (main.css, map.css etc..) into `<repo>/media/themes/default/css`
2. load a project from the `<repo>` directory into lizmap
3. you see CSS links into the source code of the html page
4. move the `<repo>/media/` directory to `/media/`
5. reload the project
6. CSS changes are not applied anymore, since there are not anymore CSS links into the HTML page

However, the mecanism is working for custom JS files. Lizmap loads JS files either from `media/js/default/` or from `<repo>/media/js/default/`

### Expected behavior

CSS files into `media/themes/default/css` should be loaded, as indicated into the documentation.

### Environment

 - Lizmap version: 3.3
 - OS: Linux
 - Browser: Firefox

**Comment by rldhont** [comment]
Here: https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/view/controllers/lizMap.classic.php#L328

Think to test `$cssRelPath = '../media/themes/'.$theme.'/css/'.$k.'.css';`

**Comment by rldhont** [comment]
https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/view/controllers/lizMap.classic.php#L326
```php
            foreach ($cssArray as $k) {
                $cssRelPath = 'media/themes/default/css/'.$k.'.css';
                $cssPath = $lrep->getPath().'/'.$cssRelPath;
                    if (file_exists($cssPath)) {
                        $cssUrl = jUrl::get(
                            'view~media:getCssFile',
                            array(
                                'repository' => $lrep->getKey(),
                                'project' => $project,
                                'path' => $cssRelPath,
                            )
                        );
                        //~ $rep->addCssLink( $cssUrl );
                        // Use addHeadContent and not addCssLink to be sure it will be loaded after minified code
                        $rep->addHeadContent('<link type="text/css" href="'.$cssUrl.'" rel="stylesheet" />');
                    }
                foreach ($themeArray as $theme) {
                    $cssRelPath = 'media/themes/'.$theme.'/css/'.$k.'.css';
                    $cssPath = $lrep->getPath().'/'.$cssRelPath;
                    if (file_exists($cssPath)) {
                        $cssUrl = jUrl::get(
                            'view~media:getCssFile',
                            array(
                                'repository' => $lrep->getKey(),
                                'project' => $project,
                                'path' => $cssRelPath,
                            )
                        );
                        //~ $rep->addCssLink( $cssUrl );
                        // Use addHeadContent and not addCssLink to be sure it will be loaded after minified code
                        $rep->addHeadContent('<link type="text/css" href="'.$cssUrl.'" rel="stylesheet" />');
                    }
                }
            }```

**Comment by nboisteault** [comment]
> CSS files into media/themes/default/css should be loaded, as indicated into the documentation.
@laurentj where did you find this information in the documentation. It looks missing to me.
cc @Gustry

**Comment by Gustry** [comment]
About the documentation I have reviewed : https://docs.lizmap.com/next/en/publish/customization/themes.html

**Comment by nboisteault** [comment]
@Gustry it is written : 

> It is possible to create themes for all maps of a repository or for a single map within a repository.
We never talk about a way to make a theme for the whole Lizmap instance.

**Comment by nboisteault** [comment]
@laurentj @rldhont : I need a discussion on this issue.
