### ISSUE TITLE
Lizmap access logs: IP not stored

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#176]
At least in my case, the IP column is always empty. 

![image](https://cloud.githubusercontent.com/assets/12136796/8594388/7b028f0a-2640-11e5-80af-031ad2e0df51.png)

We would like to know the IP so that, later, we can calculate volume of acceses to lizmap by country (using a geoip tool).

Tested in 2.11 stable.

**Comment by mdouchin** [comment]
You can configure the log by manually editing the file lizmap/var/config/lizmapLogConfig.ini.php

**Comment by jaitor1** [comment]
Thanks!
