### ISSUE TITLE
LizMap Master Installation

### ISSUE THREAD

**Issue by juliermegeotube** [3liz/lizmap-web-client#1762]
### What is the bug?

I all,

I am getting the following error while installing lizmap master. It seems to be an issue with the vendor directory. Any insight will be very appreciated.

PHP Warning:  require(./lizmap/vendor/autoload.php): failed to open stream: No such file or directory in ./lizmap/application.init.php on line 12
PHP Fatal error:  require(): Failed opening required './lizmap/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in ./lizmap/application.init.php on line 12
### Environment

 - Lizmap version: master
 - QGIS Server FULL version: 3.14
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Fedora32
 - Browser (Firefox, Chrome…): Firefox / Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

**Comment by nboisteault** [comment]
Did you follow [those instructions](https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#build-and-install-dependencies) ?

**Comment by juliermegeotube** [comment]
@nboisteault , I took a look in the contribution [guideline](https://github.com/3liz/lizmap-web-client/blob/master/CONTRIBUTING.md#build-and-install-dependencies). I am struggling trying to install lizmap master version:
1 - I cloned the master version
2 - I merged the origin/release_3_3 into the master
3 - I commited the Unmerged paths and Untracked files and directories

But I still hitting the error above.

**Comment by Gustry** [comment]
Which documentation/link did you follow at the beginning of your question?

> 2 - I merged the origin/release_3_3 into the master

Why are you trying to merge `origin/release_3_3` into `master`. `master` is the next Lizmap 3.4.
I think you shouldn't use git, use packages available on https://packages.3liz.org
As mentioned, Lizmap 3.4, you need to build the PHP and the Javascript application yourself if you are using git.

**Comment by juliermegeotube** [comment]
@Gustry. I got it.
