### ISSUE TITLE
Referencing child later in popup

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#1772]
### Description
Pop-up data can be ordered in tabs (with Bootstrap), it works as expected, and data can be organized nicely from one layer (Postgis table in our case). We would like to show child layers/tables in parent's pop-up organized in tabs.
Issues with tabs were discussed in #575 and #709.

The question is how to reference child layer's columns either by lizmap popup or qgis map tips and than to copy to lizmap.

### Environment

 - Lizmap version: Lizmap 3.3.6
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Linux
- Data source: PostgreSQL 12.x + PostGIS 3.0 database

**Comment by nboisteault** [comment]
I think your best bet is to use QGIS map tips  with `relation_aggregate()` and `concatenate` or `array_agg` as aggregate parameter. You can try to have HTML as the output or something you could use with some custom JS.

**Comment by aeduard** [comment]
Well I give it a try, but it looks to me very cumbersome. Can you point me to something similar? As auto popup mode handles well the child layer, I think referencing it from main popup would be a nice future enhancement.

**Comment by aeduard** [comment]
I'm testing relation_aggregate() in QGIS map tips. It does not work in lizmap, while results looks ok in QGIS.
Tested on lizmap web client 3.3.10 and 3.4.0.
Issue also discussed on #1997

**Comment by nboisteault** [comment]
@aeduard I have also tested `relation_aggregate()` but it doesn't work with QGIS Server.
I have just published a script to display children popups as tabs => https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/ui/display_children_popup_as_tabs
It will work with Lizmap 3.5.0 when released but you can test now with release_3_5 branch.

**Comment by Gustry** [comment]
Closing for lack of feedback.
`relation_aggregate()` has been discussed in #1997
and a javascript has been provided for LWC 3.5
