### ISSUE TITLE
Upgrading Lizmap to 3.x - nginx and apache2?

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1776]
Hello
we are upgrading to the latest Lizmap stable version on debian 10
Previous installation used apache as webserver

Now here
https://docs.lizmap.com/current/en/install/linux.html

I see that Nginx server is used instead...
Is this the preferred solution for lizmap? We need to install Nginx and apache on the same server because some other web applications use apache2..

Are there some apache2 setup hints to follow to adapt to lizmap 3.x version?

Thanks
Pietro

**Comment by pcav** [comment]
Hi Pietro
If you're already using Apache, I'd advise you to keep on with it.
Cheers.

On 25 August 2020 12:39:53 CEST, Pietro Rossin <notifications@github.com> wrote:
>Hello
>we are upgrading to the latest stable Lizmap version on debian 10
>Previous installation used apache as webserver
>Now here
>https://docs.lizmap.com/current/en/install/linux.html
>I see that Nginx server is used instead...
>Is this the preferred solution for lizmap? We need to install Nginx and
>apache on the same server because some other web applications use
>apache2..
>
>Are there some apache2 setup hints to follow to adapt to lizmap 3.x
>version?
>
>Thanks
>Pietro
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1776

-- 
Please excuse my brevity.

**Comment by pieri70** [comment]
Thank you Paolo
Is there some performance tuning for 3.x that is to be used?
Is this guide ok?

https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#installation-on-debian-based-systems

**Comment by pcav** [comment]
It should be ok.
Performance tuning is mostly done at the project level and with fastcgi params.
Cheers.

On 25 August 2020 13:12:57 CEST, Pietro Rossin <notifications@github.com> wrote:
>Thank you Paolo
>Is there some performance tuning for 3.x that is to be used?
>Is this guide ok?
>
>https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#installation-on-debian-based-systems
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1776#issuecomment-679961147

-- 
Please excuse my brevity.

**Comment by Gustry** [comment]
Try to use a single webserver, or you will be confused with apache and nginx, and it will make things more complex with ports etc.
Lizmap is only a PHP app, which should work whatever nginx or apache.

**Comment by pieri70** [comment]
Thanks Gustry
We will continue with Apache2.
Do you guys have some tuning instructions for  fastcgi parameters?
I have an old guide followed the first time we installed lizmap years ago..
pietro

**Comment by gcalibris** [comment]
I'm interesting too in tuning (apache+php), because our qgis project is heavy, showing many layers at same time and when zooming maps in or out after that data on the map is showing very slow.

**Comment by pcav** [comment]
Please follow the guidelines in the manual.

On 27 August 2020 09:25:23 CEST, gcalibris <notifications@github.com> wrote:
>I'm interesting too in tuning (apache+php), because our qgis project is
>heavy, showing many layers at same time and when zooming maps in or out
>after that data on the map is showing very slow.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/1776#issuecomment-681683011

-- 
Please excuse my brevity.

**Comment by gioman** [comment]
> I'm interesting too in tuning (apache+php), because our qgis project is heavy, showing many layers at same time and when zooming maps in or out after that data on the map is showing very slow.

@gcalibris be sure to have parallel rendering enabled

https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/config.html?highlight=parallel#qgis-server-parallel-rendering

https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#apache

**Comment by pieri70** [comment]
Thanks Giovanni
so this guide
https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#apache
has to be followed also if we don't use qgis server as standalone?

For me it's not clear where to add the code after the period
"Let’s now add mod_fcgid configuration directives for QGIS Server:"

Do I need to add them in
/etc/apache2/mods-enabled/fcgid.conf

Same thing for QGIS_SERVER_PARALLEL_RENDERING, where do I need to set these instructions?

Thanks again

**Comment by gioman** [comment]
> I mean, are these instruction needed also for Lizmap use?

@pieri70 yes of course

> For me it's not clear where to add the code after the period
> "Let’s now add mod_fcgid configuration directives for QGIS Server:"
> 
> Do I need to add them in
> /etc/apache2/mods-enabled/fcgid.conf
> Same thing for QGIS_SERVER_PARALLEL_RENDERING, where do I need to set these instructions?

you have options, as is stated on the same page:

"These directives can be added either to /etc/apache2/mods-enabled/fcgid.conf for a system-wide configuration, or to a specific Apache VirtualHost, if you want QGIS server to be available only for that address; the default one is available at /etc/apache2/sites-available/000-default.conf"

**Comment by pieri70** [comment]
Ok, that was unclear to me. I thought it was referring to the below code block
this one..
<Location /qgisserver>
 SetHandler fcgid-script
 FcgidWrapper /usr/lib/cgi-bin/qgis_mapserv.fcgi virtual
 Options +ExecCGI -MultiViews +FollowSymLinks
 Require all granted
</Location>

So all the directive in that page can be added to
/etc/apache2/mods-enabled/fcgid.conf
as we use our apache web server mainly for Lizmap..

**Comment by gcalibris** [comment]
Yes, I already using these all configuration from user manual (I cant' see big different when using or not these FcgidInitialEnv QGIS_SERVER_PARALLEL_RENDERING "1", FcgidInitialEnv		QGIS_SERVER_MAX_THREADS "-1", cores = 12). The main issues of slowness I think that when quickly zooming map many times (from 1 level to 3 or greater) to some object so browser still downloading not relevant data from database to show in the map, though these data will not show in the map because these images unnecessary anymore. For example if user already quickly zoomed from 1 to 4 level, so at first downloading all images from first level, after that from second level, third level and finally from fourth. I think would be great to kill some downloading processes of "old" data (images) that main focus of downloading would be from current level.

**Comment by gioman** [comment]
> or example if user already quickly zoomed from 1 to 4 level, so at first downloading all images from first level, after that from second level, third level and finally from fourth. I think would be great to kill some downloading processes of "old" data (images) that main focus of downloading would be from current level.

@gcalibris can you provide a public URL?
