### ISSUE TITLE
Geometry generator symbols do not propagate in QGIS Server using the lizmap image

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1779]
### What is the bug?

Serving an image with a geometry generator symbols does not return any symbols

### Steps to reproduce the issue

1. Add a layer to QGIS
2. Symbolize it using Geometry generator ie buffer
3. Server the project using the docker image 3liz/qgis-map-server:3.14
![error](https://user-images.githubusercontent.com/2510900/91184956-861e6d00-e6ed-11ea-81b4-a8b8edbfef67.png)

### Expected behavior
The same symbols as depicted in QGIS Desktop

### Screenshots and logs
Rendered symbols in desktop

![rendered](https://user-images.githubusercontent.com/2510900/91185084-a8b08600-e6ed-11ea-80d7-8ed065b05235.png)

Symbol definition
![symbls](https://user-images.githubusercontent.com/2510900/91185156-bfef7380-e6ed-11ea-8c3f-83cf336cc868.png)

QGIS version
![qgis](https://user-images.githubusercontent.com/2510900/91185320-f927e380-e6ed-11ea-8cef-da06e622ae00.png)

### Environment

 - Lizmap version: 
 - QGIS Server FULL version: 3.14.0-1.3.2
 - OS (Windows, Linux, MacOS, Android…):  Linux

**Comment by gioman** [comment]
> Serving an image with a geometry generator symbols does not return any symbols

@NyakudyaA have you checked (with a WMS GetMap request) that this isn't a QGIS Server issue?

**Comment by NyakudyaA** [comment]
> > Serving an image with a geometry generator symbols does not return any symbols
> 
> @NyakudyaA have you checked (with a WMS GetMap request) that this isn't a QGIS Server issue?

Let me test with native QGIS and will report my findings here

**Comment by NyakudyaA** [comment]
I have tested with a single layer and it seems to be working.
