### ISSUE TITLE
unable to add feature / edit Postgis

### ISSUE THREAD

**Issue by geomoes** [3liz/lizmap-web-client#1783]
I've followed the instructions of the documentation to create an annotation layer in PostGIS (a very simple one to start)
```
CREATE TABLE web.anno (
	gid serial NOT NULL,
	username text NULL,
	annotation text NULL,
	the_geom geometry(POLYGON, 3857) NULL,
	CONSTRAINT anno_pk PRIMARY KEY (gid)
);
```
I configured everything as described in the documentation and added two test polygons in QGIS.
When I try to edit data in LM, the popup shows the editing icon (small pencil), but when I hit the button, nothing happens. The editing menu (from the menu bar) only shows the blue 'progress bar', but nothing happens.

The lizmap log gives me a strange error:
```
ERROR:  column d.adsrc does not exist
LINE 2:         a.atthasdef, d.adsrc
                             ^(SELECT t.typname, a.attname, a.attnotnull, a.attnum, a.attlen, a.atttypmod,
        a.atthasdef, d.adsrc
        FROM pg_type t, pg_attribute a LEFT JOIN pg_attrdef d ON (d.adrelid=a.attrelid AND d.adnum=a.attnum)
        WHERE
          a.attnum > 0 AND a.attrelid = 34142 AND a.atttypid = t.oid
        ORDER BY a.attnum))	/var/www/lizmap-web-client-3.3.3/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174   

```
Running Lizmap 3.3
QGIS-Server 3.10.8
Ubuntu 18.04.3
PostgreSQL 12.4
PostGIS 3.0
Lizmap-Plugin 3.2.17
QGIS 3.14-1 on macOS

**Comment by Gustry** [comment]
> Running Lizmap 3.3

Tell us your full Lizmap version

>  PostgreSQL 12.4

This was a known issue with PG 12, which has already been fixed : https://github.com/3liz/lizmap-web-client/search?q=adsrc&type=Issues

>  QGIS-Server 3.10.8
>  QGIS 3.14-1 on macOS

Keep in mind that you might have troubles running two different QGIS versions between Desktop and server. You should use the same.

**Comment by geomoes** [comment]
OK
Lizmap version is 3.3.3.
I'm going to change my desktop version of QGIS so that is the same as the one on our server and'll see if problems disappear.

**Comment by gioman** [comment]
> but nothing happens

@geomoes check if you have the php7.*-pgsql package installed.

**Comment by geomoes** [comment]
@gioman 
the pgsql extension wasn't activated in php7.2 (PHP.ini) in apache2. But also after installing it with `extension=pgsql `and restarting apache it only works when I change `d.adsrc` as described above.

**Comment by Gustry** [comment]
@geomoes Do you mean you updated the code in Lizmap Web Client by editing the file?
This IMHO a bug and shouldn't be closed. Others will have the issue and your patch will disappear when you will update your Lizmap to the next version.

**Comment by geomoes** [comment]
OK,
I just thought that I close it, since You wrote yesterday:
This was a known issue with PG 12, which has already been fixed : https://github.com/3liz/lizmap-web-client/search?q=adsrc&type=Issues

I'm aware, that the edited files of the Lizmap Web Client will be lost with the next update, but I supposed, that this will be fixed already in the next release.
But I can leave it open.
Merci

**Comment by Gustry** [comment]
Sorry, I read quickly. You wrote : 

> Lizmap version is 3.3.3.

Which is indeed too old, it has been released in December 2019, before the fix, which landed in 3.3.4.
We are now at 3.3.9.

Can you try by updating to latest Lizmap 3.3.9 and check without updating manually files?

Closing as it should be fixed. Reopen if you still have the issue.

**Comment by geomoes** [comment]
I did an update / installed lizmap 3.3.9 in a new folder keeping the same structure of my old 3.3.3-version (following the instructions on https://docs.lizmap.com/current/en/install/upgrade.html.
I can log in, my projects are there, but when I try to open a map (even the Montepellier demo maps) it fails. I just see the map is loading with Lizmap-Logo.
The error-log says:

2020-08-28 14:14:08	xx.xx.255.241	error	2020-08-28 14:14:08	[403]	unzulässige Anfrage(ERROR:  current transaction is aborted, commands ignored until end of transaction block(SELECT "ug"."login", "ug"."id_aclgrp" FROM "jacl2_user_group" AS "ug" WHERE  "ug"."login"  = 'admin'))	/var/www/lizmap-web-client-3.3.9/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	174

**Comment by Gustry** [comment]
Can you open a new ticket with your new issue if you can't solve it.
It's not the same problem.

**Comment by geomoes** [comment]
You're rigt, this is a new issue. I opened a new issue.
