### ISSUE TITLE
Cached tiles with round scale

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#1785]
### Description

I have a lismap project with round scales. I am using a cached layer. The cache was generated by the console:
`php lizmap/scripts/script.php lizmap~wmts:seeding...EPSG:3857...`

In this case (round scale) the image from the cache is slightly blurry. As I understand it, tiles are generated in zoom levels with a non-round scale, and then the image is stretched to the desired size.

Is it possible to generate tiles with a round scale?

### Environment

 - Lizmap version: 3.3.9
 - QGIS Server FULL version: 3.10.9
 - QGIS Desktop FULL version: 3.10.9
 - OS (Windows, Linux, MacOS, Android…):  Ubuntu 18
 - Browser (Firefox, Chrome…): Firefox, Chrome

**Comment by Gustry** [comment]
What do you mean by "round scale" ?
Zoom levels in EPSG:3857 are from 0 to 20, integers.

**Comment by johnzet39** [comment]
@Gustry , I mean scale 500, 1000, 10 000,... in qgis and in lizmap if we dont use base  layers.

**Comment by Gustry** [comment]
This script is expecting zoom levels, not scales. It's different things.

In https://docs.lizmap.com/next/en/admin/cache.html#seeding

> TileMatrixMin - This is the minimum zoom level. This is not a map scale, but a ID of the zoom level.
