### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#179]
Hi,

I need to add the Basque language (Language of the Basque Country, North of Spain) to lizmap client interface so that later can be accesible through "lang=eu_ES" parameter. I translated myself the five UTF-8.properties files from Spanish to Basque and inserted them in a new eu_ES file in lizmap\modules\view\locales. 

Then I added "&lang=eu_ES" to my map's url but nothing happened, no translation was made. So I found in lizmap\var\config\defaultconfig.ini.php that said 
availableLocales="fr_FR,en_US,it_IT,es_ES,pt_PT,el_EL"
I cahnged it to:
availableLocales="fr_FR,en_US,it_IT,es_ES,eu_ES,pt_PT,el_EL"

Now I am getiing in every lizmap website "Error 500. A technical error has occured. Sorry for this trouble."

I reverted the changes to the original state but the error keeps showing. How can i fix this mess?
What are the steps to add a new language? I will send you the translations so you can add it to the project..if at last I can make it work...

I am using lizmap 2.11 and QGIS 2.8.2 in Windows Server 2012

**Comment by jaitor1** [comment]
Error solved, although I don't really know how. I think cleaning the temp file helped.

I din't make the new transaltion work properly yet.

**Comment by jaitor1** [comment]
Any hint on how to add a new language to lizmap client?

**Comment by jaitor1** [comment]
Ok i finally got it working. There was an error in one of the .ini.properties and i changed the key name of one entry when transalting it to basque. I left the eu_ES folder in the link below so that someone can add it to lizmap project as I don't know how to do that. This folder should go in lizmap\modules\view\locales.

https://www.dropbox.com/s/o9bqp7lf3exvsn2/eu_ES.rar?dl=0

**Comment by jaitor1** [comment]
One note:

el_EL language in lizmap (greek i guess) should be el_GR, to meet the ISO standards: https://msdn.microsoft.com/en-us/library/ee825488%28v=cs.20%29.aspx

**Comment by jaitor1** [comment]
I can see the maps in the correct interface language now but when i click on "Connect" button in my new language, the "Error 500. A technical error has occured. Sorry for this trouble" error appears.

So i think i need to edit something else....

**Comment by rldhont** [comment]
You have to localize:
* modules/admin
* var/overloads/jacl2db_admin
* var/overloads/jauth
* var/overloads/jauthdb_admin
* var/overloads/jelix
* var/overloads/master_admin

**Comment by jaitor1** [comment]
Thanks again!
