### ISSUE TITLE
Lizmap admin - Delete groups: add a warning beforehand

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#1793]
In Lizmap Web Client admin panel, the page `http://lizmap/admin.php/jacl2db_admin/groups/` allows to add, edit or delete a group.

For deletion, we should ask the user for a confirmation before running the deletion of the group. For example with the classical JS `confirm()` method. The label and ID of the group should be displayed in the confirmation message, so that the user can check if the group chosen in the combo box is the right one.

**Comment by laurentj** [comment]
done
