### ISSUE TITLE
Working with Lizmap without Primary keys

### ISSUE THREAD

**Issue by remigods** [3liz/lizmap-web-client#1798]
Hi,

I cannot use any Postgresql view, Postgres materialized view nor DB Manager view, whatever there is a unique id in the layer, in order to populate "Locate by layer" or "Atlas" tools. No list of items is displayed on the atlas list nor on the Locate by layer list when those kind of layers are set.
However, it does work with a Postgres table, when I declare a primary key, and only when I delete checkPrimaryKeyUnicity='1' in the "datasource" part from the .qgs file.

I see in the Lizmap help and in other posts here that some users are able to deal with views, and even virtual layers. How do they do?
I am using QGIS 3.10 and QGIS server 2.18

Thanks for your help!

**Comment by nboisteault** [comment]
Hi @remigods ,
QGIS Server should be updated to 3.10.

**Comment by remigods** [comment]
Hi,
Thank you.
I will try, although you know it does not depend on me^^

**Comment by Gustry** [comment]
Indeed, do not mix different QGIS versions between Server and Desktop. Especially between QGIS 2 and QGIS 3.

**Comment by remigods** [comment]
QGIS Server installation is still in progress, that is why I am not able to try this solution yet. I let you know asap. Thanks
