### ISSUE TITLE
GetLegendGraphic WMS  send invalid LAYER parameter

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#1799]
### What is the bug?

GetLegendGraphic WMS request has an Invalid LAYER parameters - It should be LAYERS. 

### Steps to reproduce the issue

Run lizmap (with WPS module)

Load a project and look at the requests sent to qgis server (show requests)

On 'GetLegendGraphic, qgis server issue a 400 http response with the following response body:

```
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">,
 <ServiceException code="MissingParameterValue">The LAYERS parameter is missing.</ServiceException>,
</ServiceExceptionReport>
```

Looking at the request the parameter used is LAYER , not LAYERS

### Expected behavior

GetLegendGraphic should succeed with status 200.

### Environment

 - Lizmap version: 
 - QGIS Server FULL version:
 - QGIS Desktop FULL version:
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by nboisteault** [comment]
@rldhont : this commit is still useful?
https://github.com/3liz/lizmap-web-client/commit/4ccccf03f9bb3c33cd77e035c1c2a2d1f4b054bd

**Comment by rldhont** [comment]
@dmarteau @nboisteault I have checked the [OpenGIS Styled Layer Descriptor Profile of the Web Map Service Implementation Specification ](file:///tmp/mozilla_dhont0/05-078r4_Styled_Layer_Descriptor_Profile_of_the_Web_Map_Service_Implementation_Specification.pdf) and `LAYER` is the defined parameter for `GetLegendGraphic` request.

So the issue is in QGIS Server not in Lizmap. QGIS Server GetLegendGraphics has to be fixed https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsgetlegendgraphics.cpp#L176

**Comment by rldhont** [comment]
@nboisteault @dmarteau QGIS Server GetLegend tests using `LAYER` not `LAYERS` https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsserver_wms_getlegendgraphic.py

I think that the exception message has to be updated https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsgetlegendgraphics.cpp#L179

**Comment by dmarteau** [comment]
> I think that the exception message has to be updated

AMHA, even if the message is wrong that does not solve the fact that the response is an error 400, so the request send by Lizmap is still invalid.

**Comment by nboisteault** [comment]
Is it related to Lizmap or just WPS module?

**Comment by dmarteau** [comment]
I have reproduced the problem with the WPS module when expending the layer tree for the calculated output layers (and the legend is indeed broken). So it may be a WPS module issue.

```
map_1     | 2020-10-06 08:26:30,397	RREQ	[1]		400	GET	?DPI=96&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&ICONLABELSPACE=2&ITEMFONTSIZE=9&LAYERFONTBOLD=FALSE&LAYERFONTSIZE=0&LAYERSPACE=0&LAYERTITLE=FALSE&MAP=wps-results%3A8f7c098a-07ad-11eb-b86b-0242ac130002%2Flzmtest_qgisbuffer.qgs&REQUEST=GetLegendGraphic&SERVICE=WMS&SLD_VERSION=1.1.0&STYLE=&SYMBOLSPACE=1&TRANSPARENT=TRUE&VERSION=1.3.0&WIDTH=150	2	202	
map_1     | 2020-10-06 08:26:30,398	REQ	[1]	172.19.0.5	400	GET	/ows/?dpi=96&exceptions=application%2Fvnd%2Eogc%2Ese%5Finimage&format=image%2Fpng&iconlabelspace=2&itemfontsize=9&layerfontbold=FALSE&layerfontsize=0&layerspace=0&layertitle=FALSE&map=wps%2Dresults%3A8f7c098a%2D07ad%2D11eb%2Db86b%2D0242ac130002%2Flzmtest%5Fqgisbuffer%2Eqgs&request=GetLegendGraphic&service=WMS&sld%5Fversion=1%2E1%2E0&style=&symbolspace=1&transparent=TRUE&version=1%2E3%2E0&width=150	3	202	Lizmap	
...
map_1     | 2020-10-06 08:26:39,158	DEBUG	[45]	Resolving 'wps-results' protocol
map_1     | 2020-10-06 08:26:39,158	WARNING	[45]	Qgis: : formatString is: image/png
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: DPI:96
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: EXCEPTIONS:application/vnd.ogc.se_inimage
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: FORMAT:image/png
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: ICONLABELSPACE:2
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: ITEMFONTSIZE:9
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: LAYERFONTBOLD:FALSE
map_1     | 2020-10-06 08:26:39,158	INFO	[45]	Qgis: Server: LAYERFONTSIZE:0
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: LAYERSPACE:0
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: LAYERTITLE:FALSE
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: MAP:wps-results:8f7c098a-07ad-11eb-b86b-0242ac130002/lzmtest_qgisbuffer.qgs
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: REQUEST:GetLegendGraphic
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: SERVICE:WMS
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: SLD_VERSION:1.1.0
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: STYLE:
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: SYMBOLSPACE:1
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: TRANSPARENT:TRUE
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: VERSION:1.3.0
map_1     | 2020-10-06 08:26:39,159	INFO	[45]	Qgis: Server: WIDTH:150
map_1     | 2020-10-06 08:26:39,159	WARNING	[45]	Qgis: Server: <ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
map_1     |  <ServiceException code="MissingParameterValue">The LAYERS parameter is missing.</ServiceException>
map_1     | </ServiceExceptionReport>
```

It appears that there is no `LAYER` parameters at all !

**Comment by dmarteau** [comment]
Moved to https://github.com/3liz/lizmap-wps-web-client-module/issues/10
