### ISSUE TITLE
Edition - Allow to add a feature with no geometry

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#1803]
### Is your feature request related to a problem? Please describe

In some use cases, a feature could be added by the user with no geometry but data for only the other fields. We could let the user in lizmap add a new feature without geometry.

At present, it is not possible: the form cannot be submitted if no geometry has been drawn.

### Describe the solution you'd like

We could allow to add a geometryless feature by checking if the geom field has a `NOT NULL` constraint in the database or not.

I can see 2 problems: 

* the geom fields in PostgreSQL or Spatialite database are very often created without `NOT NULL` constraint, and if we rely only on this, many map editors and users will be suprised by this new default behaviour.
* we do not provide in Lizmap Web Client a way to draw the geometry of an existing feature. When the user clicks on the Pencil button in the popup, the form is shown, the existing geometry is show in editing mode, but no tool is shown to let the user create a geometry if there is none.

### Describe alternatives you've considered

Add a new option in Lizmap plugin, for each edition layer: `Allow to create a feature with no geometry`

**Comment by nboisteault** [comment]
@mdouchin : in master the alert message has been removed when no geometry has been drawn. I think we should revert this change for Lizmap 3.4 and think about this issue later. Do you have the commit id of this behavior change?

**Comment by nboisteault** [comment]
I close to follow discussion here : https://github.com/3liz/lizmap-web-client/issues/1665
