### ISSUE TITLE
Qgis logo

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#1804]
Hi.
When I open a project on Lizmap, the Qgis logo appears on the left corner. How can I remove it for the esthetic ?
I think this logo wasn't here in the last version of the plugin.

Thanks for your help

**Comment by nboisteault** [comment]
Fill the issue template and add screenshot please.

**Comment by Maverick83000** [comment]
How can I fill the issue template ?
I noticed the logo appears when I checked a layer and disappear when the layer was unchecked.

![image](https://user-images.githubusercontent.com/11660738/92462906-60a06180-f1cb-11ea-9044-a45158f9231d.png)

**Comment by ygorigor** [comment]
@Maverick83000 it seems to be enabled in QGIS-Decorations

**Comment by Maverick83000** [comment]
Thks for your answer. 
How can I disabled it ?
The logo is present  in all of my projects ...

**Comment by ygorigor** [comment]
@Maverick83000 search here: QGIS Desktop - View - Decorations - Image

**Comment by nboisteault** [comment]
The template is automatically inserted in the textarea when you fill an issue.

**Comment by Gustry** [comment]
Have you enabled the QGIS Server watermark plugin?

**Comment by Maverick83000** [comment]
No, the only plugin that I try to install was wfsOutputExtension (with no success) and I delete it.
In my opinion, this is a QGIS Server issue when I try to install this plugin...

**Comment by Maverick83000** [comment]
I found the problem !
I just create a file _/var/www/qgis-plugins_ with plugins "helloworld" and "wfsOutputExtension " like I saw in a tutorial...
I delete the file and it works. I still haven't installed wfsOutputExtension but no logo anymore.
Thanks for your time
