### ISSUE TITLE
[Vagrant] QGIS Server plugins not correctly installed

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#1805]
### What is the bug?
On a fresh new install I have wfsOutputExtension plugin installed in `/srv/qgis/plugins/wfsOutputExtension/wfsOutputExtension`.
The content of the plugin should be in `/srv/qgis/plugins/wfsOutputExtension`.
Same behavior with atlasprint.

This bug is due to the fact we now put plugin content in a directory and not at root.

**Comment by nboisteault** [comment]
@laurentj this should be an easy fix for you. ;)

**Comment by laurentj** [comment]
Fixed also in 3.2 and 3.3 branches
