### ISSUE TITLE
Create cache whit script php

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#1807]
Hi, 
whit the command for create a cache  "php script.php lizmap~wmts:seeding -v -f repox repox layerx EPSG:3857 0 20", where are the tiles saved?

thank you

Roberto

**Comment by nboisteault** [comment]
Tiles are saved in path defined in Lizmap administration. `/tmp/` by default.

**Comment by Gustry** [comment]
FYI https://docs.lizmap.com/next/en/admin/cache.html#configuring-the-caching-system
