### ISSUE TITLE
Debian 9.13 Lizmap 3.3.0 nginx - 404 not found

### ISSUE THREAD

**Issue by vicente23** [3liz/lizmap-web-client#1812]
Hello,

I'm trying to install Lizmap on a virtual machine (VirtualBox) running Debian 9.13 and I encounter several difficulties.

I followed all the steps of the documentation. In a first part, I got a 403 nginx error
when I accessed the following adress `localhost/lizmap/`.
I tried to enter the address `localhost/lizmap/index.php`, I was asked to open the file instead of running it. 
By consulting the `error.log` file, the origin of the problem is a problem of access to the following directory : 

> directory` index of "/var/www/html/lizmap/" is forbidden. 

To solve the problem, I modified the `lizmap.conf` file : 

```
location / {
        try_files $uri $uri/ =404;
    }

    location ~ [^/]\.php(/|$) {
       fastcgi_split_path_info ^(.+\.php)(/.*)$; 
       #set $path_info $fastcgi_path_info; # because of bug http://trac.nginx.org/nginx/ticket/321
       #try_files $fastcgi_script_name =404;
       include fastcgi_params;

       include snippets/fastcgi-php.conf; # Added this line
       #fastcgi_index index.php;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_param PATH_INFO $path_info;
       fastcgi_param PATH_TRANSLATED $document_root$path_info;
       fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
       fastcgi_param SERVER_NAME $http_host;
    }
```

If I uncomment the lines with a comment, I have a nginx 403 problem again.
Now I have a nginx 404 problem when I try to reach the next url : 
`localhost/lizmap/index.php/view/map/?repository=montpellier&project=events`

Any hint about this issue?

**Comment by nboisteault** [comment]
Did you try [this way to install LWC](https://github.com/3liz/lizmap-web-client/tree/master/vagrant) ?
You'll have LWC installed easily.

**Comment by vicente23** [comment]
Thanks for your reply.

I tried your new way but I have a problem when launching the vagrant up command.
The command prompt gets stuck on the following task:
TASK [qgis: Add QGIS repository key]

**Comment by nboisteault** [comment]
I have updated master to fix your issue. You can use master or apply [this patch](https://github.com/3liz/lizmap-web-client/commit/8a2c156503c5fbef1829ee97dac9469696fa08ba) to your LWC version.

**Comment by vicente23** [comment]
Thanks for your answer.
However, I still have the same problem.

**Comment by nboisteault** [comment]
Try `vagrant provision` instead of `vagrant up`

**Comment by vicente23** [comment]
Unsuccessfully, I get the following message in the command prompt (just one line):
`==> default: VM not created. Moving on..`

**Comment by nboisteault** [comment]
Did you copy vagrant/vars/custom.yml.dist to vagrant/vars/custom.yml?

**Comment by vicente23** [comment]
Yes I did

**Comment by vicente23** [comment]
I solved my problem by installing LWC on Windows. Thanks for your answers!
