### ISSUE TITLE
Service configuration error http://localhost/qgis/qgis_mapserv.fcgi.exe

### ISSUE THREAD

**Issue by vicente23** [3liz/lizmap-web-client#1813]
After several installation failures under Linux, I tried to install it on Windows.
Hello

When I access the following url: http://localhost/webgis/index.php, 
I see the list of demo projects but when on load the map, the data loading popup runs in a loop.

In the file lizmap-error.log, I get the following comment:
`AH02811: script not found or unable to stat: C:/webserver/Apache24/cgi-bin/qgis_mapserv.fcgi`

I have the module mod_fcgid.so the corresponding line is uncommented in the configuration file httpd.conf.

When I access the following url: http://localhost/qgis/qgis_mapserv.fcgi.exe, I get the following page:
```<ServiceExceptionReport version="1.3.0">
<ServiceException code="Service configuration error">
Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint
</ServiceException>
</ServiceExceptionReport>
```

But When I access the foloowing url : http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&REQUEST=GetCapabilities, all is right

**Comment by vicente23** [comment]
After a lot of research, I think that my problem comes from my version of QGIS Server.

Indeed, as a reminder when I click on the url http://localhost/qgis/qgis_mapserv.fcgi.exe. I get the following page:
```
<ServiceExceptionReport version="1.3.0">
<ServiceException code="Service configuration error">
Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint
</ServiceException>
</ServiceExceptionReport>
```

I followed the documentation and downloaded qgis-server via OSGEO4W (version 3.14), I have no choice of version. 
However, on your https://github.com/3liz/lizmap-web-client/wiki/Versions page, you recommend a version 3.4 for Lizmap 3.3, which would explain the message Service unknown or unsupported.

On the https://qgis.org/downloads/ page, I can download OSGEO4W from earlier versions but this one only installs the Desktop software. I'm missing the packages: fcgi, qgis server.
I couldn't find any way to download a previous version of QGIS Server without going through the last OSGEO4W installation which offers me the installation of the latest version. 

Thanks for your help.

**Comment by Gustry** [comment]
For windows, did you see https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

It's not wrong if you use QGIS 3.14. We just recommend QGIS LTR versions.

```
<ServiceException code="Service configuration error">
Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint
</ServiceException>
</ServiceExceptionReport>
```
means QGIS Server is working properly. (because you didn't give enough arguments to QGIS Server, so it's a normal error message showing that QGIS is responding.

**Comment by vicente23** [comment]
I solved my problem, mistake of inattention. My WMS server URL was wrong.

I had written http://localhost/qgis/qgis_mapserv.fcgi instead of http://localhost/qgis/qgis_mapserv.fcgi.exe .
Can't wait to test the solution, thanks for your answer.
