### ISSUE TITLE
403 forbidden /var/www/html/lizmap

### ISSUE THREAD

**Issue by fisholo** [3liz/lizmap-web-client#1817]
Hi and first of all thanks for all the job done!
I'm trying to install lizmap following your guide: https://docs.lizmap.com/current/en/install/linux.html
I have a digital ocean VM with Debian 9 so no problem to follow the guide and install all

Lizmap 3.3.0

But when i try to resolve http://127.0.0.1/lizmap I have the error 403 forbidden from nginx

In /var/log/nginx/error.log I found that the folder /var/www/html/lizmap is forbidden

I have controlled the permissions and are ok, www-data:www-data on all files. 

Have you any ideas? 

Many thanks

Fabrizio

**Comment by nboisteault** [comment]
What happened if you go to http://127.0.0.1/lizmap/index.php ?

**Comment by fisholo** [comment]
The browser download the file..

**Comment by nboisteault** [comment]
There is something wrong with nginx and/or PHP configuration.
If you just want to test Lizmap, I suggest you to use https://github.com/3liz/lizmap-web-client/tree/master/vagrant
