### ISSUE TITLE
Lizmap Admin - Force user password at creation

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#1818]
### Description

Hi,
I have no mail server installed on my debian 9 and i would like to create the password during the user creation as the older version of lizmap-web-client. I can force the account validation but not push myself the password.

Is there a possibility to force the password ?

Thanks for your help

### Environment

 - Lizmap version: 3.3.6
 - QGIS Server FULL version: 3.4.15
 - QGIS Desktop FULL version: 3.4.13
 - OS (Windows, Linux, MacOS, Android…): Debian 9
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Gustry** [comment]
You can find it in the next version of the documentation : https://docs.lizmap.com/next/en/admin/users-groups.html#setting-password-for-users
