### ISSUE TITLE
layer with a single symbol

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1819]
### Description
hi

i don´t know if it is a lwc issue, or a qgis server issue...

if you have a layer with a single symbol, the layer name appears in front of the symbol...
this situation did not happen with qgis 2.18

qgis 2.18
![imagem](https://user-images.githubusercontent.com/10053874/93228118-0e33e780-f76d-11ea-8c54-2c3227af824f.png)

qgis 3.10
![imagem](https://user-images.githubusercontent.com/10053874/93228245-315e9700-f76d-11ea-8431-368cc84d92d3.png)

### Environment

 - Lizmap version: 3.3
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): linux
 - Browser (Firefox, Chrome…): all
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by rldhont** [comment]
What about QGIS 3.4 ?

**Comment by josemvm** [comment]
@rldhont i have no qgis server 3.4 instance
finally, i'm trying to migrate from 2.18 to 3.10

**Comment by josemvm** [comment]
we need to reolace `<title></title>` by `<title><htmlData><![CDATA[ ]]></htmlData></title>`

**Comment by rldhont** [comment]
linked to #2042
