### ISSUE TITLE
GeoJSON doesn't handle line break properly

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#182]
Version : master
I'm testing attribute tables with data that have multiline so there are line breaks in it.
GetFeature requests don't send correct GeoJson. Line breaks should be replaces by `\\n` if I'm correct.

After some research, I can see that it is a QGIS issue. I opened this [ticket](http://hub.qgis.org/issues/13118)

**Comment by mdouchin** [comment]
This is a QGIS Server bug. I just opened a bug in the hub
http://hub.qgis.org/issues/13798

**Comment by mdouchin** [comment]
ok, I just opened a new bug for nothing. Sorry, I will mark it as a duplicate

**Comment by rldhont** [comment]
I think this has been fixed in QGIS.
@nboisteault is it fixed in lizmap ?

**Comment by nboisteault** [comment]
I tested with Lizmap master and QGIS 2.8.8 and it works fine.
Thank your very much.
