### ISSUE TITLE
Demo project not visible

### ISSUE THREAD

**Issue by marcuzz0** [3liz/lizmap-web-client#1826]
Hello everyone,

I installed on a remote VPS (Ubuntu server 20.04) with LAMP, Qgis Server and Lizmap Web Client, following the various guides on the net.
I was actually able to view the main screen of the service but unfortunately I can't view the included demo project.
Do you have any ideas about it?

Tks
Marco

**Comment by geomoes** [comment]
Hi,
did You enable the demo projects during intallation?

"In case you want to enable the demo repositories, just add to localconfig.ini.php the following:

[modules]
lizmap.installparam=demo
"

**Comment by Marcuzzo77** [comment]
@geomoes 
Yes, absolutely I enable the demo projects during intallation

**Comment by geomoes** [comment]
can You see the projects-folders qgis and qgis_intranet in the lizmap-web-client-(your Version)/lizmap/install/ directory? These folders contain the data of the demo-projects. 
The rights should be set with:
`lizmap/install/set_rights.sh www-data www-data `

**Comment by Marcuzzo77** [comment]
the demo project is in this location:
/ var / www / lizmap-web-client / extra-modules / lizmapdemo / qgis-projects
here are the folders:
demoqgis demoqgis_intranet

**Comment by geomoes** [comment]
Ok Your structure is a bit different from mine, but if I translate this to your structure You should create a symlink e.g. 'lizmap' in your /var/www/html folder, that points to the /var/www/lizmap-web-client/www. You can acces Lizmap then trough https://yourdomain.com/lizmap. 
When you login as user admin /pw admin, you should adapt the path of the repositories to match Your structure. In your case this should be ../extra-modules/lizmapdemo/qgis-projects/demoqgis (for the montepellier demo) and  ../extra-modules/lizmapdemo/qgis-projects/demoqgis_intranet (for the intranet demo).

**Comment by geomoes** [comment]
sorry, I found the same structure in the new ver. 3.4.0.3. The link to the montepellier or the intranet demo should start with ../../ instead of just ../. 
In my case it works.

**Comment by Marcuzzo77** [comment]
I set the path ../../extra-modules/lizmapdemo/qgis-projects/demoqgis but it still doesn't work....
<img width="664" alt="Schermata 2020-09-20 alle 23 12 56" src="https://user-images.githubusercontent.com/26044319/93722444-1b9b0880-fb97-11ea-932a-41f316d8ac69.png">

**Comment by geomoes** [comment]
<img width="748" alt="Bildschirmfoto 2020-09-20 um 23 20 10" src="https://user-images.githubusercontent.com/30963421/93722607-56ea0700-fb98-11ea-85dc-6109266af3e0.png">

both repositories work for me ../../extra-modules/lizmapdemo/qgis-projects/demoqgis (for the montepellier demo) and ../../extra-modules/lizmapdemo/qgis-projects/demoqgis_intranet (for the intranet demo).

**Comment by Marcuzzo77** [comment]
how are your permissions in the folder ../../extra-modules/lizmapdemo/qgis-projects/demoqgis ?

**Comment by geomoes** [comment]
Owner is www-date:www-data and permissions are set 0755 for folder and 0644 for files. 
But I must admit, that I'm strugling since two weeks to get projects to work properly when I'm logged in. Public projects (projects thar anonymous can see) work, but I'm unable to display maps that need authentication. see  #1789

**Comment by Marcuzzo77** [comment]
ok tks keep trying

**Comment by geomoes** [comment]
good luck, it should work, at least You should be able to install the demo projects

**Comment by Marcuzzo77** [comment]
@geomoes Still nothing I have reinstalled from 0 on a local virtualbox virtual machine but still without any positive results.
No errors but no demo project present.
Also I miss all those options that I see on your print screen that relate to the inserted link ...

<img width="752" alt="Schermata 2020-09-21 alle 18 28 02" src="https://user-images.githubusercontent.com/26044319/93794892-fc54b780-fc38-11ea-8901-365aa46247e7.png">

**Comment by geomoes** [comment]
Hi,
this is the screen visible, when the repository has been created successfully. At the start it looks like Yours.
<img width="801" alt="Bildschirmfoto 2020-09-21 um 22 17 39" src="https://user-images.githubusercontent.com/30963421/93816967-87917580-fc58-11ea-907f-52f8ba7056f1.png">
When the path is correct and You hit save, You should be able to edit the project to set the right access-rights. Then it looks like the one above.

**Comment by Marcuzzo77** [comment]
@geomoes Hi, on qgis server I put this path: 
http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?
Is correct?

<img width="697" alt="Schermata 2020-09-22 alle 08 38 44" src="https://user-images.githubusercontent.com/26044319/93851025-ab33da80-fcaf-11ea-8d8b-e932c2411817.png">

**Comment by geomoes** [comment]
Hi, 
that should be correct. My installation is in 
`http://my.domain.com/cgi-bin/qgis_mapserv.fcgi`
without ? at the end.

**Comment by ftheeten** [comment]
Hi, don't forget to upload the ***.qgs.cfg** file created by the Lizmap plugin, not only the project file, otherwise the project won't be visible.
