### ISSUE TITLE
Lizmap is too slow.

### ISSUE THREAD

**Issue by fling-** [3liz/lizmap-web-client#183]
It takes minutes to load the map.
Sometimes it is not loading at all.
I'm running jancelin/docker-lizmap with this project http://be.gis-lab.info/data/osmshp/latest/RU-ALT.7z
from http://beryllium.gis-lab.info/project/osmshp/region/RU-ALT

**Comment by jaitor1** [comment]
In my case I always click "Single Tile" in the config of lizmap plugin for every layer...and image format png8bit. 

Hope it helps.

**Comment by fling-** [comment]
With "Single Tile" option the map loads faster but UI becomes really slow.

**Comment by mdouchin** [comment]
Lizmap is just a proxy between the web browser and QGIS Server.
I opened the project qgis-mapnik.qgs, and it is pretty simple with light data. You should not have any problem with it

If you cannot load data fast enough, you really first have a look at your server configuration and properties:
* CPU number and speed, RAM involved, disk speed
* Apache configuration

You could also create Spatial indexes ( qix files) within QGIS, but since the extent is pretty small, this won't make a big difference

I do not know if docker impacts performances, since I have not tried it.

**Comment by mdouchin** [comment]
I just tried the project in Lizmap in my laptop (localhost server), and it works pretty well here. 
Laptop : 4 CPU @ 2.5Ghz - 4Go RAM  ( So this is a light "server" ).

**Comment by fling-** [comment]
@mdouchin can you please try running jancelin/docker-lizmap with this project?

**Comment by gioman** [comment]
I have also tested your project in a ubuntu server virtual machine with very limited resources allocated (512mb of ram) and it works with no speed issues at all.

**Comment by fling-** [comment]
@gioman Can you please upload the vm running this project without issues?
I'm fighting with the project + lizmap for months by now not being able to make it anyhow useable/fast enough.

**Comment by kali06** [comment]
Bonjour, j'ai le même problème de lenteur,

j'utilise lizmap web-client 2.10.2 + qgis server 2.6 + OS linux debian

je souhaiterais savoir comment améliorer la vitesse d'affichage de mes couches sachant que toutes mes couches sont non tuilées + durée cache client au max + serveur 8 Go RAM + Intel xeon

Cependant, je trouve que les applications prennent du temps à se charger, de même que quand je zoome, les couches prennent du temps à se recharger,

je ne tuile pas mes couches car le temps de chargement est vraiment trop long

je souhaiterais savoir si il y a moyen de configurer le serveur de façon optimale pour améliorer le temps de chargement des couches,

je pense principalement aux paramètrages du mpm-worker et du mod_fcgid,

actuellement, ces deux fichiers ont une configuration standart comme indiqué sur votre site
http://docs.3liz.com/fr/admin_guide/installation/server_configuration.html#configuration-du-mpm-worker

Est-ce qu'il est possible de modifier ces configurations afin d'améliorer la vitesse de chargement des cartes,

en vous remerciant par avance,

Cordialement,

**Comment by gioman** [comment]
@fling- not sure I will be able to do a big upload in the next days, but will try.

**Comment by gioman** [comment]
@fling- please provide a mail address where I can send the download link.

**Comment by rldhont** [comment]
@kali06 Vous pouvez modifier ces fichiers de configuration. Si vous avez une solution merci d'en faire profiter les autres utilisateurs.

**Comment by rldhont** [comment]
@jancelin can you test the @fling- data ?

**Comment by jancelin** [comment]
I have no problem with this datasets under "docker-lizmap-2.11".

look permalink:
http://demo.sig.inra.fr/websig/lizmap/www/index.php/view/map/?repository=agrof&project=osm_shp&zoom=1&lat=6929924.83089&lon=9285272.61239&layers=BTTTTT

**Comment by rldhont** [comment]
Hi @jancelin, thanks for your test.

@fling- it's seems there is no speed problem with "docker-lizmap-2.11" and with your data.

**Comment by fling-** [comment]
@gioman it works fine with qgis-simple.qgs but I'm having issues running qgis-mapnik.qgs
@jaitor1 with a vm from @gioman the single tile is the only option as without it only a little part of the project loaded at the center of the screen. Probably something is wrong with my config? qgis_mapnik.qgs.cfg -> https://gist.github.com/3e3289416ffca578e948
@jancelin may you please switch the project from qgis-simple.qgs to qgis-mapnik.qgs on your server?

**Comment by jancelin** [comment]
The problem become your qgis-mapnik project. 
I create a new project with your data and it's works fine. 

Attention: the number displayed layer simultaneously reduces performance

http://demo.sig.inra.fr/websig/lizmap/www/index.php/view/map/?repository=agrof&project=qgis_mapnik_ju2&zoom=1&lat=6907211.31387&lon=9187263.05004&layers=BTTTTTTTTTTTTTTT

**Comment by fling-** [comment]
@jancelin looks great!
What have you done to the project exactly? Is there something special about it?
Is it possible to remove the underlying layer?
May you please also try setting
"Initial map extent" as '9324621.07093, 7046105.10881, 9325282.27139, 7046477.58775'
and "Scales" as '1000, 2500, 10000, 25000, 50000, 100000, 250000, 500000'

**Comment by fling-** [comment]
I don't see any text on the map btw. There were addresses and street names in the original project.

**Comment by jancelin** [comment]
Make simple projects and regularly tested during the project creation.
Try to replicate the project step by step and layer by layer.
Beware layer names without spaces, not curled image, ...
And then hopefully, change the symbology, popup ...

**Comment by fling-** [comment]
@jancelin may you please add the text to and upload your project? Looks like you already have exactly what is needed for my task.

**Comment by jancelin** [comment]
send me a mail
