### ISSUE TITLE
dataviz histogram doesnt sum y data while scatter does

### ISSUE THREAD

**Issue by brulien** [3liz/lizmap-web-client#1834]
Hi all,

On the following demo map, histograms can represent y data as an average and it seems there should be no restriction to sum, max, etc : https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=cats

I tried to aply it to a project, but unfortunately, data agregation as sum works for scatter dataviz, but for histogram it does only a count agregation, even when sum or average is checked.

With scatter dataviz
![image](https://user-images.githubusercontent.com/25728608/93996760-ec50eb00-fd92-11ea-9577-9d64e0ef94d1.png)

Exactly the same project, same aggregation but with histogram
![image](https://user-images.githubusercontent.com/25728608/93996836-02f74200-fd93-11ea-8f9f-f11cd95f3d41.png)

 - Lizmap version: 3.3.10

Does someone reproduce this ?

Thanks

JB

**Comment by mdouchin** [comment]
I think an histogram is not what you need here, but bar chart.
Histograms groups entities and shows the number of object for each group. At present in Lizmap, you cannot control how Plotly creates the groups.

Try bar charts : you will be able to tune the result better.
