### ISSUE TITLE
Probleme de configuration de PostgreSQL en tant que base de donnée pour Lizmap 

### ISSUE THREAD

**Issue by franyam2006** [3liz/lizmap-web-client#1836]
### Environment

 - Lizmap version: 3.3.6
 - QGIS Server FULL version: 3.10.1
 - QGIS Desktop FULL version: 3.10
 - PostreSQL version: 11
 - OS (Windows, Linux, MacOS, Android…):  Windows 10
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

Bonjour à tous  !

Je suis un nouvel utilisateur de Lizmap. Je l'ai intallé sur mon PC et il fonctionne très bien. Je souhaite utiliser PostgreSQL comme base de données, ainsi selon les instructions de la documentation lizmap, je paramètre mon fichier ....\lizmap-web-client-3.3.6\lizmap\var\config\profiles.ini.php comme suit :

[jdb]

; name of the default profile to use for any connection
default=jauth
jacl2_profile=jauth

;[jdb:jauth]
;driver=sqlite3
;database="var:db/jauth.db"

;[jdb:lizlog]
;driver=sqlite3
;database="var:db/logs.db"

**[jdb:jauth]
driver=pgsql
database=lizmap_base
host=localhost
user=postgres
password=12345

[jdb:lizlog]
driver=pgsql
database=lizmap_base
host=localhost
user=postgres
password=12345**

---------------------------------------------------------------------------

Apres cela je reinstalle lizmap web client en ligne de commande  :

cd C:\xampp\lizmap\prod\lizmap-web-client-3.3.6\
cd lizmap\var\config
copy lizmapConfig.ini.php.dist lizmapConfig.ini.php
copy localconfig.ini.php.dist localconfig.ini.php
copy profiles.ini.php.dist profiles.ini.php
cd ..\..\..

cd C:\xampp\lizmap\prod\lizmap-web-client-3.3.6\
php lizmap\install\installer.php

Je précise que le mot de passe ici (12345) 
c'est le mot de passe d'accès à ma base de données (lizmap_base) dans PostgreSQL et non le mot de passe d'accès à  PostgreSQL lui-même. voir image ci-dessous
![liz](https://user-images.githubusercontent.com/61616432/94041270-8a57ac00-fdb9-11ea-911a-90dad39adf0b.PNG)

Ensuite je charge mes couches dans QGIS a travers PostGIS et je configure le projet QGIS et avec le plugin lizmap et j'enregistre dans le dossier de production. Au finish lorsque je lance lizmap http://localhost/webgis/index.php il affiche SERVICE INDISPONIBLE . Qu'est ce qui n'a pas marché ? Je me demande s'il n'ya pas d'autres manipulation à faire, soit au  niveau de PostreSQL pour faire un lien avec Lizmap ou bien c'est un problème de version des logiciels utilisés. Quelqu'un peut-il me situer où se trouve exactement la faille ? Si quelqu'un l'a déjà fait en utilisant PostreSQL et que cela marche parfaitement qu'il me vienne en aide ! 

Merci beaucoup à toute la communauté. J'espère que mes explications sont un peu claire. S'il y'a des questions je suis là pour vous répondre pour encore rendre plus compréhensible ma préoccupation.

**Comment by Gustry** [comment]
**L'installation** sur une base PostgreSQL (les tables liés à Lizmap) et **l'utilisation** d'une base PostgreSQL sont 2 choses différentes.

> SERVICE INDISPONIBLE

C'est une erreur courante, si QGIS Serveur ne répond pas ou alors si votre configuration PostgreSQL n'est pas bonne dans le projet. Est-ce le mot de passe est bien dans le projet QGIS?

Est-ce que vous avez regardé les tickets ouvert et fermés : https://github.com/3liz/lizmap-web-client/issues?q=is%3Aissue+service+non+disponible+is%3Aopen

**Comment by franyam2006** [comment]
Bonjour Gustry, merci pour l'intéret accordé à ma préoccupation. Je faisais alors une confusion entre l'installation sur une base PostgreSQL (les tables liés à Lizmap) et l'utilisation d'une base PostgreSQL. Je verai avec le lien que vous avez partagé et je vous reviendrai. Merci
