### ISSUE TITLE
Limitation de l'outil locatebylayer?

### ISSUE THREAD

**Issue by veroniqueC** [3liz/lizmap-web-client#184]
Bonjour,

Notre collectivité souhaite basculer son serveur WMS vers la solution lizmap + qgis server. Je compare donc les fonctionnalités de chaque solution.

Lizmap convient pour le moment parfaitement à nos attentes exceptés l'outil locatebylayer.

Cet outil est-il limité en terme de poids de la couche utilisé? En effet nous avons un cadastre de 60 000 lignes et impossible de l’utiliser dans cet outil. (si je descends à 40 000 cela marche).

D'ou peut venir cette limitation?

En vous remerciant,

[EDIT] Réponse partiellement trouvée dans ce post https://github.com/3liz/lizmap-web-client/issues/139
Mais dans ce cas comment l'utilisateur peut-il zoomer sur la parcelle cadastrale de son choix?

**Comment by rldhont** [comment]
Bonjour, La futur version 2.12 et 3 de Lizmap Web Client devrait corriger ce problème grâce à la modification 9d04d8f27985f8ac42714c9627d2d3a77705a082

**Comment by nboisteault** [comment]
@veroniqueC is your issue still ocurring ? Reopen issue if needed.
