### ISSUE TITLE
Problem to Publish my lizmap online 

### ISSUE THREAD

**Issue by franyam2006** [3liz/lizmap-web-client#1843]
hello to the whole community.  I did a webmapping by lizmap which works very well locally.  I want to upload it via github but I can't.  It only displays text and not images and features.  I have however loaded all my openlayers, css, JS and other files.  can someone help me?  thank you.

**Comment by nboisteault** [comment]
What do you mean by publishing via Github?

**Comment by Gustry** [comment]
Closing as duplicated of #1890 

It's not possible to use GitHub Pages with Lizmap.
Either use QGIS2Web or Mappia Publisher
