### ISSUE TITLE
Organization of maps on Projects page

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#1846]
### Description
I'm using a few lizmap servers, on each server my maps are organized by default in a one column layout. With more than 6 maps it gets inconvenient to scroll down every time for the bottom maps. I've seen that on lizmap demo site maps are organized on a nice 4x2 grid.

Probably it is already documented, but I couldn't find where can this property be set. Can you point to the solution?

### Environment

 - Lizmap version: mostly 3.3.10 versions
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04
 - Browser (Firefox, Chrome…): any

**Comment by nboisteault** [comment]
You can use custom CSS to display repository/projects as you wish. https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#creating-simple-themes

**Comment by aeduard** [comment]
After reading the documentations I've downloaded the default theme both from my site and demo lizmap site (projects organized in rows). Not 100% clear which css file goes for the main project page, presumably main.css. I've compared the main.css files from these two lizmap sites and I have found no difference.
What I see as a difference with Firefox Inspector is the organization of <'ul> and <'li> elements. In my case for each project I have an <'ul> element which contains a single <'li> element. At the demo site there is only one <'ul> element and all <'li> children are within that single <'ul>. As a consequence I have 1 list with 1 element for each of my projects (maps), while at the demo site there is only one list with many elements within it.

Can someone share a css file which contains configuration for this type of horizontal layout?

**Comment by aeduard** [comment]
I have an update. Still I think there are other differences between demo project and the master lizmap package installed by default. Although with the following css line inserted on default theme's main.css file helped to achieve something similar.

`.thumbnails.liz-repository-project-list {
    display: inline-block;
}`
`.liz-repository-title {
    display: none;
}`

If it don't appear right away upon refresh, try ctrl+shift+r (to refresh page without cache).

**Comment by Gustry** [comment]
> If it don't appear right away upon refresh, try ctrl+shift+r (to refresh page without cache).

Yes, you should empty your webbrowser cache.
It's mentioned in the next version of the doc https://docs.lizmap.com/next/en/publish/customization/themes.html

Can we close?

**Comment by aeduard** [comment]
Yes, it can be closed, but still missing the information about the logic behind the organization of lizmap maps in project folder.

**Comment by geomoes** [comment]
Hi until now the display of the project thumbnails worked with the above css:

```
.thumbnails.liz-repository-project-list { display: inline-block; }
.liz-repository-title { display: none; }
```

After switching to 3.5.3 it stopped working. Projects are displayed one under the other even though the code is in my main.css?
