### ISSUE TITLE
Plots in popup - Cats movements map

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#1853]
Hello
I saw this nice map on Lizmap website
https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=cats

How did you insert plots into popup?

Do you have some example code to achieve this popup??
Thanks
Pietro

**Comment by Gustry** [comment]
I agree, it's not easy to understand these labels, but you need to use the `Only show in child popup` checkbox.

https://docs.lizmap.com/next/en/publish/lizmap_plugin/dataviz.html#configuring-the-tool

> Only show child popup : The main graph will not be shown in the main container and only the filtered graph of the relation of the layer will be displayed in the popup when you select the e

**Comment by pieri70** [comment]
Ok, thanks! I'll make some test soon..
