### ISSUE TITLE
question for Filtering data 

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-web-client#1859]
Hi. At my project is not function "search" and "filter data" . Select is ok, but zoom and center function not.
My project is here https://gisland.eu/mapserver/index.php/view/map/?repository=cernetice&project=cernetice
Layer for filtering is "body", at .csv format. Please where is problem.
Thanks
LM 3.3.10
qgis server 3.14

**Comment by nboisteault** [comment]
Hi,
You have to use QGIS LTR (long term release) which is currently 3.10.

**Comment by majky-beast** [comment]
Hi,
I had a simillar problem. In my case solution was transform coordinate system for all layers in my project from SJTSK to ETRS 89 lat long (WGS 84 equivalent). Then open a empty project, import transformed layers and set project CRS to EPSG: 3587. After that I used Lizmap plugin set everything up and it should work.

**Comment by gisgogo** [comment]
Hi. The solution was usage qgis LTR version 3.10. Thanks. 
But now is new problem. When i set cached any layer ( I'm not caching the data layer for filter), filtering data not function. When i set cache off, filtering data is ok.
