### ISSUE TITLE
Error: Data table display error

### ISSUE THREAD

**Issue by JogicPogic** [3liz/lizmap-web-client#186]
My map has 3 layers from PostgreSQL tables.
Table 1 contains dozens of records.
Table 2 contains hundreds of records.
Table 3 contains thousands of records (about 40K).

When i click the button "Detail" to output data from table 3 or table 2, nothing appears.
I found out, that browser receives broken JSON-data from server. See screenshot below.
Is it possible to add pagination on Data tab and load data dynamically?

![lizmap data fetch error](https://cloud.githubusercontent.com/assets/13277024/8856684/bbee95ae-3185-11e5-81f8-dcbac10f2364.png)

**Comment by rldhont** [comment]
This has been fixed by d45605bc74a9b0e30aaa278a7d0afd9e26921b77

Reopen if not
