### ISSUE TITLE
Which version of Apache?

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#1862]
### Description
One question. I'm using a development version of Lizmap from late 2019 and everything works perfectly with my web server, Apache 2.2.x.
I tried to install the latest version of Lizmap, 3.2.x and 3.3.x and I can install all the components but when I go to see the projects I get a 500 error. Usually this error is related to the web server so I ask you if in these newer versions of Lizmap is it mandatory to use the Apache 2.4.x version?
Did you change the code and then the old Apache 2.2 doesn't work anymore?

### Environment

 - Lizmap version: 3.2.16, 3.3.10
 - QGIS Server 3.10:
 - QGIS Desktop 3.10:
 - OS (Linux, MacOS): 
 - Browser (Firefox, Chrome, Safari…):
 - Lizmap admin information (users, logs…) stored into Sqlite

Thank you for your answer
Lorenzo

**Comment by nboisteault** [comment]
I'm not sure about Lizmap compatibility with Apache 2.2 but you should definitely upgrade to 2.4 as [2.2 is End-of-Life since December 2017](https://httpd.apache.org/security/vulnerabilities_22.html).

**Comment by news24lor** [comment]
Yes I know that Apache 2.2 is EOL. It was just to understand why an old version of Lizmap works perfectly while recent versions of Lizmap always give me the same error.
Soon I will switch to version 2.4 but on a computer with official websites it takes a bit more time.
