### ISSUE TITLE
editing tables with qgis db manager versioning

### ISSUE THREAD

**Issue by tethysgeco** [3liz/lizmap-web-client#1863]
### Description
Hi, have you ever published postgis tables where the versioning function available in QGIS db manager was applied (ref. image)? 
![immagine](https://user-images.githubusercontent.com/23027624/95433611-76cb4a00-0950-11eb-96ea-3e14332c358c.png)
If we try to edit the “current” view that is created a generic error is returned by lizmap (no error from qgis desktop with the same db user). Have you any idea about the reasons? Thank you

### Environment

 - Lizmap version: 3.3.10
 - QGIS Server FULL version: 3.4
 - QGIS Desktop FULL version: 3.4 and 3.12
 - OS (Windows, Linux, MacOS, Android…): debian
 - Browser (Firefox, Chrome…): Firefox, Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by pcav** [comment]
The original table should be edited, not the view.
Cheers.

On 8 October 2020 10:37:48 CEST, tethysgeco <notifications@github.com> wrote:
>### Description>
>Hi, have you ever published postgis tables where the versioning
>function available in QGIS db manager was applied (ref. image)? >
>![immagine](https://user-images.githubusercontent.com/23027624/95433611-76cb4a00-0950-11eb-96ea-3e14332c358c.png)>
>If we try to edit the “current” view that is created a generic error is
>returned by lizmap (no error from qgis desktop with the same db user).
>Have you any idea about the reasons? Thank you>
>>
>### Environment>
>>
>>
>>
> - Lizmap version: 3.3.10>
> - QGIS Server FULL version: 3.4>
> - QGIS Desktop FULL version: 3.4 and 3.12>
> - OS (Windows, Linux, MacOS, Android…): debian>
> - Browser (Firefox, Chrome…): Firefox, Chrome>
>- Lizmap admin information (users, logs…) stored into Sqlite (default)?
>PostgreSQL? MySQL? >
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/3liz/lizmap-web-client/issues/1863

-- 
Please excuse my brevity.

**Comment by tethysgeco** [comment]
but the meaning of the following rule is not something like "update the original table even when user start editing from the view" ?
CREATE OR REPLACE RULE "_UPDATE" AS ON UPDATE TO "demo"."table_current" DO INSTEAD
  UPDATE "demo"."table" SET etc etc

thanks again

**Comment by pcav** [comment]
Have you checked the log?
I agree that it *should* work, but I'm not surprised it doesn't.

**Comment by tethysgeco** [comment]
last lines summed up from lizmap log:
....error	An error has been raised when saving form data edition to db : 
...[403]	query non valida (ERROR:  cannot perform UPDATE RETURNING on relation "table_current"
HINT:  You need an unconditional ON UPDATE DO INSTEAD rule with a RETURNING clause.( UPDATE "demo"."table_current" SET "fid"=115, "scenario"='xxxx', "data"='xxxxx' WHERE "id_hist" = 111  RETURNING "id_hist";))	/var/www/lizmap-web-client-3.3.10/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	180
	/index.php/lizmap/edition/saveFeature
array (   'module' => 'lizmap',   'action' => 'edition:saveFeature',   'liz_project' => 'test',   'liz_repository' => 'test',   'liz_layerId' => 'table_current_dcca2425_ae90_4be1_98df_3d9529a232e0',   'liz_featureId' => '111',   'liz_srid' => '3003',   'liz_proj4' => '+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs',   'liz_geometryColumn' => 'geom',   'liz_status' => '0',   '_submit' => 'submit',   'geom' => 'POINT(xxx)',   '__JFORMS_TOKEN__' => 'c76f9b9245728850300d1c47ea16d2f6',   'scenario' => 'xxxx',   'data' =>    array (     'day' => 'xx',     'month' => 'xx',     'year' => 'xxx',   ),   'id_hist' => '111',   'fid' => '115',   'liz_future_action' => 'close', )

	0	pgsqlDbConnection->_doQuery()	/var/www/lizmap-web-client-3.3.10/lib/jelix/db/jDbConnection.class.php : 129
	1	jDbConnection->query()	/var/www/lizmap-web-client-3.3.10/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php : 825
	2	qgisVectorLayer->updateFeature()	/var/www/lizmap-web-client-3.3.10/lizmap/modules/lizmap/classes/qgisForm.class.php : 661
	3	qgisForm->saveToDb()	/var/www/lizmap-web-client-3.3.10/lizmap/modules/lizmap/controllers/edition.classic.php : 640
	4	editionCtrl->saveFeature()	/var/www/lizmap-web-client-3.3.10/lib/jelix/core/jCoordinator.class.php : 225
	5	jCoordinator->process()	/var/www/lizmap-web-client-3.3.10/lizmap/www/index.php : 23

**Comment by rldhont** [comment]
@tethysgeco your database said : **ERROR: cannot perform UPDATE RETURNING on relation "table_current"
HINT: You need an unconditional ON UPDATE DO INSTEAD rule with a RETURNING clause.**

**Comment by pcav** [comment]
Unsure whether this is strictly a problem with Lizmap, or the RULE should be updated in DB Manager.

**Comment by pcav** [comment]
In this second case, I suggest you to:
* fix the RULE in your table by hand, and
* open a ticket on DB Manager (it should be an easy fix)

**Comment by rldhont** [comment]
Lizmap made SQL UPDATE with RETURNING clause.

**Comment by tethysgeco** [comment]
Hi, we're testing a different approach, working with two tables (not a table and a view): one for the current situation and one for the historical data + a trigger to archive data from one to the other.. at the moment it seems a suitable solution for our situation. Lizmap (3.4.1) has no problem, editing is allowed only on the current situation and the trigger is working fine. I'm not sure if in the next months we'll test again also the "versioning" option. Thanks for your support
