### ISSUE TITLE
Geometries are saved in the wrong CRS

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#1873]
### Steps to reproduce the issue

I have a LMWC project where I have a PostGIS layer that has CRS EPSG 3763 and the QGIS project has the same CRS.

Editing (adding) a new feature seems to work, but then the geometry do not show in the map.

An inspection of the table shows that the geometry is written, but not with the right CRS (seems to be WGS84).

If the project is set with a different CRS (i.e. 3857 ou 32629 or 4326) then the geometries are saved as expected.

###  please complete the following information 

 - Lizmap version: 3.3.10
 - QGIS Server FULL version: Ubuntu Server 20.04
 - QGIS Desktop FULL version: QGIS 3.10.10
 - OS (Windows, Linux, MacOS, Android…): Linux and Windows
 - Browser (Firefox, Chrome…): FF
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PostgreSQL 12 and PostGIS 3

**Comment by nboisteault** [comment]
Hi @gioman 
I can't reproduce your issue with LWC in release_3_3 branch. What is your QGIS Server version?
