### ISSUE TITLE
Error import API Key Google

### ISSUE THREAD

**Issue by Marcuzzo77** [3liz/lizmap-web-client#1874]
I tried to upload a project to my Lizmap server with Google maps in the background.
Since 2016 this is no longer possible in a simple way, but you have to request the API from Google to make sure that their maps are seen.
I then requested the key that I entered in the Lizmap plugin with Qgis.
I saved my work and uploaded it to my remote server.
But it still gives me error.
Before the map I was viewing now its gray screen with the words "Sorry, there was a problem"
Do you know any more news about it?
Marco

**Comment by pcav** [comment]
Please file tickets in English.
Thanks.

**Comment by Gustry** [comment]
If you disable google layer, the application is back online and working?

Is there any Google dev key available ?
