### ISSUE TITLE
LIZMAP GetMedia Jelix error

### ISSUE THREAD

**Issue by majky-beast** [3liz/lizmap-web-client#1875]
### Description
Hi,
After I installed Lizmap on Windows Server 2019 one problem appear. If I want see pictures attached with layer in LWC or any other pictures I got error 500(internal jelix error). Interesting is that in my desktop windows 10 lizmap works fine and I don´t have any errors at all. In both caseses I have installed same version of LWC on server and desktop and pictures are stored in media directories, according installing lizmap on Windows document. In buttom of my question I will poste some printscreens of LWC in Win 10 (called localhost), and Windows Server 2019 (called server). Do you have any suggestion what can cause this error on my server?
Thank you
### Environment

 - Lizmap version: 3.3
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Windows 10, Windows Server 2019
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default) 

![localhost_PC_2](https://user-images.githubusercontent.com/72867236/96418549-3642ba80-11f3-11eb-97fe-71508585a4f7.jpg)
![localhost_PC_3](https://user-images.githubusercontent.com/72867236/96418553-380c7e00-11f3-11eb-934d-42b9a017c2c0.jpg)
![server_1](https://user-images.githubusercontent.com/72867236/96418555-38a51480-11f3-11eb-8e6e-ba0eed75cb33.jpg)
![server_2](https://user-images.githubusercontent.com/72867236/96418557-38a51480-11f3-11eb-8b25-e8df617e8ae2.jpg)

**Comment by Gustry** [comment]
Can you check file rights?
Maybe the webserver is not allowedto read these PNG?

Is-it the same project (same tree) between local and servers?

**Comment by majky-beast** [comment]
Yes between local and server I have same tree (folders have just different names). Because I´m new in this I don´t know where should I check file rights in Windows server...Do you have any suggestions where can I check it?
