### ISSUE TITLE
Enhancemenet: When editing a layer, don't show element selection window if there is only one element

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#188]
If there is only one element to be selected, there is no point in showing the window of element selection and having to click on select..especially if you need to edit 6000 elements in the street...

If there is more than one element in de BBOX where you clicked it's ok.

Example with only one possibility to select:

![image](https://cloud.githubusercontent.com/assets/12136796/8931530/4d97f6bc-3537-11e5-875a-dfd6986f2c63.png)

**Comment by nboisteault** [comment]
+1

**Comment by rldhont** [comment]
Fixes 76198f542d5a6cdfb987b74f2025988de8f44da1
