### ISSUE TITLE
Map layouts show scale values with a  comma instead of the locale set in the projects

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#1887]
# Problem

Create a project in QGIS and check the scale in the print template.
![layrout-scale](https://user-images.githubusercontent.com/2510900/97111196-27be3c80-16e6-11eb-88dd-00b06ec95fa6.png)

Print the map using lizmap and you get the following output. Lizmap shows the scales with a comma and this is passed to the template
![layouts](https://user-images.githubusercontent.com/2510900/97111252-7b308a80-16e6-11eb-8a16-b9aeca28e90b.png)

**Comment by Gustry** [comment]
This is not a issue with Lizmap as Lizmap is only forwarding the request to QGIS Server with a GetPrint request.

I think you need to use environment variables in QGIS Server : `QGIS_SERVER_OVERRIDE_SYSTEM_LOCALE` and/or `QGIS_SERVER_SHOW_GROUP_SEPARATOR` https://docs.qgis.org/testing/en/docs/server_manual/config.html#environment-variables.

In the QGIS.ini file, there is also `show_thousand_separator=true`
