### ISSUE TITLE
How to publish a Lizmap project online via Github for free?

### ISSUE THREAD

**Issue by franyam2006** [3liz/lizmap-web-client#1890]
### Environment

 Lizmap version: 3.3.6
QGIS Server FULL version: 3.10.1
QGIS Desktop FULL version: 3.10
PostreSQL version: 11
OS (Windows, Linux, MacOS, Android…): Windows 10
Browser (Firefox, Chrome…): Chrome
Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

Good morning all !
I really hope to find an adequate answer to my concern. Thank you already for the interest you are going to give it.

OK ! in fact, I have done a locally developed Lizmap project with wampp as the local server. And it works very very well, locally of course! Lol
Now I want to put it online with the "free" module of Github .

My js, css, index.php, admin.php and other files useful for displaying my page are located in the "www" folder (the path is as follows): C: \ xampp \ lizmap \ prod \ lizmap -web-client-3.3.6 \ lizmap \ www. see image below 👍 

![www](https://user-images.githubusercontent.com/61616432/97168851-0c543f80-1781-11eb-8678-02cc803e79dc.PNG)

OK. Now I have my shapefiles in another folder (C: \ xampp \ webapp \ prod \ maprep). image below again 

![shp](https://user-images.githubusercontent.com/61616432/97169100-62c17e00-1781-11eb-8d9f-82bbb29ced26.PNG)

I downloaded Github Desktop with which I cloned my repository on my github account!

I gathered everything ( all my shapefile and the  css file, js, index.php, admin.php and all other folders) in a single  folder named 'franyam2006' created in a large GITHUB folder on my local C drive ( C: \ GITHUB \ franyam2006). NB: franyam2006 is the domain name created in my repository on my github.com account.

![github_file](https://user-images.githubusercontent.com/61616432/97169154-7b319880-1781-11eb-9520-1160244c208e.PNG)

 I then followed the procedure to publish the files with github desktop. image below

![desk](https://user-images.githubusercontent.com/61616432/97169360-d6638b00-1781-11eb-82d5-c52c0a4f5028.PNG)

After all these steps I still cannot display my lizmap page. Although the page is created in 'github pages'. see here

![page](https://user-images.githubusercontent.com/61616432/97169462-06129300-1782-11eb-9a00-fce9d2af74f1.PNG)

I would like to know if there are people who have been able to publish their Lizmap project via github that they can help me, there is certainly a detail that I do not understand. after watching a lot of tutorial, I can't do it! What is the right way to put a lizmap project online with github? 
Regardless of the approach I explained, if you can explain yours to me which allowed you to publish your Lizmap project online for free via github I got it.

 thank you in advance !

**Comment by Gustry** [comment]
You already created the ticket https://github.com/3liz/lizmap-web-client/issues/1843

It's not possible.
Lizmap is a "dynamic" application, with PHP.

If you want to use GitHub Pages, you must use "qgis2web" or "Mappia Publisher".

**Comment by franyam2006** [comment]
Really ! I tried so much that I couldn't remember. thank you again for the repetition, lol. I think I at least had a peace of mind knowing where the blockage came from. It reassures me ! thank you
