### ISSUE TITLE
Project wont load, arbitrary behaviour 

### ISSUE THREAD

**Issue by GitMorin** [3liz/lizmap-web-client#190]
EDIT:

This problem seem to be a encoding problem of some kind. As far as I know all is running on UTF-8, its not clear to me what causes the problem.

I am using Lizmap 2.11

My project sometimes seem to stop working for reason I would like to find out. 
I set up a simple project with just one layer, a multiline vector layer, without any fuzz (no pop-up nothing). Open my project and the loading project just hang and wont load it. 

If i add a layer I know have worked before, open the project to see that it works fine then add the multiline layer to the project and NOW i can see the mulitline layer. Both layers has the same ESPG: 25832. If I remove the first layer my multiline layer still works.
If I now continuee builiing up my project it seem to be working fine, then if I add a layer or duplicate a layer then the loading project might hang again and I have to start from scratch.
If I change the title of a working project it might also stop working?

This happen with different layers and dont seem to be reproducible, it seem to randomly happen at any point. All my layers are in the same ESPG and all are called from PostGIS. Any ideas what this can be?

Thanks

**Comment by nboisteault** [comment]
@GitMorin does your issue still occur ? Reopen issue if needed.
