### ISSUE TITLE
Error connection to postgresql - 3.3.pre

### ISSUE THREAD

**Issue by marco-03091991** [3liz/lizmap-web-client#1904]
### What is the bug?
I'm working on an older version of Lizmap 3.3.pre running on a server Ubuntu 16.04.06. I'm not the owner of the server and I cannot at the moment upgrade to the newest Lizmap.
Actually everything works  (like using shapefile) but lizmap cannot connect to PostgreSQL data. I have the qgis project with the user and password saved.
See the attached log error.
Should we need to upgrade or we can fix it without upgrading?
Best
Marco

### Screenshots and logs

![lizmap_error](https://user-images.githubusercontent.com/61871099/98108559-731ddb00-1e9c-11eb-9042-7bebca4492c1.png)

![Screenshot at 2020-11-04 12%3A44%3A40](https://user-images.githubusercontent.com/61871099/98108576-7913bc00-1e9c-11eb-9763-8b919aad6752.png)

The result is that lizmap doesn't display PostGIS layers

### Environment

 - Lizmap version: 3.3.pre
 - QGIS Server FULL version: 2.18
 - QGIS Desktop FULL version: 2.18
 - OS (Windows, Linux, MacOS, Android…):  Ubuntu 16.04.06 LTS
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

**Comment by nboisteault** [comment]
Sorry, we can't help on old versions.

**Comment by marco-03091991** [comment]
don't worry, i will attempt to upgrade it to 3.3.11 and find out If the problem persists or not
thank you

**Comment by Gustry** [comment]
When you mean 3.3.pre, is-it before 3.3.0 ?
Please, try the latest bugfix of LWC.
Also consider upgrade your QGIS Server.

**Comment by marco-03091991** [comment]
the LWC version is 3.3pre.181017, I don't know why is  installed this version, however, I hope to upgrade it tomorrow
thank you
M

**Comment by marco-03091991** [comment]
I just upgraded to LWC 3.3.11 but I still have the same error to visualize layer from PostGIS, the error is:
2020-11-16 18:49:27	127.0.0.1	error	2020-11-16 18:49:27	[402]	errore durante la connessione 127.0.0.1	/var/www/mylizmap/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	159

any idea's to fix it?
best
Marco
