### ISSUE TITLE
attribute table - display info

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1905]
hi,

the display info ![imagem](https://user-images.githubusercontent.com/10053874/98262459-8b195b80-1f7d-11eb-83eb-0a6886b9eb81.png) is not avaiable for postgresql views

thanks

 - Lizmap version: 3.3.11
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10

**Comment by josemvm** [comment]
goog morning!

just to remind you, please, can you try to fix this issue?

thanks :-)

**Comment by josemvm** [comment]
thanks @nboisteault, very kind! :smirk:

**Comment by Gustry** [comment]
@josemvm Did it work before ? If yes, which LWC version ?

**Comment by josemvm** [comment]
hi @Gustry 

ok, maybe this is not a bug but an enhancement. is that what you want to say me? - i agree

**Comment by rldhont** [comment]
It is an issue in QGIS Server, do you have a project to test ?

**Comment by nboisteault** [comment]
> thanks @nboisteault, very kind!

Not as kind as a PR or some sponsored bug fix!  😆

**Comment by josemvm** [comment]
hi @rldhont, thanks for your feedback
yes of course, please check your mailbox

**Comment by josemvm** [comment]
> Not as kind as a PR or some sponsored bug fix! 

@nboisteault yes, it's true and the humor is also needed more and more :smiley:

**Comment by Gustry** [comment]
> ok, maybe this is not a bug but an enhancement. is that what you want to say me? - i agree

Honestly, I got no idea if it was working before ;-)
I was just wondering if yes or not it's a regression in LWC code.

**Comment by josemvm** [comment]
@Gustry sincerely, i don't know if it ever worked... i hadn't experienced it before.
thanks for all your work :-)

**Comment by josemvm** [comment]
hi @rldhont 

is there a solution in progress?
thanks

**Comment by Gustry** [comment]
@josemvm We would make a link to a pull request if we got any progress about that.

And as @nboisteault added the label, we don't plan to work on that.
