### ISSUE TITLE
DataPlotly integration

### ISSUE THREAD

**Issue by ghtmtt** [3liz/lizmap-web-client#1906]
The usage of plotly in the dataviz tool of lizmap is great but maybe we can try to integrate DataPlotly within Lizmap. e.g. see https://www.youtube.com/watch?v=ZnlYMHrLWYk

I think a more reasonable situation could be developed, like a button `export plot settings for lizmap` or similar

cc @pcav

**Comment by Gustry** [comment]
Closing because you made a duplicate with #1907

**Comment by ghtmtt** [comment]
github gave me a 404 and I thought it was not created. sorry for the noise
