### ISSUE TITLE
Dataplotly integration

### ISSUE THREAD

**Issue by ghtmtt** [3liz/lizmap-web-client#1907]
While the dataviz tool in lizmap is great we can think to integrate dataplotly within lizmap itself (e.g. see https://www.youtube.com/watch?v=ZnlYMHrLWYk)

I think a button like `export plot settings for lizmap` or similar could be reasonable

cc @pcav

**Comment by Gustry** [comment]
There is already a RFC for this idea : https://github.com/3liz/lizmap-rfc/issues/8

Can we close this issue and express your idea there ?

I think it's not going to be as easy. Even if during trainings I teach using DataPlotLy to start and then switch to Lizmap, it's not going to be easy in Dataplotly to know which options are available in LWC or not.

Not totally related to this ticket, but we talked about having DataPlotLy as q QGIS Server plugin ?
Did you think about that one ? So we could print PDF (either atlas or not) with charts ?

**Comment by ghtmtt** [comment]
@Gustry yes we can close this ticket and compact all the ideas on the other one!
