### ISSUE TITLE
drive down lists -  value relation in layer edition  

### ISSUE THREAD

**Issue by brebe** [3liz/lizmap-web-client#1908]
hello dear guys,

i want to use the edit function on a layer called problems in which i have 2 attributes (among others)

1. **towns  -  varchar field**
    (widget type:value relation in qgis project to a dictionary towns, relation based on   key_column:id / value_column: name_town )
    dictionary towns has columns : id, name_town
2. **streets - varchar field** 
   (widget type:value relation in qgis project to a dictinary street, relation based on key_column:id /value_column: street_name 
+ filter expression  
` "id_town" = current_value('town') `
)
   dictionary street has columns :  id , street_name, id_town

i want in edition mode in form to select town first(combobox)  and automatically  filter streets field in street combobox based on town selected.
same like 
**value relation widget - drive down lists (filter expression)**
https://github.com/3liz/lizmap-web-client/issues/1242

i read the forum that this problem was fixd in master, i installed the master branch(also i tried with the version 3.3.11) but nothing, i can select the towns from combobox,
but the street combobox is empty, and also errors.log not showing any error

using lizmap web client 3.3.11 i get the error in errors log:
```
2020-11-07 11:48:48	::1	notice	2020-11-07 11:48:48	[8]	Undefined variable: widgetv2configAttr	/var/www/lizmap-web-client-3.3.11/lizmap/modules/lizmap/classes/qgisFormControl.class.php	299

2020-11-07 11:48:48	::1	warning	2020-11-07 11:48:48	[2]	First parameter must either be an object or the name of an existing class	/var/www/lizmap-web-client-3.3.11/lizmap/modules/lizmap/classes/qgisFormControl.class.php	299
```

![Screenshot from 2020-11-07 12-33-52](https://user-images.githubusercontent.com/15627303/98438835-942d3880-20f5-11eb-965b-f23c59ccc233.png)

what am i doing wrong ?
thank you

### Environment

Lizmap version: 3.3.11
QGIS Server FULL version:3.14.16-Pi
QGIS Desktop FULL version:3.12
OS (Windows, Linux, MacOS, Android…): Ubuntu 20
 OS (Windows, Linux, MacOS, Android…): Ubuntu 20
 Browser (Firefox, Chrome…): ALL
 Lizmap admin information (users, logs…) Sqlite

**Comment by nboisteault** [comment]
Hi,
You have to use qgis desktop and server 3.10 as it is a LTR version. It will probably work with more recent versions but we have not tested yet.
Use lizmap master and not 3.3.11.
You also have to install lizmap plugin as a qgis server plugin for this feature to work.

**Comment by brebe** [comment]
> Hi,
> You have to use qgis desktop and server 3.10 as it is a LTR version. It will probably work with more recent versions but we have not tested yet.
> Use lizmap master and not 3.3.11.
> You also have to install lizmap plugin as a qgis server plugin for this feature to work.

Thank you, 
i downgraded qgis-server to 3.10 and saved qgs project with desktop 3.10 but i cannot find any info about 
how to install lizmap plugin as qgis-server. can you point me to some docs so i can figure it out?

**Comment by nboisteault** [comment]
You have to download master version of lizmap plugin and install it like any other qgis server plugin : https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/plugins.html#installation

**Comment by Gustry** [comment]
> You have to download master version of lizmap plugin and install it like any other qgis server plugin : https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/plugins.html#installation

It's `dev` version, not `master`.
You can find the zip on https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/
It's both server and desktop.

Side note, you shouldn't have trouble with higher version of QGIS.
3.16 is LTR soon so we accept feedbacks about the next LTR ;-)
The only advice is to use the same version between QGIS Desktop and Server.

**Comment by josemvm** [comment]
hi,

the same problem here:

![imagem](https://user-images.githubusercontent.com/10053874/98453121-84414300-214d-11eb-8726-68bcfda9b830.png)


```
2020-11-07 23:57:51	xxx.xxx.xxx.xxx	warning	2020-11-07 23:57:51	[2]	Invalid argument supplied for foreach()	/var/www/html/lizmap-web-client-3.4.0-alpha.4/lizmap/modules/lizmap/classes/qgisFormValueRelationDynamicDatasource.class.php	40

**Comment by brebe** [comment]
thank you , for your help i am going to apply them

**Comment by josemvm** [comment]
@brebe 

from http://localhost/cgi-bin/qgis_mapserv.fcgi?SERVICE=LIZMAP&REQUEST=GETSERVERSETTINGS

you need to get something like this:

![imagem](https://user-images.githubusercontent.com/10053874/98466149-99f24f00-21c5-11eb-9c3d-090b19af5d9e.png)

**Comment by brebe** [comment]
> @brebe
> 
> from http://localhost/cgi-bin/qgis_mapserv.fcgi?SERVICE=LIZMAP&REQUEST=GETSERVERSETTINGS
> 
> you need to get something like this:
> 
> ![imagem](https://user-images.githubusercontent.com/10053874/98466149-99f24f00-21c5-11eb-9c3d-090b19af5d9e.png)

![Screenshot from 2020-11-08 15-28-14](https://user-images.githubusercontent.com/15627303/98466264-13466d80-21d7-11eb-8157-43be32b18c6a.png)

**Comment by josemvm** [comment]
this is my qgis server plugin structure:

![imagem](https://user-images.githubusercontent.com/10053874/98466530-11c17900-21c8-11eb-932b-e9445aa7df1f.png)

**Comment by brebe** [comment]
same , on my side, but shall i move it to /opt/qgis-server ?

**Comment by Gustry** [comment]
It's not related to the plugin structure.

There is something wrong in the CFG file.
@brebe Can you share it ? Either here on this ticket, or on https://paste.sh/ or by email ?

**Comment by brebe** [comment]
> It's not related to the plugin structure.
> 
> There is something wrong in the CFG file.
> @brebe Can you share it ? Either here on this ticket, or on https://paste.sh/ or by email ?

yes i am sending by email now

**Comment by Gustry** [comment]
After some checks, can you try the latest zip available https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/ ?
I think there is a server config issue about utf8, CF discussion by email.

**Comment by brebe** [comment]
hello again, i did, but same error....

**Comment by Gustry** [comment]
Ok, thanks for the feedback.

Let's keep the ticket open for the documentation.

**Comment by brebe** [comment]
ahaa, sorry

**Comment by Gustry** [comment]
> Thank you, with the latest dev version it worked

Just to confirm, can you tell us what is working ?

The lizmap server plugin AND the drilldown form ?

**Comment by brebe** [comment]
yeap everything  now,

 i am filtering in a edition form the streets by towns and ITS WORKING!!!
I am qgis server /desktop 3.10 and lizmap webclient master.

**Comment by Gustry** [comment]
Great !

Feel free to make a tweet with a GIF or screenshot showing off your new form ! We will happily retweet it ;-)
The drill down is one of the key feature of LWC 3.4.

**Comment by josemvm** [comment]
hi @brebe can you share your project with me? my project works fine on qgis desktop but not yet on lizmap...
thanks

**Comment by brebe** [comment]
> hi @brebe can you share your project with me? my project works fine on qgis desktop but not yet on lizmap...
> thanks
its not only the qgis project.....

i am using 
qgis server and desktop 3.10 
lizmap web client master(current one) 
apache 2.4 

i described the relationship between towns and street (value relation with the filter "id_town" = current_value('town') on street layer and i use drag and drop designer)

1. download and install lizmap plugin from here 
https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/ - zip file with timestamp TODAY (the latest zip available with utf8 problem solved) into qgis desktop manually (install from zip) , resave the project with the lizmap dev plugin. 
put the .qgs and .cfg  into /var/www/projects and set ownerhship right
`chown -R www-data:www-data /var/ww/projects  `

2. the downloaded archieve from https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/ unzip it.
the lizmap folder from the archive put it into /var/www/qgis-server (i put there the qgis-server plugins).
into /etc/apache2/mods-enabled/fcgid.conf  set the most important 
```
FcgidInitialEnv QGIS_PLUGINPATH "/var/www/qgis-server/plugins" # this is where you set the qgis-server plugin folder
SetEnv PGSERVICEFILE /home/brebex/.pg_service.conf  #connect to postgis 
SetEnv PGSERVICE=mydb
```
and i put the pg_service.conf into /etc/postgresql-common - that was the first problem because i used the name .pg_service.conf

thats it

**Comment by josemvm** [comment]
finally, with qgis server plugin updated everything works like a charm 👍 
thanks to lizmap team developpement for this great new feature!!! :-)

**Comment by brebe** [comment]
side subject question ,
in form filtering is it possible to have same drill down comboboxes ?

**Comment by nboisteault** [comment]
@brebe It has not been developed currently.

**Comment by sergiuspinheiro** [comment]
> 
> 
> > hi @brebe can you share your project with me? my project works fine on qgis desktop but not yet on lizmap...
> > thanks
> 
> its not only the qgis project.....
> 
> i am using
> qgis server and desktop 3.10
> lizmap plugin 3.2.19-beta-
> lizmap web client master(current one) 3.4.0-alpha.4
> apache 2.4
> postgres 12 / postgis
> 
> i described the relationship between towns and street (for street value relation with the filter "id_town" = current_value('town') on street layer and i use drag and drop designer)
> 
>     1. download and install lizmap plugin from here
>        https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/ - zip file with timestamp TODAY (the latest zip available with utf8 problem solved) into qgis desktop manually (install from zip) , resave the project with the lizmap dev plugin.
>        put the .qgs and .cfg  into /var/www/projects and set ownerhship right
>        `chown -R www-data:www-data /var/ww/projects  `
> 
>     2. the downloaded archieve from https://packages.3liz.org/pub/lizmap-qgis-plugin/dev/ unzip it.
>        the lizmap folder from the archive put it into /var/www/qgis-server (i put there the qgis-server plugins).
>        into /etc/apache2/mods-enabled/fcgid.conf  set the most important
> 
> 
> ```
> FcgidInitialEnv QGIS_PLUGINPATH "/var/www/qgis-server/plugins" # this is where you set the qgis-server plugin folder
> SetEnv PGSERVICEFILE /home/brebex/.pg_service.conf  #connect to postgis 
> SetEnv PGSERVICE=mydb
> ```
> 
> and i put the pg_service.conf into /etc/postgresql-common - that was the first problem because i used the name .pg_service.conf
> 
> thats it

qgis server and desktop 3.16.1
lizmap plugin 3.4
lizmap web client 3.4

In windows environment the path is:
X:\OSGeo4W64\apps\qgis\python\plugins\

It works perfectly, congratulations to the whole team.

It would be possible to document the windows installation with the same information as the linux installation
https://docs.lizmap.com/current/pt/install/linux.html#qgis-server-plugins

Thank you very much.

**Comment by Gustry** [comment]
Thanks for your feedbacks about the drill-down ! Appreciated.

Can you create the ticket for the documentation ? https://github.com/3liz/lizmap-documentation

**Comment by sergiuspinheiro** [comment]
Thank you.

https://github.com/3liz/lizmap-documentation/issues/170#issue-788300375

**Comment by sergiuspinheiro** [comment]
> hi @brebe and @sergiuspinheiro does this still working for you?

Hi @josemvm, I apologize for the delay in responding. yes it still works.

qgis server and desktop 3.16.1
lizmap plugin 3.4.8
lizmap web client 3.4.8
