### ISSUE TITLE
Print scale not displayed correctly

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#191]
Defining several scales results in a list for printing which is slightly different (rounded, e.g. 18000 instead of 18.056). When printing, the correct scale (18.056) is used.
See e.g. http://webgis.provincia.belluno.it/index.php/view/map/?repository=mappe&project=protciv
An annoyance, not a serious issue.

**Comment by pcav** [comment]
@umbiz

**Comment by pcav** [comment]
Same for the scale displayed at bottom right.

**Comment by rldhont** [comment]
Hi @pcav, Do you think we have to display the complete scale instead of the rounded one ?

**Comment by pcav** [comment]
I think having an incorrect scale is confusing and misleading, so yes
