### ISSUE TITLE
Errors while tryring to display related features in popup

### ISSUE THREAD

**Issue by DominikVisca** [3liz/lizmap-web-client#1914]
### Description

I tried to show related features in the popup from their parent element but they simple do not show. I checked the configuration from the docs multiple times (publish WFS etc). In the Error logs I get the following entries upon opening a popup where the related features should be displayed:

`2020-11-11 16:10:44	79.239.89.33	warning	2020-11-11 16:10:44	[2]	file_get_contents(http://127.0.0.1/qgisserver/cgi-bin/qgis_mapserv.fcgi?crs=EPSG%3A25832&amp;exceptions=application%2Fvnd.ogc.se_inimage&amp;feature_count=10&amp;filter=versiegelungsflaechen%3A%22fsk_kz%22+%3D+%27061612009000400008__%27&amp;info_format=text%2Fxml&amp;layers=versiegelungsflaechen&amp;map=%2Fhome%2Fqgis%2Fprojects%2Ftest%2Ftest.qgs&amp;query_layers=versiegelungsflaechen&amp;request=GetFeatureInfo&amp;service=WMS&amp;styles=&amp;version=1.3.0&amp;with_maptip=true&amp;with_geometry=true): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
	/var/www/lizmap-web-client-3.3.0/lizmap/modules/lizmap/classes/lizmapProxy.class.php	236`

`2020-11-11 16:10:44	79.239.89.33	notice	2020-11-11 16:10:44	[8]	Trying to get property 'Layer' of non-object	/var/www/lizmap-web-client-3.3.0/lizmap/modules/lizmap/controllers/service.classic.php	849`

`2020-11-11 16:10:44	79.239.89.33	warning	2020-11-11 16:10:44	[2]	Invalid argument supplied for foreach()	/var/www/lizmap-web-client-3.3.0/lizmap/modules/lizmap/controllers/service.classic.php	849`

What am I doing wrong here?

### Environment

 - Lizmap version: 3.3
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): LUbuntu 20.04
 - Browser (Firefox, Chrome…): 
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Gustry** [comment]
> Lizmap version: 3.3
QGIS Server FULL version: 3.16

Please give us full versions, with the bugfix number.

Edit, I can see your bugfix number in the path : 

> [8] Trying to get property 'Layer' of non-object /var/www/lizmap-web-client-3.3.0/lizmap/modules/lizmap/controllers/service.classic.php 849

Lizmap 3.3.0 is more than one year old. Upgrade to latest bugfix release 3.3.11, from last month ans try again.

PS : You can subscribe to release notifications on GitHub : 
![Screenshot from 2020-11-12 08-31-00](https://user-images.githubusercontent.com/1609292/98909168-be01a900-24c1-11eb-8c20-d9dd574912bb.png)

**Comment by DominikVisca** [comment]
I updated to the Lizmap 3.3.11 and now I got slightly different error messages:

`2020-11-12 10:47:44	xx.xx.xx.xx	warning	2020-11-12 10:47:44	[2]	file_get_contents(http://127.0.0.1/qgisserver/cgi-bin/qgis_mapserv.fcgi?crs=EPSG%3A25832&amp;exceptions=application%2Fvnd.ogc.se_inimage&amp;feature_count=10&amp;filter=versiegelungsflaechen%3A%22fsk_kz%22+%3D+%27061612009000400008__%27&amp;info_format=text%2Fxml&amp;layers=versiegelungsflaechen&amp;map=%2Fhome%2Fqgis%2Fprojects%2Ftest%2Ftest.qgs&amp;query_layers=versiegelungsflaechen&amp;request=GetFeatureInfo&amp;service=WMS&amp;styles=&amp;version=1.3.0&amp;with_maptip=true&amp;with_geometry=true): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
	/var/www/lizmap-web-client-3.3.11/lizmap/modules/lizmap/classes/lizmapProxy.class.php	241`

`2020-11-12 10:47:44	xx.xx.xx.xx	error	An error has been raised when loading GetFeatureInfoHtml:\ncrs=EPSG%3A25832&exceptions=application%2Fvnd.ogc.se_inimage&feature_count=10&filter=versiegelungsflaechen%3A%22fsk_kz%22+%3D+%27061612009000400008__%27&info_format=text%2Fxml&layers=versiegelungsflaechen&map=%2Fhome%2Fqgis%2Fprojects%2Ftest%2Ftest.qgs&query_layers=versiegelungsflaechen&request=GetFeatureInfo&service=WMS&styles=&version=1.3.0&with_maptip=true&with_geometry=true\n\n`

**Comment by DominikVisca** [comment]
It seems that the cause of the problem is the type of data source: Esri GDB (please don't ask me why I use this). I have tried it with SHP now: No error messages and my popup is correct.
