### ISSUE TITLE
Authentification via SAML

### ISSUE THREAD

**Issue by AndreasLoewe** [3liz/lizmap-web-client#1915]
As per documentation, I am aware, it is possiable to conect to Lizmap via LDAP. However, we have the requirement, that we need to use SAML 2.0. 

Issue #696 indicates, that this wasn't possiable. Did that change and if so how to implement it?

Best regards

**Comment by nboisteault** [comment]
@laurentj can you answer?

**Comment by laurentj** [comment]
There is a module for that : https://github.com/jelix/saml-module

The installation is a bit tricky. I hope it's enough for you.
