### ISSUE TITLE
lizmapProxy: Undefined index: crs

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#1917]
### What is the bug?
https://github.com/3liz/lizmap-web-client/blob/release_3_3/lizmap/modules/lizmap/classes/lizmapProxy.class.php#L314 The `crs` is not defined in `GetMap` request parameters

### Environment

 - Lizmap version:  3.3.12-pre
 - QGIS Server FULL version: 3.4
 - QGIS Desktop FULL version: 3.4
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Firefox et al
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?  PostgreSQL

**Comment by Gustry** [comment]
IS this issue still valid @rldhont ?
