### ISSUE TITLE
Cascading form filter

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#1918]
Hello,
how to fit form filters like in this example "https://lizmap.legrandnarbonne.com/index.php/view/map/?repository=public&project=circuit_court"? the choice in a selection, gray the impossibilities in the other filters.

on the same data layer, I know how to filter a zone then a category but where to create the link between them ? parent-child table on the same table whith two variable ?

Thank you

### Environment

 - Lizmap version: 
 - QGIS Server FULL version : qgis server 3.4.15 and lizmap 3.3.5
 - QGIS Desktop FULL version : qgis 3.10 and lizmap 3.2.8
use postgres 9.6
 - OS (Windows, Linux, MacOS, Android…)  : Window 10
 
![filtre_lizmap](https://user-images.githubusercontent.com/46560615/99118953-bbee3600-25f8-11eb-8496-5d08a7790e04.jpg)

**Comment by cocro** [comment]
Hi,
I complete my question with a second question. Why are the filters of my layer generated under qgis and visible in the map not included in the filter by form option? all modalities are now visible. Or this must be invisible to user

**Comment by nboisteault** [comment]
Hi,
It is a paid development to customize filter behavior. You can look at the source code here : https://lizmap.legrandnarbonne.com/index.php/view/media/getMedia?repository=public&project=circuit_court&path=media%2Fjs%2Fcircuit_court%2Fsmartfilter_20190129.js

**Comment by cocro** [comment]
Thank you for this clarification and this code sharing. 
However, should I understand that this functionality cannot be deployed natively with the Lizmap plugin and that it must be inserted on the server side ?
Can we adapt the code to our own uses? or should you contact 3Liz?
Thanks

**Comment by cocro** [comment]
OK I am looking with a developer how to adapt it to our work context and of course would share code

follow-up question : https://cd34.lizmap.com/inclusion_numerique/index.php/view/map/?repository=in1&project=CD_34_Inclusin_Num
I'm assuming the project is also a department-paid js development? Impossible to reproduce natively with the standard plugin ?

very beautiful work which deserves to be known and reproduced. A beautiful business card for Lizmap and its developers

**Comment by nboisteault** [comment]
It is also a paid development. It is also made with Javascript not with plugin, you can find those custom code looking at page source code URLs beginning with`https://cd34.lizmap.com/inclusion_numerique/index.php/view/media/getMedia?repository=in1&project=CD_34_Inclusin_Num&path=media%2Fjs...`

Thank you for your kind words.

**Comment by cocro** [comment]
reproducing your code is going to be a real challenge.
I will not fail to share the result
I close the subject

**Comment by josemvm** [comment]
i would like to have the symbology linked to the legend on a filter for a sign road project
thanks
