### ISSUE TITLE
Can't open my project 

### ISSUE THREAD

**Issue by Miripit** [3liz/lizmap-web-client#1919]
### What is the bug?

Hello, I've just configurate my lizmap web client, but there is a problem: when I try to open my project, the lizmap logo uploading is still viewing, instead of diseappear. 

### Expected behavior

I would see my map without seeing this logo. Could it be a problem with the Server configuration? I followed this guide: https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#installation-on-debian-based-systems

### Screenshots and logs

![Schermata da 2020-11-14 16-08-06](https://user-images.githubusercontent.com/61166594/99150553-b1ce4500-2695-11eb-861f-a29df06d12d0.png)

### Environment

 - Lizmap version: 3.3.11
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10 coruna
 - OS (Windows, Linux, MacOS, Android…): ubuntu 18.04
 - Browser (Firefox, Chrome…): chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? nginx web server, i saved the project in /usr/lib/cgi-bin/project/ ; url wms .../cgi-bin/qgis_mapserv.fcgi
--

**Comment by nboisteault** [comment]
Hi,
Copy you Lizmap logs here please.

**Comment by rldhont** [comment]
@Miripit if you QGIS Server version is 2.18 it cannot read QGIS project made with QGIS Desktop 3.10.

**Comment by Miripit** [comment]
@nboisteault Hi, where can I see the Lizmap Logs? which commands? (sorry I am new, I have to get familiar with this :D )

**Comment by Miripit** [comment]
@rldhont I re-installed all following these instructions for the lizmap web client: https://docs.lizmap.com/current/it/install/linux.html, but this time I have installed Apache2, not Nginx. Then I followed this more simple guide for the qgis server: https://www.paulshapley.com/2016/07/how-to-install-qgis-server-on-ubuntu.html. 
It works also for the 18.04, because now I can see my projects that I did with Qgis 3.10 Desktop, but I still have that problem for the demo projects.. I don't know what kind of  of the QGIS server version I have installed, where can I see it? In terminal I have only put: "sudo install qgis-server" and It has installed without problems, but I don't know if It is the 2.18 version. Thank you in advance for all your helps.

**Comment by nboisteault** [comment]
Copy `sudo apt-cache policy qgis-server` result here.

**Comment by Miripit** [comment]
@nboisteault hello Nicolas, here the results: 

qgis-server:
  Installato: 2.18.17+dfsg-1
  Candidato:  2.18.17+dfsg-1
  Tabella versione:
 *** 2.18.17+dfsg-1 500
        500 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
so it is 2.18 version... how can I do the upload of the version that correctly works with 3.3 lizmap version?

**Comment by Gustry** [comment]
> so it is 2.18 version... how can I do the upload of the version that correctly works with 3.3 lizmap version?

You should uninstall 2.18 first maybe. 2.18 is not maintained since 2 years
Then install qgis-server, it should pick a highest version.
