### ISSUE TITLE
export select features from data table

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1922]
lizmap can´t export selected features from data table, only from selection tool.

data table log:
```
15:24:55 INFO wfsOutputExtension[24170]: WFSFilter.responseComplete
15:24:55 WARNING OGR[24170]: Cannot open /tmp/QGIS_WfsOutputExtension/gml_features_1605799495.211871.gml.()
15:24:55 CRITICAL wfsOutputExtension[24170]: Output layer /tmp/QGIS_WfsOutputExtension/gml_features_1605799495.211871.gml is not valid.
15:24:55 INFO Server[24170]: Request finished in 6 ms
```
selection tool log (OK!):
```
15:28:11 INFO wfsOutputExtension[24170]: WFSFilter.responseComplete
15:28:11 INFO Server[24170]: Request finished in 99 ms
```

 - Lizmap version: 3.3
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10

thanks

**Comment by josemvm** [comment]
this issue is still valid for lizmap 3.4
thanks

**Comment by josemvm** [comment]
please, can anyone confirm this behavior?

**Comment by ygorigor** [comment]
> please, can anyone confirm this behavior?

@josemvm I confirm, I have the same issue

**Comment by tethysgeco** [comment]
Hi, I've fastly tested export selected feature from a table and it's working fine, but we have Lizmap 3.4.1, QGIS Server and Desktop 3.4 and plugin qgis-wfsOutputExtension.

**Comment by Gustry** [comment]
I think this has been fixed, no ?

**Comment by gioman** [comment]
> I think this has been fixed, no ?

@Gustry I would say yes, but last time I checked the list of formats available from the attribute table was not coherent with the list in the layer info's panel, anyway I'm not sure this is by design.

**Comment by Gustry** [comment]
Yes, but about selection, it's fixed
