### ISSUE TITLE
Lizmap print

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#1927]
hello 
can you detail the procedure so that the IGN base maps are printable? the choice of the basemap in Lizmap allows its display but not its printing. What should be added in the project to make this possible?

I added the ign streams from "ign.fr/pratique/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities", I renamed to ign-photo and ign-scan but this returns me service unavailable

### Environment

    Lizmap version:
    QGIS Server FULL version : qgis server 3.4.15 and lizmap 3.3.5
    QGIS Desktop FULL version : qgis 3.10 and lizmap 3.2.8
    use postgres 9.6
    OS (Windows, Linux, MacOS, Android…) : Window 10

Thanks

**Comment by Gustry** [comment]
> can you detail the procedure so that the IGN base maps are printable?

You should have a look to the documentation : https://docs.lizmap.com/next/en/publish/configuration/print.html#allow-printing-of-external-baselayers

> I added the ign streams from "ign.fr/pratique/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities", I renamed to ign-photo and ign-scan but this returns me service unavailable

THis might be unrelated to Lizmap :(
I just tried on a project with `Pratiqu` and  the orthophoto, it works for me just now.
Does your server has internet access ?

**Comment by cocro** [comment]
In my project, in the hidden group, I have mounted the layer since. layer I renamed ign-scan
![lizmap_ign](https://user-images.githubusercontent.com/46560615/99947247-fc2b8200-2d77-11eb-9b58-28de095eff6d.jpg)

service unavailable

In my project, in the hidden group, I have mounted the layer since. layer I renamed ign-scan
Misinterpretation of the documentation?

Thanks
