### ISSUE TITLE
Time manager not working for point layers in lizmap 2.10/2.11/master

### ISSUE THREAD

**Issue by ninsbl** [3liz/lizmap-web-client#193]
The time manager does not seem to work any more. I tried it on my local QGIS Server (QGIS 2.8 and 2.10) with Lizmap Web Client 2.10. Even with a very simple point layer wiuth ~640 points (regardless if from shape or PostGIS, if datetime or integer field was used). Also aggregation had no influence.

My maps do load nicely in Lizmap, but when I activate the Time Manager it does not go beyond “Loading map data”. In other words I am facing the same problem like here: https://lists.osgeo.org/pipermail/qgis-user/2014-August/028981.html

It does not work with the tree demo either...
http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep6&project=trees

I tested with both Mozilla Firefox and Google Chrome. The server running QGIS and Lizmap in my environment should have more than enough resources for that task...

**Comment by ninsbl** [comment]
Polygon layers do work: http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep6&project=population_region_serie_temporelle#

**Comment by ninsbl** [comment]
Probably related to #166 , #167 , and #186

**Comment by gioman** [comment]
There is anyway a demo that works with points

http://demo.lizmap.3liz.com/index.php/view/map/?repository=rep6&project=tractor

I have not tested lately but I remember clearly that I have been able to use this functionality in the past.

**Comment by ninsbl** [comment]
OK, that means the issue is not necessarily related to the geometry type then...
So, what is the difference between the tree demo (not working) and the tractor demo (working)?

**Comment by mdouchin** [comment]
Could you please test with last master ( lizmap-web-client  and lizmap plugin ) and see if the problem stills arise ? 
Could you also check with a STRING column containing date ?

**Comment by ninsbl** [comment]
I updated lizmap-web-client and the plugin to latest master. The problem seems to be still present. I tested again a postgis layer with "timestamp" column, "integer" column (year) and the same data in shape, where "timestamp" becomes "text"... Is a specific date-time format required (e.g. YYYY-MM-DD HH:MM:SS)?

**Comment by rldhont** [comment]
Did you use curl for sending request to QGIS Server ?
Can you test Send request to QGIS Server with php ?

**Comment by mdouchin** [comment]
Please provide a link to download the Shapefile, so that we can test it. Thanks

**Comment by ninsbl** [comment]
Hi,

In the master version php was already used to send requests to QGIS Server. I changed that back to curl, but that had no effect...
I zipped the entire folder: http://www.filedropper.com/liztest
So you get my QGIS project and the Lizmap configuration as well (qgis-mapserv.fcgi is zipped as link)... 
Thanks for looking into this!

**Comment by rldhont** [comment]
The Lizmap Web Client version 2.12 et 3 would correct it 9d04d8f27985f8ac42714c9627d2d3a77705a082

**Comment by ninsbl** [comment]
Yes, now it works fine. Thanks!
