### ISSUE TITLE
Lizmap : Infobulle

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#1930]
Hello
in my project visible here http://lizmap.audiar.org/lm/index.php/view/map/?repository=test&project=base_commerce_consolidee3 (viisteur/visiteur),

question on the placement of tooltips
how to place it as close as possible to the clicked point 

![infobulle](https://user-images.githubusercontent.com/46560615/99945965-dd2bf080-2d75-11eb-8bae-4e2dfafd3b79.jpg)
?

Related question: link between Qgis and Lizmap
under qgis, I had defined my label basically; the fact of declaring it under Lizmap generated in the space dedicated to the property of the layer, a very literary html code which does what I ask of it on the web lizmap side.
on the other hand, on the Qgis side, the native tool "tooltips" no longer responds. The form defined in the form of three tabs appears. Not a big deal in itself because the project is created to be Lizmap switch but I would like to understand the mechanism and interference

Thanks
Corinne

### Environment

QGIS Server FULL version : qgis server 3.4.15 and lizmap 3.3.5
QGIS Desktop FULL version : qgis 3.10 and lizmap 3.2.8
use postgres 9.6
OS (Windows, Linux, MacOS, Android…) : Window 10

**Comment by ygorigor** [comment]
QGIS Lizmap plugin: Map Options - Information popup container - choose `map`

**Comment by cocro** [comment]
I have correctly configured "map". The popup is placed in the map. The tooltip always slides to the top left of the screen. Can this also be placed in the map ?

**Comment by rldhont** [comment]
It is not yet possible to move the tooltips close to the over point.
