### ISSUE TITLE
Pre-generate the tiles for my Lizmap project --> The coord plugin jacl2 is unknown.

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#1932]
### What is the bug?

I am following [this guide](https://github.com/mdouchin/lizmap-documentation/blob/master/source/admin_guide/administration/cache.rst#seeding) to try to pre-cache the tiles for my lizmap project as it takes a lot of time to navigate through it.
I execute `php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier` in windows cmd.
Result:
```
D:\webserver\lizmap\prod\master>php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier
Error during initialization: \n* Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated (D:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 431)
* Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown. (D:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 172)

```

I have set WMTS on all layers in QGIS project:

![image](https://user-images.githubusercontent.com/12136796/99958561-e32bcc80-2d89-11eb-943a-2f5cd59e67c7.png)

and set Server cahing for all layers

![image](https://user-images.githubusercontent.com/12136796/99958652-0ce4f380-2d8a-11eb-8bb8-0d6ce3277ef0.png)

### Steps to reproduce the issue

1. Open CMD in Windows and navigate to Lizmap installation directory. Execute `php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier`

### Environment

 - Lizmap version: 3.3.3
 - QGIS Server FULL version: 3.10.10 LTR
 - QGIS Desktop FULL version: 3.10.10 LTR
 - OS (Windows, Linux, MacOS, Android…): Windows Server 2016 Standard.
 - Lizmap admin information (users, logs…)? Everything default

**Comment by Gustry** [comment]
With an up to date LWC version, is this an issue ?

There are quite a few bugfix on that side since LWC 3.3.3
