### ISSUE TITLE
wrong map scale display with LWC 3.4.0-beta1

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#1938]
With latest beta 1 maps are displayed in a non-rounded scale (as set in lizmap plugin instead).
This occurs even in projects that opened in stable lwc releases (i.e. 3.3.11) are correctly displayed.
So I'd likes to remind developers to solve this issue (similari to closed #1754) in next lwc 3.4.0 stable release, thanks.

 - Lizmap version: 3.4.0 beta 1
 - QGIS Server FULL version: 3.10.2 ltr
 - QGIS Desktop FULL version: 3.10.12 ltr
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 18.04 lts
 - Browser: Firefox and others
 - Lizmap admin information (users, logs…) stored into Sqlite (default).

**Comment by nboisteault** [comment]
It has been answered : 
https://github.com/3liz/lizmap-web-client/issues/1754#issuecomment-703694455

**Comment by ocelot73** [comment]
Do you mean next LWC releases won't have rounded numbers in map scale anymore ?
Clicking on following link you can see two screenshots of LWC mobile interface, the project displayed is exactly the same and inside lizmap plugin I set a 50000 value (among the other scale values at different zooms)

[https://photos.app.goo.gl/AiFS83LenoF9xaQU8](url)

**Comment by nboisteault** [comment]
Yes.

**Comment by Gustry** [comment]
@ocelot73 Side question, did you enable any layers in 3857  ? A checkbox in the  in the `baselayers` tab ?

**Comment by ocelot73** [comment]
Yes @Gustry , I did.  
I set n.3 different base layers inside lizmap plugin (all XYZ tiles in epsg:3857)

**Comment by Gustry** [comment]
> I've noticed that even with lwc 3.3.11 when choosing predefined baselayers in lizmap plugin, map scale display number was not rounded

Yes, because it can't.

Scales are not rounded in EPSG:3857.

Lizmap first tab : 

![Screenshot from 2020-11-28 10-16-08](https://user-images.githubusercontent.com/1609292/100498509-f0b6cd00-3162-11eb-8f28-fb864a48e2cf.png)

Not the best English explanation I agree.

**Comment by nboisteault** [comment]
I reopen this discussion as there are other people asking why scales are not as defined in Lizmap plugin.

As far as I understand it is not possible to have correct scales in a browser as it depends of the screen's DPI (dot per inch) which can't be known in Javascript.
OpenLayers 6 assume a value of 25.4 / 0.28 = 90,714285714. [Source code](https://github.com/openlayers/openlayers/blob/v6.4.3/src/ol/control/ScaleLine.js#L39)
But for example in my case my screen's DPI is 118. (25 inches, 2560x1440)

OpenLayers 2 was saying [here](http://dev.openlayers.org/docs/files/OpenLayers/Layer-js.html#OpenLayers.Layer.scales) that 

> Note that these values only make sense if the display (monitor) resolution of the client is correctly guessed by whomever is configuring the application.  In addition, the units property must also be set.  Use resolutions instead wherever possible.

Also OL 6 has no geodesic property for its scaleline, OL 2 had it.

@rldhont @Gustry @mdouchin : any thoughts/suggestion ?

**Comment by Gustry** [comment]
Which behavior are we talking about ?
When we have 3857 layers, scales are not rounded, even in LWC 3.2 : https://demo.lizmap.com/lizmap_3_2/index.php/view/map/?repository=demo&project=pprn_montpellier
Sorry if we are not talking about this use case.

**Comment by nboisteault** [comment]
@Gustry For 3857 WMTS layers all is normal as we depends on fixed predefined scales/resolutions.
I'm talking about projects with other projections (e.g. EPSG:2154 ) where if you define scales like 100, 1000, ... you won't have those values in Lizmap but something more or less close to those values.
