### ISSUE TITLE
Enhancement: Add Tool to filter layer's data

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#194]
It would be great to have a tool to filter the data of a layer. For example adding some comboboxes at the top in the layer's attribute table. Each combobox would have the different values for each of the attributes so you can select one.

For example, I've got a layer with car accidents geolocated. Users ask me if they can filter the layer by the car accidents happened on a specific year and accidents where the gravity of the injured was severe, for example.

Is this planned to be developed in lizmap 3 or later versions?

**Comment by rldhont** [comment]
Probably already done in version 3.0. @mdouchin what do you think about it ?

**Comment by rldhont** [comment]
It's a short hand to filter data. It will be intersting to have a configuration to select which attribut you want to use to filter.

**Comment by ninsbl** [comment]
Will this be available in the next version? Would be really great!
In fact, it would be an alternative to #422 ...

**Comment by nboisteault** [comment]
@mdouchin does your filter script answer this need ?

**Comment by mdouchin** [comment]
Yep, it's done. See 

* screen cast https://twitter.com/kimaidou/status/1119180340940214275
* first doc: https://github.com/3liz/lizmap-documentation/commit/a91579c410c50152aef64d30cf0577d4dcb38f8f
