### ISSUE TITLE
Too much parameters for lizmapProxy::constructUrl in the code

### ISSUE THREAD

**Issue by alagroy-42** [3liz/lizmap-web-client#1944]
### What is the bug?

On master, in `lizmapProxy.class.php`, the method `constructUrl` defined [here](https://github.com/3liz/lizmap-web-client/blob/726ac646e63d38bd86acf49fbcbf559f1b9181a3/lizmap/modules/lizmap/classes/lizmapProxy.class.php#L58) takes only one parameter but in multiples places in the code ([here](https://github.com/3liz/lizmap-web-client/blob/726ac646e63d38bd86acf49fbcbf559f1b9181a3/lizmap/modules/lizmap/classes/qgisExpressionUtils.class.php#L315) for instance), there is a not needed `array('method' => 'post')` that is passed.

Can we remove it ?
Should it be somewhere else ?
Should the method implement something to handle it ?

**Comment by laurentj** [comment]
@alagroy-42 it seems it appears only into qgisExpressionUtils(). Move this additionnal parameter from `lizmapProxy::constructUrl()` to `lizmapProxy::getRemoteData()`
