### ISSUE TITLE
Error editing

### ISSUE THREAD

**Issue by Csantos11** [3liz/lizmap-web-client#195]
Hello i'm new to this so i don´t know if this is a common error or if i just need to set the parameters of the database in order to be able to modify the attribute of a specific layer.
I can add features with no problems, but this error appears when i try the modify the layer.
First i thought the problem was the geometry, so i changed it from multipolygon to polygon, but nothing happens.
Can anyone help me? 
![image](https://cloud.githubusercontent.com/assets/13749025/9629330/c7188792-5169-11e5-8dc5-29d98df3fe1f.png)

**Comment by nboisteault** [comment]
The message is saying that it doesn't know the SRID of your data. Did you define it?

**Comment by Csantos11** [comment]
I imported the shapefile to a PostGIS database using shp2psql, so no.
But i did set the coordinate system when i added the data to QGIS, but i see that is not enough, and for that matter i will try to add SRID.
 Thank you
