### ISSUE TITLE
External WMS slowdown

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#1951]
A project with a large number of WMS takes a long time to load, even when "Get images directly from WMS Server" is checked for all of them. My interpretation is that a GetCapabilities request is issued at project parsing. It would seem more appropriate to delay the request upon actual layer loading, especially when considering that external WMSs are often used as a background image, therefore usually only one is loaded at a time.

See an example here:
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=ext_wms

**Comment by rldhont** [comment]
Lizmap does not request GetCapabilities of external WMSs. It is trust the QGIS project file.

The slowdown is in QGIS Server. At the WMS Layer intialisation, QGIS requests the GetCapabilities. You can check the QGIS3.ini file that can contain some WMS cache config.

**Comment by pcav** [comment]
This also when "Get images directly from WMS Server" is active?

**Comment by rldhont** [comment]
@pcav I invite you to test #4380
