### ISSUE TITLE
Display non-spatial tables data as child table ?

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#1953]
Inside QGIS I've set a relation 1-to-many between a a point layer and a non-spatial child table, linked by a common field.
Inside QGIS everything is OK and if I click on a point, the child table appears with multiple records related. 
With LWC (every version, stable or master) this doesn't happen.
The only way I've been able to show child table with LWC is by adding a geometry column (i.e. by creating new points) in the table, but that would mean duplicating geometries...
Isn't there any way to show as child table a non-spatial layer (for example: a postgres table) as child table related to parent layer with LWC ?

 - Lizmap version: 3.3.11 (or 3.4.0-x)
 - QGIS Server FULL version: 3.10.2
 - QGIS Desktop FULL version: 3.10.12
 - OS (Windows, Linux, MacOS, Android…):  Ubuntu 18.04.5 LTS
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

**Comment by ygorigor** [comment]
@ocelot73 did you enable popup for child layer? Also check if parent layer has enabled popup and `Display related children...`

**Comment by ocelot73** [comment]
Yes, I did enable popup in both parent and child layer and set the "Display related children.." option.
I've forgotten to say that even the point layer even the child table are not "real" tables,
They are actually postgres views but it should work anyway, doesn't it ?

**Comment by rldhont** [comment]
Hi @ocelot73 it has to work.

Can you provide a project ?
Can you check with your browser devtools, that the GetFeatureInfo request to get children data has been send ?

**Comment by ygorigor** [comment]
> Yes, I did enable popup in both parent and child layer and set the "Display related children.." option.
> I've forgotten to say that even the point layer even the child table are not "real" tables,
> They are actually postgres views but it should work anyway, doesn't it ?

@ocelot73 I have a materialized view as parent layer, a non spatial foreign table as a child layer, and is working

**Comment by ocelot73** [comment]
Sorry @rldhont but I'm not very much experienced with devtools.
I've looked in Firefox devtools web console, but the name of child table layer doesn't appear in any GetFeatureInfo request.
(Sorry but I can't provide a project since it's in a production environment and it would be linked directly with PG database)

**Comment by ygorigor** [comment]
> @ygorigor are you able in edit features mode to add new records to the non-spatial table with LWC ?
> 
- > @ocelot73 my foreign tables are in csv format, and they are read only. Also foreign tables have no constraints so they can not be editable in LWC

**Comment by ocelot73** [comment]
It seems the problem lies with using the PG **view** as child table. In that case LWC doesn't show child layer but only father layer.
I've tried using a PG materialized view (with unique index) or a PG table and it works !
(all child layers used did not  contain geometries, just data)
Good to know
If nobody else has to add his own experience, I think issue can be closed
