### ISSUE TITLE
Automatic refresh layer

### ISSUE THREAD

**Issue by Marcuzzo77** [3liz/lizmap-web-client#1955]
Hi,

is it possible to insert an automatic update timeout of the layers with a temporal frequency?  for example every 10sec, so that when the web page is open, they update themselves without refreshing the page?
Tks

**Comment by ygorigor** [comment]
https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/misc/refresh_layers_every_n_seconds

**Comment by Gustry** [comment]
Thanks @ygorigor for the answer.

Let's close this ticket, I think the Javascript is enough for now.

Similar, there is also the atlas, with auto-play.

**Comment by mdouchin** [comment]
I think in a undefined future, it could be great to read the QGIS option for layers, and use it automatically if set ? We should add it in the roadmap, in "nice to have" ?

**Comment by pcav** [comment]
Fully agreed.

**Comment by Marcuzzo77** [comment]
hi, I tested this script with version 3.4.0rc1 but unfortunately it does not automatically update the layers.  have any of you tried this version?
