### ISSUE TITLE
Gears button should be hidden if there isn't a custom label

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#1956]
### What is the bug?

If there isn't a custom label to setup, clicking on the gears displays a small gray rectangle.

![custom_atlas](https://user-images.githubusercontent.com/1609292/100845342-5c5bab80-347d-11eb-8326-98967fee99c5.gif)

On the GIF, look on the left side of the small printer icon when I click

If there isn't a setting, we shouldn't display the gear and only be able to get the PDF

### Steps to reproduce the issue

1. Add an atlas without any custom label

### Environment

 - Lizmap version:  Master
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 
 - Browser (Firefox, Chrome…): Firefox

**Comment by nboisteault** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/commit/31353b62b044eadcbe0b33a9b8ebf27f2650d3f7
thanks @Gustry

**Comment by Gustry** [comment]
Thanks @nboisteault !
