### ISSUE TITLE
auth_url_return param not working if already logged in

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#1957]
### What is the bug?

When using the login url + auth_url_return param when you are already logged in (second time you hit a link, for example) you are directed to this web, instead of directing to destination URL in auth_url_return param:

![image](https://user-images.githubusercontent.com/12136796/100862070-fbd76900-3492-11eb-87e2-a242276b5397.png)

### Steps to reproduce the issue

1. Go to a lizmap login url with auth_url_return param.
Example:
https://SERVER/lizmap/www/admin.php/auth/login/?auth_url_return=%2Flizmap%2Fwww%2Findex.php%2Fview%2Fmap%2F%3Frepository%3DREPOSITORY%26project%3DPROJECT

2. Insert user and pass in the form
3. You are redirected to URL in auth_url_return param properly.
4. If you open a new tab and navigate again to https://SERVER/lizmap/www/admin.php/auth/login/?auth_url_return=%2Flizmap%2Fwww%2Findex.php%2Fview%2Fmap%2F%3Frepository%3DREPOSITORY%26project%3DPROJECT
You should go to the URL in auth_url_return param directly as you are already logged in, instead you are redirected to this **_USER, You are connected._** website where you have no way to go to the destination URL.

### Environment

- Lizmap version: 3.3.3
- QGIS Server FULL version: 3.10.10 LTR
- QGIS Desktop FULL version: 3.10.10 LTR
- OS (Windows, Linux, MacOS, Android…): Windows Server 2016 Standard.
- Lizmap admin information (users, logs…)? Everything default

**Comment by laurentj** [comment]
Thanks for your report

**Comment by jaitor1** [comment]
Hi,
I tried the changes and it is not working as expected.

Now I am not redirected to "USER, You are connected." site but I am redirected to the Admin Desktop:

![image](https://user-images.githubusercontent.com/12136796/101770969-877f7400-3ae9-11eb-9e04-e4cd34b68cb3.png)


I should be redirected to the auth_url_return URL. Maybe I am doing something wrong or I have a misconfiguration somewhere. My URL example:

http://MYSERVER/lizmap/www/admin.php/auth/login?auth_url_return=%2Flizmap%2Fwww%2Findex.php%2Fview%2Fmap%2F%3Frepository%3Druidos%26project%3Dmapa_ruido

**Comment by nboisteault** [comment]
@laurentj do you confirm behavior reported by @jaitor1 is a bug?
