### ISSUE TITLE
Is it possible to open a map passing the active layers by URL parameter?

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#196]
I mean, 

http://example.com/lizmap/lizmap-web-client-master/lizmap/www/index.php/view/map/?repository=turism&project=turism&activatedlayers=hotels_restaurants_bars_pois 

Please notice I added at the end: &activatedlayers=hotels_restaurants_bars_pois

I don't know if a similar functionality is working right now, I can't find anything in the doc...

The idea is to call the same map from different places with different layers activated each time. If I call the map from the Hotels section in the townhall's website, I would load the map only with the hotels layers activated, if i load the map from the restaurants and bars section only the Restaurants and Bars layers would be activated, etc..

Is this possible?

**Comment by nboisteault** [comment]
Did you try permalink?

![image](https://cloud.githubusercontent.com/assets/2145040/9731233/032be574-561c-11e5-8c4b-82d99346d9f3.png)

**Comment by jaitor1** [comment]
@nboisteault I din't try that option. It's perfect, thanks!!
