### ISSUE TITLE
Upgrading 3_3 to 3_4 Issue.

### ISSUE THREAD

**Issue by AJM-WebDev** [3liz/lizmap-web-client#1965]
### What is the bug?

php bug when attempting to update lizmap from 3_3 to 3_4 (following the documentation guides in Github for updating.)

E:\webserver\lizmap\preprod\master\lizmap\install>php installer.php
PHP Warning:  require(E:\webserver\lizmap\preprod\master\lizmap/vendor/autoload.php): failed to open stream: No such file or directory in E:\webserver\lizmap\preprod\master\lizmap\application.init.php on line 12
PHP Fatal error:  require(): Failed opening required 'E:\webserver\lizmap\preprod\master\lizmap/vendor/autoload.php' (include_path='.;C:\php\pear') in E:\webserver\lizmap\preprod\master\lizmap\application.init.php on line 12

I get the same issue if I attempt a fresh install of Lizmap as well.

I read on another issue similar to this one that to install 3_4 you have to use the files found here: https://packages.3liz.org/pub/lizmap/release/3.4/ however there is no documentation setup to explain exactly how I go about doing this.

### Steps to reproduce the issue

1. Download zip file from Github.
2. Copy lib directory into my existing 3_3 installation.
3. Copy lizmap directory into my existing 3_3 installation.
4. Run "php installer.php".

### Expected behavior

Having previously used this method to upgrade 3_2 to 3_3 I expected it to work as the documentation described.

### Environment

 - Lizmap version: 3_4
 - QGIS Server FULL version: 3.14
 - QGIS Desktop FULL version: 3.14
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

**Comment by Gustry** [comment]
> I read on another issue similar to this one that to install 3_4 you have to use the files found here: https://packages.3liz.org/pub/lizmap/release/3.4/ however there is no documentation setup to explain exactly how I go about doing this.

Yes, you must download ZIP files which are ready to be used, either from GitHub releases https://github.com/3liz/lizmap-web-client/releases or from https://packages.3liz.org/pub/lizmap/release/3.4/.
Do not use anymore the ZIP generated automatically from GitHub.

Have a look to https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#get-the-source

> Having previously used this method to upgrade 3_2 to 3_3 I expected it to work as the documentation described.

Which documentation did you read ?
