### ISSUE TITLE
Enhancement: add options to hide "Projects" and "Information" buttons in the map's Tools

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#197]
![image](https://cloud.githubusercontent.com/assets/12136796/9730629/06a49e7a-5618-11e5-9f56-45e3cb1bffe3.png)

**Comment by rldhont** [comment]
@jaitor1 thank for this request. I have open an enhancement in lizmap-plugin too https://github.com/3liz/lizmap-plugin/issues/54

**Comment by rldhont** [comment]
To do so, before we enhance web client and plugin, you can use a JavaScript in the media folder, like the file shown in fb0ba36 , see doc https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#adding-your-own-javascript

**Comment by igeofr** [comment]
It is possible by using this code :
```
lizMap.events.on({
     'uicreated':function(evt){
        $('.nav-list .metadata').css({
           'display':'none'
        });
        }
   });
```
