### ISSUE TITLE
Function Zoom to Layer doesn't work with PSQL

### ISSUE THREAD

**Issue by TecnostudiAmbiente** [3liz/lizmap-web-client#1971]
### What is the bug?

From the attributes table in Lizmap if we click on the icon with the lens (zoom) it doesn't work.
We are using PSQL for the data and if we move that data outside the DB (shape-files) it works perfectly.
We are using EPSG 4326 and the data inside the DB has an Index and a primary key.
For example, on the same server with the Montpellier demo, this functionality works as expected.

### Steps to reproduce the issue

1. Click on Data icon on the left menu
2. Click on the Details button that will show the table with the data
3. Click on the lens icon in one of the elements
4. You can see the error from the logs or using Inspect from your browser

### Expected behaviour

When clicked on the lense it should zoom on that specific layer.

### Screenshots and logs

Lens visible in the popup menu
![1bc54674-f585-4ec5-bf83-c4b59ceb79fe](https://user-images.githubusercontent.com/22416161/101258437-d1034400-3722-11eb-8352-a6e8eedfe612.jpg)

Lens visible in the attributes table
![a94a440f-135b-4fb7-801d-6c3c3386a9cc](https://user-images.githubusercontent.com/22416161/101258439-d19bda80-3722-11eb-9daf-071c97f6d12d.jpg)

Error logs from Lizmap
![c7c8478b-89b9-4a62-b770-283b5ce222bf](https://user-images.githubusercontent.com/22416161/101258440-d2347100-3722-11eb-8fb5-884e4b546c24.jpg)

Error visible when clicking on the lens using inspect in the browser
![327f34b7-d42e-4eb6-84dc-d097281d20d6](https://user-images.githubusercontent.com/22416161/101258444-d2cd0780-3722-11eb-8a13-e6b9361dd775.jpg)

Function that is causing the error (apparently passing a NULL value when clicking)
![a62892fe-fc1d-4493-a29b-dc1fd43ba3a8](https://user-images.githubusercontent.com/22416161/101258441-d2cd0780-3722-11eb-9d06-7f8edfac6952.jpg)

### Environment

 - Lizmap version: 3.3.11
 - QGIS Server FULL version: 3.4.11
 - QGIS Desktop FULL version: 3.16.1
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 18.04
 - Browser (Firefox, Chrome…): Firefox, Chrome, Safari
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PostgreSQL 11.9 with PostGIS 2.4.6

**Comment by rldhont** [comment]
Firstly, you cannot use QGIS Server 3.4 and QGIS Project made with QGIS Desktop 3.16. You cannot be sure that QGIS Server 3.4 can read correctly the project. We have found some issue with SVG path.

Other point, Lizmap 3.3 is not able to read PG datasources provided by QGIS Desktop 3.16.

**Comment by nboisteault** [comment]
Please use QGIS **3.10** for Desktop and Server.

**Comment by TecnostudiAmbiente** [comment]
Thanks a lot for your reply, we re-deployed the server with QGIS-Server 3.10.12 and used QGIS-Desktop 3.10 and it worked like a charm!
You can close this ticket.
Have a nice day :)

**Comment by nboisteault** [comment]
@mdouchin can we close this issue?

**Comment by mdouchin** [comment]
not yet, I would like to add a quick fix for this case in `qgisVectorLayer.class.php`

**Comment by TecnostudiAmbiente** [comment]
Hi, @mdouchin, do you have any news about this problem?
I see this ticket still open, and we really need to fix this.

Should we upgrade to another version, or do we risk having the same issue?
Thanks a lot!
