### ISSUE TITLE
Problem with edition tool on a non geometric layer

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-web-client#1973]
Hi ! 
I have issues with the edition tool in Lizmap with non geometric layer.
### What is the bug?

The edition tool loop for days when trying to add a new feature in a layer without geometry. No from shows up.

I have a layer without geometry and i wish to edit it with the lizmap web client. When i click on the 'add' button in the edition tool, it charge for days and never show the form.
If i 

### Steps to reproduce the issue

1. Add a layer without geometry
2. Publish WFS
3. Allow edition to layer check (Create, Delete, Modify and Allow no geometry)
4. Allow to show attribute table of the layer 
5. Go to Lizmap Web Client
6. Edit -> Select the layer -> Add
7. It only charges, no form is display

### Expected behavior
Get a form that allow to add a layer. 

I tried to add a geometry column to my layer and check the edition option 'allow no geometry' but it doesn't work verry well.
With the geometry column i can have access to the form, but i can only create feature if i add a geometry (despites the fact that i checked for 'allow no geometry'.
If i try to edit an entity from the layer attribute table, it charge again and don't show any forms.

### Environment

 - Lizmap version:  3.3.12-pre
 - QGIS Server FULL version:  ?
 - QGIS Desktop FULL version: 3.16.1 -Hannover
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Brave
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? 

I'm not the one that installed id, so i don't really know all the answer..

Thanks in advance !

**Comment by Ailurupoda** [comment]
It seems that it is caused by the QGIS Desktop version.
I switched to a 3.8 version and it works well !

**Comment by Gustry** [comment]
We didn't get an idea.

> I switched to a 3.8 version and it works well !

Why not a LTR version ?

3.8 is not supported, 3.10 is the oldest LTR.

3.16 is going to be the next LTR next month, so it would be better to find the issue.

> QGIS Server FULL version: ?

You should check this as well and have the same version.

**Comment by Ailurupoda** [comment]
I think the QGIS Server is on 3.14, the best would've been to use QGIS 3.14 as well. 
But i had issues installing it on my desktop (Linux Package issues), the LTR had also some troubles installing Lizmap Plugin.
So i took the only one i could to make Lizmap work perfectly :)

**Comment by Gustry** [comment]
We recommend QGIS 3.10, because LTR version.
But QGIS 3.16 is LTR soon, so some testing is also good !

> the LTR had also some troubles installing Lizmap Plugin.

Of course, we appreciate feedback if you have issues wiht Lizmap plugin.

But please keep the same version for both Desktop and Server.
