### ISSUE TITLE
Delay on layers resizing with zooming in/out on map

### ISSUE THREAD

**Issue by TecnostudiAmbiente** [3liz/lizmap-web-client#1976]
### What is the Problem?

When we zoom inside a map (including test maps like Montepellier) we can see a delay in resizing the layers, normally is around less then a second but depending on the complexity of the layer it could be higher, around also 3 to 5 seconds.
Is this a bug or there is something we could do to improve this on the server side?

NOTE: we notice the same issue on local installation and on our network we have 10GB uplink, we also performed network checks and it's everything working properly, so we exclude those kind of problems.

### Steps to reproduce the issue

1. Open every map
2. Zoom in or Zoom out
3. See effect on the screenshot attached below

### Expected behavior

It will be good to have a minimum delay when zooming into the map and having the layers resizing quickly in less then few milliseconds.

### Screenshots and logs

As you can see from the image, when zooming, the underlying map is immediately resized, meanwhile to resize the layers takes some seconds:

<img width="1040" alt="Schermata 2020-12-08 alle 10 47 16" src="https://user-images.githubusercontent.com/22416161/101472947-87487280-3949-11eb-987b-e1924616cba5.png">

### Environment

 - Lizmap version: 3.3.12
 - QGIS Server FULL version: 3.10.12
 - QGIS Desktop FULL version: 3.10.12-A Coruna
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04
 - Browser (Firefox, Chrome…): Chrome, Firefox, Safari.
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PSQL 11.9 PostGIS 2.4.6

**Comment by ygorigor** [comment]
@TecnostudiAmbiente this delay is related to QGIS server

**Comment by TecnostudiAmbiente** [comment]
I see... it’s there a way to tweak QGIS server and increase the performance at least to reduce a little bit this delay? 

Thanks

**Comment by gioman** [comment]
> I see... it’s there a way to tweak QGIS server and increase the performance at least to reduce a little bit this delay?

@TecnostudiAmbiente have you enabled multi-threading in QGIS Server?

**Comment by TecnostudiAmbiente** [comment]
Yes multithreading is already enabled.

**Comment by ygorigor** [comment]
@TecnostudiAmbiente you can try QGIS server from 3liz https://github.com/3liz/py-qgis-server. For me is fast enough

**Comment by TecnostudiAmbiente** [comment]
Thanks @ygorigor  for the hint, we didn't try it but we'll give it a shot : )

**Comment by Gustry** [comment]
@TecnostudiAmbiente this is mainly an issue with QGIS Server indeed, not really related to Lizmap.

The answer is not easy as they are many things impacting QGIS Server.
There is this big page : https://docs.lizmap.com/current/en/publish/configuration/optimization.html

Also, think about : 
* "trust layer metadata" for your layers
* simplify geometry on the server side for postgis layers (settings in QGIS Desktop)
* in QGIS 3.16, there new environment variable for qgis-server to speed up project loading https://docs.qgis.org/3.16/en/docs/server_manual/config.html#environment-variables
* project cache management
* check your QGIS Server install (do not use fcgiwrap for instance)
* there are always some small things here and there
