### ISSUE TITLE
Ajout de la couche cadastre IGN

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#198]
Il serait intéressant d'avoir la couche du cadastre IGN pour les français. Merci.

**Comment by rldhont** [comment]
Bonjour, pouvez-vous préciser le nom de la couche dans le web service de l'IGN ?

Merci

**Comment by nboisteault** [comment]
Bonjour,

Il s'agit de la couche CADASTRALPARCELS.PARCELS

Merci.
