### ISSUE TITLE
user property comme valeur par défaut ?

### ISSUE THREAD

**Issue by lionelbargeot** [3liz/lizmap-web-client#199]
Bonjour

pour combiner le filtrage des données à l'affichage et le module d'édition, serait-il possible d'utiliser pour certains attributs une valeur par défaut correspondant au group-id de l'utilisateur ?
Cela permettrait d'étendre les filtres lors de l'édition sans avoir à demander à l'utilisateur de rentrer lui même son group-id dans un champ.
Merci

**Comment by rldhont** [comment]
Bonjour,

Je crois avoir fais le code pour cela pour la version 3.0 de Lizmap.

Pouvez-vous tester ? ensuivant les indications d'installation du fichier install.md

**Comment by lionelbargeot** [comment]
nous avons finalement abandonné ce besoin. Du coup je ne l'ai pas testé.
