### ISSUE TITLE
Set rights for Nginx: No such file or directory

### ISSUE THREAD

**Issue by Heryx** [3liz/lizmap-web-client#1990]
Hi everyone, 
I am trying to install lizmap on my server. 
When I try to set rights to Nginx with 
```
cd /var/www/lizmap-web-client-$VERSION/
lizmap/install/set_rights.sh www-data www-data
```
it gives me this message: 

```
set_rights.sh: command not found

**Forbidden**
You don't have permission to access this resource.
_Apache/2.4.29 (Ubuntu) Server at 95.217.184.190 Port 80_
```
And if I try to leave _http:/myhost/lizmap_ it returns me this:

 - Lizmap version: **3.3.11**
 - QGIS Server FULL version: **3.16**
 - QGIS Desktop FULL version: **3.16**
 - OS (Windows, Linux, MacOS, Android…): **Server Ubuntu 18.04**
 - Browser (Firefox, Chrome…): **Chrome**

**Comment by Gustry** [comment]
The script is still there `lizmap/install/set_rights.sh`.
I'm not sure what is wrong in your zip. I suggest you to try again and check paths.

 > Lizmap version: **3.3.11**

There is a latest bugfix available.

**Comment by Heryx** [comment]
Thanks, I'll do it.

which versions would you recommend me to install?

**Comment by Heryx** [comment]
I think the problem is here:
the lizmap folder cannot be opened

![image](https://user-images.githubusercontent.com/11267377/102272906-cbc3a780-3f21-11eb-9024-5fb8a02facd8.png)

**Comment by Gustry** [comment]
> which versions would you recommend me to install?

One of the latest version available in your Lizmap QGIS plugin, on the left side. (upgrade your QGIS plugin in case you don't see it).

Keep in mind that LWC 3.4 should be released this week I think (I hope)

And do some `ls -l` to show us what it is.

**Comment by Heryx** [comment]
Thanks for your suggestions.
I followed the guidelines for installing Lizmap and QGIS Server on my own server (Hetzner). I own a small server with Ubuntu 18.04. This is the result with `ls -l`
![image](https://user-images.githubusercontent.com/11267377/102335031-abcacd00-3f8f-11eb-955e-5f356627369a.png)
