### ISSUE TITLE
Cache does not work after authorization. Auto-generated cache is not used. 3.4

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#1993]
### What is the bug?

I dont understand anything. I have 3.3.10 which works well in this regard.
I installed 3.4.0 and generate tiles by script (`php lizmap/scripts/script.php lizmap~wmts:seeding [-v] [-f] repository project layer TileMatrixSet TileMatrixMin TileMatrixMax`) into sqlite as before. But lizmap 3.4.0 not use this cache and it regenerate cache. If I open 3.3.10 version this use same cache generated by script. 
And in 3.4.0 I connect by guest and generate cache tiles I can reuse it next times. But if log in, for example, as an admin tiles start to regenerate.

### Environment

 - Lizmap version:  3.4.0
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…):  Linux
 - Browser (Firefox, Chrome…): Firefox, Chrome

**Comment by ygorigor** [comment]
@johnzet39 it is not a bug. Each user has it's key for storing cache

**Comment by johnzet39** [comment]
@ygorigor , but how can I generate or organize a shared cache for everyone?

**Comment by johnzet39** [comment]
I have changed my initial message.
Please help me solve my problems with version 3.4.0.
1. How can I get the script generated cache to be used (3.3.10 uses the generated cache correctly)?
2. How can I use a common cache for all users, and not generate for each user separately?

**Comment by Gustry** [comment]
> Each user has it's key for storing cache

@ygorigor Are you sure of this ?
I don't see it mention in https://docs.lizmap.com/current/en/admin/cache.html
Only the admin can remove the cache from the Lizmap legend panel.

Question on GIS.SE https://gis.stackexchange.com/questions/383591/cache-does-not-work-after-authorization-auto-generated-cache-is-not-used-in-liz

**Comment by ygorigor** [comment]
> > Each user has it's key for storing cache
> 
> @ygorigor Are you sure of this ?
> I don't see it mention in https://docs.lizmap.com/current/en/admin/cache.html
> Only the admin can remove the cache from the Lizmap legend panel.
> 
> Question on GIS.SE https://gis.stackexchange.com/questions/383591/cache-does-not-work-after-authorization-auto-generated-cache-is-not-used-in-liz

At least in redis is working in this way.
