### ISSUE TITLE
Attribute edition sets to null unedited fields

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#1994]
### What is the bug?

Attribute edition sets to null unedited fields (PostGIS layer)

### Steps to reproduce the issue

- Have a PostGIS layer with various fields filled with data
- Set a Qgis form to edit the value of only on field of this layer
- Put the layer in edition mode on Lizmap
- Edit a feature

--> The field value is modified as expected but all other columns are set to NULL

### Expected behavior

Change the value of the edited fields only. Other field not apparent in the forms must be protected.

### Environment

Tactis instance hosted by 3Liz. 

 - Lizmap version: 3.3.12
 - QGIS Server FULL version: ?
 - QGIS Desktop FULL version: 3.10.12-A Coruña
 - OS (Windows, Linux, MacOS, Android…): Windows

**Comment by rldhont** [comment]
* Is it a drag&drop form ?
* Is the other field disabled ?

**Comment by nboisteault** [comment]
@vlebert Please give us a minimal QGIS + Lizmap project with a sql dump of non private data.

**Comment by vlebert** [comment]
It is a drag and drop form

other fields were not in the form, but not specifically disabled from any other way (WFS activated for example).

![image](https://user-images.githubusercontent.com/49779177/102353410-47b50280-3fa9-11eb-8d82-904e6d53ece5.png)


You can try this form and dataset, though original data was on PG. I can't share the original project as it contains the password.
 
[test.zip](https://github.com/3liz/lizmap-web-client/files/5702872/test.zip)

**Comment by rldhont** [comment]
We have found why this issue and we will provide a fix.

**Comment by gioman** [comment]
Is this a re-occurrence of https://github.com/3liz/lizmap-web-client/issues/1647 ?

**Comment by nboisteault** [comment]
@gioman yes it is.
