### ISSUE TITLE
relation_aggregate() function in popup

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#1997]
Hi,

I try to use relation_aggregate() function in layer proprieties > tooltip pannel. In QGIS, informations are displayed correctly. But in Lizmap, the expression used in tooltip pannel is displayed. Any idea about where the problem might come from? Has anyone ever used this function in a popup?

![image](https://user-images.githubusercontent.com/46535425/102410711-355eb700-3ff1-11eb-9bd7-010a8c667463.png)
![image](https://user-images.githubusercontent.com/46535425/102410786-57583980-3ff1-11eb-81a9-fe729097e81c.png)

- QGIS's version : 3.10.10-A Coruña
- Lizmap's version : 3.3.6
- parent layer :
> CREATE TABLE cadastre.couche_parent
> (
>     id_parent integer NOT NULL DEFAULT nextval('cadastre.couche_parent_id_parent_seq'::regclass),
>     nom_parent character varying COLLATE pg_catalog."default",
>     geom geometry(MultiPolygon,2154),
>     CONSTRAINT couche_parent_pkey PRIMARY KEY (id_parent)
> )

- child layer :
> CREATE TABLE cadastre.couche_enfant
> (
>     id_enfant integer NOT NULL DEFAULT nextval('cadastre.couche_enfant_id_enfant_seq'::regclass),
>     nom_enfant character varying COLLATE pg_catalog."default",
>     "id_parent#" integer NOT NULL,
>     CONSTRAINT couche_enfant_pkey PRIMARY KEY (id_enfant),
>     CONSTRAINT id_parent_fkey FOREIGN KEY ("id_parent#")
>         REFERENCES cadastre.couche_parent (id_parent) MATCH SIMPLE
>         ON UPDATE NO ACTION
>         ON DELETE CASCADE
> )

-tooltip pannel's expression : 
> [% "nom_parent" %]
> 
> [% relation_aggregate('id_relation','concatenate',"nom_enfant") %]

**Comment by aeduard** [comment]
I can confirm, I'm trying to achieve something similar, but relation_aggregation do not work in lizmap web client, although it displays OK in qgis.

Environment: lizmap 3.3.10 with qgis server 3.10, also qgis desktop 3.10. Data is stored in postgresql.

**Comment by aeduard** [comment]
I've updated my lizmap to 3.4.0, error remains.

**Comment by nboisteault** [comment]
It is a QGIS Server limitation. Please open an issue on their Github.

**Comment by Mavialle** [comment]
On [this](https://github.com/qgis/QGIS-Enhancement-Proposals) Github ?

**Comment by nboisteault** [comment]
This one https://github.com/qgis/QGIS/issues.
Issue with `relation_aggregate()` is of the same kind that https://github.com/qgis/QGIS/issues/30719.
It would be perfect if you can attach a QGIS project illustrating the problem.

**Comment by Gustry** [comment]
Is there a manual test on a latest version of QGIS ?
 3.10 is not supported anymore.
