### ISSUE TITLE
Impression non fonctionnelle

### ISSUE THREAD

**Issue by eprouteau** [3liz/lizmap-web-client#2002]
### Description
Bonjour, 

En plein test de lizmap :) pour mon association, l'impression rencontre des problèmes. La génération du document se fait bien mais ne pèse que 1ko et est invalide à l'ouverture.

A quoi cela peut être dû ? Configuration de qgis server (XVFB doit être actif ?), autres piste ?

Je bloque sur la solution à apporter.

http://146.59.231.55/lizmap/

Bonne journée

Emeric

### Environment

 - Lizmap version: 
 - QGIS Server FULL version: 3.16.1 
 - QGIS Desktop FULL version: 3.14.16
 - OS (Windows, Linux, MacOS, Android…): Server Debian 9 / Client Windows 10
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Default

**Comment by rmarzocchi84** [comment]
IMHO XVFB not active can be a problem even if your pdf is generated.

Moreover I suggest to use QGIS Server LTR (actually 3.10.X)

Which version of LWC are you using?

**Comment by eprouteau** [comment]
I m using LWC 3.4.0 RC2 but i can use LWC 3.3.12

Ok! I'm going to re-install my server with a qgis server 3.10. With this version of qgis server, which qgis desktop version is better to use ?
