### ISSUE TITLE
Google Maps Satellite base layer appears 45º tilted when passing certain zoom (18 I think)

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#201]
Hi,

Since 30 minutes ago, more or less, the Google Maps Satellite base layer appears 45º tilted when passing certain zoom (I think is zoom 18). This makes all my layers not fit over the base layer. Example of my Buildings layer in zoom 17:

![image](https://cloud.githubusercontent.com/assets/12136796/9958214/004b5332-5e08-11e5-9aea-3a127daa422b.png)

Example of my Buildings layer in zoom 19:

![image](https://cloud.githubusercontent.com/assets/12136796/9958220/0c3c9c82-5e08-11e5-9507-85091d935962.png)

The new Satellite base layer gives the map great 3D view but is making all my GIS maps useless.. ( I have maps only with satellite base layer..) 

I suppose they have activated this possibility in Google Maps API today...and should be a way to activate, deactivate it...

I don't know if making a reprojection of the spatial layers would work too...

I can see that in Google Maps default interface they have added a new Button to tilt or untilt the view:

![image](https://cloud.githubusercontent.com/assets/12136796/9958539/54d6bd8a-5e0b-11e5-855c-e9b18f4bc53c.png)

**Comment by jaitor1** [comment]
Please see http://gis.stackexchange.com/questions/89008/openlayers-behaves-problematic-after-certain-zoom-level-in-google-maps-satellite for a possible solution.

**Comment by jaitor1** [comment]
It is supposed to be fixed in Openlayers version after March 2014, why is the problem showing right now? One week ago it wasn't showing..
How could I update openlayers to avoid this problem?
I also could add this line of code (myGoogleLayer.mapObject.setTilt(0);)  after the layer is added to the map, but I don't know much about programming and I don't know where to add it...
Could someone help me to fix this problem?

**Comment by nboisteault** [comment]
It has been fixed in master not in the last release 2.13.1.
Can you give us a link to your lizmap web interface?

**Comment by jaitor1** [comment]
Thanks @nboisteault 

You can check our portals map here: 
http://eudala2.getxo.eus/lizmap/lizmap-211/lizmap/www/index.php/view/map/?repository=portales&project=getxo_portales_estadistica

**Comment by nboisteault** [comment]
Above you can find the commit that fixes this issue.
You can copy the modified file here https://github.com/nboisteault/lizmap-web-client/blob/patch_google45/lizmap/www/OpenLayers-2.13/OpenLayers.js and replace your lizmap/www/OpenLayers-2.13/OpenLayers.js with it.

**Comment by rldhont** [comment]
The PR #202 has been merged.

Thanks.

I'll tagged a new 2.11 release
