### ISSUE TITLE
Warning, mkdir File exists from jCmdlinCoordinator or jApp:loadConfig

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2011]
### What is the bug?
I have found a warning in log file about `mkdir(): File exists`

### Steps to reproduce the issue
I don't know, if it is after a `clean_vartmp` or `restart php`

### Screenshots and logs
```
warning	2021-01-05 14:22:26	127.0.0.1	[2]	mkdir(): File exists	/DATAS/lizmap-web-client/lib/jelix/utils/jFile.class.php	97
	/DATAS/lizmap-web-client/lizmap/scripts/script.php
array ( )

	0	mkdir()	/DATAS/lizmap-web-client/lib/jelix/utils/jFile.class.php : 97
	1	jFile::createDir()	/DATAS/lizmap-web-client/lib/jelix/core/jConfigCompiler.class.php : 104
	2	jConfigCompiler::readAndCache()	/DATAS/lizmap-web-client/lib/jelix/core/jConfig.class.php : 84
	3	jConfig::load()	/DATAS/lizmap-web-client/lib/jelix/core/jApp.class.php : 145
	4	jApp::loadConfig()	/DATAS/lizmap-web-client/lib/jelix/core/jCoordinator.class.php : 85
	5	jCoordinator->__construct()	/DATAS/lizmap-web-client/lib/jelix/core/jCmdlineCoordinator.class.php : 27
	6	jCmdlineCoordinator->__construct()	/DATAS/lizmap-web-client/lizmap/scripts/script.php : 18
```

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by laurentj** [comment]
Probably there were several HTTP requests at the same time after cleaning the temp, so many processes recreated the configuration cache at the same time. 

won't fix.
