### ISSUE TITLE
The project ACL config is not respected

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2012]
### What is the bug?
The project config contains:
```
acl : [
  'env_velo'
]
```
So only users in `env_velo` user group can have access to the project, but the `admin` user which is in `admins` user group and not in `env_velo` can click on the map in the landing, can see the HTML but not the map, because lizmap plugin restricted the access.

`admins` user group has access to the repository defined at the repository level and has access to all repository defined in group rights management page.

### Steps to reproduce the issue

1. Go to Lizmap administration panel
2. Click on Groups of users for rights 
3. Click on Change rights of groups
4. Set View projects in the repository to yes for admins group
5. Set the acl project to env_velo
6. Go to Lizmap landing page after authentication
7. See the project with acl project set to env_velo

### Expected behavior

The project with `env_velo` acl has not to be in the landing page if the user is not in the `env_velo` user group.

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by alagroy-42** [comment]
Isn't it normal that the `admins` group has access to all projects ? @laurentj

**Comment by rldhont** [comment]
@alagroy-42 no, the lizmap project manager can restrict access for admins

**Comment by rldhont** [comment]
@mdouchin has introduced the lines that gives acces to all projects for lizmap admins.

@laurentj @alagroy-42 these lines https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/lizmapProject.class.php#L2353
```php

        // Check user is admin -> ok, give permission
        if (jAcl2::check('lizmap.admin.repositories.delete')) {
            return true;
        }
```
