### ISSUE TITLE
Tab content is not visible using Edition on Android (Lizmap 3.4.0)

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#2019]
### What is the bug?
Feature edit does not work on mobile devices if the edit form is organized in tabs (Drag and drop designer). Simply tab content does not show on mobile devices. On desktop interface it works without any problem.

### Environment

 - Lizmap version: 3.4.0
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10.6
 - OS (Windows, Linux, MacOS, Android…): error on Android (phone), works on Windows (desktop)
 - Browser (Firefox, Chrome…): Chrome

**Comment by aeduard** [comment]
Also, if not all columns of the table are present in the form (Drag and drop designer), lizmap 3.4.0 will rewrite each cell with NULL values (Postgresql 12.5).
To overcome the issue I've put each column in the form layout, and set the not used ones with hidden widget type.

**Comment by dmiolo** [comment]
I have the same issue. To get around the problem i've set on map.js (lizmap/www/assets/js/map.js) at line 5568 
`checkMobile: function() {
	return **false**;
    },
`
instead of 
`checkMobile: function() {
	return **mCheckMobile()**;
    },
`

**Comment by rldhont** [comment]
also confirmed

**Comment by nboisteault** [comment]
> Also, if not all columns of the table are present in the form (Drag and drop designer), lizmap 3.4.0 will rewrite each cell with NULL values (Postgresql 12.5).
> To overcome the issue I've put each column in the form layout, and set the not used ones with hidden widget type.

This is linked to https://github.com/3liz/lizmap-web-client/issues/1994

**Comment by nboisteault** [comment]
Issue confirmed. Working on a fix.
Thanks for report.

**Comment by nboisteault** [comment]
@rldhont @mdouchin this line cause the issue : https://github.com/3liz/lizmap-web-client/blob/release_3_4/lizmap/www/assets/js/edition.js#L1528

@mdouchin You fixed this kind of wrong behavior here : https://github.com/3liz/lizmap-web-client/commit/81de534556faaeb983d61b0d1a0145b11afe8919

`// We need to force showing the container before testing li visibility`

This comment in edition.js [here](https://github.com/3liz/lizmap-web-client/blob/release_3_4/lizmap/www/assets/js/edition.js#L1510) tell us form has to be visible but it is not the case in mobile mode.
As a workaround we could display form in mobile and desktop context.

Any thoughts?

**Comment by nboisteault** [comment]
I have made a manual test for this issue => https://github.com/3liz/lizmap-web-client/commit/81073d3f390b6bdf2703ac219b8273e3f555d8d7
