### ISSUE TITLE
QGIS Project & cfg files with a space in the name cannot be used by LWC

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#2020]
When the project file contains a space, Lizmap Web Client do not show it in the home page. 

I need to check if the project can still be accessed with URL `&project=my+project+name`

Tested with Lizmap Web Client 3.3.12 & QGIS Desktop/Server 3.10

**Comment by Gustry** [comment]
If it's a serious bug on LWC side, it's easy for me to raise a warning (even temporary for a few lizmap plugin versions) about having spaces in the QGS file name. Would it be needed ?

**Comment by laurentj** [comment]
We should fix this ASAP.
