### ISSUE TITLE
 Filtering information popups no longer works.

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#2027]
Hello,
(sorry for my poor Englisch)

After updating from Lizmap to V3.4.0 I have the following problem.
All columns are displayed in the popup. With the previous version I could set that in QGIS. In layer properties I chose fields for "Do not expose via WMS" and also WFS but stil not working.
Also with attributes forms I have set "Type widget" to hidden. But no result. Could it be a bug?

https://user-images.githubusercontent.com/8125819/104135147-7a76ce80-538e-11eb-9740-736addf70e13.mp4

 - Lizmap version: 
 - QGIS Server FULL version: 3.10.13-1
 - QGIS Desktop FULL version: 3.16.2
 - OS (Windows, Linux, MacOS, Android…): Windows10 20H2
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? 

Greetings Nico

**Comment by Gustry** [comment]
Thanks for the video.
Can you edit and fill required information just after your video ?
I see it's like 3.16.X? Which X ?
Both on server and desktop please.

If I have followed correctly, there is a fix in 3.16.2 about this new UI, maybe it's related.
