### ISSUE TITLE
The landing page shouldn't show project when not available for groups ACL

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#2032]
### What is the bug?

Given a project with these fake groups :

![Screenshot from 2021-01-12 16-22-46](https://user-images.githubusercontent.com/1609292/104295139-5d421d00-54c0-11eb-86e8-11fbee186ea7.png)

The project is still visible in the LWC landing page : 

![Screenshot from 2021-01-12 16-21-51](https://user-images.githubusercontent.com/1609292/104295239-764ace00-54c0-11eb-881d-40e045a6b18c.png)

But then if I click on it, it doesn't work : 

![Screenshot from 2021-01-12 16-22-25](https://user-images.githubusercontent.com/1609292/104295261-81056300-54c0-11eb-82c1-e6db37257b57.png)

To debug, I tried to reach the GetCapabilities 
http://qgis.server/ltr?map=%2Fhome%2Fetienne%2Fdev%2Flizmap%2Flizmap-plugin%2Flizmap%2Ftest%2Fdata%2Flizmap_3_3.qgs&request=getcapabilities&service=WFS&version=1.0.0&Lizmap_User=admin&Lizmap_User_Groups=__priv_admin%2C

But it tells me that I don't have ACL permissions

![Screenshot from 2021-01-12 16-22-34](https://user-images.githubusercontent.com/1609292/104295365-a85c3000-54c0-11eb-9828-b12534674379.png)

### Expected behavior

So IMHO, the project shouldn't be shown to the user, as it makes LWC buggy when loading the project.

If I remove the ACL in the Lizmap config, it works well.

It was maybe working before LWC 3.4 because no Lizmap server QGIS plugin ?

### Environment

 - Lizmap version: 3.4 branch and master branche
 - QGIS Server FULL version: 3.10.13
 - QGIS Desktop FULL version: 3.10.13
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PG

**Comment by rldhont** [comment]
@Gustry thanks for this review, it is the same as #2012 and I provide a fix #2033
