### ISSUE TITLE
Improve test for the PR [Bugfix] Cache does not work after authorization

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2039]
The PR #2035 [Bugfix] Cache does not work after authorization has fixed a bug in release_3_4 but does not provide a test.

The test could be:
- [x] Config the tile cache as file cache
- [x] Create the the cache with the lizmap command line
- [x] Check the tile cache size
- [x] Go to the map, zoom and pan on it without authentication
- [x] Check the tile cache size has not changed
- [x] Authenticate as admins
- [x] Go to the map, zoom and pan on it
- [x] Check the tile cache size has not changed
- [x] Authenticate as no admins
- [x] Go to the map, zoom and pan on it
- [x] Check the tile cache size has not changed

**Comment by drillinP** [comment]
@rldhont  j'ai fais toutes les étapes, la taille du cache change à chaque fois

**Comment by rldhont** [comment]
@drillinP the bug is https://github.com/3liz/lizmap-web-client/issues/2053
