### ISSUE TITLE
Popup en dessous des points

### ISSUE THREAD

**Issue by CREASIG** [3liz/lizmap-web-client#204]
Bonjour,

les points de ma couche (shp) apparaissent sur la popup lorsque je clique dessus, et impossible de la fermer.

Seule solution, ajouter dans www/themes/default/css/map.css un id 
#liz_layer_popup{
	z-index:10000 !important;
}

Je n'ai pas modifié les js de la popup qui apparemment génèrent le z-index.

Cordialement.

**Comment by mdouchin** [comment]
Bonjour,

* Quelle est la version de Lizmap-web-client impactée par ce bug ?
* Quelle est la couche de fond activée lorsque cela se produit ?

**Comment by CREASIG** [comment]
Il s'agit de la 2.11 release .
Qgis-server : 2.10
Fond de plan : Mapnik, Mapquest
Layer utilisée : Point shape, projection epsg 3944

Cela dit ce projet comporte énormément de layers. Sur d'autres projets similaires mais avec moins de layers tout fonctionne normalement.

**Comment by rldhont** [comment]
@CREASIG, le problème vient du nombre de couche de votre projet.

Nous allons tout de même voir si il n'existe pas un moyen d'améliorer les choses.

**Comment by rldhont** [comment]
Correction faîtes pour la futur 3 avec le commit bbc138200ad9fd79f11a2570c22f5176524a5172 [BUGFIX] Update Z_INDEX_BASE after layersadded

Reste à backporter

**Comment by rldhont** [comment]
Fixed in 550d204
