### ISSUE TITLE
Use RULELABEL=AUTO in WMS GetLegendGraphics to get only layer icon

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2042]
In QGIS Server 3.10 a new value AUTO is available for RULELABEL WMS GetLegendGraphics parameter. it hides item label for layers with Single symbol rendering.

https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#getlegendgraphics

**Comment by nboisteault** [comment]
@rldhont no backport for release_3_3?

**Comment by rldhont** [comment]
@nboisteault no backport
