### ISSUE TITLE
[Bug] Regression Release_3_4 - form with relationnal value 

### ISSUE THREAD

**Issue by drillinP** [3liz/lizmap-web-client#2046]
### What is the bug?

The #1960 to fix bug with relational value has introduced a regression in form edition.

### To reproduce
* test with project `form_type_relational_value`
* follow the md file assigned to this project

**Comment by rldhont** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/pull/2047/commits/d951d3d14e48fcbc39305d08045ac28e2dbd6209
