### ISSUE TITLE
dms as default option in overview-box 

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2050]
### Description
Is there a possibility to have 'dms' selected by default in overview-box when lizmap loads?
Since `MousePosition` was refactored this script 
`
lizMap.events.on({
    'uicreated': function(e) {
    $('lizmap-mouse-position > div.coords-unit > select').val('dms').change();
    }
});
`
is not working.

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version: 3.16.2
 - QGIS Desktop FULL version: 3.16.2
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome

**Comment by Gustry** [comment]
Not really answering, but maybe a linked answer : https://github.com/3liz/lizmap-web-client/issues/2004

**Comment by gioman** [comment]
> Not really answering, but maybe a linked answer : #2004

@Gustry not sure if since this 2021 ticket there is anything new about this request. Is there any configuration that can be used to achieve it?

Maybe this in QGIS project properties?

![image](https://github.com/user-attachments/assets/fb8093fa-9448-484b-866c-3fc8ca5326c9)

**Comment by ygorigor** [comment]
@gioman I use this script
 `let coords_unit_select = document.querySelector('div.coords-unit > select');
        coords_unit_select.value = 'dms';
        coords_unit_select.dispatchEvent(new Event('change'));`

**Comment by gioman** [comment]
> @gioman I use this script
> `let coords_unit_select = document.querySelector('div.coords-unit > select'); coords_unit_select.value = 'dms'; coords_unit_select.dispatchEvent(new Event('change'));`

@ygorigor ah cool! that goes in the js folder as any other LMWC js script?

**Comment by Gustry** [comment]
Thanks @ygorigor for reporting your snippet.

Yes @gioman that's correct.

**Comment by ygorigor** [comment]
> > @gioman I use this script
> > `let coords_unit_select = document.querySelector('div.coords-unit > select'); coords_unit_select.value = 'dms'; coords_unit_select.dispatchEvent(new Event('change'));`
> 
> @ygorigor ah cool! that goes in the js folder as any other LMWC js script?

Yes, after `uicreated`

**Comment by gioman** [comment]
> Yes, after `uicreated`

@ygorigor not sure what do you mean here.

**Comment by Gustry** [comment]
In your JS script, you should "listen" to some events. You need to copy/paste the snippet when the event `uicreated` is fired. 

https://docs.lizmap.com/current/en/publish/customization/javascript.html#disable-right-click

**Comment by gioman** [comment]
@Gustry @ygorigor 

so that would be

```
lizMap.events.on({
   uicreated: function(e) {
     let coords_unit_select = document.querySelector('div.coords-unit > select'); coords_unit_select.value = 'dms';
     coords_unit_select.dispatchEvent(new Event('change'));
   }
});
```

?

**Comment by gioman** [comment]
@Gustry @ygorigor 
thanks! works fine for "dms" but not for "dd", any idea?

**Comment by josemvm** [comment]
>thanks! works fine for "dms" but not for "dd", any idea?
@gioman try 'degrees'

**Comment by ygorigor** [comment]
@gioman look at values
![image](https://github.com/user-attachments/assets/fd75819d-ac4c-495a-acb9-32032c09d4a5)

**Comment by gioman** [comment]
> > so that would be
> > ```
> > lizMap.events.on({
> >    uicreated: function(e) {
> >      let coords_unit_select = document.querySelector('div.coords-unit > select'); coords_unit_select.value = 'dms';
> >      coords_unit_select.dispatchEvent(new Event('change'));
> >    }
> > });
> > ```

> 
> Yes


@ygorigor seems is not working anymore on 3.9.*, can you confirm?

**Comment by ygorigor** [comment]
> > > so that would be
> > > ```
> > > lizMap.events.on({
> > >    uicreated: function(e) {
> > >      let coords_unit_select = document.querySelector('div.coords-unit > select'); coords_unit_select.value = 'dms';
> > >      coords_unit_select.dispatchEvent(new Event('change'));
> > >    }
> > > });
> > > ```
> 
> > Yes
> 
> [@ygorigor](https://github.com/ygorigor) seems is not working anymore on 3.9.*, can you confirm?

@gioman for me is working even in 3.11
