### ISSUE TITLE
upload photos from webcam using a notebook

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2051]
### Description

is it possible?

the browsers have permissions on the camera but the lizmap allways search photos in storage drive with windows explorer...

thanks

### Environment

 - Lizmap version: 3.3.13
 - QGIS Server FULL version: 3.10.10
 - QGIS Desktop FULL version: 3.10.10
 - OS (Windows, Linux, MacOS, Android…): Windows, Linux
 - Browser (Firefox, Chrome…): All

**Comment by Gustry** [comment]
Just a note : 

On https://demo.lizmap.com using a Android device
opening https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=observatoire 
shows a camera by default.

**Comment by josemvm** [comment]
hi @Gustry thnaks for your answer

i'm talking about **mobile devices** (like tablets or notebooks) with **linux** OS or **windows** OS
these devices/OS only show the storage units by default and not the camera

thanks for your attention

**Comment by Gustry** [comment]
I understood your request. I was only mentioning the Android phone case where it works ;-)

**Comment by josemvm** [comment]
;-)

**Comment by josemvm** [comment]
is it possible to do something to solve this problem?

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/2741

**Comment by Gustry** [comment]
Did you try with latest versions of Lizmap Web Client and web-browsers ?
We are only working on LWC 3.5 and 3.6 now. Your ticket is mentioning 3.3.
