### ISSUE TITLE
Pre-generated cache is not used in Lizmap 3.4.1

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#2053]
### What is the bug?
I have 3.3.10 which works well in this regard.
I installed 3.4.1 and generate tiles by script `PHP lizmap/scripts/script.php lizmap~wmts:seeding [-v] [-f] repository project layer TileMatrixSet TileMatrixMin TileMatrixMax` into SQLite as before. But Lizmap 3.4.1 not use this cache and it regenerates the cache while I use map in browser. If I open the 3.3.10 version this uses the same cache generated by the script correctly.

### Environment

-  Lizmap version: 3.4.1
-  QGIS Server FULL version: 3.10
-  QGIS Desktop FULL version: 3.10
-  OS (Windows, Linux, MacOS, Android…): Linux
-  Browser (Firefox, Chrome…): Firefox, Chrome

How can I get the script generated cache to be used (3.3.10 uses the generated cache correctly)?

**Comment by nboisteault** [comment]
@johnzet39 if you execute `ls -l` on one of your *.cache file, what is the output?

**Comment by johnzet39** [comment]
@nboisteault , ls -l topography_EPSG_3857.db 
-rw-r--r-- 1 www-data www-data 6740133888 Feb 15 19:31 topography_EPSG_3857.db

**Comment by nboisteault** [comment]
@johnzet39 OK you use sqlite and not files, I read too quickly.
Ho do you watch that Lizmap regenerate cache?

**Comment by johnzet39** [comment]
@nboisteault when Lizmap loads map it starts loading tiles slowly like the cache file does not exist yet. And cache file size changes.

**Comment by ygorigor** [comment]
@nboisteault on master branch LWC has the same bug. If cache was generated as guest, if I login with a username LWC will start to generate another tiles

**Comment by cfsgarcia** [comment]
In version 3.4.1, I have made the changes suggested in both commits supposedly fixing the problem: [Fix Pre-generated cache is not used in Lizmap 3.4.1](https://github.com/3liz/lizmap-web-client/pull/2272/commits/9607afcb25131be8f9bf5d863e799b3bdcc16c78), [Fix WMTS Request - use specific $wmsRequest parameters array](https://github.com/3liz/lizmap-web-client/pull/2272/commits/0203fd8289e5a46da0a8fe0a45e7d288d38c5fc3)

Though it's not working, the two problems still occur:
-Cache (file format) generated in older version (3.3rc2) is not taken into account in 3.4.1. New cache is generated while navigating within the web app. 
-wmts.cmdline.php seeding script does look to it runs ok but in the end it doesnt seem to generate the cache Lizmap 3.4.1 consumes.

**Comment by Gustry** [comment]
@cfsgarcia I think instead of manually editing files, maybe you should use a Lizmap ready-to-use package.
Either from the release page : https://github.com/3liz/lizmap-web-client/releases
Or it's not yet released, like maybe this patch if I understand correctly : https://packages.3liz.org/pub/lizmap/unstable/3.4/
