### ISSUE TITLE
Apply php-cs-fixer 2.18.0

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2055]
The new php-cs-fixer version 2.18.0 discovered a lint error on lizmap/modules/admin/classes/config.listener.php
```
-        if (/*!$event->himself && */jAcl2::check('acl.user.view')) {
+        if (/*!$event->himself && */ jAcl2::check('acl.user.view')) {
```

**Comment by Gustry** [comment]
Is the version of PHP-Cs-Fixer not fixed in the source code ?
