### ISSUE TITLE
Unsupported letters in map view

### ISSUE THREAD

**Issue by majky-beast** [3liz/lizmap-web-client#2057]
![Lizmap_znaky](https://user-images.githubusercontent.com/72867236/105366488-b0724900-5bff-11eb-8762-5de498de6693.jpg)
### Environment

 - Lizmap version: 3,3
 - QGIS Server FULL version: 3,10
 - QGIS Desktop FULL version: 3,10
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…): Chrome

Hi!
When I submit my project to lizmap web client my map view don´t recognize special characters as ď, ť, ň, ľ; but in the pop up they are showing corectly as you can see in the attachment. Is there any solution to this problem?
Thank you

**Comment by Gustry** [comment]
> in the pop up they are showing corectly as you can see in the attachment.

This text is managed by the Lizmap PHP application. So Lizmap is working correctly.

> my map view don´t recognize special characters as ď, ť, ň, ľ;

This text is printed by QGIS-Server.
So it's a QGIS Server settings only, not Lizmap.
You need to configure QGIS-Server : 
* Check encoding used on the server ?
* Check font used on the server

Have a look to https://github.com/3liz/lizmap-web-client/issues/1644

**Comment by majky-beast** [comment]
Thank you 
solution mention in #1644 works for me as well.
