### ISSUE TITLE
[impression] zone de texte contenant une expression

### ISSUE THREAD

**Issue by antoine373** [3liz/lizmap-web-client#206]
Bonjour,

J'utilise un composeur d'impression sous qgis qui me permet d'afficher des valeurs attributaires au sein d'une zone de texte. Pour cela je fait une "insérer une expression" et j'utilise par exemple les fonctions "attribute" ou "getFeature". Tous s'affiche très bien dans le composeur d'impresion de QGIS, mais j'ai deux problèmes lorsque je veux utiliser ce composeur via lizmap:
- Le PDF généré ne m'affiche pas l'information attributaire voulue, mais la syntaxe de l'expression utilisée. Exemple "[% attribute( getFeature( 'Prospective', 'reference', '3.002'), 'avancement')%]"
- Lorsque que je veux configurer ma zone de texte via des balises HTML, en cochant "afficher en html", j'obtiens une erreur du type "500 Internal Server Error".

Cordialement

**Comment by antoine373** [comment]
Finalement je pense que le problème vient d'une fonction personnalisée écrite en python via "l'éditeur de fonction" dans QGIS. Celle-ci n'est apparemment pas reconnue lors de l'impression via lizmap.
Y a-t-il un moyen pour que les fonctions personnalisées créées  sur QGIS soient prise en compte lors d'une impression lizmap ?

**Comment by rldhont** [comment]
Bonjour,

Pour l'erreur 500, c'est le même problème que  [impression] les hachures génèrent un erreur #207 

Pour les expressions, nous n'avons jamais testé QGIS Server avec une expression dans une zone de texte. Avez-vous essayé avec quelque chose de simple ?

**Comment by mdouchin** [comment]
A vérifier, mais il me semble en effet que les expressions liées à des fonctions personnalisées écrites en python ne fonctionnent pas sur QGIS Server

**Comment by antoine373** [comment]
Bonjour,

Les expressions fonctionnent en effet avec des choses simples, par exemple : 
- en rentrant <b>[% $now %]</b> dans une zone de texte, on obtient, lors d'une impression via lizmap, la date et l'heure à laquelle le pdf a été généré.
- en rentrant <b>[%  attribute( getFeature( 'cadastre', 'parcelle', 'AB0001'),  'adresse')%]</b>, nous voulons afficher <i>"l'adresse"</i> de l'objet de la couche <i>"cadastre"</i> dont la valeur du champs <i>"parcelle"</i> est <i>"AB0001"</i>. Cette expression fonctionne très bien lors de l'impression lizmap.

Par contre les fonctions personnalisées écrites en python ne semblent pas fonctionner : 
- en utilisant la fonction décrite dans ce lien (http://nathanw.net/2015/05/21/accessing-composer-item-properties-via-custom-expressions-in-qgis/), il est possible d'extraire l'information d'une zone de texte d'une composeur d'impression.
En l'appliquant à l'exemple précédent, je peux ecrire un numero de parcelle dans une zone de texte, utiliser la fonction python pour extraire ce numero et ainsi retourner n'importe quel attribut de la parcelle que l'on a renseignée. En combinant ça avec la possibilité de modifier le contenu de certaines étiquettes via lizmap, on pourrait offrir beaucoup de liberté à l'utilisateur.

Mais les fonctions pythons ne semblent pas fonctionner sur qgis-server....

**Comment by loic74** [comment]
Je déterre un peu le fil de discussion, mais ce serait effectivement une fonctionnalité intéressante. J'ai une fonction python (fonctionnelle en local) qui permet d'afficher automatiquement les fournisseurs de données (champ attribution des méta-données) des couches visibles de la carte. Ce qui serait très pratique pour Lizmap afin de communiquer légalement à des tiers les impressions, sans avoir à entrer un par un les fournisseurs de données en sous-titre, ou bien lister l'ensemble des ces fournisseurs sans que leurs données soient présents sur la carte... 

A moins qu'une solution alternative existe ?

**Comment by QuentinStrappazzon** [comment]
Bonjour à tous,
Je suis confronté à la même problématique que celle évoquée dans les précédents posts : j'affiche dans un composeur d'impression des labels définis sur la base de règles utilisant des fonctions python du type maximum et minimum. Tout fonctionne bien sur QGIS mais pas sur Lizmap (fonctions non reconnues par Qgis Server).

@nboisteault je comprend du post précédent que vous essayez de travailler sur ce problématique depuis le 7 juin dernier c'est bien ça ? Ce serait effectivement une grande avancée pour pouvoir proposer via lizmap des outils dynamique d'affichage de données.

**Comment by nboisteault** [comment]
@QuentinStrappazzon Je souhaitais faire des tests mais ça ne sera pas prochainement. Pouvez-vous préciser la version de LWC et QGIS Server utilisée ? Merci.

**Comment by QuentinStrappazzon** [comment]
@nboisteault 
Nous louons notre espace lizmap directement à 3Liz
Version de LWC : 3.2.3
Version de QGIS Server : celle qu'utilise 3liz

**Comment by QuentinStrappazzon** [comment]
Rebonjour,
je viens de faire quelques tests et en fait je pense avoir trouvé une piste d'explication/solution : pour que mes labels basés sur des expressions fonctionnent, il faut que :  
- ces expressions soient liées à une couche postgis ou sqlite (et pas à une couche shape)
- que la couche utilisée soit bien active dans le projet, si elle est décochée l'expression ne marche pas.
Du coup, avec ces précautions de mon côté, ça marche, je peux afficher des labels se basant sur des expressions du type CASE WHEN maximum ("champA") <>minimum("champA") THEN 'ATTENTION' END

Si ça peut servir à d'autres ... :)

**Comment by Gustry** [comment]
Est-ce que ce ticket est toujours d'actualité ?
Nous n'avons pas de souci pour des zones de textes avec des expressions dans QGIS server lors d'une impression PDF.
