### ISSUE TITLE
CSS: Blank line between the map and the right-dock appears

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2061]
### What is the bug?
Blank line between the map and the right-dock appears

### Steps to reproduce the issue

1. Go to https://liz.lizmap.com/etrimaille/index.php/view/map/?repository=test&project=earthquake
2. Click on DataViz
3. See that a blank line at the left of the right-dock

### Expected behavior
No blank line between the map and the right-dock

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): all
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by ygorigor** [comment]
It's because `#right-dock `has fixed  `width: 30%` in map.css. It can be set to `auto` e.x.
