### ISSUE TITLE
Editing tool issue in Lizmap

### ISSUE THREAD

**Issue by CpuigGIS** [3liz/lizmap-web-client#2062]
Hi everyone, 

I'm facing a strange issue on my Lizmap project.
Everything works fine until the editing tool I would like to put on some of my layers.

These layers are spatialite db.
They have a primary key, they are published in WFS in layers properties and project properties.
I put editing tools in the Lizmap plugin without any problem, but in the browser on my project the editing tool doesn't appear at all (I also cannot edit an object from the popup dock).
I got the same issue with my own project or in the demo project (Montpellier transport) which works if it's not in my server.

A strange other thing is that if I delete the layer I want to edit and save my QGis project (but not apply in Lizmap plugin) then I can see the editing tool in the browser, but of course it's useless as I deleted the layer.

Hope someone can help me with that issue... :)

Hereunder I put all the version I have for each software.

Regards
Céline

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.10.12
 - QGIS Desktop FULL version: 3.10.12
 - OS (Windows, Linux, MacOS, Android…): Linux Ubuntu 10.04.5 LTS
 - Browser (Firefox, Chrome…): All
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

**Comment by rldhont** [comment]
If your data are stored in a spatialite db, did you configure PHP to use Spatialite extension ? https://docs.lizmap.com/current/en/install/linux.html#spatialite

**Comment by CpuigGIS** [comment]
By opening the php.ini file, it seems that clearly not.
My client didn't want the editing tool in is first approach that's why I think I passed it during the configuration. Thanks!

As the link in the lizmap documentation doesn't exist anymore, I found an GitHub issue which is the same #740 and which give the steps.
I should already have the lib files (.so) somewhere as I got "libsqlite3-mod-spatialite is already the newest version (4.3.0a-6~bionic3).". Now it's just remaining to find them... :)

**Comment by CpuigGIS** [comment]
Any other idea?

**Comment by ludovico85** [comment]
Hi, i'm facing with the same issue. I've installed sqlite and enabled spatialite as reported in [http://www.gaia-gis.it/gaia-sins/spatialite-cookbook-fr/html/php.html](http://www.gaia-gis.it/gaia-sins/spatialite-cookbook-fr/html/php.html).

php sqlite correctly installed
```
php7.0 -m|grep sqlite
```
```
pdo_sqlite

sqlite3
```

I've created the sqlite3_ext dir with the following contente
```
ls /var/www/sqlite3_ext
```
```
libspatialite.so  libspatialite.so.7.1.1  mod_spatialite.so  mod_spatialite.so.7.1.0
```

I've made a test of the spatialite extension and works fine [http://www.gaia-gis.it/gaia-sins/spatialite-cookbook-fr/html/php.html](http://www.gaia-gis.it/gaia-sins/spatialite-cookbook-fr/html/php.html)

```
 php  /var/www/SpatialiteSample.php
```
```
<html>
  <head>
    <title>Testing SpatiaLite on PHP</title>
  </head>
  <body>
    <h1>testing SpatiaLite on PHP</h1>

<h3>SQLite version: 3.31.1</h3><h3>SpatiaLite version: 5.0.0</h3><h3>Inserted 10000 entities of type POINT SRID=4326</h3><h3>Inserted 10000 entities of type LINESTRING SRID=4326</h3><h3>Inserted 10000 entities of type POLYGON SRID=4326</h3>
  </body>
</html>wilson@ubuntu-s-1vcpu-1gb-fra1-01:~$  php  /var/www/SpatialiteSample.php
<html>
  <head>
    <title>Testing SpatiaLite on PHP</title>
  </head>
  <body>
    <h1>testing SpatiaLite on PHP</h1>

<h3>SQLite version: 3.31.1</h3><h3>SpatiaLite version: 5.0.0</h3><h3>Inserted 10000 entities of type POINT SRID=4326</h3><h3>Inserted 10000 entities of type LINESTRING SRID=4326</h3><h3>Inserted 10000 entities of type POLYGON SRID=4326</h3>
  </body>
</html>
```

The permission of the folder and database

```
ls -la /var/www/lizmap-web-client-3.4.0/lizmap/qgis_projects
```
drwxr-xr-x  5 www-data www-data 4096 Mar 25 21:16 demoqgis
```

```
ls -la /var/www/lizmap-web-client-3.4.0/lizmap/qgis_projects/demoqgis
```

```
drwxr-xr-x  4 www-data www-data    4096 Mar 25 21:16 data
drwxr-xr-x  2 www-data www-data    4096 Mar 25 21:16 edition
-rw-r--r--  1 www-data www-data   40233 Feb 23 11:36 events.qgs
-rw-r--r--  1 www-data www-data    7752 Feb 23 11:36 events.qgs.cfg
drwxr-xr-x  8 www-data www-data    4096 Mar 25 21:16 media
-rw-r--r--  1 www-data www-data 1065984 Feb 23 11:36 montpellier.qfts
-rw-r--r--  1 www-data www-data  433854 Feb 23 11:36 montpellier.qgs
-rw-r--r--  1 www-data www-data   35466 Feb 23 11:36 montpellier.qgs.cfg
-rw-r--r--  1 www-data www-data  138393 Feb 23 11:36 montpellier.qgs.png

```


The error log of lizmap doesn't show any error but the editing tool is still disabled (with my own project but also with the montpellier demo dataset). Any idea?

**Comment by ludovico85** [comment]
I've solved simply by updating the project after enabling spatialite.  I don't now where the issue arose, but now is working.

**Comment by Gustry** [comment]
We are currently dropping Spatialite support for editing capabilities.
3liz/lizmap-plugin#364
