### ISSUE TITLE
Comments on Popup functionality for child layers on Lizmap 3.4.1

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#2065]
### What is the bug?
Table margins are cut on Popup dock's child table viewed in compacted way (check id column on the image below).
![lizmap_popup](https://user-images.githubusercontent.com/16295364/105645887-44b10a00-5ea5-11eb-87f2-b03acd587bd0.jpg)

Beside the bug I would like to add some general comments on Popup functionality when child layer is set to appear with 1toN relation.

- I managed to get the compacted way view only if child layer source is set to _auto_, this requirement is not specified in [docs](https://docs.lizmap.com/current/en/publish/configuration/popup.html#one-to-many-relations).
- The compact way is more meaningful in many case, it could be selectable directly as default from lizmap qgis plugin. Many users don't know about this feature and if many child rows are present the expanded view is inconvenient.
- This compact/expanded function should also work with qgis/lizmap source.
- In auto mode 2, mostly unnecessary columns are shown by default, taking important space, first the primary key column, secondly the foreign key column.
- The pre v3.4 type of compact way view of child tables is not working anymore (<table class="lizmap_merged">), but it is still present in the [documentation](https://docs.lizmap.com/current/en/publish/configuration/popup.html#display-children-in-a-compact-way). 

### Steps to reproduce the issue

1. Create a 1:n relationship, than activate popup for both layers in auto setting. Child table has 6 columns. 
2. Click on parent geometry on lizmap web client, than change to compact view the child table.
3. Table margins are cut, first column's content is not fully visible when browser is set to Maximized size (desktop resolution is 1920 x 1200).
4. When browser dimension is reduced, than scroll bar appears, and the whole table data becomes visible.

### Expected behavior

The whole table should be visible even if the browser is set to Maximized size.

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Firefox, Chrome, Opera

**Comment by ygorigor** [comment]
@aeduard it can be fixed in bootstrap-responsive.css by changing 
`@media (min-width: 1200px) {
  .row {
    margin-left: -30px;
    *zoom: 1;
  }`

to

`@media (min-width: 1200px) {
  .row {
    margin-left: -20px;
    *zoom: 1;
  }`

**Comment by nboisteault** [comment]
I have fixed the bug. I keep it open concerning other points.

**Comment by nboisteault** [comment]
> In auto mode 2, mostly unnecessary columns are shown by default, taking important space, first the primary key column, secondly the foreign key column.

@aeduard you can hide those columns by unchecking them. Layer properties => Fields tab => WMS column

**Comment by nboisteault** [comment]
> I managed to get the compacted way view only if child layer source is set to auto, this requirement is not specified in docs.

It is now => https://github.com/3liz/lizmap-documentation/commit/d11bc961dfad29c42af10852aa3b56e92d0b413e
