### ISSUE TITLE
Field restriction on edition

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-web-client#2066]
### Description
Hi ,
I have a postgreSQL table with a field as character varying and i would like to restrict its value to a specific format : 'YYYY/MM/NNN'
For this i used a QGIS function :  regexp_match("num", '^\\d{4}/\\d{2}/\\d{3}$').
With QGIS, it works well and i cannot for example enter the value 'Test' but the value '2000/20/111' is fine.

My problem is when i am on the Lizmap app and i add an entity, the value 'Test' is accepted.
Is it normal or is it a bug ?

Thanks 
### Environment

 - Lizmap version: 3.3.13
 - QGIS Server FULL version:
 - QGIS Desktop FULL version: 3.10.12
 - OS (Windows, Linux, MacOS, Android…): Windows for QGIS, Linux for web display
 - Browser (Firefox, Chrome…): Brave
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?  No Idea ..

**Comment by rldhont** [comment]
This feature is not available in lizmap web client 3.3.*

You need to upgrade your lizmap web client to version 3.4.* and to add lizmap-plugin as a QGIS Server plugins.
