### ISSUE TITLE
Docker image fail with  Could not open input file: /scripts/script.php

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#2067]
### What is the bug?
When trying to run lizmap-docker-compose with the latest lizmap 3.4 Docker image, it fails with  the error 
`Could not open input file: /scripts/script.php` - cf https://github.com/3liz/lizmap-docker-compose/issues/9

### Steps to reproduce the issue

1. Download latest lizmap-web-client docker image 
2. Run the [lizmap-docker compose stack](https://github.com/3liz/lizmap-docker-compose) in a fresh environment 
3. The lizmap container fails with `Could not open input file: /scripts/script.php`

### Expected behavior
The lizmap container should run without error

### Screenshots and logs
```
lizmap_1  | + su -c 'php /scripts/script.php jcommunity~user:create -v --no-error-if-exists --admin --reset   admin'
lizmap_1  | Could not open input file: /scripts/script.php
lizmap-docker-compose_lizmap_1 exited with code 1
```

Apperently it sesems related to a `$APPDIR` environnement variable which is not initialized.

**Comment by laurentj** [comment]
fixed
