### ISSUE TITLE
[impression] les hachures génèrent un erreur

### ISSUE THREAD

**Issue by antoine373** [3liz/lizmap-web-client#207]
Bonjour,

Lors de l'utilisation du module impression, les couches qui sont hachurées ("motif de lignes" dans le style qgis) entraînent une page "500 Internal Server Error".
Lorsque l'on supprime la représentation par "motif de lignes" l'impression fonctionne correctement.

Lizmap : 2.11.0
Qgis : 2.8.3
Qgis-server : 2.8.3 

Cordialement.

**Comment by gioman** [comment]
If I understand correctly the description this is a problem of QGIS server in headless servers, the wrokaround is here (it would be needed to be documented in the QGIS server docs):

http://www.itopen.it/qgis-server-setup-notes/

**Comment by antoine373** [comment]
Hi,
Thanks for you reply.
I'm not sure to find my problem description in your url link.
In fact the printing feature (so the getprint request I guess) is working well with all of my project layer, except with layer configure in hatch style in qgis. Every time I want to print a hatch style layer I get "500 Internal Server Error", but everything fine with all other layer.

**Comment by gioman** [comment]
The problem is exactly that, there are specific symbology styles that are causing this issue because and underlying QGIS library would need X server to render them correctly on the PDF output. Add a fake X Server as detailed in the above page and you are good to go.

**Comment by antoine373** [comment]
Yes indeed !!
The two references describe the same issues "html text" and "line pattern".
So now i have the solution to fix it, but sadly i'm not used to qgis server side and not really able to work on command line...

**Comment by rldhont** [comment]
Please update Lizmap or QGIS Server documentation if needed
