### ISSUE TITLE
Lizmap sends getcapabilities request instead of GetCapabilities to QGIS server

### ISSUE THREAD

**Issue by jfoucher** [3liz/lizmap-web-client#2077]
### What is the bug?

When loading a map, the lizmap frontend sends a GetCapabilities request to the backend. The backend should pass that request to QGIS server. However the lizmap backend seems to transform the request parameters.

indeed while I can see the following URL in the browser: https://lizmap.example.org/index.php/lizmap/service/?repository=montpellier&project=montpellier&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0` QGIS server receives something like this : `/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Flizmap%2Flizmap%2Finstall%2Fqgis%2Fmontpellier%2Eqgs&request=getcapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=&Lizmap%5FUser%5FGroups=`

Notice that `GetCapabilities` becomes `getcapabilities`

I have verified that this causes qgis server to return this error 
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
 <ServiceException code="OperationNotSupported">Request getcapabilities is not supported</ServiceException>
</ServiceExceptionReport>
```

Whereas if I modify the request as such :
`/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Flizmap%2Flizmap%2Finstall%2Fqgis%2Fmontpellier%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=&Lizmap%5FUser%5FGroups=`

it works perfectly.

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.4.11-Madeira
 - QGIS Desktop FULL version:
 - OS (Windows, Linux, MacOS, Android…): Any
 - Browser (Firefox, Chrome…): Any
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite

**Comment by Gustry** [comment]
Hi,

* FYI, QGIS 3.4 is not supported anymore by the QGIS.org community
* 3.4.11 is too old, at least update to the latest bugfix on 3.4 which is 3.4.15 https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
* This issue has already been fixed in QGIS Server 3.4, but after .11
