### ISSUE TITLE
Cache and atributelayer error

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-web-client#2079]
### What is the bug?
When is set up cache function on for any layer, zoom and center function at atribute layer function not work. The layers do not have to be identical. Just turn the casch function on.

 - Lizmap version: 3.3.10 and 3.4.1
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): win, linux
 - Browser (Firefox, Chrome…): Chrome

**Comment by nboisteault** [comment]
@gisgogo Can you provide a public link showing your issue ?
