### ISSUE TITLE
Feature : Add menu to change displayed layers order

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#208]
Add a menu in #mapmenu column at left to order displayed layers visually.

**Comment by mbernasocchi** [comment]
@rldhont was this ever considered? do you have an estimate?

**Comment by nboisteault** [comment]
@mbernasocchi We put this feature in [mapbuilder](https://github.com/3liz/lizmap-mapbuilder-module). This needs more documentation though. Can you test it and give us feedback ?

**Comment by mbernasocchi** [comment]
hey @nboisteault will be working on a LM instance next week, will try then. does this work with 3.3? is there a release plan for 3.3?
cheers

**Comment by nboisteault** [comment]
@mbernasocchi you can use lizmap 3.2.x or 3.3.x. Lizmap 3.3 should be finished but I have no date.

**Comment by paolo73an** [comment]
@nboisteault where does the content of mapbuilder zip package have to be put?
inside lizmap subdirectory named just "lizmap-mapbuilder-module" or what?
I haven't read about installation path....Thanks

**Comment by nboisteault** [comment]
@paolo73an I have updated README : https://github.com/3liz/lizmap-mapbuilder-module/commit/b52f83adc6900e36014e404eb7ef31e61b24fe92
