### ISSUE TITLE
Dataviz plots are not loading after commit ce33cd5

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2080]
### What is the bug?
After commit https://github.com/3liz/lizmap-web-client/commit/ce33cd5600f535181eeab7f3a90b055dd73bb156 was merged ino master branch, the configured dataviz plots are not showing in LWC.

### Environment
 - Lizmap version: 3.5.0-pre
 - QGIS Server FULL version: 3.16.3
 - QGIS Desktop FULL version: 3.16.3
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into PostgreSQL

**Comment by Gustry** [comment]
Thanks @ygorigor for beta testing the master branch after the merge of this huge commit in master.
I hope you read the Lizmap mailing list last week ;-)
