### ISSUE TITLE
Project title on Landing page in LWC 3.5

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2084]
### What is the bug?
Another regression I noticed after refactor, is project title on Landing page. 
Before merge the project title was taken from QGIS metadata `Title`.
Now it seems that project title is taken from .qgs file name.

### Screenshots and logs

In LWC
![image](https://user-images.githubusercontent.com/1684359/106560271-6fe3cb00-652f-11eb-8b6e-e5913f2c3984.png)

In QGIS
![image](https://user-images.githubusercontent.com/1684359/106560354-9275e400-652f-11eb-8fe2-ceeeb7b7ed48.png)

### Environment

 - Lizmap version: 3.5.0-pre
 - QGIS Server FULL version: 3.16.3
 - QGIS Desktop FULL version: 3.16.3
 - OS (Windows, Linux, MacOS, Android…):  Linux
 - Browser (Firefox, Chrome…): Chrome

**Comment by Gustry** [comment]
Linked to https://github.com/3liz/lizmap-web-client/issues/2490 ?

**Comment by ygorigor** [comment]
> Linked to https://github.com/3liz/lizmap-web-client/issues/2490 ?

Yes

**Comment by nboisteault** [comment]
@ygorigor I missed your issue. Thanks for it.
