### ISSUE TITLE
Add text labeling for Drawing tool

### ISSUE THREAD

**Issue by ghost** [3liz/lizmap-web-client#2087]
### Describe the solution you'd like
I love the new drawing tool. Unfortunately it seems, that it is not possible to add text labels. It would be great, to be able to label new drawn boxes or lines to precisely highlight and communicate isses with exported/printed PDF maps.

**Comment by nboisteault** [comment]
It has been funded and added to the main branch. Could you and other Lizmap users test this feature and give us feedback?

Ref : 
- https://github.com/3liz/lizmap-web-client/pull/3871
- https://github.com/3liz/lizmap-web-client/pull/3876
