### ISSUE TITLE
Bug on selection tool

### ISSUE THREAD

**Issue by manogenam** [3liz/lizmap-web-client#2093]
Hi
### What is the bug?

When I close selection tool, left click is still drawing and each drawing stays a screen like with drawing tool (the new one)

### Steps to reproduce the issue

1. Go to a project
2. click on selection tool
3. do a selection (any shape)
4. close selection tool 
5. left click on map

### Expected behavior

set 'move on map' tool when I closed selection tool

 - Lizmap version: 3.4.1
 
 - Browser : tested on Firefox and Chrome…

**Comment by rldhont** [comment]
Lizmap version 6.4.1 does not exist. @manogenam is it 3.4.1 ?

**Comment by manogenam** [comment]
sorry, yes it is 3.4.1
