### ISSUE TITLE
IGN Basemap (Photo + Scan) can not be displayed on Chrome and Edge

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#2102]
The IGN basemap (Photo or SCAN) are not dysplayed on the Edge or Chrome browser.
It's OK on Firefox.
It's also OK on the three browsers if you choose OpenStreetMap baselayers.

There isn't any error on the Lizmap logs.
![image](https://user-images.githubusercontent.com/68422902/107240995-d46cc180-6a2a-11eb-83d5-0afb6b9d9046.png)

Do you know how to solve that ?

**Comment by rldhont** [comment]
DO you use **choisirgeoportail** key ?

**Comment by Alain-LG** [comment]
No I have received an official key from IGN 

![image](https://user-images.githubusercontent.com/68422902/107252070-4944f900-6a35-11eb-8249-d1399a463b22.png)

**Comment by rldhont** [comment]
You have removed from the issue template some needed infos like the lizmap version. Can you provide this information ?

**Comment by Alain-LG** [comment]
- Lizmap version: 3.4.0 + web-client 3.4.1
 - QGIS Server FULL version: Lizmap Hosting
 - QGIS Desktop FULL version: LTR 3.10.12
 - OS (Windows, Linux, MacOS, Android…): server with Lizmap Hosting + Windows for users
 - Browser (Firefox, Chrome…): Firefox = OK, CHROME + EDGE = NOK

**Comment by Alain-LG** [comment]
As I need to find a solution, I have asked to IGN to modify my key with a new REFERER because I have seen that CHROME and EDGE return a "403 forbidden" error on these links.

The referer tag on these two browser are stopped on the simple URL `https://xxx.lizmap.com` and not on the complete URL `https://xxx.lizmap.com/carto/` for example.

I will try as soon as my key will be updated.

**Comment by nboisteault** [comment]
Hi @Alain-LG ,
Any feedback?

**Comment by Alain-LG** [comment]
Hello,

Yes, it's OK since a long time... I'm sorry I have forgoten to make feedback.

In conclusion, you must use the shortest URL to configure a REFERER key with these 2 browsers (CHROME ans EDGE). With FIREFOX, it's OK with the short and the long URL.
