### ISSUE TITLE
Image not publish with LIZ web map

### ISSUE THREAD

**Issue by Paruljain-sb** [3liz/lizmap-web-client#2116]
I am working QGIS Desktop version 3.1.4 and collection a field data Android mobile based application **INPUT**. The data and field Images stored in Geopackage field. Same Geopackage data has been published on LIZ web map. I have placed the Geopackage and images on FTP- FileZilla folder. I am facing an issues to publish photos in LIZ web map. Photos not visible in data field as well as  popup in LIZ.

the default path of Image which has collected from field in below snapshot.

<img width="410" alt="Image _Path" src="https://user-images.githubusercontent.com/78840494/108026270-756a0680-7041-11eb-8794-8b86d34bda37.png">

**Comment by Gustry** [comment]
In the popup documentation, there is a section how to use images : 
https://docs.lizmap.com/current/en/publish/configuration/popup.html#usage-of-media-images-documents-etc

You must use the "media" chapter.

**Comment by Paruljain-sb** [comment]
> In the popup documentation, there is a section how to use images :
> https://docs.lizmap.com/current/en/publish/configuration/popup.html#usage-of-media-images-documents-etc
> 
> You must use the "media" chapter.

Thank you. I shall create a media field rather than photo and try to publish.

**Comment by Gustry** [comment]
No, the value (not the field name) should start by `media/`. You can create a virtual field for instance adding `media` to your existing field. It will be something like `media/sdcard/INPUT/....). Then on the FTP, put the `sdcard` folder in the `media` folder.

**Comment by Paruljain-sb** [comment]
I have published the photos on web map.
Thank you
