### ISSUE TITLE
measurement result not shown on tablet

### ISSUE THREAD

**Issue by ea-refit** [3liz/lizmap-web-client#2118]
### What is the bug?
If I want to measure a distance/area/angle/perimeter with my tablet on LWC, I can't see the result. Using a computer, this problem does not exist.

### Steps to reproduce the issue

1. Open a Lizmap webmap with a tablet
2. Click on measure feature
3. Start measuring
4. See that result is missing

### Expected behavior
I expect to see the result of my measurement same as when I use my computer.

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10.14
 - OS (Windows, Linux, MacOS, Android…): IPad
 - Browser (Firefox, Chrome…): Safari
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Hosted by 3Liz

![LWC_Measure_Bug_Tablet](https://user-images.githubusercontent.com/70747853/108070739-259d3680-7065-11eb-8d97-3891d664ef6f.png)

**Comment by nboisteault** [comment]
Hi,
what is your Ipad model and screen resolution? Did you try to empty browser cache?

**Comment by ea-refit** [comment]
Hi,

our IPad model number is: A2072 (IPad Air 4th Generation). Display Resolution: | 2360x1640 (264 ppi). I also tried emptying the browser cache. That doesn't work either.

**Comment by nboisteault** [comment]
I confirm the issue. I'll fix asap.

**Comment by nboisteault** [comment]
@ea-refit do you also have popups opening/closing when clicking measurement points ?

**Comment by ea-refit** [comment]
No, we don't have popups opening/closing when clicking measurement points.

**Comment by nboisteault** [comment]
@ea-refit  Thanks for your report and feedback.
