### ISSUE TITLE
Map not Pan

### ISSUE THREAD

**Issue by Paruljain-sb** [3liz/lizmap-web-client#2122]
### What is the bug?
I have published Liz map and facing PAN issue. Data stored in Postgress server. Not able to pan the map on liz, 
attached maps not pan.

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version:3.1.4
 - QGIS Desktop FULL version:3.1.4
 - OS (Windows, Linux, MacOS, Android…): windows
<img width="960" alt="map_pan" src="https://user-images.githubusercontent.com/78840494/108198110-a840f700-7134-11eb-9059-214aaa058a55.png">
 
 - Browser (Firefox, Chrome…): chrome
 - Lizmap admin information (users, logs…) stored  PostgreSQL

**Comment by Paruljain-sb** [comment]
I have created a new project and resolved the issue

**Comment by Gustry** [comment]
You could have checked :
* Project properties -> QGIS Server tab -> Advertised Extent. This will definitely limit the pan
* Lizmap properties -> Map options -> Map extent

**Comment by Paruljain-sb** [comment]
I have created a new project and problem solved. Yesterday I closed github
ticket

Thank you for your support
