### ISSUE TITLE
Dataviz should appear only in parent layer popup

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#2123]
I'm using time series data with dataviz (water level measurements) presented with scatter plot.
The data structure is the following: parent table with monitoring points (with geometry) and child table with measurements data (without geometry). Relation is set 1:N with foreign key.
Graph shows very nice in parent's layer popup with _Display filtered plot in popups of parent layer_ selected. But the project level dataviz container is also active and renders all measured values merged from all monitoring points. Well, this representation is meaningless. Is it possible to deactivate the dataviz icon, while the popup part still work?

An alternative solution would be to create plotly plot directly in child layer's popup, but that is not dataviz anymore.

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): All
 - Browser (Firefox, Chrome…): All

**Comment by mdouchin** [comment]
There is indeed an option to show the plot only in pop-up and not in the main dock. You can see it in the plug-in interface

**Comment by aeduard** [comment]
Could you help me where to locate this option? I'm using the latest (3.4.0) plugin version.

![liz_plugin_1](https://user-images.githubusercontent.com/16295364/108350680-34165a00-71ed-11eb-9270-79c893e0b237.jpg)
![liz_plugin_2](https://user-images.githubusercontent.com/16295364/108350692-3678b400-71ed-11eb-842d-b9fb9efe05eb.jpg)

**Comment by mdouchin** [comment]
Try the "only show in child pop-up" checkbox

**Comment by aeduard** [comment]
If I check only the "only show in child popup" checkbox, than nothing appears. The child layer popup is not activated by default. If I activate, with source "auto", than just loads some rows from the child layer (as it should), but no graph.

If I activate both "Display filtered plot in popups of parent layer" and "Only show in child popup", than a constantly loading blue bar appears instead of the graph and browser fires an error in dataviz.js:168.

Uncaught TypeError: Cannot set property 'json' of undefined
    at Object.success (dataviz.js:168)
    at c (jquery-3.5.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2)
    at l (jquery-3.5.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2)

**Comment by immoblecher** [comment]
That is interesting! I can tick one of the two or both and nothing shows in a chart...the cursor is just turning, turning as if it wants to show something, but nothing comes up. I have exactly the same situation as mentioned by @aeduard with geosites displaying as points on the map and a one-to-many relationship to water levels. But the "many table" is a PostgreSQL view extracting only the water levels I want to show with an id, site_id_nr, date_time and waterlev field. My X is the date_time and my Y the waterlev. I have set up the relationships in the QGIS project as well with the site_id_nr as the common foreign key. What am I missing? Interestingly enough both tables are also set up in the Data View function, but selecting any of the two does not retrieve anything...just a turning cursor. Specs. are Linux server with QGIS server >3.0 and Lizmap 3.4.0 with data in a PostgreSQL 13. database.

**Comment by aeduard** [comment]
Few ideas I would try, well not related directly to the topic of this issue. Update lizmap, the first update had many bug fixes. In project properties / QGIS Server / Check layer to be published. In case of views (also applicable to tables) it is important to have unique IDs, missing that causes errors.
