### ISSUE TITLE
Geolocation position stays visible even if panel is closed

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#2132]
I don't really know if it's a bug or a feature, but when the Geolocation tool is activated the position (the blue circle)  stays visible on the map event if the tool has been deactivated. 

Version : lizmap 3.4.1
Browser : Firefox
OS : Ubuntu

**Comment by nboisteault** [comment]
When you say deactivated, you mean, you closed the panel or you stopped geolocation?

**Comment by nboisteault** [comment]
@arno974 gentle ping :)

**Comment by ygorigor** [comment]
@arno974 @nboisteault it cannot be a bug. 
If you have popup in mini-dock and geolocation activated, every time when you want to show a popup the geolocation will be disabled. So you will have to open geolocation tool and activate it again.
