### ISSUE TITLE
WFS link export FILTER doesn't work

### ISSUE THREAD

**Issue by AlexAtmo** [3liz/lizmap-web-client#2142]
### Description
Hello,

I have an issue concerning the exportation of data using WFS https links. I would like to filter data on a specific vector file, used in the project (the WFS option is activated in QGIS properties).

**Example:** 
I have this link where the format is a CSV, for a specific layer in my project (which works) : https://api.atmonormandie.fr/index.php/lizmap/service/?repository=dindice&project=flux_indice_atmo_normandie&SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=indice_atmo_actuel&propertyname=lib_zone,code_zone,code_qual&OUTPUTFORMAT=csv

The data table : indice_atmo_actuel
the columns wanted : lib_zone,code_zone,code_qual

Now i want to add a filter for the column "code_zone", where i only need 76540 (varchar)

I tried to modify my link according to the liz documation : 

https://api.atmonormandie.fr/index.php/lizmap/service/?repository=dindice&project=flux_indice_atmo_normandie&SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=indice_atmo_actuel&propertyname=lib_zone,code_zone,code_qua&FILTER=code_zone='76540'&OUTPUTFORMAT=csv

... But the link doesn't work, and even though I tried looking everywhere on Internet for an answer, I didn't find what I needed.

If you have some clues on this matter I'm all ears ! 

Thank you

### Environment
 - Lizmap version: 3.3
 - QGIS Desktop version: 3.16
 - OS (Windows, Linux, MacOS, Android…):  Winsows
 - Browser (Firefox, Chrome…): Chrome

**Comment by Gustry** [comment]
> Lizmap version: 3.3
> QGIS Desktop version: 3.16

I'm not answering your question, but keep in mind that there is known issue using QGIS 3.16 with LWC 3.3. Only 3.4 is fully compatible QGIS 3.16 (https://github.com/3liz/lizmap-web-client/wiki/Versions#qgis-server). In any case, you should use the same version between QGIS Server and QGIS Server.

**Comment by rldhont** [comment]
The `FILTER` parameter is defined as to be OGC Filter Encoding (XML Format).

QGIS Server has an extra parameter `EXP_FILTER` defined as an Expression filter.

Take a look at the QGIS Server documentation :
* 3.10 https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#getfeature
* 3.16 https://docs.qgis.org/3.16/en/docs/server_manual/services.html#getfeature

**Comment by AlexAtmo** [comment]
> > Lizmap version: 3.3
> > QGIS Desktop version: 3.16
> 
> I'm not answering your question, but keep in mind that there is known issue using QGIS 3.16 with LWC 3.3. Only 3.4 is fully compatible QGIS 3.16 (https://github.com/3liz/lizmap-web-client/wiki/Versions#qgis-server). In any case, you should use the same version between QGIS Server and QGIS Server.

Thank you for the advice, It seems that using the next Lizmap version is also a solution, I will keep that in mind !





> The `FILTER` parameter is defined as to be OGC Filter Encoding (XML Format).
> 
> QGIS Server has an extra parameter `EXP_FILTER` defined as an Expression filter.
> 
> Take a look at the QGIS Server documentation :
> 
> * 3.10 https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#getfeature
> * 3.16 https://docs.qgis.org/3.16/en/docs/server_manual/services.html#getfeature


It worked with &EXP_FILTER with some SQL statements, and I now understand the difference between EXP_FILTER and FILTER, so I guess this is a perfect answer to my question !

Thank you for your help et have a nice day
