### ISSUE TITLE
Table export : full fields / field filter not returned

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#2144]
Hello,
why all the variables of my table are found in the export file ?
Fields are in hidden mode and marked as 'not expose wms / wfs' ?
The user thinks of recovering the filtered rows and columns in the table, he finds himself with many columns which he does not have the use of.
this is blocking for users who end up with too many fields

Bad handling on my part? Should the fields be masked otherwise?

![attribut_wmswfs_vu_export](https://user-images.githubusercontent.com/46560615/108737515-f722ce00-7532-11eb-917b-b72faeadbf98.jpg)

Thank you for the feedback
Corinne

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version:3.4.15
 - QGIS Desktop FULL version:3.16.1
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…):Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgres

**Comment by Gustry** [comment]
> QGIS Server FULL version:3.4.15
QGIS Desktop FULL version:3.16.1

This is the problem.
QGIS Server 3.4 **can't** read the field configuration made with QGIS Desktop 3.16.
You must use the same version.
https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server

**Comment by cocro** [comment]
hello, 
OK I ask my admin to update qgis server. 
I hope to solve this question and provide a nice browsing context to my users

Thanks
Corinne
