### ISSUE TITLE
Atlas : popup all fields are visible

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#2145]
Hello,
why the popup opened by the atals does not hide the fields which have attributes "not expose to wms/wfs"
I chose to display only a few fields from my table (qgis form) and I hid all the other fields (coupled with not integrating into wms / wfs. Yet they still appear
![atlas_popup](https://user-images.githubusercontent.com/46560615/108738448-e4f55f80-7533-11eb-8f08-74c9a115f573.jpg)

Bad handling on my part ?
to get around the problem, I chose the qgis popup which almost responds to the request (1 line would be more pleasant to read)
Where can we act to make a popup

Thanks for your feedback
Corinne

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version:3.4.15
 - QGIS Desktop FULL version:3.16.1
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…):Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgres

**Comment by Gustry** [comment]
I think same issue #2144 :

> QGIS Server FULL version:3.4.15
QGIS Desktop FULL version:3.16.1

QGIS Server 3.4 **can't** read the field configuration made with QGIS Desktop 3.16.
You must use the same version.
https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server

Note, hidding the field in the `Form` tab is only used if set the popup to `QGIS` and then use the button `Copy the form drag and drop layout`.

**Comment by cocro** [comment]
hello, 
OK I ask my admin to update qgis server. 
I hope to solve this question and provide a nice browsing context to my users

Thanks
Corinne
