### ISSUE TITLE
Add Printer option

### ISSUE THREAD

**Issue by Paruljain-sb** [3liz/lizmap-web-client#2148]
How to enable a printer template option in Liz map ?
please refer the attached.

 - Lizmap version: **3.4**
 - QGIS Server FULL version:**3.1.4**
 - QGIS Desktop FULL version:**3.1.4**
 - OS (Windows, Linux, MacOS, Android…):  **Windows**
 - Browser (Firefox, Chrome…): **Chrome**
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? :- **PostgreSQL**
![image](https://user-images.githubusercontent.com/78840494/108805895-9c808500-75b9-11eb-95ce-a3bd27ffa1f4.png)

**Comment by Gustry** [comment]
https://docs.lizmap.com/current/en/publish/configuration/print.html

**Comment by Paruljain-sb** [comment]
Print option not visible on map.
