### ISSUE TITLE
Configure our css theme

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#2149]
Hello,
How to act on the css files to customize the projects by theme ?
I copied the css tree in the default folder, acted on main.css but the color # 6CC4C8 does not want to appear

![theme_css_globalLizmap](https://user-images.githubusercontent.com/46560615/108812723-efedd580-75af-11eb-8625-1c6f2e55ebbf.png)
![theme_css_main-projet](https://user-images.githubusercontent.com/46560615/108812735-f3815c80-75af-11eb-947d-09af3e5ba008.png)

Thanks for your feedback

### Environment

 
    Lizmap version: 3.4.1
    QGIS Server FULL version:3.4.15
    QGIS Desktop FULL version:3.16.1
    OS (Windows, Linux, MacOS, Android…): Windows
    Browser (Firefox, Chrome…):Firefox
    Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgres

**Comment by Gustry** [comment]
Side question, did you see ?
https://docs.lizmap.com/current/en/publish/customization/themes.html
https://docs.lizmap.com/current/fr/publish/customization/themes.html

**Comment by cocro** [comment]
Yes I followed this procedure, empty the cache with each modification in a css file and nothing helps. 
The expected blue does not appear on the screen

**Comment by cocro** [comment]
I specify that I see the blue background when downloading ... after, the map takes its place
Only the "Information menu" takes on a blue background
menu bar, navigation... remains on the default gray-black color

**Comment by cocro** [comment]
hello can you help me ?
What is the css file to modify to customize the colors of the menu blocks ? on what lines should we act ?
... main.css: default values modified by # 6CC4C8 = no effect
... map.css: bcq of default values modified by # 6CC4C8 = no effect. The gray-black color remains in the background

The lizmap cache has been emptied; the server has been restarted

We no longer know how to solve the problem ....
and say you advertise 'Create simple themes'

_admin.css: no gray-black color to send back - no modification
view.css: no gray-black color to return - no modification
embed.css: no declared color
media.css: no declared color_ 

Thanks
