### ISSUE TITLE
[Bug] projects tags not displaying in main page in master

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#2153]
### What is the bug?

This might be due to recent refactoring.

### Environment

 - Lizmap version: master

**Comment by nboisteault** [comment]
== Commit OK
cd3ec1970e118caf59314d4e6e26f6a4c7b95d3c

== Commit NOK
a74935e5fb8eabb94dc1b57d7161dbbc57649161

**Comment by nboisteault** [comment]
@laurentj Cache is not written with `keywordList` values, something is wrong somewhere around : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/lib/Project/Project.php#L236

To reproduce the issue : 

1. empty cache => `lizmap/install/clean_vartmp.sh`
2. refresh project page
3. hover Test_tags_nature_flower project => keywords are present
4. refresh project page
5. hover Test_tags_nature_flower project => keywords are not present

I think `$this->qgis->getCacheData($data)` is wrong but I don't know how to fix this. Please help.

**Comment by mdouchin** [comment]
I will look into it ASAP

**Comment by laurentj** [comment]
I will also look at this issue, after landing my patch which refactor getData calls..

**Comment by laurentj** [comment]
I found the issue after many refactoring :-)

**Comment by laurentj** [comment]
fixed
