### ISSUE TITLE
Locate by layer - Internet explorer 11 : lists open automatically at startup

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#216]

**Comment by rldhont** [comment]
Code à tester sous IE11:
```javascript
lizMap.events.on({
   'uicreated': function(evt){
      // Blur locate by layer
      $('#locate div.locate-layer select').blur();
   }
});
```

**Comment by josemvm** [comment]
hi @mdouchin and @rldhont,

i'm testing this issue on master branch but the script doesn´t fix the bug

**Comment by rldhont** [comment]
@josemvm thanks for this test. Can you test this one:
```javascript
lizMap.events.on({
   'uicreated': function(evt){
      // Blur locate by layer
      $('#locate div.locate-layer input').blur();
   }
});
```

**Comment by josemvm** [comment]
@rldhont,

the problem remains...

**Comment by rldhont** [comment]
And this one
```javascript
lizMap.events.on({
   'uicreated': function(evt){
      // Blur locate by layer
      $('#locate div.locate-layer input').autocomplete('close');
   }
});
```

**Comment by josemvm** [comment]
no...

**Comment by rldhont** [comment]
I'm sure that `$('#locate div.locate-layer input').autocomplete('close');` is the good way to programmatically close the list, but we do not have the good moment to apply it.

**Comment by rldhont** [comment]
@josemvm can you test the patch attached ?
[issue_216.txt](https://github.com/3liz/lizmap-web-client/files/586332/issue_216.txt)

**Comment by josemvm** [comment]
yes, it solve the problem but in case you have a "optional group field" option in the plugin the group box (the first combobox) appears widthout title...

**Comment by rldhont** [comment]
@josemvm does the `placeholder` attribute of the "optional group field" input is set ? Like the other one ?

**Comment by rldhont** [comment]
thanks @josemvm
