### ISSUE TITLE
L'impression "PDF" en mode atlas ne filtre pas les données

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#2165]
### What is the bug?
Lorsque l'on utilise le mode Atlas, les données peuvent être filtrées sur la carte à l'écran. On s'attend donc à avoir le même rendu à l'export au format PDF. Or, ce n'est pas le cas

### Steps to reproduce the issue
Ouvrir l'atlas des chats.
Chercher Bumbles2 car il est sur le même territoire que Pickles2.
A l'écran si on choisit de filtrer, on voit uniquement les parcours de Bumbles2
![image](https://user-images.githubusercontent.com/68422902/109171008-99d08c00-7781-11eb-9ecf-d77179d92523.png)

Mais à l'impression PDF, on a les traces de Bumbles2 et de Pickles2.
![image](https://user-images.githubusercontent.com/68422902/109170580-36465e80-7781-11eb-9dc9-0c275c58e568.png)

Le tag EXP_FILTER semble ne servir qu'à sélectionner le bon élément d'atlas et ne pas s'appliquer comme filtre de la couche.

### Expected behavior
Est-il possible d'avoir le même rendu à l'édition PDF qu'à l'écran ?

### Environment

Site web de démo de Lizmap

**Comment by Gustry** [comment]
1. Lizmap ne fait que transférer la demande de PDF à QGIS Serveur.
2. QGIS Serveur fait la même chose que QGIS Bureautique

Pour avoir ça dans QGIS Bureautique, il faut jouer avec les expressions QGIS et utiliser une règle si `$featureid != $atlasfeatureid`. Une astuce similaire, je n'ai pas QGIS devant les yeux pour tester.

Il faut donc déjà faire valider ça dans QGIS Bureautique lors de l'export de l'atlas des chats. Ensuite, ça doit suivre dans QGIS Serveur.

Donc ce n'est pas un bug de Lizmap, mais plutôt une fonctionnalité qui n'a pas été fait dans le projet chat spécifiquement.

**Comment by Alain-LG** [comment]
Merci beaucoup, je confirme que cela fonctionne très bien en passant par une symbologie définie avec une règle : 
[champ_id] = @atlas_featureid

Par exemple pour ma couche dossier où mon champ identifiant est "gid" :
![image](https://user-images.githubusercontent.com/68422902/109291635-7cef9380-7829-11eb-9f2d-862c2aa68a65.png)

NB : je ne voulais pas mettre le tag "BUG" mais plutôt "QUESTION", il faut que je fasse attention. On n'oublie parfois d'aller chercher la solution à la source et on incrimine un peu trop facilement LizMap par erreur. Désolé.

**Comment by Gustry** [comment]
> NB : je ne voulais pas mettre le tag "BUG" mais plutôt "QUESTION", il faut que je fasse attention. On n'oublie parfois d'aller chercher la solution à la source et on incrimine un peu trop facilement LizMap par erreur. Désolé.

Il n'y a pas de soucis.

On est conscient que ce n'est pas toujours facile de savoir le lien entre QGIS Desktop, QGIS Serveur et Lizmap, et qui fait quoi la dedans ;-)
