### ISSUE TITLE
Export tool - Add right to protect this feature

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#217]
The idea is to display the Export tools only for chosen groups of users

**Comment by mdouchin** [comment]
And/Or add an option to allow export for each layer individually ?

**Comment by rldhont** [comment]
Done

**Comment by Cww7** [comment]
Hello,

is it possible to modify the export rights for each layer ?

**Comment by gioman** [comment]
@rldhont @mdouchin sorry for hijacking this old ticket, but I can't find the associated commit.

So... we can protect globally the download in the LMWC backoffice, as part of the fundamental permissions of a repo, what what about a per layer config? I can't find an obvious way to do that (and for example a "groups allowed" list as it happens for other configs in LM plugin. Was this implemented or is still to be done? Notice that the same would apply to "attribute table", in a way similar to the layers editing, where is possible to specify which groups are allowed to edit a specific layer.

**Comment by Gustry** [comment]
> The idea is to display the Export tools only for chosen groups of users

It has been done, at the "repository" level.

Nothing at the layer/project level.

**Comment by gioman** [comment]
> Nothing at the layer/project level.

@Gustry thanks for the feedback, I'll be interested in having this implemented first at layer level (for both the download function in the pop up and also for attributes table) and then maybe at a project level (so globally for all layers and all published tables within one project). Ping me if you think this is an interesting feature to add.
