### ISSUE TITLE
"Error 500"

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-web-client#218]
Hello everyone,

I was wondering if you can help me in this: 

In lizmap browser, when I click on a point, opens a window with a picture and when I click again on the image to make the download the same , the following error appears:

"Error 500. A technical error has occurred. Sorry for this trouble."

It's happened to somebody else ?

Thank you for your help.

I use mozilla firefox latest version at US EN and google chrome

Orlando

![html_function](https://cloud.githubusercontent.com/assets/15649016/10936119/6b85c0a2-82e2-11e5-8b54-8232e832bcfe.png)

**Comment by gioman** [comment]
@opbernardo  what your apache/php logs say?

**Comment by opbernardo** [comment]
In the apache/logs/error these messages appear:

[Wed Nov 04 17:24:44 2015] [notice] Apache/2.2.14 (Win32) mod_fcgid/2.3.6 configured -- resuming normal operations
[Wed Nov 04 17:24:44 2015] [notice] Server built: Sep 28 2009 22:41:08
[Wed Nov 04 17:24:44 2015] [notice] Parent: Created child process 4768
[Wed Nov 04 17:24:44 2015] [notice] Child 4768: Child process is running
[Wed Nov 04 17:24:44 2015] [notice] Child 4768: Acquired the start mutex.
[Wed Nov 04 17:24:44 2015] [notice] Child 4768: Starting 64 worker threads.
[Wed Nov 04 17:24:44 2015] [notice] Child 4768: Starting thread to listen on port 80.

I do not know if I'll be seeing in the right place ...

Thank you for your help.

**Comment by gioman** [comment]
@opbernardo probably not, anyway I would personally try also run the stack on Linux and see if you get the same issue.

**Comment by rldhont** [comment]
The problem is not in apache or qgis. It's in popup lizmap.

In the exemple @opbernardo wrote some popup template:
```html
  <p>
  <a href="media/.."><img src="media/.."/></a>
  </p>
  <p>
  <a href="media/..">aMedia</a>
  </p>
```

And the problème is in the interpretation of the links.

@opbernardo can you give us how the href have been interpreted ? Does it change in the web page ?

**Comment by gioman** [comment]
> The problem is not in apache or qgis. It's in popup lizmap.

@rldhont of course, but if logged the error could give some pointer. The snippet does not seems wrong, but maybe I recall the wrong way.

**Comment by rldhont** [comment]
Hi @opbernardo,

To help you can you give us those information:
* did you define the popup content with popup template in lizmap Plugin ?
* did you use an html property with an html file in media ?

**Comment by opbernardo** [comment]
Hello,

I apologize because I do not know if I understand your question ... I am a
novice in these wanderings, I could only get here through many attempts ...

I send you some pictures of the procedures that I made by following the
instructions "Documentation Lizmap 2.10" on the internet

Thanks a lot for your help.

Orlando




2015-11-05 13:32 GMT+00:00 rldhont <notifications@github.com>:

**Comment by rldhont** [comment]
Did you use:
* Simple popup configuration http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#simple-popup-configuration
* Advanced popup configuration - HTML format http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#advanced-popup-configuration-html-format

Where did you put the HTML ?
* in a file stored in a media directory ?
* in an attribute layer ?
* in the lizmap configuration ?

**Comment by opbernardo** [comment]
Hello,

I used the three hypotheses and in both same error ...

Sending a few more pictures to you get an idea of how I set up my project
Qgis and Lizmap.

I apologize for my, almost no programming skills...

I used the simple popup configuration and the advanced popup configuration.


Thank you very much for your help.

Orlando




2015-11-05 17:27 GMT+00:00 rldhont <notifications@github.com>:

**Comment by rldhont** [comment]
Hi @opbernardo, it's not really an issue. If you use HTML in a file, you have to write complete link.

This mean that in you html files, you have to update the href and src attribute to the complete link : http://foo/bar/getMedia?path=media/path/to/file

It's better to move the HTML file content to the lizmap plugin configuration.

**Comment by opbernardo** [comment]
Hello again,

Thank you very much for the help.

But putting the html file in the lizmap popup he always opens the same file
... is there a way to openthe various different files?

Beste regards.

Orlando

2015-11-06 11:20 GMT+00:00 rldhont <notifications@github.com>:

**Comment by rldhont** [comment]
Change the link to complete ones. (start with http)

**Comment by Abelon38** [comment]
Hi guys!

My problem related Media is that Pictures stop showing up after changed port on apache from 80 to 8080. I tried to make some changes on file popup.class.php but doesnt work. I will appreciate any suggestion?
Thanks for your time!
Abel
