### ISSUE TITLE
Procedure to display images in popups with qgis source

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#2184]
### Description
My popups are created usually with lizmap source and images are displayed as expected according to the documentation. I'm experimenting with qgis source (created in Display/map tip), but I can't manage to display images. Browser throws 404 Not Found error.

Simple cod similar to the example from the [documentation](https://docs.lizmap.com/3.4/en/publish/configuration/popup.html#usage-of-media-and-external-links):

lizmap source **works**:
`<img src="{$image_column}" style="">` 
Inspecting src generated by browser after site address, it has getMedia? element together with repository and project names than path to file.

qgis source **404 error**:
`<img src=[% "image_column" %] style="">` 
Inspecting src generated by browser it has the following address: https_webserver/lizmap/index.php/view/map/ than exactly how it is defined in image_column id database table, meaning media/upload/.../*.png

### Environment

 - Lizmap version: 3.4.1
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): Any
 - Browser (Firefox, Chrome…): Any

**Comment by Vermeil-M** [comment]
Hi,
You can test this formulation : 
[% concat('<img src="', "image_column", '"style="">') %]

**Comment by aeduard** [comment]
Thank you, it worked that way!
