### ISSUE TITLE
edition - the edition form does not open

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2186]
hi

it is not possible to open the edition form...

![imagem](https://user-images.githubusercontent.com/10053874/110136556-ba26c900-7dc7-11eb-96f0-74a1dd291ac5.png)

lizmap logs:

```
2021-03-05 16:26:50	xxx.xxx.xxx.xxx	error	2021-03-05 16:26:50	[830]	 The control "imagem_choice" doesn't exist in the form "view~edition" (template view~edition_form_container)	/var/www/html/lizmap-web-client-release_3_3/lib/jelix/plugins/tpl/html/function.ctrl_label.php	32
```
thanks for your attention

 - Lizmap version: 3.3.14 (today)
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by mdouchin** [comment]
did you delete the field "imagem" ?

**Comment by josemvm** [comment]
hi @mdouchin 

it was a issue with rights on the upload folder "imagem"

thanks for your attention :-)
