### ISSUE TITLE
time manager - not working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2187]
hi

the time manager tool doesn´t work on lizmap 3.4.2. the engine/time line works but the features doesn´t appear on the map.

ps: by the way, the plugin lost the `label` parameter...

thanks

 - Lizmap version: 3.4.2
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14

**Comment by pcav** [comment]
I also have the same issue, please have a look to the thread on the mailing list 26/02/21

**Comment by josemvm** [comment]
hi @pcav 
thanks

https://github.com/3liz/lizmap-web-client/issues/1941
