### ISSUE TITLE
editon form - editing an existing feature

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2190]
hi

when a user tries to edit an existing feature the edit form closes immediately!...
Is this behavior intentional or not?

thanks

 - Lizmap version: 3.4.2
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14

**Comment by rldhont** [comment]
Is the form still available ?

**Comment by josemvm** [comment]
@rldhont yes, the user needs to ckick on edition icon (again)

**Comment by josemvm** [comment]
thanks @nboisteault
