### ISSUE TITLE
Projects page : it takes too much memory

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#2191]
### What is the bug?

When there is many projects to display, PHP can crash because of lack of memory.

This is because Lizmap loads all projects files whether from files or from the cache. So it can eat rapidely all the memory.

### Expected behavior

No crash because of lack of memory when displaying the projects list

### Proposition

For the project list, there should be a loop that reads projects one after the other. For each project, it should extract only informations needed for the display, and it should release the project object or any other variables that contain project data, in order to not eat more memory at each item.

**Comment by Gustry** [comment]
Can we make a list of things which are read by the landing page in the QGS XML ?

Maybe, we should : 
* As Laurent said, improve the parser and memory management
* Move some info in the CFG ?
* Move some info in the Lizmap server API ?

**Comment by mdouchin** [comment]
The QGIS Xml project must be read. There no way around, as soon as we do not deport all this information reading to the Python lizmap plugin (server part).

We already have tried to limit the time of XML parsing for editing and attribute tables, see 5f36cf19e68d6512acba9faee5154e71480202c4

**Comment by mdouchin** [comment]
I can have a look this morning asap

**Comment by mdouchin** [comment]
I am on it !
