### ISSUE TITLE
update project to new version of lizmap 

### ISSUE THREAD

**Issue by remichairat** [3liz/lizmap-web-client#2195]
Hello i have made an update of all my installation of lizmap : lizmap webclient 3.4 qgis server 3.16 and i have to migrate older project to new version of lizmap and qgis.
But on the updated project i have a bug when i want to add a new table,  i have a server error : GetCapabilities result code: 500

### Screenshots and logs

![image](https://user-images.githubusercontent.com/27948553/111142672-38802980-8585-11eb-87f2-9a24ea1ec974.png)

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Windows 
 - Browser (Firefox, Chrome…): firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Gustry** [comment]
>  i have a server error : GetCapabilities result code: 500

So you must check your server logs. You will find some errors there. QGIS Server logs.

**Comment by remichairat** [comment]
hello gustry you can see the log server error 

crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:23 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=getcapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"
crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:23 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=getcapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"
crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:23 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"
crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:23 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"
crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:24 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=getcapabilities&service=WFS&version=1%2E0%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"
crige-lizmap-v2.ataraxie.fr:80 127.0.0.1 - - [12/Mar/2021:10:50:24 +0100] "GET /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F04%2Fprojet%5Fdesserte%5Flizmap%2Eqgs&request=getcapabilities&service=WFS&version=1%2E0%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1 HTTP/1.1" 500 239 "-" "Lizmap"

**Comment by Gustry** [comment]
All errors are the same.
Which version of Lizmap plugin on the server ?
You would need to increase your debug output on QGIS Server to have more detailed issue about the 500 issue I guess.

**Comment by remichairat** [comment]
lizmap version is 3.4.1

**Comment by remichairat** [comment]
log of qgis server : 
14:37:43 INFO Server[13928]: ******************** New request ***************
14:37:43 INFO Server[13928]: Request URL: http://127.0.0.1:8080/cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte_84%2Fdesserte_                                                                               84_lizmap.qgs&request=getcapabilities&service=WMS&version=1.3.0&Lizmap_User=admin&Lizmap_User_Groups=__priv_admin%2C admins&Lizmap_Override_Filter=1
14:37:43 INFO Server[13928]: Environment:
14:37:43 INFO Server[13928]: ------------------------------------------------
14:37:43 INFO Server[13928]: SERVER_NAME: 127.0.0.1
14:37:43 INFO Server[13928]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F84%2Fdesserte%5F84%5Flizmap%2Eqgs                                                                               &request=getcapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1
14:37:43 INFO Server[13928]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
14:37:43 INFO Server[13928]: REMOTE_ADDR: 127.0.0.1
14:37:43 INFO Server[13928]: SERVER_PORT: 8080
14:37:43 INFO Server[13928]: QUERY_STRING: map=%2Fhome%2Fdata%2Fftp%2Frchairat%2Fqgis%2Fdesserte%5F84%2Fdesserte%5F84%5Flizmap%2Eqgs&request=getcapabilities&s                                                                               ervice=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1
14:37:43 INFO Server[13928]: REQUEST_METHOD: GET
14:37:43 INFO Server[13928]: HTTP_ACCEPT: */*
14:37:43 INFO Server[13928]: HTTP_USER_AGENT: Lizmap
14:37:43 INFO Server[13928]: LIZMAP_OVERRIDE_FILTER:1
14:37:43 INFO Server[13928]: LIZMAP_USER:admin
14:37:43 INFO Server[13928]: LIZMAP_USER_GROUPS:__priv_admin, admins
14:37:43 INFO Server[13928]: MAP:/home/data/ftp/rchairat/qgis/desserte_84/desserte_84_lizmap.qgs
14:37:43 INFO Server[13928]: REQUEST:getcapabilities
14:37:43 INFO Server[13928]: SERVICE:WMS
14:37:43 INFO Server[13928]: VERSION:1.3.0
14:37:43 WARNING OGR[13928]: Cannot open /home/data/ftp/rchairat/qgis/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D084_2019-06-20/BDTOPO/1_DONNEES_LIVRAISON_2019-06-0036                                                                               1/BDT_3-0_SHP_LAMB93_D084-ED2019-06-20/TRANSPORT/POINT_DE_REPERE.shp.()
14:37:43 WARNING WMS[13928]: Download of capabilities failed: SSL handshake failed
14:37:43 CRITICAL Server[13928]: Error, Layer(s) POINT_DE_REPERE_e3139731_a56b_4005_a684_8285893a1709, Plan_IGN_v2_7fc03886_044b_478a_b7a1_be57852dd099, ajout                                                                               _lineaire_b2285f3b_ad79_48c4_b869_7ff92be1d964, commune_84_4255bacb_b644_4bec_a30b_b4745347f43a, correction_67084dc7_0e61_44aa_a03f_ab9e179e1727, dept_region_                                                                               paca_bdtopo_e01710ef_c778_4fd1_b3b2_a98221e2a643, desserte_84_fa0d0e67_9b99_430e_b851_6709d8688190, etat_lieu_50b18102_7491_41c1_a2dd_da1f0b4ca0d1, limit_tonn                                                                               age_gabarit_84_0f1b2b44_d6bf_400c_8ec2_9a23e5ee602f, massif_forestier_84_f7cb6bf2_e963_4827_81cf_e0975f264d7b, ouvrage_art_84_attrib_utf8_a1d3eabf_361c_44fd_9                                                                               4cf_108ca556712f, reseau_routier_princip_84_9c577928_bbdf_4733_9b3a_2f7a318a976a, signalement_ce84c40c_099e_49d8_be1b_9b3123fc1ea7 not valid in project /home/                                                                               data/ftp/rchairat/qgis/desserte_84/desserte_84_lizmap.qgs
14:37:43 WARNING Server[13928]: <ServerException>Layer(s) not valid</ServerException>

14:37:43 INFO Server[13928]: Request finished in 286 ms

after search on differents forum i think my problem is connexion to my postgresql/postgis base. i have try to config pgservice file but my connection to my base don't function

**Comment by Gustry** [comment]
Postgresql and also shapefile : 

```
14:37:43 WARNING OGR[13928]: Cannot open /home/data/ftp/rchairat/qgis/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D084_2019-06-20/BDTOPO/1_DONNEES_LIVRAISON_2019-06-0036 1/BDT_3-0_SHP_LAMB93_D084-ED2019-06-20/TRANSPORT/POINT_DE_REPERE.shp.()
14:37:43 WARNING WMS[13928]: Download of capabilities failed: SSL handshake failed
14:37:43 CRITICAL Server[13928]: Error, Layer(s) POINT_DE_REPERE_e3139731_a56b_4005_a684_8285893a1709, Plan_IGN_v2_7fc03886_044b_478a_b7a1_be57852dd099, ajout lineaire_b2285f3b_ad79_48c4_b869_7ff92be1d964, commune_84_4255bacb_b644_4bec_a30b_b4745347f43a, correction_67084dc7_0e61_44aa_a03f_ab9e179e1727, dept_region paca_bdtopo_e01710ef_c778_4fd1_b3b2_a98221e2a643, desserte_84_fa0d0e67_9b99_430e_b851_6709d8688190, etat_lieu_50b18102_7491_41c1_a2dd_da1f0b4ca0d1, limit_tonn age_gabarit_84_0f1b2b44_d6bf_400c_8ec2_9a23e5ee602f, massif_forestier_84_f7cb6bf2_e963_4827_81cf_e0975f264d7b, ouvrage_art_84_attrib_utf8_a1d3eabf_361c_44fd_9 4cf_108ca556712f, reseau_routier_princip_84_9c577928_bbdf_4733_9b3a_2f7a318a976a, signalement_ce84c40c_099e_49d8_be1b_9b3123fc1ea7 not valid in project /home/ data/ftp/rchairat/qgis/desserte_84/desserte_84_lizmap.qgs
14:37:43 WARNING Server[13928]: Layer(s) not valid
```

**Comment by remichairat** [comment]
exact sorry i have delete this shpfile  after my copy / past on github. all my data on my project are on postgresql this shp file is an error
