### ISSUE TITLE
Problem editing with lizmap 3.4.2 (the editing form is closed by default)

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#2202]
Editing a feature the editing form is closed by default. 

When the "create element" is selected in the lizmap plugin user may open the form manually otherwise it is  impossible. 

![lizmap_problem_editing1](https://user-images.githubusercontent.com/4061154/111595142-1af0d100-87cc-11eb-88ce-6bbde1147210.gif)
 

Environment information:
 - Lizmap version: 3.4.2 
 - QGIS Server FULL version: 3.16.4
 - QGIS Desktop FULL version: 3.16.4
 - Server OS : Linux (Ubuntu server 18.04) 
 - Browser: tested on Firefox and Vivaldi
 - Lizmap admin information stored into PostgreSQL

**Comment by Gustry** [comment]
Duplicate of https://github.com/3liz/lizmap-web-client/issues/2190 ?

**Comment by rmarzocchi84** [comment]
Yes it seems duplicated. Solved and available in the next 3.4.3?

**Comment by rmarzocchi84** [comment]
Sorry I check only the open issues (not the closed). I close this issue
