### ISSUE TITLE
Update sequence when migrating logs from sqlite to postgresql

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#2204]
### What is the bug?

`log_detail_id_seq` and `log_counter_id_seq` don't have their 'current value' updated when migrating sqlite logs to postgresql.
Logs can not be written and there are in messages.log : 
```
Error while inserting a new line in log_detail :Erreur dans la requête (ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « log_detail_pkey »
DETAIL:  La clé « (id)=(1439) » existe déjà.(INSERT INTO "log_detail" (
"log_key","log_timestamp","log_user","log_content","log_repository","log_project","log_ip"
) VALUES (
'login', current_timestamp, 'username', NULL, NULL, NULL, NULL
)))
```

Something like that should be added in script : 
`SELECT setval('"monschema"."test_id_seq"', (SELECT max(id) FROM monschema.test));`

### Environment

 - Lizmap version: tested with 3.4.1 but 3.3.x may have the same behavior

**Comment by laurentj** [comment]
Fixed
