### ISSUE TITLE
MAJ des fonds IGN

### ISSUE THREAD

**Issue by brulien** [3liz/lizmap-web-client#2206]
Bonjour,

Le fond IGN plan ne fonctionne plus.

Depuis le 1er janvier le fond IGN plan est passé en V2, et Lizmap semble fait appel toujours à l'ancienne version  :
Ressource appelée par Lizmap (obsolète) : GEOGRAPHICALGRIDSYSTEMS.PLANIGN
Nouvelle ressource : GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2

Liste des services IGN : https://geoservices.ign.fr/ressources_documentaires/Espace_documentaire/Bouquets_de_ressources_Geoservices_IGN.pdf

Attention la documentation suivante n'est pas à jour : https://geoservices.ign.fr/documentation/donnees-ressources-wmts.html

**Comment by nboisteault** [comment]
Bonjour,
Quelle clé IGN utilisez-vous ?

**Comment by brulien** [comment]
Bonjour,

j'ai testé plusieurs clés, notamment choisirgeoportail et une clé personnalisée avec referer.

Cdlt
