### ISSUE TITLE
Project Test Filter_layer_by_user

### ISSUE THREAD

**Issue by drillinP** [3liz/lizmap-web-client#2210]
I test the project filter_layer_by_user on 3.4.3-pre but with any type of connection (admin, user, anonymous) I see all data in the map.

**Comment by rldhont** [comment]
@drillinP which QGIS Server version ?

**Comment by drillinP** [comment]
@rldhont version 3.10.11 of QGIS Server is used in the test stack

**Comment by drillinP** [comment]
Tested with version 3.10.14 of QGIS Server and it's ok !
