### ISSUE TITLE
Locate by Layer with a layer Custom CRS working wrong

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#222]
Hi,

All my layers are in SRID 23030 (ED50 / UTM zone 30N). 

When lizmap reprojects these layers to 3857 to fit the features above google maps (satellite, streets or hybrid) there is aprox. 2 meter error. See next picture:

![image](https://cloud.githubusercontent.com/assets/12136796/11090848/c9b8b34e-8875-11e5-8d87-66082db7d998.png)

The end of the line appointed should be nearly in the center of the circle (the plaza in google streets).

Ok to fix this deviation, I have to use a Custom CRS and use a grillaje downloaded from National Geographic Institute of Spain.
I followed this guide to create a custom CRS in QGIS: 
http://icvficheros.icv.gva.es/ICV/geova/erva/Utilidades/INSTRUCCIONES_ETRS89/Cambio%20de%20Sistema%20de%20REFERENCIA%20con%20software%20QGIS_v2.2.0_V_W2.pdf

Using this Custom CRS the features are displyed perfectly:

![image](https://cloud.githubusercontent.com/assets/12136796/11091143/0454effc-8878-11e5-9066-444524b6e200.png)

Note with the previous image that the features are now a little bit displaced. It's not much but in reallity it it equals to 2 or 3 meter error. With this custom CRS I can fix this deviation problem.

The problem comes when I assing this custom CRS to the layer being used in the "Locate by Layer" tool. The geometry being displayed if the CRS of the layer is 23030 (with 2 meters error) is in this case (portal: Martikoena Street 2 A):

![image](https://cloud.githubusercontent.com/assets/12136796/11091231/c7dcd0b6-8878-11e5-9e34-6b2c7ca98b8c.png)

If I assign to the layer the custom CRS to fix the 2 meter deviation, the portal should be 2 or 3 meters next to the previous yellow circle but it appears far far away always, sometimes with 100 meters deviation and others even in other countries...

I think that there is some kind of problem with custom CRSs and Locate by Layer tool.

**Comment by gioman** [comment]
> I followed this guide to create a custom CRS in QGIS:

use this plugin http://plugins.qgis.org/plugins/ntv2_transformations/ (https://github.com/NaturalGIS/ntv2_transformations) to easily transform your ED50 data into ETRS89. Add the resulting layers (that now have the ETRS89 CRS) in your project and you should not have issue.

**Comment by jaitor1** [comment]
Hi @gioman, thanks for your answer. 

The problem is that the layers are stored in postgis and for the moment need to be in ED50 as they are being edited using AutoCAD Map and other projects with more data in ED50...

We have plans to transform all the layers (more than 1000) to ETRS89 soon...

Regards

**Comment by rldhont** [comment]
Did you find a solution ?
Can we have access to this map ?

**Comment by jaitor1** [comment]
Hi,

You can check in this map:

http://eudala2.getxo.eus/lizmap/lizmap-web-client-master/lizmap/www/index.php/view/map/?repository=callejeronuevo&project=callejero_portalero_new

There are only 3 layers published (although you see more layers).

The first two layers in the layers panels and the layer using the Locate by Layer option. The layer in locate by layer, has the same data (town portals) than the layer Portales getxo, that you can see in the layer's panel. 

The difference is that the locate by layer's layer has the custom SRID that uses the grijalle and the others are in 23030. If you find one of the portal in the map, the map goes far away, sometimes to other towns...

Regards,

**Comment by rldhont** [comment]
Thanks for this, did you test it in version 3.0 ?

**Comment by jaitor1** [comment]
No, I am using Lizmap 2.12.3

**Comment by rldhont** [comment]
Firstly, can you update to Lizmap 2.12.6

Secondly, I have probably found the problem. For USER CRS, Lizmap reads the CRS proj4 definition in the QGIS Project and uses Proj4JS to transform geometries. In your case the proj4 definition can't be used by Proj4JS because it used a path to a gsd file for the nadgrids.

Can you use a more standardize CRS, that Proj4JS can interpret ?

**Comment by rldhont** [comment]
You can take a look at this Proj4JS issue https://github.com/proj4js/proj4js/issues/62

**Comment by jaitor1** [comment]
I am transforming all my layers from 23030 to 25830. I will take me some time but it will avoid me this kind of issues in thw future.

**Comment by rldhont** [comment]
I close this issue, reopen if needed. Thanks for your feedback
