### ISSUE TITLE
Install issue  / postgresql _ jacl12db 

### ISSUE THREAD

**Issue by Batpes** [3liz/lizmap-web-client#2220]
Hi Everyone
 - Lizmap version:  lizmap-web-client-3.4.3 
 - OSGEO 4W 3.16
 - Apache 2.4.46 Win64
 - Windows
 - Chrome
 - Installation de PostgreSQL/PostGis

I have a issue with the installation of Lizmap. I'm tring to follow this document " https://docs.lizmap.com/current/fr/install/windows.html " but at the step to install lizmap bellow

REM Production Lizmap
cd C:\webserver\lizmap\prod\release_3_3\
php lizmap\install\installer.php 

I have this issue and this result with cmd

![lizmap_1](https://user-images.githubusercontent.com/81574428/112852629-6482cb00-90ac-11eb-83e8-fbdaff530f6c.JPG)

Do you know where i need to focus ? I can transfert information if useful:
htppd 
httpd-vhosts.conf
php 

Many thanks
Beginner in Lizmap

**Comment by gerald2545** [comment]
It seems the postgresql extension is not activated in PHP. Have a look in https://stackoverflow.com/questions/6518694/configure-php-and-postgresql-on-windows/6519127
