### ISSUE TITLE
Demo projects are not working on LMWC 3.4.3

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2222]
Tested an installation of LMWC 3.4.3 on a Ubuntu server 20.04 (with Apache) and noticed that adding as usual
```

[modules]
lizmap.installparam=demo
```

in `localconfig.ini.php`

do not triggers the demo projects to show up after completing the installation.

**Comment by Gustry** [comment]
Is this issue still valid @gioman ?

I have demo project working for me.

**Comment by gioman** [comment]
> I have demo project working for me.

as far as I know, yes (not on docker installs anyway).

**Comment by Gustry** [comment]
I have noticed https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#test

I made a PR, waiting for review from my colleague.
