### ISSUE TITLE
Lizmap 3.4.x with QGIS-Server 2.18.28 ?

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#2227]
### Description

Is it better to use Lizmap 3.3 instead of Lizmap 3.4 for QGIS Server 2.18?
(Is there an info page with the differences between Lizmap 3.3 and 3.4?)

In the version overview it says that Lizmap 3.4 is also for QGIS server 2.18.
However, I observe that some things (legend and info window) work better with Lizmap 3.3.x and QGIS Server 2.18 than with Lizmap 3.4.  Or are these small bugs in 3.4?

QGIS server 2.18.28 with Lizmap 3.4.3 [1]:
![grafik](https://user-images.githubusercontent.com/8373176/113409134-f3dff500-93b0-11eb-851a-9cfd0f73e972.png)

QGIS server 2.18.28 with Lizmap 3.3.15 [2]:
![grafik](https://user-images.githubusercontent.com/8373176/113409181-078b5b80-93b1-11eb-9079-17518faf933b.png)

By the way, with QGIS server 3.16.5 and Lizmap 3.4.3 it looks like this [3]:
![grafik](https://user-images.githubusercontent.com/8373176/113409198-1114c380-93b1-11eb-99ab-2bde4b9cbe6d.png)

![grafik](https://user-images.githubusercontent.com/8373176/113410077-e0358e00-93b2-11eb-9b53-acf98e5a5559.png)

[1] https://test61.webgis.biz
[2] https://brw18.wyhl.webgis.biz
[3] https://test62.webgis.biz

Translated with www.DeepL.com/Translator (free version)

### Environment

 - Lizmap version: 
 - QGIS Server FULL version: 2.18.28
 - QGIS Desktop FULL version: 2.18.28
 - OS (Windows-Desktop): Win10 64bit    Server Ubuntu 18.04 LTS
 - Browser (Firefox, Chrome…): Firefox, Chrome, Opera
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by nboisteault** [comment]
Hi,
Its is better to use Lizmap 3.3.x with QGIS 2.18 and Lizmap 3.4.x with QGIS 3.10 as they have been more tested together.

**Comment by Gustry** [comment]
The Lizmap plugin for QGIS Desktop on QGIS 2 didn't get **any** update since April 2019 and therefore, before the LWC 3.4 development started.
So no test have been done with QGIS 2 and LWC 3.4.

I have updated the wikipage : https://github.com/3liz/lizmap-web-client/wiki/Versions#qgis-server-and-desktop
Were you talking about this page ?

**Comment by guenterw** [comment]
Thanks for the feedback and for adjusting the version history. Yes - I meant this document.

 

The question for me was whether the missing legend image should be called a bug or an unsupported feature in Lizmap client 3.4 with QGIS server 2.18.

I think the latter and have changed all my projects with QGIS server 2.18 to Lizmap 3.3.15.

 

Remains the suggestion that the info window in LM 3.3.15 with QGIS server 2.18 displays better than in the 3.4.3 with QGIS server 3.16.5.

 

Should I close the issue?

 

 

Translated with www.DeepL.com/Translator (free version)

 

Von: Étienne Trimaille ***@***.***> 
Gesendet: Montag, 12. April 2021 05:44
An: 3liz/lizmap-web-client ***@***.***>
Cc: guenterw ***@***.***>; Author ***@***.***>
Betreff: Re: [3liz/lizmap-web-client] Lizmap 3.4.x with QGIS-Server 2.18.28 ? (#2227)

 

The Lizmap plugin for QGIS Desktop on QGIS 2 didn't get any update since April 2019 and therefore, before the LWC 3.4 development started.
So no test have been done with QGIS 2 and LWC 3.4.

I have updated the wikipage : https://github.com/3liz/lizmap-web-client/wiki/Versions#qgis-server-and-desktop
Were you talking about this page ?

**Comment by nboisteault** [comment]
@guenterw Could you open another ticket with a small Lizmap project illustrating the bug to help us debug it?

**Comment by guenterw** [comment]
I can do that with pleasure in the next days

 

Von: Nicolas Boisteault ***@***.***> 
Gesendet: Montag, 12. April 2021 09:04
An: 3liz/lizmap-web-client ***@***.***>
Cc: guenterw ***@***.***>; Mention ***@***.***>
Betreff: Re: [3liz/lizmap-web-client] Lizmap 3.4.x with QGIS-Server 2.18.28 ? (#2227)

 

@guenterw <https://github.com/guenterw>  Could you open another ticket with a small Lizmap project illustrating the bug to help us debug it?

**Comment by guenterw** [comment]
Here are the sample projects with the corresponding data as ZIP file [1].

QGIS-Server 2.18.28 with Lizmap 3.3.15 [2]
![grafik](https://user-images.githubusercontent.com/8373176/115995945-a173ac00-a5dd-11eb-96b4-d30554ea650d.png)

QGIS-Server 2.18.28 with Lizmap 3.4.3 [3]
![grafik](https://user-images.githubusercontent.com/8373176/115996003-e697de00-a5dd-11eb-9f59-8e87d8ca88d0.png)

QGIS-Server 3.16.6 with Lizmap 3.3.15 [4]
![grafik](https://user-images.githubusercontent.com/8373176/115996068-22cb3e80-a5de-11eb-819b-cb029f0fcbae.png)

QGIS-Server 3.16.6 with Lizmap 3.4.3 [5]
![grafik](https://user-images.githubusercontent.com/8373176/115996162-78075000-a5de-11eb-8b45-305c5a25c120.png)


Lizmap 3.4.3 for QGIS server 2.18 is probably not needed anymore.
But it would be nice if under QGIS-Server 3.16 the size of the info window in Lizmap 3.4.3 would be the same as in Lizmap 3.3.15

I hope the example helps.

[1] https://wagner-it.de/download/lizmap/lizmap.zip
[2] https://test218-lm33.webgis.biz
[3] https://test218-lm34.webgis.biz
[4] https://test33.webgis.biz
[5] https://test62.webgis.biz
