### ISSUE TITLE
Is it possible somehow to assing two key fields for a dropdown?

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#224]
This is not and issue, it is just a question. Feel free to close it if you think that should not be here.

I have this table. For each description, there are two key fields and not only one.

![image](https://cloud.githubusercontent.com/assets/12136796/11178539/c57d0772-8c4d-11e5-8919-ec1308d4bf28.png)

Is there any way of selection one description in the dropdown but internally saving the two key fields?
Currently I can only assign one key field:
![image](https://cloud.githubusercontent.com/assets/12136796/11178606/2078e24a-8c4e-11e5-93bc-dd5dde16ed34.png)

**Comment by nboisteault** [comment]
It is not something that can be handled easily from frontend. To do this you can use triggers in SQL databases.

**Comment by rldhont** [comment]
Hi @jaitor1, did you test it with a virtual field ?
It will be an interesting solution for this feature.

**Comment by jaitor1** [comment]
@rldhont  I din't test it with a virtual field what do you suggest exactly?

**Comment by rldhont** [comment]
I have not well understand your question. As @nboisteault said it, you can easily do it with a trigger in the database.

**Comment by jaitor1** [comment]
Yes, I finally created a new unique id field. 
I close the question.
Thanks!
