### ISSUE TITLE
New config parameter to enable metrics - Error 500. A technical error has occured. Sorry for this trouble

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2249]
after this commit https://github.com/3liz/lizmap-web-client/commit/c3b6c66d325504cc36cb5992296d8e6daa66602c it's not possible to access lizmap administration

lizmap log:
```2021-04-21 18:40:19	xxx.xxx.xxx.xxx.xxx	error	2021-04-21 18:40:19	[0]	Cannot access private property lizmapServices::$metricsEnabled	/var/www/html/liz-pub/lizmap/modules/admin/controllers/config.classic.php	51```

config.classic.php	51
```                  $form->setData($ser, $services->{$ser});```

thanks

 - Lizmap version: 3.3.13
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14

**Comment by josemvm** [comment]
the same problem with a clean install

**Comment by Gustry** [comment]
CC @laurentj because you are the author of the commit

**Comment by laurentj** [comment]
Fixed. Thanks for your report
