### ISSUE TITLE
Layer (tables) relations in lizmap not displayed

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#225]
Hi,

I've got a layer with streetlights (points). 

For each streetlight I have other elements (data tables, with no geoemtries) that are linked to each streetlight by a foreign key. These elements are: lamps, brackets, electric line other components, etc. (1 to N relationship for each data table).

When clicking on on streetlight, I wanted to see which lamps are in there, which lines, which componentes, etc. So I followed this guide and achieved what i wanted with a first layer in QGIS:

http://blog.vitu.ch/10112013-1201/qgis-relations

Automatically, mi form when clicking over a stretlight now it is like this:

![image](https://cloud.githubusercontent.com/assets/12136796/11179792/320ced00-8c56-11e5-8139-cb56524f075a.png)

I can add, edit and delete subelements for a streetlight now on QGIS.

On lizmap, on the other hand, if I click on a streetlight, nothing is displayed about subelements:
![image](https://cloud.githubusercontent.com/assets/12136796/11179842/8a1f28d2-8c56-11e5-8a9a-b15a41f07b79.png)

The layers are correctly published in OWS.

Do I have to do a special config or is that a not developed feature in lizmap?

**Comment by rldhont** [comment]
To possibility to do it:
* enhance lizmap to make extra GetFeatureInfo request
* enhance QGIS Server to add sub-elements in GetFeatureInfo

If you use Lizmap Web Client 3, you have relations in the attribute table.

**Comment by rldhont** [comment]
Hi @jaitor1 
I have implement the display of children (relations) in the Lizmap popup, but this feature needs a qgis server bugfix https://github.com/qgis/QGIS/pull/3606?_pjax=%23js-repo-pjax-container that will be available in QGIS 2.14.8, 2.16.4, 2.18.0 and upper.

**Comment by jaitor1** [comment]
Thanks, I am currently using qgis server 2.12.
I will test it as soon as I upgrade the qgis server version.

**Comment by josemvm** [comment]
updated to 2.14.8
great!!!
