### ISSUE TITLE
lizmap~wmts:seeding not working in 3.4.0-rc.2 release

### ISSUE THREAD

**Issue by spygarcia** [3liz/lizmap-web-client#2250]
### What is the bug?

I have just deployed lizmap 3.4.0-rc-2 release. 
Running wmts.cmdline.php via lizmap~wmts:seeding does output the tiles to compute in the console as expected. But  it does not store them or at least correctly so the app ends up being stuck with old tiles.

I have lizmap 3.3rc2 on the side, same configuration, same test project, and the cache script is working well there! 

The issue is new to 3.4.0-rc-2.

### Steps to reproduce the issue

1. Lizmap plugin in qGIS, tick 'Server tile cache' option for a layer 'test'. Save config and project and publish.
2. In the web app load the map, make sure 'test' is shown, pan, zoom in/out so the server generates the tiles for 'test' tiled service.
3. Now back to qGIS, change 'test' symbology. Republish.
4. Load the web map app, as expected we do see the old symbology as 'test'  is consumed using the tiles cached.
5. Now run lizmap~wmts:seeding to recompute some cache:
`php lizmap-web-client-3.4.0-rc.2/lizmap/scripts/script.php lizmap~wmts:seeding -v -f -bbox 185895.0,6878109.5,190786.5,6883001.5 sandbox my_app "test" EPSG:3857 11 14` 

It outputs very fast:

```
The WMTS Service has been initialized!
The TileMatrixSet 'EPSG:3857'!
9 tiles to generate for "test" "EPSG:3857" "11" "185895,6878109.5,190786.5,6883001.5"
16 tiles to generate for "test" "EPSG:3857" "12" "185895,6878109.5,190786.5,6883001.5"
30 tiles to generate for "test" "EPSG:3857" "13" "185895,6878109.5,190786.5,6883001.5"
81 tiles to generate for "test" "EPSG:3857" "14" "185895,6878109.5,190786.5,6883001.5"
136 tiles to generate for "test" "EPSG:3857" between "11" and "14"
Start generation
Progression: 5%, 7 tiles generated on 136 tiles
Progression: 10%, 14 tiles generated on 136 tiles
Progression: 15%, 21 tiles generated on 136 tiles
Progression: 20%, 28 tiles generated on 136 tiles
Progression: 25%, 34 tiles generated on 136 tiles
Progression: 30%, 41 tiles generated on 136 tiles
Progression: 35%, 48 tiles generated on 136 tiles
Progression: 40%, 55 tiles generated on 136 tiles
Progression: 45%, 62 tiles generated on 136 tiles
Progression: 50%, 68 tiles generated on 136 tiles
Progression: 55%, 75 tiles generated on 136 tiles
Progression: 60%, 82 tiles generated on 136 tiles
Progression: 65%, 89 tiles generated on 136 tiles
Progression: 70%, 96 tiles generated on 136 tiles
Progression: 75%, 102 tiles generated on 136 tiles
Progression: 80%, 109 tiles generated on 136 tiles
Progression: 85%, 116 tiles generated on 136 tiles
Progression: 90%, 123 tiles generated on 136 tiles
Progression: 95%, 130 tiles generated on 136 tiles
Progression: 100%, 136 tiles generated on 136 tiles
End generation
```

Too fast to be true. No errors in the log after adding quotes to id, minRow, minCol, maxRow, maxCol  in wmts.cmdline.php, line 359.
`$tileMatrix = (object) array(
                            'id' => $tileMatrixLimit->id,
                            'minRow' => min($minRow, $tileMatrixLimit->minRow),
                            'minCol' => min($minCol, $tileMatrixLimit->minCol),
                            'maxRow' => min($maxRow, $tileMatrixLimit->maxRow),
                            'maxCol' => min($maxCol, $tileMatrixLimit->maxCol),
                        );`

### Expected behavior

Same project, same walkthrough, same command line in lizmap 3.3rc2 is doing the job like a charm. 

### Environment

 - Lizmap version:  lizmap 3.4.0-rc-2 release
 - QGIS Server FULL version: qGIS 3.16 LTR
 - QGIS Desktop FULL version: qGIS 3.16 LTR
 - OS (Windows, Linux, MacOS, Android…):  Ubuntu
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Standard install > Sqlite

**Comment by spygarcia** [comment]
Oh sorry just seeing the problem was already raised and seems to be resolved with following commit

**Comment by Gustry** [comment]
Yes, you shouldn't install 3.4.0-rc2.

3.4.2 has already been released : https://github.com/3liz/lizmap-web-client/releases

Fill up the server information in the lizmap plugin, it would inform your server is not up to date.

Thanks for checking commit history

**Comment by spygarcia** [comment]
I have just given a go with a fresh install of lizmap-web-client-3.4.3 and the same problem occurs.

**Comment by ygorigor** [comment]
@spygarcia this [commit ](https://github.com/3liz/lizmap-web-client/pull/2170/files/5bfa9b9d11291ea2b4249721f95fd2a042582db8)was not merged yet

**Comment by Gustry** [comment]
@spygarcia Move to #2053
