### ISSUE TITLE
Export data hide export to geojson and GML

### ISSUE THREAD

**Issue by adrian61** [3liz/lizmap-web-client#2252]
### Description
I've installed qgis-wfsOutputExtension and I want to be able to export data only to XLSX format. I modified definitions.py. But after that users can export files to: geoJSON, GML and XLSX. I want to hide geoJSON and GML. How to do that?

### Environment

 - Lizmap version: 3.4.2
 - QGIS Server FULL version: 3.18
 - QGIS Desktop FULL version: 3.18
 - OS (Windows, Linux, MacOS, Android…): -
 - Browser (Firefox, Chrome…): -
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?  Postgresql

**Comment by Gustry** [comment]
* Be sure that you commented properly the python file to about unwanted extensions
* Depending of the webserver you are using and the way you have setup your server, you might need to restart the webserver to read the new python file
* Lizmap keeps a cache of the "GetCapabilities", try the script in the source code https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/clean_vartmp.sh
