### ISSUE TITLE
Lizmap printing PDF not corresponding to selected entity

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-web-client#2253]
Hi
### What is the bug?
Lizmap popup generate wrong printing pdf file.
I have 2 polygon with the exact same bounds and differents attribute. When i click the polygon, i have 2 popup referencing my 2 entities respectively A and B with each a link to the printing pdf.
When clicking on the print link from A i've got the pdf corresponding, but when clicking on B i've got a random pdf.
It appears that the first time we click the pdf link, we've got the good file, but then it's like it generate a random "next entity" for pdf and it is not corresponding to the entity we're looking for.

### Steps to reproduce the issue

1. Adding layer to QGIS with duplicate geometries
2. Créating Atlas in QGIS
3. Activate popup and print option in Lizmap
4. Go To Lizmap, Select entity, and click the pdf link
5.  The pdf is the rigth one
6. Select same entity, the link to pdf won't be the same and will be a wrong one

### Expected behavior
PDF Should be the one corresponding to the entity indentified by the primary key.

### Environment

 - Lizmap version: 3.3.15
 - QGIS Server FULL version:
 - QGIS Desktop FULL version: 3.10.12
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Firefox, Chromium, Brave

**Comment by Gustry** [comment]
This occurs often with the "Cat's demo" : https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=cats

It's an issue upstream in QGIS Server if I'm correct (cc @rldhont )

**Comment by rldhont** [comment]
Bug plugin alasprint fixed https://github.com/3liz/qgis-atlasprint/issues/44 a version 3.2.2 will be released.

**Comment by Gustry** [comment]
3.2.2 has been released : https://github.com/3liz/qgis-atlasprint/releases/tag/v3.2.2

**Comment by Ailurupoda** [comment]
The problem was solved by castin primary key as integer.
The layer used was a postgres view using a row_number() over() as gid wich is a bigint i guess.

Forcing it to integer fixed the random generation.

**Comment by rldhont** [comment]
@Ailurupoda It has been fixed in https://github.com/3liz/qgis-atlasprint/releases/tag/v3.2.2
