### ISSUE TITLE
Problem to display children in a compact way

### ISSUE THREAD

**Issue by Vermeil-M** [3liz/lizmap-web-client#2254]
### What is the bug?
Hello,
The children are not displayed in a compact way when I program the qgis popup. However the compact display works correctly if the popup is set to "auto" in the lizmap plugin

### Steps to reproduce the issue
1 .Make a 1 to n relationship between the parent and child layer
2. In the child layer I set the tooltip as follows: 

            <table class="lizmap_merged">
             <tr class="lizmapPopupHeader">
                 <th ><center> label </center></th>
                 <th> <center> responsable </center> </th>
                 <th> <center> prioriter</center> </th>
              </tr>
              <tr>
                 <td><center>[% "label" %]</center></td>
                 <td><center>[% "responsable" %]</center></td>
                 <td><center>[% "prioriter" %]</center></td>
              </tr>
            </table>

3.Check "display child objects under each parent (used relations)" in the Lizmap plugin for the parent layer (note: the source of the popup for the parent layer is of type lizmap)
4. Define the qgis source for the popup of the child layer
5. Error, the display of the child entities is not compact....

### Expected behavior
The expected behavior is a compact display, as in the documentation "Display children in a compact way" with the example of PLU type

### Screenshots and logs

When the popup source, for the child layer, is set to qgis :
![image](https://user-images.githubusercontent.com/37774361/116246502-576c0100-a76a-11eb-89db-db81e2e99171.png)
image of the html code for the qgis popup source
![image](https://user-images.githubusercontent.com/37774361/116355760-9b0e4b80-a7fa-11eb-8981-3bd04dcacab5.png)

When the popup source, for the child layer, is set to auto :
![image](https://user-images.githubusercontent.com/37774361/116247084-c9dce100-a76a-11eb-88a3-04e836e0692d.png)

### Environment

 - Lizmap version: 3.4.3
 - QGIS Server FULL version: 3.16.6
 - QGIS Desktop FULL version: 3.10.14-A Coruña
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? 
PostgreSQL

**Comment by aeduard** [comment]
The expected table like behavior is working only if child layer popup is set to Auto. Check in the [documentation](https://docs.lizmap.com/3.4/en/publish/configuration/popup.html?highlight=popup#one-to-many-relations).

> If relative children popup are defined as auto, this button will be visible in the feature’s popup at the top of related objects. Click it to compact all related objects in one table with search, sort and paging capabilities.

This was discussed also in #2065 

I think the former html class type of formatting was working only until lizmap 3.3.x, although it appears for the current versions also.

**Comment by Gustry** [comment]
> I think the former html class type of formatting was working only until lizmap 3.3.x, although it appears for the current versions also.

The "manual" HTML snipped is working on latest 3.5, the one described on https://docs.lizmap.com/current/en/publish/configuration/popup.html#display-children-in-a-compact-way

But the automatic button is not working, see #2759

@nboisteault Should we close this ticket ?
