### ISSUE TITLE
Lizmap dont show content of Layers

### ISSUE THREAD

**Issue by asdro-f** [3liz/lizmap-web-client#2257]
In my Lizmap i can see my Projects, but when i open one of them, i see the Layer Names in the legend, but cant see any Content in my Map. The problem is not in the Layers, QGIS shows everything.

Ubuntu 20.04.2 LTS
Apache/2.4.41 (Ubuntu)
QGIS LTR (should be 3.16., dont knwo how to check the current Version on Ubunut, installed from https://qgis.org/ubuntu-ltr/)
lizmap-web-client-3.4.0

What steps i did:
First getting a new Ubuntu VM.
Second Installing Apache and QGIS Server on it with, amongst other things:
sudo apt-get install qgis-server python-qgis apache2 libapache2-mod-fcgid curl
After this i was able to host Layers as WMS and emped it in QGIS via URL.
Then i installed the Lizmap-Web-Client like in https://docs.lizmap.com/next/en/install/linux.html

After that the 'normal' function of the QGIS Server (Hosting WMS) doesnt work anymore.
Like described above i can see my Projects in the Lizmap Web Client but not the content of the Layers which are in the projects.

Lizmap Log tells me: 
...	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fhome%2Fazureuser%2Fmaps%2Ftestprojekt2%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
	/var/www/lizmap-web-client-3.4.0/lizmap/modules/lizmap/classes/lizmapProxy.class.php	249

Is this a problem with the compatibility of the Versions? Or did i make a mistake which i dont see right now? Any Ideas?
Thanks for help!

**Comment by asdro-f** [comment]
I reinstalled everything now
Now QGIS Server works fine, i can load my WMS e.g. in QGIS.
So it should be a lizmap-problem.
When i try to load the Map i get the following Error:
2021-05-10 14:11:25     78.48.189.77    warning 2021-05-10 14:11:25     [2]     file_get_contents(https://my.server/cgi-bin/qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas&amp;map=%2Fhome%2Fmyuser%2Fmaps%2Ftest%2Eqgs): failed to open stream: HTTP request failed! HTTP/1.1 501 Not Implemented
        /var/www/lizmap-web-client-3.4.0/lizmap/modules/lizmap/classes/lizmapProxy.class.php    249

Line 249: $data = file_get_contents($url, false, $context);

**Comment by gerald2545** [comment]
Can it help ? : https://github.com/3liz/lizmap-web-client/issues/1274

**Comment by asdro-f** [comment]
I solved it now. The problem was in the redirection of http://my.server/cgi-bin/qgis_mapserv.fcgi to https. I just changed my redirection rules and now it works well. :)

Thanks anyway for your idea gerald!

**Comment by meyerlor** [comment]
sorry to grave dig here, but i m running i a similar problem it seems - at least i'm getting the same 501 Error Code - what exactly did you change in your server config?

**Comment by Nokram** [comment]
@meyerlor @asdro-f any help about this issue. I can't solve this problem

**Comment by meyerlor** [comment]
well, i ended up using the direct url of qgis server and not the WMS provided by LWC..
