### ISSUE TITLE
Feature request: support for virtual fields 

### ISSUE THREAD

**Issue by ninbrm** [3liz/lizmap-web-client#226]
Hi,
Feature request: support for virtual fields in pop-ups...
Thanks a lot for a great tool!
Bram

**Comment by mdouchin** [comment]
Hi
Lizmap relies heavily on QGIS Server : popups content are build from the WMS GetFeatureInfo requests. QGIS Server should already support virtual fields (I have already used them to show polygons area in popup). Which QGIS Server version do you use ?

**Comment by ninbrm** [comment]
Hi, 
Thanks for the prompt reply! We are using 2.8 on the server. 
If you have used virtual fields, then the problem is clearly on our side! We will find out...
Thanks a lot for your help,
Bram

**Comment by mdouchin** [comment]
Please try to use QGIS Server 2.8.3 (if this this not the version you already use).
You should also use QGIS Desktop 2.8.3 and not 2.10 or 2.12 ( the desktop version should never be newer than the server )
I am not sure virtual fields were already implemented in QGIS 2.8, but I think so.

**Comment by ninbrm** [comment]
I must apologize, I re-tested and now things work smoothly! (I am not sure what went wrong yesterday. We were dealing with some server issues yesterday, maybe...)
So, thank you for having already implemented the features I am requesting ;-)
and sorry the trouble...
p.s.: to answer your question: we are using 2.8.3 (so, yes, virtual fields are supported here)
