### ISSUE TITLE
How to change the url of Lizmap?

### ISSUE THREAD

**Issue by SlimBot27** [3liz/lizmap-web-client#2271]
### Description

Hi, I am trying to change the url that will allow user to acess my lizmap WUI. At this moment I have : http://localhost/lizmap/lizmap/www/index.php. However, I would like to have something like http://example.com/lizmap/lizmap/www/index.php

What should I do?

### Environment

 - Lizmap version: 
 - QGIS Server FULL version:
 - QGIS Desktop FULL version: 
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…): 
 - Lizmap admin information (users, logs…) stored into Sqlite (default)?

**Comment by Gustry** [comment]
If I read your question correctly, you mainly want to change `localhost` by `example.com`, right ?
So this is not a Lizmap configuration, it's a web server configuration. You should read documentation how to add a domain name to nginx/apache or the webserver your are using. It's generic how to deploy a website.

**Comment by SlimBot27** [comment]
Ok, thank you very much for your help.
