### ISSUE TITLE
Trim registration login before used it

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2273]
### What is the bug?
https://github.com/jelix/jcommunity-module/issues/33

### Steps to reproduce the issue

1. Go to registration
2. Enter a login with a space at the end `foospace `
3. Validate the email address with the link provided in the email validation
4. Go to log in
5. Try to log in without the space at the end - see error

### Expected behavior
The login has to be trimmed before the user creation

**Comment by laurentj** [comment]
In 3.4 and 3.5, update of the module is automatic during the build, as it is installed with Composer.
