### ISSUE TITLE
Can't enable LDAP Authentication

### ISSUE THREAD

**Issue by aledalla** [3liz/lizmap-web-client#2276]
I am here to ask some help for enabling the LDAP authentication in Lizmap.

I follwed this offical doc page: https://docs.lizmap.com/current/en/install/ldap.html

But when I run the command "php lizmap/install/installer.php" I got the following errors.

```
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
PHP Notice:  Undefined property: ldapdaoModuleInstaller::$entrypoint in /var/www/lizmap-web-client-3.4.3/lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php on line 43

PHP Notice:  Trying to get property 'config' of non-object in /var/www/lizmap-web-client-3.4.3/lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php on line 43

PHP Notice:  Trying to get property 'coordplugins' of non-object in /var/www/lizmap-web-client-3.4.3/lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php on line 43

PHP Warning:  parse_ini_file(/var/www/lizmap-web-client-3.4.3/lizmap/var/config): failed to open stream: No such file or directory in /var/www/lizmap-web-client-3.4.3/lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php on line 25

PHP Fatal error:  Uncaught Error: Call to a member function getPlugin() on null in /var/www/lizmap-web-client-3.4.3/lib/jelix/auth/jAuth.class.php:53

Stack trace:
#0 /var/www/lizmap-web-client-3.4.3/lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php(26): jAuth::loadConfig(false)
#1 /var/www/lizmap-web-client-3.4.3/lib/jelix/installer/jInstaller.class.php(651): ldapdaoModuleInstaller->install()
#2 /var/www/lizmap-web-client-3.4.3/lib/jelix/installer/jInstaller.class.php(491): jInstaller->_installModules(Array, 'index', true, 3)
#3 /var/www/lizmap-web-client-3.4.3/lib/jelix/installer/jInstaller.class.php(432): jInstaller->installEntryPointModules('index', 3)
#4 /var/www/lizmap-web-client-3.4.3/lizmap/install/installer.php(16): jInstaller->installApplication()
#5 {main}
  thrown in /var/www/lizmap-web-client-3.4.3/lib/jelix/auth/jAuth.class.php on line 53
```

 - Lizmap version: 3.4.3
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS: Debian

**Comment by rmarzocchi84** [comment]
I have the same problem 

- LWC 3.4.4
- QGIS Server 3.16.X
- OS: Ubuntu 20.04

**Comment by josemvm** [comment]
hi @rmarzocchi84 
i'am using multiauth module https://github.com/jelix/multiauth-module and evetything works fine

**Comment by rmarzocchi84** [comment]
hi @josemvm but multiauth is installed on lizmap 3.4.4? 

Probably documentation (https://docs.lizmap.com/current/en/install/ldap.html) need to be updated. I can try to do it, but I have to undestand how to use it

**Comment by josemvm** [comment]
it needs installation inside lizmap-modules
https://github.com/jelix/multiauth-module/blob/master/README.md#install-files-with-jelix-1621

**Comment by rmarzocchi84** [comment]
I have correctly installed both the modules

for @aledalla the problem perhaps is in mainconfig.ini.php 

`ldapdao.installparam=noconfigfile` --> `ldapdao.installparam="noconfigfile"`

This is my [modules] section in the `mainconfig.ini.php`


```
[modules]
jelix.access=1

jacl.access=0
jacldb.access=0
jpref.access=0
jsoap.access=0
junittests.access=0
jpref_admin.access=0

jacl2.access=1
jacl2db.access=1
jacl2db.installparam=defaultuser

jauth.access=2
jauthdb.access=1

jcommunity.access=1
jcommunity.installparam="defaultusers=lizmap~defaultusers.json;manualconfig"

admin.access=1
dataviz.access=1
filter.access=1
action.access=1
dynamicLayers.access=1
lizmap.access=1
proj4php.access=1
view.access=1

ldapdao.installparam="noconfigfile"
multiauth.installparam="noconfigfile;localconfig"

ldapdao.path="app:vendor/jelix/ldapdao-module/ldapdao"


multiauth.access=1
```

I have a problem in configuration of multiauth (`localconfig.ini.php` file)
```
[modules]
;; uncomment it if you want to use ldap for authentication
;; see documentation to complete the ldap configuration
;ldapdao.access=1


[coordplugin_auth]
;; uncomment it if you want to use ldap for authentication
;; see documentation to complete the ldap configuration
;driver=ldapdao
driver=multiauth


[coordplugins]
lizmap=lizmapConfig.ini.php


[jcommunity]
resetAdminPasswordEnabled = off


[logger]
auth=file

[fileLogger]
auth=auth.log



[multiauth]
; name of the dao to get user data
dao = "jauthdb~jelixuser"

; profile to use for jDb 
profile = "jauth"

; list of authentication providers
providers[]=ldap:multiauth_ldap
;providers[]=dbdao:centraldb
providers[]=dbaccounts

; name of the form for the jauthdb_admin module
form = "jauthdb_admin~jelixuser"

; path of the directory where to store files uploaded by the form (jauthdb_admin module)
; should be related to the var directory of the application
uploadsDirectory= ""

; if set to on, when a user login successfully, an account will be created automatically
automaticAccountCreation = on

; required. Internal use for jAuth. Dont touch it.
compatiblewithdb = on

; you should set it to allow password storage migration, if you have an old
; users table.
; @deprecated
password_crypt_function = sha1




[multiauth_ldap]
; profile to use for ldap
ldapprofile = "lizmapldap"
```

**Comment by aledalla** [comment]
Thank you @rmarzocchi84 but I didn't understeand your reply.

Have you found what was wrong enabling ldap?

Se ti trovi meglio puoi scrivermi in italiano

**Comment by josemvm** [comment]
@rmarzocchi84 you don´t need to change the mainconfig.ini.php

localconfig.ini.php
[modules]
multiauth.access=1
jacl2.access=1
jauth.access=2
jauthdb.access=1

profiles.ini.php
[ldap:lizmapldap]
your ldap parameters...

run installer.php

**Comment by rmarzocchi84** [comment]
> Thank you @rmarzocchi84 but I didn't understeand your reply.
> 
> Have you found what was wrong enabling ldap?
> 
> Se ti trovi meglio puoi scrivermi in italiano

In the `mainconfig.ini.php` there is this line 

 `ldapdao.installparam=noconfigfile`

which in my opinion is wrong (no quotes)

ldapdao.installparam="noconfigfile"

This is my [modules] section in the mainconfig.ini.php

**Comment by rmarzocchi84** [comment]
> [modules]
> multiauth.access=1
> jacl2.access=1
> jauth.access=2
> jauthdb.access=1


I did it but when I try to login with the lizmap admin user I have the following error

`2021-06-30 12:17:12	10.253.249.126	notice	2021-06-30 12:17:12	[8]	Undefined property: cDaoRecord_jauthdb_Jx_jelixuser_Jx_pgsql::$status	/home/procedure/mappe/lizmap/vendor/jelix/jcommunity-module/modules/jcommunity/classes/authcommunity.listener.php	20`

**Comment by josemvm** [comment]
i think if you can try with a fresh install you can solve your problem...

**Comment by aledalla** [comment]
> > Thank you @rmarzocchi84 but I didn't understeand your reply.
> > Have you found what was wrong enabling ldap?
> > Se ti trovi meglio puoi scrivermi in italiano
> 
> In the `mainconfig.ini.php` there is this line
> 
> `ldapdao.installparam=noconfigfile`
> 
> which in my opinion is wrong (no quotes)
> 
> ldapdao.installparam="noconfigfile"
> 
> This is my [modules] section in the mainconfig.ini.php

I've just checked the mainconfig.ini.php file and "multiauth.installparam"

> I have correctly installed both the modules
> 
> for @aledalla the problem perhaps is in mainconfig.ini.php
> 
> `ldapdao.installparam=noconfigfile` --> `ldapdao.installparam="noconfigfile"`
> 
> This is my [modules] section in the `mainconfig.ini.php`
> 
> ```
> [modules]
> jelix.access=1
> 
> jacl.access=0
> jacldb.access=0
> jpref.access=0
> jsoap.access=0
> junittests.access=0
> jpref_admin.access=0
> 
> jacl2.access=1
> jacl2db.access=1
> jacl2db.installparam=defaultuser
> 
> jauth.access=2
> jauthdb.access=1
> 
> jcommunity.access=1
> jcommunity.installparam="defaultusers=lizmap~defaultusers.json;manualconfig"
> 
> admin.access=1
> dataviz.access=1
> filter.access=1
> action.access=1
> dynamicLayers.access=1
> lizmap.access=1
> proj4php.access=1
> view.access=1
> 
> ldapdao.installparam="noconfigfile"
> multiauth.installparam="noconfigfile;localconfig"
> 
> ldapdao.path="app:vendor/jelix/ldapdao-module/ldapdao"
> 
> 
> multiauth.access=1
> ```
> 
> I have a problem in configuration of multiauth (`localconfig.ini.php` file)
> 
> ```
> [modules]
> ;; uncomment it if you want to use ldap for authentication
> ;; see documentation to complete the ldap configuration
> ;ldapdao.access=1
> 
> 
> [coordplugin_auth]
> ;; uncomment it if you want to use ldap for authentication
> ;; see documentation to complete the ldap configuration
> ;driver=ldapdao
> driver=multiauth
> 
> 
> [coordplugins]
> lizmap=lizmapConfig.ini.php
> 
> 
> [jcommunity]
> resetAdminPasswordEnabled = off
> 
> 
> [logger]
> auth=file
> 
> [fileLogger]
> auth=auth.log
> 
> 
> 
> [multiauth]
> ; name of the dao to get user data
> dao = "jauthdb~jelixuser"
> 
> ; profile to use for jDb 
> profile = "jauth"
> 
> ; list of authentication providers
> providers[]=ldap:multiauth_ldap
> ;providers[]=dbdao:centraldb
> providers[]=dbaccounts
> 
> ; name of the form for the jauthdb_admin module
> form = "jauthdb_admin~jelixuser"
> 
> ; path of the directory where to store files uploaded by the form (jauthdb_admin module)
> ; should be related to the var directory of the application
> uploadsDirectory= ""
> 
> ; if set to on, when a user login successfully, an account will be created automatically
> automaticAccountCreation = on
> 
> ; required. Internal use for jAuth. Dont touch it.
> compatiblewithdb = on
> 
> ; you should set it to allow password storage migration, if you have an old
> ; users table.
> ; @deprecated
> password_crypt_function = sha1
> 
> 
> 
> 
> [multiauth_ldap]
> ; profile to use for ldap
> ldapprofile = "lizmapldap"
> ```
> 
> it doesn't work.. any suggestion @josemvm ?

I've just tried your hint but nothing changed..also tried to set localconfig file instead of nonconfig.

**Comment by laurentj** [comment]
Hi,

I confirm the bug. I will fix it.

If you don't want to wait the next release, you have to modify this file by hand : `lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php`. At line 43, replace:

```
$authconfig = $this->entrypoint->config->coordplugins['auth'];
```

by 

```
$authconfig = $this->entryPoint->config->coordplugins['auth'];
```
(This the the `p` of `entrypoint` which must be a `P`)

At side note:

- don't modify the `mainconfig.ini.php` file, else you will loose changes at the next update.
- if you want to modify something into `mainconfig.ini.php`, copy the parameter into `localconfig.ini.php` with its new value (don't forget to create also the section `[xxxx]` it is in a section)
- @rmarzocchi84 
   > the problem perhaps is in mainconfig.ini.php
   > `ldapdao.installparam=noconfigfile --> ldapdao.installparam="noconfigfile"`
  
  No, quotes are not required, except if the value contains some special characters. This is not the case here, so quotes don't change anything
- ldapdao is preconfigured, you just have to activate it (set `ldapdao.access` value and the `driver` value) and indicate ldap parameters
- multitauth is not provided into lizmap, but it is preconfigured like ldapdao (except for ldap parameters of course)
- to install multiauth instead of ldapdao, you must activate the module like @josemvm indicated
- you must not activate both modules ldapdao and multiauth at the same time

**Comment by aledalla** [comment]
@rmarzocchi84 I've just tried quoting that string but nothing changed.

@laurentj , @josemvm  Can you please help me with the original issue?

**Comment by aledalla** [comment]
> Hi,
> 
> I confirm the bug. I will fix it.
> 
> If you don't want to wait the next release, you have to modify this file by hand : `lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php`. At line 43, replace:
> 
> ```
> $authconfig = $this->entrypoint->config->coordplugins['auth'];
> ```
> 
> by
> 
> ```
> $authconfig = $this->entryPoint->config->coordplugins['auth'];
> ```
> 
> (This the the `p` of `entrypoint` which must be a `P`)
> 
> At side note:
> 
> * don't modify the `mainconfig.ini.php` file, else you will loose changes at the next update.
> * if you want to modify something into `mainconfig.ini.php`, copy the parameter into `localconfig.ini.php` with its new value (don't forget to create also the section `[xxxx]` it is in a section)
> * @rmarzocchi84
>   > the problem perhaps is in mainconfig.ini.php
>   > `ldapdao.installparam=noconfigfile --> ldapdao.installparam="noconfigfile"`
>   
>   
>   No, quotes are not required, except if the value contains some special characters. This is not the case here, so quotes don't change anything
> * ldapdao is preconfigured, you just have to activate it (set `ldapdao.access` value and the `driver` value) and indicate ldap parameters
> * multitauth is not provided into lizmap, but it is preconfigured like ldapdao (except for ldap parameters of course)
> * to install multiauth instead of ldapdao, you must activate the module like @josemvm indicated
> * you must not activate both modules ldapdao and multiauth at the same time

I've just modified the "lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php" file as you said but I got the same error

**Comment by aledalla** [comment]
@laurentj after installation has success, I tried to login and got 500 error when submitting the request.

Analyzing lizmap/var/log/errors.log I found this line:

[602]   can't find driver "ldapdao" to authenticate /var/www/lizmap-web-client-3.4.3/lib/jelix/auth/jAuth.class.php  166

**Comment by laurentj** [comment]
@aledalla From a fresh installation of Lizmap 3.4.5, I correct the issue into `lizmap/vendor/jelix/ldapdao-module/ldapdao/install/install_1_6.php`, and strictly follow the documentation at https://docs.lizmap.com/3.4/en/install/ldap.html. It works on my machine. 

> `can't find driver "ldapdao" to authenticate`

It seems that you didn't clean the content of the temp/ directory, or you forgot to launch  `php lizmap/install/installer.php`.

**Comment by aledalla** [comment]
How to clear temp folder? I removed everyting inside it and boom, nothing workin! Restoring it from backup!

ldapdao.access parameter have to be set to 1 or 2?
If I set to 2 I have no errors and I can see request passing to LDAP

**Comment by laurentj** [comment]
Sorry, I talk about the temp/lizmap/ directory. You have a `lizmap/install/clean_vartmp.sh` script to cleanup all temporary files.

>ldapdao.access parameter have to be set to 1 or 2?

For this module, 1 or 2 are ok.

**Comment by laurentj** [comment]
The issue is fixed. You can use [the package of Lizmap 3.4.6-pre](https://packages.3liz.org/pub/lizmap/unstable/3.4/lizmap-web-client-3.4.6-pre.zip] to have lizmap with the fix

**Comment by aledalla** [comment]
@laurentj  Thank you!

Another question; Editing file /lizmap/var/config/profiles.ini.php requires the command " php lizmap/install/installer.php" to be applied or not?

**Comment by laurentj** [comment]
no, you launch `php lizmap/install/installer.php` only if you modified the `[modules]` section of mainconfig or localconfig.
Other modifications into these files don't require to launch installer. In most of case, changes in these files update the content of temp/lizmap/, but depending on the machine, sometimes it does not work so you should remove all stuff from temp/lizmap/. That's all.

Changes into profiles.ini.php does not require anything.

**Comment by aledalla** [comment]
Thank you, Is there any way to check out the LDAP query? I tried lot of parameters but authentication returns "unknow user or incorrect password"

**Comment by aledalla** [comment]
Thank you.
I configured the ldap binding but I got the error 52e which means username ok but wrong password.
I am sure password provided is correct.
