### ISSUE TITLE
Google Base Layers not displayed when map loads

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#228]
Hi,

From about 5 days ago, I've been experiencing a problem with my maps.

When I load a map that has a Google Base Layer as default base layer (Google Streets, Google Satellite, etc..) the base layer is not loaded. If I then open the base layers combobox and select another one, all of them work, even the Google base layers.

So the problem is that the base layer is not displayed on map load but it does on baselayer change. This problem has appeared last week after working with lizmap perfectly for months. I guarantee that I did not make any change to any file in lizmap so I think it must be an external problem.

I have downloaded lizmap 2.12 and tried it, with the same result:
http://eudala2.getxo.eus/lizmap/lizmap-212/lizmap/www/index.php/view/map/?repository=zonas&project=zonas_juego

Regards,

**Comment by jaitor1** [comment]
It may be related with https://gis.stackexchange.com/questions/160444/google-maps-roadmap-doesnt-show-on-ol-unless-i-change-base-layer-and-re-apply

**Comment by pcav** [comment]
Confirmed, symptoms are the same. Worth releasing a new LM version and upgrading?

**Comment by rldhont** [comment]
Lizmap Web Client 2.12.1 has been released
https://github.com/3liz/lizmap-web-client/releases/tag/2.12.1
