### ISSUE TITLE
welcome page with multiple projects side by side possible?

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-web-client#2283]
### Description
I have 2 lizmap projects and in the welcome page, they are listed one above the  other. Is there a way to tell lizmap to display them side by side instead ? 
Thank you for your help
Gerald

### Environment
Lizmap version: 3.4.3
QGIS Server FULL version: 3.10
QGIS Desktop FULL version: 3.16.5
OS (Windows, Linux, MacOS, Android…): Docker sur linux
Browser (Firefox, Chrome…):Firefox
Lizmap admin information (users, logs…) stored into Sqlite

**Comment by ygorigor** [comment]
@gerald2545 you have to put project files in the same folder, then they will be side by side

**Comment by gerald2545** [comment]
nice!!!
thank you for your help

**Comment by aeduard** [comment]
Is there any other way to get projects side-by-side? I have complex maps, and I've preferred to keep them in separate folders. It is much easier to batch upload files, migrate some projects etc. The same question I've tried to ask within issue #1846 .
My folder structure looks like this:
-- project1
    |-- media
         |-- upload
         |-- js
         |-- documents1
         |-- etc
-- project2
    |-- media
         |-- upload
         |-- js
         |-- documents1
         |-- etc
-- project3

**Comment by ygorigor** [comment]
> Is there any other way to get projects side-by-side? I have complex maps, and I've preferred to keep them in separate folders. It is much easier to batch upload files, migrate some projects etc. The same question I've tried to ask within issue #1846 .
> My folder structure looks like this:
> 
> ├── project1
> │ ├── media
> │ │ ├── upload
> │ │ ├── js
> │ │ ├── pdf
> │ └── raster
> ├── project2
> │ ├── media
> │ │ ├── upload
> │ │ ├── js
> │ │ ├── pdf
> ├── project3

@aeduard only if you will change source code of LWC

**Comment by nboisteault** [comment]
Some additional CSS should do the trick.

**Comment by Gustry** [comment]
I tried a long time ago, I got issues with symbolic links. Maybe try ?
