### ISSUE TITLE
Trying to create lizmapWC docker image

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#2284]
### Description
Hi all,
I'm trying to create a LWC docker image following what is written in the readme file here https://github.com/3liz/lizmap-web-client/tree/master/docker

In the Dockerfile there is an instruction regarding the copy of a lizmap_web_client.zip file (https://github.com/3liz/lizmap-web-client/blob/c6aff845946ac400a520d5a533d0c9e58f0cb4b7/docker/Dockerfile#L34). It's not clear to me which zip file it refers to.

I tried to download the zip file of the master branch of LWC but when running the Dockerfile no factory.manifest file is found.

Maybe I got the wrong zip or I missed something else. Can you provide the path to the right zip file to build the image?

![image](https://user-images.githubusercontent.com/25825472/118393669-89250900-b640-11eb-9420-854c8298855d.png)

**Comment by ygorigor** [comment]
@RobiFag if you are on Linux you can try with this steps:
1. Clone LWC to you PC if you didn't already
2. cd lizmap folder
3. Type command: make build
4. Type command: make docker-build

**Comment by RobiFag** [comment]
@ygorigor thank you so much! I managed to create the image in Linux following your instructions!

**Comment by Gustry** [comment]
Good news. I'm closing.
