### ISSUE TITLE
logMetric - lizmap stop loads baselayers from WMS source or XML file

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2293]
hi

lizmap stop loads baselayers from WMS source or XML file:

```
2021-05-20 08:51:29	xxx.xxx.xxx.xxx	error	2021-05-20 08:51:29	[0]	Call to a member function parameters() on null	/var/www/html/lizmap-web-client-release_3_3/lizmap/modules/lizmap/controllers/service.classic.php	1548
```

thanks

 - Lizmap version: 3.3.13
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14
 -

**Comment by rldhont** [comment]
@josemvm is your lizmap web client version is 3.3.13 ?

The commit https://github.com/3liz/lizmap-web-client/commit/af8404547810b51bf61bbc0d8f89c48e8dca5552 for version 3.3.16 has to fix this issue.

**Comment by rldhont** [comment]
The regression has been introduced in 3.3.16-pre

**Comment by josemvm** [comment]
hi @rldhont
i' am working on 3.3.16-pre, with all commits

**Comment by laurentj** [comment]
Take it. I see the problem

**Comment by laurentj** [comment]
Fixed

**Comment by laurentj** [comment]
@josemvm thank you for your report

**Comment by josemvm** [comment]
solved! ;-)
