### ISSUE TITLE
Help with dinamically generate views based on a value passed with Lizmap Web Client

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#2297]
### Description
I'm using LWC with Postgres/Postgis layers/tables.
I beg your pardon in advance if mine is a silly question but I don't know how to easily reach my goal:
I've done a view that joins a spatial table (with distinct polygons each with a data_start and date_end columns) with another spatial table, with an added a calculated column with values that dynamically change according to the year I put in the view at the end (i.e.  -athe the end of the query - WHERE year= 2017) and also geometric shapes are filtered and shown according to the year I write.
One way could be to create a single query/view for each desired year but that would be less "refined".
I'd like to know if there's a way to pass a variable value through LWC and have a unique view/query automatically recalculated on different years I choose
I'm thinking about creating a further table named "year" in which I have only one record that contains just one year value that I can update with a map value widget in edition tool so that the main view could change (i.e.  -athe the end of the query - WHERE year= year.value).
Maybe I could even reach my goal with LWC filter function (the lens in the menu) applied on a view with non distinct polygons inside each with its own money value column referred to the corresponding year (maybe) but that would be a duplication of records and I wouldn't like much this solution.
Any hint or suggestion about ?
Thanks

### Environment

 - Lizmap version: 3.4.3
 - QGIS Server FULL version: 3.16.6
 - QGIS Desktop FULL version: 3.16.6
 - OS (Windows, Linux, MacOS, Android…): Linux Ubuntu 8.04 LTS
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Sqlite (default)
 - Postgres 11.x with postgis 3.x extension

**Comment by gerald2545** [comment]
hum quite complicated to understand. Could you please give us some real examples (naming the tables) and what you want to achieve?

**Comment by ocelot73** [comment]
Maybe i haven't explained well my nerds.
I have one spatial table with about 100 polygons and various columns, among which, in particular, a "date_start" and a "date_end" ones (in YYYY-MM-DD format). Some values in date_end could be NULL, meaning the polygon Is still valid.
I'm asking suggestions to find easiest way to select just one year and show all polygons that are valid (in which the year of date_start Is <= selected year AND the year of date_end Is >= selected year).
I've tried with lizmap search form filter with date type values buy I have to manually slide the two cursors and the problem Is that polygons are not correctky displayed because lizmap won't show a polygon if a selected date Is greater than the one written in db.
So in previous post i've thought about a "manual" workaround using a view/materialized view that filters shown polygons based on secondary table where I can select desired year.
What Is the best way in your opinioni?
Thanks

**Comment by cxcandid** [comment]
This is more a QGIS-Server issue. 
LIZMAP is only the peak of the iceberg, most of the work is done in the background.

The question is: how can we pass additional parameters to QGIS-Sserver that can be used as expression variables or within SQL queries?

I found a 4 year old discussion on QGIS-Developer that describes exactly this issue: https://qgis-developer.osgeo.narkive.com/gtLsN4s5/qgis-server-request-extra-parameters-as-variables-for-expressions

Maybe there is some progress in this case?
It's possible to implement a custom solution, but IMHO it wouldn't make much sense as @MatthiasKuhn describes in the discussion.
