### ISSUE TITLE
Map initial loading with heavy layer locate is too slow

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#2298]
**_What is the bug?_**
I have noticed that when I add a locate by layer with a heavy layer (14000 features, both in Postgresql and shapefiles), initial map loading decrease drammatically. When I remove that layer from "locate by layer", the map speed increase and the loading is almost instantanely. After first loading, the session goes quite speed, till next session. Any suggestion to speed up the initial loading?

_**Environment**_

 - Lizmap version: 3.3.6-pre
 - QGIS Server FULL version: 2.18
 - QGIS Desktop FULL version: 2.18
 - OS (Windows, Linux, MacOS, Android…):  Windows
 - Browser (Firefox, Chrome…): Every browser
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

I know, I have to upgrade both Lizmap and QGis versions!

**Comment by Gustry** [comment]
If you upgrade to QGIS 3, you would have a information warning at the top of the Lizmap plugin to switch to PostgreSQL Lizmap Search if possible.
https://docs.lizmap.com/current/fr/publish/configuration/spatial_search.html#postgresql-lizmap-search
This is way better for performance.

I have just added the warning in the documentation as well https://docs.lizmap.com/current/fr/publish/lizmap_plugin/locate_by_layer.html#prerequisites

When activating the "locate by layer", the web browser will indeed download all features in the layer (including geometries as vector), so 14 000 features in your case (the download and the loading then takes a long time).

There isn't too much to optimize. The locate by layer has not be designed to load 14000 features (limitation from browser, data download etc). You can reduce the number of decimals in your WFS project settings (removing decimals if your layer is in meters, it makes sense and will reduce the size for each feature * 14 000).
