### ISSUE TITLE
Points on the East missing at full zoom with EPSG:3857

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#23]
A few points are missing in a sample install of LizMap (see extreme East, N Japan and NSW, Australia):
http://www.faunalia.it/map/lizmap/www/index.php/view/map/?repository=faunalia&project=faunalia_map
Zooming in I the points are displayed:
http://www.faunalia.it/map/lizmap/www/index.php/view/map/?repository=faunalia&project=faunalia_map&lon=14965894.521554478&lat=4660684.360578368&zoom=2
Same data in EPSG:4326 (of course, without background map) are shown:
http://www2.faunalia.eu/map/lizmap/www/index.php/view/map/?repository=faunalia&project=check

I suspect this may be due to its bounding box; however, I have set up on the OWS properties 19472183 to prevent this (form the canvas a Xmax is 17087388).

I'm available for debugging.

**Comment by rldhont** [comment]
Hi @pcav, did you solved this issue ?
I think it was a QGIS-Server issue. Which QGIS Server do you use ?

**Comment by pcav** [comment]
You are probably right, now with 2.14.1 it seems to work fine:
http://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=faunalia_it
Thanks.
