### ISSUE TITLE
Attribute table  problems (no zoom and center tools) with lizmap 3

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#230]
Hi,
I am using lizmap 2.x since several months with Qgis server 2.8 and all is OK.
I just try to test the last version (lizmap 3) and i have a question about the selection tool in the attribute table.

In the template project (Montpellier Transport), when you select the attribute table for the layer “District”, there are 3 buttons for each row (Select, zoom and center).
When I try with my project, I only have the select button. Moreover, the link between the table and the map seems to not work (if i use the filter, nothing happens on the map). I have check the OWS configuration for my layer, but i cannot find the source of this problem. I also try with Postgis Layer and local shp layer, with no difference.

Thanks a lot for your help.

**Comment by rldhont** [comment]
Did you use the dev version of the plugin ?

**Comment by geoek** [comment]
Thanks a lot !! I actually had not installed the new version of the plugin.
Everythinks work now !
