### ISSUE TITLE
Do not expose via WFS is not tacking into account in Form

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2304]
### What is the bug?
The checkbox **Do not expose via WFS** in the Vector layer properties in fields tab seems to be not taking into account in the edition form.

### Steps to reproduce the issue

1. Go to **Fields** tab in the **Vector layer properties** in QGIS Desktop
2. Click on **Do not expose via WFS** in Configuration column
3. Publish the project to lizmap
4. Add an element to the layer
5. See that the field is in the form

### Expected behavior
Like with QGIS 3.10, the checkbox **Do not expose via WFS** has to be tacking into account in the edition form.

### Environment

 - Lizmap version: 3.4.*
 - QGIS Server FULL version: 3.16.*
 - QGIS Desktop FULL version: 3.16.*

**Comment by nboisteault** [comment]
@rldhont I confirm the issue. Now looking for the bug.

**Comment by nboisteault** [comment]
This .qgs part has changed from 3.10 (left) to 3.16 (right)

![image](https://user-images.githubusercontent.com/2145040/121553706-cac38c80-ca11-11eb-96af-a50c59681169.png)

**Comment by rldhont** [comment]
ok, so we have to check the new attribute `configurationFlag`

**Comment by nboisteault** [comment]
@rldhont there is also a 'Not searchable' parameter. Should we take care of it later?

![image](https://user-images.githubusercontent.com/2145040/121554397-7076fb80-ca12-11eb-9bf2-328738201788.png)

**Comment by rldhont** [comment]
> @rldhont there is also a 'Not searchable' parameter. Should we take care of it later?
> 

Probably

**Comment by nboisteault** [comment]
@rldhont @laurentj 
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/qgisProject.class.php#L801
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/lib/Project/QgisProject.php#L1395

With have duplicate code. Should we delete first file?

**Comment by rldhont** [comment]
I was thinking the one is kept for compatibility with module and reuse the second.

**Comment by nboisteault** [comment]
So I just fix the second?
