### ISSUE TITLE
Is there anything wrong with time manager on LM 3.3.15 and QGIS Server 3.16LTR?

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2305]
Hi all,
I had a look at the demo

https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=time_manager_earthquake

and everything seems ok to me (not sure what version of LMWC and QGIS Server is used)

I then download the demo project 

https://demo.lizmap.com/lizmap/index.php/view/media/getMedia?repository=feat1&project=time_manager_earthquake&path=/media/time_manager_earthquake.zip

and uploaded to a testing server of mine with LMWC 3.3.15 with QGIS Server 3.16, and the time manager tool works in a different way (seems bugged to me):

In the demo the features visible on the map are the one filtered by time manager, and they show with the proper symbology, while in the same project and data (and LMWC config file) on LM 3.3.15 the animated data is rendered "on top" of the features from the same layer (not animated) and they have a different symbology.

Moreover in the time manager control there is a checkbox that seems to enable/disable the rendering of animated data, but the checked/unchecked state seems to be exactly the same.

On the same installation I tried to animated my own (PostGIS) point data with a date/time column (which works fine for the "filter" functionality) but at no avail: time manager starts, it allow to use the date controller and play/pause, but no points are rendered in the map.

Any help would be appreciated.

![Peek 2021-05-26 20-08](https://user-images.githubusercontent.com/1951107/119718063-0a5d7680-be5f-11eb-971c-26d324df3b9d.gif)

**Comment by gioman** [comment]
Nevermind, I updated to 3.4.3 and everything is fine now... time to update ;)

**Comment by Gustry** [comment]
Indeed, these demo have been made with LWC 3.4 so the CFG file is not compatible with LWC 3.3.

And also, only LWC 3.4 is supporting fully QGIS 3.16.
