### ISSUE TITLE
If layer is filtered by user then the symbology classes of not visible features should not show in layer legend

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2307]
LMWC 3.4.3 and QGIS Server 3.16 on Ubuntu Server 20.04

Not sure if this is to be considered a bug or a feature request or if is even doable.

If a layer is filtered by user/group then when the project is loaded the legend of the filtered layer will show also the classes of features that a particular user is not allowed to see (if the layer has a categorized symbology).

The same apply to the "filter data with form" functionality, where the user will be potentially presented with options (for example when using checkboxes) that are about features he/she does not have access to.

**Comment by Gustry** [comment]
It's not yet done, but with all the development done in Lizmap Web Client 3.7 related to the layer tree
