### ISSUE TITLE
"Filter data with form" exported file has .ods extension but is GML

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2308]
LMWC 3.4.3 and QGIS Server 3.16 on Ubuntu Server 20.04

I'm using Firefox on Linux here, and the export function of "Filter data with form" save the file with a .ods extension, but in reality the file is a GML. Unsure if this is on purpose, if I'm missing something or if is just a bug.

**Comment by Gustry** [comment]
Are you talking about this menu ? https://github.com/3liz/qgis-wfsOutputExtension/blob/master/README.md the dropdown one.
Which version of wfsOutputExtension ? (the latest is 1.5.3)

**Comment by gioman** [comment]
> Are you talking about this menu ? https://github.com/3liz/qgis-wfsOutputExtension/blob/master/README.md the dropdown one.
> Which version of wfsOutputExtension ? (the latest is 1.5.3)

@Gustry not using wfsOutputExtension in this case. The menu I'm talking is

![Screenshot_20210527_085633](https://user-images.githubusercontent.com/1951107/119787777-796fb500-bec9-11eb-8215-bc34689b6df0.png)

**Comment by gioman** [comment]
I left the necessary feedback. Not stale.

**Comment by drillinP** [comment]
fixed in https://github.com/3liz/lizmap-web-client/issues/2308
