### ISSUE TITLE
WFS not sending full response

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#231]
I updated QGIS server from 2.8.2 to 2.8.4 and now WFS responses are truncated.
For example I just have: 
`{"type": "FeatureCollection",
 "bbox": [ 375556.2, 6325103.9, 457955, 6424288.8],
 "features": [`
It seems it is a lizmap bug (compatibilty issue?). If I request QGIS Server directly there is no problem.

Bug with this url :

http://92.243.19.0/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=pnrlg&project=lizmap_pnr_lg&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=Communes&PROPERTYNAME=geometry%2Cnom&OUTPUTFORMAT=GeoJSON

Not this : 

http://92.243.19.0/cgi-bin/qgis_mapserv.fcgi?map=/var/www/html/lizmap-projets/PNRLG/LIZMAP/lizmap_pnr_lg.qgs&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=Communes&PROPERTYNAME=geometry%2Cnom&OUTPUTFORMAT=GeoJSON

**Comment by rldhont** [comment]
Which Lizmap Web Client do you use ?

**Comment by nboisteault** [comment]
Lizmap 2.12.1

**Comment by nboisteault** [comment]
I saw this issue with QGIS server 2.8.3 and lizmap web client 2.11 too.

**Comment by rldhont** [comment]
Do you this issue with all layers ? or just this one ?
Can you test with a simplify layers ?

**Comment by nboisteault** [comment]
Same issue here : 

http://92.243.19.0/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=epidor&project=Epidor&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=dernieres_observations&PROPERTYNAME=geometry%2Cnom&OUTPUTFORMAT=GeoJSON

and not here : 

http://92.243.19.0/cgi-bin/qgis_mapserv.fcgi?map=/var/www/html/lizmap-projets/EPIDOR/Epidor.qgs&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=dernieres_observations&PROPERTYNAME=geometry%2Cnom&OUTPUTFORMAT=GeoJSON

**Comment by rldhont** [comment]
What's differences between the layers in the data ?

**Comment by nboisteault** [comment]
Sorry I didn't understand.

**Comment by rldhont** [comment]
Sorry, I think it's 2 URLS with 2 different layers. But it was the same layer but on URL from Lizmap and one form QGIS-Server.

Are all layers the same ?

**Comment by nboisteault** [comment]
In the first example it is the same layer, one via lizmap this other via qgis-server.
In the second example it is a more lightweight layer.
I'm not sure I'm anwsering your question. We can speak french if you want.

**Comment by rldhont** [comment]
Je voudrais savoir si pour toutes tes couches publié en WFS tu as ce problème ?
Ensuite dans la configuration Lizmap, Quelle méthode utilises-tu pour les requêtes PHP ou curl ?

**Comment by nboisteault** [comment]
Oui même problème pour toutes les couches publiés en WFS.
J'utilise curl. Merci de ton aide.

**Comment by nboisteault** [comment]
Je viens de tester avec PHP et le problème disparaît.
