### ISSUE TITLE
Bookmark print

### ISSUE THREAD

**Issue by cristomoya** [3liz/lizmap-web-client#232]
Is it possible to place a visible mark in print?

**Comment by gioman** [comment]
@cristomoya do you mean a "notes layer" that to allow users draw points/lines/polygons and have them printed in layouts?

**Comment by cristomoya** [comment]
yes

**Comment by gioman** [comment]
@cristomoya there is already a feature request here https://github.com/3liz/lizmap-web-client/issues/48 that probably is already fixed with https://github.com/3liz/lizmap-web-client/issues/119 but that I haven't tested yet.

**Comment by rldhont** [comment]
QGIS Server 2.16 will probably help lizmap to propose it.

**Comment by nboisteault** [comment]
Possible since Lizmap 3.4.0 => https://github.com/3liz/lizmap-web-client/releases/tag/3.4.0
