### ISSUE TITLE
export - output extensions

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2320]
hi

by default the avaiable file formats are GeoJSON and GML

![imagem](https://user-images.githubusercontent.com/10053874/120360468-ad4f3e00-c300-11eb-9935-d3e63866fcba.png)
maybe related with https://github.com/3liz/lizmap-web-client/issues/2308

PS: the wfsOutputExtension plugin is not recognized

thanks

LMWC 3.4.4-pre and QGIS Server 3.16 on Ubuntu Server 20.04

**Comment by Gustry** [comment]
Lizmap Web Client is not dealing with WfsOutputExtension.

WfsOutputExtension is only updating the GetCapabilities on QGIS Server side. You would need to check you QGIS Server setup.
Lizmap Web Client is listing formats available in the GetCapabilities document.

Keep in mind that the GetCapabiltiies is cached by Lizmap. You may want to clean the cache.

**Comment by josemvm** [comment]
good morning @Gustry 

thanks for your answer

> Keep in mind that the GetCapabiltiies is cached by Lizmap. You may want to clean the cache.

yes, maybe a cache problem


just a small detail on formats added by the plugin:

from table (lower case)
![tableE](https://user-images.githubusercontent.com/10053874/120449347-4032bb80-c387-11eb-8501-7544c4561430.png)

from selection tool (upper case)
![selectionE](https://user-images.githubusercontent.com/10053874/120449378-49238d00-c387-11eb-92c1-b3d4a4650d29.png)

thanks

**Comment by josemvm** [comment]
good morning @Gustry 

thanks for your answer

> Keep in mind that the GetCapabiltiies is cached by Lizmap. You may want to clean the cache.

yes, maybe a cache problem


just a small detail on formats added by the plugin:

from table (lower case)
![tableE](https://user-images.githubusercontent.com/10053874/120449347-4032bb80-c387-11eb-8501-7544c4561430.png)

from selection tool (upper case)
![selectionE](https://user-images.githubusercontent.com/10053874/120449378-49238d00-c387-11eb-92c1-b3d4a4650d29.png)

thanks

**Comment by josemvm** [comment]
good morning @Gustry 

thanks for your answer

> Keep in mind that the GetCapabiltiies is cached by Lizmap. You may want to clean the cache.

yes, maybe a cache problem


just a small detail on formats added by the plugin:

from table (lower case)
![tableE](https://user-images.githubusercontent.com/10053874/120449347-4032bb80-c387-11eb-8501-7544c4561430.png)

from selection tool (upper case)
![selectionE](https://user-images.githubusercontent.com/10053874/120449378-49238d00-c387-11eb-92c1-b3d4a4650d29.png)

thanks

**Comment by josemvm** [comment]
good morning @Gustry 

thanks for your answer

> Keep in mind that the GetCapabiltiies is cached by Lizmap. You may want to clean the cache.

yes, maybe a cache problem


just a small detail on formats added by the plugin:

from table (lower case)
![tableE](https://user-images.githubusercontent.com/10053874/120449347-4032bb80-c387-11eb-8501-7544c4561430.png)

from selection tool (upper case)
![selectionE](https://user-images.githubusercontent.com/10053874/120449378-49238d00-c387-11eb-92c1-b3d4a4650d29.png)

thanks
