### ISSUE TITLE
Optimise performance of form filters 

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#2325]
### Description

Following the logic from https://docs.lizmap.com/next/en/publish/lizmap_plugin/form_filtering.html
This works nicely when the underlying data doesn't have a lot of features. With many features, the form fields are not populated.

What is the best way to optimise the request `REQUEST=getUniqueValues`

Is the request from the WFS OGC API or natively from QGIS Server because It is not documented within QGIS

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16.3
 - OS (Windows, Linux, MacOS, Android…):  Linux
 - Browser (Firefox, Chrome…): Firefox, Safari
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL 13

**Comment by mdouchin** [comment]
This feature works only at present for PostgreSQL, SQLite and GeoPackage layers.

Lizmap Web Client runs SQL queries against the database, which will work much better for PostgreSQL.

We would like to use the QGIS Server lizmap plugin to let QGIS manage the distinct, count, and filtering the data, to allow more vector layer formats.

* Do you use a PostgreSQL database layer or SQLite/GeoPackage ?
* Have you configured a splitter ? https://docs.lizmap.com/current/fr/publish/lizmap_plugin/form_filtering.html#unique-values

**Comment by NyakudyaA** [comment]
thanks, @mdouchin Yes, I already use PostgreSQL and the feature count is just below 200k. Can you point me to where the SQL queries are being generated in the code. I will like to profile where the bottleneck seems to be

**Comment by mdouchin** [comment]
It is a simple `count(*)` with a `GROUP BY` of no splitter is defined
https://github.com/3liz/lizmap-web-client/blob/release_3_4/lizmap/modules/filter/classes/filterDatasource.class.php#L189

else it is a bit more complicated with the use of a regular expression split
https://github.com/3liz/lizmap-web-client/blob/release_3_4/lizmap/modules/filter/classes/filterDatasource.class.php#L211

Make sure you have the needed index for the column you use in the "unique values" search form field, and try to `VACUUM ANALYZE the_table;`

**Comment by gubuntu** [comment]
I'm working with @NyakudyaA on this

GetFeatureCount also fails 

I have VACUUM ANALYZED and the filter field is indexed

**Comment by gubuntu** [comment]
you can inspect the problem by trying the filter at https://gis1.adaxasuite.com

**Comment by NyakudyaA** [comment]
@gubuntu I think i found the bug in the setup. I will have to check it out if the DB connection can use service files. They will need to be referenced within the lizmap container with the proper env variable. I will test and revert here

**Comment by NyakudyaA** [comment]
I can confirm the fix works
