### ISSUE TITLE
[docker] allow bigger file to be uploaded

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-web-client#2328]
### Is your feature request related to a problem? Please describe
I use a postgis layer with a file upload field > we are limited to a 2M file upload file size

### Describe the solution you'd like
allow to set the upload_max_filesize parameter in /etc/php7/php.ini at container creation, with ENV variables

### Describe alternatives you've considered
using this docker image through https://github.com/3liz/lizmap-docker-compose, I manage to change it manually (had to modify nginx.conf file and /etc/php7/php.ini manually directly in the running container

Modifying lizmap-entrypoint.sh should be the solution?
sed -i "/^upload_max_filesize =/c\upload_max_filesize = ${UPLOAD_MAX_FILESIZE:-2M}" /etc/php7/php.ini

**Comment by gerald2545** [comment]
steps to manually change this limit (OK til the container is not restarted) with docker-compose project :
modify nginx configuration

- add client_max_body_size 10M; in lizmap/etc/nginx.conf > http directive
- docker-compose restart

modify php configuration in lizmap runing container :  

- sudo docker exec -it lizmap-docker-compose-master_lizmap_1 /bin/sh
- sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 10M/' /etc/php7/php.ini
- ps aux

```
PID   USER     TIME  COMMAND
    1 root      0:00 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.conf)
   43 1011      0:00 {php-fpm7} php-fpm: pool www
   44 1011      0:00 {php-fpm7} php-fpm: pool www
   45 1011      0:00 {php-fpm7} php-fpm: pool www
```

- kill 1

- php-fpm restarts alone > OK

**Comment by dmarteau** [comment]
You don't need to do this, 

You may override php configuration by adding configuration  files in /etc/php7/conf.d/mycustomconfig.: those files will overwrite the settings in php.ini.

There is two options for you do that with Docker:
* Mount a configuration file at the proper location i.e /etc/php7/conf.d/mycustomconfig.ini
* Or  set the PHP_INI env variable with the configuration you want to override (it is easy to do multi line variable in yaml with docker-compose) the file /etc/php7/conf.d/00_lizmap.ini will be created with the content.

> Modifying lizmap-entrypoint.sh should be the solution?

There is too many php options for that, only options for overriding php-fpm/www.conf have been exposed as env variable.

**Comment by gerald2545** [comment]
nice ;)  
tried this without success for the moment  
I added the following line in docker-compose.yml  
PHP_INI: 'upload_max_filesize = 11M'  

then docker-compose up -d  

had a look in logs of lizmap container :   
+ '[' '!' -z upload_max_filesize '=' 11M ]
sh: =: unknown operand


I tried different things...escape the =, double quote inside the quote...but I always get the same error....
how do I have to write the config in PHP_INI env variable?

Thank you

Gérald

**Comment by dmarteau** [comment]
It seems you hit a bug, try mounting the ini file instead while we are fixing this.

**Comment by dmarteau** [comment]
Fixed

**Comment by gerald2545** [comment]
nice, it works mouting the ini file

**Comment by undertaker12** [comment]
Good morning, I have the same issue. I cannot send files larger than 2 MB. I have the setup running through Docker Compose. Could someone fix this error for me? When I try to upload a file on the website, I receive the message to contact the administrator.
