### ISSUE TITLE
Allow remote raster layers to be used within QGIS Server projects

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/lizmap-web-client#2329]
# Problem

We need to be able to use remote layers from GDAL viscurl in projects.

Currently, we get the following error

![rem](https://user-images.githubusercontent.com/2510900/120930271-d8fd6a00-c6ec-11eb-8011-bb1e732ffabe.png)

https://github.com/3liz/lizmap-web-client/issues/2324

**Comment by gubuntu** [comment]
is this not a QGIS server or lizmap/docker-qgis-server issue?

**Comment by NyakudyaA** [comment]
> is this not a QGIS server or lizmap/docker-qgis-server issue?

QGIS Server can render remote cog without any problem as long as you have defined the env variables

**Comment by gubuntu** [comment]
Actually this is a BUG

I loaded and published a COG and it worked fine. 

The next time I opened the project I got the same error as the OP when I tried to open the LizMap plugin. 

LizMap seems to see the COG protocol url as if it were a file that needs a relative reference, yet it is a url so it cannot be stored in a relative path!

**Comment by gubuntu** [comment]
interesting, it only raises this error when the layer is toggled on. If it is off, the the plugin dialog opens with no error.

**Comment by NyakudyaA** [comment]
Closing the issue here as this is more a bug with the QGIS plugin than the client.
