### ISSUE TITLE
Testing Lizmap master (3.0) in Windows SO environment

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#233]
Hi guys, i'm using the lizmap web client 2.11.3 and lizmap web client 2.12.0 and work fine with OSGeo4W 32-bits in Windows.

For lizmap master when i try to open the main page, i have this error:

"Warning: require(**DIR**/core/jApp.class.php) [function.require]: failed to open stream: No such file or directory in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lib\jelix\init.php on line 37"

"Fatal error: require() [function.require]: Failed opening required '**DIR**/core/jApp.class.php' (include_path='.;C:\OSGeo4W\Apache\php\PEAR') in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lib\jelix\init.php on line 37"

When i check the path, the files are in the folder.

When i do the check of jelix_check_server.php i have this error:
Check your configuration server for Jelix 1.6.5pre.3192
Bad PHP version

Fatal error: Call to undefined method jHtmlInstallChecker::showNotice() in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lib\jelix_check_server.php on line 413

My PHP version in OSGeo4W 32bits is 5.2.5

Regards
João

**Comment by jonnyforestGIS** [comment]
[UPDATE]
So i think the problem is the version of PHP in OSGeo4W (5.2.5).

I search for anwsers and i saw this github issue (https://github.com/picocms/Pico/issues/65):

You have to have PHP 5.3 installed to use the "__DIR__" magic constant: http://php.net/manual/en/language.constants.predefined.php To preserve compability with PHP 5.2 the developers would have to replace "__DIR__" with `dirname(__FILE__)`

Regards
João

**Comment by rldhont** [comment]
Hi @jonnyforestGIS 

We don't recommend OSGeo4W because PHP and Apache packages was not updated for years.

You can test Lizmap on Windows with your own APache and PHP installation, or help for update Apache and PHP OSGeo4W packages.

**Comment by jonnyforestGIS** [comment]
Hi @rldhont, thanks for the answer.
I will try to speak with osge4w maintainers to see what is needed.

It's possible with a separate apache installer with php works fine with QGIS Server? The QGIS 

Server works independetly or it's necessary configure apache for QGIS Server configurations?

Regards
João

**Comment by rldhont** [comment]
You can use a separate Apache with Php. You don't have to install the OSGeo4W Apache and PHP packages to use QGIS Server on Windows.

**Comment by jonnyforestGIS** [comment]
OK @rlhont.
Another thing do you need help in the documentation, translation, tutorials or in lizmap?

**Comment by jonnyforestGIS** [comment]
[Update]
Hi,
@rldhont  I use stack builder from PostgreSQL to install a different version of Apache2.4.18/PHP5.5.31-1.

Some notes:
This new versions of PHP, don't bring sqlite.dll so it's is need to compile and made the pecl extensions. As alternative, i use the pgsql driver to create the information tables of the jelix instalation wizard.

I run the install.php and followed the wizard and now works. I use the WMS of qgisserver in the Lizmap configuration.

I'm using QGIS 2.12.3 and QGIS Server (OSGeo4W 32-bits).
I test the new interface and compare with the Linux version, at this time the GetPrint is not working in Windows 7 64-bits.

When i try to print open a blank page. I use the developer webtools and i see that  the method GET is giving STATUS CODE 500 Internal Server Error. 

I test: 
http://localhost/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities - Is working

Another thing the port is 8080 to Apache 2.4/ PHP5.5 and i'm using 80 for OSGeo4W Apache.

It's necessary give some permission in apache PostgreSQL to access to the folder of QGIS?

Regards
João

**Comment by rldhont** [comment]
Hi @jonnyforestGIS 

Thanks for yout tests. You can contribute by updating the documentation:
https://github.com/3liz/lizmap-documentation
And I think you can describe the steps for installation on windows with the PostgreSQL stack:
https://github.com/3liz/lizmap-documentation/tree/master/source/admin_guide/installation

---
The GetPrint request can fail because of HTML in the composition. To verify it, you have to take a look at the Apache logs and test with a simplify composition.

Thanks again for your contributions.

**Comment by jonnyforestGIS** [comment]
OK :+1: @rldhont  
I hope to see you in Girona :) Until then i will try to help to give feedback and update documentation.
Can i use github for feedback or do you want another way of communication?

**Comment by jonnyforestGIS** [comment]
[UPDATE]
Reminder:
Apache 2.4-18/PHP 5.5.31-1 (Stack Builder PostgreSQL) - Used as Document Root for LizMap WebClient-master.

Apache 2.2/PHP 5.2.25 (OSGeo4W Installer) - Used in LizMap configuration in WMS Server link.

Global Results Using the PostgreQL Apache/PHP version:
- Run the installer of LizMap Client Master - :+1:  (without extension sqlite, i use the driver pgsql and create a database inside PostgreSQL to store the information of Jelix)
- Add in LizMap configuration the wms server qgis link: http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe :+1: 
- Test the default lizmap demo :+1: 
- Add new repository with my own information :+1: 
- Query, select and export information :+1: 
- Priting :-1: 

Results of Priting:
Even with a simple composition:
Simple Map item, legend item and scale item throw me  a blank page with the method GET is giving STATUS CODE 500 Internal Server Error. 

The acess.log of PostgreSQL Apache (QGIS Server 2.12.3):
127.0.0.1 - - [04/Feb/2016:12:29:50 +0000] "GET /lizmap/lizmap-web-client-master/lizmap/www/index.php/view/media/illustration?repository=nuts&project=nuts3 HTTP/1.1" 200 59473

The error.log of PostgreSQL Apache (QGIS Server 2.12.3):
error.log PostgreSQL Apache
[Thu Feb 04 15:10:07.782425 2016] [:error] [pid 2816:tid 804] [client 127.0.0.1:58496] PHP Fatal error:  Call to undefined function curl_init() in C:\\Program Files (x86)\\PostgreSQL\\EnterpriseDB-ApachePHP\\apache\\www\\lizmap\\lizmap-web-client-master\\lizmap\\modules\\lizmap\\controllers\\service.classic.php on line 769, referer: http://localhost:8080/lizmap/lizmap-web-client-master/lizmap/www/index.php/view/map/?repository=montpellier&project=montpellier

I think the problem is that the curl is not loading in the apache postgresql server, not sure.
Dahm, .dll windows libraries :-1: 

Regards
João

**Comment by rldhont** [comment]
You can use php instead of curl if you update the lizmap configuration.

**Comment by jonnyforestGIS** [comment]
it's strange because, i don't change this parameter. In admin lizmap configuration, i have by default php. but he try to call the curl in both cases giving the same error pointing to service.classic.php.

**Comment by Abelon38** [comment]
Hi guys!

My problem related Media is that Pictures stop showing up after changed port on apache from 80 to 8080. I tried to make some changes on file popup.class.php but doesnt work. I will appreciate any suggestion?
Thanks for your time!
Abel

**Comment by jonnyforestGIS** [comment]
@rldhont  I think this issue can be close. Regards Joao
