### ISSUE TITLE
lizmap logs - persistent warning 

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2330]
hi

i have notice about this persistent warning, which is always filling up the lizmap logs capacity... requiring to delete the log file in lizmap logs administration

```
2021-06-07 12:15:26	xxx.xxx.xxx.xxx 	warning	2021-06-07 12:15:26	[2]	touch(): Utime failed: Operation not permitted	/var/www/html/lizmap-web-client-3.4.4-pre/lib/jelix-plugins/cache/file/file.cache.php	183
```
```
2021-06-07 12:15:24	xxx.xxx.xxx.xxx 	warning	2021-06-07 12:15:24	[2]	touch(): Utime failed: Operation not permitted	/var/www/html/lizmap-web-client-3.4.4-pre/lib/jelix-plugins/cache/file/file.cache.php	189
```

thanks for your attention

LMWC 3.4.4-pre and QGIS Server 3.16 on Ubuntu Server 20.04

**Comment by gerald2545** [comment]
seems to be caused by a permission error in 
 ```
public function set ($key,$var,$ttl=0){

        $filePath = $this->_getCacheFilePath($key);
        $this->_createDir(dirname($filePath));
        if ($this->_setFileContent ($filePath,$var)) {

            switch($ttl) {
                case 0:
                    touch($filePath, time() + 3650*24*3600);
                    break;
                default:
                    if ($ttl <= 2592000) {
                        $ttl += time();
                    }
                    touch($filePath,$ttl);
                    break;
            }
            return true;
        }
        return false;
    }
```

you don't run lizmap in docker, isn't it?
could you check the cache folder permission?

**Comment by josemvm** [comment]
@gerald2545 no, i'm not using lizmap in docker
cache folder permission 775 for root:www-data

**Comment by gerald2545** [comment]
Can you reproduce if you touch your file in command line in this folder with the same user used by the system to run lizmap?

**Comment by ygorigor** [comment]
@josemvm did you try this command `lizmap/install/set_rights.sh www-data www-data`

**Comment by josemvm** [comment]
@ygorigor you are right, my mistake... thanks
thanks to @gerald2545 too
