### ISSUE TITLE
Bug with the connection to the database when editing on lizmap

### ISSUE THREAD

**Issue by drillinP** [3liz/lizmap-web-client#2332]
### What is the bug?
A bug with the connection to the database when editing on lizmap.
when lizmap retrieves the datasource of the QGIS project the host is in quotes. However, lizmap did not plan to retrieve a host between quotes.

### Steps to reproduce the issue

1. Use a project QGIS without using service for connect to the database
2. Configure to lizmap
3. Click to edit a layer in lizmap
4. Editing loads continuously

 - Lizmap version: 3.4.*

**Comment by rldhont** [comment]
@mdouchin je sais comment corriger
