### ISSUE TITLE
Missing class when using altiProfil module with docker LWC container

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2346]
Using https://github.com/3liz/lizmap-docker-compose I added altiProfil module to LWC container. 
An error occurs when I use altiProfil module 
`error	[0]	Class 'PDO' not found	/www/lizmap/lizmap-modules/altiProfil/classes/altiServicesFromDB.class.php`

This issue occurs only in docker version of LWC.

 - Lizmap version: 3.5.0-pre
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into PostgreSQL

**Comment by laurentj** [comment]
Fixed for lizmap 3.5.8

**Comment by laurentj** [comment]
commit 9b56efa2d0017b5bdd33951e3ca20c3ad4649b76
