### ISSUE TITLE
Problèmes fond IGN

### ISSUE THREAD

**Issue by brulien** [3liz/lizmap-web-client#2349]
Bonjour,

L'issue #2206 a été close sans plus de précision. Or, il est toujours effectif en version 3.4.3 .

Cordialement,

Julien Brun

**Comment by Gustry** [comment]
Le ticket #2206 a été clos avec la référence d'un commit https://github.com/3liz/lizmap-web-client/commit/116ee84928158b6623beb82dd1847d9c769fc412

Le fix est dans la dernière version de Lizmap Web Client 3.3.16 et 3.4.4
