### ISSUE TITLE
Internal server error lors de l'impression en HTTPS

### ISSUE THREAD

**Issue by ThomasSIGT** [3liz/lizmap-web-client#235]
Bonjour,

Nous avons mis en place une solution LizMap (Projet QGIS) chez un client, avec un applicatif ASP.Net qui appelle l'URL du projet LizMap pour visualiser la carte. Avec toute la chaîne en HTTP (IIS & Apache), tout fonctionne bien (visualisation, impression).

L'environnement technique est le suivant : Windows Server 2012 / Suite OsGeo4W (QGIS 2.8) / LizMap 2.11

Le client nous a demandé de sécuriser l'accès avec un certificat autosigné. Avec la partie IIS en HTTPS et Apache en HTTP tout fonctionne bien (visualisation, impression).Avec toute la chaîne en HTTPS, la partie visualisation de LizMap fonctionne bien, mais l'impression provoque une erreur interne du serveur.  

Les logs semble montrer qu'un fichier javascript version 1.10.3 est recherché dans le repository 2.11 de LizMap : 

File does not exist: C:/OSGeo4W/apache/htdocs/lizmap-web-client-2.11.0/lizmap/www/js/jquery-ui-1.10.3.custom.min.js, referer: https://monserveur:30443/lizmap-web-client-2.11.0/lizmap/www/index.php/jauth/login/form?login=admin&failed=1
File does not exist: C:/OSGeo4W/apache/htdocs/lizmap-web-client-2.11.0/lizmap/www/js/jquery-ui-1.10.3.custom.min.js, referer: https://monserveur:30443/lizmap-web-client-2.11.0/lizmap/www/index.php/view/
File does not exist: C:/OSGeo4W/apache/htdocs/lizmap-web-client-2.11.0/lizmap/www/js/jquery-ui-1.10.3.custom.min.js, referer: https://monserveur:30443/lizmap-web-client-2.11.0/lizmap/www/admin.php/jauthdb_admin/user/?j_user_login=admin
File does not exist: C:/OSGeo4W/apache/htdocs/lizmap-web-client-2.11.0/lizmap/www/js/jquery-ui-1.10.3.custom.min.js, referer: https://monserveur:30443/lizmap-web-client-2.11.0/lizmap/www/index.php/view/

Le certificat a été généré avec makecert, renseigné dans IIS puis exporté et converti avec openssl pour être "lisible" par Apache. Le VirtualHost a été renseigné et les différents fichiers complétés (httpd.conf, httpd-ssl.conf, etc.)

Avez-vous une idée de l'origine du problème ? Faut-il définir un VirtualHost pour l'URL qui correspond à l'impression ou activer une option particulière ?

Merci d'avance.

**Comment by rldhont** [comment]
Bonjour,

Votre problème ne vient pas de l'utilisation du HTTPS ou de Lizmap (aucun JS n'intervient pour la génération du pdf), il est plutôt lié à QGIS Server.

Avez-vous fait des tests en attaquant directement QGIS-Server ?

Ensuite je vous conseille de passer à Lizmap Web Client 2.12.2.

**Comment by ThomasSIGT** [comment]
Bonjour, merci pour votre réponse. 

J'ai fait le lien entre l'erreur et le HTTPS côté LizMap / Apache car c'est la seule différence entre notre environnement de dev (où l'impression ne fonctionne plus) et l'environnement de production chez le client (où l'impression fonctionne toujours). 

l'URL qui fait "planter" est de la forme : 

https://[serveur]:[port]/lizmap-web-client-2.11.0/lizmap/www/index.php/lizmap/service/?repository=[erpo]&project=projet]&SERVICE=WMS&VERSION=1.3&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:3857&DPI=300&TEMPLATE=FormatA4&map0:extent=271109.963990438,6226048.760616362,275226.83098956203,6228955.846523639&map0:scale=18056&map0:grid_interval_x=451.4&map0:grid_interval_y=451.4&map0:LAYERS=[liste_couches]&LAYERS=[liste_couches]

Comment puis-je tester l'impression en attaquant directement QGIS-Server ? 

En parallèle je teste également la 2.12.2 et je vous fais un retour.

**Comment by rldhont** [comment]
Pour tester, il vous suffit de remplacer le début de l'URL
`https://[serveur]:[port]/lizmap-web-client-2.11.0/lizmap/www/index.php/lizmap/service/?repository=[erpo]&project=projet]`
par
`https://[serveur]:[port]/[url vers qgis server]?MAP=[chemin sur le serveur vers le projet.qgs]`

Autre question, est-ce que la version de QGIS Server a changé entre les 2 environnements ?

**Comment by ThomasSIGT** [comment]
l'URL suivante répond (affichage des capabilities) 

https://[serveur]:[port]/qgis/qgis_mapserv.fcgi.exe?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&MAP=[projet.qgs]

En revanche l'URL d'impression ne fonctionne effectivement pas (REQUEST=Getprint, etc.)

Côté environnement QGIS notre serveur de dev est en 2.8.1 et la production chez le client en 2.8.2. Cela pourrait-il expliquer que ça fonctionne dans la 2.8.2 et non la 2.8.1 ?

**Comment by rldhont** [comment]
Si les versions sont différentes, la vrai différence est là.

Je vous invite à avoir la même version dans les 2 environnements. Sachant que la version 2.8.2 corrige des problèmes de la version 2.8.1.

Vous pouvez ensuite dans votre version de dev tester les monter de version afin de valdier celle-ci avant de les déployer en production.

Si le problème est corrigé, merci de fermer cette issue. Merci

**Comment by ThomasSIGT** [comment]
Bonjour, 

Effectivement le passage à la 2.8.2 de Qgis Server a réglé le problème. Les deux environnements ayant été installés à peu de temps d'intervalle via le package OsGeo4W, la différence de version est passé à la trappe. 

Merci beaucoup pour votre aide.
