### ISSUE TITLE
LizMap - Themes

### ISSUE THREAD

**Issue by Uoppa** [3liz/lizmap-web-client#2354]
Good evening.

Anyone know how to change the theme in a project shown in LizMap?
I have manually set up two themes in my project in QGIS and, changing both of them, I see that they work. In the project displayed with LizMap, although the two themes appear as existing and are displayed through the eye icon present in the legend, if I change between one theme and another nothing happens.

Thanks for your help.
A greeting,

Riccardo

 - Lizmap version: 3.4
 - QGIS Server FULL version: 
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): I'm using OsGeoLive
 - Browser (Firefox, Chrome…): Firefox

**Comment by nboisteault** [comment]
Hi @Uoppa ,
Could you provide a minimal project showing your issue?

**Comment by Uoppa** [comment]
The problem has been solved.
I had the project and some layers that contained "special" characters such as points and this caused problems. Going to change the name of the project and of the layers by removing the characters (for example from "C.R.T.A._Regione" to "CRTA_Regione") now works perfectly.
I apologize for the inconvenience, I hope this post and this example will be useful for someone.
Thank you very much.

**Comment by nboisteault** [comment]
Indeed QGIS project has to be valid to avoid bugs. To check it : Project => Properties => QGIS Server => Test configuration => Launch.
There is no inconvenience. Bug reports are always welcome :)
