### ISSUE TITLE
LWC 3.5. Zoom by rectangle, or double click not zooming to selected place

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2356]
In LWC 3.5 if I use `Zoom by rectangle` the map is not zoomed to selected location, but to a different place.

### Steps to reproduce the issue

1. Open LWC
2. Click on 'Zoom by rectangle'
3. Select rectangle on map

### Expected behavior
Zoom to selected location

 - Lizmap version: 3.5
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) PostgreSQL 

![zoom](https://user-images.githubusercontent.com/1684359/123208370-9e0a7d00-d4c7-11eb-9072-8627fb61a8cf.gif)

**Comment by nboisteault** [comment]
Confirmed. Working on a fix.
Thanks @ygorigor
