### ISSUE TITLE
visibility expressions in edition tool 

### ISSUE THREAD

**Issue by lionelbargeot** [3liz/lizmap-web-client#2357]
Hi , I have problem to use some new features in LWC 3.4.4

### What is the bug?
group visibility in edition tool

### Steps to reproduce the issue

1. produce a form in qgis with a group of fields
2. control visibility by expression (other_field_value is true/false)
3. Edit the layer in LWC and set other_field_value to false
4. all the fields in the group stay visible

### Expected behavior
the group of fields may not stay visible.

### Environment

 - Lizmap plugin : latest, installed on the qgis server
 - Lizmap version: 3.4.4
 - QGIS Server FULL version: 3.18.1+15buster
 - QGIS Desktop FULL version: 3.18.1+32focal
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Firefox
 - Database : Postgresql 12

**Comment by lionelbargeot** [comment]
Hi
we tried several possibilities. If the expression test a value in a list with yes or no, it's works. But we can't get an expected result with a checkbox. It seems like if the boolean checkbox value is different between js and qgis and then the expression does'nt work in LWC.

**Comment by lionelbargeot** [comment]
Hi
using relational values seems to be unsupported either. We had to build our lists manually to be able to build expressions on.
Finally we get a good form. Thanks a lot for this functionality 
Do you want me to let this as an opened bug ?
Lionel

**Comment by mdouchin** [comment]
Yes, please keep it open, we need to document and test what is supported or not. Perhaps. Could you please give some example of expressions ?

**Comment by nboisteault** [comment]
@lionelbargeot could you test : `"other_field_value" = true OR "other_field_value" = 't'`

Source : https://docs.lizmap.com/current/fr/publish/configuration/layer.html#advanced-form

**Comment by lionelbargeot** [comment]
Hi, 
we have let down working with boolean values, it works fine with text, integer etc ...
thanks for the documentation.

**Comment by u-cav** [comment]
I can confirm this issue with the following setup:

Environment
Lizmap plugin : 3.7.0, installed on the qgis server
Lizmap version: 3.5.0
QGIS Server FULL version: 3.16.14-Hannover
QGIS Desktop FULL version: 3.16.5+15buster
OS: Linux
Browser: Chrome
Database : PostgreSQL 11
