### ISSUE TITLE
 Editing Lizmap WFS with qGIS user-interface not working

### ISSUE THREAD

**Issue by cfsgarcia** [3liz/lizmap-web-client#2358]
### Description
Is it possible to create new features in Lizmap WFS using qGIS application? 
It is working in Lizmap web app via Edition tool (via request: lizmap/edition/saveFeature) but not in qGIS.

### Reproduce
-Publish test3.qgs with a layer for which WFS full permission is granted as well as in Lizmap plugin (Layer Editing tab)
-Sign in to Lizmap, access web app as admin; consume web app and create a new feature -> WORKS!
-Switch to qGIS app, _Layer_ menu > _Add Layers_ > _Add WFS Layer..._ > Retrieve the WFS layers using admin credentials.
-Add layer to qGIS. Edit layer. Create new feature. _Toogle Editing_ and save ->  It's not working. qGIS throws the following:
_Sending of transaction failed: Error transferring https://my_server/lm/index.php/lizmap/service/?repository=sandbox&project=test3&SERVICE=WFS - server replied: Not Implemented_

### Environment
 - Lizmap version: 3.4.1 
 - QGIS Server FULL version: 3.16 LTR
 - QGIS Desktop FULL version: 3.16 LTR
 - OS: Ubuntu
 - Database: Postgres 11.10

**Comment by jancelin** [comment]
+1

**Comment by cfsgarcia** [comment]
Any idea how to edit a Lizmap WFS in qGIS? 
Is it a bug or simply not meant to be edited outside Lizmap web application?

**Comment by cfsgarcia** [comment]
Can enable WFS-Transaction with the following snippet -to insert in to lizmap/modules/lizmap/controllers/service.classic.php::index()
It simply hands over the xml request to qgis server and sends back the response to the client.

`if ($request == 'TRANSACTION' && $service == 'WFS') {
// hand over to native qgisserver to enable WFS-Transaction
# handover to qGISServer via local url
$services = lizmap::getServices();
$wmsServerURL = $services->wmsServerURL;
// Get params
$params = array(
'map' => $project->getRelativeQgisPath(),
'service' => $service
);
// Build http params
$bparams = http_build_query($params);
// Replace some chars (not needed in php 5.4, use the 4th parameter of http_build_query)
$a = array('+', '_', '.', '-');
$b = array('%20', '%5F', '%2E', '%2D');
$bparams = str_replace($a, $b, $bparams);
// Get URL
$url = $wmsServerURL.'?'.$bparams;
$xml = $requestXml;
     
 //Initiate cURL
$curl = curl_init($url);
//Set the Content-Type to text/xml.
curl_setopt ($curl, CURLOPT_HTTPHEADER, array("Content-Type: text/xml"));
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $xml);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
$res_content = curl_exec($curl);
if(curl_errno($curl)){
		throw new Exception(curl_error($curl));
}
curl_close($curl);
     $rep = $this->getResponse('xml');
     $rep->content=$res_content;
     return $rep;
    }`

**Comment by meyerlor** [comment]
sorry to gravedig, but i'm running in the same problem you described. I#Mnot quite sure, if your solution is still working - could you maybe elaborate, where exactly you put your code snippet into the `lizmap/modules/lizmap/controllers/service.classic.php::index()` ? Many thanks!
