### ISSUE TITLE
LizMap legend js

### ISSUE THREAD

**Issue by Uoppa** [3liz/lizmap-web-client#2362]
Good morning.

I am new to the world of LizMap and i have no knowledge of programming and js codes.
I saw on internet that in order to make certain changes in the web output of the QGIS project it is necessary to write some code in JavaScript, some of which are already present as examples on GitHub.
In particular, what I have to do is:

- make the legend and the contents of each layer visible from the opening of the project (currently, as soon as I open the project on the web, the legend with the various layers is visible but not the content of the individual which I have to manually make it visible through the triangle next to each layer);
- increase the size of the width of the legend tree.

While for the second point I do not know if and how it is possible to act, for the first point I know that it is possible to do it but I cannot understand the steps I have to take to succeed. I read about the creation of the "media" folder in the path where I have my QGIS project, the creation of the "js" folder etc. but, although I follow these steps and try to insert some scripts (taken from here: https://github.com/3liz/lizmap-javascript-scripts), nothing changes in the online view.

I hope I was clear.
I am attaching a photo of how I would like it to be viewed IN THE MOMENT WHEN the project is opened online.

![Immagine](https://user-images.githubusercontent.com/82570715/123424914-c1b1ee00-d5c1-11eb-9dd7-b5ee3580da85.png)

Thank you very much for your help.

Riccardo

**Comment by ygorigor** [comment]
@Uoppa you can try to use this script https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/ui/expand-collapse-legend-when-layer-toggled

**Comment by Uoppa** [comment]
Good morning, thanks for your answer.
Can you try to explain to me where I have to write this script, please? I read the LizMap guide (this link: https://docs.lizmap.com/next/fi/publish/customization/javascript.html ) but it doesn't work so I'm thinking that probably I'm doing something wrong.
Thank you so much.

Riccardo

**Comment by ygorigor** [comment]
You need to create tree of folders media/js/default in folder where qgis project file is located. Then put js file in default folder.

**Comment by Uoppa** [comment]
Thank you. I tried with this https://github.com/3liz/lizmap-javascript-scripts/blob/master/library/ui/group_collapse/group_collapse.js and it works perfectly.

Now I'm trying with this (https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/ui/expand-collapse-legend-when-layer-toggled) and it doesn't work, for sure because I don't know how to write the layers name.
I'm attaching the screenshot of the script. The three layers name are respectively "CRTA_Multipoints", "CRTA_Multilines", "CRTA_Multipolygons" and they are grouped in a group that is called "Interventi" (the layer and group names are without quotes).

![Immagine](https://user-images.githubusercontent.com/82570715/123514876-51749c80-d695-11eb-8aa9-03cd7ee3304f.png)

Thank you.

**Comment by ygorigor** [comment]
You don't have to change this file. Just put it as it is. It should work.

**Comment by Uoppa** [comment]
It doesn't work just the same.
As soon as I open the project online, the legend of each layer remains hidden.

**Comment by ygorigor** [comment]
> It doesn't work just the same.
> As soon as I open the project online, the legend of each layer remains hidden.

Ok, now I understood what you want.
The you need only https://github.com/3liz/lizmap-javascript-scripts/blob/master/library/ui/group_collapse/group_collapse.js
Try to add $('#layer-layername td a.expander').click();

**Comment by Uoppa** [comment]
It works!!!
Thank you so so so so so much!

**Comment by Uoppa** [comment]
Sorry to bother you again.

As I asked in the first question, is it possible to set a defined size legend width instead of the (default) size that fits the text content?
Thank you very much.

**Comment by ygorigor** [comment]
> Sorry to bother you again.
> 
> As I asked in the first question, is it possible to set a defined size legend width instead of the (default) size that fits the text content?
> Thank you very much.

Legend image is taken from QGIS, also the sizes

**Comment by Uoppa** [comment]
> > Sorry to bother you again.
> > As I asked in the first question, is it possible to set a defined size legend width instead of the (default) size that fits the text content?
> > Thank you very much.
> 
> Legend image is taken from QGIS, also the sizes

Where can I do this?
Neither among the project properties in QGIS nor in the LizMap plugin I can find references to the size of the legend displayed online. Also if I increase or decrease the size of the Layers Panel on QGIS, it does not change online.

**Comment by ygorigor** [comment]
> > > Sorry to bother you again.
> > > As I asked in the first question, is it possible to set a defined size legend width instead of the (default) size that fits the text content?
> > > Thank you very much.
> > 
> > 
> > Legend image is taken from QGIS, also the sizes
> 
> Where can I do this?
> Neither among the project properties in QGIS nor in the LizMap plugin I can find references to the size of the legend displayed online. Also if I increase or decrease the size of the Layers Panel on QGIS, it does not change online.

There is no config for that. The size depends on number of items in the legend and length of the text.

**Comment by nboisteault** [comment]
@Uoppa You can change get getlegendgraphics parameters, but you'll need some JavaScript to do that :  https://docs.qgis.org/3.16/en/docs/server_manual/services.html#getlegendgraphics

**Comment by Uoppa** [comment]
I don't have any knowledge in JavaScript but I'll give it a try. Thanks a lot for the help!
