### ISSUE TITLE
Affichage des enfants dans un onglet et enfants en cascade

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#2364]
### Description

Savez-vous s'il est possible de placer les éléments fils d'un objet dans un onglet ?

J'ai une couche d'éléments surfaciques (bassins d'orages) sur lesquels j'ai ajouté plusieurs relations 1:N 
--> vers des fiches de suivi de travaux, 
--> vers des fiches de suivi en cas d'orages
--> vers des photos

Au lieu d'avoir ma popup avec les champs de l'élément père puis les 3 listes de fils en dessous, j'aimerai pouvoir placer les listes de fils dans des onglets pour que cela soit plus convivial et plus ergonomique.

Sous QGIS, cette configuration est possible mais sous lizmap, les tableaux de fils semblent forcément affichés en dehors des onglets sous le parent.

A cela s'ajoute le problème suivant : mes éléments fils sont aussi pères d'autres types de fils. En l'occurrence, une fiche de suivi peut avoir des photos (fils) via une autre relation 1:N. De même, si cela s'affiche correctement et fonctionne bien sous QGIS (et sous QField), Lizmap ne semble pas être en capacité d'afficher ces relations et par conséquent il est impossible de les éditer : à titre d'exemple, je n'ai pas réussi à ajouter de photos à une fiche de suivi.

Dernier point qui est lié à 'affichage des enfants : est-il possible de masquer certains champs dans le tableau ? En l'occurrence, les champs qui sont définis comme masqués pour la fonctionnalité "Table attributaire" peuvent ils être masqués aussi dans le tableau des enfants de la popup ?

Merci par avance pour vos retours.

### Environment
 - Lizmap version: 3.4.3
 - QGIS Server FULL version: 3.10.14
 - QGIS Desktop FULL version: 3.10.14
 - OS (Windows, Linux, MacOS, Android…):  W10
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PostGreSQL

**Comment by nboisteault** [comment]
Bonjour,
concernant les éléments fils dans un onglet, je viens de publier un script fonctionnant avec la prochaine version de Lizmap, la 3.5.0. Des infos ici https://github.com/3liz/lizmap-web-client/issues/1772#issuecomment-878240874
Un développement est nécessaire afin de permettre l'édition depuis les popups enfants.

**Comment by Alain-LG** [comment]
Financer le développement, pourquoi pas si les utilisateurs jugent cette fonctionnalité comme étant indispensable. En sachant que via QField, on arrive à faire ce qu'on veut mais que cet outil nécessite des resynchronisations au retour terrain.

Quels sont les montants et délais prévisionnels pour une telle demande ? Faut-il passer par une rédaction de CCTP ? Mais quid des besoins du reste de la communauté dans ce cas.

En ayant cherché dans les différents tickets, ce besoin semble assez récurrent et pourrait sans doute être co-financé.... Qu'en pensez-vous ?

**Comment by Gustry** [comment]
> Merci pour le suivi, j'avais vu le ticket #1772 ce matin même mais il faut attendre la sortie de la V3.5 pour en profiter... A la fin de l'été, non ?

Pour un paquet à chaque commit :
https://packages.3liz.org/pub/lizmap/unstable/3.5/

Pour une RC:
https://github.com/3liz/lizmap-web-client/releases

Si jamais vous pouvez tester.

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
