### ISSUE TITLE
Add and Configure PostgreSQL/PostGIS on consisting Lizmap

### ISSUE THREAD

**Issue by asdro-f** [3liz/lizmap-web-client#2368]
Hello,

I've got problems with the configuration of PostgreSQL for Lizmap. I have a working Lizmap on my Apache and installed PostgreSQL on it with POstgis Extension. I can connect do PostgreSQL from pgAdmin and QGIS, i can upload/download Layers from the DB.

The installation of Lizmap tells me i need to change something in profiles.ini.php
```ini
[jdb:jauth]
driver=pgsql
host=localhost
port=5432
database="your_database"
user=my_login
password=my_password
search_path=public

[jdb:lizlog]
driver=pgsql
host=localhost
port=5432
database="your_database"
user=my_login
password=my_password
search_path=public
```
https://docs.lizmap.com/current/en/install/linux.html#postgresql

When i changed the file i got Error 500 when i visit Lizmap in my Browser...
Of course, i changed database, user and password fitting for my PostgreSQL Installation

Do i need to launch the Installer again with `php lizmap/install/installer.php`?

What will happen then with my projects and my (frontend) settings in Lizmap?

**Comment by Gustry** [comment]
This configuration is for using postgresql as a backend for Lizmap tables instead of SqLite.
Is-it what you want or are you talking for using Postgresql layers in QGIS and Lizmap ?

**Comment by asdro-f** [comment]
I want use Layers from PostgreSQL, to edit them in Lizmap...

**Comment by aeduard** [comment]
As @Gustry said above, you don't have to make those modifications to visualize/edit postgis data. Just add postgis layer to your project in Qgis, make the setup steps for the layer to be editable through lizmap plugin in Qgis and it should work.

**Comment by Gustry** [comment]
I agree, the documentation is confusing. I will keep this in mind.

If you want PG Layer in Lizmap, just add them in your project. Be sure that QGIS Server and Lizmap can access as well this database (either with login/password or better with a PG Service file)

**Comment by asdro-f** [comment]
Thanks for your Help, it's working now.
