### ISSUE TITLE
Lizmap Web Client - Edition tool

### ISSUE THREAD

**Issue by Uoppa** [3liz/lizmap-web-client#2369]
Good evening.
I have a question.
Does the Lizmap Web Client Edition tool (Lizmap configuration -> Create a repository -> Use the Edition tool) also modify the QGIS project or is the change only saved in the cache and does not modify the project itself?

Thanks,

Riccardo

**Comment by aeduard** [comment]
It does not modify the project file. It just enables the editing capabilities if they are already set by the Qgis lizmap plugin.

**Comment by Uoppa** [comment]
So what is this feature for? Once the change has been made via the web page, does it remain saved or is it deleted after updating the page?

**Comment by aeduard** [comment]
It remains saved. You can modify the project file, this setting on the lizmap admin page does not change. Within this feature you can set the user groups which can edit your layers.

**Comment by Uoppa** [comment]
So, to make a summary, enabling the Edition Tool allows you to modify the layers of the project via the browser. The changes made are saved in the map displayed online; however, the QGIS Desktop project is not changed.
Did I say it right?

**Comment by aeduard** [comment]
Yes, it enables the editing capability for your map for specific groups of users for layers which were previously set as editable via Qgis Lizmap plugin and I think also Qgis Project Properties/QGIS Server/WFS capabilities.
Qgis desktop project does not change by these settings. But of course if you modify/edit gis data in a postgis layer within lizmap it will be modified everywhere.

**Comment by Uoppa** [comment]
Thank you very much indeed! You have been very kind!

**Comment by Gustry** [comment]
A QGIS project is composed of one or many layers.
It's confusing when you mention "modify the QGIS project".

Lizmap won't edit the project itself, but it will edit layers composed in the project.

If you edit a layer in Lizmap, you will find the update in QGIS Desktop or in any other software (other Lizmap instance etc)
