### ISSUE TITLE
Fond de plan IGN 

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#2378]
### What is the bug?

Le fond de plan IGN V2 ne s'affiche pas en qualité de fond de plan (external baselayer) avec une clé personnelle : il y a une erreur 403 "No rights for this ressource or ressource does not exist" dans les flux réseau du navigateur web.

### Steps to reproduce the issue

1. Cocher le fond externe "IGN GéoPortail (France) "PLAN"
2. Appliquer/ transférer / charger la carte 
3. le fond IGN Plan ne s'affiche pas.

Après contact auprès des géoservices de l'IGN, le problème ne viendrait pas de notre clé sécurisée en REFERER sur notre instance Lizmap hébergée mais du nom technique de la couche WMS : 

IGN ==> Le nom technique de la ressource pour le plan IGN est 'GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2'

Est-ce qu'il faut corriger la ligne 6785 du fichier lizmap/www/assets/js/map.js ?

 layer: isFreeIgnKey ? "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2" : "GEOGRAPHICALGRIDSYSTEMS.PLANIGN",
 en 
 layer: isFreeIgnKey ? "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2" : "GEOGRAPHICALGRIDSYSTEMS.PLANIGN**V2**",

### Lizmap version

3.4.4

### QGIS desktop version

3.10.14

### QGIS server version

3.10.14

### Operating system

W10

### Browsers

Firefox

### Browsers version

Firefox 89.0.2

**Comment by nboisteault** [comment]
Bonjour,
Avez-vous une URL public pour visualiser ce problème ?

**Comment by Alain-LG** [comment]
Je viens de créer ce répertoire public : 
https://agglofecampcauxlittoral.lizmap.com/carto/index.php/view/
avec tous les fonds de plan "IGN" + OSM Stamen

**Comment by nboisteault** [comment]
Merci, je corrige cela demain.
