### ISSUE TITLE
[Bug]: bad export file name

### ISSUE THREAD

**Issue by gcalibris** [3liz/lizmap-web-client#2384]
### What is the bug?

This bug is old, because it has been in Qgis server 2.18, Lizmap 3.2, 3,3, Ubuntu 16.04. The problem is with data export (in Data section) in all formats (xlsx, gpkg and etc.). When data is exported by pressing "Export" button the exported file name automatically is generated with incorrect letters. In my case the file name should be like "export_Pranešimų.xlsx" but I getting the case that's shown in picture.
 
![Screenshot 2021-07-19 161446](https://user-images.githubusercontent.com/14087650/126168243-810bf1a8-c592-479a-af82-ac7adb721a60.png)

### Steps to reproduce the issue

1. Go to Section "Data"
2. Press "Export" button.
3. Choose any file format.

### Lizmap version

3.4.4

### QGIS desktop version

3.16.4

### QGIS server version

3.16.4

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

Firefox 90

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/1475

**Comment by gcalibris** [comment]
Maybe this issue I can solve in that way, that I can do some modification in lizmap code, that exported file name will be independent from layer name, example always name will be "data_export.xlsx". Maybe someone can help me where I can do these modifications?

**Comment by gcalibris** [comment]
Solution:
file name can be modified to static name, example to this name "data_export.xlsx".
Code changes should be done in file:
lizmap/modules/lizmap/controllers/service.classic.php

original code

`            if (in_array($outputformat, $zipped_files)) {
                $rep->outputFileName = 'export_'.$this->params['typename'].'.zip';
            } else {
                $rep->outputFileName = 'export_'.$this->params['typename'].'.'.$outputformat;
            }`

modified code

`if (in_array($outputformat, $zipped_files)) {
                $rep->outputFileName = 'data_export.zip';
            } else {
                $rep->outputFileName = 'data_export.'.$outputformat;
 }`

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/1475
