### ISSUE TITLE
Problem with displaying double byte characters on the map

### ISSUE THREAD

**Issue by kenseii** [3liz/lizmap-web-client#2385]
### Description
Qgis server and lizmap correctly returns alphabetical labels but when it comes to double byte characters(japanese characters...) it displays them as squares.

I tried the steps in this [issue](https://github.com/3liz/lizmap-web-client/issues/1644) by changing the [nginx config file](https://github.com/3liz/lizmap-docker-compose/blob/master/lizmap/etc/nginx.conf) to have `fastcgi_param QT_QPA_FONTDIR "/usr/share/fonts/";` but the problem persisted.

![image](https://user-images.githubusercontent.com/7963983/126253365-686e1132-b57a-467c-8964-cb76b258cca6.png)

I also tried the steps described in the [docs](https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/config.html#add-fonts-to-your-linux-server) on how to install extra fonts(in my case arial) but the problem did not go away(though the `fc-match Arial` command inside the `qgis-map-server` container returns `Arial.TTF: "Arial" "Regular"`.

Is there another way to fix

### Steps to reproduce the issue

Not sure if necessary but i can provide the lizmap project that is returning this problem.

### Lizmap version

3.4.4

### QGIS desktop version

3.16.8

### QGIS server version

≥ 3.0

### Operating system

MacOS(desktop), Ubuntu 20.4 (server,docker)

### Browsers

Firefox, Chrome

### Browsers version

Chrome Version 91

**Comment by Gustry** [comment]
As we can see in your screenshot, the popup on the right is correct, which is generated by the Lizmap application.

The map is not correct, which is generated by QGIS Server.

So this is not a Lizmap issue, but a QGIS Server issue. You should check the configuration, fonts etc installed on QGIS Server.

See https://github.com/3liz/lizmap-web-client/issues/2057#issuecomment-765046986

Maybe you can have some help on gis.stackexchange.com or a QGIS Dev/User mailing list ?

**Comment by kenseii** [comment]
I fixed it by mounting a local fonts folder to the one of the qgis_server service inside the `docker-compose.yml` like this`${LIZMAP_DIR}/msfonts:/usr/share/fonts/truetype/` and it solved the problem.
