### ISSUE TITLE
Atlas et champ id

### ISSUE THREAD

**Issue by sigsdis30** [3liz/lizmap-web-client#2386]
### Description

J’ai créé un atlas sous qgis qui est fonctionnel sur une vue matérialisée qui a un champ « id » de type text (issu de la concaténation de 2 champs). Cela ne fonctionne pas sous lizmap (en cliquant depuis la popup) j’ai cette erreur :
<html>
<body>
<div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filtrer le JSON"></div><div class="panelContent">

  |  
-- | --
status | "fail"
message | "ATLAS - Error from the user while generating the PDF: Expression is invalid: \nsyntax error, unexpected NAME, expecting COMMA or ')'\nsyntax error, unexpected ')', expecting $end"

</div>
</body>
</html>

_Je parle bien de la fonction d'impression d'atlas et non de la fonctionnalité d'affichage Lizmap._

Le problème  a été résolu en créant un champ « id » bigint comme ceci : row_number() OVER () AS id, et un champ "identifiant" qui contient notre ancien champ « id » issu de concaténation.

J’ai le même problème avec la table commune de la bd topo dont l’identifiant « cleabs » est de type text. Toutes mes cartes lizmap où j'ai un  champ "id" de type bigint l'atlas fonctionne très bien.

Ma question est la suivante faut-il que le champ  identifiant ai un nom (id) et type particulier pour fonctionner sous Lizmap ? 

Je n’ai rien trouvé dans la doc ni sur le web. La seule chose que j’ai trouvé est pour l’édition des tables attributaires et c’est plus de l’ordre du conseil https://docs.lizmap.com/3.1/fr/publish/advanced_lizmap_config.html#activate-the-attribute-table-tool-for-a-vector-layer

Merci d'avance pour vos retours

### Environment

 - Lizmap version: 3.4.4
 - QGIS Server FULL version: 3.4.4
 - QGIS Desktop FULL version: 3.16.4
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into PostgreSQL

**Comment by Gustry** [comment]
> QGIS Server FULL version: 3.4.4
QGIS Desktop FULL version: 3.16.4

Je ne réponds pas précisement à la question, mais vous vous exposez a des problèmes.
QGIS Bureautique 3.16 génére des projets QGS en XML format 3.16. QGIS Serveur 3.4 ne peut pas lire correctement ces fichiers dans un format qu'il ne connait pas encore. Dans 3.16, il y a des changements de le format d'enregistrements des champs WMS/WFS par ex, QGIS Serveur 3.4 **ne peut pas** lire cette nouvelle configuration. Vous devez utiliser la même version de QGIS Bureautique et Serveur, comme il est écrit sur le premier panneau "Information" du plugin Lizmap.

**Comment by sigsdis30** [comment]
Pardon la version qgis n'est pas la 3.4.4, j'ai cru que c'était la version lizmap sur le serveur. Je n'ai aucune idée de la version de qgis serveur, je suis juste client, mais notre prestataire nous a demandé de travailler avec la version 3.16, je pense donc que sur le serveur la version doit correspondre. Si il y a une manière de le savoir de mon côté je veux bien le faire.
