### ISSUE TITLE
[Bug]: potential issue about wmsGetCapabilitiesUrl and wmtsGetCapabilitiesUrl?

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#2391]
### What is the bug?

In the code of the Project class, [we retrieve](https://github.com/3liz/lizmap-web-client/blob/69584d060124d4212468379e0fc8128f8d3e6d44/lizmap/modules/lizmap/lib/Project/Project.php#L1545) the `wmsGetCapabilitiesUrl` and the `wmtsGetCapabilitiesUrl` data from the `QgisProject` object.

However, into [QgisProject](https://github.com/3liz/lizmap-web-client/blob/69584d060124d4212468379e0fc8128f8d3e6d44/lizmap/modules/lizmap/lib/Project/QgisProject.php) there is not set of such properties into the `data` property.

Am I missing something ? Or is there a bug here, and we don't retrieve the value from the right object?

All these `getData` methods from Project, ProjectMetadata and QgisProject are a nightmare to know which data we can retrieve, what are their type etc... I'm preparing a patch to deprecate them and to replace them by some explicit methods for each data, and I discover this issue during my work.

### Lizmap version

3.5.0-rc.1

**Comment by laurentj** [comment]
Same issue, few lines below those I pointed: there is a `$this->qgis->getData('label')` but nowhere in QgisProject a such value is set.

For the wmsGetCapabilitiesUrl and the wmtsGetCapabilitiesUrl data, I think it should be retrieved from the `Project` objet itself, as [there are set here](https://github.com/3liz/lizmap-web-client/blob/69584d060124d4212468379e0fc8128f8d3e6d44/lizmap/modules/lizmap/lib/Project/Project.php#L312).

**Comment by laurentj** [comment]
Ok, i see that the `label`  should comes from the `Repository` object, not from the project object.

I will make a patch.

**Comment by nboisteault** [comment]
@laurentj As you said it is a nightmare. I think this issue is related to https://github.com/3liz/lizmap-web-client/issues/2153.
I banged my head on it and ask @mdouchin for help but you can join the party if you want :)
