### ISSUE TITLE
What's the recommended Lizmap version for QGIS LTR Version 2.8.6?

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#240]
Hi,

I am going to make a clean install in a new Server (Windows Server 2012)..

I am going to Install QGIS LTR Version 2.8.6 (QGIS Server included). I've read that this is the version recommended for a production environment.

What Lizmap version should I install with this QGIS version? 

2.8.1 seems to old.. (April 2013)
2.12.3 may have compatibility issues. I gues this Lizmap version is developed for QGIS 2.12.3
3.0Beta definately is not recommended...

I am in fact very tented to install QGIS Server 2.12.3 with lizmap 2.12.3 so I can use the last features and I guess they will fit together like a charm...but I remark that it will be for production use.

Any advise would be apreciated.

**Comment by nboisteault** [comment]
You should use lizmap 2.12.3. It should work with QGIS 2.8.6.

**Comment by jaitor1** [comment]
Perfect I will, thank you.
