### ISSUE TITLE
Lizmap very slow when using high scale

### ISSUE THREAD

**Issue by aledalla** [3liz/lizmap-web-client#2405]
I built a project in QGIS having a heavy postGIS layer with many data (a layer has 80k entries).

Moving in the map results too much slow in the browser ONLY when in high scale (all object are rendered).
I noticed that it takes around 5 minuts but this happens only in Lizmap and not in QGIS.

I decided to monitor processes on the linux machine running Lizmap and noticed that the component "qgis_mapserver.fcgi" is using 100% of CPU for all the time long the browser renders the map.
The main problem is that it does not seem to use multicore! (CPU is busy in only one core)

I also checked on QGIS project and multicore is enabled. Is there some place to configure qgis server to use multithreading or it can just be limited from the apache web server?

I am running Lizmap,QGIS server  and Apache on Debian 10

**Comment by aledalla** [comment]
That problem was not reguarding Lizmap, I am closing this issue

**Comment by mdouchin** [comment]
see https://docs.qgis.org/3.16/en/docs/server_manual/config.html#environment-variables `QGIS_SERVER_MAX_THREADS` perhaps ?
