### ISSUE TITLE
Beta 3

### ISSUE THREAD

**Issue by cristomoya** [3liz/lizmap-web-client#241]
I installed the beta 3 following the steps , and had installed the beta 2, but can not create repositories . It gives a 500 error .

I tried reinstalling several times and has not been solved

The version 2.12 works correctly .

Is it a mistake by the application?

**Comment by rldhont** [comment]
Did you you use the script set_rights.sh as said in INSTALL.md ?

**Comment by cristomoya** [comment]
yes, I am stupid. Sorry
