### ISSUE TITLE
Bug or misconfiguration: selected features are in the wrong position

### ISSUE THREAD

**Issue by lucaplz** [3liz/lizmap-web-client#2412]
### What is the bug?

Hi, I have created some projects with only postgis layers, and with all layers referenced in EPSG 3003.
The selection tool works fine.
![test_3003](https://user-images.githubusercontent.com/64898041/127327570-6dde1e36-c8c6-4f18-ae77-e76771ab4789.gif)
If I add OSM as a base layer, simply using the lizmap option in "base layers" panel, then the selection tool behaves wrong, as in the next example, and also if the osm layer is not active: You can see that selection is translated by ~90 meters in NW direction
![test_osm](https://user-images.githubusercontent.com/64898041/127327608-e4545a57-ae6b-4740-9fbd-e5e29b96da8e.gif)

Is it a bug or using different CRS needs some additional configuration in the project?

Thanks,
Luca.

### Steps to reproduce the issue

1 - Create project  with EPSG 3003 postgis data
2 - add OSM base layer in lizmap configuration
3 - make any selection -> features selected do not belong to the correct area

### Lizmap version

3.4.4

### QGIS desktop version

3.10.14

### QGIS server version

3.1014

### Operating system

Debian 10

### Browsers

Firefox

### Browsers version

Firefox 78 ESR

**Comment by Gustry** [comment]
Just to check, do you have some `int8` fields in your vector layer properties, "fields" tabs ? (it should be int4 for QGIS Server to works properly, check #1745)
But it seems in fact the rectangle is shifted.

**Comment by lucaplz** [comment]
Just verified: int4 only.

**Comment by nboisteault** [comment]
Hi,
Please provide a project to help us reproduce this issue.

**Comment by lucaplz** [comment]
Sorry for the delay in my aswer!
Here a project with some postgis layers and lizmap cfg file.
[test_fogn_3857.zip](https://github.com/3liz/lizmap-web-client/files/7258481/test_fogn_3857.zip)
..

**Comment by Gustry** [comment]
Do you still replicate the issue with latest 3.6 ?

They were quite a few bugfix about layer shortnames, and also on the plugin side about primary keys which are used to identify features with these tools.

**Comment by lucaplz** [comment]
I forgot to verify: with latest versions (also 3.5.16) it works!
thank you!
