### ISSUE TITLE
Where are my Repository and Projekt Names saved

### ISSUE THREAD

**Issue by asdro-f** [3liz/lizmap-web-client#2414]
I want to use qgis2threejs with Lizmap. 
It works fine, but i need to change some pathes in the automatically created index.html befor.

But of course i dont want to do it everytime manually.

So my Question:
Where can i find Informations about my repositirories (ID-Numbers) and my project Names on my apache2-Server. 
In the Project-Folders (of course) there isnt any information about that. I searched for the informations in var/www/lizmap... but i didnt find anything.

Thanks for your Help and best regards...

**Comment by lhirlimann** [comment]
It's in var/config/localconfig.ini.php I believe.

**Comment by asdro-f** [comment]
Close to...
I found it in lizmap/var/config/lizmapConfig.ini.php
Thanks for your fast answer!

**Comment by aeduard** [comment]
I would like also to put qgis2threejs behind authenticated access, right now I'm using on public links only. Can you give a description how to modify the generated qgis2threejs html?
