### ISSUE TITLE
Is there a way to prebuild the cache?

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#242]
I'm not sure but I think I saw a way to prebuild the cache.
Did I dream or it exists?
If it exists, is it only in master or it is in version 2.x too?

**Comment by mdouchin** [comment]
Indeed this feature has been added, but only since Lizmap 3 
https://github.com/3liz/lizmap-web-client/releases

See documentation proposal : https://github.com/mdouchin/lizmap-documentation/blob/master/source/admin_guide/administration/cache.rst#seeding

**Comment by nboisteault** [comment]
Great! Thank you.
Can I take a project running in lizmap 2, put it in lizmap 3 and seed the cache for lizmap 2?
In other words, are lizmap caches compatible between version 2 and 3?

**Comment by antoine373** [comment]
Hello !
I tried your documentation proposal to prebuild cache and I encoutered some problems.
First of all I cleaned up all my cache folders and files related to my lizmap project and then I laucnh the command describe in the link above : 
- It's write new folders and files in the same directory (\tmp\ [repository] \ [project] \ [layer] \ [SRC] \...), so it's seems doing good work.
- However when I return on lizmap, nothing appear for 3.0-beta3 version, and it's appear like pink square for 2.12.3 version

As if lizmap is not able to read these prebuild cache folders and files.
Did anyone manage to make it work ?

**Comment by cristomoya** [comment]
I have an error `

> root@osgeolive:/var/www/lizmap-web-client-master# php lizmap/scripts/script.php lizmap~wmts:capabilities -v -f  4 pgou3 500_mazarron EPSG:3857 12
> 2016-02-02 17:21:35     [43]    Unknown option "-f"     /var/www/lizmap-web-client-master/lib/jelix/utils/jCmdUtils.class.php   68
> 
> root@osgeolive:/var/www/lizmap-web-client-

**Comment by rldhont** [comment]
@antoine373 You have to update rights on temp folder. You probably build the cache with an other user than the one used by your server.

**Comment by rldhont** [comment]
@cristomoya there is an issue in the documentation, `-f` is not supported for capabilities command.

**Comment by antoine373** [comment]
@rldhont Thank you !
It was indeed a problem with rights on temp folder. As i prebuild cache with "root" user, I had to update rights to my server user.
Now I can say that it's possible to prebuild cache with lizmap 3 and then use it in lizmap 2 !

**Comment by josemvm** [comment]
hi,

i'm trying to prebuild a cache for a layer raster data on server:

- /var/www/lizmap3# php lizmap/scripts/script.php lizmap~wmts:capabilities ma arq

For "437_2007_3" and "EPSG:3763" from TileMatrix 0 to 5
For "437_2007_3" and "EPSG:4326" from TileMatrix 0 to 15
For "437_2007_3" and "EPSG:3857" from TileMatrix 0 to 16

- /var/www/lizmap3# php lizmap/scripts/script.php lizmap~wmts:capabilities -v ma arq 437_2007_3 EPSG:3763

For "437_2007_3" and "EPSG:3763" the TileMatrix 0 has 1 tiles
For "437_2007_3" and "EPSG:3763" the TileMatrix 1 has 4 tiles
For "437_2007_3" and "EPSG:3763" the TileMatrix 2 has 9 tiles
For "437_2007_3" and "EPSG:3763" the TileMatrix 3 has 24 tiles
For "437_2007_3" and "EPSG:3763" the TileMatrix 4 has 60 tiles
For "437_2007_3" and "EPSG:3763" the TileMatrix 5 has 384 tiles

- php lizmap/scripts/script.php lizmap~wmts:seeding -v -f ma arq 437_2007_3 EPSG:3763 **?? ??**

what´s the best parameters to use to prebuild a cache on server in this case?


thanks

**Comment by josemvm** [comment]
hi,

I have some of my projects with rasters group/group as layer (EPSG:3763), with the following settings:

![cacheserver0](https://cloud.githubusercontent.com/assets/10053874/14815253/3a074ba6-0ba2-11e6-980c-85bb8a52836a.jpg)

![cacheserver1](https://cloud.githubusercontent.com/assets/10053874/14815262/40ffa156-0ba2-11e6-8255-edf1ac6336dd.jpg)

qgis-server create the structure folders in file system only for the EPSG:3857 (not for the EPSG:3763) like this: /opt/liz_cache/ma/pdma/PO - Rasters/EPSG_3857 but not the tiles...

- what is wrong with settings?
- the expiration time for the server and the client are mandatories?
- I would like to pre-build the caches according to the my previous post

can someone help me?
thanks

**Comment by rldhont** [comment]
Hi @josemvm,

If you publish a group as layer, lizmap considered the group as a layer and does not look at the layer in the group. You can only create server cache for the group because it's a layer.

The expiration time is mandatory in the configuration of the 'layer' you want to cache. Here you're group.

By default, Lizmap only creates the cache for the CRS used by the web client. It seems that your map is displayed with EPSG:3857 in Lizmap Web Client.

You can use this command to generate cache for EPSG:3763
* php lizmap/scripts/script.php lizmap~wmts:seeding -v -f ma arq 437_2007_3 EPSG:3763 0 5
But this cache will only be used with WMTS in an other client than Lizmap Web Client.

**Comment by josemvm** [comment]
thanks @rldhont,

i' tried to define "Server cache" for the group (Expiration: 2592000) and no any options for the individual layers in the group.

The tiles are created but the layers group doesn´t appear on the map when i enbale it in legend tree...

**Comment by josemvm** [comment]
these are the logs that i can get when I try to create the server cache:

- error.log from apache, many of these same lines from goup as layer
: {"NAME":"LIZMAP_PROXY_READ_LAYER_CONFIG","RESPONSE_TIME":176.4190196991,"CACHE_STATUS":"off"}
: {"NAME":"LIZMAP_PROXY_READ_LAYER_CONFIG","RESPONSE_TIME":164.2758846283,"CACHE_STATUS":"off"}
: {"NAME":"LIZMAP_PROXY_READ_LAYER_CONFIG","RESPONSE_TIME":169.67797279358,"CACHE_STATUS":"off"}

- error.log from apache, many of these same lines from individual layer
: {"NAME":"LIZMAP_PROXY_READ_LAYER_CONFIG","RESPONSE_TIME":143.89181137085,"CACHE_STATUS":"read"}
: {"NAME":"LIZMAP_PROXY_HIT_CACHE","RESPONSE_TIME":145.62296867371,"CACHE_STATUS":"read"}
: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":207.39483833313,"CACHE_STATUS":"read"}


thank you very much @rldhont for all the helps and sorry for the noise.

**Comment by josemvm** [comment]
hi,

can someone test to create and publish a raster group as layer using server cache for the group?
so, please pay attention to the previous comments.

thanks in advance

**Comment by virtusmankind** [comment]
Hi, 
trying to prebuild cache on Lizmap 3.0.2
With my repository and project called "prova" I want to build "Particelle" layer cache. 

Using: 
_php lizmap/scripts/script.php lizmap~wmts:capabilities prova prova Particelle_
For "Particelle" and "EPSG:32633" from TileMatrix 4 to 8
For "Particelle" and "EPSG:4326" from TileMatrix 15 to 20
For "Particelle" and "EPSG:3857" from TileMatrix 16 to 21
 
Using then; 
_php lizmap/scripts/script.php lizmap~wmts:capabilities prova prova Particelle 4 21_
 
I get this error: 
2016-09-26 16:40:00     [44]    Too many parameters     /var/www/lizmap-web-client-3.0.2/lib/jelix/utils/jCmdUtils.class.php    85

What's wrong? 

Which value I have to set for [TileMatrixMin] [TileMatrixMax]. In documentation you talk about "bus" layer using the following: 

- _For "bus" and "EPSG:3857" from TileMatrix 14 to 16

- php lizmap/scripts/script.php lizmap~wmts:seeding -v -f montpellier montpellier bus EPSG:3857 12 14_

using 12 for TileMatrixMin and 14 for TileMatrixMax even if precision gets you "14 to 16".  
Could you explain me how to use [TileMatrixMin] [TileMatrixMax] values?

**Comment by virtusmankind** [comment]
Hi all,
is it normal process takes a lot of time (hours) building cache for 9 "TileMatrix" (about 300.000 tiles)? 
I set 5,5 value for layer's tile in the layer properties.

**Comment by nboisteault** [comment]
I close the issue as it is answered. Open another one if needed.
