### ISSUE TITLE
About Atlas's Triggerfilter

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-web-client#2420]
### Description
This is a confirmation of the behavior of Lizmapplugin when Atlas' Triggerfilter is set.
　In LizmapWebClient, Atlas is filtering properly.
　However, when I print from popup, the filter does not work.
　In LizmapWebClient, Atlas is filtering properly.
　If so, is it possible to change the specification?
　If there is a fee to add this feature, what is the approximate cost?

　Or is it because the https://github.com/3liz/qgis-atlasprint set is not working?

### Environment
 - Lizmap version: 3.4.5-pre
 - QGIS Server FULL version:3.16
 - QGIS Desktop FULL version:3.16.8 and 3.16.9
 - OS (Windows, Linux, MacOS, Android…): Server-Ubuntu Linux 18.04.5，Client-Windows10
 - Browser (Firefox, Chrome…):Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?:nothing

**Comment by yamamoto-ryuzo** [comment]
It looks like https://github.com/3liz/qgis-atlasprint.
I'll try it.

**Comment by yamamoto-ryuzo** [comment]
I have installed and tried https://github.com/3liz/qgis-atlasprint. but there is no change in behavior.

**Comment by Gustry** [comment]
AtlasPrint is indeed not related to the Lizmap Atlas feature. It is 2 separate features.

AtlasPrint plugin is linked to QGIS Layout Atlas capabilities.

Do you have a single project to share ?

**Comment by yamamoto-ryuzo** [comment]
I shared a read-only project with you.
https://soja.gis-cdn.net/index.php/view/map/?repository=chiiki&project=road_maintenance
・atlas is filtered and works properly
![image](https://user-images.githubusercontent.com/86514652/128160846-c86bd5dc-9551-4f00-b496-b7c0729d6da2.png)
・Popup works fine.
![image](https://user-images.githubusercontent.com/86514652/128161044-8e3cb34d-ed0e-40af-9b8d-a93863629a95.png)
・When I print from the popup, the filter is removed.
![image](https://user-images.githubusercontent.com/86514652/128161194-f116b1f8-1974-48af-9be7-931704499e95.png)
・I want it to stay filtered.

**Comment by yamamoto-ryuzo** [comment]
I understand that there is no relationship between AtlasPrint and the Atlas feature of Lizmap.
Thank you very much.
>AtlasPrint is indeed not related to the Lizmap Atlas feature. It is 2 separate features.
>AtlasPrint plugin is linked to QGIS Layout Atlas capabilities.

**Comment by Gustry** [comment]
Did you find the problem ?
