### ISSUE TITLE
draw tool - same color for all drawings

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2421]
### What is the bug?

when the user changes the color of a picture, all the pictures take on that same color

### Steps to reproduce the issue

try to change color

### Lizmap version

3.4.4

### QGIS desktop version

3.16.8

### QGIS server version

3.16.8

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Firefox 89

**Comment by nboisteault** [comment]
What do you mean by picture. Please add a screenshot.

**Comment by josemvm** [comment]
> What do you mean by picture?

drawings

> Please add a screenshot

![imagem](https://user-images.githubusercontent.com/10053874/133117055-4c358273-bebb-45c5-a12a-2a5d2354609c.png)

it's not possible to have drawings with different colors
if you pick a new different color, all the drawings take on that new color

**Comment by nboisteault** [comment]
Is has been funded by [Lons-le-Saunier](https://www.lonslesaunier.fr/) and will be developed soon.

**Comment by josemvm** [comment]
good news!
@nboisteault thanks and thanks a lot to [Lons-le-Saunier](https://www.lonslesaunier.fr/)

**Comment by josemvm** [comment]
hi @nboisteault
is it planned to create labels for the drawings? ;-)

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/pull/1703#issuecomment-660200701

**Comment by nboisteault** [comment]
Hi @josemvm
No it is not planned. If someone want to fund it, please contact us to info@3liz.com
