### ISSUE TITLE
que signifie cette instruction lors de l'install sous windows ?

### ISSUE THREAD

**Issue by lraes** [3liz/lizmap-web-client#2424]
### Description

Assurez-vous que vous avez l’extension: kbd: .conf dans ce fichier ? (juste apres la creation du fichier php73.conf)
Merci

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: ltr
 - QGIS Desktop FULL version: ltr
 - OS (Windows, Linux, MacOS, Android…): windows 10
 - Browser (Firefox, Chrome…): firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by lraes** [comment]
Pour ceux qui font une nouvelle install, je pense qu'il faut retenir que l'extension doit être .conf (exemple php73.conf) c'est le "kbd" qui m'a induit en erreur.

**Comment by Gustry** [comment]
Il s'agit d'une erreur de traduction sur Transifex entre l'anglais et le français.

N'hésitez pas à traduire pour corriger si vous pouvez. Je viens de le faire pour les chaînes de caractères comportant "kbd".

https://www.transifex.com/3liz-1/lizmap-documentation

**Comment by Gustry** [comment]
De même nous recommandons cette documentation pour l'installation sous windows : https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows
