### ISSUE TITLE
log erreur apache suite à l'activation httpd-vhosts.conf

### ISSUE THREAD

**Issue by lraes** [3liz/lizmap-web-client#2425]
### Description

le log

httpd.exe: Syntax error on line 511 of C:/webserver/Apache24/conf/httpd.conf: Syntax error on line 33 of C:/webserver/Apache24/conf/extra/httpd-vhosts.conf: Include takes one argument, Name(s) of the config file(s) to be included; fails if the wildcard does not match at least one file

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: ltr
 - QGIS Desktop FULL version: ltr
 - OS (Windows, Linux, MacOS, Android…): windows 10
 - Browser (Firefox, Chrome…): firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by lraes** [comment]
J'ai suivi scrupuleusement les instructions d'install du doc lizmap version 3.4
-Quelles seraient les étapes et(ou) fichiers à vérifier ?
Merci
Bien cordialement

**Comment by lraes** [comment]
en capture d'ecran les 2 fichiers httpd-vhosts.conf et php74.conf
-le fichier "php.ini" est configuré selon la directive de lizmap doc...
-si je desactive "#Include conf/extra/httpd-vhosts.conf" dans le fichier "httpd.conf", Apache démarre !
![httpd-vhosts](https://user-images.githubusercontent.com/26005289/128630676-92d79e7f-d5c2-4c9d-8b61-39cb6b7ff27a.jpg)
![php74](https://user-images.githubusercontent.com/26005289/128630683-383292df-2f28-4d17-9462-fc1b5ed5b1f0.jpg)

**Comment by ygorigor** [comment]
https://qgisusers.co/es/blog/instalacion-de-lizmap-y-qgis-server-en-windows-10/

**Comment by Gustry** [comment]
Vous pouvez regarder également https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by lraes** [comment]
résolu:
dans le fichier httpd-vhosts.conf il faut enlever les commentaires !
