### ISSUE TITLE
Issue with 'group as layer' and WMS layers

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#243]
Lizmap web client 2.12 / lizmap plugin 2 / QGIS server 2.8.4

I have 2 WMS layers in a group.
I check the checkbox to directly query the external WMS server for both.
I select 'group as layer' for the group.

Now when I want to display the group as layer, lizmap doesn't query the external WMS server but lizmap server.

I looked map.js at line 523, we have :

```
 if (layerConfig.type == 'group' && layer.nestedLayers.length != 0 && layerConfig.baseLayer == 'False')
      getLayerTree(layer,node);
```

The group has 'layer' type and not 'group' so getLayerTree() is not called and line 458 is never called for WMS layers inside this group, so URL is never override.

```
 // Override WMS url if external WMS server
    if (layerConfig.externalAccess ) {
```

**Comment by rldhont** [comment]
Lizmap can't query a group as an external WMS server because a group is not a True layer.
If you use Group as layer, you probably want that QGIS server merges layers, isn't it ?
If not, why did you do this ?

**Comment by nboisteault** [comment]
I did that to have 3 different external WMS layers in a group and showing them one by one based on scale.

**Comment by rldhont** [comment]
I close it, reopen if issue still exists in 3.* branch
