### ISSUE TITLE
Exclude composers by group/user

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2431]
it would be very nice of would be possible for each layer (and eventually each composer) to define an exclusion list of groups/users. Users belonging to that groups would see/have access to that specific layers/composers.

**Comment by Gustry** [comment]
> it would be very nice of would be possible for each layer

This is already possible since LWC 3.4, in the layer panel, there is input "Group visibility". Is-it not what you are looking for ?

For layouts, this would need some funding.

**Comment by gioman** [comment]
> This is already possible since LWC 3.4, in the layer panel, there is input "Group visibility". Is-it not what you are looking for ?

@Gustry yes it is, I was using an outdated version of the LM plugin. I edited the title. Thanks!

**Comment by Gustry** [comment]
I wonder since when you didn't updated the plugin, it is already since 2020 😉 (the one who ask always to use the latest version of QGIS)

For layouts, this would need some funding

**Comment by gioman** [comment]
@Gustry no, I had a fairly recent version of the plugin, it seems strange to me I overlooked that option for so long, but it doesn't matter.

**Comment by Gustry** [comment]
This is done in LWC 3.7 for layouts, as you can see for a few months in the Lizmap QGIS plugin
