### ISSUE TITLE
popup lizmap nom de variable

### ISSUE THREAD

**Issue by sigsdis30** [3liz/lizmap-web-client#2434]
### Description
Pour créer un popup lizmap la doc [stipule ](https://docs.lizmap.com/next/fr/publish/configuration/popup.html): 
> Pour ajouter le contenu d’une colonne dans la popup, on utilise le nom de la colonne précédé d’un dollard, le tout encadré d’accolades.

Or en essayant de respecter le nom de la colonne cela ne fonctionne pas si il y a un alias. Si c'est le cas il faut appeler l'alias de la colonne. Dans mon cas {$nom_officiel} ne fonctionnait pas mais en appelant l'alias {$Nom} ça fonctionne.

Est-ce le fonctionnement souhaité ? si c'est le cas il faut modifier la doc. Je trouve curieux d'avoir à se servir d'un alias du côté technique, ils sont normalement prévus pour l'affichage. Peut-être suis-je passé à côté de quelque chose ?

### Environment

 - Lizmap version: 3.4.4
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…):  Windows
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? PostgreSQL

**Comment by mdouchin** [comment]
Le fonctionnement dépend de ce que renvoie QGIS Server à Lizmap lorsqu'on interroge le service WMS pour le projet QGIS. La réponse du GetFeatureInfo (requête d'identification utilisée pour la popup) renvoit l'alias en remplacement du nom de champ.

Je comprends que ce n'est pas évident ni prévisible.

Si vous souhaitez conserver le nom des champs, et avoir des possibilité plus importantes, je vous conseille d'utiliser le mode "QGIS": https://docs.lizmap.com/current/fr/publish/configuration/popup.html#qgis-popup
qui permet d'utiliser des expression et se base sur ce que vous remplissez dans l'onglet "Affichage" des propriétés de la couche

**Comment by sigsdis30** [comment]
Merci pour la réponse, je vais m'orienter sur cette solution.

**Comment by Gustry** [comment]
Oui, on conseille désormais la popup "qgis" au lieu de "lizmap". Beaucoup plus puissante avec les expressions.

**Comment by arthuragone** [comment]
J'ai essayé l'option "QGIS Popup" ça marche bien dans QGIS mais je ne vois rien dans Lizmap. Je n'ai d'ailleurs du coup plus de bouton infobulle sur le client web de ce projet.
