### ISSUE TITLE
[Bug]: Popup : compactage des tables erratique si plusieurs relations

### ISSUE THREAD

**Issue by sigsdis30** [3liz/lizmap-web-client#2435]
### What is the bug?

Soit il ne fonctionne pas soit il occulte la 2 relation en fonction des actions réalisées précédemment.

### Steps to reproduce the issue

0. avoir une couche interrogeable qui possède plusieurs relations.

Ces points sont à réaliser séparément en rafraichissant la carte entre chaque point. Lors d'un clic sur un objet qui possède 2 relations, dans le popup qui apparait :
1.  si je clique sur compacter la table de la 1ère relation cela n'a aucun effet.
2. Idem si après le clic je cherche à sélectionner l'objet en cliquant sur l'icône sélecteur dans le popup.
3. Si avant le clic je passe par l'outil localisation, je clique sur l'objet dans la carte, je filtre dans le popup, le compactage fonctionne mais occulte la 2ème relation.

### Lizmap version

3.4.4

### QGIS desktop version

3.16

### QGIS server version

3.16

### Operating system

Windows

### Browsers

Firefox

### Browsers version

90.0.2

**Comment by Gustry** [comment]
Related ticket #2254 #2759
