### ISSUE TITLE
[Bug]: We cannot view or edit any more a feature after closing the editing popup

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#2436]
### What is the bug?

After closing the editing popup, it is not possible to view or edit an other feature, at least by clicking on it. We must reload Lizmap in order to view/edit other features.

~~Javascript issue ? Incompatibility with the latest Firefox/Chromium ?~~

No error in the Javascript console, and we can observe that the "selection" is still there when closing the form.

### Steps to reproduce the issue

1. Go to https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=observatoire
2. click on one point in a map, the properties panel (popup) is opened
3. click on the button to edit the properties, the form appears
4. click on the "close" button
5. click on an other point in the map : it does nothing

Same issue with Lizmap 3.4 and 3.5 (even with the latest unstable version of each branch, in our snap infra). not tested with lizmap 3.3.

### Lizmap version

3.4, 3.5

### QGIS desktop version

-

### QGIS server version

-

### Operating system

-

### Browsers

Firefox, Chrome

### Browsers version

Firefox 91, Chromium 92

**Comment by nboisteault** [comment]
@laurentj I can't reproduce the issue. @drillinP Can you reproduce it?

**Comment by laurentj** [comment]
In fact, "it's not a bug, it's a feature". Clicking on the "close" button does not cancel the edition, it just close the popup. The editing mode is still active, this is why we cannot select anything else.

But this is very confusing IMHO, as, in any interface in other software/OS, closing a window/popup means "cancel" (or "no" etc...).

A message, or other UX element should inform that we are in the edition mode. Perhaps we could also reword the "close" button, by "hide".

**Comment by mdouchin** [comment]
Vote for "Arrow left square"

**Comment by nboisteault** [comment]
I changed also right dock button
![image](https://user-images.githubusercontent.com/2145040/132688795-5d4fd08e-f97c-4d6b-8cfa-b10575a0975d.png)

**Comment by nboisteault** [comment]
Here is edition pending
![image](https://user-images.githubusercontent.com/2145040/132696979-0c43a660-29bf-4e45-a0a6-dc5d037f4a2e.png)
