### ISSUE TITLE
On mouse over html in abstract is not correctly rendererd (but is ok in information panel)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#244]
Lizmap 3 Beta 3:

if you add html to layers abstract (in both Lizmap plugin or QGIS layer metadata) then is rendered ok in lizmap web client information panel, but in the balloon that shows when hovering the layer name the html is rendered as plain text.

Also a suggestion: it seems redundant now to see the same abstract in both the information panel and the balloon. Maybe an option to choose what to use?

Cheers!

**Comment by ilamarengo** [comment]
In addition to what mentioned in the comment by gioman it would be possible, after solving the current problem, to add some documentation online on how to change the style (or switch on/off) of the balloon that shows when hovering the layer name? 
Users can be interested in personalising the basic tool or understanding a bit more how it works.

**Comment by rldhont** [comment]
Fixed in dee6bf7e0a45d50e5ff051b1fee3b4e3879f612a
