### ISSUE TITLE
[Bug]: bad behaviors when the lizmap plugin is not installed, and no message to inform the user

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#2446]
### What is the bug?

When the lizmap plugin is not installed into the Qgis server, Lizmap have some bad behaviors (for example, in forms, some listbox may be empty).  And there is not any message which inform about this missing plugin.

So a message should appear somewhere about the missing plugin (a popup message during the load of a project ? a message into the admin dashboard ?).

It will be better if lizmap disabled features that need the plugin, when it is not installed.

### Steps to reproduce the issue

1. do not install the lizmap plugin
2. no information into lizmap about this missing plugin

### Lizmap version

3.5

### QGIS desktop version

.

### QGIS server version

.

### Operating system

.

### Browsers

Firefox

### Browsers version

.

**Comment by Gustry** [comment]
it has been done in https://github.com/3liz/lizmap-web-client/pull/3142 for LWC 3.6.0
The plugin is now required, with a minimum version hard-coded in the LWC source code. (which will be edited before each release)
