### ISSUE TITLE
display filter panel instead of layers panel

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-web-client#2455]
Hi,
is there a way to display the Filter panel by default instead of the layer panel when the map is loaded?

thank you for your help
Gérald

    Lizmap version: 3.4.3
    QGIS Server FULL version:
    QGIS Desktop FULL version: 3.16
    OS (Windows, Linux, MacOS, Android…): windows 10
    Browser (Firefox, Chrome…):FF
    Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? postgresql

**Comment by ygorigor** [comment]
You can use a js script for that.

**Comment by gerald2545** [comment]
thank you, any tip to knwo where to search and implement that behaviour?

**Comment by Gustry** [comment]
https://docs.lizmap.com/current/en/publish/customization/javascript.html

The video tutorial is exactly what you are looking.

**Comment by gerald2545** [comment]
thank you for the link. here is the content of the javascript file : 
lizMap.events.on({
    'uicreated':function(evt){
        $('#button-filter').click();
    }
});
