### ISSUE TITLE
Filtre sur la couche avant que l'infobulle ne marche?

### ISSUE THREAD

**Issue by Ashley-Ouedraogo** [3liz/lizmap-web-client#2456]
Bonjour, 

Est-ce normal que la localisation par couche et l'infobulle de Lizmap ne fonctionnent qu'avec des couches sur lesquelles un filtre a été appliqué? 
Une fois que je n'applique pas de filtre à la couche aucun des deux outils (localisation par couche et infobulle) ne marche et j'ai une erreur:
`
Uncaught TypeError: tfeatures[0].geometry is null
    addTooltipControl http://192.168.0.213/lizmap-web-client-3.3.0/lizmap/www/js/map.js:4950
    callFeatureDataCallBacks http://192.168.0.213/lizmap-web-client-3.3.0/lizmap/www/js/map.js:5659
    callFeatureDataCallBacks http://192.168.0.213/lizmap-web-client-3.3.0/lizmap/www/js/map.js:5657
    getFeatureData http://192.168.0.213/lizmap-web-client-3.3.0/lizmap/www/js/map.js:5749
    jQuery 4
`

Ps : ça n'a rien à voir avec le nombre d'objets puisque j'ai essayé avec la couche sans filtre (ne marche pas) et aussi avec la couche filtrée (j'ai sélectionné tous les objets) et ça a marché.

**Comment by Gustry** [comment]
Are you running `lizmap-web-client-3.3.0` or is-it the just the name of the folder ?

**Comment by Ashley-Ouedraogo** [comment]
yes i'm running the 3.3.0 version

**Comment by Gustry** [comment]
You should definitely look at the first tab in the Lizmap plugin.

https://docs.lizmap.com/current/fr/publish/lizmap_plugin/information.html

* To check the latest version available for 3.3, which is currently 3.3.16 so 16 new releases. https://github.com/3liz/lizmap-web-client/releases/tag/3.3.16
* To be able to check your own server with the table at the bottom.
