### ISSUE TITLE
Error when editing layer from view

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#247]
Hi,

I created a new postgis updateable view (with insert, update and delete triggers). If the layer is edited from QGIS de data is edited ok.

If I edit the data from Lizmap I get:

![image](https://cloud.githubusercontent.com/assets/12136796/12582793/795bd88a-c43f-11e5-8cd7-dcefff90ef36.png)

I only edited one field and the geomtry of the polygon has not been touched.

I searched a little bit in the code and found this:

``` javascript
 switch($this->formControls[$ref]->fieldDataType){
      case 'geometry':
        $value = "ST_GeomFromText('".filter_var($value, FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES)."', ".$this->srid.")";
        $rs = $cnx->query('SELECT GeometryType('.$value.') as geomtype');
        $rs = $rs->fetch();
        if ( !preg_match('/'.$this->geometryType.'/',strtolower($rs->geomtype)) )
          if ( preg_match('/'.str_replace('multi','',$this->geometryType).'/',strtolower($rs->geomtype)) )
            $value = 'ST_Multi('.$value.')';
          else {
            $form->setErrorOn($this->geometryColumn, "The geometry type doen't match!");
            return false;
          }
        break;
      case 'date':
   ...
```

I can't understand it all but I think that geomtype in lizmap is different from the one of the layer. I don't understand why because I haven't touched any geometry. 

The edition in a normal layer is Ok, so I figured out it must be a problem only with the updatable views.

**Comment by rldhont** [comment]
Hi @jaitor1, Thanks for report this issue. Is it the same as #108 ?

**Comment by jaitor1** [comment]
Looks like it could be the same issue, yes.

**Comment by rldhont** [comment]
Can you reproduce this issue ? Can we closed it ?

**Comment by jaitor1** [comment]
Hi,

You can test in[ this map](http://eudala2.getxo.eus/lizmap/lizmap-web-client-master/lizmap/www/index.php/jauth/login/in?login=test&password=testtest&auth_url_return=http%3A%2F%2Feudala2.getxo.eus%2Flizmap%2Flizmap-web-client-master%2Flizmap%2Fwww%2Findex.php%2Fview%2Fmap%2F%3Frepository%3Dtest%26project%3Dvialidad_borrar) built for testing purposes.

You can edit any data and you will see the error when saving the form.

**Comment by rldhont** [comment]
Hi, @jaitor1 thanks for this map.
Which version do you use exactly ?
Have you plan to update to version 3.0 ?

**Comment by jaitor1** [comment]
Hi @rldhont,
I am using Lizmap 2.12.3.
Yes I am planning to upgrade to Lizmap 3 + QGIS 3 + QGIS Server 3 as soon as I read that all these version (v3) have been stabilized.
I am aware that this could not be this year.
We have now a pretty big mapping infraestructure with quite a lot maps now and more than 600 layers and we don't want to take risks when upgrading versions as Lizmap and QGIS is now a daily use tool for several employees in the council.

**Comment by rldhont** [comment]
Hi @jaitor1,

Can you update to Lizmap 2.12.6, we made some fixes on edition part.

**Comment by rldhont** [comment]
I close it, reopen if the issue still exists in 3.*
