### ISSUE TITLE
[Bug]: Lizmap not displaying qgis projects

### ISSUE THREAD

**Issue by Goneiross** [3liz/lizmap-web-client#2471]
### What is the bug?

Hi guys,

I'm trying to install lizmap on my server. However, after setting the repository in the maps management, I can't manage to have any project displaying on my browser.
My QGIS config is working, I tried it with this test [here](http://map.cloud-altetia.fr/qgisserver?MAP=/home/qgis/projects/world.qgs&LAYERS=countries&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG:4326&BBOX=-90,-180,90,180&WIDTH=400&HEIGHT=200&version=1.3.0).
I tried to use both http://map.cloud-altetia.fr/qgisserver/cgi-bin/qgis_mapserv.fcgi or http://map.cloud-altetia.fr/cgi-bin/qgis_mapserv.fcgi in the configs of lizmap.

Any idea ? 
Thanks for your time !

### Steps to reproduce the issue

Go to home or view a project, for example [here](http://map.cloud-altetia.fr/index.php/view/?repository=demo).

### Lizmap version

3.4.4

### QGIS desktop version

3.16

### QGIS server version

3.16

### Operating system

Ubuntu 21.04

### Browsers

Firefox

### Browsers version

Firefox 90.0

**Comment by Goneiross** [comment]
Wrong project version, sorry.

For those who have the same issue : open your project with the desktop app QGIS, install lizmap plugin for QGIS, configure it and export your data :)

**Comment by Gustry** [comment]
> http://map.cloud-altetia.fr/qgisserver/cgi-bin/qgis_mapserv.fcgi

You shouldn't expose your QGIS Server on the internet.
This URL should stay private, only used for Lizmap Web Client.

By exposing QGIS Server on the internet, your users can bypass all requests straight to QGIS Server without using LWC so all user permissions, security issues, versions etc are exposed on the web.

**Comment by Goneiross** [comment]
Oh I see, thank you for the advice, I'll correct this now !
