### ISSUE TITLE
postgresql search bar not returning any results from database

### ISSUE THREAD

**Issue by MidPiedmont** [3liz/lizmap-web-client#2474]
### Description
I set up PostgreSQL search, exactly as the "Spatial Searching" documentation would suggest, and the search bar appears in my Lizmap projects. The search bar will not return any results. Based on the documentation, it should be returning `item_layer` and `item_label`, but instead, it says "Map data No Results".

When I run 
`SELECT * FROM public.lizmap_search`
`LIMIT 100`
in pgAdmin4, I get 100 addresses from the address data I put in the `lizmap_search` materialized view. So I am fairly confident the table is configured properly

I am actively trying to troubleshoot this issue myself, but any help would be appreciated.

### Environment

 - Lizmap version: **3.5** most recent, master, as of 1 week ago
 - QGIS Server FULL version: `1:3.20.2+34hirsute` **3.20.2**
 - QGIS Desktop FULL version: `1:3.20.2+34hirsute` **3.20.2**
 - OS: Server is **Ubuntu Desktop**, Client is **Windows**
 - Browser: **Chrome**
 - Lizmap admin information stored in: default **sqlite**

**Comment by Gustry** [comment]
Does it work with the same use set in your INI file ?
Did you change the search_path ?
https://docs.lizmap.com/current/en/publish/configuration/spatial_search.html#configure-access
Does it work with `public` as mentioned in the doc?

**Comment by MidPiedmont** [comment]
> Does it work with the same use set in your INI file ?

I'm not sure what you mean by that, the only change to the INI was to add in the `[jdb:search]` chunk.

> Did you change the search_path ?

`search-path="public"` in `profiles.ini.php`

> https://docs.lizmap.com/current/en/publish/configuration/spatial_search.html#configure-access
> Does it work with `public` as mentioned in the doc?

`lizmap_search` materialized view is in the `public` schema

I tried to stick with the most basic default settings for now until I get everything working, then I'm gonna start tweaking for security. I followed the exact settings shown in the documentation

**Comment by mdouchin** [comment]
I think you could help us to understand what is problematic with these steps
* Open your browser developer tools, go to the Network tab, and see which request is launched when pressing Enter after having typed some search words. Please paste here the full query and the returned result
* Read the log files in your Lizmap installation `lizmap/var/log/` while running this request. If you see some errors, please paste them here
* If there is no error here, you could try to log the query in the PostgreSQL log file (by changing the  parameter `log_min_duration_statement`

**Comment by MidPiedmont** [comment]
>Request URL: http://robert-zimmerman72.tplinkdns.com/lm/index.php/lizmap/searchFts/get?repository=1&project=Traffic-Equipment-Map&query=Woolsey&bbox=-84.642733%2C33.329737%2C-83.891507%2C33.672657
Request Method: GET
Status Code: 200 OK
Remote Address: 76.17.40.242:80
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 3943
Content-Type: application/json
Date: Fri, 03 Sep 2021 15:56:54 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.46 (Ubuntu)
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: PHPSESSID=doo7ou91j1l35n4j6n71fnkmel; LizmapSession[auth]=dT49KWpqIjEjcCgyIzQ3YG1odGlnbVJsdWduaCpxe2ktKHg5KTprOSMwLixBc2x3LEllY31YeX4mJj9v
Host: robert-zimmerman72.tplinkdns.com
Referer: http://robert-zimmerman72.tplinkdns.com/lm/index.php/view/map/?repository=1&project=Traffic-Equipment-Map
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
X-Requested-With: XMLHttpRequest
repository: 1
project: Traffic-Equipment-Map
query: Woolsey
bbox: -84.642733,33.329737,-83.891507,33.672657

**Comment by mdouchin** [comment]
It seems the query works well with no error, and returns the expected data 

```json
{
  "Address": {
    "search_name": "Address",
    "layer_name": "Address",
    "srid": "EPSG:6447",
    "features": [
      {
        "label": "Woolsey Rd, Hampton 30228",
        "geometry": "MULTIPOINT(2229500.928419755 1225301.2128765816,2230668.143944242 1221083.1568874926,2232238.904064446 1223702.150702786,2232340.2368475394 1223200.122394132,2232507.9674196644 1223052.1497667844,2232651.3560878034 1226273.0118414506,2233720.328517946 1224973.2376867163,2234148.7661837777 1226364.114511158,2234166.99974444 1233494.8684560698,2234217.7272959226 1225154.0784923143,2234595.068320073 1232603.8939460458,2234647.1703716503 1225322.2054769273,2234669.7929789904 1232711.617039934,2234730.630588755 1225957.806147,2234758.2990621314 1232809.2648330107,2235319.362347628 1225295.0782222932,2236247.5329629155 1234353.3852122661,2238514.340213859 1234629.0364778661,2239014.4601351833 1234969.3282019806)"
      },
      {
        "label": "14601 Woolsey Rd, Hampton 30228",
        "geometry": "MULTIPOINT(2230844.4555089124 1222499.1036888747)"
      },
      {
        "label": "14360 Woolsey Rd, Hampton 30228",
        "geometry": "MULTIPOINT(2232460.5190688088 1223639.487530404)"
      },
      {
        "label": "14372 Woolsey Rd, Hampton 30228",
        "geometry": "MULTIPOINT(2232179.85085046 1223541.756863635)"
      }
    ]
  }
}
```
Perhaps the `MULTIPOINT` geometry type is not supported by Lizmap search bar ?

Do you have any error logged in the browser developer tool panel, in the "Console" tab ?

The returned

**Comment by MidPiedmont** [comment]
console:
jquery-migrate-3.3.1.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.1
robert-zimmerman72.tplinkdns.com/:49 GET http://robert-zimmerman72.tplinkdns.com/lm/assets/js/lizmap.js net::ERR_ABORTED 404 (Not Found)
[Violation] Added non-passive event listener to event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
jquery-3.5.1.min.js:2 [Violation] 'load' handler took 6081ms
[Violation] Forced reflow while executing JavaScript took 1392ms

**Comment by MidPiedmont** [comment]
I checked the lizmap error log, it's said
>2021-09-03 18:15:04     172.58.4.68     error   2021-09-03 18:15:04     [403]   invalid query (ERROR:  syntax error at or near "."
LINE 1: SET search_path TO public.lizmap_search
                                 ^(SET search_path TO public.lizmap_search))    /var/www/lizmap-web-client-master/lib/jelix/plugins/db/pgsql/pgsql.db>

so I set the search_path to `"public.lizmap_search"`, and then the map wouldn't load at all, so I changed it back to `"public"`

**Comment by mdouchin** [comment]
A valid search_path in PostgreSQL is a list of schemas separated by comma. You must not add the table name. Since your table (or view) `lizmap_search` is in the public schema, there is no need to override the `search_path` in the `profiles.ini.php` file.
So you can leave it undefined or use "public".

**Comment by MidPiedmont** [comment]
Well that would explain 
>so I set the search_path to "public.lizmap_search", and then the map wouldn't load at all, so I changed it back to "public"
😂

**Comment by MidPiedmont** [comment]
Okay, so I converted the address dataset to singlepoint and got rid of duplicate points. I dropped the materialized view and created another with the new address dataset. Querying the database still returns positive results like last time around, but the web map search bar yet again returns no results. -_-

**Comment by MidPiedmont** [comment]
Console Errors from Chrome:
>`JQMIGRATE: Migrate is installed, version 3.3.1
lizmap.js:1 `

>`Failed to load resource: the server responded with a status of 404 (Not Found)
/lm/assets/js/Proj4js/defs/EPSG6447.js:1` 

>`Failed to load resource: the server responded with a status of 404 (Not Found)
spatialreference.org/ref/epsg/6447/proj4js/:1` 

>`Failed to load resource: the server responded with a status of 404 (NOT FOUND)`

Checking the network tab shows that lizmap successfully queried the database and was returned address points, it just didn't display them in the results from the search box.

There are no errors in the Lizmap errors log after I removed the `search_path` line from the .ini file.

**Comment by ygorigor** [comment]
@MidPiedmont This is the reason
`Failed to load resource: the server responded with a status of 404 (Not Found) spatialreference.org/ref/epsg/6447/proj4js/:1`

**Comment by MidPiedmont** [comment]
So it did have to do with the CRS after all, I had a hunch last week, but I hate using the wrong CRS for my area. I wonder what CRS's *are* supported...

**Comment by ygorigor** [comment]
@MidPiedmont 
https://github.com/3liz/lizmap-web-client/tree/master/lizmap/www/assets/js/Proj4js/defs

**Comment by MidPiedmont** [comment]
Okay, got it done, thank you all for your help. Just in case anyone else ends up looking at this question in the future, here are the final steps:

Convert PostgreSQL address table into a spatial reference that is available on [spatialreference.org](url) using QGIS. I chose 2440, my StatePlane CRS, a version that is available as opposed to the original 6447 because they don't have that one as evidenced by the console error @ygorigor pointed out.

Add in `EPSG2440.js` (used `touch EPSG2440.js` in ubuntu command) into `...assets/js` folder, copied the javascript from [spatialreference.org/ref/epsg/2440/proj4js/](url), wrote it out, restarted apache for good measure. Exact commands are below.

`cd /var/www/lizmap-web-client-master/lizmap/www/assets/js`
`sudo touch EPSG2440.js`
`sudo nano EPSG2440.js`
copy and paste contents of [spatialreference.org/ref/epsg/2440/proj4js/](url) into `EPSG2440.js`
_ctrl + o  ,  ctrl + x_
`sudo service apache2 restart`

And that did the trick. And btw, this search function is lightning fast! I don't know how you made it work so well!

**Comment by mdouchin** [comment]
Thanks a lot for your feedback. I think we could enhance the documentation about this. We tried indeed to have a automatic fetching of the projection from spatialreference.org, but it does not always work.

**Comment by mdouchin** [comment]
@MidPiedmont you could perhaps propose a PR to add the file in the source code inside `lizmap/www/assets/js/` ? 

About the "lightning fast" function, we should all thank the AWESOME PostgreSQL/PostGIS community for their tremendous job ! The trick is to use an GIN index base on the trigram extension

See: https://docs.lizmap.com/next/fr/publish/configuration/spatial_search.html#optimisation

**Comment by MidPiedmont** [comment]
I feel like the automatic fetching definitely works on your end, [spatialreference.org](spatialreference.org) just has to have the CRS in question. I just added mine to lizmap assets to see if I could and it worked, so that was nice for sure.
