### ISSUE TITLE
Use .svg

### ISSUE THREAD

**Issue by vincent-petale** [3liz/lizmap-web-client#249]
Bonjour,
je me confronte à un nouveau problème, je n'arrive pas à faire apparaître mes symboles svg sur ma carte.

> en essayant de comprendre via le fichier montpellier.qgs je trouve bien une référence à des fichiers .svg  du type **file="/usr/share/qgis/svg/arrows/Arrow_05.svg"**

> j'ai créé des dossiers dédiés aux svg en local, puis avec la même arborescence sur mon serveur et y ai placé mes symboles. J'ai ensuite ouvert mon projet avec un éditeur de texte, y ai localisé les fichiers et vérifié le chemin relatif du serveur. J ne vois cependant de ligne commençant par **file="..."** mais par **v="..."**

> j'ai aussi vu ce genre de problème sur le web mais je ne trouve pas de solution qui fonctionne chez moi, je dois mal m'y prendre et comme vous l'aurez compris je débute...

Merci d'avance pour votre aide

**Comment by mdouchin** [comment]
Bonjour,

Pour ce genre de questions sur l'utilisation de l'outil, merci d'utiliser un forum, par exemple ForumSIG : http://www.forumsig.org/tags.php?tag=lizmap
Nous pourrons y répondre, ainsi que d'autres personnes connaissant bien QGIS et Lizmap.

Les "issues" de Github sont là pour gérer les bugs et les nouvelles fonctionnalités. Elles doivent être écrites en anglais pour que l'ensemble des utilisateurs puisse les lire.

**Comment by vincent-petale** [comment]
ok pardon, j'ai republié sur GeoRezo.
Bonne suite
