### ISSUE TITLE
Clé "choisirgeoportail" et "pratique" plus disponible au 1er février 2022

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#2496]
Il semble que les différentes couches resteront disponibles en utilisant d'autres clés (decouverte, essentiels,...) : https://geoservices.ign.fr/services-web
A tester.

**Comment by Gustry** [comment]
Il faut lister par clé, les couches disponibles dans chaque service et savoir ce que l'on garde ou pas. Je me suis assigné aussi pour la partie bureautique.

Par contre, cela semble déjà en marche ces nouvelles clés, donc il ne faudra pas attendre.

**Comment by arthuragone** [comment]
La quasi-totalité des couches sont désormais accessibles sans clefs. Mais l'adresse des couches a été modifiée. C'est à mon sens ça qu'il faut mettre à jour. Cdt

**Comment by Gustry** [comment]
Selon le PR #2619, quelles sont les modifications à prendre en compte dans l'extension Lizmap ?
CC @pdrillin

**Comment by Gustry** [comment]
PR : https://github.com/3liz/lizmap-plugin/pull/390
