### ISSUE TITLE
Javascript execution in popup

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#250]
Hello everybody
we are testing Lizmap 3 beta. Making some test on using simple javascript in popup personalization we saw that no result comes from popup execution.
Is there any block on javascript execution in Web client?
Is it possible to enable js execution in popup?
Thanks
Pietro

**Comment by mdouchin** [comment]
Hi,
See documentation here : http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#adding-your-own-javascript

**Comment by pieri70** [comment]
Thank you!
We will test and report.
Pietro

**Comment by pieri70** [comment]
Ok, it works as expected!
Thanks

**Comment by rldhont** [comment]
Great, I closed this question reopen if needed
