### ISSUE TITLE
Migrating lizmap data when upgrading version

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#251]
I am planning to upgrade my current Lizmap 2.11beta5 to the last 2.12.3.

Is there any way I can migrate my users, permissions, repositories?

Or do I have to manually add every user, premission, create repos, etc?

**Comment by nboisteault** [comment]
All you need is here :+1: 
http://docs.3liz.com/en/admin_guide/installation/linux.html#version-upgrade

**Comment by jaitor1** [comment]
Thanks for the info!!!
