### ISSUE TITLE
Release 3.4.5 Fichier manquant dans l'archive tar.gz

### ISSUE THREAD

**Issue by aberceaux** [3liz/lizmap-web-client#2514]
### What is the bug?

Bonjour,

Je vous signale que le fichier lizmap.js est absent du répertoire \lizmap\www\assets\js

Merci

### Steps to reproduce the issue

Télécharger le fichier : https://github.com/3liz/lizmap-web-client/archive/refs/tags/3.4.5.tar.gz

### Lizmap version

3.4.5

### QGIS desktop version

3.4.5

### QGIS server version

3.4.5

### Operating system

Windows 10

### Browsers

Firefox

### Browsers version

Firefox 92

**Comment by mdouchin** [comment]
As written in the [Installation file](./INSTALL.md#get-the-source) file, you should not use the source code, but the generated package. In the [release page](https://github.com/3liz/lizmap-web-client/releases), Get the ZIP `lizmap-web-client-3.4.6.zip` and not the "Source code" archives.
