### ISSUE TITLE
[Bug]: Print not available in master

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#2518]
### What is the bug?

Print not available in master

### Steps to reproduce the issue

1. Go to Montpellier project
2. Print is no more available in dock

### Lizmap version

master

### QGIS desktop version

3.16

### QGIS server version

3.16

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

93

**Comment by nboisteault** [comment]
@laurentj https://github.com/3liz/lizmap-web-client/commit/78af786e6d60c92850095b4b23b8ffb28ab96776 is causing the issue.
You can reproduce the issue with attached QGIS project in tests docker stack.
[qgis_print.zip](https://github.com/3liz/lizmap-web-client/files/7249799/qgis_print.zip)

**Comment by laurentj** [comment]
fixed
