### ISSUE TITLE
Problem with duplicate layers

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#252]
I have a GeoTIFF raster file that I try to visualize in two groups using different title and name. 

QWC works fine, Lizmap webclient visualize only the layers in the first group. It is a known bug or I do something wrong?

**Comment by nboisteault** [comment]
Can you give us links to QWC and lizmap?

**Comment by rmarzocchi84** [comment]
Lizmap:
http://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/view/map/?repository=gter&
project=mappa_interventi


QWC (has a problem with the startextent but if you zoom out you can 
correctly see the layers):
http://www.gishosting.gter.it/qgis/site/qgiswebclient.html?map=/home/gter/progetti/mappa_interventi.qgs



Il 10/02/2016 11:45, Nicolas Boisteault ha scritto:
>
> Can you give us links to QWC and lizmap?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/3liz/lizmap-web-client/issues/252#issuecomment-182308965>.
>

-- 
Eng. Roberto Marzocchi, PhD
GIS Project Coordinator
Gter srl Innovazione in Geomatica, Gnss e Gis (Unige spin-off)
Piazza De Marini 3/61 - 16123 Genova
P.IVA/CF 01998770992
ph: 010-8694830 - mob: 349-8786575
E-mail: roberto.marzocchi@gter.it
skype: roberto.marzocchi84
www.gter.it

--
Gter social
www.twitter.com/Gteronline - www.facebook.com/Gteronline - https://plus.google.com/+GterIt/posts
www.linkedin.com/company/gter-srl-innovazione-in-geomatica-gnss-e-gis

-----------------------------------------------------------------
Please consider the environment before printing this email!

**Comment by rldhont** [comment]
Hi @rmarzocchi84 
The lizmap config does not have references about your layers in the 'interventi consigliati'. You have to update your Lizmap config with the Lizmap plugin and push it to the server.

If you update your QGIS project, don't forget to update the lizmap config.

QWC only depends on QGIS project.

**Comment by rmarzocchi84** [comment]
OK! sorry, you are right when I change the name of the layers in the secodn group I did not update the lizmap config. :-(

R

**Comment by rmarzocchi84** [comment]
The mutually exclusive group option can be reproduced also in Lizmap?

R

**Comment by gioman** [comment]
see also https://github.com/3liz/lizmap-web-client/issues/37

**Comment by rldhont** [comment]
Hi @rmarzocchi84, not yet.

If you're interested in it, follow #37 

I close this issue because the new discussion is a duplicated one and it's different from the title.
