### ISSUE TITLE
3D Pointclouds in Lizmap with Potree

### ISSUE THREAD

**Issue by asdro-f** [3liz/lizmap-web-client#2522]
Hello Community,

i try to enable 3D-Pointclouds in Lizmap with the Potree-Viewer: [url](https://github.com/potree/potree/).

I can use Potree on localhost and on my Webserver where Lizmap is running in the html Directory, but of course this isnt protected by password automaticly throug Lizmap.

But when i try to open it within a Lizmap-Project, which isnt stored in, but triggered from, the html-Directory, i get errors with 'require'.

I think this isnt a Lizmap Problem, but perhaps a user had and solved this or similiar Problems before...

With relative pathes I had Problems in the past when I tried to build Buttons for Media-Download, but I solved this with a workaround (scripts which update the relative paths in the necessary files to absolute paths).

Someone know a solution for my problem with relative paths in Lizmap?
Someone had success with Potree within Lizmap?
Someone know a good (and fast) 3D-Viewer, except qgis2threejs, which is easy to use and compatible to Lizmap (Automaticly password protected throug the Lizmap Projects)

Thanks for help and best regards

**Comment by Gustry** [comment]
Side question, do you have a screenshot or GIF that you can do ? mostly to show the integration with Lizmap ?

**Comment by Cww7** [comment]
Hi,

did you manage to integrate potree into lizmap? I have the same problem with relative paths.

**Comment by asdro-f** [comment]
@Cww7 unfortunately i didnt

**Comment by danzo-git** [comment]
did you find any solution?
