### ISSUE TITLE
[Bug]: Edition issues for Postgis layer for fields that a "space" in name

### ISSUE THREAD

**Issue by CorentinLemaitre** [3liz/lizmap-web-client#2524]
### What is the bug?

When you are using lizmap viewer online, you start editing a layer. You fill the form and save it. 

All the values user have written in a field that have space in name are not taken in account and NULL value are sent to the data base to replace what user have written. If there is a rule activated to verify the value is not null, then you can not do any edition. I tried different form style to understand where the issue is coming from. 

The solution was for me to not put any space in the field name, it is a general good practice so i'm ok with this. I think a better solution will be to share this information with user when edition is done or when a layer is created because I think some problems could be related with this kind of not logical reaction of lizmap edition. 

### Steps to reproduce the issue

1. Create a database with field that have space in it :  
``` 
CREATE TABLE "Mobilite"."road_change" (
    id SERIAL PRIMARY KEY,
    geom geometry(Linestring, 2154),
    "Type de modification" varchar(80),
    "Info" varchar(200),
    "Source" varchar(30) 
);
```
2. Integrate this layer in a QGIS project, activate WFS 
3. Use the lizmap plugin to activate edition on this layer and send the project online. 

### Lizmap version

3.4.4

### QGIS desktop version

3.10

### QGIS server version

3.4.6

### Operating system

Windows 10

### Browsers

Chrome

### Browsers version

Chrome 93.0.4577.82

**Comment by Gustry** [comment]
Thanks for sharing the feedback.

Indeed, I think it's way better to not have any space in a field name.
In QGIS (and therefore Lizmap), you should use "alias", which is the proper way to set the human readable field name.
https://docs.qgis.org/3.16/fr/docs/user_manual/working_with_vector/vector_properties.html?highlight=alias#fields-properties
https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/vector_properties.html?highlight=alias#fields-properties

I don't think this will be fixed in Lizmap to support fields with space. But I agree, some logs would help, did you check logs ?
I just added a line in the documentation.

**Comment by CorentinLemaitre** [comment]
I understand perfectly it will not be fixed. As I use no more shape since 3 years and a lot of geopackage I have used much more explicit column title. It is really comfortable but I know there could be issues with this. As most of the function will work normally, I think some issues I did have with lizmap could be related to this (constraints based on expression for example). 

### The logs 
I have no error logs. 
I have checked also the "logs détaillés" there is all my different try that are shown with NULL values (even if I typed other values). 

Here is one of the last try : 

<html>
<body>


editionSaveFeature | 29/09/2021 16:55:49 |   | UPDATE table="Mobilite"."V84_modification", id=Evolutions_itinéraire.1, pkeys={"id":"1"}, ("geom"=ST_GeomFromText('LINESTRING(641796.0420154259 6268549.247814079,642664.4779256659 6267835.650986538,642896.1001038338 6267335.358900139,644894.2847329209 6267124.048883567,645832.5902085089 6266396.290053175,647027.5824319429 6266441.637671176,648078.9349348139 6265907.003032575,648523.7807582099 6265944.932022617,649274.5485606849 6266021.983348648)', 2154), "Type modification"=NULL) | mobilite | SIG_V84
-- | -- | -- | -- | -- | --



</body>
</html>

And then after changing the column name, the value changes were included in the database : 

<html>
<body>


editionSaveFeature | 29/09/2021 17:02:32 |   | UPDATE table="Mobilite"."V84_modification", id=Evolutions_itinéraire.1, pkeys={"id":"1"}, ("geom"=ST_GeomFromText('LINESTRING(641796.0420154259 6268549.247814066,642664.4779256659 6267835.650986526,642896.1001038338 6267335.35890013,644894.2847329209 6267124.048883557,645832.5902085089 6266396.290053156,647027.5824319429 6266441.637671169,648078.9349348139 6265907.003032565,648523.7807582099 6265944.932022608,649274.5485606849 6266021.983348639)', 2154), "Type"='Correction') | mobilite | SIG_V84
-- | -- | -- | -- | -- | --


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Gustry** [comment]
I think you shouldn't use space in field name and define alias on columns. It's designed for this. Toggle editing mode, vector layer properties, "attributes" tab, then you can add alias on fields with spaces. These will be used in Lizmap for display etc, in QGIS Attribute table etc.
