### ISSUE TITLE
Expression to calculate X and Y in editable layers does not work

### ISSUE THREAD

**Issue by Andrea996** [3liz/lizmap-web-client#2526]
Hi, I have created a Lizmap project with editing on layers.
The editable layers are hosted on PostgreSQL database.
Some fields of these layers are automatically filled with expressions written in QGIS.
Some work correctly others do not, for example the coordinates field I entered the expression $ X to automatically calculate the X of the inserted point but this expression does not work in LizMap

Thanks

 - Lizmap version: 
 - QGIS Server FULL version: 3.20
 - QGIS Desktop FULL version: 2.16
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Chrome

**Comment by Gustry** [comment]
Which other expressions work ?
Which version of Lizmap plugin version on the server ?

Can you switch to `x(@current_geometry)` ?
https://docs.lizmap.com/next/en/publish/configuration/layer.html#edition-expressions

**Comment by Andrea996** [comment]
Hi, no 
not found x(@current_geometry)

this example expression works in my project
if (maximum (id) IS NULL, 1, maximum (id) +1)
