### ISSUE TITLE
Lizmap 3: change layer style

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#253]
I'd like to use this new feature but there is no documentation.
I have created two styles for my layer in Qgis (2.8).
When i use the "Change Style Layer" button in Lizmap, my style list is correctly displayed, but i cannot select one.
I try to save the style (qml file) in data repertory, without success.

If this feature is implemented, could you explain the process to use it ?

Thanks in advance.

**Comment by rldhont** [comment]
Hi @geoek,

You just have to create 2 styles in QGIS and stored it in the project, no qml file needed. The 2 different styles has to have different names.

But I don't know if QGIS Server 2.8 has implemented this feature.

**Comment by geoek** [comment]
Thanks a lot.
You' re right. It's because this feature is not implement in server 2.8 while it was add in Qgis 2.8 (or 2.6).
Another reason to update its server ...

**Comment by geoek** [comment]
Hi!
I have updated my configuration. I now use Qgis Server 2.14.1 and Lizmap 3 Beta4.
I still have this wrong behaviour : With Qgis, I have two style for one layer and i can switch without problem.
With Lizmap, the style list of my layer is correctly displayed but i cannot switch : the style usedduring the project saving is always displayed.

Has anyone managed to use this feature ?

**Comment by rldhont** [comment]
Hi @geoek,

You can test it with the Montpellier project. The layer tramways has 2 styles: black and colored.

**Comment by geoek** [comment]
Thanks for this answer !

I have the same behaviour with the demo project... Any idea ?

**Comment by rldhont** [comment]
Clear the temp/lizmap/www directory and verify the WMS GetCapabilities

**Comment by geoek** [comment]
I have clear the temp/lizmap/www directory but no result.
Both style are correctly defined in the WMS GetCapabilities.

Has anyone managed to use this feature with lizmap beta4 or is it a bug?

**Comment by josemvm** [comment]
I' ve the same behaviour too with the demo project

**Comment by rldhont** [comment]
@geoek and @josemvm which QGIS Server version did you use ?
Have you test the request directly to the server ?

**Comment by josemvm** [comment]
i'm using 2.14.2, server and desktop versions. i didn't request  directly to the server (how can I do that?)

**Comment by gioman** [comment]
>  i didn't request directly to the server (how can I do that?)

with a getmap request

**Comment by geoek** [comment]
I'm using 2.14.1 server.
With the following request, i obtain the "colored" line whereas "STYLES = black" : 
http://my_ip/lm/index.php/lizmap/service/?repository=montpellier&project=montpellier&LAYERS=tramway&STYLES=black&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&BBOX=422580.2407491475,5403192.011786673,441020.6738203793,5408657.259308301&WIDTH=1930&HEIGHT=572

(this request is issued from the network section of the chrome debugger)

**Comment by mdouchin** [comment]
I juste tested your request in some Lizmap with QGIS Server 2.14.2, and I cannot reproduce your bug. Have you force the refresh of the request ( CTRL + R or CTRL+F5, or empty browser cache and reload)

**Comment by josemvm** [comment]
now, i think that's a really browser cache issue...

after empty the browser cache, i get the black lines for the tramway layer with the same request and i get too the same results through the LWC

**Comment by geoek** [comment]
Really strange...
I clean the cache and also try with another browser but i cannot obtain the black lines...

**Comment by josemvm** [comment]
indeed, it seems that something is not right...
i tried with another installation and i can't get the black lines...

**Comment by rldhont** [comment]
I have tested this 2 lizmap URLs:
* BLACK http://my_ip/lm/index.php/lizmap/service/?repository=montpellier&project=montpellier&LAYERS=tramway&STYLES=black&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&BBOX=422580.2407491475,5403192.011786673,441020.6738203793,5408657.259308301&WIDTH=1930&HEIGHT=572
* COLORED http://my_ip/lm/index.php/lizmap/service/?repository=montpellier&project=montpellier&LAYERS=tramway&STYLES=colored&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&BBOX=422580.2407491475,5403192.011786673,441020.6738203793,5408657.259308301&WIDTH=1930&HEIGHT=572
They work!

You can test the sames but directly with QGIS-server
* BLACK http://my_ip/cgi-bin/qgis_mapserv.fcgi/?MAP=/path/to/lizmap/install/qgis/montpellier.qgs&LAYERS=tramway&STYLES=black&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&BBOX=422580.2407491475,5403192.011786673,441020.6738203793,5408657.259308301&WIDTH=1930&HEIGHT=572
* COLORED http://my_ip/cgi-bin/qgis_mapserv.fcgi/?MAP=/path/to/lizmap/install/qgis/montpellier.qgs&LAYERS=tramway&STYLES=colored&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&BBOX=422580.2407491475,5403192.011786673,441020.6738203793,5408657.259308301&WIDTH=1930&HEIGHT=572
You have to change the `/path/to/lizmap` to test its.

**Comment by geoek** [comment]
It doesn't work for me ! I obtain the colored lines even if STYLES=black in the request...

**Comment by rldhont** [comment]
If it doesn't work for you even if directly from QGIS-Server, it's much more a QGIS-Server issue and not a Lizmap one.

**Comment by geoek** [comment]
I agree with you. I close this issue and will report it to Qgis Server tracking.
