### ISSUE TITLE
Modify the html page

### ISSUE THREAD

**Issue by ludovico85** [3liz/lizmap-web-client#2532]
### Description

Hi, it is possible to modify the base html page? Where is located? I already know how to customize the default theme through the CSS. Thanks!

### Environment

 - Lizmap version: 
 - QGIS Server FULL version: 3.4.4
 - QGIS Desktop FULL version: 3.10.14
 - OS (Windows, Linux, MacOS, Android…): ubuntu

**Comment by ludovico85** [comment]
> Hi, Lizmap is based on the Jelix framework. Take a look at the template part of the documentation => https://docs.jelix.org/en/manual/components/templates#template-files And how to create your theme : https://docs.jelix.org/en/manual/application/themes

Hi, from th jelix documentation: "The default theme is in the directory app/themes/default/. So the app/themes/default/my_module/my_template.tpl redefines the template my_module/templates/my_template.tpl". However, I can't find the default theme in my lizmap installation.  
I found in the lizmap/modules the template for each modules in the respective template folder (e.g. the module admin contain the templates folder with template's file. I can directly modify the templates in these folders but I suppose it isn't the right way.

**Comment by nboisteault** [comment]
Sorry Lizmap is based on Jelix 1.6 not 1.7, so the correct link was https://docs.jelix.org/en/manual-1.6/templates#redefining-a-template. So default theme is in `var/themes/default/`.

**Comment by ludovico85** [comment]
Thanks, it works!
For those who want to try to change the default theme. For example, if you want to modify the template main.tpl of the module view which is stored in the /lizmap/modules/view/templates folder:

Create a folder in the default dir with the same name of the module:
`sudo mkdir /var/themes/default/view`
Copy the main.tpl file
`sudo cp /lizmap/modules/view/templates/main.tpl /var/themes/default/view`
Now you can change the main.tpl module.

**Comment by Gustry** [comment]
Great that it works for you !

Do you think we need to update https://github.com/3liz/lizmap-documentation/blob/master/source/publish/customization/themes.rst ? Source of https://docs.lizmap.com/next/fr/publish/customization/themes.html

Do you think you can make a small text explaining from your point of view @ludovico85 ?

**Comment by ludovico85** [comment]
> Great that it works for you !
> 
> Do you think we need to update https://github.com/3liz/lizmap-documentation/blob/master/source/publish/customization/themes.rst ? Source of https://docs.lizmap.com/next/fr/publish/customization/themes.html
> 
> Do you think you can make a small text explaining from your point of view @ludovico85 ?

Of course! I've already opened a PR https://github.com/3liz/lizmap-documentation/pull/187
