### ISSUE TITLE
[Bug]: Drawings are not printed if the layout has 2 maps and one is the overview of the other

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2533]
### What is the bug?

I noticed that in layouts with 2 maps where one is the overview of the other, the drawings (manual, or by importing a KML) will not show in the main map object when printed.

### Steps to reproduce the issue

Just create a layout with two maps, one being the overview for the other.

Draw some shape on map, print.

### Lizmap version

3.4.3

### QGIS desktop version

3.16.11

### QGIS server version

3.16.11

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

Latest for both FF and Chrome

**Comment by cxcandid** [comment]
It's possible to create overviews in print layouts, if we configure the overview window in Lizmap. Therefor we need to add a layer group called "Overview" to our QGIS project. In the print layout, we must add a second map as overview. I changed the map id to "Overview" but I guess that's not necessary. When printing, Lizmap substitutes the second map with the extent and layers of the overview group. Unfortunately, the size of the printed overview corresponds to the overview window in Lizmap.

**Comment by meyerlor** [comment]
The workaround from @cxcandid seems not to work anymore with LWC 3.7.3

**Comment by nboisteault** [comment]
It has been fixed: https://github.com/3liz/lizmap-web-client/issues/1605#issuecomment-2209254912
