### ISSUE TITLE
My project repository does not load with invalid .qgs.cfg error

### ISSUE THREAD

**Issue by jmarpi** [3liz/lizmap-web-client#2538]
### Environment

 - Lizmap version: 3.4.0
 - QGIS Server FULL version: 3
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): ubuntu 20.0.4
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? 
 
I have a problem with lizmap, I followed the tutorial. https://docs.lizmap.com/3.4/en/install/linux.html
When setting up a repository I have my .qgs and qgs.cfg files.
No project appears and the following error is generated in the lizmap logs.
![image](https://user-images.githubusercontent.com/29391851/137359839-11427b54-0117-4b0a-8482-dc40210c7950.png)
![image](https://user-images.githubusercontent.com/29391851/137362054-b8e5a7cb-6956-453b-9d4a-9dabc7f6aa93.png)

any idea how to solve?

Excuse me, for my writing, my English is not very good

**Comment by ygorigor** [comment]
@jmarpi did you edited cfg manually?

**Comment by jmarpi** [comment]
> @jmarpi did you edited cfg manually?
I had used the files in lizmap 3.4.0 on windows, where it worked perfectly.
 Now migrate to ubuntu but I have the mentioned errors

**Comment by jmarpi** [comment]
Thank you very much, what happened was the following:
I resorted to different forums, executing different commands such as chmod 777 and chown, now the projects I have can be viewed
![image](https://user-images.githubusercontent.com/29391851/137497725-cea63050-a03f-4b65-9086-1686490bd06b.png)

Now, I have the following problem:

 /var/www/lizmap/lizmap/modules/lizmap/classes/lizmapProxy.class.php	249 
2021-10-15 15:40:57	localhost	error	GetCapabilities empty data
2021-10-15 15:40:57	localhost	warning	2021-10-15 15:40:57	[2]	file_get_contents(http://localhost:90/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Flizmap%2Flizmap%2Fprojects%2Fanalitics%2Eqgs&amp;request=GetCapabilities&amp;service=WMS&amp;version=1%2E3%2E0&amp;Lizmap%5FUser=&amp;Lizmap%5FUser%5FGroups=): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/var/www/lizmap/lizmap/modules/lizmap/classes/lizmapProxy.class.php	249 

![image](https://user-images.githubusercontent.com/29391851/137498836-465e5b39-d626-4a22-a2b1-e3b9e5b54b40.png)

**Comment by jmarpi** [comment]
When I open the link: `http://localhost:90/cgi-bin/qgis_mapserv.fcgi`
I get the following:
![image](https://user-images.githubusercontent.com/29391851/137540045-a3bcc49e-acd3-4dc7-add3-6a3de5c57ca3.png)
 and running the command: `/usr/lib/cgi-bin/qgis_mapserv.fcgi`
I have this:
Application path not initialized
Application path not initialized
Application path not initialized
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
Initializing server modules from  "/usr/lib/qgis/server" 

"Checking /usr/lib/qgis/server for native services modules"
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
Logged warning: Loading a file that was saved with an older version of qgis (saved in 0.0.0, loaded in 3.10.4-A Coruña). Problems may occur.
Content-Length: 206
Content-Type: text/xml; charset=utf-8
Server:  Qgis FCGI server - QGis version 3.10.4-A Coruña
Status:  200

<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
 <ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>
</ServiceExceptionReport>
root@localhost:/usr/lib/cgi-bin# /usr/lib/cgi-bin/qgis_mapserv.fcgi

Is the qgis server ok?, Is the url of the qgis server wrong in lizmap?
