### ISSUE TITLE
Total Length not Visible in Data Viz

### ISSUE THREAD

**Issue by paruljain689** [3liz/lizmap-web-client#2539]
### Description
I am created a QGIS project and configure with liz. I have a cable layer and i want to see the Graph with total length based on users or area. please guide a way

### Environment

 - Lizmap version: 3.4.6
 - QGIS Server FULL version:
 - QGIS Desktop FULL version:3.10.4
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Geopackage

**Comment by Gustry** [comment]
What do you mean "based on users" ?

You can have a look to : 
* https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/tools/show_statistics_on_selection if it fits your needs.
* Or https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=covid_19_fr like these orange boxes. These are HTML template dataviz. https://docs.lizmap.com/current/fr/publish/lizmap_plugin/dataviz.html#types-of-charts
