### ISSUE TITLE
issue in the metadata abstract

### ISSUE THREAD

**Issue by ilamarengo** [3liz/lizmap-web-client#254]
Hi,

i am using lizmap3 and for each layer i have in QGIS project I am adding an abstract in the metadata section provided by lizmap (see figure). However, although i add the html code for starting and ending a paragraph, the setting it is not "memorised" by lizmap once i publish the project. Precisely what lizmap is struggling to do is to save the setting permanently. in fact, if i reload the QGIS project twice, the first time all is OK, the second time i will not be able to see the correct way of displaying the paragraph.
Is there a way to fix the issue? Where i am wrong?
Thank you very much,
iLaria

![metadata_abstractprob](https://cloud.githubusercontent.com/assets/17223497/13036025/5bea7d14-d33b-11e5-977e-0bd0637a6b09.jpg)

**Comment by gioman** [comment]
see also https://github.com/3liz/lizmap-web-client/issues/244 (?)

**Comment by ilamarengo** [comment]
@gioman you are right, thanks. It is the same problem logged into #244. This issue can be closed. Apologies.
