### ISSUE TITLE
Expression to populate one field based on another field value does not work

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2540]
### What is the bug?

i'am using a case expression for default value

![imagem](https://user-images.githubusercontent.com/10053874/137626752-cefaa556-e83f-4c04-9dc3-5985d2e161fa.png)
and when i use edition form on qgis desktop it works as expected
![imagem](https://user-images.githubusercontent.com/10053874/137627152-6eb92a2f-d4a2-4917-a432-f978c4e2daec.png)
but not on lizmap
![imagem](https://user-images.githubusercontent.com/10053874/137627296-48b75173-d811-4511-8eb9-7a30956c5215.png)

lizmap plugin version: 3.6.3

### Steps to reproduce the issue

.

### Lizmap version

3.4.6

### QGIS desktop version

3.16.10

### QGIS server version

3.16.10

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

93.0

**Comment by josemvm** [comment]
hi @Gustry is it expected to work with lizmap plugin installed on qgis server (or not) ?
thanks

**Comment by Gustry** [comment]
It depends of the content of the expression. Expressions not using fields with are within the same form are working, such as dates, `@lizmap_user`...
It's a just a quick answer, I don't know all corner cases, when/where expressions are evaluated (especially when fields are involved)

**Comment by josemvm** [comment]
i think this issue can probably be closed, since it appears to have been resolved by this PR https://github.com/3liz/lizmap-web-client/pull/6818
@meyerlor  could you confirm?

**Comment by meyerlor** [comment]
yes, that's true - but the issue is closed already, no? :)

**Comment by josemvm** [comment]
> but the issue is closed already, no?

Yes, of course it is! 🙂
thanks again
