### ISSUE TITLE
[Bug]: The first feature's popup is displayed from a click in the attribute table

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#2544]
### What is the bug?

I couldn't replicate the issue on the cats demo project.

But on the Leman (and also on my other Lizmap with other project) I can replicate.
The layer is not stored in PG according to the other participant, so it's not the issue about int4, int8.

https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=leman

### Steps to reproduce the issue

Go to https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=leman

Open the attribute table

Open the "I" button to display the popup

Check which popup is displayed, it's the always the first one

![wrong_popup](https://user-images.githubusercontent.com/1609292/137902240-44135134-7510-4f8c-a6e9-c83a70f0e55e.gif)

### Lizmap version

3.4.6

### QGIS desktop version

3.10 and 3.16

### QGIS server version

3.10 and 3.16

### Operating system

Ubuntu, windows

### Browsers

Firefox

### Browsers version

latest

**Comment by nboisteault** [comment]
I can't reproduce issue with `master` with QGIS Server 3.16.14 with pgsql and shapefile layers.
What's the QGIS Server full version?
I'm going to test with Lizmap 3.4.

**Comment by Gustry** [comment]
@nboisteault The bug is still present.
I can reproduce just now : https://demo.lizmap.com/lizmap/index.php/view/map/?repository=demo&project=leman
Version of QGIS Server https://demo.lizmap.com/lizmap/index.php/view/map/?repository=misc1&project=qgis_info

**Comment by Gustry** [comment]
I can't replicate anymore the issue.
https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=cats it works well

But now, it's a different issue : 
- popup on the map, it works
- popup from attribute table : 400 http code


[Peek 2022-08-02 09-59.webm](https://user-images.githubusercontent.com/1609292/182323628-5ba815f0-4e36-460b-b939-51babcf9576b.webm)

**Comment by nboisteault** [comment]
I can't reproduce in Lizmap 3.7.
Please reopen if issue still occurs.
