### ISSUE TITLE
[Bug]: Dataviz, the chart must be displayed in the main panel if we want to display it only in a popup

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#2555]
### What is the bug?

If we want to display a filtered chart only in the popup of the parent, it's required to have it as well in the dataviz main panel.

So for now, the "only show in child popup" mustn't be checked.

This is a regression.

### Steps to reproduce the issue

Make a chart with "only show in child popup" checked, it won't be displayed.

### Lizmap version

3.4.6

### QGIS desktop version

3.10

### QGIS server version

3.10

### Operating system

All

### Browsers

Firefox

### Browsers version

Latest firefox

**Comment by mdouchin** [comment]
Done in 3.4 here 094665bb6
