### ISSUE TITLE
Permalink breaks WFS, GetLegendGraphics and GetFeatureInfo

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#256]
Lizmap WC : 2.12.1
QGIS Server : 2.8.4

Original interface : http://carto.smiddest.fr/
Permalink : http://carto.smiddest.fr/?zoom=1&lat=5632187.18223&lon=-68734.72743&layers=00000000BFFFFFFFFFFFTFTFT

With permalink, a '%3Fzoom%3D1' parameter is added in WFS, GetLegendGraphics, GetFeatureInfo and GetMap URL. It breaks all URL but not GetMap one.

**Comment by rldhont** [comment]
I think the problem comes from the way you do the redirection. You probably add project and repository parameter not after the '?' but before it and also with a '?'.

Can you review the way you do the redirection, thanks.

**Comment by nboisteault** [comment]
This my virtualhost : 
`<VirtualHost IP>
        DocumentRoot /var/www/html/
        ServerName www.etiage-dordogne.fr
        ServerAlias etiage-dordogne.fr
        DirectoryIndex lizmap-web-client/lizmap/www/index.php/view/map/?repository=epidor&project=Epidor

</VirtualHost>`

I don't understand why zoom parameter is added but not the other parameter.
I'll take a deeper look at how correctly configure my apache virtualhost.

**Comment by mdouchin** [comment]
Hi,

I think you should change your virtual host DocumentRoot to point directly to Lizmap www folder, such as

```
<VirtualHost IP>
    ServerName www.etiage-dordogne.fr
    ServerAlias etiage-dordogne.fr

    DocumentRoot /var/www/html/lizmap-web-client/lizmap/www/    
    <Directory /var/www/html/lizmap-web-client/lizmap/www/>
            Options -Indexes FollowSymLinks MultiViews
            AllowOverride None
            Order allow,deny
            Allow from all
    </Directory>

</VirtualHost>
```

With this configuration, you won't need any DirectoryIndex option.

Please be aware you need to delete the content of the Lizmap temp/lizmap folder, to clean lizmap installation, for example with

```
cd /var/www/html/lizmap-web-client/
lizmap/install/clean_vartmp.sh
```

Then you can reload Apache.

**Comment by nboisteault** [comment]
It didn't work. With that config how can lizmap be aware of what lizmap project he has to load?

**Comment by rldhont** [comment]
I think you can use the mod_rewrite to rewrite your URI.

**Comment by rldhont** [comment]
I found this:
```
Adding to the Query String
Keep the existing query string using the Query String Append flag, but add var=val to the end.
RewriteRule ^/page /page?var=val [QSA]
```
here http://wiki.apache.org/httpd/RewriteQueryString

**Comment by rldhont** [comment]
I close it, reopen if needed
