### ISSUE TITLE
Update google maps version and parameter

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#257]
In master we have a javascript warning :
"RetiredVersion, SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages"

Looking at [documentation](https://developers.google.com/maps/documentation/javascript/error-messages) we can see that we should now have :

https://maps.google.com/maps/api/js?v=3&key=mykey

or 

https://maps.google.com/maps/api/js?v=3.22&key=mykey
if we want last release.

**Comment by nboisteault** [comment]
Here is pull request : https://github.com/3liz/lizmap-web-client/pull/258

**Comment by rldhont** [comment]
#258 has been merged
