### ISSUE TITLE
 customizing the interface of the lizmap project

### ISSUE THREAD

**Issue by gampini-jacques** [3liz/lizmap-web-client#2572]
I am in need of customizing the interface of the lizmap project interface according to the logged in user. in my research I found that the view.tpl file (/var/www/lizmap-web-client-3.4.1/lizmap/modules/view/templates/view.tpl) contains the contents of the project page.

I would like to understand how the redirection of the user is carried out, after authentication? also is there a documentation describing the tree structure of the project files?

cordially

**Comment by NJMC** [comment]
Hi Lizmap team, great project you guys have built. I would like to follow up on this post. 

**Issue:** I am having an issue adding an extra page to the Lizmap site - e.g. 'About'.

So far in Lizmap module I have duplicated and renamed both the default.tpl and default.classic.php (about.tpl and about.classic.php). Nb. I added a 'Hello world' div in the new controller before the <?php tag.

I have added the following url to the url.xml file also:

    <url pathinfo="/about"       action="about:index"/>

This will direct me to a page with a 404 error displayed below the 'Hello world' text.

**Question:** could you please advise on why the Php is not being picked up? Is there some other url.xml that I need to configure?

Thanks in advance,

Niall

**Comment by nboisteault** [comment]
@laurentj Could you answer those questions please?

**Comment by laurentj** [comment]
@NJMC 

The urls.xml file is not used (yet).  The url to access to your controller is `http://my.lizmap/index.php/lizmap/about/index/`. (url is `index.php/<module name>/<controller name>/<method name>`.

The controller file must not contain HTML content. All HTML content goes into templates. 

Lizmap is using the Jelix framework 1.6 : see https://docs.jelix.org/en/manual-1.6/

**Comment by NJMC** [comment]
Ok, thanks Laurent.

**Comment by katagen** [comment]
@laurentj : will it also work if I copy the template of the `view` in something like `lizmap/var/themes/repo1/view/` and `lizmap/var/themes/repo2/view/`?
So I can have different content for different repositories?
