### ISSUE TITLE
[Bug]: Uncaught TypeError: aProperty is undefined

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2574]
### What is the bug?

During Locate By Layer building
```
Uncaught TypeError: aProperty is undefined
    getLocateFeature https://lizmap.local/assets/js/map.js:1631
    getLocateFeature https://lizmap.local/assets/js/map.js:1626
    jQuery 8
    getLocateFeature https://lizmap.local/assets/js/map.js:1542
    createSwitcher https://lizmap.local/assets/js/map.js:2276
    init https://lizmap.local/assets/js/map.js:6080
```

### Steps to reproduce the issue

1. Add a polygon layer with a label field that contains Null value for one feature
2. Configure with lizmap plugin the locate by layer with this polygon layer and this label field
3. Publishing the project
4. Open the project with lizmap web client
5. take a look at the browser error console

### Lizmap version

3.4.2

### QGIS desktop version

3.16.*

### QGIS server version

3.16.*

### Operating system

Debian

### Browsers

Firefox

### Browsers version

Firefox 93

**Comment by Gustry** [comment]
Lizmap version 3.4.2 is old.

**Comment by Gustry** [comment]
Is this issue still valid @rldhont ?

**Comment by nboisteault** [comment]
I can't reproduce in master.
