### ISSUE TITLE
Does lizmap-web-client support multitasking?

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-web-client#2588]
Does lizmap-web-client support multitasking?
If it does, where do I configure it to do so?

**Comment by Gustry** [comment]
What do you mean by multitasking ?

**Comment by yamamoto-ryuzo** [comment]
For example, if I run Lizmap on a server with 20 CPUs, it will only use 1 CPU.
I wish there was a setting for the maximum number of threads, like in QGIS.

**Comment by Gustry** [comment]
Ah ok, you mean multi-threading the PHP application.
I would say it depends on how you install/launch Lizmap : nginx, apache, docker ...
But I don't think that Lizmap PHP application is the bottle neck on a server. Data and QGIS Server might be.
Sorry, I don't know that much in that area.

**Comment by yamamoto-ryuzo** [comment]
That's exactly what it was!
PHP was single threaded.
I'll try to see if I can speed it up with multi-threading using pthreads.
Thank you very much.
I'll try that this weekend!

**Comment by dmarteau** [comment]
Lizmap is a php application which is launched with php-fpm, you may configure the number of workers from the php-fpm configuration.

**Comment by yamamoto-ryuzo** [comment]
Thanks for the great information.
I'm looking forward to this weekend.

**Comment by yamamoto-ryuzo** [comment]
I set up php-fpm and checked it works.
PHP is now running in multi-threaded mode and seems to be faster.
However, the CPU usage of each PHP is low, less than 5%.
So it seems that PHP is not slow as a whole.
It seems that qgis_mapserv.fcgi needs to be made multi-threaded to speed up.
I'll try it.
Thank you very much.
![image](https://user-images.githubusercontent.com/86514652/142709874-47873b5e-f23e-4b8a-a006-d105675574a6.png)

**Comment by yamamoto-ryuzo** [comment]
For your reference, I've left the php installation below in Japanese.
P.16.

https://drive.google.com/file/d/1-e8hQWfPJYgfYedJb5WoPuBCyqjsqJbg/view?fbclid=IwAR3N0gd31WwMMTfiznBqtzYb6d__N61iVDKY3qrIw0M4HrLk4UP9LhdFgsU

**Comment by yamamoto-ryuzo** [comment]
P.S.
It seems that the more vector layers you display at the same time, the greater the multithreading of php when displaying them simultaneously.

**Comment by dmarteau** [comment]
> It seems that qgis_mapserv.fcgi needs to be made multi-threaded to speed up.

qgis_mapserv.fcgi  is a *synchronous* process. If you want something more scalable, you may use [supervisor](http://supervisord.org/index.html)  with fcgi socket or [an asynchronous multiprocessing wrapper to Qgis server](https://github.com/3liz/py-qgis-server).

**Comment by yamamoto-ryuzo** [comment]
Thank you for your valuable advice.
I'll try tomorrow or next weekend.

**Comment by yamamoto-ryuzo** [comment]
QGISserver's rendering was single-threaded by default.
Simply making it multi-threaded made it considerably faster.
This is very easy to do, so I'll give it a go and see how it goes.

https://docs.qgis.org/3.22/en/docs/server_manual/config.html
https://drive.google.com/file/d/1-e8hQWfPJYgfYedJb5WoPuBCyqjsqJbg/view?fbclid=IwAR2lfOUKbZ3eFOfuv5KXirsm5plrJQGnOKgFUrdVEwM6-5RJsdvJFL3762s

Configuration Example
/etc/apache2/conf-available/lizmap-fcgi.conf 

#QGIS multithreading.
#Number of threads to use when parallel rendering is activated.
#If a value is specified, the number of processor cores will be used. -1
FcgidInitialEnv QGIS_SERVER_MAX_THREADS 10
#Activate parallel rendering of WMS GetMap requests.
#By default () is disabled. Possible values are false
#0 or (case-insensitive) false
#1 or (case-insensitive) true
FcgidInitialEnv QGIS_SERVER_PARALLEL_RENDERING 1

![image](https://user-images.githubusercontent.com/86514652/142730376-6250b8d8-17a7-4b51-b53b-d45a50394715.png)
