### ISSUE TITLE
[Bug]: Using Filter expression on value relation widget always give an empty list

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#2589]
### What is the bug?

I have a PostgreSQL table that stores available values for the attributes of my tables.
After upgrading from an EOL Lizmap version to the last one I face this problem :+1: 
All value relation widget provide an empty list.
No error in logs.
Alter a lot of tries, I had the idea to clear the "Filter expression" and I get all values from the table.
The workaround is to create a view for value each and to call this view in the value relation widget.

### Steps to reproduce the issue

Create a filed with a value relation widget that uses a filter and try to edit a feature to see the list is empty.

### Lizmap version

 both 3.4 and 3.5

### QGIS desktop version

3.16.13

### QGIS server version

3Liz 3.16 docker image

### Operating system

debioan 10

### Browsers

Firefox

### Browsers version

Firefoc 94 on ubuntu

**Comment by mathieubossaert** [comment]
Maybe a duplicate of this issue... https://github.com/3liz/lizmap-web-client/issues/2561

**Comment by rldhont** [comment]
@mathieubossaert do you have lizmap-plugin installed as a QGIS Server plugin ?

**Comment by mathieubossaert** [comment]
> @mathieubossaert do you have lizmap-plugin installed as a QGIS Server plugin ?

Oups if forgot to answer your question. No I do not have any plugin installed

**Comment by Gustry** [comment]
It's now highly recommended to have Lizmap as a QGIS server plugin as well. Otherwise, a few features are not working since LWC 3.4.

**Comment by mathieubossaert** [comment]
ok Thanks @Gustry I will update my install and test it.

**Comment by Gustry** [comment]
You should install a few plugins in QGIS Server to enable more features in Lizmap : https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server-plugins

To install them, https://www.3liz.com/news/qgis-plugin-manager.html the tool qgis-plugin-manager can help
