### ISSUE TITLE
Error tiles are cached

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#259]
This issue is close to https://github.com/3liz/lizmap-web-client/pull/258

Sometimes the first request for a tile is timeouted so we have a nice pink tile.
These wrong tiles are cached and shown again when queried. 404 requests should not be cached.

**Comment by rldhont** [comment]
Which tile is timeouted ? A one comes from QGIS-Server ?

**Comment by nboisteault** [comment]
Yes from QGIS Server I think. When request to Postgis is too slow.

**Comment by rldhont** [comment]
Ok, which lizmap web client version ?

**Comment by nboisteault** [comment]
Lizmap web client 2.12.1

**Comment by rldhont** [comment]
Can you test the last 2.12 released : 2.12.4 ?

**Comment by nboisteault** [comment]
I don't have problems with last versions of LWC.
