### ISSUE TITLE
how to add logos of sponsors in Lizmap header? 

### ISSUE THREAD

**Issue by ilamarengo** [3liz/lizmap-web-client#260]
Hello,

this is not an issue but a question.
i am relative new to Lizmap (i am using the 3.0beta3 version) and i had a look a the documentation on line to see if it was explained how to add other logos, e.g. project sponsors or partners, along with that one of Lizmap in the header (see image below).
I didn't find anything so it is possible to have some advice? Alternatively, it would be possible to add this info to the online documentation so everybody can have access to it?
Thanks

![more_logos in lizmap](https://cloud.githubusercontent.com/assets/17223497/13380057/4f79352a-de17-11e5-9c05-244cb8b211f0.jpg)

**Comment by rldhont** [comment]
You can do it with a simple theme.
it's documented http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#creating-simple-themes
You can enhance it here https://github.com/3liz/lizmap-documentation

**Comment by mbernasocchi** [comment]
@rldhont does this really work?
the css are recognised and loaded, but the images like sprite_20_tools are taken from the main folder in my case.

if I just replace the image in the themes folder it is not taken. This doesn't work either:
```
#mapmenu .nav-list > li > a .icon {
    background-image: url("themes/default/css/images/sprite_20_tools.png") !important;
}
```

This works:
```
#mapmenu .nav-list > li > a .icon {
    background-image: url("../media/getMedia?repository=main&project=visu&path=media%2Fthemes%2Fdefault%2Fcss%2Fimages/sprite_20_tools.png") !important;
}
```

**Comment by mkazmiers** [comment]
Hello,

we're facing the same need as @ilamarengo, pushing multiple logos from a project partners
We've found in the lizmap documentation how to replace one logo by another by changing the css, but didn't found out to display many of them.

Is there anything in the documentation somewhere? Or is it possible to get any info about this feature?

Thanks,

**Comment by mdouchin** [comment]
What about creating a single png file with the background and the logo ? This way you can easily do what you want, without the need to place the different images via CSS (wich can be tricky if you want to have a good looking app in all screens)

**Comment by mkazmiers** [comment]
I think we've already tried, but there are too many of them to be displayed harmoniously in a single png file, they look ridiculously small (cf printscreen) 
![logos](https://user-images.githubusercontent.com/16324693/36213590-639ec2ca-11a7-11e8-996d-d9f37816964e.PNG)
Though, i don't know if we've tried yet to tweak the css to make the single png fitting in a better way in the header ; do you think it's a way to do so?

**Comment by mdouchin** [comment]
You should change the `#header` background not the `#logo`

**Comment by nboisteault** [comment]
All changes can be done with CSS as explain in [doc](https://docs.3liz.com/en/publish/advanced_lizmap_config.html#creating-simple-themes).
Look at this [example](https://eau-angouleme.arb-na.fr/) where the whole head is modified.
