### ISSUE TITLE
[Bug]: "Tooltips layers" do not work if "attribute table" is configured for the same layer

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2603]
### What is the bug?

In a project enable both tooltips and attribute table for the same layer. Tooltips won't work. Remove the layer from "attribute table" and tooltips will start to work.

### Steps to reproduce the issue

See above.

### Lizmap version

3.4.7

### QGIS desktop version

3.16.14

### QGIS server version

3.16.14

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Latest

**Comment by nboisteault** [comment]
I confirm. The issue happens when the attribute table has no hidden fields because of this line of code : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/assets/js/map.js#L4232
PR coming.
Thanks @gioman for this report.

**Comment by gioman** [comment]
> Thanks @gioman for this report.

@nboisteault thanks for the fix!
