### ISSUE TITLE
[Bug]: Edition on joined tables

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#2607]
### What is the bug?

In QGIS I have joined 2 tables. In LWC when I want to edit a feature, the edition form opens and shows only columns from first table, the columns from joined table are missing.

### Steps to reproduce the issue

1. Join 2 tables in QGIS Desktop
2. Make them editable in Lizmap plugin
3. Try to edit a feature in LWC
4. See only columns from first table

### Lizmap version

3.5

### QGIS desktop version

3.16.14

### QGIS server version

3.16.14

### Operating system

Ubuntu 20.04

### Browsers

Microsoft Edge

### Browsers version

96

### Relevant log output

```shell
No logs
```

**Comment by Gustry** [comment]
I'm not sure if it has been supported correctly before, so wondering if it's not a feature request.
Is the joined table in the postgis database as well and published as WFS ? (no need for WFS-T).

Only postgis layers are edited "straight" from LWC in the database using SQL queries. QGIS is not involved in this step for editing.

**Comment by ygorigor** [comment]
First table is a spatial table, the second one is simple table. Edition is activated on both.

**Comment by ygorigor** [comment]
I'll close it, it's not so important.
