### ISSUE TITLE
Ability to collapse / expand Layers at startup

### ISSUE THREAD

**Issue by stuggi05** [3liz/lizmap-web-client#262]
Hi everybody,

is there any possibility or option in lizmap plugin to set the layer tree at startup as collapsed?

**Comment by jaitor1** [comment]
+1

**Comment by geoek** [comment]
See https://github.com/3liz/lizmap-web-client/issues/245

It is not via the plugin, but it works !

**Comment by stuggi05** [comment]
THX, it works!
