### ISSUE TITLE
<ServerException>Layer(s) not valid</ServerException>

### ISSUE THREAD

**Issue by zura1sama** [3liz/lizmap-web-client#2628]
### Description

Hi, 

I'm trying to configure qgis with postgreSQL so i can use lizmap layer editing fiture to on my pc, i've set credential in the qgis project too, and i got this error. Can you help me? 
Thank you

### Environment

 - Lizmap version: 3.4.7
 - QGIS Server FULL version: 3.16.14
 - QGIS Desktop FULL version: 3.16.14
 - OS (Windows, Linux, MacOS, Android…): Windows
 - Browser (Firefox, Chrome…): Chrome 96.0.4664.45
 - Lizmap Logs :
2021-12-02 10:51:29	::1	error	GetCapabilities result code: 500
2021-12-02 10:51:30	::1	error	GetCapabilities result code: 500
2021-12-02 10:51:30	::1	error	An error has been raised when loading WMS GetCapabilities: HTTP Code 400
2021-12-02 10:51:30	::1	error	GetCapabilities result code: 500

 - Qgis Server Logs : 
 16:32:29 INFO Server[8408]: ******************** New request ***************
16:32:29 INFO Server[8408]: Request URL: http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe?map=C%3A%5Cwebserver%5Cproject%5Cbansel%2Fbansel2.qgs&request=GetCapabilities&service=WMS&version=1.3.0&Lizmap_User=admin&Lizmap_User_Groups=__priv_admin%2C admins&Lizmap_Override_Filter=1
16:32:29 INFO Server[8408]: Environment:
16:32:29 INFO Server[8408]: ------------------------------------------------
16:32:29 INFO Server[8408]: SERVER_NAME: 127.0.0.1
16:32:29 INFO Server[8408]: REQUEST_URI: /qgis/qgis_mapserv.fcgi.exe?map=C%3A%5Cwebserver%5Cproject%5Cbansel%2Fbansel2%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1
16:32:29 INFO Server[8408]: SCRIPT_NAME: /qgis/qgis_mapserv.fcgi.exe
16:32:29 INFO Server[8408]: REMOTE_ADDR: 127.0.0.1
16:32:29 INFO Server[8408]: SERVER_PORT: 80
16:32:29 INFO Server[8408]: QUERY_STRING: map=C%3A%5Cwebserver%5Cproject%5Cbansel%2Fbansel2%2Eqgs&request=GetCapabilities&service=WMS&version=1%2E3%2E0&Lizmap%5FUser=admin&Lizmap%5FUser%5FGroups=%5F%5Fpriv%5Fadmin%2C%20admins&Lizmap%5FOverride%5FFilter=1
16:32:29 INFO Server[8408]: REQUEST_METHOD: GET
16:32:29 INFO Server[8408]: HTTP_ACCEPT: */*
16:32:29 INFO Server[8408]: HTTP_USER_AGENT: Lizmap
16:32:29 INFO Server[8408]: LIZMAP_OVERRIDE_FILTER:1
16:32:29 INFO Server[8408]: LIZMAP_USER:admin
16:32:29 INFO Server[8408]: LIZMAP_USER_GROUPS:__priv_admin, admins
16:32:29 INFO Server[8408]: MAP:C:\webserver\project\bansel/bansel2.qgs
16:32:29 INFO Server[8408]: REQUEST:GetCapabilities
16:32:29 INFO Server[8408]: SERVICE:WMS
16:32:29 INFO Server[8408]: VERSION:1.3.0
16:32:29 CRITICAL Server[8408]: Error, Layer(s) bangunan_b82136ac_e2b5_4ac6_9082_102541cd3502, kelengkapan_pipa_d9852511_0698_460d_be02_7afbd5bc49cf, pipa_d6b812de_f9b0_4f71_969d_78b963ecbd1d not valid in project C:\webserver\project\bansel/bansel2.qgs
16:32:29 WARNING Server[8408]: <ServerException>Layer(s) not valid</ServerException>

**Comment by ygorigor** [comment]
This layers haves some issues
`bangunan_b82136ac_e2b5_4ac6_9082_102541cd3502, kelengkapan_pipa_d9852511_0698_460d_be02_7afbd5bc49cf, pipa_d6b812de_f9b0_4f71_969d_78b963ecbd1d`
Check in QGIS Desktop

**Comment by zura1sama** [comment]
> This layers haves some issues `bangunan_b82136ac_e2b5_4ac6_9082_102541cd3502, kelengkapan_pipa_d9852511_0698_460d_be02_7afbd5bc49cf, pipa_d6b812de_f9b0_4f71_969d_78b963ecbd1d` Check in QGIS Desktop

Thanks for the reply!

done checking.. the layer seems work fine in QGIS desktop 
![image](https://user-images.githubusercontent.com/94884636/144426101-efd8e963-226a-4245-9fc6-65b66fd7d336.png)

**Comment by ygorigor** [comment]
@zura1sama where are the layers stored? qgis-server can access them?

**Comment by Gustry** [comment]
You need to check if these files are all on the server (if it's file based). If it's in a database, maybe QGIS Server can't connect to your DB ?

**Comment by zura1sama** [comment]
The layer is stored in PostgreSQL. 

when i set the qgs file with layer stored in local folder, lizmap can display it well.

how to check QGIS server is connect or not with DB ?

**Comment by Gustry** [comment]
It depends of your DB is on the same machine or not as QGIS Server. If it's different environment, `ping`, then `psql` etc ... Are all credentials in the QGS project ? (host, username and password) ?

**Comment by zura1sama** [comment]
DB and QGIS Server are on the same machine. 

Yes, all redentials in the QGS project
 -  layer-tree-layer providerKey="postgres" legend_exp="" source="dbname='spam_bansel' host=localhost port=5432 sslmode=disable authcfg=zp8s529 key='gid' estimatedmetadata=true type=MultiPolygon checkPrimaryKeyUnicity='1' table=&quot;public&quot;.&quot;bangunan&quot; (geom)" name="bangunan" patch_size="-1,-1" expanded="1" id="bangunan_592479f8_baee_4c5d_b388_7146da73e345" checked="Qt::Checked" legend_split_behavior="0"
 -  layer-tree-layer providerKey="postgres" legend_exp="" source="dbname='spam_bansel' host=localhost port=5432 sslmode=disable authcfg=zp8s529 key='gid' estimatedmetadata=true srid=4326 type=Point checkPrimaryKeyUnicity='1' table=&quot;public&quot;.&quot;kelengkapan_pipa&quot; (geom)" name="kelengkapan_pipa" patch_size="-1,-1" expanded="1" id="kelengkapan_pipa_d9852511_0698_460d_be02_7afbd5bc49cf" checked="Qt::Checked" legend_split_behavior="0"
 - layer-tree-layer providerKey="postgres" legend_exp="" source="dbname='spam_bansel' host=localhost port=5432 sslmode=disable authcfg=zp8s529 key='gid' estimatedmetadata=true srid=4326 type=MultiLineString checkPrimaryKeyUnicity='1' table=&quot;public&quot;.&quot;pipa&quot; (geom)" name="pipa" patch_size="-1,-1" expanded="1" id="pipa_d6b812de_f9b0_4f71_969d_78b963ecbd1d" checked="Qt::Checked" legend_split_behavior="0"

**Comment by Gustry** [comment]
> Yes, all credentials in the QGS project

No, you are using the authentication database. We can read `authcfg=XXX`.

You can fix QGIS Server by setting up the master password database. But you will have less features with Lizmap such as editing or form filter.

Please read this ticket : https://github.com/3liz/lizmap-web-client/issues/1638#issuecomment-627872662

I'm closing, because it's a duplicate.

**Comment by Gustry** [comment]
Same question, does your Lizmap server can access the PG Database ? Did you transfer the service file and where ? Is-it the same machine ?

**Comment by zura1sama** [comment]
@Gustry thanks for taking the time for me! . sorry took long to answer your question

> does your Lizmap server can access the PG Database ?

i don't know, are the configuration is on profil.ini.php file, to make connection 
between lizmap and PG admin ?
![image](https://user-images.githubusercontent.com/94884636/144515714-f72ea332-d806-4621-ba55-3cb813f7beb8.png)

when i save the file, this cause Error 500
before change  profil.ini.php : 
![image](https://user-images.githubusercontent.com/94884636/144516195-b51f78f3-a88d-4b97-abf9-bb91eb0e5b8c.png)
after change profil.ini.php : 
![image](https://user-images.githubusercontent.com/94884636/144516469-0b5521ab-23cf-45f1-b8df-218225a2cdf9.png)

> Did you transfer the service file and where ?

Hm, yes.... C:\webserver\project\bansel\pass\pg_service.conf (set environment variable too) 
![image](https://user-images.githubusercontent.com/94884636/144516894-c4ba4d8f-0044-453a-989e-a647dcf0ccfe.png)

> Is-it the same machine ?

Yes, lizmap, PostgreSQL, Qgis Desktop and Server are on same the machine

**Comment by Gustry** [comment]
> i don't know, are the configuration is on profil.ini.php file, to make connection
between lizmap and PG Database ?

This modification in the file is for using logging logs into the PG database instead of sqlite. It's not linked to the use of PG layers. If you change this value, you must reapply the install of LWC, to create the tables, otherwise, it will have 500.

For windows, you should check https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by zura1sama** [comment]
after reapply LWC, change profiles.ini.php and perform install... it's give me an error like this 

Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
[error] An error occured during the installation of the module jacl2db: error during the connection localhost
Installation ended.

inside of profile.ini file : 

;[jdb:jauth]
;driver=sqlite3
;database="var:db/jauth.db"

[jdb:jauth]
driver="pgsql"
database="spam_bansel"
host="localhost"
port=5432
user="postgres"
password="@fiqritea"

;[jdb:lizlog]
;driver=sqlite3
;database="var:db/logs.db"

[jdb:lizlog]
driver="pgsql"
database="spam_bansel"
host="localhost"
port=5432
user="postgres"
password="@fiqritea"

(LWC 3.4.7)

**Comment by zura1sama** [comment]
update!

i try to change PostgreSQL version to 12 and LWC to 3.5.0-rc.3, edit profil.ini.php and installing is successful

![image](https://user-images.githubusercontent.com/94884636/144627917-6df55f80-8061-4479-a1ab-2b5b7dbf044c.png)

+i add this to  httpd-vhosts.conf (with out this, the lizmap showing error "SERVICE NON DISPONIBLE"
  - SetEnv PGSERVICEFILE ".../pg_service.conf" 
  - FcgidInitialEnv PGPASSFILE ".../pgpass.conf"

but still, it's give me an error to access edition fitur in LWC

lizmap logs : 
[402]	error during the connection bansel	C:\webserver\lizmap\prod\lizmap-web-client-3.1.12\lib\jelix\plugins\db\pgsql\pgsql.dbconnection.php	166

**Comment by cfsgarcia** [comment]
When authenticating your layers with qgis-auth.db you get a key called 'authcfg' within the .qgs project file. Let's say it takes the value '**pglayer**'.
I tweaked the following qgisVectorLayerDatasource.class.php and qgisVectorLayerDatasourceDatasource.class.php to take into account this key and allow authentication within Lizmap:

lizmap/modules/lizmap/classes/qgisVectorLayerDatasource.class.php:
`$parameters = array(
            'dbname', 'service', 'host', 'port', '**authcfg**', 'user', 'password',
            'sslmode', 'key', 'estimatedmetadata', 'selectatid',
            'srid', 'type', 'checkPrimaryKeyUnicity',
            'table', 'geocol', 'sql', 'schema', 'tablename',
        );
...

public function getDatasourceProfile() {
...
} **elseif ($this->provider == 'postgres' && $dtParams->authcfg != '') {
        	return $dtParams->authcfg;
        }**
          elseif ($this->provider == 'postgres') {
...
`

lizmap/modules/lizmap/classes/qgisVectorLayerDatasourceDatasource.class.php:
`protected $datasourceRegexes = array(
        'dbname' => "dbname='([^ ]+)' ",
        'service' => "service='([^ ]+)' ",
        'host' => 'host=([^ ]+) port=',
        'port' => 'port=([0-9]+) ',
    	**'authcfg' => 'authcfg=([^ ]+)',**

...

$ds = array(
            'dbname' => $dbname,
            'service' => '',
            'host' => '',
            'port' => '',
        	**'authcfg' => '',**
`

Since retrieving the user/password from qgis-auth.db would be too much code, I simply trop a copy of the credentials into lizmap/var/config/profiles.ini.php:

;copy of authcfg credentials in here
[jdb:**pglayer**] ;must take the same value as authcfg
driver="pgsql"
database="my_database"
host="my_host"
user="my_user"
password="my_password"

**Comment by Gustry** [comment]
@cfsgarcia Do you mean you have Lizmap working correctly with the QGIS auth database and credentials in the INI file following your patch ?
Can you provide the `git diff` ? It would be easier to compare, apply a proper diff.
