### ISSUE TITLE
lizmap3 bug when a layer is empty

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#264]
Hi,
if I ask a postgis layer without entity in qgis2.14 then the web project will not start

 error.log:
file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=%2Fhome%2FRUCHER.qgs&amp;request=GetCapabilities&amp;servi$ /var/www/websig/lizmap/modules/lizmap/classes/lizmapProxy.class.php     87

Array to string conversion      /var/www/websig/lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php        69

**Comment by rldhont** [comment]
It's not a lizmap but a QGIS Server issue.
Reopen if needed
