### ISSUE TITLE
After server restart, first and second "save feature" may fail due timeout

### ISSUE THREAD

**Issue by TotalNoobOnGIS** [3liz/lizmap-web-client#2648]
### What is the bug?

This seems to happen only for time consuming save operations. Normal point save succeeds OK.

However in my case save feature to postgresql launches internal postgresql trigger and operations for that take 10 to 30 seconds which
for first 2 save attempts qgis/lizmap timeout is somehow shorter.

After server restart, first and second "save feature"may fail due timeout
Third attempt is successfull and so are saves after that

### Steps to reproduce the issue

**First attempt after server restart:**
When server is restarted, user selects a project and map is displayed,
(time after restart is not relevant tried 1min & 1 hour after restart. Same result)
then user tries to add feature(point) to the postgresql layer, point is not saved.
**_"Saving" progess bar on edition pane is rolling forever and the feature is not saved._**

**Second attempt:**
After few minutes user reloads the whole page and tries to add and save new feature
**_"Saving" progess bar on edition pane is rolling forever but the feature(point) is actually saved to postgresql layer_**
'lizmapeditionfeaturecreated' event is not triggered (and thus related custom js not executed)

Third (and all after that) attempt:
After few minutes user reloads the whole page and tries to add and save new feature
"Saving" progess bar on edition pane is rolling until the feature(point) is actually saved to postgresql layer
'lizmapeditionfeaturecreated' event is triggered (and related custom js is executed)

### Lizmap version

3.4.4

### QGIS desktop version

3.20.1

### QGIS server version

3.20.1

### Operating system

WIN server 2016

### Browsers

Firefox

### Browsers version

Firefox 95.0

### Relevant log output

```shell
No lines on logfiles on first and second save attempts
```

**Comment by TotalNoobOnGIS** [comment]
running still 3_4_4
there is an error related to timeout.
 
Normal point save works perfectly 
so this bug(or maybe a question) is only about time consuming save operations after server restart.

However on my case save operation launch some calculations on postgresql(pgtrigger) side those taking 10 to 30 seconds. 
Waiting this seems to be too much for Lizmap/Qgis/? after server restart. Third attempt and all after that are success.

I have no idea where i could look for timeout settings for this save operation 
is there separate settings for Qgis-server php? Lizmap ?

![kuva](https://user-images.githubusercontent.com/39231981/146146022-0020394d-d763-4fa2-adf7-b4ff585018b4.png)

**Comment by nboisteault** [comment]
Does issue still occur?
