### ISSUE TITLE
lizmap3 bug: sort by value the relational value don't work

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#265]
reHi,

In lizmap3beta, sort by value the relational value don't work.

**Comment by jancelin** [comment]
Working with this:

https://github.com/3liz/lizmap-web-client/compare/master...jancelin:patch-2

-      if(strtolower($this->formControls[$fieldName]->valueRelationData['orderByValue']) == 'true')
+      if(strtolower($this->formControls[$fieldName]->valueRelationData['orderByValue']) == '1')

**Comment by mdouchin** [comment]
Thanks a lot for reporting this bug
I just pushed a commit to fix it. We need to keep 'true' and '1' to be compatible with different QGIS versions.
See  e1737206a1f6ba785fb57633e1f788f526eeddaa
