### ISSUE TITLE
Drawing disappear after printing

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2658]
### What is the bug?

See steps below:

### Steps to reproduce the issue

1. publish a project with a print layout
2. open the project in LMWC, add a drawing from KML
3. print
4. zoom in/out > drawing disappear from map

### Lizmap version

3.5

### QGIS desktop version

3.22.1

### QGIS server version

3.22.1

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by nboisteault** [comment]
@gioman I can't reproduce this issue. Is it a fresh install of Lizmap 3.5.0?

**Comment by gioman** [comment]
> Is it a fresh install of Lizmap 3.5.0?

@nboisteault yes, done it yesterday from scratch:


https://user-images.githubusercontent.com/1951107/146587802-eb84f52b-db9b-4b14-9897-7cb279192176.mp4

**Comment by nboisteault** [comment]
@gioman is the draw still visible when opening the draw or print tool?

**Comment by gioman** [comment]
> @gioman is the draw still visible when opening the draw or print tool?

I'll check asap.

**Comment by gioman** [comment]
Can't replicate anymore, closing.
