### ISSUE TITLE
QGIS "layer order" is ignored/wrong

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2659]
### What is the bug?

This could be an issue in QGIS Server rather than LMWC, but for the moment I can't test QGIS Server only.

The "control layer order" functionality worked for sure in the past, also in QGIS Server/LMWC.

Now what I see is the following:

In a project with a few vector layers (GPKGs) and a couple of WMS layers (not using the "get images directly..." option), the vector layers are rendered in a wrong order compared to the one in the "layer order" panel, but unclear what is the logic (not sure there is one). The two WMS layers are always rendered on top of everything, regardless their position in the "layer order" panel.

### Steps to reproduce the issue

See above.

### Lizmap version

3.5

### QGIS desktop version

3.22.1

### QGIS server version

3.22.1

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by gioman** [comment]
> and a couple of WMS layers

Does not change by using tiffs instead.

**Comment by Gustry** [comment]
Regression, previous ticket https://github.com/3liz/lizmap-web-client/issues/1343 and fix https://github.com/3liz/lizmap-web-client/commit/b483ad4e0807883a99e09871f04723b5bc506934

I think I remember another ticket as well.

**Comment by nboisteault** [comment]
@gioman did you have the same problem with QGIS desktop and server 3.16?

**Comment by nboisteault** [comment]
I can't reproduce the issue neither with 3.16 nor 3.22. @gioman Please provide a simple QGIS project illustrating the issue.

**Comment by gioman** [comment]
@nboisteault in the meantime I made some changes to the project were I observed the problem and at the moment I don't observe it anymore. Sorry for the noise.
