### ISSUE TITLE
Hide empty (NULL) fields in lizmap popup

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#2660]
### Description

thank you very much for providing version 3.5. After first tests everything works fine.

But I miss the possibility to hide empty (NULL) fields in Lizmap popup (in version 3.3.11 it works very well).

Is this still a bug (#1632) or is there still a new option?

### Environment

 - Lizmap version: 3.5.0
 - QGIS Server FULL version: 3.16.14
 - QGIS Desktop FULL version: 3.16.14
 - OS (Windows, Linux, MacOS, Android…): Win10
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Gustry** [comment]
I think you should keep a single ticket open, as you have mentioned, there is already #1632. Can you comment on the other ticket.
There isn't any option to set this for now.
Some people still want to see null values.

You can switch to the QGIS Popup, where you can configure this behavior.

**Comment by guenterw** [comment]
sorry for the double ticket and thanks for the feedback

**Comment by ygorigor** [comment]
@guenterw you ca use this js script
https://github.com/3liz/lizmap-web-client/blob/master/extra-modules/lizmapdemo/qgis-projects/demoqgis/media/js/montpellier/hideEmptyFieldInPopup.js.example

**Comment by guenterw** [comment]
@ygorigor thanks for the hint
I have not used additional js scripts yet. But then I have to deal with it, because I need this functionality urgently. Among other things, this is why I still work with 3.3.11 in many projects.

In QGIS I guess you can only control the visibility of the group bins (drag and drop). And even that does not work for me in Lizmap as desired.

**Comment by Gustry** [comment]
Nice tip @ygorigor for this JS. @guenterw for Javascript, you have the documentation, you can do it "urgently" on your server. https://docs.lizmap.com/current/en/publish/customization/javascript.html You have the video tutorial if needed.

In QGIS, with the maptip, you the full power on the popup.
https://docs.lizmap.com/current/en/publish/configuration/popup.html#qgis-popup
You add the QGIS expression `if("FIELD_A" is not null", '<tr>...</tr>','')` to hide or not some fields in the popup.

**Comment by guenterw** [comment]
@Gustry thank you very much

The one with the QGIS maptip works fine and is very flexible
Here even "NOT NULL" is already considered:  WHEN "hinweis" IS NOT NULL OR trim("hinweis") != ''

I really need to take a closer look at Javascript, hopefully after Christmas. Seems to be very powerful.

And sorry for my english, everything is done with a translation program.
