### ISSUE TITLE
shapes are not visible in the canvas 

### ISSUE THREAD

**Issue by juwizeye** [3liz/lizmap-web-client#2663]
I have been trying to install lizmap on windows 10  using this tutorial [this](https://docs.lizmap.com/current/fr/install/windows.html) , however after the installation i can't  see the shapes in the canvas . I don't know what to do . if you have any idea i am all ears . 

here are  the Environments i used:  
 - Lizmap version: 3.4.6
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.20
 - OS (Windows, Linux, MacOS, Android…): windows 10 
 - Browser (Firefox, Chrome…): firefox 
Image of lizmap: 
![image](https://user-images.githubusercontent.com/96420889/146760743-005bb6ca-b40d-4acf-96a5-be4fa6cab42b.png)

**Comment by aeduard** [comment]
Maybe it is not the case, but as a general recommendation you should use the same version of Qgis desktop and Qgis server. Also the LTR versions are more stable, and as far as I know Qgis 3.16 is fully supported by lizmap 3.4.x.

**Comment by juwizeye** [comment]
thank you for your answer @aeduard , in effect that was the problem after I installed lizmap 3.5 it worked well.  Now I have another problem when I try to edit Postgis Layer in lizmap . I can see them in  the editing panel  but when I try to change edit them nothing happens . If you have any suggestions i am all ears . 
![image](https://user-images.githubusercontent.com/96420889/147450482-bf857c15-efe2-45fe-993b-8e839c399276.png)
Do I have to use postgresql instead of spatialite ?

**Comment by aeduard** [comment]
PostGIS is a PostgreSQL add-on which adds geographic objects to Postgres. So in spatialite you can't have a PostGIS layer. In general PostgreSQL+PostGIS is recommended in general, and as far as I know, data editing is available only with PostgreSQL, check [here](https://docs.lizmap.com/3.4/en/publish/lizmap_plugin/edition.html).

**Comment by juwizeye** [comment]
yeah , I stored all those layers in PostgreSQL but I want to know if I have to use PostgreSQL credentials in my profile.ini . In  [this](https://github.com/3liz/lizmap-web-client/issues/1658#issuecomment-635201551) comment they say that it is not necessary so I don't understand why I can't edit PostgreSQL even if I see them on the map .

**Comment by ygorigor** [comment]
@juwizeye try to look in PostgreSQL logs. Check LWC logs also.
What version of PostgreSQL do you have?

**Comment by juwizeye** [comment]
@ygorigor I have this error in LWC logs: **Cannot connect to localhost (bad host, login or password?) C: \ webserver \ lizmap \ preprod \ lizmap-web-client-3.5.0 \ lib \ jelix \ plugins \ db \ pgsql \ pgsql.dbconnection. php 166**
I don't understand why  because my connection profile is right . 
I have PostgreSQL 13 and I installed it using PgAdmin 4 . I don't know where to find PostgreSQL logs on windows .

**Comment by nboisteault** [comment]
Are credentials stored in your QGIS project?

**Comment by juwizeye** [comment]
@nboisteault yes there are

**Comment by juwizeye** [comment]
I tried to do a dataviz with my postgis layers and I have the same problem(**cannot connect to localhost**) . I think that lizmap can't connect to my database but qgis server can (because I can see all my postgis Layer on my lizmap) . Does any one konws how I can fix this ?

**Comment by ygorigor** [comment]
@juwizeye how credentials are stored in QGIS project?
Try to find logs from PostgreSQL, maybe they will show something.
Logs should be somewhere where your database is.

**Comment by juwizeye** [comment]
@ygorigor  I found them , I have this error **_could not receive client data: unrecognized winsock error 10054_**

**Comment by juwizeye** [comment]
I changed my database , I used PostgreSQL instead of Spatial and now it is working.

**Comment by Gustry** [comment]
Ok, so I'm closing your issue as you said you could fix it.
