### ISSUE TITLE
LWC installation problem

### ISSUE THREAD

**Issue by mibalas** [3liz/lizmap-web-client#2665]
Hello, I'm trying to install LWC and when I get to the part "php lizmap/install/installer.php" the following error happens:
`PHP Warning: require(./lizmap/vendor/autoload.php): failed to open stream: No such file or directory in ./lizmap/application.init.php on line 12
PHP Fatal error: require(): Failed opening required './lizmap/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in ./lizmap/application.init.php on line 12`

looking for the error, i found this topic:
https://github.com/3liz/lizmap-web-client/issues/1603

but when I try to run "composer install" in lizmap folder I get another error:
![WhatsApp Image 2021-12-15 at 12 35 17](https://user-images.githubusercontent.com/15907968/146817086-120377f9-5c78-4a64-bc70-102577a078ea.jpeg)

any idea what's happens?

 - Lizmap version:  3.6.0
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04

**Comment by Gustry** [comment]
On the ticket #1603 you are mentionning, please read the answer https://github.com/3liz/lizmap-web-client/issues/1603#issuecomment-637456693

You should use production package.
