### ISSUE TITLE
[Printing issue]: Error when trying printing : Uncaught TypeError: lizMap.mainLizmap is undefined

### ISSUE THREAD

**Issue by khanh78180** [3liz/lizmap-web-client#2669]
### What is the bug?

Hi,

Have any one have this issue when trying to print ?
Lizmap web-client 3.5.0rc4
I get an error when trying to print.

Uncaught TypeError: lizMap.mainLizmap is undefined
    addPrintControl http://x.x.x.x/assets/js/map.js:4050
    jQuery 10
    addPrintControl http://x.x.x.x/assets/js/map.js:3813
    createToolbar http://x.x.x.x/assets/js/map.js:2434
    init http://x.x.x.x/assets/js/map.js:6089

I think that map.js has been changed 

### Steps to reproduce the issue

1 - Select printer to print map
2- clic on button Print
nothing happen for Lizmap web-client 3.5.0rc4 

for Lizmap version 3.4.2 , it is working fine

### Lizmap version

3.5.0rc4

### QGIS desktop version

3.16.8

### QGIS server version

3.16.8

### Operating system

Ubuntu 20.4 LTS

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Browsers version

Firefox 84, chrome last version

### Relevant log output

```shell
Uncaught TypeError: lizMap.mainLizmap is undefined
    addPrintControl http://x.x.x.x/assets/js/map.js:4050
    jQuery 10
    addPrintControl http://x.x.x.x/assets/js/map.js:3813
    createToolbar http://x.x.x.x/assets/js/map.js:2434
    init http://x.x.x.x/assets/js/map.js:6089
```

**Comment by khanh78180** [comment]
I also get this error on CHROME

Uncaught TypeError: Cannot read properties of undefined (reading 'digitizing')
    at HTMLButtonElement.<anonymous> (map.js:4050)
    at HTMLButtonElement.dispatch (jquery-3.5.1.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.5.1.min.js:2)

**Comment by nboisteault** [comment]
Did you use source code or download a lizmap built package?

**Comment by khanh78180** [comment]
Hi,

I download the package from release/download and it is working fine now.

Thanks for your reply
