### ISSUE TITLE
media folder doesn't accept symbolic links for files

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#267]
message: no media file in the specified path

**Comment by rldhont** [comment]
hi @josemvm can you be more explicit ?

**Comment by josemvm** [comment]
hi rldhont!,

i have my installation on linux.

if i set this link "media/SGO.pdf" in Lizmap plugin/Layers/Selected item settings/Link, the Open documentation for the layer works fine.

if the SGO.pdf isn´t a real file but represented by a symbolic link this error message appears "no media file in the specified path" and de SGO.pdf document will not open.

thanks

**Comment by rldhont** [comment]
We can't reproduce your issue. Lizmap uses Jelix who uses file_get_contents to read files content. It's probably due to a PHP or Apache configuration.

**Comment by josemvm** [comment]
ok @rldhont,

i have another sites and another frameworks for web applications in the same server which use "FollowSymLinks" too.

in my case:

- file system:
/var/www/lizmap3/lizmap/install/ma/media/pdf
pdf folder is symbolic link to -> /var/www/pmapper/c_prediais/pdf

table field contents:
media/pdf/R-GAFSAB-F-4.pdf

if the pdf folder is not a symbolic link but a real folder evething works fine...

**Comment by rldhont** [comment]
So it's the directory that is a sym link.

**Comment by josemvm** [comment]
yes, i'm sorry @rldhont,

it's the directory that is a sym link not the media file.

**Comment by rldhont** [comment]
I reproduced the issue!

**Comment by josemvm** [comment]
thanks @rldhont
