### ISSUE TITLE
zoom to coordinates in the search box

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#268]
i supose that's possible to search with Google (API) by geographic coordinate system... but not (yet)...

**Comment by josemvm** [comment]
hi @rldhont @mdouchin

> Concerning the future, version 3.2 is already on track with a publication target for FOSS4G Europe 2017. Developments in this future version will mainly focus on the edition module and **base layers**.

enter coordinates to find a place - is it possible?
thanks in advance

**Comment by Gustry** [comment]
> the user chooses the CRS and reaches the map at that point (center, zoom and highlights the point)

This doesn't involve google, right? Needs pan/zoom.

**Comment by josemvm** [comment]
my first idea was to use google (or/and nominatim), if possible

but now this work base already exists, and this way seems better to me and more complete!
![imagem](https://user-images.githubusercontent.com/10053874/81539915-d3f2ad80-9368-11ea-8dda-681904da9ba9.png)

**Comment by Gustry** [comment]
> my first idea was to use google (or/and nominatim), if possible

API such as Nominatim/Google are used when you want to deal with address. But in this case, you just want to type coordinates and the map needs to pan/zoom. Everything is in OpenLayers, there is no need for external API. I'm going to rephrase your title.
