### ISSUE TITLE
JSON Layout not working for filtered graph 

### ISSUE THREAD

**Issue by TheebaRaveen** [3liz/lizmap-web-client#2687]
### What is the bug?

I have a lizmap project with graphs I created thanks to the dataviz tool. I also created a filtered graph by checking the box 'Display filtered plot in popups of parent layer' in the configuration panel of the graph. I changed the default colors of my pie chart sectors using the JSON layout option in the graph config panel as explained in the documentation : 
https://docs.lizmap.com/3.4/en/publish/lizmap_plugin/dataviz.html#json-layout 

However my filtered graph still has the default colors.

![Capture d’écran 2022-01-10 110530_LI](https://user-images.githubusercontent.com/76943337/148749547-5f48165c-db6a-4d2f-8bc5-3398a617e181.jpg)
 
I assumed that changing the parent graph layout would also change the child graph layout but it's not the case... Is there any way to fix this ?
Thanks in advance for any help provided !

### Steps to reproduce the issue

1. In Lizmap plugin > Dataviz panel > add a pie chart
2. Check the 'Display filtered plot in popups of parent layer' box
3. In the Layout text area, I used the "**colorway**" attribute (ref here : https://plotly.com/javascript/reference/#layout) to change my sectors' color : 
{"colorway": ["#F18E7C", "#6B5493", "#EF4651", "#4ABEB5"]} 

### Lizmap version

3.5

### QGIS desktop version

3.16

### QGIS server version

3.16

### Operating system

Windows 10

### Browsers

Firefox, Chrome

### Browsers version

Version 97.0.4692.71 (Build officiel) (64 bits)

**Comment by josemvm** [comment]
hi @TheebaRaveen do you know how we can change the legend order for pie chart? i dont't know if it is possible, i can't find information about it here https://plotly.com/javascript/reference/#layout

@mdouchin we can read `For pie chart : the items in the legend are ordered by X as a default behaviour.` on lizmap documentation...

**Comment by mdouchin** [comment]
We published a Processing algorithm in our [QGIS Resource repository](https://github.com/3liz/QGIS-Resources), which allows to update fields for the color and the label of every feature, based on the symbology (rule based or not). These fields will then be used for X (label) and for color.
See https://github.com/3liz/QGIS-Resources/blob/master/collections/processing-scripts/processing/main_color.py

We need to improve the documentation about it cc @nboisteault @Gustry

**Comment by josemvm** [comment]
@mdouchin thanks a lot for your work and your information!
i have installed now the qgis resource sharing plugin with your 3liz sharing resources repository but i have no ideia how i can use the srcipts to get my propose `change the legend order for pie chart`...
