### ISSUE TITLE
How to fill automaticaly fields when creating feature ?

### ISSUE THREAD

**Issue by arthuragone** [3liz/lizmap-web-client#2690]
### Description
hello, 

I've set-up a project with an editable layer with linear geographic elements. I would like to add some automaticaly filled fields to this layer. 
The primary key table
The name of the user
The date of creation / modification

I've searched many threads but can't find the exact how to. 

### Environment

 - Lizmap version: 3.4.8
 - QGIS Server FULL version: 3.4.4
 - QGIS Desktop FULL version: 3.16.5
 - OS (Windows, Linux, MacOS, Android…):  Windows
 - Browser (Firefox, Chrome…): Firefox

**Comment by Gustry** [comment]
Already answered on gis.stackexchange.com https://gis.stackexchange.com/questions/420980/how-to-automaticaly-fill-fields-when-creating-feature-in-lizmap/420992#420992
