### ISSUE TITLE
[Bug]: form filtering seems to associate selected unique values with AND operator

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#2694]
### What is the bug?

I apply a form filtering on PostgreSQL layer with input type unique values and specify a splitter text.

In Lizmap project, when I select several values, filter seems to be :

`( "field_thematique" LIKE '%value1%'  AND "field_thematique" LIKE '%value2%'  )`

whereas in documentation, it's OR operator who associate selected values (see [here](https://docs.lizmap.com/3.4/en/publish/lizmap_plugin/form_filtering.html?highlight=filter#unique-values)).

In other words, when I select two values, only points with this two values are displayed on map when it should be all points with at least one of these two values.

### Steps to reproduce the issue

1. Prepare a QGIS project with one PostgreSQL layer having at least a primary key and a field with unique values separate with commas
2. In QGIS project proprieties,  published the PostgreSQL layer as WFS
3. Specify with Lizmap extension a form filtering with following parameters : 
    - layer : the PostgreSQL layer opened in step 1
    - titre : at your convenience
    - type : unique values
    - field : field with unique values separate with commas
    - format : check box
    - splitter text : ,
4. Drop the project and cfg file on the Lizmap instance
5. In Lizmap project, in filter panel, select at least two values

### Lizmap version

3.4.7

### QGIS desktop version

3.10.4

### QGIS server version

3.10.4

### Operating system

Ubuntu

### Browsers

Firefox, Chrome

### Browsers version

Chrome 97.0.4692.71, Firefox 96.0.1

**Comment by mdouchin** [comment]
fixed in #3078
