### ISSUE TITLE
[Bug]: Form Filter no longer works

### ISSUE THREAD

**Issue by NJMC** [3liz/lizmap-web-client#2696]
### What is the bug?

Lizmap Form Filter doesn't appear to work on any version of Lizmap. Also on the online example maps.

### Steps to reproduce the issue

1. Set up Form Filter.
2. Publish and view in browser.

### Lizmap version

3.4.4

### QGIS desktop version

3.16.8

### QGIS server version

3.16.8

### Operating system

Mac, Ubuntu 18.04

### Browsers

Chrome

### Browsers version

Chrome 90

**Comment by katagen** [comment]
Same here?!?

**Comment by katagen** [comment]
I made some tests... It works with PostGIS layers, but not with geopackage!
