### ISSUE TITLE
"max features in pop up" value has no effect

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2705]
### What is the bug?

I'm observing that the 

![image](https://user-images.githubusercontent.com/1951107/150108559-f11c16f2-c20f-4f25-b149-97d458e20531.png)

option has no effect, as in LWC they are always shown max 10 child records (in the popup panel). In the "data" panel it shows the correct number of child records.

Along the way I think that the alignment of the text in the header of the child table (in the popup dialog) could be improved, to be consistent with the alignment of the content of the child table.

![Screenshot 2022-01-18 184714](https://user-images.githubusercontent.com/1951107/150109280-d2dc8f7c-f14c-4396-b830-34d03ce22657.png)

### Steps to reproduce the issue

Set a project with relations, having  a parent with many (more than 10) childs and set it to show the child when identifying the parent.

### Lizmap version

3.4.8

### QGIS desktop version

3.22.3

### QGIS server version

3.22.3

### Operating system

Ubuntu 20.04, Windows 10

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Latest

**Comment by ygorigor** [comment]
@gioman you have to set 50 for child layer.

**Comment by gioman** [comment]
> @gioman you have to set 50 for child layer.

@ygorigor thanks for the heads up. Is not the first time I make this mistake, and now I was mislead by the very similar name of child and parent.
