### ISSUE TITLE
qgis_server "test": error

### ISSUE THREAD

**Issue by jmarpi** [3liz/lizmap-web-client#2707]
### Environment

 - Lizmap version: 3.4.0
 - QGIS Server FULL version:  3
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…):  Container docker ubuntu 18.0.4 LTS
 - Browser (Firefox, Chrome…): All
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? : Postgres

Hi, I have the following problem:
I followed the qgis server installation tutorial, run the following command:
`/usr/lib/cgi-bin/qgis_mapserv.fcgi`

 and it gave me this response:
```
Application path not initialized
Application path not initialized
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
QFileInfo::absolutePath: Constructed with empty filename
QFSFileEngine::open: No file name specified
Content-Length: 102
Content-Type: application/json
Server:  QGIS FCGI server - QGIS version 3.16.3-Hannover
Status:  400

[{"code":"Bad request error","description":"Requested URI does not match any registered API handler"}]
```

Proceed with the lizmap installation normally.
I uploaded a map to test the operation of lizmap, but it does not load the map 
![image](https://user-images.githubusercontent.com/29391851/150363110-a06fa78c-aac1-4dc5-9d2b-1b4da9037c2c.png)

In lizmap errors I have the following:
![image](https://user-images.githubusercontent.com/29391851/150364241-0d6b2ff2-1c35-490f-9a36-7333498d40a0.png)

Also test with the following url: 
`http://localhost:90/lm/index.php/view/app/metadata`
I get it:

```json
{"info":{"version":"3.4.0","date":"2020-12-18"},"dependencies":{"jelix":{"minversion":"1.1.6","maxversion":"1.6.*"}},"qgis_server":{"test":"ERROR","mime_type":null,"http_code":0,"response":false}}
```
Does anyone have any idea what could be the error?

**Comment by Gustry** [comment]
Just curious, where did you find on the documentation to install version 3.4.0 ?
`"version":"3.4.0","date":"2020-12-18"` is too old.

You haven't showed us the administration panel, where you need to setup the QGIS Server URL for Lizmap.

**Comment by jmarpi** [comment]
@juwizeye , I solved the problem by adding the qgis server url in the admin panel

**Comment by juwizeye** [comment]
@jmarpi , I have already added qgis server url in admin panel . I can see my maps in lizmap but i' can't open the attributes data.

**Comment by Gustry** [comment]
@jmarpi As I mentioned, do not stay on a 3.4.0 it's very old, from December 2020.
Where did you read 3.4.0 (to improve the documentation ?

I'm closing as the issue from @jmarpi is solved.

**Comment by juwizeye** [comment]
@Gustry do you have any ideas on  this issues [#2704](https://github.com/3liz/lizmap-web-client/issues/2704) ?

**Comment by jmarpi** [comment]
@Gustry , Thank you very much for your help, I found the documentation in the following link:
https://docs.lizmap.com/3.4/es/install/linux.html

**Comment by Gustry** [comment]
@jmarpi as written in the link above : 

> Retrieve the latest available stable version from our Github release page.
