### ISSUE TITLE
Singletile layers are asked wich a ratio of 1.5 which increases image size and server load

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#271]
For layers with singleTile option to True, we should use a ratio of 1 (or 1.1) to decrease a lot the image to be rendered by QGIS Server, downloaded from server, and displayed in OpenLayers.
By default, if not specified, OpenLayers requires an image 1.5 times bigger

We just have to add a 

```
,ratio: 1
```

in layer configuration (around line 882 of map.js ) when singleTile is on

This would lead to performance improvement, for complex projects with many layers, as described by @haubourg

**Comment by haubourg** [comment]
Thanks for this. Just tested right now, and it works. On my screen image requested was WIDTH=2474&HEIGHT=1501 
and now is 
WIDTH=1690&HEIGHT=900 
. I get image almost twice faster on client side if data is on sqlite (6s vs 3.5s).
With postgres provider with all metadata request overhead, the gain is almost nothing (we keep around 12s by request). 
Could that be commited in core?

**Comment by haubourg** [comment]
More tests:
on postgres test base I sent you (more simple, with table and now need to request data to get metadata), We have time response from 6.5 s with large area against 5 or 5.5 s on smaller area.

**Comment by mdouchin** [comment]
@haubourg  Done in last commit 0c185b505401340f38b5c05103ad4848656ea578
I will review other performance improvements in other issues, and with focusing on your data 
I will close this issue.

Thanks for pointing this 1.5 ratio out.

**Comment by mdouchin** [comment]
@haubourg See another morning commit 60c6d4b7c71b55e2445dc4520c9804f3d6a97c53 related to issue #270

**Comment by haubourg** [comment]
Nice, 
tested here and it speed up thing too!
