### ISSUE TITLE
Export filtered data?

### ISSUE THREAD

**Issue by ludovico85** [3liz/lizmap-web-client#2715]
Hi, is it possible to export filtered data from the attribute table? It seems that with the filter activated the export function doesn't work (when clicking nothing happens).

![Cattura](https://user-images.githubusercontent.com/24815399/150565636-b484ee4a-6f1d-4aea-bcfd-ecb2ab70c9f9.JPG)

**Comment by ludovico85** [comment]
> The selection is already supported and tester in this extension. https://github.com/3liz/qgis-wfsOutputExtension/blob/master/tests/test_feature.py#L309..L325
> 
> So the issue might be on the client side. I'm transferring the issue. Can you fill information like LWC version, WfsOutputExtension version and QGIS Server version ?

- Lizmap 3.5.0
- QGIS server 3.16.14
- WfsOutputExtension 1.6.2

**Comment by Gustry** [comment]
I just did a quick test, I couldn't replicate on demo.lizmap.com : 
https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=cats
with the same versions as yours.

**Comment by ludovico85** [comment]
I've made a video [video](https://drive.google.com/file/d/1W28-A2AZ_orCkXHVKKm9TwZj_cH_Lf0u/view?usp=sharing) with your demo. As you can see, the export function doesn't work.

**Comment by josemvm** [comment]
hi

i can confirm, it doesn't work by my side and on https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=cats

**Comment by josemvm** [comment]
the same as https://github.com/3liz/lizmap-web-client/issues/1922

**Comment by josemvm** [comment]
related with https://github.com/3liz/lizmap-web-client/issues/1922

**Comment by Gustry** [comment]
Ah, when you have filter on the layer, sorry, I was using "selection" only.

Indeed, opening the javascript console, there is a 500 :  
![Screenshot from 2022-01-24 15-42-22](https://user-images.githubusercontent.com/1609292/150804012-70efd0dd-a08a-48b6-bec2-c0feb235a5db.png)

Just before, clicking, on features, there is a `Uncaught TypeError: n[v] is undefined` in the console as well.

**Comment by ludovico85** [comment]
I've also noticed that the export function with selected feature works as expected for geometry layers, but with table without geometry the function exports the whole table and not only selected rows.

**Comment by Gustry** [comment]
> I've also noticed that the export function with selected feature works as expected for geometry layers, but with table without geometry the function exports the whole table and not only selected rows.

I could indeed confirm for tabular layer but it seems another issue.

**Comment by rldhont** [comment]
This is a regression in 3.4.8.

**Comment by rldhont** [comment]
@mdouchin I think it has been introduced by the `selectiontoken` parameter used for WFS GetFeature Request:
* https://github.com/3liz/lizmap-web-client/pull/2608
* backport https://github.com/3liz/lizmap-web-client/pull/2667

**Comment by Gustry** [comment]
This should be fixed in latest packages available on https://packages.3liz.org
Ref #2734 #2739 #2740

**Comment by josemvm** [comment]
export doesn't work if we have a selection on 3.4.9

**Comment by nboisteault** [comment]
@josemvm Did you refresh cache (ctrl + F5)? In which file format do you export?

**Comment by josemvm** [comment]
@nboisteault yes
with an activated selection, the export only works for geojson format

**Comment by Gustry** [comment]
Can you elaborate your scenario ?
I couldn't replicate just now on https://demo.lizmap.com/lizmap_3_4/index.php/view/map/?repository=feat1&project=cats# which is using the latest versions of LWC 3.4

**Comment by josemvm** [comment]
gml format:
browser:
`The server reported an error 400 during the export of the layer.`

gqgis server logs:
`WARNING [1435]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.`

`WARNING Server[1435]: <ServiceExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="RequestNotWellFormed">FEATUREID FILTER and BBOX parameters are mutually exclusive</ServiceException>
</ServiceExceptionReport>`

for all formats except geojson format:
browser: no errors

gqgis server logs:
` WARNING [1435]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.`

`17:26:20 WARNING [1435]: Service WFS 1.0.0 not found, returning default`

`WARNING Server[1435]: <ServiceExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="RequestNotWellFormed">FEATUREID FILTER and BBOX parameters are mutually exclusive</ServiceException>
</ServiceExceptionReport>`

`WARNING OGR[1435]: Cannot open /tmp/QGIS_WfsOutputExtension/gml_features_1644168380.3341568.gml.()`
`INFO WfsOutputExtension[1435]: Temporary GML file is /tmp/QGIS_WfsOutputExtension/gml_features_1644168380.3341568.gml`
`CRITICAL WfsOutputExtension[1435]: Output layer /tmp/QGIS_WfsOutputExtension/gml_features_1644168380.3341568.gml is not valid.`
`INFO WfsOutputExtension[1435]: send_output_file ran in 0.0s`
`CRITICAL Server[1435]: startswith first arg must be str or a tuple of str, not NoneType`
`INFO Server[1435]: Request finished in 11 ms`

making a filtter from selection everything works fine on data table!
using export from selection tool everything works fine too!

i can provide an url for you if you want to investigate
thanks

**Comment by rldhont** [comment]
@josemvm thanks for these logs. The service exception explains that the WFS contains FEATUREID and FILTER and/or BBOX.

* Can you provide the QGIS Server version ?
* Can you provide the request received by QGIS Server ?

**Comment by josemvm** [comment]
qgis server version  3.16.16

qgis server request:
`19:35:44 INFO Server[2326]: ******************** New request ***************
19:35:44 INFO Server[2326]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?
19:35:44 INFO Server[2326]: Environment:
19:35:44 INFO Server[2326]: ------------------------------------------------
19:35:44 INFO Server[2326]: SERVER_NAME: 127.0.0.1
19:35:44 INFO Server[2326]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi
19:35:44 INFO Server[2326]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
19:35:44 INFO Server[2326]: REMOTE_ADDR: 127.0.0.1
19:35:44 INFO Server[2326]: SERVER_PORT: 80
19:35:44 INFO Server[2326]: QUERY_STRING:
19:35:44 INFO Server[2326]: CONTENT_TYPE: application/x-www-form-urlencoded
19:35:44 INFO Server[2326]: REQUEST_METHOD: POST
19:35:44 INFO Server[2326]: HTTP_ACCEPT: */*
19:35:44 INFO Server[2326]: HTTP_USER_AGENT: Lizmap
19:35:44 WARNING [2326]: Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
19:35:44 INFO WfsOutputExtension[2326]: requestReady ran in 0.0s
19:35:44 INFO Lizmap[2326]: Request headers provided
19:35:44 INFO Lizmap[2326]: No lizmap user groups in request headers
19:35:44 INFO Lizmap[2326]: Lizmap user groups in parameters : __priv_ze_macau,admins,dausu,editors,ma,users
19:35:44 INFO Lizmap[2326]: No acl defined in Lizmap config
19:35:44 INFO Server[2326]: BBOX:-71077.12588,-137052.81516,109510.38907,-59723.635168
19:35:44 INFO Server[2326]: DL:1
19:35:44 INFO Server[2326]: FEATUREID:Plataformas.5,Plataformas.7
19:35:44 INFO Server[2326]: LIZMAP_OVERRIDE_FILTER:1
19:35:44 INFO Server[2326]: LIZMAP_USER:ze_macau
19:35:44 INFO Server[2326]: LIZMAP_USER_GROUPS:__priv_ze_macau, admins, dausu, editors, ma, users
19:35:44 INFO Server[2326]: MAP:/var/www/html/lizmap_web_client/lizmap/install/ma/RSU.qgs
19:35:44 INFO Server[2326]: OUTPUTFORMAT:GML2
19:35:44 INFO Server[2326]: REQUEST:getfeature
19:35:44 INFO Server[2326]: SELECTIONTOKEN:63de09c516edaefd9a3a682c6458f394
19:35:44 INFO Server[2326]: SERVICE:WFS
19:35:44 INFO Server[2326]: TYPENAME:Plataformas
19:35:44 INFO Server[2326]: VERSION:1.0.0
19:35:44 WARNING [2326]: Service WFS 1.0.0 not found, returning default
19:35:44 INFO Server[2326]: WFS Request parameters:
19:35:44 INFO Server[2326]:  - OUTPUTFORMAT : GML2
19:35:44 INFO Server[2326]:  - TYPENAME : Plataformas
19:35:44 INFO Server[2326]:  - FEATUREID : Plataformas.5,Plataformas.7
19:35:44 INFO Server[2326]:  - BBOX : -71077.12588,-137052.81516,109510.38907,-59723.635168
19:35:44 INFO Server[2326]:  - VERSION : 1.0.0
19:35:44 WARNING Server[2326]: <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.2.0">
 <ServiceException code="RequestNotWellFormed">FEATUREID FILTER and BBOX parameters are mutually exclusive</ServiceException>
</ServiceExceptionReport>

19:35:44 WARNING OGR[2326]: Cannot open /tmp/QGIS_WfsOutputExtension/gml_features_1644176144.9155545.gml.()
19:35:44 INFO WfsOutputExtension[2326]: Temporary GML file is /tmp/QGIS_WfsOutputExtension/gml_features_1644176144.9155545.gml
19:35:44 CRITICAL WfsOutputExtension[2326]: Output layer /tmp/QGIS_WfsOutputExtension/gml_features_1644176144.9155545.gml is not valid.
19:35:44 INFO WfsOutputExtension[2326]: send_output_file ran in 0.0s
19:35:44 CRITICAL Server[2326]: startswith first arg must be str or a tuple of str, not NoneType
19:35:44 INFO Server[2326]: Request finished in 11 ms`

**Comment by rldhont** [comment]
Thanks @josemvm BBOX and FEATUREID are in the request's parameters.

**Comment by josemvm** [comment]
@rldhont what does it mean? a srid problem, a bbox problem on my all projects?...

**Comment by rldhont** [comment]
It is a regression in Lizmap, before 3.4.8 it was using `EXP_FILTER` and `BBOX`, now it uses `FEATUREID` instead of `EXP_FILTER` but `FEATUREID` and `BBOX` cannot be used in the same WFS request.

A new issue has to be opened with your logs, and a fix has to be proposed.

**Comment by josemvm** [comment]
@rldhont thanks for clarifying
