### ISSUE TITLE
document syntax to filter fields shown in atttribute table

### ISSUE THREAD

**Issue by haubourg** [3liz/lizmap-web-client#272]
Hi, not sure if it is a bug or a feature request:
 I could'nt find a working syntax for masking fields on attribute table. A tooltip would be sufficient. 
I tried those syntaxes :
`field1,field2`
`field1, field2`
`field1;field2`

each time, this lead to a non functional attribute table.

**Comment by rldhont** [comment]
Is it a plugin issue ?

**Comment by mdouchin** [comment]
Fields must be separated by comma

```
field1, field2
```

I will check and try to reproduce the bug

**Comment by rldhont** [comment]
@mdouchin plugin issue ?

**Comment by rldhont** [comment]
This works server side
```
field1, field2
```
