### ISSUE TITLE
draw tool - always remains activated

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2727]
### What is the bug?

when the user ativate the draw tool, it always remains activated, even after the user closes the draw box or choose another tool

### Steps to reproduce the issue

try to draw a shape and drag the map...

### Lizmap version

3.4.8

### QGIS desktop version

3.16.16

### QGIS server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

96.0.2

**Comment by Gustry** [comment]
I can confirm the issue on https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=drawing

**Comment by nboisteault** [comment]
@mdouchin I'd like to discuss the UX of the draw tool with you

**Comment by josemvm** [comment]
@nboisteault and @mdouchin  if you can take in account this feature too https://github.com/3liz/lizmap-web-client/issues/2421
;-)

**Comment by nboisteault** [comment]
> @nboisteault and @mdouchin if you can take in account this feature too #2421 ;-)

https://github.com/3liz/lizmap-web-client/issues/2421#issuecomment-1434461131
