### ISSUE TITLE
[feature] allow editing update/delete if primary key is not a serial

### ISSUE THREAD

**Issue by haubourg** [3liz/lizmap-web-client#273]
Hi, 
currently in 3.0beta, editing is only allowed if primary key is a serial, which is good for inserts and newcomers. Anyway, this kills database model if we want users to only be able to update values (or delete).
Is the reason for this is that there is no edit buffer and error message raising from DB up to the user?

**Comment by mdouchin** [comment]
Done via e79a016d8268a6398e79c0f227d6e895c40a5170
@haubourg Can you test it please and report any issue ?

This is done by not adding fields with NULL values in the query,
which lets the database use sequences and default values for column
when no data is given for a field.

**Comment by haubourg** [comment]
Hi, not tested yet, but what is the behaviour if no sequence or default value is set, and provided values end up to duplicates. Postgres transaction will return an error, is it fowarded to client and end user or will that be a silent fail?

**Comment by mdouchin** [comment]
Postgresql will return an error, and Lizmap will just report to the user "An error occured while saving the form"
We should enhance error loggin, but we won't print the postgresql error in the web client. Probably the best is to let the admin user to read the last 500 logs in the admin panel.

**Comment by rldhont** [comment]
We found an issue in QGIS and QGIS Server, the FeatureID generated by qgis to have correspondance with the primary keys and the FeatureID is unique in one QGIS but not in 2 QGIS instances. So 2 QGIS Server would not have the same FeatureID for the primary keys, so the update will be unsafe.

**Comment by nboisteault** [comment]
@rldhont can it be closed ?

**Comment by rldhont** [comment]
reopen if needed

**Comment by rldhont** [comment]
QGIS Server 2.18.* and 3.4.10 provide FeatrueID that are not interger.
