### ISSUE TITLE
Remove data table transparency

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#2732]
### Description

HI, i would like to know how to remove the data table transparency when the mouse position is out of the table.

![image](https://user-images.githubusercontent.com/8012527/151431018-7fb85e0a-6999-467d-ac62-fbabdf0d0eca.png)

Many thanks

### Environment

 - Lizmap version: 3.3.1
 - QGIS Server FULL version:
 - QGIS Desktop FULL version:
 - OS (Windows, Linux, MacOS, Android…): 
 - Browser (Firefox, Chrome…):
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Gustry** [comment]
You need to use JavaScript. You have the documentation (with video tutorial):
https://docs.lizmap.com/current/en/publish/customization/javascript.html

You need to change the `opacity` of the `#bottom-dock`.

**Comment by ygorigor** [comment]
Or you can add your theme
https://docs.lizmap.com/current/en/publish/customization/themes.html
