### ISSUE TITLE
image legends on layers

### ISSUE THREAD

**Issue by gonzalezhidalgorafael** [3liz/lizmap-web-client#2733]
### Description

Hello.
I am having a problem while showing the layer or legend image of that layer (thare are WMS layers).
When i configure in the Lizmap plugin the layer, "map options section" without selecting "Get images from WMS server"

![image](https://user-images.githubusercontent.com/98315686/151528036-cd9babdb-ebe0-4e3e-9e7c-f79953c3b84e.png)

The legend image shows but not the layer itself in the map but, if i select the option mentioned before, it happens the opposite, the image legend of the layer does not show but it does the layer in the map.

In other hand, i have another layer (in this case a Vector type layer) in wich i have created an style categorization:

![image](https://user-images.githubusercontent.com/98315686/151528783-e8511fa1-7a5b-4389-a23c-7b83f9933442.png)

And in lizmap it is not showed, in fact the legend image appears to be broken:

![image](https://user-images.githubusercontent.com/98315686/151528947-2576d901-6c84-4607-bd6e-f546396b66f4.png)

Could you let me know what would be happen? I will really appreciate that. Thanks with anticipation.

### Environment

 - Lizmap version: 3.4.8
 - QGIS Server FULL version: 1.3.0
 - QGIS Desktop FULL version: 3.16.11-Hannover
 - OS (Windows, Linux, MacOS, Android…): Ubuntu Server and Windows 10 client
 - Browser (Firefox, Chrome…): Chrome & Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? user admin, nothing relative in the logs, stored into PostgreSQL

**Comment by gioman** [comment]
@gonzalezhidalgorafael does the WMS layer CRS match the CRS of the QGIS project?

**Comment by gonzalezhidalgorafael** [comment]
No, but i have configured it now and the problem remains :(
