### ISSUE TITLE
Project with Materialized view don't start

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#274]
Hello
I am testing Lizmap with materialized views.
data on Postgis/postgres9.4 debian server, lizmap 2.11 and beta3 on debian server.
Qgis server 2.14

I made a simple materialized view, to reproject and simplify a set of feature, like this
***********
CREATE MATERIALIZED VIEW webgis.region_3857 AS 
 SELECT region_3045.id,
    st_multi(st_transform(st_simplifypreservetopology(region_3045.geom, 200::double precision), 3857))::geometry(MultiPolygon,3857) AS geom
   FROM myschema.region_3045
WITH DATA;

ALTER TABLE webgis.region_3857  OWNER TO myself;

CREATE INDEX region_3045_geom  ON webgis.region_3857  USING gist(geom);

GRANT SELECT ON TABLE webgis.region_3857 TO lizmap_viewer;
***********************
Then in Qgis 2.14 I correctly load this view (as lizmap_viewer user) and it works
I set OWS Server with minimal informations.
Set preferences minimal with lizmap plugin and load on the server.

If then I try to load the project it don't show any feature, processing logo runs all the time..
It seems that also my browser waits for some response, as the tab with project loading becomes unresponsive.

I erased cache both local and on server..

I add also that if I look at processes with top command I can see qgis-server that goes for a second to top resource usage and then disappear from  command list

What is wrong with it?

Thanks
Pietro

**Comment by rldhont** [comment]
hi @pieri70 

If your project has been created with QGIS 2.14, this issue is probably due to shortname not supported by Lizmap Web Client.

We have fixe it for 2.12 and 3beta. the next release should work. Can you test directly from source version ?

**Comment by pieri70** [comment]
Hello
thanks for response
Sorry for the mess.. 
The materialized view not showing was a port restriction imposed by our IT managers..
I saw it was a problem common to all layers taken from new postgis server..
Opening 5432 for lizmap server/postgis server made my project working again.

pietro

**Comment by rldhont** [comment]
Hi @pieri70,
Does it mean that you open port 5432 and fixe this issue ?
Can you close this issue if it is fixed ?

**Comment by pieri70** [comment]
Yes I'll close it!
Thanks
