### ISSUE TITLE
add/update photo from memory card - stop working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2741]
### What is the bug?

it's not possible to upload photos from memory card

### Steps to reproduce the issue

try this operation

### Lizmap version

3.4.9

### QGIS desktop version

3.16.16

### QGIS server version

3.16.16

### Operating system

Windows 10

### Browsers

Firefox, Chrome

### Browsers version

Opera too (last versions)

**Comment by josemvm** [comment]
unlike version 3.5.1-pre, this version allows uploading only from the memory card

**Comment by josemvm** [comment]
please, can someone confirm this behavior?
different from one version to another...

thanks

**Comment by laurentj** [comment]
Hi,

I don't understand how could Lizmap be responsible of this issue. It seems it is more an issue between your browser and your computer. And storing to/from a memory card and to/from a hard disk, is the same thing from the point of vue of PHP.  

In fact, i don't understand your use case. What are you doing exactly? On which device?

**Comment by Gustry** [comment]
I think we can close.

> 3.4.9

We won't make any fix on 3.4.X for this kind of bug anymore. Only critical now.

> unlike version 3.5.1-pre.5066, this version allows uploading only from the memory card
