### ISSUE TITLE
[Bug]: Character "&" -> Export: field values with Syntax <![CDATA[value]]>

### ISSUE THREAD

**Issue by Polytrauma83** [3liz/lizmap-web-client#2742]
### What is the bug?

When data is exported with the export function, each cell of the database that contains a "&" character is saved with the syntax of a CDATA section.

Example:
Postgis: Field value -> B31; P&R Parkplatz
Export: As .ods -> \<![CDATA[B 31; P&R Parkplatz]]>

According to my experiments, this affects all output formats. At least within my data, there is this problem only with "&".
I couldn`t find something specific in the changelog. I´m sorry if this is not a bug or has been fixed already.

Thx for all your great work!

### Steps to reproduce the issue

Try it in your own setting with charakter &.
Or go to https://lizmap.rettungspunkte-forst.de
Export data. Search table or file for the syntax.

### Lizmap version

3.4.0-rc.2

### QGIS desktop version

3.22

### QGIS server version

Idk

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Latest

**Comment by rldhont** [comment]
This comes from https://github.com/3liz/qgis-wfsOutputExtension in which GML is transformed to other format. In GML, field values are DOM TextNode in which & is authorized in <![CDATA[ ]]>, and GDAL does not removed <![CDATA[ ]]> like any XML reader.

**Comment by Gustry** [comment]
Duplicated of https://github.com/3liz/qgis-wfsOutputExtension/issues/17

> QGIS server version : Idk

You will have issues if you are running an old QGIS server version. You should check, your version must match the QGIS Desktop one.

> Lizmap version : 3.4.0-rc.2

This is an old version of Lizmap. RC mean Release Candidate, ie "not fully stable". It was released more than a 1 year ago. We made a lot of bugfixes in 3.4.X. You should upgrade.

**Comment by Gustry** [comment]
This should be fixed in QGIS Server 3.24.1 and 3.22.6.

Thanks to @pcav for funding this bugfix.
