### ISSUE TITLE
Min scale not honoured

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#275]
If I define min scale for the map at 2000, the zoom with google base layer goes down to 1280. This is inconvenient, as it requires an extra zoom level (19) that was in principle excluded by the config.
See for an example:
http://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=pontedera

**Comment by nboisteault** [comment]
From what I understand and see on your map, you want the min scale to be 2257 and not 1128 (I can't see 1280). Or do you also want to have min scale 2000 available? In this case extra zooms which are not integers would be needed.

**Comment by pcav** [comment]
I set minscale to 2000, so I would expect to go down to 2257. 1128 is unwanted.

**Comment by josemvm** [comment]
Hi Paolo,

how did you insert a "permalink" (hyperlink) on the rigth up corner of the map area!?

**Comment by pcav** [comment]
It's a standard feature of recent Lizmap, I believe.

**Comment by josemvm** [comment]
Yes, you're right. i didn't notice that...
Thanks

**Comment by rldhont** [comment]
@pcav for this issue if you defined min scale as 10000 and max scale as 100000, you want to have 18056 and 72224 ?

**Comment by pcav** [comment]
I have trouble following the logic. I think actual zooming level should be approximately those chosen by the user, and should not exceed these bounds. I currently have projects with minscale at 100 which go down to ~500, and minscale 2000, that on the contrary go down to ~1000

**Comment by rldhont** [comment]
For the minscale at 100, it's more a problem of available minscale in lizmap.

I will review the way I calculate min and max scale for Google Mercator Projection.

**Comment by pcav** [comment]
Thanks @rldhont

**Comment by josemvm** [comment]
hi @rldhont 

in case of the montpellier project which has defined mapScales as 10000, 25000, 50000, 100000, and 150000, is it expected to be able to navigate with these exact zoom levels (having a empty baselayer)?

**Comment by rldhont** [comment]
Hi @josemvm This is not possible with OpenLayers 2.*.

**Comment by nboisteault** [comment]
With master version of OL 2.* you can use fractionalZoom. Here is an example : http://dev.openlayers.org/examples/fractional-zoom.html

I've use it here : http://cartographiegranderegion.observatoire-environnement.org/visualiseur/
The first scale is not one of the default one, that's why base layer tiles are a little bit fuzzy. You can also have zoom with float value when zooming with the 'zoom to area' control.
