### ISSUE TITLE
ldap authentication

### ISSUE THREAD

**Issue by prahout59** [3liz/lizmap-web-client#2750]
I want to activate ldap authentication in the lizmap container but, after a whole working day, I've always the same error

_lizmap_1  | 2022-01-31 16:59:15 [615]   ldap profile name is missing    /www/lizmap/vendor/jelix/ldapdao-module/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php  39_

As soon as I active ldapdao driver, the lizmap container does not start with the message concerning ldap profile name

My localconfig.ini.php is ok

_[coordplugin_auth]
;; uncomment it if you want to use ldap for authentication
;; see documentation to complete the ldap configuration
driver=ldapdao_

_[coordplugins]
lizmap=lizmapConfig.ini.php
auth=authldap.coord.ini.php__

Le fichier profiles.ini.php contient bien la section avec la configuration ldap
![image](https://user-images.githubusercontent.com/91070758/151830992-00be796f-ce05-4283-aeb4-30914845e312.png)

et le fichier authldap.coord.ini.php contient la ligne indiquant le profile à utiliser
_; profile to use for ldap
ldapprofile = "lizmapldap"_

J'utilise les dernières images lizmap 3.5

J'ai eu beau chercher, je n'ai rien trouvé.
Je pourrais modifier le fichier /www/lizmap/vendor/jelix/ldapdao-module/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php mais, ce n'est pas une bonne idéee, je pense.

Pouvez-vous m'aider rapidement. Je suis un peu en retard sur ce sujet.

**Comment by dmarteau** [comment]
Issue transfered to https://github.com/3liz/lizmap-web-client/issues/2750

**Comment by rldhont** [comment]
@prahout59 I have transfered your issue to lizmap-web-client where it is more relevant.

**Comment by prahout59** [comment]
Pour information, j'ai modifié le fichier ldapdao.auth.php comme suit :

	parent::__construct($params);

        if (!isset($this->_params['ldapprofile']) || $this->_params['ldapprofile'] == '') {
            $this->_params['ldapprofile'] = 'lizmapldap';
			// throw new jException('ldapdao~errors.ldap.profile.missing');
        }
        $this->_params['dao'] = 'jauthdb~jelixuser';
		$this->_params['profile'] = 'jauth';
		$this->_params['jelixAdminLogin'] = 'admin';

        $profile = jProfiles::get('ldap', $this->_params['ldapprofile']);
		//jMessage::add('constructeur de  de la classe');

Je n'ai plus les erreurs de jlog mais, cela ne fonctionne pas correctement.

Quand j'active le module ldapdao dan localconfig.ini.php

- le compte admin n'est plus reconnu (utilisateur ou mdp incorrect)
- la première connexion d'un utilisation ldap est acceptée avec le mot de passe du compte ldap puis, à la connexion suivante, cela ne fonctionne plus. (cela veut dire que le module ldapdao est bien activé quand même)
- si je supprime le compte ldap de jauth.db.jlx_usr, l'utilisateur ldap peut se reconnecter une première fois uniquement.

Quand je désactive le module ldapdao

- le compte admin est reconnu mais je ne peux bien sûr pas utiliser un compte ldap

J'espère que cela vous aidera 💯 

[ldapdao.auth - Copie.txt](https://github.com/3liz/lizmap-web-client/files/7993457/ldapdao.auth.-.Copie.txt)

**Comment by prahout59** [comment]
Après avoir perdu beaucoup de temps en ajoutant des traces dans le fichier ldapdao.auth.php, il s'avère que l'erreur vient du module jcommunity. 
La propriété cDaoRecord_jauthdb_Jx_jelixuser_Jx_sqlite3::$status est inconnue.

_2022-02-08 09:25:38     192.168.22.26   notice  2022-02-08 09:25:38     [8]     Undefined property: cDaoRecord_jauthdb_Jx_jelixuser_Jx_sqlite3::$status /www/lizmap/vendor/jelix/jcommunity-module/modules/jcommunity/classes/authcommunity.listener.php_ 

En la forçant comme suit, cela fonctionne parfaitement.

_class authcommunityListener extends jEventListener{

   /**
   *
   */
   function onAuthCanLogin ($event) {
        // debut ajout pra
        $event->getParam('user')->status=true;
        // fin ajout pra
        $event->Add(array('canlogin'=>
            ($event->getParam('user')->status >= Account::STATUS_VALID)));
   }
}_

J'investiguerai plus tard car d'autres propriétés sont  inconnues

_2022-02-08 09:32:46     192.168.22.26   notice  2022-02-08 09:32:46     [8]     Undefined property: cDaoRecord_jauthdb_Jx_jelixuser_Jx_sqlite3::$firstname      /www/temp/lizmap/www/compiled/templates/modules/lizmap/user_menu_html_t_15.php       22

2022-02-08 09:32:46     192.168.22.26   notice  2022-02-08 09:32:46     [8]     Undefined property: cDaoRecord_jauthdb_Jx_jelixuser_Jx_sqlite3::$lastname       /www/temp/lizmap/www/compiled/templates/modules/lizmap/user_menu_html_t_15.php       23_

A suivre

**Comment by rldhont** [comment]
@prahout59 pouvez-vous reverser vos corrections dans:
* jCommunity https://github.com/jelix/jcommunity-module
* jelix https://github.com/jelix/jelix

**Comment by prahout59** [comment]
Je ne pense pas que ce soit une erreur du module jcommunity mais plutôt un défaut de paramétrage de ce module dans l'image docker lizmap actuelle. 
La configuration est bien indiquée dans la description jcommunity mais n'est pas présente dans les fichiers de configuration lizmap.

jCommunity installation [https://github.com/jelix/jcommunity-module/wiki/Installation]

La modification de la classe authcommunityListener extends jEventListener permet seulement de contourner ce défaut en attendant la mise à jour de l'image.
J'ai ajouté un volume docker vers le fichier  /www/lizmap/vendor/jelix/jcommunity-module/modules/jcommunity/classes/authcommunity.listener.php afin de le rendre persistant mais le mieux serait d'avoir une image lizmap avec la configuration complète du module jcommunity.

@rldhont : qu'en pensez-vous ?
