### ISSUE TITLE
[Bug]: Timemanager does not show location pointer while running.

### ISSUE THREAD

**Issue by petunja** [3liz/lizmap-web-client#2753]
### What is the bug?

Hi to all, 
I used timemanager in lizmap_3_3 and also modified.. It was all ok.
Now, with lizmap_3_5, I have a problem.
Timemanager doesn't show poiter while running.
I add my project to let you see if there are errors in configuration.
tank you

.
[alas.zip](https://github.com/3liz/lizmap-web-client/files/7997250/alas.zip)

### Steps to reproduce the issue

1. copy project in your lizmap repositories folder
2. add project to lizmap pointing to folder
3. open project in lizmap
4. open timeManager tool
5. start track
6. observe there is no pointer during play

### Lizmap version

3.5

### QGIS desktop version

3.6.1

### QGIS server version

3.22.3

### Operating system

mint 20.3 cinnamon

### Browsers

Chrome

### Browsers version

chromium 97.0.4692.99

### Relevant log output

```shell
no log entries.
```

**Comment by Gustry** [comment]
Did you reuse the Lizmap plugin to regenerate the CFG file ? (using the timemanager tool in the QGIS desktop plugin)
Configuration from LWC 3.3 to 3.4 has changed in the CFG file.

You didn't upload the ZIP project correctly.

**Comment by petunja** [comment]
yes, I did all by zero:
- lizmap installation 2.5 (on virtualbox)
- qgis plugin last version (3.7.1)
- project qgis (qgis desktop 3.6)

**Comment by petunja** [comment]
I was asking to myself if I did error with datetime:

I setted datetime format as: aaaa/mm/gg hh:mm:ss (i tries also aaa-mm-gg hh:mm.ss)

in lizmap qgis-plugin I setted:
frame-duration: 1
kind of frame: seconds
animation duration frame: 1000ms

(I have one point at second in my track)

someone can help me?
tank you.

**Comment by Gustry** [comment]
Did you check your date time format : https://docs.lizmap.com/current/en/publish/lizmap_plugin/time_manager.html#configuring-the-tool ?

**Comment by petunja** [comment]
Yes, i did, and I had no errors.

I tried to redo again qgis project (by zero). I also tried a new datetime format (aaaa-mm-ggThh:mm:ss)...
..same result.

when I open project with chromium console opened i have foolowing messages (also if the project is correctly opened):
`GET http://localhost/gis/lizmap/www/assets/js/lizmap.js net::ERR_ABORTED 404 (Not Found)
jquery-migrate-3.3.1.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.1
localhost/:49 GET http://localhost/gis/lizmap/www/assets/js/lizmap.js net::ERR_ABORTED 404 (Not Found)
jquery-3.5.1.min.js:2 [Violation] 'setTimeout' handler took 219ms
[Violation] Forced reflow while executing JavaScript took 41ms
16[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>`

when I click on timemanager, layer disappears. 
If I play (click on start) timemanager start correctly and time updates as expected, but I can't see any pointer to map (no waypoint hilighted.

**Comment by petunja** [comment]
I'm going crazy.. 
I tried to re-convert my csv file as EsriShape giving attention to timedate format in layer (from properties of layer).
now I can save layer with correct time-date format (yyyy-MM-dd hh:mm:ss insetad of having also milliseconds).
I tried this thinking milliseconds was the problem.
Nothing changed..

I don't know if there is a precise conversion procedure from csv to shape file that I must observe to have a correct visualization of points during timemager play.

I can start play and datetime updates in timemanager, but I can't see any hilighted point.
I posted above a warning about moment deprecation, but I don't think its the fault (it's a warning and I can play timemanager).

I opened chromium console (elements tab) during timemanager-playing and I selected map.
I found a refresh every second wich show this code changings (they refresh every second):
![Senza titolo-3](https://user-images.githubusercontent.com/20890435/154262766-a2f800ae-7d2d-407e-9b5e-d7df67387d84.jpg)

If I open chromium console (network tab) during timemanger-playing, I see two elements refreshing every second:

1. xhr file: if I open it on a new tab it show me an xml message (see image below)
2. png file: if I open it on a new tab it show an empty image
![Senza titolo-4](https://user-images.githubusercontent.com/20890435/154264640-f30349ff-5bb3-41c4-91c8-2fbf0b9645a1.jpg)

I think this part of code (shown by two images thatI added) is responsible to timemnager map-updating.
I think this empty image is why I can't see any hilighted ponts on map, but I can't understand why.
Hope this can help to understand causes.

I don't undestand if I wrong project settings in qgis-desktop or I wrong some setting in lizmap or qgis-server.
![Senza titolo-4](https://user-images.githubusercontent.com/20890435/154264640-f30349ff-5bb3-41c4-91c8-2fbf0b9645a1.jpg)

If someone could give me a project wich surelly works with timemanager I could test it on my server and check if the problem is the server or the project.

tank you a lot

**Comment by petunja** [comment]
> You can also download the demo project : https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=time_manager_earthquake

please.. how to download it? if I open progect I can't click on download image..

**Comment by josemvm** [comment]
hi @petunja in your case, you are working in seconds, try to increment the `"tmAnimationFrameLength"` parameter from 1000ms to 4000ms (or more)

**Comment by petunja** [comment]
Hi @josemvm , tank you very much for your help.
I tried your suggestion, but I had no results. (with 4000ms, 6000ms.. no changes).

I downloaded and used Eathquakes demo project (https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=time_manager_earthquake) on my localhost server and It worked as expected with timemanager.

So I can be sure that the problem is not the infrastructure: the server works and it can play timemanager on Earthquakes project.

I compared every single setting between my project and the demo project and I tried to match every setting between them.
I still can't plat timemanger on my project.
As I open minidock (timemanager menu), my layer disappear and also if timenanger can be correctly started and it start update datetime, it shows any point on map.

I previously uploaded my project in this topic, I gently ask to anyone would be so nice to try test it and check if something is wrong setted or broken to be used with timenager features.
I reload the project after many checks and comparisions with the demo project (it could be a little changed after comparision)
[alasio.zip](https://github.com/3liz/lizmap-web-client/files/8104114/alasio.zip)


I'm going crazy because I really can't see any difference from earthquakes demo project and mine.

I repeat, when I open timenanger my layer simply disappear. (no log on lizmap, no error in chomium console)

To be clear, I realized my layer importing a csv (with lon-lat features for any table-row) and exported (and used) a shapefile made by this csv.

I did this with:
-  Mint 20.3(una) 64.bit
- apache2
- qgis desktop: 1:3.22.3+32focal
- qgis server:  1:3.22.3+32focal
- lizmap web client 3.5.1 (https://github.com/3liz/lizmap-web-client/releases/download/3.5.1/lizmap-web-client-3.5.1.zip)
- chromium browser

Tank you for nay.. any suggestion.

**Comment by josemvm** [comment]
@petunja did you try with `frame type` = `minutes` instead of `seconds`

**Comment by petunja** [comment]
Hi @josemvm,
yes, I tired with "frame type" as minutes and hours. (no effects)
I tried also to make a new project, with new layer and few lines in tables, but nor this one is played by timemanager.

I think problem is with filter (FILTERTOKEN in http request).
When I open Timemanager minidock in my project, layer disappear immediatelly (as it open timemanager menu)
when I do it on demo project (earthquakes), layer still reamain visible.

In the network tab (chromium console), when I open timemanager in an open project, i see a new request link as:
http://localhost/lizmap/index.php/lizmap/service/?repository= .....
in case of heartquake the link show an image with earthquakes (first frame of timeset)
in case of my project the image is empty (no points)..

this is as first frame of heartquakes:
![qgis_server_wms_map_earthquakes_time_manager_earthquake](https://user-images.githubusercontent.com/20890435/154863307-18996243-3d33-4f6c-b225-d8112661f40b.png)

(clearly I don't upload my project correspective because is empty)
