### ISSUE TITLE
server information - cannot get the details about qgis server installation

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2755]
![imagem](https://user-images.githubusercontent.com/10053874/152816868-58dc3976-b0d2-4bac-924d-2d2e156bcfd8.png)

i have installed the qgis plugin manager and i can get this information from plugin:

`/opt/qgis-server/plugins# qgis-plugin-manager list`

QGIS server version : 3.16.16
List all plugins in /opt/qgis-server/plugins

![imagem](https://user-images.githubusercontent.com/10053874/152817954-323aed2f-9b83-4d4e-a585-cd34ebe54084.png)

 - QGIS Server FULL version: 3.16.16

**Comment by Gustry** [comment]
I agree, the message is misleading because HTTP code "200" is normal for an HTTP code result... There is something to improve here IMHO.

Did you read the logs of QGIS Server ? You should have some warnings about the Lizmap plugin with what to do.

**Comment by josemvm** [comment]
my qgis server logs:

`16:05:09 INFO Server[10902]: ******************** New request ***************
16:05:09 INFO Server[10902]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities
16:05:09 INFO Server[10902]: Environment:
16:05:09 INFO Server[10902]: ------------------------------------------------
16:05:09 INFO Server[10902]: SERVER_NAME: 127.0.0.1
16:05:09 INFO Server[10902]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities
16:05:09 INFO Server[10902]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
16:05:09 INFO Server[10902]: REMOTE_ADDR: 127.0.0.1
16:05:09 INFO Server[10902]: SERVER_PORT: 80
16:05:09 INFO Server[10902]: QUERY_STRING: service=WMS&request=GetCapabilities
16:05:09 INFO Server[10902]: REQUEST_METHOD: GET
16:05:09 INFO Server[10902]: HTTP_ACCEPT: */*
16:05:09 INFO Server[10902]: HTTP_USER_AGENT: Lizmap
16:05:09 INFO Server[10902]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
16:05:09 INFO Lizmap[10902]: Request headers provided
16:05:09 INFO Lizmap[10902]: No lizmap user groups in request headers
16:05:09 INFO WfsOutputExtension[10902]: requestReady ran in 0.0s
16:05:09 INFO Server[10902]: REQUEST:GetCapabilities
16:05:09 INFO Server[10902]: SERVICE:WMS
16:05:09 INFO Server[10902]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
16:05:09 INFO Lizmap[10902]: Request headers provided
16:05:09 INFO Lizmap[10902]: No lizmap user groups in request headers
16:05:09 INFO Lizmap[10902]: Request headers provided
16:05:09 INFO Lizmap[10902]: No lizmap user groups in request headers
16:05:09 WARNING Server[10902]: WMS capabilities document not found in cache
16:05:09 INFO Lizmap[10902]: Request headers provided
16:05:09 INFO Lizmap[10902]: No lizmap user groups in request headers
16:05:09 WARNING Server[10902]: Set WMS capabilities document in cache
16:05:09 INFO WfsOutputExtension[10902]: responseComplete ran in 0.0s
16:05:09 INFO Server[10902]: Request finished in 2 ms
16:05:09 INFO Server[10902]: ******************** New request ***************
16:05:09 INFO Server[10902]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json?
16:05:09 INFO Server[10902]: Environment:
16:05:09 INFO Server[10902]: ------------------------------------------------
16:05:09 INFO Server[10902]: SERVER_NAME: 127.0.0.1
16:05:09 INFO Server[10902]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
16:05:09 INFO Server[10902]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
16:05:09 INFO Server[10902]: REMOTE_ADDR: 127.0.0.1
16:05:09 INFO Server[10902]: SERVER_PORT: 80
16:05:09 INFO Server[10902]: QUERY_STRING:
16:05:09 INFO Server[10902]: REQUEST_METHOD: GET
16:05:09 INFO Server[10902]: HTTP_ACCEPT: */*
16:05:09 INFO Server[10902]: HTTP_USER_AGENT: Lizmap
16:05:09 INFO Server[10902]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
16:05:09 INFO Lizmap[10902]: Request headers provided
16:05:09 INFO Lizmap[10902]: No lizmap user groups in request headers
16:05:09 INFO WfsOutputExtension[10902]: requestReady ran in 0.0s
16:05:09 INFO Server[10902]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
16:05:09 INFO Server[10902]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/'
16:05:09 INFO Server[10902]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/wfs3'
16:05:09 WARNING [10902]: Service  is not registered
16:05:09 WARNING Server[10902]: <ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
</ServiceExceptionReport>

16:05:09 INFO WfsOutputExtension[10902]: responseComplete ran in 0.0s
16:05:09 INFO Server[10902]: Request finished in 1 ms`

**Comment by Gustry** [comment]
I mean when QGIS Server starts, when you the see Lizmap plugin starting.

**Comment by Gustry** [comment]
In the logs, you might see some information when about Lizmap plugin and the URL above will be displayed : https://docs.lizmap.com/3.5/en/install/pre_requirements.html#lizmap-server-plugin
Did you follow this ?

**Comment by josemvm** [comment]
i have no qgis server logs when qgis server/apache restart... and i don't know why...

but with the `QGIS_SERVER_LIZMAP_REVEAL_SETTINGS` environment variable enabled i can get the expected information!

![imagem](https://user-images.githubusercontent.com/10053874/152834079-fee697f1-7360-4d73-a999-2d1e117d378c.png)

**Comment by Gustry** [comment]
Now, you can get the information straight from QGIS Desktop, in the information panel if you give set up your login : CF https://twitter.com/etrimaille/status/1484485192895115265 We will improve this new panel later.

**Comment by ocelot73** [comment]
@josemvm I had same issue and thanks to your hint I've been able to solve by inserting

`FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS True`

to my apache 000-default.conf, thank you very much !

**Comment by Cww7** [comment]
I have the same issue but I already add `FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS=True` in my Apache configuration file.

Here is my log 

`09:38:53 INFO WfsOutputExtension[614564]: responseComplete ran in 0.0s
09:38:53 INFO Server[614564]: Request finished in 0 ms
[Thu Feb 17 09:56:26.528119 2022] [mpm_prefork:notice] [pid 614555] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Feb 17 09:56:26.617562 2022] [fcgid:error] [pid 614556] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(614564) exit(shutting down), get unexpected signal 11
[Thu Feb 17 09:56:26.669978 2022] [mpm_prefork:notice] [pid 614879] AH00163: Apache/2.4.51 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1k configured -- resuming normal operations
[Thu Feb 17 09:56:26.670071 2022] [core:notice] [pid 614879] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 17 09:57:21.864277 2022] [mpm_prefork:notice] [pid 614879] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Feb 17 09:57:21.973356 2022] [mpm_prefork:notice] [pid 614909] AH00163: Apache/2.4.51 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1k configured -- resuming normal operations
[Thu Feb 17 09:57:21.973495 2022] [core:notice] [pid 614909] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 17 09:57:45.891747 2022] [negotiation:error] [pid 614912] [client X.X.X.X:42491] AH00687: Negotiation: discovered file(s) matching request: /var/www/lizmap/admin (None could be negotiated)., referer: https://XXX.fr/admin.php/master_admin/
Application path not initialized
Application path not initialized
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-www-data'
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
09:57:46 INFO Server[614928]: QGIS Server Settings:
09:57:46 INFO Server[614928]:   - QGIS_OPTIONS_PATH / '' (Override the default path for user configuration): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_PARALLEL_RENDERING / '/qgis/parallel_rendering' (Activate/Deactivate parallel rendering for WMS getMap request): '1' (read from ENVIRONMENT_VARIABLE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_MAX_THREADS / '/qgis/max_threads' (Number of threads to use when parallel rendering is activated): '-1' (read from ENVIRONMENT_VARIABLE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_LOG_LEVEL / '' (Log level): '0' (read from ENVIRONMENT_VARIABLE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_LOG_FILE / '' (Log file): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_LOG_STDERR / '' (Activate/Deactivate logging to stderr): '1' (read from ENVIRONMENT_VARIABLE)
09:57:46 INFO Server[614928]:   - QGIS_PROJECT_FILE / '' (QGIS project file): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - MAX_CACHE_LAYERS / '' (Specify the maximum number of cached layers): '100' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_IGNORE_BAD_LAYERS / '' (Ignore bad layers): 'false' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_CACHE_DIRECTORY / '/cache/directory' (Specify the cache directory): '/home/data/cache' (read from ENVIRONMENT_VARIABLE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_CACHE_SIZE / '/cache/size' (Specify the cache size): '52428800' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_SHOW_GROUP_SEPARATOR / '/locale/showGroupSeparator' (Show group (thousands) separator): 'false' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_OVERRIDE_SYSTEM_LOCALE / '/locale/userLocale' (Override system locale): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_WMS_MAX_HEIGHT / '/qgis/max_wms_height' (Maximum height for a WMS request. The lower one of this and the project configuration is used.): '-1' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_WMS_MAX_WIDTH / '/qgis/max_wms_width' (Maximum width for a WMS request. The most conservative between this and the project one is used): '-1' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_API_RESOURCES_DIRECTORY / '/qgis/server_api_resources_directory' (Base directory where HTML templates and static assets (e.g. images, js and css files) are searched for): '/usr/share/qgis/resources/server/api' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_API_WFS3_MAX_LIMIT / '/qgis/server_api_wfs3_max_limit' (Maximum value for "limit" in a features request, defaults to 10000): '10000' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_TRUST_LAYER_METADATA / '' (Trust layer metadata): 'false' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_DISABLE_GETPRINT / '' (Don't load layouts): 'false' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES / '/qgis/server_projects_directories' (Directories used by the landing page service to find .qgs and .qgz projects): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]:   - QGIS_SERVER_LANDING_PAGE_PROJECTS_PG_CONNECTIONS / '/qgis/server_projects_pg_connections' (PostgreSQL connection strings used by the landing page service to find projects): '' (read from DEFAULT_VALUE)
09:57:46 INFO Server[614928]: Ini file used to initialize settings: /srv/qgis/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
09:57:46 INFO Server[614928]: cacheDirectory: /home/data/cache/
09:57:46 INFO Server[614928]: maximumCacheSize: 52428800
09:57:46 INFO Server[614928]: Prefix  PATH: /usr
09:57:46 INFO Server[614928]: Plugin  PATH: /usr/lib/qgis/plugins
09:57:46 INFO Server[614928]: PkgData PATH: /usr/share/qgis
09:57:46 INFO Server[614928]: User DB PATH: /srv/qgis/.local/share/QGIS/QGIS3/profiles/default/qgis.db
09:57:46 INFO Server[614928]: Auth DB PATH: /home/qgis/qgisserverdb/qgis-auth.db
09:57:46 INFO Server[614928]: SVG PATHS: /usr/share/qgis/svg/:/srv/qgis/.local/share/QGIS/QGIS3/profiles/default/svg/
"Loading native module /usr/lib/qgis/server/libdummy.so"
09:57:46 INFO Server[614928]: Adding service SampleService 1.0
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
09:57:46 WARNING [614928]: Adding API Landing Page
"Loading native module /usr/lib/qgis/server/libwcs.so"
09:57:46 INFO Server[614928]: Adding service WCS 1.0.0
"Loading native module /usr/lib/qgis/server/libwfs.so"
09:57:46 INFO Server[614928]: Adding service WFS 1.1.0
"Loading native module /usr/lib/qgis/server/libwfs3.so"
09:57:46 WARNING [614928]: Adding API OGC WFS3 (Draft)
"Loading native module /usr/lib/qgis/server/libwms.so"
09:57:46 INFO Server[614928]: Adding service WMS 1.3.0
"Loading native module /usr/lib/qgis/server/libwmts.so"
09:57:46 INFO Server[614928]: Adding service WMTS 1.0.0
09:57:46 INFO Server[614928]: Server initialized
09:57:46 INFO ../../src/server/qgsserverplugins.cpp[614928]: load library /usr/lib/qgispython (3.16.15)
09:57:46 INFO ../../src/server/qgsserverplugins.cpp[614928]: Python support library loaded successfully.
<string>:1: DeprecationWarning: setapi() is deprecated
09:57:46 INFO AtlasPrint[614928]: SUCCESS - init
09:57:46 INFO Server[614928]: Adding service ATLAS 1.0.0
09:57:46 INFO atlasprint[614928]: atlasprintFilter.init
09:57:46 INFO Server[614928]: Server plugin atlasprint loaded!
09:57:46 INFO WfsOutputExtension[614928]: Temporary directory is /tmp/QGIS_WfsOutputExtension
09:57:46 INFO WfsOutputExtension[614928]: __init__ ran in 0.0s
09:57:46 INFO Server[614928]: Server plugin wfsOutputExtension loaded!
09:57:46 INFO cadastre[614928]: Init server version "1.13.5"
09:57:46 INFO cadastre[614928]: Cache directory set to /tmp/org.qgis.cadastre
09:57:46 INFO Server[614928]: Adding service CADASTRE 1.0.0
09:57:46 INFO Server[614928]: Server plugin cadastre loaded!
09:57:46 INFO Server[614928]: Server python plugins loaded
09:57:46 INFO Server[614928]: ******************** New request ***************
09:57:46 INFO Server[614928]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities
09:57:46 INFO Server[614928]: Environment:
09:57:46 INFO Server[614928]: ------------------------------------------------
09:57:46 INFO Server[614928]: SERVER_NAME: 127.0.0.1
09:57:46 INFO Server[614928]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities
09:57:46 INFO Server[614928]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
09:57:46 INFO Server[614928]: REMOTE_ADDR: 127.0.0.1
09:57:46 INFO Server[614928]: SERVER_PORT: 80
09:57:46 INFO Server[614928]: QUERY_STRING: service=WMS&request=GetCapabilities
09:57:46 INFO Server[614928]: REQUEST_METHOD: GET
09:57:46 INFO Server[614928]: HTTP_ACCEPT: */*
09:57:46 INFO Server[614928]: HTTP_USER_AGENT: Lizmap
09:57:46 INFO Server[614928]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
09:57:46 INFO WfsOutputExtension[614928]: requestReady ran in 0.0s
09:57:46 INFO Server[614928]: REQUEST:GetCapabilities
09:57:46 INFO Server[614928]: SERVICE:WMS
09:57:46 INFO Server[614928]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
Logged warning: Loading a file that was saved with an older version of qgis (saved in 0.0.0, loaded in 3.16.15-Hannover). Problems may occur.
09:57:46 WARNING Server[614928]: WMS capabilities document not found in cache
09:57:46 WARNING Server[614928]: Set WMS capabilities document in cache
09:57:46 INFO WfsOutputExtension[614928]: responseComplete ran in 0.0s
09:57:46 INFO Server[614928]: Request finished in 39 ms
09:57:46 INFO Server[614928]: ******************** New request ***************
09:57:46 INFO Server[614928]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json?
09:57:46 INFO Server[614928]: Environment:
09:57:46 INFO Server[614928]: ------------------------------------------------
09:57:46 INFO Server[614928]: SERVER_NAME: 127.0.0.1
09:57:46 INFO Server[614928]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi/lizmap/server.json
09:57:46 INFO Server[614928]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
09:57:46 INFO Server[614928]: REMOTE_ADDR: 127.0.0.1
09:57:46 INFO Server[614928]: SERVER_PORT: 80
09:57:46 INFO Server[614928]: QUERY_STRING:
09:57:46 INFO Server[614928]: REQUEST_METHOD: GET
09:57:46 INFO Server[614928]: HTTP_ACCEPT: */*
09:57:46 INFO Server[614928]: HTTP_USER_AGENT: Lizmap
09:57:46 INFO Server[614928]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
09:57:46 INFO WfsOutputExtension[614928]: requestReady ran in 0.0s
09:57:46 INFO Server[614928]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
09:57:46 INFO Server[614928]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/wfs3'
09:57:46 INFO Server[614928]: Trying URL path: '/cgi-bin/qgis_mapserv.fcgi/lizmap/server.json' for '/'
09:57:46 WARNING [614928]: Service  is not registered
09:57:46 WARNING Server[614928]: <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
 <ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
</ServiceExceptionReport>

09:57:46 INFO WfsOutputExtension[614928]: responseComplete ran in 0.0s
09:57:46 INFO Server[614928]: Request finished in 0 ms`

**Comment by josemvm** [comment]
@Cww7 for apache web server you must add `FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS 1`

**Comment by Gustry** [comment]
`1` or `True` is the same.
But your plugin is not starting, check file permissions (and user owner).

**Comment by Cww7** [comment]
@Gustry  Thanks a lot !! 
The lizmap plugin didn't belong to www-data.

👍

**Comment by Gustry** [comment]
How did you install it @Cww7 ? Did you use https://pypi.org/project/qgis-plugin-manager/ I'm planning to add a warning with the current user when using this CLI tool when installing a plugin.

**Comment by Gustry** [comment]
FYI https://github.com/3liz/qgis-plugin-manager/blob/master/README.md#list

The next version of qgis-plugin-manager will show the folder owner and file rights in the table.

**Comment by Cww7** [comment]
@Gustry Yes, I used the qgis plugin manager.
Good idea to show these informations in the table.

**Comment by ocelot73** [comment]
With nginx+spawn-fcgi combo, where It It better to insert qgis_server_lizmap_reveal 1 ?
Maybe i did something wrong but setting It as environment variabile in nginx configuration file or in qgis-server.service file, server information shows up...
Can you writer some examples for dummies?
Thanks

**Comment by Gustry** [comment]
It's the same as QGIS Server environment variables : https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables
