### ISSUE TITLE
[Bug]: Error 403 on demo project Montpellier

### ISSUE THREAD

**Issue by JustineLou** [3liz/lizmap-web-client#2758]
### Description
Hello,
I followed the documentation to install Lizmap but I encounter difficulties when installing Lizmap Web Client. I can access to the Lizmap interface but :
- When I go to http://localhost/webgis/index.php, I don't see the demo
- When I go to http://localhost/webgis/index.php/view/map/?repository=montpellier&project=montpellier, I have "_403 - Forbidden : You don't have permission to access this resource_."
- When I go to "http://localhost/webgis/index.php", I have the following message "_Vous n'avez pas les droits pour voir ce répertoire de cartes._" ( meaning "You don't have the permission to see this map directory")
I already checked the .htaccess and the httpd-vhost.conf. Everything seems ok. 

Here my Apache log : 
```
The 'Apache2.4' service is restarting.
Thon Feb 07 17:27:06.662789 2022] [mpm_winnt:notice] [pid 22120:tid 592] AH00424: Parent: Received restart signal -- Restarting the server.
[Mon Feb 07 17:27:06.918810 2022] [ssl:warn] [pid 22120:tid 592] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Mon Feb 07 17:27:06.918810 2022] [mpm_winnt:notice] [pid 22120:tid 592] AH00455: Apache/2.4.52 (Win64) mod_fcgid/2.3.10-dev OpenSSL/1.1.1m configured -- resuming normal operations
[Mon Feb 07 17:27:06.918810 2022] [mpm_winnt:notice] [pid 22120:tid 592] AH00456: Apache Lounge VS16 Server built: Dec 17 2021 10:17:38
[Mon Feb 07 17:27:06.918810 2022] [core:notice] [pid 22120:tid 592] AH00094: Command line: 'C:\\webserver\\Apache24\\bin\\httpd.exe -d C:/webserver/Apache24'
[Mon Feb 07 17:27:06.937813 2022] [mpm_winnt:notice] [pid 22120:tid 592] AH00418: Parent: Created child process 9624
[Mon Feb 07 17:27:07.692868 2022] [ssl:warn] [pid 9624:tid 524] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Mon Feb 07 17:27:07.716870 2022] [mpm_winnt:notice] [pid 9624:tid 524] AH00354: Child: Starting 64 worker threads.
[Mon Feb 07 17:27:08.676956 2022] [mpm_winnt:notice] [pid 22168:tid 548] AH00364: Child: All worker threads have exited.
[Mon Feb 07 17:27:17.147011 2022] [fcgid:error] [pid 22168] FastCGI process 1220 still did not exit, terminating forcefully
[Mon Feb 07 17:27:17.147011 2022] [fcgid:error] [pid 22168] FastCGI process 26620 still did not exit, terminating forcefully

```
### Environment

 - Lizmap version: lizmap-web-client-3.4.8
 - QGIS Server FULL version: 3.16.16-1 LTR
 - QGIS Desktop FULL version: 3.16.16-1 LTR
 - OS (Windows, Linux, MacOS, Android…): Windows 10
 - Browser (Firefox, Chrome…): Chrome
 - PHP version : 7.3.21
 - Apache version : Apache24
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? No
<img width="506" alt="droit-lizmap" src="https://user-images.githubusercontent.com/71087008/152833693-00c22cca-c380-4313-acbb-31398ba43388.PNG">

**Comment by Gustry** [comment]
Hi,

> Lizmap version: lizmap web client 3.1.12

Can you confirm which version did you try to install ?
3.1.12 is very old and unmaintained. How and where did you read this version number ? For curiosity, to know where to update.

**Comment by JustineLou** [comment]
Hi! Indeed, I made a mistake. I'm using lizmap-web-client-3.4.8!

**Comment by Gustry** [comment]
Ok.
Does it work with another home made project ?

**Comment by nboisteault** [comment]
Hi!
If you're not afraid to use Docker you can try these procedures which are easier for Windows users : 
- To test Lizmap : https://gist.github.com/nboisteault/18fb47123e1ef42d1d97aa6a5ee6682e#file-test_lwc_with_docker-md
- For production : https://github.com/3liz/lizmap-docker-compose

**Comment by laurentj** [comment]
Hi,

> I have the following message "Vous n'avez pas les droits pour voir ce répertoire de cartes." 

it seems you don't set rights in the administration page of projects ("Gestion des cartes").
