### ISSUE TITLE
popup - compact/explode tables

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2759]
### What is the bug?

it's a regression on popup compact table

### Steps to reproduce the issue

.

### Versions

3.5.1-pre.5093

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

all

**Comment by aeduard** [comment]
Can you elaborate the bug? The compact/expand feature in pop-up is not working with version 3.5.1? I just thought to migrate my servers to this version from 3.4.x, but it is a must have feature for us.

**Comment by ygorigor** [comment]
@aeduard in LWC 3.5 the button was removed

**Comment by aeduard** [comment]
@ygorigor Thank you. It is planned to put it back? Do I understand correctly, it's planned for version 3.5.2?

**Comment by nboisteault** [comment]
Yes, I'll take a look soon.

**Comment by josemvm** [comment]
hi @nboisteault can you take a look at this issue please?

**Comment by josemvm** [comment]
gentle ping M. @nboisteault :disappointed:

**Comment by nboisteault** [comment]
Hi @josemvm @ygorigor @aeduard 
Could you test https://github.com/3liz/lizmap-web-client/pull/3215 and give me your feedback please?

**Comment by ygorigor** [comment]
Hi @nboisteault. I tested it. The button is back and is working.
