### ISSUE TITLE
adding a webaddress to the information page

### ISSUE THREAD

**Issue by ilamarengo** [3liz/lizmap-web-client#276]
hello,

i am using lizmap3 and i have noticed that once the qgis project is published online there is an icon for information "i". by clicking on it a new window opens and i can recognise the information i provided in qgis when setting the OWS page of the project.
I tried to replace the http://myserverIP/cgi-bin/qgis_mapserv.fcgi with a url that links to another webpage online and with surprise i noticed that the project can still be published. 
Now it is actually correct or a bug?
Because i had thought that in the OWS page of QGIS it was compulsory to have 
http://myserveIP/cgi-bin/qgis_mapserv.fcgi in order to make the project available online.

Is there anyone able to clarify it?

**Comment by rldhont** [comment]
Hi @ilamarengo,

You don't have to specify http://myserveIP/cgi-bin/qgis_mapserv.fcgi in the OWS project page to make the project available online.

The OWS project page is for specifying OWS metadata or some OWS restriction. If you have other question about QGIS Server project configuration, the QGIS community can probably helps you.

If you think, Lizmap has some lacks about metadat reopen this issue.

Thanks
