### ISSUE TITLE
Postgresql server version 14 compatibility

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#2764]
### Description
I haven't found information in documentation: Is latest LWC v.3.5.1 compatibile with latest Postgresql v14 ?
Should I upgrade my PG server from v11 to v14 ?

### Environment
 - Lizmap version: 3.5.1
 - QGIS Server FULL version: 3.16.16
 - QGIS Desktop FULL version: 3.16.16
 - OS (Windows, Linux, MacOS, Android…): Linux Ubuntu 18.04
 - Browser (Firefox, Chrome…): Firefox
 - Lizmap admin information (users, logs…) stored into Sqlite (default)

**Comment by ygorigor** [comment]
@ocelot73 I use PostgreSQL 14 with LWC 3.5 and I have no issues
