### ISSUE TITLE
JSON in dataviz

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#2767]
### Description
I can't manage to override the default graph parameters in Dataviz Layout. I have a scatter plot generated form 1:N relation, without any aggregation. The graph is displayed as filtered in the parent layer's popup.
Example:
`{"xaxis": {"title": {"text": "Any text"}}}`

I've also tried the sample codes from the lizmap [docs page](https://docs.lizmap.com/current/en/publish/lizmap_plugin/dataviz.html#json-layout).

When displaying the graph from the main dataviz panel, it works. A similar issue was raised in august 2021 in the lizmap mailing list by Immo Blecher.

### Environment

 - Lizmap version: 3.4.6
 - QGIS Server FULL version: 3.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.4
 - Browser (Firefox, Chrome…): Opera

**Comment by Gustry** [comment]
Linked to #2687 ?

**Comment by rldhont** [comment]
#2897 has been merged in release_3_5, the issue will be fixed when the backport to release_3_4 will be merged.
