### ISSUE TITLE
attribute table -  doesn't export when a selection is active

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2770]
### What is the bug?

as this comment https://github.com/3liz/lizmap-web-client/issues/2715#issuecomment-1031376587 by @rldhont 

_It is a regression in Lizmap, before 3.4.8 it was using EXP_FILTER and BBOX, now it uses FEATUREID instead of EXP_FILTER but FEATUREID and BBOX cannot be used in the same WFS request_

### Steps to reproduce the issue

make a selection in attribute and try to export to all formats

### Versions

 Lizmap Web Client : 3.4.9
 Lizmap plugin : 3.7.2
 QGIS Desktop : 3.16.16

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

97

**Comment by rldhont** [comment]
This issue has been fixed for Postgres Layer by this PR https://github.com/3liz/lizmap-web-client/pull/2928

**Comment by josemvm** [comment]
@rldhont thanks! 👍
