### ISSUE TITLE
filter user by poligon - weird zoom behavior

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2772]
### What is the bug?

when we have a filter by polygon layer and try a deep `zoom by rectangule` over visible features, the `zoom in` takes a weird behavior...
after, we can try to `zoom in` several times but it doesn't work as expected.

### Steps to reproduce the issue

try a deep `zoom by rectangule` over visible features, and `zoom in`, `zoom in`...

### Versions

 Lizmap Web Client : 3.5.1
 Lizmap plugin : 3.7.2
 QGIS Desktop : 3.16.16

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

97

**Comment by Gustry** [comment]
> the zoom in takes a weird behavior...

What do you mean by "weird behavior" ?

Did you set a proper primary key, not int8 for instance ?
You check logs in the plugin when saving the CFG about invalid primary keys if there is any ?
