### ISSUE TITLE
[Bug]: ign-photo basemap printing

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#2782]
### What is the bug?

Ign-photo basemap printing is not working with the print button, while the other basemap are all printed (osm, ign-plan, ign-cadastral).

### Steps to reproduce the issue

1. In Qgis, add the IGN wmts layers from https://wxs.ign.fr/essentiels/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities
2. Rename these layers : ign-cadastral, ign-photo, ign-plan.
3. In the lizmap plugin, use the check box to hide these layers in legend in Lizmap
4. Activate the external baselayers ![image](https://user-images.githubusercontent.com/19794922/154422819-85a2830a-25b7-48b2-bfeb-c5b9dc4caf4a.png)
5. In Lizmap web client, click on the print button : all external baselayers work except ign-photo

### Versions

**Versions :**

* Lizmap Web Client : 3.5.1
* Lizmap plugin : 3.7.4
* QGIS Desktop : 3.16.15
* QGIS Server : 3.16.15

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

Debian 11

### Browsers

Firefox, Chrome

### Browsers version

chrome 98

**Comment by nboisteault** [comment]
@Cww7 How did you solve your problem?

**Comment by Cww7** [comment]
Nothing ! And now it's working !
Maybe the problem was on IGN' side ?

**Comment by nboisteault** [comment]
@Cww7 probably as IGN had some issues lately.
