### ISSUE TITLE
Service non disponible, message when trying to view project on web client

### ISSUE THREAD

**Issue by georgios-antoniadis** [3liz/lizmap-web-client#2787]
Hi,

I am having issues viewing my project online through the Lizmap web client
Although there are no issues raised during setting up (through the QGIS desktop application plugin and project properties) upon viewing the project through the lizmap web client I am getting a 'Service non disponible' message and the page is stuck at loading.

Upon reviewing other similar issues I have not seen anything that matches my situation (although I am not sure how I can view the qgis-server logs, a hint about that would be helpful too).

I have tried fixing the extends of my project, and it seems like it is not a broken layer issue either, since I have tried loading a project that only contained an open street map, and it still did not work.

Thank you in advance for your time!

==========================================
System configuration:

 - Lizmap version: 3.5.1
 - QGIS Server FULL version: 3.16.16
 - QGIS Desktop FULL version: 3.16
 - OS (Windows, Linux, MacOS, Android…): Ubuntu 20.04
 - Browser (Firefox, Chrome…): Firefox

**Comment by arno974** [comment]
Hi,

It's difficult to give you a proper answer without additional information. Most of the time (at least in my case), this was related to my layers (incorrect rights, layer missing, etc.).

To help you to understand what is wrong, my best advice will be to enable QGIS Server log output (for example in your site-available file if you are using Apache):
```
FcgidInitialEnv QGIS_SERVER_LOG_LEVEL "0"
FcgidInitialEnv QGIS_SERVER_LOG_STDERR "1"
```
Also, while it's not an ideal solution, you could also add the QGIS_SERVER_IGNORE_BAD_LAYERS parameters to your  web server configuration file. If your problem is related to a bad layers, at least your project will be loaded.

`FcgidInitialEnv QGIS_SERVER_IGNORE_BAD_LAYERS "1"`

**Comment by Gustry** [comment]
I agree with @arno974 
If you are really using LWC "3.5.1", please have a look at the "administration panel", then "Server information", check that the QGIS Server table is working properly first before trying with a Lizmap project.

**Comment by georgios-antoniadis** [comment]
First of all I would like to thank you both for your recommendations and I would also like to apologise for replying late. Here are a few updates since the last time I posted. 

1) I upgraded my lizmap plugin from the QGIS interface (I now have version 3.7.1 installed)
2) In the administration panel under 'Server Information' I get the following: 

QGIS Server

QGIS Server is not correctly installed in your server or the URL for OGC requests given in Lizmap configuration is not correct.

We cannot get the details about your QGIS Server installation (version, plugins, etc.).
Either the version of the installed QGIS Server is under 3.10, or the Lizmap plugin is not detected in your server, or is installed with a version under 3.7.0. Please upgrade QGIS Server to minimum 3.10 and install or upgrade the Lizmap plugin to minimum 3.7.0 by reading the documentation about the environment variable https://docs.lizmap.com/current/en/install/pre_requirements.html 

3) I have followed @arno974 instruction and have updated my "default-ssl.conf" file to have these new variables.

So, I am currently following what the message under 'Server Information' says and I will get back to you with any further updates.

PS. My layers seem to be working fine since there are no error logs under the 'Log' tab of the plugin as well as 'Test configuration' under 'QGIS server' gives a 'Project is valid' message.

**Comment by arno974** [comment]
Regarding the error message, QGIS Server seems to be not installed.
Have you followed the documentation and installed the qgis-server package ? 
If so, it is maybe related to your configuration. After the installation, you have to configure your webserver (Apache or Nginx) to use the fcgi mapserv file. That means you will also have to install the FastCGI interface depending on your webserver.

If both are installed, you can then test your qgis-server installation using this URL (you will have to adapt the URL and the path to your project) :
http://your-url/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=path-to-your-mapfile

If it works you can now test in Lizmap. Be aware that in the administration section (Administration > Lizmap Configuration > QGIS Server), you can specify the WMS server URL.

**Comment by georgios-antoniadis** [comment]
So, after typing this url I get:
Not Found

The requested URL was not found on this server.
Apache/2.4.41 (Ubuntu) Server at localhost Port 80

I guess this means it works but there is something going on with the url. I have also configured it to work with Apache and have installed FastCGI.

qgis-server seems to be installed since trying the command "sudo apt install qgis-server" prints:
qgis-server is already the newest version (1:3.16.16+32focal).

I am currently checking my configuration again.

**Comment by arno974** [comment]
Okay, could you please share your virtual host config file ?

**Comment by georgios-antoniadis** [comment]
This is what's in it: 

<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog /etc/apache2/logs/error.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet


I would also like to ask you, just in case, what would be a reason for a layer to cause lizmap to fail. Messages like 'Service not disponible' or 'Service not responding'. I have made sure that they match the project's projection, that there are not errors in test configuration, no 400 error in log.

**Comment by arno974** [comment]
The problem is you did not configured your apache server to handle request to your qgis server.
A good starting point is the official doc :
> https://docs.qgis.org/3.16/en/docs/server_manual/getting_started.html#apache-http-server

**Comment by georgios-antoniadis** [comment]
Alright, so it turns out I hadn't configured a particular file during the initial setup, namely "qgis.demo.conf"
I followed the instructions and now the file is in the location it should be.

Typing in the browser:
"http://qgis.demo/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities" 
now gives me:
" This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServerException>
Project file error. For OWS services: please provide a SERVICE and a MAP parameter pointing to a valid QGIS project file
</ServerException>" 

which as I read on another similar issue means that now the server is functioning properly. 

However, the issue is still there.... 

A few more details on how I have setup my plug-in and my QGIS project:

- The url I use is: http://192.168.1.111:80/lizmap
- I get a 'like emoji' as an icon under the 'action' tab
- Test launch under QGIS server in project properties gives me zero errors
- The only layer in my project currently is OSM
- The project is stored in a very basic directory e.g. home/user/desktop/
- I do not have more than one CRS 
- The extend for the layer is imported from the project properties
- The extend in project properties is imported from the canvas 

What is more, I have setup /etc/hosts to point to the correct IP for localhost, the same one that appears under settings>network in my machine

**Comment by Gustry** [comment]
Before trying with a project, please see first my answer : https://github.com/3liz/lizmap-web-client/issues/2787#issuecomment-1044519546

**Comment by georgios-antoniadis** [comment]
The page still shows:

Version | 3.5.1
-- | --
2022-02-08

QGIS Server

QGIS Server is not correctly installed in your server or the URL for OGC requests given in Lizmap configuration is not correct.
      
We cannot get the details about your QGIS Server installation (version, plugins, etc.).
        
Either the version of the installed QGIS Server is under 
3.10, or the Lizmap plugin is not detected in your server, or is 
installed with a version under 3.7.0. Please upgrade QGIS Server to 
minimum 3.10 and install or upgrade the Lizmap plugin to minimum 3.7.0 
by reading the documentation about the environment variable 
https://docs.lizmap.com/current/en/install/pre_requirements.html</i>
            
I have checked and both my qgis-server and qgis desktop installations are in the latest long-stable versions. 

However, "/usr/lib/cgi-bin/qgis_mapserv.fcgi" gives me: 

Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
/usr/lib/python3/dist-packages/qgis/utils.py:888: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  mod = _builtin_import(name, globals, locals, fromlist, level)
Content-Length: 0
Location: http:/index.json
Server:  QGIS FCGI server - QGIS version 3.22.4-Białowieża
Status:  302

I am currently following the instructions in the link suggested in the "server information" tab

**Comment by georgios-antoniadis** [comment]
Sorry for being inactive for so long. For people that will find this issue in the future:

I could find the source of the problem, however I decided to use LizMap with Docker and everything worked perfectly with minimal effort and configuration. If you are familiar with Docker (even if you are not, I still believe it is worth the trouble of learning how to set it up) I highly recommended it. I have not yet found any issues with using Docker, and every functionality of regular LizMap seems to be working.
