### ISSUE TITLE
LDAP authentication on windows server 2016

### ISSUE THREAD

**Issue by zatzati** [3liz/lizmap-web-client#2794]
### What is the bug?

Hello,
I want to enable LDAP authentication in lizmap web client, I followed the steps in this documentation:
https://github.com/3liz/lizmap-documentation/blob/6326d359b6038007bb04ff25b9fe57a5040bf77e/source/install/linux.rst#ldap-authentication
When I try to log into the application, it gives me the following error:
This page is unavaible at this moment
localhost cannot currently process this request.
HTTP ERROR 500
lizmap error log shows nothing
when I restart apache, its error log shows the following error:
![image](https://user-images.githubusercontent.com/100346017/155513328-36790e92-3792-4115-966a-37c255bf11c0.png)
and when I execute the command: php scripts/script.php on the command prompt, it shows this error:
   [1024]  Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated  C:\Web\lizmap\lib\jelix\core\jConfigCompiler.class.php       454
![image](https://user-images.githubusercontent.com/100346017/155513532-0e81c47d-2a30-4ab0-a2e0-2fe440a830f8.png)

can you help me to solve these errors and enable ldap authentication
Thank you!

### Steps to reproduce the issue

1. Installation of LDAPDAO module (just unzipping the module from https://github.com/jelix/ldapdao-module and copying the unzipped directory ldapdao to C:\Web\lizmap\lizmap\lizmap-modules
2. adding the line: extension=php_ldap.dll in the C:\Web\php73\php.ini file and adding these two files: libeay32.dll and ssleay32.dll in the C:\Web\php73 folder
3. C:\Web\lizmap\lizmap/var/config/localconfig.ini.php: Added the following section:
    [modules]
    ldapdao.access=1
    jacl2.access=1
    jauth.access=2
    jauthdb.access=1

4. Run the installer : php /lizmap/lizmap/install/installer.php
![image](https://user-images.githubusercontent.com/100346017/155532410-5014e8fa-7313-4701-9cc1-d46627bba23c.png)

5. Several config files changes, as stated below: 
   5.1. in the /var/config/mainconfig.ini.php file, add the line: ldapdao.access=1 in the [modules] section
   5.2. /var/config/mainconfig.ini.php: In the section [coordplugins], added the line 'auth="authldap.coord.ini.php"'
  5.3. /var/config/profiles.ini.php: Added the following section :
   [ldap:ldapdao]
   hostname=ldap.hostname
   port=389
   adminUserDn="uid=,o=,dc=,dc="
   adminPassword="******"
   5.4. /var/config/admin/config.ini.php and /var/config/index/config.ini.php: In the section [coordplugins], changing the default value 'auth="index/auth.coord.ini.php"' to 'auth="authldap.coord.ini.php"'.

### Versions

QGIS Desktop 3.16.11
QGIS server 3.16
lizmap-web-client-3.3.16
php-7.3.26
apache-2.4.52

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.11

### Operating system

windows 10

### Browsers

Microsoft Edge

### Browsers version

Microsoft Edge Version 98.0.1108.56 (64 bits)

**Comment by Gustry** [comment]
The only resource I know about Lizmap on Windows is https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows
from @gioman.

>  lizmap-web-client-3.3.16

Please add your Lizmap server URL in the Lizmap QGIS plugin. It will tell you that Lizmap 3.3 is not supported anymore and not compatible with QGIS 3.16. (WMS/WFS hidden fields won't work etc)

**Comment by zatzati** [comment]
I installed the lizmap application, but I can't enable LDAP authentication.
the documentation you just posted does not contain LDAP authentication.
please how can I have the url of the Lizmap server?

**Comment by Gustry** [comment]
>  please how can I have the url of the Lizmap server?

https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#configuring-the-tool

**Comment by zatzati** [comment]
Thank you,
I just added the url: https://demo.lizmap.com/lizmap_3_3/ in the Lizmap QGIS plugin it gives me version 3_3 is no longer maintained. do i need another version?
can this cause LDAP authentication to fail?
Please, is there compatibility between apache, php and lizmap versions? because I already tried to install the latest version of lizmap 3.5 but it didn't work.

**Comment by ygorigor** [comment]
@zatzati did you looked here https://github.com/3liz/lizmap-web-client/issues/2276 ?

**Comment by laurentj** [comment]
Please upgrade at least to Lizmap 3.4 or 3.5. Lizmap 3.3 is not supported any more, and is not compatible with Qgis 3.16.

The ldapdao module is embedded into Lizmap 3.4/3.5, and is preconfigured. It should be easier to enable it.

You could then tell us if you still have some issues.

**Comment by zatzati** [comment]
Hello @laurentj 
I just installed lizmap 3.5 but I still have the same problem.
