### ISSUE TITLE
modified a layer but lizmap doesn't update

### ISSUE THREAD

**Issue by aliasatp** [3liz/lizmap-web-client#2803]
### Description
Hi all,
I have a QGIS project based on Sqlite layers. I published succesufully in Lizmap but when I change data in my features in QGIS, Lizmap doesn't update or better doesn't refresh the layers (symbols and data).
I tried to empty cache, modify settings using lizmap plugin but nothing happens.
Thanks

### Environment

 - Lizmap version: 3.5.1
 - QGIS Server FULL version: 3.22
 - QGIS Desktop FULL version: 3.22
 - OS (Windows, Linux, MacOS, Android…): windows 10
 - Browser (Firefox, Chrome…): firefox, edge
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Layers are stored in Sqlite

**Comment by anindiap** [comment]
hi i have same issue, how to fix this?
