### ISSUE TITLE
layer editing tool

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#282]
the layer editing tool doesn't work fine in lizmap 3.0 Beta4 version. it only can add new geometries...
can somebody confirm this problem?

**Comment by mdouchin** [comment]
Please try to publish the layer with WFS ( project properties / Server OWS / WFS capabilities / Check "publish" for the layer
We must add this new behaviour in the documentation

**Comment by josemvm** [comment]
the layer is published...

**Comment by mdouchin** [comment]
Ok, so we will need more information to know what is happening. Please give as much detail as possible : table structure ( number and type of primary key field(s) ), lizmap error message, lizmap logs / apache logs and postgresql logs  (only relevant parts, and no screenshot but prefer copy/paste)

**Comment by jancelin** [comment]
Same problem, I can edit but update and delete bug.
on screen:
 Lizmap cannot get this feature data via WFS
on error.log: 
 warning 2016-04-06 14:48:33     [2]     file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?featureid=inventaire_gps.7061&amp;geometryname=none&amp;map=%2Fhome%2Fechant_messicol.qgs&amp;outputformat=GeoJSON&amp;request=GetFeature&amp;service=WFS&amp;typename=inventaire_gps&amp;version=1.0.0): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error^M
        /var/www/websig/lizmap/modules/lizmap/classes/lizmapProxy.class.php     87

**Comment by mdouchin** [comment]
It seems this is a QGIS Server bug and not a lizmap one. Any project you can share so that we can test it ?

**Comment by jancelin** [comment]
check your mail

**Comment by jancelin** [comment]
it seems that creating a new project, make cancel the bug.

All my layers now works in insert, update and delete.

**Comment by josemvm** [comment]
yes, i confirm it.
however, saving the old projects with QGIS last version (2.14.1) doesn't solve the problem.

**Comment by jancelin** [comment]
find !!!
These are the data joins on layer who causes the bug.

Can you test @josemvm ?

**Comment by josemvm** [comment]
hi jancelin,

i 've projects with no tables joins between the layers and i can´t edit it too.

**Comment by mdouchin** [comment]
we really should move this discussion in qgis-dev mailing list, or better create an issue in http://hub.qgis.org , as it concerns QGIS Server and not Lizmap

**Comment by jancelin** [comment]
ok

**Comment by josemvm** [comment]
but it's possiblee to edit the same projects with old lizmap versions. this problem arose with last lizmap updates...

**Comment by mdouchin** [comment]
@josemvm  Yes, because since Lizmap 3.0beta4, we ask QGIS Server for the feature content via WFS anytime you need to modify it. But here QGIS Server returns an error, so Lizmap cannot access the feature data and returns an error.

**Comment by josemvm** [comment]
Ok Michael Douchin, i'm sorry but i don´t understand so if the lizmap works exclusively with QGIS Server, how it's possible to implement these features before QGIS supports them?

**Comment by gioman** [comment]
@josevm what @mdouchin said is that since LM beta4 changed the way editing is handled and this apparently exposed a bug in qgis server that was previously unnoticed.

**Comment by josemvm** [comment]
hi Giovanni, thanks for your explanation.

first of all, thanks and congratulations to René-Luc D'Hont and Michaël Douchin and to all the other contributors for your great work (LizMap web Client Project)!!!

on this issue, in my opinion it would be more prudent to implement these new features after solved the bug in qgis server. so now it's impossible to work on edition with this last LM version.

thanks again

**Comment by rldhont** [comment]
Hi @josemvm, firstly thanks to test Lizmap Web Client Beta and to find this QGIS Server issue.

We discover this issue because we would like to permit the edition of layer with textual primary key field(s) 1ce5838148d656ab266dbd7e6d970826410a4f1c
This is an important enhance because QGIS permit it.

To fixe this QGIS Server issue, we need to have more information about your QGIS project:
* with which QGIS version did you create it ?
* did you update it with QGIS 2.14 ?
* did you have this trouble with all the other lizmap features that used WFS: locate by layer, tables, etc?

**Comment by josemvm** [comment]
hi @rldhont,

- all of my projects were created with QGIS 2.8.1-Wien version and laters.
- after I tried to solve the problem, without success, by updating the same projects with QGIS last version (2.14.1).
- **if i create a new project with QGIS 2.14.1 with the same layers, these layers auto loads the matching styles stored in PostgreSQL Server and so, in this way, the problem remains.**
- if i create a new project with same layers but clears (without pre-stored styles) the layer editon tool works fine! this means that i need to recreate the projects with all its style settings.
- i didn´t detect any problems with other tools like locate by layer, attribute table and tooltip layers.

i hope this helps

**Comment by jancelin** [comment]
until the bug is resolved, we can put the old "edition.classic.php"

https://github.com/3liz/lizmap-web-client/blob/c6723273f3885ebd27b7188fcb8e4a7646f7c376/lizmap/modules/lizmap/controllers/edition.classic.php

works for me

**Comment by josemvm** [comment]
yes, i confirm. I had already restore a backup file too.

**Comment by rldhont** [comment]
Hi @josemvm and @jancelin, can you test my fix 4342bf7 ?

I need to fix the QGIS Server issue too.

Reopen if needed

**Comment by josemvm** [comment]
hi @rldhont,

I've tested your fix but the problem remains.

**Comment by gioman** [comment]
@josemvm have you tested with the patched version of QGIS server?

**Comment by josemvm** [comment]
no. do you know how i can get the patched version of QGIS server for ubuntu 12.04. LTS

**Comment by rldhont** [comment]
@josemvm to help you I need information about the layer that segfault QGIS Server WFS Request: datasource, virtual fields, filter, etc (qlr)

Can you test on QGIS Server, not in Lizmap, WFS GetFeature Request on this layer ?
* Default GetFeature Request (no filter, geometry, GML2)
* Add OUTPUTFORMAT=GeoJSON
* Add FEATUREID= take a value from default value

I need to know why your layer segfault qgis server. You can send more information to info[at]3liz.com

**Comment by josemvm** [comment]
check the mailbox, please.
