### ISSUE TITLE
Hi everyone, I have a problem with Lizmap 3.5 label layer

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#2825]
Hi everyone, I have a problem with Lizmap 3.5

In practice I have installed lizmap 3.5 on a webvps, with attached qgis server and qgis. Layer labels appear quietly in qgis and disappear inside the lizmap, each element is shown only with its own symbol and without nomenclature.
Anyone have any idea what this is due to?

Desktop environment: Xubuntu 20.04
Lizmap version 3.5
Qgis 3.24
Qgis.Server last by default >3

thank you

**Comment by nboisteault** [comment]
Lizmap 3.5 is compatible with QGIS desktop and server 3.16 or 3.22.
https://github.com/3liz/lizmap-web-client/wiki/Versions#qgis-server-and-desktop

**Comment by Gustry** [comment]
Lizmap Web Client is not involved in the rendering of labels. It's **only** related to QGIS Server, especially if the symbology is working correctly.
Please double-check your QGIS Desktop, QGIS Server versions. Some issues similar because of old QGIS projects opened with newer version of QGIS Server.

I'm closing because this issue is not related to Lizmap.

**Comment by androidtv160987** [comment]
![image](https://user-images.githubusercontent.com/75124133/156783167-3746510a-7ea6-481d-bea9-f7203f2e093a.png)

**Comment by Gustry** [comment]
Ah ok you mean the legend.

So QGIS Server is rendering the legend correctly. So maybe QGIS Server can't access your data. (the symbology is coming from the QGS project.
So you must check if QGIS Server can access the data (path on the disk, postgresql credentials etc)

**Comment by androidtv160987** [comment]
Quindi potrebbe essere un problema di autorizzazioni del server qgis, non
ci avevo pensato proverò a cambiare i permessi. Ho effettuato l'accesso
come utente root

Il giorno ven 4 mar 2022 alle ore 15:55 Étienne Trimaille <
***@***.***> ha scritto:
