### ISSUE TITLE
Issue/doubt about putting Lizmapo stack behind reverse proxy

### ISSUE THREAD

**Issue by Franc-Brs** [3liz/lizmap-web-client#2830]
### Description
Hi and thank you for this amazing repository!
I'm not sure if this is a lizmap or a web server issue, but since I usually am able to put up a  reverse proxy I open the issue, let me know if it's not in the "right place".
I tried to build the stack on a CENTOS 7.9.2009 as is it described here https://github.com/3liz/lizmap-docker-compose and everything works fine: I can reach the page in localhost:8090.
Since on this server I've got a working webserver (apache in this case) I tried to add a reverse proxy to localhost:8090/ and it works almost fine.
The problem is that when I navigate the project (the map) and I try to visualize the popoup it fails to load the resources and to perform the get call (or this is what I see in the console).
The localconfig.ini.php I added the the volume to be used in the container has the following lines (I also tried what was suggested in this issue but It shows the same behaviour https://github.com/3liz/lizmap-web-client/issues/1003):

```
[urlengine]
checkHttpsOnParsing = off
forceProxyProtocol = https
forceHTTPSPort = off 
```
After adding these lines I restart the container.
the reverse proxy configuration I use in the virtualhost is like this:

```
ProxyPass        /   http://localhost:8090/
ProxyPassReverse /   http://localhost:8090/
ProxyRequests     Off
ProxyPreserveHost On
<Proxy http://localhost:8090/*>
   Order deny,allow
   Allow from all
</Proxy>
```
### Environment

I work on Docker (Docker version 20.10.12, docker-compose docker-compose version 1.29.2) 

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.16 
 - OS (Windows, Linux, MacOS, Android…): LInux (centos 7.9.2009)
 - Browser (Firefox, Chrome…): Chrome

**Comment by nboisteault** [comment]
@dmarteau Do you have any hint?

**Comment by dmarteau** [comment]
I don't quite understand what is exactly the issue here: In the compose stack, lizmap is already behind a nginx reverse proxy and the   `localconfig.ini.php` proxy configuration is related to the nginx proxy ef the stack, 

So basically you are trying to put a reverse-proxy in front of another reverse proxy. 

IMHO, a  better approach would be to customize the the nginx configuration to achieve what you want (i.e moving to https)

**Comment by Franc-Brs** [comment]
Hi @nboisteault and @dmarteau and thank you for your answer and your advice.
Yes, I agree that putting a reverse proxy in front of another is not the best solution, I only tried since it was the fastest thing I could try and it seemed to work just fine except for the popup, I was wondering if I was not taking into account something.
I will add the https configuration then, thanks!
For what concern my doubt you can close this issue.
