### ISSUE TITLE
Temporarily deactivate a user

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#2835]
Hi,

It might be more related to jelix, but It could be interesting to have an option to temporarily deactivate a user access. For example, if I don't want to let the user connect to the platform anymore but I don't want to delete his access. Then, if it is necessary I can reactivate the user and he connect to the platform.

**Comment by laurentj** [comment]
Hi,

This feature already exists. Go into the user management page, edit the profile of the targeted user, and change his status to `deactivated`.
