### ISSUE TITLE
printing orthophotos which are not by IGN

### ISSUE THREAD

**Issue by InnovPlantProtect** [3liz/lizmap-web-client#2838]
### Description

hello! 
Is there a way to print an orthophoto which is not by IGN? the documentation is very clear but it only describes what to do if the QGIS project has IGN orthophotos. How about orthophotos from other countries and providers?

### Environment

 - Lizmap version: 3.4.4
 - QGIS Server FULL version: >3.0
 - QGIS Desktop FULL version: 3.16LTR
 - OS (Windows, Linux, MacOS, Android…): Linux
 - Browser (Firefox, Chrome…): Firefox/Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL? Postgresql

**Comment by arno974** [comment]
Hi,

Is the raster stored locally or are lizmap accesses it remotely (WMS, COG) ?
In the first case, you should have no difficulty to print your map.
In the second case, it really depends on the provider.

**Comment by InnovPlantProtect** [comment]
@arno974 the raster is accessed remotely via WMS so it depends on the provider. I didn't know it hence thanks a lot for your reply!

**Comment by arno974** [comment]
If its a simple WMS, you can simply add it to your map. Then, when you will print your map, it will print all the layers selectionned by the user.

**Comment by InnovPlantProtect** [comment]
@arno974 what you suggest does not work with our WMS. Thus, based on your previous reply i thought that the provider somehow had protected the orthophoto. Have you tried to add a WMS raster in Lizmap and print it?

**Comment by arno974** [comment]
Yes, I've several project that used external WMS and the print feature works perfectly. It might be related to your provider.
