### ISSUE TITLE
[Question]: Problems showing WMS layer with a Base Layer Set

### ISSUE THREAD

**Issue by gonzalezhidalgorafael** [3liz/lizmap-web-client#2840]
### What is the question?

Hello, thanks for your help.

I have an installation of Qgis Server + Lizmap in ubuntu server and when i try to show a WMS layer with the option "Get Images directly from WMS Server" the layer does not show when i have configured a base layer (Google hybrid for example).

Curiously, the WMS layer shows with no matter when i have no base layer configured.

I need to activate the option "Get Images directly from WMS Server" in order to get the layers legends showed.

Could you help me if you know what it happens?

Thanks.

### Versions

**Versions :**

* Lizmap Web Client : 3.4.1
* Lizmap plugin : 3.7.4
* QGIS Desktop : 3.22.4
* QGIS Server and plugins unknown status

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Ubuntu 18.04

### Browsers

Firefox, Chrome

### Browsers version

Chrome 90

### Relevant log output

```shell
No relevant log output
```

**Comment by nboisteault** [comment]
Hi,
Does the WMS Server can send tiles in EPSG:3857?

**Comment by Gustry** [comment]
> Lizmap Web Client : 3.4.1

Keep in mind that this version is very old, more than one year old.
https://github.com/3liz/lizmap-web-client/releases/tag/3.4.1

Now 3.4.10 https://github.com/3liz/lizmap-web-client/releases/tag/3.4.10

**Comment by gonzalezhidalgorafael** [comment]
Yes i know,
Now a have 3.4.9 and i am going to update to 3.8.10 very soon.
Thanks for the feedback.

**Comment by gonzalezhidalgorafael** [comment]
Hi,
Thanks for your help.
I solved the problem, it seemed to be an issue related with the versions of
qgis, qgis server and lizmap.
I am going to close the question.
Thanks you very much.
