### ISSUE TITLE
Remove space before punctuation mark

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#285]
e.g. " ?"; this is AFAIK a French-only convention, should not be used in other lang.
The same applies throughout (plugin, docs).

**Comment by rldhont** [comment]
Can you report it to lizmap-locales repository ?

**Comment by pcav** [comment]
Isn't it an upstream issue?

**Comment by pcav** [comment]
For instance, in:
https://github.com/3liz/lizmap-locales/blob/master/web-client/pot/admin.pot#L215
is from en strings, not an issue with translations.
