### ISSUE TITLE
[Bug]: authentication for wms not working

### ISSUE THREAD

**Issue by FPaulsen** [3liz/lizmap-web-client#2850]
### What is the bug?

authentication for wms not working.
after enter Username / Passwort the popup ask again for username / password

wms without authentication is working

### Steps to reproduce the issue

using Lizmap wms / wmts on Browser / QGIS etc.

### Versions

Lizmap .3.5.1
QGIS - Server (1:3.16.16+28bionic)

Ubuntu 18.04 with pesk Version 18.0.42 Update Nr. 1

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 18.04

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Browsers version

all

**Comment by arno974** [comment]
Hi,

You are on the Lizmap Web Client Github. Your question should be related to the client not to QGIS.
Regarding your question this is not related either to Lizmap but more about QGIS.
Are you sure about the credentials ?
If the problem persists you should probably ask the question on the QGIS Github project.
