### ISSUE TITLE
Add length, area when user draw/edit on the map

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#2858]
Would it be possible to add some information about the measure of the segments (length, area) when a user draw or add a feature ?
This is possible with recent OpenLayers version (https://openlayers.org/en/latest/examples/measure.html) but I don't know with the one used by Lizmap.

![image](https://user-images.githubusercontent.com/425243/159648175-bc7e64c6-513e-4e0b-ad8c-5591cb4427a7.png)

**Comment by mdouchin** [comment]
Have you looked at the "Digitization" tab in the editing panel ? It should show the length and angle of the current segment. Not sure the area is shown though cc @nboisteault

**Comment by arno974** [comment]
I've never noticed this digitization tab, thanks (I confirme that the area is not displayed) ! But this only partially meets the initial demand as it's only available when using the edit functionnality. If the user want to draw on the map he doesn't have the information about the length/area.
Also, I think (IMHO) that having the area and length information directly on the map it's probably more user friendly.

**Comment by nboisteault** [comment]
Yes we have to remake this tool with OpenLayers 6 but we need fundings. Would you be interest in funding this development?

**Comment by Gustry** [comment]
There is some progress about measure indicators https://github.com/3liz/lizmap-web-client/pull/3283
