### ISSUE TITLE
Baselayers - Choose active baselayer at map startup

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#286]
Hi,

Thank you very much for these new improvements!

there is a particular case that doesn' t avaiable in baselayers drop down list: group as layer/base layer.
in this case only appears all the individual layers that make up the group.

**Comment by rldhont** [comment]
Can you provide some screenshots ? thanks

**Comment by josemvm** [comment]
the problem that i reported, it relates to the using of the empty spaces in the name of the baselayers group.

now, after trying different combinations of the baselayers i can I present the summary of my experiences with Montpellier - Transports Project (montpellier.qgs) :

- OpenStreetMap group - everything works fine.

- Google group

   1. problems when choosing Streets or Terrain with a empty baselayer at map startup. in this case the result is a large map in the background that doesn't respect the initial map extent.
   2. problems when choosing Streets or Terrain with any other map of this group as baselayer at map startup. in this case the choice of the baselayer map at map startup isn't respected.

- Bing map group - doesn't appears.

thanks

**Comment by rldhont** [comment]
Hi @josemvm thanks for these precisions.

Firstly, to see Bing map you need a key. Without this key, lizmap can't integrate bing maps.

Then for Google, I have some difficulties to reproduce your issues:
* If I have only one Google layers, I have no trouble with empty baselayer
* If I have more than one Google layers, I have the same issue
* Google layers does not respect startup choice

It seems than Google does not work like the other layers...

**Comment by josemvm** [comment]
hi @rldhont

have you tried to have a Google Streets or/and Google Terrain with a empty baselayer as startup choice?
