### ISSUE TITLE
Zoom level to "exact" values

### ISSUE THREAD

**Issue by royro** [3liz/lizmap-web-client#287]
Is ti possible to configure lizmap so that zoom levels are "round" values
like 10000 5000 2000 ...? this would lead to more standard scale values
on print outputs because now print scales are a bit odd, like 1:9028 rather
than 1:10.000

Thanks!

**Comment by rldhont** [comment]
It's not odd, it's Google Mercator scales and it's done to have the good information about scales.
If you want round scales, do not use external baselayers with ESPG:3857, Google Mercator, as CRS.

**Comment by pcav** [comment]
Please note that I have at least a project where even when using a blank baselayer, 3857 zoom levels are retained.

**Comment by royro** [comment]
Thanks ! So i'll try with a custom baselayer and no external.

**Comment by royro** [comment]
So I understand that if i want the map scale to
match the values in the print copy, when i use external baselayers (3857) I should
put the values used by google pseudo mercator i.e.

scale 2257 4514 9028 etc...

did i get it right?

thanks!

**Comment by nboisteault** [comment]
As @pcav said even if you choose the blank base layers, you can't zoom to exact values.
I think it is still the case today. I can open a bug request if confirmed or this issue could labeled with bug.

In case we use baselayer with predefined zoom levels and want different ones, is the use of 'fractionalZoom' as suggested [here](https://github.com/3liz/lizmap-web-client/issues/275) a valid option?

**Comment by rldhont** [comment]
We don't want to use fractionnalZoom because it will create some blurred on external layer and on WMTS layer in EPSG:3857.

The projection EPSG:3857 has defacto zoom levels and lizmap has to not be has the others.

**Comment by nboisteault** [comment]
I understand you don't want to use fractionnalZoom. Any thoughts concerning exact zoom values with blank base layer?

**Comment by rldhont** [comment]
In other CRS yes not in EPSG:3857

**Comment by nboisteault** [comment]
As we can't change CRS in lizmap web client, I guess we have to choose in our QGIS project a CRS different than 3857 and no other base layers than the blank one. Am I correct?

**Comment by royro** [comment]
From what I have experienced zoom is working properly as log as you know that
- if you use external baselayer with pseudo marcator you are stuck with pseudo marcator
 zoom values it is how it works, not lizmap fault
- what you set in qgis project is what you get, so you have to use your custom basemap
if you need round scale values
this is how i got it.
