### ISSUE TITLE
[Bug]: Lizmap web application does not start

### ISSUE THREAD

**Issue by andremano** [3liz/lizmap-web-client#2873]
### What is the bug?

After following the installation instructions from [https://docs.lizmap.com/3.5/en/install/linux.html](https://docs.lizmap.com/3.5/en/install/linux.html), when I try to access lizmap `mydomain/lizmap`, I get this:

```
<?php
/**
* @package   lizmap
* @subpackage lizmap
* @author    3liz
* @copyright 2011 3liz
* @link      http://3liz.com
* @license    Mozilla Public License : http://www.mozilla.org/MPL/
*/

require ('../application.init.php');
require (JELIX_LIB_CORE_PATH.'request/jClassicRequest.class.php');

checkAppOpened();

// Charge la configuration
jApp::loadConfig('index/config.ini.php');

// nouveau coordinateur, que l'on indique Ã  jApp
jApp::setCoord(new jCoordinator());

// Nouvel objet request, que l'on passe au coordinateur, pour traiter le routage.
jApp::coord()->process(new jClassicRequest());
```

I have repeated the installation procedure several times but I have no idea what can be causing this.

### Steps to reproduce the issue

My installation steps:

install packages
`sudo apt install xauth htop curl apache2 libapache2-mod-fcgid libapache2-mod-php7.4 php7.4-cgi php7.4-gd php7.4-sqlite php7.4-curl php7.4-xmlrpc python-simplejson software-properties-common php7.4-xml`

create directories for data
```
mkdir /home/data
 mkdir /home/data/cache/
 mkdir /home/data/ftp
 mkdir /home/data/ftp/template/
 mkdir /home/data/ftp/template/qgis
```

download and unzip lizmap
```
> wget https://github.com/3liz/lizmap-web-client/releases/download/3.5.2/lizmap-web-client-$VERSION.zip
> unzip lizmap-web-client-3.5.2.zip
```

create profiles.ini.php
`cp profiles.ini.php.dist profiles.ini.php
`

configure support for postgres (it works because the tables are created when i run installer.php
```
[jdb:jauth]
driver=pgsql
host=localhost
port=5432
database="your_database"
and so on...
```

set rights for www-data user
`lizmap/install/set_rights.sh www-data www-data
`
Create lizmapConfig.ini.php and localconfig.ini.php
```
cp lizmapConfig.ini.php.dist lizmapConfig.ini.php
cp localconfig.ini.php.dist localconfig.ini.php
```

Add demo project under the [modules]  section of localconfig.ini.php (btwis never installed after running installer.php)
`lizmap.installparam=demo`

Run the installer
`php installer.php`

restart apache just in case (apache is working as I can access my home page for example)
`service apache2 restart`

### Versions

Lizmap 3.24
Lizmap plugin 3.7.4
QGIS 3.24.1

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.24

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Version 99.0.4844.82

**Comment by andremano** [comment]
For some reason, I now can enter the admin panel, and change the default password,  but when I try to create a new repository or change any setting I get `Error 500. A technical error has occured. Sorry for this trouble.`

**Comment by laurentj** [comment]
Hi,

Your web server is not configured correctly. This is not a Lizmap issue. Read the log files of Apache, see what it says during its startup. It seems the configuration parameters related to the PHP fcgi handler are not good.
