### ISSUE TITLE
Function pregenerate cache not function[Bug]: 

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-web-client#2876]
### What is the bug?

Function pregenerate cache not function

### Steps to reproduce the issue

```
sudo php lizmap/scripts/script.php lizmap~wmts:capabilities -v montpellier montpellier
2022-03-27 06:02:01     [0]     The QGIS project  does not exist!       /var/www/lizmap-web-client/lizmap/modules/lizmap/lib/Project/Project.php  106

php lizmap/scripts/script.php lizmap~wmts:seeding -v -f montpellier montpellier bus EPSG:3857 12 14
2022-03-27 06:07:47     [0]     The QGIS project  does not exist!       /var/www/lizmap-web-client/lizmap/modules/lizmap/lib/Project/Project.php  106
```

### Versions

Lizmap 3.5.1

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.10

### Operating system

Ubuntu 18.4

### Browsers

Chrome

### Browsers version

90

**Comment by gisgogo** [comment]
yes
https://gisland.eu/mapserver/index.php/view/map/?repository=montpellier&project=montpellier

**Comment by Gustry** [comment]
We do manual testing of this tool before each release. The script was successful for 3.5.1 : https://github.com/3liz/lizmap-web-client/blob/master/tests/qgis-projects/tests/cache.md

The second command will fail if the first one is not successful as written in the documentation.

Maybe check file permissions ? I don't have idea.
