### ISSUE TITLE
Popup with layer cache enabled don't work

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#289]
Hello
I have LWC 3beta4 and LWC 3.12 on the same machine
Layers are simple points on postgis materialized view.
I made a new project with latest Lizmap Plugin.

If I enable cache for layers LWC 3b4 don't show popups.
A working icon turns without end
Same project with LWC 3.12 works.

If I set single tile all works as expected. Also rendering speed is super fast with single tile, really slow with cache enabled (metatile 5,5 png 16 bit).

**Comment by rldhont** [comment]
Thanks to review it
