### ISSUE TITLE
Tooltip stop button doesn't stop it

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#291]
once activated the tooltip it can't be disable by the user because the tooltip stop button only close the tooltip box but doesn't disable it

**Comment by mdouchin** [comment]
In last master, there is a "paintbrush" icon side to the little cross. You can disable the tooltip by cliking on it.
Do you think a more obvious way should be preferred, like a button under the layer combobox ?

**Comment by josemvm** [comment]
hi @mdouchin 

i'm testing the last master version and when i click the litle red cross it only close the tooltip box but doesn't disable it. if you move the mouse over the map, after close the tooltip box, the tooptip continues to get and show information about the geometries.

i think the most intuitive way for the user is disable the tooltip by clicking the litle red cross without a previsous click on the paintbrush.

**Comment by josemvm** [comment]
the tooltip doesn't work after using the layer editing tool...

**Comment by josemvm** [comment]
maximum number of layers = 5 (?)
