### ISSUE TITLE
Locate by layer don't work

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#292]
Hello
I'm using LWC both 3b4 and 2.11 on debian server, data on postgis 9.4.
Trying to add a "locate by layer functionality" (latest plugin) using multipolygons in the same CRS as my project (3857), locate layer published as wfs.
I can add it in plugin>tool>locate by layer and in LWC I have the dropdown list with names
Selecting a name nothing happens.
In LWC 2.11 the dropdown list appears but is empty.

If I add the same layer on TOC it is correctly represented..

Thanks
Pietro

**Comment by pieri70** [comment]
Just now I found it work, but in qgis I must leave the name as is in postgis for the layer to be used.
If I change the name in toc in qgis the locate by layer stop woking...

I found a similar behaviour with materialized views..

**Comment by pieri70** [comment]
And in lizmap 2.11 shows the perimeter of the selected feature to locate by, in LWC 3b4 only bounding box is shown if "display the geometry" is selected

**Comment by josemvm** [comment]
hi @pieri70 

#280

**Comment by pieri70** [comment]
Thanks @josemvm
I saw the display geometry problem, but the problem in changing layers name remains I think..

**Comment by rldhont** [comment]
Hi @pieri70 I think that you can find more information here:
* Identify layers by name leads to major configuration losses
which is lizmap-plugin issue https://github.com/3liz/lizmap-plugin/issues/53

Other point LWC 2.11 is not maintained. Regards.
