### ISSUE TITLE
Chart Plot Problem

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#2921]
### What is the question?

![image](https://user-images.githubusercontent.com/75124133/163235341-4475258a-c015-4367-a426-164a351b07bc.png)
Sorry these days I am admiring the many features of Lizmap and I ask several questions, I am a geek but without adequate training I am forced to make requests here. I don't understand why the report on the left is being loaded and the one on the right loads perfectly, what am I wrong? The example is based on the COVID.FR model distributed by 3liz on github.

### Versions

Ubuntu 20.04
3.16 Qgis
Windows 10
3.24 Qgis

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

Ubuntu 20-04

### Browsers

Firefox

### Browsers version

firefox 89

**Comment by Gustry** [comment]
You should have an error in the webbrowser console, or in the network request I guess.
