### ISSUE TITLE
Trouble on DataViz

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#2923]
### What is the bug?

When I set a scatter plot from Lizmap plugin 3.7.7 the result in LWC It's a line chart instead of a point dispersion chart

### Steps to reproduce the issue

1. set a scatter plot from Lizmap plugin 3.7;
2. insert a layout customization in layout (because I need to draw in log scale) ---> {"xaxis": {"autorange": true, "type": "log"}}
3. open Dataviz popup
4. I expect to see a dispersion points chart
5. a line chart appear
I attach screenshots 

1 - Dataviz Configuration  
![image](https://user-images.githubusercontent.com/12639444/163394705-2002c242-cb23-43e3-b19b-2a06c3fd00f1.png)

2 - Output in Dataviz popup on LWC (as in Master as in 3.4.10)
![image](https://user-images.githubusercontent.com/12639444/163395535-821bfbbf-07b6-45c9-81a1-4064af071f8a.png)

3 - the same data plotted in Dataplotly on QGIS 3.25 (what I expetted to see on also Dataviz)
![image](https://user-images.githubusercontent.com/12639444/163395678-69bb580d-aa79-486a-8695-96bbc3ded924.png)

### Versions

Versione di QGIS
3.24.1-Tisler
Revisione codice QGIS
c34a2726
Versione Qt
5.15.2
Versione Python
3.9.5
Versione GDAL/OGR
3.4.2
Versione PROJ
9.0.0
Versione database del Registro EPSG
v10.054 (2022-02-13)
Versione GEOS
3.10.2-CAPI-1.16.0
Versione SQLite
3.38.1
Versione PDAL
2.3.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.3
Versione QScintilla2
2.11.5
Versione SO
Windows 10 Version 2009

Questa copia di QGIS scrive messaggi di debug.

Plugins Python attivi
AutoLayoutTool
1.1
BivariateLegend
1.0.2
bulkvectorexportwithstyle
0.6
CalculateGeometry
0.6.4
coins
0.2
corrector_vector
0.3.1
DataPlotly
3.9
DigitizingTools
1.5.1
epmgis
3.0.25b
flexigis
0.1
GeometryShapes
0.7
Hotlink
0.8.6
HouseNumbering3
version 0.0.5
Label2Attr
1.0
label_connector
1.0
lizmap
3.7.7
mmqgis
2021.9.10
MzSTools
1.6
numerator
0.4
openlayers_plugin
2.0.0
OSMDownloader
1.0.3
pgtopoeditor
0.3.0
pg_raster_import
1.0.10
plugin_reloader
0.9.1
postgisQueryBuilder
2.0.1
postgis_geoprocessing
0.9
postgis_sampling_tool
1.5.1
qdraw
3.0.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
qgiscloud
3.4.2
QPackage
1.5
QuickMultiAttributeEdit3
version 3.0.3
QuickWKT
3.1
quick_map_services
0.19.29
QWeb
0.2.1
realcentroid
1.0.3
RenameField
0.1
shapetools
3.4.4
smooth_geometry
1.0
splitmultipart
1.0.0
StreetView
3.2
VectorMCDA
3.0.1
db_manager
0.1.20
processing
2.12.99

### Operating system

Windows 10 x64

### Browsers

Firefox, Chrome

### Browsers version

Chrome 100.0.4896.88

**Comment by rldhont** [comment]
@mdouchin how to override the plot config to display marker and not line ?

**Comment by Antoviscomi** [comment]
@rldhont thanks a lot for the answer

**Comment by nboisteault** [comment]
@Antoviscomi The second example might help you: https://docs.lizmap.com/current/fr/publish/lizmap_plugin/dataviz.html#other-customisation-with-javascript-scripts

**Comment by Antoviscomi** [comment]
@nboisteault I'll try it asap thanks

**Comment by Antoviscomi** [comment]
@nboisteault It Works! Thank you so much, so i close this issue
![Schermata del 2024-06-06 17-34-48](https://github.com/3liz/lizmap-web-client/assets/12639444/99bfcd80-2be0-4c71-842c-5454a38ca114)
