### ISSUE TITLE
[Bug]: Search not working if user is authenticated

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#2933]
### What is the bug?

PostgreSQL Search not working if user is authenticated.
Lizmap logfile: 

> Call to a member function getAppContext() on string	/var/www/lizmap-web-client-3.5.2/lizmap/modules/lizmap/classes/lizmapFts.class.php	62

When I comment code block with checking user authenticated, search works without problems.

```
class lizmapFts
{
    protected $sql;
    protected function generateSql($project)
    {
     < ... >
        // Add filter by groups and user if the user is authenticated
        $sql .= "
        AND ( item_filter = 'all' OR item_filter IS NULL";
        // $isConnected = jAuth::isConnected();
        // if ($isConnected) {
        //     // Ok if any group matches
        //     $appContext = $project->getAppContext();
        //     $userGroups = $appContext->aclUserPublicGroupsId();
        //     foreach ($userGroups as $g) {
        //         $sql .= " OR item_filter = '".$g."'";
        //     }
        //     // Ok if user matches
        //     $user = jAuth::getUserSession();
        //     $login = $user->login;
        //     $sql .= " OR item_filter = '".$login."'";
        // }
        $sql .= ' )';
        $sql .= '
        ORDER BY sim DESC
        LIMIT $3;
        ';
        $this->sql = $sql;
    }
< ... >
```

### Steps to reproduce the issue

1. authenticate
2. search

### Versions

**Versions :**

* Lizmap Web Client : 3.5.2
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.22.5
* QGIS Server : 3.22.5
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin cadastre : not found
* QGIS Server plugin lizmap : 3.7.6
* QGIS Server plugin wfsOutputExtension : not found

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.5

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

99

**Comment by ygorigor** [comment]
@johnzet39 because of this bug I switched back to 3.5.1.

**Comment by Gustry** [comment]
@rldhont Related to https://github.com/3liz/lizmap-web-client/commit/0eb1c3ddb2dcce1db14872516da4224d06f4ebde ?

If so, it's already available in 3.5.3-pre : https://packages.3liz.org/pub/lizmap/unstable/3.5/

**Comment by ygorigor** [comment]
I use docker images.

**Comment by Gustry** [comment]
Indeed, it could be nice to have a "weekly" build fro docker ? (cc @dmarteau )

**Comment by laurentj** [comment]
Fixed into the next version.
