### ISSUE TITLE
How can I change a button link

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#294]
Hello, 
I want try to change the button "Repositories" of my map to layer's repository, but from index.php I do not found where the home link is defined. 
Where it is defined?

**Comment by rldhont** [comment]
Hi @rmarzocchi84,

The home link is defined in a template in the view module and the label is defined in the locales.

Do you want to change the button label ? or do you want to change the function linked to the button ?

**Comment by rmarzocchi84** [comment]
Hi @rldhont, 

If possible, I want to change the link of the button, not the repositories but the single repository.. but I do not understand the file wher you define the function (what is the "locales"?)

**Comment by rldhont** [comment]
Take a look at this code https://github.com/3liz/lizmap-web-client/commit/fb0ba36b7438dbd666f12c4bab76d892af682d24

About loacles, it's the directory in which you'll find localization files.

**Comment by mdouchin** [comment]
To use the file shown in fb0ba36 , see doc https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#adding-your-own-javascript

**Comment by rmarzocchi84** [comment]
@mdouchin very nice! Many thanks, I think it can be very useful for users

**Comment by rmarzocchi84** [comment]
Sorry @mdouchin mdouchin I try the file also in the montpellier repo, but it doesn't seem to work 

I copy the file in a folder called media/js/repo_name/ removing "example" from the name file in order to have a Javascript extension...
