### ISSUE TITLE
deleting photos from features

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#295]
hi,

- if i try to delete a photo from feature the photo will be  erased but not the path to it in the table field

- from a mobile device, when i try to upload a photo the camera will be auto enable. is it possible to upload a photo stored in device?

thanks

**Comment by rldhont** [comment]
Hi @josemvm,
Can you test 'if i try to delete a photo from feature the photo will be erased but not the path to it in the table field' ?
I have tested it and it worked fine.

From the second part of this issue, can you opened a new issue which I will tag as enhancement.

Thanks

**Comment by josemvm** [comment]
hi @rldhont,

yes, i have tested too and now it works fine.

thanks for your attention
