### ISSUE TITLE
Cached layers don't show popup in LWC 3beta4

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#296]
Hello
in Lizmap web client 3b4 server cached point layer doesn't show popup.
The waiting wheel turns with no end.
Same layer in single tile show popup with no problem.

Same project opened with Lizmap 2.11 has no problem with popups, both cached and single tile layer.

**Comment by rldhont** [comment]
Hi @pieri70, you already opened an issue about it, issue we fixed in 83e265a

**Comment by pieri70** [comment]
Sorry, I have a  memory like a frog ;)
Thanks
