### ISSUE TITLE
edition - allow multiple selections in value relation widget

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2964]
### What is the bug?

form without "allow multiple selections" option
![imagem](https://user-images.githubusercontent.com/10053874/165501638-4a59ff1a-711c-4cbe-ac77-22f03d4a52ff.png)

form with "allow multiple selections" option
![imagem](https://user-images.githubusercontent.com/10053874/165500732-d6aa12fc-4307-45d0-b5b1-3a4c7aa1107c.png)

### Steps to reproduce the issue

try to edit

### Versions

**Versions :**

* Lizmap Web Client : 3.4.9
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.16.16
* QGIS Server and plugins unknown status because running Lizmap Web Client < 3.5

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

99.0.1

**Comment by Gustry** [comment]
> Lizmap Web Client : 3.4.9

Any chance you can upgrade to latest 3.5 ? (or latest 3.4, but 3.4 is approaching end of life very soon)

**Comment by josemvm** [comment]
hi @Gustry 
thanks for your suggestions

but i've some issues with 3.5(.3) versions, related to zoom behavior https://github.com/3liz/lizmap-web-client/issues/2772 (with or without filters)


![lizmap_](https://user-images.githubusercontent.com/10053874/166241474-675bd27a-b490-4e96-b5af-f2a8ea3f8211.gif)


in my project (projection 3763) the map scales are different between 3.4 and 3.5 versions

3.4 - 3.5

141
282
564
1128
2257
4514
9028
18056 - 14076 - STOP here
36112 - 28152
72224 - 56304
144448 - 112608
288895 - 225217
577791 - 450433

**Comment by Gustry** [comment]
Please create a separate ticket when a different issue.

**Comment by josemvm** [comment]
maybe a WIP here https://demo.snap.lizmap.com/lizmap_3_4/index.php/view/map/?repository=testsrepository&project=form_type_relational_value

**Comment by Gustry** [comment]
Value relation widget with multiple selection is supported.
https://sandbox.lizmap.com/lizmap_3_8/index.php/view/map?repository=tests&project=form_edition_all_field_type

Layer `form_edition_all_fields_types`

@josemvm Can you confirm ?
