### ISSUE TITLE
[Bug]: ScaleBar values are not correct in 3.5.2

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#2968]
### What is the bug?

ScaleBar values do not match measurement tool values.
![image](https://user-images.githubusercontent.com/30108355/165630496-ff9c88a3-af8f-40d0-93a8-6965f0e0bb95.png)
I am sure that the measurement tool works correctly, because corresponds to real data.

Why the values are different. How can I change it?

### Steps to reproduce the issue

1. Project CRS: 3857.
2. Enable baselayer.

### Versions

Lizmap Web Client : 3.5.2
Lizmap plugin : 3.7.7
QGIS Desktop : 3.22.5
QGIS Server : 3.22.5
QGIS Server plugin atlasprint : not found
QGIS Server plugin cadastre : not found
QGIS Server plugin lizmap : 3.7.6
QGIS Server plugin wfsOutputExtension : not found

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

99

**Comment by rldhont** [comment]
The scale ar is available for a line at the center of the map.

**Comment by johnzet39** [comment]
> 



> The scale bar is available for a line at the center of the map

I dont understand, what it means. My scale bar shows wrong length in any place of map.
