### ISSUE TITLE
Lizmap WC 2.12.4 does not show maps

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#297]
Hello
I am planning to migrate our production LWC from 2.11 to 2.12.4.
I made a clean install of LWC 2.12.4 on the same machine where LWC 2.11 and 3 beta 4 are running without any issue.
Each installation has its own cache folder (eg (/opt/lizmap/cache/prod/ - /opt/lizmap/cache/test/ and /opt/lizmap/cache/beta/) with given rights

Lizmap 2.11 and beta 4 are working with this setup, 2.12.4 isn't

I followed this guide
http://docs.3liz.com/it/admin_guide/installation/linux.html
with this
http://docs.3liz.com/it/admin_guide/installation/linux.html#give-the-appropriate-rights-to-directories-and-files

I didn't made a backup of configuration files but I made a manual setup of basic parameters.

I can access admin panel and set all things without problems, I can access the main page of the portal with repositories and maps icons. I can view map properties but as I choose to show maps the client remains with waiting icon forever...

I made this test on two debian machines, both upgraded to latest system/qgis server etc. updates..

And both of them have at least one LWC version working

Any suggestion?
Thanks
Pietro

**Comment by pieri70** [comment]
Hello
I found the problem is with public baselayers (OSM, Google etc.)
As I add a baselayer, no matter if Google, OSM or Bing, the map doesn't appear and LWC 2.12.4 remains in waiting status

As I add only a shp or a postgis layer the map works.

In LWC 2.11 public baselayers work, only OSM not Google ones (this is why I would like to upgrade to 2.12.4).
In LWC 3 beta4 All public baselayers are working correctly.

We behind a regional network area so may be some filter is applied.. but again on the same machine LWC 2.11 and 3b4 are ok, not the same for 2.12.4.. 

So the problem must be in how  LWC 2.12.4 handles public layers...

Any hint?
Thanks

**Comment by pieri70** [comment]
Just installed 2.12.3 and it works!

So it's the 2.12.4...

**Comment by rldhont** [comment]
Can you update from 2.12.3 to 2.12.4 ?

**Comment by pieri70** [comment]
What do you mean update?
This?
http://docs.3liz.com/it/admin_guide/installation/linux.html#version-upgrade

I just downloaded again the 2.12.4 zip and execute the setup process again.
Nothing has changed..
Thanks


2016-04-22 14:03 GMT+02:00 rldhont <notifications@github.com>:

**Comment by pieri70** [comment]
What do you mean update?
This?
http://docs.3liz.com/it/admin_guide/installation/linux.html#version-upgrade

I just downloaded again the 2.12.4 zip and execute the setup process again.
Nothing has changed..
Thanks

**Comment by rldhont** [comment]
Can you give us a link to your LWC 2.12.4, that We take a look at the JavaScript error ?

**Comment by pieri70** [comment]
http://ms09lxarpa.arpa.fvg.it/lizmap-test/
Il 22 apr 2016 14:49, "rldhont" <notifications@github.com> ha scritto:

**Comment by rldhont** [comment]
Thanks, bug found. Will be fixed

**Comment by rldhont** [comment]
Will be fixed in 2.12.5

**Comment by rldhont** [comment]
Version 2.12.5 has been released https://github.com/3liz/lizmap-web-client/releases/tag/2.12.5

**Comment by pieri70** [comment]
Thanks!
Have a nice day
Pietro
Il 22 apr 2016 15:10, "rldhont" <notifications@github.com> ha scritto:
