### ISSUE TITLE
[Question]: Problems with legend of raster layer

### ISSUE THREAD

**Issue by shock82** [3liz/lizmap-web-client#2971]
### What is the question?

Hello, thanks for your help.
I have an installation of Qgis Server + Lizmap on the Debian server and several types of layers loaded into it.
I have a problem with the legend of the raster data displayed in lizmap, because it has a different size than the legend in the qgis project.

This is the legend in Qgis project:
![image](https://user-images.githubusercontent.com/38106823/165896000-b20b171b-8738-43e8-801e-5fa52be6d442.png)

And this in Lizmap:
![image](https://user-images.githubusercontent.com/38106823/165896218-85d70f66-3e29-4ae4-a69e-6231a867c606.png)

Could you let me know how to set the height of legend in lizmap?
I will really appreciate that. Thanks in advance.

### Versions

- Lizmap Web Client : 3.4.7
- Lizmap plugin : 3.7.7
- QGIS Desktop : 3.22.1

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.1

### Operating system

Debian Buster

### Browsers

Chrome, Microsoft Edge

### Browsers version

Chrome 100.0.4896.127

**Comment by gioman** [comment]
Shouldn't this be kept open as feature request? Seems a sensible thing to have (while I guess that for that type of raster legends maybe would be just enough to tweak the getlegend request for a taller legend, with an hardcoded value).
