### ISSUE TITLE
weird zoom behavior - zoom stops at 14076 value in the scale

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2978]
### What is the bug?

zoom stops at 14076 value in the scale!

![lizmap_](https://user-images.githubusercontent.com/10053874/166314803-38321794-16d4-4631-b839-f3ee3a5a2045.gif)

in all my project (projection 3763) the map scales are different between 3.4 and 3.5 lwc versions

3.4 - 3.5

141 - ???
282 - ???
564 - ???
1128 - ???
2257 - ???
4514 - ???
9028 - ???
18056 - 14076 - zoom STOPs here
36112 - 28152
72224 - 56304
144448 - 112608
288895 - 225217
577791 - 450433

### Steps to reproduce the issue

try a deep zoom `by rectangule` over visible features, and `zoom in`, `zoom in`...
or
try from initial map extent `zoom in`, `zoom in`, `zoom in`, ...

i can provide an url if you want to inspect this weird zoom behavior

thanks

### Versions

Lizmap Web Client : 3.5.3
Lizmap plugin : 3.7.7
QGIS Desktop : 3.22.6

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.6

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

99.0.1

**Comment by geographit** [comment]
Hi,

I confirm a similar behavior. 

zoom stops at 957 with epsg 3857

Versions
Lizmap Web Client : 3.5.3
Lizmap plugin : 3.7.7
QGIS Desktop : 3.22.6

QGIS server version, only if the section above doesn't mention the QGIS Server version
3.22.6

Operating system
Ubuntu 20.04

**Comment by rldhont** [comment]
Can you provide a link to the bug ?
Is there a background layer ?

**Comment by geographit** [comment]
For info, I don't have this bug on lizmap 3.5.1 .

**Comment by geographit** [comment]
@rldhont , yes I have got a background layer allowing deeper zoom level.

**Comment by josemvm** [comment]
hi
this happens if the user has a `startupBaselayer` such as `google-terrain`, which allows a maximum zoom at 14076 value
the user can change the base layer to another map and can do zoom in but the zoom value stops at 14076

**Comment by josemvm** [comment]
this happens if the user has a `startupBaselayer` such as `google-terrain`, which allows a maximum zoom at 14076 value
the user can change the base layer to another map and can do zoom in but the zoom value stops at 14076

this still happens

**Comment by josemvm** [comment]
please can someone test it?

**Comment by josemvm** [comment]
@rldhont sorry, i didn't see this message `Can you provide a link to the bug ?`
yes of course, i can provide an url for you

**Comment by josemvm** [comment]
@rldhont can you check it, please?
thanks

**Comment by rldhont** [comment]
@josemvm I just try it with  release_3_6 and `base_layers` project provided in tests update with:
* mapScales from 500 to 500000
* startupBaselayer as ign-plan which is limited to 4514

I have no issue.

**Comment by josemvm** [comment]
thanks @rldhont :-)
