### ISSUE TITLE
Dynamic display of labels using expressions

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-web-client#2979]
### What is the question?

When displaying with several labels, you want to easily select which labels to display.
![image](https://user-images.githubusercontent.com/86514652/166345415-d2c1ed30-677f-4a92-a6ca-23029b4df666.png)
Are there any sample websites with such functionality?
QGIS is customised to allow project variables to be selected as keys.
If possible, we would like to have a bilingual setup with LIZMAP.

### Versions

3.22

### Operating system

ubuntu

### Browsers

Microsoft Edge

### Browsers version

latest

**Comment by Gustry** [comment]
Interesting idea.
What do you mean by `project variables to be selected as keys.` ? Using project variable to determine the field name to use in a context ?

Lizmap could send, in the request, the language of the user.
Similar to current logged user in Lizmap available in the project variable https://docs.lizmap.com/current/en/publish/configuration/expression.html#project-level

**Comment by yamamoto-ryuzo** [comment]
Show and hide labels in project variable status.
Show and hide labels depending on the user.

(Concrete example.)
　@disp・・・・ is the project variable.
　＠user・・・・is user.
if( @disp_earth_registration_character >='1', "earth_registration_character" ,'') || 
if( @disp_land_registration_land_number >= '1', "land_registration_land_number" ,'') || 
if( @user <> '***',
if( @disp_Locality_Name >= '1', '\n' || "Locality_Name" ,'') || 
if( @disp_Land_Governance_Namae >= '1', '\n' || "Land_Governance_Namae" ,'') 
,'') || 
if( @disp_Land_Gazetteer_Land_Gazetteer_Namae>='1', '\n' || "Land_Gazetteer_Land_Gazetteer_Namae" ,''),'') || 
if( @disp_Land_Gazetteer_Land_Gazetteer >='1', '\n' || "Land_Gazetteer_Land_Gazetteer" || 'm2' ,''')

**Comment by yamamoto-ryuzo** [comment]
Currently, QGIS uses this project variable to turn on and off so that users can choose to show or hide attributes in real time.
In addition, it is also controlled by user rights.
We would like to know if this is possible in LIZMAP.
If possible, we would like to adapt the QGIS methodology to the LIZMAP methodology.

**Comment by yamamoto-ryuzo** [comment]
If not currently available, please let us know if it is possible to add functions.
Depending on the amount, we may ask for additional functions for a fee.

**Comment by yamamoto-ryuzo** [comment]
'Dynamic display of labels using expressions' Exactly.
I will check again at the address you gave me.
Thank you very much.

**Comment by yamamoto-ryuzo** [comment]
Re-read.
It seems that lizmap_user can control which attributes are displayed for each user.
We think of this as 'dynamic display of labels using per-user expressions'.
What we want to do is to control in real-time which labels created with multiple attributes are shown or hidden per attribute.
To achieve this, QGIS currently shows and hides attributes by opening and selecting a checkbox window for the project variable.
Apologies if this is not entirely legible.
I am not suited to this task.
It does not have to be a project variable to implement this functionality.
(Concrete example.)
  　 @disp_****　is the project variable.
if( @disp_earth_registration_character >='1', "earth_registration_character" ,'') || 
if( @disp_land_registration_land_number >= '1', "land_registration_land_number" ,'') || 
if( _**@lizmap_user**_  <> '***',
if( @disp_Locality_Name >= '1', '\n' || "Locality_Name" ,'') || 
if( @disp_Land_Governance_Namae >= '1', '\n' || "Land_Governance_Namae" ,'') 
,'') || 
if( @disp_Land_Gazetteer_Namae>='1', '\n' || "Land_Gazetteer_Namae" ,''),'') || 
if( @disp_Land_Gazetteer >='1', '\n' || "Land_Gazetteer" || 'm2' ,''')

**Comment by yamamoto-ryuzo** [comment]
How do I request a [new feature][Sponsor or PR needed]?

**Comment by Gustry** [comment]
If you want to work on this feature on your own, we accept code with a "PR, Pull Request" otherwise, you can ask 3Liz how it would be possible to fund this feature request. There is a small pink heart on github at the top of this page or on the side on the github landing page redirecting to the 3Liz website.

**Comment by yamamoto-ryuzo** [comment]
We are currently looking for a company in Japan that is willing to work on LIZMAP.
However, many companies are not willing to disclose their sources.
I think I will probably ask 3LIZ to help me.
The order will be placed with the Soja government office, but since it is difficult to make a direct contract with 3LIZ, I will try to find a company that can take on the work as an agency.
Thank you very much.

**Comment by yamamoto-ryuzo** [comment]
As for the text display control, I asked around in various QGIS groups and found that many people use layers to control the display of text, so I decided to go that way as well.
　As a result, I started a dummy layer and switched the display by selecting it.
　Thank you very much.

**(controlled expression)**
　if( @lizmap_disp_Land_Gazetteer >='1', '\n' || "Land_Gazetteer" || 'm2' ,''')
　　>>> if( is_layer_visible('Land_Gazetteer') = true, '\n' || "Land_Gazetteer" || 'm2' ,''')
　　
　@lizmap_disp_Land_Gazetteer:project variables
　'Land_Gazetteer':Dummy layer without data

**Comment by yamamoto-ryuzo** [comment]
Yes, before you know it, you can choose to show or hide layers with the standard QGIS functionality, and more and more, you can achieve your goal.
　**private(プライベート)** 
![image](https://user-images.githubusercontent.com/86514652/185085084-75228f2e-e4a0-40ae-8149-faec08645cbf.png)
