### ISSUE TITLE
locate by layer tool doesn't work with virtual fields when using the "optional group by field"

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#298]
![locate](https://cloud.githubusercontent.com/assets/10053874/14783854/5910a8d4-0aea-11e6-9590-8aeca04b4b6a.jpg)

in my test case:

- the first combobox shows the correct values for the group field "freguesia"

- the second combobox based on virtual field "sp" doesn' t show values, only the blue bar

in similar conditions, i tried using a "sp" real field and everything works fine

thanks

**Comment by rldhont** [comment]
It's a QGIS Server WFS GetFeature issue.
I have noticed it with Lizmap edition issue #282 
I hope to fix it in QGIS 2.14.2 release.

Regards.

**Comment by rldhont** [comment]
Has been fixed in QGIS:
* master https://github.com/qgis/QGIS/commit/ea1d17c3937ba73cc8574a42fe5966b34e292628
* release-2_14 https://github.com/qgis/QGIS/commit/dc94df51a689a45258d2017c81e1e750f72ae4c8

Will be available in 2.14.3
