### ISSUE TITLE
[Bug] : ThemeSelector don't deselected when display layer

### ISSUE THREAD

**Issue by audelorAd** [3liz/lizmap-web-client#2980]
### What is the bug?

It is about the Theme Selector feature.
When we select a Theme it's toggling layer well, but when then we select or deselect a layer Theme is still selected. As on QGIS, Theme should be deselected when layers displayed changed.
With this behaviour on Lizmap we can't use a Theme more than once.
See below the Lizmap behaviour and the expected behaviour on QGIS.

### Steps to reproduce the issue

1. Lizmap behaviour : Theme "Tout déselectionner" is still selected when we change layers displayed, so we can't use it anymore.
![2022-05-02_10h53_23](https://user-images.githubusercontent.com/63049494/166416501-ac3e80b9-94ee-49f3-89a2-9b5aa786da4d.gif)

2. QGIS behaviour : Theme "Tout déselectionner" is welle deselected when we change layers displayed, so we can use it again.
![2022-05-02_10h56_07](https://user-images.githubusercontent.com/63049494/166416756-bc82438f-dda5-4ef4-b1b7-611e8a63537a.gif)

### Versions

**Versions :**

* Lizmap Web Client : 3.5.3
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.22.4
* QGIS Server : 3.22.4

### Operating system

Windows 10

### Browsers

Firefox

### Browsers version

Firefox 91.8.0esr

**Comment by nboisteault** [comment]
Hi,
I have partially solved the issue by leting user select again a previously selected theme.
https://github.com/3liz/lizmap-web-client/commit/bd9c0e038698571eebf046702b0ab35d848049da
To completely follow QGIS behavior there is more work as we need to unselect the theme when the map context (layer or group toggling and style toggling) does not  match its definition. Also the theme could be selected again when the map context matchs its definition.

**Comment by audelorAd** [comment]
> Hi, I have partially solved the issue by allowing users to select again a previously selected theme. [bd9c0e0](https://github.com/3liz/lizmap-web-client/commit/bd9c0e038698571eebf046702b0ab35d848049da) To completely follow QGIS behavior there is more work as we need to unselect the theme when the map context (layer or group toggling and style toggling) does not match its definition. Also the theme could be selected again when the map context matchs its definition.

I've tried with lizmap 3.5.4 and it's working well now. Thanks a lot !!
I close issue
