### ISSUE TITLE
[Question]: field with NULL not visible on identify (but visible when toggling editing)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2981]
### What is the question?

I have a PostGIS layer that is configured to show fields using QGIS D&D forms. I noticed that when identifying it, only the fields that are not NULL are shown, while if editing for the layer is toggled those fields would show up. Feature or bug?

### Versions

3.4.11

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.24

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome

### Browsers version

Most recent

**Comment by Gustry** [comment]
It's not a feature nor a bug !
As a final user, when a layer has a lot of NULL values, this user usually don't want to see NULL values. However, for GIS administrator, it's usually requested to see NULL values, to see how the data is complete etc.

For editing, this is normal that it's always visible. It's using the form you have created in QGIS, whatever the field is NULL or not. It's the only way to edit data and to remove the NULL for instance).

An option must be created in the Lizmap plugin, popup section, to choose to display NULL IMHO.

**Comment by HenriqueDV** [comment]
Hi,

from my point of view, fields must always be displayed acording to the configuration set on the form, no matter if they are empty (null) or not.

I understand Gustrys point, however I think it's up to the administrator to decide by the configuration of the form, if a field is worth to be showed or not. And sometimes, the Null value is an information itself that may be convenient presenting to end user. This additional step of toggling the edition mode can be confusing for end user.

Thanks

**Comment by gioman** [comment]
> I totally understand your point, as I said, there isn't a correct answer. Depending of the context, we sometimes want to have **all** fields and sometimes not.

@Gustry does this rationale apply to the popup as shown in the Lizmap Atlas? I noticed that it shows also the NULL attributes, I was not expecting that considered that the choice was to not show them in the standard popup.

**Comment by Gustry** [comment]
Side note, it's possible to hide NULL values with CSS now : (for HTML Maptip, or DND form). I'm not sure yet for "auto" popup.

```css
div.lizmapPopupDiv div.control-group.control-has-empty-value {
    display: none;
}
```
