### ISSUE TITLE
[Question]: Cadastre plugin on Windwos server

### ISSUE THREAD

**Issue by SigPassy74** [3liz/lizmap-web-client#2983]
### What is the question?

Is there documentation to install the cadastre plugin on qgiserver. I tried with the doc present [here ](https://docs.3liz.org/QgisCadastrePlugin/module-lizmap/configuration/)but without success. 

I asked the question on georezo.net but without success

Thank you

### Versions

• Lizmap 3.4
• QGIS  3.16
• Windows Server 2016

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

Windwos server

### Browsers

Chrome

### Browsers version

100.0.4896.127

**Comment by Gustry** [comment]
Unfortunately, we don't support Lizmap on Windows, CF the documentation : https://docs.lizmap.com/current/en/install/windows.html

At least, you should describe what is blocking you ? What is the error ?
