### ISSUE TITLE
Selection in attribute table but not visible on the map

### ISSUE THREAD

**Issue by prahout59** [3liz/lizmap-web-client#2985]
### What is the bug?

Quand je sélectionne des objets d'une couche, ils apparaissent bien comme sélectionnés dans le décompte des objets sélectionnés et dans la table attributaire mais, pas sur la carte. L'image ci-dessous est parlante.

![image](https://user-images.githubusercontent.com/91070758/166937791-d5b83f4a-91b7-4427-ab33-757767b43cae.png)

Du coup, quand je tente de sélectionner toutes les parcelles d'un même propriétaire avec le plugin Cadastre, j'ai le même soucis.
Le message "Aucune parcelle n'a été sélectionnée" s'affiche.

### Steps to reproduce the issue

Clique sur "Selection"
Sélection d'un ensemble d'objet par un rectangle
 

### Versions

![image](https://user-images.githubusercontent.com/91070758/166939838-2337c64e-66c5-4a65-a5d4-f2f296724fd6.png)

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Debian Buster

### Browsers

Chrome

### Browsers version

Mise à jour de Chrome… (11%) Version 100.0.4896.127 (Build officiel) (64 bits)

**Comment by prahout59** [comment]
Bonjour.

J'ai toujours ce problème de sélection qui s'est généralisé à l'ensemble de mes cartes. la sélection est effective dans la table attributaire, dans le module de sélection mais pas dans l'affichage de la carte.
Le plus simple, je pense serait que repasse dans une version antérieure de Qgis et de Lizmap mais je préférai que vous ayez trouvé une solution :-) Avez-vous une piste ?

![image](https://user-images.githubusercontent.com/91070758/170054253-70e9f2d3-450e-463b-a4d8-da676e2456a1.png)

**Comment by mdouchin** [comment]
Bonjour,

Nous avons eu un autre retour d'utilisateur sur ce problème, mais n'avons pas pu le reproduire en interne. Pourriez-vous svp nous fournir un projet QGIS très simple, avec le fichier `cfg` de Lizmap ainsi que les données liées (non sensibles, pas de cadastre), qui permet de reproduire le problème ? Par exemple via https://drop.chapril.org/

Si le projet pouvait n'avoir qu'une seule couche et reproduire le problème, ce serait le mieux

**Comment by rldhont** [comment]
Quelle est la version exacte de QGIS Server ? 3.22.* ?

**Comment by prahout59** [comment]
# ./qgisserver --version
qgisserver 1.7.20 (build 202205021507,commit fac344e)
QGIS 3.22.6-Białowieża 'Białowieża' (b6f33b1a9f)
QGIS code revision b6f33b1a9f
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.2.2
PROJ version 7.2.1
EPSG Registry database version v10.008 (2020-12-16)
GEOS version 3.9.0-CAPI-1.16.2
SQLite version 3.34.1
OS Ubuntu 21.04

**Comment by rldhont** [comment]
@prahout59 quel est le rendu de la sélection des Parcelles dans QGIS bureautique ? Quel est le type de symbole des Parcelles ?

**Comment by prahout59** [comment]
Pour répondre à votre demande, j'ai sélectionné des objets dans une carte qui pose problème. Ils ne sont pas affichés en jaune mais je peux les exporter. Je l'ai donc fait dans un shapefile.

![image](https://user-images.githubusercontent.com/91070758/170291872-c2be323d-12a5-4323-8e21-17adf9419da4.png)


J'ai créé un projet vide, j'y ai ajouté le shape, activé le service et paramétré la partie lizmap.
Une fois déployé, la sélection est bien en surbrillance !!!

![image](https://user-images.githubusercontent.com/91070758/170291486-cf2a1df7-3a84-453d-92c3-52d67fdff7e3.png)

C'est à s'arracher les cheveux. Avez-vous une idée de l'endroit où je peux tracer l'activité de sélection et de mise en évidence des objets sélectionnés ?

**Comment by rldhont** [comment]
@prahout59 pouvez-vous nous préciser le type de symboles utilisé pour les Parcelles ? et l'affichage de la sélection dans QGIS bureautique pour la couche Parcelles ?

**Comment by prahout59** [comment]
Voici le symbole utilisé pour la couche biens en question.

![image](https://user-images.githubusercontent.com/91070758/170294725-eb191c35-0ba5-4936-aebe-64cb4e80c49f.png)

Et le résultat de la sélection avec le Qgis Desktop

![image](https://user-images.githubusercontent.com/91070758/170295193-ec574cc4-2a93-469b-a1ff-d6dc51d25446.png)

**Comment by mdouchin** [comment]
Il semble qu'il faille supprimer le "nom court" (shortname) de la couche Parcelles dans la configuration des propriétés de cette couche, onglet "QGIS Server".

Nous allons corriger ce bug

**Comment by Gustry** [comment]
Est-ce un lien avec une MAJ récente sur l'extension Cadastre ? https://github.com/3liz/QgisCadastrePlugin/commit/50f6e61b8dcc64b3babf311f26dafa5b79cda096

**Comment by prahout59** [comment]
j'ai un serveur de qualification et un serveur de production. J'ai aligné les deux serveurs sur les versions d'images docker, de modules lizmap web client et plugins map server. Sur le serveur de qualif, cela fonctionne maintenant. Les cartes sont les mêmes des deux côtés. Cela ne fonctionne pourtant toujours pas sur le serveur de production.
![image](https://user-images.githubusercontent.com/91070758/171847866-80759cd2-8fac-4bc4-96e3-bd7bc7d3cef7.png)
La différence entre les deux est l'utilisation du plugin ldapdaao que j'avais dû corriger sur le serveur de prod à cause de Jelix. Je vais l'installer sur le serveur de qualif et voir si cela corrige quelque chose....

**Comment by rldhont** [comment]
@prahout59, la clé primaire est-elle bien de type int4 ou serial ?

**Comment by prahout59** [comment]
Je suis reparti de zéro sur le projet qui pose problème.
J'ai créé un projet vide dans lequel j'ai ajouté une couche multipolygon depuis un serveur postgis.
J'ai activé la capacité wfs et configuré la partie lizmap en activant le popup sur la couche et en ajoutant la table attributaire.
Une fois publiée dans cet état, cela fonctionne.
Ma couche s'appelle qualistock_opis.

J'ai ensuite modifié dans qgis desktop le nom court et le titre de ma couche. 'opis" pour le nom court et "Opérations d'intervention" pour le titre. Idem dans la config lizmap. Et, la sélection ne fonctionne plus !!!

J'ai remis la valeur "qualistock" comme nom court de couche dans Qgis Desktop et dans Lizmap et cela refonctionne.

Il y a donc un BUG sur le traitement des noms de couche. Je vais continuer mon exploration :-(

**Comment by prahout59** [comment]
J'ai supprimé tous les noms courts des couche du projet et cela fonctionne. Merci beaucoup pour votre aide et votre réactivité.

**Comment by Gustry** [comment]
Changement dans la version 1.16.0 de l'extension Cadastre https://github.com/3liz/QgisCadastrePlugin/blob/master/CHANGELOG.md#1160---2022-09-05

**Comment by Gustry** [comment]
Donc sauf erreur, l'erreur n'existe plus ?
Je clos, merci de réouvrir si ebsoin (ou alors un nouveau ticket)

Pensez à vérifier les logs Lizmap QGIS bureautique lors de l'enregistrement, il doit surveiller les champs clé primaire (in4t)
