### ISSUE TITLE
numeric scale values changes when the user pans the map

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2991]
### What is the bug?

![lizmap__](https://user-images.githubusercontent.com/10053874/167623615-95b1381d-89f7-48db-acff-9c93b54fb091.gif)

### Steps to reproduce the issue

pan the map

### Versions

Lizmap Web Client : 3.5.3

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.6

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

99.0.1

**Comment by rldhont** [comment]
@josemvm It is not an issue, it is the exact scale calculated by OpenLayers for EPSG:3857
