### ISSUE TITLE
Use type="number" for <input> when field type is integer

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#2992]
### Describe the solution you'd like
When a field type is `integer` we could use `<input type="number">` instead of `<input type="text">`.
This way it forces users to type integers, it displays buttons to increase/decrease value and, for touch screen devices, the numeric virtual keyboard is displayed which is convenient.

### Additional context
https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/number

**Comment by Gustry** [comment]
Done by @nworr
