### ISSUE TITLE
Lost OpenLayers function in 3.5

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#2998]
Lizmap 3.5.2

At some point, the file was shortened. As a result, the ability to add markers to the map disappeared.
I added a point marker on the map at the mouse click location by custom js-script 
`var markersLayer = new OpenLayers.Layer.Markers( "Markers" );
...`
It was very convenient and visual. 
![image](https://user-images.githubusercontent.com/30108355/168309626-ab64bdcb-ac48-441f-9a2f-f9f098c9b5aa.png)

![mouse_cursor2](https://user-images.githubusercontent.com/30108355/168314830-7f12c667-2628-4e6e-bf59-b9068acecc10.gif)

But now I get an error in the browser:

> Uncaught TypeError: OpenLayers.Layer.Markers is not a constructor

Is there any other way to implement this?
It would be nice to make an indication of the place where the cursor is clicked on the map by default

**Comment by adrian61** [comment]
Share your implementation. It will be easier to help you.

**Comment by timbo-barnes** [comment]
I would also like some of the open layers functionality added/restored. Specifically, the ability to get the extent or centerpoint of the current map window location.

**Comment by nboisteault** [comment]
Hi,
We shorten the OpenLayers 2 build step by step as we move to OpenLayers 7.
But you can add missing files as we do here : https://github.com/3liz/lizmap-wps-web-client-module/commit/8bda4c8a8fb093174e944dc6b16d6db77dda48d9

**Note that it will work for some time but, by the end of the year, we hope to remove OpenLayers 2 completely.**

You can also use OpenLayers 7 as we do here : https://github.com/3liz/lizmap-pgrouting-module/tree/master/pgrouting/www/js
The OL7 map can be put on top of OL2 map with `lizMap.mainLizmap.newOlMap = true;`. Both maps have their extent synchronized. Developer experience is not ideal, but we miss time to document that, and we keep our forces for the OL migration.
