### ISSUE TITLE
[Question]: Where to locate script for all the projects in all repositories?

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#3000]
### What is the question?

By using the /media/js folder in a repository we can add custom scripts but I would like to add the Streetview script for all the maps that I have (50+) in different repositories.
Is there a folder where I can locate the js file and be loaded with lizmap always or do I have to go to each repository and create /media/js folder and copy the file (n copies)?

### Versions

QGIS 3.10
Lizmap 3.3

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.10

### Operating system

Windows Server 2016

### Browsers

Chrome

### Browsers version

90

**Comment by Gustry** [comment]
It's possible. Make a folder called `default` located in the `media` folder, you can use a single `media` folder :

https://docs.lizmap.com/current/en/publish/configuration/media.html#use-a-single-media-folder-for-many-lizmap-folders

**Comment by Gustry** [comment]
Docs updated with the tree example above : https://docs.lizmap.com/current/en/publish/configuration/media.html#use-a-single-media-folder-for-many-lizmap-folders
