### ISSUE TITLE
Add twitter flow in the welcome page ?

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#3001]
### What is the question?

Hello,
Is it possible to integrate a twitter flow in the welcome page?
I tried to use the media link tool but nothing appears . I tried also with a youtube video but the page is empty after saving.
Does someone use this tool ?

### Versions

**Versions :**

* Lizmap Web Client : 3.5.3
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.10.11
* QGIS Server : 3.22.6
* QGIS Server plugin atlasprint : 3.3.1
* QGIS Server plugin cadastre : 1.14.1
* QGIS Server plugin lizmap : 3.7.7
* QGIS Server plugin wfsOutputExtension : v1.5.2

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Debian 11

### Browsers

Chrome

### Browsers version

chrome 100

**Comment by Gustry** [comment]
It seems, only a static content can be included in the welcome page for now. We have a few improvements ideas for this landing page HTML content (such as different content if you are connecter or not, etc) If you are interested into funding some these, please contact us.
