### ISSUE TITLE
Issue with Active layer at start up when "Visibility according to scale" is used in Qgis.

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#301]
With Qgis server 2.8 and lizmap 3 beta3, it was possible to activate a layer even if it was not visible at startup because of the scale level : layer was displayed automatically after zooming to the correct scale.

I have upgraded my server to the last version (Qgis server 2.14 and lizmap 3 beta4). It is now impossible to activate a layer at startup if this layer is not displayed because of the scale options (activate check box has no effect).

Do you have the same behaviour ?

**Comment by rldhont** [comment]
It has been fixed https://github.com/3liz/lizmap-web-client/commit/4390e5ae0dbb1094e012716f2b43c3f83455b6af
