### ISSUE TITLE
link field doesn´t work

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#302]
link field doesn´t work after fixed https://github.com/3liz/lizmap-web-client/issues/267, i think so...

![link](https://cloud.githubusercontent.com/assets/10053874/14922098/9a6d44d6-0e2d-11e6-927e-ec00c40bdc41.jpg)

http://xxx.xxx.xxx.xxx/index.php/view/media/getMedia?repository=montpellier&project=montpellier&path=/media/pdf/transport_map.pdf

No media file in the specified path: /media/pdf/transport_map.pdf

**Comment by rldhont** [comment]
It's a new issue due to link starting with /
