### ISSUE TITLE
[Bug]: Qgis/lizmap legend rendering are different when manually edited

### ISSUE THREAD

**Issue by sigsdis30** [3liz/lizmap-web-client#3026]
### What is the bug?

I have different behavior on lizmap and on qgis regarding legend rendering. I often resume my legends by hand by unchecking the auto update to have a clean rendering.

Qgis only shows me items that I keep. I feel like lizmap takes into account the full layer with all the symbo analysis. Here are 2 screenshots, the 1st under Qgis where you can see that I deleted unnecessary elements:
![image](https://user-images.githubusercontent.com/87764241/171621071-5c5b4708-c078-4c56-919d-a93152b6efb4.png)

And the 2nd rendering with lizmap where I have all the symbology of my layer including the parts (supposed to be) hidden:
![image](https://user-images.githubusercontent.com/87764241/171621188-94ffd6a9-3519-4e07-adc5-0ebfd9d9f82c.png)

### Steps to reproduce the issue

1. create a print layout in qgis
2. add a legend
3. unmark auto update legend
4. edit manually the legend
5. Render in Qgis ok (i.e. the mannually edited legend)
6. Render from lizmap not good (the legend seems not edited)

### Versions

**Versions :**

* Lizmap Web Client : 3.5.4-pre.5333
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.22
* QGIS Server and plugins unknown status because no admin login provided

### Operating system

windows 10

### Browsers

Firefox

### Browsers version

Firefox 100

**Comment by Gustry** [comment]
This is not an issue with Lizmap Web Client.

All the PDF is done by QGIS server only. The ticket should be raised upstream.
