### ISSUE TITLE
[Question]:  [602]   Authentification driver "ldapdao" not found     /var/www/gispro/lib/jelix/auth/jAuth.class.php    166

### ISSUE THREAD

**Issue by khanh78180** [3liz/lizmap-web-client#3035]
### What is the question?

Hi,

I try to setup LDAP and I g't this error for Lizmap 3.5.3.
Have anyone has already succeeded this LDAP setup ?

Thank a lot for help.

Regards

### Versions

Lizmap 3.5.3

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.24

### Operating system

ubuntu 20.4

### Browsers

Chrome

### Browsers version

Chrome

### Relevant log output

```shell
[602]   Authentification driver "ldapdao" not found     /var/www/gispro/lib/jelix/auth/jAuth.class.php    166


on Lizmap side :
Error 500. A technical error has occured. Sorry for this trouble.
```

**Comment by laurentj** [comment]
What did you do to setup ldap?

**Comment by laurentj** [comment]
It seems some steps [from the tutorial](https://docs.lizmap.com/current/en/install/ldap.html) are missing
