### ISSUE TITLE
Filtrage des données par attributs

### ISSUE THREAD

**Issue by luckgentilpiron** [3liz/lizmap-web-client#304]
Bonjour,

Pour des besoins d'impression, j'utilise l'outil de filtrage des données accessible sur la pop-up de chaque entité ou lorsque l'on se rend dans la fenêtre "données". Cette option me permettait de ne garder que les entités filtrées pour l'impression. Or maintenant, soit je ne vois plus aucune entité sur un projet, soit je les vois toutes. Est il possible de paramétrer ce filtre de façon à la rendre plus efficace ? 

Merci par avance,

**Comment by rldhont** [comment]
Can you provide an example and explain your issue in english ?
Thanks

**Comment by luckgentilpiron** [comment]
It's ok, the problem provide by the parameters of "gid" (primary key). If it doesn't publish in WFS, lizmap can't filter by selection and print all entities (it's logic when i see the request) 

Sorry for the inconvenience and Thank for your return !

**Comment by mdouchin** [comment]
@luckgentilpiron thanks for your feedback. We should add this in the documentation, and find a way in the QGIS plugin to warn the user

**Comment by rldhont** [comment]
@luckgentilpiron I have opened an issue in the lizmap-documentation https://github.com/3liz/lizmap-documentation/issues/55. You can update it to help other users. Thanks for your feedback.

**Comment by hugueslepetit** [comment]
Good morning everybody,
I have a little question on lizmap 3.2 filter datas:
I have a competition stores database with some brand (ex: CARREFOUR, LECLERC, INTERMARCHES etc... )
and i need show on the map just CARREFOUR and LECLERC brand. I have a column in my database with these brands.
How can i make this filter in the lizmap datas array filter to filter just on the column "Brand" ? ( i have an other column with adress by example with a carrefour name... )
Thank you by advance for your feedback.
Hugues
