### ISSUE TITLE
Get images directly from external WMS may break projects

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#306]
If I select Get images directly from external WMS for a non WMS layer, the project is broken in Lizmap.
I suggest to deactivate that option for the layers other than WMS.

**Comment by rldhont** [comment]
Which version is concerned by this issue ?

**Comment by pcav** [comment]
2.12.5

**Comment by rldhont** [comment]
@pcav it's, I think, also a plugin issue.
I only can add some test to fix this issue in web client.

**Comment by pieri70** [comment]
Hello did you try the quickmapservices plugin instead of OL plugin?
Il 07 mag 2016 7:11 PM, "rldhont" <notifications@github.com> ha scritto:

**Comment by rldhont** [comment]
I never used OL plugin, just QuickMapServices

**Comment by pcav** [comment]
@rldhont  right, it's both a web client and a plugin issue: do you want me to open another ticket on the plugin?

**Comment by rldhont** [comment]
Thnaks @pcav to open an issue in the plugin.

**Comment by pcav** [comment]
Done: https://github.com/3liz/lizmap-plugin/issues/58
