### ISSUE TITLE
Do not mix default config with user config in var/themes/default.

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#3061]
This is a follow up for https://github.com/3liz/lizmap-docker-compose/issues/25

### Is your feature request related to a problem? Please describe
ATM the docker configuration for lizmap is a kind of a mess and user configuration is mixed with default config wich require to mount a lot of volumes of what should stay private on the host.

Il seems it is  not actually possible to use custom configuration for theme with docker because required default files are located at the same location required for the user configuration.   

### Describe the solution you'd like
It should be possible to place user theme configuration  in another location than the default config files

**Comment by laurentj** [comment]
Since Lizmap 3.6, there is no more static files in `var/`, to this issue is fixed
