### ISSUE TITLE
The presence of a Google layer in the project breaks it

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#307]
If one publish a project with a Google map layer loaded via a plugin, the Lizmap project does not start. Better to ignore it altogether, and leave the possibility to the user to leave it in the project.

**Comment by rldhont** [comment]
How did you load Google Map layer ?
Would it be a plugin layer, an OpenLayers plugin layer ?

Other question which version is affected by this issue ?

**Comment by pcav** [comment]
OL plugin, yes. Lizmap 2.14.5
