### ISSUE TITLE
[Question]: Error in main configuration on pluginsPath

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-web-client#3072]
### What is the question?

Installation question.
I asked this question because I don't know how to get 3Liz's paid support.
The error is
Error 500. A technical error has occured.
Error in the main configuration.
According to the log, they don't like "Error in main configuration on pluginsPath".
The configuration is
FcgidInitialEnv QGIS_PLUGINPATH /usr/lib/qgis/plugins"
Where should I review this?

(Plugin information)
![image](https://user-images.githubusercontent.com/86514652/174789320-3a2958de-efe5-4bcb-9d14-0109a76194ad.png)

### Versions

QGIS Desktop 3.22

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.26.0

### Operating system

ubuntu

### Browsers

Microsoft Edge

### Browsers version

latest

### Relevant log output

```shell
2022-06-21 20:36:24	223.133.253.183	[1024]	Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php	470
	/
array ( )

	0	trigger_error()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 470
	1	jConfigCompiler::_loadPluginsPathList()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 158
	2	jConfigCompiler::prepareConfig()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 85
	3	jConfigCompiler::read()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 103
	4	jConfigCompiler::readAndCache()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfig.class.php : 84
	5	jConfig::load()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jApp.class.php : 161
	6	jApp::loadConfig()	/var/www/lizmap-web-client-3.5.3/lizmap/www/index.php : 17
2022-06-21 20:36:24	223.133.253.183	[7]	Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown.	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php	206
	/
array ( )

	0	jConfigCompiler::checkCoordPluginsPath()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 159
	1	jConfigCompiler::prepareConfig()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 85
	2	jConfigCompiler::read()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfigCompiler.class.php : 103
	3	jConfigCompiler::readAndCache()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jConfig.class.php : 84
	4	jConfig::load()	/var/www/lizmap-web-client-3.5.3/lib/jelix/core/jApp.class.php : 161
	5	jApp::loadConfig()	/var/www/lizmap-web-client-3.5.3/lizmap/www/index.php : 17
```

**Comment by Gustry** [comment]
You error is related to "Jelix" plugins, not QGIS server plugins.
So it's not about QGIS-Plugin manager. @laurentj maybe you have an idea ?

Related to your QGIS server plugins, please read the docs about plugins which that you need : https://docs.lizmap.com/current/en/install/pre_requirements.html#qgis-server-plugins
You are using "Lizmap" which is now the desktop plugin, **not** the server plugin, it's missing the server flag in your screenshot. Cadastre is only useful for French use-case. I'm not sure you need QuickOSM, this was just as an example.
