### ISSUE TITLE
[Question]: How to implement action in a popup

### ISSUE THREAD

**Issue by Catacombe** [3liz/lizmap-web-client#3077]
### What is the question?

Hi,

I've been using LWC for my private project for about a year, and I'm kinda a fans with it, and want to explore more on its features. One thing that I like to know is about the popup action.

Refer to the [Lizmap documentation](https://docs.lizmap.com/current/en/publish/configuration/action_popup.html?highlight=javascript) , as I follow the instruction, I got stuck to an error "An error occured while running the PostgreSQL query !"
![image](https://user-images.githubusercontent.com/46992423/175009603-fd99ec9f-fe2b-4775-a9b8-d16ef0817ddd.png)

From the browser console, I've got the info like this :
![image](https://user-images.githubusercontent.com/46992423/175007141-9a3b5772-a43c-4488-a777-1d41249c0dff.png)

I've also read on the issue brought up by @helene-rossignol [here](https://github.com/3liz/lizmap-web-client/issues/1622#issue-613232870) about function call with postgis, since I use postgis also.
I have followed what @mdouchin had [commented](https://github.com/3liz/lizmap-web-client/issues/1622#issuecomment-669949072), but still got the error.

Can anyone help me how to get it right ? Appreciate your help.

### Versions

QGIS Desktop 3.24.3
LWC 3.5.3

### QGIS server version, only if the section above doesn't mention the QGIS Server version

 QGIS FCGI server - QGIS version 3.22.7-Białowieża

### Operating system

 Ubuntu 20.04.4 LTS

### Browsers

Chrome

### Browsers version

Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by Catacombe** [comment]
Hi,

I just figured out that there is a miss-configuration in my postgresql setup. After the setting have been re-configured, the code can running well.
Sorry, for this ...... and I'm closing the issue as resolved. Thanks.

**Comment by Gustry** [comment]
Thanks for the feedback
