### ISSUE TITLE
[Question]: v3.5 : Debian 11 / PHP 7.4 support ?

### ISSUE THREAD

**Issue by vidlb** [3liz/lizmap-web-client#3080]
I'm trying to install v3.5.3 on a fresh Debian bullseye server and the installation process seems to have failed :  
```
root@vps80527:/var/www/lizmap-web-client-3.5.3# lizmap/install/set_rights.sh www-data www-data
root@vps80527:/var/www/lizmap-web-client-3.5.3# php lizmap/install/installer.php
PHP Warning:  require(/var/www/lizmap-web-client-3.5.3/lizmap/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/lizmap-web-client-3.5.3/lizmap/application.init.php on line 12
PHP Fatal error:  require(): Failed opening required '/var/www/lizmap-web-client-3.5.3/lizmap/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/lizmap-web-client-3.5.3/lizmap/application.init.php on line 12

```
Then in nginx I can only see error 500.
Is this related to PHP 7.4 ?

Edit : looking line 12 in the application.init.php, it looks like some files are missing or changed path, the "vendor" dir does not exists :  
```require ($appPath.'vendor/autoload.php');```

```
root@vps80527:/var/www/lizmap-web-client-3.5.3# find /var -name autoload.php
/var/www/lizmap-web-client-3.5.3/lib/recaptcha/src/autoload.php
```

### Versions

Lizmap 3.5.3
PHP 7.4.28

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.8

### Operating system

Debian 11

### Browsers

Chrome

### Browsers version

Chrome 103

**Comment by Gustry** [comment]
Where did you get the ZIP package ?
The PHP file is provided : https://github.com/3liz/lizmap-web-client/releases/tag/3.5.3

Which documentation did you follow ?

**Comment by vidlb** [comment]
The link I used is the following : https://github.com/3liz/lizmap-web-client/archive/$LIZMAP_VERSION.zip
Is the archive directory wrong ?
I juste tried with Debian 10 VM, v3.4.11 and got the same PHP error.

**Comment by vidlb** [comment]
All right it seems good with the right link, my bad. Thanks a lot

**Comment by Gustry** [comment]
I can't find any reference to `https://github.com/3liz/lizmap-web-client/archive/$LIZMAP_VERSION.zip` or similar links in the documentation.

https://docs.lizmap.com/current/fr/install/linux.html#installing-sources-of-lizmap-web-client
There is a warning about the ZIP file and the link was indeed : 
`wget https://github.com/3liz/lizmap-web-client/releases/download/$VERSION/lizmap-web-client-$VERSION.zip`

Thanks for the feedback.

**Comment by vidlb** [comment]
Yes it was a link in an old script I was updating. Pretty sure it worked 2 years ago, but yeah I just saw the warning.
Thanks for the quick reply
