### ISSUE TITLE
Show selection in printed maps

### ISSUE THREAD

**Issue by dominik-visca** [3liz/lizmap-web-client#3088]
### Describe the solution you'd like

To be able to point to specific features in a printed map (e.g. a specific parcel) it would be great to have the selection not only visible in lizmap but in the printed map as well.

**Comment by nboisteault** [comment]
@dominik-visca I have tested in `master` and it works. Could you tell us if the problem remains for you and in which Lizmap version?

**Comment by Gustry** [comment]
Which print are you talking about ? on the fly print area or from a popup ?

On the fly print area (from the print icon in the menu), it seems to work well. I just tried on LWC 3.5 as well.

Please follow the step about the request for support at the bottom of this page : https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support
