### ISSUE TITLE
Empty baselayer shows the Google map layer instead

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#309]
As above. The background stays fixed, and does not zoom nor pan.

**Comment by rldhont** [comment]
Already fixed in 9073beb082f04a989d1290473afff9cec823e91e

**Comment by pcav** [comment]
Sorry, thanks for that. Any idea of when 2.14.6 will be released?

**Comment by rldhont** [comment]
I hope to do it today.
