### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#310]
hi @rldhont,

after downloading these last commits and reinstall the LWC, i can't run it.
i get this php error:

PHP Fatal error:  Arrays are not allowed in class constants in /var/www/lizmap-3.0-beta4/lizmap/modules/lizmap/classes/lizmapProject.class.php on line 87

is it necessary to do another procedure?

thanks

**Comment by rldhont** [comment]
What is your PHP version ?
Arrays are allowed in class constants since PHP 5.6.

**Comment by josemvm** [comment]
PHP Version 5.3

**Comment by rldhont** [comment]
Check the PHP supported version http://php.net/supported-versions.php
We recommend you to update your PHP version to 5.6. PHP 5.3 is ended since 14 Aug 2014. PHP 5.5 will end the 10 Jul 2016.

**Comment by rldhont** [comment]
I have opened an issue in lizmap-documentation https://github.com/3liz/lizmap-documentation/issues/56. You can improve the documentation to help other users. Thanks for your feedback.

**Comment by josemvm** [comment]
thanks for your attention @rldhont

**Comment by rldhont** [comment]
@josemvm we will update lizmapProject to be compatible with PHP 5.4 like Jelix 1.6.
