### ISSUE TITLE
[Question]: How Create Themes for lizmap?

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#3109]
### What is the question?

Hello everyone, I need to create different themes for many projects. I created the media / themes / default / projectname directory however only the project with the base theme is loaded. Does anyone know how to elucidate me on the problem? Also I would like to associate a URL for each project with direct access

### Versions

3.26 Desktop QGIS

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.26

### Operating system

Lubuntu 20.04

### Browsers

Chrome, Microsoft Edge

### Browsers version

90

**Comment by yamamoto-ryuzo** [comment]
Perhaps that repository (folder) should be created in the administration.
![image](https://user-images.githubusercontent.com/86514652/177530143-ad322b4c-f146-49ee-9287-4388e70dfdbd.png)

**Comment by androidtv160987** [comment]
No, this is theme principal

**Comment by yamamoto-ryuzo** [comment]
I see that there is such a feature.
I will try it myself on my next holiday.
I learned a lot.

https://docs.lizmap.com/next/en/publish/customization/themes.html

**Comment by androidtv160987** [comment]
I have followed the instructions given by the Lizmap site however I cannot customize the themes in particular I would like to apply a different logo for each project, which I cannot do

**Comment by yamamoto-ryuzo** [comment]
Did you allow themes from the admin?![image](https://user-images.githubusercontent.com/86514652/177560827-1ce25171-d7eb-483f-ae63-16b2d15a2f33.png)

**Comment by yamamoto-ryuzo** [comment]
Like this
https://lizmap.yamakun.net/index.php/view/map/?repository=lizmapcloud&project=lizmaptest

**Comment by yamamoto-ryuzo** [comment]
Here is a tentative Japanese version of the memo.
https://github.com/yamamoto-ryuzo/Lizmap-installation-Japanese-memo/blob/main/6.Lizmap%20Web%20Client%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA/6-2.%E3%83%86%E3%83%BC%E3%83%9E%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA.md
