### ISSUE TITLE
Manage lizmap web client folder as user?

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#311]
Hello
I'm trying to manage the installation folder of my LWC 3beta4 as user, not as root

As root I made a folder called lizmap-beta with ownership given to lizmap, the user I want to use as lizmap WC folder manager.
As lizmap then I unzipped the master release and I went trough the install procedure

https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md

I set rights as:
cd /var/www/mylizmap/
lizmap/install/set_rights.sh lizmap www-data

in lizmap/var/config/localconfig.ini.php
I decommented the two chmod lines:

; chmod for files created by Lizmap and Jelix
chmodFile=0664
chmodDir=0775

So I think lizmap and jelix will attribute rights to modify and execute files to lizmap user.

This way many folders and files are created by www-data user so I cannot modify them as lizmap user.

Is there any solution for this?
Thanks
Pietro

**Comment by rldhont** [comment]
It's not Jelix or Lizmap who create files but Apache (aka www-data:www-data).
Did you verify the chmod ?
Did you put your lizmap user in the www-data group ?

**Comment by pieri70** [comment]
How can I verify chmod?
setting umask in /etc/apache2/envars?

Yes I put lizmap user in www-data group.

**Comment by rldhont** [comment]
@pieri70 > ls -lh

**Comment by nboisteault** [comment]
@pieri70 Reeopen if issue still occurs.
