### ISSUE TITLE
[Question]: How to add a "download" button with JavaScript?

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#3111]
### What is the question?

How to create this is fuction to download my project

![image](https://user-images.githubusercontent.com/75124133/178145239-05efdbcb-0a23-4d22-942e-8b29f1321597.png)

### Versions

3.16

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

Lubuntu 20.04

### Browsers

Firefox

### Browsers version

89

**Comment by Alain-LG** [comment]
Hello,

You just need to add this javascript file (download.js) : 

lizMap.events.on({
    'uicreated': function(evt){
    
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var project = lizUrls.params.project;
        mediaLink += '&path=/media/'+project+'.zip';
        $('#title').append(
            '<a class="btn btn-info" href="'+mediaLink+'" target="_blank"><i class="icon-download"></i>Download project</a>'
        );
    }
});

in your "media/js/[project_name]/" directory.

**Comment by Gustry** [comment]
Make CTRL+U, to open the source code. At the end, you can see all JavaScript code which are included. There is a quick demo in  the YouTube tutorial about JavaScript on lizmap.
