### ISSUE TITLE
WMS/WMTS Urls have the wrong server urls. 

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#3128]
### Is your feature request related to a problem? Please describe

GetCapabilities forwarded from WMS/WMTS urls may be not relevant: capabilities response return the internal urls used by lizmap and this should be reconsidered:

- The server is a backend and may be not exposed (voluntarly) to the end-user so the returned URLS are irrelevants.
- When dockerized with docker-compose, lizmap is not aware of the interface address (ip and port) publicly exposed for the map server, so again, the returned urls are totally irrevelants for the end user

### Describe the solution you'd like
If there is no specific reason to return Capabilities information to the end user, then don't do it:   this i exposing useless/irrelevant/insecure information about backend server 

### Describe alternatives you've considered
Make a proper message indicating that this is only informative data and in may be not relevant or usable as-is. Make it eventually only available for admin for debugging purpose.

### Additional context
See https://github.com/3liz/lizmap-docker-compose/issues/24

**Comment by Gustry** [comment]
Is-it not the new environment variable in QGIS Server settings about service URL ?

**Comment by dmarteau** [comment]
> Is-it not the new environment variable in QGIS Server settings about service URL ?

Yes, you may use either:

Environment variables:
* `QGIS_SERVER_SERVICE_URL`  (native to qgis server)
* `QGIS_SERVER_<SERVICE>_URL` for a per service configuration (native to qgis server)
* [`SERVER_PROXY_URL`](https://docs.3liz.org/py-qgis-server/configuration.html#server-proxy-url) with py-qgis-server but now superseded by variables above.

Headers from proxy
* `X-Qgis-Service-Url` and `X-Qgis-<service>-Url `headers (Qgis server native)
* `X-Forwarded-Url` which is specific to py-qgis-server.

The latter may be used with URL rewriting in proxy.  

Imho, headers would be the best choice for lizmap (no need to configure the server)

**Comment by rldhont** [comment]
@dmarteau thanks, which QGIS Server version supports X-Qgis-Service-Url ?

**Comment by Gustry** [comment]
> @dmarteau thanks, which QGIS Server version supports X-Qgis-Service-Url ?

3.20

**Comment by rldhont** [comment]
The issue still occur when the user is authenticated!

**Comment by rldhont** [comment]
The regexp is not global !
