### ISSUE TITLE
error launching the installer

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#313]
hi

i'm trying to lunch the php lizmap/install/installer.php on PHP version 5.6

i get this installer error:

PHP Fatal error:  Call to undefined function simplexml_load_file() in /var/www/html/lizmap-3.0Beta4/lib/jelix/installer/jInstaller.class.php on line 250

**Comment by rldhont** [comment]
SimpleXML functions are needed for Lizmap. Can you verify your PHP install ?

**Comment by josemvm** [comment]
yes, i checked. it's necessary to install php5.6-xml package.
a new a PHP requirement to add to the LWC future documentation.

so, i close this issue.
thanks

**Comment by josemvm** [comment]
hi,

when i'm trying to lunch the lizmap/install/installer.php i get this installer error:

root@ubuntuS14PHP56:/var/www/html/lizmap# php lizmap/install/installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
PHP Notice:  Undefined property: jauthModuleInstaller::$entrypoint in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 48
PHP Notice:  Trying to get property of non-object in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 48
PHP Fatal error:  Call to a member function getValue() on null in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 49

**Comment by pcav** [comment]
What is the name of the necessary package in Debian stable?

**Comment by josemvm** [comment]
in Ubuntu 14: php5-xmlrpc (php 5.5) or php5.6-xml

**Comment by pcav** [comment]
I confirm, I have no php5-xmlrpc package installed, and the installer throws no error.
