### ISSUE TITLE
[Question]: default today date doesn't show up automatically in edit form

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#3131]
### What is the question?

In QGIS attribute form widget related to a "date" type field I insert as default value: now()
When i enter edit form in Lizmap I would expect to see in calendar widget today's date, instead nothing appears and I have to click on calendar icon and select date needed.

![image](https://user-images.githubusercontent.com/59670568/181026054-8de788f1-e914-4fd8-93ca-7c664f257e51.png)

In lizmap desktop plugin server & lizmap are correctly detected and even in LWC Qgis server information administration section.
How can setup my qgis project to make LWC correctly show current date when acticating edit form ?
Thanks.
Bye

### Versions

**Versions :**

* Lizmap Web Client : 3.5.5
* Lizmap plugin : 3.9.0
* QGIS Desktop : 3.22.9
* QGIS Server : 3.22.9
* QGIS Server plugin atlasprint : 3.3.1
* QGIS Server plugin lizmap_server : 1.1.0
* QGIS Server plugin wfsOutputExtension : 1.7.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.9

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

Chrome 103.0.5060.134

**Comment by Gustry** [comment]
Can you show precisely what is the expression used in your form ?
Screenshot and full text expression

**Comment by ocelot73** [comment]
The vector is a postgis table with geometry. The desired column type is "timestamp without time zone".
In QGIS desktop: field type "QDateTime" - "timestamp"

Here is the screenshot of expression used:
![image](https://user-images.githubusercontent.com/59670568/181055529-2bb71d38-8626-4c0b-987b-8d0bf0665fe5.png)

**Comment by Gustry** [comment]
A `date` SQL field, QDate in QGIS works well for me.

**Comment by ocelot73** [comment]
I've not explained well the issue, sorry.
If I initially click on Edit button, edit form shows up and I actually see today's date correctly set at startup (even if field time is `timestamp` not only `date` type)
The problem is if I click before on a geometry which has a NULL value in date field, and then I click on the pencil icon in the popup, date widget doesn't not show today's date. I'd like to find a way to force showing up today's date in THAT edit form. Is it possible ?
