### ISSUE TITLE
Geolocation stopped working.

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#314]
Dear all
our IT mamagers are working on server maintenance.
The geolocation tool (GPS) that was working before now doesn't.
As I click on geolocation button a messare appears saying "geolocation failed".
Both LWC 2.14.5 and 3 beta 4.
What could be the problem? Where should I look for?
Are there any kind of door/connection to be opened?

Thanks
Pietro

**Comment by gioman** [comment]
On Android? Os pcs (with gps?)?

**Comment by pieri70** [comment]
Ok, sorry..
Usually geolocation tool gives my position on network node/server if on desktop PC, GPS position if on smartphone (Android).

In both cases now the tool doesn't work..

I didn't try with GPS connected to laptop.

Strange thing it was working untill last week ot two.
I suspect some restriction was applied on our network system..

Thanks

**Comment by pcav** [comment]
Strangely enough I noticed the same issue, but could not pin it down yet.

**Comment by pieri70** [comment]
Ok so may be it's something in 2.12.5 and last beta?

**Comment by gioman** [comment]
geolocation works fine here with 2.12.6 on a linux server and firefox on linux as client.

**Comment by pieri70** [comment]
I think my server maintainers will send me to hell..
Just a week ago I asked them to upgrade to latest stable 2.12.5..
Il 16 mag 2016 20:35, "Giovanni Manghi" <notifications@github.com> ha
scritto:

**Comment by rldhont** [comment]
Hi @pieri70,

Can you confirm this issue or close it ?

**Comment by pieri70** [comment]
I didn't upgrade the LWC version so I can't confirm.
But as said by Giovanni it works with 2.12.6.. So I close.
Thanks

**Comment by pcav** [comment]
It does not work for me. See e.g. http://lizmap.faunalia.eu

**Comment by pcav** [comment]
It seems to be working in some setting, not in others, unclear why, both in Chromium and in Firefox, mobile and desktop.
Debian sid here.

**Comment by rldhont** [comment]
Hi all,

It's not a Lizmap issue but a Google (and some other) Navigator editor choice.

> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature,
> you should consider switching your application to a secure origin, such as HTTPS. See 
> https://goo.gl/rStTGz for more details.

So If you want to use Geolocation in lizmap, you have to put lizmap under HTTPS.

**Comment by rldhont** [comment]
I have add an issue in the documentation to enhance it.
https://github.com/3liz/lizmap-documentation/issues/57

Please help us enhance the documentaion.

**Comment by pcav** [comment]
Sorry, here it keeps on not to be working on Firefox (it does on Chromium); e.g.:

https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=faunalia_en

**Comment by rldhont** [comment]
Tested on FF and Chroimum on Ubuntu, the two are working.

**Comment by rldhont** [comment]
Tested on FF on android with and without GPS activated it failed. But @pcav you use Lizmap Web Client 2.16 and we use OpenLayers Geolocate Control, which we do not change! I don't understand this issue.

**Comment by pcav** [comment]
It seems to be working in some setting, not in others, unclear why, both in Chromium and in Firefox, mobile and desktop.
Debian sid here.

**Comment by pcav** [comment]
Tested again after upgrading to LM3, same behaviour: OK with Chromium, not with FF.
e.g. https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=faunalia_it
It is likely a local factor, but I haven't a clue why.
