### ISSUE TITLE
[Bug]: Set clockwise direction for pie chart

### ISSUE THREAD

**Issue by audelorAd** [3liz/lizmap-web-client#3148]
### What is the bug?

When setting up a pie chart, the result is not really understandable because of categories order isn't in clockwise direction.

However I saw in lizmap doc :
> For pie chart : the items in the legend are ordered by X as a default behaviour.

Pie chart configuration seems to be hardcoded in Lizmap and **direction: 'clockwise'** parameter is missing.

See below expected result at the bottom :
![2022-08-03_16h43_24](https://user-images.githubusercontent.com/63049494/182637540-fc186477-6514-4f28-be74-f909b27b8725.png)

### Steps to reproduce the issue

1. Set up a pie chart
2. See result in dataviz panel
3. Categories order is well but direction is counterclockwise

### Versions

**Versions :**

* Lizmap Web Client : 3.5.4
* Lizmap plugin : 3.8.3
* QGIS Desktop : 3.22.4
* QGIS Server: 3.22.4

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

windows 10

### Browsers

Firefox

### Browsers version

91.12.0esr

**Comment by audelorAd** [comment]
Indeed it's working fine in a Javascript Script !! 
(At the ticket opening Direction of a pie chart was not a parameter accessible in json layout of a plot)

However I can't figure out how to also modify plot in popup.
See pictures, on the right (dataviz panel) plot well in clockwise direction, on the left (popup panel) not in clockwise direction
![2023-11-30_16h53_30](https://github.com/3liz/lizmap-web-client/assets/63049494/d042c7f6-ad27-472c-a0b5-75b51914ea9b)

**Comment by nboisteault** [comment]
It is a little bit different with popups, here is a quick hack to get the idea:

```js
lizMap.events.on({
    lizmappopupdisplayed: () => {
        // Wait a bit for the plot to be ready
        // TODO: use https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver instead
        setTimeout(() => {

            // Use querySelectorAll if there are several plots
            // and choose which plot to restyle
            const plot = document.querySelector('.js-plotly-plot');

            Plotly.restyle( plot, {
                'marker.color': 'red'
            }); 
        }, 500);
    }
});
```

**Comment by audelorAd** [comment]
> It is a little bit different with popups, here is a quick hack to get the idea:
> 
> ```js
> lizMap.events.on({
>     lizmappopupdisplayed: () => {
>         // Wait a bit for the plot to be ready
>         // TODO: use https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver instead
>         setTimeout(() => {
> 
>             // Use querySelectorAll if there are several plots
>             // and choose which plot to restyle
>             const plot = document.querySelector('.js-plotly-plot');
> 
>             Plotly.restyle( plot, {
>                 'marker.color': 'red'
>             }); 
>         }, 500);
>     }
> });
> ```

Thanks.
It's working in popup, but it's hard to make it works on differents plots in a same popup (especially when when there are different kind of plots). Indeed plots in popup are harder to select in JS than in dataviz panel where plots have an id easy to identify.
