### ISSUE TITLE
delay displaying Google maps basemap

### ISSUE THREAD

**Issue by vincent-dinh** [3liz/lizmap-web-client#316]
Hi,

I have got a Lizmap project using Google maps as a basemap. 
Whenever I zoom in or zoom out there is a delay that only impacts google maps basemap. The other layers update to a new zoom level straight away while the basemap kind of freeze for a second and then update to the new zoom level. It makes the application a bit awkward. 
I am not sure whether this is a bug or if it is a configuration issue on my side.

Cheers

**Comment by rldhont** [comment]
The delay is a based fonctionnality of the Google maps API. To match Google’s zoom animation better with OpenLayers animated zooming, configure your map with a zoomDuration of 10.

**Comment by rldhont** [comment]
After some test, it's better to configure zoomDuration to 0 if there is a Google map baselayer.

**Comment by vincent-dinh** [comment]
Thank you. Keep up the good work. Lizmap is great!
