### ISSUE TITLE
service indisponible 

### ISSUE THREAD

**Issue by geografic2b** [3liz/lizmap-web-client#3163]
### What is the bug?

service indisponible suite à une installation

panneau administration :

QGIS Serveur n'est pas installé correctement, ou l'URL des requêtes OGC donnée dans la configuration de Lizmap n'est pas correcte.

Nous ne pouvons avoir les détails sur l'installation de votre serveur QGIS (version, extensions etc.).
Soit la version installée du serveur QGIS est inférieure à 3.10, soit le plugin Lizmap n'est pas installé sur votre serveur, ou installé avec une version inférieur à 3.7.0. Mettez à jour QGIS Serveur au minimum à la version 3.10, et installez ou mettez à jour l'extension Lizmap à la version 3.7.0 minimum, en lisant la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html.
QGIS Serveur retourne une erreur HTTP à propos de l'extension Lizmap : 400

### Steps to reproduce the issue

https://geofeliceto.alwaysdata.net/index.php/view/

cliquez sur le fichier test

### Versions

version 3.5.5

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.10

### Operating system

ubuntu windows 10

### Browsers

Firefox

### Browsers version

103.0.2 (64 bits)

**Comment by Gustry** [comment]
Please fill the ticket following the template. The checkbox is required.

You have the error in your ticket description : 

> Nous ne pouvons avoir les détails sur l'installation de votre serveur QGIS (version, extensions etc.).
Soit la version installée du serveur QGIS est inférieure à 3.10, soit le plugin Lizmap n'est pas installé sur votre serveur, ou installé avec une version inférieur à 3.7.0. Mettez à jour QGIS Serveur au minimum à la version 3.10, et installez ou mettez à jour l'extension Lizmap à la version 3.7.0 minimum, en lisant la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html.

For the next version we have updated the wording indeed : 
* "extension Lizmap à la version 3.7.0" should be now "extension Lizmap serveur 1.1.1"

In your server administration panel, you have the "environment variable" and the link to the documentation.
https://docs.lizmap.com/current/fr/install/pre_requirements.html#lizmap-qgis-server-plugin

**Comment by Gustry** [comment]
Il existe en effet l'extension "Lizmap server" https://plugins.qgis.org/plugins/lizmap_server/ qui est une extension pour QGIS serveur. L'application Lizmap PHP s'appuie de plus en plus cette extension. L'utilisation de Lizmap 3.6 sera **impossible** sans cette extension.

Pour Lizmap 3.5, l'absence de cette extension ne bloque pas l'affichage de la carte. Mais l'ensemble des fonctionnalités de Lizmap 3.5 ne fonctionneront pas (idem avec 3.4). Toutes les fonctionnalités qui sont sur cette page https://docs.lizmap.com/current/fr/install/pre_requirements.html#lizmap-qgis-server-plugin

Ceci dit, même sans plugin QGIS serveur, le message ci-dessous : 

> QGIS Serveur n'est pas installé correctement, ou l'URL des requêtes OGC donnée dans la configuration de Lizmap n'est pas correcte.

indique que l'URL de votre serveur QGIS n'est bien configuré.

**Comment by geografic2b** [comment]
merci pour cette info. je regarderai comment intaller l'extension lizmap server sur ke veur alwaysdata.
en revanche, "QGIS Serveur n'est pas installé correctement, ou l'URL des requêtes OGC données dans la configuration de Lizmap n'est pas correcte". QGIS serveur fonctionne bien puisque la 3.4  fonctionne.
Je ne vois pas où renseigner l'URL des requêtes OGC ? sur lizmap administration ou sur le projet qgis ?

**Comment by Gustry** [comment]
> QGIS serveur fonctionne bien puisque la 3.4 fonctionne.

Sur alwaysdata ? Avec la même adresse de QGIS serveur ?

>  Je ne vois pas où renseigner l'URL des requêtes OGC ? sur lizmap administration ou sur le projet qgis ?

C'est l'URL que tu renseignes dans ton interface d'administration, pour joindre QGIS serveur. Ce n'est pas lié au projet QGIS.
PS : Il faut changer le MDP ...

Utiliser AlwaysData pour QGIS serveur ne semble pas optimal si on ne peut pas : (sauf erreur) 
* utiliser des variables d’environnement de QGIS serveur : https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables
* installer des extensions QGIS serveur : Lizmap serveur bientôt obligatoire, AtlasPrint, WfsOutputExtension etc  https://github.com/3liz/qgis-atlasprint

**Comment by geografic2b** [comment]
l'URL dont tu parles est URL du serveur WMS qui se trouve dans l'interface d'administration ?
ensuite j'ai la possibilité de renseigner des variables d'environnement du type :
FcgidInitialEnv QGIS_PLUGINPATH "/home/geofeliceto/www/qgis-server/plugins"

**Comment by Gustry** [comment]
> l'URL dont tu parles est URL du serveur WMS qui se trouve dans l'interface d'administration ?

Oui

>  ensuite j'ai la possibilité de renseigner des variables d'environnement du type :

Ok, je n'étais pas sur

**Comment by geografic2b** [comment]
donc l'URL est bonne? http://geocarto.alwaysdata.net/cgi-bin/qgis_mapserv.fcgi
je changerai le mot de passe plus tard. c'est un environnement et projet test.
donc je ne comprends pas pourquoi j'ai ce message service indisponible.

**Comment by Gustry** [comment]
> http://geocarto.alwaysdata.net/cgi-bin/qgis_mapserv.fcgi

À priori oui (en tout cas pour nous de l'extérieur) .

D'ailleurs, l'URL de QGIS serveur ne doit pas être accessible à l'extérieur du réseau
CF la documentation https://docs.lizmap.com/current/fr/install/pre_requirements.html#qgis-server avec l'avertissement

> Nous vous encourageons fortement de configurer QGIS Serveur sur un hôte virtuel différent que celui de Lizmap Web Client. L’URL de QGIS Serveur doit rester privée, accessible uniquement depuis le PHP de Lizmap.

Mais est-ce que "http://geocarto.alwaysdata.net/cgi-bin/qgis_mapserv.fcgi" est bien accessible pour l'application Lizmap ? Je ne connais pas Alwaysdata. Est-ce que `http://geocarto.alwaysdata.net` fonctionne depuis l'appli PHP ?

Il faut regarder les logs QGIS serveur au chargement du projet pour comprendre. (et peut-être augmenter les logs en plus verbeux). Je m'arrête la sur ce sujet, je ne connais pas AlwaysData et c'est un travail de debug et de recherche dans les logs pour comprendre ce qui ne marche pas.

**Comment by geografic2b** [comment]
Est-ce que ça http://geocarto.alwaysdata.netmarche depuis l'application PHP ?   quand je le lance depuis un navigateur, ça fonctionne.
J'ai 2 environnements tests. Sur geocarto, les cartes s'affichents bien, les données sont bien listées en mode liste table attributaire, en revanche si j'ai bien le fond de carte, les données ne s'affichent pas, bizarre.
Sur l'autre geofeliceto, j'ai toujours service indisponible. Ce qui différe, c'est la version lizmap client, le premier et en 3.4, le second en 3.5.
Je reprécise que j'ai une appli de prodution qui fonctionne très bien en 3.4.  L'installation est la même.
Je soupçonne quand même un souci d'accès à la base postgresql.

**Comment by Gustry** [comment]
> Je soupçonne quand même un souci d'accès à la base postgresql.

Il faut essayer sans couche postgresql pour voir si cela fonctionne

> Il faut regarder les logs QGIS serveur au chargement du projet pour comprendre

**Comment by geografic2b** [comment]
je viens de tester geofeliceto sans couches postgresql. toujours services indisponibles.
Quant à l'autre toujours affichage de la carte et des données attributaires mais pas de données sur la carte

**Comment by geografic2b** [comment]
Je suis arrivé à faire l'installation. A présent j'ai les données attributaires mais pas de données affichées sur la carte.
J'ai regardé un post qui concernait ce souci, j'ai suivi les instructions mais idem.
As-tu une idée ?

**Comment by geografic2b** [comment]
Pour clôturer ce billet. J’ai refait la même installation  sur un autre PC et ça fonctionne sans problème. Bizarre ! Dans tous les cas, merci pour votre aide
