### ISSUE TITLE
Cache server limit set to infinite - is it possible?

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#317]
Hello
may be stupid question..
using tile cache on server side, it possible to set expiration to infinite - i.e. disable expiration so cache tiles are generated only one time?

For layers that never change could this make sense??

Thanks

**Comment by rldhont** [comment]
I didn't find information in the documentation, but no time expiration specify is equal to infinity. @mdouchin can you confirm it ?

I think the documentation has to be updated.

**Comment by rldhont** [comment]
In the lizmap-plugin 0 is equal to infiniti.
