### ISSUE TITLE
Insert data from a Tile-Server into lizmap project - is it possible?

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#318]
Hello
is it possible to integrate data coming from a  tile-Server innto Lizmap Web Client Project?
I like for example to integrate the  OpenSeaMap tile server that is accessible at this URLs:
http://t1.openseamap.org/seamark/
http://tiles.openseamap.org/seamark/

http://wiki.openseamap.org/wiki/OpenSeaMap_in_Website#Tile-Server

Thanks
Pietro

**Comment by pieri70** [comment]
I'm able to insert an openseamap layer in qgis throuhg quickmapservices plugin.
But then it's not available in published map..

p

**Comment by nboisteault** [comment]
Hi pieri,

How did you insert openseamap layer with quickmapservices plugin?

It seems you need to create the proper GDAL file to access this service.
This article might help : http://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/OpenStreetMap-Tiles-in-QGIS
When I open a tile (http://t1.openseamap.org/seamark/16/37033/25340.png) directly in my browser, I can't see the image so there might be some restrisctions.
You should ask this question on their forum I think.

**Comment by pieri70** [comment]
Hello
I don't know how the plugin works, but it has a configuration file that is like this

> [general]
id = seamarks
type = TMS

[ui]
group = open_sea_map
alias = Seamarks
icon = openseamap.png

[license]
name = 
link = 
copyright_text = 
copyright_link = 
terms_of_use = 

[tms]
url = http://t1.openseamap.org/seamark/{z}/{x}/{y}.png
zmin = 8
zmax = 19
y_origin_top = False<

I'll look at your link, thanks
p

**Comment by nboisteault** [comment]
You can also get a look at http://www.gdal.org/frmt_wms.html. There are some GDAL file examples.

**Comment by rldhont** [comment]
Hi @pieri70 to use openseamap in Lizmap, you have to create a GDAL TMS file and use it in your QGIR project.
It's the method I describe on my blog
* http://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/OpenStreetMap-Tiles-in-QGIS
The source is
* http://www.gdal.org/frmt_wms.html

@nboisteault beats me.

**Comment by pieri70** [comment]
Ok thanks!
pietro

**Comment by nboisteault** [comment]
Pieri,
When it is working for you, can you share how you did? Thank you.

**Comment by rldhont** [comment]
Can I recommend to update the documentation to share with all users?

**Comment by pieri70** [comment]
Hello
I tried with the code below, but qgis doesn't load seamarks layer and freezes, with the loading bar moving left/right..

@rldhont, is my xml file wrong?

> <GDAL_WMS>
    <Service name="TMS">
        <ServerUrl>http://t1.openseamap.org/seamark/${z}/${x}/${y}.png</ServerUrl>
    </Service>
    <DataWindow>
        <UpperLeftX>11.83931</UpperLeftX>
        <UpperLeftY>46.16078</UpperLeftY>
        <LowerRightX>14.49293</LowerRightX>
        <LowerRightY>44.68924</LowerRightY>
        <TileLevel>18</TileLevel>
        <TileCountX>1</TileCountX>
        <TileCountY>1</TileCountY>
        <YOrigin>top</YOrigin>
    </DataWindow>
    <Projection>EPSG:4326</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>3</BandsCount>
</GDAL_WMS><

**Comment by rldhont** [comment]
Hi @pieri70,
TMS is not EPSG:4326 but EPSG:3857
Copy the OpenStreetMap TMS XML file http://www.gdal.org/frmt_wms_openstreetmap_tms.xml and repalce the ServerUrl content.

**Comment by nboisteault** [comment]
Hi,

In configuration file of QuickMapServices there is 'Y Origin top' unchecked too. Maybe this means you will have to remove <YOrigin>top</YOrigin>.

![image](https://cloud.githubusercontent.com/assets/2145040/15496316/d142cd26-2194-11e6-8add-a52bf7ee8db3.png)

**Comment by pieri70** [comment]
Yes 4326 is just a test because with 3857 it didn't work...

Could you please try the attached file?
I set the datawindow to the nort Adriatic, 3857 EPSG.

With this configuration qgis hangs loading the raster..
I suspect there are problems with our Proxy...
I suspect this because time ago I tried to load OSM via xml file and the result was the same.
thanks.
[seamarks2.zip](https://github.com/3liz/lizmap-web-client/files/279033/seamarks2.zip)

**Comment by rldhont** [comment]
I found the problems!
Firstly, the datawindow has to be worldwide
Secondly, the TMS is exactly the same as the OpenStreetMap
Thridly, the seamarks has transparency, that means the images has 4 bands.

Here is the good xml:
```
<GDAL_WMS>
    <Service name="TMS">
        <ServerUrl>http://t1.openseamap.org/seamark/${z}/${x}/${y}.png</ServerUrl>
    </Service>
    <DataWindow>
        <UpperLeftX>-20037508.34</UpperLeftX>
        <UpperLeftY>20037508.34</UpperLeftY>
        <LowerRightX>20037508.34</LowerRightX>
        <LowerRightY>-20037508.34</LowerRightY>
        <TileLevel>18</TileLevel>
        <TileCountX>1</TileCountX>
        <TileCountY>1</TileCountY>
        <YOrigin>top</YOrigin>
    </DataWindow>
     <Projection>EPSG:3857</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>4</BandsCount>
    <Cache />
</GDAL_WMS>
```
Regards

**Comment by pieri70** [comment]
Ok, some progress!
My suspect is true, our proxy is blocking in some way the data connection/transfer by xml file...
I don't know how this is possible, but I tried to disconnect from enterprise net and use my smartphone tethering.
I tried to open the OSM tiles via xml file as by the rldhont blog and it works!
With the file I attached above I can download seamarks, but the image is black..
So Qgis can download tiles if http proxy is disabled and I'm outside our agency net..
How could it be possible that I can use QuickMapServices layers, Openlayers and other WMS layers but not add a raster via xml???
Thanks!
![cattura](https://cloud.githubusercontent.com/assets/11612625/15497666/09220548-219c-11e6-81aa-c548a96a85f7.PNG)

**Comment by pieri70** [comment]
Hey, rldhont!
I wrote my previous post just a little after you wrote your, and I didn't see it!
Super for the 4 bands!
I must investigate why data behind proxy aren't downloaded...

Thanks!

**Comment by mdouchin** [comment]
In french, but could be useful:
http://www.forumsig.org/showthread.php/34803-Les-tuiles-OpenStreetMap-ou-Google-Maps-directement-dans-QGIS-%28sans-extension%29

Basically, when using GDAL TMS, you have to configure a environment variable in your server (and QGIS desktop too) to allow GDAL to use the proxy

```
export http_proxy=http://proxy-server.mycorp.com:3128/
ou
set http_proxy=http://proxy-server.mycorp.com:3128/ sous windows
```

Replace the URL by your proxy URL

**Comment by pieri70** [comment]
Thanks mdouchin
in qgis I set proxy configuration under preferences and it works, otherwise I couldn't use any openlayers layer or download any plugin...

The lizmap server is on another net, that is DMZ so I think that on lizmap server there shouldn't be any proxy problem..

My problem is on my laptop that is behind proxy.
Proxy is set in network preferences both for windows and qgis.
So there must be some other place GDAL gets its configuration.

Do you think there is some way to specify it in xml file?
Or some other way??

**Comment by pieri70** [comment]
It seems there is the option to set proxy on xml

http://trac.osgeo.org/gdal/wiki/SoCWMSDriver

![image](https://cloud.githubusercontent.com/assets/11612625/15498993/35bb4212-21a2-11e6-8a94-f64d1d942c0b.png)

**Comment by pieri70** [comment]
Problem solved
I added a user environmental variable with name = http_proxy
and value
http://domain\user:password@url_without_http:port/

Now it works on my laptop, next step I'll try on server ;)

Thanks

**Comment by pieri70** [comment]
Super!
It works also on server side
No environmental variable needed.

Just last question
which is the best way to handle these tiles in Lizmap plugin??

Is the config in attached file ok?

Is best to use server cache or single tile?
If "get images directly from WMS server" is selected, single tile/server cache has any effect?
