### ISSUE TITLE
[Bug]: Dataviz error (Internal Jelix Error) with Lizmap 3.5.3 and 3.5.4

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#3186]
### What is the bug?

HI all! I have different Lizmap installations on my server (Ubuntu 18.04.6 ) in particular versions 3.5.1, 3.5.2, 3.5.3 and 3.5.4. I have published the same project with two graphs (a scatter and a bar) properly defined in the dataviz tab of the Lizmap plugin.
Both graph are correctly shown with Lizmap 3.5.1 and 3.5.2 while with Lizmap 3.5.3 and 3.5.4 the getPlot requests return this error: 500 (Internal Jelix Error).

The two graphs use respectively a polygon layer from a PostgreSQL/PostGIS DB and a csv file. Since the DB user and pwd are saved in the project, I can share the project privately.

### Steps to reproduce the issue

- Create a simple QGIS project with at least a graph defined in Lizmap Dataviz tool
- publish the project with different versions of lizmap

### Versions

- The QGIS project has been created with QGIS 3.22.9-Białowieża (installed via osgeo4w on Windows 10), 
- Lizmap Plugin version 3.8.3
- Lizmap versions are mentioned above 

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Server Ubuntu 18.04.6, PC Windows 10

### Browsers

Chrome

### Browsers version

Versione 104.0.5112.102

### Relevant log output
Lizmap Log: 
2022-08-30 16:57:49	2.229.164.182	error	2022-08-30 16:57:49	[0]	syntax error, unexpected ')'	.../lizmap/modules/dataviz/controllers/service.classic.php	69

**Comment by RobiFag** [comment]
We have further investigated the problem and actually the syntax error that is reported in the lizmap log, is due to an extra comma in the error handler functions of the lizmap/modules/dataviz/controllers/service.classic.php file, in particular:

- line 68 https://github.com/3liz/lizmap-web-client/blob/fa63304d3c057c32b12e4a0f858ad6f0dccef2ce/lizmap/modules/dataviz/controllers/service.classic.php#L64-L69

- line 112 https://github.com/3liz/lizmap-web-client/blob/fa63304d3c057c32b12e4a0f858ad6f0dccef2ce/lizmap/modules/dataviz/controllers/service.classic.php#L108-L113

- line 146 https://github.com/3liz/lizmap-web-client/blob/fa63304d3c057c32b12e4a0f858ad6f0dccef2ce/lizmap/modules/dataviz/controllers/service.classic.php#L142-L147

Removing these extra commas resolves the problem!

**Comment by Gustry** [comment]
Hi, thanks for investigating.
Will you make a PR ?

**Comment by RobiFag** [comment]
Not yet, I'll make it tomorrow!

**Comment by RobiFag** [comment]
Done, I hope I did it in the right way!
