### ISSUE TITLE
[Question]: allow NULL value in Relation Reference widget

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#3192]
### What is the question?

Hi all!
Is the option "allow NULL value" in the the relation reference widget supported by Lizmap? Because in the Lizmap edition tool the field with widget relation reference is mandatory even if I set the option "allow NULL value", obviously the NOT NULL constraint is not set. 

![image](https://user-images.githubusercontent.com/25825472/187925362-b6dff7f1-c2d0-460e-99ee-14e0b243aa31.png)

![image](https://user-images.githubusercontent.com/25825472/187925530-fd4cc410-7bdc-4cfd-a894-bfa04104b3e9.png)

### Versions

The QGIS project has been created with QGIS 3.22.9-Białowieża (installed via osgeo4w on Windows 10),
Lizmap Plugin version 3.8.3
Lizmap version 3.5.4

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Server Ubuntu 18.04.6, PC Windows 10

### Browsers

Chrome

### Browsers version

Versione 104.0.5112.102

**Comment by timbo-barnes** [comment]
Have you tried publishing using the same QGIS Desktop version as the QGIS Server version (3.16)? I note they are different.

**Comment by Gustry** [comment]
> QGIS Desktop 3.22.9
> QGIS Server 3.16.16

I don't know if it's related to your issue but indeed you are running into issues. You are asking QGIS Server (3.16) to read a QGS project generated with 3.22, so in the future compare to server 3.16.

We have some tests projects having NULL, I think I haven't checked with a relation reference https://demo.snap.lizmap.com/lizmap_3_6/index.php

**Comment by RobiFag** [comment]
I tried to create and publish the project with QGIS 3.16.16 but I got the same problem. The column with the relation reference widget even if the "allow NULL value" option is set.
