### ISSUE TITLE
[Question]: Create a new repository from Ubunzu

### ISSUE THREAD

**Issue by asdro-f** [3liz/lizmap-web-client#3201]
### What is the question?

So far i create new repositorys in mydomain.com/lizmap/admin.php/admin/maps/.

But i want to create it automatically from Ubuntu.

With `grep` i found the file `lizmap/var/config/lizmapConfig.ini.php`.
In this file there are stored informations about the repositorys. But i only see Infos about label, path and allowUserDefinedThemes.
In the Lizmap Web GUI i also can manage groups/rights and define if own JS is allowed for the project.

Where i find these Informations and is it possible to define it with code from Ubuntu without accessing mydomain.com/lizmap/admin.php/admin/maps/.
With grep i found many .cache-files where minimum one projectName is stored in. 

### Versions

    Lizmap Web Client : 3.4.0
    Lizmap plugin : 3.7.7
    QGIS Desktop : 3.22.9
    QGIS Server and plugins unknown status because running Lizmap Web Client < 3.5

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Firefox 104

**Comment by Gustry** [comment]
It's in the database.
Either SQLite by default, or PostgreSQL if you have set up PostgreSQL backend. Table `jacl2_rights`.

> Lizmap Web Client : 3.4.0

Please upgrade to latest 3.4.12
