### ISSUE TITLE
[Question]: custom chart from plotly.js, access for wfs data by javascript

### ISSUE THREAD

**Issue by manubl2B** [3liz/lizmap-web-client#3207]
### What is the question?

Bonjour,
j'aimerais pouvoir utiliser davantage de graphiques disponibles dans plotly.js que ceux proposés par DataViz, en particulier les 3D Scatter plot et Scatterplot Matrix, afin de les intégrer dans un bottomdock via javascript. cependant, je ne sais pas comment accéder aux données des couches en wfs en javascript. pourriez vous me donner des indications quant aux fonctions existantes dans lizmap et qui me permettrait d'y acceder pour enfin les intégrer comme traces?

Hello,
I would like to be able to use more graphs available in plotly.js than those proposed by DataViz, in particular the 3D Scatter plot and Scatterplot Matrix, in order to integrate them in a bottomdock via javascript. However, I don't know how to access the data of the layers in wfs in javascript. could you give me indications as for the existing functions in lizmap and which would allow me to reach them to finally integrate them as traces?

### Versions

**Versions :**

* Lizmap Web Client : 3.5.5
* Lizmap plugin : 3.9.0
* QGIS Desktop : 3.22.9
* QGIS Server : 3.22.8
* QGIS Server plugin DataPlotly : 3.9
* QGIS Server plugin atlasprint : 3.3.1
* QGIS Server plugin lizmap_server : 1.0.2
* QGIS Server plugin wfsOutputExtension : v1.5.2

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Microsoft Edge

### Browsers version

Firfox 104

**Comment by nboisteault** [comment]
Hi @manubl2B ,
you might find some examples in scripts here : https://github.com/3liz/lizmap-javascript-scripts
