### ISSUE TITLE
[Bug]: On the mobile app layers name defined in location are not displayed

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#3209]
### What is the bug?

Unlike the web version, the mobile version does not show by the default the layers name in the dropdown filter.
Users cannot know what each drop-down list corresponds to.

Mobile version
![IMG_20220907_102909](https://user-images.githubusercontent.com/425243/188882261-9e5b9571-57fe-4a00-a783-8a6a67f50006.jpg)

Web version
![Screenshot 2022-09-07 at 16-48-50 Rando Patrimoine Entre-Deux - Rando_Patrimoine_Entre_Deux - L'entre deux](https://user-images.githubusercontent.com/425243/188882279-350a7ecc-0a69-43ae-9bcd-60fa68ba2151.png)

### Steps to reproduce the issue

- Add locate by layer functionality
- Display the project in a browser and in the mobile app

### Versions

Lizmap 3.4.12

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

Firefox 89

**Comment by cxcandid** [comment]
As a temporary workaround you can change a line of code in `map.js`.

Change `var options = '<option value="-1"></option>'`  to `var options = '<option value="-1" disabled selected>'+placeHolder+'</option>';`

```javascript
      //var options = '<option value="-1"></option>';
      var options = '<option value="-1" disabled selected>'+placeHolder+'</option>';
```
All in all, I'm really not satisfied with the way the locator works. All the data is prefetched during project loading. If we have a lot of layers or layers with thousands of features to locate, too much data must be loaded.

Instead I would suggest to use [bootstrap-autocomplete](https://iqbalfn.github.io/bootstrap-autocomplete/) with `QGIS OGC API Features REST Service` as Ajax Source to dynamically fetch the data.

**Comment by josemvm** [comment]
it's an old issue!...

**Comment by cxcandid** [comment]
@josemvm ... but should be solved as well 😉
