### ISSUE TITLE
tooltip doesn't work properly

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#321]
hi,

I detected some problems in the tooltip operation:

- the tool doen't display information about polygons which most of the area is not visible on map area
![tooltipnoinfo](https://cloud.githubusercontent.com/assets/10053874/15577509/bc10f1d2-2354-11e6-9b3a-a00c397490a5.jpg)

- in case you have a polygon layer that full fill the map area, the tooltip display the last polygon information and keep it on screen. after that the tooltip stops working
![tootipstop](https://cloud.githubusercontent.com/assets/10053874/15577899/3f12bdc6-2356-11e6-900a-f8e36ae60083.jpg)

- after this if you choose another layer to information is not possible to get information, the tool is blocked
![tooltipnewlayer](https://cloud.githubusercontent.com/assets/10053874/15578161/4e4cd1c2-2357-11e6-89a6-4cc056567a3d.jpg)

- the tool tooltip display information abount layers that are not enable or visible...
![layeroff](https://cloud.githubusercontent.com/assets/10053874/15578339/fc6e2026-2357-11e6-911f-2d906c3b0a4c.jpg)

**Comment by rldhont** [comment]
Hi @josemvm,

The last problem you have reported is not an issue but a wanted behavior.

I will fixe the first 3.
