### ISSUE TITLE
[Bug]: Users groups not shown

### ISSUE THREAD

**Issue by dfischetti** [3liz/lizmap-web-client#3212]
### What is the bug?

In the administration panel, when clicking on "rights" the users gropus list is not shown. It gives the following error:
![immagine](https://user-images.githubusercontent.com/113091145/189094782-03ac1885-78b6-44ed-9bdf-0de9f34020fc.png)

### Steps to reproduce the issue

1. Log in as administrator
2. Go to dashboard
3. Click on "rights"

### Versions

**Versions :**

* Lizmap Web Client : 3.6.0-beta.2
* Lizmap plugin : 3.9.0
* QGIS Desktop : 3.26.2
* QGIS Server and plugins unknown status because no admin login provided

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.26.0

### Operating system

Ubuntu 22.04 LTS

### Browsers

Firefox, Chrome

### Browsers version

Firefox 104.0, Chrome 105.0.5195.102

### Relevant log output

```shell
Problem:

2022-09-01 15:29:48       *********      warning      2022-09-01 15:29:48       [2]     SQLite3::query(): Unable to prepare statement: 1, ambiguous column name: id_aclgrp 
/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php                129

2022-09-01 15:29:48       *********      error     2022-09-01 15:29:48       [403]     query non valida (ambiguous column name: id_aclgrp (SELECT g.id_aclgrp, name, grouptype, count(login) as nb_users
FROM jacl2_group g
LEFT JOIN jacl2_user_group ug ON (g.id_aclgrp = ug.id_aclgrp)
WHERE grouptype <> 2 AND (name LIKE '%%%%' OR g.id_aclgrp LIKE '%%%%' )
GROUP BY g.id_aclgrp, name, grouptype
ORDER BY id_aclgrp asc
LIMIT 0,15))  /lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php               133

Solution:

In
/lizmap/vendor/jelix/jelix/lib/jelix-module s /jacl2db/classes/jAcl2DbAdminUIManager.class.php
add g. alias to id_aclgrp table in ORDER BY statement:
ORDER BY g.id_aclgrp asc
```

**Comment by nboisteault** [comment]
@laurentj It seems that the request constructed [here](https://github.com/jelix/jelix/blob/master/lib/jelix-modules/jacl2db/classes/jAcl2DbAdminUIManager.class.php#L518) raises `ambiguous column name: id_aclgrp` in sqlite but not postgreSQL.
Do we still maintain users/groups stored in sqlite?

**Comment by Gustry** [comment]
>  Do we still maintain users/groups stored in sqlite?

It's still possible to install Lizmap Web Client with SQlite, which is the default backend when installing it, so yes (documentation etc)

**Comment by laurentj** [comment]
Thank you for your report. It has been fixed into the Jelix framework.
