### ISSUE TITLE
tooltip limit layers

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#322]
tooltip limit layers = 5
is it possible to increase the limite of available layers?

thanks

**Comment by rldhont** [comment]
It will be an enhancement in a futur version

**Comment by rldhont** [comment]
This is limited by the configuration, can you open an issue in lizmap-plugin ?

**Comment by josemvm** [comment]
of course. done.
https://github.com/3liz/lizmap-plugin/issues/60
