### ISSUE TITLE
Keep previous layer status when disabling tree nodes in legend

### ISSUE THREAD

**Issue by cxcandid** [3liz/lizmap-web-client#3220]
I guess it would be more intuitiv if the layer tree keeps the status of all child layers when we turn off parent tree nodes and reset this status when we turn on parent nodes again. In other words: the on/off mechanism should behave like in QGIS

**Comment by Gustry** [comment]
I guess in 3.7.0, there is quite a few updates on this part. I think it's like QGIS now since #3656

**Comment by cxcandid** [comment]
Thnx Etienne! That's good news. I have seen the new functionality, but unfortunately can't remember the site 🤔

**Comment by Gustry** [comment]
Any chance you can try 3.7 ?

**Comment by cxcandid** [comment]
@Gustry I installed version 3.7 last year and tested it briefly. It looks very promising. I think we can close the issue.

**Comment by Gustry** [comment]
Thanks for your feedbacks.

If it's promising, do not hesitate to send some feedbacks (mail, social network...) always nice to read how people use Lizmap ;-)
