### ISSUE TITLE
[Bug]: datepickers ui.fr.js is missing

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#3231]
### What is the bug?

datepickers ui.fr.js is missing

### Steps to reproduce the issue

- Go to http://localhost:8130/index.php/view/map?repository=testsrepository&project=dnd_form
- Open console
- http://localhost:8130/assets/jelix/js/jforms/datepickers/default/ui.fr.js?_r=220919075702 is 404

### Versions

all

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

All

### Browsers

Chrome

### Browsers version

105

**Comment by laurentj** [comment]
fixed
