### ISSUE TITLE
Add again Norwegian language

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#3232]
### Is your feature request related to a problem? Please describe

Linked to an old ticket in LWC : https://github.com/3liz/lizmap-web-client/issues/1013
and in Jelix : https://github.com/jelix/jelix/issues/328

It should have been fixed in latest release of Jelix available in LWC 3.6.
It seems Norwegian is not available in https://github.com/3liz/lizmap-web-client/blob/master/lizmap/app/system/mainconfig.ini.php#L25

What is the new way to include this language without the issue from #1013 @laurentj ?

**Comment by laurentj** [comment]
The language is activated into lizmap 3.6 (not into lizmap 3.5 or lower, because of a bug that it cannot be fixed into Jelix 1.6)
