### ISSUE TITLE
[Bug]: 2 Cypress tests failing

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#3233]
### What is the bug?

2 Cypress tests fail in master : https://github.com/3liz/lizmap-web-client/actions/runs/3081349456/jobs/4979790703
Cypress was ok 5 days ago : https://github.com/3liz/lizmap-web-client/actions/runs/3052980346

I don't see anything in Lizmap commits that could create those bugs.
Problem might be in Jelix or Lizmap server plugin.

### Steps to reproduce the issue

Run Cypress locally or in CI.

### Versions

all

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

All

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Browsers version

All

**Comment by Gustry** [comment]
Note that with latest Lizmap plugin version, Cypress LWC 3.5 is happy https://github.com/3liz/lizmap-web-client/actions/runs/3083350956/jobs/4984176204

Test LWC 3.4 in progress. So it looks good sign for the Lizmap server plugin.

**Comment by Gustry** [comment]
In LWC 3.5, only the WMTS command line is failing CF https://github.com/3liz/lizmap-web-client/actions/runs/3083505453/jobs/4984515312
This one is a flaky test... I think

**Comment by Gustry** [comment]
In 3.6 Cypress is green. https://github.com/3liz/lizmap-web-client/actions/runs/3095907757/jobs/5010841056

I think we can close.

Fixed in Jelix and LWC https://github.com/3liz/lizmap-web-client/commit/677e1a6c9b9d509b6beb67a420bac641262f5300
