### ISSUE TITLE
[Bug]: edition external map osm-mapnik, ign-photo, ign-plan...

### ISSUE THREAD

**Issue by dechap** [3liz/lizmap-web-client#3249]
### What is the bug?

Hy,

I want to print an external background.
for this I followed the following Tutorial: [https://docs.lizmap.com/current/en/publish/configuration/print.html#allow-printing-of-external-baselayers](https://docs.lizmap.com/current/en/publish/configuration/print.html#allow-printing-of-external-baselayers)

It works very well for "osm-mapnik" but not for others...

### Steps to reproduce the issue

this is my test project
[tmp.zip](https://github.com/3liz/lizmap-web-client/files/9644922/tmp.zip)

### Versions

https://github.com/3liz/lizmap-web-client/releases/tag/3.5.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Version 105.0.5195.127

**Comment by Gustry** [comment]
Which background are you using ? Can you provide some QGIS server logs, with verbose mode ? Does QGIS server can reach the internet for fetching tiles ?
I'm not sure, QGIS needs to write tiles on filesystem temporary, so check rights ?

I don't have the issue with `osm-mapnik`, `ign-photo`.

Side note, we hope this will be legacy and we will mainly rely on the QGIS project.
