### ISSUE TITLE
Use latest IGN API for use isochronal ability into lizmap

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/lizmap-web-client#325]
Dear amazing coders,

Could it be possible to add in lizmap some function related to IGN webservices. For example : isochronal calculation. (http://professionnels.ign.fr/geoservices-itineraires)
Will be great if result could be download or load into QGIS desktop client as a WFS layer.

Thanks

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-javascript-scripts/commit/98b5e415e8a18138f6335ed7fc411073630d6826
