### ISSUE TITLE
Error 500. A technical error has occured. Sorry for this trouble.

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-web-client#326]
Hello,

After formatting my computer, with the same operating system "windows 7, 64 bit", I proceeded to the installation of Qgis through the installer "OSGeo4W. setup" installing everything I had earlier in my computer.

When I open the Lizmap browser and write this:

"http://localhost/lm/lizmap/www/", the message that appears is: Error 500. The technical error has occured. Sorry for this trouble.

I also can't access the account through the: 

"http://localhost/lm/lizmap/www/index.php/jauth/login/form", so I can log in as an administrator and change the url of the server that appears as "http://127.0.0.1/cgi-bin/qgis_mapserv." to "http://127.0.0.1/qgis/qgis_mapserv.fcgi" fcgi

What could this be?

Missing install anything else?

It's a problem of incompatibility between the Lizmap and the Qgis version 2.14.3?

I'd appreciate your help, because I have a small project created in Qgis and which has already been seen and that I wanted to put in the new portal from my job and now it's not working ...

Thank you very much for your help.

Orlando Bernardo

P.S. Sending attached images with the errors reported

[Desktop.zip](https://github.com/3liz/lizmap-web-client/files/297808/Desktop.zip)

**Comment by rldhont** [comment]
Hi @opbernardo,
Which lizmap version do you use ?
If you use Lizmap Web Client 3beta4, you have to make php install/installer.php
If you use the master branch, we have an issue after Jelix update.

If you are under windows, the QGIS Server URL is http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe

**Comment by opbernardo** [comment]
Hello,

I use this version: release_2_12.

I'am under windows, and the QGIS Server URL is this: http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe

**Comment by opbernardo** [comment]
What is the version of Lizmap that you advise me to use?

**Comment by gioman** [comment]
> If you are under windows, the QGIS Server URL is http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe

@opbernardo does the base URL of qgis server (the above) works for you or do you get the code 500 error?

**Comment by opbernardo** [comment]
Hello,
I can not enter the Admin account to change the URL ...

But before formatting my computer the URL was like this: http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe, and it worked perfectly.

**Comment by opbernardo** [comment]
With the google chrome the message that appears is: Error 500. The technical error has occured. Sorry for this trouble.

With mozilla firefox, I can see the Lizmap browser, but I can not enter the admin account.

And when I click on top of the Montpellier-Transport-Demo project, the following message appears:

SERVICE NON DISPONIBLE!

Sending attached image

Thank you very much for your help.

![proj_demo](https://cloud.githubusercontent.com/assets/15649016/15785698/84bdb122-29b0-11e6-886b-0593a0c02fe5.png)

**Comment by gioman** [comment]
@opbernardo

Enter

http://127.0.0.1/qgis/qgis_mapserv.fcgi.exe

Directly in the browser and see if it gives 500 error or not. If it does is a QGIS server/Apache issue , not a lizmap one.

**Comment by opbernardo** [comment]
Hello,

Thank you very much for your help.

Already experienced in the browser and this message (see attached image)

Any idea what it might be?

Thank you


![qgis_mapserv fcgi](https://cloud.githubusercontent.com/assets/15649016/15816680/c9e697e2-2bcb-11e6-9c13-5427d877ab16.png)

**Comment by gioman** [comment]
@opbernardo then the issue is in QGIS Server not Lizmap.

On Windows you typically have to add this line

DefaultInitEnv PYTHONHOME "C:/OSGeo4W/apps/python27"

to the C:\OSGeo4W\httpd.d\httpd_qgis.conf file to avoid the Internal Server Error (you must restart Apache). Anyway recently I tried and for only worked for qgis-ltr (2.8.*) not 2.14.*

Of course no issues on linux where the above is not necessary.

**Comment by opbernardo** [comment]
Hello again,

I had already done this option in Windows "httpd_qgis.conf"

I'm going to uninstall the qgis and I will install qgis-ltr, but only with the (2.8 version).

After I tell you how it worked

Thanks for your help.


P.S. my operating system is Windows 7, 64 bit, SP1, do you think I need any more update in Windows?

**Comment by gioman** [comment]
@opbernardo note that if you use qgis server ltr the address changes slightly

http://127.0.0.1/qgis-ltr/qgis_mapserv.fcgi.exe

**Comment by opbernardo** [comment]
Ok, 

Thank You.

I'll test and then I let you know.

**Comment by opbernardo** [comment]
Hello,

The LIZMAP browser, is already working.

I did what you said and the browser works perfectly, I just installed the qgis-ltr (2.8).

Now my question is:

1-is there any incompatibility between the latest version of Qgis and LIZMAP?

2-If I install the latest stable version of Qgis (2.14), there will be some conflict?

3-I install Qgis through OSGeo4W-setup.exe, to install version 2.14 and update daily, there will be some conflict.

Thank you very much for your help.

**Comment by gioman** [comment]
@opbernardo the real issue (at least from what I see also on my Windows VM testing box) is that QGIS Server 2.14 (and master) does not work, point (not a Lizmap incompatibility issue). On Linux no problems of course. Anyway you can install any QGIS desktop versions you may want. You have just to keep installed and running also qgis server ltr (and remember that on Windows you also need to install the desktop version to have the server working).

**Comment by opbernardo** [comment]
Hello,

Ok, thank you for your help.

Greetings.
