### ISSUE TITLE
error launching the installer on LWC Release version 3.0.0

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#327]
hi,

when i'm trying to lunch the lizmap/install/installer.php, i get this installer error:

root@ubuntuS14PHP56:/var/www/html/lizmap# php lizmap/install/installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
PHP Notice: Undefined property: jauthModuleInstaller::$entrypoint in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 48
PHP Notice: Trying to get property of non-object in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 48
PHP Fatal error: Call to a member function getValue() on null in /var/www/html/lizmap/lib/jelix-modules/jauth/install/install.php on line 49

thanks in advance for your attention

**Comment by rldhont** [comment]
It's an update or a clean install ?

**Comment by josemvm** [comment]
It's a clean install

**Comment by pcav** [comment]
Confirmed here, apparently identical issue.

**Comment by pcav** [comment]
Apparently a module is missing:
Error 500. A technical error has occured. Sorry for this trouble.
Error in the main configuration. A plugin doesn't exist

**Comment by laurentj** [comment]
I take it

**Comment by laurentj** [comment]
@pcav @josemvm : in lib/jelix-modules/jauth/install/install.php, at line 48, replace: `$this->entrypoint` by `$this->entryPoint` and tell me if it is ok for you

**Comment by josemvm** [comment]
hi @laurentj!

yes, solved.
thanks

**Comment by laurentj** [comment]
Ok! Thank you for your report. I will integrate this fix into Lizmap.

**Comment by laurentj** [comment]
Fixed at commit c299732b2b67a5549f6f562d84043a30892e24d4
