### ISSUE TITLE
How to activate OL7 in LIZMAP Client 3.7.0-pre

### ISSUE THREAD

**Issue by cxcandid** [3liz/lizmap-web-client#3275]
### What is the question?

I downloaded lizmap-web-client-3.7.0-pre.zip  from https://packages.3liz.org/pub/lizmap/unstable/3.7/ and installed it successfully on Windows Server 2022. It runs well, but unfortunately uses the old OpenLayers 2.13.1. 
I thought 3.7 was developed for OL7.

How can I switch to OL7 istead of OL2.13?

### Versions

LWC 3.7.0-pre

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.26.3

### Operating system

Windows Server 2022

### Browsers

Chrome

### Browsers version

?

**Comment by Gustry** [comment]
Since quite a few versions of Lizmap Web Client (I think 3.4), there are two OL maps used in Lizmap, they are on top of each other : OL2 and OL7.
There aren't any switch to do, Lizmap is using both at the same time.

**Comment by cxcandid** [comment]
Hi Étienne,

sorry but I don't understand... how can you use OL2.13 and OL7 side by side?
When I enter "OpenLayers.VERSION_NUMBER" in the watch window of the Chrome developer toolbar, I get back "Release 2.13.1".

Best regards
Christoph


Von: Étienne Trimaille ***@***.***>
Gesendet: Dienstag, 11. Oktober 2022 15:41
An: 3liz/lizmap-web-client ***@***.***>
Cc: Candido Christoph ***@***.***>; Author ***@***.***>
Betreff: Re: [3liz/lizmap-web-client] How to activate OL7 in LIZMAP Client 3.7.0-pre (Issue #3275)


Since quite a few versions of Lizmap Web Client (I think 3.4), there are two OL maps used in Lizmap, they are on top of each other : OL2 and OL7.
There aren't any switch to do, Lizmap is using both at the same time.

-

**Comment by Gustry** [comment]
I don't know how to get OL version number.

* `$('#map')` => OL2 map
* `$('#newOlMap')` => OL7 map

Both are synchronized until the migration is finished. Like "Drawing tools" are being migrated in a PR #3259 or like the overview map has been migrated a year ago https://github.com/3liz/lizmap-web-client/pull/2239

**Comment by nboisteault** [comment]
@cxcandid Currently we use both OL2 and OL7 and migrate functionalities one by one. Both maps have their extent synchronized.
You can have access to the OL7 map object with `lizMap.mainLizmap.map`.
OL7 map is under OL2 at initialisation but you can put it on top with `lizMap.mainLizmap.newOlMap = true`
The Lizmap API might change and break. It will be stable when there will be no more OL2 parts.

**Comment by cxcandid** [comment]
@nboisteault thanks for the info ... and *WOW* what a performance increase when I set `lizMap.mainLizmap.newOlMap = true`! 

That's definitely a game changer! 👍😁
