### ISSUE TITLE
Locate by layer [2.12]

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#328]
Hi,

I use version 2.12 of lizmap, it works well but the tool " locate by layer " appears to loading map before disappearing and with any layer (shp or postgres), any version of lizmap ... The display tool data is always empty too ... I have not renamed the layers either (the editing tool works well too).

Thanks for help

**Comment by rldhont** [comment]
Do you publish your layers as WFS ?
Have you use clean names for you layers ? I mean without space, accent or other sign except the _

**Comment by Cww7** [comment]
My layers are published in WFS (OWS server in Qgis) and the names are clean.

My Apache logs `[Fri Jun 10 13:52:59 2016] [error] [client 127.0.0.1] 2016-06-10 13:52:58\t127.0.0.1\twarning\t2016-06-10 13:52:58\t[2]\tInvalid argument supplied for foreach()\tC:\\OSGeo4W\\apache\\htdocs\\lizmap\\lizmap-web-client-release_2_12\\lizmap\\modules\\lizmap\\classes\\lizmapProject.class.php\t124, referer: http://localhost/lizmap/lizmap-web-client-release_2_12/lizmap/www/index.php/view/map/?repository=carte&project=carte
[Fri Jun 10 13:52:59 2016] [error] [client 127.0.0.1] , referer: http://localhost/lizmap/lizmap-web-client-release_2_12/lizmap/www/index.php/view/map/?repository=carte&project=carte
`

**Comment by Cww7** [comment]
Le problème est le même avec le projet démo de montpellier (affichage puis disparition de l'outil locate by layer).

**Comment by rldhont** [comment]
Can you verify the WFS requests made by Lizmap ?

If the locateByLayer widget disappears, it's because all WFS Requests failed.

**Comment by Cww7** [comment]
The WFS requests seems to be Ok :

`<WFS_Capabilities version="1.0.0" updateSequence="0" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-capabilities.xsd"><Service><Name>WMS</Name>
<Title>QGIS mapserver</Title><Abstract>A WMS service with QGIS mapserver</Abstract><KeywordList><Keyword>QGIS mapserver</Keyword></KeywordList><OnlineResource xlink:type="simple" xlink:href="http://www.sourcepole.ch/"/>
<ContactInformation><ContactPersonPrimary><ContactPerson>Marco Hugentobler</ContactPerson><ContactOrganization>Sourcepole AG</ContactOrganization></ContactPersonPrimary><ContactAddress><AddressType>postal</AddressType><Address>Weberstrasse 5</Address><City>Zürich</City><StateOrProvince>ZH</StateOrProvince><PostCode>8004</PostCode><Country>SWITZERLAND</Country></ContactAddress><ContactVoiceTelephone/><ContactElectronicMailAddress>marco.hugentobler@sourcepole.ch</ContactElectronicMailAddress></ContactInformation>
<Fees>none</Fees><AccessConstraints>none</AccessConstraints><LayerLimit>99</LayerLimit></Service><Capability><Request><GetCapabilities><DCPType><HTTP><Get onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType><DCPType><HTTP><Post onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType></GetCapabilities><DescribeFeatureType><SchemaDescriptionLanguage><XMLSCHEMA/></SchemaDescriptionLanguage><DCPType><HTTP><Get onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType><DCPType><HTTP><Post onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType></DescribeFeatureType><GetFeature><ResultFormat><GML2/><GML3/><GeoJSON/></ResultFormat><DCPType><HTTP><Get onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType><DCPType><HTTP><Post onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType></GetFeature><Transaction><DCPType><HTTP><Post onlineResource="http://localhost/qgis/qgis_mapserv.fcgi.exe?"/></HTTP></DCPType></Transaction></Request></Capability><FeatureTypeList><Operations><Query/></Operations></FeatureTypeList><ogc:Filter_Capabilities><ogc:Spatial_Capabilities><ogc:Spatial_Operators><ogc:BBOX/><ogc:Disjoint/><ogc:Intersect/><ogc:Touches/><ogc:Crosses/><ogc:Contains/><ogc:Overlaps/><ogc:Within/></ogc:Spatial_Operators></ogc:Spatial_Capabilities><ogc:Scalar_Capabilities><ogc:Comparison_Operators><ogc:Simple_Comparisons/><ogc:Between/><ogc:Like/></ogc:Comparison_Operators></ogc:Scalar_Capabilities></ogc:Filter_Capabilities></WFS_Capabilities>`

**Comment by rldhont** [comment]
Your WFS is not OK, the FeatureTypeList is empty. No layers are published through WFS. Can you verify your QGIS Projection and thé WFS configuration? The problem comes from Thatcher.

**Comment by Cww7** [comment]
My request was empty :
`http://localhost/qgis/qgis_mapserv.fcgi.exe?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities`

But the request :
`http://localhost/lizmap/lizmap-web-client-release_2_12/lizmap/www/index.php/lizmap/service/?repository=carte&project=CARTE&SERVICE=WFS&VERSION=1.3.0&LAYER=locc&REQUEST=GetCapabilities`
send me this response:
`<serviceExceptionReport version="1.3.0"><serviceException code="Error">
        Server Error !
      </serviceException></serviceExceptionReport>`

Projection and WFS configuration are OK.

**Comment by rldhont** [comment]
Hi @Cww7 
Do you have fix your issue with WFS  ?

QGIS Server only support WFS 1.0.0. The GetCapapbilities request is:
` http://localhost/qgis/qgis_mapserv.fcgi.exe?MAP=chemin/vers/le/projet/carte.qgsSERVICE=WFS&VERSION=1.0.0&REQUEST=GetCapabilities`

**Comment by Cww7** [comment]
No I don't.
There's something I don't understand, The GetCapapbilities request _http://localhost/qgis/qgis_mapserv.fcgi.exe?MAP=mypath\carte.qgs&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetCapabilities_ doesn't work (500 internal server !) but my lizmap project is ok and I can modify or add an entity.

**Comment by Cww7** [comment]
Hi,
I reinstalled the application and it works now
