### ISSUE TITLE
Lizmap new version 3.0.1

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-web-client#329]
Hello,

I'm trying to use the new version of LIZMAP 3.0, but that sending message appears in annex.

I need to install any other file, so I can use the new version?

Thanks for the help

![localhost_lm_lizmap_www](https://cloud.githubusercontent.com/assets/15649016/15892962/b5f0193e-2d74-11e6-993a-9eaed6abf4fc.png)

**Comment by rldhont** [comment]
Hi @opbernardo , Which version of PHP do you use ?
If it's the one provided by OSGeo4W, you can't use lizmap 3 with it.
The minimum version is PHP 5.4 and you have to install  apache and php with an other tool than OSGeo4W.

**Comment by rldhont** [comment]
An issue has been opened in the documentation about the minimum PHP version
https://github.com/3liz/lizmap-documentation/issues/56

**Comment by opbernardo** [comment]
Hello,

Thanks for your reply.

Can you tell me what other tool allows me to install apache and php 5.6?

To install apache and php 5.6, must be placed inside the installer OSGeo4W folder?

Thank you

**Comment by opbernardo** [comment]
Hello,

On installation of the new version of php 5.4 and apache, these files are to
be placed in the folder "C:\OSGeo4W"?

Thank you for your help.




2016-06-08 12:37 GMT+01:00 rldhont <notifications@github.com>:

**Comment by rldhont** [comment]
No Apache and PHP don't have to be placed in the folder "C:\OSGeo4W". You can instal it where you want.

**Comment by ingsbr00** [comment]
Thank you, but in ubuntu, i have installed php version 5.5.9 and if i try the last version error is:
"Error 500. A technical error has occurred. Sorry for this trouble.
The application is not installed"

**Comment by gioman** [comment]
@ingsbr00 https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md

**Comment by ingsbr00** [comment]
Now page shows:
process(new jClassicRequest());

**Comment by opbernardo** [comment]
Someone can help me to install the version 3.0.1 of LIZMAP, Apache and PHP on windows 7 operating system?

I wanted to use the 3.0.1 version, but I'm not get by working.

There will be a version of LIZMAP 3.0.1 executable (*.exe) installation?

Thank you all for your help.

**Comment by laurentj** [comment]
@ingsbr00 if the page shows PHP instructions, it means that PHP is not installed or not well configured inside Apache.

**Comment by rldhont** [comment]
@opbernardo the documentation has been pushed https://github.com/3liz/lizmap-documentation/blob/master/source/install/windows.rst
test it and improve it.

**Comment by rldhont** [comment]
@ingsbr00 and @andremano You can also take a look at the linux install documentation 
https://github.com/3liz/lizmap-documentation/blob/master/source/install/linux.rst
test it and improve it

**Comment by rabiISR** [comment]
Hi @rldhont, I want to install the version 3.0.1 of Lizmap, the modules Apache and PHP compatibles  on windows 7.  I work on the version 2.12.4 and php installed by Osgeo4W.  When I upgrade it, I have got the same problem like @opbernardo.
I have learned all issues about this question that you posted but I didn't understand how to configure the files compression that you posted. 
https://github.com/3liz/lizmap-documentation/blob/master/source/install/windows.rst
Where can I find it? 
Thank you for your help.

**Comment by rabiISR** [comment]
Bonjour,
Je suis en train d'installer les modules Apache et php.5.6.23 afin d'avoir la version lizmap3.0.1. Après avoir suivi toutes les étapes de l'installation proposées suivant ce lien https://github.com/3liz/lizmap-documentation/blob/master/source/install/windows.rst, j'ai redémarré Apache avec la commande httpd -k restart,
![apacheerror](https://cloud.githubusercontent.com/assets/21125014/17861839/ed7b1fc6-6892-11e6-841b-097603efe5a5.JPG)

Mais ça ne fonctionne pas et  j'ai le message d'erreur suivant:  
![apacheerror2](https://cloud.githubusercontent.com/assets/21125014/17861854/fc398016-6892-11e6-98e2-37eaf97241db.JPG)

**Comment by rabiISR** [comment]
J'ai trouvé la solution! ;)

**Comment by mdouchin** [comment]
@rabiISR could you give the solution here, so that other users may benefit from your experience ? We will then be able to improve documentation

**Comment by josemvm** [comment]
hi

i' ve the same problem with ubuntu 16 and php 7.
the installation of the LWC runs ok but the browser shows me this message:

process(new jClassicRequest());

thanks in advance

**Comment by nboisteault** [comment]
Reopen if you want to share what you did to solve your problem.
