### ISSUE TITLE
Problem about hour of log

### ISSUE THREAD

**Issue by luckgentilpiron** [3liz/lizmap-web-client#330]
Hi,

When I check the logs, the hour isn't correct (-1 hour). Where Lizmap is taking this hour ? In UK's system ? It's possible to change this in Lizmap config ? 

Thanks for help

**Comment by nboisteault** [comment]
Hi,

Check your system time. If you're on linux try `date` command and see if time is correct.

**Comment by mdouchin** [comment]
This is not related to lizmap, but to the server configuration. If solved, could you close this issue ?

**Comment by RaphaelChochon** [comment]
I have the same problem with LizMap 3.0.2 and Debian Jessie.
Yet, my system time is good... 
For my log, the hour is shift -2 hours (French - summer time)

**Comment by luckgentilpiron** [comment]
I have the same configuration and the same shift, but i didn't solve this.

**Comment by laurentj** [comment]
At the begining of the lizmap/var/config/localconfig.ini.php file, you should set your timezone.

For example:

```
timeZone="Europe/London"
```
See the list here: http://www.php.net/manual/en/timezones.php

By default, in Lizmap, it is "Europe/Paris" (see lizmap/var/config/mainconfig.ini.php, but you shouldn't modify this file, and set new values in localconfig.ini.php).

**Comment by luckgentilpiron** [comment]
Hi,

My timezones is good ("Europe/Paris") but i always have the wrong hour
