### ISSUE TITLE
Please add wheather maps

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#331]
Apparently easy:
http://openweathermap.org/hugemaps
It would be nice to have all weather parameters at hand, and add it to the base maps with a click.

**Comment by rldhont** [comment]
Hi @pcav, Lizmap probably needs a way to understand TMS layers from GDAL files http://www.gdal.org/frmt_wms.html.
Some things like external WMS layer.

**Comment by pcav** [comment]
Or maybe there are also WMS weather services, looking for it.

**Comment by luckgentilpiron** [comment]
I checked and it's possible to integrate with this link "http://wms.openweathermap.org/service" or with two lines in Qgis (https://www.gislounge.com/adding-real-time-weather-data-from-openweathermap-qgis-python-programming-cookbook/)

**Comment by pcav** [comment]
I cannot add a wms from http://wms.openweathermap.org/service : have you used any special trick?

**Comment by luckgentilpiron** [comment]
Indeed wms doesn't work in Qgis and Lizmap. The problem is not the flow discounting ?

**Comment by jonnyforestGIS** [comment]
Hi guys,
i found in the site that is necessary to have API key authentication. They have different price plans. [Free plan](https://openweathermap.org/price)
So is not so open anymore. 

One of the ways is to have api key and add as tile:
`https://tile.openweathermap.org/map/{layer}/{z}/{x}/{y}.png?appid={api_key}`

[See](https://openweathermap.org/api/weathermaps#library) 

Regards
João

**Comment by Gustry** [comment]
In LWC 3.7, users are now free to use the base layer they want.
