### ISSUE TITLE
I have problem with zoom extension and SR

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#3314]
Have problem SR

Hi everyone I'm having the following problem:

I have a project edited with Qgis 3.22 and lizamp 3.5 on one pc and on another 3.6 (beta) on both the same problem occurs, it is not possible to snap the map I can only zoom in, I have no possibility to move, despite having set various map extensions. The project is with SR 3004 Italy mounte Mario 2. I suspect this is the problem and that Lizmap needs Wgs84 32/33 NORD depending on the area. before doing all the items from scratch they are about (900) I wanted to ask if any of you had encountered the same problem view center.

### Versions

3.22 qgis
lizmap 3.5 and lizmap 3.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Lubuntu 20.04

### Browsers

Firefox, Microsoft Edge

### Browsers version

90

**Comment by rldhont** [comment]
Do you have check the restricted extent ?
