### ISSUE TITLE
Unable to edit postgis layer in lizmap

### ISSUE THREAD

**Issue by gmusumeci** [3liz/lizmap-web-client#332]
I'm working with Lizmap 2.12.6 on VirtualBox - Xubuntu 14.04 and Qgis-Server 2.14.I want to use the editing function of Lizmap on a postgis database.For this purpose I created in postgeSQL 9.5 - 2.2 postgis a small table with some points.
For postgreSQL I have a primary serial key in my table and editing permission on my role.
According the instructions of the lizmap manual I loaded the layer Qgis in and using the plugin I listed my layer as editable and checked all the options available from 'create' up to 'erase'.However I can not edit in any way the layer. In fact, when I load the project in lizmap browser and try to activate editing functions the following occurs:

- On insertion of a new point doesn't open any popup to insert attributes and new geometries are lost irretrievably.When editing is disabled .
On editing of existing point I'm unable to select any point and therefore can not change anything.
Can anyone suggest me if and where I'm wrong?

**Comment by nboisteault** [comment]
Did you published your layers as WFS in Project-> OWS tab?

**Comment by gmusumeci** [comment]
Yes, I published as WFS.
I attach the configuration files


[provapostgis - Copia.qgs.txt](https://github.com/3liz/lizmap-web-client/files/311552/provapostgis.-.Copia.qgs.txt)
[provapostgis - Copia.qgs~.txt](https://github.com/3liz/lizmap-web-client/files/311553/provapostgis.-.Copia.qgs.txt)
[provapostgis.qgs - Copia.cfg.txt](https://github.com/3liz/lizmap-web-client/files/311554/provapostgis.qgs.-.Copia.cfg.txt)

**Comment by rldhont** [comment]
It is probably a problem in PHP install, do you have the postgresl extension ?

**Comment by gmusumeci** [comment]
I installed php5-pgsql: 
sudo apt-get install php5-pgsql On Xubuntu.

**Comment by gmusumeci** [comment]
Is there a way I can check if all packages are correctly installed and configurated?

**Comment by laurentj** [comment]
@gmusumeci could you see in the var/log/ directory of lizmap, if there is an errors.log file, and if there are errors in it?

**Comment by gmusumeci** [comment]
The var/log directory is empty

**Comment by gmusumeci** [comment]
In the log i've found this error:

[Mon Jul 04 09:52:03.691281 2016] [:error] [pid 2823] [client 192.168.16.171:49871] 2016-07-04 09:52:03\t192.168.16.171\terror\t2016-07-04 09:52:03\t[403]\tinvalid query (ERRORE:  parametro di configurazione "autocommit" sconosciuto(SET AUTOCOMMIT TO ON))\t/var/www/lizmap-web-client-2.12.6/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php\t163\n, referer: http://192.168.16.172/lm/index.php/view/map/?repository=provapostgis&project=provapostgis

**Comment by rldhont** [comment]
It seems that your PostgreSQL version does not support autocommit. Which version do you use ?

**Comment by gmusumeci** [comment]
"PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit"

**Comment by rldhont** [comment]
From the documentation: https://www.postgresql.org/docs/9.5/static/ecpg-sql-set-autocommit.html

> SET AUTOCOMMIT is an extension of PostgreSQL ECPG.

**Comment by gmusumeci** [comment]
Could you suggest me how to install that extension???
I don't have ECPG in my Extensions List...

**Comment by gmusumeci** [comment]
For better understanding I attach a more complete log.
I use Qgis under windows and Lizmap-webclient + Qgis server + Postgres under Linux ubuntu in a virtual machine.

[Mon Jul 04 12:24:52.960093 2016] [:error] [pid 2684] [client 192.168.16.171:52246] 2016-07-04 12:24:52\t192.168.16.171\twarning\t2016-07-04 12:24:52\t[2]\tSQLite3::loadExtension(): SQLite Extension are disabled\t/var/www/lizmap-web-client-2.12.6/lizmap/modules/lizmap/classes/lizmapProject.class.php\t556\n, referer: http://192.168.16.176/lm/index.php/view/map/?repository=provapostgis&project=provapostgis

[Mon Jul 04 12:24:52.960270 2016] [:error] [pid 2684] [client 192.168.16.171:52246] 2016-07-04 12:24:52\t192.168.16.171\twarning\t2016-07-04 12:24:52\t[2]\tSQLite3::loadExtension(): SQLite Extension are disabled\t/var/www/lizmap-web-client-2.12.6/lizmap/modules/lizmap/classes/lizmapProject.class.php\t563\n, referer: http://192.168.16.176/lm/index.php/view/map/?repository=provapostgis&project=provapostgis

QFSFileEngine::open: No file name specified
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.

ERROR: Auth db directory path could not be created

[Mon Jul 04 12:25:01.365803 2016] [:error] [pid 2701] [client 192.168.16.171:52249] 2016-07-04 12:25:01\t192.168.16.171\terror\t2016-07-04 12:25:01\t[403]\tinvalid query (ERRORE:  parametro di configurazione "autocommit" sconosciuto(SET AUTOCOMMIT TO ON))\t/var/www/lizmap-web-client-2.12.6/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php\t163\n, referer: http://192.168.16.176/lm/index.php/view/map/?repository=provapostgis&project=provapostgis

**Comment by gmusumeci** [comment]
At the end I solved by a user of the gfoss group

I modified

var/www/lizmap-web-client-2.12.6/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php
row 203

I applied this fix.

https://gist.github.com/slarosa/816d005014bedc86f31f3aa2c27823cd


I didn't understand very well the problem

**Comment by rldhont** [comment]
These is a Jelix issue, fixed in 1.6 and also in lizmap 3.0

**Comment by rldhont** [comment]
The issue was _autoCommitNotify ($state) do nothing for server version >= 7.4 https://github.com/jelix/jelix/commit/59977a32c80e9968aba7de286ebf2a519da65b30

**Comment by rldhont** [comment]
Fixed by 3278ebc157d03d5218ecb90d8ad5716b224874ea
