### ISSUE TITLE
lizmap 3.X not work

### ISSUE THREAD

**Issue by ingsbr00** [3liz/lizmap-web-client#333]
Hi.
My Lizmap version 2,12 works fine.

Im tried to install the lizmap web client version 3.X and not works.
When i tried:
http://localhost/lizmap/lizmap-web-client-master/lizmap/www/

Warning: require(__DIR__/../lib/jelix/init.php) [function.require]: failed to open stream: No such file or directory in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lizmap\application.init.php on line 12

Fatal error: require() [function.require]: Failed opening required '__DIR__/../lib/jelix/init.php' (include_path='.;C:\OSGeo4W\Apache\php\PEAR') in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lizmap\application.init.php on line 12

I changed _DIR_ parameter by dirname(_FILE_) in application.init.php and /jelix/init.php 

And now error is:

Parse error: syntax error, unexpected T_FUNCTION in C:\OSGeo4W\apache\htdocs\lizmap\lizmap-web-client-master\lib\jelix\core\jConfigCompiler.class.php on line 194

And the line is:

 usort($plugins, function($a, $b){ return $a->getPriority() < $b->getPriority();});

It seems that function usort not works....

If I replace the jConfigCompiler.class.php file by the same file of 2.12 version, or if i comment this line,error in browser is:

"Error 500. A technical error has occurred. Sorry for this trouble.
The application is not installed"

How can I fix this problem??

Version 2.12 works fine without any change..
In linux and windows, the same error.

**Comment by rldhont** [comment]
Because of Lizmap is based on Jelix 1.6, it needs PHP 5.4.
But OSGeo4W does not provide à PHP version greater than 5.2.

It's the same issue hasard #329

**Comment by ingsbr00** [comment]
Thank you, but in ubuntu, i have installed php version 5.5.9 and if i try the last version error is:
"Error 500. A technical error has occurred. Sorry for this trouble.
The application is not installed"

**Comment by gioman** [comment]
@ingsbr00 have you launched the setup script?

**Comment by ingsbr00** [comment]
@gioman what is the setup script? and how to launch¿

I tried with this instructions..

http://docs.3liz.com/it/admin_guide/installation/linux.html

**Comment by mdouchin** [comment]
Please have a look at https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md

**Comment by ingsbr00** [comment]
Thank you, but now, the page shows:
process(new jClassicRequest()); :

**Comment by rldhont** [comment]
@ingsbr00 it seems that your PHP is not well interpreted?
Do you have all the required PHP modules?

**Comment by ingsbr00** [comment]
I reinstall modules php and works fine

Version 3.1 is much more slow than 2.12 showing montpelier transports map...
Its normal¿

**Comment by gioman** [comment]
@ingsbr00 

> Version 3.1 is much more slow than 2.12 showing montpelier transports map...
> Its normal¿

you are comparing using the same qgis server version?

**Comment by ingsbr00** [comment]
Yes, Im using the same qgis server, the defaut

**Comment by rldhont** [comment]
If all is now find about lizmap install, I'm closing this issue.
