### ISSUE TITLE
[Question]: toggle visibility of single layer's item

### ISSUE THREAD

**Issue by lucaplz** [3liz/lizmap-web-client#3338]
### What is the question?

Hi,
in Qgis it is possible to toggle visibility of single items in a style layer, I can't find the same functionality in Lizmap: is it a feature that will be implemented in the future?
Is there any workaround to obtain similar effect?

### Versions

QGIS server: 3.22.11
Lizmap version: 4.5.5

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11

### Browsers

Firefox, Chrome

### Browsers version

Firefox 105

**Comment by Gustry** [comment]
>  Lizmap version: 4.5.5

This is a unknown version of Lizmap. (plugin, Lizmap Web Client etc)

Related to your request, yes, we got some funding from some customers for the next version.
The workaround for now is to use the "form filter" panel.

**Comment by lucaplz** [comment]
Sorry:
plugin: 3.9.2
LWC: 3.5.5

**Comment by Gustry** [comment]
Duplicate of #422
