### ISSUE TITLE
Edition : Use QGIS drag&drop form layout with tabs and groups if available

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#334]
if a group frame is available, LWC doesn't respect qgis form order.
the group frame allways appears in the first place (before category tab fields).

qgis form:
![qgis_form](https://cloud.githubusercontent.com/assets/10053874/16021208/5c0011ac-31a9-11e6-82cf-f3290c7709de.jpg)

lwc form:
![lwc_form](https://cloud.githubusercontent.com/assets/10053874/16021216/637b5c84-31a9-11e6-9296-204d511c8a2c.jpg)

**Comment by rldhont** [comment]
In PR #693, does the commit 717b51bdd1a039b96522f5538d8ca449fe4efba0 _ [Enhancement] Build form layout server side base on QGIS drag&drop form layout mode_ fixed this issue ?

**Comment by josemvm** [comment]
hi @rldhont 

for now the form ignores/hides all the fields outside the tabs

![xxx](https://user-images.githubusercontent.com/10053874/33026014-681f6bb2-ce07-11e7-973e-e44bc961583c.jpg)

**Comment by rldhont** [comment]
Thanks for the review!

**Comment by rldhont** [comment]
The PR has been updated!

**Comment by josemvm** [comment]
**qgis:**
![form](https://user-images.githubusercontent.com/10053874/33071620-254c7f0c-ceb4-11e7-97a3-02e6d409c6fe.jpg)

**lwc:**
all fields outside the tabs (`observacoes `and `url`) appear as group at the form bottom, as it happened at the beginning...
![form1](https://user-images.githubusercontent.com/10053874/33071739-b1c10cfa-ceb4-11e7-9ee4-58d389158f29.jpg)

**Comment by josemvm** [comment]
wait...

**Comment by josemvm** [comment]
sorry, everything is ok now!!!

thanks @rldhont and go ahead with this great enhancement in refactoring edition controller :thumbsup:

**ps**: the refactoring edition controller with snapping options, it would be "_gold over blue_" :grinning:
