### ISSUE TITLE
supported file formats for export 

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#335]
please, add more supported file formats for export, like this:

![export](https://cloud.githubusercontent.com/assets/10053874/16035671/4008c838-3210-11e6-948b-8d52cd8b4015.jpg)

thanks in advance

**Comment by gioman** [comment]
@josemvm I think you need to user this

https://github.com/3liz/qgis-wfsOutputExtension

**Comment by josemvm** [comment]
thanks @gioman 

i will try it

**Comment by josemvm** [comment]
yes, done.
now, with a request to a WFS server:

http://my_host_ip:81/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities&map=/var/www/html/lizmap3/lizmap/install/ma/pdma.qgs

i can get the expected "ResultFormat"

![formats](https://cloud.githubusercontent.com/assets/10053874/16039851/2e66fc9e-3224-11e6-8101-f67401dbc4f5.jpg)

I think this is not enough or not implemented yet in LWC v.3...
how can i use it in LWC?

**Comment by mdouchin** [comment]
Indeed, Lizmap 3 uses the GetCapabilities response to build the list of available formats. You do not have to do any more configuration to have the full list available in Lizmap.

**Comment by josemvm** [comment]
thanks @mdouchin 

unfortunately the list of available formats only shows me GeoJSON and GML file formats...

**Comment by rldhont** [comment]
@josemvm can you test the GetCapabilities Request in Lizmap ?
Did you use the qgis-server url you use for the test in lizmap http://my_host_ip:81/cgi-bin/qgis_mapserv.fcgi ?

**Comment by rldhont** [comment]
@josemvm You can probably update the documentation for this point, isn't it ?

**Comment by josemvm** [comment]
my url for request to a WFS server (port:81):

http://10.27.1.31:81/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities&map=/var/www/html/lizmap3/lizmap/install/ma/test.qgs

the result:
![xml1](https://cloud.githubusercontent.com/assets/10053874/16055830/b37d1076-326a-11e6-8394-cd27d9000997.jpg)
![xml2](https://cloud.githubusercontent.com/assets/10053874/16055834/b8458016-326a-11e6-9a76-81e25065f8f7.jpg)

my url lizmap project (the same, but at the default port:80):

http://10.27.1.31/index.php/view/map/?repository=ma&project=test
the result:
![lwc](https://cloud.githubusercontent.com/assets/10053874/16056063/b65ed558-326b-11e6-9fa1-a954e2397aae.jpg)

PS:
http://10.27.1.31/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities&map=/var/www/html/lizmap3/lizmap/install/ma/test.qgs

my url for request to a WFS server (using default port:80) only shows me the GML2, GML3 and GeoJSON ResultFormat... is it expected? i think so...

**Comment by josemvm** [comment]
i' m sorry for the noise...

i had 2 virtual hosts on apache for the same purpose, one listening on port 80 (qgis-server) and another at port 81 (qgis-server plugin).

the documentation confused me...
yes, i can probably update this QGIS Server Plugin documentation...

thanks

**Comment by rldhont** [comment]
@josemvm I was thinking about lizmap-documentation https://github.com/3liz/lizmap-documentation
