### ISSUE TITLE
Php 7 error

### ISSUE THREAD

**Issue by fredericmazzini** [3liz/lizmap-web-client#336]
Hi,

I had to comment these lines 
```
 /*       if ( $ctrl = $this->_form->getReset() ) {
            if(!$this->_form->isActivated($ctrl->ref)) continue;
            $this->outputControl($ctrl);
            echo ' ';
        }*/
```

in the file htmlbootstrap.formbuilder.php to avoid the error 

> PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in /var/www/lizmap/lizmap/plugins/formbuilder/htmlbootstrap/htmlbootstrap.formbuilder.php on line 69

Fred

**Comment by rldhont** [comment]
@fredericmazzini thanks for this feedback, you can uncomment and use the bugfix.
