### ISSUE TITLE
edition - snapping options

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#337]
please, add the snapping options to the edition tool.
It's an essential feature for editing.

thanks in advance

**Comment by mdouchin** [comment]
Essential, but not trivial ;)
We probably won't add this advanced feature before migrating to OpenLayers 3. Unless @rldhont thinks of anything ?

**Comment by josemvm** [comment]
hi @rldhont @mdouchin

> Concerning the future, version 3.2 is already on track with a publication target for FOSS4G Europe 2017. Developments in this future version will mainly focus on the **edition module** and base layers.

so, please keep snapping options in mind
thanks in advance

**Comment by josemvm** [comment]
it will be a giant step for LWC 3.**??** :gift: ;-)

**Comment by rldhont** [comment]
We need to use an other javascript map library to do it. So it will be in LWC 4.

**Comment by josemvm** [comment]
i thought this could be just a litle base for... but i suppose that the process is much more complex...

`  function getFeatureInfoTolerances(){`

    var tolerances = defaultGetFeatureInfoTolerances;
    if( 'pointTolerance' in config.options
        && 'lineTolerance' in config.options
        && 'polygonTolerance' in config.options
    ){
      tolerances = {
        'FI_POINT_TOLERANCE': config.options.pointTolerance,
        'FI_LINE_TOLERANCE': config.options.lineTolerance,
        'FI_POLYGON_TOLERANCE': config.options.polygonTolerance
      };
    }
    return tolerances;

`}`

anyway, thanks for the answer @rldhont!

**Comment by josemvm** [comment]
hi

back to the snapping tools, as you know this is a very important subject

with regard to editing tasks, LWC can't be used as an alternative to others webgis frameworks while not offering these features

i'm talking about road networks, hydrological networks, electrical networks, telecommunications networks, etc.

i don't know what you think about openlayers v3 or v4 migration...
i just know that openStreetMaps offers these editing tools because i contribute with contents to the platform

one more time and always one more time thank you very much for your great project and for your skillful work

and if LIZMAP loves QGIS, I love LIZMAP!

**Comment by mdouchin** [comment]
You are right @josemvm This is a important feature, but can be achieved only with OpenLayers 4 (or 3), which means we have a rather big effort to migrate from OL 2 to OL4. We are searching some financing or support to do so, and plan it for 2018.

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-javascript-scripts/blob/master/snapping_while_editing/activateSnapWhenEditing.js

**Comment by nboisteault** [comment]
@josemvm does it mean I can close the issue ?

**Comment by josemvm** [comment]
no @nboisteault 
i think that the user needs a menu to choose the layers, tolerance, attraction type, etc

**Comment by igeofr** [comment]
I agree with @josemvm.

**Comment by josemvm** [comment]
hi all developers, @igeofr @gioman @pcav @jonnyforestGIS and others

please, can someone try this script https://github.com/3liz/lizmap-javascript-scripts/blob/master/snapping_while_editing/activateSnapWhenEditing.js and give me feedback?

see here too https://github.com/3liz/lizmap-javascript-scripts/issues/17

thanks in advance

**Comment by igeofr** [comment]
Hi @josemvm 
I tested the script, it seems to work perfectly on my project with 2 polygonal layers.

Here are my attachment parameters for its two layers which must be snapped to each other :
`var snapLayerName = '';

    var snapLayers = {
	     'Unités pastorales' : {
         'layers': [
            'Secteurs pastoraux',
            'Unités pastorales'
        ],
        snapToNode: true,
        snapToEdge: false,
        snapToVertex: true
       },
	     'Secteurs pastoraux' : {
         'layers': [
            'Unités pastorales',
            'Secteurs pastoraux'
        ],
        snapToNode: true,
        snapToEdge: false,
        snapToVertex: true
       }
    }`

**Comment by josemvm** [comment]
hi @igeofr 

thanks for sharing the parameters!

i don't understand the problem... i have tried with many layers, projects and versions and i get always the same script error!!!:

`TypeError: snapLayers[featureType] is undefined`

===> `var getSnapLayer = snapLayers[featureType]['layers'];`

**Comment by josemvm** [comment]
![imagem](https://user-images.githubusercontent.com/10053874/70617356-50d9f980-1c08-11ea-8d7a-a7fe04c34f99.png)

![error](https://user-images.githubusercontent.com/10053874/70617636-ed9c9700-1c08-11ea-9f70-3dee607f212f.png)

it seems to be something wrong here `['layers']` ...

**Comment by josemvm** [comment]
please can someone help me?
i really need to use this feature

thanks again

**Comment by josemvm** [comment]
thank you all the fellows received my help request and they decided not to answer me!

🐫 thank you so much for making me feel like a jesus preaching in the wilderness 😄

**Comment by rldhont** [comment]
It is something wrong with featuretype, we have to enhance the script to get the right layername from featuretype.

**Comment by rldhont** [comment]
The script does not check if the edited layer has snapping configuration.

**Comment by rldhont** [comment]
@josemvm I have fixed the script https://github.com/3liz/lizmap-javascript-scripts/commit/1ff41eeba74b8621e9cd81b80f43911b6f8b3f4e I invite you to update yours.

**Comment by josemvm** [comment]
i did many tests and experiments, i have updated my scripts and everything works well now!

@rldhont thank you very much!!! the LWC has become much richer with this operational feature 😄
now "_i will preach to this wilderness..._" https://github.com/3liz/lizmap-web-client/issues/636
