### ISSUE TITLE
[Bug]: Docker - 3.6.0 container does not start with non-standard UID/GID

### ISSUE THREAD

**Issue by u-cav** [3liz/lizmap-web-client#3370]
### What is the bug?

Updating to 3.6.0 when using a non-standard (not 1000) UID and GID, the container does not start.
I also tried this on a clean stack.

The first error I'm getting is:

`/bin/lizmap-entrypoint.sh: line 29: groupmod: not found`

lizmap-entrypoint.sh is calling, in some cases, for `groupmod` and `usermod`, which are not installed in the base image used. Those can be installed with the package `shadow`.

Once they are installed, I'm getting a different error:

`groupmod: invalid group ID 'groupphp'`

I assume, and this is a long shot, that this is due to a typo in the entrypoint, which refers to APP_GROUP_ID and APP_USER_ID instead of LIZMAP_GROUP_ID and LIZMAP_USER_ID

Those two variables should be empty, and as such the command that runs is `groupmod -g groupphp`, which fits the error.

### Steps to reproduce the issue

1. Start a docker stack with Lizmap 3.6.0 and a non-standard (not 1000) UID and GID, specified either as the deprecated "LIZMAP_USER", or as "LIZMAP_USER_ID" and "LIZMAP_GROUP_ID"

### Versions

**Versions :**

* Lizmap Web Client : 3.6.0
* Lizmap plugin : 3.9.8
* QGIS Desktop : 3.22.12
* QGIS Server : 3.22.13
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11

### Browsers

Firefox, Chrome

### Browsers version

Firefox 107, Chromium 108

**Comment by dmarteau** [comment]
This bug occurs also on our CI with our last docker 3.6-dev docker images.

**Comment by dmarteau** [comment]
This breaks also https://github.com/3liz/lizmap-docker-compose wihch use the `LIZMAP_USER` variable to set the UID/GID

**Comment by u-cav** [comment]
@dmarteau Thank you for your feedback. As far as I can tell, once this issue is fixed it should work also with the deprecated `LIZMAP_USER` variable, as it simply gets passed on to `LIZMAP_USER_ID` and `LIZMAP_GROUP_ID`:

https://github.com/3liz/lizmap-web-client/blob/72cbc7c22603b3cfc360eb333bee1c191e731646/docker/lizmap-entrypoint.sh#L7

**Comment by dmarteau** [comment]
It seems that the problem has been been introduced from here: 063ac41f0e05f64a3aaf9238660a2e150f14067c.
