### ISSUE TITLE
I have problem to installation Lizmap 3.6

### ISSUE THREAD

**Issue by androidtv160987** [3liz/lizmap-web-client#3377]
### What is the question?

Hi all, I'm trying to do a clean install of lizmap on a ubuntu based virtual machine. The procedure I've always adopted worked until beta 3.6. Today I can no longer make lizmap work correctly, errors related to the qgis-server version are reported to me, in short I will list what I have done up to now to install lizmap, I ask if any of you can post me its installation procedure. I can't follow the official one because in some points I get lost and not being accustomed to linux I have some difficulty the steps I follow are these:

```
1) apt update && apt upgrade && apt install apache2
2)apt install libapache2-mod-php8.1
3)apt install php8.1-gd php8.1-mysql php8.1-curl php8.1-mbstring php8.1-intl
4)apt install php8.1-gmp php8.1-bcmath php-imagick php8.1-xml php8.1-zip
5) apt install xvfb
6)apt install libsqlite3-0 libsqlite3-dev
7)apt install php8.1-sqlite3
8)apt install php8.1-xml
9)apt install curl
10)a2enmod rewrite
11)a2enmod headers
12)a2enmod env
13)a2enmod dir
14)a2enmod mime
15)apt install php8.1-gd php8.1-mysql php8.1-curl php8.1-mbstring
16)apt install libapache2-mod-php8.1
17)apt install php8.1-gmp php8.1-bcmath php-imagick php8.1-xml php8.1-zip
```

IN ORDER TO BE SURE I INSTALL A QGIS LTR I ALWAYS ADD THE UBUNTU GIS REPOSITORY AS FOLLOWS

```
18)apt-get install python-software-properties
19)add-apt-repository ppa:ubuntugis/ubuntugis-stable
20) apt update && apt upgrade -y
21) apt install qgis-server && apt install qgis
22) apt install libapache2-mod-fcgid
23)apt install python3-pip
24)pip install qgis-plugin-manager
25)qgis-plugin-manager remote
26)python3 -m pip install qgis-plugin-manager
27)qgis-plugin-manager init
28)cat sources.list
29)qgis-plugin-manager remote
30)cat sources.list
31)qgis-plugin-manager update
32)ls .cache_qgis_plugin_manager/
33)qgis-plugin-manager cache atlasprint
34)qgis-plugin-manager list
35)qgis-plugin-manager install Lizmap
36)qgis-plugin-manager install wfsOutputExtension


37 wget https://github.com/3liz/lizmap-web-client/releases/download/3.6.0/lizmap-web-client-3.6.0.zip
   38 unzip lizmap-web-client-3.6.0.zip
    39 mv lizmap-web-client-3.6.0 lizmap-web-client
40 cd /var/www/lizmap/lizmap-web-client/lizmap/install
    41 cd /var/www/lizmap/lizmap-web-client/lizmap/var/config
   42 cp lizmapConfig.ini.php.dist lizmapConfig.ini.php
  43 cp localconfig.ini.php.dist localconfig.ini.php
44 cp profiles.ini.php.dist profiles.ini.php
  45 CDs /var/www/
   46 chown -R www-data:www-data lizmap
  47 cd /var/www/lizmap/lizmap-web-client/lizmap/install
  48 cd /var/www/lizmap/lizmap-web-client/lizmap/var/config
    49 cp lizmapConfig.ini.php.dist lizmapConfig.ini.php
  50 cp localconfig.ini.php.dist localconfig.ini.php
   51 cp profiles.ini.php.dist profiles.ini.php
  52 apt install php8.1-xml
    53 cd /var/www/lizmap/lizmap-web-client/lizmap/install
    php ./installer.php
  54 nano /etc/apache2/sites-enabled/000-default.conf
55 service apache2 restart
```

At the end of this procedure Lizmap is installed so much that I can see it on localhost/lizmap/index.php. any loaded project however has an error:

> "This map cannot be displayed. Please contact the server administrator to check the server information panel."

I am notified that the version of qgis-server cannot be determined or that the plugin is not installed. Actually I did the installation as described above. If anyone has the opportunity to share their procedure I would be very grateful

Eventually it would be good if someone braver had produced a self-installing sh script, because maybe I'm missing some steps I don't know...

### Versions

QGIS 3.22
QGIS 3.22 
Lizmap 3.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

90

### Relevant log output

```shell
2022-12-20 01:15:59	127.0.0.1	warning	2022-12-20 01:15:59	[2]	Undefined array key "metadata"	/var/www/lizmap/lizmap-web-client/lizmap/modules/lizmap/lib/Server/Server.php	62

2022-12-20 01:15:59	127.0.0.1	warning	2022-12-20 01:15:59	[2]	Trying to access array offset on value of type null	/var/www/lizmap/lizmap-web-client/lizmap/modules/lizmap/lib/Server/Server.php	62
```

**Comment by Gustry** [comment]
> I am notified that the version of qgis-server cannot be determined or that the plugin is not installed.

A link was provided in the error message, leading to the "Lizmap server" plugin for QGIS Server.
https://docs.lizmap.com/current/en/install/pre_requirements.html#qgis-server-side
The plugin name is not `Lizmap` but `Lizmap server`

Your issue is the same as #3367

**Comment by Antoviscomi** [comment]
@androidtv160987 I solved this by setting  these variable in my apache2 host .conf file

# QGIS_PLUGINPATH
  FcgidInitialEnv QGIS_PLUGINPATH /var/www/qgis-server/plugins
  FcgidInitialEnv QGIS_SERVER_LIZMAP_REVEAL_SETTINGS True

**Comment by Gustry** [comment]
Documentation updated with an example of qgis-plugin-manager about the plugin name.
https://docs.lizmap.com/current/en/install/pre_requirements.html#qgis-server-side

**Comment by androidtv160987** [comment]
Many thanks
