### ISSUE TITLE
[Bug]: ver. 3.6.0 misses lib folder, is it correct?

### ISSUE THREAD

**Issue by pizzuga** [3liz/lizmap-web-client#3378]
### What is the bug?

The zip file of 3.6.0 misses the lib folder. Is it correct for upgrading to this version?

![lizmap3 6 0](https://user-images.githubusercontent.com/46919251/208878549-709dcbae-62f5-470f-9072-3166ec4602be.png)

### Steps to reproduce the issue

Just download from https://github.com/3liz/lizmap-web-client/releases/download/3.6.0/lizmap-web-client-3.6.0.zip and unzip

### Versions

**Versions :**

* Lizmap Web Client : 3.5.7
* Lizmap plugin : 3.9.8
* QGIS Desktop : 3.22.11
* QGIS Server : 3.22.14
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.21.14

### Operating system

debian 11 (CLI only, browser from WINDOWS 11)

### Browsers

Chrome

### Browsers version

108.0.1 (64 bit)

**Comment by nworr** [comment]
libs are now unified in the lizmap/vendor folder (installed using composer).

**Comment by pizzuga** [comment]
okay, I see just now https://docs.lizmap.com/current/en/install/upgrade.html

sorry!
