### ISSUE TITLE
[Bug]: Data table function center and zoom not work

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-web-client#3381]
### What is the bug?

Lizmap 3.6 - Data table function center and zoom not work at table view. At table info is center andy zoom function ok . EPSG 5514. See picture.
In a  Lizmap 3.5.5 is all ok

### Steps to reproduce the issue

![lizmap_tables_error](https://user-images.githubusercontent.com/59457759/209736883-00d7e14b-4044-400e-a883-073d81a0676a.png)

### Versions

Lizmap 3.6
qgisserver 3.10
ubuntu 18.4

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.10

### Operating system

ubuntu 18.4

### Browsers

Firefox, Chrome

### Browsers version

chrome Verze 108.0.5359.125

### Relevant log output

```shell
no error at lizmap log
```

**Comment by Gustry** [comment]
What is the error ?
Does it center and zoom in another part of the map ?
is-there an error in the web-browser console ?

Can you tell us the project projection in QGIS ? The project projection in Lizmap (if you have enabled a base layer or not ? And the layer projection EPSG:5514 ?

**Comment by gisgogo** [comment]
Function zoom zooms in another part of the map, but only once.
Function center does nothing.
No error at web-browser console
Qgis project and all layer at project has EPSG:5514
base layer is not enabled (base layer from lizmap)

**Comment by gisgogo** [comment]
New knowledge. After using the filter function, turn it on and off, the centering and zooming function will start working properly.

**Comment by rldhont** [comment]
Linked to https://github.com/3liz/lizmap-web-client/issues/3474 ?

**Comment by rldhont** [comment]
@gisgogo do you have a link to the project ?

**Comment by gisgogo** [comment]
In lizmap 3.6.2 these functions already work correctly. Problem solved.
