### ISSUE TITLE
[Bug]: Double toolbar visible in the popup

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#3408]
### What is the bug?

There is a double toolbar visible when clicking on a cat.

![image](https://user-images.githubusercontent.com/1609292/211830452-a2992ed2-031e-4e0e-8a56-0fd178b97d50.png)

CC @mdouchin @nboisteault 

### Steps to reproduce the issue

* Visit https://demo.lizmap.com/lizmap_3_6/index.php/view/map?repository=features&project=cats
* Click on a cat, got the popup with **single** toolbar
* Click on another cat (or even the same cat), with a **double** toolbar
* Check if login is triggering the issue ?

### Versions

LWC 3.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Ubuntu

### Browsers

Firefox

### Browsers version

Latest snap

**Comment by nboisteault** [comment]
I can reproduce when clicking twice not once.

**Comment by nboisteault** [comment]
I can't reproduce [here](https://demo.snap.lizmap.com/lizmap_3_7/index.php/view/map?repository=testsrepository&project=feature_toolbar) and [here](https://demo.snap.lizmap.com/lizmap_3_6/index.php/view/map?repository=testsrepository&project=feature_toolbar).
That might be a lol cat bug.

**Comment by Gustry** [comment]
Maybe depending of buttons available in the toolbar ?

Indeed, I can't reproduce on https://demo.snap.lizmap.com/lizmap_3_7/index.php/view/map?repository=testsrepository&project=form_edit_related_child_data

I'm fine to close unfortunately ... :)

**Comment by Gustry** [comment]
I can reproduce again this bug. Still on https://demo.lizmap.com/lizmap_3_6/index.php/view/map?repository=features&project=cats

Still not everytime, but quite a few times.

**Comment by nworr** [comment]
It seems that the featuretoolbar is doubled only when the popup panel is active and with content

can it be relate to the selection.changed event ? 
https://github.com/3liz/lizmap-web-client/blob/35acbd7c458b1cdbd4815b438524d253ee97f4e0/assets/src/components/FeatureToolbar.js#L124

**Comment by Gustry** [comment]
Should be fixed with #4346
