### ISSUE TITLE
Cannot setup Lizmap Plugin with Lizmap Server

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#3409]
## Description

I have QGIS Desktop installed on Windows and Lizmap Web Client on docker. When I try to add register Lizmap Server in Lizmap Plugin an error pops up
![image](https://user-images.githubusercontent.com/1684359/212299937-8b57f0de-50dd-4326-bf1e-bc03d9486506.png)

In Lizmap web client:

![image](https://user-images.githubusercontent.com/1684359/212299287-53ff8931-6157-4858-9ffb-f6c163dad3c4.png)

Log from web:

```
2023/01/13 12:30:36 [error] 30#30: *144 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: pg_close(): supplied resource is not a valid PostgreSQL link resource in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php:202

Stack trace:
#0 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(202): pg_close()
3liz/lizmap-plugin#1 /www/lizmap/vendor/jelix/jelix/lib/jelix/db/jDbConnection.class.php(113): pgsqlDbConnection->_disconnect()
3liz/lizmap-plugin#2 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(69): jDbConnection->__destruct()
3liz/lizmap-plugin#3 [internal function]: pgsqlDbConnection->__destruct()

}
  thrown in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php on line 202" while reading upstream, client: 192.168.2.5, server: lizmap, request: "GET /admin.php/admin/logs HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "192.168.2.12:8090", referrer: "http://192.168.2.12:8090/admin.php/admin/server_information"
192.168.2.5 - - [13/Jan/2023:12:30:36 +0200] "GET /admin.php/admin/logs HTTP/1.1" 200 3067 "http://192.168.2.12:8090/admin.php/admin/server_information" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
192.168.2.5 - - [13/Jan/2023:12:30:39 +0200] "GET /admin.php/admin/server_information HTTP/1.1" 200 3489 "http://192.168.2.12:8090/admin.php/admin/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

## Context
* QGIS version: 3.22.14
* Lizmap version: 3.6.0
* OS: Windows and Ubuntu server

**Comment by ygorigor** [comment]
> From your result :
> 
> > ```
> > "URL": "http://192.168.2.12:8090/index.php/view/app/metadata"
> > ```
> 
> replies with
> 
> > ```
> >   "Error": "Error transferring http://192.168.2.12:8090/index.php/view/app/metadata - server replied: Internal Server Error",
> > ```
> 
> While you tried this URL from your webbrowser, connected as `lizmap` : http://192.168.2.12:8090/index.php/view/app/metadata
> 
> I don't know why the result would be different from QGIS Desktop versus your webbrowser.
> 
> Empty your error log in the LWC admin panel. Still the same error when your request the URL ?
> 
> I'm transferring your issue on Lizmap Web Client.

I tried, but same issue.
In LWC only log is `error	Spatialite is not available`

**Comment by Gustry** [comment]
Can you please check your nginx/apache log ? You should see the request coming with the HTTP code returned ? I fail to understand how the request works in your browser, but not from QGIS.

Can you check with curl CLI ? You must use Basic authentication when sending the request.

Sorry, I am clueless about this issue for now.

**Comment by nworr** [comment]
not sure but Qgis Log has : 
`` "Error Code": "401", ``
Authentification problem ?

**Comment by Gustry** [comment]
In case of wrong login/password, on LWC 3.6.0, I have 

![image](https://user-images.githubusercontent.com/1609292/212328780-9b4f9dfe-e18e-4559-a15a-1ffccec623fd.png)

The message will be slightly different on LWC 3.6.1

**Comment by ygorigor** [comment]
This is the log from nginx when I try to add server

```2023/01/13 16:13:05 [error] 33#33: *688 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: pg_close(): supplied resource is not a valid PostgreSQL link resource in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php:202

Stack trace:
#0 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(202): pg_close()
#1 /www/lizmap/vendor/jelix/jelix/lib/jelix/db/jDbConnection.class.php(113): pgsqlDbConnection->_disconnect()
#2 /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php(69): jDbConnection->__destruct()
#3 [internal function]: pgsqlDbConnection->__destruct()

}
  thrown in /www/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php on line 202" while reading response header from upstream, client: 192.168.2.30, server: lizmap, request: "GET /index.php/view/app/metadata HTTP/1.1", upstream: "fastcgi://172.19.0.7:9000", host: "192.168.2.12:8090"
192.168.2.30 - lizmap [13/Jan/2023:16:13:05 +0200] "GET /index.php/view/app/metadata HTTP/1.1" 500 1293 "-" "Mozilla/5.0 QGIS/32214"

**Comment by nworr** [comment]
Do you have a custom configuration for lizmap users ? (in `var/config/profiles.ini.php` for example) ?

**Comment by ygorigor** [comment]
> Do you have a custom configuration for lizmap users ? (in `var/config/profiles.ini.php` for example) ?

Only for altiProfil module.

**Comment by ygorigor** [comment]
@Gustry I tried now with LWC 3.5 and is working, so the issue is with LWC 3.6

**Comment by Gustry** [comment]
Did you try with `curl` such as 

```bash
curl -u login:password http://192.168.2.12:8090/index.php/view/app/metadata
```

You confirm it works from the webbrowser (both in the administration panel using the UI and with the raw JSON url) ?

**Comment by ygorigor** [comment]
> 

Yes, it works from windows and from linux.

For now, as a temporary solution, I use LWC 3.5 (on another container) to be able to login to lizmap server from lizmap plugin.

**Comment by MeekloX** [comment]
I ran into the same issue after the QGIS plugin was updated from my previous 3.8.3 to the latest 3.10.0

I had to roll back to plugin version 3.9.5 for it to work again. 3.9.6 forward had similar errors.

**Comment by ygorigor** [comment]
@Gustry if I remove line `return @pg_close($this->_connection);`
from `lizmap/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php`
the connection from Lizmap Plugin to LWC is OK.

So it seems that this issue is somehow related to jelix.
May be @laurentj can help.

**Comment by laurentj** [comment]
@ygorigor hi, in your profiles.ini.php, to you have several jdb profiles with same parameters ?

**Comment by laurentj** [comment]
If you have several jdb profiles with same parameters except for the `search_path` parameter, add a parameter `timeout` in each section, with a different value for each section.

**Comment by laurentj** [comment]
It seems you have same issue as https://github.com/3liz/lizmap-web-client/issues/3113#issuecomment-1193939122

**Comment by ygorigor** [comment]
Thank you @laurentj for help. 
The `timeout` helps me.
