### ISSUE TITLE
Print Layout doesn' works properly in LWC 3.6

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#3412]
### What is the bug?

I'm trying to print a layout from my webgis but in the printed page it results as a single layer  instead of the three vector and one raster layers loaded in view

![Schermata del 2023-01-17 11-21-45](https://user-images.githubusercontent.com/12639444/212873041-45e8efc6-542f-4327-b291-5bf77b5b0e1d.png)

### Steps to reproduce the issue

1. set a layout with three vectors and a raster layer in
2. try to print it setting a 1:5000 scale
3. print it in pdf or jpg
I attach the result here

[T_Iassa_ProvaLayout.pdf](https://github.com/3liz/lizmap-web-client/files/10433876/T_Iassa_ProvaLayout.pdf)

(the .jpg come out empy)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.0
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.0
* QGIS Desktop : 3.28.2
* QGIS Server : 3.28.2
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.2

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

Chrome 109.0.5414.74

**Comment by Gustry** [comment]
Can you clarify your problems ?

* Are trying to make a geospatial PDF ? Did it work before in a previous version of LWC and/or QGIS Server version ? I don't know if this was supported before. In the AtlasPrint plugin, I made a ticket a long time ago about this feature request, it's still open if I'm not wrong.
* The raster is missing, where is-it stored ? Does the request was too slow for QGIS Server to fetch the data ?

**Comment by Antoviscomi** [comment]
@Gustry 
1. not a geo pdf but a simple print from the layout print button
2. the raster It's in postgresql (pgraster) ant it works fine for ptinting it in .svg or .png (I attache the two output here)
![T_Iassa_ProvaLayout (1)](https://user-images.githubusercontent.com/12639444/212879578-6b8f4c57-d99a-4a5d-8ed9-1ee8b2299d9c.png)
![T_Iassa_ProvaLayout](https://user-images.githubusercontent.com/12639444/212879588-43c38bf8-3f0c-41d5-aa68-f6bef685125a.svg)

**Comment by Antoviscomi** [comment]
@Gustry 
on 3.6.1, print in .pdf it seems to works fine, so I close this issue
[T_Iassa1_ProvaLayout (1).pdf](https://github.com/3liz/lizmap-web-client/files/10508038/T_Iassa1_ProvaLayout.1.pdf)
thanks a lot
