### ISSUE TITLE
[Bug]: Third party WMS crash project LWC 3.6

### ISSUE THREAD

**Issue by geographit2** [3liz/lizmap-web-client#3413]
### What is the bug?

When creating a project with a third party WMS layer the project crash and display the error message:
'An error occurred while loading this map. Some necessary resource may temporarily be unavailable. Please try again later.
[Go back to the home page.](https://lizmap-test.gispro.com.au/)'

In my internet browser developer tool, I can see that the get capabilities request sent before the web map gets displayed fail.

I am wondering if this is a misconfiguration on my end or bug?

### Steps to reproduce the issue

1. create a qgis project with a 3rd party wms. e.g a layer from https://wxs.ign.fr/parcellaire/geoportail/r/wms?VERSION=1.3.0
2. config the layer with Lizmap plugin for version 3.6
3. publish the qgis project in lizmap
4. open the web map -> error

### Versions

**Versions :**

* Lizmap Web Client : 3.6.0
* Lizmap plugin : 3.9.10
* QGIS Desktop : 3.28.2
* QGIS Server : 3.28.1
* Py-QGIS-Server : 1.8.6
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.1
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22 lts

### Browsers

Firefox, Chrome

### Browsers version

Firefox 89

### Relevant log output

```shell
error.log
2023-01-17 14:59:13     159.196.134.152 error   GetCapabilities result code: 422
2023-01-17 14:59:14     159.196.134.152 error   GetCapabilities result code: 422
2023-01-17 14:59:14     159.196.134.152 error   An error has been raised when loading WMS GetCapabilities: HTTP Code 400
2023-01-17 14:59:14     159.196.134.152 error   GetCapabilities result code: 422


Qgis-server.log
22:00:29 INFO Lizmap[48]: Request headers provided
22:00:29 INFO Lizmap[48]: No lizmap user groups in request headers
22:00:29 INFO WfsOutputExtension[48]: requestReady ran in 0.0s
22:00:29 INFO Server[48]: Trying URL path: '/lizmap/server.json' for '/wfs3'
22:00:29 INFO Server[48]: Trying URL path: '/lizmap/server.json' for '/lizmap'
22:00:29 INFO Server[48]: API Lizmap accepts the URL path '/lizmap/server.json'
22:00:29 INFO Server[48]: Checking API path /server.json for server.json
22:00:29 INFO Server[48]: API Lizmap: found handler server
22:00:29 INFO WfsOutputExtension[48]: responseComplete ran in 0.0s
22:00:29 INFO Server[48]: Request finished in 83 ms
22:00:31 WARNING WMS[48]: Download of capabilities failed:
SSL handshake failed
22:00:31 WARNING [48]: 1 unavailable layer(s) found:
22:00:31 WARNING [48]:  * crs=CRS:84&dpiMode=7&format=image/png&layers=CADASTRALPARCELS.HISTO.2008-2013.PARCELS&styles&url=https://wxs.ign.fr/parcellaire/geoportail/r/wms?VERSION%3D1.3.0
22:00:32 WARNING WMS[48]: Download of capabilities failed:
SSL handshake failed
```

**Comment by Gustry** [comment]
By default, QGIS server considers that if a single layer is invalid, the whole project is invalid.

> 22:00:31 WARNING [48]: 1 unavailable layer(s) found:

So your project is invalid from a QGIS Server point of view, so Lizmap can't display it. You need to configure QGIS Server :
* https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables  `QGIS_SERVER_IGNORE_BAD_LAYERS`

* With Py-QGIS-Server https://docs.3liz.org/py-qgis-server/configuration.html#cache-strict-check

**Comment by geographit2** [comment]
@Gustry , are you able to confirm that Lizmap 3.6 work with WMS on some of your instances?

I don't think the project is invalid from a QGIS server point view.
