### ISSUE TITLE
[Bug]: Datas table if restricted by location

### ISSUE THREAD

**Issue by manogenam** [3liz/lizmap-web-client#3417]
### What is the bug?

In some projects I set "Limit data to extent and layer visibility scales" in lizmap plugin.
It works perfectly in 3.5.8 version but doesn't work with 3.6. (both are installed on my server). I get a empty table.
![image](https://user-images.githubusercontent.com/78609136/213649761-048f8069-bce9-4a4a-a6d6-7cd73abf2f05.png)

### Steps to reproduce the issue

1)Limit data to extent and layer visibility scales" in lizmap plugin and add a layer if it is not done yet
2) Go to the project and display a layer that has an attribute table configured
3) Open attribute table.

### Versions

**Versions :**

* Lizmap Web Client : 3.6.0
* Lizmap Web Client target version : 3.5
* Lizmap plugin : 3.10.0
* QGIS Desktop : 3.22.14
* QGIS Server : 3.22.14
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.1
* QGIS Server plugin lizmap : 3.7.7
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.14

### Operating system

 Debian 11 (bullseye)

### Browsers

Firefox, Chrome

### Browsers version

FIREFOX 109; chrome 109.0.5414.75

**Comment by ygorigor** [comment]
It was already reported here https://github.com/3liz/lizmap-web-client/issues/3194

**Comment by Gustry** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/pull/3423
