### ISSUE TITLE
Mapquest not avalaible

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#342]
Mapquest is not avalaible. Information can be found [here ](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/).
I think a field should be added in lizmap plugin to let people add their key to the service.

**Comment by rldhont** [comment]
fixed 6bd8defb67415a3ca840adca7eccb474233bd555
