### ISSUE TITLE
Load data with lizmap: Parameter Project is mandatory!

### ISSUE THREAD

**Issue by royro** [3liz/lizmap-web-client#343]
Hi,
i'm trying to test lizmap to load data/document using lizamp in edit mode,
i'm using a postgis layer with a field "lod" (load data) set as "Flie Name" in QGIS;
the form is working in Lizmap but when i save i get this message:

The parameter project is mandatory !

where should I set this parameter to make it work?

thanks, Roy.

**Comment by royro** [comment]
I found out that "Short name" is to be set in QGIS Project properties, "OWS Server" tab
now it's working, 
Thanks again, Roy.

**Comment by rldhont** [comment]
Thanks for the feedback, it's an issue

**Comment by rldhont** [comment]
But there is no link between
> The parameter project is mandatory !
and 
> "Short name" in QGIS Project properties
Has you more explaination ?

**Comment by royro** [comment]
> But there is no link between ... Has you more explaination ?
So it must have been a coincidence that it started to work
after I added the OWS "Short name"; maybe because I reloaded
the project... i'm not able to reproduce the issue, if it'll happen again
maybe i will understand ...
thanks, roy.

**Comment by rldhont** [comment]
I have meant, that lizmap never used the short name of the project. I think it's a coincidence. Maybe just a problem of memory that the reload corrected it.

**Comment by gerald2545** [comment]
same error today. I think (pretty sure) this error arise when te file is too heavy.
with the same form, loading a 17MB file does not succeed and the "The parameter project is mandatory !" is displayed. Loading a 2MB file succeeded without problem.

maybe the error message could be more explicit...
will try to investigate

lizmap web client 3.1.14
qgis server 2.18

**Comment by WouterVermeyenSBE** [comment]
I have had this issue today. We had trouble uploading more than 2mb, we raised the limit to 20mb but were limited at 8mb. We will try to get around it by further raising the limit.

**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 4.3.14
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>
