### ISSUE TITLE
[Question]: Versions of QGIS plugins are not found or not recognized.

### ISSUE THREAD

**Issue by Forstrevier** [3liz/lizmap-web-client#3437]
### What is the question?

Hello. 
I have already since 3.6.0 the problem that the QGis Server Plugins are not recognized. The backend of Lizmap is operable. But I cannot load any maps. Until version 3.5.8 everything worked. I manage the plugins via qgis-plugin-manager. This shows the installed plugins with their version numbers. I can't figure out where Lizmap has a problem here. The path to the plugins is set, I have gone through countless hints on the internet. But I can't find a solution to my problem. Does anyone have a spark of idea or even a solution? Thanks.
![screenshot](https://user-images.githubusercontent.com/117937935/214461253-8f9df0fa-3ffa-4543-a5b8-0239b8533472.jpg)
![Groß (Bildschirm­foto 2023-01-25 um 02 30 36)](https://user-images.githubusercontent.com/117937935/214461294-a79263ab-f7bd-4b75-910c-bec875e31ea1.jpeg)

### Versions

3.6.0, 3.6.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.26.3

### Operating system

Ubuntu 20.04

### Browsers

Firefox, Chrome, Safari

### Browsers version

108.0.2

**Comment by Forstrevier** [comment]
Thanks for the tips. I have removed all plugins except the "Lizmap server" plugin and restarted apache2. After that the administration interface looked exactly the same as before. So 3 lines without plugin name, then version not found and the middle line with the request to update the plugin.

If I then also remove the plugin "Lizmap server", according to qgis-plugin-manager no plugin is installed anymore. And the administration interfac shows the following (see below). If I reinstall the "Lizmap server" plugin, the display looks like before (see above).
<img width="1149" alt="Bildschirm­foto 2023-01-25 um 10 21 08" src="https://user-images.githubusercontent.com/117937935/214525504-6d14209d-cd94-469d-b3f2-1caf5eb30d69.png">

**Comment by Forstrevier** [comment]
This is how the administration interface looks under Lizmap 3.5.8. Here the plugin names are shown but no version number. However, loading the maps works fine in the Lizmap version.
<img width="1147" alt="Bildschirm­foto 2023-01-25 um 10 27 06" src="https://user-images.githubusercontent.com/117937935/214527129-b4b03206-3189-4172-864f-a375b6dab85a.png">

**Comment by nworr** [comment]
did you set `QGIS_SERVER_LIZMAP_REVEAL_SETTINGS ` on your qgis-server conf ?

https://docs.lizmap.com/current/en/install/pre_requirements.html#qgis-server-side

**Comment by Forstrevier** [comment]
Yes, i did.

**Comment by Forstrevier** [comment]
<img width="481" alt="Bildschirm­foto 2023-01-25 um 10 35 27" src="https://user-images.githubusercontent.com/117937935/214528717-b8a9ce0b-6ee4-4f30-927a-1b5b25fa9f9a.png">

**Comment by Gustry** [comment]
Without the environnement variable, you wouldn't be able to have the plugin table.

It's strange that "lizmap server" is declared "not found" while it's the plugin it self generating this status.

> I have removed all plugins except the "Lizmap server" plugin and restarted apache2

You said you have restarted apache2. But in your first screenshot, you have installed py-QGIS-Server 1.8.5. These two are not related. Restarting apache2 is not going to reload Py-QGIS-Server. Can you confirm if you are using Py-QGIS Server or not (FCGI). In other words, did you set a Lizmap API URL in your Lizmap administration panel, "Lizmap configuration" ?

Please check QGIS server logs, especially when visiting this web page. You should see the request "lizmap/server.json" coming with some other logs.

When logged as admin, please visit the page : INSTANCEURL/index.php/view/app/metadata and report the `qgis_server_info` section.

**Comment by Gustry** [comment]
By checking the code of the server Lizmap server plugin, I think you have installed Py-QGIS-Server, but you are not using it. Therefore the Lizmap QGIS server plugin is confused about how to fetch plugins installed (using Py-QGIS-Server settings or not)

https://github.com/3liz/qgis-lizmap-server-plugin/blob/master/lizmap_server/server_info_handler.py

Please double check if you are really using Py-QGIS-Server. Did you setup a Lizmap API url in your lizmap configuration ?
If not, either remove Py-QGIS-Server, or change your QGIS Server settings to use it.

**Comment by Forstrevier** [comment]
You are angels. Problem solved. Thank you.
<img width="1143" alt="Bildschirm­foto 2023-01-25 um 11 16 06" src="https://user-images.githubusercontent.com/117937935/214537562-6d61447a-21bc-41f2-9aca-57a70b9d6d83.png">

**Comment by Gustry** [comment]
Thanks for the feedback.

* [x] The new version of the plugin will check if Py-QGIS-Server is really used, not only installed on the server. [Version 1.3.0 released this morning](https://github.com/3liz/qgis-lizmap-server-plugin/releases/tag/1.3.0)
* [ ] We could double check this with LWC server settings, and the result from the JSON in the plugin.
