### ISSUE TITLE
In LWC 3.6.1 the dasboard left panel doesn't contain links to Server informations and QGIS projects anymore

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#3443]
### What is the question?

I noticed that, in LWC 3.6.1 the Admin dasboard left panel doesn't contain the links to server informations and QGIS projects anymore as was in 3.6.0. Is this a mistake or a 'by design' choose? 

Thanks for response

![Schermata del 2023-01-26 09-59-47](https://user-images.githubusercontent.com/12639444/214796087-128d9f34-efc9-4913-83d6-0954c8927568.png)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.1
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.0
* QGIS Desktop : 3.28.2
* QGIS Server : 3.28.2
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.3.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.2

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

109.0.5414.119

**Comment by mdouchin** [comment]
It is not made on purpose but seems to be a issue when upgrading.

It seems the upgrade file has not been run during the upgrade: https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/admin/install/upgrade_newAclRights.php
This scripts should have added some new rights, and give the "admins" group the new rights.

In the changelog, it corresponds to the sentence 
> A lot of new rights in the administration panel have been added to have a publisher group. It allows you to better distinguish between administrators and QGIS publishers.

When you migrate from 3.5.X to 3.6.0, have you followed these steps 
https://docs.lizmap.com/current/en/install/upgrade.html#upgrading-from-lizmap-3-5-version
especially ran the line

```bash
php lizmap/install/configurator.php
```
before

```
php lizmap/install/installer.php
```
?

Some changes have been made and this "configurator" command is now mandatory.

We could help you run some commands to fix your issue depending on your installation process.

**Comment by Antoviscomi** [comment]
@mdouchin 
right, after run php configurator.php all work fine!
thank you very much
I close this
Cheers
