### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by andremano** [3liz/lizmap-web-client#345]
I am trying to install lizmap web client 3 in a Ubuntu-64 xenial (16.04) machine. I am having a problem I am not being able to solve. When I try to test my lizmap installation on http://localhost/lizmap-web-client-release_3_0/lizmap/www/ the response I get is a **process(new jClassicRequest());** 

I suppose this means I dont have all the dependencies I should. I have PHP7 and these are the dependencies I installed: **apache2 php curl php-curl php-sqlite3 php-pgsql php-gd php-xml**

Any idea on what could be the problem?
Thanks

**Comment by rldhont** [comment]
@andremano it seems that your PHP is not interpreted, are you sure your apache server is well configured for php ?

**Comment by andremano** [comment]
Thanks for the reply.

Not really sure about that. I only checked if Apache is running but havent done any configuration on Apache itself. Are there instructions somewhere on how to do that?

**Comment by rldhont** [comment]
@andremano you probaby have the same issue as in #329 
I'm closing this issue, to continue the discussion on #329

**Comment by rldhont** [comment]
You can also take a look at the documentation https://github.com/3liz/lizmap-documentation/blob/master/source/install/linux.rst
test it and improve it

**Comment by andremano** [comment]
@rldhont thanks, will follow your suggestions
