### ISSUE TITLE
Locate by layer - geometry issue

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#346]
Hello everybody. 
Using Lizmap 3.0.1 on Debian 8.5 server i found a strange issue using locate by layer. My layers (cadastre and other urbanistic stuff) was published in WMS but when using locate by layer, geometries won't be focused on and they're not correctly highlighted even if requested in plugin. 

Any solution? 

Thanks 
![issue](https://cloud.githubusercontent.com/assets/20582012/17104150/ea403b7e-5281-11e6-99cf-517408a81fbc.JPG)

**Comment by nboisteault** [comment]
Check in OWS tab that your layer is accessible via WFS and that you propose the SCR of your base map.

**Comment by virtusmankind** [comment]
As you can see in attached image, my layers is accessible via WFS and, even if I do not use a basemap, I add all SR in restriction tab. It seems to be really strange!!

Thanks!

![issue2](https://cloud.githubusercontent.com/assets/20582012/17106683/8d108c5a-528c-11e6-9b70-afcf11aa96d9.JPG)

**Comment by nboisteault** [comment]
Did you check that all geometries are valid?

**Comment by virtusmankind** [comment]
With cadastral parcel, it's hard to check over 10000 geometries. So i extract 2 geometries, try to validate them with Geometry Checker plugin, Topology Checker panel, and with "Check Geometry Validity" built in plugin. No errors found but the issue is the same
![issue3](https://cloud.githubusercontent.com/assets/20582012/17133168/53efe918-5325-11e6-9759-a0ffccb93767.JPG)

**Comment by rldhont** [comment]
Hi @virtusmankind it's more an issue in the WFS.
Can you check the GetFeature Request of parcelle layer ?
It seems you have a problem with rounded number.

**Comment by virtusmankind** [comment]
Do you mean in Server OWS Tab in "GetFeatureInfo"?

**Comment by virtusmankind** [comment]
Hi. 
Probably I found the issue. 
I check GetFeatureInfo value and set it to 8 instead of 2, but nothing changed. Then I try to work with SR and that's the issue. I was working with EPSG:23033 (ED50 - UTM33N) or EPSG:32633 (WGS84 - UTM33N).
Locate by layers seems to work correctly **only** with **EPSG:4326 (WGS84)** independently of GetFeatureInfo value (it works both with 2 and 8).  

P.s. I notice that in Demo repository (Montpellier - Transports) Sous-Quartiers locate do not work and the layer (VilleMTP_MTP_SousQuartiers_2011.shp) should be in EPSG:2154.

**Comment by rldhont** [comment]
Which QGIS Server version do you use ?

**Comment by rldhont** [comment]
GetFeature request is not GetFeatureInfo request.
Locate by layer uses WFS GetFeature Request to get geometries in GeoJSON format.
Do you have the same issue with Montpellier demo ?

**Comment by virtusmankind** [comment]
I'm using QGis Server 2.16. 
I have a different issue with Montpellier demo, locating Sous-Quartiers, as I wrote. 
I cannot localize any item, every action locate me near the coast at south of the city (same issue for other layers in other custom projects, it locate me away from my geometries)
I see that the layer used (VilleMTP_MTP_SousQuartiers_2011.shp) is not in EPSG:4326 but in EPSG:2154.

Hoping to help you to improve Lizmap project, thank you

![demo issue](https://cloud.githubusercontent.com/assets/20582012/17182582/3ef48532-5424-11e6-9734-8e1ed101afa1.JPG)

**Comment by virtusmankind** [comment]
**Problem completely solved**, uninstalling default QGIS Server 2.16 (installed with deb http://qgis.org/debian jessie main repo) and downgrading it to QGIS Server 2.14.4 (installed from there: https://packages.debian.org/sid/qgis-server).

That correct even a print error 500 I had before.

Hope it helps other users. 

Thanks guys!

**Comment by geoek** [comment]
Same behaviour with Qgis Server 2.16. Locate by layer locate to a wrong location.

**Comment by rldhont** [comment]
I found the issue: https://github.com/3liz/lizmap-web-client/issues/346#issuecomment-235815153
QGIS Server 2.16 always return GeoJSON in EPSG:4326. Because of this we have to add some code to smell the CRS of GeoJSON.

**Comment by pieri70** [comment]
Hello
I downloaded today the master release and this issue is still there.
Is there some way tu get rid by qgis desktop side?
I have all my layers in 3857 and I set project CRS to 4326 (OTF) but locate by layer and locate by attribute table still places me in a wrong site..
Thanks

**Comment by mdouchin** [comment]
Could you pass us an archive containing the project with some data ? Obviously please keep the whole small and as simple as possible to reproduce the issue.

**Comment by rldhont** [comment]
The problem is that Lizmap Web Client does not work yet with QGIS Server 2.16!

In QGIS Server 2.14 and earlier, the WFS always returns data in the layers CRS. In QGIS Server 2.16, the WFS always returns data in EPSG:4326.
Lizmap Web Client has been made to use WFS data in the layer CRS not always in EPSG:4326.

It's a bug and it's not fixed yet.
