### ISSUE TITLE
[Bug]: Display more than 10 children not working

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#3463]
### What is the bug?

I would like to display more than 10 chidren in a table with a relation, so i  increase to 20 "max features in popup" in the lizmap plugin. But nothing changes in lizmap, there is always only 10 childs displayed.
I also tried to decrease in order to display only one child, but lizmap still displays 10 children...

I looked into the .cfg config file and I noticed that the "popupMaxFeatures" parameter is set to 20 for the parent table like I checked in the plugin.
But if I change manually this parameter for the children table, it works in Lizmap.

Wouldn't there be a parameter assignment bug between parent table and children table ?

### Steps to reproduce the issue

1. Create a relation between 2 tables
2. In the lizmap plugin, display popup for the 2 tables
3. Check "Display children"
4. change "max features in popup" value 
5. On lizmap webclient, there is no effect 

### Versions

**Versions :**

* Lizmap Web Client : 3.5.8
* Lizmap Web Client target version : 3.5
* Lizmap plugin : 3.10.0
* QGIS Desktop : 3.22.6
* QGIS Server : 3.22.6
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.1
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 10

### Browsers

Chrome

### Browsers version

Version 109

**Comment by Gustry** [comment]
The newest version of the Lizmap desktop plugin released this morning reverted this UI change. This spinbox was for the total number of features (parents) in the popup dock.

Version 3.10.1

So I guess the problem is solved, because you can now change it in the children layer directly ?

**Comment by Cww7** [comment]
Yes I can see all my children now ! Great !!
 👍
