### ISSUE TITLE
[Question]: I have a problem with using not included CRS in Lizmap 

### ISSUE THREAD

**Issue by WouterVermeyenSBE** [3liz/lizmap-web-client#3464]
### What is the question?

I am having a problem the Locating tool and other zoom functions like when I use the attribute table. The mapzoom zoom a number of units to the east and the south of whatever position it needs to be. I think it is a result of the non-included ESPG-28992 system my project uses. 

I have added 2 files a php and js in two locations:

`./lizmap/vendor/proj4php/proj4php/src/proj4php/defs/`
```php
<?php
return [
    "EPSG:28992" => "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs ",
];
```

`./lizmap/www/assets/js/Proj4js/defs/`
```
Proj4js.defs["EPSG:28992"] = "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs";
```

However this doesn't solve the problem, is there an action I am missing?

### Versions

**Versions :**

* Lizmap Web Client : 3.6.1
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.14
* QGIS Server : 3.22.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.10

### Operating system

Windows 10

### Browsers

Chrome

### Browsers version

109.0.5414.120

**Comment by rldhont** [comment]
Linked to https://github.com/3liz/lizmap-web-client/issues/3474

**Comment by WouterVermeyenSBE** [comment]
Hi, I still notice a problem with the locating tool. I have had time again to follow up on the problem I experienced and the zoom is still of like I mentoined orginally. I noticed however that if I changed my project crs in QGIS to 4326 then the locating tool would zoom correctly. This is however not a good solution as I need to work in EPSG:28992 and if I transform the data the visual result is warped. Do you have any advice?
