### ISSUE TITLE
Let new users create an account

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#347]
Hi,
I'd like to know if new users can create an account or only an admin can do it.
I tried to select 'yes' for the 'create a new user' parameter for Anonymous group in groups rights menu but it did not work.

**Comment by rldhont** [comment]
No, but users can request an account. The admin has to validate it.

**Comment by nboisteault** [comment]
Thank you must I must be blind I haven't found where a user can ask an account.

**Comment by rldhont** [comment]
You can activate it in the lizmap configuration page of the back office.
