### ISSUE TITLE
Possibilité de réduire les groupes

### ISSUE THREAD

**Issue by samuelpriou** [3liz/lizmap-web-client#349]
#Se laisser la possibilité de ne pas déployer le ou les groupes

En effet, il serait intéressant de pouvoir paramétrer les groupes en ne déployant pas par défaut les couches présentes.

Exemple ici 

![groupes](https://cloud.githubusercontent.com/assets/9743288/17335205/6fd8f76e-58d9-11e6-8cc4-c5b11becd9af.jpg)

**Comment by geoek** [comment]
Bonjour,
Tu trouveras la solution ici : https://github.com/3liz/lizmap-web-client/issues/245

Pour la suite, il serait intéressant de permettre ce paramétrage dans le réglage des layers, via le plugin Qgis.

**Comment by RaphaelChochon** [comment]
Bonjour à tous,

Tout d'abord, merci à 3Liz pour tout ce travail que nous sommes en train de tester ! Pratique, rapide et super fonctionnel, rien de mieux pour être productif :+1:

Merci @geoek pour le lien vers cette issue qui nous avais échappée, ça fonctionne bien !

Chez nous :
```
rep4
  |--media
     |-- js
        |-- mon_project
            |-- extend.js
```

Qui contient : 
```
lizMap.events.on({
	uicreated: function(e) {
		$('#group-limregl td a.expander').click();
		$('#group-admin td a.expander').click();
	}
});
```

**Résultat**
![groupe](https://cloud.githubusercontent.com/assets/17319578/17357062/28fb9798-595b-11e6-9566-321478ddd818.JPG)


C'est vrai qu'il serait encore mieux d'avoir ce paramétrage dans le plugin, mais déjà ça fonctionne ici :smile:

**Comment by geoek** [comment]
Nickel ! Ca permet de s'entrainer à l'injection de son propre javascript dans lizmap :)
