### ISSUE TITLE
LWC is lacking 'relation reference' widget

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#350]
The 'relation reference' widget is not implemented. It is not the easiest one to implement :-) 
In QGIS it is very handy to make combobox which filter choices step by step.
An example : 

Configuration : 
![image](https://cloud.githubusercontent.com/assets/2145040/17441448/65a69652-5b31-11e6-8572-2c68e3f61753.png)

Result : 
![image](https://cloud.githubusercontent.com/assets/2145040/17441511/ac612080-5b31-11e6-9c30-2d3896abd2a0.png)

![image](https://cloud.githubusercontent.com/assets/2145040/17441527/bd496f2e-5b31-11e6-994e-64316eb2129f.png)

**Comment by nboisteault** [comment]
FYI I'll try to develop this feature.

**Comment by nboisteault** [comment]
First question : should I create one qgisFormControl by menulist or should I make qgisFormControl able to handle multiple menulist?
I think the second choice is best but I'd like to have your opinion @mdouchin and @rldhont

**Comment by nboisteault** [comment]
I have to use jFormsControlGroup I guess. Am I right?

**Comment by josemvm** [comment]
how long can we wait for this essential feature for edition on lizmap?
this enhancement would be greatly appreciated if it could be integrated in upcoming 3.4

thanks

**Comment by Gustry** [comment]
It's already supported. It's written in the documentation : https://docs.lizmap.com/next/en/publish/lizmap_plugin/edition.html?highlight=relation%20reference

> Only the following tools are supported: Text edit, Classification, Range, Value Map, Hidden, Check Box, Date/Time, Value Relation, Relation Reference.

**Comment by Gustry** [comment]
This ticket is only talking about "relation reference" in general. We should list features which are missing from Relation reference widget.

**Comment by nboisteault** [comment]
Some sponsored developments improving this widget are coming.
