### ISSUE TITLE
[Bug]: Theme/VisibilityPreset error (confusion between expanded and visible)

### ISSUE THREAD

**Issue by TeoGoddet** [3liz/lizmap-web-client#3519]
### What is the bug?

When selecting a theme in a project with layer groups, sometimes the visible layer are not correct.

### Steps to reproduce the issue

-

### Versions

3.5.8

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 20.4

### Browsers

Chrome

### Browsers version

Chrome 102

**Comment by TeoGoddet** [comment]
I investigated the problem and 

It seems that qgis store both if a layer should be expanded and if it should be visible.
![image](https://user-images.githubusercontent.com/9885447/221202373-de8a866a-1816-4224-a248-36212fba3d10.png)
(.qgs file content)

While lizmap consider all layers in the theme to be visible
![image](https://user-images.githubusercontent.com/9885447/221202758-a7f6cfa8-214a-4712-bcaf-6154c139981a.png)
(js dump of lizMap.config.themes['essentiel_google_sat'].layers)

I think that the visible attribute should be added here https://github.com/3liz/lizmap-web-client/blob/69f531559edb06549aa45804a4bf3ac3b6ad298a/lizmap/modules/lizmap/classes/qgisProject.class.php#L656
and an if condition should be added in switcher-layers-actions.js

If the fix is confirmed, I can propose a PR in the following days.

**Comment by TeoGoddet** [comment]
Hello, I'm really up to propose a fix if you confirm the problem. 
Have a nice day !

**Comment by nboisteault** [comment]
@TeoGoddet Hi, could you give us a link to a project or make a simple project with portable data which illustrate the issue?

**Comment by TeoGoddet** [comment]
[test-lizmap.zip](https://github.com/3liz/lizmap-web-client/files/11283567/test-lizmap.zip)

**Comment by nboisteault** [comment]
Thanks @TeoGoddet !

In `<visibility-preset>`, I've never had a project with a layer having the parameter `visible=0`. If the layer was visible, it was in `<visibility-preset>` with  `visible=1`. That's why I did not looked at this parameter. I saw that your project is from QGIS 3.26 so the behavior might have changed since 3.22 or maybe I missed the way to have this behavior. @TeoGoddet did you do something special?

**Comment by nboisteault** [comment]
@rldhont @laurentj This PR changes `/lizmap/modules/lizmap/classes/qgisProject.class.php` but it should change `/lizmap/modules/lizmap/lib/Project/QgisProject.php` to work. Why are there those two similar files? Also it should not have been merged yet as unit tests can't pass.
