### ISSUE TITLE
[Question]: Postgis Layer not Working Project

### ISSUE THREAD

**Issue by webgis87** [3liz/lizmap-web-client#3541]
### What is the question?

Hello everyone, I'm having significant difficulties using layers in postgres.
I don't want to save the credentials within the QGIS Project and would therefore like to use a pgservice file, as indicated by the official QGIS_SERVER guide, however without success someone would be kind enough to show me all the steps to use a pgservice to authenticate lizmap to the project.

If someone please show me precisely all the steps including any checks on postgres. Postgres opens correctly from QGIS on a different pc than the one where the database and lizmap resides, lizmap postgres are on the same system

### Versions

QGIS322

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

ubuntu 22.04

### Browsers

Microsoft Edge

### Browsers version

110

### Relevant log output

```shell
2023-03-11 11:02:55	5.170.164.85	error	GetCapabilities result code: 500
2023-03-11 11:02:55	5.170.164.85	error	GetCapabilities result code: 500
2023-03-11 11:02:55	5.170.164.85	error	An error has been raised when loading WMS GetCapabilities: HTTP Code 400
2023-03-11 11:02:55	5.170.164.85	error	GetCapabilities result code: 500
```

**Comment by rajandmk** [comment]
I was having similar problem. This is how I managed to use the load the layers from PostgreSQL:

Configuration that I have:
[QgisServer+Lizmap+Postgres+Apache2] -- **installed on a remote linux server** (eg: `testlizmap.com`)
I followed [this](https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#installation-on-debian-based-systems) guide on how to install qgisserver. under virtualhost conf it was referring to `/home/qgis/.pg_service.conf`

```
# Set pg access via pg_service file
SetEnv PGSERVICEFILE /home/qgis/.pg_service.conf
```

I therefore created that file and saved the login credentials there.
[example](https://github.com/3liz/lizmap-web-client/issues/1638#issuecomment-627872662):
```
[qgistest]
host=localhost
port=5432
user=etienne
dbname=qgistest
password=my#123password!
```
I then restarted the apache service.

---
Now on my **local windows computer** where qgis desktop is installed, I followed this [guide](https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#postgresql-service-connection-file) to add an Environment Variable named `PGSERVICEFILE` with the path - e.g. `C:\Users\John\pg_service.conf`. 
In this pg_service.conf i used same service name as above but changed the `host=testlizmap.com` (as that is where my PostgreSQL database are located).
Then on the qgis desktop I created a new PostgreSQL connection using service `qgistest`. 

This worked for me. The layers added from database is visible from lizmap. But I am still confused as if this is the correct workflow one has to follow when `pg_service.conf` is involved. I would be grateful if some of you could comment on this way of storing password as plain text files in server where qgisserver is installed and also on the desktop where qgis project files are edited.

**Comment by Gustry** [comment]
Can you explain what you did to fix your issue ? Maybe someone will find your question with a search engine with a similar issue.

**Comment by wojtek19022** [comment]
@Gustry I think that @webgis87 might have had a similar problem to me. I didn't set up previously enviromental variable to pg_service.conf file on my qgis server apache service. After I did it and reloaded, it magically started working 💃

**Comment by Gustry** [comment]
Thanks @wojtek19022 . Indeed, that's why the safeguards in the plugin has been added "prevent PG service" even if we recommend it 😉
