### ISSUE TITLE
[Question]: Problem with Lizmap and Qgis server on Ubuntu 22.04

### ISSUE THREAD

**Issue by abrousseau89** [3liz/lizmap-web-client#3544]
### What is the question?

Good morning,

I'm trying to deploy an Ubuntu 22.04 server with Lizmap 3.6 and Qgis Server. After a lot of hassle I now access the Lizmap interface.

When I check in the administration of Lizmap I have this message:

`QGIS Server
We cannot have the details on the installation of your QGIS server (version, extensions etc.).`

and in the Lizmap Logs I have this:

`023-03-13 08:31:42    192.168.20.117    error    QGIS Serveur doit être mise à jour au moins avec la version 3.10pour cette version de Lizmap Web Client.
2023-03-13 08:31:42    [2]    Undefined array key "plugins"    /var/www/lizmap-web-client-3.6.2/lizmap/modules/lizmap/lib/Server/Server.php    54

2023-03-13 08:31:42    [2]    Trying to access array offset on value of type null    /var/www/lizmap-web-client-3.6.2/lizmap/modules/lizmap/lib/Server/Server.php    54

2023-03-13 08:31:42    [2]    Trying to access array offset on value of type null    /var/www/lizmap-web-client-3.6.2/lizmap/modules/lizmap/lib/Server/Server.php    54

2023-03-13 08:31:42    192.168.20.117    error    L'extension lizmap_serverdoit être mise à jour.`

after checking on Ubuntu, I am however using the latest versions and my configuration seems correct... Maybe an oversight somewhere?

thank you for your information

### Versions

Versions :

 Lizmap Web Client : 3.6.2
 Lizmap Web Client target version : 3.6
 Lizmap plugin : 3.10.1
 QGIS Desktop : 3.22.10
 QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

Firefox 110

**Comment by nboisteault** [comment]
Thanks @abrousseau89 for your report. We reproduce the bug and we'll fix it soon.

**Comment by rldhont** [comment]
@abrousseau89 to be sure your QGIS Server install is complete for Lizmap Web Client 3.6, did you find in QGIS Server logs this line:
```
Loaded plugin lizmap_server
```

**Comment by nboisteault** [comment]
@abrousseau89 I reproduced partly your issue but it might due to another problem. Please be sure that you installed the Lizmap plugin **server side**.

**Comment by rldhont** [comment]
@abrousseau89 can you provide the messages found from Lizmap Web Client administration interface in the "Server Information" panel.

**Comment by abrousseau89** [comment]
Indeed the problem comes from the Lizmap Plugin. I installaed this one correctly and it works. Thanks !
