### ISSUE TITLE
[Question]: Errors in logs and no map

### ISSUE THREAD

**Issue by abrousseau89** [3liz/lizmap-web-client#3546]
### What is the question?

Hello, 

I systematically have errors in the Lizmap Server logs. When I try to display my map, which never displays 

`2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	An error has been raised when loading WMS GetCapabilities: HTTP Code 400`

My map are simple. 
Even a simple map does not display.

On each try, I was never able to see the map. 

`An error occurred while loading the map. Required resources may be temporarily unavailable. Please try later.`

My map are visible in the list of projects

192.168.20.118 is my Ubuntu server with Lizmap 
192.168.20.117 is my personnal computer on the same network

Do you have an idea ?

Best regards

### Versions

**Versions :**

* Lizmap Web Client : 3.6.2
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.10
* QGIS Server : 3.22.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 1.3.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.7

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

Firefox 110

### Relevant log output

2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	GetCapabilities result code: 500
2023-03-14 14:24:32	192.168.20.117	error	An error has been raised when loading WMS GetCapabilities: HTTP Code 400

**Comment by nworr** [comment]
quick guees : it seems lizmap can't talk with  Qgis server

does the server_information page show full qgis server info ?
`http://yourhost/lizmap/admin.php/admin/server_information`

it should look like this

![Screenshot 2023-03-14 at 18-13-02 Administration](https://user-images.githubusercontent.com/43475951/225086668-9e913e75-a382-47b9-b8b8-269d17cebbc8.png)

**Comment by abrousseau89** [comment]
Yes i see that

![lizmap](https://user-images.githubusercontent.com/127750775/225125148-a4f1db0d-9841-41ac-8629-12762aed2686.png)

**Comment by Gustry** [comment]
You must check your QGIS server logs (and maybe increase your log level in QGIS) (especially when hitting the GetCapabilities URL)

**Comment by abrousseau89** [comment]
Thanks for your reply. 

In error log i see that : 

`"Accept" :  "*/*"
"Host" :  "127.0.0.1"
"User-Agent" :  "Lizmap"
Logged warning: Loading a file that was saved with a newer version of qgis (saved in 3.22.10-Białowieża, loaded in 3.22.7-Białowieża). Problems may occur.
Headers:
`
i found qgis.demo.acces.log but nothing with GetCapabilities error

Another log file for QgisServer in Ubuntu ?

**Comment by nworr** [comment]
accoding to your log qgis server can't connect to x server
is xvfb installed and configured ? see [qgis docs](https://docs.qgis.org/3.28/en/docs/server_manual/getting_started.html#xvfb)
