### ISSUE TITLE
Modifying the repository V3.1pre.0001

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#355]
Hi Guys, I am a new user of lizmap-web-client. I have two (maybe) related issues. When in 'Lizmap configuration' > 'Modify the repository' if i make a change and try to save i get the error:-

Error 500:A technical error has occured. Sorry for this trouble.

Also i have configured the repository but the qgis project will not appear under the 'Projects' tab nor will the Montpellier Demo. Any ideas what the problem might be?

Thanks,

Paul Shapley

**Comment by mdouchin** [comment]
Which operating system are you using ? Linux or Windows ? Have you looked at the file 
https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md

**Comment by shapley** [comment]
Thanks...I just installed v3 and it works ok on Ubuntu 16.04
