### ISSUE TITLE
[Bug]: dataviz - can't display filtered plot

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#3559]
### What is the bug?

the plugin shows the filltered plot for each selected feature:

![imagem](https://user-images.githubusercontent.com/10053874/226144317-4fd71c58-82ef-4b4a-ae8c-2456764862eb.png)

but the LWC can't rendering the corresponding filtered plot when the user select a feature with a locate by layer tool:
![imagem](https://user-images.githubusercontent.com/10053874/226144727-ec55fc33-4916-4299-8a94-99e8d38b633e.png)

### Steps to reproduce the issue

- create a qgis project from scratch, add a spatial layer and a table with a statistical values
- create a relation between two layers
- configure the locate by layer tool with spatial layer
- configure the dataviz tool using a pie chart or a bar chart (like above)
- publish the project

### Versions

**Versions :**

* Lizmap Web Client : 3.6.2-pre.5997
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.11.0
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Firefox 110.0.1

**Comment by josemvm** [comment]
any trick is missing to make it work?
thanks

**Comment by josemvm** [comment]
maybe related to https://github.com/3liz/lizmap-web-client/issues/3101

can someone test it and give me feedback please?

**Comment by Gustry** [comment]
Can you please detail why you are closing the issue ? I guess you found why ?

In case of someone finding this issue later with a search engine etc. Even for us, it's nice to know what was wrong.
