### ISSUE TITLE
[Bug]: Export format list not complete when adding the "download button" in custom pop-ups

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3561]
### What is the bug?

The download/export list has been already expanded with the proper QGIS Server plugin

![image](https://user-images.githubusercontent.com/1951107/226378958-10b46f68-b377-45db-b533-cff7da2f8c70.png)

but regardless the download button in a custom pop up only shows the (original) list of formats:

![image](https://user-images.githubusercontent.com/1951107/226379235-dc838859-2fa7-4207-a913-cdb01324babc.png)

### Steps to reproduce the issue

See above.

### Versions

QGIS Desktop/Server, latest 3.28
LMWC latest 3.6
LM plugin latest 3.11

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by Gustry** [comment]
It has been done on purpose.

> As discussed, GPX, KML are more appropriate for this kind of download.
Download with more GIS formats are still available in attribute table.

https://github.com/3liz/lizmap-web-client/pull/2889#issuecomment-1083011535

Can we close @gioman ?
I don't think we (3Liz) will touch that.

**Comment by gioman** [comment]
> purpose

then it is ok also for me :)
