### ISSUE TITLE
Calc is Possible?

### ISSUE THREAD

**Issue by webgis87** [3liz/lizmap-web-client#3569]
### What is the question?

Hello everyone, I wanted to know if it was possible to perform calculation operations on Lizmap. Or use actions to run python scripts, and how can I achieve that. For example, to calculate the hydraulic invariance in a point or in an area

### Versions

lizmap 3.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

ubuntu server

### Browsers

Microsoft Edge

### Browsers version

92

**Comment by mdouchin** [comment]
You can, with actions and some PostgreSQL "magic". See : https://docs.lizmap.com/3.6/en/publish/configuration/action_popup.html
Improvements are coming in future 3.7.0: https://github.com/3liz/lizmap-web-client/pull/3343

**Comment by webgis87** [comment]
Many thanks you. It possibile tutorial/coure buy?

**Comment by Gustry** [comment]
Thanks for your message 😉

Did you check and try the demo about actions ? https://demo.lizmap.com/lizmap/index.php/view/map?repository=features&project=fire_hydrant_actions

You can download the ZIP and explore it to see how it's done on your own server.

>  in particular the one to recall a python command and execute it, in the same way as the MapBuilder.

Actions are only running SQL commands, it's not possible to run Python commands straight. (if you really want to use Python, it would be with [PlPython](https://www.postgresql.org/docs/12/plpython-util.html)...) :/

**Comment by webgis87** [comment]
yes I saw the demo online, but the layers are not usable because it asks for access to a pg_service file. In any case, I didn't quite understand how to use the instructions, do you have any longer references I can follow?

**Comment by webgis87** [comment]
yes I saw the demo online, but the layers are not usable because it asks for access to a pg_service file. In any case, I didn't quite understand how to use the instructions, do you have any longer references I can follow?

**Comment by Gustry** [comment]
1. Load the SQL in your database
2. Either to have a service called `PG_SERVICE`  according to the [PostgreSQL documentation](https://www.postgresql.org/docs/current/libpq-pgservice.html) and similar to an [existing one in LWC](https://github.com/3liz/lizmap-web-client/blob/master/tests/docker-conf/pg_service.conf). The most difficult part is to know where you can put this file or to define `PGSERVICEFILE`
3. Open the QGS project

Or : 
1. Load the SQL in your database
2. Open the QGS project
3. Press "Ignore for 10 seconds"
![image](https://user-images.githubusercontent.com/1609292/229053158-1ef98194-f55f-4def-9b7a-751e9a63dd92.png)
4. Either edit the datasource manually, or press gain "Keep unavailable layers"
![image](https://user-images.githubusercontent.com/1609292/229053294-5f77cbe5-77db-43bb-92e0-2b31df4d2b20.png)
5. On a unavailable layer, do this :
![ksnip_20230331-093002](https://user-images.githubusercontent.com/1609292/229053517-4fa1209f-fd68-4a6a-afce-737fdb4ff334.png)
6. Pick the layer you have imported in your database



I will add these notes and screenshots in the README.me which is included in the ZIP, for the next update.

**Comment by Gustry** [comment]
I moved the notes in the GitHub repository : https://github.com/3liz/lizmap-web-client-demo/blob/master/INSTALLATION.md

A file has been included as well in each ZIP to link to this online help.
