### ISSUE TITLE
[Bug]: date filters should be "lower or equal" / "greater or equal" and not "stricly lower" / "stricly greater"

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#3571]
### What is the bug?

When date filter is enabled, it is impossible to set a filter that include the most recent dates because:

- Lizmap web client propose a cursor up to "MAX(date)" in the dataset
- Filter is applied "stricly" (<) instead of <=

The only workaround is to add a "fake" point in the future to allow filtering on day+1 for example

A simple fix would be that filters applies <= instead of <

### Steps to reproduce the issue

Enable date filtering on a postgis layer containing dates.

### Versions

Versions :

 Lizmap Web Client : 3.6.2
 Lizmap Web Client target version : 3.6
 Lizmap plugin : 3.11.0
 QGIS Desktop : 3.22.8
 Lizmap.com : Yes
 QGIS Server : 3.22.16
 Py-QGIS-Server : 1.8.7
 QGIS Server plugin atlasprint : 3.3.2
 QGIS Server plugin cadastre : 1.17.3
 QGIS Server plugin lizmap_server : 2.7.0
 QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Macos

### Browsers

Chrome

### Browsers version

Chromium Engine Version 111.0.5563.110

**Comment by mdouchin** [comment]
I will fix this ASAP. Thanks for reporting this issue

**Comment by mdouchin** [comment]
I checked, and the filter of the request does not exclude the min and max values :

`( ( "field_date" >= '2019-03-02' OR "field_date" >= '2019-03-02' ) AND ( "field_date" <= '2019-03-02' OR "field_date" <= '2019-03-02' ) ) `

Perhaps your field contains a timestamp such as `2019-03-02 10:38:54` ? If it is the case, the rule `<= 2019-03-02` will always be `false` as you said. I figure we must add a day to the max date in the slider, as the sliders do not allow choosing an hour

**Comment by vlebert** [comment]
Good to know, as a workaround I can add a calculated column of type date to remove the time information.

As the widget does not allow to pick a time, maybe an implementation could be `< {date_max} + 1 day`, or something  like `<= {date_max} 23:59`

This should keep the current behaviour on date values and be more adapted to datetime values.

The long term evolution being adding a time picker

**Comment by mdouchin** [comment]
PR done !

**Comment by Gustry** [comment]
Can we close this ticket or not ?

**Comment by vlebert** [comment]
Hi

I think it is not released yet on our private instance so I can't confirm

**Comment by mdouchin** [comment]
I close this ticket. Please reopen once the new version is available, if this issue still occurs after testing it
