### ISSUE TITLE
Replacing MapQuest by MapBox ? 

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/lizmap-web-client#358]
Hi,

As many opensource project cannot access to MapQuest anymore, 
Should be interesting to provide MapBox provider as Gnome Project or GeoNode have done.

Thx

**Comment by Doctor-Who** [comment]
Of course, done.

**Comment by geodatup** [comment]
hi, 
you should also modify this in the [demo web site]( http://demo.3liz.com/).

bye

**Comment by rldhont** [comment]
@mdouchin fix it by replacing MapQuest by Stamen

Open a new issue to request MapBox has a feature.
