### ISSUE TITLE
[Bug]: Images links in custom themes broken

### ISSUE THREAD

**Issue by EricM71** [3liz/lizmap-web-client#3587]
### What is the bug?

Images links when overloading themes by project in the "media/themes" folder are broken. 

We have taken projects deployed in an earlier version of Lizmap (3.4). These projects were customized successfully using the method described here: https://docs.lizmap.com/3.6/fr/publish/customization/themes.html 

Once migrated to a Lizmap 3.6.2 server, the theme images are not loaded in the browser, they are not found because links are broken. 

We tested with a theme called "default" and with a theme that has the project name .qgs with the same result.

Deleting custom theme folders in the media/themes directory allows you to revert to the default theme without error.

### Steps to reproduce the issue

1. Create "media" folder
2. Create "themes" folder
3. Create "default" with index.php/view/media/getDefaultTheme
4. Logo disappeared

Same issues with custom theme

### Versions

Lizmap Web Client 3.6.2

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11

### Browsers

Firefox

### Browsers version

Firefox 110.0.1

**Comment by Gustry** [comment]
I think it's already fixed in the next release : https://github.com/3liz/lizmap-web-client/pull/3575/files
You can apply the fix yourself in the meantime. Let us know if it works.

**Comment by EricM71** [comment]
Custom themes and images links are working now with this fix, thank you !
