### ISSUE TITLE
Blend modes not shown

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#36]
LM does not support blending

**Comment by nboisteault** [comment]
@rldhont is it a feature we'd like in the next Lizmap version?

**Comment by Mavialle** [comment]
+1 ! Allow display like this with an elevation layer (sceenshoot from QGIS)

![image](https://github.com/3liz/lizmap-web-client/assets/46535425/bd51febf-363f-4071-948e-2060c7fa35d8)

**Comment by gioman** [comment]
> layer that you can group for the hillshade and the landuse ?

@Gustry the visual effect given by blending modes is different compared to the one given by a semi-transparent layer on top of another.

**Comment by mdouchin** [comment]
@gioman @Mavialle you can indeed organize your layers in a group, for example called "background", which will contain 
* your dem
* you hillshade
* your contours
* roads
* rivers
* etc.

As @Gustry proposed, if in Lizmap plugin, you publish the group "background" with the option "Group as layer" checked, Lizmap Web Client will ask QGIS Server a single image combining the child layers and respecting the blending modes between the layers of this group.

**Comment by gioman** [comment]
> As @Gustry proposed, if in Lizmap plugin, you publish the group "background" with the option "Group as layer" checked, Lizmap Web Client will ask QGIS Server a single image combining the child layers and respecting the blending modes between the layers of this group.

@mdouchin oh, let me try that then!

**Comment by gioman** [comment]
Confirmed it works, this can be closed.
