### ISSUE TITLE
Impression : la légende affiche les éléments du groupe "hidden" 

### ISSUE THREAD

**Issue by geodatup** [3liz/lizmap-web-client#361]
Aucun problème d'affichage d'un fond de carte externe mais en suivant le protocole de la doc, le bloc de la légende imprimée n'a pas filtré  pas le groupe "hidden".
[getPrint.pdf](https://github.com/3liz/lizmap-web-client/files/447196/getPrint.pdf)
Lizmap 3.0.2

**Comment by rldhont** [comment]
You have to modify the composer legend by removing the `hidden` group
