### ISSUE TITLE
[Doubt] Set user permissions  to a specific project of a repository in Lizmap

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#365]
Hi guys,
it's possible to set different user or group permissions to different projects in a repository?

Regards,
João

**Comment by mdouchin** [comment]
Hi,
This is a recurring feature request. We will add it probably in the upcoming version

**Comment by mdouchin** [comment]
Done via a997e6be635df9fb364d401da5a4f0bd37b26c78
See commit message
I am adding the options in lizmap-plugin to let the user configure it
