### ISSUE TITLE
Web Client Lizmap printing problem

### ISSUE THREAD

**Issue by GediminasBVSTT** [3liz/lizmap-web-client#3659]
### What is the bug?

When OSM Mapnik basemap are added via Lizmap plugin the printing on Web Client Lizmap is not working. Map area is white, legend are printed as expected. I created two projects without_osm.qgs without_osm.qgs.cfg and with_osm.qgs with_osm.qgs.cfg. These pairs are almost identical only with_osm.qgs.cfg file have only one line: "osmMapnik": "True". And this line makes troubles because is not working printing. This problem happen in all browsers. Both projects are valid

### Steps to reproduce the issue

.

### Versions

 Lizmap Web Client : 3.6.0
 Lizmap plugin : 3.12.0
 QGIS Desktop : 3.28.5
 QGIS Server : 3.28.5
 QGIS Server plugin atlasprint : 3.3.2
 QGIS Server plugin lizmap_server : 2.7.0
 QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

qgis 3.28.5 

### Operating system

Ubuntu 22

### Browsers

Firefox

### Browsers version

112

**Comment by Gustry** [comment]
This checkbox is only to add OSM background in the web map.
For printing, you still need to follow the documentation about printing external base layer : https://docs.lizmap.com/current/en/publish/configuration/print.html#allow-printing-of-external-baselayers
