### ISSUE TITLE
Pictures stop working when chanching port on apache

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#366]
Hi there!

I changed port on Apache from 80 to 8080 after that the images stoped showing up on Lizmap 3.0.2 . I tried to do some changes on Popup.class.php but doesnt work. 

Does someone know how to fix this or where should i look? 

Tnanks a lot for your time!

**Comment by mdouchin** [comment]
You probably need to clean the temporary folder

In Linux box, use
sudo lizmap/install/clean_vartmp.sh
from the lizmap root folder

In Windows, remove the content of
temp/lizmap/

Then retry

**Comment by Abelon38** [comment]
Thanks   a lot Raphael!

I will try and I´ll come back  with feedback.
Regards,
Abel

**Comment by RaphaelChochon** [comment]
Hey, it is @mdouchin who gave you the answer, not me ! :stuck_out_tongue_winking_eye:

**Comment by Abelon38** [comment]
Perfect! it works! 
Thank you for your time Raphael! I think you guys are doing a greate work with Lizmap! 

Have a nice weekend!
Abel

**Comment by Abelon38** [comment]
Ohh sorry my misstake.
I wil thanks him!
Regards!
Abel

2016-09-03 13:27 GMT+02:00 RaphPNM <notifications@github.com>:

**Comment by Abelon38** [comment]
Hi guys!
I have tow Lizmaps instances. One on my own server and one at work. The one at work dint work to just remove the www file under Temp/lizmap. 
What else can I do?
Hre you can fine the one working: http://webbgis.se:8080/webkarta/lizmap/www/index.php/view/map/?repository=strangnasmiljo&project=Strangnas_miljo

Thanks for your time!
Abel

**Comment by Abelon38** [comment]
Problem fixed! 

I put the Server name and port in Popup.class.php and delated www file and now is working perfect!

Thanks guys I

**Comment by Abelon38** [comment]
Hi egain!
I would love to help with translation to Swedish. Houw can i do?
Regards
Abel

Den 3 sep. 2016 1:52 em skrev "Abel Gonzalez" <abel.gonzalez.c@gmail.com>:

**Comment by Abelon38** [comment]
Thanks

Den 3 sep. 2016 12:25 em skrev "mdouchin" <notifications@github.com>:

**Comment by mdouchin** [comment]
@Abelon38 You can help translate lizmap in swedish via the Transifex platform 
https://www.transifex.com/3liz-1/lizmap-locales/
You can ask @rldhont to create the language swedish, and then create an account and start contributing.

**Comment by Abelon38** [comment]
Perfect!
I'll do that!
Have a good weekend!
Abel

Den 3 sep. 2016 4:53 em skrev "mdouchin" <notifications@github.com>:
