### ISSUE TITLE
Eliminate attribute table

### ISSUE THREAD

**Issue by matcas91** [3liz/lizmap-web-client#367]
Hi all,

in the previous versions of lizmap, when I open a pop-up there aren't attribute table.
Now i'm using lizmap 3.0.1 and I need to cancel this table.
Can anyone help me ? I tried to search into all *.php file, but I didn't found the class that generate the attribute table.

Thanks in advance

**Comment by rldhont** [comment]
What do you mean by "attribute table" ?
A new option in the lizmap-plugin specify the way to display popup:
* the default one (the one you probably named attribute table)
* the configure in Lizmap
* the qgis tooltip
