### ISSUE TITLE
[Bug]: Filtered features disappear from map

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3675]
### What is the bug?

When activating the filter on selected features/records, the features disappear from the map.
This happens from both the attribute table and the "select" dialog.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1951107/236670961-cff299ca-74e5-4846-a433-585a6ff426a1.png)

![image](https://user-images.githubusercontent.com/1951107/236670978-c6b999d1-bdfe-4817-bd3b-26d84a45e0bd.png)

![image](https://user-images.githubusercontent.com/1951107/236671000-7ecb7e3d-80dc-40e8-a8c2-1efecd9b8b55.png)

### Versions

QGIS LTR on Desktop and Server, latest version of LMWC, LM plugin and LM server plugin.

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by gioman** [comment]
Can anyone confirm?

**Comment by gioman** [comment]
Bumping my tickets before they go "quite",

**Comment by gioman** [comment]
@nboisteault I can replicate. The best I can do right now is to share the layer, attaching it here. Maybe the root cause is yet another case of a problem caused by spaces and accents in the datasource/layer name.

[Área Protegida da Ponta do Pargo.zip](https://github.com/3liz/lizmap-web-client/files/12524158/Area.Protegida.da.Ponta.do.Pargo.zip)

**Comment by nboisteault** [comment]
@gioman Ok I reproduce the issue. Working on a fix. thanks for your report.

**Comment by gioman** [comment]
@nboisteault thank you for your work.
