### ISSUE TITLE
lizmap sorts columns by alphabet and not as in postgres?

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#3678]
### What is the question?

Hi there, I'm using Lizmap Web Client 5.0 with a PostgreSQL database. I've created a view in PostgreSQL that orders the columns in a specific way, but when I view the data in Lizmap Web Client, the columns are ordered alphabetically instead. Is there a configuration option in Lizmap Web Client to control the ordering of columns in the table view, or is this not possible? Thanks for any help you can provide!

### Versions

Lwc 5.0

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubunto 20.01

### Browsers

Chrome

### Browsers version

Chrome

**Comment by Gustry** [comment]
It's written in the documentation, in the attribute table chapter.
