### ISSUE TITLE
Insert project from Lizmap Plugin

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#369]
Hi!

I think another greate step would be the posibility to insert new projects on Lizmap Webclient direct from Lizmap Plugin so you dont need to go in into the backend and add it there. This would includ users management also.

Thanks for good work guys!
Abel

**Comment by rldhont** [comment]
We needs to create an API to transfer all data and configurations (project and others)

**Comment by Gustry** [comment]
This is not on the roadmap.
We do not want to replace a dedicated protocol.
