### ISSUE TITLE
[Bug]: Obsolete custom JS script since 3.6 ?

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#3690]
### What is the bug?

Hi

I went back to a project I began on 3.5 and didn't touch for a while. After coming back, I realize some features are broken, since 3.6 I suspects.

I used this script
https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/tools/zoom_to_feature_at_startup

And more especially the showFeaturePopup(featuretype, fid) function.

I know have a JS error: `TypeError: coordinates must be finite numbers`

```
function showFeaturePopup(featuretype, fid) {

    lizMap.getLayerFeature(featuretype, fid, function (feat) {

        lizMap.getFeaturePopupContent(featuretype, feat, function (data) {
            // Add class to table
            var popupReg = new RegExp('lizmapPopupTable', 'g');
            var ptext = data.replace(popupReg, 'table table-condensed table-striped table-bordered lizmapPopupTable');

            // Get feature id
            var hfid = $(ptext).find('input').val();
            var fid = hfid.split('.').pop();

            // Remove h4 title (with layer title)
            var titleReg = new RegExp('<h4>.+</h4>');
            ptext = ptext.replace(titleReg, '');

            // Add popup menu tool if needed
            if (!$('#mapmenu .nav-list > li.popupcontent > a').length) {
                var dock = 'dock';
                lizMap.addDock('popupcontent', 'Popup', dock, '<div class="lizmapPopupContent"/>', 'icon-comment');
            }
            $('#popupcontent div.menu-content div.lizmapPopupContent').html(ptext);

            // Open popup div
            $('#mapmenu li.popupcontent:not(.active) a').click();

            // Add geometry
            lizMap.addGeometryFeatureInfo(null, null);

            // Trigger Lizmap event to add popup toolbar
            lizMap.events.triggerEvent(
                "lizmappopupdisplayed",
                { 'popup': null }
            );

        });

    });
    //lizMap.zoomToFeature(featuretype, fid);
}
```

**What is the correct way in 3.6 to programmatically open the popup of a given feature ?**

### Steps to reproduce the issue

It is a bit complicated to reproduce the full set up. Here is a quick video.

https://share.cleanshot.com/VtYZVjTd

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.11.0
* QGIS Desktop : 3.22.8
* Lizmap.com : Yes
* QGIS Server : 3.22.16
* Py-QGIS-Server : 1.8.7
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

MacOS

### Browsers

Chrome

### Browsers version

Chromium Engine Version 113.0.5672.92

**Comment by Gustry** [comment]
Opening the popup automatically with a permalink is now native in Lizmap 3.6, extra JS shouldn't be needed.

https://www.3liz.com/news/lizmap-web-client-3-6.html → Zoom sur un objet à l'ouverture de la carte
https://www.3liz.com/en/news/lizmap-web-client-3-6.html → Zoom on an object when opening the map

Does it feet your needs ?

**Comment by vlebert** [comment]
I guess so. I knew I had seen this new feature but I could not find the documentation later.

I'll give it a try thanks !

**Comment by Gustry** [comment]
Yes, I created a ticket to add it to the documentation.

Thanks for the feedback.

**Comment by vlebert** [comment]
Hi @Gustry 

I did some test and the new feature doesn't totaly fit : 
- When we set a link with `layer` and `filter` param, the page and UI is totally reloded after clicking, event when removing `target=_blank` and when the origin click in on a same project

Previously, you couln'd dynamically navigate on the map to target features without reloading the UI
The target behaviour shown here can't be reproduced https://share.cleanshot.com/VtYZVjTd

Is there something you / I can do ?

**Comment by Gustry** [comment]
Sorry, I won't be able to help.
Using an URL looks logical that the page is reloading. You are trying to call some JS indeed,

**Comment by vlebert** [comment]
What javascript should I use to reproduce the behaviour when zomming on feature on load with url parameters.

As mentioned on the first message, the JS code formerly used seems to be obsolete (https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/tools/zoom_to_feature_at_startup).

I also tried the `#fid:[qgis_layer_id].[feature_unique_id]`

It is not working on my side

By the way, the link to documentation here is broken : https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/tools/zoom_to_feature_at_startup

**Comment by nboisteault** [comment]
@vlebert here is an example : https://demo.snap.lizmap.com/lizmap_3_6/index.php/view/map?repository=testsrepository&project=startup&layer=sousquartiers&filter=%22quartmno%22%20=%20%27PA%27%20OR%20%22quartmno%22%20=%20%27HO%27&popup=true

The `filter` parameter might be rephrased but we used this word as it is a QGIS expression used to create the selection as defined [here](https://docs.qgis.org/3.28/fr/docs/server_manual/services/wfs.html#wfs-getfeature-expfilter).
