### ISSUE TITLE
[Bug]: Problem with filter tool (LWC 3.6) - Data not displayed

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#3692]
### What is the bug?

When I use the filter tool, no data is displayed or some data is displayed without correctly matching the filter.

### Steps to reproduce the issue

The number of fetaures is correctly updated but not the map.

For example, his is the map without filter (34514 features) : 
![image](https://github.com/3liz/lizmap-web-client/assets/68422902/75d14612-8e7a-4ce9-9f0d-7be0b0eda288)

If i check one option "commune = Angerville-la-Martel", there are 957 features left but only 2 points are displayed on the map and they are not corresponding to the filter (not the good municipalitie).
![image](https://github.com/3liz/lizmap-web-client/assets/68422902/df667119-e34b-4473-b6ef-23d87417133c)

May you help me to solve this issue please ?

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap plugin : 3.13.0
* QGIS Desktop : 3.28.6 (test also with 3.22.6)
* Lizmap.com : Yes
* QGIS Server : 3.28.4
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

W10 for desktop / Unknown for server 

### Browsers

Firefox

### Browsers version

Firefox 113

**Comment by gioman** [comment]
@Alain-LG Please add a title/subject.

**Comment by Gustry** [comment]
What the primary key used in your layer datasource ? What kind of field ?

**Comment by Alain-LG** [comment]
Thanks a lot, I have updated the table with your alter table request.
Now, it's OK.

**Comment by Gustry** [comment]
I have added it in https://github.com/3liz/lizmap-plugin/issues/389
