### ISSUE TITLE
Mutual disable layers

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#37]
like in other webgis platforms it would be very useful to have the chance to configure a list of layer that have to mutually disable each other (like baselayers). To make things simplier it would be enough to allow say that the layers inside a particular group have to mutually disable each other.

**Comment by rldhont** [comment]
To implement it, I think, it will be usefull to reuse the QGIS configuration.

**Comment by gioman** [comment]
@rldhont I agree.

**Comment by gioman** [comment]
@rldhont @mdouchin  as usual, really many thanks fir all your effort.

**Comment by rldhont** [comment]
@gioman de nada!

**Comment by jlstanus** [comment]
Interesting feature when 2 parallel projects where one layer is editing and other is viewing answers from the second project with same features.
