### ISSUE TITLE
[bug] Display features count in layers legend when activated in project

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#370]
hi,

it doen't display the total of the features.
please, see issue #246 

thanks again

**Comment by josemvm** [comment]
hi @rldhont  and  @mdouchin

is it possible to review this feature?

QGIS Desktop project
![qgis](https://cloud.githubusercontent.com/assets/10053874/17368954/2c0877de-598e-11e6-8a1f-6a3a855e19df.jpg)

LWC
![lwc](https://cloud.githubusercontent.com/assets/10053874/17368931/18290b84-598e-11e6-8a9f-dbe4878e9dd6.jpg)

thanks again

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/515

**Comment by josemvm** [comment]
hi @rldhont is it still not possible to display the total of features in LWC?

**Comment by Gustry** [comment]
I would say yes, it might be possible.
Because the feature count for all individual items is accessible. I haven't checked.
https://github.com/3liz/qgis-lizmap-server-plugin/blob/master/lizmap_server/get_legend_graphic.py
