### ISSUE TITLE
[Bug]: Map option "Get images directly from WMS Server" not working?

### ISSUE THREAD

**Issue by johnzet39** [3liz/lizmap-web-client#3702]
### What is the bug?

Hello. 
In may map I have XYZ layer and I want tiles to be downloaded directly from a remote service, as is done with base layers of Lizmap, for example, OSM.
When I enable option "Get images directly from WMS Server" qgis-server still generates tiles. If you look at the address of the tile, you can see that the address of the image has the address of my server.
Or what should I do so that the tiles are loaded directly from a third-party service, bypassing my qgis-server

### Steps to reproduce the issue

1. Edd XYZ layer.
2. Enable option "Get images directly from WMS Server".

### Versions

**Versions :**

* Lizmap Web Client : 3.5.2
* Lizmap plugin : 3.7.7
* QGIS Desktop : 3.22.5

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.5

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Chrome

**Comment by Gustry** [comment]
> Lizmap Web Client : 3.5.2
> Lizmap plugin : 3.7.7

We are now at Lizmap Web Client 3.5.13 versus 3.5.2
Maybe an intermediate bugfix version have fixed this bug already ? Please update and follow the ticket template next time.

Same for the plugin, you should update. 3.7.7 is very old. We are now at 3.14.0.

**Comment by gioman** [comment]
@johnzet39 @Gustry probably something unrelated to LMWC but to QGIS Server configs, and I guess this could be really stressed in LM docs:

Is not really unusual to load an external WMS/XYZ layer in QGIS Desktop and the subsequent QGIS Server WMS service do not show anything (regardless of using the "Get images directly from WMS Server" in LM plugin). 

The suggestion should be to look at the error log of the Web Server, "error.log" for Apache2.

If there appear the line

`ERROR: Auth db directory path could not be created`

or

`ERROR: Opening of authentication db FAILED`

is an indication that the Web/QGIS Server config misses

`FcgidInitialEnv QGIS_AUTH_DB_DIR_PATH "/path/to/qgisserverdb/"`

and that folder must be fully writable by the web server. Moreover the above QGIS Server config must be set in the virtual hosts files for both http and httpS.

Usually setting all the above fixes this issue.

**Comment by Gustry** [comment]
Thanks, indeed, these logs are frequent and should be written somewhere

**Comment by gioman** [comment]
> Thanks

@Gustry no problem.

On the other hand I have still not understand if the messages (returned by QGIS Server indeed)

`QNetworkDiskCache::prepare() unable to open temporary file"`

can be ingored or have any impact on the services.

I never was able to get rid of them and a few questions on the dev lists have gone unanswered

https://lists.osgeo.org/pipermail/qgis-developer/2021-May/063616.html

https://lists.osgeo.org/pipermail/qgis-user/2021-April/048576.html

Any idea?
