### ISSUE TITLE
Permalink & layers

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#371]
Hi,

How are the layer names encrypted in the permalink? Is there a way to pass clear layer names as parameter?

Thanks in advance

Edit: 
I saw apparently that F means false, T means true, in reverse order of layers addition. B for active base layers and 0 for inactive base layers. The problem is that when adding layers in the project, the links are no longer functional, while the parameters based on layer's name would solve this problem. (I use the permalink to start lizmap on a specific area with specific layers from another application)

**Comment by rldhont** [comment]
@loic74 this feature is actually based on OpenLayers permalink. We needs to redo it.

**Comment by nboisteault** [comment]
Now with Lizmap 3.7 layers name are used in the permalink. Permalink is updated in the URL when you change, extent or layer/group visibility, style or opacity.

Documentation update would be welcome! :)

Here is an example : https://demo.snap.lizmap.com/lizmap_3_7/index.php/view/map?repository=features&project=land_use#2.9722658201333396,43.15874530830561,3.2546769433854976,43.30814676820724|Limites%20communales,Occupation%20du%20sol%20en%202021,Grandes%20composantes%20du%20territoire|d%C3%A9faut,,d%C3%A9faut|1,1,1
