### ISSUE TITLE
Editing form desappears when inserting objects on the map

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#372]
Hi Guys!

Först of all thank you for a greate work! 

I have a question related edition tools: When I click on edinting tool and start inserting fpr example a line, then the editing form desappears. Does anyone know what could be worng? It is a litle bit annoying when working out in the field. 
Regards
Abel

**Comment by rldhont** [comment]
@Abelon38 I found an issue, which is that the drawing element is not displayed when it is finished. Do you speak about this ?
Or do you speak about the HTML form ?

**Comment by Abelon38** [comment]
Hi there!  Thanks for your answers. It is not the same problem i have. The problem is the attribute table to be filled when editing or inserting a new element. This form desapears at the firt moment i start editing. Then when i have finished editing i have to go back and click on icon edit again to re-open the form to fill it and save. Sorry about my english guys.
Thanks for your time! 
Abel

**Comment by rldhont** [comment]
Repeated in the demo https://demo.lizmap.com/lizmap_3_0/index.php/view/map/?repository=demo&project=observatoire
The form disappears because a GetFeatureInfo is send to the server

**Comment by rldhont** [comment]
Fixed in https://github.com/3liz/lizmap-web-client/milestone/16
