### ISSUE TITLE
[Question]: No descriptive texts for search on mobile devices

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#3725]
### What is the question?

on the smartphone (android and ios) and also on the tablet (11" portrait) the descriptive texts for the Lizmap search (no SQL search) are not displayed [1]. In landscape mode on the tablet it works correctly as on the PC [2].
Both in Chrome, and in the Firefox browser.
Lizmap WebClient 3.6.4 but also in older versions.

Is this known or is there even a workaround?

[1]  https://wagner-it.de/download/lizmap/lizmap_search1.jpg
[2] https://wagner-it.de/download/lizmap/lizmap_search2.jpg

### Versions

    Lizmap Web Client : 3.6.4
    Lizmap plugin : 3.14.0
    QGIS Desktop : 3.22.16
    QGIS Server : 3.22.16
    Py-QGIS-Server : not used
    QGIS Server plugin lizmap_server : 2.7.2

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Android 13

### Browsers

Firefox, Chrome

### Browsers version

Firefox 114.1.0, Chrome 114.0.5735.60

**Comment by nworr** [comment]
duplicate #3209 ?

**Comment by guenterw** [comment]
Thanks for the tip. I had not found that.

I had hoped for such a workaround. But in the meantime the map.js was optimized and so I can't find the place for the replacement.
Can someone give me a tip on this?

And in general: Does no one use this search or is no one bothered by this bug?
For small datasets I like to use this kind of search and find it very user friendly. But more and more users work with mobile devices and rightly miss the description for the search field there.
Where is the problem for fixing the bug, if it could be fixed earlier apparently with editing a line?
