### ISSUE TITLE
Geolocation tool not working

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#373]
Hi guys!

The Geoposition tool is not working at all, I does worked on later versions, but with 3.0.2 is not working for me. 
Any hejp?

thank you for your time!
Abel

**Comment by Abelon38** [comment]
Hi there !
I found that the problem is in Chrome! Use Firefox and the problem is fixed!

Thanks guys for a super software!
Abel

**Comment by rldhont** [comment]
Hi @Abelon38 
Someone has already opened an issue: #314 and updated the documentation https://github.com/3liz/lizmap-documentation/issues/57
In chrome, Geolocation needs HTTPS.

> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature,
you should consider switching your application to a secure origin, such as HTTPS. See
https://goo.gl/rStTGz for more details.

It is explain in documentation here http://docs.3liz.com/en/install/linux.html#enable-geolocation
