### ISSUE TITLE
[Question]: Help me for use WPS or Postgresql with example esaustive step by step

### ISSUE THREAD

**Issue by sag1687** [3liz/lizmap-web-client#3731]
### What is the question?

For some time now, I've been wanting to integrate a procedure into my Lizmap project. I have found various instructions, but many of them don't work because they are not up to date. I would like to be able to input new data along with the existing data and obtain an output. I have been advised to use either actions in PostgreSQL or the WPS module with a Python script. However, the procedure is still unclear to me, and I'm wondering if someone could provide a more detailed explanation, breaking down each step as if explaining to a beginner.

Here's the translation in English:

"I have been wanting to integrate a procedure into my Lizmap project for some time now. I have come across various instructions, but many of them are outdated and don't work. I would like to have the ability to input new data along with the existing data and obtain an output. I have been advised to either use actions in PostgreSQL or the WPS module with a Python script. However, I still don't have a clear understanding of the procedure. Can someone provide a more comprehensive explanation and guide me through each step as if explaining to a beginner?"

### Versions

QGIS_3.22

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16

### Operating system

ubuntu server

### Browsers

Chrome

### Browsers version

92

**Comment by Gustry** [comment]
Sorry, I'm closing this ticket.
There is #3707 and this current ticket is too broad to be answered. A specific question must be asked either on PostgreSQL action or on WPS.
