### ISSUE TITLE
[Bug]: postgis update/delete not working if special character in layer name

### ISSUE THREAD

**Issue by r9zzai** [3liz/lizmap-web-client#3734]
### What is the bug?

QGIS Layer name includes a "." sign (e.g. "1.1 first layer in group 1").
I think this is a common usage of naming a layer.
As a postgis layer insert/update/delete is working in QGIS Desktop.
In lizmap only insert is working. Edit and delete is not working.

As a workaround I can copy the layer name in lizmap plugin or in qgis layer settings in qgis server tab to title.

### Steps to reproduce the issue

Name a layer in QGIS with a "." sign (e.g. "1.1 first layer in group 1").

### Versions

**Versions :**

* Lizmap Web Client : 3.6.1
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.10.0
* QGIS Desktop : 3.28.3
* QGIS Server : 3.28.5
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 1.2.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

No LSB modules are available. Distributor ID: Debian Description:    Debian GNU/Linux 11 (bullseye) Release:        11 Codename:       bullseye

### Browsers

Firefox

### Browsers version

Firefox 114.0.1 (64-Bit)

### Relevant log output

```shell
2023-06-16 10:30:23	195.37.42.200	error	2023-06-16 10:30:23	195.37.42.200	[403]	unzulässige Anfrage(ERROR:  syntax error at or near ")"
LINE 4:         )
                ^(
        WITH source AS (
         SELECT "id_0" FROM "public"."netzz" WHERE True AND 
        )
        --SELECT row_to_json(fc, True) AS geojson
        --FROM (
        --    SELECT
        --        'FeatureCollection' As type,
        --        array_to_json(array_agg(f)) As features
        SELECT row_to_json(f, True) AS geojson
            FROM (
                SELECT
                    'Feature' AS type,
         Concat(
            '1.1_update_delete_not_working',
            '.',
            "id_0") AS id,
                        Null As geometry,
            
                    row_to_json(
                        ( SELECT l FROM
                            (
                                SELECT "id_0"
                            ) As l
                        )
                    ) As properties
                FROM source As lg
            ) As f
        --) As fc))	/var/www/html/lizmap-web-client-3.6.0/lizmap/vendor/jelix/jelix/lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	211
	/lizmap-web-client-3.6.0/lizmap/www/index.php/lizmap/edition/modifyFeature?repository=3&project=map_test&layerId=netzz_07475e04_cba8_4472_ae5e_0da6aec6b9ce&featureId=135
array (   'repository' => '3',   'project' => 'map_test',   'layerId' => 'netzz_07475e04_cba8_4472_ae5e_0da6aec6b9ce',   'featureId' => '135',   'module' => 'lizmap',   'action' => 'edition:modifyFeature', )

	0	pgsqlDbConnection->_doQuery()	/var/www/html/lizmap-web-client-3.6.0/lizmap/vendor/jelix/jelix/lib/jelix/db/jDbConnection.class.php : 159
	1	jDbConnection->query()	/var/www/html/lizmap-web-client-3.6.0/lizmap/modules/lizmap/lib/Request/WFSRequest.php : 855
	2	Lizmap\Request\WFSRequest->getfeaturePostgres()	/var/www/html/lizmap-web-client-3.6.0/lizmap/modules/lizmap/lib/Request/WFSRequest.php : 370
	3	Lizmap\Request\WFSRequest->process_getfeature()	/var/www/html/lizmap-web-client-3.6.0/lizmap/modules/lizmap/lib/Request/OGCRequest.php : 158
	4	Lizmap\Request\OGCRequest->process()	/var/www/html/lizmap-web-client-3.6.0/lizmap/modules/lizmap/controllers/edition.classic.php : 290
	5	editionCtrl->getWfsFeature()	/var/www/html/lizmap-web-client-3.6.0/lizmap/modules/lizmap/controllers/edition.classic.php : 438
	6	editionCtrl->modifyFeature()	/var/www/html/lizmap-web-client-3.6.0/lizmap/vendor/jelix/jelix/lib/jelix/core/jCoordinator.class.php : 266
	7	jCoordinator->process()	/var/www/html/lizmap-web-client-3.6.0/lizmap/www/index.php : 23
```

**Comment by gioman** [comment]
Other problems related to accents/spaces in layer names:

https://github.com/3liz/lizmap-web-client/issues/3696

https://github.com/3liz/lizmap-web-client/issues/3660

**Comment by nboisteault** [comment]
@r9zzai It is true for old project saved with an old Lizmap plugin version. Your version is `Lizmap plugin : 3.10.0`, please update. Now Lizmap plugin creates a shortname for every layers, this will fix your issue.

**Comment by r9zzai** [comment]
[@nboisteault](https://github.com/nboisteault) thank you, UPDATE and DELETE is now working in lizmap even if layer name contains "." character.
