### ISSUE TITLE
[Question]: Qgis styles not applied on Lizmap

### ISSUE THREAD

**Issue by badxtof** [3liz/lizmap-web-client#3755]
### What is the question?

Recently I noticed that the styles (symbols, colors, ...) chosen in QGIS are not applied in Lizmap. All symbols are the same. 
Does anyone have an idea what could be the reason for this? I am not getting anywhere.

### Versions

QGIS: 3.28
LizmapPlugin: 3.14.2
LizmapWeb: 3.5.5

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 18.04.6

### Browsers

Chrome

### Browsers version

Latest

**Comment by Gustry** [comment]
> QGIS Desktop : 3.28
> QGIS Server : 3.16.16

This is the problem.
https://www.qgis.org/en/site/forusers/visualchangelog328/index.html#feature-drop-project-backward-compatibility-for-symbology-with-qgis-3-16-and-older

In Lizmap plugin, you must have a warning saying your QGIS server is older than QGIS desktop.
QGIS Server 3.16 **can't read** a project in the future with QGIS 3.28.

**Comment by badxtof** [comment]
Thank you. 
Despite some searching, I did not come across this post. 
I will ask the hoster to make the upgrade.

**Comment by Gustry** [comment]
Even without this post, you must use the same version between QGIS server and QGIS desktop
