### ISSUE TITLE
"Add him/her to this group"

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3760]
Rather than just "him".

![Screenshot 2023-06-04 195057](https://github.com/3liz/lizmap-web-client/assets/1951107/dbfb1cc1-dcc5-4350-abf7-23298a274c83)

**Comment by nworr** [comment]
Localisation file : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/admin/locales/en_US/user.UTF-8.properties

**Comment by Gustry** [comment]
`Add the user to this group` ?

**Comment by gioman** [comment]
> `Add the user to this group` ?

yes better.

**Comment by Gustry** [comment]
> yes better.

Cool, please contribute ;-) On GitHub, there is the "pen icon" ;-)

**Comment by gioman** [comment]
> Cool, please contribute ;-) On GitHub, there is the "pen icon" ;-)

Sure, I'm on it.
