### ISSUE TITLE
Atlas popup won't show if layer name has spaces/accents in it

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3762]
### What is the bug?

I have a layer that in the datasource is named

`areas_municipais`

and has been renamed to

`Áreas municipais`

in QGIS project.

Adding that layer in LMWC as an Atlas layer with popup active, it won't show the Atlas popup. If the same layer is used without renaming it, it will work as expected.

### Steps to reproduce the issue

See above.

### Versions

QGIS latest 3.28 for Desktop and Server. LMWC latest 3.6

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by gioman** [comment]
Bumping my tickets before they go "quite",

**Comment by Gustry** [comment]
> Bumping my tickets before they go "quite",

Such tickets are never going "quite" by the stalebot.

Not sure to understand completely. Is-it not linked to https://github.com/3liz/lizmap-plugin/issues/498 ?

About versions, please follow the step in the QGIS desktop plugin. "Latest" version from July (date of the ticket) is no the latest anymore ;-)
