### ISSUE TITLE
Update doesn't work with view

### ISSUE THREAD

**Issue by nicolasvhISL** [3liz/lizmap-web-client#378]
I have a problem with the data modification form for a PostGIS view in lizmap-web-client (3.1pre).

On this view, it is possible to change the raw fields but not the calculated fields. It was tested with pgadmin.

When the form is created all fields are displayed in lizmap form (even the calculated field with wms and wfs unchecked).

When I try to update a record, there is an error : "An error has been raised when saving the form". 

I think lizmap try to update this calculated fields, but i don't understand why ...

Can you held me ?

Nicolas

**Comment by rldhont** [comment]
You can uncheck `editable` in the edition tool for the calculated fields.

Can you test with 3.0.4 ?

**Comment by nicolasvhISL** [comment]
My project restart and I have tried to produce the problem on a new server with the last version of the client 3.1.4 

If the fields have WFS uncheck its work (but i can't see my calculated fields)

if wfs est activated and editable is unchecked, the calculated are shown disabled  but when we want to save, we get this message : "An error has been raised when saving the form"

**Comment by rldhont** [comment]
@nicolasvhISL can you provide some feedbacks ?

**Comment by rldhont** [comment]
I close it, reopen if needed
