### ISSUE TITLE
Tooltip should be cached

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3780]
Enabling the tooltip tool on a (even not so) large line or polygon layer can cause a great delay before the tool is available, I guess this happens because all the features need to be parsed. 

While this is can be acceptable once (up to a certain amount of seconds) this is very inconvenient as it happens every time the user changes the (tooltip) layer and gets back to a previously selected one. I guess that whatever is being done the first time it should be better to be cached, so it does not happen again up until the user reloads te whole page.

Bonus: the LM plugin should/could quickly count the number if vertexes in a layer when added to the "tooltip" tool and warn the users that it would be better to generalize the layer

**Comment by nboisteault** [comment]
Tooltips are now cached in Lizmap 3.8.0.

**Comment by gioman** [comment]
> Tooltips are now cached in Lizmap 3.8.0.

thanks!
