### ISSUE TITLE
Changing "popup click tolerance" makes the identify tool to identify the wrong features

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3785]
### What is the bug?

1) point layer and "popup click tolerance" with the default value of 25px

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/99ea6a15-1e07-4510-ba6e-2e151dc749d7)

the identified point features are correct.

2) same point layer and "popup click tolerance" increased to 50px, and same click point

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/ab377a35-4dbc-46d9-bcf9-8d723fa2bc0c)

wrong features identified.

### Steps to reproduce the issue

See above.

### Versions

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/00ecaad6-77f6-4405-8656-44c3ad14e5f2)

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by Gustry** [comment]
I think the tolerance is sent straight in the request to QGIS server and LWC just get the result of identified features, so it might not be a bug related to LWC :

* https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#getfeatureinfo
* https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#wms-fipointtolerance

**Comment by Gustry** [comment]
Hum, this might not be a bug QGIS server.
But related to the maximum of popup asked to QGIS server indeed, which is 10 objects, as we can count in your second screenshot.

**Comment by gioman** [comment]
@Gustry bingo, you are right. Is anyway very counter-intuitive that the first "x" ones are not the closest ones.

**Comment by Gustry** [comment]
So it might be in QGIS Server itself between `FI_[POINT]_TOLERANCE` and `FEATURE_COUNT` https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#wms-featurecount

**Comment by gioman** [comment]
> @gioman so this issue can be closed?

@nboisteault the behavior is explained, but then when setting max number of features returned it should really return the closest x ones. If this is a QGIS server issue please close. Let me know if you want me to open a ticket in QGIS tracker.

**Comment by nboisteault** [comment]
@gioman yes, please open a ticket in QGIS tracker as it really seems a QGIS Server issue.

**Comment by gioman** [comment]
> @gioman yes, please open a ticket in QGIS tracker as it really seems a QGIS Server issue.

@Gustry will do, thanks!
