### ISSUE TITLE
[Bug]: Layer stack order Firefox versus Chrome

### ISSUE THREAD

**Issue by manogenam** [3liz/lizmap-web-client#3788]
### What is the bug?

I set on Qgis a specific layer stack order. It works with Google Chrome but not with Mozilla Firefox.
Layers are sorted in order of appearance in the layers panel instead of the enabled option.

### Steps to reproduce the issue

1. Enable layer order on Qgis
2. Set a different order between the layer order option and the layer panel
3. Save project and publish it

### Versions

Qgis desktpo 3.28.8

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.8

### Operating system

Debian 11

### Browsers

Firefox, Chrome

### Browsers version

Firefox 115.0.2 ; Chrome 144.0.5735.199

**Comment by Gustry** [comment]
I think it's unfortunately a known issue about the compatibility with OpenLayers. It will get fixed with an update from OpenLayers in our stack.

We will have a few components updated to latest OL 7 in the next release LWC 3.7

**Comment by Gustry** [comment]
@manogenam Can you try with the new 3.7 release ?
Or can we change the milestone ?

**Comment by nboisteault** [comment]
It is now fixed in Lizmap 3.7.
