### ISSUE TITLE
Selection tool + table of attributes

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#38]
Like in others webgis frameworks it would be very good to have a selection tool (like "selection by rectangle" in qgis) to allow select features on the map (the user must select first the layer where to apply the selection). After the selection is made a dialog opens and shows the attributes (as a table) of the selected features. Clicking on one row and the map zooms on that specific feature.

**Comment by rldhont** [comment]
Hi @gioman and @tbeg, did you test master ?
I think it's already done, isn't it @mdouchin ?

**Comment by gioman** [comment]
I think that the functionality is almost there, as I see that there is a selection tool in the identify windows now. But unless I am missing something obvious I don't see a way to make multiple selection on the map (and active a filter with such multiple selection), that would be very convenient. Feel free to close if you think so or if I'm missing the multiple selection on map. Cheers and thank you for your work.

**Comment by mdouchin** [comment]
Hi @gioman Indeed you can select multiple features, but only via the attribute table, in the "bottom" dock. You can do this in many ways:

* use the first button displayed in each line of the attribute table. You can use it one line after the other to select multiple lines
* use the text input field above each attribute table to filter the visible lines, and then click on the black star button to select all the visible lines

When you have one or more features selected, you can use the filter button ( the 4th one from the left right to the search input field) to filter the features displayed in the map and in the attribute layer

**Comment by gioman** [comment]
> Indeed you can select multiple features, but only via the attribute table, in the "bottom" dock.

yes I have seen in LM master. The suggestion is really for the multiple selection on the map (with a dedicated tool or allowing it while identifying single features). If anyway is not on your plans please close this as unfortunately I'm not able to contribute with more than a suggestion. Cheers!

**Comment by GeneralCorentin** [comment]
Hello,

As IT trainee at UMR METIS (Paris 6), I'm currently working on a project using PostgreSQL/PostGIS database and Lizmap Web Client. It fits with my needs but I regret the absence of a multiple entities selection tool via the geographical interface.

I wonder if you intend to add this feature in a future development.

However, I began to create functions in Lizmap that (I hope) will perform this idea. 
In the one hand, the user is be able to select entities one by one with the mouse. A button appears on the entity and allows to add it to a list.
In the other hand, the user can draw a polygon that selects entities in his area, then adds them to the list.

At this moment, only the first selection method (one by one) is available and I have some difficulties to extract informations. I would like to get and show a table of the selected entities with their attributes (as the one we get with the "data" feature in Lizmap Web Client).

I looked at the functions in "attributeTable.js" and "map.js files and I can see there are already features like draw a polygon that can be used with.

- Is it possible to manage a tool in Lizmap Web Client thanks to these functions or do you suggest me to develop a specific openlayer program ?
- How can I select entities "under" the drawn polygon ? (I work with punctual entities only)
- Do I have to manage WMS requests to collect data according to the successive add in the list or just one call is enough ?

Thank you for your help

Corentin

**Comment by rldhont** [comment]
This feature will be developed for 3.1

**Comment by rldhont** [comment]
@gioman done for version 3.1

**Comment by gioman** [comment]
@rldhont very cool, thanks a lot for your work!

**Comment by rldhont** [comment]
You're welcome @gioman
