### ISSUE TITLE
Project list horizontally

### ISSUE THREAD

**Issue by Abelon38** [3liz/lizmap-web-client#380]
Hi guys!
Does anyone know how to list projects horizontally istead for a list on main page of lizmap?
Thanks

Abel

**Comment by geoek** [comment]
Hi,
If you have several project in the same Lizmap directory, they will be displayed horizontally.
If you have only one project in each directory, then they will be displayed verticaly because a new line is created for each directory.

I hope it will help you.

**Comment by Abelon38** [comment]
It works! 
Thank a lot!
Abel

**Comment by rldhont** [comment]
Hi @Abelon38 if you think the documentation is not complete feel free to update it.
https://github.com/3liz/lizmap-documentation/
