### ISSUE TITLE
[Question]: Hidden container in Lizmap

### ISSUE THREAD

**Issue by BaBoWaGa** [3liz/lizmap-web-client#3805]
### What is the question?

I'm trying to hide various fields from postGIS db from unauthorized users in a Lizmap map.

![image](https://github.com/3liz/lizmap-web-client/assets/109667824/b0cf1aa7-20ef-42f1-8fd7-c5210e40c8a5)

I have tried various forms of both @lizmap_user_groups = 'admins' and setting the type of popup in lizmap, but to no avail.
does anyone know how to fix?

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap plugin : 3.15.1
* QGIS Desktop : 3.32.0
* QGIS Server : 3.32.1
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuuntu 22

### Browsers

Chrome

### Browsers version

chrome 112

**Comment by BaBoWaGa** [comment]
Thank you for replying and sorry if I use non-technical language.
I would like to create a popup with some fields visible to everyone and a countainer (tab) inside which I would put the fields that will only be visible when edited by the admins:
For some popups I would like to use, with Lizmap, the QGIS HTML Maptip, and in others QGIS Drag&Drop form, obviously if it is not possible I would use only one of the two

**Comment by Gustry** [comment]
Ticket linked to #3713, please have look to debug.
All requests must be checked with login parameters are given.

> For some popups I would like to use, with Lizmap, the QGIS HTML Maptip, and in others QGIS Drag&Drop form, obviously if it is not possible I would use only one of the two

Not sure I understood.
