### ISSUE TITLE
Please review the php var definition code in  QgisProject.php and WMSRequest.php  in 3.6.4 as in 3.7.0-alpha2

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#3809]
### What is the bug?

php ./console.php wmts:capabilities cetraro Cetraro
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Project/QgisProject.php on line 1924
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 798
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 801
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 801
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 967
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 967
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 967
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/lizmap/lizmap/modules/lizmap/lib/Request/WMSRequest.php on line 967

### Steps to reproduce the issue

substitute ${var} with {$var} to fix that errors

### Versions

**Versions :**

* Lizmap Web Client : 3.6.4
* Lizmap plugin : 3.15.1
* QGIS Desktop : 3.32.1
* QGIS Server : 3.32.1
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 4.0.3
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.32.0

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

Chrome 115.0.5790.102

**Comment by Gustry** [comment]
Can you make the PR ? You can make the change straight on GitHub.

**Comment by Antoviscomi** [comment]
@Gustry I'm not able to edit the code on Github, I need to fork the repository?

**Comment by Gustry** [comment]
You can, if you don't have enough permissions, it will create the fork for you automatically. It's what you did https://github.com/3liz/lizmap-web-client/pull/3810 now, thanks

**Comment by Antoviscomi** [comment]
@Gustry i hope i did well the PR

**Comment by laurentj** [comment]
All patchs backported manually into Lizmap 3.5 and 3.6.
