### ISSUE TITLE
[Question]: Activation de radio bouton pour l'activation des couches

### ISSUE THREAD

**Issue by jserieye** [3liz/lizmap-web-client#3819]
### What is the question?

Bonjour, 

Je cherche à activer l'option radio bouton pour les couches d'un groupe dans Lizmap (voir capture d'écran).

Visiblement, avec cette option l'utilisateur peut activer une seule couche du groupe.

Merci par avance.

![image](https://github.com/3liz/lizmap-web-client/assets/141012398/b75ac07e-baa3-474f-ae87-6f134083bf1b)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.5-pre.6193
* Lizmap plugin : 3.15.1
* QGIS Desktop : 3.28.7
* QGIS Server : 3.28.4
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.7.2
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.4

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Version 115.0.5790.110

**Comment by mdouchin** [comment]
Bonjour,
Dans QGIS, vous pouvez appliquer ce comportement en faisant un clic-droit sur un groupe et sélectionner "Groupe mutuellement exclusif". Lizmap reprend alors cette configuration et l'applique.

**Comment by Gustry** [comment]
Indeed, it's like in QGIS desktop : right click on a group in the legend, then click the "Mutually exclusive" button.

I'm closing because the question is answered by my colleague in French ;-)
