### ISSUE TITLE
Geolocation window - Different searches graphical division 

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#382]
Hi all,
Is it possible (or it could be an enhancement for future versions) to grapically divide different search in Geolocation Window? 
Basically (not this horrible graphic, it's just a rudimental example) something like this: 
![divide](https://cloud.githubusercontent.com/assets/20582012/18872369/6a4ceb90-84ba-11e6-8032-803688fe8d77.png)

**Comment by rldhont** [comment]
Fixed by 70c6ff0
