### ISSUE TITLE
[Question]: extending ckeditor in Lizmap WC landing page

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#3827]
### What is the question?

Hi all,

What is the proper way to extend (add new tools, like font color, or the
code editor) the WYSIWYG editor based on ckeditor available in the LMWC
backend, to customize the landing page?

Also > if it is possible to enable the code editor, then would PHP be
correctly parsed or it will be rendered as normal text?

Regards

### Versions

3.6.4

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04, desktop and server

### Browsers

Firefox, Chrome

### Browsers version

Latest

**Comment by gioman** [comment]
Not stale. The original question is still valid.

**Comment by nworr** [comment]
@gioman the editor "CKEditor" is provied by jelix, but it seems you can "live" edit its configuration in the file
lizmap\www\assets\jelix\js\jforms\htmleditors\ckeditor_ckdefault.js (it seem the "default" is used in most case) for example by adding fontColor feature https://ckeditor.com/docs/ckeditor5/latest/features/font.html 
Warning : this file will be overwritten to its original content on each update

PHP content won't be interpreted.

**Comment by gioman** [comment]
> the editor "CKEditor" is provied by jelix, but it seems you can "live" edit its configuration in the file
> lizmap\www\assets\jelix\js\jforms\htmleditors\ckeditor_ckdefault.js (it seem the "default" is used in most case) for example by adding fontColor feature https://ckeditor.com/docs/ckeditor5/latest/features/font.html

@nworr thanks for the tip



> Warning : this file will be overwritten to its original content on each update

That is too bad: I really think there is a clear use case to allow platform managers to enable some more functions of the WYSIWG editor. As it stands now is quite basic and while is ok for most, allowing to twak html/css manually is really important.



> PHP content won't be interpreted.

Do you mean the content of what is written in the editor?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
