### ISSUE TITLE
[Bug]: UI for mobile. Activate Hamburger button on Chrome

### ISSUE THREAD

**Issue by Crapaud04** [3liz/lizmap-web-client#3829]
### What is the bug?

When using lizmap on a tablet I realized that the group menu does not appear. Is desktop UI.

![menu_mobile](https://github.com/3liz/lizmap-web-client/assets/37582771/0706ab46-d842-4af7-9fff-8435c16c71d7)

The problem is on Chrome and not Firefox.

### Steps to reproduce the issue

1. Open project on Chrome on tablet

### Versions

**Versions :**

* Lizmap Web Client : 3.6.4
* Lizmap plugin : 3.15.1
* QGIS Desktop : 3.22.16
* Lizmap.com : Yes
* QGIS Server : 3.22.16
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.8.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.16

### Operating system

Serveur Valabre

### Browsers

Chrome

### Browsers version

Chrome 115

**Comment by nworr** [comment]
quick analyse : it seems linked to css rule for detecting non-desktop device `pointer :coarse`

see 
https://github.com/3liz/lizmap-web-client/blob/9196bcc0d3a4a53ab303de30ff178be6bc1d5eba/lizmap/www/assets/css/media.css#L177
and  https://github.com/3liz/lizmap-web-client/blob/9196bcc0d3a4a53ab303de30ff178be6bc1d5eba/lizmap/www/assets/css/media.css#L431

**Comment by Crapaud04** [comment]
Thank you for your message.

I read this blog post following your message.
https://www.ctrl.blog/entry/css-media-hover-samsung.html

Do you think we can change it css just on samsungs?

**Comment by nworr** [comment]
Thansk @Crapaud04  for the link, in comments there's another link 
https://andreasburg.de/browser-hover-check.html

For a confirmation, can you test this page with your tablet and see if pointing on the middle button works ?

![image](https://github.com/3liz/lizmap-web-client/assets/43475951/cf7d6b07-bb4f-40f3-b0e9-16063dc9e237)

**Comment by Crapaud04** [comment]
This result.
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/7ae4b363-0373-402b-a3f3-7742a7f20dd2)

I test this link https://hover-pointer-media-query.glitch.me/
In Chrome, i have this result 
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/2634fab8-0f94-420f-b070-66abf693bf28)

In autorun page (chronuim ?)
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/f705b6de-6a4d-426a-a8dd-05014ce81c58)
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/df2162fd-494c-43ac-a920-4f0342c2ef1a)

**Comment by nworr** [comment]
thanks for your feedback , so `@media(hover:none)` can't be trust 😞 

`@media(pointe:coarse)` may be the only relevant

**Comment by Crapaud04** [comment]
Yes. I don't know what's going on the side effects. 

For me,  i test this solution for change media.css . https://docs.lizmap.com/current/fr/publish/customization/themes.html
 And It works on my tablet. 
 Thank you for your help for identify this code problem.

**Comment by nworr** [comment]
you only remove the 2 "(hover: none)"  rules ?

**Comment by Crapaud04** [comment]
yes 
@media (hover: none) and (pointer: coarse) > @media (pointer: coarse)

**Comment by nworr** [comment]
The css fix has been pushed in code and will be available in the next releases (3.5, 3.6, 3.7).

Thanks for discovering it !
