### ISSUE TITLE
Does Updating Lizmap Web Client to 3.6 affect other elements (PHP, NGINX)?

### ISSUE THREAD

**Issue by AlexAtmo** [3liz/lizmap-web-client#3834]
### What is the question?

Hello,
I would like to update our API server on which Lizmap and QGIS server are installed.
Currently, we are using Lizmap 3.5.13 ;
To upgrade to version 3.6, I need to upgrade PHP from 7.3 to 7.4...
I have just one question :
Will updating Lizmap also update the NGINX server to incorporate PHP 7.4 FPM?
Thank you in advance.
Best regards

Alex                                                    

### Versions

Lizmap version : 3.5.13

QGIS Desktop version : 3.16

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

WIndows 10

### Browsers

Chrome

### Browsers version

Chrome version 115.0.5790.171

**Comment by laurentj** [comment]
>Will updating Lizmap also update the NGINX server to incorporate PHP 7.4 FPM?

Lizmap itself does not include PHP nor Nginx. So you must upgrade yourself PHP and Nginx. Or did I miss something? How did you install Lizmap, PHP and Nginx?

For Lizmap 3.6, prefer to upgrade PHP to its 8.1 version instead of 7.4.

**Comment by AlexAtmo** [comment]
Sorry about the delay; I was absent for a while.
Thank you for the response. Actually, I was just wondering if updating Lizmap would have any impact on PHP and NGINX. We need to conduct some tests before updating those two components, as updating the version might result in the obsolescence of some functionalities that we've been using for quite some time.

 > For Lizmap 3.6, prefer to upgrade PHP to its 8.1 version instead of 7.4.

I suppose updating PHP to the latest version is indeed preferable, considering that Lizmap will continue to evolve.

Thanks for the help !

Have a good day

**Comment by Gustry** [comment]
> I was just wondering if updating Lizmap would have any impact on PHP and NGINX.

Lizmap is just a PHP application. It won't install or upgrade packages on your OS.

Ok, thanks for the feedback. So I'm closing the issue.
