### ISSUE TITLE
Missing a comma in the output of WFS GetFeature as GeoJSON

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#3847]
Is it possible to display number of spatial objets in layers?
If there is no straightforward way already, I can think of using a custom js for it but I can't think of how to get the number of spatial objects in each layer.

**Comment by Gustry** [comment]
* No need for Javascript for this feature ;-)

![ksnip_20230821-085346](https://github.com/3liz/lizmap-web-client/assets/1609292/7fcaadce-4f79-4e1c-82d1-fa038536eae8)

* I will a single sentence in https://docs.lizmap.com/current/en/publish/configuration/legend.html I will do it just now.

* I'm not sure about this error in the JSON about the missing comma.

**Comment by jaitor1** [comment]
> * No need for Javascript for this feature ;-)
> 
> ![ksnip_20230821-085346](https://user-images.githubusercontent.com/1609292/261942544-7fcaadce-4f79-4e1c-82d1-fa038536eae8.png)
> 
> * I will a single sentence in https://docs.lizmap.com/current/en/publish/configuration/legend.html I will do it just now.
> * I'm not sure about this error in the JSON about the missing comma.

Tried it on my Lizmap 3.3 and Lizmap 3.5 also and it is not showing the number of features in my case. Maybe I am missing something or maybe it is a feature added in newer versions

**Comment by Gustry** [comment]
It's not related to Lizmap, but only QGIS server.
Please follow https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support at the bottom.

**Comment by jaitor1** [comment]
I am using QGIS Sever 3.10. Maybe it is a bit too old.

![image](https://github.com/3liz/lizmap-web-client/assets/12136796/acdddddf-0093-4b6a-a4f9-678078c7a3df)

**Comment by Gustry** [comment]
> I am using QGIS Sever 3.10. Maybe it is a bit too old.

Shouldn't be related.
So what is your LWC version precisely ? (in your administration webinterface) Maybe the missing comma is also fixed since... So this bug report is not necessary.

Even with LWC 3.3, the URL in your table should work. And your plugin is not up to date.

**Comment by jaitor1** [comment]
![image](https://github.com/3liz/lizmap-web-client/assets/12136796/d7811e8c-371c-4404-9e35-f5127efef72b)
Plugin is not up to date, you are right, my sys admin blocks any other internet connection in this gis server. I can update it by hand (copy/paste from another computer) but I was afraid of breaking something.
![image](https://github.com/3liz/lizmap-web-client/assets/12136796/bc814f09-54d0-4111-a126-0699942a10f9)
![image](https://github.com/3liz/lizmap-web-client/assets/12136796/6b463880-0a45-470c-acc6-6a95a2745225)

**Comment by Gustry** [comment]
Ok, so you are using LWC 3.3.3.

First, the branch version 3.3 is retired and not maintained anymore.

Then, within the branch 3.3, the latest one was 3.3.16 https://github.com/3liz/lizmap-web-client/releases/tag/3.3.16 a lot of bugfix between these 2.

Latest version of the plugin is still compatible QGIS 3.10 : https://plugins.qgis.org/plugins/lizmap/ then `Versions` tab. But the connection to the server is now required.

You should talk to your sys admin : QGIS should be able to access internet and the Lizmap server and also upgrade your Lizmap instance.

Closing, please reopen a ticket with a maintained version. I started updated the doc about the "Show feature count".
