### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by sag1687** [3liz/lizmap-web-client#3848]
### What is the question?

Hello everyone, I have this depicted project that contains shapefiles of the borders of the nations belonging to the European Union. As you can see, the project is in SR 4326. I'm having trouble bringing this project into Lizmap because it's showing completely centered on Austria or another nation. The project's extent is that of the figure, and I can't understand what I'm doing wrong. I've even tried representing a map of the Earth, but with the SR, it's not working. I also tried 3857 and 3085, but no luck. Do you have any suggestions?

![immagine](https://github.com/3liz/lizmap-web-client/assets/129679366/697c87e1-1633-4417-bcdc-d5cc35a7b39e)

![immagine](https://github.com/3liz/lizmap-web-client/assets/129679366/69ffddda-697f-44fa-82dd-206e6da1504c)

### Versions

QGIS 3.28 Firenze 
Lizmap 3.6.4

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22

### Operating system

Windows

### Browsers

Firefox

### Browsers version

edge

**Comment by r9zzai** [comment]
Your map extent is inside the bounds of epsg 4326 extent. You can check if your layers also are in the bound of their projection. If the layers bounds are inside their projection extent all should be fine from my experience.

What you can do furthermore if its not working is to reproject all layers and change project crs to epsg 3857.

**Comment by Gustry** [comment]
Please follow the issue template which was provided about versions. Read https://docs.lizmap.com/current/fr/publish/lizmap_plugin/information.html#request-for-support

**Comment by sag1687** [comment]
Thank you all, I've solved it by setting a different spatial extension than the default 4326.
