### ISSUE TITLE
[Question]: pgservice lizmap

### ISSUE THREAD

**Issue by sag1687** [3liz/lizmap-web-client#3855]
Hello everyone, I would need to use a QGIS project with layers saved in PostgreSQL. I don't want to keep the database passwords stored in the QGIS file. Instead, I would like them to be read from a pgservice file. The documentation on this matter is quite unclear for those who are not familiar with all the aspects. I would be grateful if someone could provide me with a schematic guide on where to configure the file, considering that I am using a machine with Ubuntu Server, QGIS 3.28, Lizmap 3.6.4, and Apache (I don't have a Docker installation, but a raw one). The entire documentation on pgservice is very scattered, and I'm having trouble following certain steps, also because they are taken for granted by the guide's autho

### Versions

3.28

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

ubuntu server 22

### Browsers

Firefox

### Browsers version

89

**Comment by Gustry** [comment]
There is not too much documentation on our side because it's not a "Lizmap" concept.

https://docs.lizmap.com/current/en/publish/lizmap_plugin/edition.html#prerequisites at the bottom of the prerequisites, there are two links about service file which redirects to QGIS and PostgreSQL websites.

**Comment by mdouchin** [comment]
Indeed, the QGIS docs is the more complete I know about service files

**Comment by Gustry** [comment]
Just some resources if someone find this ticket, there is also this link https://github.com/3liz/lizmap-web-client-demo/blob/master/INSTALLATION.md
when we download one demo project from https://demo.lizmap.com using a PG service file.
