### ISSUE TITLE
[Bug]: docker image crashes on startup with ldapdao enabled because app/system/cmdline/auth.coord.ini.php is outdated

### ISSUE THREAD

**Issue by maxencelaurent** [3liz/lizmap-web-client#3862]
### What is the bug?

After enabling LDAP authentication on a fresh and working docker container, lizmap is not able to start any longer.

It crashes with such a statement:
```
Too few arguments to function ldapdaoAuthDriver::__construct(), 0 passed in /www/lizmap/vendor/jelix/jelix/lib/jelix/core/jAppInstance.php on line 414 and exactly 1 expected /www/lizmap/vendor/jelix/ldapdao-module/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php 30
```

The reason is the https://github.com/3liz/lizmap-web-client/blob/master/lizmap/app/system/cmdline/auth.coord.ini.php is outdated.
It should contain a `[ldapdao]` section just like the https://github.com/3liz/lizmap-web-client/blob/master/lizmap/app/system/admin/auth.coord.ini.php do.

# workaround
The missing snippet can be injected in the localconfig by editing `lizmap-config/localconfig.d/ldapdao.ini.php`:

```
[auth_ldapdao]
compatiblewithdb=on
dao="lizmap~user"
profile=jauth
ldapprofile=lizmapldap
password_crypt_function=sha1
form="lizmap~account_admin"
userform="lizmap~account"
uploadsDirectory=
jelixAdminLogin=admin
```

### Steps to reproduce the issue

1. git clone https://github.com/3liz/lizmap-docker-compose.git
2. cd lizmap-docker-compose
3. configure the stack using 3.6 version : `LIZMAP_VERSION_TAG=3.6 ./configure.sh configure`
4. `docker compose up`
5. Enable LDAP authentication according to [the doc](https://docs.lizmap.com/3.6/en/install/ldap.html)
6. Restart lizamp `docker compose restart lizmap`

### Versions

3.6

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

not relevant, as lizmap do not even start

### Operating system

Linux

### Browsers

Firefox

### Browsers version

not relevant

**Comment by laurentj** [comment]
It has been fixed in Lizmap 3.6.8
