### ISSUE TITLE
Select children from one-to-many relations inside compact table view

### ISSUE THREAD

**Issue by ea-phanvan** [3liz/lizmap-web-client#3870]
I would like to have that compact table with sort and search options of all related children with an “select” option. For example at the left side there would be that check mark to select one entry (one related child) inside that compact table view.

**Comment by nboisteault** [comment]
@ea-refit thanks for opening this ticket, we will send you an estimate quickly.

**Comment by ea-refit** [comment]
Any news about the estimate?

Von: Nicolas Boisteault ***@***.***>
Gesendet: Freitag, 8. September 2023 14:04
An: 3liz/lizmap-web-client ***@***.***>
Cc: Refit, Ea ***@***.***>; Mention ***@***.***>
Betreff: Re: [3liz/lizmap-web-client] Select children from one-to-many relations inside compact table view (Issue #3870)

  CAUTION:  This email was sent from outside the company. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@ea-refit<https://github.com/ea-refit> thanks for opening this ticket, we will send you an estimate quickly.

**Comment by nboisteault** [comment]
@ea-refit Sorry for the delay. I opened a ticket internally. Can you give your email address sending it to mine (github profile)?

**Comment by nboisteault** [comment]
@ea-phanvan Hi, I'm working on it.

**Comment by nboisteault** [comment]
@ea-phanvan it is now in our master branch. Please test when possible.

**Comment by ea-phanvan** [comment]
Sorry, unfortunately I can’t test it anywhere, as our lizmap instance is hosted by your 3liz colleagues. In our company we do not have any linux servers that I could use for testing. On windows it’s too tricky to establish.

Von: Nicolas Boisteault ***@***.***>
Gesendet: Dienstag, 7. Mai 2024 15:55
An: 3liz/lizmap-web-client ***@***.***>
Cc: Phan Van, Ea ***@***.***>; Mention ***@***.***>
Betreff: Re: [3liz/lizmap-web-client] Select children from one-to-many relations inside compact table view (Issue #3870)

  CAUTION:  This email was sent from outside the company. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@ea-phanvan<https://github.com/ea-phanvan> it is now in our master branch. Please test when possible.
