### ISSUE TITLE
[Bug]: WMS created my LizMap not accessable by other GIS

### ISSUE THREAD

**Issue by meyerlor** [3liz/lizmap-web-client#3875]
### What is the bug?

It is not possible to open the WMS URL of a project in other GIS software (except QGIS).
I tested it with my public test project as well with the "[Cats Movement](https://demo.lizmap.com/lizmap/index.php/view/map?repository=features&project=cats)" demo project of Lizmap.

I tried to open the WMS URL with MapInfo 19 and also with the [Geo-Portal of Baden-Wurtemberg](https://www.geoportal-bw.de/#/(sidenav:kartehinzufuegen))

### Steps to reproduce the issue

Copy & Paste the WMS URL into any other GIS software available to me

https://demo.lizmap.com/lizmap/index.php/lizmap/service?repository=features&project=cats&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

### Versions

Lizmap 3.6.5

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

Firefox 115

**Comment by Gustry** [comment]
Can you please provide the error with this other GIS tool ?

Some other GIS tools are expecting a shorter URL like : 

* https://demo.lizmap.com/lizmap/index.php/lizmap/service?repository=features&project=cats&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
* https://demo.lizmap.com/lizmap/index.php/lizmap/service?repository=features&project=cats

QGIS will accept both URLS, (it will add missing parameters).

Also some tools might expect the URL from a LAYER directly, which is given by the GetCapabilities

I tried just now [Geo-Portal of Baden-Wurtemberg](https://www.geoportal-bw.de/#/(sidenav:kartehinzufuegen)) with our demo project, I get a "CORS missing allow origin" which is not related to Lizmap Web Client it self, but to our own HTTP server which doesn't accept requests providing from a not authorized website. See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In the administration interface, then "Lizmap repositories", you can configure the list of websites authorized requesting WMS/WFS etc.

**Comment by meyerlor** [comment]
Hello,
with the shortened URL i get in MapInfo the same response: 
![grafik](https://github.com/3liz/lizmap-web-client/assets/15894401/a57b6a48-e616-4952-b618-028695ed69b4)

which translates to: "Error while connectiong to the server. HTTP Statuscode is 501. The map could not be recieved from the WMS-server."

I tried it with my project as well with yours - the link to my project is: https://klak.gisgeometer.de/

**Comment by gioman** [comment]
@meyerlor does it work if you bypass LMWC and use the WMS defined by only QGIS Server and your project?

**Comment by Gustry** [comment]
> HTTP Statuscode is 501

This means error on the server side, error 5XX. It would nice to know what happened in the backend, there should be an a more global error.

**Comment by meyerlor** [comment]
@gioman that somehow does work - i moved the project to /home/qgis/projekte/mibibaum.qgs and tried to access it with http://92.205.104.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/home/qgis/projekte/mibibaum.qgs and voila, no error messages.

@gustry any specific logs i could dig into? The LMWC error logs are empty as far as i can tell

**Comment by gioman** [comment]
> @gioman that somehow does work - i moved the project to /home/qgis/projekte/mibibaum.qgs and tried to access it with http://92.205.104.45/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/home/qgis/projekte/mibibaum.qgs and voila, no error messages in MapInfo
> 
> @Gustry any specific logs i could dig into? The LMWC error logs are empty as far as i can tell

@meyerlor you should probably look into the web server logs

**Comment by meyerlor** [comment]
In the general access log of apache i found:

`37.24.0.98 - - [14/Sep/2023:12:15:12 +0200] "GET /index.php/lizmap/service?repository=mittelbiberach&project=mibibaum&VERSION=1.3.0&REQUEST=GetMap&LAYERS=Baum&STYLES=&CRS=EPSG:4326&BBOX=48.064222,9.734253,48.091749,9.767409&WIDTH=189&HEIGHT=157&FORMAT=image/png&TRANSPARENT=TRUE&BGCOLOR=0xFFFFFF&EXCEPTIONS=XML HTTP/1.1" 501 874 "-" "MapInfoPro/19.0.3.0045 (MapInfoPro.exe)"`

The Apache error log has no entries matching to the time when i tried opening the WMS via MapInfo

**Comment by Gustry** [comment]
You should check : 
* if your apache error log is configured related to your previous comment
* the file `lizmap/var/log/errors.log`

**Comment by meyerlor** [comment]
I double checked the logs - nothing here which matches the timestamps of my attempts :(

**Comment by r9zzai** [comment]
For map info it seems that the ssl certificate for the https request has to be registered to map info see https://customer.precisely.com/s/article/Error-opening-HTTPS-WMS-services-in-MapInfo-Pro-where-HTTP-works-properly?language=en_US

**Comment by meyerlor** [comment]
@r9zzai I checked the link you provided - that is not the problem i'm having. When i add the server url it correctly "connects" (showing the right service description/short name as well as the layers included in the project)

What is happening when you try to open a WMS created by Lizmap with any other GIS software except QGIS? I'm still trying to figure if its a LWC problem, a problem of my server or a problem of the GIS software i'm trying to connect to the server.

**Comment by Gustry** [comment]
> showing the right service description/short name as well as the layers included in the project)

Your question is not very clear. So you mean you can add your layer in QGIS desktop from the LWC WMS ? But nothing appears in the map ?
And it works in the LWC interface ?

**Comment by meyerlor** [comment]
sorry for the confusion.
When i add the WMS in MapInfo ( as @r9zzai provided an articel from the MapInfo Knowledgebase) it connects sucessfully - meaning, the description of the LWC is loaded, as well as all layers which are in the project are shown. The 501 error message of my original post comes as soon it trys to load an actual map.

Do you have access to any other GIS software except QGIS and can load layers from your LWC project? Because as mentioned, QGIS can load layers and show them on the map. Just any other GIS-software i have acess to (Mapinfo and GeoGraf can not add layers from LWC WMS)

**Comment by meyerlor** [comment]
Is the issue for you replicable? Is any more information needed?

**Comment by Gustry** [comment]
Lizmap is a WMS client it self, using the WMS from QGIS server in the OpenLayers library
QGIS desktop as well, is another WMS client.

Either in QGIS or in a webbrowser, we can see requests like 
https://demo.lizmap.com/lizmap/index.php/lizmap/service?repository=features&project=cats&LAYERS=v_daily_territory&STYLES=d%C3%A9faut&VERSION=1.3.0&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&DPI=96&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetMap&CRS=EPSG%3A3857&_OLSALT=0.3735116579164517&BBOX=-8202397.324266152,5029996.113389251,-8200854.25175786,5030847.669657373&WIDTH=1292&HEIGHT=713

This request is from the cat project.

Indeed, it's possible to debug using QGIS server straight, without Lizmap involved, just to debug only.

> I double checked the logs - nothing here which matches the timestamps of my attempts :(

When there is a 500 error from a server, there should be some logs, with a stack trace, a  QGIS server error, or PHP, Python or something.
