### ISSUE TITLE
`getDefaultTheme` creates a zipfile with wrong permissions

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#389]
When downloading a sample theme, the zipfile has folders and files with `700/600` permissions instead of `755/644` as expected. As a result, themes will not work, without a warning to the user, unless the user changes the permissions manually. This is not documented in the manual, bet nevertheless is not the most friendly behaviour.

**Comment by rldhont** [comment]
@laurentj in `service.classic.php`:
```php
function getDefaultTheme() {
    $rep = $this->getResponse('zip');
    $rep->zipFilename='lizmapWebClient_default_theme.zip';
    $rep->content->addDir(jApp::wwwPath().'/themes/default/', 'default', true);
    return $rep;
  }
```
Can we manage the permissions ?

**Comment by laurentj** [comment]
Zip format does not include informations about permissions on files and directories (at least in the ZIP version used by lizmap). So this is the tool you are using to unzip which sets these permissions 700/600. See if there are options in your tool to set default permissions on extracted files/directories.

However, improvements could be done into the Jelix code to set permissions into the ZIP file.

**Comment by rldhont** [comment]
@pcav can you provide some feedbacks ?

**Comment by rldhont** [comment]
I close it, reopen if needed
