### ISSUE TITLE
Control for layer transparency

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#39]
As often available in webgis applications as a slider.

**Comment by mdouchin** [comment]
Done with c588a1df754c0eaa9399641090e2a7e072bbb6aa 
Not with a slider, as not really HTML standard yet ( browser compatibility issues).

Select the layer by clicking on its name -> this now opens the layer information panel. Then, you can either
* Use the "eye icon" button in the layer tools bar above the layer tree
* Use the buttons in the layer information panel:  20 / 40 / 60 / 80 / 100

Something missing now : the current transparency is not showed ( for example, if the user sets 40, the "40" button should have a blue border to indicate this opacity is active for the layer )

**Comment by gioman** [comment]
@mdouchin many thanks! this is a much appreciated and very useful improvement.

**Comment by josemvm** [comment]
great!!!

**Comment by rldhont** [comment]
@gioman do you think we can close this issue ?

**Comment by gioman** [comment]
@rldhont yes of course!
