### ISSUE TITLE
attribute table - table doesn´t show values in media field

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#390]
it shows the alias name instead of the value name

![table](https://cloud.githubusercontent.com/assets/10053874/18993623/01f3106a-871c-11e6-879b-431a9908fc4b.jpg)

**Comment by josemvm** [comment]
after commit https://github.com/3liz/lizmap-web-client/commit/d75dbdd2cec4a1b7269ed1084167966bce251dbf ...

**Comment by mdouchin** [comment]
it is kind of made on purpose, since we do not want to display file paths there. Do you miss it ?

**Comment by josemvm** [comment]
yes, i think that it is very useful for many situations

the file path helps to understand the content before opening and helps to prevent or debug errors related to the name of the media files

**Comment by josemvm** [comment]
maybe my question doesn't make sense...
