### ISSUE TITLE
tool to change layer opacity

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#391]
if a layer has a layer transparency value defined in qgis project, it's not possible to increase the opacity.

opacity value 100/lwc = layer transparency value/qgis

**Comment by josemvm** [comment]
in this regard and if possible, i think  it will also be important to consolidate this tool in upcoming version 3.1

thanks in advance for your contribution to improve this feature

**Comment by rldhont** [comment]
Hi @josemvm,

I'm not sure to understand the issue.
In the map part, the opacity is manage by the web client, opacity is applied to images displayed in html.
In the print part, the opacity is manage by QGIS Server.
So where is the issue ?

**Comment by josemvm** [comment]
hi @rldhont,

if you have a project in QGIS Desktop with a
- postgis layer (polygon)
	- layer style, transparency = 50
	
LWC
- doesn´t "read" the transparency value (50) from project...
- shows the layer with the correct opacity (50)
- but assumes taht this value (50) corresponds to opacity value 100!

so, the tool to change layer opacity only permit to decrease opacity (from value 50), doesn't allow reaching full opacity (value 100)

**Comment by josemvm** [comment]
LWC shows and print this image with 50% transparency set in QGIS project (for LWC opacity = 100)
![fig1](https://cloud.githubusercontent.com/assets/10053874/20392926/da8be624-acd1-11e6-867f-321ea179c62d.jpg)

if you click over the 40 opacity button (for LWC opacity = 40 x 50%)
![fig2](https://cloud.githubusercontent.com/assets/10053874/20392969/ff32ff62-acd1-11e6-84d6-97fa97d21dfa.jpg)

in this case and using tool to change layer opacity, it's not possible to reach this (opacity 100%)
![fig3](https://cloud.githubusercontent.com/assets/10053874/20393001/1c8dc51a-acd2-11e6-9f5d-4f266fb03fc7.jpg)

**Comment by nboisteault** [comment]
Client side and server side transparency are different.
When you set an opacity for a WMS layer server side it is not linked to the viewer displaying it.
If a user is displaying your layer in QGIS for example and not lizmap he'll have no idea that you have set an opacity.
A solution would be to be able to set the default opacity in lizmap plugin for first view then the user will be able to increase or decrease opacity.

**Comment by josemvm** [comment]
thanks @nboisteault

i think that's an important feature such as often available in webgis applications

@rldhont if you agree to implement this feature i can open a new issue in lizmap plugin, otherwise you can close this issue here

**Comment by rldhont** [comment]
Hi @josemvm,
You can defined Opacity in almost 2 point:
* at the color
* at the symbol
* at the layer

The first can't be changed by lizmap or QGIS Server. Because you can defined fill with 50% opcaity and a border with 100% opacity.

The second is changed by QGIS Server the way is: symbol->->alpha() * opacityRatio. The third is changed by Lizmap with the same rule as the second.

If you want to change it, we firstly have to change QGIS Server, so I closed it and if QGIS Server is changed, we probably changed Lizmap.
