### ISSUE TITLE
Repository view: size of the project div adapting to the largest item

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#392]
In a LM installation, if one project in one repo has a taller icon, all other projects in all repos will have a blank space below it.
See https://lizmap.faunalia.eu/index.php/view/ for an example.

**Comment by nboisteault** [comment]
@pcav Does issue still occurs ?

**Comment by nboisteault** [comment]
@pcav can we close issue ?

**Comment by pcav** [comment]
It is still true, see the link above. However, it is not serious, feel free to close it.
