### ISSUE TITLE
[Bug]: jcommunity~user:create fails when multiauth is enabled, docker container stuck restarting

### ISSUE THREAD

**Issue by u-cav** [3liz/lizmap-web-client#3922]
### What is the bug?

[The docker-entrypoint script attempts to create an admin user, if it does not exist](https://github.com/3liz/lizmap-web-client/blob/104117a6ee1cb1b50224ea806c5b486dfd3e0dee/docker/lizmap-entrypoint.sh#L145C12-L145C96).

This command fails if [Jelix multiauth module](https://github.com/jelix/multiauth-module) is enabled, with the following error:

`Too few arguments to function multiauthAuthDriver::__construct(), 0 passed in /www/lizmap/vendor/jelix/jelix/lib/jelix/core/jAppInstance.php on line 414 and exactly 1 expected /www/lizmap/my-packages/vendor/jelix/multiauth-module/multiauth/plugins/auth/multiauth/multiauth.auth.php    37`

This causes the container to fail on startup if the stack is restarted.

### Steps to reproduce the issue

1. [Run the Lizmap docker-compose test stack](https://github.com/3liz/lizmap-docker-compose)
2. [Install the multiauth module](https://github.com/jelix/multiauth-module/blob/master/INSTALL_INTO_LIZMAP.md):
3. `docker exec -it lizmap-docker-compose-lizmap-1 sh`
4. `lizmap-install-module "jelix/multiauth-module"`
5. `cd lizmap/install/`
6. `php configurator.php multiauth`
7. `php installer.php`
8. `./clean_vartmp.sh`
9. `./set_rights.sh 1000 1000` (might need to adjust uid and gid)
10. Everything works, including auth and LDAP if configured. If you run a 
11. Restart the container, it will fail to start

### Versions

**Versions :**

* Lizmap Web Client : 3.6.6
* Lizmap plugin : 3.17.1
* QGIS Desktop : 3.28.9
* QGIS Server : 3.28.10
* Py-QGIS-Server : 
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.10

### Operating system

Debian 10

### Browsers

Firefox, Chrome

### Browsers version

Firefox 118.0.1

**Comment by u-cav** [comment]
I can confirm that this issue also happens in a non-docker environment, as long as multiauth is installed. In this case Lizmap works correctly, since there is no entrypoint, but trying to add/reset an user from the cli will give the error mentioned above.

**Comment by laurentj** [comment]
The bug is fixed into the next Lizmap 3.6 release. Thanks for your detailed report.

**Comment by u-cav** [comment]
Thank you @laurentj
