### ISSUE TITLE
sterea forward

### ISSUE THREAD

**Issue by jankoja** [3liz/lizmap-web-client#393]
in
lizmap/modules/proj4php/classes/projCode/sterea.php
line #47
-$p->y = $k * ($this->cosc0 * sinc - $this->sinc0 * $cosc * $cosl);
+$p->y = $k * ($this->cosc0 * $sinc - $this->sinc0 * $cosc * $cosl);

$ sign missing

**Comment by mdouchin** [comment]
Thanks for your contribution. Do you prefer to do a pull request, so that you become a lizmap dev contributor with your named commit, you do you prefer me to do this bugfix ?

**Comment by jankoja** [comment]
Pull request created.

**Comment by rldhont** [comment]
Merged thanks
