### ISSUE TITLE
[Bug]: In Edit mode UPDATE dosen't do its job

### ISSUE THREAD

**Issue by pizzuga** [3liz/lizmap-web-client#3932]
### What is the bug?

I upgrade from 3.6.4 to 3.6.7.
In edit mode I can INSERT new data.
In UPDATE instead even if the message, after saved the form, says it all okay, the update is not appened.
Coming back to 3.6.4 solved the problem and the UPDATE works as expected

### Steps to reproduce the issue

As in production, I haven't time to test other layers, but downgrading 3.6.4 solved the problem, so I think it's a bug of (at least 3.6.7).

### Versions

**Versions :**

* Lizmap Web Client : 3.6.4
* Lizmap plugin : 3.17.1
* QGIS Desktop : 3.28.11
* QGIS Server : 3.28.11
* Py-QGIS-Server : 
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Server: Debian GNU/Linux 11 (bullseye) , client: Ubuntu 22.04.3 LTS

### Browsers

Firefox

### Browsers version

Firefox 118.0.1 (64 bit)

**Comment by pizzuga** [comment]
Thank you for your quickly reply!
I mean editing attribute. I try in the URL you provided and I can insert a new line, and after, update and save the field "label". 
I'll check in a test machine to try to reproduce the problem and keep you informed.

thanks

**Comment by Gustry** [comment]
> Thank you for your quickly reply!

This feature of editing a feature is tested automatically by the CI process and also some manual testing before each release (because it's very important), that's why it was quick to answer without more context about the failure.

Check Lizmap logs, you shoud see the SQL request failure maybe ?
