### ISSUE TITLE
Lizmap, PostgreSQL and PHP

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#3938]
### What is the question?

I need to make a fresh install. 
i like to know if I can install PHP version 8 and PostgreSQL 16?
On the documentation, it is unclear if it will work…
Thank you for your answer!

### Versions

Lizmap 3.6

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28

### Operating system

Ubuntu 22

### Browsers

Firefox

### Browsers version

Firefox

**Comment by Gustry** [comment]
> i like to know if I can install PHP version 8 and PostgreSQL 16?

We use PHP 8 in production https://endoflife.date/php 

PostgreSQL 16 was just released last month, we haven't used in production yet. Only in a few automatic tests. https://endoflife.date/postgresql

> On the documentation, it is unclear if it will work…

Which page precisely ? Which URL did you check, so it can be edited ? Thanks

**Comment by katagen** [comment]
On this [page](https://docs.lizmap.com/current/fr/), we speak of PHP version 7, and PostgreSQL 13.

So it will work with PostgreSQL 15?

And apart that, why is the exemple of an installation with Apache has dissapeared? There is only for nginx... the lizmap.conf exemple!

**Comment by Gustry** [comment]
> On this [page](https://docs.lizmap.com/current/fr/), we speak of PHP version 7, and PostgreSQL 13.

Ok, this was just the version used at that time, not compatibility.

We started adding a table with what was used for automatic testing (which is legacy versions for now https://github.com/3liz/lizmap-web-client/releases/tag/3.7.0-beta.1)

> So it will work with PostgreSQL 15?

Yes, some are already using it in production.

**Comment by katagen** [comment]
Perfect, thank you!
Just to know, on this [page](https://github.com/3liz/lizmap-web-client/wiki/Versions), you only recommend PostgreSQL 13.

**Comment by Gustry** [comment]
> And apart that, why is the exemple of an installation with Apache has dissapeared? 

It's complicated to maintain a documentation and Lizmap is a "normal" PHP application. 

https://docs.lizmap.com/current/en/install/pre_requirements.html#server-administration-knowledge
