### ISSUE TITLE
[Bug]: filter don't filter shape in Lizmap 3.6.7

### ISSUE THREAD

**Issue by Crapaud04** [3liz/lizmap-web-client#3948]
### What is the bug?

Hello, 
After the version upgrade, the filter panel no longer works.
We choose the layer then the filter but nothing changes on the map or in the display of the data table.

The count is correct.
I did not modify any parameters in our version release.

![image](https://github.com/3liz/lizmap-web-client/assets/37582771/2da067e5-cf8d-452b-801d-7544a0c25e64)

https://www.opensis.fr/04/index.php/view/map?repository=deci&project=deci

Mais sur le projet démo de Cartophyl pas de problème 
https://cartophyl.lizmap.com/demo/index.php/view/map?repository=cartophyl&project=street_art_pap

### Steps to reproduce the issue

1. select shape
2. select filter
3. nothing is happening except object count.

### Versions

**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.28.11
* Lizmap.com : Yes
* QGIS Server : 3.28.11
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.18.1
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.11

### Operating system

Serveur Valabre

### Browsers

Firefox, Chrome

### Browsers version

Firevox 119 chrome 118

**Comment by Crapaud04** [comment]
Following problem with version upgrade of the plugin or Qgis which did not detect the correct primary key. (alias - field name)

**Comment by Gustry** [comment]
The plugin is warning these issues, in the "Log" panel, when saving the CFG file, right ?

**Comment by Crapaud04** [comment]
No message in "Log" panel
Cfg : 
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/a21547ad-84e1-4bd1-bc2a-8c649a96635f)
Plugin (Table attributaire) : 
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/3a3a8c89-a0ff-42bf-9458-9aa5256115f7)
Log panel : 
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/d8f19b7c-36dd-415d-8455-cb296ead63bc)

**Comment by Gustry** [comment]
Ok, but this is different. The missing icon the plugin (screenshot above Plugin (Table attributaire) :) indicates that the field doesn't exist anymore in your layer.
Otherwise, you should have the icon of the field displayed (integer, text, float etc), so you must review the configuration.
THis will be a little bit different in the next version of the plugin hopefully

**Comment by Crapaud04** [comment]
Ok i see icon. 
![image](https://github.com/3liz/lizmap-web-client/assets/37582771/1f5103d1-3667-4998-a5db-ef260d1cf162)

But it's strange the link between form and table.
