### ISSUE TITLE
Affichage de l'outil edition dans le client web

### ISSUE THREAD

**Issue by jbdesbas** [3liz/lizmap-web-client#395]
Bonjour,

Je cherche a rendre éditable une couche sqlite sur Lizmap 3.1.
J'ai surement raté quelque chose : dans le client web la couche sqlite s'affiche correctement mais je n'ai aucun bouton permettant d'accéder à l'outil édition.
- Dans le plugin j'ai bien ajouter la couche dans outils --> edition de couche
- Dans l'interface d'admin du client j'ai activer les droits d'édition pour tous les utilisateurs

Je tourne un peu un rond du coup... J'ai même activer les capacité WFS
php5-sqlite3 est installé
Je suis sous ubuntu 14.04 

L'outil edition ne s'affiche pas non plus dans l'exemple "Montpellier"

Merci d'avance de votre aide

**Comment by jbdesbas** [comment]
Je pense avoir un début de réponse dans le log..:

> 2016-10-09 11:29:09	79.88.221.172	warning	2016-10-09 11:29:09	[2]	SQLite3::loadExtension(): SQLite Extension are disabled	/var/www/mylizmap/lizmap/modules/lizmap/classes/lizmapProject.class.php	958

**Comment by jbdesbas** [comment]
Résolu grâce à http://www.gaia-gis.it/spatialite-2.4.0-4/splite-php.html
Par contre les fichier libspatialite.so et mod_spatialite.so sont dans /usr/lib/x86_64-linux-gnu et non dans /usr/local/lib/

**Comment by mdouchin** [comment]
C'est référencé dans la doc
http://docs.3liz.com/fr/install/linux.html?highlight=%C3%A9dition#enable-spatialite-extension

Merci de proposer un Pull Request si vous pensez que la documentation n'est pas suffisante, afin de la rendre plus claire pour les utilisateurs confrontés à la même question
