### ISSUE TITLE
[Question]: How to add buton to export layer in XLSX

### ISSUE THREAD

**Issue by jserieye** [3liz/lizmap-web-client#3956]
### What is the question?

Hello, 

I am looking to add a button to export a layer (by default) in xlsl format.

The goal is to add this button in the nav nav-list to avoid the user having to open the attribute table.

Thank you.

Jérémy

### Versions

Lizmap 3.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Chrome

**Comment by r9zzai** [comment]
If you click on the layer in the layer tree there should be a dropdown where u can select the format, e.g. xlsx. Then click the downarrow button right aside.

**Comment by jserieye** [comment]
Precisely, the goal is not to do this manipulation but to have a directly accessible button.

> If you click on the layer in the layer tree there should be a dropdown where u can select the format, e.g. xlsx. Then click the downarrow button right aside.

**Comment by Gustry** [comment]
Duplicated request with one answer from @nworr with a proposal https://github.com/3liz/lizmap-javascript-scripts/issues/66

**Comment by jserieye** [comment]
I tried with the answer from @nworr .

`lizMap.exportVectorLayer('a_batiments', 'XLSX', restrictToMapExtent )`

However nothing happens. 

I think I'm formulating the variables wrong.

**Comment by jserieye** [comment]
When I export with the attribute table button, I have "export_a_batiments.xlsx".

the variables (layername='a_batiments' and exportFormat ='XLSX' ) are therefore good.

what do I need to enter for the restrictToMapExtent variable?

**Comment by nworr** [comment]
sorry , i forgot some explanation :  `restrictToMapExtent ` is a boolean (true if you want to download only data inside the map view, false if not) .

any error in your javascript console ?

**Comment by jserieye** [comment]
Ok , With `lizMap.exportVectorLayer('a_zone_urba_ndfci', 'xlsx', 0)`
I have the error -> Uncaught TypeError: Cannot read properties of undefined (reading 'geometryType')
Do I need to enter an additional geometry variable?

**Comment by jserieye** [comment]
Here is my entire script :

lizMap.events.on({
    uicreated: function(e) {
      lizMap.addDock(
            'export',
            'Export',
            '',
            '',
            'icon-download'
        );
        $(function () {
          $('#mapmenu li.export a').click(function () {                       
            lizMap.exportVectorLayer('a_zone_urba_ndfci', 'XLSX', 0)
            //lizMap.exportVectorLayer(layername, exportFormat, restrictToMapExtent )
});
          });      
    }
});
lizMap.events.on({
    uicreated: function(e) {
        $('#mapmenu li.export').insertBefore('#mapmenu li.home')
    }
});

**Comment by nworr** [comment]
`a_zone_urba_ndfci` seems to be unknown, 
` Object.keys(lizMap.config.layers) ` will provided the list of known layers

**Comment by jserieye** [comment]
I had entered the short name of the layer in Qgis server and not the name present in the layer tree.

It's ok now, thanks ;)
