### ISSUE TITLE
[Question]: Problème de popup en fonction de la base de données source

### ISSUE THREAD

**Issue by aberceaux** [3liz/lizmap-web-client#3958]
### What is the question?

Bonjour,

Je butte sur ce problème depuis plusieurs jours sans trouver la solution.

Suite à une upgrade du serveur Ubuntu qui héberge Postgresql, QGIS et Lizmap, je me trouve confronté à un problème d'affichage de popup qui dépend de la base de données qui contient la couche SIG.

Sur l'ensemble des tables géographiques d'une même base de données, il est impossible d'afficher des popup dans Lizmap : "Aucun objet n'a été identifié à cet endroit."

Si je copie une de ces couches dans une autre base de données, là les popup s'affichent.

J'ai testé les droits d'accès, cela ne parait pas venir de là.

La source du problème vient donc très probablement de la base de données, mais je ne vois pas comment cela joue avec Lizmap. C'est pourquoi je m'adresse à vous.

Merci d'avance

### Versions

**Versions :**

* Lizmap Web Client : 3.6.5
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.28.11
* QGIS Server : 3.32.3
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : v1.5.2

PostgreSQL 12.16 (Ubuntu 12.16-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

 22.04.3 LTS

### Browsers

Firefox

### Browsers version

119

**Comment by nboisteault** [comment]
Bonjour,
Vous pouvez commencer par mettre à jour votre Lizmap et aussi il vous faut avoir la même version de QGIS Desktop et Server pour éviter tout problème.

**Comment by aberceaux** [comment]
Vous pouvez clore ce ticket. Le problème venait d'une mauvaise installation de postgis. Lizmap n'y est pour rien !
Bonne année !

**Comment by nboisteault** [comment]
Parfait !
Bonne année !
