### ISSUE TITLE
Allow admin to define the duration of the email's link for password creation when creating an account

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#3959]
Hi,

When creating a new account, users have 24 hours to click on the link in the email that allows creating their password. Would it be possible to have an option in the admin interface to let the the administrator defines a different duration (2 or 3 days for example).

Thanks

**Comment by nworr** [comment]
Not tested but according to [jcommunity code](https://github.com/jelix/jcommunity-module/blob/c7a6a528910d0af97f30962abfbb3b6b66b2cd5a/modules/jcommunity/lib/Config.php#L61) you can set a `validationKeyTTL` param (value in minute) in [the jcommunity section of your mainconfig.ini](https://github.com/3liz/lizmap-web-client/blob/45da9234f76345af0e65a10f5bf493a18c3bd4f7/lizmap/app/system/mainconfig.ini.php#L264)

the value cannot exceed 7 days (10080 min)

**Comment by arno974** [comment]
Thanks ! Good to know. I'll let @laurentj to confirm that and I will do it.

**Comment by laurentj** [comment]
@arno974 yes this is the right parameter. but set it into the var/config/localconfig.ini.php, not into the mainconfig.ini.php as it is a file provided by lizmap, and your settings could be erased during the futur upgrade. Example for 3 days:

```ini
[jcommunity]
validationKeyTTL=4320 
```

**Comment by laurentj** [comment]
and yes, it is taken account int the email content.

**Comment by arno974** [comment]
Perfect, thanks @laurentj  and @nworr !
