### ISSUE TITLE
[Question]:  How to send user email to Postgresql ?

### ISSUE THREAD

**Issue by nde34** [3liz/lizmap-web-client#3960]
### What is the question?

Hello,

I'm trying to do this [ICI](https://docs.lizmap.com/3.5/fr/publish/customization/javascript.html) to get the user email transfered to postgresql when he save modification on the edition form.
```
var userFields = {
   login: 'your_lizmap_user_login_field',
   firstname: 'your_lizmap_user_firstname_field',
   lastname: 'your_lizmap_user_lastname_field',
   organization: 'your_lizmap_user_organization_field'
};
```

What's the name for the email variable ?

i tried

```
email:'your_lizmap_user_email_field'
mail:'your_lizmap_user_email_field'
```

Nothing is working.

Thanks

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap plugin : 3.17.0
* QGIS Desktop : 3.22.8
* QGIS Server : 3.22.15
* Py-QGIS-Server : 1.8.7
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Chrome

**Comment by Gustry** [comment]
By checking what the JavaScript is doing, it's easy to check what field can be retrieved.

![image](https://github.com/3liz/lizmap-web-client/assets/1609292/24f56624-bd3b-4688-87bc-70bffcb153e3)

So I would say no, it's not possible from the web-browser side, email is not provided in the HTML.
I would do it with a PostgreSQL trigger, only on the server side with the table container all user information.

**Comment by nde34** [comment]
@Gustry 
Yes that's what i did thank you
It could be better if it is possible to retrieve email just like other informations from the web-browser side, so it's not needed to create triggers
