### ISSUE TITLE
[Bug]: treecreated event is fired before layer tree is created

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#3965]
### What is the bug?

Hi,
I noticed that the `treecreated` event fires before the new `lizmap-treeview` web component is added to the DOM, wich happen [after](https://github.com/3liz/lizmap-web-client/blob/e83415b9066e103dc9cfb66afcb30b157fdec360/assets/src/legacy/map.js#L5023) `uicreated` event fires. 

Se image below:
![treeview](https://github.com/3liz/lizmap-web-client/assets/20710470/9343f5b4-31fc-492b-861b-cbf1ae3b3001)
The `treecreated` event appears to be designed to only work with the old Lizmap 3.6 tree view.

Any chances to port this event in LWC >= 3.7 ?

Thanks!

### Steps to reproduce the issue

add this external js to reproduce the issue:

[layertree_event.js.zip](https://github.com/3liz/lizmap-web-client/files/13374340/layertree_event.js.zip)

### Versions

**Versions :**

* Lizmap Web Client : 3.7.0-beta.1
* Lizmap plugin : 3.17.0
* QGIS Desktop : 3.28.7
* QGIS Server : 3.28.5
* Py-QGIS-Server : 
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.7.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian GNU/Linux trixie/sid

### Browsers

Firefox, Chrome

### Browsers version

last

**Comment by cfsgarcia** [comment]
Same problem occurs in LWC 3.7.8. 
`$("lizmap-treeview")` returns nothing after `treecreated` or `uicreated` have been fired.
