### ISSUE TITLE
[Bug]: GetFeatureInfo - Mouse spinner when click on the map 

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#3966]
### What is the bug?

Hi,
in LWC 3.6, when you click on the map to get feature information (`GetFeatureInfo`) a spinner appears next to the mouse pointer to tell the user that Lizmap is working on something.

This feature seems to have disappeared in version 3.7.

In some cases, when several features are involved, the `GetFeatureInfo` request could take some time, and the user could think that system is not responding to his input.

Thanks

### Steps to reproduce the issue

On LWC 3.7, click on the map to see that no spinner appears.

### Versions

Lizmap Web Client : 3.7.0-beta.1
Lizmap plugin : 3.17.0
QGIS Desktop : 3.28.7
QGIS Server : 3.28.5
Py-QGIS-Server :
QGIS Server plugin atlasprint : not found
QGIS Server plugin lizmap_server : 2.8.1
QGIS Server plugin wfsOutputExtension : 1.7.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian

### Browsers

Firefox, Chrome

### Browsers version

last

**Comment by nboisteault** [comment]
@mind84 thanks for this report
