### ISSUE TITLE
[Bug]: "Toggle" setting in Layers tab on Lizmap QGIS plugin not working on groups

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#3968]
### What is the bug?

Hi,
the follow configuration on Lizmap plugin:

![group1](https://github.com/3liz/lizmap-web-client/assets/20710470/1cc13b65-018f-4241-b0df-adbb827febbc)

- group1 -> `Toggle` unchecked
- all children of group1 -> `Toggle` checked

seems not to be interpreted correctly by LWC

![group1_LWC](https://github.com/3liz/lizmap-web-client/assets/20710470/b42f8036-c978-4afc-b1ad-fad4202538d6)

The tree should be initialized like this (?)

![group1_desired](https://github.com/3liz/lizmap-web-client/assets/20710470/af2bc089-e341-4bf2-bf0a-da1d9cd17845)

Thanks

### Steps to reproduce the issue

See attached project to reproduce the issue:

[groups.zip](https://github.com/3liz/lizmap-web-client/files/13378213/groups.zip)

### Versions

**Versions :**

* Lizmap Web Client : 3.7.0-beta.1
* Lizmap plugin : 3.17.0
* QGIS Desktop : 3.28.7
* QGIS Server : 3.28.5
* Py-QGIS-Server : 
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.7.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian

### Browsers

Firefox, Chrome

### Browsers version

last

**Comment by rldhont** [comment]
The toggled option for groups was never taken into account. It was always the layers toggled state that fixed the group toggled state.

**Comment by Gustry** [comment]
I didn't follow the latest status here, but if there is a special behavior to do in the plugin when LWC 3.7 is used (and not previous versions of LWC), this can be added on the plugin side.
