### ISSUE TITLE
Geolocalisation selector don't work

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#397]
Hi! 
When I try to select a city in the select menu, lizmap send me to another location completly different. 
It's clearly not a problème of qgis plugin configuration because the project worked before. 
It's also not a projection's issue because layers are in 3857 (pseudo-mercator wgs 84).
I tried the 3.1 version of lizmap and the problem continues. 
Thanks for your help.

(Lorsque j'essaie de sélectionner une commune dans le menu déroulant, il me positionne dans une zone totalement différente. Ce n'est clairement pas un problème de configuration du plugin qgis car le projet marchait auparavant. Ce n'est également pas un problèeme de projection car les couches sont en epsg: 3857 (pseudo-mercator wgs 84). J'ai essayé la version 3.1 de Lizmap mais le problème persiste.
Merci pour votre aide.)

**Comment by rldhont** [comment]
If you use QGIS 2.16, Lizmap has an issue. Because the GeoJSON is in EPSG:4326 instead of the layer CRS.

**Comment by Maverick83000** [comment]
Thanks for your answer. 
I use the qgis 2.14 and old lizmap's projects, who worked before, don't work now then I don't update them.

**Comment by pieri70** [comment]
Hello
Is there some way to get rid of this problem?
Thanks

Il 18/ott/2016 14:55, "rldhont" <notifications@github.com> ha scritto:

**Comment by rldhont** [comment]
Do you have a link to test the GeoJSON provided by lizmap ?

**Comment by rldhont** [comment]
If you use QGIS *Server* 2.16, the WFS always returns data in EPSG:4326.

This issue is probably, the same as #346.

**Comment by pieri70** [comment]
Yes I use Qgis 2.16 server

Take a look at this
http://lizmap.arpa.fvg.it/
login with lizdevelopers/lizdevelopers

Two projects, left in 3857 right 4326

Both localization/comuni and localization by table set me in a completely wrong position..

So the only way is to downgrade qgis server to 2.14 or wait your fix?
Nothing we can do on qgis desktop side?
Thanks

**Comment by Maverick83000** [comment]
Sorry for my  absence.
I tried the ESPG:4326 and the location worked!
My computer guy told me that he had upgraded the qgis server to 2.16!

Thanks both for your answers

I will open another issue soon :)
