### ISSUE TITLE
Attribute table operations, aspect and behaviour

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#398]
Hello everybody, 
1.  Is  there any way to operate on attribute child tables? I.e.: When Selecting a record in parent table, select all records in child table related to parent's one or automatically highlight a specific record(s) in child table based on parent table selection.
2. If using "loadAttributeLayer.js" script, closing a table, you cannot open it back as shown in picture attached. Basically it doesn't show help interface with "Details" buttons as default, without using script (pics 2 attached)
   ![2](https://cloud.githubusercontent.com/assets/20582012/19524187/2dec692c-961d-11e6-9cdb-f8f3290af583.png)
   ![2 1](https://cloud.githubusercontent.com/assets/20582012/19525156/4f070560-9620-11e6-8317-f8b086dfd315.png)

**Comment by virtusmankind** [comment]
I propose 2 ideas to enhancement attribute tables:
1. Allow to open attribute table directly from Legend (using a small button near Export, Collapse, Expande, Zoom and Change layer style ones) avoiding to click in "Table" icon and then "Detail" in specific layers. In grouped layers it could be possible to select the desired table with a combo box.
2. Open the attribute table in minidock, map or dedicated dock as Popups

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
