### ISSUE TITLE
[Question]: Relations with two referenced and referencing Fields

### ISSUE THREAD

**Issue by d0rbay** [3liz/lizmap-web-client#3986]
### What is the question?

In my QGIS Project i have configured a 1:N relation between two layers using two referenced and referencing Fields.
Opening up the Parent Feature Attributes in QGIS only child features where both referencing Fields match will show up as expected. 

I also configured the relation in Lizmap.
When opening up the parent pop up in Lizmap web client only the first of the two referenced and referencing Fields will be used to establish the 1:N relation between the two layers.

Is it possible to use two referenced and referencing Fields for a relation in Lizmap web client?

### Versions

**Versions :**

* Lizmap Web Client : 3.7.0-rc.1
* Lizmap plugin : 4.0.1
* QGIS Desktop : 3.28.12
* QGIS Server : 3.28.13
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11

### Browsers

Chrome

### Browsers version

Version 109.0.5414.75

**Comment by d0rbay** [comment]
Did I formulate my Question clearly enough?
Is this an behavior that should work in Lizmap or a feature that has not been added yet?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
