### ISSUE TITLE
Removing admin from group admins renders LM unusable

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#399]
Removing the default user admin from group admins removes it immediately, without asking for confirmation, and no admin activity is possible afterwards.
This should be prevented.

**Comment by rldhont** [comment]
The right manager could be more usefull.

**Comment by laurentj** [comment]
I will fix it in the next version. issue jelix/jelix#291

**Comment by laurentj** [comment]
This issue is fixed into Jelix 1.6. I will release soon Jelix 1.6.16 and will update it into Lizmap.

**Comment by pcav** [comment]
Great, thanks.

**Comment by laurentj** [comment]
Jelix 1.6.16 has been landed into master (futur lizmap 3.2) so this issue is fixed in Lizmap 3.2

**Comment by laurentj** [comment]
Jelix have been upgraded to 1.6.16 in 3.0 and 3.1. So this bug is fixed into Lizmap 3.1.6 and lizmap 3.0.18.
