### ISSUE TITLE
adding public baselayers breaks panning

### ISSUE THREAD

**Issue by mbernasocchi** [3liz/lizmap-web-client#400]
in the same project (https://github.com/opengisch/docker-lizmap-postgis/blob/master/demo_data/qgis2015.qgs) with data in 4326, project in 3857, OTF on. 
If I add a public basemap, panning and zooming by rectangle are broken. the zooming works, but the map is always centered on [Null Island](https://en.wikipedia.org/wiki/Null_Island)

**Comment by mbernasocchi** [comment]
maybe related to #397

**Comment by rldhont** [comment]
@mbernasocchi it seems it's a transformation issue.
Does the project have a public URL?

**Comment by mbernasocchi** [comment]
http://phantom.opengis.ch:9998/websig/lizmap/www/index.php/view/map/?repository=demo&project=qgis2015

**Comment by mbernasocchi** [comment]
Soyy I was a bit quick on submitting, I need to go and edit the project so it shows the error

**Comment by mbernasocchi** [comment]
@rldhont now It shows the mistake using this project
[project.zip](https://github.com/3liz/lizmap-web-client/files/578872/project.zip)

**Comment by rldhont** [comment]
@mbernasocchi the problem is simple. The project is in EPSG:3857 but the WMS restricted extent is staied in EPSG:4326.
If you look at the GetCapabilities, the WMS Extent is:
```xml
   <CRS>EPSG:4326</CRS>
   <CRS>EPSG:3857</CRS>
   <EX_GeographicBoundingBox>
    <westBoundLongitude>-0.000329319</westBoundLongitude>
    <eastBoundLongitude>0.000433195</eastBoundLongitude>
    <southBoundLatitude>0.000151116</southBoundLatitude>
    <northBoundLatitude>0.000663276</northBoundLatitude>
   </EX_GeographicBoundingBox>
   <BoundingBox CRS="EPSG:3857" maxx="48.2231" minx="-36.6596" maxy="73.8355" miny="16.8221"/>
   <BoundingBox CRS="EPSG:4326" maxx="0.000663276" minx="0.000151116" maxy="0.000433195" miny="-0.000329319"/>
```
To fix it, you have to update the WMS restricted extent.
