### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#401]
Hi,
Is there a way to extend the session timeout? It is actually too short for me.
Thanks in advance

**Comment by laurentj** [comment]
This is done in the PHP configuration.

http://uk1.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime

**Comment by timbo-barnes** [comment]
> This is done in the PHP configuration.
> 
> http://uk1.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime
Should this be done in the lizmap config php files? or for the webserver?
