### ISSUE TITLE
[Bug]: Can not empty server cache

### ISSUE THREAD

**Issue by bsaglio2001** [3liz/lizmap-web-client#4010]
### What is the bug?

A red cross in my layer panel advise me to reset server cache. 

![image](https://github.com/3liz/lizmap-web-client/assets/47885683/c4629e38-937d-4d9f-8544-f985024b8177)

I see no reason not to do so, so I click onto that red cross, click "ok" in the pop-up window and then "suppress" in the dedicated page.

![image](https://github.com/3liz/lizmap-web-client/assets/47885683/22e761f5-ee02-44a7-86e2-c71d2ffb43cf)
![image](https://github.com/3liz/lizmap-web-client/assets/47885683/ed80d5e6-58f8-48df-995a-fa98b622d9bc)

There seems to be no effect at all. The red cros is still displayed and the global size of data stored is kept untouched.

### Steps to reproduce the issue

1. Open the project in Lizmap Web Client (https://lyonaeroports.lizmap.com/maps_dev/index.php/view/map?repository=projets&project=test_filtre_mv)
2. Open the Layer panel
3. Click on the red cross for the specific layer
4. Click OK in the next pop-up window
5. In the "Map Managing" window (https://lyonaeroports.lizmap.com/maps_dev/admin.php/admin/maps), click "Suppress server cache" for the corresponding directory

### Versions

**Versions :**

* Lizmap Web Client : 3.6.8
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.28.13
* Lizmap.com : Yes
* QGIS Server : 3.28.11
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.18.1
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10 Business

### Browsers

Firefox

### Browsers version

Firefox 120.0.1

### Relevant log output

```shell
No corresponding action in the log file
```

**Comment by Gustry** [comment]
The red cross is always displayed, you have checked the option "Server cache" on your layer configuration.

The button doesn't advise you to reset your cache ... but only "do the reset".

The cache is built from time to time. The button is there to reset the cache, if your underlying data has changed for instance ( to refresh maptiles)

The cache is stored on a Redis server, which is different from the filesystem where you drop your GIS data, and also different than the PostgreSQL server. You won't the see the size in Redis.
