### ISSUE TITLE
[Bug]: tree view map themes are not being respected in LWC

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4013]
### What is the bug?

the map themes created in QGIS desktop do not work well on Lizmap 
switching between themes also doesn't work as expected
lizmap does not respect the checked and non-checked groups, sub-groups and layers in each theme

### Steps to reproduce the issue

try to create themes on qgis desktop and see the behavior on lizmap

### Versions

**Versions :**

* Lizmap Web Client : 3.7.0-rc.2
* Lizmap plugin : 4.0.2
* QGIS Desktop : 3.28.13
* QGIS Server : 3.28.13
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

120

**Comment by Gustry** [comment]
> switching between themes also doesn't work as expected
lizmap does not respect the checked and non-checked groups, sub-groups and layers in each theme

Please provide some details/examples etc about your legend tree. Both cases mentioned here have some "basic" automatic tests about themes.

https://github.com/3liz/lizmap-web-client/blob/master/tests/end2end/playwright/theme.spec.ts#L9
https://github.com/3liz/lizmap-web-client/blob/master/tests/end2end/playwright/theme.spec.ts#L25

**Comment by josemvm** [comment]
...

**Comment by josemvm** [comment]
this is my second theme on qgis desktop:

![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/4016010a-82fd-44e2-92a8-a0fac99dc7ea)

it requires 3 clicks to change theme and all groups appear collapsed, not expanded, on lizmap

**Comment by josemvm** [comment]
please can someone confirm this problem?

**Comment by josemvm** [comment]
@Antoviscomi please are you avaiable to try something like this, with some groups and sub-groups layers?

**Comment by Antoviscomi** [comment]
@josemvm sorry but  I don't use nesting groups generally so I cannot help you in this case

**Comment by josemvm** [comment]
@Antoviscomi thanks

**Comment by josemvm** [comment]
hi lizmap developer team, what do you thing about this?

**Comment by josemvm** [comment]
@nboisteault I think this new feature was developed by you!...

**Comment by josemvm** [comment]
or @Gustry ?...

**Comment by josemvm** [comment]
It is discouraging to migrate to version 3.7 with this unresolved problem, as the expand/collapse group scripts also no longer work

**Comment by Antoviscomi** [comment]
@josemvm I triedon a project contain a group and subgroup layer, for me it works as expected see the screencast below, or tell me more about to reproduce your issue

[Video del 06-02-2024 09:27:59.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/ffb90b63-41c4-481b-89bf-8f9ca871ea6f)

**Comment by josemvm** [comment]
@Antoviscomi thanks
can you expand the "infrastrutture_viarie"?

**Comment by Antoviscomi** [comment]
@josemvm yes of course

**Comment by josemvm** [comment]
auto from theme?

**Comment by Antoviscomi** [comment]
@josemvm from theme as I configured

**Comment by Antoviscomi** [comment]
@josemvm I tried to configure "infrastrutture_viarie" with visible legend, 

![Schermata del 2024-02-06 15-22-43](https://github.com/3liz/lizmap-web-client/assets/12639444/424cbe06-cfae-4a4b-9be7-c210ced0bb2d)

and it works fine as in screencast


[Video del 06-02-2024 15:25:23.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/bc81fef9-7177-47de-82ff-4651ac09972f)

**Comment by josemvm** [comment]
@Antoviscomi can you try with `Activate first theme on startup` option in the plugin and after switch between 2 themes on lizmap?

**Comment by Antoviscomi** [comment]
@josemvm this is the configurations
1.
![Schermata del 2024-02-06 16-40-54](https://github.com/3liz/lizmap-web-client/assets/12639444/57bf41e0-225e-497b-afdd-f8ec76db4d8e)
2.
![Schermata del 2024-02-06 16-40-39](https://github.com/3liz/lizmap-web-client/assets/12639444/d3836cbb-8f00-4960-8fa1-5ef626380f6c)
3.
![Schermata del 2024-02-06 16-37-38](https://github.com/3liz/lizmap-web-client/assets/12639444/b850a8eb-7942-4a18-a6ef-db56f95bfca2)

and this is the behaviour

[Video del 06-02-2024 16:38:07.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/87e66699-0c7f-4493-bced-dd71502b8080)

**Comment by Antoviscomi** [comment]
In effects the switch on child group it carrie the switch on father group (that it seem correct), but on deselection of child the father group should remain checked (in my opinion)

**Comment by josemvm** [comment]
sorry, i think you do not have this otion in layers panel plugin...
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/f50e6cbd-f1f1-4582-8520-5c51c673512e)

please with this otion try to switch many times between themes on LWC

**Comment by Antoviscomi** [comment]
@josemvm whit activate first theme on map the behaviour it's as expected, with the father that remain active on child deselection

[Video del 06-02-2024 17:08:05.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/1a80adca-b623-4d4e-b488-cb92de9f93cd)

**Comment by josemvm** [comment]
according my several tests the lwc works fine for layers, layers group but not for sub-group layers (in this case the lwc doesn´t expand it)

**Comment by Antoviscomi** [comment]
here it expands the subgroup as you can see in screencast

**Comment by josemvm** [comment]
my video: 
![lizmap2](https://github.com/3liz/lizmap-web-client/assets/10053874/dcea5500-03f7-42bd-a9a7-c737a9a8c0fa)

**Comment by Antoviscomi** [comment]
have you select via plugin the secon option for child group sub-group1?
![Schermata del 2024-02-06 17-41-30](https://github.com/3liz/lizmap-web-client/assets/12639444/45dae398-e904-4a70-81fc-e31e2372e6d9)

**Comment by josemvm** [comment]
no...

**Comment by Antoviscomi** [comment]
try to select and reload the page

**Comment by josemvm** [comment]
but i need the "Attiva il primo tema della mappa all'avvio" and it overrides the options...

**Comment by josemvm** [comment]
can you share a similar video where you switch between themes?

**Comment by Antoviscomi** [comment]
> but i need the "Attiva il primo tema della mappa all'avvio" and it overrides the options...

![Schermata del 2024-02-06 18-46-25](https://github.com/3liz/lizmap-web-client/assets/12639444/8142392d-32c9-47d0-a202-f3ebdeead07c)


> can you share a similar video where you switch between themes?

[Video del 06-02-2024 18:49:01.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/2f38497a-9ed9-4f9f-bbde-468b3400967c)

there is the bug your're right, for some reason the `Activate first map theme at startup` was deflagged in my previous test

**Comment by josemvm** [comment]
@Antoviscomi thanks

**Comment by Gustry** [comment]
Did you check that you don't have a permalink in the URL overriding the theme ?

**Comment by Antoviscomi** [comment]
@gustry in my screencasts I refresh by `Ctrl+F5`, it this enough?

**Comment by Gustry** [comment]
> @Gustry in my screencasts I refresh by Ctrl+F5, it this enough?

No, look your URL.

**Comment by Antoviscomi** [comment]
@Gustry Yes, there is a permalink, how to disable it, in order to test it not override?

**Comment by nboisteault** [comment]
@Antoviscomi remove the whole part after the `#` and refresh.

**Comment by Antoviscomi** [comment]
@nboisteault I had do it but on refresh the url become again with permalink in

**Comment by Antoviscomi** [comment]
And the groups and sub-groups in legend still collapsed

**Comment by nboisteault** [comment]
It should work with last Lizmap. Please reopen if it is not the case.
