### ISSUE TITLE
Installing 3.7.0 on 3.6.8  results on error 500  

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#4022]
### What is the bug?

If a special setting is needed please tell us how to

all the repository are down and not recognizable,

when I overwrite the LWC 3.7.0 with 3.6.8 all works as previous

### Steps to reproduce the issue

1. configure or not configure LWC3.7.0 upgrading LWC3.6.8
2. install it
3. try to browse to url for webmaps
 the result is the 500 error

a fresh installation works fine but need to reconfigure all modules and repositories because of, the copy past of repository folders it break the LWC3.7.0

### Versions

**Versions :**

* Lizmap Web Client : 3.6.8
* Lizmap plugin : 4.0.2
* QGIS Desktop : 3.34.1
* QGIS Server : 3.34.1
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 4.1.0
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Chrome 120, Firefox 120

### Relevant log output

```shell
No log because of nothing works for me on LWC 3.7.0
```

**Comment by mdouchin** [comment]
Please tell us more.

Could you please add details

* which kind of installation (docker-based or classic package installation & configuration
* what are the commands you use to "install" or "upgrade" or "configure"
* you must have logs if there is a 500 error. Please look at the file lizmap/var/log/errors.log (or other files in this folder), also see possible errors in nginx (or Apache ?) and in PHP logs)

**Comment by Antoviscomi** [comment]
@mdouchin 
- I used the classic installation and configuration
- I used Install "configure" and non "upgrade"
- nothing in php logs
- I attach apache log

[apache2_error.txt](https://github.com/3liz/lizmap-web-client/files/13671047/apache2_error.txt)

**Comment by Gustry** [comment]
Your logs are from QGIS server.
A 500 error is triggered by a server error, you must find some logs about this error which has been raised.

**Comment by Antoviscomi** [comment]
@Gustry on the same machine a fresh installation, it works fine, just a directory change on server, so I don't know why, who, or where,  on the old folder there are something wrong in configs, modules, or js

**Comment by Antoviscomi** [comment]
I activated the jelix debugger on my 3.6.8 installation and I noticed only the warning messages you can see in screenshot

![Schermata del 2023-12-14 11-17-17](https://github.com/3liz/lizmap-web-client/assets/12639444/e21b63ab-c984-482b-ab20-12a2b0255fbd)

**Comment by Gustry** [comment]
> I activated the jelix debugger on my 3.6.8 installation

The Jelix toolbar is mainly for developers, and displaying some logs which are available on the filesystem.
As said before, you should check logs on 3.7 installation, not 3.6.

**Comment by Antoviscomi** [comment]
> > I activated the jelix debugger on my 3.6.8 installation
> 
> The Jelix toolbar is mainly for developers, and displaying some logs which are available on the filesystem. As said before, you should check logs on 3.7 installation, not 3.6.

And there are no error in 3.7.0 log, so I think it's about a module i.e. wps or Mapbuilder module but I don't know how to log them, because I got no errors in installation (upgrade) on 3.6.8

**Comment by Gustry** [comment]
Please try without module.
The compatibility with Lizmap modules has been fully checked yet.

**Comment by Alain-LG** [comment]
Hello,

I have the same problem. Before asking for an upgrade on my hosting by 3Liz, I would like to test this 3.7 version.

I work on Windows computer and i use the NaturalGIS tutorial to locally install the 3.6 version of lizmap.
Then i follow the lizmap documentation to upgrade from 3.6 to 3.7.

And i have the same error than Antoviscomi but I have found this log in the lizmap/var/log/errors.log file : 

`2024-01-17` 12:48:56	[304]	Dans le tag $gb->params|json_decode:"hash" du template C:\webserver\www\lizmap36\lizmap\modules\view\templates/map_geobookmark.tpl le modificateur json_decode est inconnu	C:\webserver\www\lizmap36\lizmap\vendor\jelix\jelix\lib\jelix\tpl\jTplCompiler.class.php	158`

Do you know how to resolve this message please ?

Thanks a lot for your help

**Comment by Antoviscomi** [comment]
I noticed that upgrade from 3.6.8 to 3.6.9 gone well

**Comment by nworr** [comment]
@Alain-LG , the message seems related to a incomplete upgrade

can you verify the content of `<lizmap_folder>\vendor\jelix\castor\VERSION` (should be "1.1.3")

**Comment by Alain-LG** [comment]
@nworr : You're right. I have the 1.1.1 version of vendor\jelix\castor\VERSION
But i don't know how to upgrade this folder... It was missing when i've installed the LMWC 3.7 so i've copied it from LMWC 3.6..

I have already spent too times on this. I think i will wait for the [NaturalGIS tutorial](https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows.git) because it's a complete package to run under windows ! It's really amazing.

Thank you for your help.

**Comment by Alain-LG** [comment]
> I noticed that upgrade from 3.6.8 to 3.6.9 gone well

Yes, thank tou but i just want to try the last version 3.7 of LMWC

**Comment by Antoviscomi** [comment]
@Alain-LG in order to try 3.7.0 you can simply install it in a clean folder and refer your repositories (that works on 3.6.8) to te new version, It works fine

**Comment by nboisteault** [comment]
@Alain-LG An even easier solution is to use our `docker compose` stack : https://github.com/3liz/lizmap-docker-compose

**Comment by Antoviscomi** [comment]
> @Alain-LG , the message seems related to a incomplete upgrade
> 
> can you verify the content of `<lizmap_folder>\vendor\jelix\castor\VERSION` (should be "1.1.3")

my castor version it's already 1.1.3, but 3.7.0 (and 3.7.1) upgrade, break my 3.6.9 installation

**Comment by nboisteault** [comment]
And also https://gitpod.io/ is excellent to make your first pull requests or just to test Lizmap without installing anything on your computer!

**Comment by nworr** [comment]
@Antoviscomi , do all declared repository have a matching folder on server ?

**Comment by Antoviscomi** [comment]
@nworr yes, they are. I'd just try to upgrade with 3.7.2, 
1. the upgrading it seems to go well
2. when I try to access a map or as admin, the response it's still Error 500  
3. I downgrade to 3.6.9 and all works fine
4.  in fresh istallation of 3.7.x I declare the same repository pointing at the same directory
I don't know what break all in case of upgrading on 3.6.x

**Comment by Gustry** [comment]
Thanks for adding some details.

> when I try to access a map or as admin, the response it's still Error 500

Can you please re-check what is the error 500 ? When clicking from the landing page on a map thumbnail ? Either as anonymous or as an admin you mean ?

**Comment by Antoviscomi** [comment]
@Gustry 
In both cases if I click on the thumbnails as when i try to login
But when I Downgrade the installation to 3.6.9 all works fine

**Comment by Gustry** [comment]
Ok, after you have set your login and password and click "connect" or even before when trying to access the login page ?
Please give us the 500 error linked.

**Comment by Antoviscomi** [comment]
1. the login page opens easily, then I enter the credentials and click on log in, when the 500 error occurs.
2. the initial index page opens, when I click on the thumbnail I get the 500 error.
3. at the moment I have reinstalled 3.6.9 so I have no possibility to reproduce and link the error
