### ISSUE TITLE
LWC 3.7.0: no checkbox in symbology if feature count >= 10

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4026]
### What is the bug?

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/59e9bce4-0f8a-4a6d-b935-583ef9167a75)

VS

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/1fcc824f-eb43-4482-9b4e-505de4e6bbd6)

### Steps to reproduce the issue

Test the attached project.

[dorset.zip](https://github.com/3liz/lizmap-web-client/files/13692549/dorset.zip)

### Versions

LMWC 3.7.0

On Ubuntu 22.04 with QGIS Server 3.28.12, Project saved on QGIS 3.28.12 ans LM plugin 4.1.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by Gustry** [comment]
I have the same issue indeed with the project.

**Comment by josemvm** [comment]
as a workaround you can create a single theme on qgis desktop

**Comment by Antoviscomi** [comment]
@gioman @josemvm @Gustry the original project have the same issue, but, I simply remove/add the layer by QGIS and reclassify it by field as in screenshot1,


![](smb://labpt.local/myshare/Screenshot1.png)


 well, all records became checkable (omitting the count features in legend) the bug occur only if I flag on count features screenshot2


![](smb://labpt.local/myshare/Screenshot2.png)

**Comment by Antoviscomi** [comment]
So I think it is not a real bug, but a behavior due to square brackets in classes names

**Comment by Antoviscomi** [comment]
It should be noted that only the features with double-digit counts present the problem of the absence of the checkbox

**Comment by Antoviscomi** [comment]
If needed the count in legend it might be obtained by classification from QGIS Style with expression 

"LU_DESCRIP"+' '+to_string(count("LU_DESCRIP", group_by:="LU_DESCRIP")

![Schermata del 2024-01-26 09-40-22](https://github.com/3liz/lizmap-web-client/assets/12639444/3756f825-bdbc-4968-8487-5686918ce7bd)

**Comment by josemvm** [comment]
@Antoviscomi please can you share your qgis project with us?
thanks

**Comment by Antoviscomi** [comment]
@josemvm yes, of course, I attach it
[dorset_cadaster.zip](https://github.com/3liz/lizmap-web-client/files/14162425/dorset_cadaster.zip)

**Comment by josemvm** [comment]
@Antoviscomi thanks 
i can confirm the problem:
> only the features with double-digit counts

however  you can write the complete expression and it works as expected
`"LU_DESCRIP"+' [≈'+to_string(count("LU_DESCRIP", group_by:="LU_DESCRIP"))+']'`

Grazing modified pastures [≈11]

**Comment by Antoviscomi** [comment]
@josemvm so it seem isn't due to square brackets

**Comment by josemvm** [comment]
yes... :-)

**Comment by josemvm** [comment]
@Antoviscomi please can you test this issue https://github.com/3liz/lizmap-web-client/issues/4036 and give us feedback

**Comment by gioman** [comment]
Just tried LMWC 3.7.3 on QGIS Server 3.28.15 and problem still there

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/702a5a04-b122-4d66-8a60-ee4e1d65a770)

**Comment by Antoviscomi** [comment]
@gioman all the tests did in the above are in 3.7.3 and I and @josemvm  suggested a workaround

**Comment by gioman** [comment]
> all the tests did in the above are in 3.7.3 and I and @josemvm suggested a workaround

@Antoviscomi workarpunds are nice, but here what I'm trying to point to is that there is something to fix (apparently) in LMWC 3.7.*

**Comment by AdiTane** [comment]
> > all the tests did in the above are in 3.7.3 and I and @josemvm suggested a workaround
> 
> @Antoviscomi workarpunds are nice, but here what I'm trying to point to is that there is something to fix (apparently) in LMWC 3.7.*

The problem is still present in 3.7.5
The workaround isn’t suitable for projects that are updated often because the feature number is not updated automatically (you have to update the symbology style every time you add a new feature)

**Comment by Antoviscomi** [comment]
> The problem is still present in 3.7.5
> The workaround isn’t suitable for projects that are updated often because the feature number is not updated automatically (you have to update the symbology style every time you add a new feature)

Yes of course @AdiTane but at the moment it seems the only way to make LWC able to see the feature counts with double digits.

**Comment by AdiTane** [comment]
> > The problem is still present in 3.7.5
> 
> > The workaround isn’t suitable for projects that are updated often because the feature number is not updated automatically (you have to update the symbology style every time you add a new feature)
> 
> 
> 
> Yes of course @AdiTane but at the moment it seems the only way to make LWC able to see the feature counts with double digits. 

Agree

**Comment by nboisteault** [comment]
Did someone tested with QGIS Desktop/Server 3.34?

**Comment by nboisteault** [comment]
> Did someone tested with QGIS Desktop/Server 3.34?

No need to test. I think the issue is in our server plugin.

**Comment by Antoviscomi** [comment]
I'm sorry @nboisteault I've not the 3.34 version anymore

**Comment by Gustry** [comment]
@Antoviscomi Still using 3.36 ? The issue is there ?

**Comment by Antoviscomi** [comment]
Yes @Gustry

**Comment by nboisteault** [comment]
I just found the bug in our server plugin. I'm making a fix.

**Comment by Gustry** [comment]
New version of the server has been released

`qgis-plugin-manager update` ;-)

**Comment by josemvm** [comment]
@Gustry thanks

but if you have layer with a single symbol (Pontos de Amostragem) the feature count doesn´t appears

![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/b02a0145-3ffc-443a-943b-160af39774d0)

**Comment by Gustry** [comment]
Was it working before ?

**Comment by josemvm** [comment]
no

**Comment by Gustry** [comment]
The fix from @nboisteault above was single character in a regexp, so I couldn't see how it bring this regression.
Can you make a new ticket, thanks.

**Comment by josemvm** [comment]
it works on lwc 3.6, because it uses a different way to show the layers with a single symbol

![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/998b3007-6455-4eaa-895b-6b882eeec21d)

**Comment by Gustry** [comment]
Yes, technically, it's very different between 3.6 and 3.7 ;-)

CF https://github.com/3liz/lizmap-web-client/issues/4036#issuecomment-1927391719

**Comment by josemvm** [comment]
this problem is related to the old case where QGIS Desktop shows the feature coun for all features of the layer and LWC doesn´t
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/a7a7cc8a-b9da-4946-90e1-5d37ab77afa2)

**Comment by nboisteault** [comment]
@josemvm another bug = another issue to open. Thanks.
