### ISSUE TITLE
LMWC 3.7.0: raster is rendered below baselayers

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4027]
### What is the bug?

In the attached test project the raster layer (topographic_map) is rendered below the baselayers (there is no custom layer ordering enabled).

This happens even after removing the legacy baselayers and adding the new baselayers group.

### Steps to reproduce the issue

Test project: 

[dorset.zip](https://github.com/3liz/lizmap-web-client/files/13692603/dorset.zip)

### Versions

LMWC 3.7.0

On Ubuntu 22.04 with QGIS Server 3.28.12, Project saved on QGIS 3.28.12 ans LM plugin 4.1.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by Gustry** [comment]
Can you share some screenshots ? (legend in QGIS) and in LWC if necessary ?

**Comment by gioman** [comment]
![image](https://github.com/3liz/lizmap-web-client/assets/1951107/833744aa-024a-4efb-b406-d696f6c17194)

VS

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/0b52bfd4-7b5a-4ad5-9989-a1b099b3ae76)

VS

Print layout in KMWC

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/fb978c59-8f02-4d54-9e5e-8c446b4cb6a1)


The description also contains the whole project.

**Comment by gioman** [comment]
After removing/re-adding/removing/re-adding a few times the baselayers group and its content, the raster now renders where expected.

**Comment by nicogodet** [comment]
I encountered this bug today (see linked issue).

I believe there is something to fix to avoid removing/re-adding/removing/re-adding a few times the baselayers group and its content to display raster on top of baselayers :)

**Comment by gioman** [comment]
> I believe there is something to fix to avoid removing/re-adding/removing/re-adding a few times the baselayers group and its content to display raster on top of baselayers :)

agree.

**Comment by nboisteault** [comment]
https://github.com/3liz/lizmap-web-client/issues/4065#issuecomment-1898124681

**Comment by nicogodet** [comment]
@nboisteault seems solved in 3.7.2
