### ISSUE TITLE
LMWC 3.7.0: layout with atlas do now show in the printing dialog

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4028]
### What is the bug?

LM plugin shows that one of the layout has an atlas

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/640a12d5-0634-41b4-9efa-2228df77b056)

but this layout does not show in the printing dialog, is this expected?

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/051f689a-2299-4660-97da-8265d1abbeb2)

### Steps to reproduce the issue

Test project:

[dorset.zip](https://github.com/3liz/lizmap-web-client/files/13692612/dorset.zip)

### Versions

LMWC 3.7.0

On Ubuntu 22.04 with QGIS Server 3.28.12, Project saved on QGIS 3.28.12 ans LM plugin 3.18.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by Gustry** [comment]
Yes, it's expected...
It's like this since 2019, layout atlas are not shown in this dialog !

Documentation from LWC 3.6 (still the `current` one in the URL)
https://docs.lizmap.com/current/en/publish/configuration/print.html#layout-with-an-atlas-when-using-a-popup
(link is at the top now)

**Comment by gioman** [comment]
> It's like this since 2019, layout atlas are not shown in this dialog !

@Gustry there is no need to shout. Just doing some testing on 3.7 and I cannot always remember any detail (also because I never used atlas layouts in LM and I was using a project created by others).
