### ISSUE TITLE
LMWC 3.7.0: adding the project-background-color group with the proper button in LM plugin and leaving it empty, causes the project to stop to load

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4029]
### What is the bug?

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/5cbc0f75-5a54-4058-8e58-47c38eb5e57e)

### Steps to reproduce the issue

See title. Test project here: 

[dorset.zip](https://github.com/3liz/lizmap-web-client/files/13692628/dorset.zip)

### Versions

LMWC 3.7.0

On Ubuntu 22.04 with QGIS Server 3.28.12, Project saved on QGIS 3.28.12 ans LM plugin 4.1.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by Gustry** [comment]
I think it's linked due to old version of the plugin.
You have a difference of layer count between your QGS file and CFG file.

**Comment by gioman** [comment]
> I think it's linked due to old version of the plugin.
> You have a difference of layer count between your QGS file and CFG file.

I referred the wrong plugin version in the description (now changed) and for good measure I tried again now (with LM plugin 4.1.1), same result.

**Comment by Gustry** [comment]
I didn't replicate this issue exactly.
The `project-background-color` is missing from your test project. I have added it, it's working as expected about this. (I met another error, not linked to this)

Are you using a some legacy checkbox about base layers AND the new `baselayers` group ?
So you were mixing both configurations ?
Was your CFG file updated ? (as always in LWC, the CFG file must have the same layer tree as in QGIS) No warning when saving about a different count of layers ?

**Comment by Gustry** [comment]
> leaving it empty

Well, it must stay empty anyway, as it's just to add the "default background color" only

**Comment by Gustry** [comment]
Please make "F12" and check the console, there might be a clue about the error it self. ("console" or "request" tab).

**Comment by gioman** [comment]
It happens even having just the "baselayers" group empty.

**Comment by Gustry** [comment]
If "baselayers" is empty, there isn't any need for the group. I guess it must have at least one item in it.

I will make a patch in the plugin to block saving if "baselayers" is empty : https://github.com/3liz/lizmap-plugin/issues/540

Can we close here ?

**Comment by gioman** [comment]
> Can we close here ?

@Gustry sure!
