### ISSUE TITLE
editing tool

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#403]
the editing tool doesn't work at this time

**Comment by rldhont** [comment]
Hi @josemvm, thanks for testing the master which is not a stable version.

I'm actually working on the editing tool to enhance it. So to help me can you be more precise on the issue:
* which commit break the editing tool ?
* which part of the editing tool is broken ? (create, update, delete, geometry, form, etc)

**Comment by josemvm** [comment]
hi @rldhont,

the editing tool doesn't work at all.

- the browsers show this message after the second click to try to edit in any editing situation:
"Are you sure you want to stop editing? In this way all changes will be lost."

-  i got back to the version 3.0.3 - bugfix release and i suppose that the problem existed on that date or even before...

**Comment by rldhont** [comment]
hi @josemvm, it's normal way editing tool works.

If you have this message: "Are you sure you want to stop editing? In this way all changes will be lost."
It means that an edition is underway (a form is displayed in the edition dock, edition controls are activated). The edition has been finished:
* the user does not finish the edition by clicking on cancel button
* an error occurred during the save.

Sorry but it's not an issue, but you can made a proposition to prevent to create a new edition without lose the current one.

**Comment by josemvm** [comment]
hi @rldhont, i'm sorry for the noise... now, everything's ok.

thank you very much and keep up the good work!
