### ISSUE TITLE
NGINX intallation RAW

### ISSUE THREAD

**Issue by sag1687** [3liz/lizmap-web-client#4031]
### What is the question?

I'm having significant difficulties installing Nginx for Lizmap. I complete the installation, but then when I click on the Lizmap login, the page doesn't proceed, and I can't understand why. Has anyone done the installation with Nginx instead of Apache2? If so, how? Can you provide me with instructions? I'm looking for a raw installation, not Docker

### Versions

3.6.4

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu server

### Browsers

Firefox

### Browsers version

x

**Comment by Gustry** [comment]
Version 3.6.4 is already old in case of a fresh installation. Better to install the latest instead.

>  but then when I click on the Lizmap login, the page doesn't proceed

You must check our server logs. Seeing incoming HTTP requests, and some error if one is failing. Maybe increase debug level on your server if necessary.

> Has anyone done the installation with Nginx instead of Apache2?

Yes, we do with Nginx on our side.

* https://docs.lizmap.com/current/fr/install/pre_requirements.html#server-administration-knowledge
