### ISSUE TITLE
[Question]: Changes in zoom in/out behavior with LWC 3.7.0

### ISSUE THREAD

**Issue by nicogodet** [3liz/lizmap-web-client#4037]
### What is the question?

As asked on IRC, I feel a change (a bad one) in zoom in/out behavior with LWC 3.7.0

Demo is better than long explanation
Old behavior : https://ccivar.lizmap.com/carto/index.php/view/map/?repository=demo&project=Inondations_toulouse
feels smoooootthhhhhh

New behavior : https://map.isl.fr/index.php/view/map?repository=aussonnelle&project=Bases_enjeux2
not so smooth

### Versions

LWC 3.7.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10

### Browsers

Chrome

### Browsers version

120

**Comment by Gustry** [comment]
The behavior has changed in LWC 3.8 if I'm not wrong about this.

**Comment by nicogodet** [comment]
I will check once 3.8 is released

**Comment by Gustry** [comment]
@nicogodet Can you check https://demo.lizmap.com/lizmap_3_8/index.php/view/map?repository=features&project=land_use

The RC 1 has been released and the final will be this month.

**Comment by nicogodet** [comment]
Ooohhh feels nice and smooth like before 3.7 !

**Comment by Gustry** [comment]
Cool thanks :)
