### ISSUE TITLE
[Question]: LWC 3.7.0 Actions

### ISSUE THREAD

**Issue by ocelot73** [3liz/lizmap-web-client#4051]
### What is the question?

I followed the instructions here:
https://docs.lizmap.com/3.7/en/publish/configuration/actions.html
to write the *.action file and to insert the PostgreSQL function.

The action works well but when I login as administrator, at startup I get the following warning when map finished loading:

`Dear administrator, the JSON configuration file for the action module is written in the old format. Please read the documentation and convert it to the new format. The old format will not work in future versions.`

So even the example in the 3.7 section of Lizmap documentation is in "old" format?
how can I understand how to write in the "new" format ?
Is there any way to print the buffer generated by lizmap action and the map underneath to a print layout ?
Now, it seems not, if I set a print layout and try to print the map with the buffer on screen, it's printed everything but the buffer.
Thanks in advance

### Versions

**Versions :**

* Lizmap Web Client : 3.7.0
* Lizmap plugin : 4.1.2
* QGIS Desktop : 3.28.14
* QGIS Server : 3.28.14
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin cadastre : 1.19.0
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04.3 LTS

### Browsers

Firefox

### Browsers version

Firefox 121.0 (64bit)

**Comment by mdouchin** [comment]
Indeed, very sorry for this, the documentation for 3.7 must be updated.
See https://github.com/3liz/lizmap-web-client/pull/3339 for an insight

Writing the new doc is on my todo list

**Comment by Gustry** [comment]
There is already https://github.com/3liz/lizmap-documentation/issues/227

Note, I have edited the documentation with a temporary warning redirecting to the PR : https://github.com/3liz/lizmap-documentation/commit/446db57c8daf299a95d449ddff893ec25045cdef

**Comment by Gustry** [comment]
PR merged https://github.com/3liz/lizmap-documentation/pull/249
