### ISSUE TITLE
[Question]: Qgis server trouble

### ISSUE THREAD

**Issue by sgalvi** [3liz/lizmap-web-client#4056]
### What is the question?

Hi,
I have a configuration problem between qgis server and lizmap.
When I authenticate in LizMap the error message is as follows
![Screenshot from 2024-01-08 11-13-45](https://github.com/3liz/lizmap-web-client/assets/153731136/303dc91c-df4f-46a8-93c2-937c6f4ce823)
If I click in server information the results is the following
![Screenshot from 2024-01-08 11-14-58](https://github.com/3liz/lizmap-web-client/assets/153731136/f5f81104-2a43-40fe-9bfe-1b434deee01c)
if I then i click to see the lizmap logs the result is the following
![Screenshot from 2024-01-08 11-14-37](https://github.com/3liz/lizmap-web-client/assets/153731136/7fafc66b-1bef-4810-b195-d8fc7c011cd1)
How do you advise me to proceed?

for the installation of qgis server I followed the official guide: :
https://docs.qgis.org/3.28/en/docs/server_manual/getting_started.html#installation-on-debian-based-systems
debian based system and apache as http server

### Versions

Lizmap 3.6.5
Qgis server 3.28.11

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

firefox 121

**Comment by Gustry** [comment]
> Lizmap 3.6.5

This version is too old. This 500 error has been fixed already. Please upgrade.
