### ISSUE TITLE
[Question]: lizmap plugin upload didn't work

### ISSUE THREAD

**Issue by sgalvi** [3liz/lizmap-web-client#4061]
### What is the question?

Hi, here is my problem
When I try to upload from QGIS Client to Lizmap via the plugin, the following happens: I get a trust project error which I then resolve with autofix.
![Screenshot from 2024-01-09 15-57-42](https://github.com/3liz/lizmap-web-client/assets/153731136/8f05853a-0639-4e39-be38-9d902d975e68)
![Screenshot from 2024-01-09 15-57-52](https://github.com/3liz/lizmap-web-client/assets/153731136/f7dc9c8e-0916-4f19-978d-f527c98389da)

At that point, I am told that everything is fine.
![Screenshot from 2024-01-09 15-59-37](https://github.com/3liz/lizmap-web-client/assets/153731136/43f21c38-5d30-47d3-a33a-3149173f16a8)

However, when I go to my Lizmap server, I can’t find anything uploaded and I don’t find any errors in the log section.

### Versions

Web Client Lizmap
Version	3.7.0

QGIS Server
Version .28.11

Py-QGIS-Server 	not used

Plugin versions
Lizmap server 	[2.8.1]
wfsOutputExtension 	[1.8.0]

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

firefox 121

**Comment by Gustry** [comment]
The plugin doesn't manage the upload of files. Only updating your local configuration file.
It's up to the system administrator to provide a way to upload files on a server : webdav, rsync, network drive etc

* https://docs.lizmap.com/current/en/publish/quick_start/index.html#upload-your-files-to-your-lizmap-server
* https://docs.lizmap.com/current/en/install/project_repository.html
