### ISSUE TITLE
PostgreSQL database for Lizmap

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4067]
### What is the question?

Does the database for Lizmap need to have the « PostGIS » extension? It is unclear (for me at least 😉)…

### Versions

Lizmap 3.7

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

89

**Comment by gioman** [comment]
> Does the database for Lizmap need to have the « PostGIS » extension? It is unclear (for me at least 😉)…

do you mean the php-pgsql one?

**Comment by Gustry** [comment]
PostgreSQL can be used for different purpose. Which [use case](https://docs.lizmap.com/current/en/install/pre_requirements.html#postgresql) do you mean ?
You don't want to install it ? Maybe it works without, but this has not been tested.

**Comment by katagen** [comment]
I have postgreSQL, but I want to know at the step "To store Lizmap Web Client users and user actions. Lizmap uses tables. This setting must be done when installing Lizmap", if this database needs the extension PostGIS?

**Comment by nworr** [comment]
A "simple" postgresql database is Ok, postgis is unrequired
