### ISSUE TITLE
selection tool: add option to add, substract or new selection

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#408]
hi @rldhont,

thanks a lot for this new and relevant feature!

is it possible to add or subtract features from a layer using this graphical data selection tool?

thanks again

**Comment by rldhont** [comment]
No it's a feature exactly like the graphical selection tool in QGIS:
* Box
* Circle
* Polygon
* Free hand

**Comment by rldhont** [comment]
Can you update the title of the issue and be more precise in the description of the feature ?

**Comment by josemvm** [comment]
i'm talking about the graphical selection tool and i'm talking about the possibility of adding or subtracting selections from an initial selection or set of features.

as if there were more 2 buttons one to add (+) and another to subtract (-) to do that, like you can use the CTL key in QGIS for to add or sub features.

if anyway it is not on your plans please close this issue.

thank you for your great work

**Comment by rldhont** [comment]
Done in 19560d4d7e1f1c00bd3ae0ec2032a586d6efea95
