### ISSUE TITLE
Do not show locate by layer drop down list after loading map

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#4081]
### What is the question?

I want to stop the locate drop down list after loading map. Only when I toggle it in the site menu on or off. Now it opens after loading my map. How can I stop it?

### Versions

latest version off all aplications

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

windows 11

### Browsers

Chrome

### Browsers version

latest

**Comment by gioman** [comment]
> I want to stop the locate drop down list after loading map. Only when I toggle it in the site menu on or off. Now it opens after loading my map. How can I stop it?

agree, is not consistent with the rest of tools available/enabled.

**Comment by NvBgm** [comment]
Solution.. I solved it with a piece of js script.

lizMap.events.on({
uicreated:function(e) {
$('#button-locate').click();
}
});
