### ISSUE TITLE
[Question]: Unable to create a table of points in QGIS after connecting to PostgreSQL and PostGIS

### ISSUE THREAD

**Issue by sgalvi** [3liz/lizmap-web-client#4086]
### What is the question?

Description: I am trying to add points to a map and modify them from Lizmap web. I have installed PostgreSQL and PostGIS on my server and connected to my PostgreSQL database from QGIS. However, when I try to create a table of points, I get the following error message: “Error creating table: no schema has been selected to create in.” Can someone please help me resolve this issue?

I hope this helps. Let me know if you have any other questions.

![Screenshot from 2024-01-22 12-28-55](https://github.com/3liz/lizmap-web-client/assets/153731136/a95c5165-4444-48f6-8185-b33ab5f344ae)

![Screenshot from 2024-01-22 12-35-41](https://github.com/3liz/lizmap-web-client/assets/153731136/db77ce23-0808-4c24-bf3e-523aa6d605b0)

New Table Creation Error: Error creating new table 'new_table_name': An error occurred while creating the vector layer: Creation of data source "public"."new_table_name" failed: ERREUR: la fonction addgeometrycolumn(unknown, unknown, unknown, integer, unknown, integer) n'existe pas LINE 1: SELECT AddGeometryColumn('public','new_table_name','geom',43... ^ HINT: Aucune fonction ne correspond au nom donné et aux types d'arguments. Vous devez ajouter des conversions explicites de type. 

### Versions

Lizmap 3.7

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu 20.04

### Browsers

Firefox

### Browsers version

firefox 121

### Relevant log output

```shell
New Table Creation Error: Error creating new table 'new_table_name': An error occurred while creating the vector layer: Creation of data source "public"."new_table_name" failed: ERREUR: la fonction addgeometrycolumn(unknown, unknown, unknown, integer, unknown, integer) n'existe pas LINE 1: SELECT AddGeometryColumn('public','new_table_name','geom',43... ^ HINT: Aucune fonction ne correspond au nom donné et aux types d'arguments. Vous devez ajouter des conversions explicites de type.
```

**Comment by Gustry** [comment]
Did you add PostGIS on your database ? https://stackoverflow.com/questions/44618374/error-function-addgeometrycolumn-does-not-exist-when-trying-to-import-file-int

**Comment by sgalvi** [comment]
MY BAD, SORRY. I didn't have postgis installed on the table. yet I was convinced that I had checked well.
But now it shows this.
![Screenshot from 2024-01-22 13-06-40](https://github.com/3liz/lizmap-web-client/assets/153731136/838871d4-68ea-47e2-8fd9-4fd92bc79942)
if I then try to open the project in lizmap:
An error occurred while loading the map. Some resources may be temporarily unavailable. Try later.
Return to the home page.

**Comment by Gustry** [comment]
>  But now it shows this.

Did you read the message at the top at the table ?

**Comment by sgalvi** [comment]
Sorry, I was too hasty in replying. I had to enable the SSL connection
