### ISSUE TITLE
Data table not shown in legend and attribute table

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#409]
Hello everyone. 
I've tried to add a simple **data table** (without geometry - just data like "Energy consumption" for street lighting) in my lizmap project, both in .dbf (not editable in lizmap) and postgis db (for editing data).

I create relations using a common field between data table and a postgis geographic features (streetlights). 

- I  **cannot see** data table neither in legend (both in .dbf and postgis) and as child table when selecting a streetlight on the map 
- I **can edit** the postgis data table, adding new items.

I'm on Lizmap 3.0.2 with Debian server and QGis Server 2.14
What's wrong?

**Comment by virtusmankind** [comment]
Merge with [https://github.com/3liz/lizmap-web-client/issues/225]

**Comment by virtusmankind** [comment]
Merge with [https://github.com/3liz/lizmap-web-client/issues/225](https://github.com/3liz/lizmap-web-client/issues/225)

**Comment by rldhont** [comment]
@virtusmankind you need to activate the option to see children in popup. The function is linked to the plugin.

**Comment by virtusmankind** [comment]
What about show data table in legend or in attribute table to read its content (and export it) ?

**Comment by rldhont** [comment]
Hi @virtusmankind,

About Attribute table, http://docs.3liz.com/en/publish/advanced_lizmap_config.html#activate-the-attribute-table-tool-for-a-vector-layer, you have to publish the layer to WFS and to add the layer in the Layer Attribute tool in the plugin.

If the layer has relation defined in QGIS, Lizmap reuse it to display children.

About children in the popup, this option is available only with the master version of the plugin and the web client.

**Comment by virtusmankind** [comment]
Thanks. I can see table in Attribute tool both as a table and as a children table (in relations). I will wait for upcoming feature to show children in popup.
