### ISSUE TITLE
Two questions...

### ISSUE THREAD

**Issue by Geographic** [3liz/lizmap-web-client#410]
First is about the maximum zoom level of the ''standard' Open Street Map. I can zoom in max at 1 : 2.257. I would like to get a bit deeper zoom level but I'm afraid this is an issue of the OSM wms-provider and has nothing to do with lizmap. I'm I right? If so, is there some way to bypass this?

Second, from the manual, there is a possibility to use a custom theme for the map client. But, in the manual there is not much more explained then a tree view:

-- media
  |-- themes
    |-- default
    |-- map_project_file_name1
    |-- map_project_file_name2
    |-- etc

So far so clear, but I suspect the theme that wil be chosen for the specific map has something to do with the name given to the folder. Only I can't figure out what name exactly to choose. Tried some things but the client always chooses the default theme. Can someone please explain how this works? THX!

**Comment by virtusmankind** [comment]
About your second question,  you should name the folder into /media/themes exactly like the name of the project, without extension  (i.e.
QGis project name: montpellier.qgs 
Theme folder name: montpellier)

**Comment by rldhont** [comment]
For the second question:
`map_project_file_name1` and `map_project_file_name2` are folder names to apply specific theme to `map_project_file_name1.qgs` and `map_project_file_name2.qgs` project.

If you think the documentation is not clear enough, you can update it https://github.com/3liz/lizmap-documentation

**Comment by nboisteault** [comment]
@Geographic Reopen with separate questions if needed.
