### ISSUE TITLE
Customize group editing rights

### ISSUE THREAD

**Issue by matteob85** [3liz/lizmap-web-client#411]
Hello. I'd like to customize the rights of editing data for each group in lizmap. for example user group can add, modify but not delete and admin group can add, modify and delete a layer. in lizmap administration i can only set in lizmap client management - use edition tool "yes" or "no" or "-".  in lizmap plugin i just can decide what layer can be editable.
thank you

**Comment by rldhont** [comment]
Hi @matteob85, this is not yet possible.
It's an enhancement to code for a futur version.
Thanks

**Comment by laurentj** [comment]
duplicate #1112
