### ISSUE TITLE
Media path in editing tool

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#412]
Hello. 
When adding a media (e.g a photo) in editing dataset, I can choose a local path to upload a media. In popup informations, I'm not able to see uploaded photo giving this message: 
No media file in the specified path: media/upload/Illuminazione_Pubblica/segnalazioni/foto/Lampione.jpg

I created a folder with this structure: 
media
-upload
--project name
---layer name
----field name

It automatically put the uploaded file in this folder but in server I cannot localize where Lizmap upload the file.

**Comment by virtusmankind** [comment]
**Solved**, helped by #175 

I had to:
_Give Apache user (usually www-data ) write permission on the upload folder, so that it can create files and folders in media/upload :
chmod 775 -R media/upload && chown :www-data -R media/upload_

Where "php.ini" file is locate? when you say:

> Check  you **php.ini** to see if the variables post_max_size and max_upload_size are correctly set (by default, php only allows uploading files up to 2 Mo )

**Comment by rldhont** [comment]
the php.ini path depends on:
* the operating system
* the php version
* the way php is used (fpm, fcgi, etc)
