### ISSUE TITLE
setting layer shortname results in grayed out layer

### ISSUE THREAD

**Issue by mbernasocchi** [3liz/lizmap-web-client#415]
I'v a project with layer names in German thus using öäü etc. The OWS server test configuration panel suggest me to assign shortnames to the layers that include a space or a öäü. If I do this the layer is not rendered in 3.1pre.0001 and the layer name in the legend is grayed out.

ex layer Bahnhöfe -> shortname bahnoefe will break lizmap.

according to https://github.com/3liz/lizmap-web-client/issues/274#issuecomment-204004552 in #274 it should be fixed

**Comment by mbernasocchi** [comment]
The project is generated in QGIS 2.18

**Comment by mbernasocchi** [comment]
setting a shortname to a layer that has no öäü... does _not_ trigger the same behavior

**Comment by rldhont** [comment]
Fixed f7fbf61ce98c96f39e47f3550310d5398a6c7a12
