### ISSUE TITLE
Atlas print does not render layers when defined as a theme

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#4164]
### What is the bug?

With lizmap 3.6 version I was able to define a theme for a map in my atlas layout and then Lizmap was following this theme to render the final map. Using the 3.7.2 version configuring layers for a map using a theme does not work anymore. If I specify a theme, some layers are printed and others not (base layers are not printed). 

Surprisingly, if I don't use a theme but if I lock the layers for a map, then all layers are well printed.

Is there something am I missing ?

### Steps to reproduce the issue

1- Create an atlas layout
2- Specify that the map is using a theme
3- Click on a feature and click on the print icon
4- the pdf is generated but without the layers

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.4
* Lizmap plugin : 4.1.8
* QGIS Desktop : 3.28.11
* QGIS Server : 3.28.11
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.17.3
* QGIS Server plugin lizmap_server : 2.8.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu

### Browsers

Firefox

### Browsers version

Firefox 122.0

**Comment by Gustry** [comment]
Hi,

Do you have a 3.7.3 pre version on our hosting infrastructure to try again ?
The bugfix release has not been officially released, but a few fixes about atlas print layouts has been deployed on lizmap.com

See changelog for next release https://github.com/3liz/lizmap-web-client/blob/master/CHANGELOG-3.7.md

Or intermediate package : https://packages.3liz.org/pub/lizmap/unstable/3.7/

**Comment by arno974** [comment]
The lizmap is not on your infrastructure. I was able to deploy the 3.7.3-pre.7174 and I can confirm that it is working now ! Just have to wait for the official release now !
