### ISSUE TITLE
COG Raster as Embed layers are not displayed

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#4169]
### What is the bug?

COG raster layer from a parent QGIS project in a children QGIS  are correctly displayed in QGIS but not ni Lizmap. 

For example my "parent" QGIS project contains 3 raster layers. 2 are cog raster and one is a gpkg raster.

![image](https://github.com/user-attachments/assets/0de297f3-59d1-444d-a3df-7eb8a75c6982)

My "children" QGIS project contains all the embed layers from the "parent" project and one raster layer added as a "normal" raster layer :

![image](https://github.com/user-attachments/assets/756ec797-16f3-43f5-962f-67d1d0501dc1)

In Lizmap, the layers from the "parent" project display perfectly. However, in the child project, only the GPKG embed layers and the raster layer directly integrated are displayed.

![image](https://github.com/user-attachments/assets/3d2bd5d6-aede-481f-a208-b296049d8235)

This used to work in previous 3.6 version. It was very useful as it was possible to centralize the tiles cache as they were generated for the "master" basemap project.

### Steps to reproduce the issue

1. Add an embed layer (or a group of layers) as basemap
2. Layers are correctly displayed in QGIS
3. Check in Lizmap, layers are not available

**Versions :**

* Lizmap Web Client : 3.7.11
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.28.11
* Lizmap.com : Yes
* QGIS Server : 3.34.11
* Py-QGIS-Server : 1.9.1
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.11.0
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu

### Browsers

Firefox

### Browsers version

122.0

**Comment by Gustry** [comment]
> QGIS Desktop : 3.28.11
QGIS Server : 3.22.7

This is a problem, using QGIS Desktop with a higher version than the server. The XML written in the "future" might not be read well by an old version of the server. There are a few warnings in plugins with this configuration.

FYI , there are a few bugfix about embed layers https://github.com/3liz/lizmap-web-client/pulls?q=is%3Apr+embed+

**Comment by Gustry** [comment]
> When adding an embed layer (layer from another project) in the baselayers group (or adding the whole baselayers group from another project) the layer or all the layers (if the whole group is added) are not displayed.

I'm clearly not sure about "adding the whole baselayers group from another project".

But adding individual layers in the `baselayers` group should work, see the ticket on plugin side to allow it : https://github.com/3liz/lizmap-plugin/issues/601 Did you upgrade your Lizmap plugin ? Can you try on latest 3.8 version ?

**Comment by Gustry** [comment]
In PR #4846 #4848 and #4850, I have added an embedded layer in the `baselayers` group for testing. It's vector layer for now.
