### ISSUE TITLE
Wrong default value inserted with character varying

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#417]
QGIS Server 2.14.8
LWC 3.0.4

Hi,

On a layer I have an attribute which have 'gerepi_grp' as default value defined in postgreSQL.
QGIS correctly set the default value but with the same project in LWC I have 'gerepi_grp'::character varying set in the field.
I had the same behaviour in QGIS when I first added the attribute in postgreSQL whitout reloading QGIS. Maybe QGIS Server keep an old default value for the attribute.

Here is a mix of correct/incorrect default value inserted : 
![image](https://cloud.githubusercontent.com/assets/2145040/20427997/0dc4537c-ad87-11e6-87bf-d05d86d20610.png)

**Comment by josemvm** [comment]
hi @nboisteault,

i can confirm it!

**Comment by mdouchin** [comment]
This is a recent behaviour, since a989e87b309ab9091be79d4d04c820f5e59b6fbc

**Comment by mdouchin** [comment]
This piece of code was added to handle views with default values. Basically it has been made with integer fields and not text fields in mind.

Should we avoid to add it in Lizmap form but only set the value if no value has been sent by the web form ? @jancelin via #75 was the issue reporter

We should also check the data type and avoid quoting default value.

I am working on this

**Comment by rldhont** [comment]
Fixed a9cd647bcc33583fd9b0afc86ed2d9b86e9f7367
