### ISSUE TITLE
[Bug]: tree view map themes - doesn't expand sub-groups (nor sub-sub-groups)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4173]
### What is the bug?

in case you have themes, the LWC doesn't expand groups nor sub-sub-groups belonging to the theme

![lizmap2](https://github.com/3liz/lizmap-web-client/assets/10053874/dcea5500-03f7-42bd-a9a7-c737a9a8c0fa)

### Steps to reproduce the issue

create themes on qgis desktop with groups and sub-groups and see the behavior on lizmap

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.2
* Lizmap plugin : 4.2.0
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

121.0.1

**Comment by josemvm** [comment]
hi @rldhont what do you think about it?
thanks in advance

**Comment by guenterw** [comment]
I would also find that very useful.
Using the QGIS themes in Lizmap is very(!) helpful for the user and a very nice solution. 
Provided it also works with the detailed legend, which I assume it will.
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/b2c10607-5b5d-40ea-ad66-de7184340ebb)


Within the scope of my possibilities (small 1-man office) I would also support it financially. I can also ask my customers if they can imagine a financial contribution.
And I can promote it at this year's German FOSSGIS conference in Hamburg and look for supporters. I have a demo session and a user meeting for Lizmap there.

**Comment by Gustry** [comment]
Thanks @guenterw !
