### ISSUE TITLE
[Bug]: MacOS : Vector layers are not shown in Firefox nor Safari

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#4177]
### What is the bug?

We share a map and a user using a Mac OS face a bug in both Safari and Firefox.
The vector layers are not visible.
The search tool works fine and show in yellow the searched object but nothing appears in the layers.

### Steps to reproduce the issue

Open this map with a Mac Book : 
https://cenoccitanie.lizmap.com/carto/index.php/view/map/?repository=znieff&project=znieff_prospect

here is what you will see : 
![Capture d’écran 2024-02-07 à 14 41 54](https://github.com/3liz/lizmap-web-client/assets/1642645/f93cb4e2-69a2-465a-be09-7549a2503064)

and here  the same map with Firefox on Linux or Windows : 
![Capture d’écran du 2024-02-07 14-48-04](https://github.com/3liz/lizmap-web-client/assets/1642645/2503c19d-f7be-421b-851a-cb872ef16eb5)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.3-pre.7098
* Lizmap plugin : 4.1.8
* QGIS Desktop : 3.28.15
* Lizmap.com : Yes
* QGIS Server : 3.28.14
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.0
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Mac OS SONOMA 14

### Browsers

Firefox, Safari

### Browsers version

unchecked

**Comment by Gustry** [comment]
Hi @mathieubossaert 

Can you try again ? I just upgraded your instance, it should be fixed.

**Comment by mathieubossaert** [comment]
I can confirm it is fixed ! Thanks a lot for such a quick fix !
