### ISSUE TITLE
[question] What is the cause of duplicate legend in a layer

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#418]
Hi,
i have in a QGIS project a wms QGIS Server connection. When i do the option in lizmap plugin get wms layers for third parts i have a duplicate legend in the lizmap webclient. If i turn off this option legend don't load.

What could be the problem?

Regards
João

**Comment by rldhont** [comment]
Fixed in 4ccccf03f9bb3c33cd77e035c1c2a2d1f4b054bd for direct wms layer.

QGIS Server is not able to retrieve WMS legend.
