### ISSUE TITLE
Add background on overview

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4188]
### What is the bug?

On Lizmap-web-client, the overview doesn’t have any background with some transparency! And I can’t add twice the « background-project-color » if it is used in the basemap layers.

Plus, the group « overview » is in mutually exclusive mode, which is not logical if I want to put a DEM and the border of the country, I want both to be visible…

### Steps to reproduce the issue

Just try to add a background (white with transparency) for the overview.
And also to have more then 1 layer visible.

### Versions, safeguards, check summary etc

All is in LTR.

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

Last

**Comment by Gustry** [comment]
> And I can’t add twice the « background-project-color » if it is used in the basemap layers.

You can just add to add it manually, the plugin is just making users aware of these groups.
But I don't know if it will work.

> Plus, the group « overview » is in mutually exclusive mode, which is not logical if I want to put a DEM and the border of the country, I want both to be visible…

Fixed in the next version

**Comment by katagen** [comment]
I saw that there is a default white background, but the transparency is set really high... for me, it should be set with the same transparency as the footer logo!

**Comment by katagen** [comment]
As I said, there is a white background, but the transparency is at 30%.
So I added in the CSS theme panel this part:

ol-overviewmap:not(.ol-collapsed) {
background: rgba(255, 255, 255, 0.7);
}

**Comment by katagen** [comment]
It doesn't need feedback!

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
