### ISSUE TITLE
Rotated print in Lizmap 3.7.3?

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4189]
### What is the question?

In version 3.7, it should be possible to specify a rotation angle for the printout. I think this already worked in earlier versions.
[mask on the map](https://user-images.githubusercontent.com/2145040/216579235-8b438ea5-7ea3-4549-95fa-398dea1450e8.png)

Is there an option that I have overlooked or is it a bug?

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/a599de3e-3e9d-4da4-a750-9f6663cd8c37)

### Versions, safeguards, check summary etc

QGIS Desktop 3.22.16 or 3.34.3
Lizmap Plugin 4.2.0
Lizmap Server-Plugin 2.8.4

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04.

### Browsers

Chrome

### Browsers version

Chrome 121.0.6167.161

**Comment by Gustry** [comment]
Only the map content was rotated, not the frame. So it was perfectly working if the frame was a square and the rotation a multiple of 90°. The current implemented behavior was misleading users.

The input number has been hidden with CSS.

With some extra [javascript](https://docs.lizmap.com/current/fr/publish/customization/javascript.html), you can remove the CSS https://github.com/3liz/lizmap-web-client/blob/986838d651ba4e998b096453b2caf69f2ba8fc6b/assets/src/components/Print.js#L164

**Comment by nboisteault** [comment]
It should be possible with few code now: https://github.com/3liz/lizmap-web-client/commit/b1e7a30066e1dd3e2ffd10ebd30c147f4e1a619d

**Comment by guenterw** [comment]
Thank you very much
