### ISSUE TITLE
[question] Exporting behavior - Export all fields even the hidden fields

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#419]
Background Run:
Lizmap Web Client: 3.0.1
SO: Windows Server 64-bits
QGIS Server 2.14.8 64-bits

We have some way to export only the fields of the attribute table in lizmap webclient?

Regards
João

**Comment by rldhont** [comment]
Lizmap exports layers as defined in the QGIS Project `OWS Server` tab.

Do you want exports is like attribute table and not like WFS service ?

**Comment by jonnyforestGIS** [comment]
Hi @rldhont i deactivate the wfs and wms in the columns of the layer proprieties but when export from the atribute table from lizmap web client when i open the exported file we bring all the columns i will do more tests and give you feedback.

Regards
João

**Comment by rldhont** [comment]
@jonnyforestGIS can you confirm it ?

**Comment by jonnyforestGIS** [comment]
@rldhont sorry for the delay. You can close this. 
Is working. The problem is when we do the changes in the layer proprieties sometimes when we do the update project is necessary wait to see the changes.
Regards
João
