### ISSUE TITLE
[Bug]: Vector data is not visible if map CRS is 3844

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#4191]
### What is the bug?

First I have reported the bug on issue #4065, but it seems that it does not relate. Almost all our maps use CRS 3844, after updating to lizmap version 3.7.0 (initially) all our vector data (postgres as source) stopped getting rendered on the maps (I've not tested rasters). I've opened projects and resaved them with new lizmap plugin, changed the way base layers are added, but nothing changed.

### Steps to reproduce the issue

To test the issue I've created 2 test maps with some randomly generated points saved to geopackage (CRS 3857). First map CRS was set to [3857], the second to [3844]. The 3857 version works, the second one with CRS 3844 doesn't.
I've converted the points to 3844 so no on-the-fly conversion is needed to render, but it did not help for CRS 3844. Then I've tried other CRS-s, namely UTM34N (32634) and EOV (23700) (although this second is not even referenced for the area of the points. In both case the points are rendered, everything works as expected.
Data can be downloaded from layer properties (tested to download as kml) so it is present but not rendered. 

I don't know where to search further for the bug...but clearly it is something with the definition of CRS EPSG 3844 and it was not present before version 3.7.

**EDIT: I'm removing links to test maps and the maps as bug was identified.**

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.3
* Lizmap plugin : 4.2.0
* QGIS Desktop : 3.28.14
* QGIS Server : 3.28.14
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : v1.5.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Firefox 122.0.1 (64-bit), Chrome 121.0.6167.161, Edge Version 121.0.2277.112

**Comment by Gustry** [comment]
QGIS Server is returning empty tiles on this CRS (due to inverted axis).
(QGIS Server, Proj4js, OpenLayers 8 and LWC)

```python
QgsCoordinateReferenceSystem('EPSG:3844').hasAxisInverted()
True
```

If you switch your project to 3857, indeed, it will work.

@rldhont Should the plugin warn users when using CRS 3844 ? Or any inverted axis ?

**Comment by aeduard** [comment]
This is how I've overcome the issue, I've switched all our projects to 3857, but than the numeric coordinate reading (following mouse position) is not that useful for us.

**Comment by Gustry** [comment]
As a temporary workaround, it's IMHO better to warn users. I made a patch in the plugin https://github.com/3liz/lizmap-plugin/pull/558

**Comment by rldhont** [comment]
@aeduard are you able to test https://github.com/3liz/lizmap-web-client/pull/4208 with your project ?

**Comment by aeduard** [comment]
I'm sure I didn't do the testing well, never tried before. I've downloaded the modified Lizmap.js file (from your link), replaced it on my server, than restarted apache2 and force refresh me browser with the map opened. Nothing is loading anymore. Than I've realized that it is not the same Lizmap.js what is found on the server at ...lizmap/www/assets/js/lizmap.js. I've tried searching for the modified Lizmap.js, but I can't find on my installation.
I've checked the folder structure of lizmap-web-client here on github and on my server, but I have only the _lizmap_ part, for e.g. the _assets_ folder is missing. So I'm completely lost :), can you give some guidance?

Also I've observed that you are using on the testing files of this commit EPSG 3044, I'm not sure that there is a problem also with that CRS, I had problems with 3844.

**Comment by rldhont** [comment]
@aeduard I have added a test for 3844.

**Comment by aeduard** [comment]
The map is opening, but the polygons are rendered on a strange place (probably due to the inverted axis). Without modifying the file/files on this commit it won't work as expected. I don't know how to do it.

![test_3844](https://github.com/3liz/lizmap-web-client/assets/16295364/ab9e1f1a-1a3d-4181-a4d1-be8cabedbcbc)

**Comment by rldhont** [comment]
@aeduard with the fix

![Capture d’écran 2024-02-14 à 19 54 40](https://github.com/3liz/lizmap-web-client/assets/1575538/1aea2d77-a9cb-4fed-bb8a-ae41acd754d7)

**Comment by aeduard** [comment]
Perfect, ty!
