### ISSUE TITLE
[Bug]: Affichage des fonds non libres IGN (SCAN25)

### ISSUE THREAD

**Issue by Alain-LG** [3liz/lizmap-web-client#4207]
### What is the bug?

Bonjour,

Après plusieurs essais, je ne parviens pas à afficher le fond de plan IGN SCAN25.

Lien avec le ticket [Issue 3591](https://github.com/3liz/lizmap-web-client/issues/3591#issue-1653825488) mais sans répondre à ce point spécifique du SCAN25.

### Steps to reproduce the issue

J'ai tenté avec l'option des fonds externes et ma clé générée sur mon espace Géoservices de l'IGN : ce qui fonctionnait parfaitement avant la bascule Géoplateforme.
J'ai suivi le paramétrage préconisé par le site de l'IGN [https://geoservices.ign.fr/documentation/services/utilisation-sig/tutoriel-qgis/gpf-wms-wmts-donneesnonlibres] : le SCAN25 s'affiche bien sous QGIS mais pas sous Lizmap.
J'ai testé la solution ci-dessus en une couche classique et en une couche définie comme "Fond de carte".

Pouvez-vous me préciser comment paramétrer ma carte pour que je puisse à nouveau afficher ce fond IGN SVP ?

En vous remerciant par avance.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.10
* Lizmap plugin : 4.1.2
* QGIS Desktop : 3.28.6
* Lizmap.com : Yes
* QGIS Server : 3.28.14
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.0
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Hébergement lizmap

### Browsers

Firefox

### Browsers version

Firefox 122

**Comment by nworr** [comment]
Les autres fond IGN libres fonctionnent-ils ?
La projection du projet est elle compatible avec les projections gérées par les service IGN ?

**Comment by nworr** [comment]
Avec QGIS 3.28, il ne faut pour l'instant pas suivre la [doc de l'ign](https://geoservices.ign.fr/documentation/services/utilisation-sig/tutoriel-qgis/gpf-wms-wmts-donneesnonlibres) mais procéder comme pour les version antérieures : ne pas utiliser la base de d'authentification qgis, et indique `apikey=<Votre clé >` dans l'URL de service.

Cela devrait fonctionner dans QGIS bureautique et lizmap

**Comment by Alain-LG** [comment]
Désolé mais cela ne fonctionne pas ou alors je n'ai pas compris votre solution. En mettant "apikey=<ma_clé> dans l'URL (geoplateforme) de service, j'ai un message d’erreur dès la tentative de connexion :  
![image](https://github.com/3liz/lizmap-web-client/assets/68422902/1be20d43-6416-4a3a-877c-244c9f39a4ad)

Pouvez-vous ajouter des copies d'écran du paramétrage côté "Gestionnaire de données QGIS" et "LWC" SVP ?
Quelle URL utilisez-vous SVP ? 

Pour le moment, je conserve l'URL du serveur "Geoservices" (wxs.ign.fr) et je fais avec la pixellisation... 
Mais quid de la bascule définitive sur la Géoplateforme au 15 mars...

**Comment by nworr** [comment]
Bonjour, 

En faisant les captures, je viens de reproduire le problème : la version 1.3.0 me génère la même erreur. 
Avec l'url 

> https://data.geopf.fr/private/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities&apikey=ign_scan_ws

Ca fonctionne

 Voici la configuration que j'indique : 
![ign_wmr-private-kety](https://github.com/3liz/lizmap-web-client/assets/43475951/34e5a251-59f7-4c2e-b1a8-32b0b4347b60)

En pièce jointe, un projet avec uniquement une couche IGN (Carte_topographique IGN Scan25),  qui fonctionne 

[ign_scan.zip](https://github.com/3liz/lizmap-web-client/files/14384398/ign_scan.zip)

**Comment by Alain-LG** [comment]
🥇 Parfait ! Un grand MERCI car ça fonctionne enfin !

Je n'aurais jamais trouvé tout seul...

Cela provient donc de la version du service : 1.3.0 ne permet pas l'affichage sous LWC alors que la version 1.0.0 ne pose pas de problème.

**Comment by Alain-LG** [comment]
🥇 Parfait ! Un grand MERCI car ça fonctionne enfin !

Je n'aurais jamais trouvé tout seul...

Cela provient donc de la version du service : 1.3.0 ne permet pas l'affichage sous LWC alors que la version 1.0.0 ne pose pas de problème.

**Comment by Gustry** [comment]
Ajout d'une vérification côté QGIS bureautique dans le PR https://github.com/3liz/lizmap-plugin/pull/564
