### ISSUE TITLE
[Bug]: draw tool - export drawings to wrong place

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4216]
### What is the bug?

the draw tool export drawings to wrong place

### Steps to reproduce the issue

try to drawing, export and import file

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.4-pre.7260
* Lizmap plugin : 4.2.2
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

122.0.1

**Comment by Gustry** [comment]
This was already done for 3.7 
https://github.com/3liz/lizmap-web-client/commits/release_3_7/

Are you sure you have the issue on 3.6 ?
https://github.com/3liz/lizmap-web-client/blob/release_3_6/assets/src/modules/Digitizing.js#L515
(we hope there won't be any new release on 3.6 maybe)

**Comment by josemvm** [comment]
@nboisteault and @Gustry thanks

**Comment by josemvm** [comment]
>Are you sure you have the issue on 3.6 ?

it's ok on 3.6.10
