### ISSUE TITLE
[Question]:  I would like to create a repository and assign user X to manage it using PHP scripts 

### ISSUE THREAD

**Issue by sag1687** [3liz/lizmap-web-client#4217]
### What is the question?

Good morning, I would like to create a repository and assign user X to manage it using PHP scripts from console.php, but I'm not very familiar with the syntax. Can someone help me? The idea is to create a repository, assign it to user X and group X for repository management.

### Versions, safeguards, check summary etc

lizmap 3.7

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu server 22

### Browsers

Chrome

### Browsers version

chrome 90

**Comment by Gustry** [comment]
You should look at the CLI tool `php lizmap/console.php`, I will check for a paragraph to mention it.

**Comment by Gustry** [comment]
Add CLI tool in the documentation https://github.com/3liz/lizmap-documentation/commit/91759e6f01283fe568b448f2c0ab712a66f81bac
