### ISSUE TITLE
[Bug]: Probleme de chargement de couche sur les projet lizmap depuis mis a jour 

### ISSUE THREAD

**Issue by remichairat** [3liz/lizmap-web-client#4227]
### What is the bug?

Après avoir mis a jour lizmap web client (vers la version 3.6.8) je rencontre un souci sur tous mes projets.
En effet le projet ce charge normalement le fond de carte charge mais aucune de mes 
![bug_lizmap](https://github.com/3liz/lizmap-web-client/assets/27948553/b3ab8188-5c50-49f5-808e-1456d6385dea)
couches n'apparait quand je regarde avec la console développer de mon navigateur web les couche ce charge mais le fichier est vide je n'ai pas d'erreur 500 mais juste un fichier vide qui ce charge.

### Steps to reproduce the issue

charger un projet lizmap avec la nouvelle version du lizmap webclient et n'avoir aucune erreur mais aucune couche qui n'apparait 
![bug_lizmap_1](https://github.com/3liz/lizmap-web-client/assets/27948553/bf8299eb-e030-423d-8b0f-1b2d5d84b05f)

### Versions, safeguards, check summary etc

lizmap web client 3.6.8
qgis serveur 3.28.15
qgis desktop  : 3.28.13
plugin lizmap : 4.2.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11 bullseye

### Browsers

Firefox

### Browsers version

firefox 123.0 (64 bits)

### Relevant log output

```shell
je n'ai aucun log qui apparait car le projet charge sans erreur juste les images de mes couches qui sont charger sont vide.
```

**Comment by remichairat** [comment]
j'ai oublier de préciser toutes mes couches sont sur postgresql version de postgresql 13

**Comment by Gustry** [comment]
> je n'ai aucun log qui apparait car le projet charge sans erreur

You need to check QGIS server logs, it's the one rendering tiles. Maybe QGIS server can't connect to your database ?

Please follow the ticket template, as we could know your safeguards and some possible questions your database settings.
How do you connect to your database ?

> lizmap web client (vers la version 3.6.8)

Side note, LWC 3.6.10 is available.
