### ISSUE TITLE
[Bug]: Blurry Basemap if QGIS Project CRS is not EPSG:3857

### ISSUE THREAD

**Issue by chrimohr** [3liz/lizmap-web-client#4228]
### What is the bug?

When using a QGIS Project CRS other than  EPSG:3857 the OpenStreetMap Mapnik Basemap gets blury.

EPSG:3857
![image](https://github.com/3liz/lizmap-web-client/assets/13176177/343b72ef-fff0-4345-bb04-16d6d7639f18)

EPSG:25832
![image](https://github.com/3liz/lizmap-web-client/assets/13176177/23896dba-76ba-4c78-8ecc-8ad3eb43a64a)

In LWC 3.6 where, baselayers were not included in the QGIS Project, this was not an issue.

### Steps to reproduce the issue

1. Save empty QGIS Project
2. Set QGIS CRS (e.g. EPSG:25832)
3. Open Lizmap Plugin and add "OpenStreetMap Mapnik" as a baselayer

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.3
* Lizmap plugin : 4.2.2
* QGIS Desktop : 3.28.11
* QGIS Server : 3.28.13
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10

### Browsers

Firefox, Chrome

### Browsers version

121.0.6167.185

**Comment by Gustry** [comment]
OpenStreetmap baselayer is only available in EPSG:3857, so it's expected to be blurry if used in another CRS.

LWC 3.6 was switching your project to EPSG:3857 automatically in the background if you got a base layer.

Now, LWC 3.7 use your project projection.

**Comment by Gustry** [comment]
I forgot to add, there is a checkbox "Use native scales" for using scales based on the map CRS in the plugin. Very useful for EPSG:3857.

**Comment by chrimohr** [comment]
> OpenStreetmap baselayer is only available in EPSG:3857, so it's expected to be blurry if used in another CRS.

I'm aware of that but did not know that LWC 3.6 changed it.
