### ISSUE TITLE
[Bug]: KML file created and imported from Drawing tool is not displayed

### ISSUE THREAD

**Issue by fbaronten** [3liz/lizmap-web-client#4234]
### What is the bug? (in English)

A geometry exported in KML from the Drawing tool then re-imported into Lizmap is not displayed.

![kml_lizmap](https://github.com/3liz/lizmap-web-client/assets/121932050/049318a0-1394-41bd-9ed2-489843ac57ee)

Thanks for your help

### Steps to reproduce the issue

1. Create a geometry with Drawing tool 
2. Export it to a KML file
3. Import the KML in Lizmap using the Import function from Drawing tool (or Selection tool)

The file seems to be imported but the geometry is not displayed. It does not seem to be related to a symbology problem because the geometry is not displayed when importing the KML file into QGIS.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.3
* Lizmap plugin : 4.2.2
* QGIS Desktop : 3.28.4
* Lizmap.com : Yes
* QGIS Server : 3.28.15
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.0
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Hébergement Lizmap

### Browsers

Chrome

### Browsers version

Chrome 121.0.6167.187

**Comment by Gustry** [comment]
It should be already fixed d48a18d212906a95c10e3dd33c112305a1c17992

If you to try in the meantime, you can download the latest zip https://packages.3liz.org/

Please reopen if necessary.
