### ISSUE TITLE
[question][Basemap] Don't load xml file of google-hibrid

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#424]
QGIS Server: 2.14.8 64-bits
Lizmap Web Client: 3.0.4

Hi guys, i'm trying to use this code of  google-hibrid base map xml file in the lizmap but we don't recognize.
Inside of QGIS works perfectly but when i try to put in the web browser lizmap project don't appear.
I test with virtual earth.xml and woks fine.
Can someone test this?
Regards
João

**File:** [google-hibrid.txt](https://github.com/3liz/lizmap-web-client/files/633644/google-hibrid.txt)

**Comment by josemvm** [comment]
hi @jonnyforestGIS 

i did text your issue and it works for me with QGIS Server/Desktop: 2.14.10 64-bits and Lizmap Web Client: master!

regards
José

**Comment by rldhont** [comment]
@jonnyforestGIS the layer name is `google-hybrid` not `google-hibrid`.

**Comment by jonnyforestGIS** [comment]
It's working :+1:
