### ISSUE TITLE
[Question]: QGIS Server is not correctly installed

### ISSUE THREAD

**Issue by pmarciniak1234567** [3liz/lizmap-web-client#4244]
### What is the question? (in English)

Hello i cant solve problem which is "QGIS Server is not correctly installed on your server or the URL for OGC requests given in the Lizmap configuration is not correct" logs in lizmap web clinets are "QGIS server minimum 3.10 and Lizmap QGIS server plugin minimum 2.8.1 need to be installed and configured correctly. Your QGIS server couldn't be reached correctly with the given URL "http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi". but we  meet the requirements

### Versions, safeguards, check summary etc

Qgis Server Version: 3.6.7

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

Chrome 121.0.6167.189

### Relevant log output

```shell
QGIS server minimum 3.10 and Lizmap QGIS server plugin minimum 2.8.1 need to be installed and configured correctly. Your QGIS server couldn't be reached correctly with the given URL "http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi".
```

**Comment by Gustry** [comment]
> Qgis Server Version: 3.6.7

I guess you mean Lizmap 3.6.7 ?

Please install latest update of Lizmap 3.6.X https://github.com/3liz/lizmap-web-client/releases
It's 3.6.10 already.

**Comment by Gustry** [comment]
Closing this ticket as you opened a new question #4252
