### ISSUE TITLE
Popup zoom  does not work

### ISSUE THREAD

**Issue by mibalas** [3liz/lizmap-web-client#425]
Hi, I'm starting to use lizmap.

I have a layer that show a popup with its table fields. So when I click on the zoom tool, it should bring the selected feature closer, but the zoom goes to another place.

Whats happening?
![1](https://cloud.githubusercontent.com/assets/15907968/20943776/0078b3c4-bbe8-11e6-8066-4c54011d1fc8.png)

![2](https://cloud.githubusercontent.com/assets/15907968/20943783/0853a234-bbe8-11e6-81e3-0dba15236c94.png)

**Comment by nboisteault** [comment]
Hi,
I have the same behavior with QGIS Server 2.14 but when I update to 2.18 it works fine.

**Comment by rldhont** [comment]
Can you be more precise about Lizmap Web Client version and QGIS Server version ?
It's probably an issue ?

**Comment by mibalas** [comment]
Hi, thank you for your replies.

I'm using QGIS Desktop 2.14 with Lizmap plugin 2.1.2 (windows) and QGIS Server 2.14 with Lizmap Web Client 3.1 (Debian 8.6);

I'm using too Postgresql 8.4 and my files are on projection EPSG:3857

I updated to QGIS Server 2.18 but nothing changed.

I think is not a issue, because in demo project this funciotn is working.


And about the projection? its correct to work with the same projection as the OSM basemap?

**Comment by mibalas** [comment]
Hi, I did a test and the problem is about projection.

I reprojected my files to another projection (EPSG:4674) and the zoom function is working.

I dont know why this happens, if anyone can explain.

thanks

**Comment by rldhont** [comment]
@mibalas, these has probably be fixed by a24c7a4074ee328b3a0a4b36c668832870ccc7a9

**Comment by rldhont** [comment]
but has to be merged

**Comment by rldhont** [comment]
a24c7a4 has ben merged. Reopened if needed
