### ISSUE TITLE
Refresh a single layer every n seconds

### ISSUE THREAD

**Issue by carekapt** [3liz/lizmap-web-client#4250]
Hi everybody.
I'm currently migrating from LWC 3.5.12 to 3.7.5 (just released this afternoon) and getting some issues with the javascript I used to refresh a layer. The data for this layer is stored in a PostgreSQL server, then passes through a Geoserver for symbology and finally, I consume it on the LWC.
This layer is updated every second, but on LWC 3.5.12 I only refreshed it every 30s.
The script is the well known (See bellow) 
[refreshLayer.txt](https://github.com/3liz/lizmap-web-client/files/14423344/refreshLayer.txt)

### Versions, safeguards, check summary etc

**QGIS-DESKTOP**: 3.28.11 Firenze
**QGIS-SERVER**: [3.28.11](https://github.com/qgis/QGIS/releases/tag/final-3_28_11)
**LWC:** 3.7.5
**QGIS-PLUGIN-MANAGER PLUGINS INSTALLED AND VERSION :**

- atlasprint	3.3.2
- Lizmap server	2.8.4
- wfsOutputExtension	1.8.0

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

latest

**Comment by Gustry** [comment]
It seems we need to find the OpenLayers object, not sure how to get that from the new API, then `.getSource().refresh();` needs to be call on this object, according to OpenLayers API.

But do we get the OL object ?

**Comment by carekapt** [comment]
> It seems we need to find the OpenLayers object, not sure how to get that from the new API, then `.getSource().refresh();` needs to be call on this object, according to OpenLayers API.
> 
> But do we get the OL object ?

I don't get an object...a get undefined...I only get an object in LWC 3.5.12

**Comment by nboisteault** [comment]
Hi @carekapt ,
I have updated the script for Lizmap >= 3.7 : https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/misc/refresh_layers_every_n_seconds
Does it work for you?

**Comment by carekapt** [comment]
> Hi @carekapt , I have updated the script for Lizmap >= 3.7 : https://github.com/3liz/lizmap-javascript-scripts/tree/master/library/misc/refresh_layers_every_n_seconds Does it work for you?

YES!
Many thanks, it works like a charm!

![image](https://github.com/3liz/lizmap-web-client/assets/38278887/e43e37f0-5d41-40ad-9979-dbad8e037094)
