### ISSUE TITLE
[Bug]: group as layer - allways checked if layers are checked

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4251]
### What is the bug? (in English)

group - group as layer (`not toggled`)
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/f3e4b8af-3224-443d-a7d5-bb047af9aec0)

layers (`all toggled`)
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/cb6b260b-cf3c-4cf7-9aea-48b8a398031d)

lwc - group appears `toggled`
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/726241a7-b4aa-433f-b163-b5f56c00c1b7)

Note: no symbol for group as layer (raster)

due to this problem i'm trying to disable the group via script
https://github.com/3liz/lizmap-documentation/issues/248#issuecomment-1962925244

thanks

### Steps to reproduce the issue

try to create a group as layer like this

### Versions, safeguards, check summary etc

 Lizmap Web Client : 3.7.4 (
 Lizmap plugin : 4.2.3
 QGIS Desktop : 3.28.15
 QGIS Server : 3.28.15
 Py-QGIS-Server : not used
 QGIS Server plugin atlasprint : 3.3.2
 QGIS Server plugin lizmap_server : 2.8.4
 QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

122.0.1

**Comment by josemvm** [comment]
not need to have layers `toggled` inside the group and it works as expected

**Comment by Gustry** [comment]
Linked to #3968 ?

**Comment by josemvm** [comment]
@Gustry yes I also think it's very important gradually to bring Lizmap's behavior closer to QGIS Desktop
