### ISSUE TITLE
[Question]: Upload field / path expression

### ISSUE THREAD

**Issue by meyerlor** [3liz/lizmap-web-client#4253]
### What is the question? (in English)

I was very delighted to see in the 3.7.3 release the added editing feature to set an expression for upload fields (I'm on LWC 3.7.4. now). Maybe I do not understand it correctly though - is it now possible to set/change the name of the uploaded file by expression? It would be very convenient to have the pictures renamed after an expression like: `'media/treepictures/'+"TreeID"+'jpg'`  so the original filename is changed to the TreeID. The original filename often is very cryptic and makes it hard to further process images. 

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.4
* Lizmap plugin : 4.2.3
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Browsers version

Firefox 115

**Comment by Gustry** [comment]
Quick answer for now, the linked PR is https://github.com/3liz/lizmap-web-client/pull/4058

There is an example in the description.

**Comment by meyerlor** [comment]
thanks for clarifying! - from the example i take it that it is possible to set the path but not the name of the picture itself.
