### ISSUE TITLE
[Feature] Resizable input text field in print option

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#426]
Hi,
when we want to add a long description (e.g notes) we have a normal input text, it's possible change to a resizable input-text (more box text)?

Regards

**Comment by nboisteault** [comment]
Hi,
There is an option in QGIS to enable multiline field. Lizmap then handle it and create a resizable text input.

**Comment by rldhont** [comment]
Thanks @nboisteault 
Can you update the doc https://github.com/3liz/lizmap-documentation ?

**Comment by jonnyforestGIS** [comment]
Hi, @nboisteault but in this case the input text is not related with the layers. Sorry i think i don't explain well. The input text is this. Change this to a box text.

Thanks
![user-guide-15-print-zone](https://cloud.githubusercontent.com/assets/4480601/21044840/b93f6e84-bdf5-11e6-8657-545ec77fc907.png)

**Comment by nboisteault** [comment]
Ah ok I read your question's title too fast.
You're right it would be better to create the description HTML element as a textarea and not an input I think.
I'll take a look and make this change in code if @rldhont is ok.
If you can't wait here is a solution. Look how to add your own javascript [here](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#adding-your-own-javascript) and add this quick hack : 

```javascript
lizMap.events.on({
     uicreated: function(e) {
        $('.print-labels [name="description"]').each(function() {
        var textbox = $(document.createElement('textarea')).val(this.value);
        $.each(this.attributes, function() {
        if (this.specified) {
           textbox.prop(this.name, this.value)
        }
      });
       $(this).replaceWith(textbox);
        });
    }
});
```

**Comment by jonnyforestGIS** [comment]
Very cool @nboisteault . Thanks :) I will test. I think that will be cool create a folder specific or repo with this kind of js examples.

**Comment by jonnyforestGIS** [comment]
@nboisteault i test but still fixed i open the firefox developer tools and i add manually the parameter height to see the change but still fixe area even with auto value.

**Comment by nboisteault** [comment]
I see. The DOM element is created when the impression template is selected.
Try this : 

```javascript
$('body').on('DOMNodeInserted', '.print-labels [name="description"]', function () {
        $('.print-labels [name="description"]').each(function() {
        var textbox = $(document.createElement('textarea')).val(this.value);
        $.each(this.attributes, function() {
        if (this.specified) {
           textbox.prop(this.name, this.value)
        }
      });
       $(this).replaceWith(textbox);
        });
});
```

**Comment by jonnyforestGIS** [comment]
@nboisteault i test and work the final js code:
```javascript
 lizMap.events.on({
     uicreated: function(e) {
		$('body').on('DOMNodeInserted', '.print-labels [name="description"]', function () {
        $('.print-labels [name="description"]').each(function() {
        var textbox = $(document.createElement('textarea')).val(this.value);
        $.each(this.attributes, function() {
        if (this.specified) {
           textbox.prop(this.name, this.value)
        }
      });
       $(this).replaceWith(textbox);
        });
		
  });
 }
}) 
```

![resizable_box_note](https://cloud.githubusercontent.com/assets/4480601/21145505/78d80cb2-c146-11e6-92a5-7b1c262371c2.png)

@rldhont can put this js example next top the others in the montepillier project example?

**Comment by rldhont** [comment]
@nboisteault can you provide a PR for this enhancement ?

**Comment by nboisteault** [comment]
@rldhont I'll take look next week.

**Comment by nboisteault** [comment]
The feature already exists. I've updated documentation to explain how to enable it here : https://github.com/3liz/lizmap-documentation/pull/98
