### ISSUE TITLE
Filter[Question]: Filter temporal data by user

### ISSUE THREAD

**Issue by BaBoWaGa** [3liz/lizmap-web-client#4268]
### What is the question? (in English)

Hi, I have a time manager on a postGIS layer with daily start and end date. Is there a way to limit data display based on logged in user?
Example:
alpha user can see data from 1 to 5 March 2024
beta user can see data from February 1 to March 5, 2024
gamma user can see the entirety of the data

Lizmap 7.5 QGIS 3.28.15

### Versions, safeguards, check summary etc

Lizmap 7.5 QGIS 3.28.15

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 11

### Browsers

Chrome

### Browsers version

122.0.6261.95

**Comment by katagen** [comment]
Did you check the documentation here ?

https://docs.lizmap.com/3.7/en/publish/lizmap_plugin/filtered_layers_login.html

**Comment by BaBoWaGa** [comment]
Yes, thanks, I managed to do something by following those instructions, the only thing I didn't understand is how and if I can hide the display of some fields depending on the logged in user.

**Comment by Gustry** [comment]
> if I can hide the display of some fields depending on the logged in user.

It's not possible with Lizmap.
Maybe with some Javascript, but I doubt and it wouldn't be secure/safety because all the data will still be in the webbrowser.

**Comment by BaBoWaGa** [comment]
Maybe with a script like this

layer = QgsProject.instance().mapLayersByName('Your_layer_name')[0]  # Make sure to replace 'Your_layer_name' with the actual name of your layer

# Check if the web user is in the lizmap_user and/or lizmap_user_groups list
web_user = 'web_username'  # Replace with the actual web user's name
user_group = 'user_group'  # Replace with the actual user's group name

# Check if the web user is in the lizmap_user list
if web_user in layer.customProperty("lizmap_user"):
    # If the web user is present, select the fields to display
    fields_to_display = ['field1', 'field2', 'field3']
else:
    # If the web user is not present, select a different set of fields to display
    fields_to_display = ['alternative_field1', 'alternative_field2']

# Update the display of fields in the layer
layer.setSubsetString('"field_name" IN {}'.format(tuple(fields_to_display)))

**Comment by Gustry** [comment]
This is Python, so it can only run as a Python plugin for QGIS server.

**Comment by BaBoWaGa** [comment]
Ok thanks
