### ISSUE TITLE
remove cache server for layer (tile cache)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#427]
hi,

i think that's very important to create, somehow (LWC or LWC plugin), a user policy that prevents remove cache server by any user.

thanks

**Comment by mdouchin** [comment]
No regular user can delete the cache, only users in "admins" group. So the red crosses right next to the cached layers or groups are only visible by the admin user, and the controller method doing the job is obviously not accessible by non-admin users.

**Comment by josemvm** [comment]
thanks for the clarification
