### ISSUE TITLE
Regression!  Attibutes table's Hide Columns doesn't works in LWC 3.6.10 and 3.7.5 and Lizmap Plugin

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#4277]
When select the colums (fields) to hide, nothing happens  on LWC

### Steps to reproduce the issue

1. publish a shp or gpkg
2. active the layers attributes by plugin

![Schermata del 2024-03-07 18-42-52](https://github.com/3liz/lizmap-web-client/assets/12639444/5a2fff4e-5871-430f-ac5a-163aab2dcaa4)

3. select multiples column to hide in popup

![Schermata del 2024-03-07 18-43-11](https://github.com/3liz/lizmap-web-client/assets/12639444/971cf1dd-65ee-43bf-ac37-c7f78e78b4ed)

4. save and publish the project
5. click on a feature in LWC map

![Schermata del 2024-03-07 18-43-38](https://github.com/3liz/lizmap-web-client/assets/12639444/397dbe93-c2d6-4251-8884-f00f81372c53)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.10
* Lizmap plugin : 4.2.4
* QGIS Desktop : 3.36.0
* QGIS Server : 3.36.0
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 4.1.0
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 10 folder(s)
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

Chrome 122.0.6261.94

**Comment by Gustry** [comment]
Your screenshots are "Popup", not "Attribute table". It's two different tools. This is not the way to hide fields in a popup (depending of the kind of popup you use, CF documentation)

**Comment by Antoviscomi** [comment]
@Gustry I use the Automatico popup that read values from Attributes Table, as configured in Lizmap plugin,  at least in all previous versions of LWC it seems to me (I remember so)

**Comment by Antoviscomi** [comment]
@Gustry consider to reopen
![IMG_20240307_193856](https://github.com/3liz/lizmap-web-client/assets/12639444/98ee1ae1-49b0-416e-8e3b-1ad50530bce1)
This is the fields configuration

**Comment by josemvm** [comment]
@Antoviscomi i think that the popup is based on WMS and the attribute table is based on WFS from field options on QGIS Desktop

**Comment by Antoviscomi** [comment]
> @Antoviscomi i think that the popup is based on WMS and the attribute table is based on WFS from field options on QGIS Desktop

In the above screenshot are the configurations

**Comment by Antoviscomi** [comment]
> What would be the right way then?

No @josemvm doesn't works, I omitted the last screenshot for mistake in the initial bug topic

**Comment by Gustry** [comment]
@gioman Look at @Antoviscomi description ;-)

> @Gustry I have not checked this on LMWC 3.7.* but on previous versions if a field is unpublished from WMS capabilities (layer properties > fields > configuration > dot not expose via WMS) it surely does not show in the automatic popup in LMWC.

This 100% correct, it's correct behavior.

The "Attribute table" tool in Lizmap is not linked to the popup tool.

* Popup → WMS service
* Attribute table → WFS service

In "Automatic" popup, fields are coming straight from QGIS Server. If fields are not exposed on QGIS server, then LWC (which is downstream) will not have fields as well.

I just tried, it works for me, with "automatic" popup and hiding fields from WMS service. : 

![image](https://github.com/3liz/lizmap-web-client/assets/1609292/7fb1d761-4ec3-4bc6-b292-262314e57511)

`field_tab_1` is missing from the popup.

> QGIS Desktop : 3.36.0
QGIS Server : 3.36.0

@Antoviscomi Does it occurs since you have updated to QGIS Desktop and server 3.36 ?

You said 3.6.10 is impacted as well, but the number of backport on the 3.6 branch has been very low now, and QGIS 3.36 is very recent.

**Comment by Antoviscomi** [comment]
@gioman I don't know it is related to 3.36 Qgis update (it's possible) but in previous configurations (as above descripted) the fields I checked to hide were really hidded now I'm not able to hide them

**Comment by Antoviscomi** [comment]
> You said 3.6.10 is impacted as well, but the number of backport on the 3.6 branch has been very low now, and QGIS 3.36 is very recent.
@gioman yes, I confirm this impact for both 3.6.10 and 3.7.5 LWC versions, so I think you're right, there is something wrong on Qgis server 3.6 I suppose

**Comment by Antoviscomi** [comment]
@Gustry @gioman @josemvm  after `systemctl restart apache2` all works fine now

**Comment by Antoviscomi** [comment]
> When did you update to :
> 
> * QGIS server 3.36 ?
> * QGIS desktop 3.36 ?
> * LWC 3.6.10 ?
> * LWC 3.7.5 ?
> 
> Was it working in between these upgrades ?
> 
> You can make the query straight to QGIS server to check if these fields are exposed from QGIS server ?
> 
> LWC is an overlay to QGIS Server. If QGIS server is hiding fields (which must happen if the flag is set, then LWC can't have data and can't display it) . If LWC can display these hidden fields from QGIS Server, it means these fields are not hidden from QGIS Server.

@Gustry was only something wrong in session (apparently) because of after restart Qgis server all works as expected
