### ISSUE TITLE
[Bug]: Geolocation not working on iPhone in Safari

### ISSUE THREAD

**Issue by tbnobody** [3liz/lizmap-web-client#4282]
### What is the bug? (in English)

When clicking on the geolocation icon using the Safari Browser the following error message is shown:
`Origin does not have permission to use Geolocation service`

It didn't work with older iOS versions either.

Other sites like https://browserleaks.com/geo are working without any problems. 
The site running lizmap has https enabled.

### Steps to reproduce the issue

1. Open map in Safari on iOS
2. click the "Location" icon
3. Press "Begin" button

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.6
* QGIS Desktop : 3.34.3
* QGIS Server : 3.36.0
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Server: Debian 12; Client: iOS 17.4

### Browsers

Safari

### Browsers version

iOS 17.4

**Comment by tbnobody** [comment]
Ahhhh, you are right. One of the base maps did use just http instead of https. Wasn't aware that this could lead to that issue. Thank you very much!

**Comment by Gustry** [comment]
All resources in a website must have `https`, not just the main webserver.
