### ISSUE TITLE
[question] Nombre d'éléments retournés via popup

### ISSUE THREAD

**Issue by majorxtrem** [3liz/lizmap-web-client#430]
Bonjour, 

Je rencontre une limitation au niveau des popups, ceux ci ne retournent que 10 éléments par couche.

En regardant les logs apache voici la requête générée par lizmap

```
127.0.0.1/cgi-bin/qgis_mapserv.fcgi
?bbox=186834.567829%2C104453.99174%2C186885.36793%2C104477.142828
&crs=EPSG%3A31370
&exceptions=application%2Fvnd.ogc.se_inimage
&feature_count=10
&fi_line_tolerance=10
&fi_point_tolerance=25
&fi_polygon_tolerance=5
&format=image%2Fpng
&height=875
&i=975
&info_format=text%2Fxml
&j=365
&layers=Personnes%2CEmplacements
&map=%2Fhome%2Fdata%2Fftp%2Fcarto%2Fqgis%2Fgeoportail-public%2Fdinant_cimetieres.qgs
&query_layers=Personnes%2CEmplacements
&request=GetFeatureInfo
&service=WMS
&styles=default%2Cdefault
&version=1.3.0
&width=1920
```

La limitation vient du &feature_count=10, mais je ne trouve pas où changer/configurer ce paramètre pour retourner plus d'élément.

Merci d'avance pour vos réponses

Lizmap : banche master
qgis client et serveur : 2.18.1

**Comment by rldhont** [comment]
We  didn't provide a way to configure it.

Can you explain it in english and made a proposition of configuration ?

**Comment by majorxtrem** [comment]
I just need to know how to increase the value of feature_count to 100 for exemple in the url generation for the request.

I have try to change the value here : https://github.com/3liz/lizmap-web-client/blob/dcbe4488dc14617aa2f72dee04bb5161b6e9e6d1/lizmap/www/js/attributeTable.js#L1750

But it's not working, in apache log when I click on a popup the value for feature_count still at 10

**Comment by majorxtrem** [comment]
I fouded a solution :)

I had change maxFeatures:10 to maxFeatures:100 (3 times) in this file and it's working

https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/OpenLayers-2.13/OpenLayers.js

**Comment by rldhont** [comment]
Duplicate https://github.com/3liz/lizmap-web-client/issues/630 ?
A PR is proposed https://github.com/3liz/lizmap-web-client/pull/489
