### ISSUE TITLE
Ability to collapse / expand layers at startup 

### ISSUE THREAD

**Issue by carekapt** [3liz/lizmap-web-client#4304]
### What is the question? (in English)

Back in LWC 3.5.12, we used a javascript to collapse all layers inside groups, I've been testing with version 3.7.5 and on startup all layers are expanded...we have projects with 200+ layers and we would like to start the map with all layers collapsed .

Is there a way to make this work again in LWC 3.7.x ?

[collapse_layers.txt](https://github.com/3liz/lizmap-web-client/files/14603444/collapse_layers.txt)

Kind regards,
Nuno Silva & Sofia Henriques

### Versions, safeguards, check summary etc

QGIS-DESKTOP: 3.28.11 Firenze
QGIS-DESKTOP-LIZMAP-PLUGIN: 4.2.7
QGIS-SERVER: [3.28.11](https://github.com/qgis/QGIS/releases/tag/final-3_28_11)
LWC: 3.7.5
QGIS-PLUGIN-MANAGER PLUGINS INSTALLED AND VERSION :

atlasprint 3.3.2
Lizmap server 2.8.4
wfsOutputExtension 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Browsers version

latest

**Comment by guenterw** [comment]
I worked in exactly the same way.
In version 3.7.5 I use the themes for this.
If all groups are collapsed in the QGIS theme, then this is also the case in Lizmap. Only the first theme has to be loaded automatically.
Setting in the plugin under Layers - Activate first map Theme on startup

However, individual groups or legends can also be opened. All in all very flexible and simply ingenious.
For better handling of the themes in QGIS, I once had the "ThemeSelector" plugin programmed.

For me, this is one of the best new features in Lizmap 3.7. Unfortunately, I can't use it productively yet because I still have speed problems.
Are you satisfied with the speed compared to the older versions (e.g. 3.5.12)?

**Comment by carekapt** [comment]
> I worked in exactly the same way. In version 3.7.5 I use the themes for this. If all groups are collapsed in the QGIS theme, then this is also the case in Lizmap. Only the first theme has to be loaded automatically. Setting in the plugin under Layers - Activate first map Theme on startup
> 
> However, individual groups or legends can also be opened. All in all very flexible and simply ingenious. For better handling of the themes in QGIS, I once had the "ThemeSelector" plugin programmed.
> 
> For me, this is one of the best new features in Lizmap 3.7. Unfortunately, I can't use it productively yet because I still have speed problems. Are you satisfied with the speed compared to the older versions (e.g. 3.5.12)?

I'll give it a try to use the "activate first map theme on startup"....

Regarding the speed, I'm trying to setup an Apache J-Meter to measure speed between versions of LWC, but right now I have many things 'on my plate' to deal with...but the feeling I have is that there's no change of speed...I mainly use WMS layers, maybe an issue with other kind of datasets?

Kind regards,
Nuno Silva

**Comment by carekapt** [comment]
Well....I must be doing something wrong...
![LWC_1](https://github.com/3liz/lizmap-web-client/assets/38278887/fdb8da63-fc20-4898-89d4-0f6243627ae8)
![LWC_2](https://github.com/3liz/lizmap-web-client/assets/38278887/215b42e5-c663-4b18-98b8-bcdeb234911b)


I have all groups of layers collapsed, even on the project canvas, but when the project is loaded, all groups are expanded :(

![image](https://github.com/3liz/lizmap-web-client/assets/38278887/5ac4abf8-21aa-4e37-b4da-f205d5abd0b0)

**Comment by nboisteault** [comment]
Can you show your first theme activated in QGIS?

**Comment by guenterw** [comment]
Have you also defined a theme in QGIS?
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/aea72b77-7ac1-4913-aef9-8c2ed667a144)

These can then also be selected in QGIS
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/24dd56c1-0f2c-4ba2-8f2d-01c544071883)

The topics are sorted alphabetically, that's why i use " Standard"
Example: https://stadt-herbolzheim7.webgis.biz/

**Comment by carekapt** [comment]
> Have you also defined a theme in QGIS? ![image](https://private-user-images.githubusercontent.com/8373176/313151403-aea72b77-7ac1-4913-aef9-8c2ed667a144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTgxMjAsIm5iZiI6MTcxMDQ5NzgyMCwicGF0aCI6Ii84MzczMTc2LzMxMzE1MTQwMy1hZWE3MmI3Ny03YWMxLTQ5MTMtYWVmOS04YzJlZDY2N2ExNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTAxNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc5ZGZiODFiYThjYTg5ZmQ3YWFkOGVhMmI2NzA5ZmU2YjExODMyZGMxNGRjOWVkOTIwZTJkZjUxODBkOGM4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zF6PxBYu3TD0P_ujYzuXqcoiqtD8bC7CBNXTCZMdfGs)
> 
> These can then also be selected in Lizmap ![image](https://private-user-images.githubusercontent.com/8373176/313151589-24dd56c1-0f2c-4ba2-8f2d-01c544071883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTgxMjAsIm5iZiI6MTcxMDQ5NzgyMCwicGF0aCI6Ii84MzczMTc2LzMxMzE1MTU4OS0yNGRkNTZjMS0wZjJjLTRiYTItOGYyZC0wMWM1NDQwNzE4ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTAxNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkxYTI5ODc2NTI3NjMwYTYyYTkxZjVkOTA0YjY3ODc4ZmM3N2NkZGQ3YWFkOWM3YmRiZGExZmQ2MjNhYTQ4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WGTcAR7cmFvGSO7JGBDmtJchIeOpyg9FnvJCmalyDH8)
> 
> The topics are sorted alphabetically, that's why i use " Standard" Example: https://stadt-herbolzheim7.webgis.biz/

Well @guenterw ...you should see how red is my face right now...I didn't know that option on QGIS DESKTOP or where to change it in LWC..

![image](https://github.com/3liz/lizmap-web-client/assets/38278887/ac754f4a-8166-41d9-93fd-ccc3ec5d1778)


But now that I know, I published a project witl all group of layers collapsed and gave me new ideas about theming a project...

Many many many thanks for the inputs about this 'issue'
![image](https://github.com/3liz/lizmap-web-client/assets/38278887/0640db1d-1be8-4d29-9619-b5396696f73e)

**Comment by nboisteault** [comment]
Who is Sofia? :)
