### ISSUE TITLE
[Question]: Plugin URL

### ISSUE THREAD

**Issue by undertaker12** [3liz/lizmap-web-client#4306]
### What is the question? (in English)

Hello, I have a setup with Docker Compose and a separate NGINX proxy. Everything works except for 2 things: in the server management tab, I see "http://link:8080/" even though in the browser I use "http://link/". How can I change the URL in the QGIS desktop plugin and in the outgoing emails because they also contain "link:8080"? thx 4 any help

### Versions, safeguards, check summary etc

<html>
<body>

Liczba | 3.34.4
-- | --
Prizren
decd43dc17c
1.8.8

</body>
[3.34.4](https://github.com/qgis/QGIS/releases/tag/final-3_34_4)

Commit ID	[decd43dc17c](https://github.com/qgis/QGIS/commit/decd43dc17c)
Py-QGIS-Server	[1.8.8](https://github.com/3liz/py-qgis-server/releases/tag/1.8.8)

atlasprint	[3.3.2](https://github.com/3liz/qgis-atlasprint/releases/tag/3.3.2)
Lizmap server	[2.8.4](https://github.com/3liz/qgis-lizmap-server-plugin/releases/tag/2.8.4)
wfsOutputExtension	[1.8.0](https://github.com/3liz/qgis-wfsOutputExtension/releases/tag/1.8.0)

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu 22

### Browsers

Chrome

### Browsers version

Chrome 90

**Comment by Gustry** [comment]
In the plugin, `http://link/` works right ?

**Comment by undertaker12** [comment]
atm lockal ip http://192.168.190.20:8080 work fine but when i use nginx proxy manager i use https://somelink.net works too BUT in mail and qgist desktop url i have http://somelink.net:8080. When i open wms its http://somelink.net:8080/... that dont work but if i del 8080 works perfect

**Comment by Gustry** [comment]
You need to set some QGIS server variables if I'm not wrong.

**Comment by undertaker12** [comment]
ok i use stream in proxy .
