### ISSUE TITLE
[Question]: Select/Deselect all layers Button

### ISSUE THREAD

**Issue by soukac98** [3liz/lizmap-web-client#4314]
### What is the question? (in English)

Hello,
I'd like to add a button to deselect/select all layers at once in my lizmap map interface.
I added a .js file in my media trajectory but it didn't work.
Here is the code I added : 

    **_var selected_Features = m_ap.getSelectInteraction().getFeatures();
    
    selectedFeatures.forEach(function (feature) {
        // Deselect each feature
        map.getSelectInteraction().getFeatures().remove(feature);
    });
}

// You might trigger this function using a button click event
// Example using jQuery (make sure to include jQuery library if not already present)
$('#deselectAllButton').on('click', function () {
    deselectAllFeatures();
});_**

Does anyone know how to make it work?
Thanks!

### Versions, safeguards, check summary etc

Lizmap web client, version : 3.6.11

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10 Professionnal

### Browsers

Microsoft Edge

### Browsers version

Version 122.0.2365.92 (Version officielle) (64 bits)

**Comment by nboisteault** [comment]
Hi,
You mean selecting all features of all layers or making all layers visible?

**Comment by soukac98** [comment]
> Hi, You mean selecting all features of all layers or making all layers visible?

I mean having a button to select all my layers at once, and deselect them all at once

**Comment by katagen** [comment]
You could do 2 different themes (layers) for that...

**Comment by soukac98** [comment]
> You could do 2 different themes (layers) for that...

Can you please elaborate on that? I don't think I understand how creating themes may help with the button...
Thanks for your reply!

**Comment by katagen** [comment]
You can create a map theme with all the layers selected, and one with no layer!
![image](https://github.com/3liz/lizmap-web-client/assets/37768582/21542a4f-4c6f-4104-9d5c-a76a4c1ded7f)

**Comment by soukac98** [comment]
> You can create a map theme with all the layers selected, and one with no layer! ![image](https://private-user-images.githubusercontent.com/37768582/315741845-21542a4f-4c6f-4104-9d5c-a76a4c1ded7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTcyNDUsIm5iZiI6MTcxMTExNjk0NSwicGF0aCI6Ii8zNzc2ODU4Mi8zMTU3NDE4NDUtMjE1NDJhNGYtNGM2Zi00MTA0LTlkNWMtYTc2YTRjMWRlZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE0MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDc4ZDdhYmMxNmE3MThmM2NjNDNhN2NmNTZhYTgxZTFhYjJjYjM1MDM1ZDgxM2E3YjQzNzVjNWJmYjVjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcmhBOOIXK2CdJAjkDSwEUGMT9jI1B79zFlVMovenJs)

Thank you very much @katagen for the tip! it worked finally :D
