### ISSUE TITLE
[Bug]: "Get images directly from WMS Server" is not working in LWC 3.7+ for non-baselayer layers

### ISSUE THREAD

**Issue by maxencelaurent** [3liz/lizmap-web-client#4318]
### What is the bug? (in English)

Since LWC 3.7, "Get images directly from WMS Server" only works for baselayers.

It seems, since the big code refactor, the `externalServer` related code is only present in src/modules/config/BaseLayer.js (Lines 816 to 913)

 https://github.com/3liz/lizmap-web-client/blob/b0f674208d2d861f7833bedff62c35f7fab467de/assets/src/modules/config/BaseLayer.js#L816

# Example 
## Layer Source
- URL:  https://www.ogc.vd.ch/public/services/OGC/wmsVD/Mapserver/WMSServer
- name:  vd.glissement_DUTI
- source: crs=CRS:84&dpiMode=7&format=image/png&layers=vd.glissement_DUTI&styles&url=https://www.ogc.vd.ch/public/services/OGC/wmsVD/Mapserver/WMSServer
- provider: WMS

## Lizmap-plugin layer config
![layer_config](https://github.com/3liz/lizmap-web-client/assets/6583528/57b187dc-7882-4172-9481-6066c7316f47)

## WMS Request in LWC 3.6.10
![image](https://github.com/3liz/lizmap-web-client/assets/6583528/999f21e8-6a0d-4c69-b54e-cb87ba9887a5)

## WMS Request in LWC 3.7.5
![image](https://github.com/3liz/lizmap-web-client/assets/6583528/9321046f-673d-406d-a9f2-ed1f5eb23515)

After moving the layer in the `baselayers` group, the WMS request targets the original external server:
![image](https://github.com/3liz/lizmap-web-client/assets/6583528/0db3f62b-560b-4c63-b2e8-2fb44225e653)

### Steps to reproduce the issue

1. Add a WMS layer in your QGIS project as a plain (non-baselayer) layer
2. Toggle the "Get images directly from WMS Server" checkbox
3. View the project in LWC 3.7+

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.13
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 23.10

### Browsers

Firefox, Chrome

### Browsers version

Firefox 124; Chromium 122

### Relevant log output

```shell
no relevant data
```

**Comment by rldhont** [comment]
@maxencelaurent I invite you to test #4380

**Comment by maxencelaurent** [comment]
@rldhont tested successfully, thanks !
