### ISSUE TITLE
LWC print tool error

### ISSUE THREAD

**Issue by mibalas** [3liz/lizmap-web-client#432]
Hi, I try to use the print tool on lizmap but the following error is occurring:

500 INTERNAL SERVER ERROR

checking my apache error.log
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
[Mon Dec 12 17:20:25.296584 2016] [fcgid:warn] [pid 9551] [client 127.0.0.1:57209] mod_fcgid: error reading data, FastCGI server closed connection
[Mon Dec 12 17:20:25.296619 2016] [core:error] [pid 9551] [client 127.0.0.1:57209] End of script output before headers: qgis_mapserv.fcgi
[Mon Dec 12 17:20:31.049859 2016] [fcgid:error] [pid 9523] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(9559) exit(communication error), get unexpected signal 11

I found others topics with the same issue but not for print tool, so I can't solve...

Does anyone know how to solve this?

I'm using Qgis server 2.18 / LWC 3.04
Debian 8.6
php 5.6 / apache 2.4

**Comment by majorxtrem** [comment]
Hello,

Try with a very simple template, just the map.
If it's work, try with a label

If you have the 500 error with the label, look this => http://www.itopen.it/qgis-server-setup-notes/

**Comment by mibalas** [comment]
Hi, thank you for reply 

I did what you said and worked, with only the map and with the map and legend too.. but when I add a text box to the map's title, it does not work anymore :( 

any idea?

**Comment by rldhont** [comment]
Did you activated HTML for your text box ?
Do you instantiated a fake Xserver and configure it in apache ?

**Comment by mibalas** [comment]
Hi, i tried with and without check html box, but doesn't work..

I followed the tutorial http://www.itopen.it/qgis-server-setup-notes/
but when I add the file fcgid.conf, the Qgis server stop working, the LWC stay in loading screen looping and show "server error" message

**Comment by majorxtrem** [comment]
I don't use to fcgid.con config qgis_server
/etc/apache2/mods-enabled/fcgid.conf
```
<IfModule mod_fcgid.c>
  AddHandler    fcgid-script .fcgi
</IfModule>

```

I do that directly in
/etc/apache2/sites-enabled/000-default.conf

```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/lizmap-web-client-master/lizmap/www
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        # Longer timeout for WPS... default = 40
        FcgidIOTimeout 120
        FcgidInitialEnv LC_ALL "fr_BE.UTF-8"
        FcgidInitialEnv PYTHONIOENCODING UTF-8
        FcgidInitialEnv LANG "fr_BE.UTF-8"
        FcgidInitialEnv QGIS_DEBUG 0
        FcgidInitialEnv QGIS_SERVER_LOG_FILE /tmp/qgis-000.log
        FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0
        FcgidInitialEnv DISPLAY ":99"
        #FcgidInitialEnv QGIS_PLUGINPATH "/opt/qgis-server/plugins"
</VirtualHost>

# Needed for QGIS HelloServer plugin HTTP BASIC auth
  <IfModule mod_fcgid.c>
      RewriteEngine on
      RewriteCond %{HTTP:Authorization} .
      RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  </IfModule>

  ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
  <Directory "/usr/lib/cgi-bin">
      AllowOverride All
      Options +ExecCGI -MultiViews +FollowSymLinks
      # for apache2 > 2.4
      Require all granted
      #Require local granted
      #Allow from all
  </Directory>
```

**Comment by mibalas** [comment]
HI, I tried it, but when I add the lines:
<IfModule mod_fcgid.c>
      RewriteEngine on
      RewriteCond %{HTTP:Authorization} .
      RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  </IfModule>

The apache cant start anymore.. I get the following error: "Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details."

**Comment by majorxtrem** [comment]
you can remove this block, is not mandatory

```
  <IfModule mod_fcgid.c>
      RewriteEngine on
      RewriteCond %{HTTP:Authorization} .
      RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  </IfModule>
```

**Comment by rldhont** [comment]
Hi @mibalas,

QGIS Server segfault if no DISPLAY environment variable is provided to draw HTML text during the GetPrint. Other request or elements need a fake X server.

Take a look at the QGIS documentation:
* http://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_server_support.html#environment-variables

In the Apache vhost, the display is defined by
```
FcgidInitialEnv DISPLAY ":99"
```
But you have to instantiate a fake X server, for exemple:
```
Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
```

**Comment by mibalas** [comment]
Hi @rldhont I dont know what's happening.

The fake x server is working
` xvfb.service - X Virtual Frame Buffer Service
   Loaded: loaded (/etc/systemd/system/xvfb.service; enabled)
   Active: active (running) since Mon 2016-12-19 14:16:08 BRST; 22h ago
   CGroup: /system.slice/xvfb.service
           └─508 /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
`
I did the settings in /etc/apache2/sites-enabled/000-default.conf file but it does not work :/

I think it may be Debian, because I tested on Ubuntu server and worked..

**Comment by jlstanus** [comment]
@mibalas See https://github.com/jancelin/docker-lizmap/issues/40 i did this for the jessie debian image
