### ISSUE TITLE
[Bug]: Cannot retrieve new password V3.7.5

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#4320]
### What is the bug? (in English)

Forgotten password

### Steps to reproduce the issue

Go to your Lizmap site
Click on Forgotten password
Fill in Username and email
Retrieve
Give a 500 error

In the error file:
```
2024-03-21 10:48:20	[300]	 In sjabloon , ongeldig syntax voor tag  $basePath	D:\Webserver\lizmap\vendor\jelix\jelix\lib\jelix\tpl\jTplCompiler.class.php	153
```
### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.2
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.36.0
* QGIS Server : 3.36.0
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Window 11

### Browsers

Firefox, Chrome

### Browsers version

Chrome Versie 123.0.6312.58 (Officiële build) (64-bits)

### Relevant log output

```shell
2024-03-21 10:48:20	[300]	 In sjabloon , ongeldig syntax voor tag  $basePath	D:\Webserver\lizmap\vendor\jelix\jelix\lib\jelix\tpl\jTplCompiler.class.php	153
```

There is more that is not working correctly. When I add a non-existent username and email it seems to work. 
But in reality it doesn't. After all, I should receive a message that the username or email address is incorrect.
As soon as you enter the correct user and email, you will receive the before mentioned error message.
Please can somone try this ??

**Comment by Gustry** [comment]
> Lizmap Web Client : 3.7.2

I do not replicate the issue, the reset password is correct with login and email.
I'm on the latest release of LWC 3.7.5

**Comment by NvBgm** [comment]
I updated to 3.7.5 but still have the same problem. The request form for a new account works great. I think it runs via the same SMTP server, so that seems to be going well. But as soon as I say "I forgot my password" and enter the correct information, then something goes wrong. Error 500. A technical error has occurred. Sorry for this trouble.
In the error.log I then find "2024-03-22 14:16:06 [300] In template , invalid syntax for tag $basePath D:\Webserver\lizmap\vendor\jelix\jelix\lib\jelix\tpl\ jTplCompiler.class.php 153
"Do I have a setting that is incorrect in the SMTP server or in another config file?

**Comment by NvBgm** [comment]
There is more that is not working correctly. When I add a non-existent username and email it seems to work.
But in reality it doesn't. After all, I should receive a message that the username or email address is incorrect.
As soon as you enter the correct user and email, you will receive the before mentioned error message.
Please can somone try this ??

**Comment by NvBgm** [comment]
Is there anyone that can help me out with this problem i did try everything but cannot find the error.

**Comment by Gustry** [comment]
What is your version of PHP ?
Did you upgrade your Lizmap Web Client from a previous installation or did you install a fresh one ?

**Comment by laurentj** [comment]
It is fixed and will be available in the next maintenance version. Thanks for your report.
