### ISSUE TITLE
[Bug]: 3.8.0: Change zoom section for first get feature query

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4325]
### What is the bug? (in English)

The first time an element is selected for the Getfeature query (and previous zoom), the image section jumps back to the maximum section.

### Steps to reproduce the issue

- Zoom in 
https://cx21.webgis.biz/index.php/view/map?repository=altiprofil&project=test_profil
- Select "Flurstücksinfo" topic (theme)
- Select a parcel
- the popup is displayed correctly but the zoom section jumps back to max.

### Versions, safeguards, check summary etc

Lizmap 3.8.0 Alpha1
QGIS (Desktop and Server) 3.34.4

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

123.0.6312.59

**Comment by nboisteault** [comment]
Hi @guenterw ,
Do you still have this problem? If yes can you put back the projet to reproduce the issue?

**Comment by guenterw** [comment]
Hi @nboisteault ,
no, in Alpha.2 (28.05.2024) the problem apparently no longer exists.
The versions are getting better and better, thank you for that.

**Comment by nboisteault** [comment]
> Hi @nboisteault , no, in Alpha.2 (28.05.2024) the problem apparently no longer exists. The versions are getting better and better, thank you for that.

You help a lot with your clear bug reports. Thanks!
