### ISSUE TITLE
If server cache is activeted, select categories doesn't work

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4327]
### What is the bug? (in English)

I have set a layer called "Surface boisée". Firest, I didn't set the server cache, and if I select/deselect some categories, it works perfectly.
Now I set the server cache for this layer (Redis). But if I deselect some categories, they are still visible?!?
![Capture](https://github.com/3liz/lizmap-web-client/assets/37768582/dfb5ec37-4ec6-4607-a264-9745c72c68d0)

### Steps to reproduce the issue

See above

### Versions, safeguards, check summary etc

LWC 3.7.6
Lizmap plugin 4.3.3

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Safari

### Browsers version

LTR

**Comment by Gustry** [comment]
> All LTR

Please fill the ticket follow the template with plugin.
If we release a new version in a few days, how can we know which was your version impacted ?

**Comment by katagen** [comment]
Done... hope is it ok like that!

**Comment by nboisteault** [comment]
Hi,
Cache is not made for every combination of categories possible. So it is normal you get the tiles cached when the first requests are made.

**Comment by katagen** [comment]
Ok, I understand, but wouldn't it be more logical to disable the capability of select/diselect categories for layers with cache enable?
It is strange to see the checkboxes, if they have no effect... no?

**Comment by Gustry** [comment]
I agree, it looks like more a bug than a question. It's leading to a broken state of the tree  view.

**Comment by nboisteault** [comment]
I suggest to hide checkboxes in this case.

**Comment by katagen** [comment]
Just to mention that it is also not a good idea to use cache if you have set "label"... cause for each zoom step, it generates the label, and at the end, you have multiple times the same label!

**Comment by nboisteault** [comment]
@katagen You must use the `Metatile` parameter in the Lizmap plugin to make larger tiles and avoid multiple labels.

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
