### ISSUE TITLE
Attribution only for baselayers

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4328]
### What is the bug? (in English)

I have a layer called "Limite cantonale", with attribution set to "ccgeo".
![c1](https://github.com/3liz/lizmap-web-client/assets/37768582/bdc45c4c-9f1c-4fb2-abd4-8766832b58d5)

But in LWC, there is only the attribution of the baselayer "Swissimage", but not also the attribution "ccgeo"... Is it normal?
![c2](https://github.com/3liz/lizmap-web-client/assets/37768582/9650856c-1c48-433b-9cd0-a2676b6da0ac)

### Steps to reproduce the issue

See above

### Versions, safeguards, check summary etc

LWC 3.7.6
Lizmap plugin 4.3.3

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Safari

### Browsers version

LTR

**Comment by katagen** [comment]
Any idea?

**Comment by katagen** [comment]
Any news?

**Comment by Gustry** [comment]
@katagen I'm sorry to say that, but there is like 500 tickets opened (and 200 tagged as "bug").
Yes, we confirm the issue, it's unfortunate.

And we have an internal bug tracker with some tickets that no one will fund, about technical debt, under the hood tasks which must be done, step by step. We are still busy trying to fix more important bugs, supporting QGIS 3.34, removing OpenLayers 2 etc ...

I know it is slightly different for Lizmap, but the article from Nyall is kind of true http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/

I know this is a kind of regression, but there is nothing I can do here, I'm not a dev on this side.

> @Gustry: sorry to tag you, but I have clients that forced me to add there name...

Do you want a quote so you can ask your customers ?

**Comment by katagen** [comment]
Yes, send me a quote, and I will see what I can do!

But I don't promise 😉

**Comment by Gustry** [comment]
Thanks, let's see what we can do.
Can you send us an email to info@3liz.com, sorry I don't have your mail.
