### ISSUE TITLE
[Feature] Store pushed data locally when offline. Synchronise when online.

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#433]
It would be great if Lizmap was capable of storing pushed data locally when device is offline (no internet).
Then Lizmap would detect device is online and would push data to server.

**Comment by Mavialle** [comment]
Is this feature planned to be available in a future version of Lizmap? If not, can we do something to help its development?

**Comment by saturdayevening** [comment]
Our projects are in the mountains (no internet connection). It would be nice to use lizmap offline on the smartphone.

**Comment by mdouchin** [comment]
This feature would be very hard to implement. Lizmap is a client/server application, not designed for such a use case. You would better use the awesome QGIS dedicated tools such as [QField](qfield.org/) and [MerginMaps](https://merginmaps.com/)
