### ISSUE TITLE
[Bug]: Baselayers are not rendered below 1:2000 scale

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#4332]
### What is the bug? (in English)

When adding baselayers (either OSM or IGN), they are not rendered below 1:2000 scale while they are properly rendered in QGIS

![digi-studio 2024-03-28 at 10 59 06](https://github.com/3liz/lizmap-web-client/assets/49779177/acbd69cc-d4b3-452c-85c1-eba297791f76)

### Steps to reproduce the issue

1. add baselayers
2. Add scales below 1:2000 in the project
3. Render the map

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.4
* QGIS Desktop : 3.28.9
* Lizmap.com : Yes
* QGIS Server : 3.28.15
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

MacOs

### Browsers

Chrome

### Browsers version

Chromium Engine Version 123.0.6312.59

**Comment by vlebert** [comment]
I found out that disabling "niveau de zoom max" allows me to zoom up to 1:1000 (better than 1:2000).

However, it is blank on 1:500 zoom level. I think when the source XYZ server is not able to provide requested tiles, Lizmap client should display most close tile with an upscaling effect ?


![digi-studio 2024-04-02 at 12 58 35](https://github.com/3liz/lizmap-web-client/assets/49779177/dee4336c-b85a-4f60-95ff-457394fd8e03)

I have the same issue with WMTS default IGN layers

**Comment by rldhont** [comment]
This bug has not been fixed yet.

**Comment by nboisteault** [comment]
A first fix is available in Lizmap 3.7.9-pre: https://packages.3liz.org/pub/lizmap/unstable/3.7/
