### ISSUE TITLE
Can't edit PostGIS layer

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4335]
### What is the question? (in English)

I have a PostGIS layer that is present in QGIS, connected via a pg_service file. I can edit it without any problem.
It is the point layer.
![proprio](https://github.com/3liz/lizmap-web-client/assets/37768582/7bb559b5-a0fd-45f3-9c9b-952f6ec417d4)
It also has a primary key.
![primary](https://github.com/3liz/lizmap-web-client/assets/37768582/b534716c-1f9c-4467-a2c1-39eca2a8b535)
In the plugin, I set the edition part like that:
![plugin](https://github.com/3liz/lizmap-web-client/assets/37768582/9b7efd7c-6481-40cc-b026-90cc3a8d14c5)
In the panel of LWC, I the set permission for the "admins" (and others).
![lwc_auto](https://github.com/3liz/lizmap-web-client/assets/37768582/5f1cb2fd-4f46-4b42-9883-93467ee70339)
As you can see, in the browser, the layer is here, so the .pg_service is OK. I can see the popup of the layer. But when I start the edition, the panel is loading the form with no end...
![web](https://github.com/3liz/lizmap-web-client/assets/37768582/af26b7d8-094b-44bd-a540-5083d58268d2)
I don't understand what is wrong here?!?

### Versions, safeguards, check summary etc

LWC 3.7.6
Lizmap plugin 4.3.3

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome, Safari

### Browsers version

LTR

**Comment by nboisteault** [comment]
What are the messages in the console?

**Comment by katagen** [comment]
I have no error log in the console of the LWC panel!

**Comment by nboisteault** [comment]
Now in admin => Lizmap logs?

**Comment by katagen** [comment]
Do you mean in ${APACHE_LOG_DIR}/error_lizmap.log ?
If yes, I'll have access to it only next week :-(

**Comment by nboisteault** [comment]
I mean in  https://yourwebsite/admin.php/admin/logs but it might be the same as in error_lizmap.log, I don't remember.

**Comment by katagen** [comment]
So I have no error int the panel...
![Capture d’écran 2024-03-29 à 11 40 04](https://github.com/3liz/lizmap-web-client/assets/37768582/ac85be6f-f8ec-4b09-a429-67bad8feaa71)

**Comment by nworr** [comment]
usually  "Error 500" php error aren't logged in lizmap-admin (displayed in admin panel), but in  `/<LizmapDir>/var/log/errors.log`

**Comment by katagen** [comment]
Damned... ok, I'll check it next week! But it is strange to be able to see the layer, to ask it (popup), to print it, but not being able to edit it?!?
And the layer is editable, cause in QGIS, I can without a problem, with the same user!

**Comment by katagen** [comment]
Di I need a pg_connect file??? I only use a .pg_service file...

**Comment by nworr** [comment]
Rendering the map, popup info retrieving is performed by QGIS through php but edition is performed by php only

Your pg_service file need to be available for php, can you try to copy it in `/etc/postgresql-common/`

see : https://github.com/3liz/lizmap-web-client/issues/620#issuecomment-459751585

**Comment by katagen** [comment]
OK, I don't have access to the server until next week... except on FTP, but I can't load data in this directory!
So I'll try it next week, and give you a feedback!
If I understand it correctly, I can also point my QGIS server PGSERVICEFILE env to `/etc/postgresql-common/.pg_service.conf`, so that I have only one pg_service file? Correct?
Thank you very much for your help!

**Comment by katagen** [comment]
Perfect... it works!!!

**Comment by nworr** [comment]
refs #1638
