### ISSUE TITLE
Lizmap no longer displaying projects due to QGIS Server configuration 

### ISSUE THREAD

**Issue by sgalvi** [3liz/lizmap-web-client#4339]
Almost suddenly, Lizmap has stopped displaying my projects. In the log section, the following error appears:
"2024-04-02 09:49:59 10.158.0.88 lizmapadmin It is necessary to install and configure QGIS Server version 3.22 or higher, and the Lizmap server plugin version 2.8.1 or higher. Unable to reach QGIS Server at the specified URL "https://orion.crs.ogs.it:8443/cgi-bin/qgis_mapserv.fcgi"."
![Screenshot 2024-04-02 101213](https://github.com/3liz/lizmap-web-client/assets/153731136/9f9197cf-6706-4fcf-9201-2e21ebff3db1)

This is strange because the versions should be among the most recent. So I went to check the QGIS logs where I found the following:
![image](https://github.com/3liz/lizmap-web-client/assets/153731136/1afc39e2-6e3c-437e-b13c-e96cc14ff544)

"ERROR: Opening of authentication db FAILED : unable to open database file Error opening database"
The strange thing is that I have configured a database on Lizmap, but not on QGIS.

### Versions, safeguards, check summary etc

** qgis-server 3.34.4 **
** Lizmap 3.7.0 **

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

nd

### Relevant log output

```shell
ERROR: Opening of authentication db FAILED : unable to open database file Error opening database
[Tue Apr 02 09:45:05.327661 2024] [mpm_prefork:notice] [pid 1059] AH00163: Apache/2.4.52 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/3.0.2 mod_wsgi/4.9.0 Python/3.10 configured -- resuming normal operations
[Tue Apr 02 09:45:05.327792 2024] [core:notice] [pid 1059] AH00094: Command line: '/usr/sbin/apache2'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-www-data'
QFSFileEngine::open: No file name specified
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
ERROR: Auth db directory path could not be created
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
```

**Comment by Gustry** [comment]
Did you follow the step from 1 to 7 as describe in the screenshot ?

> "ERROR: Opening of authentication db FAILED : unable to open database file Error opening database"

This is something not related to the current error, but still necessary. It's an internal DB for QGIS to store certificates. It must be writable. It's a classic error if you look on the internet.

>  ** Lizmap 3.7.0 **

Please do not install and use 3.7.0, we are already at 3.7.6...
The last number is very important, it's the number of bugfix version...  Same as in QGIS.

**Comment by sgalvi** [comment]
I installed QGIS at the beginning of the year, and it was working fine until a few days ago with version 3.7.0. The issue arose while I was installing Syncthing to sync Lizmap repositories. I suspect something may have broken, possibly during a reboot. Given that the page "https://orion.crs.ogs.it:8443/cgi-bin/qgis_mapserv.fcgi" isn't displaying anything, it could indeed be a QGIS-related problem. I will further investigate to resolve this issue. Thank you for your time and attention.
Best regards
