### ISSUE TITLE
[Question]: Define Redis-DB Username and Password

### ISSUE THREAD

**Issue by c-franz** [3liz/lizmap-web-client#4341]
### What is the question? (in English)

When using Redis-DB as Cache-System, how can i define the Username and Password for the Authentication?
In the LizMap-Web-Client configuration page there are only inputs for Host/IP and Port.

### Versions, safeguards, check summary etc

Versions: Latest LizMap-Web-Client Release

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 23.04

### Browsers

Firefox

### Browsers version

Newest version

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
