### ISSUE TITLE
[Bug]: Can't print anymore

### ISSUE THREAD

**Issue by sygfi** [3liz/lizmap-web-client#4342]
### What is the bug? (in English)

Since upgrading from LWC 3.4 to 3.7, I no longer see the print button in the LWC menu. Even on the qgis Lizmap QGIS plugin (v4.3.4), I can't find the print checkbox anymore. I'm having trouble identifying where the issue is coming from. 

### Steps to reproduce the issue

1. Configure a Composer
2. Export to server with plugin Lizmap (v4.3.4)
3. No 'Print' checkbox in Map Option tab
4. No print button in LWC

#### Edit 
**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.4
* QGIS Desktop : 3.28.14
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 4.1.0
* QGIS Server plugin DateFilterServerPlugin : version 0.1
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : not found

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Distributor ID: Debian Description:    Debian GNU/Linux 12 (bookworm) Release:        12 Codename:       bookworm

### Browsers

Firefox

### Browsers version

Firefox 121.0.1 (64 bits)

**Comment by Gustry** [comment]
For next time, please follow the ticket template with the right click step in the plugin, thanks.

Did you check your "Layout" panel in the plugin ?

**Comment by sygfi** [comment]
Double sorry 
- 1 noted, I've edited my ticket
- 2 You're right on target, my layout was disabled.

Thanks
