### ISSUE TITLE
[Bug]: Custom Edition screen is not shown

### ISSUE THREAD

**Issue by WouterVermeyenSBE** [3liz/lizmap-web-client#4349]
### What is the bug? (in English)

We run 2 webservers with lizmap 3.6.7 connected to the same QGIS 3.22 server. The problem is when we customize the Edition form in QGIS, this doesn't come through in the webinterface of one of the servers. We also experience this problem with multiple different layers. We tested this on the other server and there it is not an issue.

What could be causing this?

Both servers side by side:
![image](https://github.com/3liz/lizmap-web-client/assets/124688011/7b46cb03-e3b3-4bae-bc10-fe6c58294b45)

![image](https://github.com/3liz/lizmap-web-client/assets/124688011/1dc869df-141c-4ba9-8591-fab5105dedf2)

QGIS edition layout:
![image](https://github.com/3liz/lizmap-web-client/assets/124688011/8fc09b34-24e4-41b7-9d3f-babf270b617d)

### Steps to reproduce the issue

1. Load the map
2.  Edit a feature

### Versions, safeguards, check summary etc

Server with the issue:
**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 4.2.6
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 10 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

Server without the issue:
**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 4.2.6
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 10 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

NAME="Ubuntu" VERSION="20.04.5 LTS (Focal Fossa)"

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Firefox 124.0.2

**Comment by Gustry** [comment]
I'm not sure to fully understand the issue. Are you sure about your servers ?
The first screenshot looks like LWC 3.7.*, but you in your versions, both servers are on LWC 3.6.7

**Comment by WouterVermeyenSBE** [comment]
Yes, i am sure about the server versions.

![image](https://github.com/3liz/lizmap-web-client/assets/124688011/87ed6d75-e82e-49b9-866a-b99bd9bb4617)

**Comment by WouterVermeyenSBE** [comment]
We identified that the problem was the jelix cache that was disabled.
