### ISSUE TITLE
[Bug]: Lizmap 3.7 doesn't show QGIS Drag&Drop Form as pop up source

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#4358]
### What is the bug? (in English)

When choosing QGIS Drag&Drop Form as pop up source in Lizmap Plugin, the form is not shown but the pop up has the automatic format.

### Steps to reproduce the issue

1. Create a Drag&Drop Form for a vector layer
2. Open Lizmap Plugin and go to layer tab
3. select the vector layer 
4. choose QGIS Drag&Drop Form as pop up source
As you can see in the images below, only few fields are in the Form layout but the pop up shows all fields. Everything works in lizmap 3.6.10 and qgis server 3.28.5.

![image](https://github.com/3liz/lizmap-web-client/assets/25825472/f7fff8a2-36d5-4630-a535-365a34c971bb)
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/290b0218-582c-4a5d-b6b4-8b1d28d9eb9b)
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/5a0dd797-6f6c-46cb-859f-a9d23c74ae98)

[progetto_demo.zip](https://github.com/3liz/lizmap-web-client/files/14930907/progetto_demo.zip)

Lizmap is installed using https://github.com/3liz/lizmap-docker-compose
### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.5
* QGIS Desktop : 3.34.4
* QGIS Server : 3.34.4
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system
Ubuntu 20.04.6 LTS

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Firefox Versione 124.0.2, Chrome Versione 123.0.6312.106, Microsoft Edge Versione 123.0.2420.81

**Comment by mind84** [comment]
Hi @RobiFag,

it happens because the layer name is different from the layer `short_name` set in the QGIS Server tab in the layer properties panel.


![Screenshot_20240411_092102](https://github.com/3liz/lizmap-web-client/assets/20710470/7b7e187d-fdd1-4973-aad9-a485b2f08840)

If you change the layer short_name to `palazzi_rolli` then you should see the d&d layout in the popup. This solves also this one https://github.com/3liz/lizmap-web-client/issues/4359

@Gustry maybe it's related to this [control](https://github.com/3liz/qgis-lizmap-server-plugin/blob/7787d530a7df0ea089163e22b2c1deabf2f29527/lizmap_server/get_feature_info.py#L58)  in the `qgis-lizmap-server-plugin `?

**Comment by RobiFag** [comment]
Hi @mind84 thank you for the explanation!

I confirm that this also solve the #4359 

I didn't change the short name of the layer but I understood the problem. If there are two layers with the same name the Lizmap plugin returns a warning and automatically changes the short name of the two layers adding the "*_n" suffix

Before running the plugin
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/c0de3c63-4f86-43a3-8936-30725fe9fc82)

After running the plugin with warning
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/3d72baf1-6663-41ea-9f5f-45ea2709d8d9)

This behavior does not solve the warning about duplicate layer names and introduces other issues.

**Comment by Gustry** [comment]
Fixed https://github.com/3liz/qgis-lizmap-server-plugin/commit/ee5b2057ea36953f625cb921ae2dec149f2061b7

Thanks @mind84 for finding the source of the problem
