### ISSUE TITLE
[Bug]: Pop up is not shown in atlas container with Lizmap 3.7

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-web-client#4359]
### What is the bug? (in English)

The feature pop up is not shown in the atlas tool container even if the pop up is activated both in the lizmap plugin atlas tool options and in the layer options.

### Steps to reproduce the issue

1. Open Lizmap Plugin and go to layer tab
2. activate pop up for the choosen vector layer
3. go to atlas tab
4. add a new layer checking the "Display pop up (if activated)" option

![image](https://github.com/3liz/lizmap-web-client/assets/25825472/80828d8f-4319-4bca-8b4c-60edf8d921b4)
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/ae297158-5549-4a62-ba20-bdecb71c8e9e)
![image](https://github.com/3liz/lizmap-web-client/assets/25825472/9afaabf3-91f6-43db-899d-93b450181ee5)

[progetto_demo.zip](https://github.com/3liz/lizmap-web-client/files/14930918/progetto_demo.zip)

Lizmap is installed using https://github.com/3liz/lizmap-docker-compose

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.5
* QGIS Desktop : 3.34.4
* QGIS Server : 3.34.4
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04.6 LTS

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Firefox Versione 124.0.2, Chrome Versione 123.0.6312.106, Microsoft Edge Versione 123.0.2420.81

**Comment by Gustry** [comment]
This is a duplicated of #4358 ?

**Comment by nboisteault** [comment]
Hi @RobiFag I can't reproduce the issue at least in master with a QGIS drag'n drop popup.

**Comment by nboisteault** [comment]
@RobiFag Could you modify your `fid` from int64 to int32?

**Comment by nboisteault** [comment]
I found a bug I'll fix soon. @RobiFag The workaround is to set the same shortname than the layer name for the moment.

**Comment by RobiFag** [comment]
Hi @nboisteault sorry for the late reply but I missed the notifications. Thanks for the fix!
