### ISSUE TITLE
Baselayers no longer printed?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#436]
Following the instructions on:
https://docs.3liz.com/it/publish/advanced_lizmap_config.html#allow-printing-of-external-baselayers
I am no longer able to print a baselayer (LM304). I just added a group called `osm-mapnik` to the project, but this does not appear on the pdf.
Has something changed, or am I wrong?

**Comment by rldhont** [comment]
@pcav nothing has changed. `To overcome this lack Lizmap offers an easy way to print a group or layer instead of the external baselayer.` The group is not mandatory, you can continue to use a layer absed on an GDAL XML file http://www.gdal.org/frmt_wms.html

**Comment by pcav** [comment]
Sorry, not very clear to me: the xml file works, the `osm-mapnik` group does not. Thanks.

**Comment by rldhont** [comment]
The group has to contains layers with different name.

**Comment by pcav** [comment]
Thanks for the clarification. May I suggest to rephrase the manual then?

**Comment by rldhont** [comment]
Update, your help is welcome.
