### ISSUE TITLE
Problem with Lizmap-QGIS_server installation/configuration

### ISSUE THREAD

**Issue by ander2712** [3liz/lizmap-web-client#4360]
### What is the question? (in English)

I completed the installation of qgis server and lizmap client but something went wrong. In the "server information" panel it comes out: 
"
Unable to retrieve details about your QGIS Server installation (version, plugins, etc.).
QGIS Server returns an HTTP error for Lizmap plugin: Unknown
"

On the log instead: 
"
Unable to reach QGIS Server at the specified URL
"
does anyone know of a procedure to check whether qgis server was installed correctly?

### Versions, safeguards, check summary etc

LizMap 3.7.2
QGIS 3.22.16-Białowieża 'Białowieża' (exported)
QGIS code branchRelease 3.22
Qt version 5.15.8
Python version 3.11.1
GDAL/OGR version 3.6.2
PROJ version 9.1.1
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.40.1
OS Debian GNU/Linux 12 (bookworm)

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

DebianBased 22

### Browsers

Firefox, Chrome

### Browsers version

Opera 109 Chromium 123

**Comment by katagen** [comment]
Did you install the plugin "lizmap server" for QGIS server?

**Comment by ander2712** [comment]
> You can reach QGIS server with this address http://your-address/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities and if it works, you get the capabilities...

yes it works, see below:
https://gis.comune.calci.pi.it/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

**Comment by katagen** [comment]
Did you install the "lizmap server" plugin on QGIS server?

**Comment by Gustry** [comment]
> LizMap 3.7.2

Please install latest release of 3.7.X.
3.7.2 is not the latest release.

> In the "server information" panel it comes out:

Did you follow the checklist provided in this page ?

>  Unable to reach QGIS Server at the specified URL

Did you configure your QGIS Server URL in LWC ?

> https://gis.comune.calci.pi.it/cgi-bin/qgis_mapserv.fcgi

As stated in the documentation, keep in mind that this URL **mustn't** be accessible from outside, on the public network. Otherwise, you can bypass all Lizmap Web Clients ACL
https://docs.lizmap.com/current/en/install/pre_requirements.html#id1 the second warning

**Comment by ander2712** [comment]
> > LizMap 3.7.2
> 
> Please install latest release of 3.7.X. 3.7.2 is not the latest release.

DONE! (3.7.6)

> 
> > In the "server information" panel it comes out:
> 
> Did you follow the checklist provided in this page ?

I THINK yes

> 
> > Unable to reach QGIS Server at the specified URL
> 
> Did you configure your QGIS Server URL in LWC ?
> 
> > https://gis.comune.calci.pi.it/cgi-bin/qgis_mapserv.fcgi

What's LWC ?  ...maybe control panel of lizmap, so I think yes: in "QGIS server URL" 

> 
> As stated in the documentation, keep in mind that this URL **mustn't** be accessible from outside, on the public network. Otherwise, you can bypass all Lizmap Web Clients ACL https://docs.lizmap.com/current/en/install/pre_requirements.html#id1 the second warning

I understand but how I can check the URL status? (accessible or not)

Thank you :)
