### ISSUE TITLE
data tool (attribute table) - doesn't display info for features

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#437]
hi,

i'am using QGIS Server/Desktop 2.14.10 with LWC master version.

when i create a new project with a single PostGis vectorial layer, i can't get the information for feature using the (i) display info. this functionality shrinks the attribute table but only shows a gray area.

PS: the functionality (i) display info is only available if the "enable popup" tag is activated in the lizmap plugin.

**Comment by josemvm** [comment]
hi @rldhont 

the problem of the (i) display info area is solved after "Merge branch 'release_3_0'" commit.

if "the functionality (i) display info is only available if the "enable popup" tag is activated in the lizmap plugin" is purposely you can close this issue.

sorry for any inconvenience and thanks for your attention.

**Comment by rldhont** [comment]
Hi @josemvm ,
Thanks for your reviews.
