### ISSUE TITLE
Search by address bar on my lizmap map

### ISSUE THREAD

**Issue by soukac98** [3liz/lizmap-web-client#4372]
### What is the question? (in English)

How to add a tool/search bar into lizmap, so that the user can search by address?

### Versions, safeguards, check summary etc

https://github.com/3liz/lizmap-web-client/releases/tag/3.7.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

windows 10 professionnel

### Browsers

Chrome

### Browsers version

Chrome

**Comment by guenterw** [comment]
this setting in the QGIS Lizmap plugin
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/77ecebca-1c11-4dbe-be10-dde8b00da6cf)

leads to the search field at the top right
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/9fe27cfb-a503-4d3b-812b-1926324b45f6)
(the terms have been changed to German)

**Comment by soukac98** [comment]
> this setting in the QGIS Lizmap plugin ![image](https://private-user-images.githubusercontent.com/8373176/323294260-77ecebca-1c11-4dbe-be10-dde8b00da6cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTA4NTksIm5iZiI6MTcxMzc5MDU1OSwicGF0aCI6Ii84MzczMTc2LzMyMzI5NDI2MC03N2VjZWJjYS0xYzExLTRkYmUtYmUxMC1kZGU4YjAwZGE2Y2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTI1NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTYzZTI3YTcyNTBkMzdlZmQ2MGI1ZTI5MTFhNWVhZGU2MTUxMTYzNGRhZGIxYTM1ZjQzNjcxNzlmMTNhZmZkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oRhA-AVgr0lxkz0s4CWMXa78i89owNetRoEPALfI2Zw)
> 
> leads to the search field at the top right ![image](https://private-user-images.githubusercontent.com/8373176/323295968-9fe27cfb-a503-4d3b-812b-1926324b45f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTA4NTksIm5iZiI6MTcxMzc5MDU1OSwicGF0aCI6Ii84MzczMTc2LzMyMzI5NTk2OC05ZmUyN2NmYi1hNTAzLTRkM2ItODEyYi0xOTI2MzI0YjQ1ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTI1NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ2YzE3NTE2YjdjYjA1ODQyYTVkZmNlYzQ1ZTliZTc4ZjM3ZjhmZDg3N2ZiYmIxNTVmZjJhOGMzNjU0NWY1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mPUuJVt0kh7asn3KohGHJ5drm1AKWrtZD055qeelK1M) (the terms have been changed to German)

It doesn't seem to work for me : I tried it before, using a precise address , It shows no data...

**Comment by Gustry** [comment]
@soukac98 And what does it return on osm.org website ? It's the same endpoint, nominatim.

Then you can do F12 in Lizmap Web Client to see returned data from https://nominatim.openstreetmap.org/ui/search.html website

**Comment by soukac98** [comment]
> @soukac98 And what does it return on osm.org website ? It's the same endpoint, nominatim.
> 
> Then you can do F12 in Lizmap Web Client to see returned data from https://nominatim.openstreetmap.org/ui/search.html website

this is what it returns : 
![image](https://github.com/3liz/lizmap-web-client/assets/164033950/d5efa3bb-21b1-4aa6-b2d7-f9a5af8c07fe)

However, the address is recognizable on osm's website, if that's what you meant

**Comment by Gustry** [comment]
Please use F12 to open the developer toolbox in your webbrowser to see the request in the backend.

Lizmap Web Client is filtering the data according to your "allowed map extent" for your project etc (or visible extent) (can you pan on Paris ?)

**Comment by soukac98** [comment]
> Please use F12 to open the developer toolbox in your webbrowser to see the request in the backend.
> 
> Lizmap Web Client is filtering the data according to your "allowed map extent" for your project etc (or visible extent) (can you pan on Paris ?)

![image](https://github.com/3liz/lizmap-web-client/assets/164033950/04b20e0d-ad32-41e9-b798-45cb7e0002b8)

the only error i could catch up is the title of the refresh button next to my search bar..

**Comment by Gustry** [comment]
Then, you have a "Network" tab, you should see requests to the Nominatim server.

**Comment by soukac98** [comment]
> Then, you have a "Network" tab, you should see requests to the Nominatim server.

I did, but i am still lost on what the problem really is, I am not very familiar with it..
I saw a similar issue here on GItHub #1548 , still not working

**Comment by Gustry** [comment]
1. Go in your network tab
2. Empty it, with the trash icon
3. Start typing in the search bar, press enter
4. Check the nominatim request which has been sent, and you can see the result of the request. You can copy/paste the query

**Comment by soukac98** [comment]
> 1. Go in your network tab
> 2. Empty it, with the trash icon
> 3. Start typing in the search bar, press enter
> 4. Check the nominatim request which has been sent, and you can see the result of the request. You can copy/paste the query

Hello again, i am now familiar with the console and the network tab, thanks to you :D  so i added a new json script to media files, that adds a search bar, but it doesn't show any adress in my map : i added markers to the script but it either blocks the entire map loading or it doesn't seem to recognize the marker (undefined), here is my script , maybe you can point me into the right direction

// Fonction pour effectuer la recherche Nominatim
function searchNominatim(query) {
    return fetch("https://nominatim.openstreetmap.org/search?format=json&q=" + encodeURIComponent(query))
        .then(response => response.json())
        .then(data => {
            return data; // Renvoie tous les résultats trouvés
            
        });
}

lizMap.events.on({
    'uicreated': function(evt) {
        // Création de la barre de recherche en HTML
        var html = '<form id="form"><label>Adresse: <input type="text" id="barre-recherche"/></label><br /><br /><button type="submit" id="submit-btn">Rechercher</button></form><p id="log"></p>';
        $('#map-content').append(html); // Ajout du code HTML
        $('#form') // Style
            .css('position', 'absolute')
            .css('top', '30px')
            .css('z-index', '1000')
            .css('margin-left', 'calc(50% - 80px)'); // Centré en prenant en compte la barre latérale

        $('#submit-btn')
            .css('display', 'block')
            .css('margin', '-30px auto 0');

        // Ajout d'un event listener pour la recherche
        $('#form').submit(function(e) {
            e.preventDefault(); // Empêche l'envoi du formulaire

            var inputValue = $('#barre-recherche').val(); // Récupération de la valeur de la barre de recherche

            // Recherche dans Nominatim
            searchNominatim(inputValue)
                .then(result => {
                    if (result && result.length > 0) {
            // Création d'une liste pour afficher les adresses trouvées
            var listeAdresses = '<ul>';

            // Pour chaque résultat trouvé
            result.forEach(result => {
                // Création d'un marqueur pour l'emplacement trouvé et l'ajouter à la carte
                var marqueur = L.marker([result.lat, result.lon]).addTo(map);
                marqueur.bindPopup('<p>' + result.display_name + '</p>').openPopup();

                // Ajout de l'adresse à la liste
                listeAdresses += '<li>' + result.display_name + '</li>';
            });

            // Fermeture de la liste
            listeAdresses += '</ul>';

            // Affichage de la liste des adresses à côté de la carte
            $('#liste-adresses').html(listeAdresses);
                    } else {
                        console.log('Aucun résultat trouvé pour :', inputValue);
                    }
                })
                .catch(error => {
                    console.error('Erreur lors de la recherche Nominatim :', error);
                });
        });

      

 
    }
});

**Comment by Gustry** [comment]
Sorry, I won't debug your script myself. Please follow the instruction in my previous message, there is already a native search tool with Nominatim, we would be nice to understand first why it doesn't fit your need. I know there is a some extent restriction for instance, when sending the nominatim request.

**Comment by arno974** [comment]
1. you do not need to create your own search bar as it is provided by default in Lizmap. My advice will be to pass some time reading the documentation instead of creating a custom js script
2. I don't know where did you find this script but it is for Leaflet. Lizmap uses OpenLayers. It will not works.

**Comment by MaxiReb** [comment]
Hi, i have the same problem as soukac98 and to continue the discussion, in the network tab, the nominatim request that is returned by my project Lizmap is ok and gives a good answer (i changed the name of my domain but this request sends a json file) :
`https://mylizmap/osm/nominatim?repository=epfl2023v2&project=20240412_projet_lizmap&query=place%20du%20capitole%20toulouse&bbox=1.348681%2C43.545515%2C1.432578%2C43.606323`

For information, the search by address is working fine on others of my projects...

**Comment by guenterw** [comment]
I don't understand why the existing search with “Nominatim (OSM)” should not work. I have many different Lizmap versions in use and it works everywhere.

But I have an idea:
Could it be that addresses are being searched that are outside the coordinate range defined for the QGIS server? In this case, the search doesn't actually work for me either, but I think that's ok.

In the example above, the search was for Paris but the section shows an area in Germany
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/97ae8cd6-a448-4ade-91ed-824b8da44ce2)

if the coordinate range is large enough, the address will be found by me:
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/b7d25271-080b-49bf-81e6-aaadd7de0f9f)
https://cx21.webgis.biz/ Project Test
(Background map OpenStreetMap, scale 1:2500)

**Comment by arno974** [comment]
From my understanding Lizmap (see [lizmap code](https://github.com/3liz/lizmap-web-client/blob/c0a1a75f7cb6f090324395c17a19b9dccd5d5734/lizmap/modules/lizmap/controllers/osm.classic.php#L40)) get the current project BBOX and search only inside this bounding box.

In the message @guenterw   from we can see that this parameter is specified in the URL :

`https://mylizmap/osm/nominatim?repository=epfl2023v2&project=20240412_projet_lizmap&query=place%20du%20capitole%20toulouse&bbox=1.348681%2C43.545515%2C1.432578%2C43.606323`

**Comment by soukac98** [comment]
> It was indeed the bbox of my QGIS project which was too restricted... It works now, thanks for your help !



> It was indeed the bbox of my QGIS project which was too restricted... It works now, thanks for your help !

I modified the extent of my curent project, but it still doesn't work. I also tried searching inside and outside the bbox , but the "no results" still persists. Maybe I am missing something?

**Comment by Gustry** [comment]
The tip about the project extent was mentioned earlier. It's indeed taken into account to determine if a result can be shown to the user.

>  Maybe I am missing something?

Please, as describe, use the "Network tab" of your web-browser, when you enter an OSM address, you will be able to see if you got at least one response from the server etc.

**Comment by soukac98** [comment]
> The tip about the project extent was mentioned earlier. It's indeed taken into account to determine if a result can be shown to the user.
> 
> > Maybe I am missing something?
> 
> Please, as describe, use the "Network tab" of your web-browser, when you enter an OSM address, you will be able to see if you got at least one response from the server etc.

Yes, that is exactly what I verify, no response from the server

**Comment by Gustry** [comment]
Can you share the HTTP request and the response, as already described before https://github.com/3liz/lizmap-web-client/issues/4372#issuecomment-2084760880

**Comment by soukac98** [comment]
![image](https://github.com/3liz/lizmap-web-client/assets/164033950/5d803ee6-8fcc-4daa-b810-c30edb76cf2a)

**Comment by Gustry** [comment]
Please share your HTTP request parameters which has been sent, your HTTP code, the status of the request etc.
There is something wrong indeed, but we won't be able to help you with a screenshot. For us, it seems Nominatim is working fine.
You right click on the request, and copy as curl for instance
