### ISSUE TITLE
Layer group not automatically active despite corresponding setting (group as Layer)

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4382]
### What is the bug? (in English)

Layergroups that are grouped in a layer (group as layer) are not automatically displayed as active, even if this is defined as such.
This affects version 3.7.6 and 3.8.0 Alpha.2
no QGIS themes were used
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/456e696b-8b18-4755-8fff-47cf75b4d7c6)

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/01780b4b-baf0-456e-88ad-8b84679a8689)
(https://cx21-7.webgis.biz)
In version 3.6 (https://cx21-6.webgis.biz/) it works (it is always the same project, only the version has been adjusted in the plugin)

### Steps to reproduce the issue

see What is the bug?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.7
* QGIS Desktop : 3.34.6
* QGIS Server : 3.34.6
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : no
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu 22.04

### Browsers

Chrome

### Browsers version

Chrome 124.0.6367.79

**Comment by guenterw** [comment]
The error also exists in version 3.7.7-pre.7428 from 13/05/2024, regardless of whether the QGIS themes are used or not.
In version 3.6.12, the error only exists when using the QGIS themes.

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/da2d4c0c-9bb5-4329-892a-07e6ebf2df76)

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/fbd20882-4446-493f-bd3f-fa9ae687efa6)

see also https://reute3-7.webgis.biz/

**Comment by nboisteault** [comment]
If you check `Toggled` on at least one of the layers in the group, it should work.

**Comment by guenterw** [comment]
You mean a layer must be activated?
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/f34c306d-3169-465f-be2c-c7e5b055f501)

Unfortunately, this does not work. It does not work either with or without QGIS themes.
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/19457b27-b768-4c0e-9b1a-23a4d8c6550f)

See "ALKIS aus DB mit Lizmap 3.7.x" in https://cx21-7.webgis.biz

There is also a problem with the legend for grouped layers, see https://github.com/3liz/lizmap-web-client/issues/4431.
Should I leave issue 4431 open or close it? The example projects given there are based on the three current versions.

PS: I will send Etienne another ALKIS data project by e-mail in the next few days

**Comment by guenterw** [comment]
It's a shame that it's probably a bigger problem.

When switching to 3.7, I now have to dissolve all grouped layergroups and thus have almost 300 layers in the project.

**Comment by guenterw** [comment]
#4593 was to be understood as a hint that the error is also present in 3.8 RC 2.

The consideration of this error is very time-consuming for me. In order to be able to use an extensive grouped layergroup, I now provide this myself as a WMS service. I have to change the many "small" grouped layergroups accordingly.
And I don't know if it's worth the work or if I should wait for the bug to be fixed.
Would a financial contribution to fix the bug help?

**Comment by meyerlor** [comment]
I struggle with the same consideration - this is the major point which keeps me from updating to 3.7 or 3.8. I would happily chip in some money as well, if this helps a speedy resolve of the issue

**Comment by guenterw** [comment]
Thank you very much for the fast processing.

Without using the QGIS themes, the activated display of the grouped layergroup now works.
Unfortunately not yet with the use of the QGIS themes.

I have tested it in the current 3.7.10-pre.7591 and in 3.8.0-rc.3.
https://cx21-7.webgis.biz/index.php/view/map?repository=alkis&project=OpenData_ALKIS_3_34#7.626925,48.109454,7.734527,48.146055
https://cx21-8.webgis.biz/index.php/view/map?repository=alkis&project=Test_Herbolzheim8
(I can also send you the example project)

For me personally, the consistent use of the QGIS themes is the main reason to switch to the newer versions 3.7 / 3.8.
At the moment, unfortunately, there is still no improvement for me.

How should I proceed, open a new issue or reopen this one (if possible?)

**Comment by rldhont** [comment]
Hi @guenterw, you describe an other issue. I have fix the first describe at the top.

**Comment by guenterw** [comment]
ok, is there anything else i can do? Perhaps a reference to my comment above at #4232

Or can you foresee when the problem will also be solved for the QGIS themes (as described, this is currently a lot of work for me) when I update projects.

**Comment by rldhont** [comment]
@guenterw here is the fix for groupAsLayer https://github.com/3liz/lizmap-web-client/pull/4622 checked in theme.

**Comment by guenterw** [comment]
@rldhont Thank you very much!
It works in the current 3.7.10pre and also in 3.8. RC 3. 
For me it was a bit annoying that I had to deactivate the grouped layergroups in quite a few projects, but overall I am happy that with version 3.7.10 we will have a Lizmap client that fully supports the QGIS themes.
Many thanks for your work.
