### ISSUE TITLE
If layer has a "custom" CRS then does not show in Lizmap

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#44]
Sometimes it happens that a layer created in QGIS may be given a a CRS that is not exactly recognized by QGIS itself, and then added as "custom CRS".

In such cases the layers with such CRS are not shown in LM (raster shows as white rectangle, vectors are not shown at all).

**Comment by abarobopec** [comment]
Hi @mdouchin, I Encounter the same problem. I have some layers projected with a custom CRS, and QGIS Server can't serve them.

I don't really understand your answers. You said this is a QGISServer bug. But does this bug is solved if www-data user can access to /.qgis2 folder for writting ?
