### ISSUE TITLE
Update to LWC 3.0.5 problem with cyclemap layer

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#440]
I have updated to LWC 3.0.5 but I have problem with osm-cyclemap base layer.

Firebug give me the following error: 

a.tile.opencyclemap.org uses an invalid security certificate.

The certificate is only valid for the following names:
  ssl5.thunderforest.com, thunderforest.com, tile.thunderforest.com, *.tile.thunderforest.com, tile.hosted.thunderforest.com, *.tile.hosted.thunderforest.com  

Error code: SSL_ERROR_BAD_CERT_DOMAIN

I partially solved it using http instead of https in the cyclemap url of the map.js file...

line 5881

> var cyclemap = new OpenLayers.Layer.OSM('osm-cyclemap',
>             ["http://a.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png",
>             "http://b.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png",
>             "http://c.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png"]
>             ,options
>             );

**Comment by josemvm** [comment]
hi @rmarzocchi84 

i confirm this problem but not the solution...

**Comment by rmarzocchi84** [comment]
Probably it is only a temporary solution...I will try different solutions

**Comment by rldhont** [comment]
Hi @josemvm and @rmarzocchi84 it is not a lizmap issue.

OpenCycleMap needs an api key to be used in an  other site. So we needs to update the plugin and web client to have the ability to specify an api key.

You'll find more information here:
* http://www.opencyclemap.org/about/
* http://thunderforest.com/

**Comment by gerald2545** [comment]
really interested in this feature....I will have a look

**Comment by gerald2545** [comment]
quick answer to test
in LWC > mapj.js, replace
   
var cyclemap = new OpenLayers.Layer.OSM('osm-cyclemap',
            ["https://a.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png",
            "https://b.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png",
            "https://c.tile.opencyclemap.org/cycle/${z}/${x}/${y}.png"]
            ,options
            );
with
var cyclemap = new OpenLayers.Layer.OSM('osm-cyclemap','https://tile.thunderforest.com/cycle/${z}/${x}/${y}.png?apikey=YOUR_API_KEY',options);   

tested on my instance > OK

**Comment by gerald2545** [comment]
interested in a pull request?
nobody else is working on it?

**Comment by rldhont** [comment]
Fixed by #934 with mannually cherry-pick to release_3_2
