### ISSUE TITLE
[bug] layer information - opacity

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#441]
hi,

when you try to get information about some layer or base layer, the opcaity icon turns on and if you click on the icon a list of opacity values appears...

![bm_info](https://cloud.githubusercontent.com/assets/10053874/21499038/29f5732a-cc2a-11e6-88b2-06c862b8bbac.jpg)

**Comment by josemvm** [comment]
on mobile devices the panel tool overlaps part of the main tool bar and the selections don't work properly

**Comment by rldhont** [comment]
Hi @josemvm, is it the lizmap web client master version ?

**Comment by josemvm** [comment]
hi @rldhont 

yes, it's the master version

**Comment by rldhont** [comment]
@josemvm do you think the icon is not necessary ?
@mdouchin what do you thin about this issue ?

**Comment by josemvm** [comment]
in my humble opinion it' s no longer necessary

**Comment by josemvm** [comment]
the zoom tool it's also redundant...

**Comment by josemvm** [comment]
however, the zoom tool continues to work but the opacity tool doesn't (if one of the values in the list is chosen nothing happens)

alternatively, you can rehabilitate the tool and keep it
