### ISSUE TITLE
[Bug]: Minidock popup not working in Lizmap Web Client : 3.7.7, 3.8.0-alpha.2

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#4418]
### What is the bug? (in English)

After this commit https://github.com/3liz/lizmap-web-client/commit/fb13baed270b171163a111928054cd496d1017e6 minidock popup not returning data for clicked object. 

popup in dock 
![dock](https://github.com/3liz/lizmap-web-client/assets/1684359/aa84d505-4444-4418-a554-057dcab87243)

popup in minidock
![Minidock](https://github.com/3liz/lizmap-web-client/assets/1684359/89ba86ea-7e46-43bd-8cbe-70490e70cf9c)

### Steps to reproduce the issue

1. Set popup location to minidock in Lizmap plugin.
2. Go to LWC and click on object on map. 
3.  Popup will not return data.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.7-pre, 3.8.0-alpha.2
* Lizmap plugin : 4.3.11
* QGIS Desktop : 3.34.6
* QGIS Server : 3.34.6
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.9.0
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20

### Browsers

Microsoft Edge

### Browsers version

124.0.2478.80

**Comment by ygorigor** [comment]
@mind84 can you check this issue?

**Comment by mind84** [comment]
Hi @ygorigor,
do you have a link to access the project?

**Comment by ygorigor** [comment]
Hi @mind84. 
I switched back to 3.7.6, but you can test any project.  This issue is present on all my projects, even on projects from test directory.

**Comment by ygorigor** [comment]
@nboisteault on LWC 3.7.8-pre I get an error when I click on minidock close button `lizMap.mainLizmap.map.clearHighlightFeatures is not a function`

**Comment by nboisteault** [comment]
@ygorigor I can reproduce. I'll fix it. Thanks.

**Comment by nboisteault** [comment]
Fixed!
