### ISSUE TITLE
Change the title name / Changer le nom du titre de page

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#444]
Hi,

I would change on the registration page the title "LizMap" by "Registration" And the name of the tab.
Can you help me.

Thanks you.
_______________________________________
Bonjour,

J'aimerais pouvoir changer sur la page d'inscription le titre "LizMap" par "Inscription" ainsi que le nom de l'onglet. Pouvez vous m'aider.

Merci.

**Comment by rldhont** [comment]
I tagged it as a bug because, it means that we do not correctly set the template.

**Comment by rldhont** [comment]
Fixed by 61960e541bb3af9260d5fde0e6d4de1de157d4a3

The page create account has a title based on `Registration` locale and the application name defined in the back office.
