### ISSUE TITLE
Dataviz: scatterplot traces are not coloured according to values in attribute table

### ISSUE THREAD

**Issue by InnovPlantProtect** [3liz/lizmap-web-client#4444]
### What is the bug? (in English)

I have a table with meteo data from several stations. Variables are daily min, avg and max temp and relative humidity. Data start from Jan 2024. I am trying to use dataviz to plot in a single scatter plot the avg temp of each station. To do so i set colour = station_name. However, dataviz shows only 1 station.  
In plotly express the code will be something lilke
fig = px.line(df, x='date', y='temp_med_C', color='station_name')
where df is my meteo_data table

### Steps to reproduce the issue

1.in QGIS import meteo_data from postgresql and ensure that in the qgis server project property the layer has WFS checked
2.in QGIS open lizmap plugin and in dataviz choose scatter plot, then date as x axis and temp_med as y axis. Define colour = station_name
![dataviz_scatterplot](https://github.com/3liz/lizmap-web-client/assets/73950278/d18eb761-bb1e-4459-ba5e-595a6f2ee414)
3. publish the project and check the results, which unfortunately are not what expected as a single line is plotted instead of the 4 (stations)
4. 
![dataviz_published](https://github.com/3liz/lizmap-web-client/assets/73950278/d721dcc6-4ff9-4e93-91de-fdce708abfce)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.9
* Lizmap plugin : 4.3.1
* QGIS Desktop : 3.34.6
* QGIS Server : 3.34.5
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22

### Browsers

Firefox, Chrome

### Browsers version

recent

**Comment by nboisteault** [comment]
Hi @InnovPlantProtect ,
Can you show us what result you wish?

**Comment by InnovPlantProtect** [comment]
@nboisteault  please find below what i get from running a python code i wrote. the graph is obtained with plotly
![meteo_stations_prr](https://github.com/3liz/lizmap-web-client/assets/73950278/b4655ea9-87c5-4c02-90df-f80fa48608c9)

**Comment by InnovPlantProtect** [comment]
@nboisteault  the colours i had in the graphs take the station_name variable. In python i manage, in lizmap i did not.

**Comment by InnovPlantProtect** [comment]
@nboisteault and @mdouchin  i have found a work around which allows me to do what i needed. I am sharing it FYI and for everyone else having a similar situation. I opted to relate my table to a vector file and use this one as source of data. Then i selected the same type scatter plot (see above figure) with date in the x variable and meteo parameters as y variables (e.g. min, agv and max temperature). I keep on using the variable station names as colour legend. Then, i enable the filter function and use the filter to have the graph for each station. In this way, by selecting the station i have its related graph. 
One question: the filter works only if the table is from a table with geometry. If i have a simple table (with no geom) the filter does not work. Is this an unexpected behaviour? If so, it would be great to enable the filter also for ordinary tables and not imply that all data in the webGIS are necessarily with geom. Thanks!
