### ISSUE TITLE
Attribute table empty when printing some Postgis table or view

### ISSUE THREAD

**Issue by Arnaudkoch** [3liz/lizmap-web-client#445]
Hi, 

When trying to integrate attribute tables for non geometric postgis table or view in a composer, the table prints well in Qgis but not in the web client. Do you have any idea of the source of the problem?

Cheers,

**Comment by rldhont** [comment]
Lizmap have to add no spatial layers to the getPrint request to have it in the tables.

**Comment by rldhont** [comment]
Fixed in d7a1e10
