### ISSUE TITLE
[Question]: Service unavailable after installing lizmap web client

### ISSUE THREAD

**Issue by dhatudmk** [3liz/lizmap-web-client#4454]
Service Unavailable when installing lizmap

I just installed the lizmap web client but the page that appears is service unavailable. I have tried different versions but the result is the same. Can you please explain how to solve it?
http://31.220.58.138/lizmap/

Sorry, I'm very unfamiliar with Ubuntu and Apache web servers

### Versions, safeguards, check summary etc

-

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu 22.04

### Browsers

Chrome

### Browsers version

Chrome

**Comment by arno974** [comment]
Hi,

It is difficult to give you an answer with so much little information. It could be related to many different causes (your installation, your configuration, etc.) You should check your Apache logs. You will probably find what causes this error.

**Comment by Gustry** [comment]
Indeed, without more information from you and some system administrator skills, it's not possible to help you.
You can try to use docker https://github.com/3liz/lizmap-docker-compose if it can temporary help.

You can post again with more debug.
