### ISSUE TITLE
The current version of jquery.dataTables.min.js give some errors

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#446]
I update the version of /lizmap/www/js/jquery.dataTables.min.js with the [actual version](https://datatables.net/download/download) and I solve some strange behnaviour with the data tables in LWC 3.0.5 

Perhaps this can be useful for further version of LWC

**Comment by mdouchin** [comment]
thanks for your feedback !

**Comment by rldhont** [comment]
Fixed in 937b4dc9f5f606747f777a08c686fa5adf9d98a1
