### ISSUE TITLE
[Bug]: Popup In mini dock  can't be closed

### ISSUE THREAD

**Issue by nworr** [3liz/lizmap-web-client#4463]
### What is the bug? (in English)

When using a popup in minidock , the close icon doesn't work
and js exception is thrown
` lizMap.mainLizmap.map.clearHighlightFeatures is not a function` 

### Steps to reproduce the issue

1 create a popup info
2 set the popup in minidock 
3 try to close the popup

### Versions, safeguards, check summary etc

lizmap 3.7.8-pre

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

whatever

### Browsers

Firefox

### Browsers version

relevant ?

### Relevant log output

```shell
Uncaught TypeError: lizMap.mainLizmap.map.clearHighlightFeatures is not a function
    init map.js:2419
    jQuery 8
    W map.js:4042
    jQuery 10
    W map.js:4040
    init map.js:2413
    init map.js:1867
```

**Comment by rldhont** [comment]
Has been fixed by https://github.com/3liz/lizmap-web-client/commit/b499388bbca7732a1e0eea619d71e4f15fb2f325
