### ISSUE TITLE
lizmap server - using custom port/url - troubles with links to the media directory

### ISSUE THREAD

**Issue by naoM** [3liz/lizmap-web-client#448]
Hi,

I have a lizmap server that works fine. The project is accessible on port 8001 (the url looks like: http://myserver:8001/lizmap/www/index.php/view/map/)

However there is one problem setting the links to the media directory: the link to the media content which is automatically generated by lizmap does not includes the ":8001" part of the url

Example:
generated url is http:///myserver/lizmap/www/index.php/view/media/getMedia?repository=myrepository&project=myproject&path=media%2Fitworks.png

while the correct link would be http:///myserver:8001/lizmap/www/index.php/view/media/getMedia?repository=myrepository&project=myproject&path=media%2Fitworks.png

I went through the lizmap configuration files, changed the basePath as proposed in mainConfig.ini.php, but with no success.

**Comment by rldhont** [comment]
Fixed in 1c9a5f6
