### ISSUE TITLE
Working with rasters

### ISSUE THREAD

**Issue by mibalas** [3liz/lizmap-web-client#449]
Hello, I'm researching which is the best raster format to use in an application in LWC, I'm currently using geotiff, but some of my raster are very heavy and take a long time to load.

I tested the ECW format, which is quite light, but LWC does not load, is there any way to load ECW files in LWD?

I also tried importing the raster to postgis database (raster2pgsql), but LWC also does not load, is there any way to load postgis rasters into LWD?

Is there a raster format that you indicate?

Thank you for your help

**Comment by gioman** [comment]
@mibalas for ecw you will need the support in gdal also on the server, which can be both a technical and a licensing problem.

Just create overviews for your tiffs and you'll be able to publish also very large rasters even without using LM tiling.

**Comment by rldhont** [comment]
We recommand to use GeoTIFF with pyramids.
If the rasters are heavy, you can use jpeg compression in GeoTIFF http://erouault.blogspot.fr/2014/04/advanced-jpeg-in-tiff-uses-in-gdal.html
If the rasters are heavy, you can cut in tiles and use a VRT with pyramids.

If you thinks these information has to be added to the documentation https://github.com/3liz/lizmap-documentation please do it.

**Comment by tudorbarascu** [comment]
Also, you might want to take a look at http://blog.cleverelephant.ca/2015/02/geotiff-compression-for-dummies.html as it has a very nice compression tip.

**Comment by mibalas** [comment]
OK, I will try to improve the compression of my rasters.

thank you for your help!
