### ISSUE TITLE
Loading Join Tables from CSV or database connection in LWC

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#450]
I can't load join tables configured in the QGIS Desktop project from CSV tables or Oracle Connection in Lizmap. When i open the attribute table in Lizmap, it only show the native shapefile data.
Is there any way or possible improvement to solve this issue?

**Comment by gioman** [comment]
Hi @jhcardoso just tested on a shapefile + CSV on LM3 and it works as expected here.

**Comment by rldhont** [comment]
@jhcardoso it's a QGIS Server issue. You probably have to update it.

**Comment by gioman** [comment]
@jhcardoso @rldhont  I tested on qgis server 2.18.2 on Ubuntu. There it works as expected.

**Comment by jonnyforestGIS** [comment]
@gioman , @rldhont and @jhcardoso  in Windows SO is working as well. Regards

**Comment by jhcardoso** [comment]
Ok, now i have tried with csv and it works fine but with oracle tables it continues not displaying...
Have you tried with oracle tables?

**Comment by rldhont** [comment]
@jhcardoso do you have QGIS Server with oracle support ?

**Comment by jhcardoso** [comment]
Hi, maybe not... what is the best procedure to install QGIS Server with oracle support (linux)?

Many Thanks
