### ISSUE TITLE
Define active baselayer via QGIS themes

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4501]
The use of QGIS themes has been working perfectly in Lizmap since version 3.7 and is ingenious.

But often the background map (e.g. colored or black/white) should also change with the selected layers.

However, the active background map cannot yet be controlled via the QGIS themes.
Is this a bug or a new wish/extension?

**Comment by josemvm** [comment]
hi @guenterw 

> The use of QGIS themes has been working perfectly in Lizmap since version 3.7 and is ingenious.

can you try to use more than 2 themes and check if it works fine for you?

thanks

**Comment by guenterw** [comment]
Thank you very much!
That works perfectly. 
See https://cx21-8.webgis.biz/index.php project "Test BürgerGIS 3.8.0 rc.1" / "Test WebGIS-Projekt Bauleitplanung..."
Theme "Standard" / "B-Pläne Übersicht" with grey background map, theme "ALKIS Auskunft" with colored background map

Is there any hope that it will also be included in 3.7? That would be great!

**Comment by nboisteault** [comment]
@guenterw it has been backported to 3.7 so you'll have this feature in Lizmap 3.7.9. Thanks for testing.

**Comment by guenterw** [comment]
Thanks for implementing. I had once again looked in the wrong directory (release instead of unstable) and thought there was no 3.7.9-pre yet.
Works great, tested under https://cx21-7.webgis.biz
