### ISSUE TITLE
Aliases for titles / names of projects

### ISSUE THREAD

**Issue by Claire-stc** [3liz/lizmap-web-client#4503]
**Problem**

The name appearing on top of the UI of the web client is exactly the name of the QGIS project, which may be constrained by naming conventions not allowing for names that are clear and easy to understand for the users of the web client.

**Possible solution**

It would be very helpful to be able to add an alias to the project's name, a clear name that could be shown on the UI of the web client instead of the original name of the QGIS project.

**Comment by Gustry** [comment]
Are you talking about the "title" in the project properties ? 
https://docs.lizmap.com/current/en/publish/configuration/project.html#services-capabilities

**Comment by Claire-stc** [comment]
Possibly ?
I am talking of the element shown below.

We would like to keep our projects name conform to our naming convention (with codes and "_") and change the title that appears on the interface.

![image](https://github.com/3liz/lizmap-web-client/assets/171925300/0b4f4464-259a-4217-af5d-273a2e31ac12)

**Comment by Gustry** [comment]
So yes, it's already possible, as you can see in the screenshot.
Of course, no names in a web client should have a `_` etc, and they can be customized.
Update your title in the project properties, QGIS Server tab as written in the link above.

**Comment by Claire-stc** [comment]
The image shows the exact same name for the QGIS project and the project's name shown on the interface. We need to be able to have two different titles.

**Comment by Claire-stc** [comment]
Ah, found it, thanks!
I am guessing this is where the elements need to be changed?

![image](https://github.com/3liz/lizmap-web-client/assets/171925300/3adde9d1-3867-452d-8ead-be3e6325d219)
