### ISSUE TITLE
[Bug]: 3.8.0-rc.1 base layer (i) information - stop working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4506]
### What is the bug? (in English)

the information about base layer stop working on 3.8.0-rc.1

### Steps to reproduce the issue

clicking on the (i) information about base layer nothing appens

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0-rc.1
* Lizmap plugin : 4.3.14
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

126.0.1

**Comment by guenterw** [comment]
I can confirm that.
But it is displayed correctly at the bottom right:
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/54b44d0d-8067-4efb-849b-d31c6e323d5c)

Test project: https://cx21-8.webgis.biz/index.php project "Test BürgerGIS 3.8.0 rc.1" / "Test WebGIS-Projekt Bauleitplanung..."

**Comment by Gustry** [comment]
I can confirm the issue as well

![image](https://github.com/3liz/lizmap-web-client/assets/1609292/25349734-55ff-4dce-b9b4-cafeeec520eb)


Note, the tooltip goes under the map

**Comment by josemvm** [comment]
hi @Gustry any news about this issue?
the problem is not specifically about the the layer information but mainly about the possibility to set some transparency for the base layer

thanks

**Comment by Gustry** [comment]
Nothing since my last message

**Comment by josemvm** [comment]
@nboisteault maybe a css issue?

**Comment by josemvm** [comment]
@nboisteault thank you very much for this fix!
