### ISSUE TITLE
[Bug]: the Print tool brings up dynamic dialogue boxes

### ISSUE THREAD

**Issue by cocro** [3liz/lizmap-web-client#4512]
### What is the bug? (in English)

Bonjour,
My work context: Qgis 3.28.15 / Lizmap 3.6.15 project
A layout with two dynamic fields:
```
date [%format_date(now(), 'dd/MM/yyyy')%]
basemap: Basemap: [%array_to_string(map_credits('MAP'))%]
```
is visible in the online project dialog box.
For what ? How to deactivate this because modifying it has no impact in the generation of the map

### Steps to reproduce the issue

My work context: Qgis 3.28.15 / Lizmap 3.6.15 project

date [%format_date(now(), 'dd/MM/yyyy')%]
fond de carte : Fond de plan : [%array_to_string(map_credits('CARTE'))%]

### Versions, safeguards, check summary etc

    LWC 3.6.13
    QGIS Server 3.28.15

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10

### Browsers

Firefox

### Browsers version

Firefox 126

### Relevant log output

```shell
Thanks for
```

**Comment by Gustry** [comment]
> is visible in the online project dialog box.

What do you mean ? Please drag&drop a picture, the issue is not clear.
Please follow the ticket template as well about the step in the plugin.
