### ISSUE TITLE
[Question]: User automatically logged of

### ISSUE THREAD

**Issue by meyerlor** [3liz/lizmap-web-client#4515]
### What is the question? (in English)

I observed that after some time of inactivity in Lizmap you get logged off - this is a bit annoying, especially if you are a new user and do not know about this behaviour - you can still zoom and pan the map, but nothing will load (so my customer concluded that Lizmap is slow..). You have reload the page, log in again and then you can work again in Lizmap. Can this behaviour be disabled somehow?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.7
* Lizmap plugin : 4.3.15
* QGIS Desktop : 3.34.7
* QGIS Server : 3.34.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.9.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Microsoft Edge

### Browsers version

Firefox 115

**Comment by guenterw** [comment]
in my experience it depends on the setting of the general duration of the user session (Apache /php). I have set this to 12 hours.
However, the security aspect should be taken into account.


Irrespective of this, it would certainly make sense if the Lizmap web client were to give the user a corresponding message when they are logged out.

**Comment by gioman** [comment]
> Irrespective of this, it would certainly make sense if the Lizmap web client were to give the user a corresponding message when they are logged out.

Or add an option in the admin backend to set the length of the session.

**Comment by Gustry** [comment]
> Or add an option in the admin backend to set the length of the session.

It's linked to the PHP server, not Lizmap if I'm correct.
I think to the variable `session.gc_maxlifetime`, which is by default 24 minutes. (1440 seconds)

**Comment by gioman** [comment]
> It's linked to the PHP server, not Lizmap if I'm correct.
> I think to the variable `session.gc_maxlifetime`, which is by default 24 minutes. (1440 seconds

@Gustrybut I think that is possible to override it at the application level

```
<?php
// Set the session lifetime to 1 hour (3600 seconds)
ini_set('session.gc_maxlifetime', 3600);

// Set the session cookie lifetime to 1 hour (3600 seconds)
ini_set('session.cookie_lifetime', 3600);

// Start the session
session_start();

// Your session handling code here
?
```

**Comment by Gustry** [comment]
Ok, I didn't know

**Comment by meyerlor** [comment]
Uhm, will it be implemented in LWC as a setting admins can edit? Or do i need to set it on all my LWC servers manually?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
