### ISSUE TITLE
Is it possible to change highlighting color ?

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#4520]
### What is the question? (in English)

Hello,

Is it possible to change highlighting color ? By some javascript or css file ? Maybe the answer is in #748, but if so I don't understand how to do. If someone can help ? Thank you !

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.3.0
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 8

### Browsers

Chrome

### Browsers version

Version 125.0.6422.142

**Comment by Gustry** [comment]
No indeed, it is still not possible.
The ticket #478 requires some funding to be done if you are interested, feel free to contact us.

I'm closing this ticket in favor of the other one.
