### ISSUE TITLE
[Bug]: GetPrintAtlas does not work if id of feature is not a number 

### ISSUE THREAD

**Issue by maxencelaurent** [3liz/lizmap-web-client#4534]
### What is the bug? (in English)

Generating an atlas (`GetPrintAltas`)  from a popup works fine if id of features is numeric.

Nonetheless, it doesn't work if the ID is of another type, especially uuid, which is pretty common when using postgis layers.

In https://github.com/3liz/lizmap-web-client/blob/283ec7cad7b9dd58d7ebf2cad2aa72027782a952/assets/src/components/FeatureToolbar.js#L648

The id should be escaped in some way.
```
 EXP_FILTER: `$id IN (${   typeof this._fid === 'string'  `'${this._fid.replace("'", "''")}' ` ? : this._fid    } )`, 
```
Not sure if the "$id **IN** (...)" syntax suggests `this._fig` may be a list of id (eg '1, 2, 3, 4' or [1, 2, 3, 4]) ?

It seems there is also some assumptions the ID is always numeric in the atlasprint plugin too.

### Steps to reproduce the issue

1. In qgis desktop, add a postgis layer which contains a geom and an UUID pkey
2. in qgis project properties / qgisserver / WFS, make sure to publish the layer
3. Create a layout
 2. toggle `generate an atlas` which cover this layer
4. In lizmap plugin:
 1.  make sure to check the popup checkbox for this layer
5. Publish the project in LWC
6. Click on any feature of the layer
7. Click on the `print` icon

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.8
* Lizmap plugin : 4.3.4
* QGIS Desktop : 3.34.4
* QGIS Server : 3.34.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04

### Browsers

Firefox

### Browsers version

Not relevant but Firefox 127

### Relevant log output

```shell
## HTTP 400 response:

"ATLAS - Error from the user while generating the PDF: Expression is invalid: \nsyntax error, unexpected NAME, expecting COMMA or ')'\nsyntax error, unexpected NAME, expecting end of file\nsyntax error, unexpected NAME, expecting end of file\nsyntax error, unexpected NAME, expecting end of file\nsyntax error, unexpected ')', expecting end of file"
```

## Server logs 
```
Qgis: AtlasPrint: Atlas print request error 400: ATLAS - Error from the user while generating the PDF: Expression is invalid:
syntax error, unexpected NAME, expecting COMMA or ')'
syntax error, unexpected NAME, expecting end of file
syntax error, unexpected NAME, expecting end of file
syntax error, unexpected NAME, expecting end of file
syntax error, unexpected ')', expecting end of file
```
```

**Comment by Gustry** [comment]
> Lizmap plugin : 4.3.4

Can you upgrade your plugin ?

> Nonetheless, it doesn't work if the ID is of another type, especially uuid, which is pretty common when using postgis layers.

I agree, but you are hitting a few issues on QGIS Server when PK is not integers. We do not recommend using strings as PK, it's written in the plugin when the CFG file is saved, you have some "important" rules in your table, please read the description of this error in the last column, in the tooltip.

**Comment by maxencelaurent** [comment]
My plugin is now up-to-date:

**Versions :**

* Lizmap Web Client : 3.7.8
* Lizmap plugin : 4.3.16
* QGIS Desktop : 3.34.7
* QGIS Server : 3.34.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br />

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

---

There is no "important" warning in the `checks` panel.
I guess it's because my PK is of type `text` and the plugin only warns about `int8` and `varchar` PKs.

Here are the corresponding rules in the `help about checks` tab:
* `Invalid varchar field for QGIS Server as primary key`
* `Invalid bigint (integer8) field for QGIS Server as primary key`.

(by the way, `help about checks` table is editable: [Screencast from 2024-06-20 12-31-06.webm](https://github.com/3liz/lizmap-web-client/assets/6583528/9aa1a8de-42d2-412c-80b8-2f8dabedfc00))

The description field reads 
> Primary key should be an integer.
> If not fixed, expect layer to have some issues with some tools in Lizmap Web Client: zoom to feature, filtering…

I do not experience any zoom-to-feature issue, neither from the data table nor the feature pop-up. 
On the other hand, filtering is, indeed, not working.  Quoting string IDs when crafting the `cFilter`  in `attributeTable.js` should fix this issue without breaking current behaviour.

https://github.com/3liz/lizmap-web-client/blob/283ec7cad7b9dd58d7ebf2cad2aa72027782a952/assets/src/legacy/attributeTable.js#L2797


Anyway, using integer PKs is not an option for us. 

You mentioned QGIS server has some known issues with non-int PKs. I did not find much documentation about that. 
Do you have any idea where the problems are? I could take some time to investigate this.

**Comment by Gustry** [comment]
Thanks for your detailed bug report.

>  Quoting string IDs when crafting the cFilter in attributeTable.js should fix this issue without breaking current behaviour.

Can you provide a PR ?

Let me check for these fields.

**Comment by maxencelaurent** [comment]
I'll provide a PR by next days.

Is there any reason `format` and `DPI` options are disabled in the desktop plugin ?  PNG/JPEG exports seem to work fine.
![image](https://github.com/3liz/lizmap-web-client/assets/6583528/48da8bc3-2e89-4a38-872e-534ababb78e7)

**Comment by Gustry** [comment]
> Is there any reason format and DPI options are disabled in the desktop plugin ?

Legacy because there isn't any menu to let the user choose the format when you print an atlas. So the solution would be to allow a single format to be checked for atlas ?

**Comment by maxencelaurent** [comment]
A complete solution would be to display a drop-down menu if many available formats are selected.
The current  html generation  (in FeatureToolbar.js) would require a refactor to implement this. Especially to handle the dynamic field edition.

I will not address this issue in my PR.  In a first step, I would simply rely on the `default_format` setting.
