### ISSUE TITLE
[Bug]: default_background_color as default base layer not working  on qgis server 3.34

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4543]
### What is the bug? (in English)

it's not possible to set background color as default base layer
the default base layer is the first base layer after the background color base layer (GoogleSatellite in this case)
![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/da128076-f8dd-4003-913f-92bcf93ef333)

### Steps to reproduce the issue

try to set the background color as default base layer

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.9-pre.7523
* Lizmap plugin : 4.3.16
* QGIS Desktop : 3.34.7
* QGIS Server : 3.34.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

127.0.1

**Comment by Gustry** [comment]
It will be fixed when #4367 will be merged, that's why this PR is blocked.
Did you regenerate your CFG file recently (last week with latest version of the plugin ?) you should have a key in the CFG `default_background_color_index`, right ?

**Comment by josemvm** [comment]
> Did you regenerate your CFG file recently (last week with latest version of the plugin ?) you should have a key in the CFG default_background_color_index, right ?

@Gustry yes of course

**Comment by Gustry** [comment]
You mean you have the key `default_background_color_index`, what is its value ?

**Comment by josemvm** [comment]
in this case: `"default_background_color_index": 0
`

**Comment by Gustry** [comment]
It should be fixed with #4514, let's close and reopen if necessary.
