### ISSUE TITLE
Raster Legend  aspect and behaviour 3.6.13 vs 3.7.8

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#4546]
Using image as legend in 3.6.13 for a raster layer gives rise to a group with the ability to deactive and hide the layer legend from TOC, that allowed the legend to be hidden like in screencast

[Video del 25-06-2024 11:43:19.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/60e0f8ab-b56f-4a62-9a42-0daec952a4bb)

In 3.7.8 the management of the legend with use of image has changed so the display is as in the following screencast, with evident disproportion between image and title in addition to the lack of group layer-like management

[Video del 25-06-2024 11:44:31.webm](https://github.com/3liz/lizmap-web-client/assets/12639444/1547895f-a282-4b49-9c97-4c4d19cb2676)

all settings are the same for project in two LWC versions because of the same directory and the same optional js actived 

### Steps to reproduce the issue

1. configure a raster layer legend with image as legend from legend settings in qgis;
2.  save .cfg via LWC plugin;
3. open the project in LWC 3.6.13 and 3.7.8

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.13
* Lizmap plugin : 4.3.16
* QGIS Desktop : 3.38.0
* QGIS Server : 3.38.0
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 10 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

126.0.6478.126

**Comment by Antoviscomi** [comment]
In addition I share the follow screenshots to allow yourself to compare the two versions

LWC 3.6.13

![Schermata del 2024-06-25 12-00-47](https://github.com/3liz/lizmap-web-client/assets/12639444/f73a9d41-2a59-4c68-be3f-480a6137f678)

LWC 3.7.8

![Schermata del 2024-06-25 11-59-53](https://github.com/3liz/lizmap-web-client/assets/12639444/4f425b78-f0c0-4695-9928-3fa92ca6a6d3)

**Comment by Antoviscomi** [comment]
aggiungo inoltre che ho modificato il mio map.css according to @nboisteault fix Update map.css #4539, but even reinserting the controls on the layer_tree the result does not change

**Comment by guenterw** [comment]
Are they grouped layergroups (both automatic translations are not entirely clear)?

I already noticed the problem with the legend display, especially with grouped layergroups, in 3.7.x (see #4431 and #4382).
Another problem with grouped layergroups is that they cannot yet be controlled (active or not) via the QGIS themes. This is a bigger problem than I first thought, as I have grouped quite a few layers. 
I hope that the behaviour of the grouped layergroups will be revised in 3.7.x.

**Comment by Antoviscomi** [comment]
> Are they grouped layergroups (both automatic translations are not entirely clear)?

@guenterw the raster in previous isn't a member of Layergroup but simply a raster in a project. 





> I already noticed the problem with the legend display, especially with grouped layergroups, in 3.7.x (see #4431 and #4382).
> Another problem with grouped layergroups is that they cannot yet be controlled (active or not) via the QGIS themes. This is a bigger problem than I first thought, as I have grouped quite a few layers.
> I hope that the behaviour of the grouped layergroups will be revised in 3.7.x.

This seems another issue I've take part to the discussion #4431 and #4382

In this case the issue concern to the management of raster legend with a custom image in
