### ISSUE TITLE
[Question]: Display of exported table

### ISSUE THREAD

**Issue by Mavialle** [3liz/lizmap-web-client#4547]
### What is the question? (in English)

When export button is used, is it possible to export data with alias in field name, and not real field name ? And is it possible to change column order (same column order than attribute table display) ?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.3.0
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.15
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 8

### Browsers

Chrome

### Browsers version

Version 125.0.6422.142

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
