### ISSUE TITLE
[bug] (graphical) selection tool (mobile devices)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#455]
on mobile devices the selections by the selection tool don't work properly.
it's only possible to draw the shape...

![select](https://cloud.githubusercontent.com/assets/10053874/21800812/284f3752-d717-11e6-9504-6944805cbb28.jpg)

**Comment by rldhont** [comment]
I have tested with a tactil screen and only the polygon tool doesn't work.

**Comment by josemvm** [comment]
can you try with a small device?

**Comment by rldhont** [comment]
with firefox mobile screen

**Comment by josemvm** [comment]
yes  @rldhont
i updated the firefox and it works, except with the polygon
the same environment with puffin browser

**Comment by josemvm** [comment]
the polygon tool works!
start with a simple click, next click, next click, ..., and end with double click
the problem arises when you click on a feature that has an enabled popup...

it would be necessary to disable the popup tool when using the polygon for slection...

**Comment by nboisteault** [comment]
Fixed by https://github.com/3liz/lizmap-web-client/commit/9abdf0bf67ecdbb656a4fa4320a61cf2dbecefa3
