### ISSUE TITLE
to uniform colors

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#456]
change print button  background color to blue (like geolocation buttons), if you agree...

![geolocation](https://cloud.githubusercontent.com/assets/10053874/21803124/8d91bd98-d720-11e6-8d30-ee1e7ffd9dcd.jpg)

![print](https://cloud.githubusercontent.com/assets/10053874/21803129/91870e94-d720-11e6-907b-ed21b6195e17.jpg)

**Comment by rldhont** [comment]
thanks for your review
