### ISSUE TITLE
[Bug]: popups don't work on diagrams

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#4568]
### What is the bug? (in English)

When a layer contains diagrams, the popups don't appear and the browser console displays this message: "RangeError: Maximum call stack size exceeded".

![Capture d'écran 2024-07-03 120816](https://github.com/3liz/lizmap-web-client/assets/6794348/33373e0a-59b8-46ec-aa2e-c3b303584bec)

### Steps to reproduce the issue

1. Add diagrams on a points layer
2. Click on a point

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.8
* Lizmap plugin : 4.3.18
* QGIS Desktop : 3.26.3
* QGIS Server : 3.26.3
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

Chrome 126

### Relevant log output

```shell
Symbology.js:310 

Uncaught RangeError: Maximum call stack size exceeded
    at get parentRule (Symbology.js:310:9)
    at get legendOn (Symbology.js:289:18)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
    at get legendOn (Symbology.js:292:29)
```

**Comment by Gustry** [comment]
I don't think it's linked to the diagrams but the symbology. We got the issue on another project.

Are you using the rule based renderer ?
Can you check your rule based items ? Labels and description ? (remove the description and/or reduce it)

**Comment by loic74** [comment]
OK. I did a lot of tests. It seems that you can't have a diagram and more than one rule (or pictogram) in the rule based renderer. With a single rule, the popup works normally. Without diagrams, popus works even with several rules in the rule based renderer.

**Comment by nboisteault** [comment]
@loic74 can you check that you don't have any newline character in the label and description of your legends?

**Comment by loic74** [comment]
@nboisteault No newline character in the label nor description.
