### ISSUE TITLE
Add a search history tab lizmap

### ISSUE THREAD

**Issue by soukac98** [3liz/lizmap-web-client#4569]
### What is the question? (in English)

I came accross a very interesting lizmap project : carte.borbonica.re 

I wonder how the search history tab has been created ?

![image](https://github.com/3liz/lizmap-web-client/assets/164033950/e63d550b-3d3b-4cb3-a646-a928bc10b947)

### Versions, safeguards, check summary etc

https://github.com/3liz/lizmap-web-client/releases/tag/3.7.6

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

windows 10

### Browsers

Chrome, Microsoft Edge

### Browsers version

90

**Comment by Gustry** [comment]
The **history** panel on [Borbonica](https://carte.borbonica.re/index.php/occtax) is issued from the [Naturaliz module](https://github.com/3liz/lizmap-naturaliz-module). It's related to the species search history.

**Comment by soukac98** [comment]
> The **history** panel on [Borbonica](https://carte.borbonica.re/index.php/occtax) is issued from the [Naturaliz module](https://github.com/3liz/lizmap-naturaliz-module). It's related to the species search history.

Thank you for the response, it's helpful!

**Comment by soukac98** [comment]
HI again, Is it normal to have this error while adding the module to the appropriate folder? 
![image](https://github.com/3liz/lizmap-web-client/assets/164033950/d6de1d23-70bb-47ca-a21f-14c728fd9f28)

**Comment by soukac98** [comment]
> HI again, Is it normal to have this error while adding the module to the appropriate folder? I tried the latest version too but I have the same issue ![image](https://private-user-images.githubusercontent.com/164033950/347810521-d6de1d23-70bb-47ca-a21f-14c728fd9f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODI5MjcsIm5iZiI6MTcyNDY4MjYyNywicGF0aCI6Ii8xNjQwMzM5NTAvMzQ3ODEwNTIxLWQ2ZGUxZDIzLTcwYmItNDdjYS1hMjFmLTE0YzcyOGZkOWYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNDMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWRhN2JmNzg3NjJiNzdmODVlM2FkNjc2MmUzNDAyZDc0NTdkMzM5OWNkM2EwY2E2YzM0YzU3ODM5NTU1NGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.relfTlCcA5Brf_K1fZJEXoR9A3V7btpfu7Bb8fsIPmw)

I still have the same issue :/

**Comment by nworr** [comment]
The naturaliz module is a module for the lizmap web client, not a qgis plugin, it should be installed on the web server (with composer for example, see the [install doc](https://github.com/3liz/lizmap-naturaliz-module/blob/master/doc/INSTALL.md))

**Comment by Gustry** [comment]
@soukac98 

On the link I gave before, there is a section "Installation", which is explaining how to get Naturaliz on Lizmap Web Client. As my colleague said, it's not a QGIS plugin.

But this module is complex to install IMHO. Are you working with [OccTax](https://inpn.mnhn.fr/telechargement/standard-occurrence-taxon) ? If not and if you are only looking for the "history tab" you saw, installing the module will not really help you ;-)

**Comment by soukac98** [comment]
> @soukac98
> 
> On the link I gave before, there is a section "Installation", which is explaining how to get Naturaliz on Lizmap Web Client. As my colleague said, it's not a QGIS plugin.
> 
> But this module is complex to install IMHO. Are you working with [OccTax](https://inpn.mnhn.fr/telechargement/standard-occurrence-taxon) ? If not and if you are only looking for the "history tab" you saw, installing the module will not really help you ;-)

Hello, thank you again for taking the time to reply. Actually, your response now clarifies things. My client is interested in having a similar "observations research tab" (similar to the one in Borbonica), which i guess can be achieved simply by modifying the attributes form in QGIS/drag&drop?

As for the history tab, I am not sure how to have it, but as you confirmed, the module is complex to install just to have this one functionality .

**Comment by Gustry** [comment]
> As for the history tab, I am not sure how to have it, but as you confirmed, the module is complex to install just to have this one functionality .

The "history tab" has been developed to work **with** this module only, for this context. It was funded by a few customers using this Lizmap module. It would be nice to have a similar feature in Lizmap Web Client core indeed, feel free to contact us.

> My client is interested in having a similar "observations research tab" (similar to the one in Borbonica), which i guess can be achieved simply by modifying the attributes form in QGIS/drag&drop?

No, a QGIS drag and drop form is for "editing" a vector layer, this is not what you are looking for. You are looking for form filtering, like this [native tool](https://docs.lizmap.com/current/en/publish/lizmap_plugin/form_filtering.html), or [modified on this example](https://demo2.lizmap.com/lizmap/index.php/view/map?repository=cd48&project=poi) or also [this example](https://lizmap.legrandnarbonne.com/index.php/view/map?repository=public&project=circuit_court) (hopefully, this URL be back online soon, it's a 500 on this server right now)

**Comment by soukac98** [comment]
> > As for the history tab, I am not sure how to have it, but as you confirmed, the module is complex to install just to have this one functionality .
> 
> The "history tab" has been developed to work **with** this module only, for this context. It was funded by a few customers using this Lizmap module. It would be nice to have a similar feature in Lizmap Web Client core indeed, feel free to contact us.
> 
> > My client is interested in having a similar "observations research tab" (similar to the one in Borbonica), which i guess can be achieved simply by modifying the attributes form in QGIS/drag&drop?
> 
> No, a QGIS drag and drop form is for "editing" a vector layer, this is not what you are looking for. You are looking for form filtering, like this [native tool](https://docs.lizmap.com/current/en/publish/lizmap_plugin/form_filtering.html), or [modified on this example](https://demo2.lizmap.com/lizmap/index.php/view/map?repository=cd48&project=poi) or also [this example](https://lizmap.legrandnarbonne.com/index.php/view/map?repository=public&project=circuit_court) (hopefully, this URL be back online soon, it's a 500 on this server right now)

Thanks a lot, that's really helpful, i'll try the form filtering examples .
As for the history tab, i'll get back to you with a feature request.
