### ISSUE TITLE
Aggregate functions don't work when printing

### ISSUE THREAD

**Issue by Arnaudkoch** [3liz/lizmap-web-client#458]
Hi, 

Aggregate functions don't work when printing via LWC, the PDF shows the expression instead : 

![image](https://cloud.githubusercontent.com/assets/13987270/21854461/232750e8-d81b-11e6-8877-17cc58227c50.png)

**Comment by rldhont** [comment]
Which QGIS Server version ?

**Comment by Arnaudkoch** [comment]
it's the one running on your demo server

**Comment by rldhont** [comment]
It's QGIS Server 2.14 so I dont think aggregate function is supported.

**Comment by Arnaudkoch** [comment]
ok, thanks, I'll check with the last version of Qgis server.
