### ISSUE TITLE
[Question]: rounded boxes - polygon layers

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4585]
### What is the question? (in English)

how can i get rounded boxes for polygon layers?

![imagem](https://github.com/3liz/lizmap-web-client/assets/10053874/dd09961f-2037-47e6-a473-3303206aa550)

thanks

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.9
* Lizmap plugin : 4.3.19
* QGIS Desktop : 3.34.7
* QGIS Server : 3.34.8
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

127.0.1

**Comment by gioman** [comment]
> how can i get rounded boxes for polygon layers?

@josemvm  when the group is marked as mutually exclusive in QGIS.

**Comment by Gustry** [comment]
You can download the demo project to see as well, the ZIP is provided.

Feel free to improve the documentation : https://docs.lizmap.com/current/en/publish/configuration/legend.html#groups

**Comment by josemvm** [comment]
> @josemvm when the group is marked as mutually exclusive in QGIS.

@gioman thanks (grazie e salute!)

> Feel free to improve the documentation : https://docs.lizmap.com/current/en/publish/configuration/legend.html#groups

@Gustry ok, i will do it

**Comment by gioman** [comment]
> @gioman thanks (grazie e salute!)

@josemvm de nada! :)
