### ISSUE TITLE
[Question]: How to customize the popup title without changing the layer name

### ISSUE THREAD

**Issue by mariemgeo** [3liz/lizmap-web-client#4604]
### What is the question? (in English)

Hello,

In my project, nearly all the layers are queryable via popups, and these layers overlap. Therefore, multiple popups are displayed when clicking on the map.

I would like to change the way the layer name is displayed in the popup to highlight the layer name and create a separation between the popups.

I tried to include HTML tags in the layer title in the layer settings of the Lizmap plugin. It works, and the layer title appears in bold and red in my popup, but the raw tags show up in the name of my layer in the Lizmap layer manager.

lizmap layer setting
![image](https://github.com/user-attachments/assets/7166ca86-3cce-4ddb-94d5-0a9ea8f8bcc2)

lizmap popup
![image](https://github.com/user-attachments/assets/12540972-8d41-4f42-bd6e-5001902989a8)

lizmap layer name
![image](https://github.com/user-attachments/assets/730ae004-e5d3-4d28-86b6-c6195e76ff6f)

Is there another way to configure the popup title?

Thank you in advance for your response.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.9
* Lizmap plugin : 4.3.19
* QGIS Desktop : 3.28.14
* Lizmap.com : Yes
* QGIS Server : 3.28.15
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows

### Browsers

Firefox

### Browsers version

Firefox 128.0

**Comment by nboisteault** [comment]
You should use some CSS ([doc](https://docs.lizmap.com/current/fr/publish/customization/themes.html))

```css
.lizmapPopupTitle{color:red;}
```

**Comment by mariemgeo** [comment]
Hello,

Thank you for your response.

Is it possible to place the CSS in the project's media folder, or does it need to be in the global media folder of Lizmap?
