### ISSUE TITLE
[Question]: Add .js project

### ISSUE THREAD

**Issue by Jeremyserieye** [3liz/lizmap-web-client#4628]
### What is the question? (in English)

Hello, 
I'm looking to set up this project in my lizmap server --> https://github.com/opengisch/lizmap-tool-demo?tab=readme-ov-file.

I download the projects and the different elements but cannot get the .js to work.

Do you have any ideas ?

thanks in advance

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.10-pre.7578
* Lizmap plugin : 4.3.19
* QGIS Desktop : 3.34.8
* QGIS Server : 3.34.8
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Chrome

**Comment by nboisteault** [comment]
This project is 6 years old and based on Lizmap 3.1. We now have Lizmap 3.7 which is very different. A lot have changed in its API so you'll have to update the JS.

**Comment by Gustry** [comment]
Duplicated issue, it's more appropriate on the dedicated bug tracker : https://github.com/opengisch/lizmap-tool-demo/issues/2
