### ISSUE TITLE
[Question]: condition button visibility

### ISSUE THREAD

**Issue by diaznico** [3liz/lizmap-web-client#4631]
### What is the question? (in English)

Hello! I am looking to condition the administration button so that it is visible only to users who belong to the "admins" group.
How can I achieve this?

Currently the administration section shows an empty window for users who do not belong to the administrator group, since this is not visually attractive and useful, I would like to hide the button for reading and viewing users.
![Captura de pantalla 2024-07-16 180527](https://github.com/user-attachments/assets/50026922-d05b-4f71-a540-7cd8d3873ce3)
![Captura de pantalla 2024-07-16 180540](https://github.com/user-attachments/assets/2ea3ed68-7671-4f79-a7de-90d73d8c6d1d)

What should I modify in the project's php code to ensure that the "lizmap/modules/lizmap/templates/user_menu.tpl" template receives the information from the array that contains the name of the groups to which the current user belongs?

I made several attempts in the template, something like this, but no test gave the expected results!
`
{ifuserconnected}
{if isset($userGroups) && in_array('admins', $userGroups)}
      <li class="dashboard-item"><a href="{jurl 'master_admin~default:index'}">
              <span class="icon dashboard-icon"></span> <span class="text hidden-phone">{@view~default.header.menuitem.admin.label@}</span></a>
      </li>
{/if}
`
Any help is welcome, I apologize for my level of writing in English!

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.14
* QGIS Desktop : 3.22.4
* QGIS Server : 3.22.4
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : not found

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.4

### Browsers

Chrome

### Browsers version

chrome 106

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
