### ISSUE TITLE
Regression - Add selection in GetPrint request

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#464]
It seems that the SELECTION parameter is not added to GetPrint request.

**Comment by josemvm** [comment]
this functionality was lost also in version 3_0_

**Comment by rldhont** [comment]
The lizmap issue has been fixed, now the issue is in QGIS Server.

**Comment by josemvm** [comment]
it doesn't highlight the geometry 
is it a regression in qgis server?

**Comment by rldhont** [comment]
It's a regression in QGIS Server https://github.com/qgis/QGIS/blob/master/tests/testdata/control_images/qgis_server/WMS_GetPrint_Selection/WMS_GetPrint_Selection.png

**Comment by rldhont** [comment]
To fix QGIS Server, it will need to do:
- add a Flag enum to QgsComposition, with a ShowSelection option
- Q_DECLARE_FLAGS this to a QgsComposition::Flags type
- Add a flags()/setFlags() option to composition so that server can set the ShowSelection flag
- Make QgsComposerMap::mapSettings check the associated compositions flags to determine whether the selection should be shown
- (If selection color is configurable) add a getter/setter to QgsComposition to set the selection color

**Comment by josemvm** [comment]
hi,

this regression remains...
please, can anyone confirm this?

thanks

**Comment by rldhont** [comment]
Hi @josemvm, I can't confirm it. I can print with selection.

**Comment by josemvm** [comment]
sorry @rldhont you are right :-)

**Comment by josemvm** [comment]
can someone please confirm this again!?...
lwc 3.2 and master on qgis server 2.18.28

thanks

**Comment by josemvm** [comment]
it seems to me that there is a regression here, but at this time in lizmap

**Comment by rldhont** [comment]
@josemvm it seems it is a QGIS Server regression.
I close this issue because it concerns 2.18
Can you open a new issue for 3.* ?
thanks
