### ISSUE TITLE
server tile cache - server cache

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#465]
in the case of new qgis projects and if this option is chosen for the raster layers, the LWC doesn't display the rasters map.

it's not possible to generate tiles to the cache server...

**Comment by rldhont** [comment]
Can you be more explicit ?
How can we repeat the issue ? layer type ? qgis project ? lizmap config ?
Which lizmap web client version ?

**Comment by josemvm** [comment]
i' m sorry for the lack of information
you can reproduce this issue easily

- qgis server and desktop 2.14.10, LWC master
- new qgis project with only one raster layer (tif)
- LWC plugin, **server tile cache** - **server cache**, enabled option

with this option the LWC doesn't display the rasters layer.
without this option the LWC works fine ( either in "single tile" mode or tailes mode)

**Comment by rldhont** [comment]
@josemvm Have you test with a single vector layer file as a base layer ?

**Comment by josemvm** [comment]
hi @rldhont 

now, i've just done a test with a single vector layer file as a base layer and the problem is exactly the same as the raster layers.

this message appears in qgis logs file:

[18125][11:32:21] Layer 'pdm_ord_v20170116112037678' configFile: /var/www/html/lizmap-web-client-3.1pre/lizmap/install/ma/ortos_teste_tile.qgs found in layer cache

this makes me think that it does not generate the tiles because it seems to find them already in cache but not.

**Comment by josemvm** [comment]
i'm trying to seed using the command line:

php lizmap/scripts/script.php lizmap~wmts:seeding -v -f ma ortos_teste_tile Carta_Geologica EPSG:3857 0 14

however, only the folder structure was created not the tiles:

temp/lizmap
temp/lizmap/cli
temp/lizmap/cli/cache
temp/lizmap/cli/cache/myapp
temp/lizmap/cli/cache/myapp/ma_ortos_teste_tile_WMTS_tilematrixsetlist.cache
temp/lizmap/cli/cache/myapp/ma_ortos_teste_tile_WMTS_layers.cache
temp/lizmap/cli/cache/myapp/ma_ortos_teste_tile_WMTS_hash.cache
temp/lizmap/cli/cache/qgisprojects
temp/lizmap/cli/cache/qgisprojects/jelix_cache
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html/lizmap-web-client-3.1pre
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html/lizmap-web-client-3.1pre/lizmap
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html/lizmap-web-client-3.1pre/lizmap/install
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html/lizmap-web-client-3.1pre/lizmap/install/ma
temp/lizmap/cli/cache/qgisprojects/jelix_cache/jelix_cache/var/www/html/lizmap-web-client-3.1pre/lizmap/install/ma/ortos_teste_tile.qgs.cache
temp/lizmap/cli/compiled
temp/lizmap/cli/compiled/templates
temp/lizmap/cli/compiled/templates/modules
temp/lizmap/cli/compiled/templates/modules/lizmap
temp/lizmap/cli/compiled/templates/modules/lizmap/wmts_capabilities_cmdline_t_15.php
temp/lizmap/cli/cmdline~script.ini.php.conf.php

**Comment by rldhont** [comment]
@josemvm can you test lizmap 3.0 and not master ?

**Comment by josemvm** [comment]
@rldhont,

in version 3.0 everything works fine (automatically/manually seeding)!

**Comment by rldhont** [comment]
@josemvm with this commit 89960e1fbc72ccd3ef3a4f55e4fb10b91c2e4503 ?

**Comment by josemvm** [comment]
yes, i already noticed that.

**Comment by rldhont** [comment]
I have test the master, tagged 3.1beta1, and no trouble to generate cache, be sure to test with 1bd76475cb14c3480d5db4d6c09f2b9cc6ac9e06

The default folder for image is `/tmp/repository_name/project_name/CRS/*/*/*`

**Comment by josemvm** [comment]
also works fine in version 3.1 Beta2
