### ISSUE TITLE
[Question]: Can a popup be persistent ?

### ISSUE THREAD

**Issue by k9jiang** [3liz/lizmap-web-client#4653]
### What is the question? (in English)

I'm new to lizmap and i'd like to make a popup persistent, while editing a layer. When i add a new entity in an editable table, the popup dock (which is right-dock, the editing dock is the left one) disappears.
Do you have any clue how to do this ?
Thanks.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.5.2
* Lizmap plugin : 3.18.0
* QGIS Desktop : 3.14.0
* QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

### Check Lizmap plugin

- [x] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

debian 9

### Browsers

Microsoft Edge

### Browsers version

ME version 126.0.2592.113

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
