### ISSUE TITLE
User privileges

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#467]
Hello.

An idea to improve user group privileges (and avoid anonymous user can use maps with all privileges and tools activated): choose which user group can print, measure, localize and other lizmap tools. 
It could be a good enhancement and improve Lizmap's advanced user experience!

**Comment by nboisteault** [comment]
In Lizmap 3.7, you will be able to define which group can use what layout. You can now test on master branch.
I close the issue as the topic is wide. We can imagine to have user privileges for every tool.
A solution can be to expose user groups in the `<body>` as a parameter then use wildcard selectors in CSS to hide whatever you want for groups.
