### ISSUE TITLE
[Bug]: LWC 3.8 rc3 - Administration panel : users and users groups are not displayed anymore

### ISSUE THREAD

**Issue by xavyeah39** [3liz/lizmap-web-client#4682]
### What is the bug? (in English)

After upgrade from 3.7 to 3.8 rc3, users and users-groups are not displayed anymore in permissions manager (administration panel) : 

![image](https://github.com/user-attachments/assets/678adc58-5214-4ccd-aa28-7a1a82264d19)

Instead of : 

![image](https://github.com/user-attachments/assets/935bab71-88f0-4bb3-b41e-98606b67c62e)

Error in web browser console : 

![image](https://github.com/user-attachments/assets/f4918243-4244-4711-bdbb-8c1e08fe013f)

### Steps to reproduce the issue

1. Go to : Administration >> Rights (permissions)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0-rc.3
* Lizmap plugin : 4.3.20
* QGIS Desktop : 3.34.9
* QGIS Server : 3.34.9
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 12

### Browsers

Firefox, Chrome

### Browsers version

Chromium 121, Firefox 128

**Comment by Gustry** [comment]
I do not replicate on 3.8.0-rc.4 - [e589728cc](https://github.com/3liz/lizmap-web-client/commit/e589728cc) on our test server

**Comment by laurentj** [comment]
Hi,

Did you try "shift" + reload ?

It seems jQuery is not loaded. Check the network panel of the dev tools, to see if there are some JS files that are not loaded.

**Comment by xavyeah39** [comment]
> Hi,
> 
> Did you try "shift" + reload ?
> 
> It seems jQuery is not loaded. Check the network panel of the dev tools, to see if there are some JS files that are not loaded.

Hi, @laurentj , 
Yes I tried it.
It seems that jquery is loaded correctly. I don't see any JS file that is not loaded in the dev tools network panel.

![image](https://github.com/user-attachments/assets/33e84f36-d946-4b6a-95cf-bf3cdc2db6a8)

**Comment by xavyeah39** [comment]
> I do not replicate on 3.8.0-rc.4 - [e589728cc](https://github.com/3liz/lizmap-web-client/commit/e589728cc) on our test server

Hi @Gustry !
How can I try 3.8.0-rc.4 as it's not yet released (zip) ?

**Comment by Gustry** [comment]
Not tagged commit are available on https://packages.3liz.org/pub/lizmap/unstable/3.8/

**Comment by xavyeah39** [comment]
Thanks for the link.
I just tried rc4 : install OK but same problem and error in web browser console.

Everything works fine anyway except this rights managements display for groups and users.

"Global view of the rights of all groups" is working : 

![image](https://github.com/user-attachments/assets/4e65fb17-92cb-4601-b749-ab84ca5c3acf)

NB : My profiles.ini.php file is set on postgresql db with jdb:jauth

**Comment by laurentj** [comment]
This is a strange issue that i didn't reproduced yet. I'll investigate next days...

**Comment by xavyeah39** [comment]
Thanks @laurentj !
Fell free to ask me for further environnement/conf informations if needed.
I tested and reproduced this issue with 3 different instances (with the same deployment context).

**Comment by laurentj** [comment]
@xavyeah39 hi, could you zip me the content of var/config (except profiles.ini.php, i don't want your credentials ;-)),. One zip before the migration (so the directory of your  lizmap 3.7 installation), and a second zip corresponding to the directory after the migration. Send them to ljouanneau @ 3liz.com

**Comment by xavyeah39** [comment]
Thanks @laurentj for your feedback !
I share the fix you gave me : remove everything in the `[webassets_common]` section in the `localconfig.ini.php` file (due to migration scripts of LWC and Jelix in previous version).
Already encountered in #3564

**Comment by Gustry** [comment]
Gentle ping @laurentj ?

**Comment by laurentj** [comment]
Yes it's fixed
