### ISSUE TITLE
WMTS seeding - bbox cannot start with minus "-"

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#469]
If the -bbox option starts with a minus, for example "-582308,5027511,1082913,6676973"  (France metro in EPSG:3857 ), then Jelix cannot retrieve this option value, with error:

```
value for option "-bbox" is missing
```

One solution could be to
* correct bug in Jelix, if considered as a bug, to allow an option to start with an "-"
* find a way in Lizmap to use a minus.

For the second proposal, we could tell the users to escape the minus with \ , and add this modification: https://paste.sh/_76Xx13s#PoqEzWMSfajKIP1IpeDoOZ3v
This has been tested and works well (but needs documentation if we choose to do so )

**Comment by laurentj** [comment]
I could fix that in Jelix

**Comment by laurentj** [comment]
Need I fix it in the release_3_0 branch?

**Comment by rldhont** [comment]
not needed but we will merge 3.0 in master
