### ISSUE TITLE
[Bug]: Theme configuration only applied after manual intervention

### ISSUE THREAD

**Issue by vvmruder** [3liz/lizmap-web-client#4695]
### What is the bug? (in English)

Theme settings are not loaded initially from `lizmapConfig.ini.php` but only after manual intervention via admin interface edit and save the settings without changing them.

### Steps to reproduce the issue

Freshly setting up a new instance of lizmap webclient and adding a themes configuration block into the `lizmapConfig.ini.php` like this:
```
[theme]
headerBackgroundColor="rgba(237, 19, 45, 0.9)"
additionalCss="#title{background: none;} div#headermenu li a{color: #e9e9e9;} div#headermenu li a:hover{color: #777777;} #headermenu ul.dropdown-menu {background-color: #4A4A4A;background-color: rgba(0,0,0,0.7);}"
navbarColor="rgba(237, 19, 45, 0.9)"
menuBackgroundColor="rgba(237, 19, 45, 0.9)"
dockBackgroundColor="rgba(237, 19, 45, 0.9)"
headerSubtitleColor="rgba(237, 19, 45, 0.9)"
headerTitleColor="rgba(237, 19, 45, 0.9)"
```

Shows  this values correctly in the admin interface:
![grafik](https://github.com/user-attachments/assets/818241d2-fe8b-41c0-8cec-0f44f11d0fe9)

But they are not applied somehow.

Only after clicking `edit` and then `save` without any further manipulation shows the correct colors (red in this case) then.

![grafik](https://github.com/user-attachments/assets/69e9c0fd-a407-4125-b25d-12a4ca604893)

### Versions, safeguards, check summary etc

lizmap-webclient 3.7.10 (and prior versions as far as I can tell)

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04

### Browsers

Firefox, Chrome

### Browsers version

Firefox 129, Chrome 127

**Comment by nworr** [comment]
The stored config is used to generate as css file stored in `var/lizmap-theme-config/theme.css` .

Writing on the ` lizmapConfig.ini.php ` won't regenerate the CSS file, and currently the only way is to manually edit/save the config, wich will trigger the CSS refresh.

The other solution is to edit the theme.css file, knowing it will be overwritten by ` lizmapConfig.ini.php ` modifications

**Comment by vvmruder** [comment]
Thank you @nworr. For me this is good enough for the moment. This way I can rollout the application initially with the correct layout.
