### ISSUE TITLE
edition - LWC doesn't create the geometry

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#470]
qgis server and desktop 2.14.10, LWC 3.0.8 and master

LWC creates the record in the table (PostGIS) but not the geometry.

the following message appears in the browser:

&lt;ul class=&quot;jelix-msg&quot;&gt;&lt;li class=&quot;jelix-msg-item-success&quot;&gt;Data has been saved.&lt;/li&gt;&lt;/ul&gt;

**Comment by mdouchin** [comment]
@rldhont it seems the method getWfsFields does not return the geometry field

cf https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/controllers/edition.classic.php#L405

Or we loop through the fields and add them in $this->dataFields only if the field is in $fields and in $wfsFields, cf

https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/controllers/edition.classic.php#L408

This is a serious regression and should be adressed

**Comment by mdouchin** [comment]
@rldhont this is a regression caused by b20db636693a7ad69a67a1298aa0c17da007f79c

**Comment by rldhont** [comment]
@mdouchin @josemvm Can you confirm my fix 8079564 ?

**Comment by josemvm** [comment]
yes @rldhont, solved!
