### ISSUE TITLE
[Bug]: Javascript in popups stopped working after lizmap 3.7.2

### ISSUE THREAD

**Issue by aeduard** [3liz/lizmap-web-client#4707]
### What is the bug? (in English)

I'm using some simple javascript in popups, eg. to magnify an image in the popup. With version updates between 3.7.x these scripts had stopped working. I could not catch exactly at which version of lizmap it stopped working but on 3.7.2 it still works and in 3.7.6 it is not working anymore. It is not working on 3.7.10 either. I've tried the QGIS HTML maptip and also the older Lizmap HTML options.

### Steps to reproduce the issue

1. The following simple code to test the behavior (copied on the QGIS HTML maptip popup):
```
 <h1 id="test-heading">JavaScript Test</h1>
    <p id="test-paragraph">If JavaScript is working, this text will change.</p>

    <script>
        // Display an alert box to confirm JavaScript is running
        alert("JavaScript is working!");

        // Change the content of the paragraph
        document.getElementById("test-paragraph").innerText = "JavaScript is running successfully!";
    </script>
```
2. Publish the map.
3. _Allow themes/javascript codes for this repository_ are enabled at project level at Administration/Maps management. Regular javascript add-ins are working.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.10
* Lizmap plugin : 4.3.21
* QGIS Desktop : 3.28.14
* QGIS Server : 3.34.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10

### Browsers

Firefox, Chrome

### Browsers version

Version 127.0.6533.122, Firefox 129.0.2

**Comment by aeduard** [comment]
Well, it was really useful. Should I try to move the javascript to a regular one? This is the only way around?

**Comment by nboisteault** [comment]
Yes I confirm it is the only way to make added JavaScript to work.

**Comment by Gustry** [comment]
> Well, it was really useful. 

But it was a security risk, look for XSS.
It was never documented in docs/examples because of this.

**Comment by Antoviscomi** [comment]
@Gustry @nboisteault I noticed that even `<iframe>` tag it's now sanified, but you suggest a workaround or a way to enable local dynamic documents (to works as response of click on a feature on map), or this behaviour will not available anymore?
