### ISSUE TITLE
data table after clicking a line (in the presence of pivot tables) - spinning wheel

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#472]
qgis server and desktop 2.14.10, LWC 3.0.8 and master

after select same records from pivot table (the cursor becomes a spinning wheel  (as if busy doing something ...) over all "non active" spaces.

![cursor](https://cloud.githubusercontent.com/assets/10053874/22036421/5c58ddda-dceb-11e6-8347-8b497ec48f7c.png)

**Comment by josemvm** [comment]
similar environment in the use of the other tools
it' s an "aesthetic" issue...

can you reproduce this issue?

**Comment by rldhont** [comment]
Yes we can reproduce it.

**Comment by rldhont** [comment]
I'm not really able to reprooduce.
If I move the mouse pointer the wheel disapear.

**Comment by josemvm** [comment]
try to move the mouse pointer to the areas marked in the image above ("non active" areas)

**Comment by rldhont** [comment]
It's not enough.
The spinning wheel appears after Selecting an object in the attribute table.

**Comment by josemvm** [comment]
you can try to find the similar environment on selection tool, after some selections
