### ISSUE TITLE
[Bug]: Shifted geometry during editing

### ISSUE THREAD

**Issue by MoToLux85** [3liz/lizmap-web-client#4729]
### What is the bug? (in English)

Hi,
we use a PostgreSQL-PostGIS database that can be accessed via the Lizmap web client. Our users can also create and edit the geometry (polygons, points) of the database records. 

Unfortunately, when editing, the geometry is displayed 'shifted' to the later saved geometry, as shown in the following screenshot:
![geometry_shifted](https://github.com/user-attachments/assets/85f2fd71-8bb4-4b91-9696-253fb4996085)

The 'shift' also decreases when zooming in.

The geometry is only displayed incorrectly during editing, but is saved correctly in the database.

This has not always been the case, but has recently started to happen. Maybe it's related to the recent update of the Lizmap Web Client from 3.7.8 to 3.8 or the update of the QGIS Server Lizmap Plugin to 2.10.0?

Thanks in advance for your help.

### Steps to reproduce the issue

1. Open the popup of a geometry (tested with points and polygons)
2. Click on the edit button
3. Geometry is displayed shifted in the editing mode

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0
* Lizmap plugin : 4.3.22
* QGIS Desktop : 3.34.4
* QGIS Server : 3.34.10
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.10.0
* QGIS Server plugin wfsOutputExtension : not found
* PHP Version: 8.3
* PostgreSQL / PostGIS : 16 / 3.4.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Chrome 128.0.6613.119; Firefox 128.0

**Comment by guenterw** [comment]
I can confirm this with the same configuration (Lizmap 3.8.0). 
Here is a corresponding test project (editable):
![image](https://github.com/user-attachments/assets/1c327f3c-8abc-4f68-81ab-66ac1b981130)

https://cx21-8.webgis.biz  Project: Edit_test

**Comment by nboisteault** [comment]
I think this only occurs when popups are opened in the right dock.
Can you confirm ?

**Comment by guenterw** [comment]
That's right - the display is correct for all other popup positions.
However, the right dock is also the most popular with me and my users.

**Comment by guenterw** [comment]
Many thanks for the quick response and error correction

**Comment by MoToLux85** [comment]
Many thanks for your quick answers.
