### ISSUE TITLE
LM displaying a broken image in legend

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#473]
When a layer is outside its range of visualization, the legend is not generated by QGIS server. Lizmap 3.0.7 does not consider this, and the layer results active, thus a broken image is displayed.

**Comment by rldhont** [comment]
In the montpellier project, lizmap respects the range of visualization.
Do you remove the cache in temp with `./lizmap/install/clean_vartmp.sh` ?

**Comment by pcav** [comment]
Thanks @rldhont
