### ISSUE TITLE
Get Atlas for Lizmap from QGIS Print Composer

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#475]
How can we configure an atlas configuration print layout to be used? 
Any extra server side code?

Thanks

**Comment by rldhont** [comment]
This feature will probably need a QGIS Server plugin or a new QGIS Server feature

**Comment by rldhont** [comment]
I close this issue because, the atlas is available in the popup if a plugin is installed server side. Document needs to be updated
