### ISSUE TITLE
expand and collapse icons - label text on mouseover (missing)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#476]
i don't know if this is on purpose

if not and if you agree:

- you can replace in map_switcher.tpl

&lt;button class=&quot;btn btn-mini&quot; id=&quot;layers-unfold-all&quot;&gt;&lt;i class=
&quot;icon-resize-full icon-white&quot;&gt;&lt;/i&gt;&lt;/button&gt;
&lt;button class=&quot;btn btn-mini&quot; id=&quot;layers-fold-all&quot;&gt;&lt;i class=
&quot;icon-resize-small icon-white&quot;&gt;&lt;/i&gt;&lt;/button&gt;

with:

&lt;button class=&quot;btn btn-mini&quot; id=&quot;layers-unfold-all&quot; title=&quot;{@view~map.switcher.layer.layersExpandAll.title@}&quot;&gt;&lt;i class=&quot;icon-resize-full icon-white&quot;&gt;&lt;/i&gt;&lt;/button&gt;
&lt;button class=&quot;btn btn-mini&quot; id=&quot;layers-fold-all&quot; title=&quot;{@view~map.switcher.layer.layersCollapseAll.title@}&quot;&gt;&lt;i class=&quot;icon-resize-small icon-white&quot;&gt;&lt;/i&gt;&lt;/button&gt;

- add these lines in en_US/map.UTF-8.properties:

switcher.layer.layersExpandAll.title=Expand all
switcher.layer.layersCollapseAll.title=Collapse all

or i can create a little pull request

**Comment by rldhont** [comment]
The strings can be localized.

**Comment by josemvm** [comment]
i also made some corrections, some of these according to the current spelling agreement
