### ISSUE TITLE
Zoom to feature from data table takes to wrong position (master)

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#477]
Hello
I'm testing LWC master
All features are at their place and if I click on zoom to layer extent all is Ok

If then I open data table and click on center lizmap moves to a "not so far " position
If I click on zoom to feature in data table lizmap takes me to the other side of Italy

Same project on lwc 3.0.8 version works fine both on the same local virtual machine and on the production server 

pietro

**Comment by rldhont** [comment]
Which QGIS Server ?
Which CRS for layer, QGIS Project, Lizmap Web Client ?

**Comment by pieri70** [comment]
qgis-server/stable,now 1:2.18.3+13jessie i386 [installed]

LWC git cloned (3.1beta2)

CRS 3857 both for layer and project

**Comment by rldhont** [comment]
@pieri70 what is the WFS precision specified in project OWS properties ?
