### ISSUE TITLE
[Bug]: If page is loaded thru http protocol (not https) then all user java scripts not loaded

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-web-client#4777]
### What is the bug? (in English)

If a project page is loaded thru http protocol (not https) then all user java scripts not loaded on first load. Have to refresh page once.

### Steps to reproduce the issue

1. Load a project web page using http protocol
2. All user defined java scripts are not loaded
3. Refresh webpage.
OR
1. Load a project web page using http protocol
2. Press CTRL + F5
3. All user defined java scripts are not loaded
4. Refresh webpage.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.1
* Lizmap plugin : 4.4.0
* QGIS Desktop : 3.34.11
* QGIS Server : 3.34.11
* QGIS Server plugin lizmap_server : 2.10.1
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04, Windows 11

### Browsers

Chrome, Microsoft Edge

### Browsers version

Chrome 125

**Comment by nboisteault** [comment]
@ygorigor I don't think we will fix this issue as http is an insecure protocol.

**Comment by ygorigor** [comment]
Ok @nboisteault. As workaround I added a check, if page is through http it will be reloaded one time.
