### ISSUE TITLE
[Bug]: Lizmap client: layer groups fail opening up information window

### ISSUE THREAD

**Issue by cfsgarcia** [3liz/lizmap-web-client#4779]
### What is the bug? (in English)

The problem is because it's calling `getMapLayerByName`.
Traceback below.

Fix:
assets/src/legacy/switcher-layer-actions.js
Line 152:
Call `getMapLayerOrGroupByName `instead of `getMapLayerByName`
`const currentLayerState = lizMap.mainLizmap.state.rootMapGroup.getMapLayerOrGroupByName(aName);`

### Steps to reproduce the issue

1. Publish a qGIS project with some layer groups
2. In Lizmap Web Client client click the 'icon-info-sign' button next to a layer group item to open up _Information_ tab
3. This throws an error complaining about the layer group name not being a layer and stop the _information_ tab from opening.

### Versions, safeguards, check summary etc

Lizmap Web Client 3.8.1
qGIS Server 3.34.6

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04.2 LTS

### Browsers

Chrome

### Browsers version

127.0.6533.120 (Official Build) (64-bit)

### Relevant log output

```shell
`MapLayer.js:470 Uncaught RangeError: The layer name `my_layer_group_name` is unknown!
    at MapRootState.getMapLayerByName (MapLayer.js:470:1)
    at getLayerMetadataHtml (switcher-layers-actions.js:152:1)
    at toggleMetadataSubDock (switcher-layers-actions.js:236:1)
    at Object.lizmapswitcheritemselected (switcher-layers-actions.js:584:1)
    at initialize.triggerEvent (OpenLayers.js?_r=240923092313:497:145)
    at set itemNameSelected (Treeview.js:224:1)
    at HTMLElement.eval (Treeview.js:164:60)
    at EventPart.handleEvent (lit-html.js:1336:35)`
```

**Comment by Gustry** [comment]
Thanks for debugging.
If you think it's the fix, can you provide a pull request ?

**Comment by cfsgarcia** [comment]
Do you have to add me as collaborator so I can compare and submit a pull request? 
My clone: https://github.com/cfsgarcia/lizmap-web-client

**Comment by Gustry** [comment]
No, we (3Liz) do not need to do anything for now.

You can use the "pen" on the file to edit the file and fix, straight from the GitHub website, then save, it will create a commit, and then it will ask you if you want to do a "pull request", it means to forward your commit on the main 3liz repository.

I noticed you already have the branch : https://github.com/cfsgarcia/lizmap-web-client/branches I guess you should see the "create PR button ?" Or push the button "new PR" https://github.com/cfsgarcia/lizmap-web-client/pulls
