### ISSUE TITLE
Support of relation references or groups in edition forms? 

### ISSUE THREAD

**Issue by Arnaudkoch** [3liz/lizmap-web-client#478]
Hi, is there any way, in an edition form, to filter the proposed values from a list, based on the value of another field (let's say on a column we have the name of cities, and in another column, the propositions filtered by the city). 

I've made a few tests with relations in Qgis, without results in Lizmap.

**Comment by nboisteault** [comment]
Hi,
This is the same issue opened [here](https://github.com/3liz/lizmap-web-client/issues/350)
I thought I would have time to develop this feature but I didn't.
It needs works server side to read the qgs file and client side to filter but if you know javascript you can only develop the client side part for your specific fields.

**Comment by Arnaudkoch** [comment]
ok sorry for the duplicate issue. I'll have a look at the javascript option.
