### ISSUE TITLE
Is a new Configuration on a QGIS html popup needed to make a button in LWC dock popup working again?

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-web-client#4810]
### What is the question? (in English)

Before of 3.8.x LWC versions (until 3.7.10), I was able to open a link from an html qgis popup in LWC dock (popup) configured as follow:
```
<tr>
      <th><small>Norma</small></th>
	  <td> <a onclick="window.open('[%n_link%]', 'popup','location=0,width=745,height=861,left=500,top=55');" class="btn btn-primary btn-sm"><small>Clicca per visualizzare la NORMA</small></td>
</tr>
```

where `'[%n_link%]'` is my field containing the url to open, in 3.8.1 this code doesn't works anymore, how to act to grant the needed behavior to my button in popup?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.1
* Lizmap plugin : 4.4.0
* QGIS Desktop : 3.38.3
* QGIS Server : 3.38.3
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.10.1
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 10 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome

### Browsers version

 129.0.6668.70

**Comment by Gustry** [comment]
Hi,

I think it's a duplicate to https://github.com/3liz/lizmap-web-client/issues/4707 ?

**Comment by Gustry** [comment]
@Antoviscomi As explained in the ticket #4707, it's not possible anymore to load JS from the popup code.
It's was a security issue.

In JS, you can manipulate the DOM

**Comment by Antoviscomi** [comment]
@Gustry in my configuration of QGIS html popup I never tried to load a js but simply to add a button that link to an url

**Comment by Gustry** [comment]
Sorry, I'm not sure to follow.
`window.open` is a Javascript code.
