### ISSUE TITLE
[Question]: Missing tool in 3.7.10

### ISSUE THREAD

**Issue by vvmruder** [3liz/lizmap-web-client#4820]
### What is the question? (in English)

In versions previous to 3.7 we had this tool available:
![grafik](https://github.com/user-attachments/assets/bc78a000-a88a-474b-8753-05e450ee1e05)

In Version 3.7.10 I cant see this tool. Was this removed? Or is this a matter of configuration.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.10
* Lizmap plugin : 4.3.21
* QGIS Desktop : 3.34.8
* QGIS Server : 3.34.8
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin qgisserver-invalidate-cache-master : 1.0.0
* QGIS Server plugin wfsOutputExtension : 1.8.1

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04

### Browsers

Firefox, Chrome

### Browsers version

Firefox 129, Chrome 127

**Comment by Gustry** [comment]
Did you enabled it ? Admin interface → Lizmap configuration → Show projects switcher

**Comment by vvmruder** [comment]
That was, what I was missing :) Thank you very much for pointing me to it.

**Comment by Gustry** [comment]
Thanks for the feedback ;-)
