### ISSUE TITLE
[Bug]: Represent_value expression not evaluated in maptip

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#4823]
### What is the bug? (in English)

Maptips with a value which replaces the field value with its represented value is not evaluated, using the expression :
`[%  represent_value(  "field" ) %]`

Exactly the same problem as reported here: https://github.com/qgis/QGIS/issues/30719

### Steps to reproduce the issue

1. Add any vector layer with a QGIS project
2. Configure an edit widget with Value Map (or value relation, etc.) for example for a category field
3. Add content in the Maptip tab of the Vector layer properties, with the expression represent_value("category")
4. In QGIS desktop, the maptip shows the correct value
5. Publish the QGIS project with QGIS Server, and use the GetFeatureInfo request with HTML format -> the content is wrong and contains plain text containing the word represent_value

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.8
* Lizmap plugin : 4.4.0
* QGIS Desktop : 3.26.3
* QGIS Server : 3.26.3
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Chrome

### Browsers version

Chrome 129

**Comment by Gustry** [comment]
Hi @loic74 

> Exactly the same problem as reported here: https://github.com/qgis/QGIS/issues/30719

So follow the ticket you are mentioning...
It says the ticket is closed and fixed in https://github.com/qgis/QGIS/pull/50216 

In the pull request, it's written 3.28

But you are using 

> QGIS Server : 3.26.3

**Comment by loic74** [comment]
Sorry. Rookie mistake. I thought it was 3.22.

**Comment by Gustry** [comment]
Yes, it has been in backported to 3.22 as well, because 3.22 is LTR.

QGIS 3.26 is not LTR, so no backport. You must stay on LTR versions.
