### ISSUE TITLE
[Bug]: Dificulties showing Media (images) that are uploaded using Lizmap

### ISSUE THREAD

**Issue by abodsalas** [3liz/lizmap-web-client#4826]
### What is the bug? (in English)

Good day.
First I want to congratulate the Lizmap team for developing such a great and usefull software. It's awesome.

Second, I having issues trying to display uploaded images using the /media folder described in Lizmap's documentation.
https://docs.lizmap.com/3.6/en/publish/configuration/media.html

The images are uploaded to the correct location, however they are not shown in the popup.

![image](https://github.com/user-attachments/assets/3ff13d16-c2bf-49d6-92cd-41a4f297d5b0)

I finally detectaed that although my Lizmap .env file defines the port as 80 (**LIZMAP_PORT=10.20.1.12:80)**, in the web browser, the images are liked to port 8080.
When I right clic the broken image link in the attribute popup, the link is:
http://10.20.1.12:8080/index.php/view/media/getMedia?repository=publicidad03092024&project=publicidad_03-09-2024&path=..%2Fmedia%2Fimages%2Fimage004.png

**The information of my setup is:**
**Information, Lizmap Web Client:** 
Version: 3.6.14
Date: 2024-07-04
URL in the QGIS desktop plugin: http://10.20.1.12:8080/

**Information, QGIS Server:**
Number: 3.28.13
Name: Firenze

**Information, Plugins:**
atlasprint: 3.4.1
Lizmap server: 2.9.4
wfsOutputExtension: 1.8.0

By the way, if I change in docker-compose.yml
- ${LIZMAP_PORT}:8080 to - ${LIZMAP_PORT}:80
Lizmap won't start.....

Please help. Thank you very much.

### Steps to reproduce the issue

Try to upload images using Lizmap's image folder, using a port different than 8080.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.6.14
* Lizmap plugin : 4.3.21
* QGIS Desktop : 3.28.13
* QGIS Server : 3.28.13
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04

### Browsers

Chrome

### Browsers version

Versión 129.0.6668.60

### Relevant log output

```shell
A span tag was parsed inside of a <select> which was not inserted into the document. This is not valid HTML and the behavior may be changed in future versions of chrome. <option value=​"4326" selected=​"selected">​EPSG:4326​</option>​slotUnderstand this warning
map:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

**Comment by abodsalas** [comment]
Hello Gustry.
Te currently generated URL is: http://10.20.1.12:8080/index.php/view/media/getMedia?repository=publicidad03092024&project=publicidad_03-09-2024&path=..%2Fmedia%2Fimages%2Fimage004.png

It generates a:  HTTP ERROR 404 Not Found

If I manually change it to port 80:
http://10.20.1.12:80/index.php/view/media/getMedia?repository=publicidad03092024&project=publicidad_03-09-2024&path=..%2Fmedia%2Fimages%2Fimage004.png

The image loads correctly.

The path "../media/images/image004.png" exists.

The issue is tha I have Lizmap configured to port 80, yet the image URL generated in the Lizmap popup is directed to the 8080 port.

**Comment by Gustry** [comment]
Maybe @dmarteau has an idea ?

**Comment by mdouchin** [comment]
You can use some variables in Lizmap file `lizmap/var/config/localconfig.ini.php` to force the use of the port 80.
See https://docs.lizmap.com/current/en/install/advanced_install.html

But probably Lizmap saved the original 8080 port in its temporary cached data . You could try by removing this cache 

```bash
cd YOUR_LIZMAP_DIR
lizmap/install/clean_vartmp.sh
```

**Comment by abodsalas** [comment]
### Solved !!!

Thank you very much @Gustry and @mdouchin 

In case others have the same issue, I did the following:

`docker compose down`
cd to → /lizmap-docker-compose/lizmap/var/lizmap-config/
`nano localconfig.ini.php`

under the text `; put here configuration variables that are specific to this installation` , I pasted:
`forceHTTPPort = true`

Save the file and run: `docker compose up -d`

All images are uploaded, under the ../media/images folder and show correctly in the popup.



![image](https://github.com/user-attachments/assets/778c7d9b-e7da-4d29-a482-c23f497feef4)

Thanks again,

Andrés Bodini Salas
