### ISSUE TITLE
Print : Inverted Layers / Impression : Couches inversées

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#483]
Hi,

I got a problem when using GetPrint function on LizMap.
My layers order are inverted.

I don't know if the problem came from Lizmap or Qgis-Server,

The only solution i've found is to invert the layers in the address bar and it works.

Can u help me to resolve this ?

Thanks.

_________________________________________________________________________________

Bonjour,

J'ai un problème lorsque j'utilise la fonction GetPrint depuis LizMap.
L'ordres de mes couches est inversé.

Je ne sait pas si le problème vient de Lizmap ou bien de Qgis-Server,

J'ai pour le moment trouver une solution alternative pour parer le problème, j'inverse l'ordre des couches depuis la requête dans la barre d'adresse et du coup l'ordre de mes couches est bien respectés.

Merci.

**Comment by rldhont** [comment]
Hi, it's a QGIS Server issue.

I supposed you use QGIS Server 2.18 and not QGIS Server 2.14.
I found that the two versions does not read the layers parameter in the same way.
https://github.com/qgis/QGIS/pull/4035

**Comment by gioman** [comment]
> Hi, it's a QGIS Server issue.
> 
> I supposed you use QGIS Server 2.18 and not QGIS Server 2.14.
> I found that the two versions does not read the layers parameter in the same way.

@rldhont sorry for asking, so this is still an issue in 2.18 but not 2.14 (server)?

**Comment by rldhont** [comment]
For QGIS Server 2.18 user, Lizmap 3.0 and 3.1 has been fixed for printing.
Feedback are welcomes!
