### ISSUE TITLE
[Bug]: Default values does not work in edition form when using overlay_contains

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#4830]
### What is the bug? (in English)

I have an edition form valid in QGIS where the default value of a given field is calculated with this QGIS formula:

```
concat(
array_to_string(array_distinct(array_cat(overlay_contains('t_adresse_8a01a16e_9319_4737_b06e_dbc3c0b9e51d',expression:=ad_code,limit:=-1),overlay_contains('t_adresse_a5e83ddd_a3a9_4405_ac48_64b82d9245df',expression:=ad_code,limit:=-1), overlay_contains('t_adresse_2023_f1910257_f166_45a3_8af4_8639ad110a25',expression:=ad_code,limit:=-1)))))
```

This does not work in Lizmap when client

### Steps to reproduce the issue

Make a prefilled field based on overlay_contains formulas

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.10
* Lizmap plugin : 4.4.0
* QGIS Desktop : 3.34.6
* Lizmap.com : Yes
* QGIS Server : 3.34.11
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.10.1
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Lizmap hosted

### Browsers

Chrome

### Browsers version

129.0.6668.71

**Comment by Gustry** [comment]
Can you add more context ? Is the expression evaluated as soon as you open the form in QGIS ? Or after some values in the form ? Maybe with the field `ad_code` ? Or is a static expression ?

**Comment by vlebert** [comment]
Does this help ?
It does not work on feature creation in Lizmap while it works in QGIS

![digi-studio 2024-10-02 at 14 44 05](https://github.com/user-attachments/assets/ee4a5009-f3ee-4d07-b86b-84a63c04b974)

**Comment by Gustry** [comment]
Before opening your form in Lizmap, can you open your "developer tools" F12, and see if there is an HTTP requests when you open the form ? In the "Network" tab. There is one HTTP request for the form itself and another one for expressions I think

**Comment by vlebert** [comment]
hi @Gustry 

Here is a screenshot. But I don't see any interesting information here. Would you like more detail

I think the issue is that the form pops up before geometry drawing. That mean the formula can't be evaluated.

I tried keeping the default value formula in QGIS but removing the field from the edit form, but same results

![bug lizmap form create](https://github.com/user-attachments/assets/bcfe08f1-d295-45f5-8065-47b2c5507d18)

**Comment by Gustry** [comment]
> I think the issue is that the form pops up before geometry drawing. That mean the formula can't be evaluated.

Yes, this is definetely a blocker.
In QGIS, we first click on the map, then the form opens.
In Lizmap, it's the reverse, the form opens and then we can click on the map.

So you can look at the ticket mentioned earlier #3226 it's a "metaticket" now, there a few cases of expressions to work on.
