### ISSUE TITLE
[Question]: Zoom history removed

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#4832]
### What is the question? (in English)

Hi, 

with this https://github.com/3liz/lizmap-web-client/pull/4322 the `navbar` has been refactored but the new component does not include the zoom history.

Is there any reason why this functionality has been removed? Do you plan to reintroduce it in the future?

Thanks!

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.1
* Lizmap plugin : 4.4.0
* QGIS Desktop : 3.34.3
* QGIS Server : 3.34.11
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.2-alpha
* QGIS Server plugin lizmap_server : 2.10.2-alpha
* QGIS Server plugin wfsOutputExtension : 1.8.3-alpha

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 7 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian

### Browsers

Firefox, Chrome

### Browsers version

latest

**Comment by Gustry** [comment]
The reason is on this ticket : https://github.com/3liz/lizmap-plugin/issues/573
It was due to OL9 according to @nboisteault 

@mind84 Did you find an equivalent ?

**Comment by mind84** [comment]
@Gustry 

got it, thanks for the explanation.

> Did you find an equivalent ?

Nope, it's good for now

Thanks
