### ISSUE TITLE
[Bug]: style of layers invisible in lizmap map

### ISSUE THREAD

**Issue by melanieparis** [3liz/lizmap-web-client#4834]
### What is the bug? (in English)

In lizmap canevas, i see attributes and i can zoom on entities (postgres or shapfile layers) but the geom is invisible. The legend is also not available. Baselayers (IGN) are visible.
i use french app, I tried change value of style layer "défaut" to "default" but it change nothing.
Note : when i call WMS directly in Qgis desktop, legend and style are visible.

### Steps to reproduce the issue

Go to my lizmap adress
click on view map
i see the list of layers (not legend)
geom are not visible (but attributes and zoom are available)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.1
* Lizmap plugin : 4.4.1
* QGIS Desktop : 3.34.11
* QGIS Server : 3.34.4
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.10.1
* QGIS Server plugin wfsOutputExtension : not found

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04 LTS

### Browsers

Firefox, Microsoft Edge

### Browsers version

Frirefox 131 , Edge Version 129.0.2792.65

### Relevant log output

```shell
No log is admin lizmap

Qgis server
<ServiceExceptionReport xmlns=["http://www.opengis.net/ogc"](http://www.opengis.net/ogc) version="1.3.0">
<ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services
(case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
</ServiceExceptionReport>

browser console

DOMException: Invalid encoded image data. Image.js:194:20
    load Image.js:194
```

**Comment by melanieparis** [comment]
I installed 3.8.3 pre and it works. layers styles and legend are here !

**Comment by EPFDamienFRAZZONI** [comment]
I'm on Debian 12, QGIS server 3.34.13 that works well on service spawn-FCGI (I'm not on mode Py-QGIS-Server) , Lizmap Web Client : 3.8.3, QGIS Server plugin lizmap_server : 2.11.2
All URL Lizmap (démo projects for exemple) return JSON object "service" doesn't return a JSON structure but this : <?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
</ServiceExceptionReport>

**Comment by Gustry** [comment]
> I installed 3.8.3 pre and it works. layers styles and legend are here !

Thanks for feedback @melanieparis 

I'm closing this issue.

@EPFDamienFRAZZONI Your problem is not related to this issue If I'm not wrong. Please follow steps in your administration panel, then "Sever information".
