### ISSUE TITLE
[Question]: User authentication using JWT in lizmap

### ISSUE THREAD

**Issue by diaznico** [3liz/lizmap-web-client#4837]
### What is the question? (in English)

Hello! I would like to implement a REST API in my Lizmap project. The goal of this API is to receive an array of unique identifiers, use it to filter geometries, and return the URL of a map with the filtered geometries. However, I need to add a token-based authentication system so that third parties consuming the API can access the private maps.

I'm an experienced Python professional, but I feel a bit lost with the Lizmap and PHP environment. I'm wondering how I could integrate the token authentication system into Lizmap. Is it something excessively complex for someone without much experience in this environment?

I've been looking for information on forums and discussions, but I haven't found enough material. The closest thing to what I need is this guide Lizmap GobsAPI Module : https://docs.3liz.org/lizmap-gobsapi-module/install/

Could you give me some guidance on how to proceed?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.6
* Lizmap plugin : 4.3.14
* QGIS Desktop : 3.22.4
* QGIS Server : 3.22.4
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : not found

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.4

### Browsers

Chrome

### Browsers version

chrome 106

**Comment by Gustry** [comment]
Related tickets mentioning `JWT` from a search on GitHub : #937 #3650 and #922 The ticket 3650 has only been closed because of a lack of feedback.

Maybe @laurentj has an idea ?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
