### ISSUE TITLE
Server Error ! HTTP request failed! HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#484]
Hi,
In the error.log i have this message:
`2017-01-24 11:18:12	195.244.xxx.xx	warning	2017-01-24 11:18:12	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?map=%2Fvar%2Fwww%2Flizmap%2Dweb%2Dclient%2D3%2E0%2E9%2Flizmap%2Finstall%2Fqgis%2Fmontpellier%2Eqgs&amp;request=GetCapabilities&amp;service=WFS): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
	/var/www/lizmap-web-client-3.0.9/lizmap/modules/lizmap/classes/lizmapProxy.class.php	93

2017-01-24 11:18:12	195.244.162.10	notice	2017-01-24 11:18:12	[8]	Array to string conversion	/var/www/lizmap-web-client-3.0.9/lizmap/modules/lizmap/classes/lizmapOGCRequest.class.php	86`

and in the web browser "Service non disponible", the message Server Error ! appears 3 times in the yellow notice and the project is not loading.

I use php7.0. 
The locales must be fr_FR UTF8?
My apache server is configured for https ssl

thanks for help.

**Comment by rldhont** [comment]
QGIS Server failed to server Capabilities.
You can test the url in the log and directly test your QGIS Server installation.
You have to verify the way it is configured.

**Comment by jlstanus** [comment]
looks like i'm in the same situation of this guy: https://lists.osgeo.org/pipermail//qgis-user/2016-June/036767.html

**Comment by rldhont** [comment]
Hi @jlstannud, your problem is that Apache does not find something corresponding to http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi.

You have to verify that Apache is well configured for cgi-bin. Does the cgi-bin is configured to be the folder /user/lib/cgi-bin?
And then verify if qgis server is well installed. Does the file qgis_mapserv.fcgi is in the cgi-bin fonder?
You can test it without Lizmap.

**Comment by jlstanus** [comment]
Solved it was the link to.. strange. Thank you. Lizmap map could look for the  fcgi and detect the misconfiguring thing on apache. This would be a nice feature. Thanks for help
