### ISSUE TITLE
Editing a postgresql table : Lizmap use the field list of a homonymous table

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#485]
Good morning,

I have two tables called "sites" in two different schema.
My project only use table of the "intervention_site" schema.
Lizmap run well for visualizing data but when I want to edit the "site" table, it shows me column that are not in the table I use in the project, but they're from the md.site table...

Thanks a lot for your work !

Mathieu Bossaert

**Comment by rldhont** [comment]
Verify the datasource of your project? Does the schema is specified ?

**Comment by mathieubossaert** [comment]
Yes the schema is specified in the project file : 
`<datasource>dbname='sicen' host=192.168.1.231 port=5432 user='ambre' password='ambre' sslmode=disable key='id_site' srid=2154 type=MultiPolygon table="intervention_site"."site" (geometrie) sql=</datasource>`

**Comment by rldhont** [comment]
So which lizmap version ?

**Comment by mathieubossaert** [comment]
Sorry I didn't note it. It was an geoppoy install from october.
It's ok now on version 3.0.3

**Comment by rldhont** [comment]
I'll closed the issue. Thanks
