### ISSUE TITLE
Typos in string

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#486]
property %s value is to low > property %s value is too low

same for other occurrences of `to`

**Comment by rldhont** [comment]
thanks @pcav in which files ?

**Comment by pcav** [comment]
not sure, I can't see this easily in Transifex

**Comment by rldhont** [comment]
the name in Transifex will help me

**Comment by pcav** [comment]
sorry, I miss your point. the string is `property %s value is to low`.
I must say I found easier the good old .po or .ts files.

**Comment by pcav** [comment]
got it:
Lizmap locales / jelix.pot

**Comment by josemvm** [comment]
i found in jelix.pot:

	Line 290: msgid "property %s value is to high"
	Line 291: msgstr "property %s value is to high"
	Line 295: msgid "property %s value is to low"
	Line 296: msgstr "property %s value is to low"

**Comment by rldhont** [comment]
@laurentj 2 strings to update.
