### ISSUE TITLE
Attribute Tables / Table d'attributs

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#487]
Hi,

My attribute table don't load when i got more than 3000 lines on a layer.

I found a search limit (50 000) on attributeTable.js, is there a limit for filtering ?

(Qgis Server 2.18)

Thanks.

_____________________________________________________

Bonjour,

Ma table d'attributs ne charge plus lorsque je suis à environ 3000 lignes.

J'ai aussi trouver une limite sur l'outil de recherche, existe-t-il une limite identique/différente pour le filtrage ?

Merci.

**Comment by rldhont** [comment]
It's a known issue due to the time the server to provide data. #239 #139
The request is too long.
QGIS Server has to be enhance to fixed this issue.

**Comment by rldhont** [comment]
A new feature in 3.1, will give you the ability to filter the table by map 5e736a01c2cbf739c737b8e8c1d54c41d23d4f0f

**Comment by nboisteault** [comment]
@rldhont This issue can be closed ?

**Comment by rldhont** [comment]
reopen if needed
