### ISSUE TITLE
[Question]: A question o base layers on recent LMWC versions

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4890]
### What is the question? (in English)

I admit that I got lost (and frequently confused) on some of the changes that have been introduced on LMWC since 3.7, to the point that I have chosen to stick to 3.6 until possible. Now moving on is no more an option, so I'm looking to find some answer.

Until LMWC baselayers like Google and Bing could be added using the LM plugin, and that needed an API key from those providers. But I could add basically the same imagery using the QGIS plugin QuickMapServices and **no** key was needed, because I guess that those layers from QMS are basically WMS layers and not coming from a tile server.

So why is the key now needed for that QMS layers in LMWC > 3.6?

Thanks in advance

### Versions, safeguards, check summary etc

Not relevant for the question.

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by Gustry** [comment]
Hi @gioman 

There is a good answer on this other issue : https://github.com/3liz/lizmap-web-client/issues/4749#issuecomment-2376131752

Using QuickMapServices for a Google layer, without an API key is possible, but it's not guaranteed to work.

**Comment by Gustry** [comment]
> So why is the key now needed for that QMS layers in LMWC > 3.6?

Did you get the "Check" in the Lizmap plugin about missing an API key ? There is the "How to fix" : 

![image](https://github.com/user-attachments/assets/816b3f89-19a6-4469-81a9-24a4305129e7)

**Comment by gioman** [comment]
> There is a good answer on this other issue : [#4749 (comment)](https://github.com/3liz/lizmap-web-client/issues/4749#issuecomment-2376131752)

@Gustry thanks for the pointer. So if I understand correctly the key/token is necessary because otherwise would be illegal (not using the tiled service which requires the key), correct? In QMS to be able to add layers from providers as Google users have to agree with

![image](https://github.com/user-attachments/assets/7ea4167a-65bd-4f30-9332-32868dbc1234)

which I guess is their way to say "use them at your own responsibility".



> Using QuickMapServices for a Google layer, without an API key is possible, but it's not guaranteed to work.

I would say that on recent LMWC it just does not work anymore.

**Comment by gioman** [comment]
> Did you get the "Check" in the Lizmap plugin about missing an API key ? There is the "How to fix" :

@Gustry yes of course :) My question was more about why the change was needed, not how to correctly configure such layers now.

**Comment by Gustry** [comment]
> I would say that on recent LMWC it just does not work anymore.

I know some instances where they use Google without a key and it works ;-) You should check the status of the tiles (the HTTP code and explanation from the Google server)

> My question was more about why the change was needed

Because the Google Layer came back in OpenLayers in 2024 https://github.com/openlayers/openlayers/pull/15465
It was in OpenLayers 2 and then it was removed if I'm correct.
