### ISSUE TITLE
[Bug]: locating: highlight color is below the layer symbology not over

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#4893]
### What is the bug? (in English)

Just configured a layer for the "locating" functionality, by also checking the "display geometry" option

![image](https://github.com/user-attachments/assets/f7145a4b-37d0-4479-b04a-c09cfeb2075b)

that highlights the geometry selected from the list.

Unfortunately on LMWC it seems that the highlight color/rubberband is placed *below* the geometry symbology and not over.

layer active with feature selected from the dropdown list

![image](https://github.com/user-attachments/assets/caa64af6-e471-4d2b-ba0a-fe87a07e0839)

Disabling the layer shows the rubberband

![image](https://github.com/user-attachments/assets/5bb27cb6-66cf-4bde-8532-d9a262b8b29a)

### Steps to reproduce the issue

See above.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.2
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.34.9
* QGIS Server : 3.34.11
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.11.0
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox, Chrome

### Browsers version

Latest updates

**Comment by josemvm** [comment]
the same for the popup tool and data tool when highlights the geometry point by click or select features
if the symbol is than the yellow selection circle the user can' t see that the geometry is selected
![imagem](https://github.com/user-attachments/assets/fcc58912-27a5-4918-9bce-5b2b522674fb)  
![imagem](https://github.com/user-attachments/assets/eb146280-7176-4cff-b6c8-185b7e8805aa)

as an additional comment: when the user closes the popup the geometry remains highlighted

**Comment by nboisteault** [comment]
I can't reproduce the issue. Can someone give me a project reproducing the issue.

**Comment by Gustry** [comment]
Can you on latest 3.8.3 or `pre` package ?

**Comment by Gustry** [comment]
It's visible on https://sandbox.lizmap.com/lizmap_3_8/index.php/view/map?repository=modules&project=pgmetadata#3.869859,43.614587,3.872038,43.615428%7Ctrees,water_surfaces,buildings%7Cdefault,default,default%7C1,1,1

Click on a building, the higlight geometry is under.

**Comment by mdouchin** [comment]
We should probably use the method `lizMap.mainLizmap.map.addToolLayer` as proposed by @rldhont

**Comment by josemvm** [comment]
i´m on 3.8.3. if you have a layer (e.g. raster layer with opacity 100%) you can't see the yellow marker when using the locate by layer tool

**Comment by josemvm** [comment]
i'm on lwc 3.8.3. if you use a layer (e.g. raster layer with opacity 100%) you can´t see the yellow marker when using the locate by layer tool or search address tool

**Comment by josemvm** [comment]
> Click on a building, the highlight geometry is under the building (you can uncheck the building layer to see it)
@Gustry yes, is true. and when you close the the popup, the yellow marker still remains.

**Comment by Gustry** [comment]
Confirmed, it's fixed https://sandbox.lizmap.com/lizmap_3_8/index.php/view/map?repository=modules&project=pgmetadata
