### ISSUE TITLE
Print a map with a dynamic content in HTML does not work anymore 

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#4895]
### What is the bug? (in English)

In QGIS layout if my label is specify as HTML content Lizmap does not print the content filled by the user anymore.

**QGIS Map layout HTML configuration**
![image](https://github.com/user-attachments/assets/8b0d3b2a-8150-4908-b17f-fd4b163202e3)
![image](https://github.com/user-attachments/assets/7bf92a34-6cec-469d-959a-c266758339ef)

**Lizmap Print form**
![image](https://github.com/user-attachments/assets/1a83c005-e185-4c57-b0d4-c47dc9005363)

**Lizmap Print result**
![image](https://github.com/user-attachments/assets/e50e171c-12ed-4f42-8bf7-39c6538abe9c)

Parameters seems to be correctly sent to the GetPrint request :
![image](https://github.com/user-attachments/assets/c93df7b1-2d36-44f5-b490-5d37009a5a1c)

If I uncheck HTML content, then everything is fine.

**QGIS Map layout HTML configuration**
![image](https://github.com/user-attachments/assets/bfc19478-07c5-43a1-baa1-de67feddd6fd)

**Lizmap Print form**
![image](https://github.com/user-attachments/assets/27605d37-1c52-473d-8597-a24fa0a93487)

**Lizmap Print result**
![image](https://github.com/user-attachments/assets/70c9d6c0-9208-4f73-8a6c-f4406a25f2c1)

### Steps to reproduce the issue

1. Create a new layout with a text as HTML content
2. Add an ID to the text so users can change the content
3. Print a map in Lizmap. The text is not updated

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.11
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.28.11
* QGIS Server : 3.34.9
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 4.1.0
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Firefox 122.0

**Comment by Gustry** [comment]
> QGIS Desktop : 3.28.11
QGIS Server : 3.34.9

Can you try with generating your project in 3.34 ?

Linked to the new feature https://changelog.qgis.org/en/qgis/version/3.32/#layout-insure-hyperlinks-within-html-enabled-label

Work in QGIS Server https://github.com/qgis/QGIS/pull/57185

**Comment by arno974** [comment]
Indeed it was due to a different version between QGIS Desktop and QGIS Server... Sorry !
