### ISSUE TITLE
How to create a drill down form with Lizmap 

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-web-client#4898]
### What is the question? (in English)

Hello, 

For a lizmap project I need to report damages made to bus stop furniture (example : the bin has been destroyed). To create a new damage report, users have to click on a bus station and then select one of the furniture linked to this bus station. 

To only link the furniture related to this bus station, I must create a linked drop-down lists.

So I've three tables : 

- bus_station : geolocalized postgis table point
- furniture : PostgreSQL type with an FK link to bus_station
- damages : PostgreSQL type with an FK link to furniture and bus_station (a damage is linked to a a furniture and to a bus station).

I've configured the relationships in QGIS and set up the QGIS form id_arrets_bus and id_mobiliers fields. 

**QGIS form id_arrets_bus id_mobiliers parameter**
![image](https://github.com/user-attachments/assets/4af740ab-dc18-465b-80cb-a62f5ad3da94)

**QGIS form id_mobiliers field parameter**
![image](https://github.com/user-attachments/assets/2d4b3536-47c4-469b-ac9c-00255aace5f6)

In QGIS, the furniture is correctly filtered according to the selected stop.
![image](https://github.com/user-attachments/assets/233ca7c5-ec8f-4d69-bd58-5e7564f03e12)

But in Lizmap, the drop down list remains empty
![image](https://github.com/user-attachments/assets/5194a3e3-fd0d-4749-9fed-3b12df0edc83)

I have read that Lizmap is able to use QGIS Expression and filters but it doesn't seems to work in my case.

Have you ever had to create nested drop-down lists? If so, could you please explain me how to do it ?

Thanks,

Arnaud

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.11
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.34.4
* Lizmap.com : Yes
* QGIS Server : 3.34.11
* Py-QGIS-Server : 1.9.1
* QGIS Server plugin DataPlotly : Not installed
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 24.04

### Browsers

Firefox

### Browsers version

Firefox 131

**Comment by Gustry** [comment]
I think this question might be linked to discussion on the pinned ticket about expressions : https://github.com/3liz/lizmap-web-client/issues/3226, especially the comment https://github.com/3liz/lizmap-web-client/issues/3226#issuecomment-1670884104

It would be nice if you can provide a PR on the repository, with the existing test data to have use case.

BTW, it seems the screenshot is wrong, for the second one.

**Comment by arno974** [comment]
Hi Gustry,

I'm not quite sure that this is the same use case, as in my case I've no geometry. The two tables are only attributes table.

I don't think there is an error with the second screenshot. What makes you think that?

I can't make a public PR with the project as it is a customer project, but I will send you the project.

Thanks

**Comment by Gustry** [comment]
Just checking quickly, this should work already : 

https://sandbox.lizmap.com/lizmap_3_8/index.php/view/map?repository=tests&project=form_advanced

If you : 

* select `form_advanced_point`
* Draw a point
* The `quartier` is already filled (neighborhood)
* The `sousquartier` is pre-populated according to the previous neighborhood value (sub-neighborhood)

So the issue is somewhere. Anylogs about when expressions are evaluated ? Is the HTTP requests sent when you change the value in the dropdown menu ?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
