### ISSUE TITLE
Hidden/Encrypt database password on .qgs file

### ISSUE THREAD

**Issue by mibalas** [3liz/lizmap-web-client#490]
Hi, I'm using Lizmap with postgres database, I realized that my .QGS file writes my db credentials (user and pass), but if I don't check save username and password in the qgis connection settings, the Lizmap does'nt work (which is explained by not having the credentials for connection in db).

Is there any way to hide or encrypt my db password?

I thought of some way to include an external file with the credentials of the database as it is possible in mapfiles

**Comment by rldhont** [comment]
You can use pg_service

**Comment by mdouchin** [comment]
See http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/supported_data.html#pg-service-file 
for details

**Comment by mibalas** [comment]
Hi, thank you for your replies.

I configured pg_service locally and worked fine, but I can't use this method remotely.

In my case, my postgres database is hosted remotely, and i can't connect in QGIS..

**Comment by mibalas** [comment]
Hi, I made a mess, sorry.
Now I was able to connect my data base remotely.

Thanks for the help

**Comment by rldhont** [comment]
@mibalas can I invite you to update documentation ? https://github.com/3liz/lizmap-documentation
thanks

**Comment by pieri70** [comment]
Hello
here we tried to use pg_service file as linked bi @mdouchin but it works locally, not on lizmap web server.
Could you @mibalas explain how you got rid of this issue?
Thanks

**Comment by mibalas** [comment]
Hello @pieri70 
Firstly I configured the pg_service file on my desktop and on the server (where Lizmap is hosted), then following this topic by @mdouchin http://osgeo-org.1560.x6.nabble.com/QGIS-Server-use-PGSYSCONFDIR-in-a-server-with-no-postgresql-installed-td5237401.html
I setup the variables:
/etc/apache2/mods-enabled/env.conf :
SetEnv PGSYSCONFDIR "/path/to/pg_service.conf"

/etc/apache2/mods-enabled/fcgid.conf
FcgidInitialEnv PGSYSCONFDIR "/path/to/pg_service.conf"

I re-configured my QGIS project using connection per service and in the LWC it worked fine.
