### ISSUE TITLE
[Bug]: layer from wfs source via https doesn't work

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#4909]
### What is the bug? (in English)

![imagem](https://github.com/user-attachments/assets/f58b6941-9939-4aa9-82d9-f989532e7087)

### Steps to reproduce the issue

try to add a layer from wfs source

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.3-pre.7994
* Lizmap plugin : 4.4.2
* QGIS Desktop : 3.34.11
* QGIS Server : 3.34.11
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* multiauth : 1.2.2
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal
* Allow parent folder : no
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Firefox

### Browsers version

131.0.3

### Relevant log output

```shell
qgis server logs:

13:24:53 WARNING Server[225942]: Error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.

13:24:53 INFO WfsOutputExtension[225942]: requestReady ran in 0.0s
```

**Comment by josemvm** [comment]
@Gustry 
> Is your WFS layer quick enough ?

not very very quickly but it visible in the map on qgis desktop (not in lwc) and i can work as well with it

> It depends on your QGIS Server settings

what kind of settings in qgis server


i will test https://github.com/3liz/lizmap-web-client/pull/4910 and if you want to test my layer I can provide the url as it is open data

**Comment by Gustry** [comment]
There is nothing to test in #4910. It was just to add test data.

We got sometimes the issue about the SSL handshake being written in a SQLite from QGIS, where QGIS server didn't get write permissions on this file.
You should check QGIS Server logs if there is kind of data.
What is the error in LWC about this blank tiles ? or logs in QGIS server during this request ?

**Comment by josemvm** [comment]
>We got sometimes the issue about the SSL handshake being written in a SQLite from QGIS, where QGIS server didn't get write permissions on this file.

`22:03:56 WARNING WFS[1425]: Cannot create temporary SpatiaLite cache.: Cannot copy file to //.local/share/QGIS/QGIS3/profiles/default/cache/wfsprovider/pid_1425/cache_4.sqlite:`

**Comment by rldhont** [comment]
@josemvm I think your QGIS Server needs the environmental variable to define the home directory

**Comment by josemvm** [comment]
@rldhont  thanks for your answer

now i' ve the environmental variable

 `FcgidInitialEnv QGIS_OPTIONS_PATH "/home/qgis/.local/share/QGIS/QGIS3/profiles/default"`

the structure folders:

`/home/qgis/.local/share/QGIS/QGIS3/profiles/default`

and the error remains:

`WARNING WFS[4667]: Cannot create temporary SpatiaLite cache.: Cannot copy file to //.local/share/QGIS/QGIS3/profiles/default/cache/wfsprovider/pid_4667/cache_2.sqlite:`

**Comment by Gustry** [comment]
> Cannot copy file to `//.local/share/`

I doubt that your process can write to this directory...

**Comment by josemvm** [comment]
> I doubt that your process can write to this directory...

@Gustry i don't know why!
owner: `root`, group: `www-data`
permissions: all (`777`)

**Comment by Gustry** [comment]
On which directory did you check this owner and group ? Look at the path in my message.

**Comment by josemvm** [comment]
> On which directory did you check this owner and group ?

from `qgis/.local/share/QGIS/QGIS3/profiles/default` in `/home/` to the end

**Comment by josemvm** [comment]
@Gustry please where do you point me with
> Look at the path in my message

(?)

**Comment by Gustry** [comment]
> Cannot copy file to //.local/share/QGIS/QGIS3

It's trying to write in `//.local`.

**Comment by josemvm** [comment]
i think that one slash (`/`) = double (`//`) slash...
this mean that the process needs to write at root file system `/.local` ?

**Comment by josemvm** [comment]
ok! so the qgis server ignores the environmental variable `QGIS_OPTIONS_PATH `... (?)
thank you so much @gustry :-)

**Comment by Gustry** [comment]
> ok! so the qgis server ignores the environmental variable QGIS_OPTIONS_PATH ... (?)

No, it works, but then it's the value of `QGIS_CUSTOM_CONFIG_PATH` which overrides the other one.

Try to set both with the same value.

>  thank you so much @Gustry :-)

That's why I pointing you to read your own logs ;-)

**Comment by Gustry** [comment]
There is also `QGIS_AUTH_DB_DIR_PATH`, and `HOME`.
