### ISSUE TITLE
[Bug]: Button onclick Event Not Triggering in Popups

### ISSUE THREAD

**Issue by aaronlaver** [3liz/lizmap-web-client#4914]
### What is the bug? (in English)

When using Lizmap version 3.8.2 (Docker tag 3.8), the onclick event for buttons embedded in HTML popups does not trigger as expected. Despite proper rendering of the buttons and JavaScript code, the events are never fired, and no network requests are initiated. The issue was confirmed to be tied to this specific Lizmap version, as downgrading or upgrading resolved the problem.

Expected Behavior:
The onclick event should trigger the associated JavaScript function when the button is clicked, making the corresponding network request or handling the event.

Actual Behavior:
The button appears, but clicking it does not trigger any associated action, and no JavaScript function is called.

Workaround:
Downgrading to Lizmap 3.7.11 (Docker 3.7) resolves the issue.

Additional Information:
Logs or console output may not provide useful information as the JavaScript function is not triggered at all. The issue seems confined to the specific version of Lizmap.

### Steps to reproduce the issue

Create a popup with a button using the onclick attribute in a Lizmap project.
Bind the onclick event to a JavaScript function (e.g., triggering a fetch request).
Load the project and try to click the button.
Observe that no action is taken, and no JavaScript function is triggered.

### Versions, safeguards, check summary etc

Environment:
Lizmap version: 3.8.2
Browser: Chrome/Firefox/Edge
QGIS version: 3.34.11

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian 11 Bullseye

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Chrome: Version 129.0.6668.101 (Official Build) (64-bit)

**Comment by Gustry** [comment]
Javascript inside a popup is not possible, due to [XSS security issue](https://en.wikipedia.org/wiki/Cross-site_scripting).
You must use [Javascript signals](https://docs.lizmap.com/current/en/publish/customization/javascript.html).
Duplicate of #4707
