### ISSUE TITLE
WMS third party not working when using it in a child project

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#492]
Lizmap v 3.0.9
Ubuntu 14.04

I try to load a WMS external layer (base map) from an other lizmap project master-child with feature 'group and layer'. 
In the master the WMS et set with 'loads directly from third party' activated. In the child it s the same.
With a local base layer from the same master-child architecture it  works.

error.log:

> 2017-02-07 14:17:40     0.0.0.0  warning 2017-02-07 14:17:40     [2]     SimpleXMLElement::xpath(): Invalid predicate    /var/www/websig/lizmap/modules/lizmap/classes/lizmapProject.$

> 2017-02-07 14:17:40     0.0.0.0  warning 2017-02-07 14:17:40     [2]     SimpleXMLElement::xpath(): xmlXPathEval: evaluation failed      /var/www/websig/lizmap/modules/lizmap/classe$

> 2017-02-07 14:17:40     0.0.0.0  notice  2017-02-07 14:17:40     [8]     Trying to get property of non-object    /var/www/websig/lizmap/modules/lizmap/classes/lizmapProject.class.ph$

> 2017-02-07 14:17:40     0.0.0.0  notice  2017-02-07 14:17:40     [8]     Trying to get property of non-object    /var/www/websig/lizmap/modules/lizmap/classes/lizmapProject.class.ph$

> 2017-02-07 14:17:44     0.0.0.0  warning 2017-02-07 14:17:44     [2]     mkdir(): Permission denied      /var/www/websig/lib/jelix/utils/jFile.class.php 97

> 2017-02-07 14:17:44     0.0.0.0  warning 2017-02-07 14:17:44     [2]     chmod(): No such file or directory      /var/www/websig/lib/jelix/utils/jFile.class.php 100

Thanks

**Comment by rldhont** [comment]
Thanks for this feedback, it will be a hard work to fix it.

**Comment by rldhont** [comment]
Can you take a look at 9c849eb1a48dc1924ec912ca593cd071ee8effa2 and close if it fixed it.

**Comment by jlstanus** [comment]
Sorry i m on holliday.  I ll give Yop feedback as soon as possible.

**Comment by rldhont** [comment]
Has you test this ? Is it fixed ?

**Comment by jlstanus** [comment]
https://www.gate-16.xyz/index.php/view/map/?repository=master&project=LIZ_cirb_master
https://www.gate-16.xyz/index.php/view/map/?repository=slave&project=LIZ_slave

**Comment by nboisteault** [comment]
@jlstanus links are dead. Do you still have issue with last Lizmap 3.2 ?

**Comment by jlstanus** [comment]
Sorry, i have no more active instance Lizmap available to test
