### ISSUE TITLE
Popup - Add print button to allow to print the feature popup content

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#493]
For example, use an empty composer with an HTML input

**Comment by Abelon38** [comment]
That would be a vary nice enhancement! I actually have som clients asking for this possibility? 
Regards!
Abel

**Comment by jancelin** [comment]
exemple: for print atlas popup with a print_atlas.js

```
lizMap.events.on({
  uicreated: function(e) {
      function nWin() {
      var w = window.open();
      var html = $("#liz-atlas-item-detail").html();
      $(w.document.body).html(html);
      w.print();
      }
    lizMap.addDock('icon-print');
    $('#button-icon-print').click(nWin);
  }
});
```
https://github.com/jancelin/lizmap_js/blob/master/print_atlas.js

**Comment by josemvm** [comment]
hi @jancelin 

how does it work?

- put the print_atlas.js inside the media folder of the lizmap project
- needs an empty composer with an HTML input ?
- "liz-atlas-item-detail" ?

thanks

**Comment by jancelin** [comment]
Hi @josemvm,
This JS print lizmap atlas item
1. Create a lizmap project ans configure atlas option on lizmap plugin
2. Copy print_atlas.js on /media/js/default or project name folder.
3. Run your project on Firefox, active atlas, choose a entity. Now you see entity item.
4. Click on print icon (on the left, above the atlas icon.
A New tab is open with your item and you can print it (pdf or paper).

**Comment by josemvm** [comment]
hi @jancelin

thanks for your help!

![imagem](https://user-images.githubusercontent.com/10053874/45560824-12576280-b83e-11e8-9ecf-db282ba743c6.png) we need to improve the icon

![imagem](https://user-images.githubusercontent.com/10053874/45561384-83e3e080-b83f-11e8-9a7b-3e1e7df54b51.png) and the label too

nice :-)

**Comment by nboisteault** [comment]
With coming Lizmap 3.7, it will be possible to launch the browser print to print the feature popup content as pdf or directly on a printer.

https://github.com/3liz/lizmap-web-client/pull/3383
