### ISSUE TITLE
attribute table - select searched line button

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#494]
LWC 3.0.11 and master

the select searched line button (*) only selects features shown on the first page of results table (the first 50, 10, 25 or 100 lines)

**Comment by Maverick83000** [comment]
Hy!
I'm sorry, I don't have an answer but an issue too. I've a problem with attribute table. I can see the table but there is no attributes inside. My layer is on postgis and in scr: 4326.

I'm on Lizmap 3.02 and qgis-serveur 2.18.

Thanx for your help

**Comment by rldhont** [comment]
Hi @Maverick83000 if your issue is not the same, open a new one or find the same as yours.

**Comment by Maverick83000** [comment]
Sorry, 
I was thinking that my problem was similar.

I will open another issue.
