### ISSUE TITLE
No attributes in the table

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#496]
Hy!
I've a problem with attribute table. I can see the table but there is no attributes inside. My layer is on postgis and in scr: 4326.

I'm on Lizmap 3.02 and qgis-serveur 2.18.

Thanx for your help

**Comment by rldhont** [comment]
Does the fields are published in WFS ?
Can you provide a print screen ?
Can you provide a link that help us verify the browser console ?
