### ISSUE TITLE
[Question]: Why are there 2 versions of Lizmap

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-web-client#4962]
### What is the question? (in English)

Why are there two versions of Lizmap web client on Github??
Today i found V3.8.3 and also V3.7.12
I could not found any explanation...
Or is this a stupid question ?

### Versions, safeguards, check summary etc

nvt

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 11

### Browsers

Chrome

### Browsers version

Chrome 130.....

### Relevant log output

```shell
nvt
```

**Comment by katagen** [comment]
It is the same for QGIS... you have the last version (3.8) and the LTR (3.7)!

**Comment by Gustry** [comment]
Yes, it's the same for nearly all softwares (Windows, FireFox, LibreOffice...). One branch released earlier, more stable but less features, and one branch released later, more features but less stable.

Look at PostgreSQL, they released https://endoflife.date/postgresql, they 6 current releases supported.
