### ISSUE TITLE
[Question]: Is there a way to configure WMS version for third party WMS layers?

### ISSUE THREAD

**Issue by RaineEkman** [3liz/lizmap-web-client#4972]
### What is the question? (in English)

In my project there is a layer configured using the "Get images directly from WMS Server" checkbox. It won't show in the web client, and I can see in my browser dev tools that WMS 1.3.0 is tried. However, when I try manually any of the WMS 1.3.0 URLs I can see, I get this, indicating that the server doesn't support WMS 1.3.0:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
 <ServiceException>Unsupported WMS version</ServiceException>
</ServiceExceptionReport>
```
QGIS Desktop loads the layer fine, and checking it I can see that the URLs are WMS 1.1.1. I can't find a way in the Lizmap plugin to configure the version as 1.1.1. Should this even be possible or is only 1.3.0 supported?

### Versions, safeguards, check summary etc

Server startup:
qgisserver 1.9.3rc0 (build 202411110425, commit feca61f)
QGIS 3.34.12-Prizren 'Prizren' (eeb6af36386)
QGIS code revision eeb6af36386
Qt version 5.15.13
Python version 3.12.3
GDAL/OGR version 3.8.4
PROJ version 9.4.0
EPSG Registry database version v11.004 (2024-02-24)
GEOS version 3.12.1-CAPI-1.18.1
SQLite version 3.45.1
OS Ubuntu 24.04.1 LTS

Plugin:
**Versions :**

* Lizmap Web Client : 3.8.3
* Lizmap plugin : 4.4.4
* QGIS Desktop : 3.34.0
* QGIS Server : 3.34.12
* Py-QGIS-Server : 1.9.3rc0
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal<br/>
* Allow parent folder : no<br/>
* Prevent other drive : yes<br/>
* Prevent PG service : yes<br/>
* Prevent PG Auth DB : yes<br/>
* Force PG user&pass : yes<br/>
* Prevent ECW : yes<br/>
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 11

### Browsers

Microsoft Edge

### Browsers version

Microsoft Edge Version 130.0.2849.80 (Official build) (64-bit)

### Relevant log output

```shell
Lizmap Web Client application error log file: empty
```

**Comment by Gustry** [comment]
Can you check in your QGS file **all** occurences of the URL of your WMS to see if the `VERSION` is included in it ?

**Comment by Gustry** [comment]
Well, there are a few area where 1.3.0 is hardcoded : https://github.com/search?q=repo%3A3liz%2Flizmap-web-client%201.3.0&type=code

**Comment by RaineEkman** [comment]
> Can you check in your QGS file **all** occurences of the URL of your WMS to see if the `VERSION` is included in it ?

I tweaked the server settings in QGIS:
- Added `?VERSION=1.1.1` to the server connection 
- Checked the "ignore GetXXXXURI reported in capabilities" options to keep the entered connection URL 
- Re-added the layer
- Exported using the Lizmap plugin.

The version number went into both copies of the URL in the .qgs file. Now I get URLs with double version numbers in the web client:
`https://<redacted>/TeklaOGCWeb/WMS.ashx?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image%2Fpng&STYLES=&TRANSPARENT=true&LAYERS=<redacted>&DPI=135&TILED=true&WIDTH=384&HEIGHT=384&CRS=EPSG%3A3067&BBOX=<redacted>`

Some hardcoded version number should probably be replaced by something more flexible/smarter.

**Comment by Gustry** [comment]
It's not just the version number in the HTTP call, but mainly parameters and response that should bec checked.
