### ISSUE TITLE
export layers to spatial formats - experiences and troubles

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#500]
i would like to share with you some qgis server (2.14.11) issues:

- GeoJSON
malformed file/the exported file have no crs information in the header
so, when the user import the file into qgis desktop, the user have to specify the native crs
maybe a regression in qgis server https://github.com/3liz/lizmap-web-client/issues/278, https://github.com/qgis/QGIS/commit/9ea56acde03ace5c078c3d95f98be267eb1c22fd

- SHP
the .prj file contains the crs information (WGS 84)
however, when the user import the file into qgis desktop, the user have to specify the native crs because the properly coordinate system transformation doesn´t solve the correct spatial position
with ESRI proprietary software (arcmap)
![esri](https://cloud.githubusercontent.com/assets/10053874/22854393/a18d3bca-f065-11e6-9282-59d9ef7a9d62.jpg)

- KML
export to kml format produces a huge column of bizarre geometries lost in space... when imported to the google earth or qgis desktop
![kml](https://cloud.githubusercontent.com/assets/10053874/22854484/5e478d50-f067-11e6-934b-317aee50e0cb.jpg)

- GML
no problem

see ya!

**Comment by rldhont** [comment]
Hi @josemvm:
* GeoJSON: QGIS Server has never put a CRS information in the file. In QGIS Server 2.14, the crs is the source one; in 2.18, the CRS is 4326 as defined in the RFC.
* SHP and KML are build by QGIS from the GML exactly as QGIS Desktop done it. In the SHP case, I don't know if arcmap likes ones build by QGIS. In the KML case, it seems that the coordinate has been rounded.

**Comment by pcav** [comment]
I have saved GeoJSON to a file, but QGIS desktop refuses to open it, pretending it is not a valid forma. Suggestion has been made by @tomchadwin on qgis-dev to save to JSONP, as: "JSONP can be loaded in from anywhere, without having to configure CORS. It's therefore arguably the best export format for geo vector data, if you don't know where it is going to be hosted."

**Comment by tomchadwin** [comment]
@pcav No, I was saying that possibly the export *was* JSONP. While what I said about JSONP is correct, QGIS will not open it. If the export is JSONP, you can convert it to JSON, which should work.

**Comment by pcav** [comment]
Sorry I misunderstood. I'm still not at all familiar with the format.
Thanks for clarifying.

**Comment by josemvm** [comment]
wrong spatial location (far faraway or opposite hemisphere) on exports!...

QGIS Server: 2.14
Lizmap: 3.2

**Comment by nboisteault** [comment]
@josemvm is issue still occuring with QGIS 2.18 ?

**Comment by josemvm** [comment]
hi @nboisteault 

QGIS 2.18
> - GeoJSON

solved

> - SHP
> the .prj file contains the crs information (WGS 84)
> however, when the user import the file into qgis desktop, the user have to specify the native crs because the properly coordinate system transformation doesn´t solve the correct spatial position

remains

> - KML
> export to kml format produces a huge column of bizarre geometries lost in space... when imported to the google earth or qgis desktop
> ![kml](https://cloud.githubusercontent.com/assets/10053874/22854484/5e478d50-f067-11e6-934b-317aee50e0cb.jpg)

remains

thanks

**Comment by nboisteault** [comment]
hi @josemvm 
Does issue still occur with Lizmap 3.3 and QGIS Server 3.4 ?

**Comment by josemvm** [comment]
hi @nboisteault

with qgis server 3.4 everything works fine! except for MIF format, which generates an empty zip file...

just one note at lizmap level, the lizmap exports the files with wrong file name encoding (e.g.: `export_Bocas_de_IncÃªndio.xxx` in case of `Bocas de Incêndio`/layer name in lizmap).
if you consider it relevant, i may open another issue about it.

thanks for your attention

**Comment by rldhont** [comment]
@josemvm can you report issues about format in the QGIS Server plugin wfsOutputExtension https://github.com/3liz/qgis-wfsOutputExtension

Thanks.
