### ISSUE TITLE
[Bug]: Child feature table items not displayed in child popup

### ISSUE THREAD

**Issue by erw-1** [3liz/lizmap-web-client#5023]
### What is the bug? (in English)

In a popup, when a [feature table](https://github.com/3liz/lizmap-web-client/pull/4502) item is selected, other items are automatically hidden, as expected. However, if there is another feature table in the selected child feature's popup, new items are also hidden before they can be picked, because they share the same CSS selector.

You could introduce a hierarchy level into the selector to differentiate between parent and child feature tables.

#### IN QGIS:
1. Setup a [lizmap-features-table html element ](https://github.com/3liz/lizmap-web-client/pull/4502) in the popup of the parent layer
2. Setup a second lizmap-features-table in the popup of the child layer

#### IN LIZMAP WEB CLIENT:
1. Click one of the items of the lizmap-features-table (the child popup unwraps) 
Bug happens here, the lizmap-features-table items from the child layer popup are not displayed
Video example (FRA): https://youtu.be/zZafmypUBVs

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.4-pre.8071 - commit ce348b697 https://github.com/3liz/lizmap-web-client/commit/ce348b697
* Lizmap plugin : 4.4.5
* QGIS Desktop : 3.34.12
* QGIS Server : 3.34.11
* Py-QGIS-Server : 1.9.1
* QGIS Server plugin DataPlotly : 4.2.0
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.20.0
* QGIS Server plugin lizmap_server : 2.11.2
* QGIS Server plugin wfsOutputExtension : 1.8.2

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* cadastre : 2.1.4
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal<br/>
* Allow parent folder : yes<br/>
* Number of parent : 2 folder(s)<br/>
* Prevent other drive : yes<br/>
* Prevent PG service : yes<br/>
* Prevent PG Auth DB : yes<br/>
* Force PG user&pass : yes<br/>
* Prevent ECW : yes<br/>
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10/11

### Browsers

Microsoft Edge

### Browsers version

Edge 131.0.2903.70

**Comment by rldhont** [comment]
@erw-1 do you have a solution or a proposition to fix it ?
