### ISSUE TITLE
Print only selected features

### ISSUE THREAD

**Issue by matteob85** [3liz/lizmap-web-client#506]
in qgis print composer i can add a table showing only map visible features. can i print only the feature i select in lizmap with geolocalization, clicking on feature (it is possible to filter a feature without clicking on filter icon in popup?) or filtering it from data table instead of all visible features?

**Comment by rldhont** [comment]
Hi @matteob85,

After selected features, you can filter them and only print them.
The selection can be done through popup and table.
In version 3.1, a new tool can give you the ability to graphically select features.

Documentation needs to be updated https://github.com/3Liz/lizmap-documentation
Any helps are welcome.

**Comment by nboisteault** [comment]
Note added : https://github.com/3liz/lizmap-documentation/commit/752a0a060dc6dcfecbdaa151337ead9f7d1e8fb2
