### ISSUE TITLE
permalink tool - layers style

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#507]
the permalink tool doesn't include the layers style (given by the "change layer style" button)

it's very usefull for show and sharing the overlaying layers

thanks in advance

**Comment by rldhont** [comment]
Styles is conserved.
Test this permalink `?repository=montpellier&project=montpellier&layers=B0TFTTTFFFTTTFTTT&bbox=407164.127264%2C5399454.040359%2C455969.169817%2C5411416.435284&crs=EPSG%3A3857&layerStyles=tramway%3Acolored`

**Comment by josemvm** [comment]
yes, in fact styles are conserved
it's a problem in a project of mine and i don't know why... the "&amp;layerStyles=..." doesn't appear in permalink
