### ISSUE TITLE
layers dock - switcher layers actions (buttons)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#508]
on mobile devices or small screens it's not possible to use these buttons:
- zoom to layer extent
- change layer style
- export

it's not possible to enable the layer name because when the user clicks on a layer, the layer information panel automatically appears, occupying the entire screen
so, it's not possible to activate the buttons

one way to solve the problem could be to use the (i) icon for open the information panel and not used for open the documentation, since the documentation can be opened from the information panel

**Comment by mdouchin** [comment]
I think a better solution would be to port all features of the layer action bar to the layer information panel, at least in mobile mode, so that
* User clicks a layer
* the layer information panel is opened fullscreen
* big buttons are then available to zoom to layer, change layer stye, export

**Comment by josemvm** [comment]
yes, only for mobile mode, i also think so

**Comment by Spitfiire** [comment]
I got the same problem and the slide bar doesn't work properly on very small resolution (like 800x600) on computer

**Comment by rldhont** [comment]
@mdouchin do you think you can do it ?

**Comment by josemvm** [comment]
very nice improvement in quality and look :-)
you are the best!

thanks a lot
