### ISSUE TITLE
Button search function  by using QGIS Desktop

### ISSUE THREAD

**Issue by bellaaaaaa** [3liz/lizmap-web-client#509]
How to relate the button search in lizmap web client function with our categories by using QGIS Desktop?
For example i wanna name the food categories in QGIS attributes,then when the user search it will show only the location in food categories.

**Comment by josemvm** [comment]
hi @bellaaaaaa 

you can read about it here:
https://docs.3liz.com//en/publish/advanced_lizmap_config.html#add-the-localization-function
