### ISSUE TITLE
[question] - project information at map starup

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#511]
hi,

- how can i set the project information at map starup?

- how can i set the first title ("Welcome on this map"), like this:

![title](https://cloud.githubusercontent.com/assets/10053874/23172250/1b2a4858-f84d-11e6-9037-5409bb3ea73b.jpg)

thanks

**Comment by Spitfiire** [comment]
Hi,

Go in lizmap/install/qgis/media/js/montpellier
and copy displayMessageAtStartup.js.example in YourProjectFolder/media/js/
delete .example extensions.

Verify on lizmap admin panel "Allow themes for this repository” is on

And it works.

**Comment by josemvm** [comment]
hi @Spitfiire 

nice!

thanks
