### ISSUE TITLE
scale dependent visibility works differently from QGIS

### ISSUE THREAD

**Issue by mbernasocchi** [3liz/lizmap-web-client#512]
If I set a layer's maximum  scale visibility to 1:5000 in qgis I still see the layer when at scale 1:5000 in lizmap the layer is grayed out.

If I set a layer's maximum  scale visibility to 1:4999 all works as expected in QGIS and Lizmap

**Comment by rldhont** [comment]
Which lizmap version ?
Can you provide an example ?

**Comment by mbernasocchi** [comment]
3.1beta1

**Comment by mbernasocchi** [comment]
now that you mention, let me try with a later one

**Comment by rldhont** [comment]
Do you have the same in 3.0 ?

**Comment by nboisteault** [comment]
Scale in browser can't be correct. OpenLayers 2 has a constant for DPI which might be incorrect for some devices. Maybe we should disable the gray out behavior.
