### ISSUE TITLE
[Bug]: Antivirus identifies threat in lizmap 3.7.13

### ISSUE THREAD

**Issue by oskardabrowski** [3liz/lizmap-web-client#5129]
### What is the bug? (in English)

The antivirus identifies a threat while attempting to download Lizmap; it is likely that something within it matches an entry in the Windows virus database or other virus databases.

### Steps to reproduce the issue

Just try downloading Lizmap 3.7.13 on Windows 11. If you try to open zip then it will be removed

### Versions, safeguards, check summary etc

![Zrzut ekranu 2024-12-16 074828](https://github.com/user-attachments/assets/be0a9d10-bcb8-4281-9ae1-32439ab1237b)

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 11

### Browsers

Firefox, Chrome, Microsoft Edge

### Browsers version

Edge 131, Chrome 131

**Comment by meyerlor** [comment]
Which antivirus are you using? Scanning the ZIP file with on Virustotal gives 0 false positives:
https://www.virustotal.com/gui/file/c5b7b4ecfb6353e664fa27ddf9660c21fd1cf6336e8c98677a445ba0c2367bc3

**Comment by oskardabrowski** [comment]
I'm using Windows Defender, and it identified a Trojan:Script inside a ZIP file.

![Untitled](https://github.com/user-attachments/assets/67ff29f3-14c6-43fb-a5d5-8756466fd045)

ENG Translation:
Threat Quarantined
Severity: Severe

Detected: Trojan:Script/Wacatac.B!ml
Status: Quarantined
Files quarantined are in a restricted area where they cannot harm your device. These files will be automatically deleted.

Date: 16.12.2024 08:27
Details: This program is dangerous and executes commands from an attacker.

Related items:
File: C:[redacted]\Desktop\lizmap-web-client-3.7.13.zip

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

I don't think someone intentionally added a threat to this project, but I think it's something that could be mistakenly identified as a threat. I'll try to figure out where the problem is, and for now, I'll add Lizmap to the whitelist. If I find anything, I'll contact 3Liz or create a new issue. You can close this issue if you want or I'll close it next week.

**Comment by nworr** [comment]
I downloaded the file and launched an analysis with "Windows Security" on my computer, I don't have that message (consistent with @meyerlor comment ).
In my opinion, this is a false positive.

**Comment by oskardabrowski** [comment]
Ok, issue closed
