### ISSUE TITLE
edition tool - mobile mode (popup)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#513]
hi

qgis server and desktop 2.14.11

on mobile devices, when a user tries to create a geometry in a space where there is a layer with "activate popup" option the popup appears overlapping the edition tool panel

**Comment by rldhont** [comment]
Hi lizmap version ?

**Comment by josemvm** [comment]
hi

version 3.0.11 and master

**Comment by josemvm** [comment]
this issue it's just a "mobile mode" issue

with a mobile device, you can try to create a feature with the layer Points of interest of the project montpellier in a location on one of the districts/Quartiers

when you click on map to create the feature, the popup relative to the district in that location will appear and the editing tool panel will be closed

**Comment by rldhont** [comment]
Did you test it with a touch screen ?
The commit abadf56 in the release_3_0 branch fix this issue with a touch screen.

**Comment by josemvm** [comment]
yes, i did it

**Comment by rldhont** [comment]
Tested with Firefox 53.0.1 on Android without and with abadf56, the commit fix it well.

**Comment by josemvm** [comment]
yes, tested using the firefox private mode and this issue is well fixed with https://github.com/3liz/lizmap-web-client/commit/abadf5671ec270ca232220319715fad4e2c19e83

thanks, @rldhont
