### ISSUE TITLE
Display features count has been lost in 3.0.11

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#515]
Has explain by @josemvm in https://github.com/3liz/lizmap-web-client/issues/246#issuecomment-281949946 and tested with lizmap web client 3.0.11, the showFeatureCount parameter is not well set.

**Comment by rldhont** [comment]
Issue introduced by 4ccccf0

**Comment by josemvm** [comment]
thanks @rldhont 

i apologize for insisting on this question, why this feature doesn't show the total of features like in qgis desktop?

https://github.com/3liz/lizmap-web-client/issues/370

**Comment by rldhont** [comment]
Hi @josemvm, 
The total of features is displayed in the title. Lizmap does not request the title to do not duplicate it.
To display the total, we have to duplicate the title or to update QGIS Server to display the total without the layer title.

**Comment by josemvm** [comment]
thanks for your explanation, @rldhont
