### ISSUE TITLE
Lizmap 3.1rc1 error printing in PDF/SVG format

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#516]
Hello, 
using QGis Server 2.14.3 and Lizmap 3.1rc1 I found the following error printing in PDF and SVG:
_Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Apache/2.4.23 (Debian) Server at 127.0.0.1 Port 81_

This is the server error log:
_[Thu Feb 23 19:41:03.825972 2017] [fcgid:warn] [pid 19186] [client 127.0.0.1:57468] mod_fcgid: error reading data, FastCGI server closed connection
[Thu Feb 23 19:41:03.826174 2017] [core:error] [pid 19186] [client 127.0.0.1:57468] End of script output before headers: qgis_mapserv.fcgi_

I can print without problems in JPG and PNG
I have no problem using, in the same machine, QGis Server 2.14.3 with Lizmap 3.0.7 (where I cannot choose the printing format).

**Comment by rldhont** [comment]
In lizmap 3.0, the format is PDF.
Can you compare url parameters between 3.1 and 3.0 ?

**Comment by virtusmankind** [comment]
I was wrong! Using the **same** project in Lizmap 3.0 and 3.1, I've got same error in printing PDF (no problems with JPG and PNG). Probably there is something wrong in Print Composer or in server?

Here's the url parameters:

**3.1rc1**
_&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:32633&DPI=100&TEMPLATE=IMU&map0:extent=333769.13443981484,4687242.084998724,334091.1421831994,4687463.090313283&map0:scale=1000&map0:grid_interval_x=50&map0:grid_interval_y=50&map0:LAYERS=TerreniEdificabili,EntiUrbani,Localita,Confine,Fogli,PRG&map0:STYLES=default,default,default,default,default,default&LAYERS=TerreniEdificabili,EntiUrbani,Localita,Confine,Fogli,PRG&STYLES=default,default,default,default,default,default_

**3.0.7**
_&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:32633&DPI=100&TEMPLATE=IMU&map0:extent=333779.717794315,4687231.501644225,334101.7255376996,4687452.506958784&map0:scale=1000&map0:grid_interval_x=50&map0:grid_interval_y=50&map0:LAYERS=TerreniEdificabili,EntiUrbani,Localita,Confine,Fogli,PRG&map0:STYLES=default,default,default,default,default,default&LAYERS=TerreniEdificabili,EntiUrbani,Localita,Confine,Fogli,PRG&STYLES=default,default,default,default,default,default&OPACITIES=255,255,255,255,255,255_

**Comment by rldhont** [comment]
Does the template is a simple one ?
Do you have a fake server X ?
Can you update QGIS server version to 2.14.11 or 2.14.12 (released today) ?

**Comment by virtusmankind** [comment]
It is a A3 format page with a map, a legend and a attribute table (in one version I added also an image with website path as source). I do not have a fake server X. 
I'm running QGis Server 2.14.3. Do you think it would be good to upgrade to 2.16 or even 2.18?

**Comment by gioman** [comment]
> I do not have a fake server X

you'll likely need one to solve printing errors

http://www.itopen.it/qgis-server-setup-notes/

**Comment by virtusmankind** [comment]
I can print other projects templates without it...

**Comment by gioman** [comment]
> I can print other projects templates without it...

it can depend on the kind of styles/effects you have in the layers in the projects.

**Comment by rldhont** [comment]
To be sure that all the templates are usable, you need a fake server X.

**Comment by virtusmankind** [comment]
Thanks @gioman and @rldhont. I'll try with a fake server X.

**Comment by jonnyforestGIS** [comment]
Test Environment
SO: Windows 7 64-bits
LWC: 3.1RC
QGIS Server: 2.18.3 64-bits
localhost
Test with montpelier.qgs project demo

1.º I clean the cache
2.º Reboot the apache
3.º Reboot the computer
500 error server.

This Working in machine with LWC 3.0.1.

This is a test machine so the links in the server are not a problem. I share my logs in a zip.
**Zip file content:**
lizmap-error.log
lizmap-access.log
error.log
qgis_server.log - In this file i see a traceback error (this can be the problem?): 

Traceback (most recent call last):
```python
  File "", line 1, in 
  File "C:\OSGeo4W64\apps\Python27\lib\os.py", line 423, in __getitem__
    return self.data[key.upper()]
KeyError: 'USERPROFILE'
```

I will update with qgis 2.18.4 to see if this persists. 
[logs.zip](https://github.com/3liz/lizmap-web-client/files/816668/logs.zip)

**Comment by jonnyforestGIS** [comment]
Test Environment 2
SO: Windows Server 64-bits
LWC: 3.1RC
QGIS Server: 2.14.11 64-bits

Printing is OK in differents formats.

**Comment by rldhont** [comment]
I have discovered an issue in QGIS Server print on Debian 9 when the composition integrated a scalebar. Is it some one case ?

**Comment by jonnyforestGIS** [comment]
Hi @rldhont . In my test Environment 2 is working fine printing with scalebar. 
But my qgis server ltr 2.14.11.

**Comment by nboisteault** [comment]
@rldhont Can we close this issue ?
