### ISSUE TITLE
help with the new installation on windows10

### ISSUE THREAD

**Issue by lraes** [3liz/lizmap-web-client#517]
Hi
I have a problem with an installation on windows10 !
thank you

![installer_php](https://cloud.githubusercontent.com/assets/26005289/23304579/d2c0367c-fa9a-11e6-8307-40747513f15a.jpg)
![pdo](https://cloud.githubusercontent.com/assets/26005289/23304664/3f2a1b7a-fa9b-11e6-912d-9eb358bde3b4.jpg)

**Comment by rldhont** [comment]
Lizmap needs at least 1 Database system: SQLite or PostgreSQL.

**Comment by lraes** [comment]
of course
But this is already the case !

![php](https://cloud.githubusercontent.com/assets/26005289/23306343/74dad464-faa3-11e6-890e-89c6720e8932.jpg)

may be reinstall php ?

**Comment by rldhont** [comment]
does these `*.dll` files exist on your system ?
does these `*.dll` files are in the extension dir ?

If not you have to install these extensions.

**Comment by lraes** [comment]
yes, *.dll exist and are in ext dir

![ext_dll](https://cloud.githubusercontent.com/assets/26005289/23306805/6323e16e-faa5-11e6-9598-b270b47d410b.jpg)

**Comment by rldhont** [comment]
And after`httpd -k restart` does the `phpinfo` page is updated ?

**Comment by lraes** [comment]
Thanks for the replies,
I have restarted apache and then open the phpinfo. How to know if it's up to date ?

![phpinfo](https://cloud.githubusercontent.com/assets/26005289/23307250/23bfff7e-faa7-11e6-900d-60588191ab87.jpg)

**Comment by rldhont** [comment]
Search for sqlite!

**Comment by lraes** [comment]
nothing sqlite

**Comment by rldhont** [comment]
take a look at this http://www.wikihow.com/Enable-SQLite-for-PHP-5.X-in-Windows

**Comment by lraes** [comment]
Ok Mister Rldhont
I found the solution
I will post it a little later
Thank you again for your answers
Good week

**Comment by rldhont** [comment]
@lraes if you have the solution and this one is not provided by the documentation, please participate to the documentation https://github.com/3liz/lizmap-documentation thanks

**Comment by lraes** [comment]
ok, any problem

**Comment by lraes** [comment]
Désolé de vous avoir solicité pour une erreur qui m'est entièrement imputable.
Lors de l'installation de liz map web client j'utilise à tort le copier collé.l'erreur de syntaxe venait du fichier "php.ini" à la ligne : extension_dir = “C:\webserver\php-5.6.23\ext” (les guillemets avant C: était le problème, comme si ça avait utilisé une police différente !)
-Merci encore pour vos contribution

**Comment by baradgeo** [comment]
I have the same issue.
λ php lizmap\install\installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
[error] An error occured during the installation of the module jacl2db: jDb:  sqlite3 extension is not installed in PHP
Installation ended.

**Comment by gioman** [comment]
> I have the same issue.
> λ php lizmap\install\installer.php
> Installation start..
> [notice] Installation starts for the entry point index
> All modules dependencies are ok
> [error] An error occured during the installation of the module jacl2db: jDb: sqlite3 extension is not installed in PHP
> Installation ended.

@baradgeo to avoid having to download and manually configure a lot of stuff (on Windows) you can use this almost ready to use package https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

**Comment by baradgeo** [comment]
> > I have the same issue.
> > λ php lizmap\install\installer.php
> > Installation start..
> > [notice] Installation starts for the entry point index
> > All modules dependencies are ok
> > [error] An error occured during the installation of the module jacl2db: jDb: sqlite3 extension is not installed in PHP
> > Installation ended.
> 
> @baradgeo to avoid having to download and manually configure a lot of stuff (on Windows) you can use this almost ready to use package https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows

Thanks a lot.. it worked... Saved me a lot of time.

**Comment by margaritagolemi** [comment]
Hi, I'm facing the same problem as well. I haven't download and manually configure anything, I used almost ready to use packages. I've checked that I have installed the sqlite3.
