### ISSUE TITLE
edition tool - save picture in photo field (mobile mode)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#518]
hi

qgis server and desktop 2.14.11
version 3.0.11 and master
firefox 51.0.3 and beta

it's not possible to create or update feature when sending photo

chrome and opera (not mini opera) works well

**Comment by rldhont** [comment]
Hi @josemvm, 
Do this issue is the same as #320 ?
I do not understand the issue.

**Comment by josemvm** [comment]
no, it's not the same issue (https://github.com/3liz/lizmap-web-client/issues/320), this issue remains in most internet browsers

according to my last tests with firefox, it is not possible to create a new geometry (or update another one) if you want to submit a photo with it

please, can you try it?

**Comment by rldhont** [comment]
@josemvm it's just about geometry or all the form is not editable ?

**Comment by josemvm** [comment]
the problem is not related to geometry, the user can create and edit geometries

all the fields in the forms receive data and send it

the problem is when there is a photo field in the form. in this case it is not possible to submit any data

**Comment by rldhont** [comment]
Uploading image does not work ?

**Comment by josemvm** [comment]
precisely!

**Comment by rldhont** [comment]
Tested with:
* the layer `Points of interest` of the project `montpellier`
* Firefox 51.0.1 on Linux
and I can created and updated features

**Comment by josemvm** [comment]
i am talking about firefox 51.0.3 on mobile devices

tested with POI/montpellier project too

**Comment by rldhont** [comment]
I can't reproduce the issue with Firefox 51.0.3 on Android.

**Comment by rldhont** [comment]
I can't reproduce for create but I can reproduce for update and the message is about the image size.
But there also some improvements have to be added:
* add a waiter when the user has touched `Save`
* close attribute table on mobile when edition open

**Comment by rldhont** [comment]
I can't update the object because the image was too big, with a smaller one it's ok.

**Comment by josemvm** [comment]
i have already tested on 3 or 4 devices with firefox (51.0.3 and beta) and i can't create or update features... i don't know why!

however, with chrome or opera browser i can do it

i'm sorry for the noise and thanks for your attention @rldhont
 
---

if more users could try it they would be welcome
thanks

**Comment by josemvm** [comment]
if someone want to try, please use this url: http://pdm-revisao.municipioarraiolos.pt 

with your **mobile device** on **firefox**, using the edition tool, create a feature, upload a photo and try to submit

thanks

**Comment by rldhont** [comment]
This commit 1bccbe90322fcf0d369b7884899b534cd51a9414 will help user to know that he have to wait from server.

**Comment by josemvm** [comment]
hi @rldhont 

i already tested: useful and nice feature!
thanks

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
