### ISSUE TITLE
tooltip  on mobile devices - "useless"

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#519]
hi

in my opinion, the tooltip could be automatically disabled on mobile devices
- can not be used...
- occupies unnecessary space in the toolbar

even if used with a mouse emulator, the information appears underneath the search tool

![tooltip](https://cloud.githubusercontent.com/assets/10053874/23356678/b554dce8-fcd2-11e6-99a7-d25ce928c8fc.png)

but in this case, you can rehabilitated it, according to your opinion about this issue

thanks

**Comment by rldhont** [comment]
You're right
