### ISSUE TITLE
Display the images next to the title of the layer

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#520]
Hi,

How can i display the legend next to the title of the layer.

You can check an example on this site : http://lizpoi.3liz.com/demo/index.php/lizpoi/map/
Thanks

**Comment by josemvm** [comment]
hi
 
you must use .svg symbols into QGIS.
the images must be available in both sides (client-side and server-side)

i hope this may help you

**Comment by bgisb** [comment]
+1 That would be great

**Comment by Gustry** [comment]
The example is not visible anymore.

Is this issue still valid ? I think it's done.

With 3.7, a lot of work has been done about the legend.
