### ISSUE TITLE
Problem when I create a child

### ISSUE THREAD

**Issue by ambreLy** [3liz/lizmap-web-client#522]
Hello,

I have a problem on lizmap31 when I create a child, it doesn't work and there is a bug, as you can see in this picture : 

![capture d ecran_2017-02-28_17-36-39](https://cloud.githubusercontent.com/assets/25345151/23414882/b559ccf6-fddd-11e6-98de-7a594d2eb98d.png)

Could you help me ? Thanks a lot !
Ambre

**Comment by rldhont** [comment]
I do not see the issue in the image. Can you be more explicit ?
What do you do to add a child ? Do you click on `ruche` in the list of the button `Create a child` ?

**Comment by Amber66** [comment]
Hello, if you look at the symbols on the left ('projects', 'layers', 'edition'...) you can see something wrong... and it happening when I create a child. 
Yes, I click on 'data', then on 'rucher', then on 'ruche' in the list of 'create a child' and it doesn't work. I tried to modifie the Relation between the two layers on Qgis but nothing change.

**Comment by ambreLy** [comment]
Ok thanks, I work with Docker, I removed my docker image Lizmap and I built a new image from Github, I start the container and now it work normally. Thanks for help :)
