### ISSUE TITLE
Internal server error => print external baselayer

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#523]
Hi,
I try to print osm-mapnik in lizmap but i got a 500 Internal server error.
I have a osm-mapnik layer (.xml) in my qgis project.

Last line log : [4548][09:37:45] Trying to get layer osm-mapnik//Overview

Thanks.

**Comment by rldhont** [comment]
You probably have a problem with:
* rights to access external sources from the server
* GDAL tms cache (can GDAL create this cache directory ?)

It's a QGIS Server issue.

**Comment by jlstanus** [comment]
Same problem with QGIS 2.18.x and 3.2 (master branch)

**Comment by Gustry** [comment]
@rldhont Do you know something about this server issue? Still valid?
