### ISSUE TITLE
Editing - Mandatory field

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#524]
Hi 
It is possible to set a field as mandatory in order to allow "save" in a new record on Lizmap?

**Comment by rldhont** [comment]
Yes, you'll find some example in the Montpellier project:
* in tram stop works, date and title fields are mandatory
* in bicycle ride, description and type fields are mandatory

**Comment by virtusmankind** [comment]
I cannot find which QGIS option you set to make a "Text Edit" column value "not null" in order to have a mandatory text box in Lizmap to save a new record (or editing an existing one)

**Comment by rldhont** [comment]
Lizmap read the "not null" in the database, not in the QGIS project. Lizmap does not support all the 2.18 features.

**Comment by virtusmankind** [comment]
Sorry, but I still cannot understand how to make a field **mandatory** to allow saving an edited feature in Lizmap 3.1rc1?

**Comment by rldhont** [comment]
In the database you can define some attributes to be `NOT NULL`
You have to update the table in the database to define fields has mandatory `NOT NULL`

**Comment by virtusmankind** [comment]
Thanks a lot! It works!

**Comment by rldhont** [comment]
Can you update the documentation ? https://github.com/3liz/lizmap-documentation/
Thanks

**Comment by pcav** [comment]
Quickly done not to forget, please add more flesh:
https://github.com/3liz/lizmap-documentation/commit/46b6c3be54df2d320cd8c8713fbbf04218fdc838

**Comment by rldhont** [comment]
Thanks a lot @pcav for this
