### ISSUE TITLE
delete feature from popup -> close popup

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#525]
hi

being time to improve the editing tool, i think it would be a good idea to automatically close the popup after deleting a feature

![popup](https://cloud.githubusercontent.com/assets/10053874/23475454/8a55fe76-feaf-11e6-8688-2bc5e7f326ec.jpg)

thanks

**Comment by rldhont** [comment]
Done here 501e0bcc56c8767d06030f67814694122f40418e,  isn't it ?

**Comment by josemvm** [comment]
yes, it is!

and then if you could avoid the popup message "No object has been found at this location."

![popup1](https://cloud.githubusercontent.com/assets/10053874/23500610/9a8b338c-ff28-11e6-927c-f2ec44692938.jpg)

the process would be cleaner  (particularly in the case of mobile devices) - i think so

thanks

**Comment by josemvm** [comment]
> the process would be cleaner (particularly in the case of mobile devices)

the screen remains completely obscured by the popup message, due to an object whose deletion was previously confirmed:

![screenshot_2017-03-02-09-27-36](https://cloud.githubusercontent.com/assets/10053874/23501314/576cb8b6-ff2b-11e6-9692-07d0bd92434f.jpg)

**Comment by josemvm** [comment]
hi  @rldhont 

this fix has been lost in 3.0.12 and 3.1.0

thanks

**Comment by rldhont** [comment]
@josemvm the code is already there...

**Comment by josemvm** [comment]
but doesn't work. if you could try...

**Comment by josemvm** [comment]
hi @rldhont 

please, can you review this bugfix?
https://github.com/3liz/lizmap-web-client/commit/479eb7826ab146a9031a3491fcf4292043e0042b

thanks again

**Comment by josemvm** [comment]
hi @rldhont 

LWC 3.1.1 (fresh install)

just to remind you, this problem has not yet been solved
please can you reopen the issue and review the code?

thanks
