### ISSUE TITLE
permalink tool - anonymous group

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#528]
permalink tool doesn´t show the "Bookmarks" feature for anonymous group
![permalinkt](https://cloud.githubusercontent.com/assets/10053874/23551737/03f78932-0010-11e7-98e7-3e3864d4ca6f.jpg)

only "link to current map"
![permalink](https://cloud.githubusercontent.com/assets/10053874/23551655/ae30f132-000f-11e7-9760-c015c3669d4e.jpg)

i don't know if this is on purpose...

thanks

**Comment by rldhont** [comment]
Bookmarks are linked to a user so they need an authenticated user.
The documentation as to be updated.

**Comment by josemvm** [comment]
thanks @rldhont

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
