### ISSUE TITLE
projets lizmap invisible après authentification 3.1rc1 (windows10)

### ISSUE THREAD

**Issue by lraes** [3liz/lizmap-web-client#529]
Bonjour,
J'ai voulu installer la dernière version de lizmap-web-client (3.1rc1). Je m'authentifie en tant qu'admin pour la configuration. Je ne vois pas le répertoire par défaut de "montpellier". Je rajoute également des répertoires sans messages d'erreur mais lorsque j'accède à la page "projets-lizmap" je n'ai que le bandeau lizmap qui s'affiche...
Par contre avec la version 3.011 ça fonctionne très bien ! (installation sur un autre pc windows10)
Merci de votre contribution

**Comment by rldhont** [comment]
@lraes il faut vérifié que le groupe admin ai bien accès au différents répertoires.

**Comment by lraes** [comment]
Effectivement...
Merci et bravo pour votre application.
PS/ pensez-vous qu'il y a un réelle différence de performance avec un serveur linux par rapport à windows ?
Par contre l'installation sous linux est assez compliqué !

**Comment by rldhont** [comment]
Bonjour,
L'installation sous Windows est plus compliqué que sous Linux, car vous devez télécharger et installer chaque logiciel indépendamment ce qui n'est pas le cas sous Linux.
Ensuite pour la configuration la complexité est la même.
Enfin oui tous ses logiciels fonctionne mieux sous Linux.
