### ISSUE TITLE
Lizmap 2.12 - print- localhost - grids

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-web-client#531]
Hello everyone,

I use the QGIS Desktop 2.18.4 and I have the plugin LIZMAP installed (old version), when I do a print using the lizmap (http://localhost/lm/lizmap/www/index.php/view/), the printed layout appears with grids and they are off on the QGIS project ...

This is a new function of the lizmap (old version)?

Or is there some setting to turn off and on if we want to use the grids?

I appreciate all the help.

Thank you.

Orlando
![lizmap_print_layout_grids](https://cloud.githubusercontent.com/assets/15649016/23587907/3fbe8878-01ad-11e7-9913-184a7dd34958.png)

**Comment by rldhont** [comment]
Do you have the same result with QGIS Server 2.14 ?

Lizmap 2.12 is not updated since 1 year, so it has not been tested with QGIS Server 2.18.

**Comment by opbernardo** [comment]
Hi,

Thank you for your help.

I use the QGIS-ltr-Server 2.14.12-1

Only after updating (OSGEO4W) to version of Qgis Desktop 2.18, the prints
layouts appear with the grids ... but the qgis server is the same (
QGIS-ltr-Server 2.14.12-1).

Thank you for your help.




2017-03-06 13:58 GMT+00:00 rldhont <notifications@github.com>:

**Comment by opbernardo** [comment]
Hi,
Thank you for your help.
I use the QGIS-ltr-Server 2.14.12-1
Only after updating (OSGEO4W) to version of Qgis Desktop 2.18, the prints layouts appear with the grids ... but the qgis server is the same (QGIS-ltr-Server 2.14.12-1).
Thank you for your help.

**Comment by josemvm** [comment]
hi

qgis server and desktop 2.14.12

![grids](https://cloud.githubusercontent.com/assets/10053874/23823637/813922bc-065e-11e7-97a6-b08c48a10a24.jpg)

**Comment by josemvm** [comment]
is it a qgis server issue?

**Comment by rldhont** [comment]
I think, I have fix the grid in print in QGIS Server so the feature is reactivated in Lizmap.

**Comment by rldhont** [comment]
QGIS Server has lost is capability to display GRID requested by the client.
I have fixed this regression https://github.com/qgis/QGIS/commit/000e97453dfa01e3cbb2e60bbaee16f0ce760a2a
If in the QGIS Composition, Lizmap found a grid, Lizmap is requested the GRID like in the Montpellier example. It's a back to old feature.

**Comment by josemvm** [comment]
clean!

thanks @rldhont

**Comment by opbernardo** [comment]
Hi again, 
Thank you for your help. 
I use the QGIS-ltr-Server 2.14.14-1 and Qgis Desktop 2.14.14, the prints layouts appear with grids ... but the grids on Qgis print layou is off...
Thank you for your help.
This is the second time this appen... the first time I use the QGIS-ltr-Server 2.14.12-1
Can you help me please?
Thank you very much.
Orlando

**Comment by opbernardo** [comment]
Hi again,
Thank you for your help.
I use the QGIS-ltr-Server 2.14.14-1 and Qgis Desktop 2.14.14, the prints layouts appear with grids ... but the grids on Qgis print layout is off...
Thank you for your help.
This is the second time this happen... the first time I use the QGIS-ltr-Server 2.14.12-1
Can you help me please?
Thank you very much.
Orlando

**Comment by rldhont** [comment]
Fixes with f8048995f49a71e72c09b3c4b280840eeae4e863
