### ISSUE TITLE
[Question/enhancement] Transaction id, locks on PostGIS

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#532]
In the edit lizmap feature, 
When i select an object in the map.
Is there a lock on it to avoid parallel edition and an overwrite in databate ?

How it's managed?

**Comment by rldhont** [comment]
There is no lock on feature.
Features can be updated in the same time by QGIS directly connected on PostGIS DB.

**Comment by jlstanus** [comment]
ok. Tks for this informations with qgis.
So could we use 'lizmapeditionformdisplayed' with JS to send a lock to a row to qgis then to PostGIS ? or only to PostGIS or QGIS server?
I m reading:
https://www.postgresql.org/docs/9.1/static/view-pg-locks.html
https://www.postgresql.org/docs/9.1/static/explicit-locking.html
https://hub.qgis.org/issues/14717
https://hub.qgis.org/issues/972

Could that be easily implemented?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
