### ISSUE TITLE
Using of D3.js in Lizmap

### ISSUE THREAD

**Issue by ClaireSeard** [3liz/lizmap-web-client#533]
Hi,

I’m currently working on a lizmap project to map the land cover. To illustrate the relative percentage of the different land cover classes for each town, I’m drawing a pie chart with D3.js in the lizmap popup.

I’m trying to display the labels of the land cover classes on mouse over the donut but it’ not working.

The data are:
var data = [
          { label: 'Surfaces artificialisées', percent: {$pourc_niv1_1}, color: "#D84C47" },
          { label: 'Zones agricoles', percent: {$pourc_niv1_2}, color: "#F0AD4E" },
          { label: 'Forêts et zones semi-naturelles', percent: {$pourc_niv1_3}, color: "#5CB55C" },
          { label: 'Zones humides et lagunes', percent: {$pourc_niv1_4}, color: "#5BC0DE" },
	  { label: 'Zones en eau', percent: {$pourc_niv1_5}, color: "#0000FF" }
        ];

I’ve tried to append an svg:title to each path:
g.append("path")
.attr("d", arc)
.style("fill", function(d,i) {return d.data.color;})
.append("svg:title")
.text(function(d) {return d.label;});

I’ve also tried to creating a tooltip using mouseover events:
g.on('mouseover', function(d) { var label = function(d) {return d.data.label;}; 
tooltip.select('.labels').text(d.data.label);
tooltip.style('display', 'block');});	
g.on('mouseout', function() {tooltip.style('display', 'none');});

Does anyone already try to make an interactive donut on a lizmap popup?

Thanks,
Claire
Narbonne, France

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
