### ISSUE TITLE
[Question] attribute in a table

### ISSUE THREAD

**Issue by ambreLy** [3liz/lizmap-web-client#534]
Hello,

I have a question, in my project Lizmap, I don't arrive to see the data of one of my layers. I can't see this attributes when I click on 'data'. But I can see the data of the others layers. I wonder if it's because there too much data in this layer? 

Thanks for help :)

**Comment by jlstanus** [comment]
Give precisions, type of file/ DB, how many lines, columns.. Tks

**Comment by ambreLy** [comment]
The table was created in postgresql, in a schéma with 14 others tables. There are 19 columns and 560 lines.

**Comment by rldhont** [comment]
Which QGIS Server version ? Which Lizmap Web Client version ?

**Comment by ambreLy** [comment]
I use the Lizmap version 3.1rc1 and I think the Qgis server version 1.3.0.

**Comment by rldhont** [comment]
To help you, please update QGIS Server to the LTR version 2.14. We can't help you with a so old version which probably not have WFS support.

**Comment by ambreLy** [comment]
Oh sorry I was wrong I use the Qgis version 2.14.

**Comment by nboisteault** [comment]
@ambreLy Reopen if issue still occurs.
