### ISSUE TITLE
base layer - zoom to layer extent

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#535]
hi

zoom to layer extent doen't work on base layers

thanks

**Comment by josemvm** [comment]
hi @rldhont 

sorry, i can't see the result of this bugfix...

when i discovered this bug, i was using custom base layers (raster type)
now with the same project the (i) doesn't display the baselayer info panel

**Comment by rldhont** [comment]
For external base layers, the zoom button is zooming to the max extent.
For other base layers, I reopen the issue.

**Comment by rldhont** [comment]
Hi @josemvm 

I have tested with Districts as baselayer and I have no issue:
* the info panel opens
* the zoom button zooms to the extent

Can you do an other test, and provide an example ?

**Comment by josemvm** [comment]
hi @rldhont 

i have tested with a vector layer too and all works fine but when i try with a raster layer it doesn´t work
if you can try a raster layer, i think you can see the problem

thanks

**Comment by josemvm** [comment]
hi @rldhont 

my tests with a LWC 3.1.1 fresh install

2 layers: one vector layer and another raster layer

- vector layer as baselayer:

![bl_v](https://cloud.githubusercontent.com/assets/10053874/25216026/82574922-2598-11e7-9ac9-a08e3a770cee.jpg)

everything (zoom to layer extent, opacity and documentation) works fine for both layers

---
- raster layer as baselayer:

![bl_r](https://cloud.githubusercontent.com/assets/10053874/25216027/825faaae-2598-11e7-8424-811e9929d1d3.jpg)

it's not possible to get information (i) from baselayer (**raster layer as baselayer**)


thanksfor your attention

**Comment by rldhont** [comment]
I have made a little update fbe37c0
@josemvm can you test it ?

**Comment by josemvm** [comment]
one raster layer as not a base layer, the zoom to layer extent function works fine

the same raster layer as a base layer (keeping all other settings):

![zzz](https://user-images.githubusercontent.com/10053874/26950546-e2564070-4c95-11e7-9505-9a480498951e.jpg)

- now, it's possible to get information from raster layer as baselayer but not close (close button) the information panel
- the zoom to layer extent function doesn´t work

**Comment by rldhont** [comment]
@josemvm can you provide an example, that I can check the problem ?

**Comment by josemvm** [comment]
hi @rldhont 
please, check your email

**Comment by rldhont** [comment]
@josemvm you can update your lizmap with f99590a
