### ISSUE TITLE
Spatialite problem

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#536]
Hi, 
I got a problem when i try to use Spatialite : 

> PHP Warning:  SQLite3::loadExtension(): The specified module could not be found.

I set on my php.ini "sqlite3.extension_dir", "enable_dl" to on and put mod_spatialite.dll (and all necessary libraries) in.

PHP version : 7.1
SQlite : 3.15.1
Windows server 2012 with Apache

Can you help me ?

**Comment by Spitfiire** [comment]
Ok now i got a new problem : 

>SQLite3::query(): not authorized in

but i don't know how to set rights on windows server

**Comment by rldhont** [comment]
Does SQLite3 is well installed?

**Comment by Spitfiire** [comment]
Yes, i got this message : 
>SQLite3::query(): not authorized in

I'm on windows server

**Comment by rldhont** [comment]
Can you provide more log text ?
`SQLite3::query(): not authorized in` is not enugh to help you

**Comment by Spitfiire** [comment]
I try to load spatialite with a test page.

```
<?php
$db = new SQLite3(':memory:');

$db->query("SELECT load_extension('mod_spatialite.dll');");

# reporting some version info
$rs = $db->query('SELECT sqlite_version()');
while ($row = $rs->fetchArray())
{
  print "<h3>SQLite version: $row[0]</h3>";
}
$rs = $db->query('SELECT spatialite_version()');
while ($row = $rs->fetchArray())
{
  print "<h3>SpatiaLite version: $row[0]</h3>";
}
?>

```

and in log : 

```
mod_fcgid: stderr: PHP Warning:  SQLite3::query(): not authorized in X:\\My\\Dir\\Test\\Lizmap\\www\\SpatialiteSample.php on line 4
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 {main}
```

Test Page return the Sqlite3 version (3.15.1)

And when i try with 
`$db->loadExtension('mod_spatialite.dll');`

I got this : 

`PHP Warning:  SQLite3::loadExtension(): Unable to open extensions outside the defined directory in X:\\My\\Dir\\Test\\Lizmap\\www\\SpatialiteSample.php on line 4`

**Comment by rldhont** [comment]
Can you test with an sqlite file and not a memory database ?

**Comment by Spitfiire** [comment]
Same problem,  `SQLite3::query(): not authorized in mod_fcgid: stderr: PHP Warning:  SQLite3::query(): not authorized in X:\\My\\Dir\\Test\\Lizmap\\www\\SpatialiteSample.php on line 4`

when i put `$db->query("SELECT load_extension('mod_spatialite');");`

And when i put  : `$db->query("SELECT load_extension('mod_spatialite.dll');");`

I got this message : 

```
 [fcgid:warn] [pid 3404:tid 964] (OS 109)The pipe has been ended.  : [client IP] mod_fcgid: get overlap result error
[core:error] [pid 3404:tid 964] [client IP] End of script output before headers: test.php
```

**Comment by Spitfiire** [comment]
I still have no solution

**Comment by FRANCOSIBILLINI** [comment]
I have the same problem. Did you solved??

windows 7 - apache 2.4 - php 5.6.3.4 (NTS) fast CGI - mod_spatialite-4.3.0a-win-x86
