### ISSUE TITLE
Print on lizmap

### ISSUE THREAD

**Issue by CARUN974** [3liz/lizmap-web-client#537]
Hi,

I have installed Lizmap and Qgis server on my server (Windows 2008 R2)
All is right, many project are online

But when i use the print function, the background map is not visible.

Someone have a solution please?

Best regards,

**Comment by rldhont** [comment]
Which Lizmap version do you use ?

**Comment by rldhont** [comment]
Did you define a layer like defined here https://docs.3liz.com/en/publish/advanced_lizmap_config.html#allow-printing-of-external-baselayers ?

**Comment by CARUN974** [comment]
Hi,

I have 3.1pre.0001 version

It's works whith your link.

Thank you
