### ISSUE TITLE
cache generation pb - lizmap 3.1.0 upgrade

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#538]
I have an issue after upgraded to 3.1.0.

The cache seems to be ok (tiles are generated) but lizmap seems not to load cached files. Rasters loading is very slow, exept when tiles are in client browser's cache. But, after a cache reset (browser's cache), it becoms very slow again and server's CPU is very busy (closer to a tile generation than a simple pre-generated tile I think.).

I reset server cache et generated it again : same result. This is not a bandwith problem (bandwidth between server & client is approximatively of 945 Mbits/sec).

Any idea ?
Thanks in advance

**Comment by geodatup** [comment]
Did you configure correctly your Lizmap project in the Qgis's plugin interface ?
there is a check box to make request from cache.

I didn't try on the 3.1 but it worked fine before.

**Comment by loic74** [comment]
I rebooted the server and reset the server's cache again. It solved the problem... Don't know why but it works.

Thanks anyway for your help ;-)

**Comment by geodatup** [comment]
you're welcome,
good to know the tricks,

thanks

**Comment by loic74** [comment]
I reopen this issue cause it is not solved.

I made some changes on vector tables in a project (just group as layer in Lizmap plugin). I uploaded files on server and... the project lags a lot.  After a browser's cache reset, cache not works for this project (lags...) but continue working for other projects...

I don't have changed anything else...

Need help !

**Comment by nboisteault** [comment]
@loic74 does your issue still occur ?

**Comment by nboisteault** [comment]
@loic74 I close this issue. Reopen if needed.
