### ISSUE TITLE
Problem with update of lizmap on debian 8.7

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#539]
I update lizmap from 2.9.X to  lizmap 3.1 (or 3.0.12) on a debian 8.7 server. 

I see all the old repositories and users, but when I try to view a QGIS project from admin (or different user)  I have an error if I am logged in. Setting view permission of repositories for anonymous I view correctly the project of the repository. 

I do not find any info from the log of lizmap  and the error is a generic error 500 "Error 500. A technical error has occured. Sorry for this trouble."

It seems an error of the jauth.db file. Perhaps a problem of sqlite /sqlite3??

But I do not find the old script in order to update the db

**Comment by nboisteault** [comment]
@rmarzocchi84 Reopen if issue still occurs.
