### ISSUE TITLE
relations in lizmap

### ISSUE THREAD

**Issue by naoM** [3liz/lizmap-web-client#540]
Hi,

I would like use relations between tables in my published lizmap project.

Relations are needed because they allow me to manage many-to-one relations

They work fine in QGis, but they do not show up in lizmap.

I found one GitHub lizmap relation issue: https://github.com/3liz/lizmap-web-client/issues/225 but the problem seems to be closed.

Does any one already used this feature ? Am I missing something in the lizmap project ?

Thanks for you help / tips / ideas...

Regards,

Naomi

**Comment by nboisteault** [comment]
Hi,
Which version of QGIS Server and lizmap do you use? Have you enabled WFS for your related layers?

**Comment by naoM** [comment]
Hi Nicolas,

WFS is enabled

I use the last stable lizmap docker container (https://github.com/jancelin/docker-lizmap)

My child layer is a ".txt" (attribute layer only, no geometry).

**Comment by naoM** [comment]
the problem remains if the txt layer is converted into a dbf

**Comment by nboisteault** [comment]
Please give us QGIS Server and lizmap version.

**Comment by mdouchin** [comment]
The best would be to have a reproductible case, for example with a project and a lizmap config. Or an URL to check the issue in real context

**Comment by naoM** [comment]
The versions are
- lizmap web client 3.0.3
- Qgis server 3-2.14 (LTR)

**Comment by naoM** [comment]
minimal (not working) example: [lizmap_example.zip](https://github.com/3liz/lizmap-web-client/files/844012/lizmap_example.zip)

**Comment by naoM** [comment]
does any body has a working example for relations in lizmap ? 

Regards,

**Comment by josemvm** [comment]
hi @naoM 

you have the montpellier project example, like districts/quatier and sous-quartiers. you can check the montpellier.qgs and montpellier.qgs.cfg files.

**Comment by Gustry** [comment]
Indeed, it's working as expected with `Value Relation widget`. I will go and check the lizmap documentation. Thanks.

These widgets are so similar. I think I was mixed with translation not 100% correct between these widgets with QGIS in french and documentation in English.

**Comment by nboisteault** [comment]
Fixed in LWC 3.2.
