### ISSUE TITLE
Update Lizmap

### ISSUE THREAD

**Issue by CARUN974** [3liz/lizmap-web-client#542]
Hi,

How to update Lizmap from 3.1pre.0001 to the new version?

Thanks for you help

**Comment by rldhont** [comment]
it's quite simple if you already are in 3.1 branch:
* download the release
* extract the content and paste in your lizmap directory
* `lizmap/install/set_rights.sh www-data www-data`
* `sudo lizmap/install/clean_vartmp.sh`
* `php lizmap/install/installer.php`
* `lizmap/install/set_rights.sh www-data www-data`

Please help us enhance documentation: https://github.com/3liz/lizmap-documentation

**Comment by CARUN974** [comment]
Thanks. 

I'm on Windows Server so i run the installer.php?

**Comment by rldhont** [comment]
The import command is `php lizmap/install/installer.php`. It will apply changes.

**Comment by CARUN974** [comment]
Ok thanks a lot for your help.
