### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by CARUN974** [3liz/lizmap-web-client#543]
Hi,

I don't modify my Lizmap config and its not possible to see a map
The message "Service non disponible" appear

Thanks for your help!

**Comment by rldhont** [comment]
This mean that QGIS Server does not return the Capabilities.
Take a look at the XHR requests, with your browser dev tools.
Verifying the QGIS Server URL and test it.

**Comment by CARUN974** [comment]
If i run qgis_mapserv.fcgi.exe in a terminal i have the erroe 0xc000007f. application can't start

**Comment by CARUN974** [comment]
If i test the URL:
http://localhost/qgis/qgis_mapserv.fcgi.exe

I have:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by nboisteault** [comment]
@CARUN974 does this issue still occur ? Reopen issue if needed.
