### ISSUE TITLE
INSTALL instructions: `php-xml-rpc` mentioned, maybe unnecessary?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#544]
In the INSTALL instructions the above package is mentioned as necessary, but apparently Lizmap works well without it. Furthermore, in Debian there are several similar packages ( php-xml-rpc, php-xml-rpc2, php5-xmlrpc), and it is unclear which one would eventually be the correct one.
Could you please check and update the instructions?
Thanks.

**Comment by rldhont** [comment]
@laurentj if you have some explanations ?

**Comment by mdouchin** [comment]
Have you tried  php-xmlrpc ?

**Comment by pcav** [comment]
I have not installed any of the packages on a new server, which appears to work well, except for issues on Google layers and group management which can be unrelated.

**Comment by laurentj** [comment]
Since lizmap doesn't use classes from Jelix for XML-RPC , instruction in the document is useless..
