### ISSUE TITLE
Lots of issues with Lizmap 3.1 / qgis server 2.18

### ISSUE THREAD

**Issue by loic74** [3liz/lizmap-web-client#547]
Hi,

Since Lizmap was upgraded to 3.1 with qgis server 2.18 I have a lots of issues:

- got server error when printing -> solved with the help of this page http://www.itopen.it/qgis-server-setup-notes/
- like in issue #531, printed layout appears with grids.
- labels as truncated in every layers, like if layer was tiled, which is not the case
- users cannot edit layers while rights are well difined in Lizmap parameters (groups, users) and qgis Lizmap plugin (authorised groups)

Thanks,
Loïc

**Comment by rldhont** [comment]
@loic74 can you better describe the point:
> users cannot edit layers while rights are well difined in Lizmap parameters (groups, users) and qgis Lizmap plugin (authorised groups)

Is it spatialite layers or postgis layers ?

**Comment by loic74** [comment]
Sure. Edition rights are well difined in layer edition (Lizmap qgis plugin), Qgis OWS parameters, Lizmap administration (users rights) and PostgreSQL. And I work with postgis layers.

All is functional with 3.0.3 version

**Comment by Cec78** [comment]
Hi,
I also get a "server error when printing" with Lizmap 3.2pre170303 and QGIS Server 2.18.6.
I didn't try "http://www.itopen.it/qgis-server-setup-notes/" already, I will do this as soon as possible.
Céc.

**Comment by cimbach** [comment]
Hi
Isn't the print problem the same as this?
https://github.com/3liz/lizmap-web-client/issues/483
https://github.com/qgis/QGIS/pull/4035

If so, it is related to the QGIS server version > 2.14 which broke both QGIS and Lizmap Web Clients.

One told me (forgot who sorry) on the QGIS IRC channel that:
QGIS 2.14 is the LTR and QGIS Web CLient or lizmap 3 are designed to use it

Thx for the itopen.it link btw!

**Comment by Cec78** [comment]
OK. I also have problems in Lizmap with the Time manager tool.
Can somebody tell me if we can use Qgis 2.18.6 with Lizmap 3.X or not?
Thank you!

**Comment by mdouchin** [comment]
It is not advised to use QGIS 2.18 server-side, as it is not the LTR yet, and has not yet been fully tested in the server context.

We at 3liz and other QGIS devs will propose QGIS enhancement and bug fixes. In between, you should use 2.14 instead.

**Comment by Cec78** [comment]
OK, thank you!

**Comment by rldhont** [comment]
For QGIS Server 2.18 user, Lizmap 3.0 and 3.1 has been fixed: GetPrint, GetFeature and Time mannager.
Feedback are welcomes!

**Comment by Cec78** [comment]
Thank you for the information!

**Comment by cimbach** [comment]
> For QGIS Server 2.18 user, Lizmap 3.0 and 3.1 has been fixed: GetPrint, GetFeature and Time mannager. Feedback are welcomes!

Print is not working here.
Ubuntu 16.04.3 LTS _(server version)_
qgis-server                          1:2.18.11+24xenial                         amd64
<qgis projectname="Projet de base LIZMAP" version="2.18.11">
lizmap version: HEAD detached at 3.1.3

Print button opens a new windows which shows: Internal Server Error

Apache error log:
[fcgid:warn] [pid 17466] [client 127.0.0.1:59434] mod_fcgid: error reading data, FastCGI server closed connection
[core:error] [pid 17466] [client 127.0.0.1:59434] End of script output before headers: qgis_mapserv.fcgi
[fcgid:error] [pid 17436] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(17448) exit(communication error), get signal 11, possible coredump generated

lizmap error log:
-

Did I miss something?

**Comment by mdouchin** [comment]
fix the editing of layer with empty "Allowed group" : cb317e42  
this will be available in next 3.1 bugfix release 
this is not yet merge in master

**Comment by rldhont** [comment]
@loic74 does lizmap still have issues with QGIS Server 2.18 ?
Can I close this issue ?

**Comment by loic74** [comment]
@rldhont Sorry, I couldn't tell you. I reinstalled 2.14 version. Since everything is functional, I didn't update the server...

**Comment by gioman** [comment]
> @loic74 does lizmap still have issues with QGIS Server 2.18 ?
> Can I close this issue ?

@rldhont one question partially related to this ticket: in QGIS Desktop 2.18 print layouts the legend option "map" cannot be set anymore to "none", you have to set this option to an existing map object. Setting it to "none" in QGIS 2.14 allowed to do getprint requests and in the output have a legend that was/is fixed. How this can be achieved in 2.18? I'm possibly missing some new way to do it? Thanks!

**Comment by gioman** [comment]
> Still facing the internal server error when trying to print (PDF/JPG/PNG/SVG) with the following configuration:

@cimbach you must install a fake xserver. With QGIS 2.18 this become a requirement on Linux Desktop too (it was already on a headless server installation): https://www.itopen.it/qgis-server-setup-notes/

**Comment by cimbach** [comment]
Thanks @gioman, I finally get the print working on my desktop Ubuntu.
Following your link was still giving me a servor error as soon as _FcgidInitialEnv DISPLAY ":99"_ was added either to /etc/apache2/mods-enabled/fcgid.conf or to  /etc/apache2/sites-enabled/000-default.conf
Then I found out this issue https://github.com/3liz/lizmap-web-client/issues/432 where @rldhont kindly add that this final step was also needed: `Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &`

Unfortunately, no way my sys admin will agree doing the same on our Ubuntu server for stability and security reasons...

**Comment by gioman** [comment]
> Unfortunately, no way my sys admin will agree doing the same on our Ubuntu server for stability and security reasons...

@cimbach I understand, and this raises the question about why this is not yet a dependency for the qgis server installer/package...
