### ISSUE TITLE
[question] LWC - multiple domains (not subdomains)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#549]
what is the best way to have multiple domains on a linux ubuntu server, apache/virtual hosts?

- an independent installation per domain?
- an independent installation per domain - using symbolic links to the main installation, except for folders /install, /var/config, /var/db (and others like themes, ...)?
- ...

thanks

**Comment by josemvm** [comment]
i' m doing some tests and in the future i will give my own feedback on this matter

**Comment by nboisteault** [comment]
Hi josemvm,
I use several apache virtual hosts and only one installation for all domains.

    <VirtualHost *:80>
        DocumentRoot /var/www/html/
        ServerName yourdomain.fr
        DirectoryIndex lizmap-web-client/lizmap/www/index.php/view/map/?repository=yourrepo&project=yourproject
    </VirtualHost>

**Comment by josemvm** [comment]
hi @nboisteault 

thanks for sharing your knowledge

is it possible one apache virtual host for one repository (not for one repository/project), like this: (?)

`lizmap-web-client/lizmap/www/index.php/view/map/?repository=yourrepo`

**Comment by nboisteault** [comment]
If you then add `&project=yourproject` in urls, I think it will work.

**Comment by josemvm** [comment]
i'm talking about the possibility of relating a virtual host with all the projects of a repository

`lizmap-web-client/lizmap/www/index.php/view/map/?repository=yourrepo`

but it doesn't work on this way...

**Comment by josemvm** [comment]
if you try with `lizmap-web-client/lizmap/www/index.php/view/map/?repository=yourRepo`

you get:
![imagem](https://user-images.githubusercontent.com/10053874/81163156-383af900-8f86-11ea-847f-252b9ce0f1f3.png)

**Comment by nboisteault** [comment]
@josemvm there is no page showing only projects for a given repository, please open an issue asking for this feature.
