### ISSUE TITLE
Responsive layout problem

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#550]
Lizmap should be fully responsive interface, adapting contents both for desktop and mobile. 
I used HTML in Repository's "Title", sizing and positioning items based on my browser's view, and it works well (I see good interface both with Microsoft Edge and Mozilla Firefox). Using another desktop PC I see a good interface with one browser (Microsoft Edge) and a bad interface with Mozilla Firefox. Some users complain about bad views, other see the webpage with good interface. 

This is what I'm talking about

Good interface
![good](https://cloud.githubusercontent.com/assets/20582012/24295286/4ed378a4-109a-11e7-9360-79463b70a819.JPG)
Bad inteface:
![bad](https://cloud.githubusercontent.com/assets/20582012/24295296/5b6e8c02-109a-11e7-884c-5ba2628a4d0a.JPG)

I cannot understand why only in some machines responsive design works good.

**Comment by rldhont** [comment]
Thansk for your feedback.
It's a CSS issue. I think that the city image force the header height in the first size and not in the second. The second (bad) is the default behavior.
What is the size of the web page ?

**Comment by virtusmankind** [comment]
Are you talking about screen resolution? I use 1366x768 px both in 15,6'' laptop (with bad behavior) and desktop (with good behavior and bigger monitor).

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
