### ISSUE TITLE
Question sur la définition de la table pivot dans Lizmap

### ISSUE THREAD

**Issue by ClaireSeard** [3liz/lizmap-web-client#553]
Bonjour à tous,

Je suis en train de faire un projet Lizmap sur des réseaux d'eaux pour que les utilisateurs puissent mettre à jour les données attributaires des réseaux. Le projet Qgis associé inclut de nombreuses tables avec des liaisons relationnelles gérées dans l'onglet relations des propriétés du projet. J'aimerais que ces relations soient prises en compte dans le projet Lizmap et je me questionne sur le rôle des tables pivots.

Je ne comprends pas bien la notion de 'table pivot' dans Lizmap.  Dans le fichier de configuration de Lizmap, dans l'onglet outils, lorsque l'on ajoute des couches dans le tableau 'Table attributaire', on peut cocher 'table pivot'. Dans quel cas faut-il cocher cela? 

Je vous remercie d'avance pour vos réponses,
Claire,
Le Grand Narbonne

**Comment by nboisteault** [comment]
Bonjour Claire,
Avez-vous lu la partie de la documentation sur la [fonctionnalité table pivot](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#using-relations-with-the-attribute-layers-tool)?

**Comment by ClaireSeard** [comment]
Bonjour Nicolas,
oui je l'ai lu mais je n'étais pas sûre de la compréhension. Il me semble que c'est une table 'intermédiaire' qui relie 2 tables majeures et inclut les identifiants de ces 2 tables.
Merci,
Claire

**Comment by nboisteault** [comment]
Bonjour Claire,
Oui c'est cela. Les tables pivots sont utilisées lorsqu'on veut créer une relation many-to-many (N:M) entre 2 tables. Pour info, ni QGIS ni Lizmap ne gèrent pas les relations N:M dans les formulaires **en utilisant une table pivot**.
 Il est malgré tout possible de créer ce type de relation avec le widget 'valeur relationnelle' en cochant 'Permettre les sélections multiples' mais cela se fera à l'aide d'une colonne supplémentaire de type array dans la table 1 qui permet d'y stocker les identifiants de la table 2. Même si l'utilisation d'une table pivot est une bonne pratique, si cela ne pose pas de problème dans votre schéma de données vous pouvez optez pour ce choix.
Ce que je viens de dire est valable pour les formulaires mais Lizmap permet malgré tout, d'après la doc ci-dessus, de gérer les tables pivots dans la partie 'table attributaire'.

**Comment by ClaireSeard** [comment]
Merci Nicolas pour ces informations complémentaires

**Comment by nboisteault** [comment]
Petite mise à jour.
Il est normalement possible de créer des relations N:M dans QGIS depuis la version 2.18 ([doc](http://docs.qgis.org/2.18/en/docs/user_manual/working_with_vector/attribute_table.html#n-m-relation)), malheureusement je n'ai pas réussi à les faire fonctionner. J'ai ouvert un [ticket](https://issues.qgis.org/issues/16446).
Si quelqu'un parvient à les faire fonctionner qu'il n'hésite pas  le dire.

**Comment by chanteclair12** [comment]
Hi,
I have installed on a Windows Server 2008 R2, Qgis/Qgis Server 2.14.17 LTR and Lizmap Web Client 3.1.3.
In my Qgis project, i have 2 tables with a relation one to many. It works well and i'm able to add record in the related table since the main table.
In Lizmap, I don't manage to see the records of the related table (witch is displayed) when i click on a record of the main table.
I don't understand very well the functionality of the "table pivot".
For french people, you can see : [http://www.forumsig.org/showthread.php/44464-Relation-dans-Lizmap] for more explanation.
Thx.

**Comment by nboisteault** [comment]
@chanteclair12 does your issue still occur ? Reopen issue if needed.
