### ISSUE TITLE
Insert feature by coordinates

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#554]
Hello,
we are developing a web service to insert points in some postgis layers.
Many time the user gets a paper with coordinates and not a detail map of the feature to be inserted.
And most of the times users are not able to use qgis, this is why we are going the Lizmap way..

Do you know if there is some easy way to insert by X/Y coordinates?
Is it feasable by Lizmap Web Client?

Data can come in different SRID, usually 4326 (long/lat WGS84) , 32633 (UTM33N/Wgs84) and 3004 that is an old still used italian EPSG.

Any suggestion on how to deal with this?

A web form with direct connection to PostgreSQL and ST_Makepoint function?

Thanks
Pietro

**Comment by pcav** [comment]
Il 30/03/2017 13:40, Pietro Rossin ha scritto:

> Any suggestion on how to deal with this?
> 
> A web form with direct connection to PostgreSQL and ST_Makepoint function?

Hi Pietro,
agreed, this is a more common function than I thought, especially for
people taking filed notes. I'm dealing with a similar situation,
fortunately only on the desktop for now, but it's not very obvious how
to solve it in an elegant way.
All the best.

-- 
Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html
https://www.google.com/trends/explore?date=all&geo=IT&q=qgis,arcgis

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/268

**Comment by pieri70** [comment]
Thanks Paolo
I thought to insert a button under the edit dock (guessing it's possible by themes) and this would open a form with direct database connection. 
Given user logged in, a district code to control that coordinate inserted are reasonable placed, and xy field with flag to set origin srid would permit to make an insert into postgis table.. 
I must discuss this with my IT colleagues. 
And of course it will be a custom solution, not a widely usable one.

**Comment by pcav** [comment]
I think the problem is common enough to warrant a core solution. Could you start the effort for it?

**Comment by josemvm** [comment]
> this is a more common function(s)

in this state of evolution of LWC it seems to me imperative that LWC provide a tool for **locate** and reach a point on the map by coordinates (for each of the project CRS) using multiple coordinate units:
![read](https://cloud.githubusercontent.com/assets/10053874/26283773/c295eba6-3e25-11e7-85e9-d2e8f5f66c0c.jpg)

not only this tool but also a tool for **read coordinates** of a point on the map for each of the project CRS:
![crs](https://cloud.githubusercontent.com/assets/10053874/26283738/8180e8be-3e25-11e7-90e4-f5f94293fa28.jpg)

**Comment by gioman** [comment]
> seems to me imperative

I can only assume you have a very good support contract with the 3Liz guys...

**Comment by josemvm** [comment]
hi

i'm trying to improvise this feature in an archaic way...

so, i create a table of type point with 2 fields (**longitude** and **latitude**) to provide the coordinates and a trigger in postgresql to run this function:

> NEW.the_geom = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)

![lonlat](https://user-images.githubusercontent.com/10053874/31829638-d0fe9672-b5b5-11e7-9e48-a71e38d514aa.jpg)

it works well on the qgis! i click somewhere on the map, i provide the coordinates and when i save the layer edits the point moves itself to the right place.

on lizmap (master version) when i select the layer to edition and click in the add button of edition the behavior is only an animated progress bar...

i have this error:

>2017-10-20 17:59:41     10.27.10.180    warning 2017-10-20 17:59:41     [2]     array_key_exists() expects parameter 2 to be array, null given  /var/www/html/lizmap-web-client-master/lizmap/modules/lizmap/classes/qgisProject.class.php     243

>2017-10-20 17:59:41     10.27.10.180    notice  2017-10-20 17:59:41     [8]     Undefined offset: 0     /var/www/html/lizmap-web-client-master/lizmap/modules/lizmap/controllers/edition.classic.php    179

>2017-10-20 17:59:41     10.27.10.180    error   2017-10-20 17:59:41     [0]     Call to a member function xpath() on null       /var/www/html/lizmap-web-client-master/lizmap/modules/lizmap/controllers/edition.classic.php   180

can you help me, please?
thanks in advance

**Comment by josemvm** [comment]
this is just a workaround...

**Comment by rldhont** [comment]
I think you have to test this PR  #693
