### ISSUE TITLE
LWC popups - not display the content (text or HTML) of the file for symbolic links

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#556]
hi,

as you can read in documentation https://docs.3liz.com/en/publish/advanced_lizmap_config.html#media-in-lizmap

> if the path points to a text file or HTML file, the file contents will be displayed in the popup

![popup](https://cloud.githubusercontent.com/assets/10053874/24648237/f08a1bca-191a-11e7-8973-61bb343402ef.jpg)

but if you have a text file or HTML file the popup doesn't display the file contents

qgis server and desktop 2.14.13
LWC version 3 and 3.1

**Comment by josemvm** [comment]
hi

does anyone already try to get the content of text file or html file?

**Comment by rldhont** [comment]
The content of text or html file is added to the popup if
* the file is in the media directory
* the file is ended by txt, htm or html

The documentation probably needs to be updated ?

**Comment by josemvm** [comment]
hi @rldhont 

no, the documentation is clear.

- i have my html and txt files into media folder
- the file extension is also correct for text  or htm/html files

but the content is not added to the popup.

in my test case with a field alias **Site** i have a html file with this simple code to hide and replace the big url: 
![pop-url](https://cloud.githubusercontent.com/assets/10053874/25055352/1ede3f32-215a-11e7-974b-57ceb1adbbe0.jpg)
&lt;html&gt;&lt;p&gt;
&lt;a href=&quot;http://www.ccdr-a.gov.pt/alentejoape/index.php?action=3&amp;id=55&amp;lang=1&quot; target=&quot;_blank&quot;&gt;
&lt;strong&gt;&gt;&gt;&amp;nbsp;Alentejo a P&eacute;&lt;/strong&gt;
&lt;/a&gt;
&lt;/p&gt;&lt;/html&gt;

but the content does not appear as you can see at first image above.

**Comment by josemvm** [comment]
i' m talking about `Auto popup` and not `Lizmap popup`

i have already done enough tests with this files type (.html and .txt), including with the montpellier project

sorry  @rldhont, this not a question but a bug

**Comment by rldhont** [comment]
and if you remove `html` element. Get only the `p` element ?

**Comment by josemvm** [comment]
sorry @rldhont, you are right

the problem is only related to symbolic links within the media folder
if the path to html or txt files contains a symbolic link, like this:

`media/symbolic_link_to_this_folder/file.html`

it doesn't work

it only works with real paths

thanks

**Comment by rldhont** [comment]
the bug is du to symbolic link. can you update the title issue?

**Comment by josemvm** [comment]
thanks @rldhont :-)
