### ISSUE TITLE
[Question] Comment utiliser Hierarchical Lists

### ISSUE THREAD

**Issue by ambreLy** [3liz/lizmap-web-client#557]
Bonjour,
Je travaille sur un projet Lizmap, et je cherche une fonctionnalité particulière : j'ai une table avec 2 champs, "type_action" et "objectifs". Je voudrais pouvoir faire ceci : quand je choisi un type d'action (champs "type_action") je voudrais que le champs objectifs soit filtré en fonction du type d'action choisi avant.

Je sais que sur qgis, il y a le pluggin Form value relation pour cela, mais j'ai vu dans la documentation Lizmap, dans Hierarchical Lists que c'était possible sur lizmap, seulement il y a peu de détails dans le paragraphe.
Quelqu'un peut il m'éclairer sur ce qu'il est possible de faire ou pas, et comment?
Merci beaucoup pour votre aide, bonne soirée
Ambre

**Comment by nboisteault** [comment]
Bonjour,
Avez-vous besoin de listes hiérarchiques dans un formulaire?
Auquel cas votre demande est la même que celles-ci https://github.com/3liz/lizmap-web-client/issues/350 et https://github.com/3liz/lizmap-web-client/issues/478
S'il s'agit de filtrer des valeurs qui ont un lien hiérarchique pour finalement zoomer sur une entité il s'agit bien de Listes hiérarchiques documentées [ici](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#hierarchical-lists)
Faites un essai à l'aide du plugin et remonter votre problème si vous n'y arrivez pas en précisant les versions de lizmap et QGIS Server que vous utilisez.

**Comment by ambreLy** [comment]
Bonjour,
Merci beaucoup pour votre aide. Oui il s'agit plutot d'avoir des listes hiérarchiques dans un formulaire. Donc si j'ai bien compris pour faire ceci, je peux utiliser l'outil d'édition "reference de la relation", que vous avez utilisé dans votre exemple. 
Je souhaite savoir si vous pouviez me détailler un peu plus comment vous vous y êtes pris dans votre exemple. Par exemple, à quoi correspond la "relation" que vous avez sélectionné?
J'utilise Qgis 2.14 et la version 3.1rc1 de lizmap.
Merci, Ambre

**Comment by nboisteault** [comment]
Il faut utiliser le [gestionnaire de relations](http://docs.qgis.org/2.14/fr/docs/user_manual/working_with_vector/attribute_table.html#definition-relation-manager)
Je rappelle que ceci vous sera utile dans QGIS mais que vous ne retrouverez pas le même comportement dans Lizmap. Cette fonctionnalité doit être développée.

**Comment by ambreLy** [comment]
D'accord, merci bien pour toutes ces précisions !
