### ISSUE TITLE
geolocation bug

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#558]
I encounter geolocation problems on version 3.1. Buttons gray except stop. Problem on PC, Android and iPhone. Someone else has this bug?

**Comment by gioman** [comment]
@jancelin yeah seen it... it seems to affect Chrome but not Firefox.

**Comment by jancelin** [comment]
On android7, chrome and firefox

**Comment by gioman** [comment]
@jancelin works on FF 52.0.2 here (at least on Linux).

**Comment by jancelin** [comment]
@gioman, Do you have an open lizmap project? To see if it comes from my installation 

Ans here ils mine, if you can test: http://demo.sig.inra.fr/websig/lizmap/www/index.php/view/map/?repository=demo&project=brouillon1

**Comment by jancelin** [comment]
And no problem with googlemap or geoportail,...

**Comment by gioman** [comment]
> Ans here ils mine, if you can test: http://demo.sig.inra.fr/websig/lizmap/www/index.php/view/map/?repository=demo&project=brouillon1

works here on FF.

**Comment by jancelin** [comment]
The problem must come from my side, thanks for the help
