### ISSUE TITLE
The edition tool needs a primary key on the table to be defined but table has primary key

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#559]
The editing tool was working well at the begining.
But when i edited the table, after that, the editing tool says "The edition tool needs a primary key on the table to be defined" but i have a primary key as shown.

![liznokey](https://cloud.githubusercontent.com/assets/402354/24805846/3d8aa080-1bb3-11e7-9822-8c45e16a732a.png)

Maybe the qgis server is not updated?

**Comment by rldhont** [comment]
The primary key detection is done by Jelix with this request:
```
SELECT indkey FROM pg_index WHERE indrelid = the_table_oid  and indisprimary = true
```
And the table oid is get with
```
SELECT oid, relhaspkey, relhasindex FROM pg_class WHERE relname = 'the_table_name'
```

And the primary key field has to be published in WFS.

**Comment by rmarzocchi84** [comment]
Perhaps is the same problem of my issue #783 ?

**Comment by jlstanus** [comment]
I m very sorry but i don't remrmber how i solved the problem.
@rmarzocchi84  Do you use docker?  Maybe you have to restart the container with your DB and with LWC.
