### ISSUE TITLE
Problems with sending point data to EPSG 2276

### ISSUE THREAD

**Issue by TheDude005** [3liz/lizmap-web-client#560]
So I am using an install of the 3.1 web client and I have a map with a PostGIS layer that is in EPSG 2276 which is in Texas State Plane and in feet.  When I add a point using the edition tool it saves the point and then puts the point down in Mexico.  Looking at the logs it looks like the point coordinate conversion from EPSG 3857 to EPSG 2276.  I don't know if it has to do with the meters to feet conversion but if I reverse the x and y it gets closer to where I put the point but still many miles off.  I have the QGIS project OTF from 2276 to 3857 (if I leave in in 2276 and just include 3857 it starts the map on Null Island) so I don't know if the problem is there as it seemed that the publishing instructions said it could be in any projection you wished so long as you had 3857 as an option in the OWS.

The message from my logs is:
 2017-04-10 01:37:13	::1	default	SQL =  INSERT INTO "citizenservice"."servicerequest" ("requesttype", "requestdate", "status", "globalid", "geom" ) VALUES ('Abandoned Motor Vehicle', '2017-04-09', 'Unassigned', '', ST_Multi(ST_GeomFromText('POINT(732322.7243846036 2165742.920783637)', 2276)) );

**Comment by rldhont** [comment]
Does the code `2276` in PostGIS is the id for `EPSG:2276` ?
Is not we have an issue.

**Comment by TheDude005** [comment]
Yes it is, making edits either with the PostGIS file loaded in QGIS or with it served through QGIS Server as a WFS both work.

**Comment by rldhont** [comment]
The question is: in the PostGIS spatial_ref_sys table, does the SRID of the `EPSG:2276` is `2276`?

**Comment by TheDude005** [comment]
Yes it is.  I've been using it for 3 years in PostGIS.

**Comment by TheDude005** [comment]
My point on the edits was that it was correctly editing in those environments with proper coordinates and positions.

**Comment by rldhont** [comment]
I have made this test in the browser console:
```
Proj4js.defs['EPSG:2276'] = "+proj=lcc +lat_1=33.96666666666667 +lat_2=32.13333333333333 +lat_0=31.66666666666667 +lon_0=-98.5 +x_0=600000 +y_0=2000000.0001016 +datum=NAD83 +units=us-ft +no_defs ";
ll = new OpenLayers.LonLat(-96, 32);
ll.transform('EPSG:4326', 'EPSG:3857');
ll.transform('EPSG:3857', 'EPSG:2276');
```
The result is `POINT(836219.911251411 2039775.7537763251)`
If I test this point in Postgresql/PostGIS:
```
SELECT ST_X(pt), ST_Y(pt)
FROM
  (SELECT ST_TRANSFORM(ST_GeomFromText('POINT(836219.911251411 2039775.7537763251)', 2276),4326) as pt) as p;
```
The result is `-101.695500261205 19.3045151810343`.
So the Proj4js transformation does not do the right transformation.
