### ISSUE TITLE
Localisation ne fonctionne pas.

### ISSUE THREAD

**Issue by kagou** [3liz/lizmap-web-client#562]
Bonjour,
Lorsque j'essaye avec différents projets sous lizmap, sur des serveurs différents, de me geolocaliser en utilisant safari sous ios (iphone), rien ne se passe. Les boutons Centrer et Rester Centrer ne semble pas activés (bleu clair) et ne répondent pas et seul le bouton Stop en bleu foncé fonctionne.
Ce qui est étonnant c'est que lorsque je suis sur un site web voulant savoir où je suis, j'ai toujours une alerte me demandant si j'autorise ce dernier à me localiser (bing/google map etc.) ce qui n'est pas le cas sous lizmap.

Le problème se pose également sous différents navigateurs sous Windows10. Seul Firefox me sort un popup,les autres (chrome IE opera) non. Je soupçonne donc lizmap ne pas demander comme il faut l'autorisation au navigateur

**Comment by pieri70** [comment]
Hello
may be it'a your website that isn't https..
Take a look here
https://github.com/3liz/lizmap-web-client/issues/314#issuecomment-222459621

**Comment by rldhont** [comment]
Information has been added in the documentation. https://github.com/3liz/lizmap-documentation/issues/57
To use geolocation, the website has to be secured.
