### ISSUE TITLE
media: display or download rules

### ISSUE THREAD

**Issue by daniloprocaccini** [3liz/lizmap-web-client#564]
Hi,
is there a way to choose between 1. display directly in the browser 2. activate the window with the request open or save (download) a file linked from repo/media (the "i" at the right of the name layer)? 

i have a .csv file, the same file:
linked from a website: window with the request open or save (download) is activated
linked in lizmap (repo/media the "i" at the right of the name layer): it's dispayed directly in the browser without ask if open or download it

where lizmap defines this kind of rules?
is there a simple way to define the rules for any file extensions?

Thanks

**Comment by josemvm** [comment]
hi @daniloprocaccini 

on the outside of LWC you can do this using the browser options

**Comment by daniloprocaccini** [comment]
hi @josemvm 

i don't understand why the same browser (so the same browser options) acts in a different mode on the same file.
i have a .csv file, the same file:
- linked from a website (http://www.agenziacoesione.gov.it/opencms/export/sites/dps/it/documentazione/Aree_interne/Marche/MARCHE_-_Indicatori_per_la_DIAGNOSI_APERTA.csv): window with the request open or save (download) is activated
- (i downloaded it from the website http://www.agenziacoesione.gov.it/opencms/export/sites/dps/it/documentazione/Aree_interne/Marche/MARCHE_-_Indicatori_per_la_DIAGNOSI_APERTA.csv and) linked it in lizmap (repo/media the "i" at the right of the name layer): it's dispayed directly in the browser without ask if open or download it

(i've already compress it into zip file and it works, but i would know if there is another way to do this without using archives formats)

thanks

**Comment by josemvm** [comment]
hi @daniloprocaccini 

i'm using the mozilla firefox browser

i have tested some examples of file formats (including the .csv extension) and LWC (also in (i)/documentation particular case) always respects the browser options and their actions defined for each file format

**Comment by nboisteault** [comment]
@daniloprocaccini Reopen if issue still occurs.
