### ISSUE TITLE
process(new jClassicRequest()); 

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#567]
Hi,

I tried to install Lizmap Web Client 3.1 today on an Ubuntu 16.04 machine, with PHP 7.0.
After it's done, I have troubles to access the Lizmap client in my browser, here is the only thing I can see:
process(new jClassicRequest()); 
Can you help me? Maybe I didn't install something very important :-)

Thank you in advance.
Regards.
Cec.

**Comment by Cec78** [comment]
To complete my question, here are all the php modules installed, (I think it's maybe a problem around PHP?)
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by rldhont** [comment]
You probably do not correctly configure Apache and PHP.

**Comment by Cec78** [comment]
Yes it's absolutely that.
I 've just set Apache and php as it is indicated here and it works:
https://docs.3liz.com/fr/install/linux.html#generic-server-configuration
Thank you and regards.
Cec.
