### ISSUE TITLE
TypeError: e is undefined OpenLayers.js (line 1081, col 257)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#568]
Hi, not sure if this is a bug report or something wrong here.

Resume:
LM project published on a server with both OSM and Google baselayers (OSM by default). Is all ok when the project/map is visualized using the IP of the server in the URL.

If the same project/map is visualized using a domain name, then switching from OSM baselayers to Google results in no map being shown possibly because of this JS error

```
TypeError: e is undefined
OpenLayers.js (line 1081, col 257)
```

the error does not happen if using the IP.

Any hint would be appreciated.

**Comment by rldhont** [comment]
Do you have a key for this domain ?
Google has hardened its rules about Maps licence.

**Comment by gioman** [comment]
@rldhont thanks for the feedback! It was indeed that the issue. The error message and the very long list of possible google maps api keys got me confused.
