### ISSUE TITLE
[Question] Génerer un message d'erreur pour les utilisateurs

### ISSUE THREAD

**Issue by ambreLy** [3liz/lizmap-web-client#570]
Bonjour,
Je travaille sur un projet Lizmap. Je cherche une fonctionnalité particulière : je travaille sur les formulaires que les utilisateurs vont remplir lors de la création d'un objet sur la carte, et je souhaiterais rendre obligatoire la saisie de certains champs du formulaire. Dans l'idéal, j'aimerais qu'un message d'erreur soit envoyé à l'utilisateur si certains champs ne sont pas remplis.
J'ai regardé du côté des triggers (sur postgresql), avez-vous des pistes pour une solution?
Merci beaucoup pour votre aide,
Ambre

**Comment by rldhont** [comment]
Bonjour,
Il vous suffit de préciser dans QGIS que la valeur des champs en question doit-être non null.

Je vous invite à participer à la documentation https://github.com/3liz/lizmap-documentation et à sa traduction https://www.transifex.com/3liz-1/lizmap-documentation/

**Comment by ambreLy** [comment]
Bonjour, j'ai cherché mais je ne trouve pas, dans 'propriété' de la couche et 'champs'?
Merci pour les liens

**Comment by josemvm** [comment]
hi @ambreLy 

see here:
https://docs.3liz.com/fr/publish/advanced_lizmap_config.html?highlight=null
"To make the field compulsory you have to define it as NOT NULL in the properties of the table, at the database level."

**Comment by ambreLy** [comment]
Hello, thanks for your ansmwer josemvm, it works. 
Un peu sur la même lancée, je cherche à générer une erreur sur lizmap si 2 champs en particulier sont remplis, je veux que l'utilisateur ne puisse en remplir qu'un seul sur les 2. J'ai été regardé encore la du côté des triggers, si quelqu'un a une idée :) merci beaucoup!

**Comment by nboisteault** [comment]
Bonjour,
En SQL vous pouvez aussi voir du côté des [contraintes](https://www.postgresql.org/docs/9.4/static/ddl-constraints.html).
Côté client il faudra écrire un script [javascript](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html?highlight=null#adding-your-own-javascript) pour afficher un message si la condition n'est pas valide.
