### ISSUE TITLE
[Lizmap 3.1.1] Time Manager doesn't launch

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#573]
Hello,
I'm trying to test the Time Manager tool in Lizmap 3.1.1, on an Ubuntu 16.04 VM.
My data are stored as EPSG 3857 tables in Postgis and are very light.
My Lizmap maps work without any problem, but I simply can't lauch the Time Manager: I waited for minutes while "Loading Map data" but nothing hapenned.
Thank you in advance for your help.
Céc.

**Comment by pcav** [comment]
Il 02/05/2017 14:08, Cec78 ha scritto:
> Hello,
> I'm trying to test the Time Manager tool in Lizmap 3.1.1, on an Ubuntu
> 16.04 VM.
> My data are stored as EPSG 3857 tables in Postgis and are very light.
> My Lizmap maps work without any problem, but I simply can't lauch the
> Time Manager: I waited for minutes while "Loading Map data" but nothing
> hapenned.

Not yet tested on 3.1.1, but on 3.1.1 it works correctly.
All the best.
-- 
Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html
https://www.google.com/trends/explore?date=all&geo=IT&q=qgis,arcgis

**Comment by Cec78** [comment]
Does anyone else encountered a problem on 3.1.1 and could help me?
Paolo, you may want to say "on 3.1.0 it works correctly."?

**Comment by josemvm** [comment]
hi @Cec78 

on LWC 3.1.1 everything works fine
see here time manager configuration: https://vimeo.com/83845949

**Comment by josemvm** [comment]
time manager doesn't launch if you have a blank spaces in layer name/QGIS project

**Comment by Cec78** [comment]
Hello, Thank you for you answers. I will check the names of my layers.
