### ISSUE TITLE
https: Mixed content

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#574]
hi,
I pass my docker-lizmap in https (with nginx-proxy and let's encrypt):
I saw that the logo_footer.png goes in http and not in https. So I get mixed content and therefore an unsafe connection.

I solved the problem by commenting on logo_footer.png in ./lizmap/modules/view/templates/map.tpl and ./lizmap/modules/view/templates/main.tpl

```
<!--      {image $j_themepath.'css/img/logo_footer.png'} -->
```

I have not yet found where is this variable http ???

I also saw that the "OSM Stamen Toner" also goes into http while OSM is well in https

**Comment by jancelin** [comment]
@rldhont 

```
rm -r ./temp/lizmap/www
``` 

 Does not change the problem...

**Comment by rldhont** [comment]
For the images, HTTPS, is detected by Jelix with this code
```php
(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] && $_SERVER['HTTPS'] != 'off');
```
Does the server config force to do not have https ?

**Comment by rldhont** [comment]
@jancelin I have fixed stamen, can you check your config ?

**Comment by loic74** [comment]
Hi,
I have the same problem (mixed content with logo_footer.png). Lizmap is on a simple http server behind an https proxy. I have turned checkHttpsOnParsing off in lib/jelix/core/defaultconfig.ini.php, but it's not working either...

Any idea ? Thanks.

**Comment by rldhont** [comment]
yes, you have to lie to PHP by adding environmental param in your vhost:
```
HTTPS ON
SERVER_PORT 443
```

**Comment by loic74** [comment]
Thanks, it's works fine ;-)

**Comment by jlstanus** [comment]
@loic74  Where do i write 
`HTTPS ON
SERVER_PORT 443`
?
in apache site.conf? or mainconfig.ini.php ?
Maybe it could solve #695

**Comment by loic74** [comment]
@jlstanus In apache site.conf ;-)
It could maybe solve #695

**Comment by jlstanus** [comment]
@loic74  Sorry but, could you show antract? with this parameters, its crashing.
Thks

**Comment by loic74** [comment]
@jlstanus Sure. Like this:
`SetEnv HTTPS on`
`SetEnv SERVER_PORT 443`

**Comment by laurentj** [comment]
This is a bug in Jelix I need to fix. We should not have to set HTTPS and SERVER_PORT variable.

**Comment by laurentj** [comment]
In Lizmap 3.0.18 and 3.1.6 you can fix this issue by setting the parameter `forceProxyProtocol` in your localconfig.ini.php, if lizmap is accessible behind an https reverse proxy.

```
forceProxyProtocol=https
```

It says that the public access of the reverse proxy is in https, so Lizmap/Jelix will generate url with `https://`.


Reminder: if you want to change settings in mainconfig.ini.php, set new values into localconfig.ini.php. Do not change anything in mainconfig.ini.php ;-)

**Comment by laurentj** [comment]
Documentation done. https://github.com/3liz/lizmap-documentation/commit/b89e1e98bff569321158548906bfe34326acad43
