### ISSUE TITLE
Tab in popup

### ISSUE THREAD

**Issue by Spitfiire** [3liz/lizmap-web-client#575]
Hi,

I search a solution to display tab in popup like when you edit a layer, you can see an example on :
http://carto.aduga.org/index.php/view/map/?repository=observatoire&project=friche_grd_amienois

Thanks

**Comment by rldhont** [comment]
You have to use the QGIS tooltip with bootstrap css classes.

**Comment by Spitfiire** [comment]
Nice thanks !

**Comment by josemvm** [comment]
hi @Spitfiire and @rldhont 

can you share with us some example?

thanks

**Comment by abodsalas** [comment]
> hi [@Spitfiire](https://github.com/Spitfiire) and [@rldhont](https://github.com/rldhont)
> 
> can you share with us some example?
> 
> thanks

Just for anyone to whom this might be useful:

I'm using QGIS 3.34 with Lizmap Web Client 3.8.4
I detected that the Bootstrap being used is: Bootstrap 2.3.2

1) In the Lizmap Plugin → Layers → Select Layer to show Map Tip → Enable Popup → Source: QGIS HTML Maptip

2) Select Layer on QGIS's Layers panel, right clic → Properties → Display
2.1) Enable Map Tips
2.2) Content of "HTML Map Tip":

```
<ul class="nav nav-tabs">
  <li class="active"><a href="#tab1" data-toggle="tab">Tab 1</a></li>
  <li><a href="#tab2" data-toggle="tab">Tab 2</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="tab1">
    Content 1
  </div>
  <div class="tab-pane" id="tab2">
    Content 2
  </div>
</div>
```
