### ISSUE TITLE
Third part WMS block Map Loading 

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#577]
Hello.
I'm running Lizmap 3.1.1. and QGis Server 2.18, I notice a strange bug. When in my project I use some WMS as basemap (using "Obtain images directly from server" in Lizmap Plugin), map stucks on loading, with layer panel blocked as shown in figure attached. 
![bug](https://cloud.githubusercontent.com/assets/20582012/25800551/1ec90cbe-33ea-11e7-91a4-e0cdd77fc841.JPG)

Removing WMS I can load the map. Adding WMS without "Obtain images directly from server" it works. In early versions (Lizmap until 3.0.7 with QGis Server 2.14) this options won't stuck maps.
It could be relate to [https://github.com/3liz/lizmap-web-client/issues/492](url) issue?

**Comment by gioman** [comment]
Recently QGIS server also lost the ability to cascade WMS servers working with https. An upstream ticket has also been filed.

**Comment by nboisteault** [comment]
@virtusmankind  Do you have a public link to your interface to show us the issue?

**Comment by virtusmankind** [comment]
@nboisteault I fixed the maps, so unfortunately I do not have a public link to a stuck map. If the problem will come again, I'll post a link with the interface. Try to publish yourself a map with a basemap with "Obtain images directly from server" if you can!
I notice that some maps, with projects running in LM 3.0.7 and QGis Server 2.14, stucks on loading even without "Obtain images directly from server". I have to remove all layers from projects, save an empty .qgs and .cfg, then re-add all layers and re-save .qgs and .cfg. Cannot understand why!

**Comment by nboisteault** [comment]
Try to execute clean_vartmp.sh next time you have weird behavior.

**Comment by gioman** [comment]
@nboisteault try for example any layer from http://www.igeo.pt/WMS/PNPOT

In general the option "get images directly..." never worked for me, not even after rebuilding the projects, cleaning tmp folders, etc.

cheers!

**Comment by rldhont** [comment]
Hi all, I have tested in 3.0.13 a WMS layer with the option "get images directly..." and I have no issue even if the layer is used as baselayer.
Is it a regression in 3.1 ?

**Comment by gioman** [comment]
@rldhont can you post a public WMS URL (and layer name) that works for you when activating the  "get images directly..." option? possibly not a QGIS Server based service. Thanks!

**Comment by rldhont** [comment]
I have tested with a lizmap WMS URL.

**Comment by gioman** [comment]
@rldhont what about for example with any layer from http://www.igeo.pt/WMS/PNPOT ? or maybe the functionality is really supposed (by design) to work with layers from QGIS Server services? cheers!

**Comment by rldhont** [comment]
Hi @gioman can you test the branch release_3_0 with the commit 4464b71 ?

**Comment by gioman** [comment]
@rldhont sorry, same as always (for me at least), as soon as that option is active the LM application does not load

![screenshot_20170608_175002](https://user-images.githubusercontent.com/1951107/26940567-125454ba-4c73-11e7-9287-b55d46f7c90e.png)

**Comment by rldhont** [comment]
@gioman can you provide an URL that I can check the error ? (in private if you prefer)

**Comment by gioman** [comment]
@rldhont for me *any* WMS layer from *any* service (not based on QGIS Server) always caused this. For example create a QGIS project with a layer at your choice by http://www.igeo.pt/WMS/PNPOT . Lizmap works if that option in unchecked (and the cascaded layers shows ok), in the option is on LM webapp does not load.

**Comment by rldhont** [comment]
@gioman I have tested a simple map with a WMS layer from http://www.igeo.pt/WMS/PNPOT and a shape. The map is loaded well with my last fix.
Can you clear the lizmap cache with: `./lizmap/install/clear_vartmp.sh` ?

**Comment by gioman** [comment]
@rldhont no dice. Attached there two very sample test projects (with LM cfg files), one working, the other don't.

[test_projects.zip](https://github.com/3liz/lizmap-web-client/files/1063585/test_projects.zip)

**Comment by rldhont** [comment]
Found and fix

**Comment by gioman** [comment]
@rldhont thanks! will try it asap!

**Comment by gioman** [comment]
> Found and fix
@rldhont is the patch expected to work only on master?

**Comment by rldhont** [comment]
It is in 3_0 https://github.com/3liz/lizmap-web-client/commits/release_3_0 and 3_1 https://github.com/3liz/lizmap-web-client/commits/release_3_1

**Comment by gioman** [comment]
@rldhont thanks! fix confirmed!
