### ISSUE TITLE
[Enhancement] Filter feature by more than 1 user or group

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#580]
One feature that would be very interesting is to filter feature with more than one user or group.

In my case, i can reuse the same DB in many projects to show the form answers to one group without answering rights.

The users could be comma separated. Then you could simply use .split(",") to get users.
Looks not too difficult, maybe i m wrong.

Thanks

**Comment by mdouchin** [comment]
You can also put your users in groups (in lizmap web client admin panel) and use groups instead of users filtering. To do so, use the group ids (and not labels) to fill the field on which the filtering is based.

**Comment by jlstanus** [comment]
In my project, i have about 1000 features and 100 users in 4 groups. Each **user** from 1 group have to answer to a set af features that others are not allowed.
- 1 filtred user of each group have to answer to 2 questions (2 fields) in 1 feature.
- The answers can be **read**  by 1 user of other groups

So i'd need to make 4 projects with the same table shared and duplicate user field

> To do so, use the group ids (and not labels) to fill the field on which the filtering is based.
Do you mean integer (group_id) in place of string (group_name)?

**Comment by saturdayevening** [comment]
I was looking for this too. Thanks for working on it.

**Comment by Gustry** [comment]
@mdouchin You have changed the milestone to 3.7, any news on this ?
 Can we change the milestone back ?

**Comment by Gustry** [comment]
@jlstanus Can you try latest 3.8 release ?

Linked to https://github.com/3liz/lizmap-web-client/pull/4559
