### ISSUE TITLE
[Question] Production architecture and directories synchronization

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#586]
Hi,

I'm trying to understand what is the optimized production architecture for a Lizmap application.

I understood that Qgis server and Lizmap web client must be installed ont the same server machine. I also saw on [this page](https://docs.3liz.com/fr/publish/publish_with_ftp.html) that Qgis Desktop should not be installed on this same machine. What are the reasons for this?

So I suppose that the best thing is to create mys Qgis projects on my PC and improve a directories synchronization between my PC and the server. Is it the best practice? How to improve this synchronization?

Thank you for your answers.

Céc.

**Comment by nboisteault** [comment]
Hi,
In WinSCP you can synchronise local and distant files (ctrl+U).

**Comment by mdouchin** [comment]
The best practice is to have a local copy of all directories, and synchronize them to the server when needed. 
This way, 

* You do not modify maps in production directly in the server
* You always keep a copy of your data and projects, configurations locally (which is good). Of course you also need to backup your server, but it is always good to have many backups in various places

You can use FTP or SFTP to push your files to the server. If you use FTP, we advise you to use SSL encryption.
WinSCP is a good client on Windows for both protocols.

**Comment by Cec78** [comment]
OK, thank you for these very interesting informations.
Regards.
Céc.
