### ISSUE TITLE
Users in group permission

### ISSUE THREAD

**Issue by virtusmankind** [3liz/lizmap-web-client#587]
Hello.
"Users" group do not appears in repository permission group choice, when configuring a new or existing repository. 
I thought it depends from general group permissions, so I created a new group "ospite", and give them general permissions. This group appears in groups to set permission in repository. ("Users" is still set as default group when registering)
![user](https://cloud.githubusercontent.com/assets/20582012/25957135/e26d73c8-366d-11e7-9076-c5c56392ad10.png)

When I set "ospite" as default group, the group disappear from repository permission choice. "Users" still do not appears in repository permissions choice. 
![ospite](https://cloud.githubusercontent.com/assets/20582012/25957163/f50c513e-366d-11e7-9f7e-5d4f886a7d78.png)
How can I allow a new registered user (grouped in default 'users' group) to have some permission as default (e.g see a map or edit a feature)?

**Comment by rldhont** [comment]
'Users' group is a special group to let the user manage his own profil. So every user has to be in this group (default one).
We have to enhance the way lizmap used the default group.

**Comment by rldhont** [comment]
It was a bug and has been fixed in release_3_0 and release_3_1
