### ISSUE TITLE
Link between Lizmap userID and PostgreSQL roles

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#588]
I would like to ask the following questions:
- Is there a possibility of creating a link between Lizmap userID and PostgreSQL roles / groups?
- Alternatively, can I automatically enter the Lizmap userID in an attribute of an edit mode feature in the LWC environment?

The goal would be to be able to record automatically users in a changes history attribute feature in edit mode.

Thank you,
João Cardoso

**Comment by pieri70** [comment]
Hello
you must have the same list of users in Lizmap and Postgresql
We are trying to make a common LDAP authentication.
Then, at this moment, we used the "info-user-login.text" content (top right - user id in LWC) and used this value to populate a table column.
Then on Postgresql side we made some rule to control action andd populate user id field and creation/modification data

**Comment by pieri70** [comment]
It would be nice if the user logged in will be presented by some ..
[lizmap event](https://docs.3liz.com/it/publish/advanced_lizmap_config.html#id5
)

**Comment by jhcardoso** [comment]
Hello Pietro,
How do you make possible to use "info-user-login.text" content to populate a table column? For the moment, it would be a good solution to me.

Thanks

**Comment by pieri70** [comment]
hello @jhcardoso sorry for my delay
to answer your question we used jQuery to get the username logged in from Lizmap web interface.
the command is
`$('b[id="info-user-login"]').html()`

The value returned is inserted into my table
To do this we created a custom javascript

We insert points on a postgis table (my_layer) with insert_user field in it, this field must be hidden to the user interface and automatically populated by lizmap.

So in js we have something like this:

```
var hideOnInsertMyFeature = [
"some_field",
"insert_user",
"some_other_field"
]


lizMap.events.on({
  'lizmapeditionformdisplayed': function(e) {
     /* INSERT NEW FEATURE */
    if ( e.layerId.match(/a_my_layer/g) ) {
      if ( $('input[name="id_feature"]').val() == "" ) {
         HideElements(hideOnInsertMyFeature);
         $('[[name="insert_user"]').val($('b[id="info-user-login"]').html());
    }
  })
}
```
This way a user logged don't see the field with his username and can't modify it.
The value is then stored to postgres when he saves his editing session
