### ISSUE TITLE
Issue with editing fields with predefined values

### ISSUE THREAD

**Issue by Strappy74** [3liz/lizmap-web-client#591]
Hi,
I noticed that when you use an editable layer in lizmap with some fields defined in QGIS as value list type, you can create new objects and fill these fields but if you try to modify a existing object, all the value list type field reset to NULL which is very problematic.

This problem does not occur in QGIS so I think it is liked to lizmap.

Is it possible to fix it ? Any background about this problem before ?

Thanks

**Comment by josemvm** [comment]
hi @Strappy74 

no problem, if you define the default value in the database (i think so)

**Comment by Strappy74** [comment]
Hi @josemvm 
This thing is I do not want a defaut value.
I want my chosen values in these fields to be saved and no reset when I modify an object

**Comment by josemvm** [comment]
are you using the latest version of LWC (3.1.1 or master)?
are you using the PostGIS database?

in my case it doesn't happen

**Comment by Strappy74** [comment]
I am using the last stable version of LWC and my layer is on PostGis.

Which is weird is that I created a new attribute in my postgis layer and defined values' list and for this attribute no problem of reseting whereas there is one for the attributes I created before importing my shape layer in PostGIS (for these attributes, the predefined value appears between comma which is not the case for the last attribute created)

All these attribute have the same type and the same parameters

**Comment by mdouchin** [comment]
The best way to help here would be to pass a very small QGIS project with one layer allowing to reproduce the bug. Please also provide SQL to create the table(s), and some INSERT statements.

**Comment by mdouchin** [comment]
It seems there are invisible line breaks in your data, and in the configuration of the values and labels in the "value list" edit type.
You should trim your data and this configuration values.

**Comment by Strappy74** [comment]
Thanks a lot @mdouchin !

I copied/pasted my values from EXCEL directly in QGIS value list which was not a good idea as it created invisible line breaks.

**Comment by rldhont** [comment]
Do you use QGIS 2.18 to create your QGIS project ?

**Comment by Strappy74** [comment]
@rldhont : no I use 2.14

**Comment by nboisteault** [comment]
@Strappy74 Reopen if issue still occurs.
