### ISSUE TITLE
Call geojson layer in lizmap

### ISSUE THREAD

**Issue by Strappy74** [3liz/lizmap-web-client#592]
Hi,

I am trying to call a public geojson layer in lizmap (Vigicrues water unit) with a public URL (by adding a vector layer as a protocol and not a file in QGIS) but when I click on the lizmap plugin in QGIS, I got a warning indicating that all layers have to be stored in the same file so I guess my geojson connexion is not recognized.

Here is the qlr code of the geojson layer (to open with Notepad +++)

[TRONCON_VIGICRUES.txt](https://github.com/3liz/lizmap-web-client/files/1013634/TRONCON_VIGICRUES.txt)

Thanks by advance for your help

**Comment by rldhont** [comment]
Can you clone your issue in lizmap-plugin and close this one ?
