### ISSUE TITLE
dataviz module - doesn't launch if the time manager tool is present

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#593]
hi @mdouchin 

![dataviz](https://cloud.githubusercontent.com/assets/10053874/26285656/f90f96d4-3e4b-11e7-8964-aa97a851186f.jpg)

thanks again for this nice feature

**Comment by josemvm** [comment]
hi,

here there is a bug too or something incompatible:

time manager works fine.

after you remove the time manager section from .cfg file, dataviz module works fine too!

    "timemanagerLayers": {
        "AtividadeS\u00edsmica(1975-2014)": {
            "group": "", 
            "label": "Info", 
            "layerId": "sismicidade_wfs20170506110440591", 
            "startAttribute": "data", 
            "groupTitle": "", 
            "order": 0
        }
    }, 

thanks again

**Comment by rldhont** [comment]
@mdouchin are you fixed it ?

**Comment by mdouchin** [comment]
No, and I have no clue how to do so yet. It seems date.js and plotly have function with the same name. Perhaps see if plotly can manage date string and replace date.js ?

**Comment by josemvm** [comment]
hi @rldhont @mdouchin 
if you want i can provide an url to check the problem

**Comment by nboisteault** [comment]
@josemvm Please provide an url if issue still occurs.

**Comment by josemvm** [comment]
hi
i can provide a link if you want to investigate

**Comment by josemvm** [comment]
@nboisteault what is your email address?

**Comment by nboisteault** [comment]
@josemvm nboisteault@3liz.com

**Comment by josemvm** [comment]
@nboisteault please check your mail box

**Comment by nboisteault** [comment]
@rldhont Could we replace Date.js by [moment.js](https://momentjs.com) with modification of timemanager.js code ?

**Comment by josemvm** [comment]
i think it is necessary to take a decision on this issue before freeze...
thanks

**Comment by nboisteault** [comment]
Same behavior with 1.47.1 version of plotly.js.
