### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by stuggi05** [3liz/lizmap-web-client#595]
Hi,

i've updated LizMap from 3.0.4 to 3.1.1 and now i've some trouble with performance.

Single tile loading was no problem, the performance was really good.
But in 3.1.1 single tile loading is not working, all layers are be loaded in tiles.
In general my impression is, that performance is worse than in 3.0.4.

I use qgis-server 2.14 LTR on debian.

**Comment by mdouchin** [comment]
This issue has been solved in branch release_3_1, see
https://github.com/3liz/lizmap-web-client/commit/a7a6471e29de38914a8d75d578189d816661b803

It will be in next point release

**Comment by stuggi05** [comment]
Hi,
thanx!

When will be the next release?

**Comment by rldhont** [comment]
The milestone 3.1.2 was fixed to yesterday but we have to fix some issues https://github.com/3liz/lizmap-web-client/milestone/22
