### ISSUE TITLE
Several upload photo into same record (lizmap edit mode)

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#596]
Is there any chance to admit several upload images/docs into the same record in lizmap edit mode?
For the moment, it's only possible to save one path in media/upload and the older image is deleted when the user click on "update" image, blocking a possible photo history.

Thanks,
João

**Comment by mdouchin** [comment]
the best would be to use QGIS relations

* 1 table with you data
* 1 table with your picture

Then link the 2 layers with QGIS relations, and use Lizmap 3.1 to have sub forms in editing form, and to show children in popups

**Comment by jhcardoso** [comment]
Thanks a lot , i will try that option!

**Comment by jhcardoso** [comment]
Hi,
Right now, i can view all my child records but with a vertical side bar.
![lizmap_edition_child record](https://cloud.githubusercontent.com/assets/8012527/26398497/8f75ae16-4071-11e7-90ac-31e1f6587048.jpg)

Can i define a change record button to view child records/images (horizontal view) in the info or edit feature window?

**Comment by jhcardoso** [comment]
The idea would be a previous/next button for photo record.
