### ISSUE TITLE
Data Table - Field name not showing

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [3liz/lizmap-web-client#597]
I've noticed that with the versions 2.18 of QGIS the field's name in the data table are not available.
![field](https://cloud.githubusercontent.com/assets/2738850/26397886/02372c1c-4078-11e7-94d5-bb5a72c55232.png)

However, selecting a field and clicking "Display Info" shows the name of the field.
Am I missing something or is it a bug?

**Comment by jhcardoso** [comment]
Hi, you need to define in QGIS the alias in layer properties. Then, it will be showned in lizmap table.

**Comment by GabrielePrestifilippo** [comment]
Thanks, I didn't find it anywhere in the documentation, maybe you should mention it somewhere.

**Comment by gioman** [comment]
> Thanks, I didn't find it anywhere in the documentation, maybe you should mention it somewhere.

consider also doing a pull request with a patch/improvement for the docs.

**Comment by rldhont** [comment]
It's an issue, if nothing is defined when alias is not defined, isn't it ?

**Comment by jhcardoso** [comment]
That's right. It seems that there's no other way without the alias.

**Comment by rldhont** [comment]
Which Lizmap version do you use ?

**Comment by GabrielePrestifilippo** [comment]
I provided a temporary fix here:
https://github.com/3liz/lizmap-web-client/pull/598

**Comment by rldhont** [comment]
manually merged in 3_0
