### ISSUE TITLE
permalink tool - doesn't respect current map scale if the startup base layer has a smaller max. deep zoom avaiable

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#600]
hi,
i checked the following problem:

**montpellier project test**

- set the "google-terrain" (max. deep zoom avaiable=18056) as "startupBaselayer"
- change the base layer to OSM Stamen Toner (max. deep zoom avaiable=2257)

- reach the maximum zoom for OSM Stamen Toner (2257)
![osm](https://cloud.githubusercontent.com/assets/10053874/26441576/ef4a94ca-4128-11e7-8248-19a077beba68.jpg)

- create/load a link to current map
![osm2](https://cloud.githubusercontent.com/assets/10053874/26441568/e989be58-4128-11e7-8904-94250ba6555f.jpg)

permalink tool doesn't respect the current map scale (max. deep zoom avaiable) if the startup base layer has a smaller max. deep zoom avaiable (e.g. Google Terrain)

thanks for your attention

**Comment by rldhont** [comment]
Hi @josemvm thanks for the feedback. Do you use 3.0 or 3.1 ?

**Comment by josemvm** [comment]
hi @rldhont 

i'm using 3.1 (and master)

thanks
