### ISSUE TITLE
time manager : blocage sur "chargement des données"

### ISSUE THREAD

**Issue by charmosz** [3liz/lizmap-web-client#602]
Salut, 
Je tente d'utiliser le time manager sur Lizmap (version 3.1beta1) mais au moment de le lancer il tourne dans le vide avec l'animation "Chargement des données". Voici l'erreur dans la console de Chromium :

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at a.initialize (proj4js.min.js:41)
    at a (proj4js.min.js:38)
    at initialize (OpenLayers.js:153)
    at activateTimemanager (timemanager.js:164)
    at Object.minidockopened (timemanager.js:26)
    at initialize.triggerEvent (OpenLayers.js:138)
    at HTMLAnchorElement.<anonymous> (map.js:5780)
    at HTMLUListElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLUListElement.r.handle (jquery-1.11.1.min.js:3)

Je vous envoie aussi le fichier que j'essaye de visualiser (cf mon mail perso). Le champ date est le champ "date2" et le pas de temps souhaité est d'une semaine. Est-ce que vous avez une idée d'où peut provenir le bug?

A noter que je peux utiliser sans problème le plugin time manager dans QGIS, donc le format du fichier et du champ date doit être correct je pense.

Merci !

**Comment by rldhont** [comment]
Pouvez-vous mettre à jour Lizmap à la version 3.1.1, merci ?

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/573
`time manager doesn't launch if you have a blank spaces in layer name/QGIS project`

**Comment by Cec78** [comment]
Bonjour,

Même problème de chargement pour moi avec Lizmap web client 3.2pre170303 et Qgis server 2.18.6 (je n'ai pas regardé la console par contre).
Le Time manager fonctionne avec les mêmes données dans Qgis desktop 2.18.6.

Céc.
