### ISSUE TITLE
Opening table attributes in the browser

### ISSUE THREAD

**Issue by pigreco** [3liz/lizmap-web-client#603]
In the chrome browser the table occupies the entire window, in the MS Edge browser it works fine.
Same project lizmap
![image](https://cloud.githubusercontent.com/assets/7631137/26586950/291a5e2a-4551-11e7-8d02-7cfc26fd8bd1.png)

**Comment by josemvm** [comment]
hi @pigreco 

i can´t reproduce your issue...

LWC 3.1
google chrome ver. 58.0.3029.110 (64-bit)

**Comment by rldhont** [comment]
@pigreco can you precise: the Lizmap Web Client version and the screen size ?

**Comment by nboisteault** [comment]
@pigreco reopen issue if issue still occurs.
