### ISSUE TITLE
[Question] Droits d'administration perdus

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#605]
Bonjour,

Je suis très très embêtée car, pour faire du ménage dans notre application Lizmap que nous avons installée et testée il y a quelques semaines j'ai par erreur totalement supprimé tout droit d'administration sur le seul admin de l'application. Cela s'est passé lors d'un changement de groupe.
Comment faire? Puis-je aller directement dans la base Sqlite pour réaffecter l'admin au groupe qui lui conférait ses pleins droits? Autre solution?

Merci d'avance pour votre réactivité.

Cordialement.

Céc.

**Comment by pcav** [comment]
Est-ce que vous avez un backup du jauth.db?

**Comment by Cec78** [comment]
OK, je vais demander une restauration du jauth.db à notre administrateur système.
Cela suffit?

**Comment by pcav** [comment]
Je crois que oui.

**Comment by rldhont** [comment]
Bonjour,

Vous pouvez utiliser une ligne de commande pour attribuer un utilisateur au groupe admins
```php cmd.php acl2group adduser admins admin```

Information trouvée dans la documentation jelix https://docs.jelix.org/fr/manuel-1.6/droits2/configuration

**Comment by Cec78** [comment]
OK. Je ne suis pas une pro du shell.
J'entre telle que cette commande dans le terminal?

**Comment by Cec78** [comment]
`Could not open input file: cmd.php`
J'imagine que je dois préalablement me placer dans le dossier qui contient le fichier cmd.php?

**Comment by rldhont** [comment]
Dans le dossier de l'application:
```php lizmap/cmd.php acl2group adduser admins admin```

**Comment by Cec78** [comment]
Un grand merci ça fonctionne! J'ai retrouvé les droits de mon admin (j'ai le sudo sur notre système de fichiers du serveur).
Je pense que cette discussion servira à d'autres, en tous cas je l'espère!
Je garde précieusement cette manip dans mon carnet de notes favori ;-)
Merci également Paolo pour la solution alternative de restauration du jauth.db.

**Comment by laurentj** [comment]
duplicate #399

L'impossibilité de supprimer des droits d'admins sera disponible dans des prochaines mises à jour
