### ISSUE TITLE
[Question] lizmap configuration disappeared

### ISSUE THREAD

**Issue by dassau** [3liz/lizmap-web-client#606]
Hi,

login as admin to lizmap client (3.0.4) I cannot see the menu entry "my account" anymore to configure the client. I only can click on "exit". I must have set some wrong hooks somewhere during another session :( and after that the menu disapeared.

Can I change some values in a config file to be able to see the Lizmap configuration as admin again?

Thanks for your help
Otto

**Comment by rldhont** [comment]
You can do something like that, in the lizmap application directory:
```
php lizmap/cmd.php acl2group adduser users admin
php lizmap/cmd.php acl2group adduser admins admin
```
The first line is for adding the user admin the users group. The users group set rights to let user manage its profil.
The second line is for adding amin user in admins group to manage the application.

You can renable users group as default group:
```php lizmap/cmd.php acl2group setdefault readers true```

**Comment by rldhont** [comment]
documentation here: https://docs.jelix.org/en/manual-1.6/rights2/configuration

**Comment by dassau** [comment]
Thanks a lot, that fixed my mistake!
