### ISSUE TITLE
Lizmap and QGIS-ltr-Server 2.14.14-1 - print- localhost - grids - Again

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-web-client#607]
Hi,

I use the QGIS-ltr-Server 2.14.14-1 and Qgis Desktop 2.14.14, the prints layouts appear with grids ... again, but the grids on Qgis print layout is off...

This is the second time this happen... the first time I use the QGIS-ltr-Server 2.14.12-1

My operating system is Windows 7 64bit.

Can you help me please?

Thank you very much.

Orlando

**Comment by rldhont** [comment]
fixes with f8048995f49a71e72c09b3c4b280840eeae4e863
you can update lizmap 2.12 https://github.com/3liz/lizmap-web-client/releases/tag/2.12.7
