### ISSUE TITLE
Information popup container: dock not taking into account image size

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#611]
When using Information popup container: dock, the image size as defined in QGIS does not seem to be taken into account. As a result, if using high-res photos, they are huge and essentially unusable.

**Comment by nboisteault** [comment]
@pcav Where do you define the image size in QGIS ?

**Comment by nboisteault** [comment]
@pcav Can you give us a simple project illustrating the issue ?

**Comment by pcav** [comment]
Apparently this is no longer the case.

**Comment by pcav** [comment]
@nboisteault I define image size in the Layer properties>form

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
