### ISSUE TITLE
[Question] Custom Date/time format

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#612]
Benchmark:
SO: Windows Server
Lizmap Web Client Version: master
QGIS Server: 2.18.9 64-bits

Hi guys,
i have a date format yyyy-mm-ddTHH:mm:ss . I define custom format to show as yyyy-mm-dd in the date/time widget of QGIS postgis layer proprieties and works fine. When i open the lizmap popup the form don't recognize the pattern. 
Lizmap Web Client only use the content of the cell or receive information about the datetime format?
If yes it's is possible to change the datetime format in the lizmap web client side?

I need to add this format in the date.js?

Regards
João

**Comment by mdouchin** [comment]
Does your issue occur when displaying the editing form, or when displaying the feature popup ? If this is in the popup, which popup config do you use : qgis, lizmap, auto ?

**Comment by jonnyforestGIS** [comment]
Hi,
I change the date field to dd-m-yyyy and works fine. I notice that if you put the date field non editable in the layer proprieties the value of the field don't appear in the edit form of lizmap. (see picture)
Tested in Lizmap 3.0 and Lizmap master. Knowing this i will try put editable check in the other format date to see if this persists (it's seems to me that are different issues).
![date](https://user-images.githubusercontent.com/4480601/27122107-9cefac9c-50e1-11e7-81db-f084cb75e71c.png)

**Comment by jonnyforestGIS** [comment]
[UPDATE]
@mdouchin I forget to tell in the popup the value works fine.

It's seems that lizmap in edit form for date/time fields only fill with existent values if i put the date format as yyyy-mm-dd. I test In the field value:
2017-06-14T00:00:00 - QGIS (configure with custom data/time format and custom widget format to yyyy-mm-dd): **Not work** 
14-06-2017 - QGIS (configure with custom data/time format and custom widget format to yyyy-mm-dd): **Not work**
2017-06-14 - QGIS (default data/time format and default widget format): **Work**




So the problem is not in editable checking field.

**Comment by jonnyforestGIS** [comment]
Hi guys,
Find the problem...
I not define the timezone in php, that was the reason of bad format.
