### ISSUE TITLE
[Question] Anonymous access

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#613]
Hi,

I was wondering if it is possible to configure an anonymous access to some Lizmap maps, without login/password.

Thank you in advance for your answers.

Céc.

**Comment by rldhont** [comment]
Yes, if you restrict access to repositories, all the repository without restricted access are available to anonymous.
If you use Lizmap Web Client 3.1the restricted acces can be defined at project level.

**Comment by Cec78** [comment]
Hi René-Luc,
Thank you for your answer. I finally found how to do.
Céc.
