### ISSUE TITLE
Probleme affichage popup

### ISSUE THREAD

**Issue by nepileptik** [3liz/lizmap-web-client#614]
Bonjour ;
Tout d'abord merci pour cet outil qui est formidable, mais depuis hier je rencontre un souci en effet jusqu’à présent ma page web fonctionné très bien popup et tout ce qui vas avec mais depuis hier mes popup refuses de s'afficher j'ai lu et relus ma fonction HTML afin de voir si aucune faute de frappe ne pouvais entrainer le blocage de l'affichage, j'ai également changé le mode d'affichage du popup  je suis passé de map à dock et j'ai été surpris de constater qu'un message apparaissait disant :"Aucun objet n'a été identifié à cet endroit." alors que je clique sur le ponctuel qui est activé avec les popups.
la je suis un peu perdu si quelqu'un peu m'aider ça serait cool je dois présenter ma page web la semaine prochaine.
merci par avance 
Rémi
![image](https://user-images.githubusercontent.com/27948553/26964702-16a40d8c-4cf3-11e7-8977-496ed19f3de3.png)
![image](https://user-images.githubusercontent.com/27948553/26964742-3c14a75c-4cf3-11e7-83b9-ccdbef9a0bf2.png)

**Comment by nboisteault** [comment]
Bonjour Rémi,
As-tu un accès public à ton interface? Si oui donnes nous le lien.
Pour info mais ça ne concerne pas ton bug : dans ton exemple, seule la dernière balise <p> est fermée, penses à fermer les autres.

**Comment by nepileptik** [comment]
Bon j'ai fini par comprendre le problème.
J'ai remplacé la couche qui est concerné par les popup mais dans qgis serveur il garde en mémoire les fichier de l'ancienne couche donc blocage après avoir supprimé les fichiers résiduels les popup sont revenu
