### ISSUE TITLE
WMS authentification problem with LDAP

### ISSUE THREAD

**Issue by kevindescamps** [3liz/lizmap-web-client#617]
I have a problem with WMS service with login/password.
I tried to use wms link with qgis with login/password.
The message error is : `L'hôte requiert une authentification...`
It doesn't recongize my login.
Without login, it work... 
I have lizmap 3.1.0 and qgis serveur 2.14
I have ldap configuration.
The problem has been detected since we change lizmap version (3.0 before ), qgis version (2.8 before) and authentification type (was normal before).
We tried to edit the virtualhost with : 
```
RewriteEngine on
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```

But it doesn't work...
Any solution?
Thank you.

--------------------------

J'ai un problème avec le service WMS avec login/mot de passe.
J'ai tenté d'utiliser le lien wms sur qgis avec mon login et mon mot de passe.
Le message d'erreur est : `L'hôte requiert une authentification...`
Il ne reconnait visiblement pas mon login.
Pourtant, avec un lien WMS qui ne nécessite pas d'authentification, cela fonctionne...
Je dispose de lizmap 3.1.0 et qgis serveur 2.14
Lizmap utilise une authentifcation ldap dans le paramétrage
le problème est survenue depuis le changement de type d'authentification (normal), de version lizmap (3.0) et de version qgis (2.8).
Nous avons tenté de modifier le virtualhost avec les lignes suivantes :
```
RewriteEngine on
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```

ça n'a pas marché...
Une idée?
Merci d'avance pour votre aide

**Comment by rldhont** [comment]
I have tested an 'hideProject' with authentication and I can access the WMS GetCapabilities.
I think the issue comes from LDAP authentication.

**Comment by rmarzocchi84** [comment]
I have probably the same problem with a private repository. I have the WMS link. 

When I try to connect the message is: "Impossible download the capabilities: Download of capabilities failed: Host requires authentication" but I try to add the authentication

![problem_wms1](https://user-images.githubusercontent.com/4061154/28927716-8f0763a2-786b-11e7-9b96-68e217d4ead2.png)

**Comment by rldhont** [comment]
some feedback ?

**Comment by Gustry** [comment]
@rldhont As a tip, in my own repo, I'm using a label "Candidate for closing", so a few weeks later, I can loop in this list and I know that I can safely close this issue if no more feedbacks are coming. My 2 cents ;-)

**Comment by rldhont** [comment]
@kevindescamps @rmarzocchi84 can you provide some feedbacks ?

**Comment by kevindescamps** [comment]
It's working for me

**Comment by rmarzocchi84** [comment]
I need to install the new lizmap client.. I will be give feedbacks as soon as possible

**Comment by rldhont** [comment]
I close it, reopen if needed
