### ISSUE TITLE
popup (qgis/edit widget/value map) - shows the description instead of the value

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#618]
hi

firstly, thanks for all the latest improvements in LWC!

QGIS Server 2.14
LWC all versions

i already checked for some time that the LWC popup (auto/lizmap/qgis) shows the description and not the value from the edit widget/value map

**Comment by rldhont** [comment]
@josemvm do you mean that for each field the popup shows the database value and not the value like is configured in the edit widget ?

**Comment by josemvm** [comment]
no, but the opposite

for each field the popup shows the value (description) like is configured in the edit widget and not the database value

**Comment by rldhont** [comment]
@josemvm the value displayed is provided by QGIS Server, so if you want to deactivate the configuration, we have to enhance QGIS server to add an option for this.

**Comment by josemvm** [comment]
thanks for the information @rldhont

**Comment by rldhont** [comment]
If you use the qgis popup, build by QGIS with tooltips, you probably can have the database value.
https://docs.3liz.com/en/publish/advanced_lizmap_config.html#how-to-configure-popups

**Comment by josemvm** [comment]
i'll try to do it
thank you again
