### ISSUE TITLE
native base layers - (i)nformation panel doesn't close

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#621]
hi

for the native base layers the close button doesn't work:

![info](https://user-images.githubusercontent.com/10053874/27229473-a70e6204-52a3-11e7-86bf-b5e9049be9e2.jpg)

PS:
if the info panel refreshes the information when you change the base layer map (such as layers in the layers panel) it seems to me to be a good improvement

thanks

**Comment by josemvm** [comment]
hi @rldhont 

the switching mechanism works fine but the panel doesn't close for native base layers...

**Comment by rldhont** [comment]
@josemvm What do you mean by 'native base layers' ?
I have tested with a QGIS vector Layer as baselayer and OpenStreetMap baselayers, and I can close the info panel.

**Comment by josemvm** [comment]
i'm talking about google maps and OSMaps
i' ve google maps and other raster layer and can´t do it... http://observa.municipioarraiolos.pt

**Comment by rldhont** [comment]
I have to verifying external baselayers.

**Comment by josemvm** [comment]
yes, the problem manifests itself only in present of non-native raster baselayers
thanks

**Comment by rldhont** [comment]
@josemvm fixed ?

**Comment by josemvm** [comment]
yes @rldhont !

i really appreciate your great skills :-)
thank you very much
