### ISSUE TITLE
unnaccent in the locate by layer tool and data search

### ISSUE THREAD

**Issue by tudorbarascu** [3liz/lizmap-web-client#622]
It would be a nice feature if the locate by layer tool and the data search would have the Unaccent feature.
I noticed there is some code for unnacent in https://github.com/3liz/lizmap-web-client/search?utf8=%E2%9C%93&q=unaccent&type=

**Comment by rldhont** [comment]
Why do you want unaccent feature in the locate by layer tool and the data sach ?
