### ISSUE TITLE
LWC edition tool - send current login userid to postgresql table field

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#624]
how is it possible LWC send current login userid to postgresql table field in editing environment?

without correspondence between LWC users and postgresql users https://github.com/3liz/lizmap-web-client/issues/457

thanks

**Comment by josemvm** [comment]
is it possible to improvise this feature? how?
thanks

**Comment by mdouchin** [comment]
At present, the only solution would be to use some Javascript which will
* detects the user opened a form
* get the login from the Lizmap interface
* put it in some field if the field is empty.

Example of code

```
var formPrefix = 'jforms_view_edition';

// Name of the QGIS vector layer fields which must containt the user info
var userFields = {
    login: 'lizmap_user_login',
    firstname: 'lizmap_user_firstname',
    lastname: 'lizmap_user_lastname',
    organization: 'lizmap_user_organization'
};


lizMap.events.on({

    'lizmapeditionformdisplayed': function(e){

        // If user is logged in
        if( $('#info-user-login').length ){
            // Loop through the needed fields
            for( var f in userFields ){
                // If the user has some data for this property
                if( $('#info-user-' + f).text() ){
                    // If the field exists in the form
                    var fi = $('#' + formPrefix + '_' + userFields[f]);
                    if( fi.length ){
                        // Set val from lizmap user data
                        fi.val( $('#info-user-' + f).text() )
                        // Set disabled
                        fi.attr('disabled', 'disabled');
                    }
                }
            }
        }

    }

});

```

This is possible with some coding, but be aware it is a workaround and not bullet proof. A more robust and secure way would be to do this server side, which means we should add an option in Lizmap web client. For example, let the map editor give the name of the field in which to store the lizmap login for each editing layer. If the option is set, Lizmap will transform the field as Hidden, and set the content client and server side.

**Comment by josemvm** [comment]
hi @mdouchin 

thanks for your work

i put this script in media/js/myproject, using only one empty field to receive 'lizmap_user_login' but nothing happens... is something missing like layer name or or something else...?

**Comment by mdouchin** [comment]
Have you activated the JS ?
https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#adding-your-own-javascript

**Comment by josemvm** [comment]
yes, lizmapUserLogin.js

**Comment by josemvm** [comment]
i have 2 editable layers in my project...

**Comment by mdouchin** [comment]
a test url ?

**Comment by josemvm** [comment]
yes, http://smpc.municipioarraiolos.pt

please, check your mailbox for access credentials

**Comment by mdouchin** [comment]
You have not adapted the script ! You need to change the dictionary **userFields**

For example, if you field for login is **observacoes**, you need this instead of the one put in my example

```
// Name of the QGIS vector layer fields which must containt the user info
var userFields = {
    login: 'observacoes'
};
```

**Comment by josemvm** [comment]
sorry, i misinterpreted the script (observacoes: 'lizmap_user_login')...

now the form takes the value of the login but does not pass it to the database...
thanks

**Comment by mdouchin** [comment]
Can you look at `lizmap/var/log/error.log` and see if there is a SQL error when you save the form ?

**Comment by josemvm** [comment]
hi @mdouchin 

no, there are no errors...

**Comment by josemvm** [comment]
i've tried with other projects, with other tables, without alias name for login field...
have you already tried with postgresql database?

**Comment by jhcardoso** [comment]
Macau, i have exactly the same problem... it doesn't write in postgres database

**Comment by josemvm** [comment]
hi

my postgresql log on insert feature:

`2017-07-25 17:42:11 WEST [18838-7] user@databaseName LOG:  statement:  INSERT INTO "schema"."table" ("the_geom", "field1", "field2", "field3" ) VALUES (ST_GeomFromText('POINT(19629.678001044926 -74745.29503882483)', 3763), '2017-07-25', 55, 55 );`

the field containing the login value `login: 'observacoes'` (observacoes) is not transported from lizmap form to the postgresql database.

**Comment by josemvm** [comment]
hi @mdouchin 

with the purpose to help debugging the problem, i've tried with a not null field

the form take the current user login value
![obs](https://user-images.githubusercontent.com/10053874/28615991-efd7702a-71f2-11e7-9a11-d7764ac76e60.jpg)

when submitting, the form controller doesn't recognize the value in the field
![obs1](https://user-images.githubusercontent.com/10053874/28615997-f2d995f0-71f2-11e7-82bb-4d3b803f74f2.jpg)

**Comment by mdouchin** [comment]
@josemvm Is your field published in the WFS column of the vector layer field ?

**Comment by josemvm** [comment]
yes @mdouchin

**Comment by josemvm** [comment]
hi @mdouchin 

here is the problem: `fi.attr('disabled', 'disabled');`
with this code, which protects the field, the form controller interprets the field as empty

i commented this part of the code and instead i put the field as hidden in qgis project. so it works fine for me!

thanks

**Comment by mdouchin** [comment]
@josemvm This could be great in documentation :) as en example of the "add your own JS"

**Comment by josemvm** [comment]
yes i think so, too. i will do it! :-)

**Comment by josemvm** [comment]
done

**Comment by josemvm** [comment]
@laurentj 

this js script doesn´t send the user name (login) to the postgresql, it works for local users only:
```
var formPrefix = 'jforms_view_edition';

// Name of the QGIS vector layer fields which must containt the user info
var userFields = {
    login: 'login',
    firstname: 'lizmap_user_firstname',
    lastname: 'lizmap_user_lastname',
    organization: 'lizmap_user_organization'
};


lizMap.events.on({

    'lizmapeditionformdisplayed': function(e){

        // If user is logged in
        if( $('#info-user-login').length ){
            // Loop through the needed fields
            for( var f in userFields ){
                // If the user has some data for this property
                if( $('#info-user-' + f).text() ){
                    // If the field exists in the form
                    var fi = $('#' + formPrefix + '_' + userFields[f]);
                    if( fi.length ){
                        // Set val from lizmap user data
                        fi.val( $('#info-user-' + f).text() )
                        // Set disabled
                     // fi.attr('disabled', 'disabled');
						fi.hide();
                    }
                }
            }
        }

    }

});
```

how can we adapt it for ldapdao and multiauth modules?

thanks in advance

**Comment by josemvm** [comment]
sorry, no problems, it works again!

**Comment by rmarzocchi84** [comment]
> @laurentj
> 
> this js script doesn´t send the user name (login) to the postgresql, it works for local users only:
> 
> ```
> var formPrefix = 'jforms_view_edition';
> 
> // Name of the QGIS vector layer fields which must containt the user info
> var userFields = {
>     login: 'login',
>     firstname: 'lizmap_user_firstname',
>     lastname: 'lizmap_user_lastname',
>     organization: 'lizmap_user_organization'
> };
> 
> 
> lizMap.events.on({
> 
>     'lizmapeditionformdisplayed': function(e){
> 
>         // If user is logged in
>         if( $('#info-user-login').length ){
>             // Loop through the needed fields
>             for( var f in userFields ){
>                 // If the user has some data for this property
>                 if( $('#info-user-' + f).text() ){
>                     // If the field exists in the form
>                     var fi = $('#' + formPrefix + '_' + userFields[f]);
>                     if( fi.length ){
>                         // Set val from lizmap user data
>                         fi.val( $('#info-user-' + f).text() )
>                         // Set disabled
>                      // fi.attr('disabled', 'disabled');
> 						fi.hide();
>                     }
>                 }
>             }
>         }
> 
>     }
> 
> });
> ```
> how can we adapt it for ldapdao and multiauth modules?
> 
> thanks in advance

@josemvm It is possible to obtain also the group of the user logged in? Which is the name of the variable?

lizmap_group ????

**Comment by josemvm** [comment]
hi @rmarzocchi84 

i don't think so. an user can belong to more than one group...

**Comment by rmarzocchi84** [comment]
> hi @rmarzocchi84
> 
> i don't think so. an user can belong to more than one group...

maybe an array?

**Comment by rmarzocchi84** [comment]
I like to view a custom button created with my javascript code (https://github.com/3liz/lizmap-web-client/issues/712) only for user with edit permission

perhaps  `view~edition.access.XXX 
`?

**Comment by rmarzocchi84** [comment]
sorry @josemvm and there is a way to obtain the authenticated user using a php code? I try with $_SESSION variables but I do not obtain nothing

**Comment by josemvm** [comment]
sorry @rmarzocchi84 
i don´t know. the script was developed by @mdouchin
