### ISSUE TITLE
 direct access to protected repository

### ISSUE THREAD

**Issue by elyparker** [3liz/lizmap-web-client#625]
hi is it possible call by another site a lizmap repository with authentication?

i mean if you know user and password call it with url passing user and password into it or in session php variable?

**Comment by jaitor1** [comment]
You should be able to do something like:

http://yourdomain/lizmap/lizmap/www/index.php/jauth/login/in?login=youruser&password=yourpass&auth_url_return=%2Flizmap%2Flizmap%2Fwww%2Findex.php%2Fview%2Fmap%2F%3Frepository%3Dwhatever%26project%3Dwhatever

**Comment by elyparker** [comment]
**thank you, it works!!**

can you tell me if is possible to use session variable php for call url with map?
or other way 
for to not show password in url?

**Comment by mdouchin** [comment]
You should really be carefull with this kind of "trick". Passwords must never be available in plain text, nor used in URLs

To achieve the feature, we would need to add some SSO capability in Lizmap, so that you can echange tokens between your app and Lizmap.

**Comment by elyparker** [comment]
yes, you have reason 
but sso now not exist right?

however i need somethink more simple that sso, i am in the same site/host but i need joomla (old version old backup)  for normal pages do  u think that there is way for to call lizmap in secret way in the same host without use plain password?

**Comment by rldhont** [comment]
You probably needs a proxy, to add login/password in request
