### ISSUE TITLE
Lizmap - Strange printing issue

### ISSUE THREAD

**Issue by jonoGIS** [3liz/lizmap-web-client#628]
Hi all, I am new to Lizmap and have been loving it lately. Everything has been going smoothly but I have run into a strange issue with printing of my maps..

I have my QGIS print composer set up and working with LizMap, however when I print a PDF (or any available format), the layers of the project are not in the correct order anymore. More specifically, the raster layer (GeoTIFF Orthophoto) is now covering all the vector (.SHP) data.

Please view my public project here: https://goo.gl/K3ot1p

Try for yourself and print the map. If you don't want to view the map, I have also attached 2 screenshots:

1. The correct order of the layers (vector on top of the raster)
![image](https://user-images.githubusercontent.com/29750498/27629831-e723d83e-5bf3-11e7-8085-1cb73ff4d6ff.png)

2. Printing result (raster layer now covering all vector)
![image](https://user-images.githubusercontent.com/29750498/27629911-20900b06-5bf4-11e7-94db-254e0ac7e89a.png)

Thanks for your help :)

**Comment by lionelbargeot** [comment]
Hi 
I had the same problem.
you have to setup qgis-server version you use in the lizmap-web-client backoffice (>= 2.18 to true).
Regards
Lionel

**Comment by jonoGIS** [comment]
Hi Lionel, thanks for your reply.

Lizmap currently says this:
![image](https://user-images.githubusercontent.com/29750498/27631720-aef86a96-5bf9-11e7-8646-850d1e178468.png)

I am using QGIS version 2.18.4, could this be the problem?

**Comment by lionelbargeot** [comment]
witch lizmap-web-client version do you use ?
a fresh bugfix release should resolve this problem : https://github.com/3liz/lizmap-web-client/releases

> QGIS Server version and Layer order in Print

**Comment by jonoGIS** [comment]
"3.2pre170303"

Ok thanks, I will try the bugfix release

**Comment by rldhont** [comment]
@jonoGIS do you have resolvec your issue, with the right version in config ?

**Comment by nboisteault** [comment]
@jonoGIS reopen if issue still occurs.
