### ISSUE TITLE
[Question] Related tables in popup

### ISSUE THREAD

**Issue by Cec78** [3liz/lizmap-web-client#629]
Hi,
I was wondering if it is possible to get informations about related tables in the popup of the object of a spatial table. 
For an example: I would like to clic on a point that represent a university and be able to see the attributes of every publication from this university. University table is related one to many with the publication table.
I know I could do that with the attribute layers tool but my client wants to see the information into a popup.
Thank you in advance for your answers.
Cec.

**Comment by rldhont** [comment]
If you have relation defined in the project, if you use lizmap web client 3.1, the attribute table is activated and have popup display children activated.

**Comment by Cec78** [comment]
Thank you, does popup have to be activated with auto, qgis or lizmap source?
Related lines appear in my qgis desktop project popups but not in lizmap popups.
I'm using LWC 3.2pre170303.

**Comment by rldhont** [comment]
The relation is displayed in every popup type. You have an example in the Montpellier project about Tram stops and Tram stop works

**Comment by Cec78** [comment]
Thank you, I will check my related tables.
