### ISSUE TITLE
Feature Count limited to 10

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [3liz/lizmap-web-client#630]
Is there a reason why in WMS Get Feature Info Request there is a limit of 10 Features?

https://github.com/3liz/lizmap-web-client/blob/bd0eec219e9aa2cc60ec841230797c78a2d478e4/lizmap/www/js/attributeTable.js#L2718

Isn't it better to remove this limit?

**Comment by rldhont** [comment]
The limit is used by qgis server for each layer, so a feature_count of 10 means that we can 10 x number of layers features displayed in popup.

It is better to configure this limit than remove it.

**Comment by rldhont** [comment]
Duplicate https://github.com/3liz/lizmap-web-client/issues/430 ?
A PR is proposed https://github.com/3liz/lizmap-web-client/pull/489
