### ISSUE TITLE
[feature] popup - zoom to feature

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#631]
hi,

the zoom tool would be very useful in popup even if the layer is not an "attributeLayer"

![zoom](https://user-images.githubusercontent.com/10053874/27769188-59be1b04-5f1c-11e7-9db7-f4c742768757.jpg)

thanks

**Comment by shapley** [comment]
Hi,

Would be really useful if there was an option on the popup to activate a mobile camera or an 'app'.
