### ISSUE TITLE
Qgis project in Lizmap not showing layers, only base layers

### ISSUE THREAD

**Issue by ocastillog** [3liz/lizmap-web-client#632]
I am following the lizmap tutorial for publish a QGIS project in lizmap but I only see the base layers. Checking and unchecking the layers don't show them. The demo Montpellier project is working well but not my project. Using lizmap 3.1.2 , QGIS 2.18, QGIS Server 2.18.10, Apache 2, PHP 7.0 on Ubuntu 16.04

This is my qgis project:
[https://drive.google.com/file/d/0B_wKMfiC-CYdVEdMSW1lMTRWeEE/view](url)

Any suggestions?

Osmin

**Comment by rldhont** [comment]
@ocastillog QGIS Server does not read the layers in your project!
