### ISSUE TITLE
Error 500. A technical error has occured. Sorry for this trouble

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#633]
I keep getting this error when i get to these two pages:-

http://127.0.0.1/lm/admin.php/admin/config/saveSection
http://127.0.0.1/lm/admin.php/admin/theme/save

I'm using Ubuntu Server 17.04 with Apache2 and php7.0
Unable to proceed to the Project.

**Comment by mdouchin** [comment]
Hi,

I guess it is related to directory rights.
Please re-run the command (from the root of lizmap installation folider)

```
lizmap/install/set_rights.sh www-data www-data
```

**Comment by rldhont** [comment]
If you think, that the documentation is not enough explicit, you can enhance it.
