### ISSUE TITLE
lizmap Project Title on Map 

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#634]
Hi,

Where do you change the header 'lizmap Project' on the map project page for a title of my choice?

**Comment by rldhont** [comment]
In version 3.1, you can specify the application name in the Lizmap config in admin.

**Comment by shapley** [comment]
This only appears to change the 'Projects' page not the 'Map' page.

**Comment by rldhont** [comment]
The Map page title is based on the project title.

**Comment by shapley** [comment]
It is set in the 'Project Properties' in QGIS...Thanks Guys
