### ISSUE TITLE
Vector layers not interactive or selectable on map.

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#635]
This may be related to the 'set_rights.sh' script but not sure. I have all vector layers showing on the map but i am unable to access the 'attribute' tables or the the 'locating or selection' tools or click on the information 'i' tool (and click on an object). I have run the script as root from /var/www/lizmap-web-client-release_3_1/ folder but there is no change to this. I am sure the script has run correctly because the folders (within the script) all have 'www-data' permissions. I am thinking there is some problem with the project shapefiles but they have all 'read and write'. Can you think of anywhere else i could check...perhaps the 'set_rights.sh' script is not run appropriately.

**Comment by rldhont** [comment]
Hi @shapley It seems to be:
* WFS issue, are vector layers published as WFS in OWS Server tab in QGIS Project Properties ?
* Identifiable issue, are vector layers not checked in identifiable tab in QGIS Project Properties ?
* popup activation issue, is vector layers popup option checked in Lizmap plugin ?

**Comment by shapley** [comment]
All of the above have been checked but still it won't work.

**Comment by mdouchin** [comment]
Do you have a public URL, so that we can check what is going on ?

**Comment by shapley** [comment]
I found out that some of the layer groups were not correctly named (some groups had too many characters on the names).

**Comment by shapley** [comment]
closed
