### ISSUE TITLE
Filter field A values based on filed B selected value

### ISSUE THREAD

**Issue by vherreros** [3liz/lizmap-web-client#636]
Hello,

I'd like to know if this is possible. Please forgive me for asking such question here but I don't know of any other LizMap user forum...

I have in my project two fields of type 'value map' in QGIS and editable in LizMap config. One of them is the country of the object and the other is the region. I have in the underlying PostGIS database one table with the 1 to n relationship between country and region. 

I'd like to know if it's possible that, when editing the objects through the LizMap web client, if I select one value for country then the roll-up field for the region gets limited to only the regions of that country.

Is it possible?

TIA.

**Comment by nboisteault** [comment]
Hi,
It has not been developed but you easily do it with javascript.
Look at [this issue](https://github.com/3liz/lizmap-web-client/issues/350).

**Comment by rldhont** [comment]
This feature could be based on https://plugins.qgis.org/plugins/FormAwareValueRelationWidget/

**Comment by Mavialle** [comment]
Hi,

Until this fonctionnality is developed, does anyone have a javascript example to do this ? 
I am beginner in javascript, and I can modify an existing code but not create one from scratch...

**Comment by josemvm** [comment]
hi @nboisteault (and all developers)

> It has not been developed but you easily do it with javascript

please, can you help us with a workaround javascript to temporarily solve this "gap" in LWC?

many thanks in advance :-)

**Comment by Gustry** [comment]
This is possible since a few version of Lizmap 
https://demo.snap.lizmap.com/lizmap_3_6/index.php/view/map?repository=testsrepository&project=form_edition_value_relation_field
https://docs.lizmap.com/current/fr/publish/configuration/layer.html#edition-expressions
