### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#640]
Hi,

When i press the 'Print' button i get the following error:

Error 500. A technical error has occured. Sorry for this trouble.

**Comment by gioman** [comment]
> When i press the 'Print' button i get the following error:

what version of qgis server do you run? on what operating system? by chance the layout you are trying to print contains a text box (or "label" as it is called in QGIS print composer)?

**Comment by shapley** [comment]
Hi,

qgis-server 1:2.18.10+26zesty (ubuntu 17.04)

**Comment by gioman** [comment]
> qgis-server 1:2.18.10+26zesty (ubuntu 17.04)

the layout you are trying to print contains a text box/label?

**Comment by gioman** [comment]
another question is you Ubuntu box headless (Ubuntu Server) or is a Ubuntu Desktop installation?

**Comment by shapley** [comment]
Hi,

Ubuntu Desktop. The map template only contains a map frame (no text box or label).

**Comment by Oneil974** [comment]
Hi,

Are you using specific symbology? Dashed Lines, svg symbols... for example?

**Comment by shapley** [comment]
Yes...some svg symbols and some line pattern fills.

**Comment by Oneil974** [comment]
try to print a map where no svg symbols are in the print zone.

SVG symbole may have relative path sometime and have to be put in the map repository

**Comment by shapley** [comment]
Hi,

Removed all poly 'fills' and svg symbols but same error.

**Comment by Oneil974** [comment]
Hi,

Have you put images or svg symbols in print composer?

**Comment by shapley** [comment]
No...just a map frame.

**Comment by Oneil974** [comment]
Maybe you should verify right access on folders like this

[https://docs.3liz.com/fr/install/linux.html#redefine-the-rights-to-the-application-files](https://docs.3liz.com/fr/install/linux.html#redefine-the-rights-to-the-application-files)

even if I don't think it will change something

I think something is wrong with your apache2 configuration (apache2.conf)

**Comment by gioman** [comment]
I don't know if can explain the issue reported here, but at this moment in qgis server 2.18.10/11 there are serious printing issues, see:

https://issues.qgis.org/issues/15440

moreover an important option was removed from the QGIS print composer, the one that allowed to unlink a legend from a map object and that made possible to print "fixed" legends with QGIS Server GetPrint request. I didn't had the time yet to test it deeply, but this seems also creating another issue, the appearance of "?" in place of layer names in the legend of a map printed via GetPrint.

https://issues.qgis.org/issues/16899
