### ISSUE TITLE
Anti-Aliased Web Map Services

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#641]
Hi,

I noticed that a web map service (WMS) displayed in the web client looks very jagged in appearance compared to the same service in QGIS as though anti-aliasing is off. Is this a future enhancement for the plugin?

**Comment by mdouchin** [comment]
Hi, 

I have never seen this behavior. Could you please share images illustrating the issue ?
Are you sure you have no zoom active in your browser ?

**Comment by shapley** [comment]
Hi,

Attached is an image of a typical Ordnance Survey GB Map.
![map](https://user-images.githubusercontent.com/7022885/28455823-421a8f24-6df8-11e7-83af-1baae08140e3.PNG)

**Comment by gioman** [comment]
> Hi,
> 
> Attached is an image of a typical Ordnance Survey GB Map.

is the original datasource a raster or a vector, in LM are you reprojecting it?

**Comment by shapley** [comment]
Hi,

It is a raster wms in 'png' format

**Comment by gioman** [comment]
> It is a raster wms in 'png' format

so if you reproject to another CRS it (in QGIS or also in LM) is normal that it could look a little jagged.

**Comment by shapley** [comment]
Hi,

The WMS service has a default epsg:27700 (osgb 1936). I think Lizmap is trying to re-project it to epsg:3857 so it is causing it to look jagged. Does Lizmap support epsg:27700?

**Comment by gioman** [comment]
> Does Lizmap support epsg:27700?

The CRS LM uses is the CRS of your QGIS project.

**Comment by shapley** [comment]
Hi,

I've set the Project CRS to 27700 (and all layers and WMS services to the same) but LM does not display the correct co-ordinates for this CRS. LM appears to retain 3857 same as google streets, hybrid, satellite etc (also included as a basemap).

**Comment by gioman** [comment]
> I've set the Project CRS to 27700 (and all layers and WMS services to the same) but LM does not display the correct co-ordinates for this CRS. LM appears to retain 3857 same as google streets, hybrid, satellite etc (also included as a basemap).

when you add Google/Bing/OSM basemaps the LM project automatically switches to 3857, there is no way around.

**Comment by shapley** [comment]
Hi,

So...if i take out Google Maps it should stay with the project CRS instead. I will try this.
