### ISSUE TITLE
Edition Tool

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#642]
Hi,

I have set an 'Edition' point layer to test data capture but when i press the 'add' button the blue scroll bar seems to 'hang'. Not sure why. Any suggestions welcome. Data is coming from a PostGIS layer with full permissions.

**Comment by gioman** [comment]
> Hi,
> 
> I have set an 'Edition' point layer to test data capture but when i press the 'add' button the blue scroll bar seems to 'hang'. Not sure why. Any suggestions welcome. Data is coming from a PostGIS layer with full permissions.

be sure to have installed php7.1-pgsql or php5-pgsql depending on what version of php you are using.

**Comment by shapley** [comment]
Solved...forgot to install php7.1-pgsql.
Many thanks as always for your excellent support.
