### ISSUE TITLE
startup baselayer - doesn't assume the map chosen by the user in the plugin

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#644]
hi

after [BUGFIX] Manage Google Maps baselayer - name and error (https://github.com/3liz/lizmap-web-client/commit/aa2227c5470c161d77655a5d2a00fa7b880b411b), the LWC expects from the plugin the following entries in "startupBaselayer":

gsat instead  of google-satellite for Google Satellite
ghyb instead  of google-hybrid for Google Hybrid
gphy instead  of google-terrain for Google Terrain
gmap instead  of google-street for Google Streets
...

matching names LWC/plugin...

thanks

**Comment by morvan80** [comment]
Hi,
In the repository "without making changes" it works well the problem is when I have to choose in base layer option putting Google Hybrid always shows me Google Streets.
Thanks for your time

**Comment by josemvm** [comment]
@morvan80 you need to edit your .cfg file, serach for `"startupBaselayer"` and replace the value as above

**Comment by morvan80** [comment]
I have just made the changes you were saying to me but it does not change anything is always set up basic google street. my problem seems to be this https://github.com/3liz/lizmap-web-client/issues/228.
Thank you

**Comment by morvan80** [comment]
I have just made the changes you were saying to me but it does not change anything is always set up basic google street. my problem seems to be this https://github.com/3liz/lizmap-web-client/issues/228.
Thank you

Da: José Macau
Inviato: lunedì 29 gennaio 2018 11:13
A: 3liz/lizmap-web-client
Cc: morvan80; Mention
Oggetto: Re: [3liz/lizmap-web-client] startup baselayer - doesn't assume themap chosen by the user in the plugin (#644)

@morvan80 you need to edit your .cfg file, serach for "startupBaselayer" and replace the value as above

**Comment by morvan80** [comment]
I have just made the changes you were saying to me but it does not change anything is always set up basic google street. my problem seems to be this https://github.com/3liz/lizmap-web-client/issues/228.
Thank you

**Comment by josemvm** [comment]
did you set `"startupBaselayer": "gphy",` ?

**Comment by morvan80** [comment]
I'm also proving this change does not change anything.

**Comment by morvan80** [comment]
I'm also proving this change does not change anything.

Da: José Macau
Inviato: lunedì 29 gennaio 2018 11:42
A: 3liz/lizmap-web-client
Cc: morvan80; Mention
Oggetto: Re: [3liz/lizmap-web-client] startup baselayer - doesn't assume themap chosen by the user in the plugin (#644)

did you set "startupBaselayer": "gphy", ?

**Comment by morvan80** [comment]
Resolved, thanks for your availability.

**Comment by morvan80** [comment]
Resolved, thanks for your availability.

Da: José Macau
Inviato: lunedì 29 gennaio 2018 11:42
A: 3liz/lizmap-web-client
Cc: morvan80; Mention
Oggetto: Re: [3liz/lizmap-web-client] startup baselayer - doesn't assume themap chosen by the user in the plugin (#644)

did you set "startupBaselayer": "gphy", ?
