### ISSUE TITLE
[enhancement] selection inverter

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#650]
hi

the possibility of inverting the selection would be quite useful, like in qgis desktop attribute table

if you agree...

thanks

**Comment by josemvm** [comment]
goog morning

could any developer contribute to the development of this feature?
;-)

Is this task too complex? or do you think it will not be useful?

![imagem](https://user-images.githubusercontent.com/10053874/73522202-b45df780-43ff-11ea-8527-8eb3a0d9aec9.png)

thanks

**Comment by nboisteault** [comment]
Coming soon...
![invert-selection](https://user-images.githubusercontent.com/2145040/76539231-c90ec000-6480-11ea-8467-d6d30b4ead45.gif)

**Comment by josemvm** [comment]
@nboisteault thanks! :-)

**Comment by josemvm** [comment]
done via the https://github.com/3liz/lizmap-web-client/pull/1552
thanks @nboisteault

**Comment by nboisteault** [comment]
Funded by http://www.le64.fr
