### ISSUE TITLE
group as layer - zoom to layer extent doesn't work (information panel)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#651]
hi

for group as layer the zoom to layer extent tool doesn't work
maybe, due to a problem of calculating the bbox of the layer group...

thanks

**Comment by mdouchin** [comment]
fixed in release_3_1 via 9809c62b9ab682999477da9181c6b9c2d9e42b57 
We will merge it into master

**Comment by josemvm** [comment]
thanks @mdouchin
