### ISSUE TITLE
[question] LWC montpellier project & qgis quickfinder plugin

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#652]
hi,

i'm trying to get search results with the qgis quick finder plugin on montpellier project:

after running quick find refresh i can get search results on qgis desktop
![qf](https://user-images.githubusercontent.com/10053874/28776100-000476ac-75ed-11e7-9f30-8fd900cfaa20.jpg)

after that, i put the file montpellier.qfts to the server

but when i try to search on LWC i get results only from nominatim...

![qfl](https://user-images.githubusercontent.com/10053874/28776226-9f3091f2-75ed-11e7-868e-5031efaf73c6.jpg)

is something missing?
thanks

**Comment by mdouchin** [comment]
It should "just work". Have you an url so we can see what is going on ?

**Comment by josemvm** [comment]
http://observa.municipioarraiolos.pt

**Comment by mdouchin** [comment]
You have an internal server ERROR (see http://observa.municipioarraiolos.pt/index.php/lizmap/search/get?repository=montpellier&project=montpellier&query=centre&bbox=3.746034%2C43.542477%2C4.016889%2C43.672143 )

Can you look in your log file `lizmap/var/log/error.log`

What is your Operating system and which version ?

**Comment by josemvm** [comment]
>Can you look in your log file lizmap/var/log/error.log

i've no errors in lizmap/var/log/error.log
i' ve one this recurring error from my varnish proxy: 

`2017-08-08 10:46:53     10.27.3.8       error   Spatialite is not available` and i don't know why...
But this error does not arise when i search on the montpellier project

>What is your Operating system and which version
i'm on ubuntu server 16.04 lts

**Comment by mdouchin** [comment]
You should have an error in the log, since this URL display a 500 error:
http://observa.municipioarraiolos.pt/index.php/lizmap/search/get?repository=montpellier&project=montpellier&query=centre&bbox=3.746034%2C43.542477%2C4.016889%2C43.672143

Have you tried in `/var/log/apache2/*.log` ?

**Comment by josemvm** [comment]
my error.log apache at level trace8

[error.log.txt](https://github.com/3liz/lizmap-web-client/files/1208326/error.log.txt)

**Comment by josemvm** [comment]
can you see something inside the log that justifies 500 error ?

**Comment by rldhont** [comment]
nothing interesting in the log file you provide.
```
[Tue Aug 08 14:58:35.612730 2017] [core:trace3] [pid 30253] request.c(304): [client 10.27.3.8:58620] request authorized without authentication by access_checker_ex hook: /lizmap/search/get
[Tue Aug 08 14:58:35.628385 2017] [http:trace3] [pid 30253] http_filters.c(1102): [client 10.27.3.8:58620] Response sent with status 500, headers:
```
Do you have a specific PHP error log ?

**Comment by josemvm** [comment]
`[HY000] SQLSTATE[HY000]: General error: 1 unknown tokenizer: unicode61  /var/www/html/lizmap-web-client-release_3_1/lib/jelix/db/jDbPDOConnection.class.php       152`

**Comment by josemvm** [comment]
it's a php5.6 problem

**Comment by josemvm** [comment]
no problems with php7

**Comment by rldhont** [comment]
can you update the documentation ?

**Comment by josemvm** [comment]
yes, of course, i'll do it later

**Comment by josemvm** [comment]
hi

quickfinder plugin not working for my projects...

i noticed that the my test projects (.qgs files) contains a reference to the plugin but the montpellier project doesn´t... however this works fine!

>
     <quickfinder_plugin>
      <qftsfilepath type="QString">./teste_qfplugin.qfts</qftsfilepath>
      <project type="bool">true</project>
      <refreshDelay type="int">15</refreshDelay>
      <refreshAuto type="bool">true</refreshAuto>
      <refreshLastAsked type="QString">2017-09-13</refreshLastAsked>
    </quickfinder_plugin>

can you help me please?
thanks

**Comment by josemvm** [comment]
found!:

problem related to the geometry storage format. it doesn´t work in binary format, it only works in text format...

**Comment by mdouchin** [comment]
@josemvm This really need documentation. Indeed, only WKT or Extent formats are working, since binary cannot be decoded by Lizmap Web Client

**Comment by josemvm** [comment]
hi @mdouchin 

i noticed that LWC doesn´t highlight the lines (geometry) as opposed to what happens in QGIS and OSM. instead it highlights a small circle in the middle of the line...

QGIS
![qgis](https://user-images.githubusercontent.com/10053874/30511781-fe7a894c-9ad7-11e7-891e-18eb00eb56af.jpg)
LWC
![lwc](https://user-images.githubusercontent.com/10053874/30511782-04925ce2-9ad8-11e7-8b9e-ead4a82eca81.jpg)

i can open a new issue if you agree
thanks

**Comment by josemvm** [comment]
is it a open layers problem inside lizmap or a lizmap bug?

**Comment by josemvm** [comment]
what do you think about it @rldhont and @mdouchin ?
