### ISSUE TITLE
Lizmap ported to php 7 for debian 9 and ubuntu 16.4

### ISSUE THREAD

**Issue by dassau** [3liz/lizmap-web-client#653]
Hi,

I haven't found any notice. Last summer (june) lizmap was not yet ported to support php 7. Is this already done? And I remember you recommended to use QGIS LTR (2.14) so far. Is the new 2.18 working well, too, from your experience?

Thanks a lot
Otto

**Comment by josemvm** [comment]
hi @dassau 

yes, LWC supports php7!

**Comment by gioman** [comment]
@dassau Hi Otto,

the lists of dependencies to install for PHP7 is

sudo apt-get install xauth htop curl apache2 libapache2-mod-fcgid libapache2-mod-php7.0 php7.0-cgi php7.0-gd php7.0-sqlite php7.0-curl php7.0-xmlrpc python-simplejson python-software-properties php7.0-xml

you have also to enable the following PHP7 extension

/etc/php/7.0/apache2/php.ini > extension=php_xmlrpc.dll

it could php7.1 on some distribution

**Comment by dassau** [comment]
ok, perfect and is QGIS 2.18 also fine to use?

**Comment by josemvm** [comment]
see https://github.com/3liz/lizmap-web-client/issues/547

**Comment by gioman** [comment]
> ok, perfect and is QGIS 2.18 also fine to use?

yes it is, but in QGIS 2.18.10/11 there are a couple of nasty regressions:

1) Server seems that cannot do anymore a getprint of a layout with a label/textbox without crashing
2) on Desktop in print composer the "none" option of a legend (to define to what map object the legend is linked) was removed, this do not allow anymore to do getprint with a "fixed" legend regardless the list of layers passed in the getprint request

No one else noticed the two issues above?

**Comment by dassau** [comment]
Ok, then I will give 2.18 a try with the latest LWC. Thanks a lot Giovanni and José, that already helps me a lot. Bye!

**Comment by rldhont** [comment]
@dassau can you update the documentation https://github.com/3liz/lizmap-documentation ?

**Comment by dassau** [comment]
good idea - just added a short note and can do more, once I really installed it for debian 9.

**Comment by Cww7** [comment]
Hi,

I'm trying to install Lizmap on Debian 9 with virtualbox but Qgis-server doesn't work and I don't know why. I installed all the dependencies for PHP7 like @gioman said.
Did you manage to install it on Debian stretch ?

**Comment by jlstanus** [comment]
@dassau  did you add the notes to the documentation?

**Comment by nboisteault** [comment]
Reopen if issue still occurs.
