### ISSUE TITLE
Cannot see Dataviz module in Windows

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#654]
Hi,
In linux, i can add dataviz module in LWC and see it within qgis lizmap plugin for data configuration. I've tried in windows but without success. The lizmap plugin doesn´t exhibit this module. I've installed LWC 3.2pre. Am i missing any step for dataviz installation? Any guess?
Thanks

**Comment by josemvm** [comment]
hi @jhcardoso 

download the master version https://github.com/3liz/lizmap-plugin/archive/master.zip and replaces the existing one in C:\Users\xxx\.qgis2 \python\plugins\lizmap

i hope it helps

**Comment by jhcardoso** [comment]
hi @josemvm 
Done! Many thanks.
