### ISSUE TITLE
Lizmap ignore my postgreSQL field

### ISSUE THREAD

**Issue by Luisa77** [3liz/lizmap-web-client#655]
Hi, I have a strange problem in the popup configuration on Lizmap version 3.1.
I created a posgreSQL (version 9.3) table, link it to my QGis project, add a new layer and then show some of theese fields to a Lizmap popup on my web client. If I add a new field on the postgreSQL table, I can see it on QGis project and on the list of my popup configuration but if I refresh my browser, there's no way to see my new field. WMS and WFS are checked, the fields have no particular name or value inside... but no way. I can't see my new field. Strange thing is that if I generate  a new layer, it works but I can't do the entire project every time I have to add a simple field.
I have the same credential for db and qgis... I really don't know what to do... 
Any suggestion?
Thx
Luisa

![image](https://user-images.githubusercontent.com/30622790/28821075-69357582-76b4-11e7-84e6-b6edb6aa7d80.png)

**Comment by josemvm** [comment]
hi @Luisa77 

try to run ./lizmap/install/clean_vartmp.sh inside your app lizmap directory...

**Comment by josemvm** [comment]
or check the popup source (auto, lizmap, qgis) in lizmap plugin - layers, popup

**Comment by Luisa77** [comment]
Thanks José,

Popup source is set on "auto".
I cleaned the temp dir but the problem is the same.
I don't know maybe if the problem is due to postgresql database. If I
duplicate the pgsql table and create a new layer on QGis, then Lizmap show
mee my new fields. Really amazin...



*Follow me..*.http://climbyourlife.net/blog/

"*Se mi fosse dato di vivere senza la possibilità di **sognare e di lottare
per un sogno**, bello quanto inutile, sarei un uomo finito*" (G. Gervasutti)

--------------
Prima di stampare, pensa all'ambiente ** Think about the environment before
printing

2017-08-01 13:00 GMT+02:00 José Macau <notifications@github.com>:

**Comment by Oneil974** [comment]
Hi,

"Popup" feature and "Editing" feature don't use the same settings. So if you use drag and drop generating forms  (Like I see in your screen) don't forget to refesh with new fields (And look into your tabs).

For the popups if you use custom popup like HTML you need to update "popup" too, and save qgis project.

Next update lizmap config file by opening lizmap plugin and applying modification. Then send all to your server and try again.

**Comment by rldhont** [comment]
@Luisa77 your screenshot is about editing not popup. And it seems that you use a drag and drop generating forms for editing feature.

The popup is displayed when the user clicked on the map. You can also take a look at the attribute table to be sure that lizmap does not take into account your new field.

**Comment by rldhont** [comment]
@Luisa77 have you fixed this ?

**Comment by chanteclair12** [comment]
I have a similar problem.
When i add a layer to my Qgis project which is yet online (of course i configure before the layer, the project's properties and the lizmap plugin), i can see the new layer but only one field is displayed.
Few time ago, i have just save again my project with a new name and all was ok, but this time, it doesn't work.

**Comment by nboisteault** [comment]
Please reeopen if issue still occurs.
