### ISSUE TITLE
Export layer formats from Lizmap

### ISSUE THREAD

**Issue by jhcardoso** [3liz/lizmap-web-client#656]
Hi,
by default, lizmap allows the export GML and GeoJSON formats. How can include more vector formats, like shapefile or dxf (CAD format), for example?

Thanks

**Comment by josemvm** [comment]
hi @jhcardoso 
see https://github.com/3liz/qgis-wfsOutputExtension

**Comment by rldhont** [comment]
The export is based on WFS and needs a QGIS server plugin to propose more formats.
The DXF is not supported.

**Comment by 80ben** [comment]
Sorry is my first comment!

I use Ubuntu 16.04.3 LTS,   qgis-server 2.14, qgis 2.8.6, Lizmap web client 3.1.1, postgresql 9.5, postgis 2.3.3 python 2.7.11 and php 7.0.18. 

I follow this procedure https://github.com/3liz/qgis-wfsOutputExtension
This is the result of WFS GetCapabilities

 
![wfs getcapabilities](https://user-images.githubusercontent.com/30823307/29061636-f8cd33f0-7c1e-11e7-8256-98275fb49206.png)

The list of available formats only shows me GeoJSON and GML file formats
What checks can I do on qgis-server?

**Comment by nboisteault** [comment]
@80ben Reopen if issue still occurs.
