### ISSUE TITLE
Printing basemap not working here

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#657]
I cannot print basemaps following https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers

https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=boat_survey

* if the group is called osm-mapnik and the layer openstreetmap_mapnik, the basemap is not printed
* if I change the name of the layer to osm-mapnik I get:
<ServiceExceptionReport version="1.3.0"><ServiceException
code="LayerNotDefined">Layer 'osm-mapnik' and/or style 'default' not
defined</ServiceException></ServiceExceptionReport>

Note:
https://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/OpenStreetMap-Tiles-in-QGIS
reports the old projection (900913 instead of 3857), therefore the example proposed is not working:

**Comment by josemvm** [comment]
hi @pcav 

i have a project with a basemap printing (google satellite) and it works fine!

xml:

![gg](https://user-images.githubusercontent.com/10053874/28864051-21a3921c-7763-11e7-97d5-8b79e9ad010b.jpg)

plugin settings

![ggp](https://user-images.githubusercontent.com/10053874/28863947-c2f822f0-7762-11e7-9c28-27951a85c038.jpg)

and, that's all...
i hope it helps

**Comment by pcav** [comment]
Thanks a lot. This looks different from the instructions in the manual, right?
Are you on qgis 2.14 or 2.18?

**Comment by josemvm** [comment]
`This looks different from the instructions in the manual, right?`

no...

> ...group or layer whose name is part...

layer name: **google-satellite**-printing

`Are you on qgis 2.14 or 2.18?`

i'm on 2.14

**Comment by pcav** [comment]
Sorry, I do not understand: https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers contains `google-satellite` for Google Satellite, not `google-satellite-printing`.
Did you add this layer to a `hidden` group?
More generally, may I ask you the favour of describing step by step the procedure, or attach here a miniproject + cfg, so I can chack on my system?
Thanks a lot.

**Comment by josemvm** [comment]
hi @pcav 

the documentation says that:

... `simply add to the QGIS project a group or layer whose name is part of the following list:`
**(the name is part)**

    `google-satellite for Google Satellite`
so, in qgis project, my layer name for **frmt_wms_googlesatellite_tms.xml** is part=**google-satellite** + ("**-printing"** or "foo") = **google-satellite-printing**

in my interpretation of the documentation you can have a  layer whose name is  google-satellite-stampa or anything else...

you just have to respect the name part **google-satellite** for Google Satellite, **google-hybrid** for Google Hybrid, **google-terrain** for Google Terrain, etc.

my .cfg:
>
           "google-satellite-printing": {
            "abstract": "", 
            "displayInLegend": "False", 
            "cacheExpiration": 0, 
            "baseLayer": "True", 
            "noLegendImage": "False", 
            "id": "frmt_wms_googlesatellite_tms20170528213404933", 
            "title": "Google Satellite (Impress\u00e3o)", 
            "singleTile": "False", 
            "groupAsLayer": "False", 
            "popupTemplate": "", 
            "popup": "False", 
            "popupDisplayChildren": "False", 
            "clientCacheExpiration": 2592000, 
            "link": "", 
            "extent": [
                -20037508.34, 
                -20037508.34, 
                20037508.34, 
                20037508.34
            ], 
            "toggled": "True", 
            "crs": "EPSG:3857", 
            "name": "google-satellite-printing", 
            "cached": "True", 
            "type": "layer", 
            "maxScale": 1000000000000, 
            "popupSource": "lizmap", 
            "imageFormat": "image/png", 
            "minScale": 1
        }, 

i hope this helps you

**Comment by pcav** [comment]
I see, thanks for the explanation. I think docs can be improved, I'll be happy of doing it as soon as I have a working example.
Thanks for sharing your cfg; could you please also attach the qgs for me to try?

**Comment by josemvm** [comment]
yes of course
please, check your mailbox and send me feedback

**Comment by pcav** [comment]
So, it turns out to be working if the xml layer is added as a baselayer, *and* the user selects that baselayer for printing.
The trick of hidden layer, as described in the man, does not seem to aply here.
Thanks.

**Comment by rldhont** [comment]
Hi @pcav,
If you take a look at the WMS GetCapabilities, you can see that the osm-mapnik layer has not been well created by your QGIS Server.
Here is the extent of the osm-mapnik layer in your getcapabilities https://lizmap.faunalia.eu/index.php/lizmap/service/?repository=faunalia&project=boat_survey&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
```
<BoundingBox CRS="EPSG:3857" maxx="1e-06" minx="-1e-06" maxy="1e-06" miny="-1e-06"/><BoundingBox CRS="EPSG:4326" maxx="8.98189e-12" minx="-8.98189e-12" maxy="8.98315e-12" miny="-8.98315e-12"/>
```
The right bounding box for EPSG:4326 should be:
```
<BoundingBox CRS="EPSG:4326" maxx="180" minx="-180" maxy="90" miny="-90"/>
```

**Comment by pcav** [comment]
This derived historically from the old Google CRS reported in the website.
Thanks a lot, now it seems to be working fine.

**Comment by pcav** [comment]
Spoken too early:
*  adding a TMS layer, possible in QGIS 2.18, does not seem to work - any special config necessary?
* with the XML approach, base map is working, but overlay layers apparently not::

https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=test_print
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=boat_survey

Thanks for hints.

**Comment by pcav** [comment]
Spoken too early:
*  adding a TMS layer, possible in QGIS 2.18, does not seem to work - any special config necessary?
* with the XML approach, base map is working, but overlay layers apparently not::

https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=test_print
https://lizmap.faunalia.eu/index.php/view/map/?repository=faunalia&project=boat_survey

Thanks for hints.

**Comment by josemvm** [comment]
> with the XML approach, base map is working, but overlay layers apparently not:

it's possible to set transparency values for the xml layer using the layer (i)nformation panel

**Comment by giusme** [comment]
Good evening, I'm trying to print osm basemap layer following https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers using the montpellier example project with this frmt_wms_openstreetmap_mapnik_tms.xml file:

<GDAL_WMS>
    <Service name="TMS">
        <ServerUrl>http://tile.openstreetmap.org/${z}/${x}/${y}.png</ServerUrl>
    </Service>
    <DataWindow>
        <UpperLeftX>-20037508.34</UpperLeftX>
        <UpperLeftY>20037508.34</UpperLeftY>
        <LowerRightX>20037508.34</LowerRightX>
        <LowerRightY>-20037508.34</LowerRightY>
        <TileLevel>18</TileLevel>
        <TileCountX>1</TileCountX>
        <TileCountY>1</TileCountY>
        <YOrigin>top</YOrigin>
    </DataWindow>
    <Projection>EPSG:3857</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>3</BandsCount>
    <Cache />
</GDAL_WMS>

You can find my test site here:
http://94.177.206.19:8282/index.php/view/map/?repository=montpellier&project=montpellier.

Colud you help me?

**Comment by josemvm** [comment]
hi @giusme 

> To add to printing a layer that replaces an external baselayer, simply add to the QGIS project a group or layer whose name is part of the following list:

in your case:

> osm-mapnik for OpenStreetMap

e.g. **osm-mapnik-printing**

that's all

**Comment by giusme** [comment]
hi @josemvm I have already added a group layer osm-mapnik inside a hidden folder following following https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers tutorial, but I can't print the OSM baselayer. You can see my test site here:

http://94.177.206.19:8282/index.php/view/map/?repository=montpellier&project=montpellier.

**Comment by josemvm** [comment]
i can't get your url
you don´t need a hidden folder

**Comment by giusme** [comment]
The correct url is:

http://94.177.206.19:8282/index.php/view/map/?repository=montpellier&project=montpellier

I used an hidden folder following the https://github.com/3liz/lizmap-documentation/blob/master/source/publish/advanced_lizmap_config.rst#allow-printing-of-external-baselayers tutorial. I tried also to remove hidden folder but still i can't print mi baselayer.

**Comment by josemvm** [comment]
no, i can't get your url... time out

**Comment by giusme** [comment]
I tested the url is working..Could be a problem with your firewall?

**Comment by josemvm** [comment]
sorry, yes it's a problem with my firewall
now, i can see your map but i can't find the problem...

you can try to create new project (with other basemap) or try the @pcav alternative solution

**Comment by giusme** [comment]
I created a new project, added other basemaps /Bing and Goggle satellite with API key), tried the @pcav alternative solution, but nothing to do..I can't print basemap layers...

**Comment by josemvm** [comment]
weird...
i'm on linux, qgis server 2.14 and lizmap 3.14 and master.  what software are you using?

**Comment by giusme** [comment]
I'm using windows server 2012, qgis server 2.14 ltr and lizmap 3.2 and master...

**Comment by josemvm** [comment]
maybe the developers can take a look at your site...

**Comment by nboisteault** [comment]
@giusme Reopen if issue still occurs.

**Comment by giusme** [comment]
I still have problems printing OSM basalayer. Any solution?

**Comment by giusme** [comment]
Yes I tried it.  I loaded your qlr inisde qgis and it is showed correctly. Then I setted it as baselayer in Lizmap plugin but when I access to Lizmap-we-client I can't see any basemap.
![schermata 2018-12-12 alle 16 46 53](https://user-images.githubusercontent.com/32569091/49881025-a3ce7480-fe2d-11e8-96c3-3dd9bc417a72.png)

**Comment by giusme** [comment]
Lookink at WMS GetCapabilities I found, as in @pcav case, incorrect bounding box for osm-mapnik layer:

   <Layer queryable="1">
     <Name>hidden</Name>
     <Title>hidden</Title>
     <CRS>CRS:84</CRS>
     <CRS>EPSG:32633</CRS>
     <CRS>EPSG:3857</CRS>
     <EX_GeographicBoundingBox>
        <westBoundLongitude>-8.98315e-12</westBoundLongitude>  
        <eastBoundLongitude>8.98315e-12</eastBoundLongitude>
        <southBoundLatitude>-8.98189e-12</southBoundLatitude>
        <northBoundLatitude>8.98189e-12</northBoundLatitude>
     </EX_GeographicBoundingBox>
     <BoundingBox CRS="EPSG:3857" maxx="1e-06" minx="-1e-06" maxy="1e-06" miny="-1e-06"/>
     <BoundingBox CRS="EPSG:32633" maxx="-1.18866e+06" minx="-1.18866e+06" maxy="1.02804e-06" miny="-1.02804e-06"/>
   </Layer>
   <Layer queryable="1">
     <Name>osm-mapnik</Name>
     <Title>osm-mapnik</Title>
     <CRS>CRS:84</CRS>
     <CRS>EPSG:32633</CRS>
     <CRS>EPSG:3857</CRS>
     <EX_GeographicBoundingBox>
        <westBoundLongitude>-8.98315e-12</westBoundLongitude>  
        <eastBoundLongitude>8.98315e-12</eastBoundLongitude>
        <southBoundLatitude>-8.98189e-12</southBoundLatitude>
        <northBoundLatitude>8.98189e-12</northBoundLatitude>
     </EX_GeographicBoundingBox>
     <BoundingBox CRS="EPSG:3857" maxx="1e-06" minx="-1e-06" maxy="1e-06" miny="-1e-06"/>
     <BoundingBox CRS="EPSG:32633" maxx="-1.18866e+06" minx="-1.18866e+06" maxy="1.02804e-06" miny="-1.02804e-06"/>
   </Layer>
  </Layer>
</Capability>
</WMS_Capabilities>

I used a hidden folder with a osm-mapnik subgroup and inside I loaded the frmt_wms_openstreetmap_mapnik_tms.xml layer, but in the WMS GETCapabilities I see only the hidden and the osm-mapnik group (with not right coordinates) but not the frmt_wms_openstreetmap_mapnik_tms, so I think this layer has not been well created by your QGIS Server.
Any help to solve?
Thank you
