### ISSUE TITLE
Internationalized projects

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#658]
A frequent request is having internationalizedprojects, i.e. essentially the same project, with information in different languages (e.g. labels from a different column, html content from a different media directory, etc.
Currently one has to clone the entire project + cfg, but it would be interesting to have a way to show different content according, e.g. to the language of the browser.

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/453

**Comment by pcav** [comment]
Right, it's a duplicate. Thanks, sorry for the noise.
