### ISSUE TITLE
Group of layers global tick mark

### ISSUE THREAD

**Issue by vherreros** [3liz/lizmap-web-client#660]
Hellos,

I've seen that under LizMap web client 3.1.1, when displaying a QGIS group of layers with its individuals layers, there is no check box for checking all the contents of the group at once. There is just the chance to collapse or expand the group, as can be seen on this snapshot:

![snap](https://user-images.githubusercontent.com/5656340/28919687-e4c4b866-784e-11e7-929a-2097e013b16f.jpg)

However, in previous versions there was the 'global' check box:

![snap](https://user-images.githubusercontent.com/5656340/28919780-44e7fad2-784f-11e7-8898-149759a63680.jpg)

Is there a way to revert to the previous state?

Thanks in advance.

**Comment by josemvm** [comment]
hi,

i can not reproduce this issue, i'm using master version
but you can try `"hideGroupCheckbox": "False",` in your project.cfg

**Comment by vherreros** [comment]
Manually changing this parameter in the cfg file works as expected.
However, I can't find the option to configure this parameter from QGIS
LizMap plugin interface. I'm using QGIS 2.14.11-Essen and LizMap WebClient
plugin 2.1.3. I've upgraded the plugin to the latest version, 2.3.0 and I
can't still find the option.

Maybe is it a bug from the plugin interface?

2017-08-03 13:40 GMT+02:00 José Macau <notifications@github.com>:

**Comment by josemvm** [comment]
download the master version https://github.com/3liz/lizmap-plugin/archive/master.zip and replaces the existing one in C:\Users\xxx.qgis2\python\plugins\lizmap

![xxx](https://user-images.githubusercontent.com/10053874/28921581-692fac92-784e-11e7-9010-3c44f761f876.jpg)

**Comment by vherreros** [comment]
Great!

Master branch is working as expected. So I suppose it's just a matter of
adding that master branch to the QGIS plugins repo, right?

Thanks!

**Comment by vherreros** [comment]
By the way, I've seen a weird behaviour on this parameter when using the master branch of the lizmap plugin in QGIS. When you open the plugin UI, it doesn't matter what option does the project have - it always show the box for 'Hide checkboxes for groups' checked. And if you click on 'Apply' button, it really applies it. So every time you open the lizmap plugin UI for changing anything, you have to review the state of this checkbox...

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-plugin/issues/68

**Comment by vherreros** [comment]
OK, thanks for you redirection to the proper bug thread... I close the present issue, so,
