### ISSUE TITLE
media directory location for project theme

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#661]
Hi,

Just want to clarify where the 'media' directory should be located specifically to utilise my own 'theme' for a single project only. The guide says that it should be located at the same level as the QGIS project. 

Is this on the 'server' i.e usr/lib/cgi-bin/project/myproject.qgs?
or in the 'home' directory i.e /home/project/myproject.qgs? (then sym-linked to above)

**Comment by josemvm** [comment]
hi @shapley 

see here: https://docs.3liz.com/en/publish/advanced_lizmap_config.html#media-in-lizmap
