### ISSUE TITLE
Menu Bar and Dock CSS Configuration

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#662]
Hi,

I am trying to configure some colour changes to the Menu Bar (toolbar) and Docks through amending the css files in the 'media' directory. Which 'css' files (main/admin/map/media/view) and under what 'headings' control the colours.

**Comment by josemvm** [comment]
hi,

you can do some changes using lizmap backoffice: user(admin), my account, theme
https://github.com/3liz/lizmap-web-client/commit/af10c30c4b36238968f0f23e927d8fe1f5fcd824

**Comment by josemvm** [comment]
you can see here: https://docs.3liz.com/en/publish/advanced_lizmap_config.html#creating-simple-themes

**Comment by shapley** [comment]
Yes...but that seems to control the 'global' colour theme not the individual project theme stored in the 'media' directory. If there a way of changing the colours of just the open project?

**Comment by josemvm** [comment]
> it is possible to create themes for all maps of a repository or for a single map

**Comment by josemvm** [comment]
according to the lizmap documentation
i have not tried it yet...
