### ISSUE TITLE
LWC edition tool - send Long/Lat to postgresql table fields

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#663]
hi,

based on the script example https://github.com/3liz/lizmap-web-client/issues/624

how can i send the geographic coordinates values (decimal degrees, e.g.) from a point feature to postgresql database?

thanks in advance!

**Comment by mdouchin** [comment]
You really should do this inside the database: use triggers and functions such as ST_X(geom) to automatically set or modify the lat and lon based on the geometry. This would be much more robust, for example if you use other tool to edit the data outside Lizmap

**Comment by josemvm** [comment]
i was thinking that it would be possible to get values from coordinate reading of mouse position (lower right corner, below the overview area)...

**Comment by josemvm** [comment]
anyway, thanks
