### ISSUE TITLE
Error 500 Debian 8 et Debian 9 Php 5.4 et php 7 ( even with command lizmap/install/set_rights.sh www-data www-data)

### ISSUE THREAD

**Issue by ncraveia** [3liz/lizmap-web-client#664]
Hello, 
I want to install lizmap 3.1.1 for my private use

I have a "Error 500. A technical error has occured. Sorry for this trouble.
The application is not installed"

This typical error :)

I tested the  installation with Debian 9 and php 7  and secondly tested with Debian 8 and php 5.4

I followed the notice lizmap but I have always this message.. for your information I have already installed lizmap 2.12 on another server with success.

This command "lizmap/install/set_rights.sh www-data www-date" doesn't resolve a problem

Thank you for your help

**Comment by gioman** [comment]
@ncraveia The  Error 500 returned by the browser is not informative, please open your Apache error log, look for the proper error message and post it here. Cheers!

**Comment by ncraveia** [comment]
Fichier error.log 

`root@scarto:/home/nicolas# nano /var/log/apache2/error.log
  GNU nano 2.2.6                                                            Fichier : /var/log/apache2/error.log

[Sun Aug 13 14:31:57.369050 2017] [mpm_event:notice] [pid 745:tid 139643070367616] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Sun Aug 13 14:31:57.369140 2017] [core:notice] [pid 745:tid 139643070367616] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:33:41.733655 2017] [mpm_event:notice] [pid 657:tid 140585508620160] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Sun Aug 13 14:33:41.741597 2017] [core:notice] [pid 657:tid 140585508620160] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:45:12.639569 2017] [mpm_event:notice] [pid 657:tid 140585508620160] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Aug 13 14:45:12.645926 2017] [mpm_event:notice] [pid 657:tid 140585508620160] AH00489: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Sun Aug 13 14:45:12.645936 2017] [core:notice] [pid 657:tid 140585508620160] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:45:12.978112 2017] [mpm_event:notice] [pid 657:tid 140585508620160] AH00491: caught SIGTERM, shutting down
[Sun Aug 13 14:45:14.039932 2017] [mpm_event:notice] [pid 2626:tid 139687021967232] AH00489: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 14:45:14.040016 2017] [core:notice] [pid 2626:tid 139687021967232] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:45:17.936490 2017] [mpm_event:notice] [pid 2626:tid 139687021967232] AH00491: caught SIGTERM, shutting down
[Sun Aug 13 14:45:19.000252 2017] [mpm_prefork:notice] [pid 3737] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 14:45:19.000340 2017] [core:notice] [pid 3737] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:45:20.314945 2017] [mpm_prefork:notice] [pid 3737] AH00169: caught SIGTERM, shutting down
[Sun Aug 13 14:45:21.474668 2017] [mpm_prefork:notice] [pid 3837] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 14:45:21.474784 2017] [core:notice] [pid 3837] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 14:51:46.176852 2017] [mpm_prefork:notice] [pid 3837] AH00169: caught SIGTERM, shutting down
[Sun Aug 13 14:51:47.634638 2017] [mpm_prefork:notice] [pid 5518] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 14:51:47.634696 2017] [core:notice] [pid 5518] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 15:31:40.770938 2017] [mpm_prefork:notice] [pid 5518] AH00169: caught SIGTERM, shutting down
[Sun Aug 13 15:31:41.847987 2017] [mpm_prefork:notice] [pid 10453] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 15:31:41.848046 2017] [core:notice] [pid 10453] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 15:43:40.281534 2017] [mpm_prefork:notice] [pid 10453] AH00169: caught SIGTERM, shutting down
[Sun Aug 13 15:43:41.358121 2017] [mpm_prefork:notice] [pid 10572] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 15:43:41.358181 2017] [core:notice] [pid 10572] AH00094: Command line: '/usr/sbin/apache2'
[Sun Aug 13 18:35:33.059095 2017] [mpm_prefork:notice] [pid 744] AH00163: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 configured -- resuming normal operations
[Sun Aug 13 18:35:33.069074 2017] [core:notice] [pid 744] AH00094: Command line: '/usr/sbin/apache2'
`

**Comment by gioman** [comment]
> Fichier error.log

@ncraveia have you tried in the first place if QGIS Server is working?

http://my_server_ip/cgi-bin/qgis_mapserv.fcgi?map=/path/to/project.qgs&service=WMS&request=GetCapabilities

**Comment by ncraveia** [comment]
Not Found

The requested URL /cgi-bin/qgis_mapserv.fcgi was not found on this server.

Apache/2.4.10 (Debian) Server at 192.168.1.27 Port 80

**Comment by gioman** [comment]
> The requested URL /cgi-bin/qgis_mapserv.fcgi was not found on this server.

so better check your QGIS Server installation first... without it you can't have LizMap working.

**Comment by ncraveia** [comment]
Ok thanks !

I have a result with THIS commande "a2enmod cgid" and restart apache2

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
<ServiceException code="WMS configuration error">
There was an error reading the project file or the SLD configuration
</ServiceException>
</ServiceExceptionReport>

But error is always present

**Comment by gioman** [comment]
> <ServiceException code="WMS configuration error"> There was an error reading the project file or the SLD configuration </ServiceException>

if QGIS Server can't read your QGIS project file then is normal that LM won't work. You must first solve your issues with QGIS Server (it seems you are now ok) and check that the project you want to use in LM works for QGIS Server in first place.

**Comment by mdouchin** [comment]
Have your installed the application with the command `php lizmap/install/installer.php` ?  Installation procedure has changed between 2.X and 3.X versions
See https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#installation

**Comment by ncraveia** [comment]
Thanks mdouchin and gioman

php lizmap/install/installer.php and a2enmod cgid  is the solution for me :)

Thank you !

**Comment by rldhont** [comment]
@ncraveia if the documentation is not complete, you can contribute to the documentation https://github.com/3liz/lizmap-documentation
