### ISSUE TITLE
Baselayers and Locating

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#665]
Hi,

Sometimes if i add a new 'baselayer' the 'dropdown' option to select the second baselayer does not appear. The same can happen with the 'Locating' dropdown list. It will sometimes appear with no listing. Another project in my repository appears to work fine.

![baselayers](https://user-images.githubusercontent.com/7022885/29569746-5e581ee6-874c-11e7-8e44-363c8ea23fe5.png)
![locating](https://user-images.githubusercontent.com/7022885/29569747-5e7102a8-874c-11e7-82d4-8b186b52b021.png)

**Comment by shapley** [comment]
Hi,

Decided to try and re-install apache2 with all compontents as in documentation for ubuntu server but i now get the following error when i go to:-

http://myIPAddress/lm

<?php
/**
* @package   lizmap
* @subpackage lizmap
* @author    3liz
* @copyright 2011 3liz
* @link      http://3liz.com
* @license    Mozilla Public License : http://www.mozilla.org/MPL/
*/

require ('../application.init.php');
require (JELIX_LIB_CORE_PATH.'request/jClassicRequest.class.php');

checkAppOpened();

// Charge la configuration
jApp::loadConfig('index/config.ini.php');

// nouveau coordinateur, que l'on indique Ã  jApp
jApp::setCoord(new jCoordinator());

// Nouvel objet request, que l'on passe au coordinateur, pour traiter le routage.
jApp::coord()->process(new jClassicRequest());

**Comment by shapley** [comment]
So, i've re-installed the 'libapache2-mod-php7.0' library on Ubuntu Server and the 'process(new jClassicRequest());' error has gone and i'm back to the original problem above. Still unable to get the dropdown's to display the setup attributes. This is only happening with one repository, the other one works properly so is the problem in the Lizmap Plugin in the qgis project?

**Comment by josemvm** [comment]
hi
are you using ie browser?

**Comment by shapley** [comment]
Hi,
No...Chrome/Firefox

**Comment by shapley** [comment]
Hi,

Perhaps one option to try and remedy this would be to somehow remove and re-install the Jelix/php modules only. When i try to re-install by the 'installer.php' it tells me the 'module dependencies are OK' but how can i **remove them before** a reinstall without replacing the whole 'lizmap-web-client-release_3_1' folder?

$ sudo php lizmap/install/installer.php

Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jauthdb_admin installed
Module master_admin installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauth installed
Module jauthdb installed
Module admin installed
Module lizmap installed
Module view installed
Module proj4php installed
All modules are installed or upgraded for the entry point index
[notice] Installation starts for the entry point admin
All modules dependencies are ok
Module jelix installed
Module jauthdb_admin installed
Module master_admin installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauth installed
Module jauthdb installed
Module admin installed
Module lizmap installed
Module view installed
Module proj4php installed
All modules are installed or upgraded for the entry point admin
[notice] Installation starts for the entry point script
All modules dependencies are ok
Module jelix installed
Module jauthdb_admin installed
Module master_admin installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauth installed
Module jauthdb installed
Module admin installed
Module lizmap installed
Module view installed
Module proj4php installed
All modules are installed or upgraded for the entry point script
Installation ended.

**Comment by shapley** [comment]
Removed and restored '.cfg' file from project folder but still no dropdown.

**Comment by nboisteault** [comment]
@shapley Reopen and give an url to test if issue still occurs.
