### ISSUE TITLE
lizmap 3.1.3 on debian 9 and php 7 problem for saving

### ISSUE THREAD

**Issue by Lgranjon** [3liz/lizmap-web-client#666]
Hi all
I install lizmap on debian 9 with php 7 and it seems to be work.
But I have some troubles.
When I want to modify my password I have
Error 500. A technical error has occured. Sorry for this trouble.
When I add a repository, it work but when I try to modify it i have
Error 500. A technical error has occured. Sorry for this trouble.
Have you an idea ?
Thanks

**Comment by Lgranjon** [comment]
Ok sorry for that
I change the right on jauth.db for my apache user and it's ok now

**Comment by pcav** [comment]
Have you ran set_rights.sh?

Il 25 agosto 2017 14:36:30 WEST, Lgranjon <notifications@github.com> ha scritto:
>Hi all
>I install lizmap on debian 9 with php 7 and it seems to be work.
>But I have some troubles.
>When I want to modify my password I have
>Error 500. A technical error has occured. Sorry for this trouble.
>When I add a repository, it work but when I try to modify it i have
>Error 500. A technical error has occured. Sorry for this trouble.
>Have you an idea ?
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/3liz/lizmap-web-client/issues/666

-- 
Sent from mobile. Sorry for being short

**Comment by Lgranjon** [comment]
Yes I do
