### ISSUE TITLE
Popup works only clicking on polygon border

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#669]
Clicking on the inner area results in "no geom here":
http://qgis.arpal.gov.it/lm313/index.php/view/map/?repository=baora&project=balneazione

**Comment by rldhont** [comment]
In your example which layer is not clickable ?

**Comment by pcav** [comment]
"Dati di balneazione", the grey area. The border is clickable, the inner area is not.
Thanks.

**Comment by rldhont** [comment]
@pcav I have no problem to click the inner and ave the popup.

**Comment by pcav** [comment]
which browser? firefox here

**Comment by pcav** [comment]
in fact, with Chromium it works well

**Comment by rldhont** [comment]
Firefox for me, but it will be interesting to compare GetFeatureInfo URLs.

**Comment by pcav** [comment]
Tested on other systems, no clear results: it does not work on a Win machine with Chrome 60.0.3112.113 nor Explorer. Now it works back also on Fireox here.
Could it be an incomplete loading of a js lib?

**Comment by pcav** [comment]
I'm available for further testing, just let me know.
Thanks.

**Comment by rldhont** [comment]
@pcav, do you have done more test ? I don't know why you have this issue. I think it comes from QGIS Server. For exemple: Do you have the issues with all the polygon or just for some ? Do you have some geometry errors in the layer ?

**Comment by pcav** [comment]
Unfortunately I could not figure out a general pattern. Just tested, the geometry checker finds some sliver and small areas, but no topology error.

**Comment by pcav** [comment]
Using tiles seems to prevent the popup from appearing.

**Comment by nboisteault** [comment]
@pcav Reopen if issue still occurs.
