### ISSUE TITLE
geolocation stopped working in firefox 55

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#675]
hi,

i noticed that geolocation stopped working in firefox 55
i downgraded to version 54 (54.0.1) and it works now

**Comment by mdouchin** [comment]
Firefox (and other browsers) has change the security policy about geolocation. Now, you need an site with encryption ( HTTPS ) to be able to use geolocation inside your browser.

**Comment by josemvm** [comment]
while the users do not proceed due migration, the opera browser is an exception...

**Comment by rldhont** [comment]
@josemvm it will probably be interesting to add some comment in the plugin to explain it and/or move this text: https://docs.3liz.com/en/install/linux.html#enable-geolocation

**Comment by josemvm** [comment]
yes, i'll do it
