### ISSUE TITLE
ServerName/Localhost

### ISSUE THREAD

**Issue by chanteclair12** [3liz/lizmap-web-client#676]
Hi everybody,
I have a problem with the servername of my qgis server.
I have installed Qgis Server 2.14 with Lizmap Web Client 3.1.3 on a Windows Server 2008 R2.
All works well but i have a problem for opening a pdf document from a field of a layer.
On the server it works well but the new windows has got an address starting with localhost. The problem is with a PC on the same network. The link tries to still open an address with localhost instead of the IP of the server.
I have changed the ServerName in the httpd.conf and the httpd-vhosts.conf : IP address 192.168.x.x instead of localhost, reboot Apache server and even the server but no result.
Could you tell me where i can change this parameter please ?
Thx.

**Comment by rldhont** [comment]
Hi @chanteclair12 
Lizmap is based on Jelix and Jelix has a cache in which is stored the ServerName used by users to accessing the application.
You have to clean the lizmap temp directory `temp\lizmap\www\ ` and only used the servername to access Lizmap web client.
If you think the documentation about Windows install https://docs.3liz.com/en/install/windows.html is not complete, thanks to contribute to https://github.com/3liz/lizmap-documentation and explicitly here https://github.com/3liz/lizmap-documentation/blob/master/source/install/windows.rst

**Comment by chanteclair12** [comment]
Thanks @rldhont for your quick answer.
Is it the good directory ? : 
C:\webserver\lizmap\prod\lwc\temp\lizmap\www
Do I erase all the Cache directory (which contains myapp directory and qgisprojects directory) and also the admin~config.ini.php.resultini.php and indexéconfig.ini.php.resultini.php ?
Thx

**Comment by rldhont** [comment]
You have to clean this directory C:\webserver\lizmap\prod\lwc\temp\lizmap\www  but do not remove it.

**Comment by chanteclair12** [comment]
I did and now the new windows as the good address starting with 192.168.x.x but i have got this error message
`error | "404 not found (wrong action)"
-- | --
message | "No media file in the specified path: /media/pdf/64-2016-07-13-011.pdf"
`
is it only a problem with the url in my bdd field ?

**Comment by rldhont** [comment]
It is now an issue with the path in your bdd field. It has to do not start with **/** but with **media**.

**Comment by chanteclair12** [comment]
Without the "/" in the bdd field, the problem is persisting : 
`error | "404 not found (wrong action)"
-- | --
message | "No media file in the specified path: media/pdf/64-2016-07-13-011.pdf"
`

**Comment by chanteclair12** [comment]
I have found what was wrong.
First, i had put my qgis project in rep2 and not erase it and it seems that when the url was built there was a mix between my rep1 where my project is and rep2.
Without the same project in rep2, the file is well opened in a new window.
Thx for your help.
