### ISSUE TITLE
feature request: highlight on info

### ISSUE THREAD

**Issue by mach0** [3liz/lizmap-web-client#684]
When I click a feature in a map I am getting all infos about this feature but the feature itself is not highlighted (as it is when I select a feature).
This is a bit uncomfortable as I do have a street network here, where the streets are sometimes very close to each other and it would help a lot to have the (info) feature highlighted.

It would be nice to have the features highlighted the same way with the info button as they are with the select button.

**Comment by josemvm** [comment]
:+1:
