### ISSUE TITLE
LWC doesn´t export content

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#685]
hi

at this moment the LWC (master version) doesn't export content
the output is an empty file

thanks

**Comment by rldhont** [comment]
Which LWC version ?

**Comment by josemvm** [comment]
>  LWC (master version)

**Comment by rldhont** [comment]
sorry...

**Comment by josemvm** [comment]
:-)

**Comment by mdouchin** [comment]
We need more context:
* qgis server version
* vector layer provider (postgres or other ?)
* lizmap log messages and errors

**Comment by rldhont** [comment]
Which export type ?

**Comment by josemvm** [comment]
>  qgis server version

2.14.19 ltr

> vector layer provider (postgres or other ?)

postgres

> lizmap log messages and errors

i'll inspect

> Which export type ?

all

**Comment by josemvm** [comment]
lizmap error.log:

> 2017-10-11 10:25:03     10.27.10.180    notice  2017-10-11 10:25:03     [8]     Undefined variable: data        /var/www/html/lizmap-web-client-master/lizmap/modules/lizmap/controllers/service.classic.php 1076

**Comment by mdouchin** [comment]
I found the error, and will provide a fix

**Comment by mdouchin** [comment]
@josemvm could you try with the new master please ?

**Comment by josemvm** [comment]
hi @mdouchin 

very nice :-)
hard work at  yesterday night!!!

thanks for your work

ps: if you (3Liz guys) had more time to work on LWC you'd make it a GIS Ferrari. Even so, it is on right way

**Comment by rldhont** [comment]
For the ferrari we have to update some libs. Thanks
