### ISSUE TITLE
Configure the overview scale

### ISSUE THREAD

**Issue by ElieLP** [3liz/lizmap-web-client#686]
Hello,
I need a larger scale on my overview, but I don't see any methods to configure it.

**Comment by josemvm** [comment]
hi @GgLaPoule 

the overview map is related to the map maximum extent defined in QGIS project properties, OWS server tab.
in the plugin you can define the initial extent of the map.

maybe it could be enhanced in the future...

**Comment by rldhont** [comment]
@josemvm can you tag this to enhancement ?
@GgLaPoule can you update an issue in https://github.com/3liz/lizmap-plugin, to request this enhancement ?

**Comment by nboisteault** [comment]
In Lizmap 3.5.3, initial overview scale will be the initial extent defined in the Lizmap plugin.

https://github.com/3liz/lizmap-web-client/issues/2837#issuecomment-1090100503
