### ISSUE TITLE
attribute table (related table) - photo column/field alias

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#688]
hi

the field alias "Fotografia" in attribute table (related table) photo column has been lost in **LWC master version**

**3.1** ![31](https://user-images.githubusercontent.com/10053874/31614347-062228c2-b27e-11e7-81e6-0d1083be9d4a.jpg) **master** ![32](https://user-images.githubusercontent.com/10053874/31614367-204e8380-b27e-11e7-89a9-b91ac1284e7f.jpg)

thanks

**Comment by josemvm** [comment]
sorry, i'm doing some more tests...
if necessary I will reopen this issue

have a nice weekend!

**Comment by josemvm** [comment]
the problem occurs in the following behaviour:

- in the case where the child table has records without pictures in photo field
- when the user starts by selecting in the main table a record which corresponds to the previous item

I'll send you an illustrative video for help to understand the behaviour.

thanks

**Comment by josemvm** [comment]
not only for images in related tables but for single tables too in documentation field alias

![xxx](https://user-images.githubusercontent.com/10053874/32322331-1645dfb4-bfbc-11e7-8dbc-5c8dc638dcf9.jpg)

it's a regression in master version

**Comment by rldhont** [comment]
can you provide the project ?

**Comment by josemvm** [comment]
yes @rldhont 
please, check your mail box

**Comment by rldhont** [comment]
First time of access to the table, raw data are displayed. After reloaded the page, the table displays link.
It 's strange

**Comment by josemvm** [comment]
displays link because you click on feature whose media field is not filled

**Comment by rldhont** [comment]
I have understand the issue. If the column started by an empty string, the first cell does not contain string, the datatable does not activate the replacement of string by link! @mdouchin ping

**Comment by josemvm** [comment]
that's right @rldhont

**Comment by josemvm** [comment]
it's a regression from 3.1

**Comment by rldhont** [comment]
@josemvm can you test the PR *[BUGFIX] Attribute table cell renderer* #915 ?

**Comment by josemvm** [comment]
solved!!!
thanks @rldhont :-)
