### ISSUE TITLE
Module "lizmap" is unknown or disabled 

### ISSUE THREAD

**Issue by majorxtrem** [3liz/lizmap-web-client#689]
Bonjour, 

J'essaie d'utiliser les commandes pour prégénérer le cache dans un projet mais j'ai une erreur qui est retournée par la commande.
```
php lizmap/scripts/script.php lizmap~wmts:capabilities demo montpellier
2017-10-14 15:58:55     [130]   Module "lizmap" is unknown or disabled  /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php    160

```

Avez-vous une idée ?

PS: j'utilise la branche master (mis à jour à l'instant) et la version 5.6 de php

D'avance merci

**Comment by josemvm** [comment]
documentation: https://docs.3liz.com/en/admin/cache.html?highlight=seeding#seeding

tested here, master version, php 7.0, with

`php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier`

same error:

`2017-11-02 16:15:45     127.0.0.1       error   2017-11-02 16:15:45     [130]   Module "lizmap" is unknown or disabled  /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 160
`

version 3.1:
no output and no errors...

**Comment by jancelin** [comment]
+1

**Comment by rldhont** [comment]
It seems to be an error in the lizmap installation. The script config does not have all the needed modules. Can you replay:
```
sudo lizmap/install/set_rights.sh www-data www-data
sudo lizmap/install/clean_vartmp.sh
php lizmap/install/installer.php
sudo lizmap/install/clean_vartmp.sh
```

**Comment by laurentj** [comment]
does this error appear after a fresh installation ? after a change in the web server configuration ? after an upgrade of Lizmap ? after an upgrade of PHP ? Did this script worked correctly in the past and if yes, what changes did you made in lizmap, in the web server etc. ?

**Comment by josemvm** [comment]
> does this error appear after a fresh installation ?

yes
`2017-12-12 17:04:33     [130]   Module "lizmap" is unknown or disabled  /var/www/html/lizmap-web-client-master-edition-32/lib/jelix/core/jCoordinator.class.php 160`

>  after a change in the web server configuration ?

no

> after an upgrade of Lizmap ?

no

> after an upgrade of PHP ?

no

> Did this script worked correctly in the past and if yes, what changes did you made in lizmap, in the web server etc. ?

yes, no changes

**Comment by josemvm** [comment]
hi @jancelin 

can test this fix?

https://github.com/jelix/jelix/issues/314
