### ISSUE TITLE
[question] Print button not generated in my Lizmap Project

### ISSUE THREAD

**Issue by ocastillog** [3liz/lizmap-web-client#691]
I select the "Print" option in the "Map tools" section for the Lizmap plugin in my QGis project, then when my project is published the "Print button" is not displayed in my Lizmap Project. Any Ideas? Thanks in advance

**Comment by josemvm** [comment]
hi @ocastillog 

> QGIS project has at least one print composition

https://docs.3liz.com/en/publish/advanced_lizmap_config.html?highlight=print#printing-configuration

i'm sorry if this is not your case

**Comment by josemvm** [comment]
did you solve your issue @ocastillog?
