### ISSUE TITLE
Overview isn't correctly displayed

### ISSUE THREAD

**Issue by fredericmazzini** [3liz/lizmap-web-client#692]
On version 3.1.4 the overview isn't correctly displayed (see attached file). 
![image004](https://user-images.githubusercontent.com/19612433/31706470-61e874e2-b3e9-11e7-8cca-d4beaafb8291.png)
There is a large space between the frame left border and the overview left border.

I also have 2 others questions about overview ;
- how do I define its  extent ?
- how do I define its scale ?

Thanks

Fred

**Comment by josemvm** [comment]
hi

i had noticed it a long time ago...

> there is a large space between the frame left border and the overview left border

the same for the frame top border and the overview top border

**Comment by josemvm** [comment]
#686

**Comment by josemvm** [comment]
i think it could be enhanced simultaneously with this other issue https://github.com/3liz/lizmap-web-client/issues/686

**Comment by josemvm** [comment]
see also https://github.com/3liz/lizmap-web-client/issues/768

**Comment by josemvm** [comment]
thanks @rldhont !
