### ISSUE TITLE
 Protocoles d’authentification

### ISSUE THREAD

**Issue by Louisus** [3liz/lizmap-web-client#696]
Bonjour,

Savez vous si Lizmap web client est compatible avec les protocoles d’authentification SAML 2.0 ou WS-FED?

Cordialement

Louis

**Comment by rldhont** [comment]
Bonjour, Lizmap Web Client n'intègre pas pour le moment la possibilité d'utiliser un Système d'Authentification Unique ou SSO. Il est par contre possible d'utiliser LDAP.

Hello,Lizmap Web Client does not currently include the ability to use a Single Sign On (SSO) Authentication System. It is possible to use LDAP.

**Comment by mbernasocchi** [comment]
@rldhont this is still the case right?
