### ISSUE TITLE
Problem editing in lizmap-client

### ISSUE THREAD

**Issue by ronbm08** [3liz/lizmap-web-client#697]
Hello, I have a problem I am new using lizmap and postgresql, I do not know if it is something very elemental however I can not understand that it is wrong I think it is referring to the user and permissions but if they can help me ... I have a database and a table added to the lizmap canvas client which I configured in qgis with the lizmap plugin to be able to edit the layer, but when I want to edit it happens this: 

![wron](https://user-images.githubusercontent.com/1429709/32115030-80254c9e-bb02-11e7-9021-f0fd50b384e2.png)

and it does not happen there, I can not really edit that I have to do to be able to edit, in qgis if I succeeded edit but I do not know how to edit from lizmap client

Do you have any idea

thx 
Ronny

**Comment by gioman** [comment]
@ronbm08 do you have php-pgsql installed?

**Comment by ronbm08** [comment]
**gioman** effectively that was the problem install php-pgsql and everything worked perfect
