### ISSUE TITLE
Google Address Search

### ISSUE THREAD

**Issue by shapley** [3liz/lizmap-web-client#698]
Hi,

Google address search yields results works when i use it on an internal wifi but not on a secured network. What could be preventing results from displaying on secured web page.

**Comment by josemvm** [comment]
hi @shapley 

what do you mean by 

> a secured network

?
google address search works fine in both http and https protocols

tested here in the master version

**Comment by shapley** [comment]
From what i am reading...this is a known bug Google are working on.
