### ISSUE TITLE
Add a fonction in lizmap-web-client: export layer table in .csv 

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#70]
Hi, 
Is it possible to export in .csv the table of a layer?

This feature would be nice to allow users to view and use for the treatment of a layer attribute table.

**Comment by Glasnost46** [comment]
Very useful.
Is there a way to use this plugin with qgis_server on OS windows server 2012 (OSgeo install ?
Any docs to install it ? Thanks.
