### ISSUE TITLE
search address tool - clear button

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#700]
the search address tool needs a clear button...

if the search tool is not configured ![untitled-1](https://user-images.githubusercontent.com/10053874/32374615-6a94823e-c096-11e7-9ebf-1f9889e42fe9.jpg) the user has no way to clear the highlighted geometry

**Comment by gioman** [comment]
See also https://github.com/3liz/lizmap-web-client/issues/751

**Comment by josemvm** [comment]
thanks
