### ISSUE TITLE
Force IE Edge compatibility

### ISSUE THREAD

**Issue by mbernasocchi** [3liz/lizmap-web-client#702]
Hi, guys, I deployed a lizmap site on a corporate network and spent some hours trying to figure out why the site was broken (the popup wasn't opening anymore) I was seeing 

```<LI class="popupcontent nav-dock"><A id=button-popupcontent href="http://qgis/websig/lizmap/www/index.php/view/map/?repository=main&amp;project=visu#popupcontent" rel=tooltip jQuery112408049461254235297="274" data-container="#content" data-placement="right" data-original-title="Popup"><SPAN class=icon style="BACKGROUND-IMAGE: none"><I class="icon-comment icon-white" style="MARGIN: 4px"></I></SPAN></A></LI>
<li class="popupcontent nav-dock active">   <a id="button-popupcontent" rel="tooltip" data-original-title="Popup" data-placement="right" href="#popupcontent" data-container="#content">       <span class="icon" style="background-image: none;"><i class="icon-comment icon-white" style="margin: 4px;"></i></span>   </a></li>

```
please note the href attribute.

it turns out that IE defaults to compatibility mode 7 if the site is on an intranet [[0](https://blogs.msdn.microsoft.com/ie/2008/08/27/introducing-compatibility-view/)] [[1](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/fix-compat-issues-with-doc-modes-and-enterprise-mode-site-list)]

ideally we could add ```<meta http-equiv="X-UA-Compatible" content="IE=edge" />``` in the head section of the map. I just couldn't find where

**Comment by rldhont** [comment]
@mbernasocchi Can you add 
```php
    $this->addHeadContent('<meta http-equiv="X-UA-Compatible" content="IE=edge" />');
```
in `lizmap/responses/myHtmlMapResponse.class.php` afetr line 44.

**Comment by rldhont** [comment]
@mbernasocchi have you tested my proposition ?

**Comment by rldhont** [comment]
@mbernasocchi has you test and fix this issue ?
