### ISSUE TITLE
Tooltip doesn't let choose the layer and data load forever for one layer

### ISSUE THREAD

**Issue by Yolecomte** [3liz/lizmap-web-client#706]
Using LWC 3.1.0, I try to use a Tooltip on a PostgreSQL view.

I have two layer which come from a postgres view. This two layers shows different data based on filter set in the QGIS project on this view. 
The Tooltip works well for one layer called 'parcelle Vente' which get 3500 features.
But for the other layer based on the same view (called Actes administratif (6900 features)), the tooltip load forever and never let the user get the informations.

The GeoJSon send back is OK and come with a 200 status with the request send by the tooltip for both layer. 

The same issue occurs when I try to get the data attribute table for this two layers.
The attribute table show well for 'parcelle Vente' but never show up for 'Actes administratif'.

A second point is that when I click on the tool, it starts to load the first layer before I can choose for which layer I want to use the tooltip... While the layer is loading, I can't change to another layer. As the loading time may be long, it's uncomfortable that I can't choose the layer I want to use before starting loading anything.

Anything else in the project works very well and I'd like to thank's the lizmap team developpement for this great tool!

**Comment by josemvm** [comment]
👍

**Comment by josemvm** [comment]
![tooltip](https://user-images.githubusercontent.com/10053874/32604640-367719f8-c546-11e7-8a60-06eddfda2695.jpg)

i have tried to replace this code
`<option value="">---</option>`
by the following code
`<option disabled selected value> -- select an option -- </option>`

inside

>  lizmap-web-client/lizmap/modules/view/templates/map_tooltip.tpl

but it doesn't work...

**Comment by Yolecomte** [comment]
Ok thank's for the feedback!
So I hope It will come in a next release ;)

**Comment by josemvm** [comment]
as workaround, you can add

`<option style="display:none">`
after
`<option value="">---</option>`

**Comment by Yolecomte** [comment]
Ok, that works well to avoid a default layer to be load when initializing the tool.
Thk's a lot for that. 

But I still have no idea about why the tool never finish to load when using my 'Actes administratifs' layer.

**Comment by rldhont** [comment]
@Yolecomte have you tested with last versions ?

**Comment by Yolecomte** [comment]
@rldhont Thk's for your feedback.
Answer is no... The company which I worked for when I face this problem isn't ready to upgrade for now. But I will make a try with a fresh installation on my own computer with the problematics datas. 
I give some feedbacks as soon as possible!

**Comment by rldhont** [comment]
Related to #1123

**Comment by nboisteault** [comment]
@rldhont A quick fix to avoid first layer to be loaded automatically is to remove https://github.com/3liz/lizmap-web-client/blob/master/lizmap/www/js/map.js#L4962 to line 4967. There might be another bug related to view but we have to deal with it apart. OK for a PR ?

**Comment by rldhont** [comment]
@nboisteault To fix it, I think, you have to automatically load layer if there is only one layer, and do not load it automatically if there is more than one layer.
