### ISSUE TITLE
Ajouter un systeme de mise en surbrillance des entitées selectionnées 

### ISSUE THREAD

**Issue by nepileptik** [3liz/lizmap-web-client#707]
Bonjour; 

Dans mon projet j'ai un mis en place des popups sur plusieurs linéaire différents, j'aimerais savoir si il existe un moyen de mettre en surbrillance le linéaire correspondant au popup affiché.

merci pour vos réponses

Rémi

**Comment by josemvm** [comment]
https://github.com/3liz/lizmap-web-client/issues/684
