### ISSUE TITLE
Problem using WMS Géofoncier layer in Lizmap 3.1.0

### ISSUE THREAD

**Issue by Yolecomte** [3liz/lizmap-web-client#708]
Using LWC 3.1.0, I'm trying to add a WMS layer to a project

url: _http://api.geofoncier.fr/referentielsoge/ogc/wms?_

When I load it in my QGIS project, it works perfectly and I can configure this layer with Lizmap plugin but when I load the corresponding Lizmap project, this layer does not show up (nothing in the layers, nothing in the map, actually nothing anywhere, it's like this layer isn't in the project).

**Comment by Cww7** [comment]
Hi,
I have the same problem with the layers from GeoBretagne, if I add a WMS layer from [http://geobretagne.fr/geoserver/megalis/ows? ](url), I can see it in my Qgis project but not in LWC. And this is true for all the layers from GeoBretagne and Geofoncier.
But it works for WMS layers from another server ([http://carto.geopal.org/cgi-bin/mapserv?](url) for example).

**Comment by nboisteault** [comment]
@Yolecomte @Cww7 
Does issue still occur ?

**Comment by Yolecomte** [comment]
Haven't try it for a while...  And for the moment I don't have any lwc instance to test... sorry... If it works for you, don't hesitate to close this issue !

**Comment by nboisteault** [comment]
If you request a HTTPS WMS server, [see this](https://docs.qgis.org/2.18/fr/docs/user_manual/working_with_ogc/server/getting_started.html#cascading-ogc-layers).
