### ISSUE TITLE
Popup tables reliées

### ISSUE THREAD

**Issue by chanteclair12** [3liz/lizmap-web-client#709]
Bonjour,
Est-il possible d'afficher dans la popup d'une couche, les valeurs de champs de tables reliées à la table principale interrogée ? J'ai essayé sans succès {$nom_de_ma_table.nom_de_mon_champ}

Hi,
Is it possible to display in the popup, the fields values of related tables linked to the main table ? I have tried this but no success {$name_of_my_table.name_of_my_field}.
Thx.

**Comment by josemvm** [comment]
hi @chanteclair12 

> Is it possible to display in the popup, the fields values of related tables linked to the main table ? 

yes

> I have tried this but no success {$name_of_my_table.name_of_my_field}.

it seems to me that you are talking about "Lizmap popup"
https://docs.3liz.com/en/publish/advanced_lizmap_config.html?highlight=popups#lizmap-popup

first of all, you can try to use "auto popup"
https://docs.3liz.com/en/publish/advanced_lizmap_config.html?highlight=popups#one-to-many-relations

**Comment by chanteclair12** [comment]
Hi,
Yes "auto popup" works well but i would like to use "Lizmap Popup".

I have a polygon layer (called EPCI) and several simples tables linked (ARRETES, TIERS, ELUS...). So to make my own popup i would like to create a tab for each linked table. 

But i don't manage to declare the fields of those tables.

For example, {$ELUS.name} is not display in the popup of the main table EPCI (but in auto it is).

**Comment by josemvm** [comment]
i'm not sure, but i think you just need to add a relation in QGIS project properties and configure the fields for each table (main and related tables) in lizmap plugin.

like `{$name_of_my_field}`
not `{$name_of_my_table.name_of_my_field}`

> If you have configured an alias for a field, you have to use the alias instead of the name, between the brackets.

i have not yet tried...

**Comment by chanteclair12** [comment]
I have tried to put only the name of the field of a linked table but it doesn't work.

**Comment by josemvm** [comment]
does the alias name is the issue?

**Comment by chanteclair12** [comment]
For my test, i have not put Alias on the fields of the tables, they have their database name.

**Comment by josemvm** [comment]
@rldhont and @mdouchin what do you think about this issue?

**Comment by aeduard** [comment]
Hi! Do you have an update on this issue? I'm trying to use tabs as in #575. Tried both QGIS tooltips and lizmap html, but I don't know how to reference a child field. With _auto_ mode, the child table appears in lizmap without any problem.

**Comment by nboisteault** [comment]
Lizmap popups are more limited than QGIS ones, they should be used for simple popups.
This comment might be a solution if you it is ok for you to have children popups as tabs : https://github.com/3liz/lizmap-web-client/issues/1772#issuecomment-878240874

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
