### ISSUE TITLE
Adding your own JavaScript

### ISSUE THREAD

**Issue by valeriodeluca** [3liz/lizmap-web-client#712]
Hi guys,

I have lizmap 3.1.5.

I've seen that now it's possible add custom buttons as you show in this slide:

http://mdouchin.github.io/lizmap-presentation/#/46

I'm interested in this because I had already done something like this on my work with leafletjs:

http://www.mainjoin.eu/map/lamone/

that is to add more content than the map.

For example 3D how do you show with threejs or video or virtual tour etc.
Or charts like here:

http://mdouchin.github.io/lizmap-presentation/#/47

I saw the reference in file map.js:

lizmap-web-client/lizmap/www/js/map.js
Line 5202 in 95c8b09
 // Create new dock or minidock 
at line 5202:

// Create new dock or minidock
// Example: lizMap.addDock ('mydock', 'my dock title', 'dock', 'some content', 'icon-pencil');

I was wondering where to insert the code in the slide:

http://mdouchin.github.io/lizmap-presentation/#/46

if it is placed in file map.js or in the bottom-dock.js file:

https://github.com/3liz/lizmap-web-client/blob/55ea21f2b435ef748526317b6422243f57df17fb/lizmap/www/js/bottom-dock.js

or in another file :).

I wanted to understand if all the repositories will have the same set of extra buttons or if I can add different extra buttons to different repositories.

Thank you
Ciao
Valerio

@josemvm says:
hi @valeriodeluca

https://docs.3liz.com/en/publish/advanced_lizmap_config.html#adding-your-own-javascript
you can see above same information about "Adding your own JavaScript"
i hope it will help you, otherwise you can open an issue

valeriodeluca says:
Hi José,

thanks for the link to the documentation:

Adding your own JavaScript
https://docs.3liz.com/en/publish/advanced_lizmap_config.html#adding-your-own-javascript

I tried the sample code, disableRightClick.js, on a single reporitory and it works.

Then I tried the slide code:

http://mdouchin.github.io/lizmap-presentation/#/46
The code tailored to my project, I changed only:

the name of the "observatoire" folder I renamed with my repository name "Trento_Catasto"
the name of the html file of threejs with "index.html"
and in the same folder "Trento_Catasto" I put the custom js code. I called it "add3d.js":
lizMap.events.on({
uicreated: function(e) {
var mediaLink = OpenLayers.Util.urlAppend(
lizUrls.media,
OpenLayers.Util.getParameterString(lizUrls.params)
);
var frameSrc = mediaLink +'&path=/media/js/Trento_Catasto/index.html';
lizMap.addDock(
'threejs',
'Vue 3D',
'right-dock',
'<iframe src="' + frameSrc + '" height="800px" width="100%">',
'icon-globe'
);
}
});

Everything works:

adding the button
the dock opening
the dock closure
This is my link lizmap:
http://37.139.2.71/lm/index.php/view/map/?repository=trentocat&project=Trento_Catasto

I can not see the content that is a file threejs that I carry here with the various folders and files:

https://drive.google.com/drive/folders/1TeISCfr8yq__K9fBFjMG9QLb8RLQ_n2k?usp=sharing

Maybe I'm wrong in the path?
Tks a lot :)
Ciao
Valerio

**Comment by valeriodeluca** [comment]
@josemvm says:

hi @valeriodeluca

https://docs.3liz.com/en/publish/advanced_lizmap_config.html#adding-your-own-javascript
you can see above same information about "Adding your own JavaScript"
i hope it will help you, otherwise you can open an issue

**Comment by valeriodeluca** [comment]
Hi José,

thanks for the link to the documentation:

Adding your own JavaScript
https://docs.3liz.com/en/publish/advanced_lizmap_config.html#adding-your-own-javascript

I tried the sample code, disableRightClick.js, on a single reporitory and it works.

Then I tried the slide code:

http://mdouchin.github.io/lizmap-presentation/#/46
The code tailored to my project, I changed only:

the name of the "observatoire" folder I renamed with my repository name "Trento_Catasto"
the name of the html file of threejs with "index.html"
and in the same folder "Trento_Catasto" I put the custom js code. I called it "add3d.js":
lizMap.events.on({
uicreated: function(e) {
var mediaLink = OpenLayers.Util.urlAppend(
lizUrls.media,
OpenLayers.Util.getParameterString(lizUrls.params)
);
var frameSrc = mediaLink +'&path=/media/js/Trento_Catasto/index.html';
lizMap.addDock(
'threejs',
'Vue 3D',
'right-dock',
'<iframe src="' + frameSrc + '" height="800px" width="100%">',
'icon-globe'
);
}
});

Everything works:

adding the button
the dock opening
the dock closure
This is my link lizmap:
http://37.139.2.71/lm/index.php/view/map/?repository=trentocat&project=Trento_Catasto

I can not see the content that is a file threejs that I carry here with the various folders and files:

https://drive.google.com/drive/folders/1TeISCfr8yq__K9fBFjMG9QLb8RLQ_n2k?usp=sharing

Maybe I'm wrong in the path?
Tks a lot :)
Ciao
Valerio

**Comment by josemvm** [comment]
`i think that you need to get a srtm data (SCR 3857) to load it in your qgis project`
see here https://vimeo.com/83511028

does the scr code is the issue?

your `"DEM_Riserva"` is set to `crs:"EPSG:32632"`

**Comment by valeriodeluca** [comment]
Hi guys,

when I try "simple" content like:
- pdf or
- video
no problem. I put my pdf/video(mp4) content in my repository media folder:
-  media/pdf/sample.pdf
-  media/video/sample.mp4

and in repository js folder I add:
- media/js/repository/addpdf.js
- media/js/repository/addvideo.js

that are:
media/js/repository/addpdf.js:
lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/pdf/sample.pdf';
        lizMap.addDock(
            'pdf',
            'PDF',
            'right-dock',
            '<iframe src="' + frameSrc + '" height="800px" width="100%">',
            'icon-file'
        );
    }
});

and

media/js/repository/addvideo.js
lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/video/sample.mp4';
        lizMap.addDock(
            'video',
            'VIDEO',
            'right-dock',
            '<iframe src="' + frameSrc + '" height="800px" width="100%">',
            'icon-facetime-video'
        );
    }
});

This my rusults:
http://37.139.2.71/lm/index.php/view/map/?repository=trentocat&project=Trento_Catasto

I've a little problem.. video starts automatically :).

What's better solution to add more extra buttons? Add one custom js for each button:
- media/js/repository/addpdf.js
- media/js/repository/addvideo.js
or add only one custom js for all extra buttons:
- media/js/repository/addextrabuttons.js:
lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/pdf/sample.pdf';
        lizMap.addDock(
            'pdf',
            'PDF',
            'right-dock',
            '<iframe src="' + frameSrc + '" height="800px" width="100%">',
            'icon-file'
        );
    }
});
lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/video/sample.mp4';
        lizMap.addDock(
            'video',
            'VIDEO',
            'right-dock',
            '<iframe src="' + frameSrc + '" height="800px" width="100%">',
            'icon-facetime-video'
        );
    }
});

Then I tried add other contents such as:

- 3D in threejs format like this on my website:
http://www.mainjoin.eu/map/lamone/3d/index.html
The content folder is here:
https://drive.google.com/drive/folders/1KEiNDWr6I08ClVHZGDeWmpGIJ68CE9mL?usp=sharing

- 3D in 3DHOP format like this on my website:
http://www.mainjoin.eu/map/swiss/3d/index.html
The content folder is here:
https://drive.google.com/drive/folders/1Akw07Axn1NbxYFKJgaHNQGr4zGEAKEOF?usp=sharing

- Virtual Tour in Marzipano format like this on my website:
http://www.mainjoin.eu/map/lamone/vt/vt10/index.html
The content folder is here:
https://drive.google.com/drive/folders/1iFzHf0Vk5ktZJpX9URK2Ajd9g2jCcity?usp=sharing

Making these folders in repository media folder:
- media/3dthree
- media/3dhop
- media/vt

In these last contents cases I can't view these in lizmap right dock.
Maybe some js conflicts? Can I organize different content folders  structure to avoid these conflicts?

Tks eb :)
Valerio

**Comment by valeriodeluca** [comment]
tks @josemvm for EPSG suggest, I ll convert my dem in 3857 and then I ll post my results :)

**Comment by josemvm** [comment]
my test without success:

js code inside:

> media/js/project_name/3D.js

...
`var frameSrc = mediaLink +'&path=/media/js/project_name/generated_contents_by_Qgis2ThreeJS_plugin/threejs.html`
...

browser console output:
![imagem](https://user-images.githubusercontent.com/10053874/32993080-2945580a-cd4b-11e7-8cc3-92d550647144.png)

LWC error.log:

> error [102]   Action media:Qgis2threejs.css: method Qgis2threejs.css of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html) /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102]   Action media:Qgis2threejs.js: method Qgis2threejs.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102]   Action media:threejs: method threejs of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102]   Action media:threejs: method threejs of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102]   Action media:dat-gui: method dat-gui of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102]   Action media:3Dteste.js: method 3Dteste.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)     /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102] Action media:dat-gui_panel.js: method dat-gui_panel.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html) /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102] Action media:Qgis2threejs.js: method Qgis2threejs.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102] Action media:threejs: method threejs of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102] Action media:3Dteste.js: method 3Dteste.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)     /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error [102] Action media:dat-gui: method dat-gui of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html)   /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271

> error  [102] Action media:dat-gui_panel.js: method dat-gui_panel.js of the controller class mediaCtrl doesn't exists (file: /var/www/html/lizmap-web-client-master/lizmap/modules/view/controllers/media.classic.php REFERER:http://myhost/index.php/view/media/getMedia?repository=ma&project=teste_3D&path=/media/js/teste_3D/3D_teste/threejs.html) /var/www/html/lizmap-web-client-master/lib/jelix/core/jCoordinator.class.php 271


in fact it seems just a simple media path problem... but i tried several path alternatives without success

e.g.
`var frameSrc = mediaLink +'&path=../../../media/js/teste_3D/3Dteste/threejs.html`

![imagem](https://user-images.githubusercontent.com/10053874/32993421-a573ff40-cd4f-11e7-98cc-06e2051890d6.png)

`{"error":"404 not found (wrong action)","message":"No media file in the specified path: ..\/..\/..\/media\/js\/teste_3D\/3Dteste\/threejs.html"}`

@mdouchin could you help us please?
thanks

**Comment by valeriodeluca** [comment]
ABOUT DOCK WIDTH
In previous tests I used "right-dock" option.
What dock type can I use to have full width dock?
Like in this slide:
http://mdouchin.github.io/lizmap-presentation/#/47
Tks guys

**Comment by josemvm** [comment]
hi @valeriodeluca 
how did you solve your threejs issue?

**Comment by valeriodeluca** [comment]
hi @josemvm 
I solved with no very good solution (only fast) with iframe:

repository/media/js/repository_name/add3dthreeiframe.js:

lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/3dhop/index.html';
        lizMap.addDock(
            '3D',
            '3D',
            'right-dock',
            '<iframe width="100%" height="500" src="http://www.mainjoin.eu/map/lamone/3d/index.html" frameborder="0" allowfullscreen></iframe>',
            'icon-globe'
        );
    }
});

No problem if the repository is public. No good way if the repository in private.

The same solution with virtual tour:

repository/media/js/repository_name/addvtiframe.js:

lizMap.events.on({
    uicreated: function(e) {
        var mediaLink = OpenLayers.Util.urlAppend(
            lizUrls.media,
            OpenLayers.Util.getParameterString(lizUrls.params)
        );
        var frameSrc = mediaLink +'&path=/media/3dhop/index.html';
        lizMap.addDock(
            'vt',
            'VIRTUAL TOUR',
            'right-dock',
            '<iframe width="100%" height="500" src="http://www.mainjoin.eu/map/lamone/vt/vt10/index.html" frameborder="0" allowfullscreen></iframe>',
            'icon-repeat'
        );
    }
});

Have u any idea abaut this?
ABOUT DOCK WIDTH
In previous tests I used "right-dock" option.
What dock type can I use to have full width dock?
Like in this slide:
http://mdouchin.github.io/lizmap-presentation/#/47

Tks @josemvm 
Ciao :)

**Comment by josemvm** [comment]
thanks @valeriodeluca 
i will try your solution

> ABOUT DOCK WIDTH
> What dock type can I use to have full width dock?

i have no idea about it

**Comment by valeriodeluca** [comment]
ok @josemvm post your results :)

**Comment by valeriodeluca** [comment]
hi @jlstanus hi @Abelon38
have u any ideas about this issue?
"Adding your own JavaScript"
Tks guys

**Comment by rldhont** [comment]
The right dock activate/deactivate function has been fixed 8850da3a7e77af5a259cf34fffbdf4e45d9b090a

**Comment by valeriodeluca** [comment]
Tks @rldhont , right dock activate/deactivate function works fine! My results:
http://37.139.2.71/lm/index.php/view/map/?repository=trentocat&project=Trento_Catasto
