### ISSUE TITLE
overview - coordinate unit (default unit)

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#714]
hi

how can i set by default the coordinate unit to degrees value?
i tried with
`<option selected value="d">{@view~map.mouseposition.units.d@}</option>`
in 
>  lizmap-web-client/lizmap/modules/view/templates/map.tpl

but it doesn't work...

thanks

**Comment by rldhont** [comment]
with this JS code:
```js
$('#mouseposition-bar select').val('m');
```
But you probably want an option in the lizmap-plugin dto do so ?

**Comment by josemvm** [comment]
hi @rldhont 

i tried with this js code:

`var mpUnitSelect = $('#mouseposition-bar > select').val('d');`

it set the coordinate unit to degrees but when i move the mouse over the map i can't get the coordinates value...

> But you probably want an option in the lizmap-plugin dto do so ?

yes, i think it's good idea to have an option in the lizmap plugin to do it!

thanks

**Comment by josemvm** [comment]
@rldhont, for now, is it possible to create a js `lizMap.events.on({` to load at startup project?

**Comment by rldhont** [comment]
Yes you can do:
```
lizMap.events.on({
    'uicreated': function() {
        var mpUnitSelect = $('#mouseposition-bar > select').val('d');
    }
});

**Comment by josemvm** [comment]
@rldhont 

that's not enough, anything is missing yet...

the js script set the unit to degrees ![imagem](https://user-images.githubusercontent.com/10053874/33657449-5306e7f2-da71-11e7-8634-9b95ba2c242b.png) but the coordinate reading remains in meter values

**Comment by josemvm** [comment]
hi @rldhont 
could you help me here, please?

**Comment by josemvm** [comment]
@rldhont can you take a look?

**Comment by josemvm** [comment]
hi @rldhont 

i'm sorry for the noise... but please can you take a look at this script?

thanks

**Comment by RobiFag** [comment]
We got the same problem using the suggested script. The selected unit is degree but the coordinates are still in meters. Changing the unit to meters, using the drop-down menu, and then setting the unit to degree again, it works fine.

**Comment by RobiFag** [comment]
Maybe the problem is due to the lizmapMousePosition.js file where the units are set to meters (displayUnit: 'm',)?

**Comment by josemvm** [comment]
@RobiFag try it

```
lizMap.events.on({
    'uicreated': function() {
        var mpUnitSelect = $('#mouseposition-bar > select').val('d');
    }
});
lizMap.events.on({
    'uicreated': function() {
        var mpUnitSelect = $('#mouseposition-bar > select').val('m');
    }
});
lizMap.events.on({
    'uicreated': function() {
        var mpUnitSelect = $('#mouseposition-bar > select').val('d');
    }
});

**Comment by RobiFag** [comment]
Hi @josemvm thank you for the suggestion but unfortunately, it doesn't work. The selected unit is degree but the coordinates are shown in meters.

**Comment by rmarzocchi84** [comment]
I think the problem is that with this javascript code we correctly change the select option form (we read degree in the select input form) but without the associated _event_

**Comment by josemvm** [comment]
in effect, it doesn't work :-(

**Comment by RobiFag** [comment]
We have modified the script in this way:
```
lizMap.events.on({
    'mapcreated': function(e) {
        var mpUnitSelect = $('#mouseposition-bar > select').val('d');
    }
});
```
Now the coordinates are shown in degrees but without decimal number. Do we have to update the numdigits variable?

**Comment by rmarzocchi84** [comment]
using **mapcreated** instead of **uicreated** effectively has effect also on coordinates. But the problem on numDigits remains. I think you are close to solution but I  have no suggestion. Perhaps @rldhont or @nboisteault which are more expert on javascript codes

**Comment by rmarzocchi84** [comment]
I try with 

```
lizMap.events.on({
    'mapcreated': function(e) {
        var mpUnitSelect = $('#mouseposition-bar > select').val('d');
        var mousePosition = new OpenLayers.Control.lizmapMousePosition({
        displayUnit:mpUnitSelect.val(),
        numDigits: 5,
        prefix: '',
        emptyString:$('#mouseposition').attr('title'),
        div:document.getElementById('mouseposition')
        });
        //map.addControl( mousePosition );
        mpUnitSelect.change(function() {
        var mpSelectVal = $(this).val();
        if (mpSelectVal == 'm')
          mousePosition.numDigits = 0;
        else
          mousePosition.numDigits = 5;
        mousePosition.displayUnit = mpSelectVal;
    });
    }
});
```

but it doesn't work.  

It only works changing the map.js file (`numDigits: 5,`), but it affects also metric coordinates

**Comment by nboisteault** [comment]
`$('#mouseposition-bar > select').val('d').change();
`

**Comment by RobiFag** [comment]
Thank you @nboisteault it works!!
Just another question about mouse position, is it possible to change the coordinate reference system?

**Comment by josemvm** [comment]
thanks @nboisteault ! ;-)

**Comment by nboisteault** [comment]
@RobiFag You'll have to change displayProjection as documented here http://dev.openlayers.org/docs/files/OpenLayers/Control/MousePosition-js.html#OpenLayers.Control.MousePosition.displayProjection

@rldhont this parameter is not present in lizmapmouseposition, what is the reason ?

**Comment by rmarzocchi84** [comment]
@nboisteault 

there are some line commented 

https://github.com/3liz/lizmap-web-client/blob/bedef9b9d8ca8634bc658c34279bfebf879f8ca7/lizmap/www/OpenLayers-2.13/lib/OpenLayers/Control/lizmapMousePosition.js#L187

If I correctly understand the commented section give problem with geographical projection system where meters coordinates are not available
