### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by remichairat** [3liz/lizmap-web-client#717]
Bonjour,

Dans le cadre du projet sur lequel je travaille, il serait intéressant de pouvoir recevoir une notification mail lorsque l'outil édition est utilisé.
Travaillant dans une société il faudrait que ces notifications puisse être attribué a différent utilisateur en fonction du projet.

est ce que cela est possible ? 

merci pour vos réponses.

**Comment by josemvm** [comment]
hi @nepileptik 

for a while, it's possible to send an email to lizmap administrator as you can see here https://github.com/3liz/lizmap-web-client/commit/636e4baa113099b3e7c22be888d844e796683efc

however, according to my tests, lizmap notifications only for:

    A feature has been created or modified by a user
    A feature has been deleted by a user

**Comment by laurentj** [comment]
duplicate of #738
