### ISSUE TITLE
Lizmap on windows 10 tablet with location API

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#719]
Hello
We have recently bought some windows 10 tablet, Dell latitude 5175 with Dell Wireless 5811e module (broadband and GPS module).
After the installation of the correct drivers for this peripheral we can not use the location function in edge/firefox/explorer.
It seems that Microsoft from win8 onward changed the way gps information is managed by system and apps. There is no COM port available and some windows Api are used by (really few) applications. Browsers seem not to be among these.. 
Somebody did face this problem and have some solution? 
Thanks
Pietro

**Comment by rldhont** [comment]
@jancelin can probably help you ?
