### ISSUE TITLE
Small Fix for the Lizmap installation documentation

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#72]
Hi,

I think that here

http://docs.3liz.com/en/lizmap-web-client/installation/linux.html

the line

<i>apt-get install apache2 php5 curl php5-curl php5-sqlite php5-gd</i>

should include the package

php5-pgsql

otherwise editing of PostGIS layers will not work.

On another note I have never seen Spatialite layers show (in Lizmap) as possible layers for edition, on both Linux and Windows. Am I missing something?

**Comment by rldhont** [comment]
Hi @gioman, can you update the documentation https://github.com/3liz/lizmap-documentation and close this issue ?

**Comment by gioman** [comment]
@rldhont will do.

**Comment by rldhont** [comment]
@gioman thanks for your help

**Comment by gioman** [comment]
https://github.com/3liz/lizmap-documentation/pull/40
