### ISSUE TITLE
Printing error

### ISSUE THREAD

**Issue by ludovico85** [3liz/lizmap-web-client#722]
Hi,
I have a lizmap project running on Ubuntu (xenial) server and with Qgis server 2.18. When I try to print the map I get the following error:

Error 500. A technical error has occurred. Sorry for this trouble.

The error occurs regardless the printing format (PDF, SVG, JPEG). The error also occurs with a simple map without text, labels, legend, etc.

I followed these instruction
http://www.itopen.it/qgis-server-setup-notes/
but without success.

Thank you in advance 

The error log

php-apache2handler-165.227.79.18[10946]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":92.514991760254,"CACHE_STATUS":"off"}
php-apache2handler-165.227.79.18[10953]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":64.393997192383,"CACHE_STATUS":"off"}
php-apache2handler-165.227.79.18[10953]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":83.313941955566,"CACHE_STATUS":"off"}
php-apache2handler-165.227.79.18[10947]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":64.368963241577,"CACHE_STATUS":"off"}
php-apache2handler-165.227.79.18[10947]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":89.71095085144,"CACHE_STATUS":"off"}
php-apache2handler-165.227.79.18[10947]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":87.871074676514,"CACHE_STATUS":"off"}

**Comment by josemvm** [comment]
hi @ludovico85 

have you checked this option in lizmap configuration/admin?

![imagem](https://user-images.githubusercontent.com/10053874/33561803-8fdf2386-d90b-11e7-9e8d-fa492deccd66.png)

**Comment by ludovico85** [comment]
Yes, I have checked it.

**Comment by nboisteault** [comment]
@ludovico85 Please reopen if issue still occurs.
