### ISSUE TITLE
Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated	

### ISSUE THREAD

**Issue by kevincote** [3liz/lizmap-web-client#724]
Following the resolve of my issue: https://github.com/3liz/lizmap-web-client/issues/723, I'm getting an Error 500 when connecting to the portal. In the log, I get this:

```
2017-12-06 17:44:19	192.168.99.1	notice	2017-12-06 17:44:19	192.168.99.1	[1024]	Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated	/var/www/websig/lib/jelix/core/jConfigCompiler.class.php	423
	/websig/lizmap/www/
array ( )

	0	trigger_error()	/var/www/websig/lib/jelix/core/jConfigCompiler.class.php : 423
	1	jConfigCompiler::_loadPluginsPathList()	/var/www/websig/lib/jelix/core/jConfigCompiler.class.php : 133
	2	jConfigCompiler::prepareConfig()	/var/www/websig/lib/jelix/core/jConfigCompiler.class.php : 81
	3	jConfigCompiler::read()	/var/www/websig/lib/jelix/core/jConfigCompiler.class.php : 99
	4	jConfigCompiler::readAndCache()	/var/www/websig/lib/jelix/core/jConfig.class.php : 86
	5	jConfig::load()	/var/www/websig/lib/jelix/core/jApp.class.php : 145
	6	jApp::loadConfig()	/var/www/websig/lizmap/www/index.php : 17
2017-12-06 17:44:19	192.168.99.1	error	2017-12-06 17:44:19	[18]	Unknown module in the selector "view~default:index@classic"	/var/www/websig/lib/jelix/core/selector/jSelectorActFast.class.php	56
```

Any idea what could cause this ?

**Comment by rldhont** [comment]
This mean, the modules are not installed.

**Comment by kevincote** [comment]
It's strange because it looks like they have been installed correctly during the image build.

![image](https://user-images.githubusercontent.com/31894882/33674223-dfe6addc-da7c-11e7-835c-fc2a3c4e822c.png)

**Comment by laurentj** [comment]
@kevincote i don't think you should launch the installer during the build of the docker image. You should launch the installer during the execution of the image, since the installer needs to access to a database etc. It makes more sens IMHO.

**Comment by laurentj** [comment]
I don't understand why you have this error. Did you change something in lizmap/var/config or in lib/?

**Comment by kevincote** [comment]
@laurentj solved this error by doing a clean deployment. Not sure where it came from, but it's fixed on my side.

**Comment by laurentj** [comment]
ok
