### ISSUE TITLE
[Question][js] Lizmap variable and functions available for custom.js

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#725]
Hello,

I read about the [Lizmap doc](https://docs.3liz.com/fr/publish/advanced_lizmap_config.html#adding-your-own-javascript) about adding your own js.

What i missing is the variable and function i can use. By example : 
* lizmap_user_login
* jforms_view_edition

Where are the others?

In my case, i would like to automatically open the popup in mini-dock to show attributes after use of _find by location_ on a feature.
Or inserting 2 buttons  _next_ or _forward_ to get the following feature in the dock.

Could you show me the way. Thank you.

**Comment by josemvm** [comment]
related to https://github.com/3liz/lizmap-web-client/issues/712

**Comment by jlstanus** [comment]
Thank you for there reffering link.

However, this is not covering my needs:
* Open _mini-dock_ and load attributes of a selected object
* Acces to attribute list

I can create the documentation if know where to look at the code and how it's works.

Thank you.

**Comment by rmarzocchi84** [comment]
It is possible to limit custom javascript button only to certain groups?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
