### ISSUE TITLE
layers with datasource starting with HTTPS 

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#736]
hi

LWC doesn't allow OWS layers from https protocol

https://sniambgeoogc.apambiente.pt/getogc/services/Atlas/Atlas_Ambiente/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=Atlas_Ambiente:_0a._Sismicidade__Intensidade_Sismica_&SRSNAME=urn:ogc:def:crs:EPSG::3763&format_options=CHARSET:UTF-8

i saw this commit https://github.com/3liz/lizmap-plugin/commit/93bc24dd52e1548a80e25144a1d0f4724aa61495 and i tried to adapt it for https but it doesn't work

**Comment by gioman** [comment]
@josemvm @rldhont at some point QGIS server lost the ability to cascade WMS layers from services using https. See https://issues.qgis.org/issues/16462

**Comment by rldhont** [comment]
QGIS Server needs to be fixed!

**Comment by nboisteault** [comment]
@josemvm @rldhont Does issue still occur ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
