### ISSUE TITLE
Atlas menu is not opening

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#737]
![qtlqs](https://user-images.githubusercontent.com/402354/34492694-b6e7b0ce-efe0-11e7-8fda-6f08ec22fc2c.png)

I tested with WFS string key and pg with int key

**Comment by mdouchin** [comment]
Do you have any Javascript error in the browser console ? Is there any atlas icon in the left vertical menu bar ?

**Comment by jlstanus** [comment]
Yes, the layer looks like WFS is not enabled but it is in OWS configuration.

So i can understand that the module atlas.js is not launched as seen the code of atlas.js check if layer, pri;ary key is available...

![capture d ecran_2018-01-03_11-09-26](https://user-images.githubusercontent.com/402354/34518435-4e4d3f10-f077-11e7-977a-fc075aa201c1.png)

**Comment by mdouchin** [comment]
Could you pass me an url (privately if needed) to check the configuration in situ ? ( email kimaidou on gmail )

**Comment by josemvm** [comment]
a small note: the atlas icon appears with some delay in the left vertical menu bar...

**Comment by jlstanus** [comment]
As i explained to @mdouchin in pm, the problem is WFS not enabled with last master. So no atlas because atlas.js code checks wfs informations before launching. The only tool working well is the pop up. The same project in 3.1.5 works perfectly with tools based on wfs but no atlas...

**Comment by josemvm** [comment]
@mdouchin 
by default the atlas doesn't show the features of the child tables but if the user has previously used the popup tool the atlas will show them...

maybe an option in the plugin for this purpose would be useful, or set it by default...

**Comment by jlstanus** [comment]
OK, that works now.

I used the 2.18 QGIS server instead of 2.14
