### ISSUE TITLE
wms link and link for popup image - localhost instead of ip of server

### ISSUE THREAD

**Issue by brebe** [3liz/lizmap-web-client#739]
i have a project created in qgis , i have qgis server and lizmap webclient as a client 
in view metadata of the project both links of wms url and wmts url are with localhost instead of ip of server (making it unnaccesible from lan network )
i have a layer with attributes table that contains also photos.
I am trying to attach to a point a photo that can be uploaded via the interface.
The picture is going to the folder i created as in documentation but the link is  like that

http://localhost/lm/index.php/view/media/getMedia?repository=braila&project=test&path=media%2Fupload%2Ftest%2FINTERVENTIE%2Fpoza_interventie%2F31conflict1.jpg

it should be 

http://192.168.88.139/lm/index.php/view/media/getMedia?repository=braila&project=test&path=media%2Fupload%2Ftest%2FINTERVENTIE%2Fpoza_interventie%2F31conflict1.jpg

From where are generating the link with localhost address?
What do i need to change so the link to be generated with the ip of the server instead of localhost?

**Comment by josemvm** [comment]
hi @brebe 

try to change the "WMS server URL" in user/admin, My account, Lizmap configuration

**Comment by brebe** [comment]
i have the wms server url pointing to the ip of server
![lizmap](https://user-images.githubusercontent.com/15627303/34665756-1ac55f8c-f46a-11e7-8584-dedcb4871c65.png)

**Comment by josemvm** [comment]
after changes, try to run `lizmap/install/clean_vartmp.sh` inside your lm folder

**Comment by brebe** [comment]
i did but still same thing

**Comment by josemvm** [comment]
try to clear the browser cache...

is your webserver accessible from your lan network?

**Comment by brebe** [comment]
i did , also used mozilla / chrome alternate
when i access wms url  - is pinpointing to localhost 
if i change manually to ip of server like that  
http://192.168.88.139/lm/index.php/lizmap/service/?repository=brailax&project=test&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

![lizmap 1](https://user-images.githubusercontent.com/15627303/34668205-fb6ab8d4-f474-11e7-966d-d9f8fc7ee996.png)

**Comment by brebe** [comment]
THANK YOU GUYS !! BY REINSTALLING LIZMAP MASTER BRANCH I SOLVED IT !!!! HEHEHE
