### ISSUE TITLE
limited number of relational value,  sort by value does not work

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#74]
lizmap-web-client limit the number of values ​​in relational value. 
416 values ​​visible with lizmap while qgis displays 660 present values ​​of the postgresql table.

and

sort by value does not work

**Comment by rldhont** [comment]
Does the commit d3855eacb09704d841b511ef1fefdf921a51d9a9 fixes it ? like #121 ?

**Comment by jancelin** [comment]
works well, thanks

**Comment by jancelin** [comment]
oups, petit bug:
Les valeurs relationnels deviennent pré-remplis par la première valeur de la liste lors de la création d'une nouvelle entitée.

**Comment by rldhont** [comment]
Fixed with 34cc6ae6dc0419673725eabfb2db371be5f9cc23
