### ISSUE TITLE
lwc edition - illustrations and media files stored folder is not writable

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#741]
hi

before saving files in cache, lwc should check if the target folder is writable

thanks

**Comment by rmarzocchi84** [comment]
Hi @josemvm: a basic question. I do not understand where is saved the cache

From documentation [[link](https://docs.3liz.com/en/install/linux.html#creating-a-user-account)] it is not clear. I need to create a cache folder in each repository folder?

**Comment by josemvm** [comment]
hi @rmarzocchi84 

for the tile cache you can set a common `Cache root directory` for all your repositories, in my account, lizmap configuration, services

lizmap stores temporarily data as you can see here: https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/clean_vartmp.sh

in this issue i'm talking about `uploads` folder

**Comment by rmarzocchi84** [comment]
Ok. But I do not understand how set the `Cache root directory`

**Comment by josemvm** [comment]
Lizmap configuration
Generic
Services
![imagem](https://user-images.githubusercontent.com/10053874/36306898-a075432a-1311-11e8-8036-164b320ea98e.png)

**Comment by rldhont** [comment]
@josemvm Lizmap Checks if the `Cache root directory` exists, is directory and is writable.
If not the system temporary directory is used.

```php
        // Cache root directory
        $cacheRootDirectory = $ser->cacheRootDirectory;
        if( $cacheStorageType != 'redis' ){
            if(!is_dir($cacheRootDirectory) or !is_writable($cacheRootDirectory)){
                $cacheRootDirectory = sys_get_temp_dir();
            }
        }
```

**Comment by josemvm** [comment]
i think there should be some warning if the directory is not writable or it doesn´t exist because when the cache expires or is cleared the information is lost...

**Comment by rldhont** [comment]
@josemvm In the config controller, lizmap verifiying the directory and an error.
```php
    // Check the cacheRootDirectory : must be writable
    $cacheStorageType = $form->getData('cacheStorageType');
    if($cacheStorageType != 'redis') {
        $cacheRootDirectory = $form->getData('cacheRootDirectory');
        if(!is_dir($cacheRootDirectory) or !is_writable($cacheRootDirectory)){
            $ok = false;
            $form->setErrorOn(
                'cacheRootDirectory',
                jLocale::get("admin~admin.form.admin_services.message.cacheRootDirectory.wrong", array(sys_get_temp_dir()))
            );
        }
    }
```
Do you need some texts in the log ?

**Comment by josemvm** [comment]
hi @rldhont 

i think that lizmap should not cache data if the directory doesn't exist or it's not writeable, and in this case it should inform the user with an warning message...

**Comment by rldhont** [comment]
Lizmap can't warn the user for each tiled not cached! It's an information the lizmap admins.

I'd like to have other advice on this point:
* Does lizmap has to cache in the temp directory if the configured directory is not writable ?

@mdouchin @gioman @jonnyforestGIS @pcav what is your opinion ?

**Comment by jonnyforestGIS** [comment]
Hi @rldhont ,

i think the warning's only need to be in the admin side. This is a kind of issue that lizmap admin need to deal not the user.

Why you need to save in the temp folder? When you as admin know where is the folders and you can redirect the cache? I missing something?

Do you have an example to specific the need of this procedure?

Cheers,
João

**Comment by josemvm** [comment]
hi

i'm just talking about lizmap edition and multimedia files caching, so i think this case should be treated as a particular way

**Comment by rldhont** [comment]
It's not the cache directory but the media directory of the layer in which files are stored. I have updated the title

**Comment by pcav** [comment]
Saving in user data `temp` seems risky to me - or am I missing something?

**Comment by rldhont** [comment]
@pcav I have missed understood the issue.
