### ISSUE TITLE
[Question] Dataviz aggregation

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#743]
I read about the aggregation on Dataplotly

https://plot.ly/python/aggregations/

How can i do the same in Lizmap on fresh answered fields?

I could use aggregate functions in 2.18. But, I don't know the structure and constraints of the ouput

**Comment by mdouchin** [comment]
It has been added in current master and in branch release_3_2, which means it will be available in Lizmap 3.2. Please use the last master version of the lizmap plugin to correctly set these new options.

Please not there is a pending PR on the aggregation of pie plots https://github.com/3liz/lizmap-web-client/pull/822
