### ISSUE TITLE
"?" instead of layer names in legend of prints, no more "fixed" legends

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#750]
This is not really a LM issue but rather a QGIS one (Desktop and possibly also Server). Opening a ticket also here because the QGIS ticket I filed isn't getting any traction at all and at the same time I believe this is an issue it is particularly important for who uses LM (and not for example as much who uses QGIS server to publish just OGC services), so I hope for some discussion here. In case this is not appropriate please just close it.

The upstream QGIS ticket is this one

https://issues.qgis.org/issues/16899

and I added further details here:

https://issues.qgis.org/issues/16899#note-5

and I believe the description should be good enough, but I may be wrong, in case I can add further details.

Short version:
Since QGIS 2.18.10 the map composer "none" value for a map legend "map" option is no more available. This turns impossible to "unlink" a map legend from a map object, with the result that is not possible to print (via QGIS Server GetPrint) anymore a legend that is fixed, this means that does not change regardless the list of layers in the GetPrint request (of course in QGIS Desktop print composer the "auto update" and "filter" option for a map legend must be not used).

This is apparently the offending commit:

https://github.com/qgis/QGIS/commit/1b4bd47076103e931e642c9c2b6a363f14b20a45

and this was the one that actually made possible to print (via GetPrint) fixed legends:

https://github.com/qgis/QGIS/commit/7c735213ca54371f10881856ebac767dbcc878c4

**Comment by rldhont** [comment]
@gioman do you think something has been fixed in QGIS ?

**Comment by gioman** [comment]
> do you think something has been fixed in QGIS ?

@rldhont Hi René-Luc, thanks for the answer. This is not solved at all. The whole story is in the original description of this ticket, and as far as I know in QGIS 3 is still valid. Bringing back the "none" value for the "map" option for a legend item seems to me very important, not also because of its clear general utility (otherwise there is mo way to print a *fixed* legend with a QGIS Server GetPrint) but also as because once servers will start update from 2.14 to 2.18 legends will become corrupted for existing projects (when printed using GetPrint).

**Comment by nboisteault** [comment]
@rldhont  @gioman Does issue still occur ?

**Comment by gioman** [comment]
@nboisteault I should check, anyway the "?" problem should be solved. On the other hand I'm not sure that is (again) possible to print fixed legends, but as I said this is not really a LM issue (but if still confirmed has a direct impact on LM indeed).
