### ISSUE TITLE
Allow "unselect" features searched using the Quick Finder plugin

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#751]
Suggestion for a minor improvement:

when searching using the Quick Finder plugin the geometry of the selected results gets highlighted. As far as I can see (maybe I'm missing something obvious) there is not obvious way to remove this highlighting, unless of course searching/selecting another result.

**Comment by josemvm** [comment]
@gioman  is it the same as https://github.com/3liz/lizmap-web-client/issues/700 ?

**Comment by gioman** [comment]
@josemvm correct. Closed as duplicate of https://github.com/3liz/lizmap-web-client/issues/700
