### ISSUE TITLE
"Get Images directly from WMS Server" does not seems to always work

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#753]
Note:
I'm filing this here as this is a LM option, but I'm not really sure is a LM problem, a QGIS Server one or even (possibly?) a problem with the used remote WMS services. I would like to discuss the problem anyway to try pinpoint it.

The advantage of this option (beside speed because the layer does not need to be cascased through QGIS Server) is that we can add remote WMS layers that will show their original (the one defined in the remote service) legend in LM (while when cascading them through QGIS Server the original legend is lost). 

Problem is that frequently when activating the option "Get Images directly from WMS Server" for a remote WMS layer the layer shows in the LM legend but once activated does not show in the map.

Two examples, one working the other not working (I believe both are Geoserver services):

1) this layer

http://snimar.madeira.gov.pt/geoserver/ExtracaoInertes_RAM/wms

if added in a QGIS project and then set to use "Get Images directly from WMS Server" in LM plugin will show correctly in LM map and will show correctly its original legend

2) any layer from

http://mapas.hidrografico.pt/geoserver/psoemm/ows

will only show in LM map if not using "Get Images directly from WMS Server". If using this option the original legend will show on LM legend but the layer will not show in LM map.

**Comment by josemvm** [comment]
@gioman tested on QGIS Server 2.14.21, works well

**Comment by gioman** [comment]
@josemvm apparently I finally found the pattern/key of the problem: the option "Get Images directly from WMS Server" works as expected only when the CRS of the added external WMS layer matches the one of the QGIS project. When it does not match then the external WMS layer does not show in the LM map, while its original legend shows as expected in the LM legend.

At this point I'm not sure this is the expected behavior (and if is already documented eventually) or it figures as bug in the QGIS/LM stack. 

@mdouchin @rldhont any idea?

**Comment by rldhont** [comment]
@gioman it's a limitation because the QGIS Project does not provide the available CRSes of the WMS.

To enhance LM we have to enhance the plugin to provide the available CRSes.

**Comment by gioman** [comment]
> it's a limitation because the QGIS Project does not provide the available CRSes of the WMS.
> 
> To enhance LM we have to enhance the plugin to provide the available CRSes.


@rldhont got it. Do you want me to add a note on docs in the meantime?

**Comment by rldhont** [comment]
@gioman docs enhancements are welcome!

**Comment by gioman** [comment]
@rldhont I cannot find any reference to "Get Images directly from WMS Server" in the master docs, can you confirm?

**Comment by Gustry** [comment]
This GitHub repository accept only "bug reports". Questions must go to another channel such as [Discourse](https://discourse.osgeo.org/c/qgis/lizmap/48) for instance. 

if you think it's a proper bug, please open a new detailed bug report, with the latest version of Lizmap available.
