### ISSUE TITLE
permalink tool - multiple layer styles stored in postgresql

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#754]
hi

the permalink tool ignores the layer style if it stored in postgresql database

- montpellier case (spatialite database) - link to current map:
http://xxx/index.php/view/map/?repository=montpellier&project=montpellier&layers=B00TFTTTTFFFTTFTTTT&bbox=408960.130271%2C5392934.382187%2C455204.532378%2C5416820.953523&crs=EPSG%3A3857&layerStyles=tramway%3Acolored

   ok

- my case  (postgresql database) - link to current map:
http://xxx/index.php/view/map/?repository=ma&project=pdma_repor&layers=B0000000FFFFFFFFFFFFFTTFFTFTFTTT&bbox=-879491.530518%2C4692484.959562%2C-867930.429992%2C4698456.602396&crs=EPSG%3A3857

   have no references to the layer styles

can someone test it and confirm?
thanks

**Comment by josemvm** [comment]
when the user chooses an alternate layer style other than the default layer style, like colored (instead of black) in montpellier project, tram lines layer

**Comment by rldhont** [comment]
@josemvm do you have an url to test it ?

**Comment by josemvm** [comment]
hi @rldhont 

I built new test projects and the result was different... for now, i close this issue
thanks
