### ISSUE TITLE
A layer where the "filter" funcionality does not work

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#755]
I tested on LM 3.1.5 on both QGIS Server 2.14 and 2.18

Similar layers (same type of geometries and CRS) work ok.

What happens is that after making a selection in this layer and clicking the "filter" button, the selection is removed (as expected) but the previously unselected features are not removed from the map.

The layer was imported in PostGIS if it can matter, I attach here the original shapefile.

[estradas.zip](https://github.com/3liz/lizmap-web-client/files/1660664/estradas.zip)

**Comment by josemvm** [comment]
hi @gioman 

i can't import this shapefile to postgis

> Error 2
Creation of data source "arquivo"."estradas" failed: 
ERROR:  AddGeometryColumn() - invalid SRID
CONTEXT:  SQL statement "SELECT AddGeometryColumn('',$1,$2,$3,$4,$5,$6,$7)"
PL/pgSQL function addgeometrycolumn(character varying,character varying,character varying,integer,character varying,integer,boolean) line 5 at SQL statement

**Comment by gioman** [comment]
@josemvm the CRS of this vector is very recent and only available (out of the box) in recent versions of PostGIS.

**Comment by josemvm** [comment]
if you can send me all the parameters, like `srid, auth_name, auth_srid, srtext, proj4text`, i can insert it into the `spatial_ref_sys` postgis table

**Comment by gioman** [comment]
@josemvm is this one https://epsg.io/5016

**Comment by josemvm** [comment]
yes, i know it. it's more easy `select * from spatial_ref_sys where srid='5016'`...

**Comment by gioman** [comment]
5016;"EPSG";5016;"PROJCS["PTRA08 / UTM zone 28N",GEOGCS["PTRA08",DATUM["Autonomous_Regions_of_Portugal_2008",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","1041"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5013"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-15],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","5016"]]";"+proj=utm +zone=28 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs "

**Comment by josemvm** [comment]
> The layer was imported in PostGIS if it can matter

this is the `estradas.prj` content...

**Comment by josemvm** [comment]
hi @gioman 

the layer was imported in postgis (after insert the new srid) and tested with lwc **master branch**

![imagem](https://user-images.githubusercontent.com/10053874/35454880-b8311d72-02c7-11e8-9e3e-340beb62facc.png)

no problems, if i well understood your issue

**Comment by gioman** [comment]
@josemvm from image you understood the issue and indeed seems to work on master. I tested only on 3.1.5 and will retest on the next release when available.

**Comment by josemvm** [comment]
also tested with 3.1.5 release, with all the fixes until bugfix https://github.com/3liz/lizmap-web-client/commit/29bcfcc1975398eeeb1b59d1bc1d4ab50c1096b6

thanks, i closed this issue, reopen if needed

**Comment by gioman** [comment]
> thanks, i closed this issue, reopen if needed

@josemvm yeah... I tested on a simpler project with LM 3.1.5 and QGIS Server 2.18 and it works... it may be something related to a bigger project (where I see the issue)... but can't find the detail that triggers the problem... so leave this closed for now.
