### ISSUE TITLE
Text Label in Composer sends Lizmap in error

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#757]
Hi
I have a problem with Print in Lizmap. If I add a map, a scalebar, a legend in the Composer the PDF and PNG output are OK at any resolution. If I add a Text Label in Composer the server goes to crash with Error 500. Only when I add a Text label. I have checked any feature but I have not a solution.
Please an help.
Thanks
Lorenzo

**Comment by gioman** [comment]
@news24lor is your server a Linux one without any desktop environment (i.e. ubuntu server)?

**Comment by news24lor** [comment]
It's on Mac OS X. The problem is for any kind of text that I use. Example: if I use "Show Feature Count" on a vector layer, in lizmap I don't see the legend and it goes to crash and I have to restart Apache server. 
The label text in Composer causes an error to Apache server. 
Graphical elements such as the Legend are visible in the print in Lizmap, the written text sends it in tilt. 
Other features work like print in PDF and PNG format, not in JPG.

I use QGIS 2.18.15 on Mac OS X and last GitHub version of Lizmap plugin and Lizmap web client

Thanks

**Comment by gioman** [comment]
@news24lor the description fits a known problem for Linux servers (with no GUI) that need a fake x server as fix, see https://www.itopen.it/qgis-server-setup-notes/ I have no idea about macOS.

**Comment by news24lor** [comment]
@gioman Thank you. I've seen the document of 2014. The os x base system is UNIX. There is X11 inside OS X. The headless emulation with xvfb application is difficult to implement for QGIS that has a Qt interface also in OS X. Xvfb is useful to rendering text inside QGIS but I thinked that this problem was outdated. I will try.
Thanks!

**Comment by news24lor** [comment]
Thanks @gioman . I've seen the document and I've seen this one: https://docs.qgis.org/2.18/en/docs/training_manual/qgis_server/install.html
This fix is for working in Print Composer in a X11 environment (xvfb is a part of X11) and X11 is present in Mac OS X but it's not used in QGIS and all OS X software.
The error is only if I add the Label text. Without Label text the Print Composer works in Lizmap in OS X. There is a problem for text rendering not for graphic elements. The "Label Text" cause an error in Apache webserver. The "Show feature count" cause an error in Lizmap.

**Comment by gioman** [comment]
@news24lor have you tried if you have the same problem on another platform, one you will likely use it on the server, as for example Linux?

**Comment by news24lor** [comment]
I will try in Linux server in a Virtual machine but this problem is not linked to xvfb that is not used in QGIS OS X version. The display output of QGIS in OS X is not X11, it's Qt. The problem is only for text rendering. If the "text label" is converted to a graphic label, Print Composer works. QGIS Server or Lizmap does not render text label. The other error is the JPG output that does not work: the PDF, PNG and SVG output are OK.

**Comment by rldhont** [comment]
@news24lor, is the issue https://issues.qgis.org/issues/15440 about **QGIS Server - GetPrint Internal Server error when there is a label item in map composer** is the same ?

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/pull/5413#issuecomment-338619514 (that I previously forgot); in QGIS Server 2.18 the fake xserver is needed also on systems with a Desktop environment. This is why for example on Windows it always crashes (when doing a getprint with text boxes).

**Comment by news24lor** [comment]
Hi @rldhont . Yes I read now and the issue is the same like Windows. The problem is in QGIS Server not Lizmap. I've try QGIS 2.14 and it works: there is an error if I select "Show Feature Count" in Apache Web Server (libXML: 0: Element 'SrcSql': This element is not expected).

Only QGIS Server 2.18 does not renderize text label. The fake server inside Mac OS X with X11 does not work because QGIS is a binary for OS X environment not for X11.

This problem is only for QGIS Server 2.18 and it have to solved

**Comment by rldhont** [comment]
@news24lor The issue is due to the way qgis server is packaged. If you can build your own qgis server it's ok.
