### ISSUE TITLE
Error print "Error 500. A technical error has occured. Sorry for this trouble."

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#758]
Hi, I have a problem with lizmap everything works only when I try to print gives me the following error "Error 500. A technical error has occured.
The WMS server responds well.
Do you have any suggestions?
everything is installed on ubuntu 16.04 with qgis-server 2.14 lizmap 3.1.5
Thank you

**Comment by morvan80** [comment]
Resolved, thank you all

**Comment by josemvm** [comment]
can you share your solution with us?
