### ISSUE TITLE
get media doesn't work with pdf link to page

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/lizmap-web-client#76]
Link to a specific page from a pdf file doesn't work

Exemple : myfile.pdf --> work
Exemple : myfile.pdf#page=5 --> doesn't work

With lizmap popup default and html tuning from the plugin too...

**Comment by Alain-LG** [comment]
Hello,
Is it possible to control that this bugfix is always OK or is it broken ?
With Lizmap 3.6 and 3.7, I can't open a link to a PDF file with a specific page. It's OK for a link without specific page.

Thanks a lot for your help
