### ISSUE TITLE
[error] Error during initialization. Application temp base directory is not writable

### ISSUE THREAD

**Issue by mika973** [3liz/lizmap-web-client#760]
Hello, 

i have installed lizmap on centOS 6. When i try to acces index.php i got this error : Error during initialization. Application temp base directory is not writable. 

I dont know how to fixe this error. Do you have an idea ? 

Regards,

**Comment by rldhont** [comment]
Firstly, do not use CentOS 6!

The directory temp/lizmap in the lizmap-web-client has to be writable by the web group and the user used to install lizmap.

**Comment by mika973** [comment]
hi, 
I am forced to use centOS 6. 

I setted the right  but i still have the same problem. 

:)

**Comment by jancelin** [comment]
You can use Docker on CentOS and install a debian_lizmap container

**Comment by jancelin** [comment]
You can use Docker on centOs and install a debian lizmap container

**Comment by rldhont** [comment]
@jancelin thnaks for this option.

@mika973 if you have to use CentOS 6 and cannot use docker, you will have to build QGIS Server! The available version in the packages on CentOS 6 is QGIS Server 1.8!

If you have to use CentOS, upgrade the version to 7

**Comment by mika973** [comment]
Oops,
 i apologise, i wanted to said i run on centOS 7.

There is any specific step for this OS ? 

thank u all, 

thank u all,

**Comment by rldhont** [comment]
No special step, jsut be sure to have all packages installed, and for your issuer, be sure the directory `temp/lizmap` in the lizmap-web-client has to be writable by the web group and the user used to install lizmap.
