### ISSUE TITLE
Adding Mysql layer to Lizmap

### ISSUE THREAD

**Issue by ovidiudb** [3liz/lizmap-web-client#761]
I added a vector layer from a mysql database that only contains text attributes to link it to a layer with geometries but when I want to configure lizmap I get the error "the layers paths must be relative to the project file".
Is it possible to add layers from a mysql database? how.... ?
thank you

**Comment by mdouchin** [comment]
This is a Lizmap bug. Could you please pass here the datasource of the layer : got to the layer properties dialog, tab General, and copy the datasource text in the 1st "infos" group

**Comment by ovidiudb** [comment]
MySQL:cg,host=localhost,port=3306,user=root,tables=test|layername=test

**Comment by ovidiudb** [comment]
I added several layers like this one

**Comment by mdouchin** [comment]
Can you modify the file lizmap.py in the plugin root folder ( ~/.qgis2/python/plugins/lizmap/lizmap.py under unix or mac and /Users/yourusername/.qgis2/python/plugins/lizmap/lizmap.py )

Replace 
`if layerProviderKey in ('delimitedtext', 'gdal', 'gpx', 'grass', 'grassraster', 'ogr')`

By 
`if layerProviderKey in ('delimitedtext', 'gdal', 'gpx', 'grass', 'grassraster', 'ogr') and not layerSource.lower().startswith('mysql')`

Then restart QGIS and retry please

**Comment by ovidiudb** [comment]
It works !!
Thank you

**Comment by rldhont** [comment]
AN issue has been opened in the plugin
