### ISSUE TITLE
Master: no edition with postgresql View

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#765]
Hi,
in the master version, Lizmap cannot edit Postgresql views because there is no primary key. 
Here is the message
```
The layer "ocs_edit_view" has no primary keys. The edition tool needs a primary key on the table to be defined.
```
No problem in version 3.1.6.
No log error on master.

**Comment by jancelin** [comment]
on another project, the edition does not start and an error message is displayed.
```
error	2018-02-05 10:30:41	[0]	dbtools, pgsql: unknown table	/var/www/websig/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php	241
```

**Comment by rldhont** [comment]
@jancelin do you have multi schema with same name ?

Do you have tested last release_3_2 ?

**Comment by jancelin** [comment]
harg....
warning	2018-06-21 10:01:33	[2]	file_get_contents(http://qgiserverD/cgi-bin/qgis_mapserv.fcgi): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/var/www/websig/lizmap/modules/lizmap/classes/lizmapProxy.class.php	121

**Comment by jancelin** [comment]
@rldhont 
always the message:

```
The layer "ocs_edit_2018" has no primary keys. The edition tool needs a primary key on the table to be defined
```

I don't understand, while the primary key is manually stipulated in the Qgis file when importing a Postgis view.

```
<datasource>dbname='****' host=***** port=5432 user='****' password='****' sslmode=disable ### **key='id'** srid=2154 type=Point table="public"."limi_view" (geom) sql="limi_date" >= '2018-01-01'</datasource>
```

**Comment by rldhont** [comment]
@jancelin thanks to reactivate this issue!

**Comment by jancelin** [comment]
Thanks @rldhont , Working :)
