### ISSUE TITLE
Problem with extended display in Overview

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#768]
Hi,
In the overview view in lizmap I have a white band left on the left and below the map, is there a way to make the layer display in the whole box?
Thank you
![overview](https://user-images.githubusercontent.com/35898831/35862257-525b5b16-0b4b-11e8-8819-95d1855f2cc5.png)

**Comment by josemvm** [comment]
this is the same as https://github.com/3liz/lizmap-web-client/issues/692
@morvan80 can you confirm it?

**Comment by morvan80** [comment]
yes, so there is no solution to the problem for now?

**Comment by josemvm** [comment]
no, it's an issue tagged by developers as enhancement
closed as duplicate of https://github.com/3liz/lizmap-web-client/issues/692

thanks @morvan80
