### ISSUE TITLE
Print error with dotted symbol

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#769]
Hi!
When I try to change in qgis the symbol putting dotted, in lizmap it gives me a printing error, with gree symbols, lan, etc. the printing is done correctly.
Usage ubuntu 16.4.3 qgis / qgis-server 2.14.22
Thank you

![error_print](https://user-images.githubusercontent.com/35898831/35910192-178fac0c-0bf6-11e8-9931-72391227e198.png)
![error_print1](https://user-images.githubusercontent.com/35898831/35910195-1b3a1bf8-0bf6-11e8-9464-bbf15676c925.png)

**Comment by josemvm** [comment]
hi @morvan80 

> Usage ubuntu 16.4.3 qgis / qgis-server 2.14.22

tested here, on lizmap 3.1.6 and master branch, with no problems
![imagem](https://user-images.githubusercontent.com/10053874/35911793-b1a11686-0bf2-11e8-895b-2ee88f64c185.png)

**Comment by morvan80** [comment]
As always, thanks for your availability,
I had to add these lines to run qgis-server in the "000-default.conf" file:

  FcgidIOTimeout 120
  FcgidInitialEnv LC_ALL "en_US.UTF-8"
  FcgidInitialEnv PYTHONIOENCODING UTF-8
  FcgidInitialEnv LANG "en_US.UTF-8"
  FcgidInitialEnv QGIS_DEBUG 1
  FcgidInitialEnv QGIS_SERVER_LOG_FILE /tmp/qgis-000.log
  FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0

otherwise it did not answer correctly, can this be the cause?

**Comment by josemvm** [comment]
yes, probably...
in your case you don't need a fake X server, you have a desktop environment

**Comment by morvan80** [comment]
yes, in fact, even if I do not have a sevr X the print works for me, you have some suggestions to make the qgis server work without that string.
Thank you

**Comment by josemvm** [comment]
in your case (ubuntu desktop) you need to remove the lines above in your virtual host and stop the xvfb service if you have it running

**Comment by morvan80** [comment]
launching the command from the terminal the answer is this:
xvfb: unrecognized service

I would like to install from the head of qgis server you could recommend a reliable guide, I have followed many but the result as you see is not good.

**Comment by josemvm** [comment]
> launching the command from the terminal the answer is this:
xvfb: unrecognized service

so it is not installed

> I would like to install from the head of qgis server you could recommend a reliable guide, I have followed many but the result as you see is not good.

i'm using ubuntu server, not ubuntu desktop
about xvfb http://www.itopen.it/qgis-server-setup-notes/

about qgis server, among many other sites, you can read here https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/getting_started.html

i hope it help you

**Comment by gioman** [comment]
> yes, probably...
> in your case you don't need a fake X server, you have a desktop environment

gentle reminder when this matter comes up: the above is true for QGIS Server 2.14, in QGIS 2.18 something changed and it seems the requirement for a fake x server is always true, making almost impossible -for example- to use this version (referring to the GetPrint requests)  on Windows servers (not that I care a lot of Windows servers, but many out there do).

**Comment by morvan80** [comment]
Excuse me, if I understand correctly you say that if install qgis server 2.18 the problem does not occur?
Thank you

**Comment by gioman** [comment]
> Excuse me, if I understand correctly you say that if install qgis server 2.18 the problem does not occur?

no, I said that in QGIS Server 2.18 you must always install the fake xserver (i.e. on a Linux server that has a Desktop environment). But as this has become a "requirement" always true (likely is a bug, not a feature) then is also for Windows... but as there I really have no idea if there is a "xserver" package (especially in the osgeo4w installer, that is the most straightforward way to get QGIS Server on Windows) then GetPrints often fail.

**Comment by morvan80** [comment]
sorry I can not understand, I usu ubuntu 16.04 desktop so I still have to install the server "xserver" or not?
Thank you

**Comment by josemvm** [comment]
@morvan80 it depends on the QGIS server version and note the ubuntu desktop version

as @gioman said

>  in QGIS Server 2.18 you must always install the fake xserver (i.e. on a Linux server that has a Desktop environment).

**Comment by morvan80** [comment]
I installed everything on Ubuntu desktop 16.04 x64 qgis server 2.14 my question is if I use simple symbols the stamap happens without problems if in place I use complex symbols freezes.
If it had been an X server problem, did not it have to be a problem in both cases?

**Comment by gioman** [comment]
> I installed everything on Ubuntu desktop 16.04 x64 qgis server 2.14 my question is if I use simple symbols the stamap happens without problems if in place I use complex symbols freezes.
> If it had been an X server problem, did not it have to be a problem in both cases?

if you install the fake xserver as described here http://www.itopen.it/qgis-server-setup-notes/ you should not have issues.

**Comment by morvan80** [comment]
I saw the guide but I can not figure out how to install from the terminal, could you help me to do the procedure?
Thank you

**Comment by josemvm** [comment]
sorry @morvan80 

> FcgidIOTimeout 120
FcgidInitialEnv LC_ALL "en_US.UTF-8"
FcgidInitialEnv PYTHONIOENCODING UTF-8
FcgidInitialEnv LANG "en_US.UTF-8"
FcgidInitialEnv QGIS_DEBUG 1
FcgidInitialEnv QGIS_SERVER_LOG_FILE /tmp/qgis-000.log
FcgidInitialEnv QGIS_SERVER_LOG_LEVEL 0

these lines are required for the wfsOutputExtension plugin and not for the fake X server

about fake X server installation all you need to know is in the guide above, just follow the few steps as explain it the description

this subject goes beyond the scope of this issue, so i close it
