### ISSUE TITLE
Popup doesn't work.

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#772]
Popup does not seem to work properly, does not open more than that (see screenshot below), whatever I click.
Any idea?
![cattura](https://user-images.githubusercontent.com/28729838/36087938-3957ff78-0fd5-11e8-8e9d-e32c26139935.PNG)

**Comment by rldhont** [comment]
The left dock has a width depending on the content with a max-width to 30% of the screen.

In your example the ledtf dock is empty, so the width is equal to the dock title width.

**Comment by rldhont** [comment]
The GetFeatureInfo seems to do not responds. Which LWC version do you use ?
Can you take a look at the dev console to see the GetFeatureInfo request and take a look at the QGIS Server log ?

**Comment by quelo1972** [comment]
**@rldhont** 

> The GetFeatureInfo seems to do not responds. Which LWC version do you use ?

Now I've installed the master but I tried also the 3.1.6

> Can you take a look at the dev console to see the GetFeatureInfo request and take a look at the QGIS Server log ?

How can I do this?

**Comment by rldhont** [comment]
with Firefox `Ctrl+Maj+k`

**Comment by quelo1972** [comment]
**@rldhont**
Ok when I click on an element in the map, in the console tab network response I have:

```
<GetFeatureInfoResponse>
 <Layer name="Quartiers">
  <Feature id="4">
   <Attribute value="7" name="QUARTIER"/>
   <Attribute value="MC" name="QUARTMNO"/>
   <Attribute value="MONTPELLIER CENTRE" name="Name"/>
   <Attribute value="MCB" name="SQUARTMNO"/>
   <Attribute value="media/layer/quartier/montpelliercentre.png" name="Illustration"/>
   <Attribute value="http://montpelliercentre.montpellier.fr/" name="Website"/>
  </Feature>
 </Layer>
 <Layer name="publicbuildings">
  <Feature id="5">
   <Attribute value="Railway station" name="Name"/>
   <Attribute value=" " name="Description"/>
  </Feature>
 </Layer>
 <Layer name="tramway">
  <Feature id="1">
   <Attribute value="media/layer/trams/tram4.html" name="html"/>
  </Feature>
  <Feature id="2">
   <Attribute value="media/layer/trams/tram4.html" name="html"/>
  </Feature>
  <Feature id="3">
   <Attribute value="media/layer/trams/tram2.html" name="html"/>
  </Feature>
  <Feature id="4">
   <Attribute value="media/layer/trams/tram2.html" name="html"/>
  </Feature>
 </Layer>
 <Layer name="tramstop"/>
 <Layer name="edition_line"/>
 <Layer name="points of interest"/>
</GetFeatureInfoResponse>
```
But **nothing** in the popup.

**Comment by rldhont** [comment]
It seems that Lizmap does not transform the XML to HTML.

Can you take a look at the logs `lizmap/var/log/error.log` ?

**Comment by quelo1972** [comment]
Nothing in the error.log or in the dev console.
I tried to replicate it on another identical machine with ubuntu 16.04 LTS and the popup works. the only difference is that on the machine where the popup does not work is installed php 7.2 (from external repository) instead of the official 7.0 provided by ubuntu. Maybe there is an incompatibility with php > 7.0?

**Comment by nboisteault** [comment]
@quelo1972 
Does issue still occur ?
