### ISSUE TITLE
Display categorized layer column

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#776]
Hi!
I have a problem in the visualization in lizmap, I would like to bring up the column of membership of the categorized layer as in picture.
How can I do?
Thank you
![heading](https://user-images.githubusercontent.com/35898831/36157948-5858ff74-10db-11e8-8120-53eda9009837.png)

**Comment by josemvm** [comment]
hi @morvan80 

as a workarround, i.e.,  you can create a group named `Elettori totali` above your `Elettori totali` layer in your qgis project

**Comment by rldhont** [comment]
@morvan80 is it an issue in the legendGraphics ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
