### ISSUE TITLE
Data edition and user rights

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#78]
I didn't test if this function exists but I didn't see it in the documentation (http://docs.3liz.com/fr/lizmap-plugin/features/edition.html) so I guess it doesn't exist.

When a logged user edit data and add a feature to a layer, his group id should be written in a predefined column (for example "group_id"). This way the user only work with the features of his group.

**Comment by rldhont** [comment]
This enhancement has been probably fixed with ade9bfb703c6d5955c16511a0d402750b6ced346 and #119
