### ISSUE TITLE
seeding script: tilematrixset not found

### ISSUE THREAD

**Issue by zoidable** [3liz/lizmap-web-client#781]
hi there,

since updating to 3.1.8, apparently the cache is gone and in the seeding script, i get the following error message: 

> The TileMatrixSet EPSG:25832 has not to be found!

the var/log/error.log states:

> 2018-02-22 13:19:17	127.0.0.1	notice	2018-02-22 13:19:17	[8]	Undefined variable: tileMatrixSetList	C:\Webserver\lizmap\prod\master\lizmap\modules\lizmap\controllers\wmts.cmdline.php	244
> 
> 2018-02-22 13:19:17	127.0.0.1	warning	2018-02-22 13:19:17	[2]	Invalid argument supplied for foreach()	C:\Webserver\lizmap\prod\master\lizmap\modules\lizmap\controllers\wmts.cmdline.php	244

cheers,
tobias

**Comment by rldhont** [comment]
what is the result of the command:
```
php lizmap/scripts/script.php lizmap~wmts:capabilities repository project
```

**Comment by zoidable** [comment]
the capabilities are working as they should, e.g. in this case:

> C:\Webserver\lizmap\prod\master\lizmap\scripts>php script.php lizmap~wmts:capabilities -v public bplaene zeichn EPSG:25832
> For "zeichn" and "EPSG:25832" the TileMatrix 0 has 49 tiles
> For "zeichn" and "EPSG:25832" the TileMatrix 1 has 132 tiles
> For "zeichn" and "EPSG:25832" the TileMatrix 2 has 575 tiles
> For "zeichn" and "EPSG:25832" the TileMatrix 3 has 2156 tiles
> For "zeichn" and "EPSG:25832" the TileMatrix 4 has 8245 tiles
> For "zeichn" and "EPSG:25832" the TileMatrix 5 has 49951 tiles
