### ISSUE TITLE
Locate by layer very slow and do not works with PostGIS and spatialite

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-web-client#783]
I recently do an update of my server from QGIS-Server 2.14 to 2.18 and php5.5 to php 7.0 
Now the locate by layer function is very slow if I have a large number of entity (e.g. 25'000)
Using a postgis layer apache2 crash

How can I do it more quickly? 

With old qgis server and php 5.6 it is slow but it works.

**Comment by rmarzocchi84** [comment]
Moreover I see the following strange behaviour.  sing spatialite or postgis the output of the WFS GetFeature request do not contain the id, while using an ESRI shapefile it contain the id


POSTGIS REQUEST
https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=dorota&project=mappa_incidenti&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=municipo&OUTPUTFORMAT=GeoJSON&GEOMETRYNAME=extent&PROPERTYNAME=geometry%2Cnome_munic

{"type": "FeatureCollection",
 "bbox": [ 8.66328335, 44.37787282, 9.0979391, 44.52055853],
 "features": [
  {
   "type":"Feature",
   **"id":"municipo.",**
   "bbox":[8.911015, 44.394807, 8.948944, 44.441498],
   "geometry":
   {"type": "Polygon", "coordinates": [[ [8.911086, 44.394807], [8.948944, 44.394831], [8.948903, 44.441498], [8.911015, 44.441475], [8.911086, 44.394807]]] },
   "properties":{
      "nome_munic":"Centro est"
   }
}
[...]


SPATIALITE REQUEST
https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=dorota&project=mappa_incidenti&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=municipi&OUTPUTFORMAT=GeoJSON&GEOMETRYNAME=extent&PROPERTYNAME=geometry%2CNOME_MUNIC

{"type": "FeatureCollection",
 "bbox": [ 8.66543983, 44.3785835, 9.09578466, 44.51985394],
 "features": [
  {
   "type":"Feature",
   **"id":"municipi.",**
   "bbox":[8.911015, 44.394807, 8.948944, 44.441498],
   "geometry":
   {"type": "Polygon", "coordinates": [[ [8.911086, 44.394807], [8.948944, 44.394831], [8.948903, 44.441498], [8.911015, 44.441475], [8.911086, 44.394807]]] },
   "properties":{
      "NOME_MUNIC":"Centro est"
   }
}
[...]

SHAPEFILE REQUEST
https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=dorota&project=mappa_incidenti&SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=municipi_shape&OUTPUTFORMAT=GeoJSON&GEOMETRYNAME=extent&PROPERTYNAME=geometry%2CNOME_MUNIC

{"type": "FeatureCollection",
 "bbox": [ 8.66543983, 44.3785835, 9.09578466, 44.51985394],
 "features": [
  {
   "type":"Feature",
   **"id":"municipi_shape.0",**
   "bbox":[8.911015, 44.394807, 8.948944, 44.441498],
   "geometry":
   {"type": "Polygon", "coordinates": [[ [8.911086, 44.394807], [8.948944, 44.394831], [8.948903, 44.441498], [8.911015, 44.441475], [8.911086, 44.394807]]] },
   "properties":{
      "NOME_MUNIC":"Centro est"
   }
}
[...]

**Comment by gioman** [comment]
> Now the locate by layer function is very slow if I have a large number of entity (e.g. 25'000)

@rmarzocchi84 see https://issues.qgis.org/issues/18249#note-1

**Comment by gioman** [comment]
> Moreover I see the following strange behaviour. sing spatialite or postgis the output of the WFS GetFeature request do not contain the id, while using an ESRI shapefile it contain the id

@rmarzocchi84 cannot confirm here, see https://issues.qgis.org/issues/18247#note-9

**Comment by rmarzocchi84** [comment]
So It seem a problem of qgis serverEng. Roberto MarzocchiGter srlSent by my Android phoneIl 27 feb 2018 17:30, Giovanni Manghi <notifications@github.com> ha scritto:
Now the locate by layer function is very slow if I have a large number of entity (e.g. 25'000)

@rmarzocchi84 see https://issues.qgis.org/issues/18249#note-1

**Comment by rldhont** [comment]
lizmap can't detect the QGIS Server version because there is no request to get this information.

**Comment by pcav** [comment]
I also have an issue with zooming to feature from the attribute table, only for PostGIS layers, see https://lists.osgeo.org/pipermail/lizmap/2020-April/000105.html
Possibly related?

**Comment by Gustry** [comment]
> So It seem a problem of qgis server

You were using QGIS 2.X/ Do you still have the issue with QGIS 3?

@pcav Are your columns using int8 longlong as a primary key?

**Comment by pcav** [comment]
QGIS 3.10
PK is int
I can provide a demo installation
thanks

**Comment by rmarzocchi84** [comment]
> You were using QGIS 2.X/ Do you still have the issue with QGIS 3?

No the problem is solved. Perhaps it is better to close this issue and open a new one with the problem of @pcav

**Comment by Gustry** [comment]
Yes, thanks for the feedback
