### ISSUE TITLE
Error 500 version 3.1.8

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#791]
Hi,
I've installed the versione 3.1.8 but when I go to the main web page i have
`Error 500. A technical error has occured. Sorry for this trouble.`
in the error.log I have
`2018-03-03 17:19:27     192.168.23.171  error   2018-03-03 17:19:27     [18]    Unknown module in the selector "view~default:index@classic"        /opt/www/lizmap-web-client-3.1.8/lib/jelix/core/selector/jSelectorActFast.class.php56`
where can be the problem?

**Comment by quelo1972** [comment]
I've configured LWC to authenticate with Active Directory and to use Postgresql for the project and logging as the previous 3.1.6 successfully configured.

**Comment by rldhont** [comment]
do you do `php limzap/install/installer.php` ?

**Comment by rldhont** [comment]
Can you provide some feedback on this issue ?

**Comment by rldhont** [comment]
I close it, reopen if needed
