### ISSUE TITLE
lwc - fresh install (master branch) - not working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#792]
error during installation:

> PHP Warning:  SQLite3::exec(): NOT NULL constraint failed: jlx_user.firstname in /var/www/html/lizmap-web-client-master/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php on line 120

> [error] An error occured during the installation of the module lizmap: invalid query (NOT NULL constraint failed: jlx_user.firstname (INSERT INTO jlx_user (usr_login, usr_password, usr_email ) VALUES
> ('lizadmin', '$2y$10$ha68N.rBRBSZoPFzExDSGuYfsXaGYy/D4acMf5j6hhzjC8oglICrS' , 'lizadmin@nomail.nomail')))

browser error:

> 404 Not Found
Sorry, the requested page doesn't exist
Page generated by Jelix.

**Comment by rldhont** [comment]
The lizmap installation not welle finished so Lizmap is not installed and available.

**Comment by buoncri** [comment]
in addiction to this, it seems near same bug is in installing with postgres. This is the message:

`
luca@vespucci:/var/www/mylizmap$ sudo php lizmap/install/installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
[error] An error occured during the installation of the module jacl2db: invalid query (ERRORE:  la INSERT o l'UPDATE sulla tabella "jacl2_user_group" viola il vincolo di chiave esterna "jacl2_user_group_id_aclgrp_fkey"
DETAIL:  La chiave (id_aclgrp)=(__priv_admin) non è presente nella tabella "jacl2_group".(INSERT INTO "jacl2_user_group" ("login","id_aclgrp") VALUES ('admin','__priv_admin')))
Installation ended.
`

**Comment by laurentj** [comment]
Both issues are fixed. thanks for your reports
