### ISSUE TITLE
Service non disponible?!?

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#793]
I have installed LWC 3.1.8 (basic configuration as the installation manual) but when I click on the demo project it not work, see the attached screenshot:
![cattura](https://user-images.githubusercontent.com/28729838/37021969-bb857bee-2121-11e8-9b75-8e516a7c3233.PNG)

**Comment by quelo1972** [comment]
qgis-server is installed...
`root@SRVLNXWINTRA01:~# dpkg -l | grep qgis-server
ii  libqgis-server3.0.0                   1:3.0.0+24xenial-ubuntugis                               amd64        QGIS - shared server library
ii  qgis-server                           1:3.0.0+24xenial-ubuntugis                               amd64        QGIS server providing various OGC services`
what should i check?

**Comment by quelo1972** [comment]
Ho un sospetto... siccome ho installato qgis-server python-qgis from launchpad adding in sources.list the following line

```
deb https://qgis.org/ubuntugis xenial main
deb-src https://qgis.org/ubuntugis xenial main
```

ho visto che dopo un aggiornamento si è passati alla versione 3.0 the problem can be this?

**Comment by quelo1972** [comment]
I suspect ... as I installed qgis-server python-qgis from launchpad adding in sources.list the following line
```
deb https://qgis.org/ubuntugis xenial main
deb-src https://qgis.org/ubuntugis xenial main
```
I saw that after an update has been passed to version 3.0, that this is the problem?

**Comment by gioman** [comment]
> It return this:

@quelo1972 
have you replaced the path in 

http://yourip/cgi-bin/qgis_mapserv.fcgi?map=/path/to/project.qgs&service=WMS&request=GetCapabilities

with a real patch pointing to a qgis project file?




> I saw that after an update has been passed to version 3.0, that this is the problem?

should work I guess, but I won't suggest using qgis 3 until it will become a ltr.

**Comment by quelo1972** [comment]
> @quelo1972
have you replaced the path in
http://yourip/cgi-bin/qgis_mapserv.fcgi?map=/path/to/project.qgs&service=WMS&request=GetCapabilities
with a real patch pointing to a qgis project file?

Yes

How can I downgrade to the LTR 2.18 in ubuntu 16.04 LTS release? I do not see it among the available packages.

**Comment by gioman** [comment]
> How can I downgrade to the LTR 2.18 in ubuntu 16.04 LTS release? I do not see it among the available packages.

@quelo1972 remove all installed qgis packages, use

deb https://qgis.org/ubuntugis-ltr xenial main

**Comment by quelo1972** [comment]
@gioman 
Done! now it works!

We found out that lizmap does not work with qgis-server 3.0! :)

**Comment by gioman** [comment]
@quelo1972 

> We found out that lizmap 3.1.8 does not work with qgis-server 3.0! :)

it turns that LM work fine with QGIS Server 3, it is/was QGIS Server 3 that was not ok

See: https://github.com/qgis/QGIS/pull/6502

if you install QGIS Server 3 master is ok.

From what I can see because of changes in the QGIS 3 print composer likely it will be needed to change LM accordingly in the way it builds the GetPrint requests. @rldhont

**Comment by Alexandr06** [comment]
@gioman 
vous pouvez développer encore un peu plus svp ? parce qu'en fait actuellement j'ai un problème au niveau de l'impression sur lizmap et je crois que c'est de ça que vous parlez :)

**Comment by Alexandr06** [comment]
@gioman  
can you develop a little more please? because I actually have a problem with lizmap printing, and I think that's what you're talking about :)

**Comment by gioman** [comment]
> can you develop a little more please? because I actually have a problem with lizmap printing, and I think that's what you're talking about :)

@Alexandr06 I have not tested qgis server 3 extensively but from what I have seen in QGIS 3 Desktop the way the map objects (in a print layout) are numbered is different if compared to QGIS 2.*. So when building a GetPrint request LM will need to take into account this change. At the moment it uses the numbering as it is in QGIS 2 and of course the result is not correct (in the simplest case, 1 map object, the map is visible at all in the resulting pdf).

**Comment by Alexandr06** [comment]
@gioman thank you for your answer, excuse me I'm not very well explained, in fact, the settings of my server are:
win7 x64 bit, apache2.4, php7.1, lizmap3.1 qgis 2.18, qgis server 2.18.
but when I want to print with a qgis layout template that I customized according to the map I want to have as a result, the server sends me "Internal server error", in the file error.log I "[Thu May 31 13: 48: 46.290655 2018] [fcgid: warn] [pid 9420: tid 476] mod_fcgid: process 1832 graceful kill fail, sending SIGKILL". an error that I can not solve for more than a month ...

**Comment by Alexandr06** [comment]
https://github.com/gioman dcdcc

**Comment by gioman** [comment]
@Alexandr06 I see you are on Windows, so you are out of luck. Explanation: on Linux headless installation (no GUI) to make the QGIS Server GetPrint requests was always necessary to install a fake xserver. At some point in QGIS Server 2.18 this become mandatory also for installations on Desktops. Unfortunately this has affected the Windows packages/installers meaning that QGIS Server 2.18 expect a fake xserver... that on Windows is not even available. I reaised this problem several times here, on the QGIS mailing lists, direct messaging developers (asking how much would cost fixing this) but basically at no avail. If you can stick with QGIS Server 2.14.

**Comment by Alexandr06** [comment]
thank you @gioman oman yes I see what you say and I want to stay on version 2.14 of qgis, except that it does not exist anymore! when I try to install it from Osgeo there's only 2.18 and 3.0...

**Comment by gioman** [comment]
> thank you @gioman oman yes I see what you say and I want to stay on version 2.14 of qgis, except that it does not exist anymore! when I try to install it from Osgeo there's only 2.18 and 3.0...

@Alexandr06 I'm not sure if with osgeo4w there is any procedure to install obsolete packages, I haven't looked into it myself yet. I would be more interested in a clear fix of this regression, I even asked some professional support to QGIS developer (and also the official packager), but for different reasons they do not seem very interested (or have time) in tackling this matter.
