### ISSUE TITLE
spatialite warning

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#795]
The editing on spatialite layers seems to work but in error.log I have this warning can you tell me if it's a problem and then how to fix it?

`2018-03-06 17:26:58     192.168.23.171  warning 2018-03-06 17:26:58     [2]     SQLite3::loadExtension(): /var/www/sqlite3_ext/libspatialite.so: undefined symbol: sqlite3_spatialite_init     /opt/www/lizmap-web-client-3.1.8/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php 90`

despite this warning the points are added correctly on my spatialite layer.

**Comment by rldhont** [comment]
It's just a warning, because spatialite can be provide as `libspatialite.so` or `mod_spatialite.so`, lizmap tests the two files and warn for the one not available.
