### ISSUE TITLE
Fond IGN

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#799]
Bonjour,

Je dispose d'une clé IGN pour l'affichage du fond de plan IGN mais celui-ci ne s'affiche pas, juste un fond blanc pour les 4 couches disponibles (photo, plan, scan et cadastre). Il y a pourtant bien la signature 'Géoportail' en bas à droite et je peux afficher ces cartes en WMS directement dans QGIS.
J'utilise le protocole referer.
D'où peut venir ce problème ?

**Comment by mdouchin** [comment]
QGIS Server ne semble pas réussir à charger ces couches. Selon les version de QGIS Server, il peut y avoir des souci si les URL des couches WMS sont en https . Si c'est le cas, essayez d'utiliser l'URL IGN avec http (en clair) pour voir si cela corrige le souci

**Comment by rldhont** [comment]
@Cww7 can you provide some feedback ?

**Comment by Cww7** [comment]
Hi,
Sorry, but I have no IGN key available since a few months. I no longer use IGN basemaps.
