### ISSUE TITLE
Regression: cannot login when password is lower than 8 characters

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#801]
When migrating Lizmap from 3.1 to the master branch, existing users in the database may have password less than 8 characters (which is bad ;-)). However, the password field in the login form provided by the new module jCommunity has a constraint on the minimal length (8 characters). So users cannot sign in.

Will be fixed in the next version of jCommunity.

**Comment by josemvm** [comment]
we have the **lizadmin** user, lizadmin password (8 characters)... but no admin rights... it can become an administrator (?)...

**Comment by laurentj** [comment]
If by admin rights, you mean rights to manage users and their rights, these rights was own by the "admin" user. However, because of a regression, this user is not created. see #800
