### ISSUE TITLE
locating tool on qgis server 2.18 - montpellier project

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#804]
some problems detected:

- the refresh button desn't work
- the tool doesn't highlight the geometry if it's set `displayGeom": "True`
- "Tram Lines" layer - the tool crashes after first location

thanks

**Comment by josemvm** [comment]
on qgis server 2.14 the clear button desn't work properly too

the clear button on the header menu works fine

**Comment by rldhont** [comment]
@josemvm which lizmap version ?

**Comment by josemvm** [comment]
@rldhont master version

**Comment by josemvm** [comment]
solved on QGIS Server 2.18.24 and LWC 3.3pre version

**Comment by mdouchin** [comment]
can we close this issue ?

**Comment by josemvm** [comment]
yes, everything is fine
