### ISSUE TITLE
CACHE_STATUS":"off" error

### ISSUE THREAD

**Issue by elyparker** [3liz/lizmap-web-client#805]
hi receive often the following error on log of apache 
generally it is associated to long time of load map

i enabled cache in apache and in lizmap (file)  but the problem continue

```
php-apache2handler-webgis.sit-sglapunta.it[7224]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":103.7700176239,"CACHE_STATUS":"off"}
php-apache2handler-webgis.sit-sglapunta.it[30066]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":109.04622077942,"CACHE_STATUS":"off"}
php-apache2handler-webgis.sit-sglapunta.it[7217]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":92.41509437561,"CACHE_STATUS":"off"}
php-apache2handler-webgis.sit-sglapunta.it[7220]: {"NAME":"LIZMAP_SERVICE_GETMAP","RESPONSE_TIME":246.69599533081,"CACHE_STATUS":"off"}

```

**Comment by guenterw** [comment]
hi

i have the same problem and my lizmap-client is very slow

how do you enable the cache in apache (V 2.4.18) and in lizmap?

**Comment by elyparker** [comment]
for apache 
sudo a2enmod file_cache
[a guide](https://www.digitalocean.com/community/tutorials/how-to-configure-apache-content-caching-on-ubuntu-14-04)

and in lizmap option in aadmi account set as file caching 

but the error ther is always

**Comment by guenterw** [comment]
thanks,
i have the same: enabled cache in apache and in lizmap (file)

but the error is only in my projects.
in the montpellier-project in the same lizmap-installation there is no error in the logfile!

have you tried the same with the montpellier-project?

**Comment by elyparker** [comment]
no i not tried, i deleted it 
but whas is the cause of problem?

**Comment by guenterw** [comment]
i don't know about the difference

**Comment by nboisteault** [comment]
Lizmap 3.1.3
QGIS Server 2.18
I have the same logs in /var/log/syslog when Lizmap do some GetMap request. It writes a line for every getMap of every project. Strangely the domain name in the log is always the one of the first project in my project list. I'm looking more deeply.

**Comment by rldhont** [comment]
@nboisteault is quick fix possible ?

**Comment by nboisteault** [comment]
@rldhont I don't have any setup with Apache actually.

**Comment by rldhont** [comment]
The messages are wrote by lizmap.

**Comment by rmarzocchi84** [comment]
I encountered this error in the Apache error log and it correspond to  long time of load map. 

![image](https://user-images.githubusercontent.com/4061154/68296678-7453d680-0095-11ea-8e73-1e847f4fdf36.png)

In particular there is an high Waiting (TTFB) time
