### ISSUE TITLE
Error when run the installer

### ISSUE THREAD

**Issue by quelo1972** [3liz/lizmap-web-client#807]
What it means when I run the installer and exit the following error?
```
root@UBUNTUGIS02:/var/www/lizmap-web-client-3.1.8# php lizmap/install/installer.php
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/lizmap-web-client-3.1.8/lib/jelix/installer/jInstaller.class.php:250
Stack trace:
#0 /var/www/lizmap-web-client-3.1.8/lizmap/install/installer.php(14): jInstaller->__construct(Object(textInstallReporter))
#1 {main}
  thrown in /var/www/lizmap-web-client-3.1.8/lib/jelix/installer/jInstaller.class.php on line 250
```

**Comment by quelo1972** [comment]
ok ... sorry ... the php-xml package was missing!
You can close the issue.

**Comment by wladyslawlokietko** [comment]
I have the same error:
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/lizmap-web-client-3.3.2/lib/jelix/installer/jInstaller.class.php:261
Stack trace:
#0 /var/www/lizmap-web-client-3.3.2/lizmap/install/installer.php(14): jInstaller->__construct(Object(textInstallReporter))
#1 {main}
  thrown in /var/www/lizmap-web-client-3.3.2/lib/jelix/installer/jInstaller.class.php on line 261

when trying to install Lizmap by this command in Ubuntu 18:
php lizmap/install/installer.php

I installed xml packages (apt install php-xml). Everything is up-to-date.
Can anybody please help???
