### ISSUE TITLE
cannot access to dashboard for user admin

### ISSUE THREAD

**Issue by mkazmiers** [3liz/lizmap-web-client#808]
Hi,

In the lizmap dashboard, with the admin user, we've updated rights for a custom user group we've created ('crige_users'). After the update, the dashboard is not showing anything for the admin user on the admin.php as you can see below 

![image](https://user-images.githubusercontent.com/16324693/37334179-73b9fa4e-26ab-11e8-8c4c-813ba93d2e4c.png)

We can still log in, projects are still usable but the admin interface is empty, not only for the admin user but for all the granted users...

We've restarted apache & postgre, nothing better. We've checked documentation but still don't know where the rights are stored ; in a file? in postgres? in another db (sqlite?)?

Any idea?

**Comment by mkazmiers** [comment]
We have found some error in the error.log close to the issue #332 .

> Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
> Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
> Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
> Warning 1: Unable to find driver ECW to unload from GDAL_SKIP environment variable.
> Warning 1: Unable to find driver JP2ECW to unload from GDAL_SKIP environment variable.
> **ERROR: Auth db directory path could not be created**

Could it be related with a jelix error?

**Comment by mkazmiers** [comment]
Update : we've updated rights for the admin & users user_group by updating the sqlite DB. The dashboard can be accessed again - good.

Though, the rights for all the others groups seems to have been erased, which might be a consequence of the sequence described above !

Any suggestion would be great so as we don't want to repeat it and loose again our sqlite db..!
Thanks

**Comment by laurentj** [comment]
I cannot reproduce the issue. Probably some steps are missing from the issue description. 

You can reopen the issue if it occurs again.
