### ISSUE TITLE
Sender address of e-mails - "Sender address of e-mails" field is invalid

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#809]
hi

when the user change same value in lizmap configuration, just like "QGIS server version", the "root@localhost" default value is not valid

no problems if the we change from "root@localhost" default value to "root@localhost.localdomain" default value

**Comment by laurentj** [comment]
Which version of Lizmap?

**Comment by josemvm** [comment]
master version @laurentj

**Comment by laurentj** [comment]
I will replace the default value by an empty value, and will improve the form to enable or disable some fields that depend of the email.

**Comment by laurentj** [comment]
The issue is fixed, but the improvements I talked about will be done later, see #871

**Comment by josemvm** [comment]
@laurentj the "Sender address of e-mails" happens as a required field when you try to change any other field
