### ISSUE TITLE
atlas popup - montpellier project

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#811]
hi @mdouchin 

please add this feature to the montpellier project

thanks in advance

**Comment by mdouchin** [comment]
Done in 9dc91f94

**Comment by josemvm** [comment]
thanks @mdouchin 

i'm testing qgis server 2.18 and when i try to print the popup contents i get these apache errors:


`[Thu Mar 15 21:46:25.678654 2018] [fcgid:warn] [pid 16988] [client 127.0.0.1:53196] mod_fcgid: error reading data, FastCGI server closed connection`

`[Thu Mar 15 21:46:25.679212 2018] [core:error] [pid 16988] [client 127.0.0.1:53196] End of script output before headers: qgis_mapserv.fcgi`

`[Thu Mar 15 21:46:30.240422 2018] [fcgid:error] [pid 16949] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(17262) exit(communication error), get signal 11, possible coredump generated`

**Comment by josemvm** [comment]
on qgis server 2.14 everything works fine!
nice feature :-)

**Comment by mdouchin** [comment]
I also have problems in last 2.18, but for some projects only (Montpellier demo): some requests return the PDF, but for some QGIS segfault (same query...) I could not find any valid reason. It is not a Lizmap issue, but a QGIS one. @rldhont

**Comment by josemvm** [comment]
@mdouchin 

Is it possible to print according to active layers, styles layers, transparency layers, filter features?

**Comment by josemvm** [comment]
like print tool...

**Comment by mdouchin** [comment]
I would like to keep it this way, at least for the next release. When the editor configures an atlas, I think he does not want the export PDF to be too different from the original composer settings. This is why I chose not to change anything yet.

Please open a ticket in atlasprint plugin for this feature request

**Comment by josemvm** [comment]
@mdouchin 

about this feautre, i think it's very important to print the highlight geometry for the current feature (because sometimes the printing becomes difficult to read)

but the qgis server lost this ability a long time ago... https://github.com/3liz/lizmap-web-client/issues/464

for while, the alternative could be the possibility of using the filter tool... as here https://github.com/3liz/qgis-atlasprint/issues/2

thanks

**Comment by josemvm** [comment]
more tests on QGIS server 2.18.21

apache errors:

```[Fri Jul 20 11:40:56.664897 2018] [fcgid:warn] [pid 2477] [client 127.0.0.1:50414] mod_fcgid: error reading data, FastCGI server closed connection

[Fri Jul 20 11:40:56.664897 2018] [fcgid:warn] [pid 2477] [client 127.0.0.1:50414] mod_fcgid: error reading data, FastCGI server closed connection

[Fri Jul 20 11:40:56.665097 2018] [core:error] [pid 2477] [client 127.0.0.1:50414] End of script output before headers: qgis_mapserv.fcgi

[Fri Jul 20 11:41:02.567071 2018] [fcgid:error] [pid 1332] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(2475) exit(communication error), get signal 11, possible coredump generated
```


lizmap error:

```2018-07-20 12:47:58 10.27.11.245 warning 2018-07-20 12:47:58 [2] file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error /var/www/html/lizmap-web-client-release_3_2/lizmap/modules/lizmap/classes/lizmapProxy.class.php 136
2018-07-20 12:47:58 10.27.11.245 warning 2018-07-20 12:47:58 [2] file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error /var/www/html/lizmap-web-client-release_3_2/lizmap/modules/lizmap/classes/lizmapProxy.class.php 136
```

thanks

**Comment by josemvm** [comment]
more tests on QGIS Server 2.18.24

lizmap url:
```
http://mydomain/index.php/lizmap/service/?repository=montpellier&project=montpellier&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrintAtlas&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&DPI=100&TEMPLATE=Landscape%20A4&EXP_FILTER=$id%20IN%20(0)
```
apache errors:
the same as above and
```
[Mon Oct 01 10:50:31.592404 2018] [negotiation:error] [pid 2332] [client 10.27.11.245:49305] AH00687: Negotiation: discovered file(s) matching request: /var/www/html/lizmap3/lizmap/www/admin (None could be negotiated)., referer: http://10.27.1.31/admin.php/admin/logs/
```

lizmap error:
the same as above

thanks

**Comment by gioman** [comment]
is confirmed this is not working with qgis server 2.18?

**Comment by josemvm** [comment]
hi @mdouchin 
it works well inside the atlas frame but not inside the popup frame
qgis server 2.18.28

**Comment by nboisteault** [comment]
@josemvm Can you put steps to reproduce your issue please ?

**Comment by josemvm** [comment]
hi @nboisteault 

try to run the atlas tool, go to the first feature `croixc d'argent` and print it - output ok
click over `Landscape A4` again - no results

you need to run the `clean_vartmp.sh` to solve it
similar behavior for the print from popup

you can only print once at a time...

**Comment by nboisteault** [comment]
In my case it prints randomly. `clean_vartmp.sh` doesn't make it work better.
@mdouchin I don't think this bug will be resolved for 3.2 as it depends on QGIS Server 2.18. I think we'll have to wait for a migration of the qgis-atlasprint plugin to work with QGIS Server 3.4. Can I change milestone to 3.3 ?

**Comment by rldhont** [comment]
Move to 3.3

**Comment by nboisteault** [comment]
Everything works as expected with qgis-atlasprint plugin v 1.2.2.
