### ISSUE TITLE
modify the popup "informazioni"

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#812]
hi, in which file .js is possible modify the title and the text  what show
in the popup "informazioni"?
![cattura](https://user-images.githubusercontent.com/28442671/37467307-27076b26-2860-11e8-847e-fd4fe494778f.PNG)

**Comment by rldhont** [comment]
The title and the text is extracted from the WMS GetCapabilities. You can update the QGIS Project properties to update it.

**Comment by igeofr** [comment]
Yes it is possible by using this code :
`$("div#content div#metadata.tab-pane div div dl.dl-vertical dt:contains('Title')").html("New title");`
`$("div#content div#metadata.tab-pane div div dl.dl-vertical dd:contains('Old value')").html("New value");`

**Comment by rmarzocchi84** [comment]
We try with: 
```
lizMap.events.on({
    mapcreated: function(e) {
        $("div#content div#metadata.tab-pane div div dl.dl-vertical dt:contains('Organization')").html("New name for organization");
    }
});
```

It works!!

**Comment by rmarzocchi84** [comment]
It is possible to add image as html content?

**Comment by Gustry** [comment]
> It is possible to add image as html content?

As you can use the media folder and add the image path with the JS.
Follow https://docs.lizmap.com/next/en/publish/customization/javascript.html#url-of-a-static-file

Issue solved!
