### ISSUE TITLE
Problem with embedded maps

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#815]
I use embedded maps and noticed one thing to correct.
If I select a layer in the layers list, the window that should open on the right with the possibility to select transparency and more, goes under the layer window and therefore really unusable.

Can you correct this problem? 

Thanks

**Comment by SenequeC** [comment]
I added a picture of the problem to help to analyze the problem.

![image](https://user-images.githubusercontent.com/33847726/37585917-fdf592c8-2b5a-11e8-9c35-94e1b7c0be74.png)

**Comment by josemvm** [comment]
small size...

**Comment by news24lor** [comment]
![screenshot](https://user-images.githubusercontent.com/33484600/37587196-e7aa2250-2b5e-11e8-8809-0af2b7505ced.jpg)

**Comment by josemvm** [comment]
![imagem](https://user-images.githubusercontent.com/10053874/37587687-ecc463ec-2b57-11e8-8b14-8f09e12df986.png)

**Comment by news24lor** [comment]
Selecting the layer, the INFORMATION window (INFORMAZIONI in italian) is below the main one, as you can see from the screenshot: you can see it even if it is a little blurred.
Your INFORMATION window is on the right as in the normal full-screen maps. The problem is only in the maps embedded in the HTML page.

**Comment by nboisteault** [comment]
@news24lor does this issue still occur ?

**Comment by news24lor** [comment]
Hi @nboisteault 

Now it works very well...
Thank you!

**Comment by nboisteault** [comment]
Thanks for the feedback.
