### ISSUE TITLE
impression quadrillée lors de la generation du pdf

### ISSUE THREAD

**Issue by lraes** [3liz/lizmap-web-client#824]
Bonjour,
Est-il possible d'enlever le quadrillage lorsqu'on génère une impression ?
Testé sur plusieurs viewer pdf mais le quadrillage est à chaque fois présent.
Merci

**Comment by rldhont** [comment]
Quelle version de Lizmap et de QGIS Server utilisez-vous ? Cette erreur a été corrigé dans les dernières version 3.* de lizmap.

**Comment by lraes** [comment]
J'utilise la version 2.18 de qgis server et 3.1 pour lizmap.
* Je suis sous Windows 10

**Comment by rldhont** [comment]
Avez-vous défini un quadrillage dans votre composition ?

**Comment by lraes** [comment]
non pas du tout.
je vais essayer d'installer la dernière version de LWC.

**Comment by lraes** [comment]
Bonjour,
Non car j'ai tout réinstallé (derniere version apache, php, et surtout lizmap)
ainsi je m'aperçois que les impressions ne sont plus quadrillées.
Merci
Cordialement

**Comment by nboisteault** [comment]
Parfait. Merci pour votre retour.
