### ISSUE TITLE
media in lizmap

### ISSUE THREAD

**Issue by adelchia** [3liz/lizmap-web-client#827]
I am using GGIS 2.14.22, QGIS server 2.14 and Lizmap 3.1.8.
The image put in photo subfolder of media folder aren't visible in popup (auto). I followed the instructions in:
https://docs.3liz.com/en/publish/advanced_lizmap_config.html#media-in-lizmap
In  popup window I only see the icon; if I see the path of icon,  it is:
http://192.168.1.113/lizweb/index.php/view/media/getMedia?repository=repo100&project=WG_centraline&path=media%2Ffoto%2Flamartella_2.jpg
where, after media, there are %2F instead slashes,  although the path in the attribute table of shape file is right.
How to solve it?
Tanks,
Adelchi

**Comment by rldhont** [comment]
If you change the IP or domainName, you have to clean the temp directory. To do so, just use:
```
lizmap/install/clean_vartmp.sh
```

**Comment by adelchia** [comment]
Ok, right!! Thanks to you I remember now  what I learned from Paolo Cavallini.
Wonderful!
I'll work there tomorrow.
Thank you very much
Adelchi
