### ISSUE TITLE
attribute table - misaligned columns

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#829]
hi

![imagem](https://user-images.githubusercontent.com/10053874/38358576-8cc6392a-38bd-11e8-9c96-f8cf92c16327.png)

![imagem](https://user-images.githubusercontent.com/10053874/38358635-b93a28ae-38bd-11e8-9187-d617251ef187.png)

thanks for your attention

**Comment by mdouchin** [comment]
@josemvm please try with last master after 4bf4951

**Comment by josemvm** [comment]
fixed! :-)
thanks @mdouchin
