### ISSUE TITLE
A request for enhanced safety

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#833]
In the embedded map I can make choices about what to show. The problem is that there is always a full-screen icon that I would not like to see.
Can I hide the icon 'Open the map in full screen'?

Thanks
![screenshot](https://user-images.githubusercontent.com/33484600/38727587-c20a4684-3f0d-11e8-82ef-342b9672494b.jpg)

**Comment by nboisteault** [comment]
Can you give us all the steps to reproduce your issue ?

**Comment by news24lor** [comment]
Hi @nboisteault 
My request is only for embedded maps: Lizmap inside a normal web page. The first two icon are right (layer and info). I want to hide the third icon, "Open the map in full screen", only hide. This option is not present inside Lizmap web client and Lizmap plugin. It's more safe.

Thanks

**Comment by nboisteault** [comment]
You mean you put Lizmap in an iframe ? Do you use this [script](https://github.com/3liz/lizmap-web-client/blob/55c0a869a7c8d610d91e1a0faf8fde8d81647488/lizmap/install/qgis/media/js/montpellier/toggleFullscreenViaLogo.js.example) ?

**Comment by nboisteault** [comment]
@news24lor 
Please reopen if issue still occurs.
