### ISSUE TITLE
Problem in printing baselayer OSM and Google

### ISSUE THREAD

**Issue by Andrea996** [3liz/lizmap-web-client#835]
Hi, we have a problem with printing.
We can not print Openstreet and Google baselayers
Do you know how to solve?

**Comment by rldhont** [comment]
How did you do to have this baselayers print ?
Which Lizmap Web Client version ?
Which QGIS Server version ?
Does the server need a proxy to acces external data ?

**Comment by gioman** [comment]
> Hi, we have a problem with printing.
> We can not print Openstreet and Google baselayers
> Do you know how to solve?

@Andrea996 you cannot print directly what in Lizmap you add as baselayers. You need to use a documented trick: use hidden (WMS) layers:

https://docs.3liz.com/en/publish/advanced_lizmap_config.html#allow-printing-of-external-baselayers
