### ISSUE TITLE
How to hide child tables from editing list

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#837]
In my project I have about 10 spatial layers which can be edited : parcelle, haie, mare, foret, muret and so one.
Once a abject is created in one of those layers, I had a child to describe the state of the drawn object, one line for one year.
To do that I need to make child tables writable which appear in the editing list. In the image below I would like to hide all tables begining with "suivi".
![editing_list](https://user-images.githubusercontent.com/1642645/39198319-0f41b856-47e7-11e8-8301-d6c8810710b3.png)

Is there a way to do it, am I wrong when I mark all child tables as editable ?

Mathieu

**Comment by nboisteault** [comment]
@mathieubossaert did you find a solution to your issue ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
