### ISSUE TITLE
Lizmap should display a message when tring to delete an objetc referenced in a child table

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#839]
Trying to delete an object, I get a success massage but the object reappears.
It is normal because I have foreign key between tables and the object is referenced in a "child" table.

On database side, I don't want to active "ON DELETE CASCADE" clause to avoid drama.

A good thing should be to catch the related error from the PostgreSQL Server server and to ask user to start by deleting child tuples before thez can delete the object.

**Comment by rldhont** [comment]
which lizmap version ?

**Comment by mathieubossaert** [comment]
3.1.1 I will test on a fresh update.

**Comment by mathieubossaert** [comment]
the message "The deletion has failed!" appears in lizmap 3.1.11.

**Comment by nboisteault** [comment]
Does issue still occur ?

**Comment by mathieubossaert** [comment]
As I don't have a more recent version I do think so. I plan to upgrade this winter.
