### ISSUE TITLE
Legend display problem

### ISSUE THREAD

**Issue by camillemonchicourt** [3liz/lizmap-web-client#842]
I installed Lizmap-web-client 3.2beta1 (Debian 9 with PHP7) and I am having a display problem of legends. 

They are OK in my QGIS project : 

![qgis-legend](https://user-images.githubusercontent.com/4418840/39784656-79749094-5319-11e8-97ca-2aa1a8b242d7.png)

But the legend image isn't displayed correctly in my Lizmap-web-client project (with Chrome or Firefox) : 

![lizmap-legend](https://user-images.githubusercontent.com/4418840/39784726-b49293ec-5319-11e8-99b2-58e177734a1e.png)

**Comment by rldhont** [comment]
It's a QGIS Server issue.
Is it the same for all your project ? Which QGIS server version do you use ?

**Comment by camillemonchicourt** [comment]
Yes it is the same on all my Lizmap projects. 
Not sure which version of QGIS server I am using but in Lizmap admin, it says : 

```
Version de QGIS Server | ≤ 2.14
```

It is on a Debian 9 server and I had some issues with installing QGIS server that I noted here : https://github.com/PnX-SI/Ressources-techniques/blob/master/Lizmap/install-debian9.rst

**Comment by Gustry** [comment]
Some fonts are missing on the server?

To know the QGIS Server version: 'apt cache policy qgis-server'should be enough I think.

**Comment by josemvm** [comment]
`apt-cache policy qgis-server` :-)

**Comment by camillemonchicourt** [comment]
Hum yes looks like a Font problem. 
``apt-cache policy qgis-server`` answers :

```
qgis-server:
  Installé : 1:3.0.2+14stretch
  Candidat : 1:3.0.2+14stretch
 Table de version :
 *** 1:3.0.2+14stretch 500
        500 https://qgis.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.11+dfsg-3+deb9u1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
```

**Comment by etrimaille** [comment]
Hum, you are already using QGIS 3 on your server. I haven't tried it yet.
Might be good to have a look on QGIS Server 2.18? Did you use lizmap plugin on QGIS 3 too?

**Comment by camillemonchicourt** [comment]
Oh OK, I didnt noticed that. I thought I was using QGIS server 2.18. 
I did my projects on QGIS 2.18, that's maybe why. I will try with QGIS 3 but I heard Lizmap is not yet ready for QGIS 3. 
Don't know how to change my QGIS server 3 to 2.18.
Thanks.

**Comment by Gustry** [comment]
I saw that about Lizmap on QGIS 3: https://github.com/3liz/lizmap-plugin/tree/master_3

You can uninstall everything I guess, change your APT repository to LTR and install qgis-server again.

**Comment by camillemonchicourt** [comment]
OK I should rather have used QGIS-server 2.18 indeed. But now that I am on QGIS-server 3 I will test with the QGIS 3 plugin. Thanks for the link.

**Comment by gioman** [comment]
From what I have seen from some quick test I also expect some issues when printing (GetPrint requests) with QGIS Server 3.

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
