### ISSUE TITLE
[Feature] QGIS layer action support - partial ?

### ISSUE THREAD

**Issue by TotalNoobOnGIS** [3liz/lizmap-web-client#844]
Would it be possible to run QGIS layer actions from lizmap ?

Then the actions like python commands and SQL query related processing would be enabled from the web (and executed on the QGIS server side)

Scenario in QGIS:
- by using identify tool user selects a layer object
- attribute table appears, with pull down menu containing a user defined layer actions
- user can run defined layer actions (like SQL queries etc.)

My (limited) use case
- User selects an object from lizmap canvas
- pop-up is displayed with list of layer actions (buttons)
- user can run the action in the context of select layer object 

By having this functionality one could e.g. add features and then run layer action which could modify postgres layers, do calculations on server etc.

**Comment by TecnostudiAmbiente** [comment]
Right now as a workaround I am using an action managed by qgis, I used a personal pop-up with some variables in lizmap. My problem was to recall a link to a page using a unique code that could be found inside the geographic data table present in the psql database. I hope however to see the qgis action integration in the next release of lizmap.

Example lizmap custom pop-up with variables:

```
<Html>
<Body>
<P> Button </ p>
<button onclick = "window.location.href = 'https: //xxxxxx/?parameter={$variable}'" target = "_blank"> Click Me </button>
</ Body>
</ Html>
```

**Comment by rldhont** [comment]
To support Actions in Lizmap, we need that qgis server supports actions or a way to execute actions in qgis server.

**Comment by mdouchin** [comment]
Related PR https://github.com/3liz/lizmap-web-client/pull/3343

**Comment by Gustry** [comment]
Can you try version 3.7 ? It has actions at the layer level now.
