### ISSUE TITLE
The geometry type does not match! Error

### ISSUE THREAD

**Issue by mathieubossaert** [3liz/lizmap-web-client#845]
Hi,

I face a bug I tried to understand by checking data in my PostGIS database... I Just want to edit PostGIS tables and for som of them, I can't save data because of this error message.
Here is my table definition. Table has been truncated.

```sql
CREATE TABLE saisie.bande_enherbee
(
    id integer NOT NULL DEFAULT nextval('saisie.objets_nid_seq'::regclass),
    login text COLLATE pg_catalog."default",
    nom text COLLATE pg_catalog."default",
    id_parcelle integer,
    geometrie geometry(LineString,2154),
    CONSTRAINT bande_enherbee_pkey PRIMARY KEY (id),
    CONSTRAINT bande_enherbee_id_parcelle_fkey FOREIGN KEY (id_parcelle)
        REFERENCES saisie.parcelle (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
```

Do you have any idea ? 

Huge thanks :-)

Mathieu

**Comment by mathieubossaert** [comment]
Seems to be relative to this function but I can't find the problem.

https://github.com/3liz/lizmap-web-client/blob/ae24ae5b86a048cbce5acee536350c07c111b514/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L346

**Comment by mdouchin** [comment]
What is the error message please ?

**Comment by mathieubossaert** [comment]
Hi @mdouchin,

"**The geometry type does not match!**". appars when I try to save the new feature.

**Comment by mdouchin** [comment]
Do you have the query written in your `lizmap/var/logs/error.log` ? If so, you could try to copy paste that in your SQL tool and investigate further

**Comment by mathieubossaert** [comment]
I do not have any message relative to this problem. Logs are "on" but nothing appears, neither on the database side...

**Comment by mathieubossaert** [comment]
Maybe my logs are not well configured...

**Comment by mdouchin** [comment]
it must an error inside Lizmap, not related to a wrong SQL syntax. Can you paste here the datasource of your layer ( from the General tab of the layer properties dialog)

**Comment by mathieubossaert** [comment]
here it is : 
dbname='ecodiag' host=192.168.1.119 port=5432 user='dba' sslmode=disable key='id' srid=2154 type=LineString table="saisie"."bande_enherbee" (geometrie) sql=

**Comment by mathieubossaert** [comment]
L'erreur est renvoyée ici contrairement à ce que j'ai mentionné plus haut : https://github.com/3liz/lizmap-web-client/blob/d914f17d5e372ed6c3e7f4eb0a3bd046e2404dc5/lizmap/modules/lizmap/controllers/edition.classic.php#L961

$value contient ceci  : 
`ST_GeomFromText('LINESTRING(750326.904363714 6294367.941679799,749420.3447046095 6290004.405641499,753965.9347403175 6289268.980299428,754887.0873179653 6291593.595401786,753593.8161612587 6294008.731652429)', 2154)`
et $rs ligne 963 ceci : 
`LINESTRING`

**Comment by mathieubossaert** [comment]
Found but not yet solved : error is due to another table with the same name in another schema with generic geometry(geometry,2154) column.

https://github.com/3liz/lizmap-web-client/blob/d914f17d5e372ed6c3e7f4eb0a3bd046e2404dc5/lizmap/modules/lizmap/controllers/edition.classic.php#L427

**Comment by rldhont** [comment]
It's necessary to test `f_table_schema`as we do it for views' primary keys, isn't it @mdouchin ?
