### ISSUE TITLE
Error during registration of an external visitor

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#853]
Hi

Thanks for all bugs resolved: I can install Lizmap.

Now I have a problem with an external visitor.
When the visitor enters his information for registration and presses 'Create an account' there is an error of type 500 in the server ( Error 500. A technical error has occured ) and the lizmap log has this information:

> 018-05-18 12:17:09	xxx.xxx.xxx.xxx	error	2018-05-18 12:17:09	[17]	
> The selector "jcommunity~mail_registration" does not match the resource of the type : "template"	.../maps/lib/jelix/core/selector/jSelectorTpl.class.php	101

In the user list, the new visitor is present with all the data and there is the activation flag waiting for the email validation. No emails were sent.

Thank you

**Comment by rldhont** [comment]
the template `jcommunity~mail_registration` is only available in en_US and fr_FR. So what is your config for:
* `availableLocales`
* `fallbackLocale`

The `fallbackLocale` is defined in the lizmap sources to `en_US`. In the case if a lack of translation or template localized, the `en_US` is used.

**Comment by news24lor** [comment]
I already use this language. In mainconfig.ini.php I have:

locale=en_US
charset=UTF-8

Where is the error?

**Comment by news24lor** [comment]
I checked for these 2 variables and tried to change them in the file lizmap/var/config/mainconfig.ini.php:

> availableLocales="fr_FR,en_US,en_US,ex_ES,eu_ES...." 
> availableLocales="fr_FR,en_US"
> 

The other variable is always set to en_US.

The error remains and is always the same.

**Comment by rldhont** [comment]
It's not explain in the lizmap documentation, but you don't have to update the `mainconfig.ini.php`. If you need to update variables, you can do it in `localconfig.ini.php`.

What is your `fallbackLocale` variable ?

**Comment by news24lor** [comment]
This variable is not present in the file `localconfig.ini.php`.
I have inserted it:

> fallbackLocal = en_US

I restarted and now I have the layout in English, better because before it was in Italian and there were problems, for example with the question below "Are you human?" wanted answers in English while with answers in Italian there was always error.

I tried to create a new visitor user and the previous error disappeared and asks me to wait for the validation email sent.

Unfortunately the validation email did not arrive and I would like to know where to set up the configuration for sending the email in lizmap.

**Comment by news24lor** [comment]
Now it works with these changes.

I have insert in `localconfig.ini.php`

> fallbackLocal = en_US

I have modified `mainconfig.ini.php`

> availableLocales="fr_FR,en_US"

Optional for smtp:
> mailerType=smtp
> smtpHost=xxxxxxx.xxxxxxx.xx
 
Now the email arrives and after the 'admin' give the validation to the new user.

It's a bit difficult but it works

**Comment by news24lor** [comment]
Rectification: with the changes reported before the email arrives regularly to the visitor who can validate his account directly.
I also confirm that, although the application is multilingual, in practice the function `jcommunity~mail_registration` for registration is only in French and English (the question of "Are you human" can only be answered in English and French and any other language by mistake) and this requires one of these two languages if you want to have all the functions.
The "Are you human?" function could be replaced with the CAPTCHA function, which is not language-dependent.

**Comment by rldhont** [comment]
@news24lor do not change `availableLocales=` in `mainconfig.ini.php`.

Your report probably means that the documentation is not up to date and we have to update the loacales to translate.

**Comment by news24lor** [comment]
Yes I know.
This is a only temporary solution for me. I'll change it.

In normal use all languages are fine. The layout in the own language is great. The administrator can also create as many users as he wants.
The problem is only with external visitors, not English or French, who register: that module "Are you human? is not translated and causes errors.

**Comment by laurentj** [comment]
This is a bug in Jelix. The fallbackLocal parameter is not taken account to retrieve a template. The template must exists in all supported language by the application. Or it should exists for all languages, i.e. not in a language directory.

I'll fix that.

**Comment by laurentj** [comment]
Documentation has been improved about configuration files and localization settings: https://docs.3liz.com/en/install/configuration.html
