### ISSUE TITLE
problems with viewing in google chrome

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#854]
Hello,
I noticed that a project opened with Firefox the order of the layers display is correct, but the same project opened with google chrome is different.
In short, if a layer placed above all as in the qgis project when it is opened with Firefox the display is correct while instead on chrome others are displayed above it.
Thank you

**Comment by rldhont** [comment]
Can you provide screenshors: FF, Chorme and QGIS ?
Which lizmap web client is concerned ?

**Comment by morvan80** [comment]
screenshors: FireFox
![firefox](https://user-images.githubusercontent.com/35898831/40486049-7aa29972-5f60-11e8-8d74-6339d70df950.jpg)
screenshors: Chrome
![chrome](https://user-images.githubusercontent.com/35898831/40486074-8f10cd66-5f60-11e8-8b8f-609e7a4b73b8.jpg)
"See the CATASTALI layer with FF is positioned above all, inveco son chrome is positioned in the middle of other layers. "of course the images refer to the same project."

LIZMAP 3.1.11


THANK YOU

**Comment by rldhont** [comment]
Are you able to reproduce the issue in other projects or in a simple one ?
Is the order of layer is inverted in chrome ?
Do you use in the QGIS Project configured layer order, the layer tree order is different than the map layer order ?

**Comment by morvan80** [comment]
Salve,
Il problema si conferma su tutti i progetti.
L'ordine dei livelli su Fire Fox e Explorer sono corretti in base alla mappa di qgis, mentre su chrome risulta diverso come in foto.
No l'ordine dei layer è uguale nel progetto qgis a quello che viene visualizzato in lizmap, il problema e che in chrome pur essendo sopra a tutti "Catastali" vengono sovrapposti altri layer.
Grazie

**Comment by rldhont** [comment]
@morvan80 can you provide an access to the map ?

**Comment by morvan80** [comment]
www.sitland.eu

**Comment by rldhont** [comment]
@morvan80 can you update your lizmap-web-client to 3.1.12 ?

**Comment by morvan80** [comment]
the use i use is 3.1.12

**Comment by rldhont** [comment]
@mdouchin: @SenequeC has reproduced it. To soleve it we need to provide the right order from project.

**Comment by rldhont** [comment]
I will probably have a solution but needs to be tested on projects to avoid regression.

**Comment by morvan80** [comment]
Hi, I have updated to version 3.1.13 but the problem persists.
Thank you

**Comment by rldhont** [comment]
@morvan80 it seems that your QGIS server as some issues:
```xml
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException>
</ServiceExceptionReport>
```

**Comment by morvan80** [comment]
after updating to version 3.1.13 and updated the https certificate did not work properly anymore, now I have reset everything to version 3.1.12 and it works all regularly.
