### ISSUE TITLE
lizmap 3 support for QGIS 3 desktop and server

### ISSUE THREAD

**Issue by dassau** [3liz/lizmap-web-client#857]
Hi,

does lizmap 3 support QGIS 3 desktop and server. Would you think it can be used in a professional environment already? And is the lizmap plugin already available for QGIS 3?

Reason is, I would like to use some new QGIS 3 server features together with the lizmap client.

Thanks a lot for your assessment
Otto

**Comment by Gustry** [comment]
Just giving some links:
Have a look to this issue: https://github.com/3liz/lizmap-plugin/issues/91
And this branch for the plugin: https://github.com/3liz/lizmap-plugin/tree/master_3

**Comment by pcav** [comment]
Should this be closed?

**Comment by nboisteault** [comment]
See #1075 for reference.
