### ISSUE TITLE
OSM nominatim search problem - ?http / https ?

### ISSUE THREAD

**Issue by TotalNoobOnGIS** [3liz/lizmap-web-client#858]
Search in my lizmap setup stopped working. (nominatim with OSM)
And so did the QuickFinder plugin in QGIS.
Was not able to search locations using nominatim.

**I was able to get Quickfinder working in QGIS desktop 
by setting a plugin service setting from http:// to https://**
I would have tried the same for lizmap - not able to figure out how ... :(

Any help appreciated

Lizmap setup i have, is not configured for SSL. Plain http used while viewing "lizmap" maps
Qgis2.18.18, lizmap3.2pre,php-7.2,Apache2.4.33

**Comment by nboisteault** [comment]
I have the same problem.

**Comment by Gustry** [comment]
Same problem. I made the PR above to fix the problem, it's working fine now.

**Comment by TotalNoobOnGIS** [comment]
Did that change to that file. No success for me... 

Is there some additional things one should do after the modification. 

Or is there dependencies related eg. Ssl enable from apache or php or ?

**Comment by nboisteault** [comment]
Did you check your firewall ?
You can try wget on some https url to debug.

**Comment by Gustry** [comment]
Maybe try with CURL on your server to see what is happening? Lizmap is using curl for the Nominatim request : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/controllers/osm.classic.php#L41

Nominatim switched to HTTPS for all requests: https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html

**Comment by rldhont** [comment]
fixed by 17f326889612a6870eb9491a62d985cb59a755c4

**Comment by TotalNoobOnGIS** [comment]
**Thank you @Gustry to point me to the right direction.**

In my case 
commit #860 was not enough.

As my setup is operating in internal network i havent use https before on this server.
PHP CURL was present ok
But without proper certificate stuff to verify remote end certificates

After few failed attempts to configure those, i gave up and
**for this specific purpose i did totally disable PKI-security** enbling man-in-the-middle etc.
in OSM_classic.php by adding these below line 41
curl_setopt($curl_handle, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curl_handle, CURLOPT_SSL_VERIFYPEER, 0);

i was able to get my setup functioning.

On my opinion correct fix for this bug should also include correct cert usage e.g. by using curl_setopt
