### ISSUE TITLE
problem with displaying symbol svg for point layer

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#861]
Hi,

Sometimes Lizmap displays symbols svg, sometimes not.
It doesn't seem to depend on scale or position.

![image](https://user-images.githubusercontent.com/32867483/40494170-823ccf4a-5f74-11e8-9bbb-1cd0f867af1c.png)

![image](https://user-images.githubusercontent.com/32867483/40494198-91eb3d1e-5f74-11e8-8762-2d1b211da62d.png)

Thanks.

MFANGAIN

**Comment by rldhont** [comment]
It's a known QGIS Server issue.

**Comment by igeofr** [comment]
I have the same problem, is there an alternative? 
Thanks

**Comment by nboisteault** [comment]
@rldhont still a QGIS Server issue ?

**Comment by Gustry** [comment]
This has been fixed in QGIS 3.10 https://changelog.qgis.org/en/qgis/version/3.10/#qgis-server-renders-svg-correctly

I'm closing as it should be fixed. Reopen a ticket if necessary.
