### ISSUE TITLE
List of issues according to QGIS Server version

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#863]
According to other issues #859, #862, and some personal experiences, is-it possible to have a kind of wiki page of known bugs for QGIS 2.14, 2.18, 3.X ?

I'm currently setting up a new lizmap instance and it's difficult to make a choice between these QGIS versions. It would be nice to know which bugs are known when we use a specific QGIS version.

A kind of list like this:
* 2.14 : 
* 2.18 :
  * Delete impossible on PostGIS with lizmap 3.1.11 #859
  * Info popup is ok but clicking on edit button opens the form for another feature #862
* 3.0 : 
  * Composer/layout is broken [#857](https://github.com/3liz/lizmap-web-client/issues/857#issuecomment-391381361)
* 3.2 :
  * Same as 3.0 I think, related to LWC version

For instance, some users might not be bothered by no deletion on Postgis using 2.18 so no need to downgrade to 2.14.
And for my use case, my lizmap instance will be on production not before January 2019, so I may expect to have QGIS 3 mature enough in the mean time.

Can I start a wiki page and everyone try to contribute to this list? Any thoughts?

**Comment by rldhont** [comment]
Hi @Gustry 

QGIS 2.18 is recommended. 
* Delete impossible on PostGIS with lizmap 3.1.11 #859 has to be fixed in QGIS Server 2.18 
* Info popup is ok but clicking on edit button opens the form for another feature #862 is due to the way QGIS (not especially QGIS Server) is defined and managed FeatureID. A FeatureID has to be an integer, so if you use integer, no bigint or other type, you will have no issue. It is also an issue with 3.* and it's not an easy way to fix.

**Comment by mathieubossaert** [comment]
>  so if you use integer, no bigint or other type, you will have no issue
Do you mean the type of the primary key in PostGIS ? Because my primary keys serial are integer.

**Comment by rldhont** [comment]
If in QGIS, the type is QLongLong, it's not a simple integer and we have an issue.

**Comment by mathieubossaert** [comment]
Sorry @rldhont  but in the attribute panel, type is int, and I c'ant find Qlong or Qlonglong in the qgs file.

**Comment by Gustry** [comment]
Ok, thanks for your inputs.

**Comment by gioman** [comment]
@Gustry I find very bad the following two regressions in QGIS Server 2.18 (one is really in Desktop, but is affecting directly Server):

1) in print composer is not possible anymore to add a legend that is not linked to a specific map object, this made impossible to do GetPrint requests producing a legend that is "fixed" (so does not depend on what layers are listed in the request). This option has been arbitrarily removed from QGIS Desktop 2.18 with no previous discussion or warning (it was removed within the 2.18 development, the first point releases were still ok)

2) possibly as consequence of 1) (not sure) now legends out of GetPrint requests show a not very nice "?" for layers that have not been part of the request

![screenshot_20180530_112712](https://user-images.githubusercontent.com/1951107/40715129-7f1980ba-63fc-11e8-91f5-ad1193d629dc.png)
