### ISSUE TITLE
Error messages from Lizmap logs

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#864]
### What is the bug?
These types of errors are reported by the Lizmap logs and give useful information.
Analyzing 'lizmap/var/log/messages.log' I always found this line indicating an error:

```
...default Error while inserting a new line in log_detail :invalid query (no such column: now (INSERT INTO log_detail (
log_key,log_timestamp,log_user,log_content,log_repository,log_project,log_ip
) VALUES (
viewmap', now, '', NULL, 'projectAJK', 'projectAJK', NULL
)))

```

Analyzing 'lizmap/var/log/error.log' instead, I have found these messages many times:

```
warning	2018-05-25 15:01:19	[2]	SQLite3::exec(): no such column: now	.../lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	120

warning	2018-05-25 15:01:20	[2]	file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0	.../lizmap/modules/lizmap/classes/lizmapProxy.class.php	109

warning	2018-05-25 15:01:20	[2]	file_get_contents(http://..../qgis_mapserv.fcgi?service=WMS&amp;request=GetCapabilitiesAtlas): failed to open stream: no suitable wrapper could be found	.../lizmap/modules/lizmap/classes/lizmapProxy.class.php	109

notice	2018-05-25 15:01:20	[8]	Undefined variable: http_response_header	.../lizmap/modules/lizmap/classes/lizmapProxy.class.php	113

warning	2018-05-25 15:01:20	[2]	Invalid argument supplied for foreach()	.../lizmap/modules/lizmap/classes/lizmapProxy.class.php	113
```

These are warning or notice messages, but they are more or less errors. Some of these are just alerts and do not cause problems but others do. 
 

### Steps to reproduce the issue

I almost always find these error messages

### Expected behavior

Most of these messages should not be there

### Environment

 - Lizmap version: last GitHub version
 - QGis version: 2.18.17
 - OS: Mac OS 10.11
 - Browser: Safari, Firefox, Chrome
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? Sqlite

**Comment by rldhont** [comment]
Issue introduced by b2d81bc882297236e3b07bdf41b5447c624729cc
