### ISSUE TITLE
A new error in the latest release

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#866]
### What is the bug?
I installed the latest version from GitHub but I have a new error at the start, not present before:
'Error in the main configuration. A plugin doesn't exist'

### Steps to reproduce the issue

At the beginning

### Expected behavior

No error at the start

### Screenshots and logs
This is the 'errors.log'

array ( )

```
	0	trigger_error()	.../lib/jelix/core/jConfigCompiler.class.php : 431
	1	jConfigCompiler::_loadPluginsPathList()	.../lib/jelix/core/jConfigCompiler.class.php : 137
	2	jConfigCompiler::prepareConfig()	.../lib/jelix/core/jConfigCompiler.class.php : 85
	3	jConfigCompiler::read()	.../lib/jelix/core/jConfigCompiler.class.php : 103
	4	jConfigCompiler::readAndCache()	.../lib/jelix/core/jConfig.class.php : 89
	5	jConfig::load()	.../lib/jelix/core/jApp.class.php : 145
	6	jApp::loadConfig()	.../lizmap/www/index.php : 17
2018-05-30 16:02:53	192.168.55.12	[7]	Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown.	.../lib/jelix/core/jConfigCompiler.class.php	172
	/roveri/
array ( )

	0	jConfigCompiler::checkCoordPluginsPath()	.../lib/jelix/core/jConfigCompiler.class.php : 138
	1	jConfigCompiler::prepareConfig()	.../lib/jelix/core/jConfigCompiler.class.php : 85
	2	jConfigCompiler::read()	.../lib/jelix/core/jConfigCompiler.class.php : 103
	3	jConfigCompiler::readAndCache()	.../lib/jelix/core/jConfig.class.php : 89
	4	jConfig::load()	.../lib/jelix/core/jApp.class.php : 145
	5	jApp::loadConfig()	.../lizmap/www/index.php : 17

```
### Environment

 - last GitHub version: 
 - QGIS 2.18.17:
 - mac OS 10.11 
 - All browsers:
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?  Sqlite

**Comment by laurentj** [comment]
Hi,

We already had this kind of report, but I never succeded to reproduce the issue.

>At the beginning

This is not a useful response sorry :) Since the error appear "at the begining", please describe what you did to install lizmap: did you change some configuration file, what did you change etc...

And "latest github version" is not useful too: we have 4 "github version", one for each branch (master, 3.2, 3.1, 3.0). Which branch please?

It seems also some few lines are missing at the start of your log

**Comment by news24lor** [comment]
The log is complete without the first part of the path.
I have download the master version of 20150529.
I have made all steps like previous versions for installing, master of 20150518 and previous.
The master version of 20150518 worked.
The master version of 20150529 does not work and has this new error.

**Comment by laurentj** [comment]
>20150529

Is this a date? If yes, did you mean instead **2018**0529?

**Comment by news24lor** [comment]
Yes, sorry

**Comment by laurentj** [comment]
>I have made all steps like previous versions for installing

Full reinstall? or only an update? Which steps please? 

I really need **your** list of steps to try to reproduce your issue: what you have done exactly, commands after commands, from the unarchive step to the step before the launch of your browser. And what was the initial context: did you restore your previous configuration files or not, did you start from cleaned files etc.. 

I need some details, because we install and update lizmap instances everyday and we don't have this issue. And I would like to understand why you and some other users have this issue.

I know that it could take time to list these steps, and it could be boring, but it could help us very much. 
Thank you :-)

**Comment by news24lor** [comment]
Hi @laurentj 

It's a full reinstall from master, downloaded from GitHub

I have followed step by step the install file [https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md](url)

I have tested two master, before and after, and the problem is from the installer.php

MASTER of 20180518 - Lizmap works
This is the output from terminal of installer.php

```
$ sudo php lizmap/install/installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module proj4php installed
All modules are installed or upgraded for the entry point index
[notice] Installation starts for the entry point admin
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module proj4php installed
All modules are installed or upgraded for the entry point admin
[notice] Installation starts for the entry point script
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module proj4php installed
All modules are installed or upgraded for the entry point script
Installation ended.
$
```


MASTER of 20180529 - Lizmap doesn't run
This is the output from terminal of installer.php

```
$ sudo php lizmap/install/installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
$ 
```

Many modules are missing from the installer

**Comment by manasa-maddi** [comment]
I got this error when i upgraded the jelix version from 1.3 to 1.6
 Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown.
