### ISSUE TITLE
png 8bit output

### ISSUE THREAD

**Issue by lionelbargeot** [3liz/lizmap-web-client#87]
Hi, 

I have a qgis project perfectly working with default png image format,  with qgis 2.4 and a fresh lizmap web-client install (master branch, 20 aout 2014).
I would  like to use a png 8bit image format to optimize tile downloads. So I configure the option in lizmap plugin : format=image/png; mode=8bit.
I upload the project config, I reload the map and the legend and the map content does not appear. I have the following error in apache log
[Tue Aug 26 16:06:04 2014] [warn] [client 192.168.1.2] mod_fcgid: stderr: 2014-08-26 16:06:04\t192.168.1.2\tnotice\t2014-08-26 16:06:04\t[8]\tUndefined offset: 0\t/var/www/lizmap-web-client-master/temp/lizmap/www/compiled/templates/modules/view/map_html_t.php\t12, referer ...
The only change is the project.qgs.cfg file.
The only changing line is :             "imageFormat": "image/png; mode=8bit", 

Could it be a ";" problem ?
Thanks
Lionel

**Comment by rldhont** [comment]
Hi, the problem probably comes from your color choices. Do you confimr it ?

**Comment by nboisteault** [comment]
Maybe a feedback label should be created for this kind of issue.
