### ISSUE TITLE
Filter a non spatial layer doesn't filter related layer with cascading

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#872]
It is not possible to filter a non spatial layer and have a related layer filtered with cascading.
 - Lizmap version: master

I've seen this in code : 
[lizmap 3.0 and 3.1](https://github.com/3liz/lizmap-web-client/blob/release_3_0/lizmap/www/js/attributeTable.js#L2223)
[lizmap 3.2](https://github.com/3liz/lizmap-web-client/blob/release_3_2/lizmap/www/js/attributeTable.js#L2340)

The comment says : 

> comment this to allow non spatial layers to trigger filters for children layers

comment out or uncomment this code part does not change behaviour.

**Comment by rldhont** [comment]
@nboisteault do you mean that 3.2 do the works and not 3.0 and 3.1 ?

**Comment by nboisteault** [comment]
I've just tested master 'live' but the only difference I see in `updateMapLayerDrawing` between those versions is the commented out part. I've tested master with this part uncomment as suggested but that doesn't change behaviour.

**Comment by nboisteault** [comment]
OK I realized that I forgot to create the second relation to make filter working both sides, the behaviour is correct now. @rldhont : nevertheless parts of the code we talked about by phone should be looked more deeply as they might cause other issues.
