### ISSUE TITLE
Lizmap 3.1.11 : search by address (nominatim or google) don't work anymore

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#876]
### What is the bug?
Any result when searching an address : 
![image](https://user-images.githubusercontent.com/32867483/41031337-a89eff94-6980-11e8-9900-e501b04c0a65.png)

### Steps to reproduce the issue

1. Enter an address
2. Enter
3. nothing happens
4. Click on "close" don't work either

### Screenshots and logs

development tools display this error :
![image](https://user-images.githubusercontent.com/32867483/41031425-e0d0192a-6980-11e8-9c29-8efdae9490b9.png)

### Environment

 - Lizmap version: 3.1.11
 - QGis version: 2.18.18
 - OS (windows, linux, macOS, android..): windows
 - Browser (Firefox, Chrome...): Firefox, Internet explorer
 - Lizmap data stored into Postgresql

**Comment by Gustry** [comment]
Are you sure it happens with google too?
In your screenshot, we can read 'Nominatim' and it's already fixed: https://github.com/3liz/lizmap-web-client/issues/858

**Comment by mfangain** [comment]
I see the same problem with google, but indeed the error is different : 
![image](https://user-images.githubusercontent.com/32867483/41094577-000382ea-6a4f-11e8-9719-81f90383c728.png)

So I'm waiting for version 3.1.12 ;-)

Thanks!

**Comment by Gustry** [comment]
3.1.12 has been released already:
https://github.com/3liz/lizmap-web-client/releases/tag/3.1.12
