### ISSUE TITLE
Editing PostGIS layer does not work

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#878]
### What is the bug?

In a my test I've seen that the editing of PostGIS layer does not work in last master of Lizmap (20180605).
It's also impossible to view the whole table of data of PostGIS layer.

The editing of a Spatialite layer works very well

### Steps to reproduce the issue

I view PostGIS layer on Lizmap and I view the attribute of that object.
When I select the editing button there is an error:

`2018-06-07 16:38:41	192.168.45.185	error	2018-06-07 16:38:41	[402]	error during localhost connection	.../lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php	144
` 
I have no other errors in PHP

### Expected behavior

The possibility of editing

### Environment

 - Lizmap version: master of 20180605
 - QGis version: 2.18.17
 - OS (windows, linux, macOS, android..): macOS
 - Browser (Firefox, Chrome...): all
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?  Postgresql

**Comment by rldhont** [comment]
Is the layer accessible through localhost for lizmap ?

**Comment by news24lor** [comment]
Hi @rldhont 

Yes, it is in localhost.

In QGIS, PostGIS layer works and I see the data.
In Lizmap the same layer does not work with an error in jelix plugin

**Comment by rldhont** [comment]
Can you take a look at the lizmap log ? `lizmap/var/log/error.log`

**Comment by news24lor** [comment]
Hi @rldhont 

The only error is this one inside error.log

```
2018-06-18 19:40:48	192.168.63.20 error	2018-06-18 19:40:48
[402]	errore durante la connessione localhost	.../lib/jelix/plugins/db/pgsql/pgsql.dbconnection.php
144

```

And also in Lizmap it's impossible to view the relation data of a pg layer.
I see only the data of pg layer

The error is the same, the jelix driver.

I use PostgreSQL 10.4 and Postgis 2.4.4

**Comment by nboisteault** [comment]
@news24lor 
Does issue still occur ?

**Comment by news24lor** [comment]
Thanks! I try with the last version
