### ISSUE TITLE
One request is a wrong URL

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#880]
### What is the bug?

When I load the main lizmap map http://localhost:8082/index.php/view/map/?repository=papillon&project=projet_218 one request leads to a 404 after a very long time:

![screenshot from 2018-06-07 16-53-49](https://user-images.githubusercontent.com/1609292/41125848-ab8c550a-6a73-11e8-97c5-89a92a967e0b.png)

```
GET /themes/default/css/img/logo_footer.png HTTP/1.1
Host: lizmap:8082
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8082/index.php/view/map/?repository=papillon&project=projet_218
Connection: keep-alive
```

My firefox tab is still spinning until the request is finished.

### Expected behavior

This request shouldn't lead to `http://lizmap:8082` which doesn't exist. It should use my default path `localhost:8082`.

### Environment

 - Lizmap version: 3.2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): Linux
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? Postgresql

**Comment by rldhont** [comment]
Is it the only one link with this host name error ?
Can you clean the lizmap temp directory ?

**Comment by rldhont** [comment]
@Gustry have you clear the lizmap temp directory ?

**Comment by Gustry** [comment]
Sorry I forgot to check. I will do ASAP.
BTW I'm not sure about will lizmap temp directory.

**Comment by rldhont** [comment]
use the `clean_vartmp.sh` script.

**Comment by Gustry** [comment]
I don't have the same setup using a port http://localhost:8082/ and I can't reproduce right now. I will check again this ticket if it occurs again. Thanks.
