### ISSUE TITLE
[3.3pre] Error running set_rights.sh - temp/lizmap not exists

### ISSUE THREAD

**Issue by GohanSSj2** [3liz/lizmap-web-client#882]
Hi,

When i install LWC 3.3pre, an error occure when I run command line "lizmap/install/set_rights.sh www-data www-data".
lizmap/install/../../temp/lizmap not exists.

I create directory lizmap-web-client-master/temp/lizmap and  script runs correctly.

Folder ./temp/lizmap exists in 3.1.12 version.

**Solution :**
create the directory in project or change `$SCRIPTDIR/../../temp/lizmap` by `$SCRIPTDIR/../../temp` in line 16 of the file [set_rights.sh](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/set_rights.sh)

thank you for your work!

**Environment**
OS : Debian Stretch
Lizmap version : 3.3pre

**Comment by rldhont** [comment]
Has been fixed by 447873a989a07e0ee5da8c8e20ed06f2d9eb72af and the commit b9fff6f29ab9b0ac7046ae7eda72748d5d168ba7 does prevent to come back.
