### ISSUE TITLE
Activate tooltip automatically

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#883]
hi,
has someone been able to automatically activate the Tooltip command for a chosen layer with js?
If the function like many users of lizamap  we could organize a fundraising... 
Thanks
Roberto

**Comment by nboisteault** [comment]
@robibrazze something like this ?
```javascript
$('#button-tooltip-layer').click();
$('#tooltip-layer-list').val('YOURLAYERVALUE').change();
```

**Comment by nboisteault** [comment]
@robibrazze Reopen if needed.
