### ISSUE TITLE
Jelix as a submodule ?

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#884]
### Is your feature request related to a problem? Please describe
Is-it possible to switch to a git submodule for jelix?

It would make it much easier I think for me to have the git source tree of jelix inside lizmap instead of having a static copy of Jelix. It would allow developers to make patches to Jelix straight from the lizmap environment.

Just a question. Feel free to close if it's not possible.

Thanks

**Comment by laurentj** [comment]
I already work with git sub modules on some project, this is too complex. This is a complex command, so a complex workflow. Developers should know well this command (and this is not the case for most of them) else it is easy to break something. It would complexify too our continuous integration, the build of Docker images etc...

A best solution is to use Composer (package system for PHP). The upcoming Jelix 1.7 will be provided as a Composer package so we could remove Jelix from the Lizmap repository. We will migrate to Jelix 1.7 into the lizmap master branch soon.
