### ISSUE TITLE
Use the default expression value in calendar field

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#888]
### Describe the solution you'd like

In QGIS Desktop on the right panel, I put the default expression `now()`. It would be nice if Lizmap could follow the expression too by having the date of the day:

![screenshot from 2018-06-12 15-24-30](https://user-images.githubusercontent.com/1609292/41312325-be8c94a0-6e54-11e8-805c-737f69156a8c.png)

**Comment by josemvm** [comment]
![imagem](https://user-images.githubusercontent.com/10053874/41461380-76261292-7087-11e8-847d-4c58cd402150.png)

https://github.com/3liz/lizmap-web-client/issues/828

**Comment by RobiFag** [comment]
Hi all! I have the same issue with a text edit field. I added the expression maximum(  "id"  )  + 1 in order to create a kind of serial field but it doesn't work on Lizmap.

**Comment by Gustry** [comment]
@RobiFag Your issue must work with LWC 3.4 and Lizmap plugin Server side. Are you trying with this setup ?

We should be able to close this issue, it's now supported.

**Comment by RobiFag** [comment]
Hi @Gustry! I tried with lizmap 3.4 but maybe I missed something on server side (https://www.3liz.com/blog/rldhont/index.php?post/2020/11/24/Evaluate-QGIS-Expression-server-side-with-Lizmap-plugin). I have to talk about this with @rmarzocchi84 who managed the server! Thanks for the hint!

**Comment by Gustry** [comment]
Reopen a new ticket if necessary.

**Comment by rmarzocchi84** [comment]
Thanks @Gustry! To install on the server side the instruction is the same of other qgis server plugins (e.g atlas print, WFSexport, etc.) ?
