### ISSUE TITLE
Long unibloc attribute value

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#891]
### What is the bug?

Very long Attributes values without space are out of the box. I have to keep the no-space

### Steps to reproduce the issue

1. Go to 'Pop Up'

### Expected behavior
Return to the line 
By example on a _non_ alpha numeric character

### Screenshots and logs
![image](https://user-images.githubusercontent.com/402354/41346265-492c837a-6f06-11e8-979c-cea900f9969d.png)

### Environment

 - Lizmap version: 3.2beta2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): Ubuntu 16.04
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? PG

**Comment by nboisteault** [comment]
@jlstanus 
Does issue still occur ?

**Comment by jlstanus** [comment]
I cannot test anymore. sorry
