### ISSUE TITLE
The 'Change your password' button has disappeared

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#893]
### What is the bug?
In the last GitHub version (20180614) the 'Change your password' button in disappeared

In previous versions there has always been the button to change the default password

### Steps to reproduce the issue

Install last GitHub version (20180614). Enter in Lizmap and press Login button. The first time enter: 
user: admin
pw:   admin

Enter the administration area and at top right under admin press 'Your Account'.
Under the administrator's profile, there is only the 'Edit your profile' button, but the 'Change your password' button has disappeared.

Of course it is impossible to change the 'admin' default password.

### Expected behavior

The return of 'Change your password' button to change the default password

### Environment

 - Lizmap version: GitHub version (20180614) 
 - QGis version: 2.18.20
 - OS (windows, linux, macOS, android..): linux, macOS
 - Browser (Firefox, Chrome...): all
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? Sqlite

**Comment by rldhont** [comment]
You can reactivate it by changes the group rights for admins and users

Before:
![screenshot-2018-06-26-17-46-administration](https://user-images.githubusercontent.com/1575538/41923935-1402e474-7969-11e8-878e-254fee4f0d7a.png)

After:
![screenshot-2018-06-26-17-47-administration](https://user-images.githubusercontent.com/1575538/41923958-200f35a6-7969-11e8-9465-191fe9fd70dc.png)

**Comment by rldhont** [comment]
@laurentj do you think we can update it by default ?

**Comment by rldhont** [comment]
@laurentj no need to install ldap authentication to have, password change disabled.

**Comment by laurentj** [comment]
ok i found it : the ldapdao module is always enabled in fact :-/. A fix is coming.

**Comment by laurentj** [comment]
This issue is fixed, the button is back. But there is an other issue related to this button when ldap is enabled, issue #909

**Comment by laurentj** [comment]
When updated Lizmap, be sure that there is no "ldapdao.access=2" and no "jauth.access=2" into index/config.ini.php, admin/config.ini.php, cmdline/scripts.ini.php and mainconfig.ini.php (anyway, in a normal update, these files should be overwritten by those provided by lizmap). Check also localconfig.ini.php.
