### ISSUE TITLE
edit attributes of Big geometry returns an error

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#894]
### What is the bug?
When try to edit attributes of complex geometries, this cannot be commited. Click on the save button returns an error.

### Steps to reproduce the issue

1. Go to [test site](https://www.gate-16.xyz)  with usr : test and pwd testtest
2. Click on 124652 spatial object
3. Edit this object from the popup and add any value
 * error	An error has been raised when saving form data edition to db : Erreur dans la requête (ERROR:  value too long for type character varying(254)
* An error has been raised when saving the form!

### Expected behavior
change attributes is commited

### Screenshots and logs
![image](https://user-images.githubusercontent.com/402354/41601436-bd01d076-73d8-11e8-8a0e-9e9e14559ef7.png)

2018-06-19 15:49:24	195.244.181.133	error	An error has been raised when saving form data edition to db : Erreur dans la requête (ERROR:  value too long for type character varying(254)( UPDATE "public"."prog0806_180518_chantiers" SET "id"=184, "id_ws"=124652, "type_pert_"='Perturbant', "type_per_1"='Storing', "comment"='fgzr', "vote"='N', "gv_type"='MIXTE', "gv_fr"='Gestionnaire Régional, VBX', "imp_type_f"='Impétrant Institutionnel', "imp_type_n"='Institutionele verzoeker', "imp_fr"='SPRB - BM - DPT', "imp_nl"='GOB - BM - DPW', "imp_lang"='BIL', "coor_imp_n"='Proximus Infra 
VIVAQUA 
Sibelga SB-CO 
TLN 
GOB - BM - DBO - Beplantingen, monumenten en fonteinen 
GOB - BM - DPW 
GOB - BM - DBO - Uitrusting 
GOB - BM - DBO - Telematica 
Infrabel 
MIVB - BL - PROJECT 
MIVB - SIG - PROJECT 
MIVB - SPOREN - PROJECT 
D', "status_fr"='Subdivisé (initial)', "status_nl"='Subdivisé (initial)', "inte_refe"='projet 237 avenue Roosevelt', "label_fr"='réfection voirie + trottoir', "label_nl"='réfection voirie + trottoir', "procedure"='PCA', "classe_voi"='A1', "nature_fr"='Travaux de voirie et d''infrastructure', "nature_nl"='Werkzaamheden aan weg en infrastructuur', "methode_fr"='En tranchées ouvertes', "methode_nl"='In open sleuven', "surface"=117237, "pgm_start_"='2017-07-03', "pgm_end_da"='2020-12-18', "auto_start"=NULL, "auto_end_d"=NULL, "dura_open"=300, "yn_plan"='N', "road_impl_"='Avenue Franklin Roosevelt (Bruxelles); Chaussée de La Hulpe (Uccle); Avenue du Congo (Bruxelles); Avenue du Brésil (Bruxelles); Avenue de l''Orée (Bruxelles); Avenue Lloyd George (Bruxelles); Chaussée de La Hulpe (Bruxelles); Avenue Air Marshal Coning', "road_imp_1"='Franklin Rooseveltlaan (Brussel); Terhulpensesteenweg (Ukkel); Kongolaan (Brussel); Braziliëlaan (Brussel); Zoomlaan (Brussel); Lloyd Georgelaan (Brussel); Terhulpsesteenweg (Brussel); Air Marshal Coninghamlaan (Brussel); Uruguaylaan (Brussel); Victoria', "id_ws_dev"=NULL, "yn_modi_tr"='N', "deviation"='Absence de deviation', "start_date"='03/07/17', "end_date"='18/12/20', "pct_leo"=NULL, "pct_hc"=NULL, "select75"='YES', "hyperco"='no' WHERE "id" = 184 AND  "user" IN ( 'test' , 'all' )  RETURNING "id";))

### Environment

 - Lizmap version: 3.2beta2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): Linux 
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? PG

**Comment by rldhont** [comment]
The error is explicit. One field is defined in your database as a varchar(254), so even if this field is not updatable for user the value provided by lizmap is too big.

**Comment by jlstanus** [comment]
- OK found the problematic feature with the lenght() function in Qgis. 
- I didn't see this error because the field lenght is 254 (it has been 'naturally' truncated by qgis) so not grater than 254  
- the reasoni was thiking it s big geometry it s because there are more informations for big geometries
![image](https://user-images.githubusercontent.com/402354/41603747-e53b2e34-73dd-11e8-8e36-357400fc83eb.png)

so when the field lenght is 253, it s ok. Bug or not?

**Comment by nboisteault** [comment]
@jlstanus You should use `text` type and not `varchar(n)`. Can you close issue ?

**Comment by jlstanus** [comment]
Thank you for your tip
