### ISSUE TITLE
Issues with tooltip if CRS is not EPSG:4326

### ISSUE THREAD

**Issue by ilamarengo** [3liz/lizmap-web-client#895]
### What is the bug?
hello, i am trying to add the tooltip to some layers in a project and i am failing.
Layers are in postgresql, QGIS version is LTR 2.18.17, OS is windows, Lizmap is the latest release, i use firefox as browser.

I had a look at the DEMO, montpellier and i can see that tooltip works fine for both shape files and sqlite files, hence i don't think it s a bug per se but certainly there is a problem in what i am doing or in the way the layer is set up.

### Steps to reproduce the issue
I have decided to start from level "zero": shapefile, just to test my steps. I created a new project, taken only the "quartiers" layer from Montpellier, published in lizmap and the tooltip works fine. I have then created a second QGIS project, created a new layer using quartier as model (e.g. copied attribute tables structure and field types), published in lizmap adding the tooltip function and no success. The tooltip online really doesn't turn on. Notice that the layer i created is very basic, a polygon split into 4 parts, each with a different attribute. In both cases the field used for tooltip is a string. LIBQUART for quartier and SOILNAMES for my test file.

I have added screen shots of the attribute tables of the  model i used (quartier) and the test i am running.
I don't understand where i make a mistake. Any help is appreciated!

![montpellier_quartier_table](https://user-images.githubusercontent.com/17223497/41627830-5fea7ada-73f8-11e8-8a16-f8c4e59634b6.jpg)
![my_test_table](https://user-images.githubusercontent.com/17223497/41627841-684ed040-73f8-11e8-9a21-e7bc9b379a3a.jpg)

**Comment by rldhont** [comment]
Do you have publised the layer in WFS ? Do you have verified that the request GetFeature returning good GeoJSON ?

**Comment by ilamarengo** [comment]
yes i did,


Hello and thanks for you prompt reply.


So, if i export the file as GEOJSON i get a proper file: i can import into QGIS and see it properly with the entire attribute table.

Yes i have activate the WFS and WMS capabilities and if i copy and paste the following in firefox


http://148.251.22.181/cgi-bin/qgis_mapserv.fcgi?
map=/home/gmanghi/www/saeri_webgis/lizmap/install/dplus052/saint_helena_web.qgs&SERVICE=WFS&REQUEST=GetCapabilities


i get this as return:


[cid:3346d78a-f736-4ec6-af48-9bb3f98acd63]

   lrs32_soils is the layer i am applying the tooltip

HOWEVER, if i try to load the WFS in QGIS i get this message

"capabilities document contain no layer"

so somewhere i am missing something relevant and it generates the problem with the tooltip....i think.




________________________________

**Comment by ilamarengo** [comment]
further on the mail i sent.
i tried the WMS link generated by lizmap and it works fine, i can see all the layers i generated in the project and i can upload them in QGIS.
see attachment

what is the url i should then use only for WFS?
was what i sent in the previous email correct?

Many thanks!

![wms-sainthelena](https://user-images.githubusercontent.com/17223497/41651962-44841ff2-7458-11e8-96fa-3b8595914e68.jpg)

**Comment by rldhont** [comment]
The WFS layer is the same but replace WMS by WFS.

**Comment by ilamarengo** [comment]
Hello and thanks for your advice.


i followed it but now the error message that i obtain from QGIS is "unexpected end of file"


i still can't figure out what i am missing.



________________________________

**Comment by rldhont** [comment]
Do you have some messages in your Browser Dev tools ?
Do you have some error in lizmap ? Does @gioman can help  you ?

**Comment by ilamarengo** [comment]
Hmm Lizmap doesn't show any error message.

Not sure where to check the error messages in the Browser Dev Tool.

Yes, i am in touch with @gioman and he can help me.


thanks, will keep you posted

________________________________

**Comment by gioman** [comment]
@rldhont hi, I gave it a try. QGIS Server/Desktop 2.18.20, latest stable LM. WFS/GeoJSON is all ok. No error on the dev console in Firefox. As far as I can see (tested with the Montpellier demo project) tooltips only work if the layer is in EPSG:4326. Try with SousQuartiers, it won't work. The moment you save a copy of it in 4326, then for this copy tooltips will work (Quartiers and Tramstops work out of the box as they are in 4326).

**Comment by rldhont** [comment]
@gioman I can't reproduced this issue. I have simply added SousQuartiers in tooltips without reprojection and it works!

I'm using QGIS Server 2.18.20 and lizmap 3.1.12

**Comment by rldhont** [comment]
In the lizmap admin, what is the value defined for qgis server version ?

**Comment by gioman** [comment]
@ilamarengo please check if in the Lizmap configurations (after logging as admin) the QGIS Server version is set as ">= 2.18"

**Comment by gioman** [comment]
> In the lizmap admin, what is the value defined for qgis server version ?

@rldhont I still see this issue with recent releases of Lizmap and QGIS Server. When activating tooltips on a layer in CRS 3763 the tooltip do not show and the "display geometry" part works in weird way (you can tell is very slow, geometries are show with the chosen color, but when hovering on a second geometry, the color for the first one is not cleared). If I make a copy of the same layer in CRS 4326 it works as expected. Project is in CRS 3763.
