### ISSUE TITLE
Print error when selecting features in more than 1 layer

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#896]
### What is the bug?

Print does not work when using a selection on more than 1 layer.

### Steps to reproduce the issue

1. Use the demo Montpellier project
2. Select district and tram lines with the selection tool
3. Open the print tool and submit
4. 500 error for the getPrint request

The Lizmap log show there is a problem with the cache key :+1: 

```
erreur clé b33188e338ffd2b8b2a9d81bf35f95a9;a80a86527560828bbca63ed6af007ac5 , limité à 255 caractères et seuls les caractères alphanumeric et le caractère '_' sont autorisés
```
We should replace the ; by _ in the cache key used to store the selection token

### Expected behavior

The getPrint request suceed and returns the PDF with both layers showing selection

### Environment

 - Lizmap version: 
 - QGis version:
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...):
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?

**Comment by rldhont** [comment]
has been fixed, needs to be merged
