### ISSUE TITLE
Align projects thumbnails horizontally instead of vertically 

### ISSUE THREAD

**Issue by ilamarengo** [3liz/lizmap-web-client#897]
I am trying to change the way the project thumbnails are display in the main page of all lizmap projects.
I know that it is possible as i have seen the demo example 
https://demo.lizmap.com/lizmap_3_1/
i read the source page and i compared with my lizmap projects page (where the thumbnails are displayed vertically and therefore people need to scroll down to find the latest project) and i can spot one difference. However, i don't know which file and which line i should change (e.g. main.css?) in order to modify the alignment of the thumbnails.

Any help is much appreciated.

**Comment by rldhont** [comment]
In the demo all the projects are in one repository.

**Comment by ilamarengo** [comment]
great, thank you for your help

________________________________

**Comment by rldhont** [comment]
If you think the documentation is not clear, please, fill free to update it https://github.com/3liz/lizmap-documentation
