### ISSUE TITLE
[UI] Point masked by bottom dock when zooming on

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-web-client#898]
### What is the bug?
Point features are partially masked by top of the bottom dock when zooming on.

### Steps to reproduce the issue

1. Load a point layer in attribute table tool
2. Click on 'zoom' for one of the point feature
3. Point is masked by top of the bottom dock

### Expected behavior
I think the point should be clearly visible on the map. If we put bottom dock height at 48% and not 50%, point becomes visible and dock height doesn't  become too small. That could be an easy fix.

### Screenshots and logs
![image](https://user-images.githubusercontent.com/2145040/41769543-ef32a1a4-760f-11e8-82ec-e1a34e1e11ed.png)

### Environment

 - Lizmap version: 3.2
 - QGis version: all
 - OS (windows, linux, macOS, android..):  all
 - Browser (Firefox, Chrome...): all

**Comment by rldhont** [comment]
Not so easy to do!

**Comment by SenequeC** [comment]
Fixed by #907.

**Comment by nboisteault** [comment]
Thanks @SenequeC !
