### ISSUE TITLE
Edit layer empty in lizmap plugin

### ISSUE THREAD

**Issue by adelchia** [3liz/lizmap-web-client#899]
Lizmap 3.1.8 – Qgis 2.18 – OS UBUNTU
When I click on "add layer" (aggiungi layer) in lizmap plugin (you can see the image) I can not find any Qgis level to edit. Is it the bug or other settings problem? Tank you.
![schermata del 2018-06-22 19-39-02](https://user-images.githubusercontent.com/37080380/41790821-109d5250-7654-11e8-841d-5e82be39a20f.png)

**Comment by rldhont** [comment]
If the issue concerning Lizmap-plugin, please use the repository https://github.com/3liz/lizmap-plugin to open an issue about it.
