### ISSUE TITLE
Support ZM and Z values

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#902]
### Is your feature request related to a problem? Please describe

When data are stored in Postgresql, lizmap is using the `geometry_columns` view to fetch informations about the geometric field:
https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L221

But if a layer contains a Z or ZM values in the geometry, then the `geometry_column` is not giving enough information.

For instance:
```sql
CREATE TABLE field_test
(
    SERIAL integer, geom geometry(Point,32620) NOT NULL,
    geom_z geometry(PointZ,32620) NOT NULL,
    geom_m geometry(PointM,32620) NOT NULL,
    geom_zm geometry(PointZM,32620) NOT NULL
);
SELECT f_table_name, f_geometry_column, coord_dimension, type from geometry_columns WHERE f_table_name = 'field_test';
```
is giving me:
```
"field_test"	"geom"	2	"POINT"
"field_test"	"geom_z"	3	"POINT"
"field_test"	"geom_m"	3	"POINTM"
"field_test"	"geom_zm"	4	"POINT"
```
As we can see, whenever it's a `Point`, or `PointZ` or `PointZM`, in the view it results in a `POINT`.
Lizmap is failing as soon as we try to save a new feature in the DB because one dimension is missing.

### Describe the solution you'd like

Lizmap should detect correctly the dimension of the field and apply `ST_Force_3DZ` `ST_Force_3DM` or `ST_Force_4D` in the same way as it's already done for `ST_Multi` in https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php#L362

### Describe alternatives you've considered

Using this SQL query is giving the correct geometry type:
```sql
SELECT a.attnum
      ,a.attname                            AS name
      ,format_type(a.atttypid, a.atttypmod) AS typ
      ,a.attnotnull                         AS notnull
      ,coalesce(p.indisprimary, FALSE)      AS primary_key
      ,f.adsrc                              AS default_val
      ,d.description                        AS col_comment
FROM   pg_attribute    a 
LEFT   JOIN pg_index   p ON p.indrelid = a.attrelid AND a.attnum = ANY(p.indkey)
LEFT   JOIN pg_description d ON d.objoid  = a.attrelid AND d.objsubid = a.attnum
LEFT   JOIN pg_attrdef f ON f.adrelid = a.attrelid  AND f.adnum = a.attnum
WHERE  a.attnum > 0
AND    NOT a.attisdropped
AND    a.attrelid = 'schema.table_name'::regclass  -- table may be schema-qualified
ORDER  BY a.attnum;
```
I took it from https://stackoverflow.com/questions/15928118/how-to-get-column-attributes-query-from-table-name-using-postgresql

I'm also not sure it's normal for the `geometry_column` to give `POINT` when there is a Z value in it. If someone knows if it's a bug upstream? I would expect to have Z in the view, no?

I'm investigating a bit on postgresql. Just writing my thoughts ;-)

Using a trigger is not working to update the geometry: https://stackoverflow.com/questions/36870972/using-before-insert-trigger-to-change-the-datatype-of-incoming-data-to-match-t

CRUD is working well in QGIS.

**Comment by rldhont** [comment]
It is a bug to fix but also an enhancement for lizmap poit of view.
Thansk for this feedback.

**Comment by mdouchin** [comment]
Thanks for raising this issue. Indeed at present Lizmap cannot edit complex geometries like 3D or Z or M. 

What about an update on X and Y ? Should we set the additional dimension (ex: Z) to 0.0 ? Should we keep it ? Should we provide a (complex) way,  like in QGIS, to let the user edit the third coordinate in a table ?

**Comment by Gustry** [comment]
> What about an update on X and Y ?

This doesn't work currently. I currently have a trigger to add altitude to my point. But lizmap is creating a XY point while my database takes a XYZ point. We can't change the data type even if we are usign a trigger: https://stackoverflow.com/questions/36870972/using-before-insert-trigger-to-change-the-datatype-of-incoming-data-to-match-t

> Should we provide a (complex) way, like in QGIS, to let the user edit the third coordinate in a table ?

I actually don't mind if we can't edit Z or M in lizmap. I just except Lizmap to don't fail when saving the new feature. So Lizmap must use `ST_Force_3DZ` `ST_Force_3DM` or `ST_Force_4D` to be compliant with the DB before inserting the new feature.

I will try a patch with my SQL above.

**Comment by Gustry** [comment]
I made the PR in lizmap plugin to warn the user that he will lose Z M values when editing: https://github.com/3liz/lizmap-plugin/pull/107

**Comment by Gustry** [comment]
And finally I updated my opened PR on lizmap-documentation:
https://github.com/3liz/lizmap-documentation/pull/96
