### ISSUE TITLE
Layer names disappear when clicking twice on 'deploy all'

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#903]
### What is the bug?
Some layers name disappear (everytime with wps computed layers names)

### Steps to reproduce the issue
1. Click twice on 'deploy all'

### Expected behavior
Layers name shord not disappear

### Screenshots and logs
<img width="203" alt="capture_d_ecran_2018-06-26_a_12 52 26" src="https://user-images.githubusercontent.com/1822286/41908951-f120dfec-7945-11e8-8526-01334c4a18c9.png">

### Environment

 - Lizmap version:  3.2
 - QGis version: 3.0.1
 - OS: Linux (debian 9)
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?

**Comment by josemvm** [comment]
fixed https://github.com/3liz/lizmap-web-client/issues/551
