### ISSUE TITLE
WMS url

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#906]
Hello,
is it possible to escape a layer from the WMS url?

**Comment by rldhont** [comment]
What do you mean by `escape` a layer from the WMS URL ?

If the layer is in the WMS GetCapabilities, it is accessible through WMS.

**Comment by morvan80** [comment]
I explain better, I need to display a layer in the project but to block the display on the wms used in qgis (not to do it download locally)
Thank you

**Comment by nboisteault** [comment]
@morvan80 Please reopen and describe your issue more clearly if needed.
