### ISSUE TITLE
Impossible de voir ma carte sous Lizmap

### ISSUE THREAD

**Issue by guigui26** [3liz/lizmap-web-client#910]
Bonjour,
j'ai suivi la documentation "éditeur puis administrateur" pour installer Lizmap sur un Windows 10 en local.
J'ai créé mon projet sous Qgis (avec des données vecteur et raster)
J'ai activé le serveur OWS dans Qgis.
J'ai paramétré le plugin lizmap. A l'issue, j'obtiens bien un fichier de configuration (.cfg) dans le répertoire de mon projet.
J'ai copier coller l'ensemble du dossier au même endroit que les répertoires des cartes de démo Montpellier et Montpellier Intranet (dans un dossier parallèle).
Je me connecte en admin sur localhost/admin.php. J'ai ajouté l'utilisateur "admin" dans le groupe admin et j'ai donné les droits de visu/création sur les répertoires.
J'ai ajouté mon nouveau répertoire avec le chemin vers mon dossier contenant mon projet et mes couches.
Et la, impossible de voir ma carte dans les projets.....
Avez vous une idée de là où je me suis loupé ?
Merci d'avance pour votre aide.
Cordialement
Guillaume

**Comment by guigui26** [comment]
Je précise qu'en dessous du nom du répertoire, si je clique sur Voir, je n'ai que le bandeau du haut mais pas la carte ....

**Comment by jlstanus** [comment]
Vérifie

- les droits du répertoire projet/données que ce soit bien read pour utilisateurs et groupes
- vérifie les logs
- que la couche apparait dans l'arbre

Envoie un max de capture et logs

**Comment by rldhont** [comment]
Pouvez-vous nous indiquer la configuration de votre répertoire ? (chemin, titre)
Pouvez-vous nous fournir une impression écran de votre page d'accueil lizmap ?

**Comment by rldhont** [comment]
Avez-vous regarder le log d'erreurs de Lizmap, `lizmap/var/log/errors.log` ?

**Comment by guigui26** [comment]
Merci de vos retours
voici des captures du paramétrage
"que la couche apparait dans l'arbre"?, désolé je ne comprends pas. Pouvez vous me préciser davantage ?
Je regarde le répertoire des logs
Faut il que le nom donné répertoire dans le client lizmap soit le meme que le nom du projet Qgis ?
Merci de votre aide
![repertoire-data](https://user-images.githubusercontent.com/40691279/42097190-c9178784-7bb7-11e8-9bef-faaf10709559.jpg)
![lizmap-config](https://user-images.githubusercontent.com/40691279/42097191-c93510ec-7bb7-11e8-8178-6cd3e1d4e829.jpg)
![lizmap-config-mon-repertoire](https://user-images.githubusercontent.com/40691279/42097192-c956f68a-7bb7-11e8-9111-1e526674a62f.jpg)
![lizmap-droits-admin](https://user-images.githubusercontent.com/40691279/42097194-c9851524-7bb7-11e8-9969-4bd0a787250f.jpg)
![lizmap-droits-admin-suite](https://user-images.githubusercontent.com/40691279/42097196-c9ad831a-7bb7-11e8-9795-39575ce79ff7.jpg)
