### ISSUE TITLE
Additional export/download formats do not show in LMWC(?)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#911]
### What is the bug?

I Installed the QGIS Server plugin

https://github.com/3liz/qgis-wfsOutputExtension

as the documentation explains, and in the GetCapabilities of the WFS service I indeed see the additional formats:

```
...
<GetFeature>
<ResultFormat>
<GML2/>
<GML3/>
<GeoJSON/>
<SHP/>
<XLSX/>
<ODS/>
<KML/>
<MIF/>
<TAB/>
<CSV/>
</ResultFormat>
...
```

### Steps to reproduce the issue

see above.

### Expected behavior
Is expected to see the additional formats automatically also in LMWC? or it is needed some additional configuration (that I can't see at the moment in the backoffice nor in the LM plugin)?

### Environment

 - Lizmap version: 3.1.12
 - QGis version: 2.18.21
 - OS (windows, linux, macOS, android..): Ubuntu Server 16.04
 - Browser (Firefox, Chrome...): all
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? sqlite

**Comment by rldhont** [comment]
Are the WFS Capabilties is the same in lizmap and in QGIS Server ?
Do you have clear the `/temp/lizmap` directory with `lizmap/install/clean_vartmp.sh` ?

**Comment by gioman** [comment]
> Are the WFS Capabilties is the same in lizmap and in QGIS Server ?

@rldhont you are right, from within LM the WFS Capabilities do not show the additional formats (even after running the clean tmp script). Not sure if I understand what it going on here (what I'm doing wrong). Any tip?

**Comment by gioman** [comment]
@rldhont I guess could be an Apache misconfiguration on my side, am I correct? thanks in advance for any tip you can leave. Cheers.

**Comment by rldhont** [comment]
Use `clean_vartmp.sh` or update the `*.qgs` files.
