### ISSUE TITLE
bug url images when moving a project to a different folder?

### ISSUE THREAD

**Issue by jancelin** [3liz/lizmap-web-client#913]
Why can't I see images simply by moving a project to a different folder?

https://lizmap.sig.inra.fr/websig/lizmap/www/index.php/view/media/getMedia?repository=demo&project=atlas&path=media%2Fupload%2FProjet_plantation%2Fphoto%2Fphoto_chemin%2FIMG_20180516_100939.jpg
Working
https://lizmap.sig.inra.fr/websig/lizmap/www/index.php/view/media/getMedia?repository=public&project=atlas&path=media%2Fupload%2FProjet_plantation%2Fphoto%2Fphoto_chemin%2FIMG_20180516_100939.jpg
Not working

**Comment by rldhont** [comment]
Did you move or copy the `media/upload` folder in the public repository ?

**Comment by jancelin** [comment]
Harg....
My first idea!!! but is it not feasible to share media?

**Comment by rldhont** [comment]
you can create link folder, I have made fixes about this capability.

**Comment by jancelin** [comment]
I try...

**Comment by jancelin** [comment]
Yep, thanks!!!

**Comment by rldhont** [comment]
Can you update the documentation ?

**Comment by jancelin** [comment]
Ok
just for track...

```
mkdir /home/public/media/
ln -s /home/media/upload /home/public/media/
chown www-data:www-data -R /home/public/media/upload
```
