### ISSUE TITLE
Ldapdao : the user cannot log in more than one time

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#914]
### What is the bug?

When ldapdao is active on a PostgreSQL profile, a user can connect one time only. The second connection leads to a "wrong user or password message".

### Steps to reproduce the issue

1. install Lizmap with a PostgreSQL user profile and ldapdao active
2. log as a user, the deconnect: OK
3. log in again as the same user : Lizmap shows a connexino error (not bug but the red message wrong password)

I think the status is not well set in the database when the user is inserted in the table. It must be linked to the jCommunity new module.

I added some logs in ldapdao verifyPassword method, and this methods does the job well, and returns a the following json-encoded user:

```json
{"login":"carto","email":"","password":"!!ldapdao password!!","firstname":"Carto","lastname":"","organization":null,"phonenumber":null,"street":null,"postcode":null,"city":null,"country":null,"comment":null,"status":null,"keyactivate":null,"request_date":null,"create_date":null,"distinguishedName":"CN=Carto,OU=Services,DC=acme,DC=fr","userPrincipalName":"carto@acme.fr"}
```

### Expected behavior

The user can log more than one time ;)

### Environment

 - Lizmap version: release_3_2
 - OS (windows, linux, macOS, android..): debian 9.4
 - Lizmap data stored into Postgresql

**Comment by rldhont** [comment]
Without LDAP, the user DAO is defined by the lizmap modules: https://github.com/3liz/lizmap-web-client/blob/master/lizmap/modules/lizmap/daos/user.dao.xml

@laurentj:
* is the same DAO used by ldapdao ?
* would the solution be to create a dedicated DAO for LDAP, with a default value for status to 1 ?

**Comment by laurentj** [comment]
>is the same DAO used by ldapdao ?

[yes](https://github.com/3liz/lizmap-web-client/blob/master/lizmap/var/config/admin/auth.coord.ini.php#L119)

>would the solution be to create a dedicated DAO for LDAP, 

no

>with a default value for status to 1 ?

[This is already done](https://github.com/3liz/lizmap-web-client/blob/master/lib/vendor-modules/ldapdao/plugins/auth/ldapdao/ldapdao.auth.php#L209)

I will investigate...
