### ISSUE TITLE
Implement php/REST command for creating new repository as back office management

### ISSUE THREAD

**Issue by dmarteau** [3liz/lizmap-web-client#922]
### Is your feature request related to a problem? Please describe
Develop back-office tools for project management.

### Describe the solution you'd like
- A php command to add new lizmap repository
- Support command with REST API

This could be a starter for a larger move for managing Lizmap on server side or with REST.

**Comment by laurentj** [comment]
REST API means to have a strong authentication system.

For a first iteration, I propose to create only a php command

**Comment by rldhont** [comment]
Implemented

To create a repository definition, the command line is:
```
php lizmap/scripts/script.php lizmap~repository:create key label path [allowUserDefinedThemes]
```

Then to add rights you can use the command line `acl2right`:
```
php lizmap/cmd.php acl2right add group right key
```

For example, create the `test` repository and add view rights to all users
```
php lizmap/scripts/script.php lizmap~repository:create test 'Test repository' test
php lizmap/cmd.php acl2right add __anonymous 'lizmap.repositories.view' test
php lizmap/cmd.php acl2right add users 'lizmap.repositories.view' test
```

The other rights for lizmap repositories are:

* lizmap.tools.edition.use
* lizmap.tools.displayGetCapabilitiesLinks
* lizmap.tools.layer.export
* lizmap.tools.loginFilteredLayers.override

**Comment by dmarteau** [comment]
Command are working but do not send the correct exit error code:

If a repository cannot be created:
```
> php lizmap/scripts/script.php lizmap~repository:create foo 'Foo Directory' foo
The path provided is not authorized!
The repository can't be created!
```
The return code is still 0 ! It should be at least 1

The command `lizmap/cmd.php acl2right` should not send error if the rights are already set (idempotence should not be consdered as error). 

Other possible improvements

* The output message `---Add a right` is not very useful; it should be `rights <rights> set for <group>`
* Since rights seems to have a tree-like structure one should be able to set rights in the form: `lizmap.tools.*` or `lizmap.tools.` - for not colliding with shell wildcards.

**Comment by rldhont** [comment]
@dmarteau The exit error code has been fixed.

For the `acl2right`, I invite you to open an issue directly in jelix repository https://github.com/jelix/jelix
