### ISSUE TITLE
Feature to create link with hash to share hidden or restricted acces project

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-web-client#923]
### Is your feature request related to a problem? Please describe
Often, the project is not so confidential and can be shared with any people interested that get the link
The link is an alternative to authentification

### Describe the solution you'd like
To generate a link with hash without the name of the project and gives acces to a restricted project (or hidden project)
The admin could manage and revoke the link generated
The link could be similar to tiny url

**Comment by nboisteault** [comment]
@jlstanus this issue is not specific to Lizmap. Did you find a solution ?

**Comment by jlstanus** [comment]
No, But i agree, it can be solved by a reverse proxy or something else.
