### ISSUE TITLE
Attribute table is empty for an external WFS layer

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#924]
### What is the bug?
Lizmap displays well objects on the map and popup,  but attribute table is empty (see image above).
I've tried with differents sources and several layers, the same problem occurs.

### Screenshots and logs
![image](https://user-images.githubusercontent.com/32867483/42503706-ace6ff1a-8439-11e8-908d-48e0a710cd7e.png)

### Environment

 - Lizmap version: 3.1.12
 - QGis version: 2.18.18
 - OS (windows, linux, macOS, android..): linux I think (hosting by 3Liz)
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? this problem occurs with wfs layers from open data.
 
Thanks.

MFANGAIN

**Comment by nboisteault** [comment]
@mfangain does WFS url begins with https ?

**Comment by mfangain** [comment]
@nboisteault yes, it does :
WFS server URL : https://public.sig.rennesmetropole.fr/geoserver/ows?

**Comment by nboisteault** [comment]
@mfangain Does it occur with LWC 3.3.3 ?

**Comment by mfangain** [comment]
@nboisteault No, I don't have this problem anymore with Lizmap 3.3. Thanks.
MFANGAIN
