### ISSUE TITLE
INSERT IMAGE INTO A LAYER LEGEND

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#927]
Hi,
how is possible insert a personal image in a layer legend
(layer categorized) too view all simbol?
Thanks!
![legend](https://user-images.githubusercontent.com/28442671/42624893-c12a3d82-85c6-11e8-9ffb-cd135bc6c97f.JPG)

**Comment by josemvm** [comment]
hi @robibrazze 

yes, it's possible, you must use svg symbols
