### ISSUE TITLE
popup tool - no longer highlights the geometries

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#929]
### What is the bug?
popup tool no longer highlights the geometries

### Steps to reproduce the issue

see Montpellier project

### Environment

 - Lizmap version: 3.2
 - QGis version: 2.14, 2.18
 - OS (windows, linux, macOS, android..): linux
 - Browser (Firefox, Chrome...): firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? sqlite
 
thanks

**Comment by SenequeC** [comment]
Hi, when you click on the 'select' button of the popup the feature is not highlighting itself ? I have no problem on my side.

**Comment by rldhont** [comment]
The Montpellier porject has been changed, the option to provide geometries in GetFeatureInfo has not been activated.

**Comment by josemvm** [comment]
@rldhont are you talking about "Add geometry to feature response" option in project properties, OWS server?

**Comment by rldhont** [comment]
@josemvm yes, it is.

**Comment by josemvm** [comment]
thanks @SenequeC and @rldhont !
