### ISSUE TITLE
atlas tool - no longer zooms to the geometries

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#930]
### What is the bug?
atlas tool no longer zooms to the geometries

### Steps to reproduce the issue

see Montpellier project

### Environment

 - Lizmap version: 3.2
 - QGis version: 2.14, 2.18
 - OS (windows, linux, macOS, android..): linux
 - Browser (Firefox, Chrome...): firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? sqlite
 
thanks

**Comment by SenequeC** [comment]
Hi, i think it's just a change in parameter of in the plugin Lizmap for the project.
'Zoom to feature' option is set to 'center' instead of 'zoom'. So it's probably not a bug but just a change.

**Comment by rldhont** [comment]
The Montpellier project config has been changed with center and not zoom.

**Comment by josemvm** [comment]
thanks @SenequeC and @rldhont !
