### ISSUE TITLE
Search location doesn't work behind a webproxy

### ISSUE THREAD

**Issue by Bray-N** [3liz/lizmap-web-client#932]
### What is the bug?

If lizmap is behind a web proxy for http requests, location searching is KO, with PHP or Curl.

### Expected behavior

![image](https://user-images.githubusercontent.com/41430958/42940255-13b3af38-8b59-11e8-934c-c452d5f39c53.png)

### Screenshots and logs

![image](https://user-images.githubusercontent.com/41430958/42940245-08ad1dae-8b59-11e8-87e0-cc42e4a81968.png)

Works with Curl by adding those lines in lizmap/controllers/osm.classic.php, line 46
    curl_setopt($curl_handle, CURLOPT_PROXY, '_myProxyHost:myProxyPort_');
    curl_setopt($curl_handle, CURLOPT_NOPROXY, '_mydomain.com,localhost_');

Probably same issues with functionnalities using getRemoteData() in lizmap/classes/lizmapProxy.class.php

### Environment

 - Lizmap version: 3.1.12
 - QGis version: 2.14 (N/A)
 - OS (windows, linux, macOS, android..): Linux
 - Browser (Firefox, Chrome...): N/A
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? N/A

**Comment by rldhont** [comment]
How did you exactly fix it ? Can you provide a Pull-Request ?

**Comment by Bray-N** [comment]
It's a very ugly fix, and working only for curl method...

[github-lizmap-3.1.12-proxy.patch.txt](https://github.com/3liz/lizmap-web-client/files/2336390/github-lizmap-3.1.12-proxy.patch.txt)

**Comment by nboisteault** [comment]
We could add a 'proxy' parameter in Lizmap's Administration configuration and use it for every CURL calls.
Another solution would be to directly request from the browser, this way we avoid a request to the lizmap server. @rldhont do we really need to query lizmap server ? When I look osm.classic.php I can' t see the reason why we don't directly query nominatim.

**Comment by laurentj** [comment]
I take it

**Comment by laurentj** [comment]
I have a patch. I have to add new parameters into the configuration form before doing a PR.

**Comment by laurentj** [comment]
@nboisteault you're right, we could make a request directly from the UI.  nominatim.openstreetmap.org allows to request itself from any origin (because of its [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), so it should not be an issue in the UI. But we should open an other ticket for that.
