### ISSUE TITLE
Does Lizmap support a custom CRS?

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-web-client#933]
I'm trying to view a multiband raster file with a custom CRS. In QGIS it works well while in Lizmap it doesn't work. I have also selected the custom CRS in the properties but it is not visible.
I then did a test converting the file into a standard coordinate system and Lizmap saw it.
I ask you if Lizmap supports custom CRS, since I have many large raster files with their own CRS.

Thanks

**Comment by gioman** [comment]
@news24lor I remember this was an issue in old versions of LM, I always assumed it was fixed in LM3 but may be I'm wrong, or may be it regressed.

**Comment by rldhont** [comment]
Hi @news24lor ,
For helping you about this issue, can you provide a test URL ?
Have you tested the WMS directly from QGIS Server ?

**Comment by news24lor** [comment]
HI @rldhont 
I don't have a public link unfortunately, sorry.
Files with a custom projection are netcdf multiband while other files, vector and raster have standard projections.
In QGIS I created new WMS, WCS and WFS links by inserting this simple QGIS Server link:

http://localhost/qgis-mapserv/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&map=/www/path_of_qgis_projects/myprojectwithcustomcrs.qgs

When I press the connect button I see the list of all layers for that protocol. In WFS for example I see only the vectorial layers while in WMS I see all the layers.

Between WMS and WCS there is a different behavior for custom projection files.

Connection via WMS:
pressing Connect I see the whole list. Selecting a layer with the custom projection the projection available is the WGS84. Add the layer and the layer is perfectly centered with all available bands. Probably the WMS already does a transformation directly from the server to the client. If I then press to see the pixel data I see the data of all bands. Of course with the WMS I can not change any color for the various bands. The legend is OK.

Connection via WCS:
Instead in WCS the same layer doesn't have a projection but if I enter after my custom CRS after to the map the layer is centered. The problem is that the pixel data is not transferred. No data can be displayed only for layers with CUSTOM projection.

All other raster and vector layers with standard projections work perfectly in both WMS and WCS.

Then I did a test directly with QGIS Server creating a link to be displayed on the web directly and all layers are displayed except with the custom projection. Perhaps the bug is already in QGIS Server version 2.18.x. But as I indicated at the top in QGIS the WMS of the custom CRS layers from QGIS server is seen. The situation is a bit complex. I think the problem is already in QGIS Server 2.18.x for custom projection layers and so Lizmap can't work for those layers.

It would be useful to test QGIS Server 3 to see if the bug has been fixed or report the bug to QGIS.
Do you have Lizmap for QGIS version 3? And how do I install it?

Thank you again

**Comment by Gustry** [comment]
Since Lizmap Web Client 3.6, the project page in the administration panel is warning the GIS administrator when a project has a custom CRS.
