### ISSUE TITLE
How to connect a project to local Postgresql database?

### ISSUE THREAD

**Issue by lymankj** [3liz/lizmap-web-client#935]
Hi, when trying to load a project containing two layers from the localhost postgresql database, the postgresql log is full of errors about www-data not having permission or roles to access, login, etc. This was surprising because I assumed that lizmap would use the user name and password in the project.qgs file to connect to the database and not the user name of the apache2 user. Note that the project is created on a QGIS desktop machine and then uploaded to the server along with the .cfg file.

Is there a recommended way to specify a database user name and password? I did attempt to use environment variables in profiles.ini.php by adding directly something like:

```
[jdb:jauth]
driver="pgsql"
database="mydb"
host= "localhost"
user= "myuser"
password= "mypass"
```
But this causes lizmap to display a 500 error when trying to load the admin or project page. Am I missing a step? Also, what should be the permission line in pg_hba.conf?

Thanks!

**Comment by gioman** [comment]
@lymankj LM uses indeed the connection informations are they are saved inside the QGIS project. Check (yo can edit the .qgs file with a text editor) if the project file has the connection informations saved in it.

**Comment by lymankj** [comment]
Hi, that's what I thought but the postgresql error log is still ::
`2018-07-25 22:30:52 HST [8474-1] www-data@mydb FATAL:  role "www-data" is not permitted to log in`

**Comment by gioman** [comment]
@lymankj when you created the postgis connections in QGIS have selected to save both username and password? It seems that you haven't.

**Comment by lymankj** [comment]
Sorry my mistake! The postgresql errors are from a few minutes ago.
Even though I explicitly told QGIS desktop to use the old credential format for the project file it still saved the password in some sort of cipher (dekstop v3.2). However, this now creates an error in the apache2 error log stating:
```
[Wed Jul 25 22:47:32.555049 2018] [fcgid:error] [pid 7567] mod_fcgid: process /usr/lib/cgi-bin/qgis_mapserv.fcgi(9181) exit(communication error), get unexpected signal 11
```
I suspect this could be a project.cfg error due to using QGIS 3.2 on the desktop and QGIS 2.18 on the server? Would you recommend updating the server or downgrading the desktop?

**Comment by gioman** [comment]
@stick with QGIS LTR (2.18) on both ends.

**Comment by lymankj** [comment]
OK! THANKS for your help I will give that a try!

**Comment by pcav** [comment]
I think this can be closed.
