### ISSUE TITLE
Cascading combo boxes in a form to add or modify data ?

### ISSUE THREAD

**Issue by ribelinu** [3liz/lizmap-web-client#936]
Hi,
is it possible to have cascading combo boxes in the form (Value Relation)  when a user add or modify a data ?
i try in Qgis with python code (just add), but I could not get the code to work in LWC

regards

**Comment by nboisteault** [comment]
@ribelinu did you solve your problem ?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.

**Comment by rldhont** [comment]
Probably duplicate, but it is something, we have to add to lizmap.

**Comment by Gustry** [comment]
Duplicate of https://github.com/3liz/lizmap-web-client/issues/1242
