### ISSUE TITLE
how to configure wps service in the lizmap web client

### ISSUE THREAD

**Issue by gaowudao** [3liz/lizmap-web-client#940]
Dear friend,

I can run lizmap web client, but i don't know how to configure wps configuration in php.ini. Can you give a specific example: including wps_url, wps_rootDirectories, redis_port and ows_url. I am a beginner about how to configure wms, wps service.

Thank you very much.

[wps]
wps_url=http://wps:8080
wps_rootDirectories=/projects/wps
redis_host=localhost
redis_port=6379
redis_key_prefix=lzmwps
ows_url=http://map:8080

**Comment by nboisteault** [comment]
@gaowudao 
Please reopen if issue still occurs or it lacks documentation.
