### ISSUE TITLE
column name in database and alias

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-web-client#941]
Hi 
instead displaying the name of the columns of the table of the database which contain my records, I wuold like to display the aliases, defined in QGIS, in the edition form as well as in the popup

I manage to display theses aliases in the edition form, but when clicking on one of the object on the map, the popup which displays the data linked to it uses the name of the columns instead of the aliases

For example, I added 2 screenshots : look at the author_name field (colmun name in the popup) and Auteur (alias in the edition form).

Is my configuration faulty?

thank you for your help!!

Gérald
![sdca_lizmap_popup](https://user-images.githubusercontent.com/10177830/43833206-4dd18288-9b0a-11e8-9f03-6c3f711b5529.png)
![sdca_lizmap_edition](https://user-images.githubusercontent.com/10177830/43833208-4f6ba9a2-9b0a-11e8-93f7-04bdde48e2f5.png)

QGIS : 2.18.21 (windows 7 pro)
lizmap : 3.1.12 (on centOS 7, apache 2.4)
QGis server : 2.14.9 (installed with "yum install qgis-server" on a centos 7 server)
Browser : chrome & firefox tested
Lizmap data in postgresql 9 database

**Comment by gerald2545** [comment]
sorry, my question is in french as I asked the georezo forum before.
Do you want me to translate in english?

**Comment by rldhont** [comment]
Can you translate and give us some information like:
 - Lizmap version: 
 - QGis version:
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...):
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql?

**Comment by nboisteault** [comment]
Hi Gérald,
I've created the same field "author_name" and the same alias and I can't reproduce your issue using QGIS Server 2.18.23 and Lizmap 3.1.14. Can you update both QGIS Server and Lizmap ?

**Comment by gerald2545** [comment]
Sorry I thought I made a feedback...
it no more appears using lizmap 3.1.12 and qgis server 2.18...don't know whate happened?
a cache not deleted between modifications?
