### ISSUE TITLE
[Lizmap Master] Printing Montpellier Project

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#942]
### What is the bug?
Don't print map of Montepillier Project

### Steps to reproduce the issue
1. Open Montepellier Project
2. Select a print area
3. Fill description map
4. Open New Window to print and give blank page

### Expected behavior
PDF print of template map of Montepillier.

### Logs
2018-08-09 12:52:27	::1	warning	2018-08-09 12:52:27	[2]	file_get_contents(http://localhost/qgis/qgis_mapserv.fcgi.exe): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	E:\webserver\lizmap\master\lizmap-web-client\lizmap\modules\lizmap\classes\lizmapProxy.class.php	136

### Environment Testing

 - Lizmap version: master
 - QGis version: 2.18.22
 - OS (windows, linux, macOS, android..): Windows 7
 - Browser (Firefox, Chrome...): Chrome
 - Lizmap data stored into Postgresql 9.3

**Comment by rldhont** [comment]
Do you have the QGIS Server log ?

**Comment by gioman** [comment]
@jonnyforestGIS @rldhont On WIndows/QGIS 2.18 Server LTR the GetPrint request is broken since... always. On Linux you can workaround the problem by installing and configure a fake xserver. This was NOT necessary on 2.14 (and of course was not a problem on Windows). Not sure if this is still an issue in QGIS Server 3.

**Comment by gioman** [comment]
So it's not a LM issue.

**Comment by jonnyforestGIS** [comment]
Test with:
Composeur1 and Landscape A4. Yes @gioman the error in adding a label and description persists. It's possible that the problem is from QGIS Server. I will try to make more tests.

@rldhont sorry for my delay 
[logs.zip](https://github.com/3liz/lizmap-web-client/files/2401676/logs.zip)

**Comment by gioman** [comment]
> Test with:
> Composeur1 and Landscape A4. Yes @gioman the error in adding a label and description persists. It's possible that the problem is from QGIS Server. I will try to make more tests.

@jonnyforestGIS don't waste your time, mine was not a "maybe", the QGIS Server 2.18 GetPrint is really broken under Windows, and at this point (we approach the next LTR) I guess it will never be fixed.

**Comment by nboisteault** [comment]
Please reopen if it is a LWC bug.

**Comment by gioman** [comment]
> Please reopen if it is a LWC bug.

it is not.
