### ISSUE TITLE
MAPBOX LAYER X,Y,Z DOES'T SHOW

### ISSUE THREAD

**Issue by robibrazze** [3liz/lizmap-web-client#943]
Hi, i insert basemap created whit mapbox studio
(https://api.mapbox.com/styles/v1/robibrazze/cj9smkic4265m2srq3wg9vkx2/tiles/256/{z}/{x}/{y}@2x?access_token=pk.ey myapikey)
in qgis 2.18.14 whit the connection tile server (x,y,z).
In lizmap set the layer as baselayer but the webmap don't show this layer.
(see http://94.130.187.94/webgis/index.php/view/map/?repository=repo5&project=prova_wms)

N.B.: my server is http not https and i tried to insert the tile url whit the http and https but don't change.
In my project the url inserted is whitout s.
In general I find this problem with any layer x,y,z what I try to publish on lwc.

any suggestions?
thanks a lot
Roberto

**Comment by rldhont** [comment]
It's an issue in QGIS Server https://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/server/getting_started.html#cascading-ogc-layers it's the same for WMS or WFS layers.

**Comment by robibrazze** [comment]
Hi, 
whit QGIS Server 2.18 it work only create a tms file whit gdal but whit QGIS Server 3.10 and
LWC 3.3 the problem  is still there whit the layer x,y,z, wmts and wms.
Fot this issue i think that the correct thread is https://github.com/3liz/lizmap-web-client/issues/1574.
Thanks

**Comment by Gustry** [comment]
Yes, I think let's move to #1574
