### ISSUE TITLE
Not well form table name in giving geometry format type

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#948]
### What is the bug?
This issue following #904 force geometry to Z and/or M when saving from lizmap which fixing the issue #902 Support ZM and Z values.

The request to get the exact geometry type fails in the case of schema or table name with upper case.

### Steps to reproduce the issue

1. Define a schema or a table in the Postgres Database with upper case
2. Add the layer with upper case in schema or table name in your QGIS project
3. Set the lizmap configuration with edition capability for the layer
4. Publishing the project
5. Start an edition on the layer with upper case in schema or table name
6. See edition freezing because of an 500 error in the request to get form

### Expected behavior
the request to get the edition form has to return HTML

### Screenshots and logs
```
[403]	Error in the request (ERROR:  the schema « 17axxx_3m » does not exist
LINE 1: ...g_attribute WHERE attname = 'geom' AND attrelid = '17AXXX_3M...
                                                             ^(SELECT format_type(atttypid,atttypmod) AS type FROM pg_attribute WHERE attname = 'geom' AND attrelid = '17AXXX_3M.com'::regclass))
```

### Environment

 - Lizmap version: 3.2RC2
 - QGis version: 2.18.*
 - OS (windows, linux, macOS, android..): linux
 - Browser (Firefox, Chrome...): all

**Comment by Gustry** [comment]
Sorry for that. Is your commit already fixing this issue?

**Comment by rldhont** [comment]
@Gustry yes
