### ISSUE TITLE
Wrong scale when locating using the new functionality "attributeLayers"  

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#95]
Configure your .cfg to use the new "attributeLayers"  functionality, using a mutipart layer.

Then zoom to an extent where just one part of a particular multipart feature is visible, and click on "get data". The list of visible features will show.

Now select the feature that has only one part visible.

Expected result:

* the canvas centers and zooms at a scale to show all the parts of that selected feature.

Actual result:

* the canvas just centers, but there is no change of zoom/scale, so it may very well happen that nothing of what it selected is shown.

**Comment by mdouchin** [comment]
In upcoming 3.0, 2 buttons have been added : one to zoom, one to center
