### ISSUE TITLE
Edition bug

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#950]
Bonjour,

J'utilise Lizmap 3.2 et postgresql 9.6. Lorsque je modifie une table sous lizmap, après avoir appuyé sur "enregistrer", la barre bleue charge indefiniment. Si je souhaite de nouveau modifier un objet, j'ai le message "Êtes-vous certain de vouloir annuler l'édition de cet objet ? Les modifications faites sur l'objet en cours d'édition seront perdues."

Dans le log de Lizmap, ce message apparaît : 
`[8]	Undefined variable: pkVals	/var/www/lizmap-web-client-master/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php	536`
Quelqu'un aurait-il une idée sur le sujet ?
Merci.

**Comment by rldhont** [comment]
Can you update your issue with this template:
```
### What is the bug?
<!-- A clear and concise description of what the bug is -->


### Steps to reproduce the issue

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior
<!-- A clear and concise description of what you expected to happen. -->


### Screenshots and logs
<!-- optional. If applicable, add screenshots and/or logs to help explain your problem 
WARNING: obfuscate all sensible data (IP, passwords, domain name...) -->


### Environment

<!-- please complete the following information -->

 - Lizmap version: 
 - QGis version:
 - OS (windows, linux, macOS, android..): 
 - Browser (Firefox, Chrome...):
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? 
```

**Comment by Cww7** [comment]
### What is the bug?
When I edit a table, after pressing "save", the blue bar loads indefinitely. If I want to change an object again, I have the message "Are you sure you want to cancel the editing of this object?" Changes made to the object being edited will be lost. "
The changes are however saved in the database

### Steps to reproduce the issue
1.  Add the layer in the 'data' tool
2. Add the layer in the 'edition' tool
3. Publishing the project
4. Open data tab
5. Start an edition on the layer : click on the icon 'pen'
6. Save

### Expected behavior
get a change validation message without indefinite loading.


### Screenshots and logs

`[8] Undefined variable: pkVals /var/www/lizmap-web-client-master/lizmap/modules/lizmap/classes/qgisVectorLayer.class.php 536`

![1](https://user-images.githubusercontent.com/19794922/45019600-0e9d3200-b02d-11e8-981c-77bd1ed57a76.PNG)

![2](https://user-images.githubusercontent.com/19794922/45019605-1066f580-b02d-11e8-9fdc-5081f78dc4e9.PNG)


### Environment
 - Lizmap version: 3.2
 - QGis version: 2.18
 - OS : Linux
 - Browser : Firefox
 - Lizmap data stored into Postgresql

**Comment by rldhont** [comment]
@Cww7 this issue has been probably fixed in RC3. Can you update your lizmap version ?

**Comment by nboisteault** [comment]
@Cww7 is your issue fixed with RC3 ?

**Comment by Cww7** [comment]
Hi,
I have updated my lizmap version to RC5 and I do not encounter any problem.
Thx.
