### ISSUE TITLE
Edition - When modifying an existing feature, timestamp data is not filled in the form with edity type date/time

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#957]
### What is the bug?

The edition forms show the field with multiple enties for each date and time elemnts (day, month, hour, etc.). The data for all the input is empty, which means the data can be lost when submitting the form.

### Steps to reproduce the issue

* publish a postgresql layer with a timestamp field with no default value, and add it in edition tool
* choose the edit type "calendar" and set type to date/time (and allow NULL values)
* in lizmap, launch the editing of a existing feature
* the field inputs are empty for this timestamp field

When using a text edit type, the value is well set in the edit form, with the following format `2018-08-03 11:49:45.478321`, but when saving, a jelix client-side error is shown for this field (but the form is submitted)

### Expected behavior

The edition form field is set with its proper value (we can remove seconds and milliseconds ?)

**Comment by nboisteault** [comment]
@mdouchin I've tried to reproduce the issue without success. Do you still have this issue?

**Comment by nboisteault** [comment]
@mdouchin : I spoke too quickly, I can reproduce it. I didn't see that I had to check 'allow NULL values'. I was watching constraints 'not NULL'...

**Comment by rldhont** [comment]
I have fixed **Edition -Should we reactivate the client side jelix checks and not submit the form is not passed** #962 with 3a6ac4cd981c7669f382d291fb82353ce958e625 does it fix this one ?

**Comment by mdouchin** [comment]
I have not managed to reproduce this bug either. I will ask the reporter to provide a QGIS project

**Comment by Gustry** [comment]
I think it's the same issue as mine
When editing an existing feature, we lost the previous date time. So we can't save the form because this field is compulsory.

![date_is_lost](https://user-images.githubusercontent.com/1609292/51750432-76a9ee80-2088-11e9-803b-9207984a1afa.gif)

The table is simple : 
```sql
CREATE TABLE metiers_biodiv.papillon_observation(
    id SERIAL PRIMARY KEY,
    date_heure TIMESTAMP NOT NULL,
    .....
);
```
The field description in QGIS 2.18:
![screenshot from 2019-01-25 10-11-27](https://user-images.githubusercontent.com/1609292/51750844-a4436780-2089-11e9-90ad-23654c615946.png)

**Comment by nboisteault** [comment]
@Gustry : the issue in your case is that you define a timestamp attribute in postgresql but define a 'Date' field format in QGIS => you have to select 'Date time'. I remove bug tag and add need-doc.

**Comment by nboisteault** [comment]
An enhancement would be to allow Date widget to be correctly filled and saved even if the postgresql format is timestamp.

**Comment by laurentj** [comment]
Fixed widget generators from Jelix
