### ISSUE TITLE
Edition - Error when saving an uneditable empty boolean field

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#958]
### What is the bug?

When adding (creation) a new feature in a edition layer with a boolean field (with no default value set in database), Lizmap returns an error like `La saisie de "actif" est invalide`.
This field is not editable, so must not be clickable by the user

1. It seems the user can click it when he shoud not
2. the value of the field is set to 't' but should not be set. There is no default value in the databse. So the value should not be set to 't' nor 'f'
3. When saving again, without clicking or not the checkbox, the feature is saved.
It seems the read-only class is not set evenly the 1st and 2nd time.

Workaround : add a default value for this field in the database. It is cumbersome and not always wanted

**Comment by nboisteault** [comment]
- Also the error message is not returned when value for checked/unchecked are 1/0 in QGIS.

**Comment by mdouchin** [comment]
With @laurentj we decided to remove the disabled fields from the query (INSERT or UPDATE) sent to the PostgreSQL database. We think that if the editor has disabled the field (for example to allow to see it in the form, contrary to the hidden fields which are not visible), it should not be modified. 

For new features (INSERT query), the editor should add a DEFAULT VALUE if the field is set NOT NULL. Otherwise an error would be raised (which is not considered a Lizmap bug in this situation)

**Comment by rldhont** [comment]
@mdouchin can you test https://github.com/3liz/lizmap-web-client/pull/1111 or actual release_3_2 branch ?

**Comment by rldhont** [comment]
@mdouchin has been fixed ?
Can be closed ?

**Comment by nboisteault** [comment]
@rldhont Not sure. I will do some tests later.

**Comment by nboisteault** [comment]
Only 1. has been fixed.

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.

**Comment by nboisteault** [comment]
@mdouchin Please reopen if issue still occurs.
