### ISSUE TITLE
Edition -Should we reactivate the client side jelix checks and not submit the form is not passed

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-web-client#962]
Since version 3.2, the Jelix form displayed when editing a layer feature can be submitting even if client-side javascript checks have not been passed.

Issue : when the form is then submitted, all the values are lost !
We should etiher reactivate the JS checks and not submit the form, or do it be restore the previously filled values (for creation and modification)

**Comment by rldhont** [comment]
@mdouchin can you test it 3a6ac4cd981c7669f382d291fb82353ce958e625
