### ISSUE TITLE
Problem with versions 3.1.13 and 3.1.14

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#963]
I encountered a problem from version 3.1.13 onwards, doing the update from version 3.1.12 does not show me the layers anymore but only shows me the basic maps, to get back everything working I have to go back to version 3.1.12. This happens only on the online one instead on the local one does not give me problems, the problem found and on the https protocol.

as https protocol use: letsencrypt

The problem is found both on version 3.1.13 and 3.1.14.

The Linux version of ubuntu 16.04.
Thank you

**Comment by rldhont** [comment]
When you update lizmap did you do these commands ?
```
sudo lizmap/install/clean_vartmp.sh
php lizmap/install/installer.php
sudo lizmap/install/clean_vartmp.sh
```

**Comment by morvan80** [comment]
Hello,
unfortunately I also tried to format the server in the cloud and rebuild everything from scratch but the problem persists.
I repeat this only makes it from version 3.1.13 onwards with all the previous ones working perfectly.
Suggestions, thank you.

**Comment by morvan80** [comment]
The problem also persists with version 3.1.15.

**Comment by rldhont** [comment]
Do you have an example map ?

Do you use shortName ? Do you use layer name with space, and accent ? Do you have configure PHP or curl in lizmap config for request to the server ? Do you have take a look at the logs : lizmap, qgis server ?

**Comment by rldhont** [comment]
What is your QGIS Server version ?

**Comment by morvan80** [comment]
with version 3.1.12 everything works regularly, when I go to update from 3.1.13.

Ubuntu server 16.04

**Comment by rldhont** [comment]
@morvan80 we can't reproduce your issue, so we can't fix it.

Can you give us an example ?

**Comment by morvan80** [comment]
now I'm not in front of the pc, when can we do the test?

**Comment by morvan80** [comment]
Version 31.12
![lizmap_3 1 12](https://user-images.githubusercontent.com/35898831/46526829-b063a900-c88f-11e8-9df9-6216337d0609.jpg)
Version 3.1.15
![lizmap_3 1 15](https://user-images.githubusercontent.com/35898831/46526832-b48fc680-c88f-11e8-9944-84f06e2a6dc3.jpg)
https://www.sitland.eu/index.php/view/map/?repository=acerno&project=cdu


Thanks, link with 3.1.12.

**Comment by rldhont** [comment]
Can you provide a link for 3.1.15 ?
If not, can you use the dev tools of your browser to check the URL of WMS images and test its ?

**Comment by morvan80** [comment]
Since it is the only provider running I can only load version 3.1.15 when you want to do the tests, I'm waiting for your news. Thank you

**Comment by rldhont** [comment]
Can you give us an acces after upgrade today ?

**Comment by morvan80** [comment]
When you want to do the tests let me know because now I'm back to version 3.1.12, it's the only one that works.

**Comment by morvan80** [comment]
Excuse me what you mean by access, do I need to create an account in lizmap?

**Comment by rldhont** [comment]
I'd like to have an access to your install with version upper than 3.1.12

**Comment by morvan80** [comment]
How can I send a user and password in a private way?

**Comment by rldhont** [comment]
Send me an email: rldhont at 3liz.com

**Comment by morvan80** [comment]
e-mail sent

**Comment by morvan80** [comment]
tell me when can I upgrade to version 3.1.16?

**Comment by rldhont** [comment]
go!

**Comment by morvan80** [comment]
version upgrade 3.1.16

**Comment by rldhont** [comment]
Can you clean the var and temp lizmap directory with the script clean_vartmp.sh ?

**Comment by morvan80** [comment]
could you describe the procedure I have to do?

**Comment by rldhont** [comment]
Can you provide Lizmap logs in mysitland/var/logs ? and QGIS Server logs ?

**Comment by morvan80** [comment]
the folder is empty

**Comment by rldhont** [comment]
The strange thing, is that some request response is:
```
<ServiceExceptionReport version="1.3.0"><ServiceException code="Service configuration error">Service unknown or unsupported</ServiceException></ServiceExceptionReport>
```

**Comment by rldhont** [comment]
Can you launch
```
sudo lizmap/install/set_rights.sh
```

**Comment by morvan80** [comment]
ok launched

**Comment by rldhont** [comment]
Is POST request authorized to your QGIS Server in your Apache2 or NGINX configuration ?

**Comment by morvan80** [comment]
yes since version 3.1.12 works, after having done some previous checks, when I install this library it does not work anymore:
cd letsencrypt
./letsencrypt-auto --help
./letsencrypt-auto --apache
./letsencrypt-auto renew

**Comment by morvan80** [comment]
if you want I send you access to my server?


Da: rldhont
Inviato: lunedì 29 ottobre 2018 11:36
A: 3liz/lizmap-web-client
Cc: morvan80; Mention
Oggetto: Re: [3liz/lizmap-web-client] Problem with versions 3.1.13 and 3.1.14(#963)

Is POST request authorized to your QGIS Server in your Apache2 or NGINX configuration ?

**Comment by morvan80** [comment]
can I go back to version 3.1.12?

**Comment by rldhont** [comment]
yes

**Comment by morvan80** [comment]
As you can see, just back to version 3.1.12 "without any other changes" it starts working perfectly again.

**Comment by morvan80** [comment]
The problem seems to have arisen after solving this:
# 854

**Comment by rldhont** [comment]
@morvan80 it's not the same, Your issue here is that Lizmap or QGIS Server returns 'Service unknown or unsupported' for WMS GetMap, GetPrint...

**Comment by morvan80** [comment]
ok thanks, I'm waiting for your news.

**Comment by rldhont** [comment]
Since 3.1.13, Lizmap communicate with QGIS Server through POST request. So to solve this issue, you have to create a dedicated vhost for your qgis server.

For exemple create a vhost with `qgis.server` serverName and without https and update you hosts file to associated 127.0.0.1 with qgis.server. And finally update your lizmap config to use http://qgis.server/cgi-bin/qgis_mapserv.fcgi

**Comment by morvan80** [comment]
Could you tell me step by step what should I change?
Thank you
