### ISSUE TITLE
Error loading legend of a wms layer

### ISSUE THREAD

**Issue by sylsta** [3liz/lizmap-web-client#964]
### What is the bug?
The legend of wms layer is not correctly shown when loading it in Qgis.

### Steps to reproduce the issue
Load any wms in a project

### Screenshots and logs
![legend_issue](https://user-images.githubusercontent.com/19348327/45306726-a57e5880-b51d-11e8-90ae-c45880eab208.png)

It seems that a '&' is missing in the legend url (see red line on screenshot) between 'project' and 'SERVICE' parameters

### Environment
 - Lizmap version: 3.1.14
 - QGis version: 3.2.2 & 2.18.23
 - OS (windows, linux, macOS, android..): Debian 9 for both client and server
 - Lizmap data stored into Postgresql

All the best, 
S.

**Comment by rldhont** [comment]
Can you take a look at the WMS GetCapabilities xml document ? And check the GetLegendGraphic element content ?

**Comment by sylsta** [comment]
Please find attached the xml document (with txt extension because of github upload rules). 
[qgis_server_wms_capabilities_montpellier_montpellier.xml.txt](https://github.com/3liz/lizmap-web-client/files/2378520/qgis_server_wms_capabilities_montpellier_montpellier.xml.txt)
The GetLegendGraphic item is incorrectly worded.

**Comment by rldhont** [comment]
the '&' is missing at the end of the URLs but QGIShas to identify it and add it.
