### ISSUE TITLE
When editing an object, retrieve user account to fill a field

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#966]
Hi, 

### Is your feature request related to a problem? Please describe
I use "filter by user" functionality and when an user create a new object, I would like that the field used to filter would be automatically filled with the account of the user.

### Describe the solution you'd like
Perhaps an option in the table “Layer Editing” located in the plugin Lizmap “Tools” tab, where we could specify the name of the field?

### Describe alternatives you've considered
Now, users will select their name in a list configured by the admin.

Thanks!
MFANGAIN

**Comment by josemvm** [comment]
hi @mfangain 

see here: https://github.com/3liz/lizmap-web-client/issues/624

**Comment by mfangain** [comment]
Thanks, I didn't find this when I looked at some information about this problem!
I will try the solution, even if I never used a javascript :D
