### ISSUE TITLE
minScale/MaxScale

### ISSUE THREAD

**Issue by andrerjesus** [3liz/lizmap-web-client#967]
### What is the bug?
Scale concept of min and max scales between QGIS and Lizmap are different.

**QGIS**: To show a layer up to 1:40.000 I need to set **minScale: 40.000** and **maxScale: 0** in the Rendering option.
**Lizmap**: To show a layer up to 1:40.000 I need to set **minScale: 0** and **maxScale: 40000** in the .cfg file.

### Steps to reproduce the issue

1. Go to QGIS and add two layers and set:
layer-1 minScale 10.000 and maxScale 0
layer-2 minScale 10.000 and maxScale 0

2. Manually edit the layer cfg file and set:
layer-2 minScale 0 and maxScale 10000

3. Add the layer to Lizmap and check that only layer-2 is correctly displayed

 - Lizmap version: 3.1.14
 - QGis version: 3.2.2
 - OS (windows, linux, macOS, android..): Ubuntu 18
 - Browser (Firefox, Chrome...): Chrome
 - Lizmap data stored into Sqlite (default)? Postgresql

**Comment by andrerjesus** [comment]
I'll move it to the right session. Sorry

**Comment by mbernasocchi** [comment]
for reference the right session above means: https://github.com/3liz/lizmap-plugin/issues/122

**Comment by bgisb** [comment]
I'm a little bit confused. Right now, I have the same issue with Lizmap 3.2.1 and QGIS 3.4.5. Should it still work like this? 

I have to manually edit cfg file:
from
"minScale": 50000,
"maxScale": 0,
to
"minScale": 1,
"maxScale": 50000
