### ISSUE TITLE
Edition in Lizmap doesn't work on a layer with 2 styles

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#968]
### What is the bug?
It isn't possible to modify features for a layer which have several styles defined.
After the click on icon "Add"
![image](https://user-images.githubusercontent.com/32867483/45616602-41edb100-ba70-11e8-8403-d7cad9aa7722.png)
the editing panel never opens.

It's the same thing when I want to modify an existing feature from attribute panel or popup.

### Expected behavior
Click on "add a new feature" or "modify data" (in popup or in attribute table) = open the editing panel

### Screenshots and logs
![image](https://user-images.githubusercontent.com/32867483/45616785-c4767080-ba70-11e8-9246-bbcda83dbd56.png)

![image](https://user-images.githubusercontent.com/32867483/45616143-d820d780-ba6e-11e8-9943-c87b5d1d592b.png)

### Environment

 - Lizmap version: 3.1.14
 - QGis version: 2.18.18
 - OS (windows, linux, macOS, android..): I don't know (host by 3Liz) 
 - Browser (Firefox, Chrome...): Firefox
 - Lizmap data stored into Sqlite (default)? Postgresql? Mysql? Postgresql
 

Thanks

**Comment by mfangain** [comment]
The same problem occurs when a filter's defined on the layer, in Layer Properties, Provider feature filter and another filter by user in Lizmap plug in.

**Comment by nboisteault** [comment]
I can't reproduce the issue neither with QGIS 2.18 nor 3.4.5. Lizmap version is last 3.2 on release_3_2 branch. I have also tested when filtered by user.
Please reopen if issue still occurs.

**Comment by mfangain** [comment]
Hi, 
I can't reproduce the problem either with Lizmap 3.2.2.
Thanks!
MFANGAIN
