### ISSUE TITLE
Locate by layer - filter 

### ISSUE THREAD

**Issue by haduarte** [3liz/lizmap-web-client#969]
Hi,

Is it possible to use "locate by layer" with additional filters?

I have a number of records that according to a particular action (edit) will have a status field with changed value. I would like to display in the "combobox" (locate by layer) only the records that have not yet been updated.
Can I do it through additional javascript? Could an example be possible?
thankful

**Comment by nboisteault** [comment]
@haduarte You can use a view as your layer in the "locate by layer" tool. This view would only display records in the 'not edited' state. I don't think "locate by layer" tool is refreshed after a layer is edited so you would have to do it with additional javascript.
