### ISSUE TITLE
Atlas not working?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#970]
With current   LM  3.3pre.180827 I configure the atlas, but it is not shown.
Sample project attached.
[atlas.zip](https://github.com/3liz/lizmap-web-client/files/2396362/atlas.zip)

**Comment by rldhont** [comment]
@pcav  Can you test this commit 03b0f16ff3560b637377f3dfc68800a2da7261db **Create lizMap.getFeatureData to getFeature without Attribute table config**

**Comment by pcav** [comment]
Confirmed, now it works.
Thanks a lot.
