### ISSUE TITLE
QGIS Server 3: Can't correctly print or use the selection tool

### ISSUE THREAD

**Issue by ulmi** [3liz/lizmap-web-client#971]
Been testing around with qgis-server+lizmap and almost successfully run the demo, bump into 2 issues in 3.1.14 and master

* can't use the selection tool
  in the log it show up this error
  `2018-09-19 17:29:58	10.0.2.2	notice	2018-09-19 17:29:58	[8]	Undefined offset: 0	/var/www/html/mylizmap/lizmap/modules/lizmap/controllers/service.classic.php	1237`

* when printing it only prints the map at full extent with the districts or gives and URL error because it's too long

I'm pretty sure I'm missing something basic. I'm thinking it's in apache or qgis server, but I can't figure it out.

The setup it's in a VM with
* OS: Ubuntu 18.04.1
* QGIS SERVER: Installed: 1:3.2.3+28bionic
* PHP: 7.2
* Lizmap: 3.1.14 or master

thx in advance

**Comment by gioman** [comment]
@ulmi any public URL or maybe one I can see privately?

**Comment by ulmi** [comment]
Hi @gioman nop not yep.

let me see I can convince the IT department for a deploy, or workaround some solution...will you posted! 

Thx

**Comment by josemvm** [comment]
welcome @ulmi :-)

maybe your issue (printing tool) could be related to this other https://github.com/3liz/lizmap-web-client/issues/942

**Comment by ulmi** [comment]
Hi @josemvm 

Nop it's not related, altought the print issue is on the LM side, with some @gioman guidance, found out that, maybe the project montpellier.qgs has a problem on the request to qgis server on the address I change the **map1**0 and **map0** after the extent and it works as intended.

On the selection tool issue still no luck, I keep getting the same notice.

**Comment by ulmi** [comment]
Ok so after talk with @gioman I did fresh install but this time with qgis server 2.18.17 and everything works as intended, printing and the selection tool...so the trouble is with the changes on the qgis server 3.x version 

thx all

**Comment by nboisteault** [comment]
@ulmi 
Please reopen if issue still occurs.
