### ISSUE TITLE
Problem adding new export format (CSV, KML, ecc)

### ISSUE THREAD

**Issue by dmiolo** [3liz/lizmap-web-client#985]
I installed qgis-wfsOutputExtension reading this guide: https://github.com/3liz/qgis-wfsOutputExtension.
and in the GetCapabilities of the WFS service I indeed see the additional formats:
```
...
<GetFeature>
<ResultFormat>
<GML2/>
<GML3/>
<GeoJSON/>
<SHP/>
<XLSX/>
<ODS/>
<KML/>
<MIF/>
<TAB/>
<CSV/>
</ResultFormat>
...
```
I've just clear the `/temp/lizmap` directory with `lizmap/install/clean_vartmp.sh` following this issues: https://github.com/3liz/lizmap-web-client/issues/911 but don't work's.

- Lizmap version: 3.1.14
- Qgis version: 2.14.22
- OS: Ubuntu server 14.04 
- Lizmap data stored into Postgresql 9.3.

I need some help!!
Thanks

**Comment by rldhont** [comment]
Do you have some format (GML, GeoJSON) or none to download vector data ?
Has the user have the right to download vector data ?

**Comment by dmiolo** [comment]
Yes, i can download the standard format (GML and GeoJSON).

**Comment by rldhont** [comment]
Does the WFS GetCapabilities provided by lizmap contain extra format ?

**Comment by dmiolo** [comment]
Yes, the WFS GetCapabilities provided by lizmap contain extra format  but i can't show it in the user interface to export it.

**Comment by rldhont** [comment]
Can you provide a link to view the issue ?

**Comment by dmiolo** [comment]
Sure: http://80.211.160.7/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities&MAP=/var/www/lizmap-web-client-3.1.5/lizmap/install/ENEL_Rilievi/etra/00907571_PADOVA.qgs

**Comment by rldhont** [comment]
Thanks for the QGIS Server link, but I need the lizmap one.

**Comment by dmiolo** [comment]
80.211.1607/lm
login as user: test
password: testlizmap

**Comment by dmiolo** [comment]
How can i check if Apache2 does not activate QGIS Server Plugin?

**Comment by rldhont** [comment]
take a look at this page https://www.itopen.it/qgis-server-python-plugins-tutorial/

**Comment by dmiolo** [comment]
I followed the guide and I can correctly view the Hello Word plugin, but I can not get the wfsOutputExtension extension to work.
Could you help me please?

**Comment by dmiolo** [comment]
I solved by setting the address (URL) of the WMS server by pointing to port 81.
http://127.0.0.1:81/cgi-bin/qgis_mapserv.fcgi

Thanks!
