### ISSUE TITLE
Error when redis server is down

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#986]
### What is the bug?

When lizmap is configured to use Redis as cache, and when the Redis server is down, there is a 500 error. With Lizmap 3.1, there was no error

### Steps to reproduce the issue

1. configure lizmap to use redis
2. stop the redis server
3. open lizmap in the browser
4. See error 500, blank page

### Expected behavior

We should discuss if  we should ignore Redis error or not.

### Environment

 - Lizmap version: 3.2

**Comment by laurentj** [comment]
Possible solutions :

- we ignore the error, but we should have to log it into errors.log
- we keep the 500 error, but we should probably show a message indicating the origin of the issue

**Comment by nboisteault** [comment]
@laurentj is it still an issue?
