### ISSUE TITLE
Filter Data by User/Group do not work 

### ISSUE THREAD

**Issue by NoAtaraxie** [3liz/lizmap-web-client#988]
I followed the tutorial step by step: https://vimeo.com/83966790
But when I connected to the account that should see the data,
I do not see any layers on the map.
I checked, I disabled client / server caching. But nothing changes. i
What could be the raison? 

- Lizmap verison : 3.2
 - QGis version: 2.18
 - OS (windows, linux, macOS, android..): ubuntu 16
 - Browser (Firefox, Chrome...): chrome

**Comment by nboisteault** [comment]
Hi,
Do you have a public link to share ?

**Comment by rldhont** [comment]
Is the field used to filter provided by a joined layer ?
Is the user in a group that override filtre ?

**Comment by NoAtaraxie** [comment]
Hello rldhont, 
1) I created a new column for all my layers.  So they all have their own column. 
2) My user is in the group 'users' and 'viewers_1'(id group i used for filter data)

**Comment by rldhont** [comment]
What is the exactly the lizmap config for Filter Data by User/Group ? 
Do you want to use login or group to filter layer ?

**Comment by Gustry** [comment]
I think I have the same problem with Lizmap 3.2. The map displays all features, even if they must be filtered by users(login).

![Capture d’écran de 2019-03-29 10-43-21](https://user-images.githubusercontent.com/1609292/55240565-87551d00-520f-11e9-8f62-9ae389d4005b.png)

The online edition, it works, I have only a subset of students (`papillon_eleve` in my screenshot) in my combobox. That's OK.
But on the map, all students are displayed, despite their login (teacher `code_prof`).

So with this issue, it means I can't enable feature update on this layer, because students will be able to edit features (by clicking in the unfiltered map) which doesn't belong to their class/teacher.

For 3Liz, the project is hosted on the lizmap.com server, `Papillon` project

**Comment by mfangain** [comment]
Hi,
I use filter by user.

As for me, it's the opposite : display on map is right, but user can see all data in the attribute table.
And so, every user can modify all data.

(Lizmap 3.2.2)

**Comment by nboisteault** [comment]
@NoAtaraxie I can't reproduce your issue with LWC 3.2.3.
@jlstanus I have used text field for the filter column. Could you test and tell us if it changes something ?
@Gustry @mfangain @NoAtaraxie  Could you test with 3.2.3 ?

**Comment by mfangain** [comment]
Hi,
I've got the same problem with Lizmap 3.2.3 installed on your server.
I don't know if I can use a newer version, and how...

**Comment by nboisteault** [comment]
@mfangain which project please ?

**Comment by josemvm** [comment]
hi @nboisteault 

unfortunately, i can confirm this regression too
if you want, i can share a link with you to inspect this problem

**Comment by josemvm** [comment]
i'm trying with qgis server 2.18 and 3.4, so i think this is not a qgis server issue but a lizmap one

**Comment by nboisteault** [comment]
@josemvm Share a link please.

**Comment by josemvm** [comment]
sorry @nboisteault

i did more tests and everything is ok now
i had bad configuration for users/group in 

> Administration, Lizmap configuration, repository, Always see complete layers data, even if filtered by login

thanks

**Comment by mfangain** [comment]
Hi, 

Project Keops, in repository 13 (activite_rl).
The problem still occurs with version 3.2.5.

Thanks.

MFANGAIN

**Comment by nboisteault** [comment]
@mfangain could you provide me by email the credentials of a user who should not see the data and tell me which data he should not see ?

**Comment by Gustry** [comment]
Related tickets in lizmap QGIS plugin:
* https://github.com/3liz/lizmap-plugin/issues/41
* https://github.com/3liz/lizmap-plugin/issues/34

I wonder if I shouldn't close them in QGIS plugin, I CFG is fine.

**Comment by nboisteault** [comment]
@Gustry there are some interesting information to understand the issue, thanks it will help. I think you can close those issues now they are linked here. It is a LWC and/or QGIS Server issue apparently.

**Comment by rldhont** [comment]
A more explicit documentation seems to be needed

**Comment by josemvm** [comment]
not working for layers that belong to a group `Group as layer`

**Comment by rldhont** [comment]
Available with lizmap-plugin as a QGIS Server access control plugin https://github.com/3liz/lizmap-plugin/pull/289

**Comment by rmarzocchi84** [comment]
From my test there is a problem using filter with QGIS virtual field and for layers that belong to a group as noticed by @josemvm

**Comment by rmarzocchi84** [comment]
Here a project affected by problem https://www.gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/view/map/?repository=workshop&project=test_filter


Here the plugin options selected: 
![image](https://user-images.githubusercontent.com/4061154/98008951-57132e80-1df5-11eb-9cd4-91a31f6a7011.png)


Here the attribute table of my layers:
![image](https://user-images.githubusercontent.com/4061154/98009134-80cc5580-1df5-11eb-8e4e-14d30580753b.png)


The layer is a postgis table

**Comment by rmarzocchi84** [comment]
@rldhont there are few problems in the "filter layer by user". It is better to re-open this issue or create a new one with the previous test. 

I made test with LWC 3.3.1 and last QGIS LTR 3.10.11

**Comment by Gustry** [comment]
@rmarzocchi84 This ticket has been opened in 2018 and some messages are not relevant (my message above https://github.com/3liz/lizmap-web-client/issues/988#issuecomment-478045467 is not relevant anymore) so it's difficult to follow in the history.

Maybe create a ticket with a single use case broken ?

**Comment by nboisteault** [comment]
@rmarzocchi84 : please update LWC to 3.3.11 if you are really using LWC 3.3.1. Then open a ticket for each single bug found if any. Thanks

**Comment by rmarzocchi84** [comment]
> @rmarzocchi84 : please update LWC to 3.3.11 if you are really using LWC 3.3.1. Then open a ticket for each single bug found if any. Thanks

Sorry 3.3.11 ;-). I will open a new ticket

**Comment by rmarzocchi84** [comment]
Opened issue https://github.com/3liz/lizmap-web-client/issues/1912
