### ISSUE TITLE
trying to login on lwc - php error

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#991]
hi

[Wed Oct 17 15:44:51.048640 2018] [:error] [pid 1979] [client 10.27.11.245:63505] PHP Fatal error:  Trait 'Lizmap\\Form\\WidgetTrait' not found in /var/www/html/lizmap-web-client-master/lizmap/plugins/formwidget/input_htmlbootstrap/input_htmlbootstrap.formwidget.php on line 14, referer: http://myhostip/

lwc master version

thanks

**Comment by rldhont** [comment]
Can you update to last master version 3.3pre.181017 ? 6cb90102bbb0479fe43946eda526266048c915ce

**Comment by josemvm** [comment]
hi @rldhont 

the problem remains...
and the map is not rendering...
![imagem](https://user-images.githubusercontent.com/10053874/47143593-721daf00-d2bd-11e8-8e2d-c802b454a2f6.png)

**Comment by josemvm** [comment]
the same for the version 3.2 RC6

**Comment by rldhont** [comment]
Which PHP version ?

**Comment by josemvm** [comment]
sorry, you are right. no problems with 3.2.0
php 7.0

**Comment by majorxtrem** [comment]
Same issue on a fresh install of debian 9 php 7.0 and git master version of LWC

**Comment by mdouchin** [comment]
@laurentj same error I told you about

**Comment by laurentj** [comment]
A change in the release_3_2 (which declare the `Lizmap` PHP namespace) was not merge into master. I don't understand why...

I fixed the declaration of the namespace into the master branch.

**Comment by mdouchin** [comment]
Thanks @laurentj !
