### ISSUE TITLE
No Grid in PDF - Print

### ISSUE THREAD

**Issue by FPaulsen** [3liz/lizmap-web-client#993]
System: 
lizmap 3.2rc6 & 3.1.14
QGIS 2.18.24
Ubuntu 16.04 Server

In my QGIS project exist 2 print composers. Both have one grid at MAP 0.

In QGIS the grid is in the pdf file.
In LIZMAP the grid is not in the PDF.

**Comment by FPaulsen** [comment]
Sorry it is an internal Server.

Can i help with more informatios / examplefiles etc ?!

**Comment by nboisteault** [comment]
Could you share a simple QGIS project reproducing the issue ?

**Comment by FPaulsen** [comment]
[qgis_intranet.zip](https://github.com/3liz/lizmap-web-client/files/2519976/qgis_intranet.zip)

**Comment by FPaulsen** [comment]
I have activate an Grid in the demo project. 

The Grid is shown in QGIS but not in the PDF in LizMap
