### ISSUE TITLE
Legend takes up all the screen in smaller devices

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-web-client#994]
When opening on a small screen, eg a mobile phone, the legend is displayed at startup, and no map is shown

**Comment by pcav** [comment]
This does not follow the option selected in the plugin: when choosing to have the legend closed at startup, it is open nevertheless on small screens.

**Comment by nboisteault** [comment]
@pcav Thank you for your report. Fixed with #1294

**Comment by pcav** [comment]
Thanks a lot. Would it be possible to have a `3.3rc3` release?

**Comment by nboisteault** [comment]
@pcav it should come this week.

**Comment by pcav** [comment]
Great news, thanks!
