### ISSUE TITLE
Problem with German umlauts in wms service

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#998]
Hi,

I'm new here, because my English is very bad but I try using Google Translate.
Lizmap I use for over 2 years, a great tool. Thanks a lot for this!

But I have two problems. The first here, the second in another issue:
wms services of lizmap projects misrepresent German umlauts:
https://www.wagner-it.de/download/pic/wms_lizmap.jpg
 
https://wms.webgis.biz/index.php/lizmap/service/?repository=1&project=wms_endingen_brw16_gesamt&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

when wms service directly via qgis server everything is ok:
https://www.wagner-it.de/download/pic/wms_qgis-server.jpg 

In the file .../lizmap/var/config/mainconfig.ini.php "en_US" was changed to "de_DE"

Do I have to make any further changes or is it a bug?

Thanks and Regards
Günter

Lizmap-Client 3.1.16
Ubuntu 18.04.1
QGIS-Server: 2.18.25
QGIS-Client: 2.18.25 / 3.4.0  Win10-64
Data in Postgis 9.6.10 with Encoding UTF-8
Popup in Lizmap-Plugin (2.4.1) activated, source QGIS

**Comment by rldhont** [comment]
There is no issue in Lizmap HTML User Interface. The bad displayed is done by QGIS.

Here is a WMS GetFeatureInfo: https://wms.webgis.biz/index.php/lizmap/service/?repository=1&project=wms_endingen_brw16_gesamt&LAYERS=brw2016_gesamt&QUERY_LAYERS=brw2016_gesamt&STYLES=default&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&BBOX=5331317.813424%2C3393693.264383%2C5336027.406176%2C3410560.485617&FEATURE_COUNT=10&HEIGHT=356&WIDTH=1275&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&CRS=EPSG%3A31467&I=547&J=125&FI_POINT_TOLERANCE=25&FI_LINE_TOLERANCE=10&FI_POLYGON_TOLERANCE=5

In the response header, we have 
```
Content-Type | text/html;charset=UTF-8
```

I'm not sure it's a Lizmap issue. But probably a QGIS one.

**Comment by guenterw** [comment]
thank you for the fast feedback

**Comment by nboisteault** [comment]
@rldhont Can we close as it is a QGIS Server issue ?
