### ISSUE TITLE
Problems with Lizmap 3.1.16 on Android 8.0

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#999]
In Lizmap-Client (3.1.16) on Android 8.0 (Samsung Galaxy Tab S3 and Samsung Galaxy S7), I can not select items (for example Points) in the Chrome and Samsung browsers. It works in the Firefox browser.

With Android 7.0 (Samsung Galaxy Tab A 2016) it works on all Browsers.

Are problems with Android 8 known.

Thanks and Greetings

**Comment by danzig666** [comment]
Same here on Samsung Galaxy S8 (Android 8.0)

**Comment by pcav** [comment]
Still true in Lizmap 3.2.1?

**Comment by danzig666** [comment]
> Still true in Lizmap 3.2.1?

Still the same

**Comment by blaisegeo** [comment]
Lucky I am to have found this thread, because it was impossible to select points on a Samsung Tab with the default driver (Chrome). But now it rocks with Firefox ! :)

**Comment by nboisteault** [comment]
I let #1596 open and close this one.
